### ISSUE TITLE
need to be able to track merged disease entities well

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/mondo#1]
not just synonyms, but actual annotation that points at an expert clingen WG for determining a merge (in addition to tracking synonyms and ids)

**Comment by jmcmurry** [comment]
@mellybelly can you be more precise?

**Comment by nicolevasilevsky** [comment]
We are now adding xrefs to ClinGen working groups (via a URL) and add ORCIDs.

I am going to close this, please reopen if needed
