### ISSUE TITLE
issue with Darier's disease subclass of Acrokeratosis Verruciformis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#10]
There is an issue with Darier's disease as a subclass of Acrokeratosis Verruciformis - I'm not sure if this is a proper subclass assertion, from what I can tell, theses diseases are similar but maybe not properly parent and child.

![image](https://user-images.githubusercontent.com/6722114/32243984-52ac5d5e-be34-11e7-9c2e-ce6ef7196a23.png)

**Comment by cmungall** [comment]
The protocol here is to check the xrefs assigned by sources. We know OMIM doesn't xref to EFO, but EFO xrefs to OMIM. Check EFO in OLS, and look at the xref. If you think it is in error, file a ticket on the EFO tracker. You can also remove the xref in the edit file and reference the ticket here.

In general for cases like this it may not be necessary to make a ticket here in this tracker.

**Comment by nicolevasilevsky** [comment]
EFO xrefs [OMIM:101900 ACROKERATOSIS VERRUCIFORMIS; AKV](https://www.omim.org/entry/101900?search=101900&highlight=101900) on EFO_0004124 Darier's disease.

I tried to delete this xref in MonDO, but I am unable to make any changes in Protege, when I deleted the dbxef to OMIM:101900, and tried to save, I got this error:
![image](https://user-images.githubusercontent.com/6722114/32251888-3719e432-be50-11e7-847b-56403a22c41f.png)

**Comment by nicolevasilevsky** [comment]
According to Sira, [MeSH](https://meshb.nlm.nih.gov/record/ui?ui=D007644) has Acrokeratosis Verruciformis (OMIM:101900) as one of the alternative terms. Seems like these are related diseases or maybe the same, depending on who you talk to.

What course of action should I take here?

**Comment by nicolevasilevsky** [comment]
@cmungall 
Following up on this old issue. Should I remove the xref to OMIM:101900 ACROKERATOSIS VERRUCIFORMIS; AKV?

Also, there is an asserted subclass relationship to 'acrokeratosis verruciformis', should this be deleted too?

Thanks!
