### ISSUE TITLE
Incorrectly formatted x-refs inherited by EFO

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#1002]
Hello!

Nico noticed a few incorrectly formatted x-refs in EFO recently (see https://github.com/EBISPOT/efo/issues/632). Some of these have been inherited from Mondo. I have our terms and the Mondo terms plus the incorrect x-refs below. Some are obvious (e.g. Orphanet727 should be Orphanet:727). I double checked to see how you model PMID x-refs and there seems to be a mix of PMID:x-ref and url:pubmedurl. In EFO we use PMID:x-ref and it would be very useful if the below pubmed referenced could be in that format.

Thanks!

```
http://www.ebi.ac.uk/efo/EFO_1000784,Orphanet727 (inherited from http://purl.obolibrary.org/obo/MONDO_0019124)
http://www.ebi.ac.uk/efo/EFO_0000255,url:https://www.ncbi.nlm.nih.gov/pubmed/22700722 (inherited from http://purl.obolibrary.org/obo/MONDO_0004977)
http://www.orpha.net/ORDO/Orphanet_1885,url:https://www.ncbi.nlm.nih.gov/pubmed/20141359 (inherited from http://purl.obolibrary.org/obo/MONDO_0015998)
http://www.orpha.net/ORDO/Orphanet_90349,url:https://www.ncbi.nlm.nih.gov/pubmed/19401719 (inherited from http://purl.obolibrary.org/obo/MONDO_0019572)
http://www.orpha.net/ORDO/Orphanet_85165,url:https://www.ncbi.nlm.nih.gov/pubmed/10053006 (inherited from http://purl.obolibrary.org/obo/MONDO_0014658)
http://www.orpha.net/ORDO/Orphanet_85165,url:https://ghr.nlm.nih.gov/condition/saddan (inherited from http://purl.obolibrary.org/obo/MONDO_0014658)
http://www.orpha.net/ORDO/Orphanet_3032,url:https://www.ncbi.nlm.nih.gov/pubmed/18371931 (inherited from http://purl.obolibrary.org/obo/MONDO_0009966)
http://www.orpha.net/ORDO/Orphanet_36386,url:https://www.ncbi.nlm.nih.gov/pubmed/18348718 (inherited from http://purl.obolibrary.org/obo/MONDO_0018213)
http://www.orpha.net/ORDO/Orphanet_308386,url:https://www.ncbi.nlm.nih.gov/pubmed/9731530 (inherited from http://purl.obolibrary.org/obo/MONDO_0009643)
http://www.orpha.net/ORDO/Orphanet_308393,url:https://www.ncbi.nlm.nih.gov/pubmed/10053004 (inherited from http://purl.obolibrary.org/obo/MONDO_0009644)
http://www.orpha.net/ORDO/Orphanet_308400,url:https://www.ncbi.nlm.nih.gov/pubmed/11095995 (inherited from http://purl.obolibrary.org/obo/MONDO_0014212)
http://www.orpha.net/ORDO/Orphanet_107,Orphanet107 (inherited from http://purl.obolibrary.org/obo/MONDO_0007029)
http://www.orpha.net/ORDO/Orphanet_642,url:https://www.ncbi.nlm.nih.gov/pubmed/14272277 (inherited from http://purl.obolibrary.org/obo/MONDO_0009746)
http://www.orpha.net/ORDO/Orphanet_642,url:https://www.ncbi.nlm.nih.gov/pubmed/8696348 (inherited from http://purl.obolibrary.org/obo/MONDO_0009746)
http://www.orpha.net/ORDO/Orphanet_2962,url:https://www.ncbi.nlm.nih.gov/pubmed/18388779 (inherited from http://purl.obolibrary.org/obo/MONDO_0017569)
http://purl.obolibrary.org/obo/MONDO_0020460,url:https://www.ncbi.nlm.nih.gov/pubmed/28028990
http://www.orpha.net/ORDO/Orphanet_970,url:https://www.ncbi.nlm.nih.gov/pubmed/21089229 (inherited from http://purl.obolibrary.org/obo/MONDO_0019941)
http://www.orpha.net/ORDO/Orphanet_139564,url:https://www.ncbi.nlm.nih.gov/pubmed/16311270 (inherited from http://purl.obolibrary.org/obo/MONDO_0011961)
http://www.orpha.net/ORDO/Orphanet_139564,url:https://www.ncbi.nlm.nih.gov/pubmed/12870133 (inherited from http://purl.obolibrary.org/obo/MONDO_0011961)
http://www.orpha.net/ORDO/Orphanet_64752,url:https://www.ncbi.nlm.nih.gov/pubmed/77656 (inherited from http://purl.obolibrary.org/obo/MONDO_0012092)
http://www.orpha.net/ORDO/Orphanet_64752,url:https://www.ncbi.nlm.nih.gov/pubmed/14976160 (inherited from http://purl.obolibrary.org/obo/MONDO_0012092)
http://www.orpha.net/ORDO/Orphanet_221145,url:https://www.ncbi.nlm.nih.gov/pubmed/19836010 (inherited from http://purl.obolibrary.org/obo/MONDO_0013170)
http://www.orpha.net/ORDO/Orphanet_140944,ICD10CQ87.3 (inherited from http://purl.obolibrary.org/obo/MONDO_0013038)
```

**Comment by nicolevasilevsky** [comment]
@zoependlington I think some of these are fixed already (I checked the first 5 or so). Chris just put out the latest release - would you mind checking this again against the latest release?

I'm happy to fix any remaining xrefs in Mondo.

Thank you!

**Comment by zoependlington** [comment]
Thanks @nicolevasilevsky! I've checked and, while some were fixed, the following are still present and should be replaced with the x-ref after the -->:
- [ ] MONDO_0004977
     - https://www.ncbi.nlm.nih.gov/pubmed/22700722 --> PMID:22700722
- [ ] MONDO_0015998
     - https://www.ncbi.nlm.nih.gov/pubmed/20141359 --> PMID:20141359
- [ ] MONDO_0019572
     - https://www.ncbi.nlm.nih.gov/pubmed/19401719 --> PMID:19401719
- [ ] MONDO_0014658
     - https://www.ncbi.nlm.nih.gov/pubmed/10053006 --> PMID:10053006
- [ ] MONDO_0014658
     - https://ghr.nlm.nih.gov/condition/saddan --> unsure? We don't have a definite way of referencing these in EFO. May be okay as is?
- [ ] MONDO_0009966
     - https://www.ncbi.nlm.nih.gov/pubmed/18371931 --> PMID:18371931
- [ ] MONDO_0018213
     - https://www.ncbi.nlm.nih.gov/pubmed/18348718 --> PMID:18348718
- [ ] MONDO_0009643
     - https://www.ncbi.nlm.nih.gov/pubmed/9731530 --> PMID:9731530
- [ ] MONDO_0009644
     - https://www.ncbi.nlm.nih.gov/pubmed/1005300 --> PMID:1005300
- [ ] MONDO_0014212
     - https://www.ncbi.nlm.nih.gov/pubmed/11095995 --> PMID:11095995
- [ ] MONDO_0009746
     - https://www.ncbi.nlm.nih.gov/pubmed/14272277 --> PMID:14272277
- [ ] MONDO_0009746
     - https://www.ncbi.nlm.nih.gov/pubmed/8696348 --> PMID:8696348
- [ ] MONDO_0017569
     - https://www.ncbi.nlm.nih.gov/pubmed/18388779 --> PMID:18388779
- [ ] MONDO_0020460
     - https://www.ncbi.nlm.nih.gov/pubmed/28028990 --> PMID:28028990
- [ ] MONDO_0019941
     - https://www.ncbi.nlm.nih.gov/pubmed/21089229 --> PMID:21089229
- [ ] MONDO_0011961
     - https://www.ncbi.nlm.nih.gov/pubmed/16311270 --> PMID:16311270
- [ ] MONDO_0011961
     - https://www.ncbi.nlm.nih.gov/pubmed/12870133 --> PMID:12870133
- [ ] MONDO_0012092
     - https://www.ncbi.nlm.nih.gov/pubmed/77656 --> PMID:77656
     - https://www.ncbi.nlm.nih.gov/pubmed/14976160 --> PMID:14976160
- [ ] MONDO_0013170
     - https://www.ncbi.nlm.nih.gov/pubmed/19836010 --> PMID:19836010
