### ISSUE TITLE
[Revise subclass] MONDO:0006625 altitude sickness

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1013]
**MONDO:0006625 altitude sickness**

I know we've discussed this before, but with the help of our collaborator @smnorthen we've finally resolved on a better home for 'altitude sickness' than the current 'cardiovascular disease' branch. Mondo definition says "Multiple symptoms associated with reduced oxygen at high altitude." Based on the oxygen intake being the problem, (which results in too little oxygen in the blood and following symptoms), @smnorthen suggested to make it a subclass of 'respiratory system disease' and 'injury' (with an axiom disease_has_feature some hypoxia). Would you please consider removing the parent 'cardiovascular disease' please?
Tentatively tagging for your January release as EFO is getting the unwanted parent from Mondo.
Thanks.

(Note for self, stemming from https://github.com/ebispot/efo/issues/486)

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia HP doesn't actually have Hypoxia as a phenotype (but it is in MP). I'll make a NTR to HP.

I partially addressed this ticket on the PR #1039

**Comment by nicolevasilevsky** [comment]
Oh, nevermind, I guess hypoxemia is a synonym for hypoxia:
https://github.com/obophenotype/human-phenotype-ontology/issues/3904

**Comment by nicolevasilevsky** [comment]
I added the axiom too

**Comment by paolaroncaglia** [comment]
Thanks @nicolevasilevsky .
