### ISSUE TITLE
[Revise subclass] dermis disease and  breast fibrocystic disease

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#1016]
**Mondo term (ID and Label)**
dermis disease (MONDO_0021154)

**Suggested revision and reasons**
Should be a child of skin disease (like other epidermal disease etc.).

_____

**Mondo term (ID and Label)**
 breast fibrocystic disease (MONDO:0005219)

**Suggested revision and reasons**
Should be a child of breast disease rather than integumentary disease.

Stemming from EFO ticket: https://github.com/EBISPOT/efo/issues/606

**Comment by nicolevasilevsky** [comment]
Re: breast fibrocystic disease (MONDO:0005219)
integumentary disease was inferred to be a superclass based on the superclass assertion:
'disease has location' some 'mammary gland'

I revised this to 'disease has location' some breast and now 'breast disease' is inferred to be a parent.

Let me know if this is not the correct approach.
