### ISSUE TITLE
[NTR]GATA1-Related X-Linked Cytopenia

### ISSUE THREAD

**Issue by miajsullivan** [monarch-initiative/mondo#1018]
Preferred term label: GATA1-Related X-Linked Cytopenia

Synonyms: GATA1-Related Cytopenia

Definition: X-Linked cytopenia characterized by anemia and/or thrombocytopenia.  Additional features including platelet dysfunction, dyserythropoesis, mild beta-thalassemia, neutropenia, or congenital erythropoetic porphyria may be present.  These GATA1 variants are germline as opposed to GATA1 variants seen in leukemia.

PMID: 20301538
PMID: 28895773 
PMID: 18930124

currently there are several MONDO ID's that are not fully encompassing: 

beta-thalassemia x-linked thrombocytopenia syndrome MONDO ID 0010745
Thrombocytopenia x - linked with or without dyserythropoetic anemia MONDO ID 0010308
x-linked dyserythropoetic anemia with abnormal platelets and neutropenia MONDO ID 0010444
thrombocytopenia with congenital dyserythropoetic anemia MONDO ID 0019031

Parent term: hematologic disease?

Your nano-attribution (ORCID): I am unsure what this is

This suggestion comes from the ClinGen Hemostasis/Thrombosis gene curation expert panel.

**Comment by nicolevasilevsky** [comment]
@miajsullivan is there a URL for the ClinGen Hemostasis/Thrombosis gene curation expert panel?

This is ORCID: https://orcid.org/

**Comment by miajsullivan** [comment]
ORCID: 0000-0001-6964-7302

URL for the ClinGen Hemostasis/Thrombosis gene Curation expert panel: https://clinicalgenome.org/affiliation/40028/

**Comment by nicolevasilevsky** [comment]
note to self - add subclass Of assertion:
'disease has basis in dysfunction of' some GATA1

**Comment by miajsullivan** [comment]
When is the January release?  I assume the MONDO ID is not active until the release, correct?

**Comment by nicolevasilevsky** [comment]
@cmungall will you be doing a Mondo release soon?

**Comment by miajsullivan** [comment]
Sorry to be bothersome, I am waiting for this MONDO ID to be published in order to curate the gene for a ClinGen panel.  Is there any estimate on when the January release will happen?  Thank you in advance.

**Comment by nicolevasilevsky** [comment]
Sorry for the delay @miajsullivan, I believe the next release will be at the end of the month.

**Comment by nicolevasilevsky** [comment]
@miajsullivan 
a question came up about this term - what is the relationship of this term to these four diseases in OMIM:

- Anemia, X-linked, with/without neutropenia and/or platelet abnormalities [OMIM:300835](https://omim.org/entry/300835), MONDO_0010444
- Leukemia, megakaryoblastic, with or without Down syndrome, somatic [OMIM:190685](https://omim.org/entry/190685), MONDO_0008608
- Thrombocytopenia with beta-thalassemia, X-linked [OMIM:314050](https://omim.org/entry/314050), MONDO_0010745
- Thrombocytopenia, X-linked, with or without dyserythropoietic anemia [OMIM:300367](https://omim.org/entry/300367), MONDO_0019031

Do you think this new term is a superclass of these?

**Comment by miajsullivan** [comment]
This new term would be the superclass of the following three diseases:

  *   Anemia, X-linked, with/without neutropenia and/or platelet abnormalities OMIM:300835<https://omim.org/entry/300835>, MONDO_0010444
  *   Thrombocytopenia with beta-thalassemia, X-linked OMIM:314050<https://omim.org/entry/314050>, MONDO_0010745
  *   Thrombocytopenia, X-linked, with or without dyserythropoietic anemia OMIM:300367<https://omim.org/entry/300367>, MONDO_0019031
The last term: Leukemia, megakaryoblastic, with or without Down syndrome, somatic OMIM:190685<https://omim.org/entry/190685>, MONDO_0008608  is not in the same class.  This is somatic GATA1 variants that are found in individuals with Down Syndrome (higher predisposiotion to leukemia) or other individuals with somatic GATA1 variants unrelated to DS.

Thank you,
Mia

**Comment by nicolevasilevsky** [comment]
Thanks for your quick response! I'll implement this change

**Comment by courtneythaxton** [comment]
@nicolevasilevsky Do you have an estimate of the release for this information?

**Comment by nicolevasilevsky** [comment]
This should be available in the February release

**Comment by courtneythaxton** [comment]
@nicolevasilevsky Thanks! will that be at the end of the month, or in the middle? I have noticed you sometimes have fortnight (every two week) releases.

**Comment by nicolevasilevsky** [comment]
@cmungall usually releases at the beginning of each month

**Comment by courtneythaxton** [comment]
@nicolevasilevsky Again, thank you for this information and for your help!

**Comment by nicolevasilevsky** [comment]
I just released it IS february. So this will probably be available in the March release (I was thinking it was still January!)

**Comment by miajsullivan** [comment]
this is not active as a MONDO ID yet.  W?ill this not go live until April's release?


Mia Sullivan

________________________________

**Comment by nicolevasilevsky** [comment]
Hi @miajsullivan this was added to Mondo and the release was done today, you should  now see it in the latest release file.

MONDO:0100089 'GATA1-Related X-Linked Cytopenia'

Sorry for the delay! Let me know if you need anything else.

**Comment by miajsullivan** [comment]
Nicole,


Sorry if you are the wrong person to pursue this with.  I am trying to start a curation for my ClinGen group - upon opening a new Gene-Disease caution in prompts you to add the Gene name and MONDO ID.  You can either look it up or add the MONDO ID (if you know it).  I have tried both ways and it is not accepting the MONDO ID if I put the number in and if I look up by gene-disease, it is not listed.  I've attached a screen shot for you.


Mia
 ?


________________________________

**Comment by courtneythaxton** [comment]
Hi Mia,

I can help with this issue. Likely this is because the ontology lookup system (OLS<https://www.ebi.ac.uk/ols/ontologies/mondo>) hosted by EMBL-EBI has not updated the MonDO ID yet. It can take a few days after a release for them to update the records and changes.

If by the end of this week you do not see the update in OLS, then I would contact them at ols-support@ebi.ac.uk  to indicate the need to update based on the new release.

I have had to do this a couple of times. It happens very infrequently, but is a possibility.

I hope this helps!

Courtney

Courtney Thaxton, Ph.D.
Director of the ClinGen-
Affiliated UNC Biocuration
and Coordination Core
Assistant Professor- Research
Dept. of Genetics
120 Mason Farm Road
5100 B, Genetic Medicine Building
CB#7264
University of North Carolina,
Chapel Hill, NC 27599
919-966-9562

**Comment by miajsullivan** [comment]
​great!  thank you much.


Mia

________________________________
