### ISSUE TITLE
omim_300232, ORPHA:168448, and ORPHA:83629

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1019]
OMIM recently moved https://www.omim.org/entry/300660 into omim_300232.  
How should these concepts now be sorted out?

**Comment by nicolevasilevsky** [comment]
Sounds like we should obsolete **MONDO_0010394 'leukoencephalopathy-metaphyseal chondrodysplasia syndrome'**
and replace it with **MONDO_0010275 'spondyloepimetaphyseal dysplasia, Bieganski type'**

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet and @annieolry 
See above, OMIM merged these two terms. Does Orphanet want to consider retiring
ORPHA:83629 Leukoencephalopathy-spondylometaphyseal dysplasia syndrome
and merged it with
ORPHA:168448 Spondyloepimetaphyseal dysplasia, Bieganski type

**Comment by annieolry** [comment]
I passed on to the team here. We will let you know asap.

**Comment by AntoineMarmignon** [comment]
Hi, I am Antoine from Orphanet, in charge of genetic info and OMIM alignement
If I understand correctly we already do the opposite, obsolete "Spondyloepimetaphyseal dysplasia, Bieganski type" and merge it with "Leukoencephalopathy-spondylometaphyseal dysplasia syndrome"

The Orpha168448 has been deprecated to Orpha83629 
On the website you can see :
"This disease has been moved to Leukoencephalopathy-spondylometaphyseal dysplasia syndrome"
The OMIM phenotype 300232 is linked to Orpha83629 only now.

**Comment by nicolevasilevsky** [comment]
@AntoineMarmignon - We went ahead and followed OMIM: they moved https://www.omim.org/entry/300660 into omim_300232.
