### ISSUE TITLE
Incorrect Mondo associations are partly responsible for a problem at monarch-ui

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/mondo#1021]
**Mondo term (ID Label)**
N/A

**Bug/Typo/Error description**
from @pnrobinson:

While looking at how information is displayed on the Monarch website, Peter found a problem that 
he believes to be partially due to incorrect Mondo associations - and partially due to incorrect ClinVar mapping on our end. I'm describing the issue here, for your awesomeness to please review. :bowtie: 

FLCN - Problems
__1. Disease associations__
Monarch has this https://monarchinitiative.org/gene/HGNC%3A27310#causal-disease

Monarch | OMIM
-- | --
Birt-Hogg-Dube syndrome | Birt-Hogg-Dube syndrome
familial spontaneous pneumothorax | Pneumothorax, primary spontaneous
familial colorectal cancer | Colorectal cancer, somatic
nonpapillary renal cell carcinoma | Renal carcinoma, chromophobe, somatic

__Analysis__
1. Birt-Hogg-Dube syndrome => Matches!

2. familial spontaneous pneumothorax => We chose a name that differs from OMIM, but seems to be just as correct. Nonetheless, we are guilty of xkcd:927. Why is there a need to introduce a new name?

3. familial colorectal cancer => Here, we have made a modelling mistake. There is a big difference between Colorectal cancer, somatic and familial colorectal cancer (the former means that a mutation occurs in colorectal tissue, and the latter implies that a mutation is transmitted in the germline). The problem appears to be that this OMIM entry includes genes that are of both categories (https://omim.org/entry/114500). As far as I can see, FLCN has never been implicated in the familial form, and the OMIM page states: Nahorski et al. (2010) did not find any germline mutations in the FLCN gene among 50 patients with familial nonsyndromic colorectal cancer. 

4. nonpapillary renal cell carcinoma. I believe that Renal carcinoma, chromophobe, somatic is a particular subtype of nonpapillary renal cell carcinoma, but these are not synonymous. See https://www.ncbi.nlm.nih.gov/medgen/463622

__Mutation__

ClinVarVariant:253251 NM_144997.5(FLCN):c.1429C>T (p.Arg477Ter) is noted to be related to Potocki-Lupski syndrome (PTLS) in Kent’s analysis.

Nonetheless, if I search for this mutation on the old website I get:
NM_144997.5(FLCN):c.1429C>T (p.Arg477Ter) has 11935 matches

If I search on the new website, I get
NM_144997.5(FLCN):c.1429C>T (p.Arg477Ter) has 297106 matches

The top hit of the search is our mutation. It is listed as being associated with all four of the Monarch diseases listed above and additionally with PTLS.

However, I cannot find the PTLS association in ClinVar
https://www.ncbi.nlm.nih.gov/clinvar/variation/253251/
(we later found it at https://www.ncbi.nlm.nih.gov/clinvar/RCV000762980.1/)

I am going to guess that the reason we are picking up this association is that FLCN is one of roughly 17 genes located in the CNV that causes PTLS: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2833368/

Nonetheless, this is incorrect as “the dosage-sensitive gene RAI1 is likely to be responsible for the predominant clinical features of the PTLS phenotype associated with 17p11.2 duplications.“

(Note: Apologies in advance if I'm filing under the wrong issue category.)

**Comment by nicolevasilevsky** [comment]
@monicacecilia if you can outline the specific action items needed here, I can implement these changes. (Or perhaps more discussion is needed)?

**Comment by kshefchek** [comment]
For point 2, I'll add that I saw this in our PCORI funded project as well, where there was confusion over the labelling of:

MONDO:0017178	osteochondritis dissecans (disease)
MONDO:0009798	intellectual disability-cataracts-calcified pinnae-myopathy syndrome
MONDO:0007841	coxopodopatellar syndrome

For Osteochondritis dissecans, it was confusing from the label alone that this is the same thing as https://omim.org/entry/165800, and I think the other two have similar issues in that people expect the OMIM primary label for a disease.

For 3, I think Peter's point is that https://omim.org/entry/114500 is much broader than familial colon cancer, so either the label is incorrect or the OMIM id should be at a more general grouping of colon cancer

4 I find confusing because OMIM doesn't have a specific entry for "Renal carcinoma, chromophobe, somatic" -- it all seems to be grouped under https://omim.org/entry/144700.  So since FLCN is associated with this OMIM:144700, we get the incorrect labelling, see https://beta.monarchinitiative.org/gene/HGNC:27310#causal-disease

This is not a Mondo issue but rather an OMIM ingest issue that I'm not certain how to fix without OMIM referencing an identifier for renal carcinoma, chromophobe, somatic 

I think everything under mutation is extraneous

**Comment by nicolevasilevsky** [comment]
@kshefchek 
> For Osteochondritis dissecans, it was confusing from the label alone that this is the same thing as https://omim.org/entry/165800, and I think the other two have similar issues in that people expect the OMIM primary label for a disease.

Should we relabel MONDO:0017178 to 'short stature and advanced bone age, with or without early-onset osteoarthritis and/Or osteochondritis Dissecans'?

**Comment by nicolevasilevsky** [comment]
>For 3, I think Peter's point is that https://omim.org/entry/114500 is much broader than familial colon cancer, so either the label is incorrect or the OMIM id should be at a more general grouping of colon cancer

Currently, [OMIM:114500 COLORECTAL CANCER; CRC](https://omim.org/entry/114500) is an xref for MONDO_0005575 'colorectal cancer', annotated as a MONDO:subClassOf. Sounds like we should change this to MONDO:equivalentTo and remove the xref to OMIM:114500 from MONDO_0023113 'familial colorectal cancer'

**Comment by maglott** [comment]
Independent of the explicit names. should all oncepts from OMIM be considered genetic?  @ahamosh, how do you think https://omim.org/entry/114500 should be treated?  As genetic or as more general, given that the text also lists the somatic mutations.

**Comment by nicolevasilevsky** [comment]
@monicacecilia and @kshefchek is this still needed?

**Comment by kshefchek** [comment]
We still have the associations displayed on our app, but seems https://github.com/monarch-initiative/mondo/issues/1021#issuecomment-563275214 is the only thing that’s actionable?  I'm not really qualified to make a judgement here.

**Comment by ahamosh** [comment]
I am so sorry.  It looks like I totally dropped this ball. 114500 is one of a few big, broad, hairy in OMIM.  It is colorectal cancer and really talks about somatic contributions to colorectal cancer.  It is "genetic" but NOT Mendelian.  Each of the single gene caused (not included in this list) is broken out into the individual phenotype entries.

**Comment by nicolevasilevsky** [comment]
No worries, thanks for your input @ahamosh!

Just to clarify, we should proceed with this action item:

I will proceed with the action item outlined above (Currently, OMIM:114500 COLORECTAL CANCER; CRC is an xref for MONDO_0005575 'colorectal cancer', annotated as a MONDO:subClassOf. Sounds like we should change this to MONDO:equivalentTo and remove the xref to OMIM:114500 from MONDO_0023113 'familial colorectal cancer'). Please let me know if that is incorrect.

Thank you!

**Comment by ahamosh** [comment]
Hi Nicole, I think that is the correct plan.  Thanks!
