### ISSUE TITLE
[Revise subclass] MONDO:0016644, "Logopenic progressive aphasia" = cancer?!

### ISSUE THREAD

**Issue by turbomam** [monarch-initiative/mondo#1028]
**Mondo term (ID and Label)**
http://purl.obolibrary.org/obo/MONDO_0016644, "Logopenic progressive aphasia"

**Suggested revision and reasons**
Asserted parent class, http://purl.obolibrary.org/obo/MONDO_0005061 "lung adenocarcinoma" seems dubious. Is this some kind of perineoplastic thing?

**Comment by cmungall** [comment]
not good... @nicolevasilevsky can you fix, looks like the ncit xref is incorrect
