### ISSUE TITLE
[Revise subclass] MONDO:0006761 fibromuscular dysplasia

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1029]
**MONDO:0006761 fibromuscular dysplasia**

Currently a child of 'cardiovascular disease, but its def clearly refers, more specifically, to arteries: "A disorder characterized by fibrous thickening of the arterial wall resulting in narrowing of the arterial lumen. It most often affects the renal artery and less often the carotid artery and abdominal arteries.". Could you please consider making it a child of 'arterial disorder' instead. Asking for this because our users at Open Targets need specific therapeutic areas for 'heart disease' and 'vascular disease' rather than a broader 'cardiovascular' one.

Also, you may wish to check if 
MONDO:0007613 fibromuscular dysplasia of arteries
is indeed the same as
MONDO:0006761 fibromuscular dysplasia
(I haven't had time to check the dbxrefs, but based on the label, it sounds like it can't be anything else).

Thanks!

**Comment by nicolevasilevsky** [comment]
Yes, I think MONDO:0007613 fibromuscular dysplasia of arteries and MONDO:0006761 fibromuscular dysplasia are the same and should be merged.
