### ISSUE TITLE
[Revise subclass] MONDO:0005468 hypotension (disease)

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1030]
**MONDO:0005468 hypotension (disease)**

("Blood pressure that is abnormally low.") is currently a subclass of 'cardiovascular disease'. However, its "mate" MONDO:0005044 'hypertensive disorder' is, rightfully, a subclass of 'arterial disorder'. Would you please consider making MONDO:0005468 'hypotension (disease)' a subclass of 'arterial disorder' too? EFO would benefit from this (trying to clean up children of 'cardiovascular disease' that can have more specific parents, for our Open Targets work). Thanks.

**Comment by cmungall** [comment]
also make the naming consistent
