### ISSUE TITLE
Add license to OWL header

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#1031]
http://obo-dashboard-test.ontodev.com/ - the ontology is failing the 'open' check

the release owl should contain:

```
     xmlns:terms="http://purl.org/dc/terms/"
...
        <terms:license rdf:resource="https://creativecommons.org/publicdomain/zero/1.0/"/>
```

See https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1041

**Comment by nicolevasilevsky** [comment]
Hi @cmungall -
Do you want the license for Mondo to be: https://creativecommons.org/publicdomain/zero/1.0/
?

Currently it is http://creativecommons.org/licenses/by/4.0/ in protege and noted as 
CC BY 3.0 on the [OBO Foundry page](http://obofoundry.org/ontology/mondo.html).

Should I change both of those to https://creativecommons.org/publicdomain/zero/1.0/

![image](https://user-images.githubusercontent.com/6722114/70756826-79d6b900-1cf2-11ea-96f7-ed8aa9b126d9.png)

Thanks!

**Comment by cmungall** [comment]
no stick with cc by for now, only the logic subset gets cc-0

**Comment by nicolevasilevsky** [comment]
Do we want CC-BY 3 as per obofoundry metadata (https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/mondo.md) or CC-BY 4 as per ontology metadata?

Also, the fact that the logical subsets are cc-0, how should this be reflected in the ontology metadata?

**Comment by nicolevasilevsky** [comment]
closing, please reopen if needed
