### ISSUE TITLE
Are xrefs supposed to bidirectional? MONDO:0002144 "hyperuricemia" -> ICD9 790.6 "Other abnormal blood chemistry"

### ISSUE THREAD

**Issue by turbomam** [monarch-initiative/mondo#1033]
**Mondo term (ID and Label):**
MONDO:0002144 "hyperuricemia"

**Xref that should be fixed (ID and label):**
ICD9 790.6 "Other abnormal blood chemistry"

**Other comments:**

Is MonDO saying 

> If your patient has asymptomatic  hyperuricemia, you could encode it as 790.6?

I think that's fine. 

But if it's saying

> if you see a patient with 790.6 in their EHR, then they have asymptotic hyperuricemia

That would be wrong most of the time, right?

**Comment by cmungall** [comment]
xref is inherently ambiguous - for some sources we ensure these are 1:1
(unless we do a proxy) merge, but not for ICD9

I recommend using the skos mappings or the owl equivalencies file for
precise unambiguous mappings

**Comment by turbomam** [comment]
Thanks, @cmungall . That's helpful clarification.

**Comment by turbomam** [comment]
@cmungall I though of two followup questions

1. how do you decide which predicate to assert? Is there a paper I can read, or some web documentation?
2. there are `?mondo ?p ?external` assertions as well as `?external ?p ?mondo` assertions. What's the significance of the orientation of those statements?

**Comment by cmungall** [comment]
1. @nicolevasilevsky can you provide a link to the section in the manual?
2. I think this only happens with owl:equivalentClass triples. This is a symmetric property. The owlapi writes these in an arbitrary (but deterministic) order.

**Comment by nicolevasilevsky** [comment]
https://mondo.readthedocs.io/en/latest/editors-guide/f-entities/#axiom-annotations-on-xrefs

**Comment by cmungall** [comment]
Do we have anything in the users manual? What the editor sees and does will
be different
