### ISSUE TITLE
should MITOCHONDRIAL COMPLEX I DEFICIENCY have subclasses?

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1042]
UMLS (likely from OMIM)  and OMIM have established multiple terms for nuclear and mitochondrial subtypes
https://www.omim.org/phenotypicSeries/PS252010
MITOCHONDRIAL COMPLEX I DEFICIENCY, MITOCHONDRIAL TYPE 1; MC1DM1

**Comment by nicolevasilevsky** [comment]
@cmungall looks like some new terms were added to OMIM. Should I manually add these to Mondo, or is there a way for you to programmatically import them?

**Comment by cmungall** [comment]
I don't see a PS for the mitochondrial subtype yet?

**Comment by nicolevasilevsky** [comment]
me neither.

I see some specific terms, but not a PS.

https://www.omim.org/entry/516000
https://www.omim.org/entry/500014

**Comment by nicolevasilevsky** [comment]
- [ ] rename 'mitochondrial complex I deficiency' to 'mitochondrial complex I deficiency, nuclear type' (double check OMIM name)
- [ ] add parent 'mitochondrial complex I deficiency'
- [ ] add subclass 'mitochondrial complex I deficiency, mito type'
- [ ] move 'mitochondrial complex 1 deficiency, mitochondrial type 1' to be a child of 'mitochondrial complex I deficiency, mito type'

**Comment by nicolevasilevsky** [comment]
-[ ] look at all the dbxrefs and make sure they are attached to the correct terms

**Comment by maglott** [comment]
I don't see _mitochondrial complex I deficiency, nuclear type_ or _mitochondrial complex I deficiency, nuclear type 1_
Will they be in the next release?

**Comment by nicolevasilevsky** [comment]
Yes! Hopefully we'll have a new release next week.
