### ISSUE TITLE
Is 'KAT6A Syndrome' a synonym for 'autosomal dominant intellectual disability-craniofacial anomalies-cardiac defects syndrome' (MONDO:0014558)

### ISSUE THREAD

**Issue by GullyBurns** [monarch-initiative/mondo#1052]
**Mondo term (ID and Label)**
'autosomal dominant intellectual disability-craniofacial anomalies-cardiac defects syndrome' (MONDO:0014558)

**Synonym to be added**
KAT6A Syndrome

**Synonym subtype: ie, broad/exact/narrow/related**
exact (?)

Seems to be good correspondence between phenotypes and exact match with underlying genes.

References:
* https://rarediseases.org/rare-diseases/kat6a-syndrome/
* http://www.kat6a.org/
* https://www.ncbi.nlm.nih.gov/pubmed/30245513

**Comment by nicolevasilevsky** [comment]
Hi @GullyBurns I am not sure if these are the same. @ahamosh, @annieolry, @ana-rath-orphanet - do you have any thoughts?

**Comment by GullyBurns** [comment]
The reason for the submission is largely based on etiology (mutations of the KAT6A gene). 

Also, the OMIM entry for 'MRD32' (https://www.omim.org/entry/616268) cites the same underlying primary research articles as the NORD entry for 'KAT6A Syndrome' (https://rarediseases.org/rare-diseases/kat6a-syndrome/). In particular, Arboleda et al. 2015 ( https://www.ncbi.nlm.nih.gov/pubmed/25728775) and Tham et al. 2015 (https://www.ncbi.nlm.nih.gov/pubmed/25728777).  

Would love to learn more about how these decisions are made in this context.

**Comment by nicolevasilevsky** [comment]
Sounds good! 

We don't have a formal process for making these kind of decisions, but usually try to get any advice from medical experts in this case. Being that I am not a medical expert, I though we could see if anyone else had any thoughts, but it sounds like KAT6A Syndrome  is a proper synonym, so I'll go ahead and add it and create a PR. (Others will still have time to weigh in while we wait for review of the pull request.)
