### ISSUE TITLE
Is 'TANGO2 deficiency' actually 'metabolic encephalomyopathic crises, recurrent, with rhabdomyolysis, cardiac arrhythmias, and neurodegeneration' (MONDO:0014812)

### ISSUE THREAD

**Issue by GullyBurns** [monarch-initiative/mondo#1054]
**Mondo term (ID and Label)**
metabolic encephalomyopathic crises, recurrent, with rhabdomyolysis, cardiac arrhythmias, and neurodegeneration (MONDO:0014812)

**Synonym to be added**
1. Transport And Golgi Organization protein 2 (TANGO2) deficiency 
2. TANGO2 deficiency
(https://www.ncbi.nlm.nih.gov/pubmed/31339582)

Is this also the same as this? 
3. tango2-related-metabolic-encephalopathy-and-arrhythmias
(https://rarediseases.info.nih.gov/diseases/13423/tango2-related-metabolic-encephalopathy-and-arrhythmias)

Also see for patient-centered phenotypes: https://tango2research.org/signs-symptoms/

**Synonym subtype: ie, broad/exact/narrow/related**
exact

**Comment by nicolevasilevsky** [comment]
@GARDinfocenter, @ahamosh, @cmungall: do any of you have an opinion if MONDO:0014812 'metabolic encephalomyopathic crises, recurrent, with rhabdomyolysis, cardiac arrhythmias, and neurodegeneration' is the same as the GARD term: tango2-related-metabolic-encephalopathy-and-arrhythmias
(https://rarediseases.info.nih.gov/diseases/13423/tango2-related-metabolic-encephalopathy-and-arrhythmias)

These seem like they could be equivalent to me. In which case, we should add an xref to GARD.

**Comment by ahamosh** [comment]
These are the same.  I can't tell you how much I wish that people would stop putting gene symbols in disease names....

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh!

**Comment by mellybelly** [comment]
@ahamosh me too!

**Comment by GullyBurns** [comment]
Thank you for your prompt action on this.

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky GARD has listed the two terms as synonyms since 3/5/2018. The change was prompted by research conducted by GARD due to an inquiry from a patient organization.
