### ISSUE TITLE
MONDO:0012231

### ISSUE THREAD

**Issue by Antonialock** [monarch-initiative/mondo#1058]
**Mondo term (ID Label)**
MONDO:0012231 Charcot-Marie-Tooth disease type 2A2

**Bug/Typo/Error description**
currently
Heritability:  Autosomal dominant inheritance, Autosomal recessive inheritance

but from the xrefs and synonyms this looks like AD only. not AR

**Comment by nicolevasilevsky** [comment]
Hi @Antonialock, where do you see the description of the heritability in the Mondo ontology? I don't see this disease described as AR in the ontology.
Thanks!

**Comment by Antonialock** [comment]
Thanks Nicole. Please see the highlight in the screenshot below. I'm not sure what the 'heritability' is inferred from

<img width="1148" alt="Screenshot 2020-01-06 at 10 55 18" src="https://user-images.githubusercontent.com/12727506/71814021-22b6d080-3073-11ea-8524-03e356e2fc78.png">

**Comment by nicolevasilevsky** [comment]
Thanks @Antonialock. This isn't coming from Mondo, I'll figure out which tracker to add this to.

**Comment by nicolevasilevsky** [comment]
I reported this on the HPO annotation tracker, I am going to close this here.
