### ISSUE TITLE
Cowden vs PTEN hamartoma tumor syndrome

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1060]
**Mondo term (ID and Label)**
MONDO_0016063/Cowden has an exact synonym of `PTEN hamartoma syndrome` yet it is_a PTEN hamartoma tumor syndrome, MONDO_0017623

**Suggested revision and reasons**
* I do not know clinical usage, but this representation is confusing.   Are these distinct entities or not?
The definition of MONDO_0017623 states Cowden is a subset.   Perhaps just remove `PTEN hamartoma syndrome` as an exact synonym of Cowden and treat `PTEN hamartoma syndrome` as search term/keyword for Cowden.

Also , are there check for prevent the same term from being both an exact synonym and related synonym?  MONDO_0016063 has `multiple hamartoma syndrome` as both exact and related synonyms

**Comment by nicolevasilevsky** [comment]
@maglott I don't believe we currently have a check to prevent a term having the same synonyms as exact and related. @cmungall could we add a check for this?

I addressed this in this term - I made the related synonym (multiple harmatoma syndrome) an exact synonym (moved the dbxref for DOID:6457 to the exact synonym annotation)

**Comment by cmungall** [comment]
2 distinct classes should never match based on exact or the label. robot report counts this as ERROR by default (note there is a separate ticket where you are working through all of these).

> Also , are there check for prevent the same term from being both an exact synonym and related synonym? MONDO_0016063 has multiple hamartoma syndrome as both exact and related synonyms

Although having the exact synonym is redundant, it's useful as we can annotate the synonym with metadata. While technically we *can* do this for label, most consuming software doesn't expect this, so we make a semi-redundant exact syn instead. It's not ideal..

But we should never have a single term have a related syn that matches either exact or label, I think this needs to be a new check. Do you want to suggest this on the robot tracker Nicole?
Formally this is allowed,

**Comment by nicolevasilevsky** [comment]
> Do you want to suggest this on the robot tracker Nicole?

done
