### ISSUE TITLE
febrile seizures 8 vs ECA2/epilepsy, childhood absence, susceptibility to, 2/MONDO_001189

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1062]
OMIM deprecated https://www.omim.org/entry/611277 and used the name it had had, namely FEBRILE SEIZURES, FAMILIAL, 8, to rename https://www.omim.org/entry/607681, which had been name EPILEPSY, CHILDHOOD ABSENCE, SUSCEPTIBILITY TO, 2, INCLUDED; ECA2.

EPILEPSY, CHILDHOOD ABSENCE, SUSCEPTIBILITY TO, 2, INCLUDED; ECA2 is not reported as an alternate name for 697681; it is reported as included, which we have usually interpreted to indicate a distinct disorder.

Are these equivalent concepts, or should NCBI keep them distinct and clean up submissions to retain the distinction?
Note also:
Febrile seizures, familial, 8 is reported as a child of https://www.omim.org/phenotypicSeries/PS600131
UMLS still has distinct concepts:
[C1969810]  FEBRILE CONVULSIONS, FAMILIAL, 8
[C1843244]  EPILEPSY, CHILDHOOD ABSENCE, SUSCEPTIBILITY TO, 2

**Comment by nicolevasilevsky** [comment]
Summarizing below, for my own benefit:

MONDO_0012647 `'generalized epilepsy with febrile seizures plus, type 3'` was deprecated in OMIM and it was merged with MONDO_0011891 `'epilepsy, childhood absence, susceptibility to, 2'`.

MONDO_0011891 `'epilepsy, childhood absence, susceptibility to, 2'` was renamed to FEBRILE SEIZURES, FAMILIAL, 8; FEB8 in OMIM.

@cmungall should we follow OMIM? If yes, then I think the action item here is for Mondo to:

- [ ] obsolete MONDO_0012647 `'generalized epilepsy with febrile seizures plus, type 3'`
- [ ] MONDO_0012647 should be replaced by MONDO_0011891
- [ ] MONDO_0011891 should be renamed to febrile seizures, familial, 8 (see OMIM for synonyms: https://www.omim.org/entry/607681)
- [ ] MONDO_0011891 should be a child of MONDO_0010826 'childhood absence epilepsy'

cc @maglott

**Comment by cmungall** [comment]
I agree with your plan, thanks!
