### ISSUE TITLE
[Revise subclass] MONDO_0012455 /Kleefstra syndrome

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1063]
**Mondo term (ID and Label)**
MONDO_0012455 /Kleefstra syndrome

**Suggested revision and reasons**
This currently has 4 children.  OMIM distinguishes 2 types, 
* Kleefstra syndrome 1, because of the loss of function of EHMT1 whether by deletion or point mutation, and 
Kleefstra syndrome 2, because of loss of function of KMT2C. whether by deletion or point mutation

Thus, if it necessary to retain  terms distiguishing between point mutations and larger deletions, 
MONDO_0019896 should be a child of MONDO_0019896, not a sibling.

BTW, kleefstra syndrome 2 should be Kleefstra syndrome 2

I

**Comment by nicolevasilevsky** [comment]
@maglott 
Is this correct?

![image](https://user-images.githubusercontent.com/6722114/71701807-b9884200-2d80-11ea-9e24-a491f72f1510.png)

**Comment by maglott** [comment]
Looks better.  Still not certain what to do about Kleefstra syndrome due to point mutation.  Point mutations contribute to Kleefstra syndrome 1, too. It is critical medically to name a disorder based on the type of variant.  Is there any objection to making that term obsolete?

**Comment by nicolevasilevsky** [comment]
I have no objections. Our new policy is to send an email to the user community regarding any candidates for obsoletion, so I will do them and give folks a couple weeks to respond, then I will obsolete it if there are no objections.

**Comment by nicolevasilevsky** [comment]
cc @annieolry and @ana-rath-orphanet

**Comment by ErinRiggs** [comment]
Hello - if it helps, both the ClinGen ID/Autism Gene Curation Expert Panel and the Dosage Sensitivity curation team have evaluated EHMT1 for Kleefstra syndrome.  ID/Autism used the parent term "Kleefstra syndrome" (and specifically did not choose the terms that indicated variant type).  While Dosage Sensitivity currently uses OMIM terms, I can say with certainty that when we switch to MONDO, we will use the same term.  Both groups preferentially stay away from terms that specify a variant type (e.g. "point mutation"), particularly when the phenotype is the same regardless of variant type.  If the phenotype were drastically different between a larger microdeletion/duplication and a point mutation in a single gene, we would consider using different terms, but this occurs infrequently.  We would support the obsoletion of the variant type terms in this case.
