### ISSUE TITLE
MUSCULAR DYSTROPHY, LIMB-GIRDLE, TYPE 1B and Emery-Dreifuss muscular dystrophy 2, autosomal dominant

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1086]
MONDO_0021569 and MONDO_0008033 

OMIM moved MUSCULAR DYSTROPHY, LIMB-GIRDLE, TYPE 1B into Emery-Dreifuss muscular dystrophy 2, autosomal dominant as a former name; both seem to be defined in MONDO as being autosomal dominant, resulting from LMNA mutation.

It there any distinction to be retained?

**Comment by maglott** [comment]
From OMIM's text:
Some cases of Emery-Dreifuss muscular dystrophy-2 were previously classified as a form of limb-girdle muscular dystrophy (type 1B; LGMD1B). LGMD1B was characterized as an autosomal dominant, slowly progressive limb-girdle muscular dystrophy with age-related atrioventricular cardiac conduction disturbances and the absence of early contractures. Straub et al. (2018), on behalf of the LGMD workshop study group, reclassified LGMD1B as EDMD2

**Comment by nicolevasilevsky** [comment]
We should obsolete MONDO_0008033 'autosomal dominant limb-girdle muscular dystrophy type 1B' and replace with MONDO_0021569 'Emery-Dreifuss muscular dystrophy 2, autosomal dominant'

**Comment by nicolevasilevsky** [comment]
FYI @gardinfocenter, @ana-rath-orphanet, @annieolry
