### ISSUE TITLE
MONDO:0007920 has a wrong xref

### ISSUE THREAD

**Issue by dancingline** [monarch-initiative/mondo#1087]
**Mondo term (ID and Label):**
MONDO:0007920  Meige disease

**Xref that should be fixed (ID and label):**
MESH:D008538  Meige Syndrome

**Other comments:**
Meige disease is not a same disease as meige syndrome, which can be see in https://www.ncbi.nlm.nih.gov/mesh/?term=C562467.

**Comment by nicolevasilevsky** [comment]
Thanks for catching that, @dancingline. It seems that Meige syndrome did exist in Mondo but was (incorrectly) merged with Meige disease. I'll un-obsolete Meige syndrome.
