### ISSUE TITLE
COL4A1 or COL4A2-related cerebral small vessel disease

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1089]
**Mondo term (ID and Label)**
COL4A1 or COL4A2-related cerebral small vessel disease, MONDO_0018788

**Suggested revision and reasons**
OMIM_175780  (currently the XRef for porencephaly 1) has been renamed to brain small vessel disease-1 with or without ocular anomalies (BSVD1)

1. do we need a node named by the genes that contribute to cerebral small vessel disease?  OMIM now lists 3: https://www.omim.org/phenotypicSeries/PS175780, so the listing of 2 may be out of date
2. Not sure in clinical practice whether or not porencephaly 1 equates to COL4A1-related familial vascular leukoencephalopathy (MONDO_0011865) 

i don't know if something like this is valid or not (are differnent nodes defined by genetic basis or characteristics?)
genetic cerebral small vessel disease
--genetic cerebral small vessel disease with hemorrhagic tendancy
----more nodes
--genetic cerebral small vessel disease with ischemic  tendancy
----more nodes

**Comment by nicolevasilevsky** [comment]
action items:
- [ ] rename MONDO_0008289 'porencephaly 1' to brain small vessel disease 1 with or without ocular anomalies
- [ ]  add synonyms to MONDO_0008289 'porencephaly 1' : 
- BSVD1
- hemiplegia, infantile, with porencephaly
- brain small vessel disease with hemorrhage
- retinal arteriolar tortuosity, infantile hemiparesis, and leukoencephalopathy, autosomal dominant
- brain small vessel disease with axenfeld-rieger anomaly
- T1P
- leukoencephalopathy with axenfeld-rieger anomaly
- ADT1P
(xref OMIM:175780)
- [ ] Add new term: 
brain small vessel disease 3
parent: MONDO_0020496 'familial porencephaly'
syn: BSVD3
xref (equiv): OMIM:618360

>Not sure in clinical practice whether or not porencephaly 1 equates to COL4A1-related familial vascular leukoencephalopathy (MONDO_0011865)

@maglott I see OMIM merged OMIM:607595 (which is equiv to  MONDO_0011865 'COL4A1-related familial vascular leukoencephalopathy') with OMIM:175780 (which is equiv to MONDO_0008289 'porencephaly 1'), so I think these should be merged.
