### ISSUE TITLE
Should hypertrichosis, hyperkeratosis, mental retardation, and distinctive facial features be retained?

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1098]
Live in GARD and MONDO: MONDO_0012372
https://rarediseases.info.nih.gov/diseases/9945/index

Moved by OMIM into Coffin-Siris 1 (https://www.omim.org/entry/135900, https://www.omim.org/entry/609943)

**Comment by nicolevasilevsky** [comment]
I think if OMIM merged these terms, we should consider doing so as well.

The proposal is to:
obsolete MONDO_0012372 'hypertrichosis, hyperkeratosis, mental retardation, and distinctive facial features'
and replace it with MONDO_0007617 'Coffin-Siris syndrome 1'

cc @gardinfocenter
