### ISSUE TITLE
Issue with kidney stone 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#11]
I think the issue here is EFO kidney stone should be equiv to MONDO_0008171 nephrolithiasis (need to merge these terms and obsolete MONDO_0005285 kidney stone).

Also, EFO xrefs [OMIM:605990](https://www.omim.org/entry/605990?search=605990&highlight=605990) on the nephrolithiasis class (EFO_0004253) (although the annotation is an 'OMIM_definition_citation' - is that different than an xref?)
I created this ticket in EFO: https://github.com/EBISPOT/efo/issues/24

![image](https://user-images.githubusercontent.com/6722114/32249810-8525e120-be47-11e7-870e-c83bf8d10b7e.png)

**Comment by nicolevasilevsky** [comment]
@zoependlington and @paolaroncaglia could we revisit this? Do we think the 'kidney stone' class is the same as 'MONDO_0008171 nephrolithiasis'?

thanks!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky (and @zoependlington )
I am looking into this, thanks!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky (and @zoependlington )
My thoughts:

Kidney stone, renal lithiasis and nephrolithiasis mean the same thing (based on etimology; also see https://en.wikipedia.org/wiki/Kidney_stone_disease and https://www.mayoclinic.org/diseases-conditions/kidney-stones/symptoms-causes/syc-20355755)
- [ ] Hence, 'kidney stone' should be merged into/obsoleted in favor of 'nephrolithiasis';

Urolithiasis refers to the finding of the same stones (formed in the kidneys) anywhere in the urinary system, including further down in the urinary tract
- [ ] Hence, we should consider making 'urolithiasis' the parent of 'nephrolithiasis'. One might argue that they are synonyms, but having 'urolithiasis' as a distinct term may be useful to describe the condition more broadly when (smaller) stones are detected in the lower urinary tract.

The former issue pertains to terms in both EFO and Mondo namespace, while the latter is present in both ontologies but pertains to a Mondo-only term. @nicolevasilevsky , would you like to go ahead with the edits first, and we'll follow accordingly? Of course, let me know if you disagree with anything!

Thanks,

Paola

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I added 'urolithiasis' as a parent of 'nephrolithiasis' but also kept 'kidney disease' as a parent. Does that work?
