### ISSUE TITLE
[NTR] SELENON-related myopathy

### ISSUE THREAD

**Issue by mayherpatel** [monarch-initiative/mondo#1106]
**Preferred term label:**
SELENON-related myopathy

**Synonyms**
SEPN1-related myopathy

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Myopathy caused by pathogenic variants in SELENON that is congenital or present early in childhood with neonatal hypotonia, delayed motor development, axial muscle weakness, scoliosis, and significant respiratory involvement. Spinal rigidity of varying severity is often present. (PMID: 12192640)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
congenital myopathy (MONDO:0019952)

**Your nano-attribution (ORCID)**

**Comment by mayherpatel** [comment]
Hi @NCIEVS, this is a request from the ClinGen Congenital Myopathies GCEP. Is there a timeline on when this will be modified?

**Comment by nicolevasilevsky** [comment]
Hi @mayherpatel I can work on this soon (probably today) but it wouldn't be available until the February release, which should be in early Feb

**Comment by mayherpatel** [comment]
That sounds good. Thank you!

**Comment by mayherpatel** [comment]
@nicolevasilevsky Thank you for continuing to work on this! If possible, would you be able to provide an update on when the term can be retrieved from the OLS?

**Comment by nicolevasilevsky** [comment]
Hi @mayherpatel I believe we'll have a new release of Mondo by the end of the month, and I think OLS is updated in the middle of each month
