### ISSUE TITLE
Align with ICD 11

### ISSUE THREAD

**Issue by saramsey** [monarch-initiative/mondo#1107]
Requesting support for ICD11 codes in MONDO. Thank you, @cmungall !

**Comment by nicolevasilevsky** [comment]
I am not clear what is needed here, but if this makes sense to @cmungall, then it's all good. :)

**Comment by saramsey** [comment]
Sorry for the (very terse) request, I will provide a bit more context. Our specific use-case is programmatically mapping an ICD-11 code for a rare/mendelian disease to an OMIM identifier. @cmungall indicated here
https://twitter.com/chrismungall/status/1217254240420159488
that it may be possible at some point in the future, to do this via MONDO as an intermediary. He requested that I put a feature request for MONDO in GitHub, related to this. Hope that helps?
Cheers,
Steve

**Comment by nicolevasilevsky** [comment]
Yes, thanks! @cmungall let me know if there are any action items for me.

**Comment by mellybelly** [comment]
Our hope is that in the future mondo will be a modular contribution to icd11, so it may end up being the other way around. But this is different than icd9/10 of course.

**Comment by nicolevasilevsky** [comment]
From @saramsey:
One example:  how would one programmatically map ICD-11 code "4A44.5 Mucocutaneous lymph node syndrome" to an OMIM ID?

**Comment by nicolevasilevsky** [comment]
@cmungall noted there is a mapping from snomed to ICD11:
https://confluence.ihtsdotools.org/download/attachments/61145760/ICD11_4A.xlsx?api=v2

**Comment by cmungall** [comment]
We map to ICD10 and there are ICD10 to 11 mappings, but it will be more complete to map directly since presumably ICD11 will be more complete than ICD10.

Some things we need to determine

 - canonical source for ICD11
 - how fluid it is?
 - how is it being coordinated with ordo, omim, etc?

**Comment by mellybelly** [comment]
@hsolbrig @cgchute would know better RE any coordination with OMIM or ORDO, but my understanding was that we would ideally be able to include a Mondo module with attribution/provenance.

**Comment by cgchute** [comment]
Melissa may be right, it might start as the other way around.  Robert Jakob (Dr. ICD at WHO) indicated last year an openness to reference MONDO with attribution.  Chris Mungall made some suggestions about exploring the anatomy hierarchy of ICD11 with OBO resources to demonstrate utility.  I think I sent an anatomy download, but I suspect we all got overtaken by other events.  Is it time to resurrect an ICD11/Mondo relationship for the Foundation?  The ICD group did favorably discuss HPO some time back.  

Once things are in the Foundation, this more or less faciliates the reverse direction.  Basically one looks for the most appropriate parent (which may be the term itself) in the Foundation that has a corresponding tabular code (those hierarchical, alphanumeric things as opposed to URIs).

**Comment by cgchute** [comment]
ICD11 has multiple components.  One is an acyclic graph, semantic network of terms and concepts, that more or less is the backbone of the new ICD.  Each entry also has rich metadata, like a definition and various identifiers.

The traditional monohierarchy that most folks see and use, which we call a linearization, derives from this foundation.  It has the seven digit base 34 IDs, rather than the URI identifiers of the Foundation.

Chris

**Comment by joeflack4** [comment]
Thanks Chris! That is helpful; probably all I need to know for now. But interested to learn more about how that works under the hood when it comes time for me to work with ICD11.

**Comment by matentzn** [comment]
@cgchute is there anything like [this](https://bioportal.bioontology.org/ontologies/ICD10CM) for ICD11 to run some experiments for mapping?

**Comment by cgchute** [comment]
Actually, I was coPI on the NCBO and BioPortal back in the day.  ICD11 does not seem to be there yet, which would be a Stanford thing these days.  I am copying Can Çelik at WHO, who can point you to the API resources for ICD11.  That may ultimately be the more useful resource.

Chris

**Comment by matentzn** [comment]
I am not sure cc-ing someone on GitHub is possible :) but Can, if you see this, I would be happy to learn which file you recommend to get a "complete dump" of ICD11 including hierarchies and "semantic core". Thank you!

**Comment by sabrinatoro** [comment]
@mellybelly needs to sort out our agreement with WHO before they send us the ICD11 foundation.

**Comment by joeflack4** [comment]
@matentzn @twhetzel I'm wondering what additional tasks remain in this issue that aren't already addressed by https://github.com/monarch-initiative/mondo-ingest/issues/16, which is essentially done as soon as a couple PRs are merged (links in that issue).

**Comment by joeflack4** [comment]
Completed via #16
