### ISSUE TITLE
Merge? Filippi syndrome and Scott Bryant Graham syndrome

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#111]
We have two distinct diseases in MONDO here (consistent with ORDO and GARD)

OMIM used to have a live entry for SCOTT CRANIODIGITAL SYNDROME (SCOTT-BRYANT-GRAHAM SYNDROME):

https://omim.org/entry/312860

This is now moved to:
https://omim.org/entry/272440 FILIPPI SYNDROME; FLPIS
SYNDACTYLY, TYPE I, WITH MICROCEPHALY AND MENTAL RETARDATION
SCOTT CRANIODIGITAL SYNDROME WITH MENTAL RETARDATION

it's straightforward to update but we want to remain in sync with other resources

Orphanet has two distinct entries for SBG syndrome and Filippi:

Orphanet:1514 Scott-Bryant-Graham syndrome, Scott craniodigital syndrome
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_1514
OMIM:312860 (E (exact mapping (the terms and the concepts are equivalent)))

Orphanet:3255 Filippi syndrome
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_3255
OMIM:272440 (E (exact mapping (the terms and the concepts are equivalent)))

Question for @Orphanet: Do you plan to merge these two? Which ID will prevail?

@GARDInfoCenter: you also have two distinct entries:

 * https://rarediseases.info.nih.gov/diseases/4776/scott-bryant-graham-syndrome
   * xref: OMIM:312860
   * xref: Orphanet:1514
   * xref: UMLS:C1839311
 * https://rarediseases.info.nih.gov/diseases/62/filippi-syndrome
   * xref: OMIM:272440
   * xref: Orphanet:3255
   * xref: UMLS:C0795940

**Comment by annieolry** [comment]
Hello,
We are not going to merge these two entities unless there are new publications to show that these two entries are now considered as an unique entity.

here is the argumentation from the decision we have taken in March 2017:

Filippi syndrome is AR with CKAP2L gene identified;25 cases descibed, majority male. Characterized by microcephaly, bilateral syndactyly of fingers and toes (2-4), intellectual disability. 
Scott syndrome has no identified gene: Charcaterized by bilateral syndactyly of fingers and toes (2-4) Brachycephaly + intellectual deficiency/AR or XL in Orphanet. 
OMIM Scott syndrome has been moved to Filippi syndrome: 312860 MOVED TO 272440 (may 2013) 
Facial appearance different (broad Vs narrow nose) 
1971 A new craniodigital syndrome with mental retardation. 
1990 The craniodigital syndrome of Scott: Report of a second family PMID: 2174209 
1995 Craniodigital syndromes: report of a child with Filippi syndrome and discussion of differential diagnosis. --> "Lorenz et al,3 Scott et al,4 and Zerres et al5 independently reported two distinct MCA/MR syndromes with microcephaly, syndactyly, and short stature.  -However, in both cases, the facial appearance is very different from the dysmorphism observed in Filippi syndrome. Moreover, microcephaly in the patient reported by Zerras et al5 is of postnatal occurrence -only boys have been affected with Scott syndrome, suggesting an X linked mode of inheritance. 
2007 Craniodigital Syndrome of Scott: Clinical and Neuroradiological features of a New Case  : last published article--> Scott and filipi are considered different entities within the spectrum of craniodigital syndromes
No clear evidence in the litterature that Filippi and Scott is the same entity. Filippi syndrome appears to be an independent and possibly homogeneous genetic condition. 
Decision: Do not deprecate
PMID: 2174209, 18553552, 7473664

**Comment by nicolevasilevsky** [comment]
ping @annieolry 
Can this be closed?
