### ISSUE TITLE
Fetal akinesia deformation sequence vs. Pena-Shokeir syndrome type 1

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1114]
Is Fetal akinesia deformation sequence (MONDO_0008824) equivalent to Pena-Shokeir syndrome type 1 or is 
Pena-Shokeir syndrome type 1 equivalent to fetal akinesia deformation sequence 1?

See also:
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=994
https://www.omim.org/entry/208150
https://rarediseases.info.nih.gov/diseases/9634/index
https://www.omim.org/phenotypicSeries/PS208150

@ahamosh , @ana-rath-orphanet

**Comment by nicolevasilevsky** [comment]
@maglott 'Pena-Shokeir syndrome type 1' is a synonym for 'Fetal akinesia deformation sequence' (MONDO_0008824) 

Is 'fetal akinesia deformation sequence 1' a different disease from 'Fetal akinesia deformation sequence' (MONDO_0008824) ?

**Comment by maglott** [comment]
@nicolevasilevsky , I am asking for review by medical experts.  I see what is in MONDO.  My question arose from review of https://www.omim.org/phenotypicSeries/PS208150,  which I interpret as meaning the general term is distinct from type 1.  Those are the cases where I try to intepret whether the synonomy reported in https://www.omim.org/entry/208150 is misleanding because OMIM often retains general terms with the original record when adding gene-specific terms and MIM numbers.

**Comment by ahamosh** [comment]
Hi All,
The general concept of Fetal Akinesia is equivalent to Pena-Shokeir and should be mapped to PS208150 (details in the entry 2018150).  Fetal Akinesia syndrome 1 is the same as Pena-Shokeir 1 and is entry 208150.   I am a bit concerned by the words deformation sequence because they imply an environmental cause rather than genetic etiology.  Happy to discuss further and apologies for the delay.
All the best,
Ada

**Comment by maglott** [comment]
Thanks for the clarification, @ahamosh .

**Comment by nicolevasilevsky** [comment]
I added OMIM:PS208150 as an xref to Fetal akinesia deformation sequence (MONDO_0008824)

Is there any other action required?

Thanks!

**Comment by maglott** [comment]
Pena-Shokeir syndrome type 1 needs to be removed as an exact synonym,
Likely nodes also have to be added for children  of https://www.omim.org/phenotypicSeries/PS208150

**Comment by nicolevasilevsky** [comment]
@ahamosh FETAL AKINESIA DEFORMATION SEQUENCE; FADS is an alternative title for [OMIM:208150 FETAL AKINESIA DEFORMATION SEQUENCE 1; FADS1](https://www.omim.org/entry/208150). We have these as equivalent in Mondo too. Is this incorrect?

**Comment by ahamosh** [comment]
In principle, I would use the PS# for the generic and then the MIM number alone for the 1 of a series, the members of a series should all be children of the PS number.  If this isn't clear, I would love to talk to you about it, because it is an important distinction. My cell phone is 410-961-0065.

**Comment by nicolevasilevsky** [comment]
That makes sense to me Ada, thank you! I'll work on this. :)
