### ISSUE TITLE
Remove synonym "lower grade glioma" from MONDO_0005499 brain glioma

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1115]
(This is a request to remove, rather than add, a synonym, but there isn't a specific issue template.)

Stemming from https://github.com/EBISPOT/efo/issues/685

**MONDO_0005499 brain glioma**

Has (exact?) synonym "lower grade glioma", coming from DOID. But MONDO_0021637 'low grade glioma' already exists and the two are not the same, so you may want to remove the synonym.

Also, I noticed that MONDO_0005499 brain glioma has an "Editor note: TODO report incorrect EFO assigment of NCIT:C71732". I think I fixed that previously while working on another term, see https://github.com/EBISPOT/efo/issues/340#issuecomment-456006897. If that's what the Editor note referred to, could you delete that comment please?

Also, do let us know if there are other similar TODOs for EFO buried in Mondo comments somewhere :-) Thank you!

**Comment by nicolevasilevsky** [comment]
I see comments mentioning EFO on two classes:
'palatal neoplasm'
'mucoepidermoid tumor'

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
> I see comments mentioning EFO on two classes:
> 'palatal neoplasm'
> 'mucoepidermoid tumor'
Thank you. For the former, the action item is for EFO first (FYI I opened https://github.com/EBISPOT/efo/issues/710). For the latter, the action item seems to be for Mondo first. Best wishes,
Paola
