### ISSUE TITLE
question: spinocerebellar ataxia and cerebellar ataxia

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1116]
MONDO_0015244 defines autosomal recessive cerebellar ataxia as a disorder involving both the cerebellum and the spinal cord "..characterized by degeneration or abnormal development of the cerebellum and spinal cord..."

Looking for guidance as to whether "Autosomal recessive cerebellar ataxias (ARCA)" as described by Orphanet are equivalent to SCAR (Autosomal recessive spinocerebellar ataxia) as described by OMIM.
I see that individual records in Ophanet report synonomy for specific disorders (e.g. ORPHA:412057, Autosomal recessive cerebellar ataxia due to STUB1 deficiency has a synonym of Spinocerebellar ataxia autosomal recessive type 16

In particular, should PS213200 (https://www.omim.org/phenotypicSeries/PS213200) be an XRef for MONDO_0015244?

**Comment by nicolevasilevsky** [comment]
> In particular, should PS213200 (https://www.omim.org/phenotypicSeries/PS213200) be an XRef for MONDO_0015244?

I think so

**Comment by nicolevasilevsky** [comment]
@maglott I added PS213200 as a xref for MONDO_0015244.

Is there any other action required?

**Comment by nicolevasilevsky** [comment]
@maglott pinging you - thanks!

**Comment by maglott** [comment]
Looks OK to me. thanks

**Comment by nicolevasilevsky** [comment]
Thanks! Closing. :)
