### ISSUE TITLE
add a SOP to manual for adding new gene-centric diseases, how we relate these to omim

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1118]
Need to add add a SOP to the manual for adding new gene-centric diseases, how we relate these to omim

see https://github.com/monarch-initiative/mondo/pull/1037

**Comment by maglott** [comment]
Key questions:
* when is including a gene symbol in name of a disease justified ?
* are those gene reports valid only for germ-like changes (and not somatic) or all gene-phene terms.

**Comment by nicolevasilevsky** [comment]
I added additional content to the disease naming doc above, I think that addresses this ticket.
