### ISSUE TITLE
[Revise subclass] MONDO:0003778 primary immunodeficiency disease

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1143]
**MONDO:0003778 primary immunodeficiency disease**
Is defined as "A disorder in which the immune system is unable to mount an adequate immune response."
but has subclass 'immune deficiency disease' (undefined).
Shouldn't it be the other way around? See e.g. https://en.wikipedia.org/wiki/Immunodeficiency#Primary_or_secondary
Also, MONDO:0003778 'primary immunodeficiency disease' has an editor's note "check relationship to immunodeficiency syndrome", but I couldn't find a Mondo term labeled exactly as such.
I started looking into MONDO:0003778 because in EFO there is an apparent duplication with Orphanet:101997 Primary immunodeficiency which we'd like to fix (https://github.com/EBISPOT/efo/issues/551). It seems that Mondo doesn't xref Orphanet:101997 at all. Any advice please?
Thanks!

**Comment by nicolevasilevsky** [comment]
I removed the comment on MONDO:0003778 'primary immunodeficiency disease'

**Comment by nicolevasilevsky** [comment]
looks like Orphanet:101997 was an xref on MONDO_0015138 rare genetic primary immunodeficiency, which was obsoleted and replaced with MONDO:0003778 'primary immunodeficiency disease'.

I will move all these xrefs to 'primary immunodeficiency disease', this wasn't done (but should have been)

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia all the action items on this ticket are done :)
