### ISSUE TITLE
Request to Relabel MONDO:0010624

### ISSUE THREAD

**Issue by ErinRiggs** [monarch-initiative/mondo#1144]
**Mondo term (ID and Label):**
MONDO:0010624 ichthyosis follicularis-alopecia-photophobia syndrome
**Suggested new label:**
IFAP/Breshek syndrome
**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Related to the request to update the definition (Ticket #1142 ), the ClinGen ID/Autism GCEP would like to request a relabel of this term to more accurately reflect the phenotypic spectrum.  Though initially we felt that simply updating the definition would suffice, after further discussion, we are requesting that the label be updated.  References are in Ticket #1142  - please let me know if you have any questions.

**Comment by ErinRiggs** [comment]
Hi Nicole!  We are doing this curation today, so I was just checking on this ticket.  I see that it is closed, but I don't see the change in OLS.  Is it just in the queue for a subsequent release?

**Comment by nicolevasilevsky** [comment]
I think this is dependent on the Mondo release, which should be any day now. And then I think it takes a couple weeks before OLS picks it up.

**Comment by ErinRiggs** [comment]
Sounds good - thanks for the update!


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by ErinRiggs** [comment]
Hi Nicole - I am so sorry, but I need to request an edit to this.  The "Breshek" part of this name is actually an acronym, and should be "BRESHECK" (all caps, with the extra c).  Here is a reference describing the features associated with BRESHECK if you need it: https://www.ncbi.nlm.nih.gov/pubmed/22105905?dopt=Abstract
Please let me know if you have any questions.

**Comment by nicolevasilevsky** [comment]
no problem! I'll make this change and it will be available in the next release (in early May)
