### ISSUE TITLE
[Obsolete] MONDO:0015597 dup of MONDO:0002985?

### ISSUE THREAD

**Issue by cbizon** [monarch-initiative/mondo#1146]
**Mondo term (ID and Label)**
http://purl.obolibrary.org/obo/MONDO_0015597 
pustulosis palmaris et plantaris

**Reason for deprecation**
Possible duplication of http://purl.obolibrary.org/obo/MONDO_0002985

**Suggested replacement or term to consider**
These terms seem to be referring to the same thing?  And both have the same exact synonym of "palmoplanter pustulosis"

**Comment by nicolevasilevsky** [comment]
I will email the list and work on this after 02/28, assuming there are no objections
