### ISSUE TITLE
Monogenic SLE and SLEB16

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#1164]
OMIM generic entry for SLE https://omim.org/entry/152700

For most SLE entries in OMIM (e.g SLEB1, SLEB2, ...) we should treat as susceptibilities and not subtypes of SLE. Note we don't typically have HPOA entries for these.

An exception is SLEB16. We have annotations for this.

In OMIM this is called SYSTEMIC LUPUS ERYTHEMATOSUS 16; SLEB16 https://omim.org/entry/614420 and caused by AR mutation in DNASE1L3

ORDO has a concept they call Autosomal systemic lupus erythematosus https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_300345 which is declared equivalent to the OMIM concept.

This ORDO concept is stated to be caused by germline mutations in 2 genes: DNASE1 and PRKCD; and loss of function mutations in DNASE1L3 (note ORDO provides to citations for g2d links)

(note that PRKCD is not associated with SLE in OMIM, it is associated with  [https://omim.org/entry/615559](ALPS3) )

Note that the ORDO concept sounds more generic - it doesn't have a gene name or number in the label.

The ORDO def is _Autosomal systemic lupus erythematosus is a rare, genetic, multisystemic, chronic autoimmune disease characterized by the presence of systemic lupus erythematosus symptoms in two or more members of a single family._

(confusingly this seems like it should apply not only to monogenic autosomal forms, but to susceptibilities)

Are these equivalent? I don't think they should be

Review of monogenic SLE
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6232876/

Claims many genes involved in monogenic forms

Also talks of similarity with ALPS

Cites an n-of-1 observation that can justify the g2d to PRKCD in ORDO:

Belot A, Kasher PR, Trotter EW, Foray AP, Debaud AL, Rice GI, S et al. Protein kinase cdelta deficiency causes mendelian systemic lupus erythematosus with B cell-defective apoptosis and hyperproliferation. Arthritis Rheum. (2013) 65:2161–71. 10.1002/art.38008

Conversely in the generic entry https://omim.org/entry/152700 there is no mention of PRKCD

This is all a bit confusing. Clearly it's not straightforward as the genetics of SLE are hard but I think we need to be attaching evidence and provenance to all associations. Also think that if the semantics of a class are gene-specific this should be reflected by not having a generic name.

**Comment by nicolevasilevsky** [comment]
@cmungall can this be closed? I see you merged your PR

**Comment by cmungall** [comment]
I don't think I addressed ebveryhing

**Comment by nicolevasilevsky** [comment]
I think this has been addressed, closing. Please reopen if other action it needed.
