### ISSUE TITLE
[Revise subclass] MONDO:0020135 non-syndromic pontocerebellar hypoplasia

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1168]
**MONDO:0020135 non-syndromic pontocerebellar hypoplasia**

Defined as "Nonsyndromic pontocerebellar hypoplasias (PCH) are a rare heterogeneous group of diseases characterized by hypoplasia and atrophy and/or early neurodegeneration of the cerebellum and pons. Eight subtypes named type 1-8 have been described (see these terms), generally inherited in an autosomal recessive pattern.".

Not surprisingly, the more specifically defined among its children are clearly syndromic, e.g. pontocerebellar hypoplasia type 2, pontocerebellar hypoplasia type 3... so their parent MONDO:0020135 should not be described as non-syndromic - or those children should be moved elsewhere. 'non-syndromic pontocerebellar hypoplasia' is a child of 'non-syndromic central nervous system malformation' which has an "Editor note: ORDO has various potentially syndromic disease groupings under here, we modify these. See https://github.com/monarch-initiative/mondo-build/issues/58", so possibly 'non-syndromic central nervous system malformation' simply escaped editing, or was added later. TBH, it's hard to imagine that a central nervous system malformation could not result in syndromes :-(

Thanks,
Paola

**Comment by cmungall** [comment]
I agree with @paolaroncaglia's analysis.

Shall we reach out to @Orphanet for comments

https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=98523

_Nonsyndromic pontocerebellar hypoplasias (PCH) are a rare heterogeneous group of diseases characterized by hypoplasia and atrophy and/or early neurodegeneration of the cerebellum and pons. Eight subtypes named type 1-8 have been described (see these terms), generally inherited in an autosomal recessive pattern._

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 

> I agree with @paolaroncaglia's analysis.
> 
> Shall we reach out to @Orphanet for comments
> 
> https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=98523

Thank you for changing the label from 'non-syndromic pontocerebellar hypoplasia' to 'pontocerebellar hypoplasia'. I'm re-opening this ticket as I'm not sure if the action item suggested above is for you guys (who probably have better links to Orphanet than we do), or for EFO. Thanks anyway.
Paola

> 
> _Nonsyndromic pontocerebellar hypoplasias (PCH) are a rare heterogeneous group of diseases characterized by hypoplasia and atrophy and/or early neurodegeneration of the cerebellum and pons. Eight subtypes named type 1-8 have been described (see these terms), generally inherited in an autosomal recessive pattern._

**Comment by nicolevasilevsky** [comment]
I updated the definition. I'll email Orphanet folks.

**Comment by nicolevasilevsky** [comment]
I think this ticket can be closed, I sent Orphanet an email with a link to this ticket.

**Comment by paolaroncaglia** [comment]
Thanks @nicolevasilevsky !
