### ISSUE TITLE
[NTR] TPM3-Related Myopathy

### ISSUE THREAD

**Issue by RedRiver1816** [monarch-initiative/mondo#1169]
**Preferred term label:** 
TPM3-Related Myopathy

**Synonyms:** 
Autosomal Dominant TPM3-Related Myopathy
TPM3 Myopathy
Congenital Myopathy Related to TPM3

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
TPM3-Related Myopathy is a disorder of the musculoskeletal system that covers a wide spectrum of phenotypes and is caused by pathogenic variants in the skeletal muscle γ-Tropomyosin gene. These variants lead to a variety of overlapping adult onset and congenital myopathies characterized by muscle weakness, hypotonia, motor delay, myopathic facies, scoliosis, and sometimes respiratory involvement. Histologic findings on skeletal muscle biopsy are variable with nemaline and intranuclear bodies, cap-like lesions, fiber-type disproportion, and dystrophic features even in patients with the same mutation. (PMID:24692096)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser):** 
MONDO:0017303 (qualitative or quantitative defects of tropomyosin)
MONDO:0019952 (congenital myopathy)

**Suggested child terms for collapse under new term:**
MONDO:0012239 (Nemaline Myopathy 1)
MONDO:0015753 (Cap Myopathy)
MONDO:0009711 (congenital fiber-type disproportion myopathy)

Comment: The most penetrant phenotype among all of the TPM3-related myopathy disease entities is muscular weakness. While nemaline myopathy is the most common presentation, several other myopathies have been reported in association with TPM3 mutations. The absence of clearly defined and/or distinct differences in molecular mechanism, coupled with noted phenotypic variability (both intra- and inter-familial) for individual variants, indicates that these entities are part of the same clinical spectrum.

@nicolevasilevsky: This is a ClinGen EP Request.

**Comment by nicolevasilevsky** [comment]
is this the correct EP to reference?
https://clinicalgenome.org/docs/clingen-cmp-ep-acgs-collaboration/

**Comment by RedRiver1816** [comment]
This is the correct EP: https://clinicalgenome.org/affiliation/40031/
Thanks!
