### ISSUE TITLE
MONDO stats for R24

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/mondo#117]
In preparation for our upcoming R24 progress report we need some numbers since 2016-09-01; to the extent that these reports can be auto generated for future, it would be useful:

Number of ontologies integrated
Number of cross references incorporated
Number of issues detected/resolved [using k-boom] ?
Number of terms added
Some meaningful quantification of curation?

**Comment by nicolevasilevsky** [comment]
@jmcmurry do you still need all these #'s?
- **number of ontologies integrated** is 10
- **number of cross refs**: @cmungall can you easily generate this number?
- **number of issues detected**: not sure how to best answer this, there are currently 75 open issues and 22 issues that have been closed (so I guess we could report there are/were 97 issues?)
- **number of terms added**: I have added 3 new terms myself, not sure if any other terms have been added
- I've also been working on adding new definitions for the GARD rare disease subset. So far I've added 34 new defs.

**Comment by jmcmurry** [comment]
Great! Thanks. I have to dig in and get this into the RPPR. I've not even read the latest yet.

**Comment by nicolevasilevsky** [comment]
I believe this can be closed now. Please reopen if not.

**Comment by jmcmurry** [comment]
Well, the automatic generation of reports is still to be done. @cmungall did you make any headway?
