### ISSUE TITLE
[NTR] Placeholder ticket for OMIM diseases absent from Mondo

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1173]
Stemming from discussion at our EFO-Mondo call today (https://docs.google.com/document/d/11OY4HN4EzmviVyqe3CrHy6TA-KiSRxeaqPA5pYWvT6U/edit), I will provide some OMIM disease IDs that I couldn't find in Mondo. To be continued (not very shortly though). Thanks.

**Comment by nicolevasilevsky** [comment]
related to #1283

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky @cmungall 
I believe this ticket could be closed as superceded by #1283 (unless you have objections). I made a note for our next EFO-Mondo call to please discuss expected/approximate timelines for the OMIM ingest update. Thanks.

**Comment by nicolevasilevsky** [comment]
sure, I'll close.
