### ISSUE TITLE
add synonyms for Ehlers-Danlos syndrome?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1174]
**Mondo term (ID and Label)**
MONDO_0020066 'Ehlers-Danlos syndrome'

**Synonym to be added**
@pnrobinson and @cmungall all of these synonyms exist in Mondo source ontologies, but they are not all in Mondo. Any objections to adding these to Mondo?

- Cutis hyperelastica - _this is an excluded synonym in Mondo, but it seems like it may be a legit synonym,  it is in 4 other ontologies, and this [article](https://www.medscape.com/answers/1294801-87652/how-is-cutis-hyperelastica-ehlers-danlos-syndrome-differentiated-from-cutis-laxa) makes it seem like a synonym_
- Cutis hyperelastica
- EDS
- elastic skin
- Ehlers-Danlos Syndrome
- Danlos disease
- Dystrophia mesodermalis congenita
- Ehlers Danlos Disease
- Ehlers-Danlos Disease
- Hereditary collagen dysplasia
- India rubber skin
- Ehlers Danlos Syndrome
- Ehler Danlos Syndrome
- Danlos Disease, Ehlers
- Disease, Ehlers Danlos
- Disease, Ehlers-Danlos
- ED syndrome
- EHLERS DANLOS DIS
- Ehlers-Danlos syndrome (disorder)
- Ehlers-Danlos Syndrome [Disease/Finding]
- Fibrodysplasia elastica generalisata
- Meekeren-Ehlers-Danlos syndrome
- Syndrome, Ehlers-Danlos
- Danlos
- danlos ehlers syndrome
- EDS - Ehlers-Danlos syndrome
- eds ehlers danlos syndrome
- ehlers danlos syndromes
- Ehlers-Danlos
- Ehlers-Danlos syndrom
- Ehlers-Danlos syndrome (diagnosis)
- Ehlers-Danlos syndrome, NOS
- EHLERS-DANLOSOV SINDROM
- ELERSA-DANLOSA SINDROM
- hyperelastica; cutis
- skin elastic

See this spreadsheet for more details: https://docs.google.com/spreadsheets/d/1rVK1-c9xU-HNDdVFhtL43I36iXUi9V1WpKJTg2Hglts/edit#gid=1888372711

I'll add these if there are no objections.

@jmcmurry would like to use this as an example for my AMIA talk.

**Comment by pnrobinson** [comment]
DANLOSA and DANLOSOV are incorrect. Ehlers-Danlos syndrome, NOS is ICD. Danlos is incorrect.
There are some historical terms we should label as obsolete, India rubber skin, and cutis hyperelastica etc.

**Comment by nicolevasilevsky** [comment]
Thanks for the feedback, Peter!
