### ISSUE TITLE
MONDO:0018797 genetic cardiac malformation

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1175]
**MONDO:0018797 genetic cardiac malformation**

This is an Orphanet grouping term (I see that it's in a subset called "ordo_group_of_disorders"), currently a subclass of 'heart disease' and with no link to genetic diseases despite its label. Its children seem a mix of congenital/familial and genetic disorders, but the label only refers to genetic. I presume that this is a known issue and that Mondo is fine with the ambiguity in this case? Useful to know as EFO imports the Mondo term. Thank you.

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia what is the action item? Are you suggesting we rename the class to cardiac malformation?

Or obsolete the class?

Thanks!

**Comment by nicolevasilevsky** [comment]
Maybe we should ask Orphanet too?

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
The simplest action item would be to rename 'genetic cardiac malformation' to 'cardiac malformation'. Whether it'd be ok to do that to an Orphanet grouping term, may need discussion with @cmungall ;-)
(I'll be away for a few days so I won't be responding/commenting on tickets, thanks!)

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I created a PR, and assigned Chris to review

**Comment by cmungall** [comment]
does this grouping really do us any work? What if we obsolete it? Do we lose information? Is it really a disease, not a phenotype?

I think we need to be a bit more vigorous in obsoleting some of these ordo groupings?

**Comment by nicolevasilevsky** [comment]
I'm okay with obsoleting. It has 4 children that are also classified under other parents too, so those will not be affected too much. I'll email the list

**Comment by courtneythaxton** [comment]
@nicolevasilevsky @cmungall From what I see on the ClinGen side, is that we have no groups that currently use this term. I also agree that the child terms do have other parental terms that are just as befitting, so obsoletion of the term seems reasonable, and that it would not severely impact any other entity.

**Comment by pnrobinson** [comment]
I think that probably this term intends to mean the same thing as congenital heart disease, which in my opinion is a far better label. "Genetic" in the sense of not necessarily Mendelian but related to the "genesis" of the heart.

**Comment by nicolevasilevsky** [comment]
cc @ana-rath-orphanet @annieolry

**Comment by nicolevasilevsky** [comment]
emailed Ana on 03/17/20

**Comment by ana-rath-orphanet** [comment]
Hello. This group is included in Rare genetic diseases (so in Orphanet, there is a link to genetic diseases: please check that in MONDO) and allows to group CHD for which a gene is known or that are familial. It is populated following the discovery of new genes. Obsoleting is, for me, losing the info on what CHD care of genetic origin (known or supposed based on inheritance). 
@pnrobinson "genetic" here means really genetic origin and not genesis of the heart ;)
@annieolry FYI
Happy to discuss further.

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet sounds like it is best to leave the term in Mondo, as is.

Hopefully everyone is okay with that. I'll add a comment with a link to this ticket in the ontology.

Please reopen if you would like to continue to discuss.

**Comment by courtneythaxton** [comment]
Well one compromise would be to use a different term than "genetic" due to the ambiguity. In other instance the word "hereditary" or even "familial" has been used. 

For example for cardiomyopathy MONDO current has familial  hypertropchc cardiomyopathy ([MONDO:0024573](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0024573&viewMode=All&siblings=false)) to indicate a genetic underpinning to a disorder that can also arise for non-genetic, external factors.

**Comment by nicolevasilevsky** [comment]
I like that idea, Courtney!

**Comment by nicolevasilevsky** [comment]
Ok - I relabeled the term to 'genetic cardiac malformation' and added synonyms.

**Comment by ana-rath-orphanet** [comment]
We are working on the nomenclature of he whole group (Pas and synonyms), will keep you posted
Ana

Dr.Ana Rath
Directrice / Director
Inserm US14 - Orphanet

Coordinator of RD-CODE, Codification for rare diseases in health information systems
Coordinator of HIPBI-RD - Harmonizing information on phenomics for a better
interoperability in the rare diseases field

Coordinator of RD-ACTION, European Joint Action on Rare Diseases 2015-2018
Past Member of the Revision Steering Committee of the WHO's International
Classification of Diseases (ICD11)
Past Scientific coordinator of Support-IRDiRC, Scientific secretariat of the International Rare Diseases Research Consortium

Phone number: +33 (0)1 56 53 81 37
Direct line: +33 (0)1 56 53 81 47
Mobile : +33 (0)6 09 73 55 83
email: ana.rath@inserm.fr

www.orpha.net
www.orphadata.org
www.rd-code.eu
www.rd-action.eu
www.irdirc.org

**Comment by maglott** [comment]
Please note: (https://www.medicinenet.com/script/main/art.asp?articlekey=3378)
Familial: A condition that tends to occur more often in family members than is expected by chance alone. A familial disease may be genetic (such as cystic fibrosis) or environmental (such as chicken pox).

That distinction was certainly hammered into those applying MeSH terms to articles in PubMed.

**Comment by courtneythaxton** [comment]
Fair enough @maglott on familial. Would there be an objection to the use of hereditary then? 

This are several examples of derivatives in medicine net:
**Hereditary mutation:** https://www.medicinenet.com/script/main/art.asp?articlekey=3723
**Definition:** A gene change that occurs in a germ cell (an egg or a sperm) and is then incorporated into every cell in the developing body of the new organism. Hereditary mutations play a role in cancer, as, for example, in the eye tumor retinoblastoma and Wilms' tumor of the kidney. Also known as germline mutation.


**Heredity:** https://www.medicinenet.com/script/main/art.asp?articlekey=3725
**Definition:** The genetic transmission of characteristics from parent to child.

**Heritable:** https://www.medicinenet.com/script/main/art.asp?articlekey=3719
**Definition:**  Capable of being transmitted from parent to child.

Many other dictionaries refer to "Hereditary" as transmission of genetic effects from parts to child, including both plan language ones (Oxford, Cambridge, Merriam-Webster), and medical dictionaries.

**Comment by courtneythaxton** [comment]
Actually looking at the initial request, it seems that there were other diseases that are child terms that were familial, and not necessarily genetic. So I think it would be good to consider if you want to keep the same classes grouped, that "Familial cardiac malformation" may be more appropriate for the term at this time. 

Then one can consider adding a child term that deals specifically with the inherited forms, i.e. genetic or hereditary.

**Comment by pnrobinson** [comment]
Well, some of these diseases clearly have genetic influences but do not run in families, e.g. tetralogy of Fallot.
Why not say "Developmental cardiac malformation" as the upper level term?

**Comment by nicolevasilevsky** [comment]
Thanks all for the discussion!

Here is what we have right now :
![image](https://user-images.githubusercontent.com/6722114/77090862-fef1fe00-69c4-11ea-90b5-1e1785fbd91b.png)

Sounds like @ana-rath-orphanet is working on the nomenclature, so it's probably best that I wait for her, and then I'll revise accordingly.

**Comment by nicolevasilevsky** [comment]
Action items for me from the call on 05/22:

- [ ] Relabel children under 'genetic cardiac malformation' as ‘(disease)’ and add has features some Phenotype
- [ ] follow up with Ana

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky , it's me again. May I ask if there's any update on this, please? Sorry to bug you, I know how many tickets you're looking into, but it'd be great to get these edits in the next Mondo release! :-)
Best,
Paola

**Comment by pnrobinson** [comment]
Somehow I think that this label is not ideal, since for the most part it is not possible to characterize the genetic causes of congenital heart disease. I think that the phrase "Congenital heart disease" is well established in the community. Why not use that?

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia there is a pending PR for @cmungall to review/approve.

I'll try to discuss this on a Monarch call tomorrow, I'll keep you updated. Please always feel free to nag us. :)

**Comment by nicolevasilevsky** [comment]
Decision on 05 June call:
- [ ] obsolete 'genetic cardiac malformation'
- [ ] consider 'congenital heart disease'

**Comment by maglott** [comment]
What then is the distinction between a congenital functional disorder and a congenital structural abnormality?

**Comment by nicolevasilevsky** [comment]
@maglott - I'm not sure I understand your question - are you saying that this grouping term provided a distinction between congenital functional disorders and a congenital structural abnormalities?

All of the classes that were under 'genetic cardiac malformation' had other superclasses, so they will be classified under those terms.  'Genetic cardiac malformation' was undefined.

**Comment by maglott** [comment]
That is what i was asking, I did not look at the classifications. I misread the comment to mean that the terms were being considered equivalent.  Thanks for explaining.
