### ISSUE TITLE
[NTR] Adenovirus renal infection

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1188]
**Preferred term label:**
adenovirus renal infection

**Synonyms**
adenovirus kidney infection

**Definition**
Infection of the kidney due to adenovirus. Adenovirus renal infections usually occur in immunocompromised patients, more commonly in bone marrow and stem cell transplant recipients.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO_0043479 'adenoviridae infectious disease'
MONDO_0005240 'kidney disease'

**Logical def**
'adenoviridae infectious disease'
 and ('disease has location' some kidney)

related to: https://github.com/obophenotype/human-phenotype-ontology/issues/5024

@pnrobinson how does this proposed new term look?

**Comment by nicolevasilevsky** [comment]
Also, should we add the SubClassOf assertion:
'disease has major feature' some 'Severe adenovirus infection'

to MONDO_0043479 'adenoviridae infectious disease'

@pnrobinson and @cmungall

**Comment by nicolevasilevsky** [comment]
Could we add a SubClassOf assertion to adenovirus renal infection that is:

'disease has major feature' some ('Severe adenovirus infection' and 'part of' some kidney)

**Comment by pnrobinson** [comment]
Small point but I think the definition Infection of the kidney **by** Adenovirus is better
