### ISSUE TITLE
[Revise logical def] MONDO:0005267 heart disease

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1189]
**MONDO:0005267 heart disease**

Is a subclass of 'cardiovascular disease' and 'thoracic disease', and equivalent to
disease or disorder and (disease has location some heart) 
which is fine

MONDO:0000474 pericardium disease 
Is a subclass of 'cardiovascular disease' and 'thoracic disease', and equivalent to
disease or disorder and (disease has location some pericardium) 
which is also fine

So 'heart disease' and 'pericardium disease' are siblings. The pericardium wraps around the heart  and the roots of the great vessels. EFO has the same structure (EFO's 'heart disease' is mapped to Mondo's, and EFO imports Mondo's 'pericardium disease'). 

We're working with https://www.opentargets.org/ to provide them with an EFO profile where diseases sit under Therapeutic Areas based on clinical relevance rather than anatomical location. In most cases the existing EFO (and Mondo) classification works well. However, Open Targets favours to split cardiovascular diseases into two therapeutic areas (cardiac/heart and vascular diseases, and no overall cardiovascular area), which we've already done, and ideally they'd like to have 'pericardium disease' sitting under 'heart disease', because they regard pericardial issues to be mostly cardiologists' pertinence. I guess there may be slight differences in how national health systems work, but my understanding is that e.g. pericarditis' simptoms may resemble a heart attack and warrant a trip to a cardiologist, so I'd agree with Open Targets (but I'm not a medical doctor so please correct me if you disagree). 

Would Mondo be willing to modify the disease location axiom of 'heart disease', from UBERON 'heart' to UBERON:0015410 'heart plus pericardium'? Or would you have other suggestions please?

Thanks,
Paola

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I created a PR with your suggested edit and assigned @cmungall to review - he can let us know if he has any issues.

**Comment by cmungall** [comment]
this is probably the best approach. I would have added a systematic syn for "heart/pericardial disease". I think changing the primary label is a step too far for usability?

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 
Thanks for approving my suggestion to modify the disease location axiom of 'heart disease' to  'heart plus pericardium'. That's a great help. I'm taking the liberty to re-open this ticket please to ask if you'd be willing to 
- [ ] Add that systematic synonym "heart/pericardial disease" as Chris suggested
- [ ] Perhaps add a short gloss to the definition, or an editor's comment, to clarify that pericardial diseases are included?

I think both additions would help avoid any future confusion. Just in case ;-) Thanks!
