### ISSUE TITLE
[Revise subclass]

### ISSUE THREAD

**Issue by Mohan-Shruthi** [monarch-initiative/mondo#1196]
**Mondo term (ID and Label)** MONDO:0013681 / alpha-methylacyl-CoA racemase deficiency 

**Suggested revision and reasons** The ClinGen Peroxisomal disorders gene curation expert panel recommends that the term "alpha-methylacyl-CoA racemase deficiency" (AMACR deficiency) be moved up as the parent term to "MONDO:0008967 / congenital bile acid synthesis defect 4". In other words, swap the two entities. Currently, the relationship is in the reverse order, with "alpha-methylacyl-CoA racemase deficiency" being the subclass of "congenital bile acid synthesis defect 4". This change is suggested as congenital bile acid synthesis defect is one of the outcomes of AMACR deficiency. AMACR deficiency also results in reduced pristanic acid oxidation. 

We also want to ADD to the definition of MONDO:0013681: "AMACR deficiency rarely presents as liver disease in infancy." 

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@Mohan-Shruthi 

I revised the classification, so no we have:

'rare hereditary metabolic disease with peripheral neuropathy'
-'alpha-methylacyl-CoA racemase deficiency'
--'congenital bile acid synthesis defect 4'

Is this correct?

**Comment by Mohan-Shruthi** [comment]
@nicolevasilevsky 

Yes. That's correct. This change would also reorganize the classification in the other branches, right? For ex: 
"Peroxisomal disease"
-"disorder of peroxisomal alpha-, beta- and omega-oxidation"
--"alpha-methylacyl-CoA racemase deficiency"
---"congenital bile acid synthesis defect 4"

**Comment by nicolevasilevsky** [comment]
Ah, I had not added "disorder of peroxisomal alpha-, beta- and omega-oxidation" as a superclass of 'alpha-methylacyl-CoA racemase deficiency', but I just went ahead and did that.

So now you will see that hierarchy above, yes (after the Pull Request is merged and Mondo is released)
