### ISSUE TITLE
acro-renal-ocular syndrome and acrorenoocular syndrome

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1201]
MONDO_0011812 has an exact synonym of 'acrorenocular syndrome'
and is the parent of MONDO_0019863, named acro-renal-ocular syndrome

If these should be retained as distinct entities, then perhaps the exact synonym of 'acrorenocular syndrome' should be moved from MONDO_0011812 to MONDO_0019863. I am assuming the hyphens do not matter

Or should there be a merge?
See also: https://rarediseases.info.nih.gov/diseases/9182/index  --not distinct entities
https://www.omim.org/entry/607323  --not distinct entities

**Comment by nicolevasilevsky** [comment]
these seem equivalent to me too.

note to self, add synonyms:
Okihiro syndrome GARD:0009182, OMIM:607323
