### ISSUE TITLE
Baraitser Rodeck Garner syndrome and craniosynostosis-mental retardation-clefting syndrome

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1202]
GARD ( https://rarediseases.info.nih.gov/diseases/817/index) has a record for Baraitser Rodeck Garner syndrome (MONDO_0021971).  
GARD's page  provides a link to OMIM (https://www.omim.org/entry/218650) for CRANIOSYNOSTOSIS-MENTAL RETARDATION-CLEFTING SYNDROME  (MONDO_0009041) ,  for which the only reference is authored by Baraitser, M., Rodeck, C., Garner, A..

Is it possible that MONDO_0021971 and MONDO_0009041 represent the same disorder?

**Comment by nicolevasilevsky** [comment]
@gardinfocenter

**Comment by GARDInfoCenter** [comment]
We reviewed both Baraister Rodeck Garner syndrome and craniosynostosis-mental retardation-clefting syndrome and have determined that they are indeed the same condition. Additionally, the condition does not meet our inclusion criteria, as the condition has only been reported in one family. At this time, we have decided to retire both terms from our list.

**Comment by nicolevasilevsky** [comment]
action item:
- [ ] obsolete MONDO_0021971, add term replaced by MONDO_0009041
