### ISSUE TITLE
evaluate results from OBO dashboard

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1208]
See: http://obo-dashboard-test.ontodev.com/
see report here: http://obo-dashboard-test.ontodev.com/mondo/robot_report.html

**Comment by cmungall** [comment]
http://obo-dashboard-test.ontodev.com/mondo/dashboard.html

![image](https://user-images.githubusercontent.com/50745/76264177-3bcc3100-621e-11ea-9a11-ba40d1d7b423.png)

**Comment by nicolevasilevsky** [comment]
related to #808

**Comment by nicolevasilevsky** [comment]
note to self - stopped a line 11 (fixing duplicate definitions)

**Comment by nicolevasilevsky** [comment]
@cmungall is the best approach for me to manually fix the duplicate definitions? I can do this, but it is going to take a lot of time.

**Comment by nicolevasilevsky** [comment]
there are errors for multiple_equivalent_classes, which in Mondo, I don't think are actual errors (upon first glance)

**Comment by nicolevasilevsky** [comment]
note to self - stopped a line 79 (fixing duplicate definitions)

**Comment by nicolevasilevsky** [comment]
I believe I am done fixing duplicate definitions (or I created a ticket to obsolete duplicate terms)

**Comment by nicolevasilevsky** [comment]
[ExactSynonymsSpreadsheet](https://docs.google.com/spreadsheets/d/1qdYtg_SVAsx9yVf2E6ErGHUreRyW2n7bZi8mywD4hAE/edit#gid=1922639824)

**Comment by matentzn** [comment]
I will reopen it when necessary
