### ISSUE TITLE
[Revise subclass] MONDO:0015943 eosinophilic granulomatosis with polyangiitis

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1214]
**MONDO:0015943 eosinophilic granulomatosis with polyangiitis**

"Eosinophilic granulomatosis with polyangiitis (EGPA), previously known as Churg-Strauss syndrome, is a systemic vasculitis of small-to medium vessels, characterized by asthma, transient pulmonary infiltrates, and hypereosinophilia."

Should be a subclass of
MONDO:0012105 granulomatosis with polyangiitis
"A small-vessel necrotizing vasculitis characterised by the association of inflammation of the vessel wall and peri- and extravascular granulomatosis."

On the other hand, existing subclass relationships of both terms suffer from the known Orphanet-derived issues and should be revised, see https://github.com/ebispot/efo/issues/667#issuecomment-588193841. 

Thanks,
Paola

**Comment by nicolevasilevsky** [comment]
I added the superclass of
- 'granulomatosis with polyangiitis'

and removed the following superclass of assertions:
- 'systemic inflammatory disease associated with an acquired peripheral neuropathy'
- 'non-familial rare disease with dilated cardiomyopathy'
- 'secondary glomerular disease'
