### ISSUE TITLE
Behcet's syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#122]
The primary label of Behcet's syndrome should probably be Behcet disease (disease is used much more commonly than syndrome for Behcet, and also we should in general avoid the possessive form in disease names). 

There is a misspelling in the definition, "BehC'et's", that probably results from the fact that the C has a diacritical mark that was improperly parsed (In Unicode, Latin small letter C with cedilla, U+00E7).

see:
https://www.mayoclinic.org/diseases-conditions/behcets-disease/symptoms-causes/syc-20351326

**Comment by pnrobinson** [comment]
Also, this synonym is a little off: "Morbus Behçet's Syndrome"

**Comment by nicolevasilevsky** [comment]
@cmungall I am getting a weird diff when I try to edit this:
BICB119:ontology vasilevs$ git status
On branch issue-122
nothing to commit, working tree clean
BICB119:ontology vasilevs$ git diff
diff --git a/src/ontology/mondo-edit.obo b/src/ontology/mondo-edit.obo
index 44a4b8c..5dacc38 100644
--- a/src/ontology/mondo-edit.obo
+++ b/src/ontology/mondo-edit.obo
@@ -121813,7 +121813,7 @@ property_value: confidence "1.5244851391448875" xsd:double
 
 [Term]
 id: MONDO:0007191
-name: Behcet's syndrome
+name: Behcet disease
 def: "BehC'et's disease (BD) is a chronic, relapsing, multisystemic vasculitis characterized by mucocutaneous lesions, as well as articular, vascular, ocular and central nervous system manifestations." [Orphanet:117]
 subset: ordo_disease {source="Orphanet:117"}
 synonym: "Adamantiades-Behcet disease" EXACT [DOID:13241, SCTID:310701003]
@@ -187202,7 +187202,7 @@ xref: UMLS:C0268690 {source="OMIM:277440", source="NCBI:mim2gene_medline"}
 xref: UMLS:C0342646 {source="OMIM:277440", source="MONDO:equivalentTo"}
 is_a: MONDO:0005520 {source="DC-OMIM:277440", source="NCIT:C131075"} ! rickets (disease)
 is_a: MONDO:0019642 {source="MONDO:cjm"} ! vitamin D-dependent rickets, type 2
-relationship: disease_has_basis_in_disruption_of GO:0008434 ! calcitriol receptor activity
+relationship: disease_has_basis_in_disruption_of GO:0008434
 relationship: disease_has_basis_in_dysfunction_of NCBIGene:7421 {source="mim2gene_medgen"}
 property_value: confidence "1.4999999999999996" xsd:double
 
@@ -200414,7 +200414,7 @@ xref: OMIM:600081 {source="MONDO:Leader", source="MONDO:equivalentTo"}
 xref: Orphanet:289157 {source="MONDO:subClassOf", source="OMIM:600081"}
 xref: UMLS:C1838657 {source="NCBI:mim2gene_medline", source="OMIM:600081", source="MONDO:equivalentTo"}
 is_a: MONDO:0009924 {source="ORDO:289157/btnt"} ! vitamin D-dependent rickets, type 1
-relationship: disease_has_basis_in_disruption_of GO:0030343 ! vitamin D3 25-hydroxylase activity
+relationship: disease_has_basis_in_disruption_of GO:0030343
 relationship: disease_has_basis_in_dysfunction_of NCBIGene:120227 {source="mim2gene_medgen"}
 property_value: confidence "3.3578947368421037" xsd:double
 
@@ -313678,7 +313678,7 @@ subset: ordo_group_of_disorders {source="Orphanet:308448"}
 xref: Orphanet:308448 {source="MONDO:Leader", source="MONDO:equivalentTo"}
 is_a: MONDO:0019213 {source="Orphanet:308448"} ! cerebral organic aciduria
 intersection_of: MONDO:0019052 ! inborn errors of metabolism
-intersection_of: disease_has_basis_in_disruption_of GO:0004046 ! aminoacylase activity
+intersection_of: disease_has_basis_in_disruption_of GO:0004046
 
 [Term]
 id: MONDO:0017687
@@ -313688,7 +313688,7 @@ xref: ICD10:E72.0 {source="Orphanet:308451", source="ORDO:308451/ntbt", source="
 xref: Orphanet:308451 {source="MONDO:Leader", source="MONDO:equivalentTo"}
 is_a: MONDO:0019216 {source="Orphanet:308451"} ! inborn disorder of amino acid absorption and transport
 intersection_of: MONDO:0019052 ! inborn errors of metabolism
-intersection_of: disease_has_basis_in_disruption_of GO:0015804 ! neutral amino acid transport
+intersection_of: disease_has_basis_in_disruption_of GO:0015804
 
 [Term]
 id: MONDO:0017688
@@ -372525,8 +372525,8 @@ name: vitamin D-dependent rickets
 synonym: "VDDR" EXACT []
 xref: SCTID:68295002 {source="MONDO:equivalentTo"}
 intersection_of: MONDO:0005520 ! rickets (disease)
-intersection_of: disease_has_basis_in_disruption_of GO:0033280 ! response to vitamin D
-relationship: disease_has_basis_in_disruption_of GO:0070561 ! vitamin D receptor signaling pathway
+intersection_of: disease_has_basis_in_disruption_of GO:0033280
+relationship: disease_has_basis_in_disruption_of GO:0070561
 
 [Term]
 id: MONDO:0024300

**Comment by nicolevasilevsky** [comment]
I updated the label and def @pnrobinson. Peter, you said the synonym is a bit off, do you suggest revising it to something else? I can report it to NCIt too.

**Comment by nicolevasilevsky** [comment]
@pnrobinson I updated the label, let me know if you would like the synonym to be revised. Closing this.
