### ISSUE TITLE
Correction to term inherited genetic disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#123]
Suggestion about term inherited genetic disease [MONDO:0003847]
Current definition: A disease that is caused by genetic modifications where those modifications are inherited from a parent's genome.
Current comment: Usage note: this is intended only for diseases with an inherited genetic etiology. Somatic genetic mutations are excluded. Some ontologies use the term 'genetic disease' in the sense of inherited disorders only, we are here careful to distinguish.
Current synonym list: Molecular Disease;Genetic Disorder;familial disorder;Hereditary Disease;Inherited Disease;Hereditary Diseases;Genetic Condition;hereditary disease;inborn disorder;Molecular Disease;inherited disease;genetic disease;Genetic Condition;Genetic Disorder

My suggestion: 
This term may lead to logical inconsistencies. In many cases, the same disease can be caused by
an inherited mutation or from a de novo (spontaneous) mutation. An example is neurofibromatosis type 1. 
Therefore, it is unclear whether NF1 should be classified as a subclass of this term or not.

**Comment by cmungall** [comment]
Yes, the current placement of NF1 is not correct (in addition to potentially being de-novo, it can also be somatic). This could be moved up to 'genetic disease'.

What if we ignore de-novo vs hereditary and split genetic into somatic vs germline? It does seem useful to broadly separate neoplasms from mendelian diseases (with mendelian diseases that cause cancer being germline).

The real intent here is to capture what is meant when a disease is named "familial X" or "hereditary X", where we want to axiomatize the difference between this and X. We know that the name is shorthand and in many cases the mutation can be de-novo. It may be sloppy to reinforce the terminological practice as a logical axiom, you could say we're axiomatizing the name rather than the clinical reality... but it is incredibly useful to have this level of axiomatization, we've caught a lot of errors and inconsistencies this way.

**Comment by pnrobinson** [comment]
There are also somatic versions of genetic diseases, e.g., segmental NF1
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4293382/
These distinctions are not the usual ones according to which patients would be sent to different physicians. 
I realize it may be useful in order to catch mistakes, but I do not think it will lead to a hierarchy that will be appealing to most MDs. Maybe this is a topic for a skype rather than issues.

**Comment by cmungall** [comment]
Here's another example of something that gets flagged (from ORDO):

![image](https://user-images.githubusercontent.com/50745/38169192-5723df46-3518-11e8-9d42-686168e2b2da.png)

the beta-globin form is classified as acquired. I suppose it could be argued that secondary diseases could be acquired as a result of inherited primary disease... but seems dubious.

Point taken though. If this is going to make things unappealing to MDs we can filter this in the release. I'd rather first do a catalog of all cases where this is a problem though, to see how broadly the issue permeates.

**Comment by cmungall** [comment]
OK, just to be pedantic, should the name of HP:0000005 be changed?

```
  is_a HP:0000005 ! Mode of inheritance [DEF: "The pattern in which a particular genetic trait or disorder is **passed from one generation to the next**."]
   is_a HP:0000006 ! Autosomal dominant inheritance [DEF: "A mode of inheritance that is observed for traits related to a gene encoded on one of the autosomes (i.e., the human chromosomes 1-22) in which a trait manifests in heterozygotes. In the context of medical genetics, an autosomal dominant disorder is caused when a single copy of the mutant allele is present. Males and females are affected equally, and can both transmit the disorder with a risk of 50% for each child of inheriting the mutant allele."]
    is_a HP:0001444 ! Autosomal dominant somatic cell mutation ***  [DEF: "Being related to a **de novo variant** that occurs in a single cell in developing somatic tissue. The cell is the progenitor of a population of identical mutant cells, all of which have descended from the cell that mutated. Clinical manifestations depend on the identity and proportion of affected cells in the body."]
```

I guess we can say that inherited is not exclusively meoitic.. but I don't think that's the intent. :-)

**Comment by pnrobinson** [comment]
dont understand--why is thalassemia (blood disease) being classified under pituitary and how did logical reasoning help us to figure this out?
The motivation for the HP hierarchy is that the mutation can be inherited as AD once it occurs as de novo....yes but it is difficult to model this.

**Comment by mellybelly** [comment]
RE mode of inheritance- we should harmonize with GENO and add XREF equivalence/taxon specific subclass axioms (or mireot). @mbrush can you look into this? We need for all organisms

**Comment by cmungall** [comment]
> dont understand--why is thalassemia (blood disease) being classified under pituitary and how did logical reasoning help us to figure this out

See #120 for Protege explanations. We caught it due to the GCI disjointness axiom.

Note the screenshot above is Orphanet, do you want to open a ticket on the Orphanet tracker?

**Comment by cmungall** [comment]
Another example #134 (see also https://github.com/Orphanet/ORDO/issues/4)

**Comment by nicolevasilevsky** [comment]
this term has been renamed, so I think this can be closed
