### ISSUE TITLE
revise superclasses: MONDO:0019170 'polyarteritis nodosa' 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1241]
From @paolaroncaglia on #834  
(Creating a new ticket for myself, as that other ticket has so many comments!)

Making a note that MONDO:0019170 'polyarteritis nodosa' also seems to have some questionable superclasses. Full list:
a) arteritis [ok based on def]
b) systemic inflammatory disease associated with an acquired peripheral neuropathy [probably not ok, unless the disease is always associated with an acquired peripheral neuropathy; otherwise that's just a symptom]
c) neurovascular disease [not ok; symptom]
d) secondary glomerular disease [not ok; symptom]
Note that the term has exactMatch not only with ORDO but also with other resources. Thanks.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Thanks for opening this ticket. I'll add the EFO label to keep track. Note for self: EFO action items have already been carried out (see https://github.com/EBISPOT/efo/issues/667#issuecomment-593952714).
