### ISSUE TITLE
[Obsolete] halo nevus or halo nevi

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1259]
**Mondo term (ID and Label)**
MONDO_0009322 and MONDO_0006778

**Reason for deprecation**
seem to differ only in singular vs. plural

**Suggested replacement or term to consider**
probably keep the singular form

**Comment by nicolevasilevsky** [comment]
From GARD:
the change to “Halo nevus” makes sense because is mostly used in the literature.  However, for GARD this term may be retired because is not rare nor genetic.
