### ISSUE TITLE
[Obsolete] MONDO_0003195	peritoneal serous adenocarcinoma'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1263]
**Mondo term (ID and Label)**
MONDO_0003195	peritoneal serous adenocarcinoma'

**Reason for deprecation**
duplicate

**Suggested replacement or term to consider**
MONDO_0006386	primary peritoneal serous adenocarcinoma'

**Comment by pnrobinson** [comment]
These are not 100% the same, ,I think, see
http://www.ccij-online.org/article.asp?issn=2278-0513;year=2015;volume=4;issue=4;spage=551;epage=554;aulast=Heda

I think that peritoneal serous adenocarcinoma can also refer to other tissues of origin.

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson!
