### ISSUE TITLE
[Obsolete] MONDO_0001676	erythropoietic protoporphyria'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1264]
**Mondo term (ID and Label)**
MONDO_0001676	erythropoietic protoporphyria'

**Reason for deprecation**
duplicate

**Suggested replacement or term to consider**
MONDO_0008319	protoporphyria, erythropoietic'

**Comment by cmungall** [comment]
merge is not appropriate here.

Always watch out for prototype errors!

MONDO:0008319 should be EPP1, a gene-specific form, as it is equivalent to an omim

**Comment by nicolevasilevsky** [comment]
Thanks Chris - I re-did the edits in #1456
