### ISSUE TITLE
[Obsolete] MONDO_0006440	systemic mastocytosis with associated clonal hematological non-mast-cell lineage disease'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1270]
**Mondo term (ID and Label)**
**Note- I am suggesting obsoleting two terms**
- [x] MONDO_0006440	systemic mastocytosis with associated clonal hematological non-mast-cell lineage disease'
(EFO:1000559)

- [x] MONDO_0003148 SM-AHNMD

**Reason for deprecation**
duplicate
comment says: This is a place-holder for Orphanet term ORDO_98849 which is not currently part of the rare genetic disorders imported from ORDO2 (as of January 2016).

**Suggested replacement or term to consider**
MONDO_0020332	systemic mastocytosis with an associated clonal hematologic non-mast cell lineage disease'

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Could you please confirm that you received no objection to the obsoletions above?
If so, I'll go ahead with https://github.com/EBISPOT/efo/issues/734. Thanks.

**Comment by nicolevasilevsky** [comment]
Confirmed, there were no objections.
