### ISSUE TITLE
[Obsolete]Patau/Trisomy 13

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1272]
**Mondo term (ID and Label)**
MONDO_0001333 /Patau vs trisomy 13/MONDO_0018068

**Reason for deprecation**
GARD reports these as equivalent  https://rarediseases.info.nih.gov/diseases/7341/trisomy-13
GHR reports these as equivalent: https://ghr.nlm.nih.gov/condition/trisomy-13
NHS reports as equivalent: https://www.nhs.uk/conditions/pataus-syndrome/
**Suggested replacement or term to consider**

**Comment by nicolevasilevsky** [comment]
see [spreadsheet](https://docs.google.com/spreadsheets/d/1s-jaBDNbJmQtv38uPrXOy7yiKZxbYJ940mfZeUt-T8U/edit#gid=510128657)

**Comment by nicolevasilevsky** [comment]
From GARD:
We already have “trisomy 13” as the main term, but we kept Patau syndrome as a synonym because it is widely used too.
