### ISSUE TITLE
[Obsolete] MONDO_0003500 squamous cell bile duct carcinoma'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1274]
MONDO_0003500	squamous cell bile duct carcinoma'

replace with: 
MONDO_0006203	extrahepatic bile duct squamous cell carcinoma'

reason:
duplicate

**Comment by pnrobinson** [comment]
Not synonyms, see
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6187985/

**Comment by nicolevasilevsky** [comment]
Thank you for the feedback @pnrobinson!
