### ISSUE TITLE
MONDO_0003549 adenosquamous bile duct carcinoma'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1275]
MONDO_0003549	adenosquamous bile duct carcinoma'

replace with:
MONDO_0006202	extrahepatic bile duct adenosquamous carcinoma'

reason:
duplicate

**Comment by cmungall** [comment]
We should be careful here. What is the reason for thinking these are duplicates?

Based on the label and the definition (both text and logical), these are not duplicates. extrahepatic bile dict is a narrower concept than bile duct.

this whole area could do with some review

**Comment by nicolevasilevsky** [comment]
The text definitions are duplicates, they came up in the ROBOT report.

MONDO_0003549 'adenosquamous bile duct carcinoma' comes from DO and xrefs NCIT:C5778 as a directSiblingOf. Such a term does not exist in NCIT.

MONDO_0006202 'extrahepatic bile duct adenosquamous carcinoma' is equivalent to NCIT:C5778

From my google search, I'm not sure that such a term as 'adenosquamous bile duct carcinoma' exists, I think it is intended to be extrahepatic bile duct. NCIT did review this when I sent out my obsoletion email and okay'd it.

**Comment by nicolevasilevsky** [comment]
I don't feel strongly though - if you think we should retain MONDO_0003549 'adenosquamous bile duct carcinoma', I will update the text def.

**Comment by nicolevasilevsky** [comment]
- [ ] go ahead and merge, keep broad synonyms for 'adenosquamous bile duct carcinoma'
