### ISSUE TITLE
update OMIM and Orphanet ingest

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1283]
in the last meeting, we discussed that updating the OMIM and Orphanet ingests are high priority.

As part of this process, we need to ensure the pipeline for updating OMIM and Orphanet is properly documented so it is runnable by @ShahimEssaid/ @wdduncan / @nicolevasilevsky / @matentzn 

- [x] @cmungall update OMIM source to latest version
- [x] @cmungall update Orphanet source to latest version

Ultimately we want to add documentation to [Mondo developers guide](https://mondo.readthedocs.io/en/latest/), but this is not ready yet.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 
(cc @zoependlington )
> in the last meeting, we discussed that updating the OMIM and Orphanet ingests are high priority.
> 
> As part of this process, we need to ensure the pipeline for updating OMIM and Orphanet is properly documented so it is runnable by @ShahimEssaid/ @wdduncan / @nicolevasilevsky / @matentzn
> 
>     * [ ]  @nicolevasilevsky add documentation to [Mondo developers guide](https://mondo.readthedocs.io/en/latest/)
> 
>     * [ ]  @cmungall update OMIM source to latest version
> 
>     * [ ]  @cmungall update Orphanet source to latest version

Wrt the last item, should I then wait before looking at the list/spreadsheet in https://github.com/monarch-initiative/mondo/issues/834? To avoid looking into terms that may potentially not be in Orphanet any more, or that may not make it into Mondo? Asking as I'm not sure about your strategy/procedure/timeline. Please ignore me if this is not relevant. Thanks and a safe weekend to all!

**Comment by nicolevasilevsky** [comment]
Hi @paolaroncaglia there isn't a timeline in place yet to update Orphanet, it probably will be delayed for a bit due to other competing priorities and all the other craziness.

**Comment by nicolevasilevsky** [comment]
If you need this more urgently, let me know.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky Thanks. I commented here https://github.com/monarch-initiative/mondo/issues/834#issuecomment-604560302, and we can catch up at our next EFO-Mondo meeting, or sooner if necessary.

**Comment by nicolevasilevsky** [comment]
@cmungall Is it correct that Orphanet was updated to the latest version in the last release? Could we check off that box above?

**Comment by nicolevasilevsky** [comment]
This can be closed
