### ISSUE TITLE
propagate NCIT_P334 (ICD-0) property to xref

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#129]
See: https://github.com/monarch-initiative/monarch-app/issues/1567

**Comment by cmungall** [comment]
@balhoff @jmcmurry what prefix for ICD-0? `ICD0`?

**Comment by balhoff** [comment]
It's a capital 'O'. Could the prefix be `ICD-O` or `ICD-O-3`? I'm not sure how the codes do or don't change across versions.

**Comment by monicacecilia** [comment]
We still have some work to do to improve ICDO alignments, and we need a better strategy for updating our ICDO x-refs. This issue references a _workaround_ way to import ICDO references from NCIt. We now have documentation and a pipeline that will eventually take us to address this issue again (eventually). Let's close for now and work on it when it surfaces again.
