### ISSUE TITLE
review: psychiatric and mental disorders

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#130]
A lot of existing resources seem to handle this poorly, and classify a lot of things as psychiatric that are not (or were considered this way historically). We need a review of this area

**Comment by cmungall** [comment]
Example:

![image](https://user-images.githubusercontent.com/50745/38594613-e45112fe-3cfb-11e8-9247-646afb842a8b.png)

when combined with

![image](https://user-images.githubusercontent.com/50745/38594632-f77684d6-3cfb-11e8-9365-8d55ddb8b286.png)

makes all pain disorders neuroses

**Comment by nicolevasilevsky** [comment]
pain disorder has been obsolete. I converted this to a discussion
