### ISSUE TITLE
Synonym Type ABBREVIATION is not declared in obo

### ISSUE THREAD

**Issue by althonos** [monarch-initiative/mondo#132]
Hi there,

it seems the `mondo.obo` does not declare the `ABBREVIATION` synonym type, causing some picky OBO parsers to fail. I couldn't find anywhere in the actual specification whether or not having every synonym types defined in the headers is required, but the OBO Flat Format Guide v1.4 does go in that direction.

Concerned terms are `MONDO:0021203` and `MONDO:0005404`, and this could be resolved by simply adding:
```
synonymtypedef: ABBREVIATION "ABBREVIATION" EXACT
```
to the headers.

I didn't see any other missing synonymtypedefs otherwise.

Actual issue was reported in althonos/pronto#17 thanks to @genomics-geek.

**Comment by genomics-geek** [comment]
@cmungall @althonos - Thanks for addressing this issue!

**Comment by cmungall** [comment]
Thanks for the bug report! Added a sparql check (which will be rolled into ROBOT so other ontologies will benefit) so won't happen again. Hope to have new release out in a few days
