### ISSUE TITLE
[NTR] Should we add subclasses of COVID-19?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1341]
**name:** pneumonia caused by SARS-CoV-2
**def:** A pneumonia caused by infection with SARS-CoV-2.
**synonym:** pneumonia caused by SARS-CoV-2SARS-CoV-2" 
**synonym:** pneumonia caused by SARS-CoV-2
**synonym:** pneumonia caused by severe acute respiratory syndrome coronavirus 2

**name:** upper respiratory tract infection caused by SARS-CoV-2
**def:** An upper respiratory tract infection caused by infection with SARS-CoV-2. 
**synonym:** upper respiratory tract infection caused by SARS-CoV-2
**synonym:** upper respiratory tract infection caused by severe acute respiratory syndrome coronavirus 2

(_labels have been edited per @maglott's comment below_)

@mellybelly @pnrobinson @ShahimEssaid @cmungall @jmcmurry

**Comment by pnrobinson** [comment]
Is "2019 novel coronavirus" actually the written out name? I thought it was "coronavirus disease of 2019" (Question -- I do not know but it sounds odd)

Whether or not to make subsets like this gets back to the lumper/splitter debate. One argument against splitting is that it is unlikely that a patient "only" has pneumonia etc, since the virus can be at multiple body sites. An argument for splitting is that some studies may want to have groupings like this.

**Comment by nicolevasilevsky** [comment]
I just updated the primary label to COVID-19, but looks like 'coronavirus disease 2019' should be the exact synonym. I'll fix this.

https://www.cdc.gov/coronavirus/2019-ncov/downloads/2019-ncov-factsheet.pdf

**Comment by cmungall** [comment]
The more general question is: do we add a DP for disease classified by sequelae? does this lead to ICD10?

**Comment by nicolevasilevsky** [comment]
there are a few examples of this in Mondo already, for example:
'pneumonia caused by chlamydia'
'pneumonia caused by gram negative bacteria'
'bacterial meningitis caused by gram-negative bacteria'
'cytomegalovirus pneumonia'

**Comment by nicolevasilevsky** [comment]
We have this pattern in Mondo:

MONDO:patterns/specific_infectious_disease_by_agent

**Comment by maglott** [comment]
Given that a name as been assigned to this virus, should SARS-CoV-2 be used instead for the virus?
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=2697049

**Comment by nicolevasilevsky** [comment]
@maglott Good point, yes, if we decide we want to add these terms, I think we should use the NCBI taxon name.

**Comment by dnahotline** [comment]
SARS-CoV-2 is the virus and COVID-19 is the disease.

**Comment by mellybelly** [comment]
@cgchute was involved in the original naming, can you comment here?

**Comment by nicolevasilevsky** [comment]
@dnahotline can you please clarify?

The suggested terms above are:
[disease] caused by [virus name]
[disease] = pneumonia or upper respiratory tract infection

Are you suggesting a revision to those disease names?

**Comment by nicolevasilevsky** [comment]
Currently, the Mondo disease class is named COVID-19 (MONDO_0100096). This will be available in the next release.

**Comment by cgchute** [comment]
I agree with the above statement "SARS-CoV-2 is the virus and COVID-19 is the disease."  The disease was named by WHO to mean nothing more than the SARS variant that caused the "COrona VIrus Disease" starting in 2019.  They had an allergy to SARS, and specific geographical references like MERS.

**Comment by cgchute** [comment]
I am not sure what MONDO considers a class.  The class in my mind is corona virus disease, that would include SARS, MERS, and COVID-19, and probably others.  The leaf rubric is COVID-19.

**Comment by nicolevasilevsky** [comment]
@cgchute that is the question here. :) Whether we want to add `pneumonia caused by SARS-CoV-2` and `upper respiratory tract infection caused by SARS-CoV-2` as new classes.

You bring up a good point - SARS and MERS should be subclasses of MONDO_0005719 'coronavinae infectious disease', right? Aka siblings of COVID-19?

It doesn't look like we have MERS in Mondo, from what I can tell. I'll create a new ticket to add that.

thanks!

**Comment by dnahotline** [comment]
Looking forward to futher outbreaks I like how Chris puts it. There will be lots of COVID (SARS, MERS etc) from many types of corona viruses. 
WRT to disease it seems ARDS should be there. Not all ARDS is caused by COVID-19, nor is all pneumonia or URT infection.

**Comment by nicolevasilevsky** [comment]
we do have ARDS:
MONDO_0006502 'adult respiratory distress syndrome'

**Comment by dnahotline** [comment]
I mean we are not "looking forward" with happiness to other outbreaks...it's just that we know future outbreaks are coming. Just like people knew this one was coming. Especially now that SARS-Cov-2 is spreading in so many areas with lots of different animals that can be co-infected and have chances to recombine. Thus, there should be room in this naming strategy to allow new coronaVs and decendents of the current transmission to be classified.

**Comment by dnahotline** [comment]
> we do have ARDS:
> MONDO_0006502 'adult respiratory distress syndrome'

It is Acute resp distress syndrome, not adult

**Comment by pnrobinson** [comment]
ARDS was pretty common before COVID and we definitely need a MONDO term for it.
There are subclassifications, e.g. 
https://www.ncbi.nlm.nih.gov/pubmed/25393701
I am not aware of whether any classifications are generally accepted, but we might want to cite this paper somewhere

**Comment by jmcmurry** [comment]
We should also make room for the distinction between viral pneumonia and that it increases susceptibility to bacterial superinfection, and that is often the kiss of death.

**Comment by nicolevasilevsky** [comment]
> It is Acute resp distress syndrome, not adult

Acute respiratory distress syndrome and ARDS are a synonym, and it is equivalent to the NCIt term: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C3353

**Comment by nicolevasilevsky** [comment]
I suggest we make Acute respiratory distress syndrome the primary label and make adult respiratory distress syndrome a narrow synonym.

**Comment by nicolevasilevsky** [comment]
> Not all ARDS is caused by COVID-19, nor is all pneumonia or URT infection.

@dnahotline Right, and we do have terms in Mondo for pneumonia and URT infections already. The question on this ticket is, should we create new diseases classes that are 'a disease caused by a specific infection'. We do have terms for pneumonia and upper respiratory tract infection, but do we want to add a term for 'pneumonia caused by SARS-CoV-2' and 'URT infection caused by SARS-CoV-2?

The issue with this, is if we did this for every potential infectious agent, we'd end up with a massive, unwieldy ontology. But since this is such a special and current use case, I wonder if we would want this.

But based on everyone's comments, I am thinking maybe not.

**Comment by nicolevasilevsky** [comment]
> We should also make room for the distinction between viral pneumonia and that it increases susceptibility to bacterial superinfection, and that is often the kiss of death.

@jmcmurry are you suggesting a specific action item is for Mondo?

We could edit the text definition of MONDO_0006012 'viral pneumonia' to read:

Inflammation of the lung parenchyma that is caused by a viral infection. _Viral pneumonia often increases susceptibility to bacterial superinfection and increased morbitity._

If you want to add this, could you please give me a reference for this?

**Comment by nicolevasilevsky** [comment]
I am going to close this ticket, as my impression is that we don't want to add these new subclasses. Please reopen if there are any outstanding action items or if any action is needed. Thanks for your input everyone!
