### ISSUE TITLE
dystonia from GeneReviews, take 2

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1351]
https://www.ncbi.nlm.nih.gov/books/NBK1155/table/dystonia-ov.T.nomenclature_system_for_in/?report=objectonly

1. add the terms in the column 'New Designation & Phenotypic Subgroup' as synonyms
2. move DYT-KMT2B under isolated dystonia
3. check all the other relationships 
--I checked dopa-responsive dystonia and it looks OK

**Comment by nicolevasilevsky** [comment]
Hi @maglott I think all these synonyms have already been added.

DYT-KMT2B is a synonym for MONDO_0100016 'early-onset generalized dystonia', which is a child of 'generalized isolated dystonia'.

Would you mind checking again and let me know if other action is needed or if I can close this ticket?

Thanks!

**Comment by nicolevasilevsky** [comment]
Hi @maglott gentle reminder that there is an open question above

**Comment by nicolevasilevsky** [comment]
Closing, please reopen if still needed.
