### ISSUE TITLE
[NTR] MERS

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1354]
**Preferred term label:**
Middle East Respiratory Syndrome 

**Synonyms**
MERS

https://www.cdc.gov/coronavirus/mers/index.html

related to https://github.com/monarch-initiative/mondo/issues/1341

**Comment by nicolevasilevsky** [comment]
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C128424

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Making a note here that Mondo:NEW 'Middle East Respiratory Syndrome' (synonym: MERS) is needed in EFO too. I see this is already marked as high priority. Thanks!
