### ISSUE TITLE
[NTR] subclasses of ARDS ?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1359]
Should we add subclases of ARDS (MONDO_0006502 'adult respiratory distress syndrome')?

mild ARDS 
def: PaO2/FiO2 of 201–300 mmHg

moderate ARDS 
def: PaO2/FiO2 of 101–200 mmHg is 

severe ARDS 
def: PaO2/FiO2 ≤100 mmHg is 

Source: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6709677/

**Comment by nicolevasilevsky** [comment]
this paper divides the subclasses into four groups:
https://www.ncbi.nlm.nih.gov/pubmed/25393701
(from @pnrobinson, thanks!)

![image](https://user-images.githubusercontent.com/6722114/77973278-80406f00-72a8-11ea-949e-5cd2fca3635c.png)

**Comment by monicacecilia** [comment]
Dear @nicolevasilevsky - please note: _acute_ (not _adult_ respiratory distress syndrome).

**Comment by nicolevasilevsky** [comment]
See related ticket: https://github.com/monarch-initiative/mondo/issues/1360

**Comment by nicolevasilevsky** [comment]
@pnrobinson @cmungall do we want to add these terms?

**Comment by pnrobinson** [comment]
There are multiple ways of subclassing ARD. And each of these has a cross product with an etiology. It would be good to discuss and document a strategy for this!
