### ISSUE TITLE
Relabel: adult respiratory distress syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1360]
**Mondo term (ID and Label):**
adult respiratory distress syndrome

**Suggested new label:**
Make Acute respiratory distress syndrome the primary label and make adult respiratory distress syndrome a narrow synonym.

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C3353

 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6709677/

@pnrobinson @mellybelly @DNAhotline @jmcmurry  - please let me know if you have any objections. I will try to get this change in for the April release (hopefully within the next week).

Related to #1341

**Comment by nicolevasilevsky** [comment]
@ShahimEssaid and I discussed this.

It appears that the respiratory distress classes in Mondo should be reviewed.

**Comment by nicolevasilevsky** [comment]
I am not going to take action on this before the April release.

**Comment by cmungall** [comment]
I think this is straightforward, the adult form should be a subclass; add childhood as a sib?

the ordo equiv should go with the adult subclass:
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http://www.orpha.net/ORDO/Orphanet_70578
