### ISSUE TITLE
[Obsolete] MONDO_0001046 'imperforate anus'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1364]
**Mondo term (ID and Label)**
MONDO_0001046 'imperforate anus'

**Reason for deprecation**
There is a comment on this term: Consider obsoleting as dupe with HPO

**Suggested replacement or term to consider**
None

This term is in a lot of disease ontologies though, I don't think we should obsolete it, I think we should remove this comment.

cc @pnrobinson @cmungall

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/pull/1229

**Comment by pnrobinson** [comment]
The etiology of Imperforate anus is not known in many cases. It is better conceptualized as a phenotypic feature (https://en.wikipedia.org/wiki/Imperforate_anus)

However, there are cases where there is no known disease and whether the feature occurs in isolation. Maybe we want to have a disease term for this kind of situation. Can we ask a pediatric surgeon about this?

**Comment by nicolevasilevsky** [comment]
Do we know any pediatric surgeons? :)

**Comment by nicolevasilevsky** [comment]
@ahamosh - do you think this is a valid disease term or do you think it should be retired/obsoleted?

**Comment by ahamosh** [comment]
It is exactly as Peter described.  It should be a feature, but if it is in isolation and no disease or syndrome is identified, then it could be isolated imperforate anus.  You can't really eliminate it...  I am NOT a pediatric surgeon.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh. I'll close this ticket and we'll keep the term.
