### ISSUE TITLE
MAUMENEE CORNEAL DYSTROPHY

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1368]
OMIM represents  this under CORNEAL DYSTROPHY, POSTERIOR POLYMORPHOUS, 1; PPCD1;
https://www.omim.org/entry/122000

GARD represents this under https://rarediseases.info.nih.gov/diseases/6196/corneal-endothelial-dystrophy-type-2

https://en.wikipedia.org/wiki/Congenital_hereditary_endothelial_dystrophy says Maumenee is equivalent to 'CHED' not PPCD1 , with CHED formerly having been CHED2.

Arizona State ( https://disorders.eyes.arizona.edu/category/alternate-names/maumenee-corneal-dystrophy) PPCD1, citing OMIM.  

Does anyone know which, if any of these,  is correct?

**Comment by nicolevasilevsky** [comment]
In Mondo, there is an annotation on the synonym (Maumenee corneal dystrophy) to 'posterior polymorphous corneal dystrophy 1' that says the synonym is to be removed from public release but maintained in the edit version as a record of external usage.

So it seems that Mondo does not think Maumenee corneal dystrophy is a correct synonym for 'posterior polymorphous corneal dystrophy 1'.

Maumenee corneal dystrophy is a synonym for MONDO_0009019 'congenital hereditary endothelial dystrophy of cornea', which seems consistent with GARD and Wikipedia.

The [GARD class](https://rarediseases.info.nih.gov/diseases/6196/corneal-endothelial-dystrophy-type-2) is an equivalent term for MONDO_0009019 'congenital hereditary endothelial dystrophy of cornea'

cc @ahamosh

**Comment by nicolevasilevsky** [comment]
to do:

- [ ] delete VSX1 from'posterior polymorphous corneal dystrophy 1'
- [ ] Maunmenee is a synonym of type 1 (per the Mondo call/conversation with Peter)
