### ISSUE TITLE
[Obsolete] Salt and pepper developmental regression syndrome, also known as Amish infantile epilepsy syndrome

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1372]
**Mondo term (ID and Label)**
GM3 synthase deficiency, MONDO_0018274
Amish infantile epilepsy syndrome, MONDO_0012189
salt and pepper syndrome, MONDO_0018275
**Reason for deprecation**
OMIM states: Salt and pepper developmental regression syndrome, also known as Amish infantile epilepsy syndrome
SNOMEDCT_US (722762005) and UMLS (C1836824) equate Ganglioside GM3 synthase deficiency and Amish infantile epilepsy syndrome 

**Suggested replacement or term to consider**
I don't know if there are any other manifestations of GM3 deficiency, but wonder if there should be some consolidation here.

**Comment by maglott** [comment]
Orphanet has 3 records:
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=370938
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=370933
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=171714

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet it seems like OMIM combines all of these as one disease. Do you think these should be combined, or do you prefer to keep these as three separate diseases?

**Comment by nicolevasilevsky** [comment]
From GARD:
This term “groups” both Amish infantile epilepsy syndrome and salt and pepper syndrome.  Reading the papers described with this syndrome it does not make sense to have these separated.  We already have “GM3 synthase deficiency”.

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet @annieolry @Orphanet 
do you have any objections to merging these three terms?
Thanks!

**Comment by ana-rath-orphanet** [comment]
Hello, Orphanet has already deprecated ORPHA:370938 and ORPHA:171714 to ORPHA:370933.
It is both reflected in the website and in the nomenclature files.

I don't know which version are you looking at?

Cheers

Ana
