### ISSUE TITLE
[Revise logical def] MONDO:0100096 '2019 novel coronavirus infection' and anosmia/ageusia

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1373]
**MONDO:0100096 '2019 novel coronavirus infection'**

The disease has been associated with anosmia and/or ageusia (affected senses of smell and taste). I found 3 papers on PubMed, 5 on bioRxiv, plus 2 reports from US and UK medical societies. The association is not observed in all documented cases, and is not exclusive to covid. However, I'm wondering if capturing it might be beneficial for data analysis:

MONDO:0100096 '2019 novel coronavirus infection'
disease has feature
HP:0000458 'Anosmia' 

The disease association with ageusia seems less well documented. In case, the HP term HP:0000223 'Abnormality of taste sensation' could be used (and possibly added a synonym of "ageusia" in HP).
=> UPDATE: Nicole created an exact term now, HP_0041051> (Ageusia) (see https://github.com/obophenotype/human-phenotype-ontology/issues/5547)

@matentzn confirmed that it would be acceptable to use 'disease has feature' even if the disease doesn't _always_ have that feature. That said, I'll go with your decision. Thanks!

P.S. Tagging as 'high priority' in case I'm still in time for the coming release :-)

**Comment by nicolevasilevsky** [comment]
We just missed getting this in for the April release. This seems okay to me, I'll do this. 

@cmungall please let us know if you have any objections, thanks!

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia see: https://github.com/obophenotype/human-phenotype-ontology/issues/5547

would you mind sharing the PMIDs and links to the papers you found for these? I'll xref them on the Mondo axioms.

Thank you!

**Comment by cmungall** [comment]
Yes go ahead and add phenotypes for now, but wait for my PR which touches covid-19

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 

> @paolaroncaglia see: [obophenotype/human-phenotype-ontology#5547](https://github.com/obophenotype/human-phenotype-ontology/issues/5547)

Thanks for createing a new HP term for ageusia!

> would you mind sharing the PMIDs and links to the papers you found for these? I'll xref them on the Mondo axioms.

PMID:32240279 ("Isolated sudden onset anosmia in COVID-19 infection. A novel syndrome?")
PMID:32237238 ("Anosmia and ageusia: common findings in COVID-19 patients.")
PMID:32215896 ("The Covid-19 pandemic and otolaryngology: What it comes down to?") (in German with abstract in English)

bioRxiv 2020.03.25.009084; doi: https://doi.org/10.1101/2020.03.25.009084 ("Non-neural expression of SARS-CoV-2 entry genes in the olfactory epithelium suggests mechanisms underlying anosmia in COVID-19 patients")
This and 5 more hits in bioRxiv as of today searching for "covid anosmia" ("covid ageusia" retrieves 2 in the same set) 

As for reports from medical societies, this NYT article quotes warnings around anosmia symptoms released by ENT UK (Ear, Nose and Throat surgery) and the American Academy of Otolaryngology - not sure if you need the exact links, so I'll stick with the news article for now: https://www.nytimes.com/2020/03/22/health/coronavirus-symptoms-smell-taste.html

Thanks,
Paola

**Comment by nicolevasilevsky** [comment]
You're the best, thanks @paolaroncaglia!
