### ISSUE TITLE
relabel Native American Myopathy and Athabaskan brainstem dysgenesis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1377]
From Gioconda Alyea(NIH/NCATS): I would like to let you know that we had make changes in the main terms in the following diseases: (we decided to do this due to the current COVID-19 situation and taking in consideration WHO recommendations for naming infectious diseases (link) to “avoid causing offense to any cultural, social, national, regional, professional or ethnic groups).
 
1.Native American Myopathy changed to STAC3 Disorder.  Justification for the change:
 
It refers to a group or race
The name itself is a misnomer as it had been originally identified in members of Native American populations but has since been identified in numerous other populations worldwide
A 2019 Gene Review article instead uses the primary name STAC3 Disorder
 
2. Athabaskan brainstem dysgenesis was changed to “HOXA1-related syndromes”.  Justification for the change:
It refers to a group Athabaskan brainstem dysgenesis is also the primary name used by MONDO and Orphanet
A 2013 NORD Article instead uses the primary name Human HOXA1 Syndromes

**Comment by maglott** [comment]
https://omim.org/entry/255995 uses MYOPATHY, CONGENITAL, BAILEY-BLOCH; MYPBB

**Comment by nicolevasilevsky** [comment]
I went with the OMIM label for MONDO_0009722 (I relabeled Native American Myopathy to Bailey-Bloch congenital myopathy and added STAC3 Disorder as a synoonym.
