### ISSUE TITLE
MONDO_0033766 is declared in the current owl file without any content

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1379]
**Mondo term (ID Label)**

    

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/MONDO_0033766"/>
    

    

**Bug/Typo/Error description**
Is this valid?

**Comment by nicolevasilevsky** [comment]
this seems like a bug! Ii will investigate

**Comment by nicolevasilevsky** [comment]
This class has one child, MONDO_0015289 'infectious epithelial keratitis', which I think is supposed to be a child of MONDO_0015288 'herpes simplex virus keratitis' (this how it is modeled in [Orphanet](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_137586&viewMode=All&siblings=false). 

I think the action item is to reclassify MONDO_0015289 'infectious epithelial keratitis' and obsolete MONDO_0033766. Not sure how it got in there.

**Comment by nicolevasilevsky** [comment]
@ShahimEssaid I started a work on a branch but something is really weird. I am hoping we can work on this together.

the branch is issue-1379
