### ISSUE TITLE
Question about GARD term: amyloidosis nodular localized cutaneous'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#139]
Is this term: MONDO_0022446 'amyloidosis nodular localized cutaneous' (GARD:0010562) the same as MONDO_0015302 'nodular cutaneous amyloidosis'?

The def of the latter term is:
Primary localized cutaneous nodular amyloidosis (PLCNA) is the most rare form of primary cutaneous amyloidosis (see this term), a skin disease characterized by the accumulation of amyloid deposits in the dermis, characterized clinically by yellowish waxy crusted nodules and papules on the face, lower extremities, trunk, scalp, and genitalia and histologically by the localized deposition of immunoglobulin-derived amyloid in the papillary dermis and subcutis. PLCNA can be associated with connective tissue disorders such as SjC6grenBs syndrome and CREST syndrome (see these terms).

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter

**Comment by nicolevasilevsky** [comment]
ping @GARDInfoCenter

**Comment by galyea-gard** [comment]
Hi! I changed 'amyloidosis nodular localized cutaneous' (which was added in 2013 and had not being reviewed since)  to 'Primary localized cutaneous nodular amyloidosis' (GARD:0010562) because is the preferred name.  I added 'nodular cutaneous amyloidosis' as a synonym. Thank you!  Gioconda

**Comment by nicolevasilevsky** [comment]
Hi @galyea-gard can you point me to the GARD page for this term?

When I search for 10562 or Primary localized cutaneous nodular amyloidosis I don't get any results.

Thanks!

**Comment by nicolevasilevsky** [comment]
the gard page is working now:
https://rarediseases.info.nih.gov/diseases/10562/primary-localized-cutaneous-nodular-amyloidosis

**Comment by nicolevasilevsky** [comment]
@galyea-gard do you think it is okay to merge these two terms?

MONDO_0022446 'amyloidosis nodular localized cutaneous' (GARD:0010562) with 
MONDO_0015302 'nodular cutaneous amyloidosis'(Orphanet:137810)

thanks!

**Comment by galyea-gard** [comment]
Hi Nicole!  We have this one under “Primary localized cutaneous nodular amyloidosis” which is a synonym of nodular cutaneous amyloidosis.  Thanks, Gioconda
