### ISSUE TITLE
[Revise subclass] Human prion disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1404]
**Mondo term (ID and Label)**
Human prion disease- child of 'neurodegenerative disease with dementia' - this should be fixed. (Note, fix text def too).

**Suggested revision and reasons**
Per conversation with EFO today- dementia is a phenotype of human prion disease, this classification is not quite right.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Prioritizing this please as linked to https://github.com/monarch-initiative/mondo/issues/1498.
Thank you as always.

**Comment by nicolevasilevsky** [comment]
I'm working on this right now!
What do you think is an appropriate parent?

**Comment by nicolevasilevsky** [comment]
I added 'infectious disease' as the parent. Do you think I should add 'neurodegenerative disease' too?

**Comment by paolaroncaglia** [comment]
> I'm working on this right now!
> What do you think is an appropriate parent?

'neurodegenerative disease' please, in keeping with our plan in https://github.com/monarch-initiative/mondo/issues/1498 :-)

**Comment by paolaroncaglia** [comment]
> I added 'infectious disease' as the parent. Do you think I should add 'neurodegenerative disease' too?

Sorry we "crossed". I think the latter would be good based on this bit in the def "The disorders all involve accumulation of an abnormal prion protein in the central nervous system".

**Comment by nicolevasilevsky** [comment]
thanks @paolaroncaglia!
