### ISSUE TITLE
[Obsolete] look for terms that are tagged ‘obsoletion candidate’

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1405]
Fixing these will help address #834 

Adding Shahim, as I am not sure if I know how to filter all the terms that are tagged 'obsoletion candidate'

**Comment by nicolevasilevsky** [comment]
@matentzn said he would help generate this list (thank you!) Once we have the list, I'll post it here for folks to review.

**Comment by matentzn** [comment]
@nicolevasilevsky I think @cmungall  pretty extensive reports already cover this:

https://github.com/monarch-initiative/mondo/blob/master/reports/obsoletion-candidates.tsv

Isnt this what you are looking for?

**Comment by nicolevasilevsky** [comment]
this is great, thank you @matentzn!

**Comment by nicolevasilevsky** [comment]
I sorted this list by label:
https://github.com/monarch-initiative/mondo/blob/master/reports/obsoletion-candidates-sorted.tsv

**Comment by nicolevasilevsky** [comment]
Google spreadsheet [here](https://docs.google.com/spreadsheets/d/1pASj2MnBI285ogOeKVqEVe2TsKCvOWDFFNq_ekN2juw/edit#gid=0)

**Comment by nicolevasilevsky** [comment]
@matentzn could you please regenerate this list? Looks like many terms have already been obsoleted. Thank you!

**Comment by matentzn** [comment]
This is how to do this:

```
sh run.sh report-query-obsoletion-candidates
```

Can you add a section to the editors doc how to generate reports?

## How to generate reports

Reports are generally created like this:

```
sh run.sh make report-query-%
```

For example, the following command...

```
sh run.sh make report-query-obsoletion-candidates
```

will run this:

```
robot --catalog catalog-v001.xml query --use-graphs true -i mondo-edit.obo -f tsv --query ../sparql/reports/obsoletion-candidates.sparql reports/report-obsoletion-candidates.tsv
```

Which will generate a TSV report here: `reports/report-obsoletion-candidates.tsv`.

The only requirement for a report is, that a suitable SPARQL query can be found in `../sparql/reports/`, for example, `../sparql/reports/obsoletion-candidates.sparql`. 

If you want to create your very own report, you can 
1. tweak an existing command, for example using Ubergraph (https://api.triplydb.com/s/YfJCi9mrR)
2. Save the query as a `.sparql` query in `../sparql/reports/`, for example, `../sparql/reports/my-query.sparql`. 
3. Run `sh run.sh make report-query-my-query` to generate the report as above.

Note that the above does not cover automated upload to Google docs (if you want to learn that, put it on a QC meeting agenda).

**Comment by nicolevasilevsky** [comment]
thank you, will do!

**Comment by nicolevasilevsky** [comment]
Updated spreadsheet is [here](https://docs.google.com/spreadsheets/d/1bEiENtEqPQ5hOLZdeVP_wEL_USpVPruNy4D9avNKC74/edit#gid=1454394910)

**Comment by nicolevasilevsky** [comment]
reviewed the list and created separate tickets for this
