### ISSUE TITLE
[Revise text def] MONDO:0005249 pneumonia

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1439]
MONDO:0005249 pneumonia has a comment "Editor note: TODO change text def to make it clear always infectious etiology"
(current def is:
"An acute, acute and chronic, or chronic inflammation focally or diffusely affecting the lung parenchyma, due to infections (viruses, fungi, mycoplasma, or bacteria), treatment (e.g. radiation), or exposure (inhalation) to chemicals. Symptoms include cough, shortness of breath, fevers, chills, chest pain, headache, sweating, and weakness.")

Its sibling MONDO:0043905 'pneumonitis' has a comment "Pneumonitis typically refers to non-infectious inflammation, whereas pneumonia refers to infectious" (current def is "An inflammatory process affecting the lung parenchyma. It is a milder form of lung inflammation compared to pneumonia.")

The Wikipedia entry for 'pneumonitis' (https://en.wikipedia.org/wiki/Pneumonitis) suggests that pneumonitis should be parent of pneumonia. The "-itis" also fits with a broader inflammation term. But this contrasts with "...It is a milder form of lung inflammation compared to pneumonia." I'm not sure if doctors would agree to see pneumonia as a subtype of pneumonitis, rather than siblings. (In EFO, pneumonitis is a child of pneumonia!) Either way, the def. of pneumonia should be corrected please (especially important in times of COVID, for data analysis, text searches etc.). Thanks! :-)

**Comment by nicolevasilevsky** [comment]
@pnrobinson could you comment on the classification of pneumonia and pneumonitis? Thank you!

**Comment by nicolevasilevsky** [comment]
I revised the def to:
An acute, acute and chronic, or chronic inflammation focally or diffusely affecting the lung parenchyma, caused by an infection in one or both of the lungs (by bacteria, viruses, fungi, or mycoplasma.). Symptoms include cough, shortness of breath, fevers, chills, chest pain, headache, sweating, and weakness.

@paolaroncaglia (and all) please let me know if you have any suggested revisions.

**Comment by pnrobinson** [comment]
Indeed pneumonia should be a subclass of pneumonitis. See for instance the Mayo Clinic:

https://www.mayoclinic.org/diseases-conditions/pneumonitis/symptoms-causes/syc-20352623

**Comment by nicolevasilevsky** [comment]
Thank you @pnrobinson!

**Comment by paolaroncaglia** [comment]
@pnrobinson and @nicolevasilevsky thanks for your feedback and revision of def and placement, I agree with your edits. Have a good and safe weekend.
