### ISSUE TITLE
[NTR] P5CS Deficiency

### ISSUE THREAD

**Issue by RedRiver1816** [monarch-initiative/mondo#1444]
**Preferred term label:** 
P5CS Deficiency

**Synonyms:** 
Δ1-Pyrroline-5-carboxylate synthetase deficiency

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
P5CS Deficiency is an inborn error of proline/orinthine metabolism that covers a wide spectrum of phenotypes and is caused by pathogenic variants in the Aldehyde Dehydrogenase 18 Family Member A1 (ALDH18A1) gene. These variants lead to a variety of neurocutaneous and motor syndromes characterized by cutis laxa, connective tissue weakness, facial dysmorphism, growth restriction, developmental delay, cataracts, hypotonia, hypertonia, and amyotrophy. (PMID:32017139)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0019230 (inborn disorder of ornithine or proline metabolism)

OR

MONDO:0017356 (inborn disorder of ornithine metabolism)
AND
MONDO:0017355 (inborn disorder of proline metabolism)

**Suggested child terms for collapse under new term:**
MONDO:0009053 (ALDH18A1-related de Barsy syndrome)
MONDO:0015091 (autosomal dominant spastic paraplegia type 9)
MONDO:0014702 (autosomal recessive complex spastic paraplegia type 9B)
MONDO:0014706 (cutis laxa, autosomal dominant 3)

@nicolevasilevsky: This is a ClinGen EP Request.

**Comment by cmungall** [comment]
How does this relate to:

```
name: ALDH18A1-related de Barsy syndrome
def: "ALDH18A1-related De Barsy syndrome combines intellectual deficit, bilateral cataracts, and skin and joint hyperlaxity." [Orphanet:35664]
subset: ordo_etiological_subtype {source="Orphanet:35664"}
synonym: "ARCL3A" EXACT [DOID:0070132, MONDO:Lexical, OMIM:219150]
synonym: "autosomal recessive cutis laxa type IIIA" RELATED [DOID:0070132]
synonym: "cutis laxa, autosomal recessive, type 3A" RELATED [OMIM:219150]
synonym: "cutis laxa, autosomal recessive, type IIIA" RELATED [MONDO:Lexical, OMIM:219150]
synonym: "cutis laxa, autosomal recessive, type IIIA; ARCL3A" RELATED [OMIM:219150]
synonym: "cutis laxa, corneal clouding, and mental retardation" RELATED [OMIM:219150]
synonym: "De Barsy syndrome A" EXACT [DOID:0070132]
synonym: "De Barsy syndrome a" RELATED [OMIM:219150]
synonym: "Delta-1-pyrroline 5-carboxylate synthetase deficiency" EXACT [Orphanet:35664]
synonym: "neurocutaneous syndrome, Bicknell type" EXACT [Orphanet:35664]
****synonym: "P5CS deficiency" EXACT [Orphanet:35664]****
synonym: "progeroid syndrome of De Barsy" RELATED [OMIM:219150]
xref: DOID:0070132 {source="MONDO:equivalentTo"}
xref: ICD10:Q82.8 {source="DOID:0070132"}
xref: ICD10:Q87.8 {source="ORDO:35664/attributed", source="ORDO:35664/ntbt", source="Orphanet:35664"}
xref: ICD9:371.89 {source="MONDO:relatedTo", source="i2s"}
xref: OMIM:219150 {source="DOID:0070132", source="MONDO:equivalentTo", source="ORDO:35664/e", source="Orphanet:35664"}
xref: Orphanet:2962 {source="MONDO:subClassOf", source="OMIM:219150"}
xref: Orphanet:35664 {source="DOID:0070132", source="MONDO:equivalentTo", source="OMIM:219150"}
xref: SCTID:59252009 {source="MONDO:equivalentTo", source="MONDO:kboom-pr-0.67/0.31/0.16"}
xref: UMLS:C0268354 {source="NCBI:mim2gene_medline", source="MONDO:notFoundInDiseaseSubset", source="OMIM:219150"}
is_a: MONDO:0016175 {source="DOID:0070132/inferred", source="MONDO:Redundant", source="OMIM:219150", source="Orphanet:35664/inferred", source="linkedlifedata"} ! cutis laxa
is_a: MONDO:0017569 {source="DOID:0070132", source="MONDOLEX:0009053", source="Orphanet:35664"} ! de Barsy syndrome
relationship: disease_has_basis_in_dysfunction_of http://identifiers.org/hgnc/9722 {source="mim2gene_medgen"} ! ALDH18A1
```

Note the orphanet exact synonym

**Comment by RedRiver1816** [comment]
@cmungall Note that ALDH18A1-related de Barsy syndrome is proposed as a child term for the more general P5CS Deficiency. Specifically, the above entity only refers to a single form of the disorder (AR Cutis Laxa) whereas this general term should cover the other three forms as well (AD Cutis Laxa, AR/AD Spastic Paraplegia). The above publication (PMID:32017139) provides evidence to support this.
