### ISSUE TITLE
[NTR] MYPN-related myopathy

### ISSUE THREAD

**Issue by mayherpatel** [monarch-initiative/mondo#1446]
**Preferred term label:**
MYPN-related myopathy

**Synonyms**
MONDO:0015023

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Congenital myopathy caused by pathogenic mutations in MYPN that lead to a wide spectrum of phenotypes. Patients with mutations in this gene often experience muscle weakness, facial weakness, and sometimes cardiac and respiratory issues. Histological findings on skeletal muscle biopsy are variable with nemaline bodies and cap-like lesions. 

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

MONDO:0019952

**Your nano-attribution (ORCID)**

**Comment by mayherpatel** [comment]
This request is from the ClinGen Congenital Myopathies GCEP

**Comment by nicolevasilevsky** [comment]
@mayherpatel is 'nemaline myopathy 11' a synonym for 'MYPN-related myopathy'? If yes, should MYPN-related myopathy be added as a synonym to the existing Mondo term MONDO:0015023 'nemaline myopathy 11'?

We could update the definition to use your definition above, if you prefer. 

Could you provide a source for the definition, like a PubMed ID for a paper?

Thanks!

**Comment by mayherpatel** [comment]
@nicolevasilevsky Yes the term "nemaline myopathy 11" is a synonym but the group would like the main term to be changed to "MYPN-related myopathy", if possible. 

Here is the first publication - PMID: 28017374
