### ISSUE TITLE
[Revise logical def] anodontia vs. Anodontia of permanent dentition

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1449]
**Mondo term (ID and Label)**
anodontia MONDO:0008797

**Suggested revision of logical definition**
Should the label incorporating of permanent dentition be made a child of MONDO:0008797 or are these truly equivalent to clinicians? 
UMLS and SNOMED make  distinctions among 
1. Anodontia of permanent dentition [A3618086/SNOMEDCT_US/PT/109444001]
2. Anodontia of primary dentition [A3618113/SNOMEDCT_US/PT/109443007]
3. Developmental absence of tooth  aka anodontia
Congenital absence of the teeth; it may involve all (total anodontia) or only some of the teeth (partial anodontia, hypodontia), and both the deciduous and the permanent dentition, or only teeth of the permanent dentition.)  for which anodonia is treated as a synonym

**Comment by nicolevasilevsky** [comment]
Looks like @GARDInfoCenter lumps them together. OMIM has anodontia of permanent dentition as its own record.

I think it is okay to separate them.

@GARDInfoCenter, do you want to weigh in?

Thanks!

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky - From our research, most reports indicate that when agenesis occurs as an isolated finding, the primary dentition is not affected, only the permanent teeth. We noticed that the OMIM information from 2009.  For this reason, GARD just has only one page for anodontia which states that the condition can involve either primary or permanent dentition.

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter thanks for your input! Sound like we should leave it as is. @maglott is that okay with you? I'll close this but please reopen if you'd like to continue the discussion.

**Comment by maglott** [comment]
@nicolevasilevsky , I don't see how to reopen.  I am fine with anodonita (MONDO_0008797) being appropriate for permanent or  deciduous teeth; But given that  anodontia of permanent dentition is a related synonym, I am trying to understand why OMIM_206780  (permanent only) is considered as xref.  I guess we will retain the specificity from UMLS, and keep OMIM_206780 with Anodontia of permanent dentition
