### ISSUE TITLE
MONDO:0015194 and link to OMIM

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1450]
sideroblastic anemia MONDO:0015194 is defined as 'inherited or acquired', yet has an XRef to https://www.omim.org/phenotypicSeries/PS300751 which is clearly the genetic subset
1. What is the term in MONDO for the equivalent of '[C0221018]  Hereditary sideroblastic anemia
'?
2.  When MONDO does distinguish between concepts with multiple etiologies and the subsets that are inherited, is an effort made to limit  xrefs from OMIM to the inherited ones?
3. The new browser has 2 links to OMIM phenotypic series, the one constructed as http://www.omim.org/phenotypicSeries/300751 does not work/; the one as https://www.omim.org/phenotypicSeries/PS300751 does.

**Comment by nicolevasilevsky** [comment]
1. MONDO_0020721 'X-linked sideroblastic anemia 1' is equiv to [C0221018] Hereditary sideroblastic anemia
2.  I am not sure. @cmungall could you answer this?
3. Which new browser do you mean, @maglott?

**Comment by nicolevasilevsky** [comment]
@cmungall should we change the xref to OMIMPS:300751 to 'MONDO:relatedTo'? Or just remove MONDO:equivalentTo?

**Comment by maglott** [comment]
The new Monarch display:
https://monarchinitiative.org/disease/MONDO:0015194

**Comment by nicolevasilevsky** [comment]
I see, thanks @maglott. I'll report this bug on the Monarch tracker.
