### ISSUE TITLE
Which is the best release artefact for display in tree browsers?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#1451]
OLS for example has some [serious issues](https://github.com/EBISPOT/OLS/issues/312) with the equivalent class axioms in the normal mondo.owl release.

**Comment by matentzn** [comment]
I think I would like to request a Mondo version that has only Mondo ids and "exactMatch" or "dbxref" annotations to the other ontologies.. Does this make sense?

**Comment by nicolevasilevsky** [comment]
@matentzn do you know who can help with this? Are you able to assign them?

**Comment by matentzn** [comment]
@cmungall Are we allowed to add another standard release artefact with xrefs instead of logical equivalences between Mondo and other disease ontology terms? For the browsing use case?

**Comment by nicolevasilevsky** [comment]
This needs to be solved more generally in OBO, this is not a specific issue for Mondo.
