### ISSUE TITLE
[Revise logical def]  Some gene/protein  records from OMIM are being treated as disorders

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1452]
**Mondo term (ID and Label)**
MONDO_0007521 : egasyn
MONDO:0012424: heat-shock RNA 1 
MONDO:0007149: arbitrary restriction polymorphism 1 
MONDO:0008126: oncogene Yuasa

**Suggested revision of logical definition**

**Comment by nicolevasilevsky** [comment]
If these are genes and not diseases, we should obsolete these

**Comment by maglott** [comment]
Adding this fragile site to the list.  I think it should be treated as a sequence variant, not a disorder.
https://monarchinitiative.org/disease/MONDO:0007632
