### ISSUE TITLE
[NTR] SCN4-related myopathy, autosomal recessive

### ISSUE THREAD

**Issue by brookepalus** [monarch-initiative/mondo#1453]
**Preferred term label:**
SCN4A-related myopathy, autosomal recessive 

**Synonyms**

- Congenital myopathy with "corona" fibers, selective muscle atrophy, and craniosynostosis
- Myopathy with ptosis and mild dystrophic pattern
- Congenital Myopathy with severe fetal hypokinesia

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Congenital Myopathy, MONDO:0019952

**Your nano-attribution (ORCID)**
@nicolevasilevsky this is a submission from the ClinGen LGMD GCEP! Thank you.

**Comment by nicolevasilevsky** [comment]
Hi @brookepalus could you please give me a bit more information? Is there a paper (PubMed ID) that I can reference, and can you suggest a text definition to describe this term?

Thanks!

**Comment by brookepalus** [comment]
Hi Nicole, 
I apologize for the lack of information. I am putting in this request on the behalf of one of our biocurators, so please let me know how else I can clarify the request beyond what I have included below. 

I also made an error in the original request, and the new MonDO term should be: SCN4A-related myopathy, autosomal recessive  (where originally I left off the A). Please let me know if you can alter the original request or if I should put in a new request. 

Here is a description of the term: 
SCN4A related myopathy is a spectrum of autosomal recessive disorders including congenital myasthenic syndrome, fetal hypokinesia, and congenital myopathy that are related to pathogenic variants in SCN4A gene.

There are no PMIDs that specifically refer to this term. The decision to lump the above mentioned congenital myopathies was made by the ClinGen LGMD Gene Curation Expert Panel, who determined that these conditions represent a phenotypic spectrum and not separate disease entities and thus should be lumped under an umbrella term. The PMIDs that were considered in this decision include: PMID 30824560; PMID 28003497; PMID 26700687; PMID 28003497; PMID 28262468; and PMID 28003497. 

Please let me know what other information I can provide to help clarify. 

Many Thanks!
Brooke

**Comment by nicolevasilevsky** [comment]
Thanks Brooke, this is great!

**Comment by brookepalus** [comment]
Hi Nicole, 
I just wanted to check in regarding this MonDo ID request. Do you have an estimated time line for approval? 

Many thanks,
Brooke

**Comment by nicolevasilevsky** [comment]
This should be available in the next release at the end of this month/early next month. Thanks for your patience.

The new Mondo ID is: MONDO:0100121

**Comment by nicolevasilevsky** [comment]
@brookepalus sorry for the delay, this should be available in the release at the end of July

**Comment by brookepalus** [comment]
Hi @nicolevasilevsky, it appears that this Mondo ID is still not live. Does it appear to be live on your end or do you have any updates you can share? 

Many thanks, 
Brooke

**Comment by nicolevasilevsky** [comment]
Hi @brookepalus apologies for the delay, the release has been slightly delayed and should be ready by the end of next week.
