### ISSUE TITLE
split term: 'X-linked nonsyndromic deafness'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1462]
**Term to split:**
MONDO_0019586 'X-linked nonsyndromic deafness'

**Name for new term:**
deafness, X-linked
https://omim.org/phenotypicSeries/PS304500

**definition**
X-linked form of deafness.
dbxref: MONDO:patterns/x_linked

**parent**
auditory system disease
hearing loss disorder

**equiv axiom**
'hearing loss disorder'
 and ('has modifier' some 'X-linked inheritance')

**List properties that should be moved to new term:**
dbxref: OMIMPS:304500
source: MONDO:equivalentTo

exact syn: deafness, X-linked
dbxref: OMIMPS:304500

- [ ] make X-linked deafness from DOID:0050566 a related synonym on MONDO_0019586

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/monarch-disease-ontology-RETIRED/issues/408

**Comment by cmungall** [comment]
I'll handle, part of a complex operation

**Comment by nicolevasilevsky** [comment]
Great, thanks!
