### ISSUE TITLE
Merge MONDO:0023310 (hemiplegic migraine) + MONDO:0018925 (familial or sporadic hemiplegic migraine)

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#1463]
they are the same

**Comment by galyea-gard** [comment]
Hi!  I agreed with this change because the term is used in Orphanet and it is, per se, illustrative of the subtypes or causes of HM.

**Comment by galyea-gard** [comment]
We have also made this change in GARD.
