### ISSUE TITLE
[NTR] vector-borne disease

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1468]
Hi again, would you please consider addition of the grouping term

**vector-borne disease**

It doesn't seem to exist in any of the usual resources.
Some of our collaborators need this for text mining, but I wonder if it might be a meaningful addition for others too.

**Synonyms**
vector-borne infectious disease
vector-borne infection

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
An infectious disease where a pathogen is carried and transmitted by another organism that acts as disease vector. 
Wikipedia:Vector_(epidemiology) 
https://www.who.int/news-room/fact-sheets/detail/vector-borne-diseases

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0005550 infectious disease

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-2825-0621

You may wish to assert some existing Mondo terms to be subclasses of 'vector-borne disease', a useful start is the list here: https://www.who.int/news-room/fact-sheets/detail/vector-borne-diseases

If you'd rather not create a new term, perhaps you could add "vector-borne disease' as a narrow synonym of 'infectious disease'?

Thanks!

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,
I see that my requested new term for 'vector-borne disease' is pending PR. Is there any update on that, please? We'd need the term for a collaborators' project. Thanks!

**Comment by nicolevasilevsky** [comment]
Chris had some comments for me, which I just addressed. Hopefully we can get this into the next release.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky I took the liberty to add the priority flag, see https://github.com/monarch-initiative/mondo/pull/1472#issuecomment-638284357. Thanks as always :-)
