### ISSUE TITLE
About the value of xmlns:obo in the header

### ISSUE THREAD

**Issue by yy20716** [monarch-initiative/mondo#148]
This may be a duplicated/known/fixed issue. When I downloaded the mondo.owl file from [this link](http://purl.obolibrary.org/obo/mondo.owl), I saw that the value for `xmlns:obo` was a bit weird, i.e.,
~~~~
<?xml version="1.0"?>
<rdf:RDF xmlns="http://purl.obolibrary.org/obo/mondo.owl#"
     ...
     xmlns:obo="http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/"
     ...
~~~~
I guess that the value should be `http://purl.obolibrary.org/obo/`, but I was not sure whether this was intended or simply I misunderstood. I would appreciate it if someone can check this issue. Thank you.

**Comment by nicolevasilevsky** [comment]
@yy20716 closing this, please reopen if you still see this issue
