### ISSUE TITLE
[Revise subclass] MONDO:0005328 eye disease

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1482]
eye disease (MONDO:0005328)

Definition | Parents
-- | --
A non-neoplastic or neoplastic disorder that affects the eye. Representative examples include conjunctivitis, glaucoma, cataract, conjunctival squamous cell carcinoma, uveal melanoma, and retinoblastoma.

Are all of these children really 'eye diseases"

some look like they might be more appropriately descendants of the parent
"disease of orbital region"

e.g.
MONDO:0013768 arterial calcification, generalized, of infancy, 2
Any arterial calcification of infancy in which the cause of the disease is a mutation in the ABCC6 gene.

MONDO:0008048 autosomal dominant centronuclear myopathy

probably via
myopathy with eye involvement (MONDO:0020259)

this does not  sound as though it would necessarily be classed as an eye disease.

I did not check the list thoroughly  but  we get a lot of inferences which seem slightly dodgy

**Comment by nicolevasilevsky** [comment]
I agree that MONDO:0013768 arterial calcification, generalized, of infancy, 2 does not seem like an eye disease. I am not sure why it has the parent 'oculocutaneous albinism', I think we can exclude this supclassOf relationship.

**Comment by nicolevasilevsky** [comment]
I think the classification:
'rare disorder with ptosis'
->'centronuclear myopathy'

may be incorrect. I'll look into it further and we can exclude the subclassOf assertion

**Comment by ValWood** [comment]
Thanks! No huge hurry, the migration overall looks pretty good, and we get much better coverage of most  grouping terms in our slim.
There may be a couple of further tickets as I see a couple more things I would like to QC check.

**Comment by cmungall** [comment]
> I am not sure why it has the parent 'oculocutaneous albinism',

what's the axiom annotation say?

**Comment by nicolevasilevsky** [comment]
there is not a axiom annotation 

![image](https://user-images.githubusercontent.com/6722114/81979747-53d77c80-95e2-11ea-863e-8f81a9611ff3.png)

**Comment by nicolevasilevsky** [comment]
@ValWood I excluded the subclass Of assertions for:
MONDO:0013768 arterial calcification, generalized, of infancy, 2 
MONDO_0018947 centronuclear myopathy

There are 2500 subclasses of 'eye disease', so I can't review this entire list. Could you please report any other issues as you see them? Thank you!

**Comment by cmungall** [comment]
thanks. some of these should fall out of the ordo cleanup work

**Comment by ValWood** [comment]
OK, I will have another look when these are gone. That was my plan anyway.   I wasn't sure  how many would go away  when these terms were removed because I can't see all  the hierarchy in our view, we just get a. flat list of everything under eye disease 
Like:
https://www.pombase.org/term/MONDO:0005328
