### ISSUE TITLE
inborn vs inherited

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1483]
inborn errors of metabolism MONDO:0019052

Definition | Parents
-- | --
A group of disorders present at birth that involve genetic defects leading to disturbances in carbohydrate, lipid, lysosomal storage or amino acid metabolism in the body. The inborn errors of metabolism are typically rare, but this class also encompasses non-rare diseases like hereditary hemochromatosis type 1

What does "present at birth" mean ? how does it differ from 'inherited"?
does this mean that the disease is already visible, or something else?

for example,  hemochromatosis type 1 in the def does not manifest until middle age?

**Comment by nicolevasilevsky** [comment]
I think 'present at birth' is different from inherited in that it doesn't necessarily have to be an inherited disease, but could be a disease that arose via a different mechanism.

There is a comment on MONDO_0006507 'hereditary hemochromatosis' (which is the parent of  hemochromatosis type 1):
Editor notes: HH1 is not rare, so the current placement of generic HH under rare inborn errors of metabolism is technically incorrect. However, reclassifying on the basis of prelvalence does not make biological sense since the mechanism is the same. See notes on MONDO:0019052

**Comment by nicolevasilevsky** [comment]
@pnrobinson or @cmungall do you want to weigh in?

**Comment by ValWood** [comment]
>I think 'present at birth' is different from inherited in that it doesn't necessarily have to be an inherited disease, but could be a disease that arose via a different mechanism.

So what would an example of  another mechanism be other than "inherited"?

Hemochromatosis type 1 is 
inherited, autosomal, recessive 
but not "present at birth"

**Comment by pnrobinson** [comment]
Exactly. For instance congenital infection (https://med.emory.edu/departments/pediatrics/divisions/neonatology/dpc/conginf.html). 

inborn and inherited are synonymous (for all effective purposes). Not all inborn defects manifests at birth
congenital means something that manifests at birth

**Comment by ValWood** [comment]
>congenital means something that manifests at birth

So can you use "congenital" for everything that is currently "manifests at birth"
(Or did I misunderstand which part this was the answer too.

> More towards your question - I don't see mention of middle age onset in the def of MONDO_0021001 hemochromatosis type 1

 hemochromatosis type 1 is *definitely*  not ever symptomatic at birth

"Haemochromatosis is an inherited condition where iron levels in the body slowly build up over many years. This build-up of iron, known as iron overload, can cause unpleasant symptoms. If it is not treated, this can damage parts of the body such as the liver, joints, pancreas and heart."
"only a small proportion of people with 2 copies of the faulty HFE gene will ever develop the condition"
https://www.nhs.uk/conditions/haemochromatosis/

I'm still a bit confused if "present at birth" refers to the mutation or the symptoms but I'm new to this. It could be clearer.....

i.e if it means only  inherited why not say 'inherited'  and if it  means "visible from birth" say congenital. Or isn't it that simple?

**Comment by pnrobinson** [comment]
an inherited condition does NOT mean visible at birth. Essentially it means in this context that the affected person carries genetic variants that strongly (and in many cases deterministically) predispose to health problems later in life.

**Comment by ValWood** [comment]
> an inherited condition does NOT mean visible at birth.

No, clearly. But I said 
"i.e if it means only inherited why not say 'inherited'"

if "present from birth"  means more than inherited,  what is that? This is the part that I am not getting.

**Comment by pnrobinson** [comment]
I see what you mean. AFAIK this is a question of usage. The Inborn errors or metabolism refer to a group of very serious disorders that happen to also present at birth. They result from defects in enzymes that are basically required from birth on. This is an additional specification.

**Comment by ValWood** [comment]
OK, so action is to review those which are described as "inborn"

inborn disorder of purine or pyrimidine metabolism (MONDO:0019254)

includes  things which are not severe at birth


Definition | Parents
-- | --
A group of disorders present at birth that involve genetic defects leading to disturbances in carbohydrate, lipid, lysosomal storage or amino acid metabolism in the body. The inborn errors of metabolism are typically rare, but this class also encompasses non-rare diseases like hereditary hemochromatosis type 1

and the definition includes hemochromatosis type 1 as a specific example which is *definitely* not inborn based on this additional  criteria.  Hemochromotosis   *never* has observed  symptoms at birth because by definition it is an iron overload disorder.

**Comment by pnrobinson** [comment]
Might be easier to skype. inborn means hereditary not congenital, and thus inborn is correct here!

**Comment by ValWood** [comment]
Yes, I can't do today as I'm supposed to be off, it's bank holiday here. I just got caught up in some "small tasks'

So far summarizing  I'm getting 

hereditary
--congenital
--inborn hereditary not congenital 
--other? 

but then

- inborn and inherited are synonymous (for all effective purposes). 
- Not all inborn defects manifests at birth
- The Inborn errors of metabolism refer to a group of very serious disorders that happen to also present at birth. They result from defects in enzymes that are basically required from birth on.

It just that these statements  seems to be conflicting.

- Congenital  disorders are present from birth.
- Inborn disorders are non-congenital disorders.
- Some inborn disorders are present from birth (so some inborn disorders are congenital)

**Comment by ValWood** [comment]
I think I get it now.

So
inborn errors of metabolism (MONDO:0019052)
could have 
exact synonym "inherited metabolic disease"

is that correct?
I was just wondering why sometimes inherited is used, and sometimes inborn is used?

**Comment by ValWood** [comment]
No I am still getting it wrong


Definition | Parents
-- | --
Diseases caused by abnormal function of the mitochondria. They may be caused by mutations, acquired or inherited, in mitochondrial dna or in nuclear genes that code for mitochondrial components. They may also be the result of acquired mitochondria dysfunction due to adverse effects of drugs, infections, or other environmental causes.


so inherited is narrower than inborn?

Maybe it doesn't matter for the ontology. I just wanted to know because I can't check our groupings sensibly unless I understand what the term names/definitions  mean.

Happy for a Skype explanation sometime.

**Comment by pnrobinson** [comment]
@ValWood if you would like to send me an email, I'd be happy to set up a skype. 

I think that inborn and inherited are very close, but inborn tends to be used to describe a disease that is caused by an inherited mutation. The word is not much used any more, I think we mainly see it in inborn errors of metabolism.

Another point is that we should avoid the use of the word mutation (the community is rejecting this word and prefers variant with a modifier...)

**Comment by ValWood** [comment]
I just spoke  with @pnrobinson  and I was going to say this ticket could close.

But I see the problem I first reported.

According to Peter,  inborn is synonymous with inherited, but this definition says "present at birth"

inborn errors of metabolism MONDO:0019052
Definition 
A group of disorders present at birth that involve genetic defects leading to disturbances in carbohydrate, lipid, lysosomal storage or amino acid metabolism in the body. The inborn errors of metabolism are typically rare, but this class also encompasses non-rare diseases like hereditary hemochromatosis type 1

BUT the 
inborn errors of metabolism MONDO:0019052
are NOT necessarily present from birth.

So the definition SHOULD change, 

Could it say instead 
A group of ~disorders present at birth~ inherited disorders

that would fix the problem!

**Comment by nicolevasilevsky** [comment]
Yes, I'll fix this. thanks @ValWood! Glad you and Peter were able to catch up.

**Comment by ValWood** [comment]
I would like @pnrobinson  to confirm first, but this is my understanding.

Sorry I missed   chatting to you too!

**Comment by pnrobinson** [comment]
I would suggest this definition:
Inborn errors of metabolism are rare inherited disorders resulting from an enzyme defect in biochemical and metabolic pathways affecting proteins, fats, carbohydrates metabolism or organelle function. 

The following is not true: The inborn errors of metabolism are typically rare, but this class also encompasses non-rare diseases like hereditary hemochromatosis type 1

**Comment by ValWood** [comment]
I agree, I'm HFE-/HFE-, iron overload  isn't a metabolic disorder ;)

**Comment by nicolevasilevsky** [comment]
sounds good, I updated the def to:
Rare inherited disorders resulting from an enzyme defect in biochemical and metabolic pathways affecting proteins, fats, carbohydrates metabolism or organelle function.

Chris asked that we not replicate the name of the class in the definition in his [blog](https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/)

**Comment by cmungall** [comment]
Technically the def is still not right as it says "rare" yet HH1 is not rare... but this is a "rare" exception (where "rare" applies at the metaclass level...)

**Comment by nicolevasilevsky** [comment]
Shall we revise to 'Inherited disorders resulting from an enzyme defect in biochemical and metabolic pathways affecting proteins, fats, carbohydrates metabolism or organelle function.' ?

**Comment by pnrobinson** [comment]
Nicole's suggestion seems fine. Possibly we should de-pluralize the definition thought. An inherited disorder resulting...
since we are striving to be singular!

**Comment by nicolevasilevsky** [comment]
Thanks, I will fix this!

**Comment by ValWood** [comment]
inborn errors of metabolism MONDO:0019052
Would it also be clearer, because of the confusion, to standardize term names on "inherited" and have "inborn" as exact synonym?

**Comment by pnrobinson** [comment]
For whatever reason, the word inborn seems to be used solely in this context and it would probably engender even more confusion if we use it in other contexts.

**Comment by ValWood** [comment]
I'm still a bit confused.



2. The term
inborn  errors of metabolism 

is now defined
Inherited disorders resulting from an enzyme defect in biochemical and metabolic pathways affecting proteins, fats, carbohydrates metabolism or organelle function.

and has 
inherited  disorders of metabolism 
as an exact synonym?
Is that correct?

3.
If this is the case it still seems that  using 
"inherited errors of metabolism"  would be a more universally understandable term name? or do people more commonly use "inborn"
especially since here:
https://github.com/monarch-initiative/mondo/issues/1483#issuecomment-628568249
@pnrobinson  you say that 'inborn' is not used very much anymore 
(Note that I am not suggesting using 'inborn' in other contexts. I am suggesting the opposite, that you 'demote' the use of 'inborn' because it is confusing, if it means the same).

Google
"inborn metabolic disorder" About 14,200
"inborn disorders of metabolism" 2,620
"inherited disorders of metabolism" About 65,100 
"inherited metabolic disorder" About 113,000 results

**Comment by pnrobinson** [comment]
I am saying just for this group of diseases use the word inborn, and have inherited as a synonym. The other synoynms are also fine.

**Comment by nicolevasilevsky** [comment]
I updated the definition and added the synonym `inherited disorder of metabolism`
