### ISSUE TITLE
inborn mitochondrial metabolism disorder

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1485]
**MONDO:0004069**

inborn mitochondrial metabolism disorder

is defined
Diseases caused by abnormal function of the mitochondria. They may be caused by mutations, acquired or inherited, in mitochondrial dna or in nuclear genes that code for mitochondrial components. They may also be the result of acquired mitochondria dysfunction due to adverse effects of drugs, infections, or other environmental causes.

That would seem to exclude
MEHMO syndrome caused by translation initiation factor eIF2 gamma subunit

**Comment by maglott** [comment]
Is 'inborn error' consistent with a definition that states 'acquired or inherited'?
That definition seems more consistent with a general term for 
**mitochondrial metabolism disorder**, for which **inborn mitochondrial metabolism disorder** would be the inherited subset (nuclear or mitochondrial, maternal)

**Comment by ValWood** [comment]
I also queried the use of inborn vs. inherited here
https://github.com/monarch-initiative/mondo/issues/1483

I don't understand the distinction, but there may be one.

**Comment by ValWood** [comment]
In case this request is not =clearv 

MEHMO syndrome 
currently is_a inborn mitochondrial metabolism disorder

**Comment by nicolevasilevsky** [comment]
@ValWood I am unclear what the request is here, could you please clarify? Thank you!

**Comment by ValWood** [comment]
Sorry!

I  don't think that 
"MEHMO syndrome" is an "inborn mitochondrial metabolism disorder"

I see that is has a comment at the end about mitochondrial dysfunction

MEHMO syndrome is characterised by severe intellectual deficit, epilepsy, microcephaly, hypogenitalism, and obesity. Growth delay and diabetes are also present. To date, it has been described in seven boys, all of whom died within the first two years of life. The causative gene has been localised to the 21.1-22.13p region of the X chromosome and the syndrome appears to result from mitochondrial dysfunction.


but this is cytoplamsic translation factor so it will likly  have pleiotropic phenotypes

**Comment by ValWood** [comment]
Although it is called a mitochondrial disorder here:
https://www.nature.com/articles/5200791
so maybe that is OK

**Comment by ValWood** [comment]
but it's really a defect in the control of protein synthesis globally
https://pubmed.ncbi.nlm.nih.gov/30517694/?from_term=MEHMO+syndrome&from_pos=2

so the mitochondrial effects sound more like phenotypes.
Is this how you would differentiate?

**Comment by ValWood** [comment]
MEHMO is also a single gene disorder

**Comment by nicolevasilevsky** [comment]
> MEHMO is also a single gene disorder (EIF2S3)

Could you provide a reference for this? Thank you!

**Comment by nicolevasilevsky** [comment]
thanks for clarifying!
