### ISSUE TITLE
drop in numbers for autosomal dominent and recessive after migration (DO>MONDO)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1488]
i.e.

<img width="979" alt="Screenshot 2020-05-07 at 12 53 55" src="https://user-images.githubusercontent.com/7359272/81291573-e5cf0a80-9061-11ea-882f-8e11c49b6e49.png">

A drop in number means that a gene product which used to map to this grouping term by propagation no longer does.

You can see the current inferences here
https://www.pombase.org/term/DOID:0050737

and here
https://www.pombase.org/term/DOID:0050736

(NOTE:  these pages will disappear after we switch which should. be quite soon)

**Comment by nicolevasilevsky** [comment]
@ValWood 
Sorry I wasn't able to get to this ticket sooner, the links above no longer work. Not sure how to address this.

cc @cmungall

**Comment by ValWood** [comment]
I saved the lists before we migrated, but they are only pombe gene name lists now.

[autosomal dominent.txt](https://github.com/monarch-initiative/mondo/files/4661545/autosomal.dominent.txt)

[autosomal recessive.txt](https://github.com/monarch-initiative/mondo/files/4661546/autosomal.recessive.txt)

I need to do diffs on the current  lists, and then ask @kimrutherford to extract the 
disease associations for us.

**Comment by nicolevasilevsky** [comment]
> I need to do diffs on the current lists, and then ask @kimrutherford to extract the
disease associations for us.

Ok, thanks!

**Comment by nicolevasilevsky** [comment]
@ValWood is there still action needed here?

**Comment by ValWood** [comment]
I'm happy for it to close. I just wondered why many diseases which had these ancestors in DO no longer have the., but perhaps they were incorrect?
