### ISSUE TITLE
review of Zellweger spectrum disorders

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1490]
According to GeneReviews and GHR
https://www.ncbi.nlm.nih.gov/books/NBK1448/#pbd.Nomenclature
The relationships should look something like
Peroxisome biogenesis disorders
* Zellweger spectrum disorder
** Zellweger syndrome
***all its gene-specific subclasses
** neonatal adrenoleukodystrophy (NALD)
**infantile Refsum disease
* rhizomelic chondrodysplasia punctata spectrum

Do we need another node between peroxisome biogenesis disorder
and Zellweger syndrome  for the Zellweger spectrum?

**Comment by maglott** [comment]
@ahamosh , @GARDInfoCenter any insights?

**Comment by maglott** [comment]
And I do see that all the gene-specific subclasses should not be under Zellweger syndrome, given that PEROXISOME BIOGENESIS DISORDER 3B; PBD3B is not a Zellweger

NCIT does have a node for Zellweger spectrum.
http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C146639

**Comment by kanems** [comment]
Just following up, this remains an unresolved issue. @nicolevasilevsky Can you look into this please?

**Comment by ahamosh** [comment]
Ok, Not sure exactly what the question is.  OMIM has Zellweger which is neonatal onset and lethal and then NALD and IRD are listed peroxisomal biogenesis disorders which have prolonged survival, but overlap.  They are not lethal in the first year, hence the separation.  The descriptions in 214100 or 601539 explain this.  We also don't have a Zellweger spectrum.  We use the term Zellweger with more lethal biogenesis disorders (numbered with an A).

**Comment by nicolevasilevsky** [comment]
I am also unclear what the question is.

@maglott and @kanems Would you like to request a new term? We do have MONDO_0019234 'peroxisome biogenesis disorder' which is equivalent to NCIT:C146639  Zellweger spectrum.

Would you like a rearrangement of the current hierarchy?

**Comment by maglott** [comment]
The original question was establishing relationships as in GeneReviews.  
Peroxisome biogenesis disorders as a parent.
Peroxisome biogenesis disorders
*  Zellweger spectrum disorder
** Zellweger syndrome

NORD (https://rarediseases.org/rare-diseases/zellweger-spectrum-disorders/) does  equate Peroxisome biogenesis disorders and Zellweger spectrum.  I am not an expert. Just asking whether they should be equated or not given as I read it rhizomelic chondrodysplasia punctata spectrum is a peroxisome biogenesis disorder but not in the zellweger spectrum.

**Comment by nicolevasilevsky** [comment]
Currently Zellweger syndrome is a child of 'peroxisome biogenesis disorder' which is equivalent to NCIT:C146639 Zellweger spectrum.

I am also not an expert, so I cannot comment if it is appropriate for 'peroxisome biogenesis disorder' to be equivalent to Zellweger spectrum, but that is how we currently have it modeled in Mondo.

MONDO_0015776 'rhizomelic chondrodysplasia punctata' is not a child of peroxisome biogenesis disorder in Mondo (it is a child of MONDO_0016398 'peroxisomal disease with epilepsy').

I may be misunderstanding, but it seems like this current classification is okay?

**Comment by maglott** [comment]
If I thought it was OK I would not have created the ticket.  Again, I am not an expert either, but Nancy Braverman is and she authored https://www.ncbi.nlm.nih.gov/books/NBK1270/ where it states

> Rhizomelic chondrodysplasia punctata type 1 (RCDP1), a peroxisome biogenesis disorder (PBD) has a classic (severe) form and a nonclassic (mild) form.

And https://www.ncbi.nlm.nih.gov/books/NBK1448/, specifically https://www.ncbi.nlm.nih.gov/books/NBK1448/#pbd.Nomenclature, where the distinctions are made that I tried to suggest.

We are trying to be consistent with MONDO, but have reservations about equating peroxisomal biogenesis disorder with Zellweger spectrum.

**Comment by nicolevasilevsky** [comment]
@cmungall and @pnrobinson could you please weigh in? Thanks!

**Comment by ahamosh** [comment]
In OMIM we treat RCDP as a Peroxisome biogenesis disorder, but not as part of the Zellweger spectrum.  Not sure it helpful, but I did get a clarification from Joanna and Anne on the OMIM team.

**Comment by nicolevasilevsky** [comment]
- [ ] Zwelleger should not be an exact syn for 'peroxisome biogenesis disorder'
- [ ] add grouping class for 'Heimler syndrome 1' and 'Heimler syndrome 2' (https://en.wikipedia.org/wiki/Heimler_syndrome)

@maglott https://rarediseases.org/rare-diseases/zellweger-spectrum-disorders/
based on the NORD page, it doesn't seem that zellweger spectrum disorders is justified as a separate class (discussing with @cmungall now)

**Comment by maglott** [comment]
Thanks
