### ISSUE TITLE
[NTR] GTP cyclohydrolase I deficiency

### ISSUE THREAD

**Issue by jennygoldstein** [monarch-initiative/mondo#1491]
Background: Based on discussion with the ClinGen Aminoacidopathy Gene Curation Expert Panel and ClinGen Lumping and Splitting Working Group chair, the following change is requested.
To best capture the spectrum of disease for GTP I cyclohydrolase deficiency, we propose to have a parent term, “GTP Cyclohydrolase I deficiency” (would need new MONDO ID), with child terms “Dystonia 5” (keeping the current MonDO ID, text definition, and synonyms) and “GTP Cyclohydrolase I deficiency with hyperphenylalaninemia” (MONDO:0009314; updating the term name from “GTP cyclohydrolase I deficiency” and using the current text description and synonyms for MONDO:0009314).

**Preferred term label:** GTP cyclohydrolase I deficiency. (Would need a new MonDO ID; Note that a change is being requested to the preferred term label for the current entry that is labeled GTP cyclohydrolase I deficiency, see below) 

**Synonyms** GTPCH deficiency 

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
 GTP cyclohydrolase I, which is encoded by GCH1, catalyzes the first reaction, and rate-limiting step, in the biosynthesis of tetrahydrobiopterin (BH4) from GTP. GTP cyclohydolase I deficiency, with the consequent reduction in BH4, reduces the activity of three BH4-cofactor dependent enzymes - phenylalanine hydroxylase, tyrosine hydroxylase, and tryptophan hydroxylase. GTP cyclohydrolase I deficiency encompasses a spectrum of disease that includes autosomal dominant and autosomal recessive forms (PMID:19234759), with severity correlating with the residual enzyme activity. Individuals who are heterozygous for pathogenic variants in GCH1 have symptoms ranging from none (due to reduced penetrance) to dopa-responsive dystonia, which is the most common presentation in symptomatic cases, to rarer neurological presentations such as adult-onset "benign" parkinsonism, various types of focal dystonia, and symptoms simulating cerebral palsy or spastic paraplegia (PMID:19332422). Hyperphenylalaninemia is absent, and patients respond well to treatment with levodopa. Individuals who are homozygous or compound heterozygous for pathogenic variants in GCH1 typically present with hyperphenylalaninemia, often identified by newborn screening, and severe neurological features and due to very low or undetectable enzyme activity. Treatment with levodopa, BH4, and 5-hydroxytryptophan can improve the symptoms but does not prevent development of severe encephalopathy (PMID:22729819). Rare cases of GTP cyclohydrolase I deficiency with a phenotype that is intermediate in severity between dopa-responsive dystonia and the severe autosomal recessive form have also been described, supporting the existence a phenotypic spectrum of disease (PMID:9566389, PMID:9667588, PMID:18044725, PMID:18276179, PMID:20818608, PMID:20842687, PMID:29471552).

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**  Tetrahydrobiopterin metabolic process disease (MONDO:0045014)

We propose that the above entry would be a parent term for:
- “Dystonia 5”, MONDO:0007494 (all details in the current entry remain the same)
AND
- “GTP Cyclohydrolase deficiency with hyperphenylalaninemia”, MONDO:0009314. Currently, the term name for MONDO:0009314 is “GTP cyclohydrolase I deficiency”. We propose changing the term label to ““GTP cyclohydrolase I deficiency with hyperphenylalaninemia” and to keep the description and synonyms that are currently used for MONDO:0009314.

We greatly appreciate your consideration of this request and would welcome any feedback.

## Attribution: ORCID: 0000-0002-5655-9589

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@cmungall could I ask for some guidance with this one:

The request is to:
- rename the orphanet term to from `GTP Cyclohydrolase I deficiency` to `GTP Cyclohydrolase I deficiency with hyperphenylalaninemi` (MONDO:0009314)
- and create a new grouping class called `GTP Cyclohydrolase I deficiency`

and the hierarchy would  be:
`GTP Cyclohydrolase I deficiency` (new term)
-`GTP Cyclohydrolase I deficiency with hyperphenylalaninemia` (MONDO:0009314) (OMIM:128230, Orphanet:2102)  
-`Dystonia 5` (OMIM:128230, Orphanet:98808)

Is this okay?

And if we do this, should I obsolete MONDO:0009314 and create new classes for `GTP Cyclohydrolase I deficiency` and `GTP Cyclohydrolase I deficiency with hyperphenylalaninemia`?

**Comment by cmungall** [comment]
I agree with your proposed course of action and the obsoletion, with one modification. The OMIM:128230  should only be equivalenced to a single MONDO, not two. Also let's coordinate with Orphanet to resolve the naming confusion

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet @annieolry @Orphanet 
FYI - we renamed Orphanet:2102 to GTP Cyclohydrolase I deficiency with hyperphenylalaninemia in Mondo.
