### ISSUE TITLE
Missing parent (MP)  argininosuccinic aciduria MONDO:0008815

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1492]
DOID:14755
Definition | Parents
An amino acid metabolic disorder that involves the accumulation of argininosuccinic acid (ASA) in the blood and urine.

MONDO:0008815
Argininosuccinic aciduria (ASA) is a disorder of urea cycle metabolism 

(causative genes are  also 
GO:0042450 | arginine biosynthetic process via ornithine
pathway)

is missing a parent to "amino acid metabolic disorder"

**Comment by cmungall** [comment]
Thanks for the fix @nicolevasilevsky - not you can also make an assertion that this results from the disruption of GO:0042450 and it will auto-classify under "amino acid metabolic disorder"
