### ISSUE TITLE
MP  hyperargininemia  /argininosuccinic aciduria / ornithine translocase deficiency

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1493]
All of these are urea cycle disorders, but also amino acid disorders

hyperargininemia MONDO:0008814
Arginase deficiency is a rare autosomal recessive amino acid metabolism disorder

argininosuccinic aciduria
Description
Argininosuccinic aciduria (ASA) is a disorder of urea cycle metabolism most c

ornithine translocase deficiency MONDO:0009393
Hyperornithinemia-hyperammonemia-homocitrullinuria syndrome (triple H syndrome) is a disorder of urea cycle metabolism characterized.....
(I wonder why this is called a 'translocase deficiency""? Causative gene is  ornithine aminotransferase not  a translocase)
but this is clearly within an amino acid metabolism pathway

arginine catabolic process to proline via ornithine

**Comment by ValWood** [comment]
In DO "urea cycle disorder" is a descendant of "amino acid metabolism" disorder.

If always true this relationship could be instantiated. If not the parent will need adding to these individual terms.

**Comment by nicolevasilevsky** [comment]
Hi @ValWood I am a bit unclear what the request is here - would you mind outlining the action items for this ticket? Thank you!

**Comment by nicolevasilevsky** [comment]
Ah, I think I understand - MP=missing parent.

In Mondo, 'urea cycle disorder' is a child of 'inherited amino acid metabolic disorder', which is inferred to be a child of 'amino acid metabolism disease'.

I added 'urea cycle disorder' as a parent of 'inborn disorder of urea cycle metabolism and ammonia detoxification' and I _think_ this addresses the issue.

**Comment by ValWood** [comment]
thanks, I'm so used to using MP I forgot to spell it out.
