### ISSUE TITLE
Large number of false positives for carbohydrate metabolic disease

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1494]
Mondo term (MONDO:0037792)

None of these gene products are directly involved in 'carbohydrate metabolism"

https://www.pombase.org/results/from/id/d2d6ddb3-5bc1-413d-8029-f1bb7dc67107

although some might appear to be by the product names they are really only transferring large carbohydrate moieties onto proteins (they are really defects in protein glycosylation, or glycolipid biosynthesis which isn't carbohydrate metabolism _per se_ (the carbohydrate is alteady formed it is only being transferred)

that would apply to this subset
https://www.pombase.org/results/from/id/81a2214c-6c61-41f6-9f7e-f9a9a0801e79

the rest
https://www.pombase.org/results/from/id/e68ff05e-b392-4534-98ec-53cffb51ddc6
just look wrong?
To access the disease click on the link and go to "disease association" in the left hand menu

**Comment by nicolevasilevsky** [comment]
Hi Val- I'm not sure what the request is here. Is there an issue with the children of 'carbohydrate metabolism disease' in Mondo?

**Comment by nicolevasilevsky** [comment]
pinging @ValWood

**Comment by ValWood** [comment]
HI,

The problem is that we have a large number of  disease gene orthologs classed as 'carbohydrate metabolism'
https://www.pombase.org/term/MONDO:0019214
which do not seem to be correct.

For example, this is the subset which are not directly involved in carbohydrate metabolism (although some of these may affect carbohydrate metabolism causally and may  therefore be OK)
https://www.pombase.org/results/from/id/9cbcaa62-8b19-4722-862e-d0817cf7e59c

For example, this subset, are defect in glycosylation, 
https://www.pombase.org/results/from/id/46704da8-38d3-4aa7-bbc3-7c41c07c4b30
which are not defect in carbohydrate metabolism (carbohydrate metabolism is upstream of the construction  and attachment of the carbohydrate containing N-glycan structure to proteins).

It will take a while to locate to  the terms with  incorrect parentage in this set, as there could be many. Probably the best way forwards  is to find the "big bang for buck" issues which are likely to fix a lot, and see what is left.

I'll kick off with the first one in the "glycosylation" list
SRD5A3-CDG (pombe dfg10)
has ancestor "congenital disorder of glycosylation (MONDO:0015286)"
which has ancestors   "carbohydrate metabolism disease"

To me, this seems wrong (and would not be inferred from GO https://www.ebi.ac.uk/QuickGO/term/GO:0006486)

This change (I.e removal of  carbohydrate metabolism disease as a parent of congenital disorder of glycosylation 
) would likely fix over half of the potential problems.

@cmungall @pnrobinson  does this sound OK to you?

**Comment by nicolevasilevsky** [comment]
this subclass relationship between 'congenital disorder of glycosylation' and 'inborn carbohydrate metabolic disorder' comes from DO, MeSH, and NCIT
DOID:5212
MESH:D018981
NCIT:C84615

I'm not sure if we want to remove the parent class. I'll let @cmungall comment.

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] remove this parent class, reference this ticket on the ExcludeSubclassOf, include Val's ORCID
- [ ] let NCIt know we removed this relationship
