### ISSUE TITLE
[Obsolete]  'neurodegenerative disease with dementia'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1498]
**Mondo term (ID and Label)**
 MONDO_0020136 'neurodegenerative disease with dementia'

**Reason for deprecation**
This is a grouping class and not every child term includes dementia, for example, MONDO_0018926 'human prion disease' - patients with human prion disease eventually develop dementia, but it is not a disease that is necessarily a type of dementia.

**Suggested replacement or term to consider**
consider: neurodegenerative disease

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,

Following up on this (I'm looking for a good test case to demonstrate downstream effect for Open Targets). I see that the obsoletion email for MONDO_0020136 'neurodegenerative disease with dementia' was sent out on May 16th and there have been no comments here. I'm taking the liberty to tag this ticket as high priority so it gets into the next release please. Thanks!
