### ISSUE TITLE
Missing Orphanet Diseases

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#150]
_From @drseb on November 24, 2017 10:14_

Hi,

I can't seem to find several Orphanet diseases in MONDO (obo version).

The complete list is:
```
not found Orphanet:1894
not found Orphanet:156177
not found Orphanet:50817
not found Orphanet:2720
not found Orphanet:226316
not found Orphanet:2058
not found Orphanet:2672
not found Orphanet:1664
not found Orphanet:2703
not found Orphanet:2547
not found Orphanet:3374
not found Orphanet:2184
not found Orphanet:2725
not found Orphanet:465508
not found Orphanet:2321
not found Orphanet:3419
not found Orphanet:158014
not found Orphanet:1773
not found Orphanet:2715
not found Orphanet:2705
not found Orphanet:1321
not found Orphanet:2158
not found Orphanet:3360
not found Orphanet:2111
not found Orphanet:2033
not found Orphanet:2258
not found Orphanet:1323
not found Orphanet:1167
not found Orphanet:2048
not found Orphanet:95501
not found Orphanet:1767
```

To show an example I took "Orphanet:156177" which is "Retinal ciliopathy due to mutation in Usher gene". When looking at the [disease hierachy in Orphanet](http://www.orpha.net/consor/cgi-bin/Disease_Classif.php?lng=EN&data_id=151&PatId=17107&search=Disease_Classif_Simple&new=1), I find that all of the following are not found:
```
"Ciliopathy ORPHA:363250"
"Retinal ciliopathy ORPHA:156165"
"Retinal ciliopathy due to mutation in Usher gene ORPHA:156177"
```

Only Usher syndrome ORPHA:886 is found. I especially wonder why "Ciliopathy ORPHA:363250" is not in MONDO, as I found a seemingly good match, i.e.:

```
[Term]
id: MONDO:0005308
name: ciliopathy
def: "A ciliopathy is a genetic disorder of the cellular cilia or the cilia anchoring structures, the basal bodies, or of ciliary function." [http://en.wikipedia.org/wiki/Ciliopathy]
xref: DOID:0060340 {source="MONDO:equivalentTo", source="EFO:0003900"}
xref: EFO:0003900 {source="MONDO:equivalentTo", source="MONDO:Leader"}
xref: MESH:D002925 {source="EFO:0003900"}
xref: SCTID:86204009 {source="EFO:0003900"}
is_a: MONDO:0003847 {is_inferred="true"} ! genetic disease
```

Can you clarify why these Orphanet entries are excluded and especially why MONDO:0005308 does not have an xref to ORPHA:363250?

Thanks for any clarifications.

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#420_

**Comment by nicolevasilevsky** [comment]
_From @cmungall on December 6, 2017 20:53_

we've been piggybacking off the EBI ORDO effort, looks like these aren't present:

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_1894

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_156177

Maybe ORDO lags behind?

@siiraa @SimonJupp I forgot what we discussed, should we take over the XML2OWL part? Would be good to stay in sync here.

**Comment by nicolevasilevsky** [comment]
_From @simonjupp on December 6, 2017 23:3_

Orphanet maintain the Ordo OWL file that was last updated in July (according to OLS). Maybe Marc @Orphanet can comment on how often this is being generated from the Orphanet db?

The Ordo imported into EFO will most likely be further behind as we don't have a clean way to import and update Ordo in EFO just yet, although we have been manually importing new Ordo terms into EFO as we've needed them.

**Comment by nicolevasilevsky** [comment]
_From @cmungall on December 7, 2017 2:59_



On 6 Dec 2017, at 18:03, Simon Jupp wrote:

> Orphanet maintain the Ordo OWL file that was last updated in July 
> (according to OLS). Maybe 
> Marc [@Orphanet](<https://github.com/orphanet>) can comment on how 
> often this is being generated from the Orphanet db?

OK, thanks for the clarification. I'll want to hear back

> The Ordo imported into EFO will most likely be further behind as we 
> don't have a clean way to import and update Ordo in EFO just yet, 
> although we have been manually importing new Ordo terms into EFO as 
> we've needed them.

OK. Just to clarify for others reading this thread, mondo is not using 
the Ordo with EFO (although EFO is itself integrated), we treat Ordo as 
it's own first class entity and we pull from 
http://www.orphadata.org/data/ORDO/ordo_orphanet.owl.zip of which the 
latest is ordo_orphanet_2.4.owl
  from July as you say.

**Comment by nicolevasilevsky** [comment]
Looks like some of these are still missing, I checked the list above and these are not in MONDO:

not found Orphanet:156177
not found Orphanet:50817
not found Orphanet:226316
not found Orphanet:2058
not found Orphanet:1664
not found Orphanet:2703
not found Orphanet:2547
not found Orphanet:3374
not found Orphanet:2184
not found Orphanet:3419
not found Orphanet:1773
not found Orphanet:2258
not found Orphanet:1167
not found Orphanet:95501

**Comment by cmungall** [comment]
where did the original list come from?

> not found Orphanet:2058

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_2058

**Comment by nicolevasilevsky** [comment]
@drseb made this ticket originally. Seb, can you comment?

**Comment by drseb** [comment]
If I remember correctly, these are items for which we have HPO annotations, which I expected to find in MONDO.

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] check if the terms [here](https://github.com/monarch-initiative/mondo/issues/150#issuecomment-384799993) are in Mondo
- [ ] if they are not in Mondo, check OLS to see if they have been obsoleted from Orphanet
- [ ] if they are in Orphanet and not in Mondo, make a new ticket and mention the term(s) needs to be added in next Orphanet slurp and mention this ticket

**Comment by nicolevasilevsky** [comment]
these are not in Mondo:
Orphanet:2703
Orphanet:3374
Orphanet:3419
Orphanet:1773
Orphanet:2258
Orphanet:1167
Orphanet:95501
