### ISSUE TITLE
missing cancer inheritance

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1506]
Action items:

- [x] review MONDO:0009693 | plasma cell myeloma, should this be a subclass of cancer? the malignant form is an exact synonym
_The alt def in NCIT is: A malignant neoplasm of the bone marrow composed of plasma cells._

- [ ] question from Val: but I still don't understand the precise relationship between neoplasm and cancer.

_updated 10/22/21 NV_

----

myeloid neoplasm (MONDO:0005170)
does not map to cancer (MONDO:0004992)

**Comment by ValWood** [comment]
and
B-cell chronic lymphocytic leukemia (MONDO:0004948)

**Comment by nicolevasilevsky** [comment]
In Mondo, neoplasms are siblings of cancer, so I think that explains why myeloid neoplasm (MONDO:0005170) is not a descendent of cancer.

But it seems like B-cell chronic lymphocytic leukemia (MONDO:0004948) should be. It is a child of 'leukemia (disease)' which is a child of 'hematopoietic and lymphoid cell neoplasm'.

@cmungall should 'leukemia (disease)' be asserted to be a child of 'cancer'? Or is there a better way to address this?

**Comment by ValWood** [comment]
Makes sense, I'm never sure about  the cancer  vs. neoplasm ones, but some appear to clearly be cancers.

- Should there be a relationship between the neoplasm and a full blown cancer?
- Should we be annotating to 2 separate disorders?

**Comment by nicolevasilevsky** [comment]
cancer is a child of neoplasm.

> Should we be annotating to 2 separate disorders?

I am not sure.

Are there any actions required for this ticket?

**Comment by nicolevasilevsky** [comment]
Hi Val,
In Mondo, we distinguish between neoplasm as a benign or malignant growth, and cancer, which is defined as a malignant neoplasm, and is a child of neoplasm.

I added a superclassOf assertion to plasma cell myeloma:
relationship: has_modifier PATO:0002097 {source="https://orcid.org/0000-0001-5208-3432"} ! neoplastic, malignant

and now it is a subclass of immune system cancer.

I will close this but if there are other issues that pop up, please open a new ticket, thanks!
