### ISSUE TITLE
[NTR] chilblain lupus erythematosus

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1507]
**Preferred term label:**
chilblain lupus erythematosus

**Synonyms**
CHLE, Hutchinson lupus

**Comment**
I don't know if this is equivalent to chilbain lupus or not, but according to the second reference it has multiple etiologies and should not be represented as genetic
"CHLE is a rare variant of LE that presents as sporadic or as an autosomal inherited form,"

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Some articles:
https://jofskin.org/index.php/skin/article/view/655: 
Chilblain lupus erythematosus (CHLE), also known as Hutchinson lupus, is rare form of chronic cutaneous lupus erythematosus.

https://www.karger.com/Article/FullText/488543
Chilblain lupus erythematosus (CHLE) is a rare, chronic variant of lupus erythematosus (LE), sometimes associated with other forms of cutaneous (CLE) or systemic LE (SLE) [1, 2].

https://jamanetwork.com/journals/jamadermatology/fullarticle/478189

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
likely http://purl.obolibrary.org/obo/MONDO_0015574
**Your nano-attribution (ORCID)**

**Comment by maglott** [comment]
FWIW, SNOMED does not use chilblain lupus, and UMLS has chilbain lupus as a synonym of chilblain lupus erythematosus.  So it may be correct to treat chilblain lupus erythematosus, Hutchinson disease , and CHLE as valid for MONDO_0019557

**Comment by nicolevasilevsky** [comment]
I added CHLE, Hutchinson lupus as synonyms to MONDO_0019557, and the text def from Orphanet

**Comment by maglott** [comment]
Super.  Thanks.
