### ISSUE TITLE
Hallucinogen-Persisting Perception Disorder

### ISSUE THREAD

**Issue by galyea-gard** [monarch-initiative/mondo#1508]
Hallucinogen-Persisting Perception Disorder

According to DSM-5, Hallucinogen Persisting Perception Disorder is caused by intoxication with hallucinogen drugs, especially LSD.  It is defined as the recurrence of perceptive disturbances that firstly develop during intoxication. The contents of the perception and visual imagery range extensively. DSM-5 and previous DSM editions report a list of the most common symptoms experienced by HPPD patients, but only a few symptoms have been described in the professional literature. The main group of symptoms reported by Criterion A of the DSM-5 are visual disturbances. In fact, as in the vast majority of induced psychoses, visual hallucinations are notably more common than auditory (PMID: 29547576)
PMID: 27822679 
ICD-10-CM code: F16.183
MSD-5 code 292.89  F16.983
Parent term (Substance use related  disorders  -   Hallucinogen abuse]

**Comment by nicolevasilevsky** [comment]
I added this as a child of 'perceptual disorders', as the def of Hallucinogen abuse says: A substance abuse that involves the recurring use of hallucinogenic drugs despite negative consequences. -> I think this could occur even after one use of a hallucinogenic drug, it doesn't have to be recurring abuse.

**Comment by galyea-gard** [comment]
Thank you Nicole!
