### ISSUE TITLE
missing parent: hereditary nonpolyposis colon cancer (MONDO:0018630)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1509]
hereditary nonpolyposis colon cancer (MONDO:0018630)
This term does not have the parent 

cancer MONDO:0004992
should this be added?

**Comment by nicolevasilevsky** [comment]
I think so!

**Comment by ValWood** [comment]
Its a strong disposition though, probably one of the most high expressivity inherited cancers (MutL and MutS family  DNA repair).

Aren't most of the hereditary cancers dispositions with very high expressivity?

**Comment by ValWood** [comment]
For example this is a susceptibility and you have this  as a "cancer' decendant

**Comment by nicolevasilevsky** [comment]
> For example this is a susceptibility and you have this as a "cancer' descendant: https://www.pombase.org/term/MONDO:0013669

yes, you are right.

I am not sure how to answer this. I'll have to turn this over to @cmungall.

**Comment by nicolevasilevsky** [comment]
@ValWood I think this can be closed, per https://github.com/monarch-initiative/mondo/issues/1627, we added 'familial colorectal cancer' as a parent and now this is a descendent of cancer.
