### ISSUE TITLE
congenital factor VII deficiency MONDO:0009211 vs factor VII deficiency MONDO:0002244

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1511]
**Mondo term (ID and Label):**
congenital factor VII deficiency MONDO:0009211 vs factor VII deficiency MONDO:0002244

**Xref that should be fixed (ID and label):**

The CUI for the congenital subset is C1394919 not C0015503, which seems more appropriate for 
factor VII deficiency MONDO:0002244
**Other comments:**
If Mondo is going to retain the distinction between F7 deficiency and the congenital subset, then  these should not be synonyms for congenital factor VII deficiency 
factor VII deficiency
F7 deficiency
factor 7 deficiency

**Comment by nicolevasilevsky** [comment]
> If Mondo is going to retain the distinction between F7 deficiency and the congenital subset, then these should not be synonyms for congenital factor VII deficiency
factor VII deficiency
F7 deficiency
factor 7 deficiency

These are related synonyms, I think it is okay to keep these. Let me know if you disagree.

**Comment by maglott** [comment]
The display from Monarch https://monarchinitiative.org/disease/MONDO:0009211  does not make any distinction between related synonyms and synonyms.  This is thus confusing to anyone using the Monarch display (where MedGen is going to point our users)  It is likely just me, but I have never understood the use of 'related synonym' . If it strictly means something like 'Did you know we also have a related term xxx, so consider using xxx instead?', then I think it should not be reported with the word synonym.
