### ISSUE TITLE
Need New MONDO ID for NAA10-related syndrome

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#1512]
Preferred term label: NAA10-related syndrome

Synonyms/Other Disease Assertions: Odgen Syndrome, Lenz Microphthalmia Syndrome, Autism Spectrum Disorder, Intellectual Disability

Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): Variants in NAA10 are currently associated with two diseases in Monarch: Odgen Syndrome and Lenz Microphthamia Syndrome. It has also been associated with non-syndromic Intellectual Disability.  The ID/Autism experts have reviewed the disease assertions/available literature and have determined that evidence suggests that patients that have variants in the NAA10 gene demonstrate symptoms such as developmental delay, ID, ASD, hypotonia, facial dysmorphism, cardiac anomalies, and/or skeletal anomalies. The ID/Autism GCEP suggests that the term "NAA10-related syndrome" is more suited to the symptoms displayed in patients with variants in NAA10. (PMIDs: 29558889, 31127942, 28967461, 31174490, 31088393, 29748569, 26522270, 24431331, 23871722, 27094817, 25099252)
 

Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): X-Linked Syndromic Intellectual Disability

Your nano-attribution: ClinGen ID/Autism Gene Curation Expert Panel

**Comment by maglott** [comment]
I am confused about suggesting Autism Spectrum Disorder and  Intellectual Disability as synonyms for
 NAA10-related syndrome.   Don't synonyms require that the terms mean the same thing?  Are all ASD or ID are based on NAA10 misfunction?

**Comment by tibingaman** [comment]
Hello,

I apologize for creating confusion – I suggested them as other disease entities associated with NAA10. There are no synonyms.

Thank you,
Taylor

**Comment by cmungall** [comment]
thanks @tibingaman - of the terms you mention, which would be classified under your proposed term? E.g Ogden syndrome arises from mutations in NAA10, so it would presumably go here

@nicolevasilevsky - perhaps we should add something to the issue template to suggest existing terms that should be moved underneath the proposed term

In fact we might even want an issue template for diseases defined entirely by gene such as this one

**Comment by nicolevasilevsky** [comment]
Looks like I added:
'microphthalmia, Lenz type'
'Ogden syndrome'

as children as part of of this PR.

**Comment by tibingaman** [comment]
@ErinRiggs The ID/Autism GCEP decided to lump into NAA10-related syndrome. Looping you in to ensure that this is correct. Thank you!

**Comment by ErinRiggs** [comment]
Yes, that is correct.  I agree with the two terms Nicole added as children (Lenz/Ogden).  I think what Taylor meant earlier is simply to convey that intellectual disability and autism are observed features as part of this phenotypic spectrum (reflected in the definition), and not that they should be synonyms.  Please let me know if there are any other questions on this one!

**Comment by tibingaman** [comment]
Hello, will the new identifier be MONDO:0100124? Thank you for your help!

**Comment by nicolevasilevsky** [comment]
> Hello, will the new identifier be MONDO:0100124? Thank you for your help!

@tibingaman sorry for the delayed reply - yes!

This term will be available in the next release, end of July/early Aug
