### ISSUE TITLE
MIS-C [NTR]

### ISSUE THREAD

**Issue by cbizon** [monarch-initiative/mondo#1518]
**Preferred term label:**
Multisystem Inflammatory Syndrome in Children  Associated with Coronavirus Disease 2019

**Synonyms**
MIS-C

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
See https://emergency.cdc.gov/han/2020/han00432.asp

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

**Your nano-attribution (ORCID)**

**Comment by cmungall** [comment]
for modeling diseases like this, should it be is-a or a causal relation to COVID-19? I think the latter.

**Comment by cbizon** [comment]
I agree, but I don't claim any deep understanding of this particular case beyond popular news reports.

**Comment by nicolevasilevsky** [comment]
We already have the term MONDO_0100163 'SARS-CoV-2 Kawasaki-like syndrome', which I think is the same thing, I added synonyms.
