### ISSUE TITLE
ORDO constitutional vs acquired alplastic anemia

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#153]
_From @cmungall on October 23, 2017 17:30_

Consider: https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_68383

![image](https://user-images.githubusercontent.com/50745/31903435-ee79615e-b7dc-11e7-940d-54b5ad0cdc48.png)

Aplastic anemia is already classified under 'rare constitutional anemia'. This means that every instance of Aplastic anemia is an instance of 'rare constitutional aplastic anemia'. Which would render the distinct class RCAA superfluous - and its sibling 'rare acquired aplastic anemia' unsatisfiable.

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#415_

**Comment by cmungall** [comment]
Can you post a ticket on the ordo tracker

**Comment by nicolevasilevsky** [comment]
this has been reclassified in Mondo and this ticket can be closed.
