### ISSUE TITLE
childhood absence epilepsy

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1535]
**Mondo terms (ID and Label):**
childhood absence epilepsy MONDO:0010826
epilepsy, childhood absence, susceptibility to, 1  MONDO:0020759
**Xrefs that should be fixed (ID and label):**
https://www.omim.org/phenotypicSeries/PS600131: Epilepsy, childhood absence
https://www.omim.org/entry/600131: EPILEPSY, CHILDHOOD ABSENCE, SUSCEPTIBILITY TO, 1; ECA1

**Other comments:**

**Comment by nicolevasilevsky** [comment]
HI @maglott I hope to get to this soon, we're planning to have a call to discuss how to address susceptibility terms soon. Thanks for reporting this

**Comment by nicolevasilevsky** [comment]
https://www.omim.org/entry/600131: EPILEPSY, CHILDHOOD ABSENCE, SUSCEPTIBILITY TO, 1; ECA1 is part of the phenotypic series in OMIM:
https://omim.org/phenotypicSeries/PS600131

**Comment by nicolevasilevsky** [comment]
Update:

The OMIMPS seems to combine a mix of diseases and susceptibility to diseases:

- [OMIM:611136](https://omim.org/entry/611136)  Epilepsy, childhood absence, susceptibility to, 13 (MONDO_0012627 'epilepsy, idiopathic generalized, susceptibility to, 13'). OMIM includes susceptibility to, 4 and 5 in this. These are synonyms for type 13 in Mondo.
- [OMIM:611136](https://omim.org/entry/611136)  Epilepsy, juvenile myoclonic, susceptibility to, 5 (see above)
- [OMIM:607681](https://omim.org/entry/608681)   Febrile seizures, familial, 8 (MONDO_0011891 'febrile seizures, familial, 8'). OMIM includes  susceptibility to, 2
- [OMIM:607681](https://omim.org/entry/607681)  Generalized epilepsy with febrile seizures plus, type 3 (included with Febrile seizures, familial, 8)
- [OMIM:600131](https://omim.org/entry/600131) EPILEPSY, CHILDHOOD ABSENCE, SUSCEPTIBILITY TO, 1 (MONDO_0020759 'epilepsy, childhood absence, susceptibility to, 1')
- [OMIM:612269](https://omim.org/entry/612269) Epilepsy, childhood absence, susceptibility to, 5 (MONDO_0012843 'epilepsy, childhood absence, susceptibility to, 5')
- [OMIM:611942](https://omim.org/entry/611942) Epilepsy, childhood absence, susceptibility to, 6 (MONDO_0012763 'epilepsy, childhood absence, susceptibility to, 6')
- [OMIM:611942](https://omim.org/entry/611942) Epilepsy, idiopathic generalized, susceptibility to, 6 (included with OMIM:611942)

**Comment by nicolevasilevsky** [comment]
In OMIM:
![image](https://user-images.githubusercontent.com/6722114/144133812-1abf7517-9753-4fc9-abb4-1543022df0e8.png)
