### ISSUE TITLE
 autism (disease)  MONDO:0005260 missing MeSH ID

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#1547]
autism (disease) (MONDO:0005260)
Xref that should be fixed (MeSH: D001321)

**Other comments:**
Just wondering why MeSH: D001321 is no longer included in this entry?

Thanks

**Comment by nicolevasilevsky** [comment]
Hi @lcdaugherty - I still see it listed as an xref, where are you looking?

![image](https://user-images.githubusercontent.com/6722114/82630049-70f1e980-9ba6-11ea-9a64-1297d18b0d3d.png)

**Comment by lcdaugherty** [comment]
Hi @nicolevasilevsky - I was looking here: https://monarchinitiative.org/disease/MONDO:0005260, am I looking at the wrong place?

<img width="1837" alt="mondo_mesh_query_20200522" src="https://user-images.githubusercontent.com/14925172/82659224-3e84d280-9c20-11ea-9913-a0df391281d3.png">

**Comment by nicolevasilevsky** [comment]
@lcdaugherty - ah, I see! I'm not sure why it isn't showing up in Monarch.

@kshefchek can you help investigate? Thanks!

**Comment by kshefchek** [comment]
Monarch is currently running http://purl.obolibrary.org/obo/mondo/releases/2020-03-05/mondo.owl . I can close when we push our next data release (likely a few weeks out)

**Comment by lcdaugherty** [comment]
@nicolevasilevsky is this anything to do with absoluteMatch and closeMatch? 

The MeSH ID for autism is not equivalent to the MONDO term -- in the OWL file  OWL.edition of MONDO (v1.0), it's neither an equivalent class, nor an exact match. 

https://monarchinitiative.org/disease/MONDO:0005260 only shows mappings that use the equivalence classes, not the cross references (as far as I can tell?) 

OWL file states that the identifier is an exact match e.g. for autism:
   <owl:Class rdf:about="http://purl.obolibrary.org/obo/MONDO_0005260">
        <skos:exactMatch rdf:resource="http://purl.obolibrary.org/obo/DOID_12849"/>

BUT, the  MeSH ID is denoted closeMatch not exactMatch
<oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">MONDO:0005260</oboInOwl:id>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">autism (disease)</rdfs:label>
        <skos:closeMatch rdf:resource="http://identifiers.org/mesh/D001321"/>

So, would the next release change the associated MeSH ID associated to autism (disease) MONDO:0005260 from closeMatch to exactMatch?

Sorry for all these questions, as you can see I am getting a bit confused!

**Comment by maglott** [comment]
@kshefchek , @nicolevasilevsky 
A little off topic, but trying to reduce my confusion, too.
I can tell frm https://www.ebi.ac.uk/ols/ontologies/mondo which release is being displayed.
* where is the same information from Monarch?
* what is the update cycle in Monarch for Mondo?

**Comment by kshefchek** [comment]
The monarch release cycle is dependent on a lot of factors, I would say at best monthly and at worst quarterly

**Comment by kshefchek** [comment]
> where is the same information from Monarch?

@maglott I've added a ticket here for this to be added https://github.com/monarch-initiative/monarch-ui/issues/340

**Comment by lcdaugherty** [comment]
@nicolevasilevsky I might have a handful of similar cases to this, so would be good to know if the following is true or not?

> So, would the next release change the associated MeSH ID D001321 associated to autism (disease) MONDO:0005260 from closeMatch to exactMatch?

**Comment by nicolevasilevsky** [comment]
@lcdaugherty apologies - I didn't realize this is what you were asking for - I made the MESH xref equiv to the Mondo term. This will be available in the next release in late July/early Aug

**Comment by lcdaugherty** [comment]
@nicolevasilevsky thank you for clarifying. I am returning to ontology related work after a few years not working with them, so it good to be able to make contributions again (where there is agreement of course!)
