### ISSUE TITLE
pulmonary fibrosis and/or bone marrow failure, Telomere-related, 1 (MONDO:0013878)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1548]
**Term** 
pulmonary fibrosis and/or bone marrow failure, Telomere-related, 1 (MONDO:0013878)

**def**
Any pulmonary fibrosis and/or bone marrow failure, Telomere-related in which the cause of the disease is a mutation in the TERT gene.

**question**
Is this a disease?
It looks like the symptoms of dyskeratosis congenita, autosomal dominant 1 (MONDO:0007485)
A dyskeratosis congenita that has_material_basis_in an autosomal recessive mutation of TERT on chromosome 5p15.33.

A disease which is already a descendant of
dyskeratosis congenita (MONDO:0015780)
Dyskeratosis congenita (DC) is a rare ectodermal dysplasia that often presents with the classic triad of nail dysplasia, skin pigmentary changes, and oral leukoplakia associated with a high risk of bone marrow failure (BMF) and cancer.

**Comment by ValWood** [comment]
or 
.dyskeratosis congenita, autosomal dominant 1 (MONDO:0007485)
A dyskeratosis congenita that has_material_basis_in an autosomal dominant mutation of TERC on chromosome 3q26.2.

i.e  Dyskeratosis congenita
seems to be a grouping them with the same meaning  

or similar? I can't quite figure this one out

**Comment by nicolevasilevsky** [comment]
Hi @ValWood My apologies, I don't understand the question. Would it be possible to reorganize the comments to add some headers to your comments, like I did above? (Term, def, question). That would be super helpful! :) 

For MONDO:0013878, in the first part,  I believe you are asking if this is a valid disease and if we should consider obsoleting it. I agree that this seems like a collection of phenotypes. Although sometimes diseases are named as such, we see this a lot in Mondo. 

@cmungall could you advise? Note MONDO:0013878 comes from OMIM: OMIM:614742

**Comment by ValWood** [comment]
According to this PFBMFT1
https://www.ncbi.nlm.nih.gov/gtr/conditions/C3553617/
it isn't a TERT specific thing

**Comment by nicolevasilevsky** [comment]
The OMIM record says it is due to a mutation in the TERT gene: https://www.omim.org/entry/614742
I just skimmed it, but it looks like there are references supporting that.

**Comment by nicolevasilevsky** [comment]
The NCBI page says TERT is an associated gene:
![image](https://user-images.githubusercontent.com/6722114/82582194-86cfc200-9b46-11ea-8d1f-c95324efa4e5.png)

Is this the question? I am still a bit unclear - apologies!

**Comment by ValWood** [comment]
It seems that    PFBMFT1 is a less severe later onset thing.

But the definition of 
pulmonary fibrosis and/or bone marrow failure, Telomere-related, 1 (MONDO:0013878)
isn't necessary and sufficient to differentiate it from

autosomal recessive dyskeratosis congenita 4 (MONDO:0027353)
A dyskeratosis congenita that has_material_basis_in an autosomal recessive mutation of TERT on chromosome 5p15.33.

which is also TERT, and also  has a symptom of "high risk of bone marrow failure (BMF) and cancer." see the parent term dyskeratosis congenita (MONDO:0015780),  for the BMF part it is a feature of this class.

I don't think MONDO:0027353 is the same as PFBMFT1 but based on the current defs it is difficult to establish this.

**Comment by ValWood** [comment]
Oh I see what is happening now!
When I cut and past  a query I usually start with the term, and the term definition. I cut and paste from the PomBAse page. Unfortunatly when I do this only the definition gets transferred, not  the term name. I need to copy paste them individually.
I keep seeing issues where I was sure I put the  term name first!

If you see any like this just ping me and I will add the term I am querying. Sorry about that, it's super-confusing!

**Comment by nicolevasilevsky** [comment]
> I don't think MONDO:0027353 is the same as PFBMFT1 but based on the current defs it is difficult to establish this.

I understand now! The definition of 'pulmonary fibrosis and/or bone marrow failure, Telomere-related, 1' was created using a Mondo pattern. In OMIM, they say the mutation is on chromosome 5p15. Would this def be sufficient:

Any pulmonary fibrosis and/or bone marrow failure, Telomere-related disease in which the cause of the disease is a mutation in the TERT gene on chromosome 5p15.

**Comment by ValWood** [comment]
This def would still have the same problem


autosomal recessive dyskeratosis congenita 4 (MONDO:0027353)
A dyskeratosis congenita that has_material_basis_in an autosomal recessive mutation of TERT on chromosome 5p15.33.

Is also
a disease which has_material_basis_in in the same gene (TERT) and has BMF (according to its parent)

**Comment by ValWood** [comment]
Ah no  this is OK. I am misreading. The pulmonary fibrosis has to be present in MONDO:0013878 and the BMF May be present.

can close....
