### ISSUE TITLE
ORDO: Text definitions sometimes truncated

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#155]
_From @cmungall on October 21, 2017 18:12_

E.g. https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_199 has a text definition `).`

![image](https://user-images.githubusercontent.com/50745/31854586-840139a6-b650-11e7-9be8-f131687ac05a.png)

The def on the orpha site is fine:
http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=199

so looks like introduced when going from xml2owl?

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#412_

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
The definition of Orphanet:199 ‘Cornelia de Lange syndrome’ looks good in the latest OLS update (09 May 2018), so looks like the changes have propagated there. I haven’t checked bioportal. I will unassign myself from this ticket now. Should there be any future issue related to OLS, please create a ticket here: https://github.com/EBISPOT/OLS/issues
Thanks! :-)

**Comment by nicolevasilevsky** [comment]
Sounds good, closing
