### ISSUE TITLE
 embedded linking to other terms

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1550]
Description
Bjrnstad syndrome is characterized by congenital sensorineural hearing loss and pili torti. Less than fifty cases have been reported so far. The hearing loss usually becomes evident very early in life, often in the first year. Pili torti, a condition in which the hair shaft is flattened and twisted, makes the hair very brittle and patients develop hair loss in the first two years of life. Bjrnstad syndrome is transmitted as an autosomal recessive condition. It is caused by mutations in the BCS1L gene. Mutations in this gene also cause GRACILE syndrome (see this term).

when I see something in a definition "(see this term)"
I would expect this to be see up to function as a link.
So I was going to see if we could do that, but it isn't a link in MONDO

https://monarchinitiative.org/disease/MONDO:0009872

 Would it be better to put the MONDO:ID in brackets so links could be established easily ?

**Comment by nicolevasilevsky** [comment]
I have to double check, but I think this def comes from Orphanet. We should delete the (see this term).

**Comment by nicolevasilevsky** [comment]
> Would it be better to put the MONDO:ID in brackets so links could be established easily ?

I'm not sure what you mean. Are you looking in Monarch?

**Comment by ValWood** [comment]
I'm looking  both
here https://www.pombase.org/term/MONDO:0009872
and here]
https://monarchinitiative.org/disease/MONDO:0009872

if you put (see MONDO:0011308) in the brackets we would both be able to establish internal linking in our respective resources.

**Comment by nicolevasilevsky** [comment]
Ah, got it. I'm not sure that @cmungall would want to reference other Mondo classes from the definitions in Mondo. I just deleted the (see this term).
