### ISSUE TITLE
 Nephronophthisis

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1557]
According to the recent review at Orphanet, Nephronophthisis has 3 categories distinguished by age of onset, with gene-specific types for each.
MONDO does not have nodes for  Infantile nephronophthisis,  Juvenile nephronophthisis,  Late-onset nephronophthisis, so the ORPHA XRefs are incorrectly associated with a gene-specific type.
Example: nephronophthisis 16 MONDO:0014158, which is an infantile form, reports an exact XREF to exactMatch Orphanet:93591, which is defined as Infantile nephronophthisis, not a gene-specific form.
1. Should nodes be added to MONDO for the 3 subtype?
2. Is there any method that prevents attaching an XRef from Orphanet that references multiple genes (7 in this case) to gene-specific disease labels?

**Comment by nicolevasilevsky** [comment]
1. Yes, I think we should create new classes for Infantile nephronophthisis, Juvenile nephronophthisis, Late-onset nephronophthisis that are equivalent to the Orphanet classes.
- [ ] obsolete 'nephronophthisis 16'
- [ ] create new class for 'nephronophthisis 16' that is equiv to OMIM:615382
- [ ] obsolete 'nephronophthisis 1'
- [ ] create new class for 'nephronophthisis 1' that is equiv to OMIM:256100
- [ ] create new classes for Infantile nephronophthisis and Juvenile nephronophthisis, that are equivalent to the Orphanet classes.
_Note: we already have Late-onset nephronophthisis (MONDO_0019742)_

2. >Is there any method that prevents attaching an XRef from Orphanet that references multiple genes (7 in this case) to gene-specific disease labels?

@matentzn is this a check you could implement?

**Comment by matentzn** [comment]
Will work on this in next meeting! On Agenda.

**Comment by nicolevasilevsky** [comment]
@maglott 
scratch what I wrote above.

Mondo does have classes for Infantile nephronophthisis, Juvenile nephronophthisis, Late-onset nephronophthisis:

Mondo ID | Label | syn |Orphanet xref | orphanet label | OMIM xref 
-- | -- | -- | -- | -- | --
MONDO_0011190 | 'nephronophthisis 2' | infantile nephronophthisis 2 | Orphanet:93591*| Infantile nephronophthisis | OMIM:602088
MONDO_0009728 | 'nephronophthisis 1' | nephronophthisis, familial juvenile | Orphanet:93592 | Juvenile nephronophthisis | 256100
MONDO_0019742 | 'late-onset nephronophthisis' | n/a |Orphanet:93589 | Late-onset nephronophthisis | n/a

* I added this in the pull request

**Comment by nicolevasilevsky** [comment]
I am going to close this when the pull request is merged, please reopen if this does not adequately address your question.

**Comment by nicolevasilevsky** [comment]
@maglott the fix above didn't work, because 'nephronophthisis 16' is already equiv to Orphanet:93591 Infantile nephronophthisis.

I need to look into this further.

**Comment by nicolevasilevsky** [comment]
@maglott do you know which genes should be associated with which subset/onset?

**Comment by maglott** [comment]
If we use OMIM as the authority for the gene-specific terms, the  listing in the phenotypic series may help:
https://www.omim.org/phenotypicSeries/PS256100

**Comment by nicolevasilevsky** [comment]
Thanks @maglott 

I think the table above is correct. I just revised the xref on 'nephronophthisis 16' to Orphanet Infantile nephronophthisis to be related, not equiv. Orphanet xrefs both of these OMIM records on their website, but we can only have one be equiv in Mondo.

**Comment by maglott** [comment]
Thanks. That helps.
