### ISSUE TITLE
fatal infantile encephalocardiomyopathy ancestry

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1566]
4 | fatal infantile encephalocardiomyopathy (MONDO:0015487) 
51 | cardiomyopathy (MONDO:0004994)

I have annotations to both of these terms, but nothing in the  intersection.

0 | (cardiomyopathy (MONDO:0004994) AND fatal infantile encephalocardiomyopathy (MONDO:0015487)) | ...

Should MONDO:0015487 be a type of MONDO:0004994?

**Comment by ValWood** [comment]
should MONDO:0004994 also be a 

mitochondrial disease with hypertrophic cardiomyopathy (MONDO:0016327)

(historically I had COX15 which is MONDO:0014051 annotated to MONDO:0016327 too)

**Comment by nicolevasilevsky** [comment]
I added cardiomyopathy as a superclass of 'fatal infantile encephalocardiomyopathy'

I don't think it makes sense for MONDO:0004994 cardiomyopathy to be a child of mitochondrial disease with hypertrophic cardiomyopathy (MONDO:0016327).
