### ISSUE TITLE
Question progeroid and premature ageing, difference?

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1567]
What is the difference between

premature aging syndrome MONDO:0019303 and a 
progeroid syndrome MONDO:0015333

the only difference I have annotation wise are to 
de Barsy syndrome (MONDO:0017569)

but this is defined 
A rare autosomal recessive genetic disorder characterized by facial dysmorphism (down-slanting palpebral fissures, a broad flat nasal bridge and a small mouth) with a _**progeroid appearance**_, large and late-closing fontanel, cutis laxa (CL), joint hyperlaxity, athetoid movements and hyperreflexia, pre- and postnatal growth retardation, intellectual deficit and developmental delay, and corneal clouding and cataract.

if they are different, maybe  de Barsy syndrome (MONDO:0017569)
should move under MONDO:0015333

**Comment by kallia-p** [comment]
premature aging syndrome MONDO:0019303 and progeroid syndrome MONDO:0015333 are disease grouping terms that are separate in Orhanet.
Premature aging ORPHA:79389 is a group of disorders classified under the Orphanet classification of Rare genetic skin disease ORPHA:68346. Progeroid syndrome ORPHA:139033 is a group of disorders classified under Rare developmental defect during embryogenesis ORPHA:93890. There is quite a bit of overlap between the children of the 2, approximately 9 of them are shared between the two Orphanet grouping disease terms. de Barsy syndrome (MONDO:0017569) is classified under premature aging in Mondo which is in line with the Orphanet classification. 

![image](https://user-images.githubusercontent.com/77484553/135052413-ee154210-ffb7-46be-b38c-751aa2a74dea.png)
![image](https://user-images.githubusercontent.com/77484553/135052372-724b216a-c900-4151-9b88-995cbd9a2b9b.png)

In Mondo progeroid syndrome is a SubClassOF premature ageing syndrome and the source of this is cjm (Chris Munghal?) I am not quite sure what is the reason behind this assertion. 
![image](https://user-images.githubusercontent.com/77484553/135054448-ba5e4ff7-5c37-42cb-863e-1799f2f2605f.png)

Progeroid is a Greek word that means pre-mature ageing by the way! Let me know if you need me to investigate further or we are fine to keep in line with Orphanet grouping disease terms.

**Comment by nicolevasilevsky** [comment]
Hi @ValWood- the definition of de Barsy syndrome  says it has progeroid appearance but that doesn't necessarily mean it is a progeroid syndrome, from what I understand. I think we should leave this classification as is. Please reopen if you disagree or if further action is needed.
thanks!

**Comment by ValWood** [comment]
progeroid appearance means 'premature ageing features', so if it has these features I assume it must be a progeroid syndrome? Although I agree that in all cases x features might not == 'x syndrome', that depends how the syndrome  itself is classified. But this definition  of  progeroid syndrome is very generic:

"A group of rare genetic disorders which mimic physiological aging, making affected individuals appear to be older than they are" which seems to fit "De Barsy syndrome"

Googling I found https://pubmed.ncbi.nlm.nih.gov/4076251/
title De Barsy syndrome--an autosomal recessive, progeroid syndrome

and https://rarediseases.info.nih.gov/diseases/49/de-barsy-syndrome
has a synonym " Progeroid syndrome of De Barsy"

@pnrobinson  is this an exception?

**Comment by ValWood** [comment]
Also, I no longer have the ability to re-open tickets (I used to).

**Comment by pnrobinson** [comment]
Progeria means that patients age quickly and survive until their teens. This is the classic progeria disease: https://omim.org/entry/176670. I would suggest a good terminology is that progeroid syndrome be used for syndromes associated with a substantially reduced life expectancy due to "premature aging". Additionally there are syndromes with characteristics that cause affected people to "look older than they are", for instance because of wrinkly skin, and sometimes one sees the term progeroid appearance. I think that is the case here. To my knowledge, Cutis laxa, autosomal recessive, type IIIA is not a progeroid syndrome in this sense. @ahamosh is this accurate?

**Comment by ahamosh** [comment]
There are many entries in OMIM that are "progeroid syndromes" that aren't associated with reduced life expectancy.  De Barsy (I have only seen one) have remarkably wrinkly skin and are thin and have severe MR.  There are only two progeria syndromes HGPS (the classic) and Nestor-Guillermo Progeria syndrome, which should probably be changed to progeroid syndrome.  I don't think that there is consistency in the two Orphanet trees.  I can think about this more, but not right now.

**Comment by nicolevasilevsky** [comment]
> Also, I no longer have the ability to re-open tickets (I used to).

I sent you an invite to this repo, you may need to accept it, then you should be able to open/close issues.

**Comment by nicolevasilevsky** [comment]
@ValWood @pnrobinson @ahamosh we have many classes subclassified under 'progeroid syndrome' in Mondo in the list below. The **bold** terms are classified as a child of 'progeroid syndrome' only by Orphanet. 

My questions:
- [ ] should we exclude 'progeroid syndrome' as a superclass for the terms in the list below, except progeria.
- [ ] Progeria is a grouping class from OMIM (https://omim.org/phenotypicSeries/PS176670). I think this may be equivalent to the Orphanet grouping class 'progeroid syndrome' and these terms could potentially be merged. 

_Current children of progeroid syndrome:_
- **'acquired partial lipodystrophy'**
- **'acroosteolysis-keloid-like lesions-premature aging syndrome'**
- **'ataxia-telangiectasia-like disorder 2'**
- **'atypical Werner syndrome'**
- **'Berardinelli-Seip congenital lipodystrophy'**
- **'Cockayne syndrome'**
- '**Donohue syndrome'**
- **'familial partial lipodystrophy, Dunnigan type'**
- 'Fontaine progeroid syndrome'
- **'lipodystrophy-intellectual disability-deafness syndrome'**
- '**mandibular hypoplasia-deafness-progeroid syndrome'**
- **'mandibuloacral dysplasia'**
- **'Ogden syndrome'**
- progeria
- '**progeria-short stature-pigmented nevi syndrome'**
- **'progeroid features-hepatocellular carcinoma predisposition syndrome'**
- **'pseudoprogeria syndrome'**
- '**Rothmund-Thomson syndrome'**
- **'SHORT syndrome'**
- **'Werner syndrome'**
- **'xeroderma pigmentosum'**
- **'xeroderma pigmentosum-Cockayne syndrome complex'**

_Proposed hierarchy for progeroid syndrome:_

- progeroid syndrome (equivalent to progria (OMIM:PS176670) and Orphanet:139033
  - 'Hutchinson-Gilford progeria syndrome'
  - 'Nestor-Guillermo progeria syndrome'
  - 'Wiedemann-Rautenstrauch syndrome'

**Comment by nicolevasilevsky** [comment]
I will proceed with removing the children from progeroid syndrome, as noted above.

**Comment by ValWood** [comment]
So no Werner syndrome?
A rare inherited syndrome characterized by premature aging with onset in the third decade of life

**Comment by nicolevasilevsky** [comment]
Thanks, @ValWood, I'll fix that.

**Comment by ValWood** [comment]
Also Cockayne syndrome I think?

**Comment by ValWood** [comment]
PMID: 35748794 
PMID: 19181118
PMID: 29752965

**Comment by nicolevasilevsky** [comment]
Cockayne syndrome is still a child, per this ticket from Peter: #6023

**Comment by ValWood** [comment]
OK thanks (currently Cockayne syndrome  is not is_a progeroid syndrome)

I guess I'm a bit confused by the proposed 3 term heirarchy.

**Comment by nicolevasilevsky** [comment]
Reopening this - here is the current hierarchy for progeroid syndrome, please let me know if you see any issues.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/6722114/225042391-b168f3ce-79e9-4f96-8d71-027c0e544e7c.png">

**Comment by ValWood** [comment]
got it!

**Comment by nicolevasilevsky** [comment]
I believe everything has been addressed, closing.
