### ISSUE TITLE
[NTR/Uner Tan Syndrome

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1571]
name: Uner Tan Syndrome
synonym: recessive quadrupedalism

Uber Tan Syndrome is a tubulinopathy with material basis in  TUBB2B
this def is likely not sufficient to distinguish from other tubulinopathies , some characteristics are below)

variant R390Q
quadrupedal locomotion
cerebellar hypoplasia
NOT basal ganglia malformations (typical of TUBB2B )

Reference PMID: 28013290

Parents
global cerebellar malformation (MONDO:0017114)?
movement disorder MONDO:0005395? or dystonic disorder (MONDO:0003441)?
autosomal recessive disease (MONDO:0006025)

https://orcid.org/0000-0001-6330-7526

**Comment by ValWood** [comment]
and parent monogenic disease (MONDO:0000275)

**Comment by nicolevasilevsky** [comment]
this was added:
MONDO_0100144
