### ISSUE TITLE
hypertelorism (disease) MONDO:0007778

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1574]
hypertelorism (disease) MONDO:0007778
Description
A condition in which there is an abnormally increased distance between two organs or bodily parts; most often, this term is referring to an increased distance between the orbits (orbital hypertelorism).

I had an annotation to this term for atp6 which I have removed. But while looking at it it struck me that this is too general to refer to a specific disease.

OMIM Although hypertelorism means an excessive distance between any paired organs (e.g., the nipples), the use of the word has come to be confined to ocular hypertelorism. Hypertelorism occurs as an isolated feature and is also a feature of many syndromes, e.g., Opitz G syndrome (145410), Greig cephalopolysyndactyly (175700), and Noonan syndrome (163950) (summary by Cohen et al., 1995). 

If it is meant to refer to a disease, maybe you need to confine to  "orbital hypertelorism", or it doesn' really make any sense as a grouping term. (increased distance between any two things?). 

Or maybe it does make sense, but then it should be  an ancestor of   other terms like

de Hauwere Leroy adriaenssens syndrome MONDO:0022936
iris dysplasia, orbital hypertelorism, and psychomotor retardation

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall could you weigh in on this?

I agree that the children don't seem appropriate ('bagatelle Cassidy syndrome' and 'Krauss Herman Holmes syndrome')- I think we should exclude hypertelorism as a parent.

**Comment by pnrobinson** [comment]
Hypertelorism is a phenotypic feature. Rarely it occurs as an isolated finding, but in that case the disease should be called Isolated or perhaps Idiopathic hypertelorism. 
I do not think it makes sense to have Hypertelorism be a grouping node in MONDO -- if we had it, then that would mean that we woulc logically need to mirror the entire HPO in MONDO. So I would suggest obsoletion.

**Comment by nicolevasilevsky** [comment]
Thank you @pnrobinson!
