### ISSUE TITLE
maternally-inherited spastic paraplegia synonym, def, parent

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1575]
maternally-inherited spastic paraplegia

Suggest an update
synonym Maternally-inherited SPG (exact)
synonym MT-ATP6-related mitochondrial spastic paraplegia (exact, if not this would be a new child term)

there is also a def here:
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=320360
MT-ATP6-related mitochondrial spastic paraplegia is a rare, genetic, complex hereditary spastic paraplegia disorder characterized by adulthood-onset of slowly progressive, bilateral, mainly lower limb spasticity and distal weakness associated with lower limb pain, hyperreflexia, and reduced vibration sense. Axonal neuropathy is frequently observed on electromyography and nerve conduction examination.

also, this term should be and  is_a parent (I think)
MONDO:0010781 | ataxia and polyneuropathy, adult-onset

**Comment by nicolevasilevsky** [comment]
> also, this term should be and is_a parent (I think)
MONDO:0010781 | ataxia and polyneuropathy, adult-onset

Could you provide evidence for this? Thanks!

**Comment by ValWood** [comment]
Possibly it is a slightly different disorder in the same gene (MT-ATP6).

But maybe the
MT-ATP6-related mitochondrial spastic paraplegia
needs to be a new  instance of 
Maternally-inherited SPG, 
presumably there are other causative genes?

**Comment by ValWood** [comment]
So far this seems to be the only mitochondrial inherited form identified, at least from the ones we have annotated
https://www.pombase.org/term/MONDO:0015150
Although we won't have them all, we should have identified any mitochondrial associated ones.
All of the other complex hereditary spastic paraplegia seem to be autosomal.

So just the def and synonyms and this one is good.
