### ISSUE TITLE
[Obsolete] 'cytokine deficiency'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1576]
**Mondo term (ID and Label)**
MONDO_0022918 'cytokine deficiency'

**Reason for deprecation**
No children
Was added to mirror existing term
No info in GARD: https://rarediseases.info.nih.gov/diseases/9529/cytokine-deficiency

**Suggested term to consider**
HP_0011112 'Abnormality of serum cytokine level'

cc @GARDInfoCenter

**Comment by nicolevasilevsky** [comment]
@galyea-gard
do you have any objections to obsoleting this term in Mondo?
thanks!

**Comment by nicolevasilevsky** [comment]
pinging @galyea-gard

**Comment by galyea-gard** [comment]
I added this one to my list of terms to be retired when our review process is done.  Thank you Nicole!  Gioconda
