### ISSUE TITLE
[NTR/gene] Succinate-CoA ligase deficiency

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1577]
Succinate-CoA ligase deficiency

https://ghr.nlm.nih.gov/condition/succinate-coa-ligase-deficiency
Succinate-CoA ligase deficiency is an inherited disorder that affects the early development of the brain and other body systems. One of the earliest signs of the disorder is very weak muscle tone (severe hypotonia), which appears in the first few months of life.

 SUCLA2 or SUCLG1 gene. SUCLG1 gene mutations can cause fatal infantile lactic acidosis, while mutations in either gene can cause the somewhat less severe form of the condition.

 
Recent publications
 PMID: 26475597
PMID: 31240156 

**Parent term 
inborn mitochondrial metabolism disorder (MONDO:0004069)

https://orcid.org/0000-0001-6330-7526

**Comment by ValWood** [comment]
NOte that the related term for the sever form is
mitochondrial DNA depletion syndrome, encephalomyopathic form with methylmalonic aciduria (MONDO:0012791)

this term definitions says "Transmission is likely to be linked to maternal mitochondrial DNA.
but since the gene in question (see above)  is known to be SUCLG1 this comment is not true and should be removed.

**Comment by ValWood** [comment]
actually I'm happy just to annotate to the severe form ( MONDO:0009504 | mitochondrial DNA depletion syndrome 9), 

but this is also referred to as "Succinate-CoA ligase deficiency" s could this be added as a broad synonym"

**Comment by nicolevasilevsky** [comment]
> could this be added as a broad synonym"

of course, done!
