### ISSUE TITLE
[Merge] MONDO:0003436 lung oat cell carcinoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1579]
**Mondo term (ID and Label)**
MONDO:0003436 lung oat cell carcinoma

**Reason for deprecation**
lung oat cell carcinoma is a syn for MONDO_0008433 'small cell lung carcinoma'

**Term to be merged with**
MONDO_0008433 'small cell lung carcinoma'

**Comment by galyea-gard** [comment]
Hi!  We already have "small cell lung carcinoma" (preferred term by the NCI) and kept lung oat cell carcinoma. Thanks!
