### ISSUE TITLE
NTR: venom hypersensitivty

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#158]
**New term:** venom allergy 

**Synonym:** IgE- mediated venom hypersensitivity, venom hypersensitivity

**Parent:** MONDO_0005271 'allergic disease'

**Definition:** A allergic disease involving venom.

**Source:** PMID:26154789

See https://github.com/obophenotype/human-phenotype-ontology/issues/3428

add chebi venom:
https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_78505

**Comment by dosumis** [comment]
@nicolevasilevsky - could you put a difficulty label on this?

**Comment by nicolevasilevsky** [comment]
I agree with 'medium' effort- should take less than an hour

**Comment by kallia-p** [comment]
Thanks Nicole,
Kallia

**Comment by kallia-p** [comment]
Nicole is looking into importing 'venom' term from CHEBI by adding it to a text file, then we need to add Equivalent class definition.
