### ISSUE TITLE
mitochondrial complex III deficiency nuclear type 1 MONDO:0007415 def  query

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1581]
https://monarchinitiative.org/disease/MONDO:0007415
mitochondrial complex III deficiency nuclear type 1 MONDO:0007415
Description
Mitochondrial complex III deficiency is one of several conditions caused by dysfunction of mitochondria , which are specialized compartments in cells that generate more than 90% of the energy required by the body. It is a severe, multisystem disorder that includes features such as lactic acidosis , hypotonia , hypoglycemia , failure to thrive , encephalopathy , and delayed psychomotor development. Involvement of internal organs, includingliver diseaseand renal tubulopathy, may also occur. Symptoms typically begin at birth. Many affected individuals die in early childhood, but some have survived longer. It is generallycaused by mutations in nuclear DNA in the BCS1L , UQCRB and UQCRQ genes and inherited in an autosomal recessive manner.However,it may also be caused bymutations in mitochondrial DNA in the MTCYB gene, which is passed down maternally or occurs sporadically and may result in a milder form of the condition. Treatment generally focuses on alleviating symptoms and/or slowing down the progression of the disease,and effectiveness can vary among individuals.

1. this def has a lot of formatting errors
2. Is this the correct def for type I?
I thought type I was specific for BCS1L?
For example 
UQCRB  is type 3  https://monarchinitiative.org/disease/MONDO:0014064
and  UQCRQ  is type 4 https://monarchinitiative.org/disease/MONDO:0014065

**Comment by ValWood** [comment]
Also the def should say that this is a dysfunction of 

"mitochondrial respiratory chain complex III "  to distinguish from the myriad of other syndromes which affect energy production and have similar symptoms.

( I think this definition was maybe meant for the parent)?

**Comment by ValWood** [comment]
Actually, I think this term should exist, so
https://github.com/monarch-initiative/mondo/issues/1552 is out or date.

The problem is the incorrect definition assigned

**Comment by ValWood** [comment]
Out of curiosity when was the def assigned? I can't find  a ticket mentioning it, but we are not picking this up in PomBase, so I just wondered if it was recent 
@kimrutherford
https://www.pombase.org/term/MONDO:0007415

**Comment by kimrutherford** [comment]
> so I just wondered if it was recent

The definition is not in the mondo.obo from the latest release.

**Comment by nicolevasilevsky** [comment]
Strange - I don't see this definition in the mondo-edit.obo file.

@cmungall and @kshefchek do either of you have any idea where this definition came from in Monarch?

**Comment by nicolevasilevsky** [comment]
It looks like it is from https://rarediseases.org/gard-rare-disease/8295/mitochondrial-complex-iii-deficiency/

I've never seen a case those where there is a def in Monarch but not in the Mondo file.

If I add this def to Mondo, will it show up in Monarch?

**Comment by kshefchek** [comment]
Monarch is currently running http://purl.obolibrary.org/obo/mondo/releases/2020-03-05/mondo.owl , I can see this def there but must have been fixed in the last release.  I can close when we push our next data release (likely a few weeks out)

**Comment by nicolevasilevsky** [comment]
Oh yeah, I see the def there. It must have been removed in the latest release. Thanks @kshefchek!

**Comment by nicolevasilevsky** [comment]
@ValWood this term is currently undefined in the current Mondo file, I'll add a definition. (There was a def on the GARD website, but it looks like it is down at the moment, so I'll come back to this.)
