### ISSUE TITLE
Missing parent: constitutional mismatch repair deficiency syndrome (MONDO:0010159)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1583]
constitutional mismatch repair deficiency syndrome (MONDO:0010159)

does not map to 
DNA repair disease (MONDO:0021190)

**Comment by ValWood** [comment]
but it does have parents to

a immunodeficiency with severe reduction in serum IgG and IgA with normal/elevated IgM and normal number of B-cells

is that correct?
I thought the immunodeficiencies can be caused by the same genes but are distinct?

**Comment by cmungall** [comment]
> is that correct?
> I thought the immunodeficiencies can be caused by the same genes but are distinct?

I agree, this does seem dubious.

I have not reviewed the literature but looking at a recent BMJ
_Diagnostic criteria for constitutional mismatch repair deficiency syndrome: suggestions of the European consortium ‘Care for CMMRD’ (C4CMMRD)_

https://jmg.bmj.com/content/51/6/355.long

indicates that immune defects are only seen in a minority of patients.

@nicolevasilevsky I'll merge your PR which removes this classification of CMRDS. However, note that this leaves MONDO:0018040 with a single child, which is an anti-pattern.

Let's dig a little deeper here. These came from ORDO:

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_331240

![image](https://user-images.githubusercontent.com/50745/84103956-53f04f80-a9c9-11ea-8c16-853f3ee90d94.png)

and already know that ORDO has a tendency to over-classify, and to make lots of groupings of the form "disease X with [molecular] phenotypes A, B, and C", and then to classify things under that even if the phenotype is infrequent for that disease.

We're already working with @paolaroncaglia to review and obsolete these in mondo.

I would take this opportunity to look at the parent MONDO:0018040 'immunodeficiency with severe reduction in serum IgG and IgA with normal/elevated IgM and normal number of B-cells' and ask: is this a useful grouping (certainly not if it's left with a single child!)? Can we get rid of it?

**Comment by cmungall** [comment]
reopening til we deal with the single child issue.

**Comment by nicolevasilevsky** [comment]
related https://github.com/monarch-initiative/mondo/issues/1665

**Comment by nicolevasilevsky** [comment]
the single child check has been implemented, so I think this can be closed
