### ISSUE TITLE
[NTR] Hydatidiform mole, recurrent, 4

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1586]
Hydatidiform mole, recurrent, 4

This is a form associated with  c11orf80
https://www.omim.org/entry/616109

https://www.malacards.org/card/hydatidiform_mole_recurrent_4

**Comment by nicolevasilevsky** [comment]
We have this term in Mondo:
MONDO_0032747 'hydatidiform mole, recurrent, 4'

Was your intention to request a new term? This term already exists.

**Comment by ValWood** [comment]
That's odd. When I searched on 'hydatiform" I did not locate this term? (I only see 2 terms)

When I extend to "hydatidiform mole, recurrent, 4" I don't see 4, only 1&2

**Comment by ValWood** [comment]
I don't find anything with the ID either?

**Comment by nicolevasilevsky** [comment]
Where are you searching? I don't see it in Monarch, but Monarch doesn't have the latest Mondo release. It is in OLS: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0032747

**Comment by ValWood** [comment]
Oh right. I always search Monarch for terms. I  assumed it was current.
I can use OLS.
