### ISSUE TITLE
Question: genetic recurrent myoglobinuria (MONDO:0020504) parentage query

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1587]
Definition | Parents
-- | --
Genetic recurrent myoglobinuria is an inborn error of metabolism characterized by abnormal urinary excretion of myoglobin due to acute destruction of skeletal muscle fibers.

This  has parents
muscular lipidosis (MONDO:0016117)
and
disorder of phospholipids, sphingolipids and fatty acids biosynthesis with skeletal muscle predominant involvement (MONDO:0018120)

Is that correct for this disease?

I have one assignment (cox1) 

It isn't obvious from the genes, or the description that  this is a "muscular lipidosis"
I can't find anything linking "cytochrome oxidase" and lipidosis (Google)

**Comment by ValWood** [comment]
It seems that myopglobinurea is a symptom of
lipodystrophy in
https://www.omim.org/entry/605518

but is this the same disease as the MT-CO1 disorder?

**Comment by nicolevasilevsky** [comment]
@ValWood what is MT-CO1 disorder? I don't see that as a class in Mondo or OLS

**Comment by ValWood** [comment]
The entire definition is 

myoglobinuria, recurrent (MONDO:0010791)

Definition | Parents
-- | --
Genetic recurrent myoglobinuria is an inborn error of metabolism characterized by abnormal urinary excretion of myoglobin due to acute destruction of skeletal muscle fibers. Epidemiology The exact prevalence remains unknown. Clinical description In the majority of cases, the disease manifests in childhood and is often triggered by exertion or infection (febrile illness). Hypertonia, muscle stiffness and muscle pain, impaired kidney function and elevated levels of serum creatine kinase are common clinical features. Etiology Mutations in the mitochondrial DNA-encoded cytochrome C oxidase genes ( **MT-CO1 and MT-CO2** ) should be considered in patients with recurrent myoglobinuria. Recently, mutations in the LPIN1 gene (chromosome 2p21) have been reported to have a causative role in three patients with recurrent episodes of myoglobinuria, originating from consanguineous families. Genetic counseling The disorder may occur sporadically, or be inherited in either a recessive or dominant manner.

So I now think this is probably OK.
I  came across it  via MT-CO1  (pombe cox1). 
But I think the parentage is probably fine here. Closing...
