### ISSUE TITLE
Commit an export of precise logical equiv calls

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#159]
Per discussion with @GARDInfoCenter - need to commit an export of precise logical equivalence calls.

cc @GARDInfoCenter

**Comment by nicolevasilevsky** [comment]
I am not sure what this means.

@galyea-gard, do you know if this is still needed? If not, I'll close, thanks!

**Comment by galyea-gard** [comment]
Hi Nicole!  I am not sure what this means or who opened this ticket. It seems to me that this is regarding a bigger picture than just one specific question.  If needed we can open a new ticket in the future. Please let me know what you think. Thank you! Gioconda

**Comment by nicolevasilevsky** [comment]
Sounds good, i will close, thank you!
