### ISSUE TITLE
[Obsolete] 'alpha-2 deficient collagen disease'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1594]
**Mondo term (ID and Label)**
'alpha-2 deficient collagen disease'

**Reason for deprecation**
Looks like this term was obsoleted from GARD.

@GARDInfoCenter or @galyea-gard could you confirm?

**Comment by galyea-gard** [comment]
Confirming that this term was retired in GARD in 3/9/2018.  It was retired because  was based in a single report in 1979 about a boy who could have another diagnosis. Thank you!

**Comment by nicolevasilevsky** [comment]
Thank you @galyea-gard!
