### ISSUE TITLE
[Merge] MONDO_0022939 'deafness hyperuricemia neurologic ataxia'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1596]
**Mondo term (ID and Label)**
MONDO_0022939 'deafness hyperuricemia neurologic ataxia'

**Reason for deprecation**
Looks like this term was obsoleted from GARD.

**Replace by**
MONDO:0043176 'phosphoribosylpyrophosphate synthetase deficiency'

@GARDInfoCenter or @galyea-gard could you confirm?

**Comment by galyea-gard** [comment]
Confirming that this term was retired in GARD.  It was retired because it was actually referring to (duplicate)  Phosphoribosylpyrophosphate synthetase superactivity.  Thanks!

**Comment by nicolevasilevsky** [comment]
thanks @galyea-gard!
