### ISSUE TITLE
UMLS CUI xrefs that start with "CN"

### ISSUE THREAD

**Issue by saramsey** [monarch-initiative/mondo#1597]
**Mondo term (ID and Label):**

MONDO_0000023

**Xref that should be fixed (ID and label):**

UMLS:CN228161

**Other comments:**
I am confused by this UMLS cross-reference. CUIs have a "C" followed by seven digits. I cannot find this identifier in any database except MedGen. It's provenance is unclear. Has it been superseded by a newer CUI?

**Comment by nicolevasilevsky** [comment]
Hi @saramsey - I believe this probably did come from MedGen, but cannot comment on the provenance. 
@cmungall could you comment?

**Comment by maglott** [comment]
Yes, the values that start with CN are used by MedGen, when a CUI from UMLS has not been identified.
Looking at MONDO_0000023, CN228161 is the identifier assigned by MedGen; PS615438 should be added for OMIM phenotypic series.

**Comment by nicolevasilevsky** [comment]
@maglott The OMIMPS is annotated to that term:
![image](https://user-images.githubusercontent.com/6722114/83059176-59838800-a00e-11ea-902d-3420ab56f650.png)

**Comment by nicolevasilevsky** [comment]
I think this can be closed?

**Comment by saramsey** [comment]
Thank you, this is very helpful!

**Comment by saramsey** [comment]
After some experimenting, I think I have found a persistent URL that can resolve to one of these MEDGEN CN concept pages:
```
http://identifiers.org/medgen:CN207495
```
which I am shortening to the following CURIE ID:
```
medgen:CN207495
```
