### ISSUE TITLE
EFO classifies CERVICAL RIB as reproductive disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#160]
_From @cmungall on October 1, 2017 11:46_

![image](https://user-images.githubusercontent.com/50745/31054104-5c312b64-a6a3-11e7-89b6-e1c742e5255e.png)

The DO xref is to an obsolete term (no replacement or reason given):

```
[Term]
id: DOID:3102
name: cervical rib syndrome
namespace: disease_ontology
is_obsolete: true
synonym: "Arterial thoracic outlet syndrome due to cervical rib" EXACT [SNOMEDCT_2005_07_31:413577001]
```

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#405_

**Comment by nicolevasilevsky** [comment]
_From @pnrobinson on October 2, 2017 12:49_

Possibly this syndrome does have some impact on reproduction, which is why it is sooo important for MONDO to define really well what the criteria are for the hierarchy. I do not think that any of the existing disease nosologies really do such a great job of it.

-Peter


Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

New Book: Computational Exome and Genome Analysis<https://www.crcpress.com/Computational-Exome-and-Genome-Analysis/Robinson-Piro-Jager/p/book/9781498775984>

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by nicolevasilevsky** [comment]
_From @cmungall on October 2, 2017 12:57_


On 2 Oct 2017, at 13:49, Peter Robinson wrote:

> Possibly this syndrome does have some impact on reproduction, which is 
> why it is sooo important for MONDO to define really well what the 
> criteria are for the hierarchy. I do not think that any of the 
> existing disease nosologies really do such a great job of it.

I think in this case this is simply a mistake, Sira can the EFO team 
comment?

**Comment by nicolevasilevsky** [comment]
_From @jmcmurry on October 3, 2017 23:21_

Just mentioning @siiraa for comment.

**Comment by nicolevasilevsky** [comment]
_From @siiraa on October 11, 2017 8:48_

The term was requested by Open Targets that recommended this classified as a reproductive system disease. Can modify/add better classification if someone can make a recommendation please?

PS. @cmungall can you please make me a collaborator so i can close the issue that has been resolved? Thank you :)

**Comment by nicolevasilevsky** [comment]
_From @cmungall on October 21, 2017 0:48_

@siiraa - now a collaborator. But keep this open til we get to the bottom of it :-)

Would it be OK to check with the OT team what their reasoning was behind this classification? I don't like to overwrite in mondo if there was a good reason, but it seems very odd.

**Comment by nicolevasilevsky** [comment]
_From @cmungall on October 21, 2017 0:49_

And also determine if they think it is the same as https://omim.org/entry/117900

**Comment by nicolevasilevsky** [comment]
the comment above says to keep this ticket open until we get to the bottom of it.

**Comment by cmungall** [comment]
@siiraa no longer at EBI

@nicolevasilevsky can you submit to EFO?

**Comment by nicolevasilevsky** [comment]
done, closing this here

**Comment by siiraa** [comment]
@simonjupp
