### ISSUE TITLE
Request: add Mondo release product for tree viewers

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#1600]
Tree viewers such as OLS rely on abstracting ontologies such as Mondo into a tree before showing them. Users of OLS want to see:

1) associated equivalent classes
2) xrefs
3) (potentially associated genes, see Slack/Dipper discussion on slack)

For that to work, we need a Mondo release artefact that simply expresses:

OWLEquivalentClass(A,B) 

as 

OWLAnnotationAssertion(hasMondoEquivalent, A, B).

I can help to set that up, but I need your blessing @cmungall 

Also, if we want to merge in stuff like associated genes, I need some instructions on how to do that.

**Comment by nicolevasilevsky** [comment]
I believe this has been address. Please reopen if needed.
