### ISSUE TITLE
MeSH: C537666 is not a recognised xref for Becker muscular dystrophy (MONDO:0010311) 

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#1601]
Hi
I was looking at the following MONDO term in the OWL file OWL.edition of MONDO (v1.0), it is listed as having an exactMatch to MeSH: C537666, but that ID does not exist

Becker muscular dystrophy (MONDO:0010311) it has a exactMatch to MeSH: C537666
But that ID is not found/does not exist : https://www.ncbi.nlm.nih.gov/mesh/?term=C537666

For Becker muscular dystrophy (MONDO:0010311)  should the MeSH ID be: 

https://www.ncbi.nlm.nih.gov/mesh/?term=C570377 
or
https://www.ncbi.nlm.nih.gov/mesh/?term=D020388

(or none of the above?)

Thanks

**Comment by nicolevasilevsky** [comment]
This xref comes from Orphanet (cc @ana-rath-orphanet and @Orphanet). Looks like it has been retired from MeSH? 

I agree this should be updated to D020388, I will do so.

**Comment by ana-rath-orphanet** [comment]
Thank you pointing this out. Will be corrected in Orphanet as well .
Relationship (Orphanet to MeSH) ND (as Becker is a sibling of Duchenne
and not a subtype, the main MeSH code being exact for Duchenne) 

Best


Ana 

Le 2020-05-27 20:32, Nicole Vasilevsky a écrit :

> This xref
comes from Orphanet (cc @ana-rath-orphanet [1] and @Orphanet [2]). Looks
like it has been retired from MeSH? 
> 
> I agree this should be updated
to D020388, I will do so. 
> 
> --
> You are receiving this because you
were mentioned.
> Reply to this email directly, view it on GitHub [3],
or unsubscribe [4].
 

Links:
------
[1]
https://github.com/ana-rath-orphanet
[2] https://github.com/Orphanet
[3]
https://github.com/monarch-initiative/mondo/issues/1601#issuecomment-634858814
[4]

**Comment by lcdaugherty** [comment]
@nicolevasilevsky MeSH: D020388 is for Duchenne so I think that MeSH:C570377 should be added to MONDO:0010311?

**Comment by lcdaugherty** [comment]
>re: @nicolevasilevsky MeSH: D020388 is for Duchenne so I think that MeSH:C570377 should be added to MONDO:0010311?
Should I put this in as a separate request? Was this resolved?

**Comment by nicolevasilevsky** [comment]
@lcdaugherty I made this change, it should be available in the next release at the end of July/early Aug.

(Sorry for the delayed reply!)

**Comment by lcdaugherty** [comment]
@nicolevasilevsky no problem, thank you for following up and making the change.
