### ISSUE TITLE
[Revise subclass]hereditary methemoglobinemia

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1612]
**Mondo term (ID and Label)**

http://purl.obolibrary.org/obo/MONDO_0018963 

**Suggested revision and reasons**
According to MedlinePlus and OMIM, seems the hemoglobin M should be treated as subclass of hereditary methemoglobinemia, and that hemoglobin M should have children based on whether the defect is in alpha or beta globin

https://medlineplus.gov/ency/article/000562.htm

hereditary methemoglobinemia
..hemoglobin M disease
....https://omim.org/entry/617973  
....https://omim.org/entry/617971

**Comment by nicolevasilevsky** [comment]
https://omim.org/entry/617971 is equiv to hemoglobin M disease
so I don't think it makes sense for it to be a subclass of hemoglobin M disease. I made them siblings. Does this address this?

![image](https://user-images.githubusercontent.com/6722114/83213347-c3875480-a116-11ea-9ab7-569bbc30231b.png)

**Comment by maglott** [comment]
It comes down to the question of whether hemoglobin M disease is defined, as medline plus puts it, as 
'hemoglobin M disease. It is caused by defects in the hemoglobin protein itself.'
In that is true, then one subtype results from altered alpha chain and one subtype results from altered beta chain.

Is there a hemoglobinopathy expert somewhere?
