### ISSUE TITLE
[Revise subclass] Saldino-Mainzer syndrome

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1624]
**Mondo terms (ID and Label)**
http://purl.obolibrary.org/obo/MONDO_0015373
      "label" : "Saldino-Mainzer syndrome",
http://purl.obolibrary.org/obo/MONDO_0009964
      "label" : "short-rib thoracic dysplasia 9 with or without polydactyly",

**Suggested revision and reasons**
These records have exact synonyms that apper to  differ only by punctuation
"renal dysplasia, retinal pigmentary dystrophy, cerebellar ataxia and skeletal dysplasia" 
renal dysplasia-retinal pigmentary dystrophy-cerebellar ataxia-skeletal dysplasia syndrome

Are these the same things, or should "Saldino-Mainzer syndrome" have 2 subclasses, as the Orphanet record suggests via its links to OMIM

  "label" : "short-rib thoracic dysplasia 9 with or without polydactyly",
    "iri" : "http://purl.obolibrary.org/obo/MONDO_0014284",
      "label" : "short-rib thoracic dysplasia 10 with or without polydactyly",

Note:  OMIM treats Saldino-Mainzer syndrome as an alternate for SHORT-RIB THORACIC DYSPLASIA 9 WITH OR WITHOUT POLYDACTYLY

**Comment by nicolevasilevsky** [comment]
Yes, this one is confusing. OMIM seems to treat them as the same. @ahamosh do you think these should be separate classes in Mondo?

**Comment by nicolevasilevsky** [comment]
@maglott there is an annotation on 'Saldino-Mainzer syndrome' that this term is a superclass of OMIM:615630 SHORT-RIB THORACIC DYSPLASIA 10 WITH OR WITHOUT POLYDACTYLY; SRTD10, so maybe that should be added as a subclass.

Potential action item:
- [ ] add 'short-rib thoracic dysplasia 10 with or without polydactyly' as a subclass of 'Saldino-Mainzer syndrome'

**Comment by maglott** [comment]
@nicolevasilevsky , I really don't know the answer for this.  When disease experts have reviewed current classifications, we can make MONDO reflect that.

**Comment by nicolevasilevsky** [comment]
emailed Ada on 06/08/20
