### ISSUE TITLE
missing parentage Muir-Torre syndrome (MONDO:0008018)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1627]
Muir-Torre syndrome (MONDO:0008018)

Definition | Parents
Muir-Torre syndrome (MTS) is a form of hereditary nonpolyposis colon cancer (HNPCC) characterized by cutaneous sebaceous tumors, keratoacanthomas and at least one visceral malignancy, most frequently gastrointestinal carcinoma.

should be a 
familial colorectal cancer (MONDO:0023113)

Definition | Parents
-- | --
Familial colon cancer is a cluster of colon cancer within a family. Most cases ofcolon cancer occur sporadically in people with little to no family history of the condition. Approximately 3-5% of colon cancer is considered 'hereditary' and is thought to be caused by an inherited predisposition tocolon cancer that is passed down through a family in an autosomal dominant or autosomal recessive manner. In some of these families, the underlying genetic cause is not known; however, many of these cases are caused by changes ( mutations ) in the APC , MYH , MLH1 , MSH2 , MSH6 , PMS2 , EPCAM , PTEN , STK11 , SMAD4 , BMPR1A , NTHL1 , POLE , and POLD1 genes (which are associated with hereditary cancer syndromes). An additional 10-30% of people diagnosed with colon cancer have a significant family history of the condition but have no identifiable mutation in a gene known to cause a hereditary predisposition to colon cancer. These clusters of colon cancer are likely due to a combination of gene(s) and other shared factors such as environment and lifestyle. High-risk cancer screening and other preventative measures such as prophylactic surgeries are typically recommended in people who have an increased risk for colon cancer based on their personal and/or family histories.

(this definition even mentions the causative genes for Muir-Torre syndrome MLH1, MSH6, MHS2)

**Comment by ValWood** [comment]
Correction, I think it's probably the M-T parent


hereditary nonpolyposis colon cancer (MONDO:0018630)
-- | --
Hereditary nonpolyposis colon cancer (HNPCC) is a cancer-predisposing condition characterized by the development of colorectal cancer not associated with colorectal polyposis, endometrial cancer, and various other cancers (such as malignant epithelial tumor of ovary, gastric, biliary tract, small bowel, and urinary tract cancer) that are frequently diagnosed at an early age.

That should have the familial colorectal cancer (MONDO:0023113)
parent.

Probably also worth checking that  the  specific familial colorectal cancers  caused by other genes listed in the def of "familial colorectal cancer (MONDO:0023113)" are also positioned correctly under here.

**Comment by nicolevasilevsky** [comment]
@ValWood hereditary nonpolyposis colon cancer (MONDO:0018630) is not a parent of 'Muir-Torre syndrome'

I am confused - what is the specific action item?

**Comment by ValWood** [comment]
Muir-Torre syndrome (MONDO:0008018)
- a hereditary nonpolyposis colon cancer (HNPCC) see def
should be is_a hereditary nonpolyposis colon cancer (MONDO:0018630)

**Comment by ValWood** [comment]
Also currently has a parent "Muir-Torre syndrome (MONDO:0008018)"
genetic nervous system disorder
but is that true? 
I don't see a reference to this in *Any* description

characteristics (compiled from multiple sources, but most agree)
- Muir-Torre syndrome (MTS) is a rare hereditary, autosomal dominant cancer syndrome.
- characterized by the presence of at least one sebaceous gland neoplasm and at least one visceral malignancy.
- The gastrointestinal tract is the most commonly affected organ, with almost one-half of patients having colorectal cancer.

**Comment by nicolevasilevsky** [comment]
thanks @ValWood 

I cleaned up the hierarchy a bit, let me know if anything looks incorrect:

![image](https://user-images.githubusercontent.com/6722114/90083385-312f2f80-dcc7-11ea-9c7e-83a53610bb0d.png)

I assigned Chris to review the Pull Request.

**Comment by ValWood** [comment]
Looks good!
