### ISSUE TITLE
[Merge] hereditary angioedema type 3 AND  hereditary angioedema with normal c1inh

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1628]
**Mondo term(s) (ID and Label)**
http://purl.obolibrary.org/obo/MONDO_0012526
hereditary angioedema type 3
AND
http://purl.obolibrary.org/obo/MONDO_0033947
hereditary angioedema with normal c1inh

**Reason for review**

OMIM states, for HAE3: It differs from HAE types I and II (106100) in that both concentration and function of C1 inhibitor (C1NH; 606860) are normal

What is the distinction we are trying to make between these sibling terms?

**Comment by maglott** [comment]
Also, if both are kept, the capitalization of C1inh needs to be corrected.

**Comment by galyea-gard** [comment]
Hi Nicole!  Orphanet has all the subtypes (please see the classification below).   In GARD we probably will only have the parent term “Hereditary Angioedema” but I will let you know when we have decided.

ORPHA:91378   Hereditary angioedema<https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=12136&Disease_Disease_Search_diseaseGroup=Hereditary-angioedema&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Hereditary-angioedema&title=Hereditary%20angioedema&search=Disease_Search_Simple>  Synonym(s) : Hereditary bradykinine-induced angioedema ; Hereditary non histamine-induced angioedema

     *   ORPHA:528623   (Disorder)   Hereditary angioedema with C1Inh deficiency<https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=27541&Disease_Disease_Search_diseaseGroup=Hereditary-angioedema&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Hereditary-angioedema-with-C1Inh-deficiency&title=Hereditary%20angioedema%20with%20C1Inh%20deficiency&search=Disease_Search_Simple>
        *   ORPHA:100050   (Subtype of disorder)   Hereditary angioedema type 1<https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=14623&Disease_Disease_Search_diseaseGroup=Hereditary-angioedema&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Hereditary-angioedema-type-1&title=Hereditary%20angioedema%20type%201&search=Disease_Search_Simple>
        *   ORPHA:100051   (Subtype of disorder)   Hereditary angioedema type 2<https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=14624&Disease_Disease_Search_diseaseGroup=Hereditary-angioedema&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Hereditary-angioedema-type-2&title=Hereditary%20angioedema%20type%202&search=Disease_Search_Simple>
     *   ORPHA:528647   Hereditary angioedema with normal C1Inh<https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=27542&Disease_Disease_Search_diseaseGroup=Hereditary-angioedema&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Hereditary-angioedema-with-normal-C1Inh&title=Hereditary%20angioedema%20with%20normal%20C1Inh&search=Disease_Search_Simple> Synonym(s) : Hereditary angioedema with normal C1 inhibitor
        *   ORPHA:537891   ANGPT1-related hereditary angioedema with normal C1Inh<https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=27912&Disease_Disease_Search_diseaseGroup=Hereditary-angioedema&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=ANGPT1-related-hereditary-angioedema-with-normal-C1Inh&title=ANGPT1-related%20hereditary%20angioedema%20with%20normal%20C1Inh&search=Disease_Search_Simple>
        *   ORPHA:100054   F12-related hereditary angioedema with normal C1Inh<https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=14627&Disease_Disease_Search_diseaseGroup=Hereditary-angioedema&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=F12-related-hereditary-angioedema-with-normal-C1Inh&title=F12-related%20hereditary%20angioedema%20with%20normal%20C1Inh&search=Disease_Search_Simple>  Synonym(s) : Hereditary angioedema type 3
        *   ORPHA:537072   PLG-related hereditary angioedema with normal C1Inh<https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=27892&Disease_Disease_Search_diseaseGroup=Hereditary-angioedema&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=PLG-related-hereditary-angioedema-with-normal-C1Inh&title=PLG-related%20hereditary%20angioedema%20with%20normal%20C1Inh&search=Disease_Search_Simple>
Thank you!  Gioconda
