### ISSUE TITLE
Refresh OMIM ingest

### ISSUE THREAD

**Issue by Antonialock** [monarch-initiative/mondo#1629]
Hello,
I was told by @paolaroncaglia that if I can't find a large number of OMIM terms in MONDO I can ask you to refresh your OMIM ingest.

We need terms for the following disorders for UniProt mappings:

618800
618803
618804
618805
618806
618808
618810
618811
618820
618821
618822
618823
242700
618849
618850
618841
618853
301041
301043
301044
273250
301045
618828
618829
618832
618835
618838
618839
618851
618840
618845
618846
618847
618848
618852
618863
602093

Let me know if you need anything specifically from me.

Many thanks
Antonia.

**Comment by nicolevasilevsky** [comment]
@Antonialock Yes, you asked in the right place! :)

Our OMIM import was recently refreshed, and I did a quick spot check of some of these terms and I do see them in Mondo, where are you looking?

OMIM ID | Mondo ID
-- | --
618800 | MONDO_0032923
618803 | MONDO_0032925
618804 | MONDO_0032926

**Comment by Antonialock** [comment]
I'm searching the website for diseases
https://monarchinitiative.org

so if I use the top right search box with the filter set to 'disease'

609465 finds Al-Gazali syndrome 

I get "no results for 618804" or "Sandestig-Stefanova syndrome"

where can I look these up?

**Comment by nicolevasilevsky** [comment]
Unfortunately Monarch is not up to date with the current version of Mondo. We recommend using OLS:
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0032923

(I believe OLS is usually updated approx 2 weeks after each Mondo release)

cc @kshefchek

**Comment by Antonialock** [comment]
aha ok thank you Nicole! 

I'll close this for now and request any straggler term if needed

**Comment by paolaroncaglia** [comment]
Hi @Antonialock and @nicolevasilevsky ,

> Unfortunately Monarch is not up to date with the current version of Mondo. We recommend using OLS:
> https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0032923
> 
> (I believe OLS is usually updated approx 2 weeks after each Mondo release)

I can confirm that the latest Mondo release (June 1st) is already in OLS.
Thanks and have a good day.
