### ISSUE TITLE
[NTR] Fanconia anemia complementation group M

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1636]
Fanconia anemia complementation group M
(this might be present but I can't see all search results in the drop down/ Also tried OLS)

Child of Fanconi anemia (MONDO:0019391)

def

Any Fanconi anemia in which the cause of the disease is a mutation in the FANCM  gene.

**Comment by cmungall** [comment]
Does this exist?

https://pubmed.ncbi.nlm.nih.gov/28837162

cc @dnahotline 

Note: if we agree with the paper that this doesn't exist (and lack of a term in OMIM lends credence) then in these cases I am in favor of the "born obsolete" term. Add the term to MONDO, but immediately obsolete, and put a link to the paper such as the above. While this "clogs up" the ontology a bit with obsoletes, I really like having an explicit record of why a term is not in the ontology.

**Comment by dnahotline** [comment]
Hi 
I’m not sure what the question is. The paper exists. 
If the question is about FANCM science then there is a more complicated answer.
In short, we and others discovered by biochemical and mass spec that FANCM is physically part of one of Fanconi protein complexes. Yet, analysis of mutations in FANCM in patients and in populations gets more complicated. 
Let me know if you need the full story and I’ll write a summary of as we now understand it. Bottom line: The role of FANCM in FA is an emerging incomplete story.
M

**Comment by ValWood** [comment]
Yes I understand. I just found some into that FANCM was complementation group F and I wanted to make these more specific
https://www.pombase.org/term/MONDO:0019391
Instead I  will remove  Fanconi anemia (MONDO:0019391) from the 2 pombe FANCM orthologs completely https://github.com/pombase/curation/issues/2752

**Comment by dnahotline** [comment]
OK FANCM is def not FANCF!

**Comment by ValWood** [comment]
coorrection, M

**Comment by cmungall** [comment]
https://fanconi.org/wp-content/uploads/2024/03/Chapter_2._Diagnosis__July_2023_.pdf

**Comment by pnrobinson** [comment]
See Is this actually FA ?
https://pubmed.ncbi.nlm.nih.gov/34793962/

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7226125/

https://pubmed.ncbi.nlm.nih.gov/30942098/

lots

**Comment by dnahotline** [comment]
Yes and no, depending on how you define FA. Like many multifunctional proteins with novel functions,  it is not a simple answer. So if the question is if FANCM is a part of the Fanconi protein complex and does it have highly related functions—then  yes. If the question is are the cells from FA-M patients corrected by vectors expressing wild type FANCM, then no, not to my knowledge. (My lab worked on this for over a year when we and others discovered FANCM). 
A paper out this week describes new analysis of FANCM and as you can see FANCM functions are highly related to the disorder and are still emerging. https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkae727/7742388?login=false
How do we describe BRCA2 and BRCA1? These are FA genes that were only recognized as such late in the game long after BRCA2 and BRCA1 were discovered as breast cancer susceptibility genes. 
This is probably too much information but there is no simple answer 
M

**Comment by pnrobinson** [comment]
Looking at the articles, it seems there is some evidence of increased cancer risk with polymorphisms in FANCM, but the effect is substantially weaker than with other genes such as BRCA*, and there seems to be no real evidence for mendelizing variants in these papers. In any case, this is not Fanconi anemia sensu strictu, and so presumably even though FANCM interacts in the FANC pathway, it is not actually a Fanconi anemia gene. See this paper as well: https://pubmed.ncbi.nlm.nih.gov/28837162/

**Comment by dnahotline** [comment]
Yes that’s essentially what I described.

**Comment by dnahotline** [comment]
To reiterate — I understand this is complex- the test for a gene to be a FA
gene is to find a patient with a corresponding defective FA gene. This step
is hard. FA-A is the most common complementation group and yet it is still
rare. You may never find such a patient in some complementation groups. The
second step is to isolate the corresponding wild type gene and show that it
can complement the cellular defect. If you don’t ever find this rare
patient, then you technically can’t say it’s an FA gene.  However it is
part of the extended biochemical pathway.  There are also other
complexities with FANCM.

**Comment by nicolevasilevsky** [comment]
Hi @ValWood, if I am understanding correctly, it sounds like we are not in agreement to add a new term called 'fanconia anemia complementation group M'. Is it okay if I close this ticket?

**Comment by ValWood** [comment]
ok!
