### ISSUE TITLE
QC script- add note to epilepsy children that these classes should be classified elsewhere

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1640]
On the Mondo call on 6/05/20 we discussed potentially obsoleting the age of onset epilepsy terms.

I added an obsoletion candidate tag to these terms in PR https://github.com/monarch-initiative/mondo/pull/1641.

to do:
- [ ]  write a QC script to add note to epilepsy children that these classes should be classified elsewhere

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/745

**Comment by nicolevasilevsky** [comment]
Note to self:
Follow up with Ingo and Ada and ask if we still want to remove these age-of-onset classifications

**Comment by nicolevasilevsky** [comment]
@ahamosh Not sure if I ever followed up with you about this.

I feel like these classifications are wanted amongst the epilepsy community, what are your thoughts? I can follow up with Ingo too.

**Comment by ahamosh** [comment]
Hi Nicole,  I am not sure that I understand the question here.  Age of onset for epilepsy are quite variable, although usually organized broadly by infantile, childhood and adulthood, but there will be variability even among these.  I would definitely check with Ingo about how the Epilepsy GCEP of ClinGen is looking at this.  Let me know.

**Comment by nicolevasilevsky** [comment]
I emailed @ihelbig on 12/11//20:

This ticket is suggesting we obsolete the of the age of onset epilepsy terms, such as MONDO_0020071 'infantile epilepsy syndrome', etc. There is a comment on these terms:
This type of grouping class represents an older way of classifying diseases, and represented here https://www.epilepsydiagnosis.org/index.html.

However, I remember sitting down and talking with you and your colleagues about these terms, and it seemed like this was the best way to classify these terms from a clinical perspective. 

I’d love to hear your thoughts – would you like to keep these grouping terms in Mondo? If we do decide to obsolete the grouping classes, we can add an annotation to the terms that state the class has a modifier of infantile onset, so the relevant terms could still be grouped together, and this information would be preserved, just represented in a slightly different way in the ontology.

**Comment by nicolevasilevsky** [comment]
Ingo recently emailed and said the ClinGen expert group is meeting soon to discuss epilepsy nomenclature. Closing this for now, and I anticipate there will be a larger restructuring of epilepsy terms in Mondo.
