### ISSUE TITLE
Add single-child check

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#1665]
E.g for #1583 

- [ ] need to review the outcome of this check and decide what to do with the single children.
- [ ] should we annotate all the current single children with a tag and make them exempt from this check, then we can add this as a QC that causes a failed build?

**Comment by nicolevasilevsky** [comment]
there is a check for this but this doesn't trigger a fail because there are too many positive hits.

**Comment by matentzn** [comment]
Report:
https://docs.google.com/spreadsheets/d/13eIa2Ihe6ChwOjH0s-8hp0K9IGMtveIqpFTtVvuvWK4/edit#gid=534546997

```
sh run.sh make  report-reason-query-single-child-warning
```

**Comment by matentzn** [comment]
Discussed in meeting:
- [ ] use flaggedForReviewByCheck ---> sparql check (make this a general theme throughout)
- [ ] introduce a fail for future additions

**Comment by nicolevasilevsky** [comment]
I think this is done, we have a single-child check.
Please reopen if anything else is needed.
