### ISSUE TITLE
[Obsolete]records based on MIM numbers that OMIM has moved

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1675]
**Mondo term (ID and Label)**
This is just an example I found this morning.  Did not look for others.
  "iri" : "http://purl.obolibrary.org/obo/MONDO_0000911",
      "label" : "dilated cardiomyopathy 1T",
      "description" : null,
      "annotation" : {
        "comment" : [ "Editor note: consider obsoleting, see OMIM" ],
**Reason for deprecation**
Exemplar of a pattern for systematic review.
* OMIM has integrated the concept into another record
* no XRef from Orphanet or GARD

**Comment by ahamosh** [comment]
Hi Nicole and Donna, Not sure that it makes a difference by CMD1T was thought to be caused by mutations in TMPO.  Those variants are too frequent and so CMD1T no longer exists. The discussion is in CMD1A.  So, I don't know whether a merge is the right term, but you will.
Thanks, Ada

**Comment by maglott** [comment]
Thanks, Ada.  I personnally  vote for obsolete, based on the assumption that a merge would be limited to cases where what was thought to be distinct disorders are not, and the possible causitive genes differ.

**Comment by galyea-gard** [comment]
We don't list the subtypes in GARD but based in my review I agree that the term should be obsolete.  The variant that was found was reclassified in 2017 as being of unknown significance and there is not firm evidence it is CMT1A.  Thank you!
