### ISSUE TITLE
[Merge] MONDO:0009304 Gorlin-Chaudhry-Moss syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1685]
**Mondo term (ID and Label)**
MONDO:0009304 Gorlin-Chaudhry-Moss syndrome

**Reason for deprecation**
OMIM merged these terms
https://omim.org/entry/233500

**Term to be merged with**
MONDO_0012853	progeroid syndrome, Petty type'

**Comment by galyea-gard** [comment]
Gorlin-Chaudhry-Moss syndrome:  Agree with the merging (will do the same in GARD). Thanks, Gioconda
