### ISSUE TITLE
[Obsolete] MONDO:0013001	synesthesia

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1688]
**Mondo term (ID and Label)**
MONDO:0013001	synesthesia

**Reason for deprecation**
This is not a disease, and may be obsoleted or moved to another hierarchy

**Suggested term to consider**
N/A
should this be added to HPO?

def:
Synesthesia is a condition in which one sense (for example, hearing) is simultaneously perceived as if by one or more additional senses such as sight. Another form of synesthesia joins objects such as letters, shapes, numbers or people's names with a sensory perception such as smell, color or flavor.
source: https://faculty.washington.edu/chudler/syne.html#:~:text=Synesthesia%20is%20a%20condition%20in,as%20smell%2C%20color%20or%20flavor.

cc @pnrobinson

**Comment by pnrobinson** [comment]
The composer Scriabin claimed to see colors when he heard music. 
https://www.wqxr.org/story/99054-synesthesia-scriabin-and-seeing-music/
It is well worth getting acquainted with his music! If you are not familiar, take 1 minute to listen to the first prelude here! https://www.youtube.com/watch?v=ry5L3_0XVuk

**Comment by nicolevasilevsky** [comment]
I listened to the whole thing - very lovely! Thanks for the recommendation @pnrobinson!

**Comment by nicolevasilevsky** [comment]
todo: obsolete this class
