### ISSUE TITLE
[Merge] MONDO:0010195	Weissenbacher-Zweymuller syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1689]
**Mondo term (ID and Label)**
MONDO:0010195	Weissenbacher-Zweymuller syndrome

**Reason for deprecation**
OMIM merged these

**Term to be merged with**
MONDO:0008490	Stickler syndrome type 3'

**Comment by galyea-gard** [comment]
I would propose to merge it with Autosomal dominant otospondylomegaepiphyseal dysplasia instead, according to Orphanet and available literature (https://pubmed.ncbi.nlm.nih.gov/9805126/ https://www.ncbi.nlm.nih.gov/books/NBK1302/  and Genetics Home Reference. Will review it in GARD too.
