### ISSUE TITLE
[Merge] MONDO:0010272	syndromic X-linked intellectual disability type 10

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1690]
**Mondo term (ID and Label)**
MONDO:0010272	syndromic X-linked intellectual disability type 10

**Reason for deprecation**
OMIM merged these

**Term to be merged with**
MONDO:0010327	HSD10 disease

**Comment by ahamosh** [comment]
OMIM calls this HSD10 mitochondrial disease (HSD10MD)
