### ISSUE TITLE
[Merge] MONDO:0010518	Wiskott-Aldrich syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1694]
**Mondo term (ID and Label)**
MONDO:0010518	Wiskott-Aldrich syndrome

**Reason for deprecation**
OMIM merged these

**Term to be merged with**
MONDO:0013779	Wiskott-Aldrich syndrome 2

**Comment by maglott** [comment]
Do we really want to merge a generic label with a gene-specific one?   Isn't there still a distinction to be made?

**Comment by nicolevasilevsky** [comment]
@maglott good point!

I see now that there are two OMIM IDs that are equivalent to MONDO:0010518 Wiskott-Aldrich syndrome: 

[OMIM:277970](https://www.omim.org/entry/277970)
[OMIM:301000](https://www.omim.org/entry/301000)

OMIM:277970 was moved to OMIM:614493 (which is equiv to: MONDO:0013779 Wiskott-Aldrich syndrome 2)

My action item is to move the OMIM:277970 ID to MONDO:0013779 Wiskott-Aldrich syndrome 2, but not to merge those terms above.

Thanks @maglott!
