### ISSUE TITLE
Obsolete MONDO:0010601	gynecomastia, familial

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1695]
**Mondo term (ID and Label)**
MONDO:0010601	gynecomastia, familial

**Reason for deprecation**
OMIM merged these

**Term to be merged with**
MONDO:0010720	partial androgen insensitivity syndrome

**Comment by galyea-gard** [comment]
I think this should be included under Aromatase excess syndrome which has a synonym “prepubertal hereditary gynecomastia”

**Comment by nicolevasilevsky** [comment]
@galyea-gard are you suggesting that we merge MONDO:0010601 gynecomastia, familial with MONDO_0007690 'aromatase excess syndrome'?

I agree, that seems to be a better merge, rather than what is suggested above.

**Comment by galyea-gard** [comment]
Yes, I think so.  Thank you!

**Comment by nicolevasilevsky** [comment]
@ahamosh 
OMIM obsoleted this term 'gynecomastia, familial' and merged it with ANDROGEN INSENSITIVITY, PARTIAL; PAIS (https://omim.org/entry/312300), which doesn't really seem equivalent, as gynecomastia seems to be is a feature of this disease, but not the same thing

As @galyea-gard suggested, I could merge MONDO:0010601 gynecomastia, familial into MONDO_0007690 'aromatase excess syndrome', which is equiv to OMIM:139300, and synonyms for this term are: 
GYNECOMASTIA, FAMILIAL, DUE TO INCREASED AROMATASE ACTIVITY, INCLUDED
GYNECOMASTIA, HEREDITARY, INCLUDED 

This seems like the right merger to me, do you agree?

Or I could just obsolete MONDO:0010601 gynecomastia, familial and add a annotation to consider MONDO:0010720 partial androgen insensitivity syndrome, which would be in alignment with OMIM.

Thanks!

cc @cmungall

**Comment by nicolevasilevsky** [comment]
Update- per discussion with Chris, I'll just obsolete this term and add consider MONDO:0010720 partial androgen insensitivity syndrome and MONDO_0007690 'aromatase excess syndrome'

**Comment by galyea-gard** [comment]
Thank you Nicole!
