### ISSUE TITLE
[Merge] MONDO:0010804	BRCATA

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1698]
**Mondo term (ID and Label)**
MONDO:0010804	BRCATA

**Reason for deprecation**
OMIM merged these

**Term to be merged with**
MONDO:0016419	hereditary breast carcinoma

**Comment by cmungall** [comment]
shouldn't be a merge, see
https://github.com/monarch-initiative/mondo/issues/1700

**Comment by nicolevasilevsky** [comment]
I take it that this should be obsoleted?
