### ISSUE TITLE
[Merge] MONDO:0012461	bulimia nervosa, susceptibility to, 2

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1704]
**Mondo term (ID and Label)**
MONDO:0012461	bulimia nervosa, susceptibility to, 2

**Reason for deprecation**
OMIM merged these

**Term to be merged with**
MONDO:0005452	bulimia nervosa

**Comment by cmungall** [comment]
The course of action here conflicts with #1705 

also this would not be a merge. MONDO:0012461 is susceptibility caused by a particular gene. MONDO:0005452 is the actual condition
