### ISSUE TITLE
[Merge] MONDO:0014852	palmoplantar carcinoma, multiple self-healing

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1711]
**Mondo term (ID and Label)**
MONDO:0014852	palmoplantar carcinoma, multiple self-healing

**Reason for deprecation**
OMIM merged these

**Term to be merged with**
MONDO:0014089	corneal intraepithelial dyskeratosis-palmoplantar hyperkeratosis-laryngeal dyskeratosis syndrome

**Comment by cmungall** [comment]
these have the same IDs!

**Comment by nicolevasilevsky** [comment]
Oops - I fixed this above!
