### ISSUE TITLE
MONDO:0100130 adult acute respiratory distress syndrome

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1712]
**MONDO:0100130 adult acute respiratory distress syndrome**

Hi, 
Following up on https://github.com/monarch-initiative/mondo/issues/1360 and https://github.com/EBISPOT/efo/issues/736#issuecomment-611034773, would you please consider adding the following synonyms:

"adult respiratory distress syndrome" (broad), 
"adult respiratory distress syndrome, ARDS" (broad), 
"adult ARDS" (could be exact), 
"ARDS" (acronym, or related if acronym option is not applicable).

Thanks,
Paola

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia 
"adult respiratory distress syndrome" is already there as an exact syn
"adult respiratory distress syndrome, ARDS" is already there as an exact syn
"adult ARDS" is already there as an exact syn

I added ARDS as a related syn.

**Comment by paolaroncaglia** [comment]
Thanks @nicolevasilevsky ,

> "adult respiratory distress syndrome" is already there as an exact syn
> "adult respiratory distress syndrome, ARDS" is already there as an exact syn
> "adult ARDS" is already there as an exact syn

I can't see them in OLS (screen shot attached). Maybe they were added after the last release? Asking to make sure there isn't a broader issue in OLS/Mondo import.
![Screen Shot 2020-06-16 at 12 32 22](https://user-images.githubusercontent.com/4982516/84764252-b2bb5780-afcd-11ea-9b5a-c499e4570d5f.png)
 
> I added ARDS as a related syn.

Thank you!
Paola

**Comment by nicolevasilevsky** [comment]
Very interesting!

I do see these synonyms in the last release:

![image](https://user-images.githubusercontent.com/6722114/84805065-86491080-afb8-11ea-976a-f06bbc7e6be5.png)

@paolaroncaglia I think this may be an issue with Mondo/OLS
