### ISSUE TITLE
SATB2 associated disorder

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#1718]
Preferred gene-related syndrome label: SATB2 associated disorder

Synonyms: NONE

Definition (free text, please give PubMed ID, if applicable, in format PMID:#######):
The Intellectual Disability and Autism GCEP has identified that this disorder is characterized by significant neurodevelopmental disabilities with limited to absent speech, behavioral issues, and craniofacial anomalies. Most distinctive features are neurodevelopmental with invariably severely limited speech, cleft or high arched palate, dental anomalies (crowding, macrodontia, abnormal shape), and behavioral issues with or without bone or brain anomalies (PMIDs: 29436146, 31021519, 17377962). Using the term SATB2 associated disorder better includes all phenotypic features associated with variants in this gene. We would like to request that the group is made aware of this change before the next release date. You are more than welcome to @ me in the comments to make me aware of this. Thank you!

Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): Syndromic Intellectual Disability

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? NONE

**Your nano-attribution (ORCID) or URL for a working group: ClinGen ID/Autism Gene Curation Expert Panel

**Comment by nicolevasilevsky** [comment]
@tibingaman I added this as:
MONDO_0100147

It should be available in the July release
