### ISSUE TITLE
Synonym request for  invasive non-typhoidal salmonellosis

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#172]
Would you consider "non-typhoidal Salmonella bacteremia" the same as "invasive non-typhoidal salmonellosis" [1].

@cmungall do you have input on this?

[1] https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0017944

**Comment by nicolevasilevsky** [comment]
I'm not sure these two are synonymous. If you like, please reopen. It would be great to have a reference, if possible.
