### ISSUE TITLE
DKC1-related disorder

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#1720]
Preferred gene-related syndrome label: DKC1-related disorder

Synonyms: none

Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): In literature, the DKC1 gene has been associated with dyskeratosis congenita and Hoyeraal-Hreidarsson syndrome. However, literature has presented overlap of these two disease entities (PMID:10700698). The ID/Autism group would like to suggest the new term DKC1-related disorder (PMIDs: 10583221, 12437656, 14648217, 19633571). 
It would be greatly appreciated if you could please contact me in the comments with the new identifier as soon as this case is closed. @ErinRiggs 

Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): This term should appear everywhere the term "dyskeratosis congenita, X-linked" appears.

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? Yes - dyskeratosis congenita, X-linked and Hoyeraal-Hreidarsson syndrome should both be moved as child terms under DKC1-related disorders. Once DKC1-related disorder appears everywhere dyskeratosis congenita, X-linked appears, then dyskeratosis congenita, X-linked should be moved underneath DKC1-related disorders. Currently, Hoyeraal-Hreidarsson syndrome is a child term of dyskeratosis congenita, X-linked, and they should be siblings. Also, Revesz syndrome should remain as is and it should be listed under DKC1-related disorders. 

Your nano-attribution (ORCID) or URL for a working group: ClinGen ID/Autism Gene Curation Expert Panel

**Comment by nicolevasilevsky** [comment]
> This term should appear everywhere the term "dyskeratosis congenita, X-linked" appears.

@ErinRiggs I don't understand what you mean here

**Comment by nicolevasilevsky** [comment]
> Also, Revesz syndrome should remain as is and it should be listed under DKC1-related disorders.

This syndrome says it has mutations in TINF2, not DKC1. Has the evidence changed?

**Comment by nicolevasilevsky** [comment]
> Currently, Hoyeraal-Hreidarsson syndrome is a child term of dyskeratosis congenita, X-linked, and they should be siblings. 

![image](https://user-images.githubusercontent.com/6722114/87839479-da614200-c84f-11ea-9b32-b87a774dff8e.png)

If I remove the assertion that 'Hoyeraal-Hreidarsson syndrome' is a child of 'dyskeratosis congenita, X-linked', it still gets inferred to be a child of 'dyskeratosis congenita, X-linked' because of the X-linked inheritence.

**Comment by nicolevasilevsky** [comment]
I added 'DKC1-related disorder' as MONDO_0100152 but it hasn't been approved/merged into the ontology yet.

**Comment by tibingaman** [comment]
@nicolevasilevsky Hi Nicole! I'm going to try to address your questions above as best as I can. But, if anything is still confusing or you have any other questions, please just let me know!

What I meant by "This term should appear everywhere the term "dyskeratosis congenita, X-linked" appears" is that the term DKC-1 related disorder should replace the term dyskeratosis congenita, X-linked. Here is the link to the page where "DKC-1 related disorder" should appear instead of "dyskeratosis congenita, X-linked": [https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0010584]
We would like to move dyskeratosis congenita, X-linked as a child under DKC-1 and so, it makes sense to have DKC-1 related disorder as the parent term and then dyskeratosis congenita, X-linked and Hoyeraal-Hreidarsson syndrome as the children terms. 
So maybe this tree helps:
-dyskeratosis congenita
      -DKC1-related disorder
                 -dyskeratosis congenita, X-linked
                 -Hoyeraal-Hreidarsson syndrome
                
I will get back to you with more information regarding Revesz Syndrome tomorrow!

I'm not sure exactly what your question is in your comment "If I remove the assertion that 'Hoyeraal-Hreidarsson syndrome' is a child of 'dyskeratosis congenita, X-linked', it still gets inferred to be a child of 'dyskeratosis congenita, X-linked' because of the X-linked inheritence". But, perhaps this is a good thing to discuss when we meet during the Neurodevelopmental CDWG call coming up on 7/28/20? Let me know what you think and if you have any suggestions!

Thanks!
@ErinRiggs Just keeping Erin in the loop!

**Comment by nicolevasilevsky** [comment]
@tibingaman 

Does this hierarchy look correct?

![image](https://user-images.githubusercontent.com/6722114/88195544-03d5f100-cbf5-11ea-8b7a-7847dd74cba1.png)

**Comment by tibingaman** [comment]
That looks correct to me! Thank you for figuring this out! If you need any information about Revesz Syndrome, let me know! But it has only been associated with variants with TINF2 at this point and not DKC1 but causes dyskeratosis congenita. There is more information below from NORD and NIH.

FROM NORD:
https://rarediseases.org/rare-diseases/dyskeratosis-congenita/
“In addition to the many more mild manifestations of this disease we also realize that there are some rare but very severe forms of dyskeratosis congenita. These were previously known as the Hoyeraal-Hreidarsson syndrome and the Revesz syndrome but today we know that they have the same underlying abnormality and are caused at least in part by mutations in the same genes responsible for dyskeratosis congenita.”
 
FROM NIH:
Genotype-Phenotype Correlations
Genotype-phenotype correlations have not yet been studied comprehensively.
Individuals with Hoyeraal Hreidarsson and Revesz syndrome have shorter telomeres than individuals with classic DC.
In general, persons with DKC1, TINF2, and autosomal recessive PARN, RTEL1, and ACD pathogenic variants appear to have more clinical features and complications than persons with pathogenic variants in other genes known to cause DC [Alter et al 2012, Ballew et al 2013a, Ballew et al 2013b, Deng et al 2013, Le Guen et al 2013, Walne et al 2013, Guo et al 2014, Kocak et al 2014, Moon et al 2015, Tummala et al 2015]. Persons with DKC1 or TINF2 pathogenic variants may have Hoyeraal Hreidarsson syndrome. Persons with Revesz syndrome may have TINF2 pathogenic variants. Some individuals with TINF2 pathogenic variants developed bone marrow failure manifest as aplastic anemia by age ten years; others may be asymptomatic heterozygotes [Ballew & Savage 2013, Dokal et al 2015, Glousker et al 2015, Bertuch 2016].

**Comment by nicolevasilevsky** [comment]
great, thanks!
