### ISSUE TITLE
 MONDO:0023616 MONDO:0007888

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1723]
hereditary leiomyomatosis and renal cell cancer MONDO:0007888

is described in OMIN
A number sign (#) is used with this entry because multiple cutaneous and uterine leiomyomatosis with or without renal cell carcinoma, also referred to as hereditary leiomyatosis and renal cell cancer (HLRCC), is caused by heterozygous mutation in the gene encoding fumarate hydratase (FH; 136850) on chromosome 1q43.

so is it different from:
familial leiomyomatosis MONDO:0023616
An instance of leiomyomatosis that is caused by an inherited modification of the individual's genome.

I can only find information  about FH as a causative gene ?

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter 
is [Leiomyomatosis familial](https://rarediseases.info.nih.gov/diseases/3218/leiomyomatosis-familial) different from [Hereditary leiomyomatosis and renal cell cancer](https://rarediseases.info.nih.gov/diseases/10096/hereditary-leiomyomatosis-and-renal-cell-cancer) or could these two terms be merged?

**Comment by nicolevasilevsky** [comment]
Leiomyomatosis familial is currently undefined in GARD. If we should retain it, could you provide a definition?
thanks!

**Comment by galyea-gard** [comment]
Hi!  The term "familiar leiomyomatosis" was retired from GARD.  I reviewed this and found out that it was added  in 2013 as a synonym of Hereditary leiomyomatosis and renal cell cancer. The right synonyms are now listed.  Thank you for letting us know.

**Comment by galyea-gard** [comment]
Hi!  The term "familiar leiomyomatosis" was retired from GARD.  I reviewed this and found out that it was added  in 2013 as a synonym of Hereditary leiomyomatosis and renal cell cancer. The right synonyms are now listed.  Thank you for letting us know.

**Comment by galyea-gard** [comment]
Hi!  The term "familiar leiomyomatosis" was retired from GARD.  I reviewed this and found out that it was added  in 2013 as a synonym of Hereditary leiomyomatosis and renal cell cancer. The right synonyms are now listed.  Thank you for letting us know.

**Comment by galyea-gard** [comment]
Hi!  The term "familiar leiomyomatosis" was retired from GARD.  I reviewed this and found out that it was added  in 2013 as a synonym of Hereditary leiomyomatosis and renal cell cancer. The right synonyms are now listed.  Thank you for letting us know.

**Comment by nicolevasilevsky** [comment]
thanks @galyea-gard!

I deleted the duplicate comments.
