### ISSUE TITLE
[add def] Liberfarb syndrome

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#1724]
Liberfarb syndrome
Liberfarb syndrome is a progressive disorder involving connective tissue, bone, retina, ear, and brain.

https://www.omim.org/entry/618889 for description and clinical features

Caused by mutation in PISD

I'm still not sure about the rules for including syndromes but  all mapped instances (including the historical ones tested ) map to PISD so it seems to be a single gene disorder

**Comment by maglott** [comment]
OMIM: 618889
https://omim.org/entry/618889

**Comment by nicolevasilevsky** [comment]
This is available now:
MONDO_0030045 'liberfarb syndrome'

(I fixed the capitalization in #1872, which will be available in the next release)

**Comment by ValWood** [comment]
Thanks!

**Comment by ValWood** [comment]
I see the term but it is undefined.
this is a good supporting reference
https://www.nature.com/articles/s41436-019-0595-x
