### ISSUE TITLE
New Term Request: Intellectual disability and spastic paraplegia

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#1728]
Preferred term label: Intellectual disability and spastic paraplegia

Synonyms: None

Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): The ClinGen ID/Autism GCEP would like to propose a new term "Intellectual disability and spastic paraplegia". The GCEP recently curated AP4B1 where it was noted that there was no term available to describe both the spastic paraplegia phenotype and severe ID observed in individuals with this genetic disorder. PMIDs: 30543385, 29193663, 321171285, 29430868 

Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): Hereditary spastic paraplegia 47 MONDO:0013551

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

Your nano-attribution (ORCID):
ClinGen ID/Autism GCEP

**Comment by nicolevasilevsky** [comment]
Hi @tibingaman 
The description of this disease sounds like it is 'hereditary spastic paraplegia 47', which is a child of 'severe intellectual disability and progressive spastic paraplegia', meaning it has those characteristics as well.

I think this existing term has the features you describe above, here is the OMIM record:
https://www.omim.org/entry/614066

Let me know your thoughts, thanks!

**Comment by nicolevasilevsky** [comment]
pinging @tibingaman

**Comment by tibingaman** [comment]
Hi @nicolevasilevsky, thank you for the ping! We understand that hereditary spastic paraplegia 47 has been associated with variants in the "AP4" genes previously however, this term does not encompass the phenotypic spectrum described in patients with all the "AP4" genes. Some phenotypes and percent of patients with variants in AP4B1 reported with the phenotype are as follows: Early DD/ID (100%), delayed motor development (100%), infantile hypotonia (100%), delayed speech development (94%), progression to spastic diplegia (89%), loss of independent walking (88%), microcephaly (69%), epilepsy (47%) (PMID:30543385). As we see in this publication, developmental delay/intellectual disability is reported in 100% of the patients and is the first reported feature. We do not alone plan on using this term just for variants in AP4B1 but all of the AP4 genes. There are 3 others (also listed above). 

Here is a similar term in Orphanet: https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=20498&Disease_Disease_Search_diseaseGroup=Severe-intellectual-disability-and-progressive-spastic-paraplegia&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Severe-intellectual-disability-and-progressive-spastic-paraplegia&title=Severe%20intellectual%20disability%20and%20progressive%20spastic%20paraplegia&search=Disease_Search_Simple

**Comment by nicolevasilevsky** [comment]
@tibingaman sorry, I still don't understand. The term you are requesting seems to be represented by MONDO_0017241 'severe intellectual disability and progressive spastic paraplegia', which is equivalent to [ORPHA:280763 Severe intellectual disability and progressive spastic paraplegia](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=20498&Disease_Disease_Search_diseaseGroup=Severe-intellectual-disability-and-progressive-spastic-paraplegia&Disease_Disease_Search_diseaseType=Pat&Disease(s)/group%20of%20diseases=Severe-intellectual-disability-and-progressive-spastic-paraplegia&title=Severe%20intellectual%20disability%20and%20progressive%20spastic%20paraplegia&search=Disease_Search_Simple) (which you linked above).

The term is undefined in Mondo, we could add a definition to this term - would that cover your request?

The orphanet def is:

Severe intellectual disability and progressive spastic paraplegia is a rare complex spastic paraplegia characterized by an early onset hypotonia that progresses to spasticity, global developmental delay, severe intellectual disability and speech impairment, microcephaly, short stature and dysmorphic features. Patients often become non-ambulatory, and some develop seizures and stereotypic laughter.

We could extend this def to include the additional phenotypes you mention above, and reference PMID:30543385.

Let me know your thoughts!

**Comment by nicolevasilevsky** [comment]
@tibingaman pinging you about the question above.

**Comment by tibingaman** [comment]
Hi @nicolevasilevsky, thank you for the reminder. I don't believe that the words "severe" and "progressive" are terms that accurately represent what we are trying to describe. Because the severity and how it changes over time is unknown, we would rather select a term that does not have these factors, like Intellectual disability and spastic paraplegia. I think that is a good idea to include the PMID reference in the definition. Please let me know if you have any other questions.

**Comment by nicolevasilevsky** [comment]
Got it, thanks for the clarification @tibingaman.

I think this is what I should add, I'd like to verify this with @cmungall 

**label:** AP4B1-related intellectual disability and spastic paraplegia

**subclassOf:**
MONDO_0019064 'hereditary spastic paraplegia'
MONDO_0000508 'syndromic intellectual disability'
'disease has basis in dysfunction of' some AP4B1

**Def:** 
A disorder that presents with spastic paraplegia and intellectual disability in which the cause of the disease is a mutation in the AP4B1 gene.

**Source:**
PMID:30543385
PMID:29193663
PMID:321171285
PMID:29430868
https://www.clinicalgenome.org/affiliation/40006/

**Comment by tibingaman** [comment]
Thanks @nicolevasilevsky! We also know that this caused by variants in AP4E1, AP4M1, and AP4S1. So for right now, we would like to request the name not reference just one of the AP4 genes. Please let me know your thoughts and if you need any clarification from me.

**Comment by cmungall** [comment]
Is it correct to say that the common molecular feature is variants in members of the AP-4 adaptor complex?

I am not convinced we need a separate concept than MONDO:0017241/Orphanet:280763

Orphanet already calls this  "AP4 deficiency syndrome"

The objection is that "severe" and "progressive" do not apply to all cases. I think we just relabel this as  "AP4 related  intellectual disability and spastic paraplegia", and we include the orphanet label as a narrow symbol. We may also want to coordinate with them to see if they would like to synchronize primary label.

@nicolevasilevsky I think additionally we want

 - a design pattern for grouping by members of a complex, and use this here
 - I think we should also include an extensive (union) definition here, where this is the union of SPG47, ..., 51

**Comment by nicolevasilevsky** [comment]
see related ticket:
https://github.com/monarch-initiative/mondo/issues/1729

**Comment by nicolevasilevsky** [comment]
another related ticket:
https://github.com/monarch-initiative/mondo/pull/1877

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet @Anne-Pariser @Orphanet 
we renamed MONDO:0017241/Orphanet:280763 to 'AP4-related intellectual disability and spastic paraplegia'. FYI, in case you'd like to follow suit.

**Comment by nicolevasilevsky** [comment]
@tibingaman I made the changes Chris suggested here:
https://github.com/monarch-initiative/mondo/issues/1728#issuecomment-747078176

But now I am wondering how this is different from MONDO_0100176 'AP-4 deficiency syndrome'? Looks like it is more narrow in scope from the definition. So should `MONDO:0017241 'AP4-related intellectual disability and spastic paraplegia'` be a child of `MONDO_0100176 'AP-4 deficiency syndrome'`?

**Comment by nicolevasilevsky** [comment]
> I think we should also include an extensive (union) definition here, where this is the union of SPG47, ..., 51

Not sure how to address this.

**Comment by nicolevasilevsky** [comment]
@tibingaman my apologies for the delay in getting back to this ticket. 
MONDO_0017241 is renamed 'AP4-related intellectual disability and spastic paraplegia', these updates will be available in the next release at the beginning of March.
