### ISSUE TITLE
New Term Request: AP-4 deficiency syndrome

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#1729]
Preferred term label: AP-4 deficiency syndrome

Synonyms: None

Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): The term "AP-4 deficiency syndrome" is often used in literature to describe genetic disorders associated with the "AP4 genes", AP4B1, AP4E1, AP4M1, and AP4S1. The phenotypes observed in individuals with genetic variants in these genes are often complex and include ID, spastic paraplegia, microcephaly, brain abnormalities, and seizures. The ClinGen ID/Autism GCEP would like to request the term "AP-4 deficiency syndrome" to encompass the complexity of phenotypes associated with variants in these four genes. PMIDs: 30543385, 29193663, 32171285, 29430868

Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): I have recently requested a new term "intellectual disability and spastic paraplegia" (ref #: #1728) and when this is created, this will be the parent term.

Children terms (if applicable) Should any existing terms that should be moved underneath this new proposed term?: None

Your nano-attribution (ORCID)
The ClinGen ID/Autism GCEP

**Comment by nicolevasilevsky** [comment]
Hi @tibingaman 
This term you requested is more broad than "intellectual disability and spastic paraplegia" (ref #: #1728) and I had some questions about that term.

I think this term is better suited as a child of Mendelian disorder.

I added this as such - let me know if you'd like any changes.

**Comment by cmungall** [comment]
Hello - you indicated no children, but by the proposed definition it would include

https://www.omim.org/entry/602296 (caused by AP4M1)
https://www.omim.org/entry/614067 (caused by AP4S1)

and possibly others

these have equivalents in MONDO

This is consistent with summary eg. here
https://www.ncbi.nlm.nih.gov/books/NBK535153/#ap4-def.Summary

**Comment by nicolevasilevsky** [comment]
@tibingaman 
This term has been added as MONDO_0100176

It will be available in the release file, which will be released at the end of this month. If you would like it sooner, I'd be happy to run a release for you sooner (ie today or next week). Let me know. :)
