### ISSUE TITLE
NCIT_C4392	Cervical Symmetrical Lipomatosis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#173]
_From @nicolevasilevsky on August 8, 2017 23:1_

NCIT_C4392 | Cervical Symmetrical Lipomatosis | SuperClassOf | DOID_3137 | multiple symmetrical lipomatosis
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29098184-e3e67634-7c52-11e7-91b8-8f369df03c82.png)

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#333_

**Comment by nicolevasilevsky** [comment]
there is a comment on MONDO_0002521 'multiple symmetrical lipomatosis' to merge this class with the superclass (MONDO_0007908 'multiple symmetric lipomatosis')

@cmungall is there any documentation on how to merge classes? If yes, I can do so.

**Comment by cmungall** [comment]
```
../utils/obs.sh ID-TO-OBSOLETE REPLACEMENT-ID
diff -u OBS mondo-edit.obo
mv OBS mondo-edit.obo
git commit -m 'enter message here' mondo-edit.obo
```

only do the mv if the diff looks normal

you will need latest owltools

or assign to me (if you do, give the reason for obsoletion - although not in this case it's obvious and there is already the note in the ontology to do it)

**Comment by nicolevasilevsky** [comment]
I think this has been dealt with, closing this ticket
