### ISSUE TITLE
New Term Request: X-linked Complex Neurodevelopmental Disorder

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#1730]
Preferred term label: X-linked Complex Neurodevelopmental Disorder

Synonyms

Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): The ClinGen ID/Autism GCEP was recently curating FRMPD4 and would like to request the new term "X-linked Complex Neurodevelopmental Disorder". X-linked Syndromic ID has been associated with this gene in the past however, most individuals with genetic variants in FRMPD4 express both intellectual disability and epilepsy, making Complex Neurodevelopmental Disorder a better suited term. This is also an X-linked disorder. PMIDs: 29267967, 25644381, 25644381, 29267967

Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): Complex Neurodevelopmental Disorder MONDO:0100038

Children terms (if applicable) Should any existing terms that should be moved underneath this new proposed term?: None

Your nano-attribution (ORCID)
ClinGen ID/Autism GCEP

**Comment by nicolevasilevsky** [comment]
@tibingaman do all patients with X-linked Complex Neurodevelopmental Disorder have a variation in FRMPD4?

**Comment by nicolevasilevsky** [comment]
Does this definition work:
A complex neurodevelopmental disorder with genetic variants in FRMPD4, that is characterized by intellectual disability and epilepsy.
?

**Comment by nicolevasilevsky** [comment]
I added this as MONDO_0100148

(pending a pull request)

**Comment by tibingaman** [comment]
@nicolevasilevsky No, X-linked Complex neurodevelopmental disorder is not caused by variants in FRMPD4 only. I am not aware of any examples, but at this time we can assume that like Complex neurodevelopmental disorder (MONDO:0100038), variants in many genes can be associated with this disorder. Thank you for checking!

**Comment by nicolevasilevsky** [comment]
got it, thanks!

I updated the def to:
A complex neurodevelopmental disorder that is characterized by intellectual disability and epilepsy.

**Comment by tibingaman** [comment]
Thank you @nicolevasilevsky! Can we also say that it includes but is not limited to intellectual disability, autism, and epilepsy?
Do we have to include anything about it being X-linked?

**Comment by nicolevasilevsky** [comment]
Yes, and good point!
How is this revised def:
A complex neurodevelopmental disorder that is transmitted via X-linked inheritance, and is characterized by intellectual disability, autism and epilepsy.

**Comment by cmungall** [comment]
What is the relationship of this to https://www.omim.org/entry/300983?

Note the first PMID listed for definition provenance
https://pubmed.ncbi.nlm.nih.gov/29267967/

is one of the two refs for the OMIM

What about the other MRXs? Relationship to them?

apologies for brevity

**Comment by nicolevasilevsky** [comment]
@tibingaman could you comment on Chris' questions above?
Thank you!

**Comment by nicolevasilevsky** [comment]
@tibingaman please let me know if this is correct:

From what I understand, this should be a grouping class, yes? @tibingaman are there any terms that should be children?
Are diseases with variants in FRMPD4 meant to be children, such as MONDO_0010509 'intellectual disability, X-linked 104' (which corresponds to https://www.omim.org/entry/300983, which Chris linked above).

Do you know which gene variants are seen in this disorder? Should we encode them with this term?

thank you!

**Comment by tibingaman** [comment]
@nicolevasilevsky Sorry for the delay in my response! At this time, there should not be any children under X-linked complex neurodevelopmental disorder. 'Intellectual disability, X-linked 104' MONDO:0010509 should not be a child under x-linked complex neurodevelopmental disorder because the definition says that this is a non-syndromic disorder (def: Any non-syndromic X-linked intellectual disability in which the cause of the disease is a mutation in the FRMPD4 gene.) This new disease term may be associated in the future with other genes, just like Complex neurodevelopmental disorder is.

**Comment by nicolevasilevsky** [comment]
thanks @tibingaman!

**Comment by tibingaman** [comment]
@nicolevasilevsky will this be released during the July release? Thanks!

**Comment by nicolevasilevsky** [comment]
@tibingaman it is pending review by @cmungall, I checked with him.

**Comment by nicolevasilevsky** [comment]
@tibingaman Yes- this will be in the next release
