### ISSUE TITLE
[NTR/gene]TTN-Related Myopathy

### ISSUE THREAD

**Issue by smcnulty13** [monarch-initiative/mondo#1731]
Preferred term label:
TTN-Related Myopathy

Synonyms:
TTN Myopathy
Congenital Myopathy Related to TTN

Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)
TTN-Related Myopathy is a disorder of the musculoskeletal system caused by pathogenic variants in the TTN gene encoding the titin protein expressed in striated muscle. These variants are associated with a variety of overlapping congenital and adult-onset myopathies characterized by non-progressive or progressive neck, axial, and limb weakness, joint contractures, early-onset respiratory insufficiency, facial weakness, congenital cardiac anomalies and/or early-onset dilated cardiomyopathy. Histologic findings on skeletal muscle biopsy reveal a wide range of structural abnormalities and can include increased internalized and central nuclei, minicores, and dystrophic changes (PMID:27854229 and PMID:29691892).

Parent term (use OLS, or your favorite ontology browser):
MONDO:0019952 (congenital myopathy)

Suggested child terms for collapse under new term:
MONDO:0015705 (autosomal recessive centronuclear myopathy)
MONDO:0011362 (hereditary proximal myopathy with early respiratory failure)
MONDO:0012714 (early-onset myopathy with fatal cardiomyopathy)
MONDO:0017939 (classic multiminicore myopathy)

Comment: In the absence of evidence supporting distinct differences in molecular mechanisms between the associated disease entities, as well as considerable phenotypic overlap, these entities can be considered part of a clinical spectrum of TTN-related myopathy.

@nicolevasilevsky: This is a ClinGen EP request (https://clinicalgenome.org/affiliation/40031/).

**Comment by nicolevasilevsky** [comment]
@smcnulty13 
This has been added as MONDO_0100175

It will be in the next release at the end of the month - but if you need it now, I'm happy to run another release sooner (ie today or next week), let me know. :)

**Comment by smcnulty13** [comment]
@nicolevasilevsky 
Thank you for the update! We are scheduled to review the curation of this gene in a ClinGen EP in a couple of weeks, so if you are able to run another release sooner it would be greatly appreciated.

**Comment by nicolevasilevsky** [comment]
will do! I'll let you know when it is done.
