### ISSUE TITLE
[Revise subclass] [add synonym] MONDO:0020708 "Brachial Amyotrophic Diplegia"

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/mondo#1734]
For Brachial Amyotrophic Diplegia consider adding the synonyms "flail arm syndrome" "FAS" and "man-in-barrel syndrome"

Also consider making this a subclass of ALS

https://link.springer.com/article/10.1007/s00415-015-7993-z

**Comment by nicolevasilevsky** [comment]
@kshefchek based on this paper, I'm not sure if ALS is an appropriate parent:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4461255/

"The relationship between FAS and ALS is still unclear. Some researchers argue this syndrome is a variant of ALS, while others believe that FAS is an independent entity[3–5]."

**Comment by nicolevasilevsky** [comment]
I added the synonyms
