### ISSUE TITLE
Mappings required for UniProtKB_Swiss-Prot Release 2020_04

### ISSUE THREAD

**Issue by Antonialock** [monarch-initiative/mondo#1735]
Hello,

Could you please add broad mappings between the following OMIM xrefs and MONDO terms:

618853 - MONDO_0011773
618849 - MONDO:0000159
618835 - MONDO_0000732
618838 - MONDO_0000732
618839 - MONDO_0000732
618851 - MONDO_0000732
618847 - MONDO_0021094

**Comment by nicolevasilevsky** [comment]
@ShahimEssaid I think these terms could be brought in as new classes from OMIM. Were you able to figure out that workflow?

**Comment by nicolevasilevsky** [comment]
@cmungall said he is working on bringing in the new OMIM ingest

**Comment by paolaroncaglia** [comment]
> @cmungall said he is working on bringing in the new OMIM ingest

@cmungall 
@nicolevasilevsky 
(cc @Antonialock )
Is there any update on this, please?
UniProtKB needs new OMIM IDs to be in EFO (see also https://github.com/EBISPOT/efo/issues/829). If Mondo is planning a new OMIM ingest soon, I'd rather import the new, exact Mondo terms in EFO than create broad mappings or new EFO terms (that would eventually be replicated by Mondo). 
Thanks in advance for your help with this!

**Comment by nicolevasilevsky** [comment]
Hi @Antonialock 
Sorry for the delay! The following mappings are now available in the release file (as of yesterday):

OMIM:618853 - MONDO_0030019 'anauxetic dysplasia 3'
OMIM:618849 - MONDO_0030015 'bone marrow failure syndrome 6'
OMIM:618835 - MONDO_0030006 'combined oxidative phosphorylation deficiency 40'
OMIM:618838 - MONDO_0030007 'combined oxidative phosphorylation deficiency 41'
OMIM:618839 - MONDO_0030008 'combined oxidative phosphorylation deficiency 42'
OMIM:618851 - MONDO_0030017 'combined oxidative phosphorylation deficiency 43'
OMIM:618847 - MONDO_0030013 'immunodeficiency 66'

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
I'm taking the liberty to re-open this ticket because @Antonialock had asked for other, more recent OMIM IDs too; all details in https://github.com/monarch-initiative/mondo/issues/1735#issuecomment-669253578 (the EFO ticket has a spreadsheet of new OMIM entries). I believe those aren't in Mondo yet, but I can't double-check at the moment. Thank you in advance for looking into this.

@Antonialock I'll import the 7 Mondo terms above into EFO.

**Comment by nicolevasilevsky** [comment]
Sure thing, @paolaroncaglia. I requested access to the spreadsheet.

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia and @Antonialock 
All of the OMIM terms are now in Mondo!
I added the MONDO IDs in the [spreadsheet](https://docs.google.com/spreadsheets/d/1efvKQf4eovo5p4I1KBK-4UOiTgUvMI4YH0Q5N9sHLBc/edit?ts=5f32f8a1#gid=0), in column F.

Thank you @cmungall for doing the OMIM ingest. :)

**Comment by nicolevasilevsky** [comment]
I think this can be closed again :)

**Comment by Antonialock** [comment]
so these terms will be included in the enxt MONDO release correct? @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
They are available now! (They were in the last release, which came out two days ago). It takes about a week for OLS to pick up the latest Mondo release.

**Comment by Antonialock** [comment]
Ah super @paolaroncaglia

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@Antonialock 
Thanks for your feedback. I'll import the new Mondo terms - we already have EFO tickets for that.
