### ISSUE TITLE
inconsistencies WRT hasRelatedSynonym and exactMatch properties

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1745]
I was looking at MONDO_0008136/isolated optic nerve hypoplasia

This has no definition, but has  
"exactMatch Orphanet:137902"
"exactMatch http://identifiers.org/omim/165550"

The label for Orphanet is _Isolated optic nerve hypoplasia/aplasia_, which is broader than _isolated optic nerve 
hypoplasia_ . _Isolated optic nerve hypoplasia/aplasia_ is classified as  "hasRelatedSynonym"
The label for OMIM is OPTIC NERVE HYPOPLASIA, BILATERAL, which is specific to hypoplasia, but is also classified as  "hasRelatedSynonym"

Are there rules for making certain the labels follow the identifiers?
Not sure how many nodes are necessary for these disorders; is this too specific?

- Isolated optic nerve hypoplasia/aplasia  (aka non-syndromic) Orphanet:137902
-- Optic nerve hypoplasia -- UMLS:C0338502 , NCIT:C98999
--- Isolated optic nerve hypoplasia UMLS:C4510723 , snomed 724999003
---- unilateral optic nerve hypoplasia  UMLS: C3640068
---- bilateral optic nerve hypoplasia  OMIM:165550, NCIT:C101268
-- Optic nerve aplasia (snomed 722989007, UMLS:C4021084)
--- bilateral optic nerve aplasia   UMLS:C1833798

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall 
Do you think we want to add these new terms? Upon first glance, they seem like phenotypes, but some of these terms do exist in NCIT, in their disease or disorder branch.

I thought I should check before adding all these - thanks for your help!

**Comment by nicolevasilevsky** [comment]
@maglott I agree that OMIM:165550 OPTIC NERVE HYPOPLASIA, BILATERAL is not equivalent to ORPHA:137902 Isolated optic nerve hypoplasia/aplasia - thank you for catching this.

@pnrobinson and @cmungall these two xref each other but I disagree with this mapping.

The Orphanet def says:

A rare genetic optic nerve disorder characterized by visual impairment or blindness resulting from varying degrees of underdevelopment of the optic nerve or even complete absence of the optic nerve, ganglion cells, and central retinal vessels. **It may be unilateral, typically with otherwise normal brain development, or bilateral with accompanying severe and widespread congenital malformations of the central nervous system.**

**Comment by pnrobinson** [comment]
Orphanet itself says there is an exact match to the OMIM disease. Both are related to PAX6 mutations. I think we should ask Ada if she feels there is a case to be made for adding a new PAX6 OMIM entry to cover the Orphanet description. However, I would guess that they are both referring to the "same thing", which is a small collection of imperfectly described case reports

**Comment by maglott** [comment]
This is an example of whether we want to process by ID (Orphanet/OMIM/UMLS/NCIT), by causative gene, or by label for the condition.
If distinctions are fuzzy at best, and we should lump aplasia and hypoplasia, unilateral and bilateral, then the definitions and the xrefs should make that clear.  I am hoping we can avoid, however, equating labels and their ids as exact matches when they are related.
In this example, the orphanet definition appears broader than the term used by OMIM.

**Comment by pnrobinson** [comment]
What I am saying is that it is impossible to know if there truly is a separation into two distinct diseases based on the data provided and given that all diseases are variable.  If we restrict ourselves to those with a molecularly confirmed disease there are four patients described in the OMIM entry (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1180317/). Not enough information is provided by the Orpha entry to know if they are referring to the same case report using different language or if one of the clinical experts has a large cohort of patients that would justify the differentiation into distinct diseases.  I think that we need to have FAIR evidence for disease definitions and that is not really the case here!

**Comment by maglott** [comment]
Hi Peter,
I think we are agreeing. I am asking only that Mondo be careful in its assignments of definitions , terms, synonyms (exact or related)  and XRefs when concepts fuzzy.

**Comment by kanems** [comment]
@nicolevasilevsky, I see this is moved to high priority, just wanted to follow up on this ticket/issue. For MedGen users, it would be helpful if we had a separate term, a new term for "Optic Nerve Hypoplasia, Bilateral" with X-refs: OMIM:165550 , UMLS:C1833797 , MESH C563492, NCIT C101268, ICD10 H47.033
Thanks!

**Comment by nicolevasilevsky** [comment]
per Mondo call - unsure if the proposed plan is the best way to proceed. See paper:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3779419/

**Comment by nicolevasilevsky** [comment]
Question for Ada:
should these terms be lumped together and should the synonyms be broad or narrow synonyms?

**Comment by nicolevasilevsky** [comment]
This lumped in OMIM. To do:
review xfrefs and synonyms and make sure the scope is correct (ie equivalentTo vs subClassOf, etc.)

**Comment by nicolevasilevsky** [comment]
I reviewed the xrefs and they looked okay to me
