### ISSUE TITLE
NTR: monoclonal mast cell activation syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#175]
See: https://github.com/obophenotype/human-phenotype-ontology/issues/3450

**Comment by nicolevasilevsky** [comment]
Proposed new hierarchy:
Parent: MONDO_0004805 'leukocyte disease'
**-Mast cell activation syndrome**
def: 
Syn: MCAS
Source: PMID:23409940

**-- Primary mast cell activation syndrome**
Def: Mast cell activation syndrome where KIT-mutated and clonal mast cells are detected.
Syn: Primary MACS
Source: PMID:23409940

**-- Secondary mast cell activation syndrome**
Def: Mast cell activation syndrome where an underlying inflammatory disease is present, often in the form of an IgE-dependent allergy, but there are no KIT-mutated mast cells.
Source: PMID:23409940

**-- Idiopathic mast cell activation syndrome**
Def: Mast cell activation syndrome where neither an allergy or other underlying disease is association, nor KIT-mutated mast cells are detectable.
Source: PMID:23409940

@cmungall and/or @pnrobinson if this looks okay, I will add these term and do a PR.

**Comment by cmungall** [comment]
go ahead. xref MEDDRA:10075217. Axiomatize parent using GO. Diffs should be solved

**Comment by nicolevasilevsky** [comment]
added new term Mast cell activation syndrome, accidentally referred #122 instead of this ticket.

**Comment by nicolevasilevsky** [comment]
added logical def for mast cell activation syndrome.

**Comment by nicolevasilevsky** [comment]
see https://github.com/monarch-initiative/mondo/pull/195

**Comment by nicolevasilevsky** [comment]
closed the PR #195 and created new PR #266
