### ISSUE TITLE
New Term Request: ATP6AP2-related disorder

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#1751]
**Preferred gene-related syndrome label: ATP6AP2-related disorder
For example: NAA10-related syndrome

**Synonyms: none

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): Variants in the gene ATP6AP2 have been associated with a multitude of diseases. These disease assertions include X-linked syndromic ID Hedera type, X-linked parkinsonism-spasticity syndrome, and congenital disorder of glycosylation type 2R. A wide range of phenotypes have been presented in the literature for these genes, including global developmental delay, intellectual disability, progressive neurologic decline, spasticity, seizures, infantile onset of liver failure, recurrent infections, dysmorphic features, and features of parkinsonism (rigidity, resting tremor, bradykinesia). These phenotypes do not appear in all individuals with one of the above disease assertions, but many are overlapping phenotypes.The ID/Autism GCEP would like to suggest the term "ATP6AP2-related disorder" to encompass the phenotypes presented in individuals with variants in ATP6AP2. (PMIDs: 15746149, 23595882, 26467484, 29127204, 30985297, 26376863)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): Syndromic X-Linked Intellectual disability

**Children terms (if applicable): none

**Your nano-attribution (ORCID) or URL for a working group: ClinGen's ID/Autism GCEP

**Comment by nicolevasilevsky** [comment]
@tibingaman it doesn't look like we have congenital disorder of glycosylation type 2R in Mondo - do you think we should add it? Or is it a synonym for something else? Could you please provide more info?
Thanks!

**Comment by nicolevasilevsky** [comment]
I added this new term as MONDO_0100146 'ATP6AP2-related disorder'

**Comment by tibingaman** [comment]
@nicolevasilevsky Hi Nicole, we do not need to add the term "congenital disorder of glycosylation type 2R". In previous publications, ATP6AP2 has been associated with this disease term, but the ID/Autism GCEP is not interested in curating for this disease name. I see no need to add this in Mondo. Thank you for checking!

**Comment by maglott** [comment]
This is a record in OMIM: https://www.omim.org/entry/301045
CONGENITAL DISORDER OF GLYCOSYLATION, TYPE IIr

**Comment by nicolevasilevsky** [comment]
Perfect, thanks @maglott! We have an open ticket to import the latest OMIM terms, so hopefully this will be added soon.

#1735
