### ISSUE TITLE
[Obsolete] Monogenic disease (super ticket)

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1758]
**Mondo term (ID and Label)**
MONDO_0000275 monogenic disease

See tickets:
#1495 
#722 
PR #972 

I think the open questions are:

From Chris: The central question is:
1. does it make sense to differentiate between monogenic and digenic via bucket classes in the ontology
2. if so, how do we ensure the ontology stays up to date with current findings
On (2): don't think this is easy to tell from existing gene to disease resources. It can be hard to tell computationally if cardinality>1 is to be interpreted as a can-be-caused-by-either-of or digenic.

Chris is convinced that as a group we can solve this problem, but I don't think this will happen overnight. He is concerned that in the short term we don't put out misleading incomplete information, or incorrect information. If you put a term in an ontology, you are committed to doing a good job of fully populating it, within reason, otherwise users will be confused.
It seems safer to roll up to whatever we call the grouping class of mono/di for now, and return to this later. But he may be overestimating the curation effort

[Melissa said](https://github.com/monarch-initiative/mondo/issues/722#issuecomment-637096330): idea was to obsolete and have monogenic/polygenic be inferred from the annotations

cc @valwood

**Comment by ValWood** [comment]
OK!

**Comment by nicolevasilevsky** [comment]
Discussion with Peter + Chris on Mondo call 07/17/20:
- it is difficult to properly classify terms as monogenic
- consider renaming 'inherited genetic disease' to 'Mendelian disease'
- obsolete monogenic disease
