### ISSUE TITLE
RYR1-Related Myopathy[NTR/gene]

### ISSUE THREAD

**Issue by mayherpatel** [monarch-initiative/mondo#1763]
**Preferred gene-related syndrome label**
RYR1-Related Myopathy

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
RYR1-Related Myopathy is a disorder of the musculoskeletal system caused by pathogenic variants in the RYR1 gene, which encodes the ryanodine receptor type 1 protein. These are the most common class of congenital myopathies. These variants are associated with a variety of overlapping features characterized by symmetric proximal muscle weakness, often with pronounced facial weakness with or without dysmorphism and ophthalmoparesis/ophthalmoplegia with ptosis, bulbar weakness, significant respiratory involvement, severe neonatal hypotonia, scoliosis, orthopedic deformities including arthrogryposis, hip dislocation, club feet, and King Denborough syndrome (pectus carinatum or excavatum, short stature, joint contractures, facial and skeletal deformities), MH susceptibility, anesthesia-induced rhabdomyolysis, fatigue, exercise-induced hyperthermia/exertional heat stroke, and exertional myalgia. Histologic findings on skeletal muscle biopsy reveal a wide range of structural abnormalities and can include central core disease, multiminicore disease, cone-rod myopathy, centronuclear myopathy, and congenital fiber-type disproportion. (PMID:30406384) 
**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0019952
**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term?
MONDO:0018528
MONDO:0009712
MONDO:0009711
**Your nano-attribution (ORCID) or URL for a working group**
This is a ClinGen EP request (https://clinicalgenome.org/affiliation/40031/).

**Comment by nicolevasilevsky** [comment]
@mayherpatel what is MH susceptibility?

**Comment by mayherpatel** [comment]
@nicolevasilevsky I'm sorry for not defining the acronym. It is malignant hyperthermia susceptibility

**Comment by nicolevasilevsky** [comment]
It's all good!

**Comment by nicolevasilevsky** [comment]
This was added as MONDO_0100150 'RYR1-related myopathy'

It will be available in the next release
