### ISSUE TITLE
[Merge] records that seem to differ only in word order or punctuation

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1764]
***Note***  this list may be out of date because it is based on the April release

## Done (PR merged or addressed in the comments below)

1. MONDO_0014988	3-methylglutaconic aciduria, type VIII	MONDO_0044723	3-methylglutaconic aciduria type 8~
1. MONDO_0007539	encephalopathy, recurrent, of childhood	MONDO_0023065	encephalopathy recurrent of childhood PR https://github.com/monarch-initiative/mondo/pull/1917
1. MONDO_0016002	Ehlers-Danlos syndrome, kyphoscoliotic type	MONDO_0034024	kyphoscoliotic ehlers-danlos syndrome. _These are two separate records in Orphanet, they should not merged. I renamed MONDO_0034024 with the OMIM name._ PR https://github.com/monarch-initiative/mondo/pull/1918
1. MONDO_0010682	myoclonic epilepsy, progressive	MONDO_0020074	progressive myoclonic epilepsy. _Both terms come from OMIM, so they shouldn't be merged. I renamed one._ https://github.com/monarch-initiative/mondo/pull/1920
1. MONDO_0001676	erythropoietic protoporphyria	MONDO_0008319	protoporphyria, erythropoietic _**see related tickets**_ https://github.com/monarch-initiative/mondo/issues/1737 and https://github.com/monarch-initiative/mondo/issues/281. _MONDO_0008319 has been renamed to 'protoporphyria, erythropoietic, 1', so this has been addressed._
1. MONDO_0008761	alpha-2-deficient collagen disease	MONDO_0022423	alpha-2 deficient collagen disease. PR https://github.com/monarch-initiative/mondo/pull/1919
1. MONDO_0005302	attention deficit hyperactivity disorder	MONDO_0007743	attention deficit-hyperactivity disorder PR https://github.com/monarch-initiative/mondo/pull/1911
1. MONDO_0010059	spinal muscular atrophy, type I, with congenital bone fractures	MONDO_0014806	spinal muscular atrophy with congenital bone fractures 1 - _OMIM merged these, I will merge too_ PR https://github.com/monarch-initiative/mondo/pull/1910
1. MONDO_0015425	lethal recessive chondrodysplasia	MONDO_0022725	chondrodysplasia lethal recessive
1. MONDO_0010898	Autosomal dominant epilepsy with auditory features	MONDO_0100031	autosomal dominant epilepsy with auditory features
1. MONDO_0011261	spondyloepiphyseal dysplasia, Nishimura type	MONDO_0032835	spondyloepiphyseal dysplasia, nishimura type, **Created a new ticket:** https://github.com/monarch-initiative/mondo/issues/1932
1. MONDO_0008408	scapuloperoneal spinal muscular atrophy	MONDO_0010058	spinal muscular atrophy, scapuloperoneal
1. MONDO_0013816	palmoplantar keratoderma, mutilating, with periorificial keratotic plaques	MONDO_0019014	mutilating palmoplantar keratoderma with periorificial keratotic plaques
MONDO_0013850	periodic fever, menstrual cycle-dependent	MONDO_0044660	menstrual cycle-dependent periodic fever
1. MONDO_0007796	hypoparathyroidism, familial isolated	MONDO_0016390	familial isolated hypoparathyroidism
1. MONDO_0016368	Rothmund-Thomson syndrome type 1	MONDO_0032840	rothmund-thomson syndrome, type 
1. MONDO_0020435	atrial septal defect, coronary sinus type	MONDO_0022512	atrial septal defect coronary sinus
- [x] MONDO_0011268	renal tubular acidosis, distal, autosomal recessive	MONDO_0018440	autosomal recessive distal renal tubular acidosis. _Related to_ https://github.com/monarch-initiative/mondo/issues/1825 See question on #1825 
_MONDO_0011268 is renamed to 'renal tubular acidosis, distal, 3, with or without sensorineural hearing loss'_
1. MONDO_0010560	cleft palate with or without ankyloglossia, X-linked	MONDO_0017938	X-linked cleft palate with or without ankyloglossia PR #1886
1. 1. MONDO_0007450	neurohypophyseal diabetes insipidus	MONDO_0010582	diabetes insipidus, neurohypophyseal type. PR: https://github.com/monarch-initiative/mondo/pull/1914

**Comment by nicolevasilevsky** [comment]
MONDO_0007796 hypoparathyroidism, familial isolated MONDO_0016390 familial isolated hypoparathyroidism
Note: from GARD: they changed it in GARD too.

**Comment by nicolevasilevsky** [comment]
MONDO_0010560 cleft palate with or without ankyloglossia, X-linked MONDO_0017938 X-linked cleft palate with or without ankyloglossia
From GARD: Changed GARD term to “X-linked cleft palate and ankyloglossia” according to Orphanet and to the phenotype.

**Comment by nicolevasilevsky** [comment]
MONDO_0013850 periodic fever, menstrual cycle-dependent MONDO_0044660 menstrual cycle-dependent periodic fever
From GARD:  We don’t have this one but will add it to the list of disorders considered for inclusion

**Comment by nicolevasilevsky** [comment]
MONDO_0013816 palmoplantar keratoderma, mutilating, with periorificial keratotic plaques MONDO_0019014 mutilating palmoplantar keratoderma with periorificial keratotic plaques
From GARD:  We have this one as Olmsted syndrome but we have Mutilating palmoplantar keratoderma (PPK) with periorificial keratotic plaques as a synonym.

**Comment by nicolevasilevsky** [comment]
MONDO_0010898 Autosomal dominant epilepsy with auditory features MONDO_0100031 autosomal dominant epilepsy with auditory features
From GARD: We have this one as “Autosomal dominant partial epilepsy with auditory features” according to several sources

**Comment by nicolevasilevsky** [comment]
MONDO_0015425 lethal recessive chondrodysplasia MONDO_0022725 chondrodysplasia lethal recessive
From GARD:  We have “Lethal recessive chondrodysplasia” as per Orphanet

**Comment by nicolevasilevsky** [comment]
MONDO_0005302 attention deficit hyperactivity disorder MONDO_0007743 attention deficit-hyperactivity disorder
From GARD: Not a rare disease but according to the Manual of psychiatry the term is Attention-deficit hyperactivity disorder, even so I have seen it in different way depending on the source.

**Comment by nicolevasilevsky** [comment]
MONDO_0008408 scapuloperoneal spinal muscular atrophy MONDO_0010058 spinal muscular atrophy, scapuloperoneal
From GARD: I think the preferred term for the order should be scapuloperoneal spinal muscular atrophy.

**Comment by nicolevasilevsky** [comment]
MONDO_0016368 Rothmund-Thomson syndrome type 1 MONDO_0032840 rothmund-thomson syndrome, type 1
From GARD:  in GARD we don’t have subtypes of rothmund-thomson syndrome but the proposed term order seem correct to me.

**Comment by nicolevasilevsky** [comment]
MONDO_0020435 atrial septal defect, coronary sinus type MONDO_0022512 atrial septal defect coronary sinus
From GARD: Same as GARD

**Comment by nicolevasilevsky** [comment]
MONDO_0007450 neurohypophyseal diabetes insipidus MONDO_0010582 diabetes insipidus, neurohypophyseal type

From GARD: We have it as “Central diabetes insipidus”  according to Orphanet but has added neurohypophyseal diabetes insipidus as a synonym (please note the order of words)

**Comment by nicolevasilevsky** [comment]
MONDO_0011261 spondyloepiphyseal dysplasia, Nishimura type MONDO_0032835 spondyloepiphyseal dysplasia, nishimura type

From GARD: We don’t have this one but I will add it for consideration for inclusion to my list

**Comment by nicolevasilevsky** [comment]
MONDO_0011268 renal tubular acidosis, distal, autosomal recessive MONDO_0018440 autosomal recessive distal renal tubular acidosis

From GARD:  Same in GARD

**Comment by nicolevasilevsky** [comment]
MONDO_0014988 3-methylglutaconic aciduria, type VIII MONDO_0044723 3-methylglutaconic aciduria type 8

From GARD: We don’t have this one in GARD but I will add it for consideration for inclusion to my list

**Comment by ahamosh** [comment]
I agree that menstrual cycle-dependent periodic fever and periodic fever, menstrual cycle-dependent should be merged.

**Comment by nicolevasilevsky** [comment]
Everything here is done! The changes will be available in the next release. Closing.
