### ISSUE TITLE
[NTR/gene] MYH7-related skeletal myopathy 

### ISSUE THREAD

**Issue by brookepalus** [monarch-initiative/mondo#1765]
**Preferred gene-related syndrome label**
MYH7-related skeletal myopathy 

**Synonyms**
Myosin storage myopathy 
Laing distal myopathy 

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
MYH7 related myopathy with scapuloperoneal, distal or limb-girdle muscle weakness and involving the skeletal system.
PMID:22918376
PMID:24664454
PMID:22918376

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Congenital Myopathy, MONDO:0019952

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term?

**Your nano-attribution (ORCID) or URL for a working group**
@nicolevasilevsky This MonDO ID request is coming from the ClinGen Congenital Myopathy Gene Curation Expert Panel. Let me know if I can provide any other info. Thanks!

**Comment by nicolevasilevsky** [comment]
I added this as MONDO_0100149

There is a pending pull request, but this should be available in the next release - end of July/early Aug

**Comment by nicolevasilevsky** [comment]
@brookepalus I have a question -
There is an existing term for Laing distal myopathy (MONDO_0008050 'Laing early-onset distal myopathy')

Are these the same terms?

Or should Laing distal myopathy be a related synonym?

**Comment by brookepalus** [comment]
@nicolevasilevsky Laing distal myopathy should be a synonym for MYH7-related skeletal myopathy. I do not think that it should be a subclass/subtype. 

Thanks!

**Comment by nicolevasilevsky** [comment]
thanks @brookepalus. See the comments on: https://github.com/monarch-initiative/mondo/pull/1771

Based on your's and Chris' comments, it seems this is best added as a synonym to the existing class MONDO_0008050 Laing distal myopathy

**Comment by brookepalus** [comment]
Hi @nicolevasilevsky, I want to follow up with this previous request for MYH7-related skeletal myopathy. I understand that  MYH7-related skeletal myopathy and Laing distal myopathy are now synonyms, but is there any way that MYH7-related skeletal myopathy could be used as the primary Mondo term? This is at request from the experts of the ClinGen Congenital Myopathies GCEP. Please let me know if you have any questions and many thanks for your help! 

Best,
Brooke

**Comment by nicolevasilevsky** [comment]
Of course @brookepalus, no problem at all. This will be updated in the next release in early March.
