### ISSUE TITLE
[Merge] MONDO_0021281 'cavernous hemangioma of retina' and MONDO_0019101 'retinal capillary malformation'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1768]
**Mondo term (ID and Label)**
MONDO_0021281 'cavernous hemangioma of retina' 

**Reason for deprecation**
These terms seem like duplicates. The def of MONDO_0019101 is
Retinal cavernous hemangioma is a rare, benign, usually unilateral retinal vascular hamartoma that in most cases is asymptomatic but in some patients may present with blurred vision or floaters and that is characterized by the presence of grape-like vacuoles.

**Term to be merged with**
MONDO_0019101 'retinal capillary malformation'

cc @ana-rath-orphanet 

Not sure which term is preferential to keep vs obsolete.

**Comment by galyea-gard** [comment]
Hi!  We don't have these terms in GARD, however both retinal cavernous hemangiomas and retinal capillary hemangiomas are vascular hamartomas of the retina.  I don't think the terms are duplicates.  I found the following very helpful:  https://www.aao.org/disease-review/retinal-hemangiomas

**Comment by galyea-gard** [comment]
However, I am not able to see Orphanet, their server is down...

**Comment by nicolevasilevsky** [comment]
it sounds like we should keep both terms. I am going to close this ticket, please reopen if any other action is needed.
