### ISSUE TITLE
NCIT_C9088	Iris Melanoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#177]
_From @nicolevasilevsky on August 8, 2017 5:48_

NCIT_C9088 | Iris Melanoma | SubClassOf | Orphanet_39044 | Uveal melanoma
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29057954-7b1216ee-7bc2-11e7-947c-b85556b19dde.png)

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#279_

**Comment by nicolevasilevsky** [comment]
[Orphanet](http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=10453&Disease_Disease_Search_diseaseGroup=39044&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Uveal-melanoma&title=Uveal-melanoma&search=Disease_Search_Simple) has a syn 'Iris melanoma' for 'Uveal melanoma'

![image](https://user-images.githubusercontent.com/6722114/29092092-e8e5b3d4-7c39-11e7-939f-ebed6e6ec0d9.png)

**Comment by nicolevasilevsky** [comment]
iris is part of the uvea, so not sure if these should be equiv? Should I make a ticket for Orphanet?

**Comment by nicolevasilevsky** [comment]
I think we should remove the subclassOf assertion that iris melanoma is a subclass of uveal melanoma. It also has the parent iris cancer.

**Comment by cmungall** [comment]
why remove the assertion? Note it should just pop back if you try and remove it:

https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001769

I think a lot of these older tickets are no longer relevant

**Comment by nicolevasilevsky** [comment]
ok, I'll close this ticket
