### ISSUE TITLE
[Merge]MONDO_0100039 'CDKL5 disorder' and MONDO_0010396 'epileptic encephalopathy, early infantile, 2'

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#1785]
**Mondo term (ID and Label)**
MONDO_0100039 'CDKL5 disorder'

**Reason for deprecation**
I am not clear what there is a separate term for CDKL5 disorder (MONDO:0100039) - this has no identifiers (GARD:0006867??) and could be merged with  epileptic encephalopathy, early infantile, 2 MONDO:0010396

**Term to be merged with**
MONDO_0010396 epileptic encephalopathy, early infantile, 2

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter

**Comment by nicolevasilevsky** [comment]
@LCCarmody this term was requested by ClinGen:
https://github.com/monarch-initiative/mondo/issues/202

and it is cross-referenced by GARD: https://rarediseases.info.nih.gov/diseases/12173/cdkl5-deficiency-disorder

I'm not sure if we want to obsolete it.

**Comment by LCCarmody** [comment]
Also not me! @lcdaugherty :)

**Comment by nicolevasilevsky** [comment]
Sorry again, @LCCarmody! Your input is always welcome too. :)

**Comment by lcdaugherty** [comment]
@nicolevasilevsky Although they are essentially describing the same thing I can see there is some nuance in the reasoning as to why it was decided to keep them separate, so thanks to your link to the discussion in 2018 regarding this entry, I can see that is was discussed in great length and it was agreed to have a separate term for CDKL5 disorder (MONDO:0100039). I can't really insist with it being merged even if it seems more logical. Would it be possible include a comment to reflect the MONDO reasoning for future reference? Thanks

**Comment by nicolevasilevsky** [comment]
I added a link to the original GitHub ticket on this term.
