### ISSUE TITLE
need pattern: nuclear vs mitochondrial subtypes

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1800]
related to:
https://github.com/monarch-initiative/mondo/pull/1621

need pattern: nuclear vs mitochondrial subtypes

**Comment by nicolevasilevsky** [comment]
@cmungall see patterns:
https://github.com/monarch-initiative/mondo/blob/master/src/patterns/nuclear_subtype.yaml
https://github.com/monarch-initiative/mondo/blob/master/src/patterns/mitochondrial_subtype.yaml

**Comment by cmungall** [comment]
not really a defect of a mt or nuc per se, use:

disease_has_basis_in_dysfunction_of some

SO:0000087 ! nuclear_gene

or

SO:0000088 ! mt_gene

**Comment by nicolevasilevsky** [comment]
Thank you for clarifying! :)
My patterns definitely seemed wrong!

**Comment by nicolevasilevsky** [comment]
@matentzn once these patterns are merged, can we script in the logical definitions to the respective terms?

**Comment by matentzn** [comment]
Yeah can do. That should be easy, ping me when the time comes again.
