### ISSUE TITLE
need pattern: pre/a/symptomaatic forms of infectious dis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1801]
need pattern: pre/a/symptomaatic forms of infectious dis

related to: 
https://github.com/monarch-initiative/mondo/pull/1668

**Comment by nicolevasilevsky** [comment]
@cmungall and @pnrobinson 
If I were to make a pattern, would we want to add new clinical modifiers to HPO for presymptomatic and asymptomatic ?

**Comment by nicolevasilevsky** [comment]
see related pattern:
https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/infectious_disease_by_agent.yaml

I think the logical def would be:

'infectious disease' and 'realized in response to stimulus' some %s and 'has modifier' some %s"
  - agent
  - Clinical modifier

**Comment by pnrobinson** [comment]
I would strongly advise against making classes like

asymptomatc disease X
presymptomatic disease X
symptomatic disease X
?postsymptomatic disease X

This is first of all difficult to define, and not entirely logical (asymptomatic is not a disease). 
I think that the disease annotations should try to capture some of this intuition.

**Comment by nicolevasilevsky** [comment]
I will close this, it doesn't sound like we want these types of diseases, and presymptomatic COVID-19 infection has been obsoleted (which is the class that initiated this ticket).
