### ISSUE TITLE
split term:Imerslund-Grasbeck syndrome into: generic+type1

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#1802]
Term to split: Imerslund-Grasbeck syndrome

Name for new term:

aside: @nicolevasilevsky cna you update this templaate. With a split there aare 2+ new terms, not one

 - Imerslund-Grasbeck syndrome
 - Imerslund-Grasbeck syndrome type 1

List properties that should be moved to new term

We need documentation on this split pattern. ORDO tends to represent the generic. Most properties will move to the generic. Use judgment. Eg syns that end in "1" should move to subclass

```
name: imerslund-grasbeck syndrome
xref: OMIMPS:261100 {source="MONDO:equivalentTo"} ! imerslund-grasbeck syndrome
```

**Comment by maglott** [comment]
Also need type 2

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] update the 'split template'

**Comment by nicolevasilevsky** [comment]
I didn't realize you created a new ticket as I was working on this. See linked PR

**Comment by nicolevasilevsky** [comment]
@cmungall I updated the template here:
https://github.com/monarch-initiative/mondo/blob/master/.github/ISSUE_TEMPLATE/split-term.md
