### ISSUE TITLE
create documentation about splitting terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1810]
https://github.com/monarch-initiative/mondo/issues/1804

From Chris:
This is a common pattern. OMIM renames FOO to FOO 1, creating a new PS with name FOO. We should split (obs + 2 new terms) to avoid confusion. Use judgment in moving properties. E.g. ordo tends to represent generic form but their def may mention a gene.

**Comment by maglott** [comment]
Another pattern from OMIM is redefining something like name 1 to name1A. IMO name 1 needs to be retained and the MIM number and the name1A be used for the new record.

**Comment by nicolevasilevsky** [comment]
this is done:
https://mondo.readthedocs.io/en/latest/editors-guide/splitting-classes/
