### ISSUE TITLE
[NTR] Alcoholic ketoacidosis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#1823]
**Preferred term label:**
Alcoholic ketoacidosis

**Synonyms**
alcoholic ketosis
alcoholic acidosis

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Alcoholic ketoacidosis (AKA) is an acute disease characterized by severe ketoacidosis in the absence of diabetes mellitus and occuring in individuals with a history of prolonged excessive alcohol consumption. Disease manifestations include nausea, intractable vomiting, and abdominal pain. When treated, AKA resolves rapidly and completely with no apparent sequelae. 
PMID:16714496

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0006022

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**

**Comment by maglott** [comment]
Is  alcoholic acidosis  equivalent to Alcoholic ketoacidosis?   Or is it just that acidosis with alcohol is always a ketoacidosis?

**Comment by pnrobinson** [comment]
In this disease, you have episodes of acidosis following long bouts of drinking and the ketone bodies seem to be the predominant but not sole type. The synonyms are taken from this article: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2564331/

**Comment by maglott** [comment]
Thanks, @pnrobinson.   I certainly don't know the medicine as you do.
