### ISSUE TITLE
acidosis disorder should not be a child of hematologic disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#1824]
**Mondo term (ID Label)**
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0006022

**Bug/Typo/Error description**

It should be a child of metabolic disease
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005066&viewMode=All&siblings=false

Note that 'lactic acidosis' is not a disease (it is a feature and is an HPO term). The children underneath lactic acidosis also need attention and should be moved elsewhere.

**Comment by nicolevasilevsky** [comment]
@pnrobinson here are 2 explanations for that inference:

![image](https://user-images.githubusercontent.com/6722114/88593103-e6998c00-d013-11ea-9ace-f35d502d8cb0.png)

**Comment by nicolevasilevsky** [comment]
if I remove subClassOf 'disease has location' some blood 
the inference goes away. The source for that assertion was EFO:0000784 has_disease_location, which doesn't seem quite right, and the text def says it affects the blood and other bodily tissues, so that doesn't seem totally right.

**Comment by nicolevasilevsky** [comment]
I added metabolic disease as a parent.

**Comment by pnrobinson** [comment]
Acidosis is not *spefically* located in blood, it is the tissues/the body that are acidotic, and we just measure it in the blood. Therefore, ``diseaseHasLocation some blood`` is wrong! I would vote for just removing this triple.

**Comment by cmungall** [comment]
> acidosis disorder should not be a child of hematologic disease

I agree, what is confusing is that we had already removed this and we keep a shadow axiom:

```
id: MONDO:0006022
name: acidosis disorder
...
relationship: excluded_subClassOf MONDO:0005570 {source="EFO:1000014"} ! hematologic disease
relationship: disease_has_location UBERON:0000178 {source="EFO:0000784"} ! blood
```

@nicolevasilevsky can you add a ticket for a check that prevents resuscitation of excluded axioms via reasoning

> I added metabolic disease as a parent.

No need, it is already a parent via it's logical definition. are you not seeing his?

> I would vote for just removing this triple.

Agreed, we could also review all location axioms coming from EFO, cc @paolaroncaglia 



```

```

**Comment by nicolevasilevsky** [comment]
> No need, it is already a parent via it's logical definition. are you not seeing his?

Oh, yes, I do see it. I removed the superclass assertion.

> @nicolevasilevsky can you add a ticket for a check that prevents resuscitation of excluded axioms via reasoning

yes, will do

**Comment by paolaroncaglia** [comment]
@cmungall 
@nicolevasilevsky 
cc @zoependlington 

> Agreed, we could also review all location axioms coming from EFO, cc @paolaroncaglia

Sure. I opened https://github.com/EBISPOT/efo/issues/832 to address the specific link between EFO 'acidosis' and 'blood'. But we'd be happy to assist if you carry out a sistematic review of all location axioms coming from EFO and find any issue there. Thanks!
