### ISSUE TITLE
[NTR] Kawasaki-like syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1837]
**Preferred term label:**
Kawasaki-like syndrome

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
see: https://medicalxpress.com/news/2020-06-kawasaki-like-syndrome-linked-covid-children.html

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
COVID-19

cc @pnrobinson

**Comment by pnrobinson** [comment]
Prefered label:
SARS-CoV-2 Kawasaki-like syndrome
Syn
COVID-19 Kawasaki-like syndrome
Pediatric Inflammatory Multisystem Syndrome Temporally Associated With SARS-CoV-2
Paediatric Inflammatory Multisystem Syndrome: Temporally Associated with SARS-CoV-2
Synonym (abbreviation): PIMS-TS
Def: A inflammatory syndrome in children infected by the SARS-CoV-2 with similarities to Kawasaki disease. Clinical manifestations range from fever and inflammation to myocardial injury, shock, and development of coronary artery aneurysms.
PMID:32511692
PMID:32529358
PMID:32630212
Comment: The clinical presentation of MIS-C includes fever, severe illness, and the involvement of two or more organ systems, in combination with laboratory evidence of inflammation and laboratory or epidemiologic evidence of SARS-CoV-2 infection. Some features of MIS-C resemble Kawasaki Disease, toxic shock syndrome, and secondary hemophagocytic lymphohistiocytosis/macrophage activation syndrome.
