### ISSUE TITLE
Issue with MeSH ID as ExactMatch for MONDO:0011340 (Congenital tracheal stenosis) and MONDO:0018058 (Tracheal agenesis)

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#1839]
MONDO:0011340 (Congenital tracheal stenosis) and MONDO:0018058 (Tracheal agenesis) currently both have MeSH:C536975 Tracheal agenesis (syn.Tracheobronchial Stenosis, Congenital) as  ExactMatch. 

Suggest:
- synonym Congenital tracheal stenosis should be removed from MeSH: C536975 (Tracheal agenesis) 
- MeSH:C536975 should be removed from MONDO:0011340 (Congenital tracheal stenosis)
- MeSH: C566362 (Tracheobronchial Stenosis, Congenital) should be an ExactMatch of MONDO:0011340 (Congenital tracheal stenosis)

**Comment by nicolevasilevsky** [comment]
cc @ana-rath-orphanet @annieolry @Orphanet

**Comment by nicolevasilevsky** [comment]
Thanks @lcdaugherty!

I reported this to MeSH (Case number is CAS-585144-F4H1G4) and made this change. It should be available in the release at the end of August/Early Sept.
