### ISSUE TITLE
Add 3 new PSs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#1844]
- [x] xref: OMIMPS:164310 {source="MONDO:equivalentTo"} ! oculopharyngodistal myopathy
- [x] xref: OMIMPS:180860 {source="MONDO:equivalentTo"} ! silver-russell syndrome
- [x] xref: OMIMPS:314580 {source="MONDO:equivalentTo"} ! wieacker-wolff syndrome

In each case, determine if either

 - we have the grouping already; add the xref
 - we haave a conflated prototype term; split

tip: the prototypic member usually has the same omim number, OMIM:nnnn

**Comment by nicolevasilevsky** [comment]
I'm not sure what to do for this last one, should the parent class and the child class have the same name?

![image](https://user-images.githubusercontent.com/6722114/89473660-4bea2d00-d738-11ea-823a-cd4ae410f1ef.png)

**Comment by maglott** [comment]
Maybe treat  PS314580 as equivalent to  ORPHA:3454/MONDO:0010758 given that Orphanet does not make a distinction between the primarily male form and the female-restricted form

**Comment by nicolevasilevsky** [comment]
name child Wieacker-Wolff, X-linked recessive

**Comment by nicolevasilevsky** [comment]
@cmungall I didn't realize there was already a class for 'Wieacker-Wolff syndrome (spectrum)' that is equiv to OMIMPS:314580, which has MONDO_0010758 'intellectual disability-developmental delay-contractures syndrome' as a child (equiv to OMIM:314580).

Action items:
- [ ] rename MONDO_0010758 to Wieacker-Wolff, X-linked recessive
- [ ] fix annotation BROAAD, not sure how this got added

**Comment by nicolevasilevsky** [comment]
I think this may be done, need to check
