### ISSUE TITLE
C0009405 is not  correct for MONDO:0018618

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1857]
**Mondo term (ID and Label):**
MONDO:0018618/46,XY disorder of sexual development due to dihydrotestosterone backdoor pathway biosynthesis defect

**Xref that should be fixed (ID and label):**
C0009405 is the CUI for Hereditary Nonpolyposis Colorectal Neoplasms

**Other comments:**
Could not find a exact match in UMLS for MONDO:0018618

**Comment by nicolevasilevsky** [comment]
Good catch, thanks @maglott
