### ISSUE TITLE
Hemihypertrophy subClassOf Macroglossia?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#186]
_From @siiraa on April 26, 2017 14:15_

Orphanet_373 Hemihypertrophy by definition is an overgrowth characterized by an aymmetric regional body overgrowth, invoving at least one limb.

Macroglossia Orphanet_156207 (http://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_156207) is the presence of an excessively large tongue, appearing to be the parent of Hemihypertrophy.

Does this sound right? Something feels a bit off to me.

Thank you,
Sira

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#242_

**Comment by nicolevasilevsky** [comment]
Orphanet_373 is not hemihypertrophy (it is 'Simpson-Golabi-Behmel syndrome')

However, there is the class 'hemifacial hypertrophy' as a child of macroglossia, which may be incorrect.

**Comment by pnrobinson** [comment]
Hemihypertrophy subClassOf Macroglossia is NOT true in general. Hemihypertrophy refers to limbs and in general one would not expect one half of the tongue also to be enlarged.

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] exclude superclass macroglossia from MONDO_0010731 'Simpson-Golabi-Behmel syndrome'
- [ ] review all the children of macroglossia, I think these are all suspect.
