### ISSUE TITLE
weird annotation - BROAAD

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1860]
there is an annotation in Mondo called BROAAD, with just one usage on MONDO_0010758  'intellectual disability-developmental delay-contractures syndrome'.

@matentzn can I just go ahead and delete this (after I fix the annotation)? Related to #1844 

cc @cmungall

**Comment by matentzn** [comment]
If you mean "delete it from the edit file" ok! But I would never manually teach the release files.. It seems possible that BROAAD really is a type from one of our sources; meaning broadSynonym perhaps. In the absence of certainty, I would delete it, but it would be nice to know where it came from..

**Comment by nicolevasilevsky** [comment]
Yes, I meant delete it from the edit file.

I strongly suspect it is a typo from either me or Chris, one of us must have edited the text file. Both of our keyboards stick and we have typos with double letters (this keyboard is the worst!)
