### ISSUE TITLE
[Obsolete] CFM1 ?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1861]
**Mondo term (ID and Label)**
MONDO_0011378 CFM1

**Reason for deprecation**
Is this a real disease? This seems like it is a gene:
https://omim.org/entry/603855?search=190180&highlight=190180

**Suggested term to consider**
N/A

Related to #1855

**Comment by cmungall** [comment]
agreed

**Comment by nicolevasilevsky** [comment]
thanks! I'll take care of this
