### ISSUE TITLE
Relabel MONDO:0013128

### ISSUE THREAD

**Issue by tsneddon** [monarch-initiative/mondo#1879]
The ClinGen Kidney CDWG would like to request the following name change:

Mondo term (ID and Label): MONDO:0013128  familial juvenile hyperuricemic nephropathy type 2

Suggested new label: Autosomal dominant tubulointerstitial kidney disease due to mutations in REN (ADTKD-REN)

PMID: 25738250

**Comment by nicolevasilevsky** [comment]
@tsneddon 
![image](https://user-images.githubusercontent.com/6722114/89937570-2347b480-dbca-11ea-9513-aacb1cf845ce.png)

This class is part of a series, and I think we prefer to keep the naming consistent. Would you be okay if I added the new label as a synonym instead?

**Comment by tsneddon** [comment]
Sure, thanks Nicole.
