### ISSUE TITLE
Merge or redefine UMOD-related entities

### ISSUE THREAD

**Issue by tsneddon** [monarch-initiative/mondo#1880]
The ClinGen Kidney CDWG would like to request the following change as we have determined that the three UMOD diseases listed in OMIM should be lumped together for the purposes of gene curation (ie they are on a phenotypic spectrum):

Mondo term (ID and Label): MONDO:0019511 autosomal dominant medullary cystic kidney disease with hyperuricemia

Suggested new label: Autosomal dominant tubulointerstitial kidney disease due to mutations in UMOD (ADTKD-UMOD)

Add OMIM IDs 609886, 162000 and 603860
Merge in MONDO:0012356
Add HNFJ1 and MCKD2 to the definition and/or merge in MONDO:0008073 and MONDO:0011379

PMID: 25738250

Thanks,
Tam

**Comment by nicolevasilevsky** [comment]
@ahamosh- would OMIM consider merging these three OMIM records:

[OMIM:609886](https://www.omim.org/entry/609886): GLOMERULOCYSTIC KIDNEY DISEASE WITH HYPERURICEMIA AND ISOSTHENURIA (MONDO:0012356)
[OMIM:162000 ](https://www.omim.org/entry/162000): HYPERURICEMIC NEPHROPATHY, FAMILIAL JUVENILE, 1; HNFJ1 (MONDO:0008073)
[OMIM:603860](https://www.omim.org/entry/603860): MEDULLARY CYSTIC KIDNEY DISEASE 2; MCKD2 (MONDO:0011379)

**Comment by ahamosh** [comment]
I am looking into it and will get back to you soon.

**Comment by nicolevasilevsky** [comment]
@ahamosh have you had a chance to look into this? Thank you!

**Comment by nicolevasilevsky** [comment]
these were merged in OMIM. To do:
- [ ] Merge MONDO:0012356 'glomerulocystic kidney disease with hyperuricemia and isosthenuria' with 'familial juvenile hyperuricemic nephropathy type 1'
