### ISSUE TITLE
Rename isolated polycystic liver disease

### ISSUE THREAD

**Issue by tsneddon** [monarch-initiative/mondo#1882]
The ClinGen Kidney CDWG would like to request the following update:

Mondo term (ID and Label): MONDO:0008265 isolated polycystic liver disease

Suggested new label: Autosomal dominant polycystic liver disease (ADPLD)

Add genes: PRKCSH, SEC63, LRP5, ALG8, and SEC61B

PMID: 29038287

**Comment by nicolevasilevsky** [comment]
@tsneddon 
Similar to your other ticket, this disease is named as part of a series, and I believe our preference is to keep the naming consistent. Would it be okay to add this as a synonym?

- [ ] I will add the genes.

![image](https://user-images.githubusercontent.com/6722114/89958526-e04c0800-dbee-11ea-9e7c-6032d90a1a1b.png)

**Comment by tsneddon** [comment]
Nicole:
How do I view what you screenshot above?
I'm not seeing a term "autosomal dominant polycystic liver disease" in MONDO:
![image](https://user-images.githubusercontent.com/7256012/90006050-2ee8b900-dc66-11ea-878b-779234231017.png)
Thanks,
Tam

**Comment by nicolevasilevsky** [comment]
Looks like that was just updated in the last release, and it takes OLS about a week to pick up the latest release from Mondo, so I expect you'll see it in OLS by mid-next week (approx Aug 18 or 19).

In our [release notes](https://github.com/monarch-initiative/mondo/releases),  you can see the classes that were renamed.

And you can download the latest release files from the [release page](https://github.com/monarch-initiative/mondo/releases) as well. (The release files are OWL, OBO or json format, so you'd need Protege or similar software to open the OWL or OBO file.)

**Comment by nicolevasilevsky** [comment]
@tsneddon this is visible in OLS now:

![image](https://user-images.githubusercontent.com/6722114/95799612-11f25580-0caa-11eb-8284-2d169004220c.png)

I believe this ticket can be closed, please reopen if anything else is needed.

**Comment by tsneddon** [comment]
Please can you add an entry for the SEC61B gene under the autosomal dominant polycystic liver disease parent term:
http://purl.obolibrary.org/obo/MONDO_0000447
PMID: 29038287

**Comment by nicolevasilevsky** [comment]
@tsneddon MONDO_0000447 is a grouping class, SEC61B is linked to MONDO_0014860 'polycystic liver disease 2'. I will add the PMID to this class. Thanks!

**Comment by tsneddon** [comment]
@nicolevasilevsky MONDO_0014860 is linked to SEC63.
SEC61B is a different gene.
Please can you make a separate entry for SEC61B under the MONDO:0000447 umbrella term for autosomal dominant polycystic liver disease (PMID:29038287).
Thanks,
Tam

**Comment by nicolevasilevsky** [comment]
@tsneddon I will create a new ticket for this.
