### ISSUE TITLE
Charcot Marie Tooth dual parentage

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#189]
_From @jmcmurry on October 27, 2016 15:49_

Motor Peripheral Neuropathy
Sensory Peripheral Neuropathy

Generation of intermediate nodes semi-automatically? eg. Motor and sensory...

@pnrobinson @mellybelly @nicolevasilevsky 

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#161_

**Comment by nicolevasilevsky** [comment]
_From @pnrobinson on October 27, 2016 17:24_

As suggested on the call by MH, it would be great to create a suggested list and vet it by hand. 
I would make time for this in November of early December and would suggest we go through 2-3 major categories a week -- I think it would be good if we try to stick to community norms and integrate them wherever possible, so we will need to do a little research.

**Comment by nicolevasilevsky** [comment]
@jmcmurry Is this issue still outstanding? If yes, could you outline the action items, or if no, please close it.

**Comment by jmcmurry** [comment]
No longer really sure what this was about or what prompted it.
