### ISSUE TITLE
Dravet syndrome blank?

### ISSUE THREAD

**Issue by colleenXu** [monarch-initiative/mondo#1893]
**Mondo term (ID Label)**

**Bug/Typo/Error description**
I noticed no genes, phenotypes, publications, etc. for Dravet syndrome. 
https://beta.monarchinitiative.org/disease/MONDO:0100135
https://monarchinitiative.org/disease/MONDO:0100135

Has it been subsumed in generalized epilepsy with febrile seizures plus? I notice Dravet syndrome is mentioned in the description of this term: https://monarchinitiative.org/disease/MONDO:0018214

**Comment by nicolevasilevsky** [comment]
@colleenXu are you referring to the Monarch page? https://monarchinitiative.org/disease/MONDO:0100135

@kshefchek could you help?

**Comment by kshefchek** [comment]
@colleenXu do you know the OMIM and/or Orphanet ids for Dravet syndrome?  This is likely where we'll find the gene and phenotype data.  Possibly https://monarchinitiative.org/disease/MONDO:0100079

**Comment by nicolevasilevsky** [comment]
@kshefchek https://www.omim.org/entry/607208 has Dravet syndrome as a synonym, but we split Dravet syndrome from EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 6; EIEE6

**Comment by colleenXu** [comment]
@nicolevasilevsky yes, I'm referring to the Monarch page and what is returned by the API. Perhaps the issue should have been opened elsewhere, like https://github.com/monarch-initiative/helpdesk/issues?

I don't have a strong suggestion for OMIM or Orphanet IDs, and I'm not an expert in this area. However, after reviewing the previous issues, it seems like none of the OMIM IDs are exact equivalents because some cases of Dravet syndrome have unknown genetic cause. I like this article's discussion section of Dravet syndrome and gene-based vs syndrome-based diagnostic labels: https://onlinelibrary.wiley.com/doi/full/10.1111/epi.13889

**Comment by nicolevasilevsky** [comment]
@colleenXu sorry for the delayed reply. Yes, I think this should be reported on the Monarch GitHub, thanks!

I'm going to close this here.
