### ISSUE TITLE
split Ohtahara syndrome from early infantile epileptic encephalopathy?

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#19]
There is a request to have this split. Are these distinct diseases? 

Orphanet:1934 "Early infantile epileptic encephalopathy" has "Ohtahara syndrome" as synonym

DOID has two classes.

https://www.epilepsy.com/learn/types-epilepsy-syndromes/ohtahara-syndrome
suggests there are the same

**Comment by cmungall** [comment]
"Early infantile epileptic encephalopathy" sounds as if it should be more generic than a named syndrome like Ohtahara syndrome". 

https://en.wikipedia.org/wiki/Ohtahara_syndrome

says a synonym is " early infantile epileptic encephalopathy with burst-suppression (EIEE)"

**Comment by pnrobinson** [comment]
The eponym Ohtahara syndrome, which is synonymous with early infantile epileptic encephalopathy, came into prominent use in the mid-1980s [3].
according to http://www.sciencedirect.com/science/article/pii/S0887899412002688

But this is a very difficult area of the nosology anyway, and we should not discuss terms in isolation, we should have a workshop on the overall nosology. Several experts have expressed interest in working with HPO on this, so let's try to combine.

**Comment by nicolevasilevsky** [comment]
Ohtahara syndrome has been obsoleted, this can be closed.
