### ISSUE TITLE
append taxon to animal diseases in OMIA

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#190]
_From @jmcmurry on August 17, 2016 22:50_

Related to https://github.com/monarch-initiative/monarch-disease-ontology/issues/59 for human diseases, we should be able to append taxon to animal diseases. This will be needed for downstream enhancements to site search. https://github.com/monarch-initiative/monarch-app/issues/1317

<img width="462" alt="screen shot 2016-08-17 at 3 48 53 pm" src="https://cloud.githubusercontent.com/assets/3658863/17756038/53c88e3a-6492-11e6-91be-48d821deb09c.png">

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#144_

**Comment by nicolevasilevsky** [comment]
@jmcmurry is this something we still need?

**Comment by jmcmurry** [comment]
Yes please :)

**Comment by nicolevasilevsky** [comment]
This doesn't seem like a Mondo ticket, as we don't have these OMIA diseases in Mondo. It is related to https://github.com/monarch-initiative/mondo/issues/3855

I'll copy this over to the other ticket and close this, just so we're aware of it.
