### ISSUE TITLE
[merge]MONDO:0017161/frontotemporal dementia with motor neuron disease

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1902]
**Mondo term (ID and Label)**
`MONDO:0017161 frontotemporal dementia with motor neuron disease`

**Suggested revision and reasons**
Orphanet and OMIM appear to equate FTD-ALS and FTD-MND
`ORPHA:275872  frontotemporal dementia with motor neuron disease` (https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=275872)
`OMIM:105550 Frontotemporal dementia and/or amyotrophic lateral sclerosis 1` https://www.omim.org/entry/105550  

MONDO:0017161 has an XRef of `Orphanet:275872 Frontotemporal dementia with motor neuron disease`
 and `OMIMPS:105550 Frontotemporal dementia and/or Amyotrophic Lateral Sclerosis`, yet has a child of `MONDO:0000712 FTDALS`

If both `MONDO:0017161 frontotemporal dementia with motor neuron disease` and `MONDO:0000712 FTDALS`, should be retained, should `Orphanet:275872 Frontotemporal dementia with motor neuron disease` and `OMIMPS:105550 Frontotemporal dementia and/or Amyotrophic Lateral Sclerosis` be moved to `MONDO:0000712 FTDALS`?

**Comment by nicolevasilevsky** [comment]
@maglott thanks for this feedback - I see what you mean, it seems like MONDO_0000712 FTDALS is redundant with MONDO_0017161 'frontotemporal dementia with motor neuron disease'. I am not sure where MONDO_0000712 FTDALS came from, it xrefs a PubMed article, but doesn't appear to have come from source ontology, like most of our terms.

I propose we merge these two terms:
obsolete:
MONDO_0000712 FTDALS

reason:
duplicate

replace by term:
MONDO_0017161 'frontotemporal dementia with motor neuron disease'

**Comment by galyea-gard** [comment]
This is a bit complex and  GARD does not have this condition yet.  About 20% of ALS cases are associated with  FTD (which is known as ALS-FTD or as FDD-ALS).  ALS have different genetic "subtypes".  One of these, "C9orf72-Related Amyotrophic Lateral Sclerosis and Frontotemporal Dementia" I think is the most accurate on defining the cases where ALS and FTD are associated features (Please see: OMIM  105550 and GR  https://www.ncbi.nlm.nih.gov/books/NBK268647/) The other genetic subtypes of ALS can have  cognitive features (FDD) or not. I believe Orphanet groups all of these diseases  (ALS-FTD or FTD-ALS) under Frontotemporal dementia with motor neuron disease (see all the OMIM subtypes in this ORPHA:275872 page: OMIM: 105550  608030  612069  613954  615911  616437  616439).  So, I think that it will be OK to change it to the Orphanet term. Thanks, Gioconda
