### ISSUE TITLE
Create mechanism to push to Wikidata

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#192]
_From @mellybelly on April 13, 2016 12:59_

It be great to push the outcomes of the recent kBOOM output (especially after NCIT) to Wikidata.
see https://www.wikidata.org/w/api.php
@cmungall maybe this or Uberon a good first test for other OBO ontologies?

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#77_

**Comment by cmungall** [comment]
Next release will have a CC0 subset that can go to WD

**Comment by nicolevasilevsky** [comment]
can this be closed?
