### ISSUE TITLE
confusing axiom in `mondo.owl`

### ISSUE THREAD

**Issue by saramsey** [monarch-initiative/mondo#1921]
**Mondo term (ID and Label):**
`MONDO:0000001`

**Xref that should be fixed (ID and label):**
the file `mondo.owl` has an axiom asserting:
`MONDO:0000001`, `MONDO:equivalentTo`, `ICD10:N18`

<img width="912" alt="Screen Shot 2020-08-19 at 9 43 51 PM" src="https://user-images.githubusercontent.com/5562107/90718016-cdc47500-e265-11ea-8862-0638df0b9c92.png">

but isn't `ICD10:N18.9` "chronic kidney disease"?
see [the 2020 ICD-10-CM codes](https://www.icd10data.com/ICD10CM/Codes/N00-N99/N17-N19/N18-)

Apologies if we have misunderstood the `ICD10:N18` identifier in `mondo.owl`.

**Other comments:**

**Comment by saramsey** [comment]
I should add that this is causing issues in [KG2](https://github.com/RTXteam/RTX/tree/master/code/kg2) because it is leading to a `biolink:same_as` relationship between `MONDO:0000001` and "chronic kidney disease", which is causing problems for node synonymization and some of our reasoning code.

**Comment by asmvernon** [comment]
I was about to report the same issue. 
Indeed ICD10 N18 refers to "chronic kidney disease" (https://icd.who.int/browse10/2019/en#/N17-N19)

**Comment by saramsey** [comment]
Hello MONDO team, any update on this?

**Comment by nicolevasilevsky** [comment]
Hi, My apologies for the long delay! I'll look at this now.

**Comment by nicolevasilevsky** [comment]
good catch @saramsey and @asmvernon
I fixed this on a PR, it will be resolved in the next release in early March

**Comment by saramsey** [comment]
thank you!
