### ISSUE TITLE
[NTR/gene] TPM2-Related Myopathy

### ISSUE THREAD

**Issue by RedRiver1816** [monarch-initiative/mondo#1922]
**Preferred gene-related syndrome label**
TPM2-Related Myopathy

**Synonyms**
TPM2 myopathy
congenital myopathy related to TPM2
autosomal dominant TPM2-related myopathy

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
TPM2-related myopathy is a disorder of the musculoskeletal system that covers a wide spectrum of phenotypes and is caused by pathogenic variants in the skeletal muscle β-Tropomyosin gene. These variants lead to a variety of overlapping adult onset and congenital myopathies characterized by muscle weakness, amyotrophy, hypotonia, myopathic facies, scoliosis, and sometimes contractures among other phenotypes. Histologic findings on skeletal muscle biopsy are variable with nemaline and intranuclear bodies, cap-like lesions, core-like lesions, fiber-type disproportion, and dystrophic features all observed to some degree. (PMID: 23413262)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0017303 (Qualitative or quantitative defects of tropomyosin)
MONDO:0019952 (Congenital Myopathy)

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term?
MONDO:0012240 (Nemaline Myopathy 4, Cap Myopathy 2)
MONDO:0009711 (Congenital Fiber-Type Disproportion Myopathy)
MONDO:0007294 (Central Core Myopathy)

**Your nano-attribution (ORCID) or URL for a working group**
ClinGen Congenital Myopathy EP https://clinicalgenome.org/affiliation/40031/

**Comment**
The most penetrant phenotype among all of the TPM2-related myopathy disease entities is muscular weakness. Notably, other developmental disorders such as distal arthrogryposis have also been reported in association with TPM2 mutations. While phenotypic and mechanistic similarities demonstrate that the TPM2-related myopathy disorders share a similar pathogenic mechanism, these developmental disorders characterized primarily by contractures are not considered part of the same spectrum as this entity.

@nicolevasilevsky

**Comment by RedRiver1816** [comment]
Checking in to make sure there's no missing information or any questions regarding this update.

**Comment by nicolevasilevsky** [comment]
@RedRiver1816 This got pushed down on my list - I'l take a look at it today

**Comment by nicolevasilevsky** [comment]
> MONDO:0009711 (Congenital Fiber-Type Disproportion Myopathy)

Can you provide evidence this has a mutation in TPM2? OMIM says it has a mutation in TPM3:
https://www.omim.org/entry/255310

I'm happy to add this, just need some evidence.

**Comment by nicolevasilevsky** [comment]
Same with MONDO:0007294 (Central Core Myopathy) - can you provide evidence?
see: https://www.omim.org/entry/117000

**Comment by RedRiver1816** [comment]
You're correct in that traditionally those two are from TPM3, however there are a few cases with TPM2 variants. For example, PMID: 28881016 demonstrates CFTD with a TPM2 variant and PMID: 23413262 has an instance of "core-rod myopathy" due to the K7del variant in TPM2.

**Comment by nicolevasilevsky** [comment]
Thank you @RedRiver1816 I added those as children. This is pending review by @cmungall before it will be available
