### ISSUE TITLE
Add PRKCSH to MONDO:0008265

### ISSUE THREAD

**Issue by tsneddon** [monarch-initiative/mondo#1927]
**Mondo term (ID and Label)** MONDO:0008265 polycystic liver disease 1

**Synonym to be added** PRKCSH

**Synonym subtype: ie, broad/exact/narrow/related** Gene

**Comment by nicolevasilevsky** [comment]
@tsneddon we don't add gene symbols as synonyms, but I can add a subclass of axiom that says this disease is caused by disruption of this gene ('disease has basis in disruption of PRKCSH')

I'll do this for the similar tickets you requested too.
