### ISSUE TITLE
Review MONDO:0010682 myoclonic epilepsy, progressive, X-linked

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1928]
- the OMIM entry is from 1986 and the latest publication supporting an X-linked form is from the 70s. https://omim.org/entry/310370. Is an X-linked form still supported?
 - the PS only has AD/AR forms https://omim.org/phenotypicSeries/PS254800; it doesn't include this entry
 - we equate this PS to MONDO:0020074 - if we really think the X-linked form is a subtype we should include here, but coordinate with OMIM. **Question is - should MONDO_0010682 'myoclonic epilepsy, progressive, X-linked' be a child of MONDO_0020074 'progressive myoclonus epilepsy'?**
 - the is-a link to Unverricht-Lundborg syndrome is dubious/wrong
 - the other is-a seems unsupported
 -  Action item: we should probably exclude the other two subclasses on this term.

Related to #1764

**Comment by nicolevasilevsky** [comment]
Peter recommends obsoleting this in Mondo

**Comment by nicolevasilevsky** [comment]
@ahamosh could you comment if you have any objections to obsoleting MONDO_0010682 'myoclonic epilepsy, progressive, X-linked' in Mondo?
thanks!

**Comment by nicolevasilevsky** [comment]
confirmed that it is okay to obsolete this term

**Comment by sabrinatoro** [comment]
@nicolevasilevsky what is left to do on this issue? Do we still have questions for Ada and Peter?

**Comment by nicolevasilevsky** [comment]
I don't think so, it looks like we discussed it already and the ticket is closed and
