### ISSUE TITLE
missing tendinopathy

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#193]
_From @nlwashington on February 18, 2016 5:50_

i can't find tendinopathy.

https://en.wikipedia.org/wiki/Tendinopathy

_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#70_

**Comment by nicolevasilevsky** [comment]
@cmungall I don't see this term - should I add it?

**Comment by cmungall** [comment]
We have tendinitis. Can you provide examples of tendinopathies that are non-infammatory?

**Comment by nicolevasilevsky** [comment]
tendinosis
def: The chronic degeneration of a tendon without inflammation
source: PMID:27469590

Do you think we should add this and add tendonopathy as a parent?

These are subtypes of tendonitis, but it are not in MONDO, as far as I can see:
Paratenonitis
def: Inflammation of the outer layer of the tendon (paratenon) alone, whether or not the paratenon is lined by synovium.
source: PMID:14560540

Paratenonitis with tendinosis
def: Paratenonitis associated with intratendinous degeneration
source: PMID:14560540

**Comment by cmungall** [comment]
Go ahead and add all the these
