### ISSUE TITLE
Automation - take OMIMs with last major update

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1931]
See related PR: https://github.com/monarch-initiative/mondo/pull/1912

We need to automate ingesting the OMIMs with the last major update.

Could we auto-tag older OMIMs? (And then I think we'd need to review these)

**Comment by matentzn** [comment]
I need some context for this during the next meeting.

**Comment by nicolevasilevsky** [comment]
Decision: lets leave this until we know who will manage omim (Mondo vs Dipper)

**Comment by matentzn** [comment]
Notes:

we need to know these stale OMIMs (issue)
If this were tagged then the bad smell would be more immediately obvious. 
“auto-tag ancient OMIMs”
Last edit
Last publication, for example: https://omim.org/entry/271220, publications are from the 1970’s
Tag ancient

**Comment by nicolevasilevsky** [comment]
Discussed with Nico, this is determined to be too much effort for what it is worth.
