### ISSUE TITLE
review 'spondyloepimetaphyseal dysplasia' classification

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1932]
Related to #1764 and https://github.com/monarch-initiative/mondo/pull/1915

From @cmungall:
Do a review of 'spondyloepiphyseal dysplasia' in mondo

There are a a lot slurped from OMIM that are not classified under 'spondyloepiphyseal dysplasia', e.g

```

id: MONDO:0032885
name: spondyloepimetaphyseal dysplasia, Isidor-Toutain type
synonym: "SPONDYLOEPIMETAPHYSEAL DYSPLASIA, ISIDOR-TOUTAIN TYPE; SEMDIST" RELATED [OMIM:618728]
xref: OMIM:618728 {source="MONDO:equivalentTo"}
is_a: MONDO:0003847 {source="OMIM:618728"} ! Mendelian disease
```

I recommend closing this and making a ticket to review 'spondyloepimetaphyseal dysplasia' classification, ensure classification is complete, and fold the proposed merge into this.

**Question:**
There is not a generic 'spondyloepiphyseal dysplasia' class in Mondo, do we want one?

**Question:**
`MONDO_0011261 spondyloepiphyseal dysplasia, Nishimura type` and  `MONDO_0032835 spondyloepiphyseal dysplasia, nishimura type` are closing related in name.

Should they be merged?

They correspond to two separate OMIM entries though:
Mondo ID | Mondo Label | OMIM ID | OMIM Label
-- | -- | -- | --
MONDO_0011261 | spondyloepiphyseal dysplasia, Nishimura type | OMIM:602611 | SPONDYLOEPIPHYSEAL DYSPLASIA WITH CORONAL CRANIOSYNOSTOSIS, CATARACTS, CLEFT PALATE, AND MENTAL RETARDATION
MONDO_0032835 | spondyloepiphyseal dysplasia, nishimura type | OMIM:618618 | SPONDYLOEPIPHYSEAL DYSPLASIA, NISHIMURA TYPE; SEDN

**Comment by nicolevasilevsky** [comment]
Nicole - to do for now - use OMIM labels as primary labels in Mondo.

Need some advice from @ahamosh  - does the synonym 'spondyloepiphyseal dysplasia, nishimura type' belong to one or both of terms? Or should it only be applied to one term?

**Comment by nicolevasilevsky** [comment]
Nicole to do:
- [ ] rename MONDO_0016761 'spondylo-epi-(meta)-physeal dysplasia' to a label without dashes and make this label a synonym.
- [ ] 'spondyloepiphyseal dysplasia with punctate corneal dystrophy' should be a child of  MONDO_0016761

**Comment by nicolevasilevsky** [comment]
- [ ] 'spondyloepiphyseal dysplasia tarda, Kohn type' and 'spondyloepiphyseal dysplasia tarda, X-linked' and 'spondyloepiphyseal dysplasia tarda with characteristic facies' should be children of 'spondyloepiphyseal dysplasia tarda'
- [ ] add logical def for AD and AR subtypes of 'spondyloepiphyseal dysplasia tarda, Kohn type'

**Comment by ahamosh** [comment]
Hi All, First, 618618 is NOT the same as 602611.  The former is Nishimura type, has a gene, etc.  The latter is a single family and no gene has been identified.  The features are not the same.  I will talk with Joanna and Carol about making a spondyloepiphyseal dysplasia phenotypic series.  The parent is certainly appropriate for Mondo.  Also you are correct that spondyloepimetaphyseal dysplasia is not the same as spondyloepiphyseal dysplasia, although both can come under the grandparent (right term?) of skeletal dysplasia.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh!
