### ISSUE TITLE
[NTR/gene] MSX2-related craniosynostosis

### ISSUE THREAD

**Issue by mhughes5** [monarch-initiative/mondo#1933]
**Preferred gene-related syndrome label**
MSX2-related craniosynostosis

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
The premature fusion of one or more cranial sutures resulting from a variant in or encompassing the MSX2 gene. The phenotypic spectrum includes syndromic and non-syndromic forms of craniosynostosis including Boston type.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
craniosynostosis (MONDO:0015469)

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term?
craniosynostosis, Boston type MONDO:0011481

**Your nano-attribution (ORCID) or URL for a working group**

**Comment by nicolevasilevsky** [comment]
@mhughes5 are you part of one of the ClinGen expert working groups? Could you please let me know which one so I can add it to the term?
thanks!

**Comment by nicolevasilevsky** [comment]
pinging @mhughes5

**Comment by mhughes5** [comment]
Hi Nicole, sorry I missed this notification. I'm a part of the Craniofacial Malformations GCEP, which is in the application process

**Comment by cmungall** [comment]
Do we think the existing OMIM entry https://omim.org/entry/604757 CRS2 encompasses Boston and non-Boston types? What are some of the non-Boston types causes by MSX2? Is the Bosnian type referenced in the OMIM entry a distinct type?

@nicolevasilevsky we should examine this more closely. It may be the case that the existing class MONDO:0011481 which has name "craniosynostosis, Boston type" and has a definition that seems specific to the Boston type yet is equivalent to https://omim.org/entry/604757 is ambiguous and may need to be obsoleted-split.

**Comment by mhughes5** [comment]
@cmungall @nicolevasilevsky After an initial lumping and splitting call, the expert panel decided MSX2-related craniosynostosis would be the most appropriate term for which to curate. However, if there are larger questions about how it would fit into the existing ontology, I could try and arrange a call for the three of us + the expert panel chairs.

**Comment by nicolevasilevsky** [comment]
@mhughes5 that would be great if you could arrange a call. We already have a standing call on Fridays at 10am PT, if folks were available to join one of these weeks. Or if you'd prefer to find another time, that works too.

**Comment by cmungall** [comment]
It would be good to include @ahamosh. My main question is how this proposed MSX2-related craniosynostosis term relates to  https://omim.org/entry/604757 CRS2 - are they equivalent, or is one a subtype or the other, or do they overlap?

**Comment by ahamosh** [comment]
Hi All,  CRS2 is craniosynostosis due to MRSX2.  The two families described in OMIM are the Boston family and the Bosnian family.  Both are individual huge pedigrees with lots of affected individuals. They have variable expressivity but it looks like everyone has craniosynostosis.  I would certainly not call these different types.  There are seven entries in the craniosynostosis phenotypic series. I want to be sure that everyone in Mondo and the ClinGen expert panels understands that OMIM splits phenotypes molecularly (by gene), but doesn't put the gene symbol in the name, hence craniosynostosis 2, rather than MSX2-related craniosynostosis.    Also despite the nice grammar of GENE SYMBOL-related DISEASE, I think that it is a huge mistake to lead with the gene symbol for data mining and gene symbol stability reasons.

**Comment by mhughes5** [comment]
From our initial EP discussion, the rational for curating for a MSX2-related was to account for large translocations involving MSX2 described in patients with craniosynostosis, in addition to the Boston and Bosnian families. I am meeting with the craniofacial malformations EP chairs on Monday 9/21 and will raise the issue again as to which MONDO term is appropriate.

**Comment by mhughes5** [comment]
Hi everyone, I talked to the Craniofacial Malformation EP chairs today and they agreed we will curate for MSX2- craniosynostosis. Thanks so much for your input!

**Comment by nicolevasilevsky** [comment]
If I understand this correctly, I will add MSX2-related craniosynostosis and CRANIOSYNOSTOSIS 2 should be a child

**Comment by ahamosh** [comment]
Hi Nicole, MSX2-related craniosynostosis is a synonym for CRANIOSYNOSTOSIS 2.  That is why I advocated for retaining craniosynostosis 2 as the name.  It is in the literature that way...
Thanks,  Ada

**Comment by nicolevasilevsky** [comment]
Ah, got it - thanks for clarifying!

I'll make this change.

**Comment by ahamosh** [comment]
Hi Nicole, One more bit of clarification: I don't think that either the 'Boston-type' or 'Bosnian-type' exist as true types.  Not sure the right way to represent this in the ontology.  If you want to keep those 2, they are children of craniosynostosis 2 which is a synonym or alternate title for MSX2-related craniosynostosis.

**Comment by nicolevasilevsky** [comment]
Hi @ahamosh 
Just to clarify:
- [ ] we should rename MONDO_0011481 'craniosynostosis, Boston type' to Craniosynostosis 2

Is it okay to leave 'craniosynostosis, Boston type' and 'craniosynostosis, Bosnian type' as related synonyms? If they are not true types, I don't think we'd want to create new classes for them. (Note - Bosnian type is not a synonym currently, but I can add it.)

**Comment by ahamosh** [comment]
I would obsolete Boston and not add Bosnian.  This is my read.

**Comment by nicolevasilevsky** [comment]
Ok, I'll exclude Boston as a synonym - thanks @ahamosh!
