### ISSUE TITLE
Merge MONDO:0033004 and MONDO:0033004

### ISSUE THREAD

**Issue by tsneddon** [monarch-initiative/mondo#1935]
**Mondo term (ID and Label)** MONDO:0033004 - polycystic kidney disease 4 

**Reason for deprecation** Links to OMIM:263200 / PKHD1

**Term to be merged with** MONDO:0009889 - autosomal recessive polycystic kidney disease

**Comment by cmungall** [comment]
Thank you!

I think there is a reason for not merging, AR is not equivalent to PKD4 
https://omim.org/phenotypicSeries/PS173900

PKD5 is also AR, which justifies keeping the grouping

@nicolevasilevsky can you assign PKD5 as AR thanks

**Comment by pnrobinson** [comment]
What is the motivation for deletion? There is a separate OMIM entry for PKD4 (263200) and PKD1 (173900)?

**Comment by nicolevasilevsky** [comment]
> can you assign PKD5 as AR thanks
done on PR
