### ISSUE TITLE
MONDO:0018661 Zika virus infectious disease - synonyms and typo

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1937]
**MONDO:0018661 Zika virus infectious disease**

**Synonym to be added**
congenital Zika syndrome [narrow]
congenital Zika virus infection [narrow]
fever, Zika [narrow or related]
ZikV infection [exact or related]

Also please "mosquito" at the very start of the def should read "Mosquito". Thanks!

(Note for self: stemming from https://github.com/EBISPOT/efo/issues/848, but doesn't need any further action in EFO.)

**Comment by maglott** [comment]
This is for my own education.  
If we think these terms 
   congenital Zika syndrome [narrow]
   congenital Zika virus infection [narrow]
 are narrower than Zika virus infectious disease, should they define distinct entity?

**Comment by paolaroncaglia** [comment]
Dear @maglott ,

I'll leave it to main Mondo editors to confirm, but IMHO in this case I would not create distinct subclasses for congenital Zika because those wordings are used to denote the same viral infection when that is transmitted to a fetus. Unless you'd want to discriminate that a child is sick because he was transmitted the infection during gestation vs. because he/she was infected directly by a mosquito i.e. after birth. Symptoms are different, so now I'm having second thoughts, would a 'congenital' subtype be useful to clinicians after all?

**Comment by nicolevasilevsky** [comment]
@pnrobinson could you give advice, from a physician's perspective? thanks!

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I'll add these as synonyms for now.

**Comment by pnrobinson** [comment]
I think we absolutely need a separate term for congenital Zika because clinically it is a very different disease.
For postnatal infections, "Most people infected with the Zika virus have no signs and symptoms, while others report mild fever, rash and muscle pain."
Congenital Zika means the fetus is infected in the womb, and a series of very serious malformations can occur, such as microcephaly. This obviously does not happen with the postnatal infection. I would suggest making sibling terms "Zika infection" and "Congenital Zika infection"

**Comment by cmungall** [comment]
I accidentally merged your PR @nicolevasilevsky but it's incomplete

See @pnrobinson's comments above. We should include the distinct entity. Ypu'll want to revise the synonyms afterwards as we won't be cramming multiple concepts into one ID

**Comment by nicolevasilevsky** [comment]
We already had a separate term in Mondo: MONDO_0000890 'Zika virus congenital syndrome'

I made it a subclass of 'vector-borne disease' (and a sibling of 'Zika virus infectious disease').

Is there any other action needed?
