### ISSUE TITLE
Cystinuria type A (MONDO:0019745) incorrect exactmatch MeSH ID 

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#1955]
Current:
cystinuria type A (MONDO:0019745) has exactMatch MeSH:C531664 but this maps to Cystinuria type 1

Suggest:
cystinuria type A (MONDO:0019745)  has exactMatch MeSH:C565652 which maps to Cystinuria type A

CystinuriaType I, II and III are a biochemical classification system for Cystinuria whereas the type A and type B (there is also a type AB) are based on genetics. So I don't think type I is interchangeable with type A so I don’t know why cystinuria type A (MONDO:0019745) references the MeSH term for Cystinuria type 1 (Mesh: C531664) and not the MeSH term for Cystinuria type A (Mesh: C565652), if you agree can this be corrected? Thank you

**Comment by nicolevasilevsky** [comment]
thanks @LCCarmody - this will be fixed in the next release around Oct 01

**Comment by LCCarmody** [comment]
Not me! :) It was  @lcdaugherty

**Comment by nicolevasilevsky** [comment]
Oops, ha, sorry @LCCarmody!
