### ISSUE TITLE
apolipoprotein A-I , OMIM, and possible children

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#1957]
apolipoprotein A-I in orphanet (https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=425) references OMIM: 604091  and 618463, but MONDO_0011393 references only 604091

https://omim.org/entry/618463 is defined as HYPOALPHALIPOPROTEINEMIA, PRIMARY, 2 and https://omim.org/entry/604091 is defined as HYPOALPHALIPOPROTEINEMIA, PRIMARY, 1.

Should MONDO_0011393 be retained to represent the equivalent of ORPHA:425 ,
 two new records be created for the MIM numbers and 
604091 be removed from MONDO_0011393?

**Comment by nicolevasilevsky** [comment]
cc @kanems

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet 
Looks like Orphanet is xref'ing two OMIM terms as exact for Orphanet:425, but we think they should be NTBT instead:
- OMIM:618463 (E (Exact mapping: the two concepts are equivalent))
- OMIM:604091 (E (Exact mapping: the two concepts are equivalent))

**Note to self:**
we will create a new Mondo entry for a class that has mutations in both genes
It seems like there are 3 different diseases:
1) New class: Combined ApoA-I and ApoC-III Deficiency - where there is mutations in both genes (PMID: 3118360)
2) MONDO_0011393 _rename to hypoalphalipoproteinemia, primary, 1_, equiv to OMIM:604091 (gene variation in ABCA1)
3) MONDO_0032766 'hypoalphalipoproteinemia, primary, 2', equiv to OMIM:618463 (gene variation in APOA1)

Additionally, we will add a grouping class for these three terms that correspond to Orphanet:425 Apolipoprotein A-I deficiency (child of hypoalphalipoproteinemia). @ana-rath-orphanet Does this make sense to you?
 
@ahamosh would OMIM consider creating a new class too? (in 1 above, Combined ApoA-I and ApoC-III Deficiency)

**Comment by cmungall** [comment]
Thanks @nicolevasilevsky - all the above looks good though now I'm wondering why the ORDO class isn't simply equivalent to OMIM:618463 based on the name?
