### ISSUE TITLE
Ensure no Mondo terms use labels from other ontologies

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#1972]
Not really high priority, but since there are only three cases:

MONDO:0007955	rdfs:label	Meckel's diverticulum
MONDO:0045042	rdfs:label	localized
MONDO:0007303	rdfs:label	cervical rib

All three terms share a label with at least one external ontology (UBERON or PATO I think). In the last meeting we agreed to rename sensibly.

**Comment by nicolevasilevsky** [comment]
these have all been fixed already and are on master.
