### ISSUE TITLE
[NTR]Multiple

### ISSUE THREAD

**Issue by paulacarrio** [monarch-initiative/mondo#1973]
Dear Nicole,

Following up with the initiated project with Michael Baudis and the mappings ICD-O-3 Morphology+Topography - NCIt, here I provide a first set of new terms for inclusion at NCIt. 

Please, advise if the submissions need to strictly be done one by one.

Thanks in advance.

Best regards,
Paula Carrio
[terms.xlsx](https://github.com/monarch-initiative/mondo/files/5209507/terms.xlsx)

**Comment by nicolevasilevsky** [comment]
Hi @paulacarrio  - these are terms you'd like to request to be added to NCIt, right? You'll have to make these new terms to NCIt here: https://ncitermform.nci.nih.gov/ncitermform/?dictionary=NCI%20Thesaurus

Let me know if you need any help.
Best,
Nicole
