### ISSUE TITLE
Revise diseases with non-unique textual definitions

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#1975]
ROBOT report:

```
MONDO:0001868	IAO:0000115	A form of glaucoma in which there is no visibl...
MONDO:0007665	IAO:0000115	A form of glaucoma in which there is no visibl...
```

```
MONDO:0012676	IAO:0000115	Any autosomal recessive malignant osteopetrosi...
MONDO:0012679	IAO:0000115	Any autosomal recessive malignant osteopetrosi...
```

These must be duplicates to classes _outside_ of Mondo (use Protege search to find)
MONDO:0005318	IAO:0000115	Oral aphthous ulcers typically present as pain...
MONDO:0003085	IAO:0000115	Inflammation of the cornea.
MONDO:0007303	IAO:0000115	A rib that is attached to a cervical vertebra.

**Comment by nicolevasilevsky** [comment]
MONDO:0005318 'canker sore' has the text def from HPO - I think this is allowable, yes?

**Comment by matentzn** [comment]
Yes! Since we explicitly allow (provenanced definition to migrate over). Made a ticket [here](https://github.com/ontodev/robot/issues/734), so yes, you can ignore this for now.

**Comment by nicolevasilevsky** [comment]
Cool - will close this, as these have all been addressed.

**Comment by cmungall** [comment]
Let's think more critically - does canker sore really belong in mondo? If it does, should it really have the same definition? If it does, then we surely should have an equivalence axiom between the two?

**Comment by nicolevasilevsky** [comment]
Based on past comments from Peter, "I think that canker sore is probably best as an HPO term.", so we should obsolete canker sore from Mondo:
https://github.com/monarch-initiative/mondo/issues/1262

**Comment by nicolevasilevsky** [comment]
Although it is a disorder in NCIt:
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C62546

We could use their def instead?

**Comment by maglott** [comment]
Canker sore is also a disease in UMLS, represented under [C0038363]  Aphthous Stomatitis
