### ISSUE TITLE
References of deprecated entities

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#1982]
These classes (column 1) refer to deprecated entities (column3) in a column 2 expression!

MONDO:0001328	owl:someValuesFrom	GO:0004887
MONDO:0010142	owl:someValuesFrom	GO:0004887
MONDO:0010186	owl:someValuesFrom	GO:0008434
MONDO:0010966	owl:someValuesFrom	MONDO:0000746
MONDO:0019154	owl:someValuesFrom	GO:0004882
MONDO:0020186	rdfs:subClassOf	MONDO:0016033
MONDO:0024239	owl:someValuesFrom	GO:0072358

Happy hunting and fixing!

**Comment by nicolevasilevsky** [comment]
MONDO:0020186 is obsoleted and it doesn't have any parents

**Comment by matentzn** [comment]
did you check the other way around?

**Comment by matentzn** [comment]
Cornelia de lange (Protege usage tab!)

**Comment by nicolevasilevsky** [comment]
my bad!
fixed now :)
