### ISSUE TITLE
MONDO:0018087 'viral hemorrhagic fever'

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1991]
**MONDO:0018087 'viral hemorrhagic fever'**

Please consider adding the following synonyms, to aid in searches:
hemorrhagic fever [narrow or related]
haemorrhagic fever [narrow or related]
viral haemorrhagic fever [exact]
Haemorrhagic Fevers, Viral [exact]
Hemorrhagic Fevers [narrow or related]
VHF [acronym if feasible; otherwise narrow or related]
VHFs [acronym if feasible; otherwise narrow or related]
As suggested by one of our collaborators at EFO (see https://github.com/EBISPOT/efo/issues/854).

Thanks,
Paola

(Note for self: no further action for EFO.)

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/1993

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia if possible, could you provide dbxrefs for the syns?

thanks!

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,

> @paolaroncaglia if possible, could you provide dbxrefs for the syns?

They were requested by our collaborator @gkos-bio (Gautier Koscielny). Looks like his ORCID id is https://orcid.org/0000-0002-6315-0263. Thanks.

Paola

**Comment by cmungall** [comment]
Hi @gkos-bio!

bacterial forms exist
https://science.jrank.org/pages/3289/Hemorrhagic-Fevers-Diseases.html

I think the correct scope is BROAD

perhaps we should instantiate the triad
