### ISSUE TITLE
MONDO:0004651 smallpox

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#1993]
**MONDO:0004651 smallpox**

Please consider adding the following synonyms, as suggested by one of our collaborators (see https://github.com/EBISPOT/efo/issues/855):

variola virus [related]
Variola Virus VAR [related]
Variola Virus [related]
VARIOLA VIRUS [related]
Smallpox Virus [related]

Thanks.

(Note for self: no further action needed in EFO.)

**Comment by maglott** [comment]
Should we have a different relationship between infectious  diseases and their etiological agent?  I personally vote against treating as a synonym, even if only 'related'

**Comment by nicolevasilevsky** [comment]
Good question @maglott 

@cmungall and @pnrobinson do you have any opinion?

**Comment by pnrobinson** [comment]
How about adding "variola virus infection" as a synonym?

**Comment by nicolevasilevsky** [comment]
that sounds good to me, thanks @pnrobinson!

@paolaroncaglia does that work for you?

**Comment by paolaroncaglia** [comment]
@maglott 
@nicolevasilevsky 
@pnrobinson 
I agree with your strategy. Also, I trust/hope that a good search engine would pick up the NCBITaxon label anyway, so hopefully the collaborator who requested those synonyms will agree too. Mentioning him here just in case @gkos-bio, but @nicolevasilevsky please go ahead with your plan. Thanks!
