### ISSUE TITLE
Revise: Add parent term of MONDO:0010252

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#2002]
**Mondo term (ID and Label): Intellectual disability, X-linked, with panhypopituitarism MONDO:0010252

**Suggested revision and reasons: Currently, Intellectual disability, X-linked, with panhypopituitarism is a child term of panhypopituitarism, X-linked and the ClinGen ID/Autism GCEP would like to request that it should also appear as a child term of X-linked syndromic intellectual disability MONDO:0020119.  

I would like to request that this is release as soon as possible. Thank you!

**Comment by nicolevasilevsky** [comment]
@tibingaman I plan to run the next release in a couple weeks, is that soon enough?
