### ISSUE TITLE
Creation of Disease Entity for FOXG1 Disorder  

### ISSUE THREAD

**Issue by CarrieBarry** [monarch-initiative/mondo#201]
For new term requests, please provide the following information:

This request is on behalf of the ClinGen Rett/Angelman-like Variant Curation Expert Panel. Following precuration of this gene we find that the disease entity is different in nature than possible disease terminology that currently exists and request for a new term associated with a FOXG1 Disorder.

# •	List of subclasses
o	Rett Syndrome, Congenital Variant (MONDO:0013270)
o	Atypical Rett Syndrome (MONDO:0017746)
# •	Suggested parent(s) terms for FOXG1 Disorder
o	Monogenic disease with epilepsy (MONDO:0015653)
o	Rare genetic syndromic intellectual disability (MONDO:0015983)
o	Rare Pervasive Developmental Disorder (MONDO:0015680)
o	Motor Stereotypies (MONDO:0017656)
# •	Suggested definition
o	FOXG1 is the cause of a developmental phenotype which differs from classic Rett syndrome and other so-called Rett variants based on a specific and recognizable combination of developmental and MRI findings. Specifically, neurodevelopmental impairment presents during early infancy, in contrast to classical Rett in which symptoms appear after a period of normal development. Patients can also be affected by motor dysfunction, epilepsy, stereotypic hand movements, dyskinetic-hyperkinetic movement disorder, abnormal breathing and unexplained episodes of crying, lack of speech development, and severe post-natal microcephaly with reduced myelinization and/or corpus callosum hypoplasia or agenesis on MRI. FOXG1 disorder has distinct but overlapping features with a rapidly growing group of developmental encephalopathies that already includes Angelman (UBE3A-associated), Rett (MECP2-associated), Pitt Hopkins (TCF4-associated), Christianson (SLC9A6-associated), CNTNAP2-associated, and NRXN1-associated syndromes. 
o	PMID:21441262 Our data and review of prior reports confirm mutations or dysregulation of FOXG1 as the cause of the developmental phenotype, which differs from classic Rett syndrome and other so-called Rett variants based on a specific and recognizable combination of developmental and brain imaging features. We prefer to designate this as the FOXG1 Disorder which has overlapping features with a rapidly growing group of developmental encephalopathies that already includes Angelman (UBE3A associated), Rett (MECP2 associated), Pitt Hopkins (TCF4 associated), CNTNAP2 associated, NRXN1 associated, and SLC9A6 associated syndromes.
# •	List of references supporting the grouping
o	The PMIDS in support of this assertion: 21441262, 28661489
# •	Analysis of how other disease IDs relate to this 
o	The most penetrant phenotype among all the FOXG1-related disorders regard the early neurodevelopmental phenotype; but due to the absence of clearly defined and/or distinct differences in molecular mechanism, coupled with noted phenotypic variability (both intra- and inter-familial) the ClinGen Rett/Angelman experts believe the FOXG1-related disorder is more distinct than the historically associated Rett syndrome related to MECP2, UBE3A, TCF4, and SLC9A6. Therefore, we are proposing that although the FOXG1-related disorder has a similar presentation to Rett-like syndromes, this gene-disease relationship should have its own disease assertion.
# •	Genes
o	 FOXG1
# •	Any verbiage you care to add
o	Subtypes of the heterogeneous, eponymously named Congenital variant of Rett Syndrome, and Atypical Rett Syndrome are caused by mutations in the gene FOXG1. The common and most penetrant phenotype shared among these disease entities is neurodevelopmental impairment present in early infancy, progressive microcephaly, and MRI of the brain showing reduced myelinization and/or abnormal corpus callosum. Stereotypic hand movements, epilepsy, and abnormal breathing can have variable phenotypic expressivity.

**Comment by CarrieBarry** [comment]
@erinriggs

**Comment by CarrieBarry** [comment]
Just wanted to check in on the status of this ticket and if any additional information is needed, thanks!

**Comment by nicolevasilevsky** [comment]
Hi @CarrieBarry - I will take a closer look at this ticket asap and will get back to you with any questions.

**Comment by CarrieBarry** [comment]
Preview
@nicolevasilevsky

Hello Nicole!

Thank you so much for looking into this for us as well! To clarify, yes we wish to add the new term 'FOXG1 Disorder' under the suggested parent terms listed above as they are the current existing parent terms of Rett Syndrome - in order to keep the same logical setup.

Let me know if you have any additional questions!

Thank you,
Carrie

**Comment by nicolevasilevsky** [comment]
Minor comment - when noting the names of classes, could you write them in lowercase, it just makes things a bit faster for me when editing the ontology, because all of the labels are lowercase unless it is a proper name. Thank you! :)

**Comment by nicolevasilevsky** [comment]
added new class MONDO_0100040 'FOXG1 disorder'
see PR #258 

As with #202, Atypical Rett Syndrome (MONDO:0017746) is a grouping class, so it is not a suitable subclass for FOXG1 disorder.

Rett Syndrome, Congenital Variant (MONDO:0013270) is inferred to be a subclass.
