### ISSUE TITLE
Creation of Disease Entity for CDKL5 Disorder

### ISSUE THREAD

**Issue by CarrieBarry** [monarch-initiative/mondo#202]
For new term requests, please provide the following information:

This request is on behalf of the ClinGen Rett/Angelman-like Variant Curation Expert Panel. Following precuration of this gene we find that the disease entity is different in nature than possible disease terminology that currently exists and request for a new term associated with a CDKL5 Disorder.

# List of diseases groups
o	Epileptic Encephalopathy, Early Infantile, 2 (MONDO:0010396)
o	Early Infantile Epileptic Encephalopathy (MONDO:0016021)
o	Atypical Rett Syndrome (MONDO:0017746)
o	West Syndrome (MONDO:0018097)
# Suggested parent(s) terms for CDKL5 Disorder
o	Monogenic disease with epilepsy (MONDO:0015653)
o	Rare genetic syndromic intellectual disability (MONDO:0015983)
o	Rare Pervasive Developmental Disorder (MONDO:0015680)
o	Motor Stereotypies (MONDO:0017656)
o	X-Linked Syndromic Disability (MONDO:0020119)
# Suggested definition
o	The CDKL5 disorder is an independent clinical entity from Rett syndrome (RTT) associated with early-onset encephalopathy. CDKL5 disorder was historically described as "early-onset seizure variant of RTT”, however individuals with CDKL5 disorder lack some of the distinctive clinical features of classical Rett syndrome such as the clear period of regression and the characteristic intense eye-gaze (PMID:21154482). Of note, normal development during the first 6 months of life commonly seen in RTT is rare in individuals with CDKL5 disorder. Additionally, only 19/75 females and no males with pathogenic CDKL5 variants fulfilled all previously defined criteria for early-onset seizure variant of Rett syndrome (ESV RTT), largely due to absence of regression in all males and most females. (PMID:22872100)
# List of references supporting the grouping
o	The PMIDS in support of this assertion: 21154482, 22872100, 27528505, 27080038
# Analysis of how other disease IDs relate to this
o	The most penetrant phenotype among all the CDKL5-related disease entities is early-onset encephalopathy and dysmorphic facial features; but due to the absence of clearly defined and/or distinct differences in molecular mechanism, coupled with noted phenotypic variability (both intra- and inter-familial) these entities appear to be part of a broader disease entity.
# Genes
o	CDKL5
# Any verbiage you care to add
o	Subtypes of the heterogeneous, eponymously named Early Infantile Epileptic Encephalopathy, Atypical Rett Syndrome, West Syndrome are caused by mutations in the gene CDKL5. The common and most penetrant phenotype shared among these disease entities is early onset epilepsy, progressive microcephaly, dysmorphic facial features, and intellectual disability, with stereotypic hand movements, respiratory impairment with breath holding and hyperventilation having variable phenotypic expressivity.

**Comment by CarrieBarry** [comment]
@erinriggs

**Comment by CarrieBarry** [comment]
Just wanted to check in on the status of this ticket and if any additional information is needed, thanks!

**Comment by nicolevasilevsky** [comment]
Hi @CarrieBarry - I will take a closer look at this ticket asap and will get back to you with any questions.

**Comment by CarrieBarry** [comment]
@nicolevasilevsky 

Hello Nicole!

Thank you so much for looking into this for us! To clarify, yes we wish to add the new term 'CDKL5 Disorder' under the suggested parent terms listed above as they are the current existing parent terms of Rett Syndrome - in order to keep the same logical setup. 
Regarding the list of disease groups - those are all the currently listed disease assertions of CDKL5 across OMIM and Orphanet. Essentially we wish the more accurate term 'CDKL5 disorder' to encompass all of those disease assertions i.e. replacing them as a more inclusive and broader term.

Let me know if this was helpful!

Thank you, 
Carrie

**Comment by cmungall** [comment]
Should we revisit this one in light of today's discussion?

Maybe give a more specific name? GARD calls it "CDKL5 deficiency disorder"

**Comment by ErinRiggs** [comment]
I completely understand all of the points against a gene-based name brought up in discussion today, and we typically try not to use these types of terms for exactly those reasons.  However, in this particular case, we did discuss these things with the Rett-Angelman Expert Panel before they decided to go with this gene-based name.  They felt very strongly at the time that this was the best choice; their main desire was to distinguish this entity from Rett syndrome, and they felt that "Atypical Rett" was inappropriate, and they did not wish to use an eponym (Ada mentioned briefly some of the reasons some people don't like those). I believe Ingo also mentioned a few reasons why the epilepsy-focused names were inappropriate.  We can certainly check back in again with them, though I am doubtful they would be interested in changing, unless they were presented with a plausible alternative (i.e., none of the  previous disease names associated with this gene).  Do you have any suggestions? Copying in @kellytoner to add this item to the next Rett/Angelman agenda (12/17), with possible follow-up on Neurodevelopmental CDWG for cross-discussion with ID/Autism and Epilepsy teams.

**Comment by cmungall** [comment]
Thanks! I think this is sufficient. @nicolevasilevsky let's think of ways we can record some of this as provenance in the ontology
