### ISSUE TITLE
[Merge] MONDO_0016021 'early infantile epileptic encephalopathy' and MONDO_0100062 'developmental and epileptic encephalopathy'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2027]
Based on the ClinGen call today with @ahamosh and @ihelbig, OMIM and Mondo should do the following action items:

**OMIM:**
- rename ''early infantile epileptic encephalopathy' to 'developmental epileptic encephalopathy' and rename classes in the phenotypic series to 'developmental epileptic encephalopathy 1, 2, etc.'

**Mondo:**
- [x]  Merge MONDO_0016021 'early infantile epileptic encephalopathy' with MONDO_0100062 'developmental and epileptic encephalopathy'
- [x] add comment/reason for deprecation: This term will be renamed to 'developmental epileptic encephalopathy' in OMIM. 
- [x] @ihelbig Should I rename MONDO_0100062 'developmental and epileptic encephalopathy' to 'developmental epileptic encephalopathy' or just add it as a synonym?
- [x] rename children of 'early infantile epileptic encephalopathy' to developmental epileptic encephalopathy 1, 2, etc. to align with OMIM. 
- [x] Change existing label to be a synonym. 
- [x] Add synonym DEE1, DEE2, etc.

**Comment by nicolevasilevsky** [comment]
@matentzn - could we automatically update the labels for the early infantile epileptic encephalopathy subclasses after OMIM makes this change? (Ie when we do the next OMIM ingest?) 

Or maybe we can use ROBOT to address this ticket? There are a lot of subclasses and it will take a minute to do this in Protege.

**Comment by matentzn** [comment]
Put on the agenda for Friday!

**Comment by nicolevasilevsky** [comment]
already done :)

**Comment by nicolevasilevsky** [comment]
I will make these changes manually

**Comment by ahamosh** [comment]
Hi @nicolevasilevsky and @ihelbig,  
We at OMIM are trying to make sure we do this once and correctly.  Is it developmental and epileptic encephalopathy?  That is what is in the literature. Also this moniker applies regardless of age of onset (as long as it is childhood), correct?  Ingo, Joanna has a few questions for you.  What is the best way to reach you?  Thanks!
=

**Comment by ahamosh** [comment]
Not sure why that is all huge and bold??

**Comment by nicolevasilevsky** [comment]
I fixed it, there was an = at the end.
Apparently that is some kind of formatting in markdown!

**Comment by nicolevasilevsky** [comment]
pinging @ihelbig

**Comment by ahamosh** [comment]
Nicole, Ingo answered Joanna directly. We are calling the development and epileptic encephalopathy (DEE) and we are going through them now.  It will take a little while.
Thanks,
Ada

**Comment by nicolevasilevsky** [comment]
I renamed all the classes to be developmental and epileptic encephalopathy, to match OMIM
