### ISSUE TITLE
OMIM ingest to map UniProtKB 2020_06 release to MONDO

### ISSUE THREAD

**Issue by Antonialock** [monarch-initiative/mondo#2039]
Hello,

After our last update, we would like new MONDO terms for the following terms:

UniProt Accession | Disease Name | OMIM | Comment | MONDO:def_cite
-- | -- | -- | -- | --
DI-05867 | Warfarin sensitivity, X-linked. | 301052 |   |  
DI-05874 | Arthrogryposis multiplex congenita 5. | 618947 |   |  
DI-05876 | Suleiman-El-Hattab syndrome. | 618950 |   |  
DI-05877 | Combined oxidative phosphorylation deficiency 45. | 618951 |   |  
DI-05878 | Combined oxidative phosphorylation deficiency 46. | 618952 |   |  
DI-05882 | Combined oxidative phosphorylation deficiency 47. | 618958 |   |  
DI-05886 | Immunodeficiency 69. | 618963 |   |  
DI-05887 | Immunodeficiency 70. | 618969 |   |  
DI-05888 | Cone-rod synaptic disorder syndrome, congenital non-progressive. | 618970 |   |  
DI-05889 | Immunodeficiency 74, COVID19-related, X-linked. | 301051 |   |  
DI-05890 | Tolchin-Le Caignec syndrome. | 618971 |   |  
DI-05891 | Mitochondrial DNA depletion syndrome 19. | 618972 |   |  
DI-05892 | Neurodegeneration, infantile-onset, biotin-responsive. | 618973 |   |  
DI-05893 | Optic atrophy 12. | 618977 |   |  
DI-05894 | Li-Ghorbani-Weisz-Hubshman syndrome. | 618974 |   |  
DI-05895 | Myopathy, congenital, with diaphragmatic defects, respiratory insufficiency, and dysmorphic facies. | 618975 |   |  
DI-05896 | Immunodeficiency 72 with autoinflammation. | 618982 |   |  
DI-05897 | Growth hormone insensitivity syndrome with immune dysregulation 2, autosomal dominant. | 618985 |   |

I know you said there's a 2 week lag between MONDO and OLS update - perhaps these are in the pipeline already ?
@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
Hi @Antonialock These terms have not been added to Mondo yet, but @matentzn will work on the OMIM ingest.

**Comment by maglott** [comment]
How often is MONDO going to be updating from OMIM?

**Comment by nicolevasilevsky** [comment]
I think we'll just be doing it on an ad hoc basis.

**Comment by matentzn** [comment]
We have been working to update omim for every Mondo release; we are not there yet, but I am positive we will get there! :)

**Comment by Antonialock** [comment]
I don't get why omim doesn't provide an ontology? That's probably a discussion for the pub...

**Comment by matentzn** [comment]
Yes that would be good (I mean them providing one). We have made some very initial plans to help them provide one, but the problem of this ticket here I guess is not as much omim providing an ontology as Mondo ingesting it in a more timely manner!

**Comment by maglott** [comment]
What NCBI does is not very complex, but is labor-intensive after step 3
1.  We diff previous releases against current (daily)
2.  If there is a diff, we reprocess
3. We treat preferred terms and alternates and their abbreviations as defining a disorder distinct from included terms
    a. note caveat in step 4
    b. each included term and its abbreviation defines a distinct concept (hard to know if there are multiple include terms, which if any are synonyms of each other)
4.  We track by MIM number, but a ticket is open to change our logic to track by MIM number and term
     a. If a term for a mim number changes from disease_name  to disease_name 1,  we **should** create a new record for disease_name 1, because the definition of the MIM number has changed from generic to gene-specific
     b. Not all alternate terms for a disease_name 1 (i.e. the first gene-specific record) are true synonyms for disease_name; they likely are synonyms for disease_name or the phenotypic series that may have been created for disease_name
4.  Terms for disorders are also assigned to allelic variants
   a. Some of these terms may not match terms that are provided for a record in OMIM for a disorder

Curation steps involve (but we don't have the time or expertise in all cases to keep up to date)
* determining if an alternate term for a MIM number is truly equivalent to the preferred term, or should point to a generic concept
* determining if a novel name for an allelic variant is equivalent to a term in a record for a MIM number, or should be kept distinct
* determining which (if any) included terms are equivalent to each other
* determining whether, when OMIM moves a MIM number to another MIM number, that move is consistent with other resources (i.e. should we retain the original term, without the MIM number, or merge)

Note:  UMLS processes terms from OMIM provided as
* preferred, alternate, and included names for a OMIM record for a disorder
* terms for phenotypes assigned to allelic variants

**Comment by zoependlington** [comment]
> We have been working to update omim for every Mondo release; we are not there yet, but I am positive we will get there! :)

@AntoniaLock @matentzn @nicolevasilevsky  Just wanted to check if this is within scope for the next Mondo release? Related to EFO ticket: https://github.com/EBISPOT/efo/issues/865 Thanks!

**Comment by matentzn** [comment]
We will prioritise them soon Zoe, but the next release is too soon; we will do it for the release after. I can try to push for 10 November so you have time to sync with the EFO November release?

**Comment by zoependlington** [comment]
That's great Nico, thanks!

**Comment by nicolevasilevsky** [comment]
All of these terms are in Mondo now and will be available in the next release.
