### ISSUE TITLE
Disambiguate neurodegeneration with brain iron accumulation prototype from 2A

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#204]
currently NBIA2A is conflated with the more generic NBIA2

this is spotted by the reasoner:

![image](https://user-images.githubusercontent.com/50745/40248180-f32b5c76-5a83-11e8-90fc-6aaf3f014422.png)

**Comment by cmungall** [comment]
Nomenclature
https://www.omim.org/entry/610217 NBIA2B

This disorder, caused by mutation in the PLA2G6 gene, is referred to in OMIM as NBIA2B, since the original phenotype was described as a form of neurodegeneration with brain iron accumulation (NBIA; Morgan et al., 2006). Some references in the literature (see, e.g., Chinnery et al., 2007) use the designation 'NBIA2' to refer to a similar disorder caused by mutation in the FTL gene (134790). OMIM refers to NBIA caused by mutation in the FTL gene as NBIA3 (606159). 


ORDO has this grouping

```
[Term]
id: Orphanet:329303
name: PLA2G6-associated neurodegeneration
subset: ordo_group_of_disorders 
synonym: "PLAN" EXACT []
xref: ICD10:G23.0
is_a: Orphanet:352306  ! Disorder of phospholipids, sphingolipids and fatty acids biosynthesis with central nervous system predominant involvement
is_a: Orphanet:377794  ! group of disorders
is_a: Orphanet:385  ! Neurodegeneration with brain iron accumulation
```

```
    is_a Orphanet:329303 ! PLA2G6-associated neurodegeneration *** 
     is_a Orphanet:199351 ! Adult-onset dystonia-parkinsonism
     is_a Orphanet:35069 ! Infantile neuroaxonal dystrophy
```

**Comment by kanems** [comment]
Additional clarification requested on NBIA2A.

Per OMIM, "Neurodegeneration with brain iron accumulation-2A is an autosomal recessive neurodegenerative disease characterized by onset in the first 2 years of life; it is also referred to as infantile neuroaxonal dystrophy (INAD). "  https://www.omim.org/entry/256600

So should MONDO:0009739 (infantile neuroaxonal dystrophy) merge with MONDO:0024457 (NBIA-2A)? That would mean that NBIA-2B (and -2A) would then be children to the parent-term "PLA2G6-associated neurodegeneration" 

This page suggests that there are three forms of PLAN: INAD (aka -2A), aNAD (aka -2B) and a third with much later onset (adult onset dystonia-parkinsonism) https://www.nbiadisorders.org/about-nbia/overview-of-nbia-disorders  And this PubMed article suggests even a 4th, late onset autosomal-recessive form also exists. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6305538/

**Comment by kanems** [comment]
Hi Nicole, Can this be addressed sooner rather than later? NBIA2A is very popular term in NIH GTR (77 active tests) & ClinVar (>150 variant submissions) and we can't put a MONDO ID on it till this is merged/closed out. Thanks!

**Comment by nicolevasilevsky** [comment]
Hi @kanems yes, I'll prioritize this!

**Comment by cmungall** [comment]
I agree with @kanems analysis
