### ISSUE TITLE
NTR: pregnancy associated osteoporosis

### ISSUE THREAD

**Issue by galyea-gard** [monarch-initiative/mondo#2040]
**New Term**
pregnancy associated osteoporosis

**Synonym**
pregnancy and lactation-associated osteoporosis

**Reference**
https://grantome.com/grant/NIH/R01-FD006007-01

Original text:
Hi Nicole!  We received an inquiry requesting to add the term  **pregnancy associated osteoporosis**, also known as **Pregnancy and lactation-associated osteoporosis**. I am wondering if you could consider to add this one.  After my review I found that there is a study  Pregnancy and lactation associated osteoporosis: Bone microstructure and metabolism, genotypic characteristics, natural history and biomarkers of disease severity that has a grant from the Orphan Products Grants Program.  https://grantome.com/grant/NIH/R01-FD006007-01 so I think it could be considered a good candidate to add in GARD in the next future.  As you know we are not adding any new conditions right now because we are still in our review process. Please let me know your thoughts.  Thank you!  Gioconda.

**Comment by nicolevasilevsky** [comment]
Hi @galyea-gard - I will look into adding this term, it looks good to me!

**Comment by galyea-gard** [comment]
Thank you Nicole!  Have a GREAT weekend!  Gioconda
