### ISSUE TITLE
New term: X-linked intellectual disability with hypopituitarism

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#2045]
**Preferred term label: X-linked intellectual disability with hypopituitarism 

**Synonyms: none

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): This new term should be associated with variants in the gene SOX3. Variants in SOX3 have been linked to other disease terms in the past however, these disease terms are not all encompassing of the presenting phenotype. Additionally, X-linked intellectual disability with isolated growth hormone deficiency & X-linked intellectual disability with panhypopituitarism (which are available terms in MONDO), are not appropriate terms because they fall on the opposite extremes of hypopituitarism.  In humans, over and underdosage of SOX3 is associated with X-linked hypopituitarism, with variable phenotypes. The ClinGen ID/Autism GCEP would like to propose a new term X-linked intellectual disability with hypopituitarism (PMID: 24450934). Please note, SOX3 may/may not be the only gene associated with this newly requested disease term.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): Hypopituitarism MONDO: 0005152

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?**

**Your nano-attribution (ORCID): ClinGen ID/Autism GCEP
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by tibingaman** [comment]
Hi @nicolevasilevsky, was this released at the beginning of October? Thanks!

**Comment by nicolevasilevsky** [comment]
Hi @tibingaman, sorry, this didn't make it in to the last release and we have a question for you - 

Do you think this class should also be a subclass of your new term:
MONDO_0010712 'panhypopituitarism, X-linked' (see https://www.omim.org/entry/312000)

Thanks!

**Comment by nicolevasilevsky** [comment]
@tibingaman pinging you about the question above ^

**Comment by tibingaman** [comment]
Hi @nicolevasilevsky I completely missed this so thank you for pinging me! I think that 'panhypopituitarism, X-linked' can be a class under the parent term that I am requesting for 'X-linked intellectual disability with hypopituitarism' which is Hypopituitarism MONDO: 0005152. Please let me know if you have any other questions!

**Comment by nicolevasilevsky** [comment]
@tibingaman looking at this more closely, I don't see any evidence that 'panhypopituitarism, X-linked'  has intellectual disability as a primary feature. I am not sure that it should be a subclass of 'X-linked intellectual disability with hypopituitarism'

**Comment by tibingaman** [comment]
@nicolevasilevsky If it does not have any evidence of intellectual disability as a primary feature then it should not be included as a subclass of the newly requested term. Will this term be released at the end of November? Thank you!

**Comment by nicolevasilevsky** [comment]
yes- I'll get it into the next release, apologies for the delay.
