### ISSUE TITLE
cat scratch fever

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#205]
axiomatizing bacterial diseases reveals:

![image](https://user-images.githubusercontent.com/50745/40281172-a7dd28f4-5c12-11e8-8864-179f862e7122.png)

definition needs to use species not genus.

also reveals:

```
id: NCIT:C84586
name: Bartonella Infection
def: "A gram-negative bacterial infection caused by Bartonella bacilliformis. It is transmitted by ticks, flies and mosquitoes. Signs and symptoms include fever, headache, muscle pain, enlargement of the lymph nodes and anemia." []
subset: NCIT:C128453 
subset: NCIT:C90259 
synonym: "Bartonella Infection" EXACT []
synonym: "Bartonellosis" EXACT []
is_a: NCIT:C2890  ! Bacterial Infection
```

the text def is too specific for the name

**Comment by mellybelly** [comment]
@putmantime have you been reviewing these? if not perhaps we can come up with a plan to reconcile them with wikidata and other sources.
