### ISSUE TITLE
NTR: Parainfluenza Infectious Disease

### ISSUE THREAD

**Issue by callahantiff** [monarch-initiative/mondo#2063]
**Preferred term label:**
Parainfluenza Infectious Disease  

**Synonyms**
- parainfluenza  
- parainfluenza (disorder)  
- human parainfluenza viruses  
- human parainfluenza virus  
- HPIV  

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Human parainfluenza viruses (HPIVs) are single-stranded, enveloped RNA viruses of the Paramyoviridaie family. There are four serotypes which cause respiratory illnesses in children and adults.

Definition copied from abstract: [`PMID:27486735 `](https://pubmed.ncbi.nlm.nih.gov/27486735/)  

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Paramyxoviridae infectious disease (`MONDO_0005896`)   

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
Parainfluenza virus type 3 infectious disease (`MONDO_0042974`)   

**DbXRefs:**  
`SCTID:12188008`; `OMOP:4008269`

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0000-0002-8169-9049

**Comment by nicolevasilevsky** [comment]
@cmungall I don't see a term in NCIB taxon that corresponds to this virus - there is:
- [Human parainfluenza virus HCM-2015](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=2559897&lvl=3&lin=f&keep=1&srchmode=1&unlock)
- [Human parainfluenza virus Hue-2015](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=2559896&lvl=3&lin=f&keep=1&srchmode=1&unlock)

These are not in the same hierarchy as 'Human respirovirus 3' (child of  Respirovirus)

**Comment by nicolevasilevsky** [comment]
@callahantiff I'm not sure if Parainfluenza virus type 3 infectious disease (MONDO_0042974) is a child, based on what I said above. (Let me know if you need further clarification).

I added  human virus as a related synonym - unless you purposely wanted this class to be constrained to humans?

**Comment by nicolevasilevsky** [comment]
Here are the annotations, let me know if you'd like any changes:
![image](https://user-images.githubusercontent.com/6722114/94755501-9c9d9100-0349-11eb-869c-99d407dbb76b.png)

**Comment by callahantiff** [comment]
> @callahantiff I'm not sure if Parainfluenza virus type 3 infectious disease (MONDO_0042974) is a child, based on what I said above. (Let me know if you need further clarification).
> 
> I added human virus as a related synonym - unless you purposely wanted this class to be constrained to humans?

HI @nicolevasilevsky - thanks for your help adding this. I think the way that you have represented this looks great. I agree that at least for now, being more general and not limiting to only humans probably makes the most sense!

**Comment by callahantiff** [comment]
If I have to add human parainfluenza virus 1, 2, and 4. Should I create a separate ticket or add the required information for each to this ticket? I figured it was worth asking since this is still open? 😄

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] write to author of paper and ask if they think the NCBI taxonomy should be changed (https://pubmed.ncbi.nlm.nih.gov/27486735/)

**Comment by callahantiff** [comment]
> to do:
> 
> * [ ]  write to author of paper and ask if they think the NCBI taxonomy should be changed (https://pubmed.ncbi.nlm.nih.gov/27486735/)

Is there anything I can do to help with this? I'm happy to help gather additional evidence or literature if you think it would be useful!

**Comment by nicolevasilevsky** [comment]
need to add a tag with a design pattern
add comment that it is deliberately unaxiomitized b/c it does not align with NCBI taxonomy

@callahantiff I am talking to Chris right now, I'll let you know if we need more help- thanks!

**Comment by maglott** [comment]
Did anyone ask taxonomy directly?  A question, with the citations, should likely come from MONDO and not me:
1. go to https://www.ncbi.nlm.nih.gov/taxonomy
2. click on support center at the right below the thick blue line.

the FAQ does not say whether anyone can request a tax_id and whether the substrain needs to be defined by sequence

**Comment by nicolevasilevsky** [comment]
@maglott I am going to read the paper that Tiffany shared, and then I will likely ask NCBI Taxonomy about adding this class. 
https://pubmed.ncbi.nlm.nih.gov/27486735/

**Comment by nicolevasilevsky** [comment]
> If I have to add human parainfluenza virus 1, 2, and 4. Should I create a separate ticket or add the required information for each to this ticket? I figured it was worth asking since this is still open? 😄

Either way is fine, @callahantiff. (Sorry for the delay in answering this question)

**Comment by callahantiff** [comment]
> > If I have to add human parainfluenza virus 1, 2, and 4. Should I create a separate ticket or add the required information for each to this ticket? I figured it was worth asking since this is still open? 😄
> 
> Either way is fine, @callahantiff. (Sorry for the delay in answering this question)

No problem at all, I am sorry to give you more to do! I will hold off on adding anything until we know what will happen with adding this term. If I can do anything in the meantime, don't hesitate to let know.

Thanks so, so much for looking into this. I really appreciate it 🙏 🙇‍♀️

**Comment by nicolevasilevsky** [comment]
@callahantiff I can go ahead and add human parainfluenza virus 1, 2, and 4 now.

I sent a request to NCBI Taxonomy to add these taxon terms.

**Comment by callahantiff** [comment]
> @callahantiff I created these terms on PR #2109
> Do you want me to add xrefs to OMOP and/or SNOMED, and do you have syns you'd like me to add?
> 
> Do you know how to edit in Protege? You are also welcome to edit my PR in Protege :)

Happy to add these, thanks for the invite! Is it OK with your timing if I get that information added by Wednesday?

**Comment by nicolevasilevsky** [comment]
@callahantiff yes, that timing is fine, whatever works for you. :) Let me know if you need help with editing, I am happy to train you. Editing Mondo is a bit more complicated than other ontologies I've worked on. You don't have to edit though, I am happy to make all the changes for you- whatever you prefer.

**Comment by callahantiff** [comment]
> @callahantiff yes, that timing is fine, whatever works for you. :) Let me know if you need help with editing, I am happy to train you. Editing Mondo is a bit more complicated than other ontologies I've worked on. You don't have to edit though, I am happy to make all the changes for you- whatever you prefer.

OK, synonyms and dbxrefs added as new commit to PR #2109. Happy to make any needed changes!
