### ISSUE TITLE
MeSH:C538339 is not a recognised xref for Nasopharyngeal Carcinoma (MONDO:0015459)

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#2068]
Nasopharyngeal Carcinoma (MONDO:0015459) it has a exactMatch to MeSH:C538339
But that ID is not found/does not exist : https://www.ncbi.nlm.nih.gov/mesh/?term=C538339

For Nasopharyngeal Carcinoma (MONDO:0015459) should the MeSH ID be:
https://www.ncbi.nlm.nih.gov/mesh/?term=D000077274

I think this might be another one for Orphanet? as the MeSH xref comes from them (cc @ana-rath-orphanet and @Orphanet). The MeSH id seems to have been retired and replaced with D000077274.

Although it is not always the case I have found a number of these on this list https://www.nlm.nih.gov/mesh/2019/download/TermsMovingFrom2018SCRsto2019Descriptors.pdf
Could this be check/cross referenced somehow within MONDO to see if there are any more cases like this or should this list be checked with each of the xref databases used for the MeSH terms?
I haven't found a more recent pdf listing the retired MeSH terms and their new equivalent descriptors but hoping you might know @nicolevasilevsky 

Thank you!

**Comment by maglott** [comment]
https://www.nlm.nih.gov/databases/download/mesh.html

**Comment by nicolevasilevsky** [comment]
@lcdaugherty I updated the xref to MESH - thanks for catching that.

We do not have a process to check for deprecated terms that are xref'd in Mondo. The list you attached is super helpful, but too long for me to look through manually. I'll create a new ticket to see if we could automate this process somehow.

**Comment by lcdaugherty** [comment]
@nicolevasilevsky as you know, updating xrefs is the known ongoing cat and mouse chase!

I agree it super useful if that deprecated list could be used to do a mass update (and a task that no curator should do manually).  PDF is an awful format for relaying info but even with open source converters you should be able to get in into something that can be used computationally.   

As  I continue to check our dataset I have come across a few not that list (we are after-all now in 2020!),  shall I create new tickets for each one, a single ticket with them all with an attached list or will Mondo be able to do a review of the new download features/data now available direct at MeSH (as linked by @maglott)
