### ISSUE TITLE
hypertrophic cardiomyopathy

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#207]
[MONDO:0005045](http://purl.obolibrary.org/obo/MONDO_0005045) ! hypertrophic cardiomyopathy

we treat this as familial, we have a synonym for familial, consider making this explicit in the primary name.

check with clingen

NCIT has a single-isa structure:

```
        is_a NCIT:C34449 ! Hypertrophic Cardiomyopathy ***  [DEF: "A condition in which the myocardium is hypertrophied without an obvious cause. The hypertrophy is generally asymmetric and may be associated with obstruction of the ventricular outflow tract."]
          is_a NCIT:C84773 ! Familial Hypertrophic Cardiomyopathy [DEF: "Hypertrophic cardiomyopathy caused by mutations in the genes encoding components of the sarcomere, in the absence of predisposing conditions.
```

in contrast we combine these.

**Comment by maglott** [comment]
I strongly discourage treating a familial disorder as equivalent to the general class.
IMO Familial Hypertrophic Cardiomyopathy should be a child of hypertrophic cardiomyopathy

**Comment by cmungall** [comment]
Thanks for your comments @maglott -  familial hypertrophic cardiomyopathy will be a distinct class MONDO:0024573 in next release
