### ISSUE TITLE
Progressive Myoclonic Epilepsy typo 

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#2070]
**Mondo term (ID Label): Progressive Myoclonic Epilepsy MONDO:0020074

**Bug/Typo/Error description: The term Progressive Myoclonic Epilepsy should be changed to Progressive Myoclonus Epilepsy   (Myoclonic -> Myoclonus)

**Your nano-attribution (ORCID): ClinGen ID/Autism GCEP
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
this has already been changed in the edit file and will be available in the next  release (I plan to do a release on Friday)
