### ISSUE TITLE
Add Synonym: Ichthyosis (disease)

### ISSUE THREAD

**Issue by callahantiff** [monarch-initiative/mondo#2081]
**Mondo term (ID and Label)**
Ichthyosis (disease) (`MONDO_0016444`)

**Synonym to be added**
- xeroderma  
- xerodermia

**Synonym subtype: ie, broad/exact/narrow/related**
Exact

**Database cross reference for the synonym** Such as PubMed ID (in the format PMID:XXXXXX) or a cross-reference to another ontology, like OMIM or Orphanet.
- `SCTID:52475004`  
- `OMOP:4198562`

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0000-0002-8169-9049

**Comment by nicolevasilevsky** [comment]
@callahantiff please see the linked PR (#2110) - this does not seem like an appropriate synonym for Ichthyosis (disease).

Note - the Mondo ID you provided above is for 'primary anetoderma', I assume that was a mistake.

I will close this ticket, but please reopen if you'd like to discuss further.
