### ISSUE TITLE
Add Synonym: PSMNSW

### ISSUE THREAD

**Issue by callahantiff** [monarch-initiative/mondo#2083]
**Mondo term (ID and Label)**
PSMNSW (`MONDO_0013494`)

**Synonym to be added**
Broad 

**Synonym subtype: ie, broad/exact/narrow/related**
- sleep walking disorder   
- sleepwalking disorder 
- sleep walking  
- somnambulism  

**Database cross reference for the synonym** Such as PubMed ID (in the format PMID:XXXXXX) or a cross-reference to another ontology, like OMIM or Orphanet.
- `SCTID:80495009`  
- `OMOP:377535`

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0000-0002-8169-9049

____

I'm curious as to why this is a subclass of a Mendelian disorder?

**Comment by nicolevasilevsky** [comment]
note to self - I made these changes on PR https://github.com/monarch-initiative/mondo/pull/2111
but they are not showing up for some reason

**Comment by callahantiff** [comment]
> @callahantiff
> This term comes from OMIM - OMIM:613938 and has autosomal dominant or multifactoral inheritance:
> https://omim.org/entry/613938

I noticed that too. Perhaps it would make sense for me to request a new term for sleep walking related disorders and to use a different term in the meantime? I definitely want to use a sleep walking term, but don't want to restrict to being Mendelian in origin. Perhaps I should remove these synonyms. Should I do that directly myself? 😄

**Comment by nicolevasilevsky** [comment]
@callahantiff that sounds good to request a new term for sleeping walking disorder. Before you do though, maybe we could get feedback from @pnrobinson. I see there is a sleep walking term in HPO (https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0025236). @pnrobinson does this seem to add to Mondo too?

@callahantiff do you know how to add new terms to Mondo? I'm happy to train you, or I am happy to to do these edits too, you don't have to do them yourself. :) (But you are welcome to if you like)

**Comment by callahantiff** [comment]
> @callahantiff that sounds good to request a new term for sleeping walking disorder. Before you do though, maybe we could get feedback from @pnrobinson. I see there is a sleep walking term in HPO (https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0025236). @pnrobinson does this seem to add to Mondo too?
> 
> @callahantiff do you know how to add new terms to Mondo? I'm happy to train you, or I am happy to to do these edits too, you don't have to do them yourself. :) (But you are welcome to if you like)

I would love to be trained, I'd love to lear your preferred ways of adding things so I can do the same. My hope would be that this would allow me to be more helpful to do and decrease the likelihood of me inadvertently causing you more work 😄 . Should I email you to find a time to meet?

**Comment by nicolevasilevsky** [comment]
Yes, that would be great, thanks @callahantiff!

**Comment by nicolevasilevsky** [comment]
closed by mistake - reopening

**Comment by cmungall** [comment]
nicole - we need to work on the susceptibility patterns

for now how about obsoleting the existing ID, making a new one that is not mendelian, but still doing an exact xref to OMIM with the possibility of making a distinct concept later
