### ISSUE TITLE
Update to mondo.owl file

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2087]
- [x] need to update: http://obofoundry.org/ontology/mondo
- [x] put this in Changes.md and the release notes https://github.com/monarch-initiative/mondo/releases/tag/v2020-10-03
- [x] updating the docs on the OBO site
- [x] the duplicative docs here https://mondo.monarchinitiative.org/
- [x] coordinate with dipper team (Nico is on this)

**Comment by nicolevasilevsky** [comment]
Note to self and @matentzn: update docs when adding SSSOM and OWL equivalences

See #2086

**Comment by nicolevasilevsky** [comment]
@matentzn can we close this?

**Comment by matentzn** [comment]
No action items. Closing.
