### ISSUE TITLE
Invalid definitions?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2095]
These seem like invalid definitions:

<http://purl.obolibrary.org/obo/MONDO_0006326>	"https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C7913&ns=NCI_Thesaurus"
<http://purl.obolibrary.org/obo/MONDO_0006430>	"https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C7306&ns=NCI_Thesaurus"
<http://purl.obolibrary.org/obo/MONDO_0006315>	"https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C37005&ns=NCI_Thesaurus"

**Comment by matentzn** [comment]
Best you fix these Nicole; when they are done, I can add Chris check to the Jenkins pipeline..

**Comment by nicolevasilevsky** [comment]
will do!
