### ISSUE TITLE
[Obsolete] MONDO:0006315 neoplastic medium-sized B-lymphocyte with basophilic cytoplasm

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2099]
**Mondo term (ID and Label)**
MONDO:0006315 neoplastic medium-sized B-lymphocyte with basophilic cytoplasm

**Reason for deprecation**
this is a cell type and not a disease

**Suggested term to consider**
NCIT:C37005

cc @zoependlington

**Comment by nicolevasilevsky** [comment]
related to #2095

**Comment by cmungall** [comment]
On Thu, Oct 8, 2020 at 12:10 PM Nicole Vasilevsky <notifications@github.com>
wrote:

> related to #2095
> <https://github.com/monarch-initiative/mondo/issues/2095>
>
is it?

**Comment by nicolevasilevsky** [comment]
yes, MONDO_0006315 had an invalid def
