### ISSUE TITLE
Review: ALS

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#210]
ALS is in Chris A's translator pitch. We should make sure  it is correct and complete:

     is_a MONDO:0020126 ! rare peripheral neuropathy
      is_a MONDO:0004976 ! amyotrophic lateral sclerosis ***
       is_a MONDO:0000711 ! amyotrophic lateral sclerosis type 13
       is_a MONDO:0000712 ! FTDALS1
       is_a MONDO:0005144 ! familial amyotrophic lateral sclerosis
       is_a MONDO:0005145 ! sporadic amyotrophic lateral sclerosis
       is_a MONDO:0008781 ! juvenile amyotrophic lateral sclerosis with dementia
       is_a MONDO:0008782 ! amyotrophic lateral sclerosis with polyglucosan bodies
       is_a MONDO:0011196 ! amyotrophic lateral sclerosis type 5
       is_a MONDO:0011223 ! amyotrophic lateral sclerosis type 4
       is_a MONDO:0011632 ! amyotrophic lateral sclerosis type 21
       is_a MONDO:0011691 ! amyotrophic lateral sclerosis type 3
       is_a MONDO:0011952 ! amyotrophic lateral sclerosis type 7
       is_a MONDO:0012077 ! amyotrophic lateral sclerosis type 8
       is_a MONDO:0012753 ! amyotrophic lateral sclerosis type 9
       is_a MONDO:0014531 ! amyotrohpic lateral sclerosis type 22
       is_a MONDO:0018687 ! progressive muscular atrophy

**Comment by nicolevasilevsky** [comment]
I see more classes than these in Protege:
![image](https://user-images.githubusercontent.com/6722114/40336261-8340706c-5d1d-11e8-87e2-211947780ba8.png)

**Comment by nicolevasilevsky** [comment]
I am reviewing these classes now

**Comment by nicolevasilevsky** [comment]
This class MONDO_0013861 'amyotrophic lateral sclerosis type 17', as an incorrect xref I think:
PMID:24514863
This paper doesn't mention anything about ALS, it is about Parkinson's disease

**Comment by nicolevasilevsky** [comment]
otherwise I don't see any issues.

**Comment by nicolevasilevsky** [comment]
I think this has been addressed. closing
