### ISSUE TITLE
New term: cerebellar ataxia, intellectual disability, and dysequilibrium syndrome

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#2100]
**Preferred term label: cerebellar ataxia, intellectual disability, and dysequilibrium syndrome

**Synonyms: none

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): The ClinGen ID/Autism GCEP would like to request the new term cerebellar ataxia, intellectual disability, and dysequilibrium syndrome. In OMIM, this is referred to cerebellar ataxia, mental retardation, and dysequilibrium syndrome 1, 2, 3, or 4, using OMIM's numbering system and also the term "mental retardation" however, that is not a preferred term. Please let me know if you have any questions.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): The parent term of this new term request should be dysequilibrium syndrome MONDO:0009133. 

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?: Yes, cerebellar ataxia, mental retardation, dysequilibrium syndrome 1, 2, 3, and 4 (MONDO: 0024542, 0012430, 0013188, 0014104) should be children terms of the new term cerebellar ataxia, intellectual disability, and dysequilibrium syndrome.

**Your nano-attribution (ORCID): ClinGen ID/Autism
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by cmungall** [comment]
Thank you!

How would this differ from MONDO:0009133. https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0009133

![image](https://user-images.githubusercontent.com/50745/95505641-90c25800-0963-11eb-84e2-4c203c7ffc76.png)

Maybe we should instead rename MONDO:0009133?

This would be consistent with the name of the PS:

https://omim.org/phenotypicSeries/PS224050
