### ISSUE TITLE
question about Amyotrophic lateral sclerosis type 2

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#211]
@gardinfocenter - we have MONDO_0008780 amyotrophic lateral sclerosis type 2 in the gard rare disease subset, but I can't find a definition for this.

https://rarediseases.info.nih.gov/diseases/9470/amyotrophic-lateral-sclerosis-type-2

Thanks for your help!

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky  - we will look into this disease and get back to you by the end of the week. I have a feeling we will be making changes to several of the ALS entries we have. However, I will let you know the details by COB Friday.

**Comment by nicolevasilevsky** [comment]
Great, thank you!

**Comment by GARDInfoCenter** [comment]
As an update, we have made some changes to our list of terms. We no longer lists the subtypes separately instead we list only Amyotrophic lateral sclerosis and Juvenile amyotrophic lateral sclerosis. Thank you for bringing this entry to our attention.

**Comment by nicolevasilevsky** [comment]
Thanks for the update, i think this can be closed.
