### ISSUE TITLE
[Revise subclass] MONDO:0016587, arrhythmogenic right ventricular cardiomyopathy

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2116]
**Mondo term (ID and Label)**
MONDO:0030062 'arrhythmogenic right ventricular dysplasia, familial, 14'

**Suggested revision and reasons**
Should this be a direct child of MONDO:0016342 'familial isolated arrhythmogenic right ventricular dysplasia' rather than a sibling?

**Your nano-attribution (ORCID)**
0000-0001-7451-4467

**Comment by nicolevasilevsky** [comment]
Yes, I believe so. This is how it is classified in Orphanet, not sure why it wasn't done this way in Mondo - I will fix.
Thanks @maglott

**Comment by cmungall** [comment]
agreed, but can you look a bit deeper here @nicolevasilevsky?

There should be a logical axiom connecting fiARVC and ARVC. I believe it should be fiARVC = ARVC and has-characteristic isolated

(Note ARVC is already inherited: https://www.cardiomyopathy.org/arrhythmogenic-right-ventricular-cardiomyopathy/intro )

AFAICT the only non-isolated form is Naxos. 

The PS appears to collect only the isolated forms
https://omim.org/phenotypicSeries/PS107970

Thus the PS xref should move down to the fi form.

Can you also fix the parents of MONDO:0007152?

**Comment by cmungall** [comment]
@matentzn - we should connect the isolated dp to some kind of annotation check, not sure how to implement, e.g. semantic similarity threshold... or maybe isolated Xs should also always be accompanied by disjointness axioms?
