### ISSUE TITLE
[Revise subclass]  Diamond-Blackfan anemia (MONDO:0015253)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#2118]
Diamond-Blackfan anemia (MONDO:0015253)

is currently 
inborn disorder of purine metabolism (MONDO:0019236)

this doesn't seem correct 

is there a reference for that?

( disease causing genes are mainly ribosomal proteins)

**Comment by nicolevasilevsky** [comment]
the reference is from Orphanet:124
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_124

@ValWood do you think we should exclude this as a parent? (There is a related ticket to review parent terms that come from Orphanet, see #1520)

**Comment by ValWood** [comment]
I would defer to an expert, as I'm not at all sure. But it seems wrong based on my cell biology knowledge. When I search PubMed for  "Blackfan" and "purine" the source is likely these 2 papers, which are disease markers.

@pnrobinson 
 
Elevated red cell adenosine deaminase activity: a marker of disordered erythropoiesis in Diamond-Blackfan anaemia and other haematologic diseases.
Glader BE, Backer K.
Br J Haematol. 1988 Feb;68(2):165-8. doi: 10.1111/j.1365-2141.1988.tb06184.x.
PMID: 3348976
These data thus further support that measurement of this purine metabolic enzyme is useful in diagnosing the cause of pure RBC aplasia in children. ...However, since almost all patients with Diamond-Blackfan anaemia manifest elevated RBC-ADA activity, this chemical …

 
Elevated erythrocyte adenosine deaminase activity in congenital hypoplastic anemia.
Glader BE, Backer K, Diamond LK.
N Engl J Med. 1983 Dec 15;309(24):1486-90. doi: 10.1056/NEJM198312153092404.
PMID: 6646173
Abnormalities of adenosine deaminase, a critical enzyme of the purine salvage pathway, have been reported in association with immune dysfunction, acute leukemia, and hereditary hemolytic anemia. We report data showing that erythrocyte adenosine deaminase activity is also a …

**Comment by nicolevasilevsky** [comment]
thanks @ValWood!

**Comment by pnrobinson** [comment]
Elevated red cell adenosine deaminase level is a common feature of BDA. However, these diseases are not (to my knowledge) considered to be inborn disorders of purine metabolism, they are related to ribosomal proteins. This is ourr multiparentage problem -- if we make a parentage for every feature, then each disease will have k parents where k is the number of organs with abnormalities. I would suggest to remove this link.

**Comment by nicolevasilevsky** [comment]
thank you @pnrobinson!

I think these two parents should be removed too, please let me know if you disagree:

- 'orofacial clefting syndrome'
- 'polymalformative genetic syndrome with increased risk of developing cancer'

**Comment by pnrobinson** [comment]
The other two parents are not *always* true for individual patients. What is the current "main" parent of these terms?

**Comment by nicolevasilevsky** [comment]
These are all the parents at the moment:
![image](https://user-images.githubusercontent.com/6722114/95922625-88ee2380-0d68-11eb-9f5e-686e65cca6b7.png)

If I remove the proposed parents above though, all the inferred parents go away:

![image](https://user-images.githubusercontent.com/6722114/95922685-ade29680-0d68-11eb-81a7-d6d625f4e5d9.png)

**Comment by ValWood** [comment]
keep some or all of
is_a anemia with erythroblastopenia. 
is_a congenital anemia
is_a pure red-cell aplasia
is_a inherited aplastic anemia

remove these
is_a developmental anomaly of metabolic origin
is_a orofacial clefting syndrome
is_a polymalformative genetic syndrome with increased risk of developing cancer
is_a genetic otorhinolaryngologic disease
is_a inborn disorder of purine metabolism
is_a hereditary connective tissue disorder

?
