### ISSUE TITLE
[Revise subclass] glycogen storage diseases

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2128]
Action items:
- [x] relabel MONDO_0010598 to glycogen storage disease IXa1
- [x] revise def for MONDO_0010598: Def:  Any glycogen storage disease in which the cause of the disease is a mutation in the PHKA2 gene, with no PHK activity in liver or erythrocytes.
- [x] add new term glycogen storage disease IXa2, xref OMIM:306000 MONDO:siblingOf. Add synonym GSD9A2 (exact, OMIM:306000). Def:  Any glycogen storage disease in which the cause of the disease is a mutation in the PHKA2 gene, with no PHK in liver, but normal activity in erythrocytes.

_updated 10/21/21 by NV_

----

**Mondo term (ID and Label)**
This may be related to ticket #1484, or how the ebi browser handles the data, but something is very dd

**Suggested revision and reasons**
I was looking for the treatment of disorders due to deficiency of  liver phosphorylase kinase , particularly what OMIM describes as `glycogen` storage disease type IXa (GSD9A1) and type IXa2 (GSD9A2) are caused by mutation in the PHKA2 gene (300798), which encodes the alpha-2 subunit of hepatic phosphorylase kinase, on chromosome Xp22.`  and glycogen storage disease type VIII, which OMIM has deprecated.  When I expanded 9a , I found some rather odd children
![image](https://user-images.githubusercontent.com/17743017/96124968-9f5bc280-0ec1-11eb-98f1-f12eebceb675.png)

My specific questions:
* should glycogen storage disease type VIII be retained as a distinct entity?
* should ids be created for GSD9A1 and GSD9A2?
* what can be done about the current subclasses

**Your nano-attribution (ORCID)**
 0000-0001-7451-4467

**Comment by nicolevasilevsky** [comment]
Sorry for the delay @maglott - this is on my high priority list

**Comment by nicolevasilevsky** [comment]
I think the OLS display is resolved
![image](https://user-images.githubusercontent.com/6722114/107569207-e5d5db00-6b9c-11eb-9687-118013d94f0b.png)

**Comment by nicolevasilevsky** [comment]
> should glycogen storage disease type VIII be retained as a distinct entity?

It still exists in DO, MeSH and GARD, but I can add it as a candidate for obsoletion and send it to the list. I'll create a separate ticket.

https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_2751
https://rarediseases.info.nih.gov/diseases/6538/glycogen-storage-disease-8
https://meshb.nlm.nih.gov/record/ui?ui=D006015

**Comment by nicolevasilevsky** [comment]
> should ids be created for GSD9A1 and GSD9A2?

we have MONDO_0010598 'glycogen storage disease IXa'

I'm not sure if we want to split out the terms from the OMIM record, I need to ask @cmungall how to handle that.

**Comment by cmungall** [comment]
I have no objection to making subtypes of an instance of an OMIM, if this is clinically justified.

I would recommend making a DP (e.g. "clinical subtype") and tagging the term with this, and having a rule that flags any subclass of an OMIM not in this category

**Comment by nicolevasilevsky** [comment]
Thanks @cmungall! So does that mean I could have two (or more) terms in Mondo that have a MONDO:equivalentTo xref on the term?

**Comment by nicolevasilevsky** [comment]
per discussion on the Mondo call - cannot have two OMIM equiv xrefs on two terms
