### ISSUE TITLE
Reflexive annotations

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2129]
A new check spots reflexive annotations, i.e. annotations to itself. Fix?

```
<http://purl.obolibrary.org/obo/MONDO_0002722>	<http://purl.obolibrary.org/obo/mondo#excluded_subClassOf>
<http://purl.obolibrary.org/obo/MONDO_0019072>	<http://purl.obolibrary.org/obo/mondo#excluded_subClassOf>
<http://purl.obolibrary.org/obo/MONDO_0003924>	<http://purl.obolibrary.org/obo/mondo#excluded_subClassOf>
<http://purl.obolibrary.org/obo/MONDO_0016706>	<http://purl.obolibrary.org/obo/mondo#excluded_subClassOf>
<http://purl.obolibrary.org/obo/MONDO_0019118>	<http://purl.obolibrary.org/obo/mondo#excluded_subClassOf>
```

**Comment by cmungall** [comment]
indeed, the semantics of excluded_subClassOfare intended to follow subClassOf  (i.e `x excluded_subClassOf y <==> not(x subClassOf y)`)  which is reflexive, so these would all be correctly flagged as unintentional

I assume these arose from merges. I'd just go ahead and remove the annotation without further examination
