### ISSUE TITLE
Remove related synonym where there is already an exact

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2134]
We have many cases where there are related synonyms that are already exact. The way this ticket will work is this:

1. You (@nicolevasilevsky) work through [this table](https://docs.google.com/spreadsheets/d/1at_bN5bzNiKtJKtkPXPw2tTcFyWbGttMV_q-1AQzAJk/edit#gid=0) in your own time (I gave you access in a separate email).

The table looks like this:

ID | Label | Synonym | Type | Broken and fixed
-- | -- | -- | -- | --
MONDO:0021010 | skin lymphangiosarcoma | lymphangiosarcoma of Stewart and Treves |   |  
MONDO:0000270 | lower respiratory tract disease | disorder of lower respiratory tract |   |  

2. In the `Type` column, you write `E` to denote that this is an exact synonym of the `Label`, and `R` if it is related.
3. If the synonym is fully broken, you fix it manually and just write `fixed` in the `Broken and fixed` column.  
4. When you are done, I will take over. I will automatically fix all the related and exact synonyms, and ignore all the `fixed` ones.

**Comment by matentzn** [comment]
Note this is a very labour intensive ticket - I would not try to fix it in one go. This is part of our great Mondo spring cleaning action :) Let me know if I can help you further with this!

**Comment by matentzn** [comment]
Updated instructions:

1. If you have to check Protege in any case, delete either the related or the exact synonym. Also check that there are not multiple instances of the same exact synonym with different xrefs
2. If you can see whats what from the table, just fill in the row. Intuition is fine, does not have to be perfect.

**Comment by cmungall** [comment]
I think 95% of the checking can be automated

can we add to the table whether the exact syn is justified by a DP? I don't think dosdp-generate uses synonyms yet so you may need to use the python or coordinate with Jim

we also need to codify the omim patterns. 

e.g this is justified, consistent PS acronym + number

MONDO:0014929> | retinitis pigmentosa 76 | RP76 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by nicolevasilevsky** [comment]
I think this is done? @matentzn

**Comment by matentzn** [comment]
This ticket can be closed, it will be dealt with by our wider synonym revision plan.
