### ISSUE TITLE
[Obsolete] 'polymalformative genetic syndrome with increased risk of developing cancer'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2145]
**Mondo term (ID and Label)**
MONDO_0015945 'polymalformative genetic syndrome with increased risk of developing cancer'

**Reason for deprecation**
this is a grouping class from ORDO and is not used in the primary literature, from what I can tell.

**Suggested term to consider**
N/A

**Comment by pnrobinson** [comment]
This is an important category, although I do not know of a name for it. Here is a review https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4416231/
We should ask Ada for her opinion.
Alternatively we can treat the cancer risk as a phenotypic feature

**Comment by nicolevasilevsky** [comment]
Sounds like we should keep this. I will close.
