### ISSUE TITLE
Something is badly wrong with the OLS version of MONDO

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#2147]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0016587

![image](https://user-images.githubusercontent.com/50745/96410545-f2709680-119b-11eb-8588-596c52b570e9.png)

these should not be subclasses of ARVC14!

ontobee is fine:

http://www.ontobee.org/ontology/MONDO?iri=http://purl.obolibrary.org/obo/MONDO_0030062

**Comment by cmungall** [comment]
![image](https://user-images.githubusercontent.com/50745/96410661-1af89080-119c-11eb-9cb9-a3308dd1d78f.png)

**Comment by nicolevasilevsky** [comment]
very strange!

**Comment by matentzn** [comment]
These are subclasses of every class. There is only one way this can happen.. 
![image](https://user-images.githubusercontent.com/7070631/96577390-770e0280-12cb-11eb-9131-c4f7b1cadf72.png)

And yes, its true.. They are all unsatisfiable! I will fix them, and then you can do another patch release.. However, they must have always been unsatisfiable.

This ticket needs to stay open until we find a way to check. Elk 0.4.3 misses those unsats! OLS just moved to Elk 0.5

**Comment by matentzn** [comment]
Ok, I linked all the related issues. These should be super easy to fix but high priority. If these are fixed, no more unsats (minimal set, rest depends on these).

**Comment by balhoff** [comment]
> OLS just moved to Elk 0.5

This is important to know! We should probably accelerate efforts to adopt it.

**Comment by aholovenko** [comment]
Hi, how long will it take to fix it in OLS?

**Comment by matentzn** [comment]
Working for this to be fixed soon (this week, hopefully tomorrow)

**Comment by matentzn** [comment]
@nicolevasilevsky I know you are stretched thin but can we attack this from both sides? fix all the unsats, while the EBI spot team reloads Mondo?

**Comment by nicolevasilevsky** [comment]
dependent on:
https://github.com/monarch-initiative/mondo/issues/2182
https://github.com/monarch-initiative/mondo/issues/2181
https://github.com/monarch-initiative/mondo/issues/2180

https://github.com/monarch-initiative/mondo/pull/2191

@cmungall

**Comment by nicolevasilevsky** [comment]
@matentzn I've done everything I can on this and am blocked

**Comment by nicolevasilevsky** [comment]
@matentzn and I worked on the dependent tickets. I am running a new release now.

**Comment by nicolevasilevsky** [comment]
release is done:
https://github.com/monarch-initiative/mondo/releases/tag/v2020-10-21

**Comment by matentzn** [comment]
Problem solved! Great work @nicolevasilevsky that was a bit exciting but a bit satisfying as well :D Nicely done.

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0016587

**Comment by nicolevasilevsky** [comment]
you too, @matentzn !
