### ISSUE TITLE
[Obsolete] Futcher line

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#2148]
**Mondo term (ID and Label)**

MONDO:0007641 Futcher line

**Reason for deprecation**

This should not be classified as a disease.

The OMIM refs are from 1938, 1940, and 1975, nothing more recent. The language in the entry is dated.

When obsoleting, add synonyms: Voigt lines, pigmentary demarcation lines. 

I think this could be considered as a phenotypic feature/trait, but I'm not sure if belongs under abnormal phenotype in HPO

**Comment by cmungall** [comment]
@pnrobinson would you agree with this?

**Comment by pnrobinson** [comment]
This is definitely a phenotypic feature, see for instance https://pubmed.ncbi.nlm.nih.gov/24087785/
We should probably add it as an HPO term!

**Comment by nicolevasilevsky** [comment]
- [ ] note to self: when Peter adds this to HPO, add a consider in Mondo
