### ISSUE TITLE
Align mediastinitis with inflammation pattern

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2180]
![image](https://user-images.githubusercontent.com/7070631/96586399-de7e7f00-12d8-11eb-91e0-75d41c13ca78.png)

@cmungall please advise.

**Comment by matentzn** [comment]
see #2147

**Comment by nicolevasilevsky** [comment]
I think changing the range for 'disease has inflammation site' to 'anatomical entity' (UBERON:0001602) will fix this- but does this have to be done in RO, not in Mondo?

**Comment by matentzn** [comment]
We fixed this by redefining as `inflammatory diseases and has location some mediastinum`

**Comment by matentzn** [comment]
Ok so I made a PR on RO to loosen the range of 'disease has inflammatory site':

https://github.com/oborel/obo-relations/pull/406

**Comment by matentzn** [comment]
We will keep this open until https://github.com/monarch-initiative/mondo/issues/2198 is decided.

**Comment by nicolevasilevsky** [comment]
#2198 is closed, so I think this can be closed.
