### ISSUE TITLE
Unsatisfiable 'infective arthritis'

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2182]
![image](https://user-images.githubusercontent.com/7070631/96587364-281b9980-12da-11eb-9fa9-c3295af8d76a.png)

**Comment by matentzn** [comment]
see #2147 
@cmungall

**Comment by matentzn** [comment]
Same for bacterial arthritis:

![image](https://user-images.githubusercontent.com/7070631/96587676-88aad680-12da-11eb-95c4-cb5a10730b8a.png)

**Comment by nicolevasilevsky** [comment]
I fixed bacterial arthritis, but I am not sure how to fix 'infective arthritis'.

There is no logical def for 'infectious disease'. 

My best guess is to remove the logical def from 'infective arthritis', but @cmungall probably has better insights.

**Comment by cmungall** [comment]
bacterial arthritis, infective arthritis, infectious disease are all the same pattern. A general disease with differentia that is the pathogen

**Comment by nicolevasilevsky** [comment]
but what should the pathogen be for infective arthritis & infectious disease ?

**Comment by matentzn** [comment]
Ncbitaxon root?

**Comment by nicolevasilevsky** [comment]
organism is the parent for the NCBITaxon classes

**Comment by cmungall** [comment]
not obi, we don't have an obi import

i dislike the name root but this is consistent. maybe we need a more
specific relation

**Comment by nicolevasilevsky** [comment]
I will close this PR, but I'm not clear what the path forward is.
