### ISSUE TITLE
Unsatisfiable 'maple bark strippers'

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2183]
![image](https://user-images.githubusercontent.com/7070631/96588102-1ab2df00-12db-11eb-806c-f6c853572cc6.png)

@cmungall seems we should have used `realized in response to stimulus` maybe?
see #2147

**Comment by nicolevasilevsky** [comment]
yes, I agree it should be `realized in response to stimulus`
https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/infectious_disease_by_agent.yaml
