### ISSUE TITLE
pattern: inflammatory disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2198]
Nico and I changed the logical def of mediastinitis to make it satisfiable (see: https://github.com/monarch-initiative/mondo/issues/2180) and to fix the display in OLS (https://github.com/monarch-initiative/mondo/issues/2147). 

We changed it to:

'inflammatory disease'
 and ('disease has location' some mediastinum)

This does not conform to the current pattern:
https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/inflammatory_disease_by_site.yaml

Should we consider using this pattern above instead of the current pattern?

Note - Nico created a PR in RO to edit the range for 'disease has inflammation site'
https://github.com/oborel/obo-relations/pull/406

(The previous logical def for for mediastinum was unsatisfiable b/c of the restrictions on the range for that property)

**Comment by nicolevasilevsky** [comment]
cc @matentzn

**Comment by cmungall** [comment]
what exactly does mediastinitis mean?

not a trick question, I can read online definitions. formally, what does it
mean?

is it the inflammation of an immaterial entity?

**Comment by nicolevasilevsky** [comment]
yes, the mediastinum is an 'anatomical cavity' which is an immaterial entity

**Comment by cmungall** [comment]
how can an immaterial entity be inflamed?

**Comment by nicolevasilevsky** [comment]
The text def in mondo says:
An inflammatory process affecting the mediastinum.

From: [Mediastinitis: MedlinePlus Medical Encyclopedia](https://medlineplus.gov/ency/article/000081.htm#:~:text=Mediastinitis%20is%20swelling%20and%20irritation,lymph%20nodes%2C%20and%20connective%20tissue)

Mediastinitis is swelling and irritation (inflammation) of the chest area between the lungs (mediastinum). This area contains the heart, large blood vessels, windpipe (trachea), food tube (esophagus), thymus gland, lymph nodes, and connective tissue.

How do we fix this? Is mediastinum a material entity? Seems like it is referring to an area containing a lot of tissues.

**Comment by cmungall** [comment]
There is nothing needing urgently fixed just now but it is worth pursuing
this

you are right, it refers to an area with a lot of tissues, not an
immaterial entity

another thing: if the area contains the heart, why isn't heart inflammation
a subtype?

**Comment by nicolevasilevsky** [comment]
I think these are uberon questions, right? In Uberon, it doesn't look like the heart is part of the thoracic cavity

**Comment by cmungall** [comment]
what would you like uberon to say? the encyclopedia entry you picked says
that mediastinitis contains the heart. But we have a not-subClassOf between
myocardiatis and mediastinitis

**Comment by nicolevasilevsky** [comment]
action item per Mondo call on 01/20/22
revise logical def:
'inflammatory disease'
 and ('disease has inflammation site' some mediastinum)

Consider changing anatomical entity to 'mediastinal pleura' - need to read about this further.

Add comment on the term about our decision
