### ISSUE TITLE
Weave in new OMIMPS terms

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2202]
I hope you know what to do :D @nicolevasilevsky 

- [x] [Term]
id: MONDO:X
name: spondylometaphyseal dysplasia
xref: OMIMPS:184255 {source="MONDO:equivalentTo"} ! spondylometaphyseal dysplasia

- [x] [Term]
id: MONDO:X
name: growth hormone insensitivity syndrome with immune dysregulation
xref: OMIMPS:245590 {source="MONDO:equivalentTo"} ! growth hormone insensitivity syndrome with immune dysregulation

- [x] [Term]
id: MONDO:X
name: ifap syndrome
xref: OMIMPS:308205 {source="MONDO:equivalentTo"} ! ifap syndrome

- [x] [Term]
id: MONDO:X
name: rajab interstitial lung disease with brain calcifications
xref: OMIMPS:613658 {source="MONDO:equivalentTo"} ! rajab interstitial lung disease with brain calcifications

- [x] [Term]
id: MONDO:X
name: arthrogryposis multiplex congenita
xref: OMIMPS:617468 {source="MONDO:equivalentTo"} ! arthrogryposis multiplex congenita

**Comment by maglott** [comment]
I think this should be 
[Term]
id: MONDO:X
name: IFAP syndrome
xref: OMIMPS:308205 {source="MONDO:equivalentTo"} ! ifap syndrome
