### ISSUE TITLE
question - relationship b/w phaeochromocytoma + Adrenal/paraganglial tumor

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2203]
@drseb was asking about the relationship between MONDO_0008233 (OMIM:171300) `phaeochromocytoma` and MONDO_0015077 (Orphanet:100091) `Adrenal/paraganglial tumor`.

**Note**-  MONDO_0019116 `catecholamine-producing tumor` was obsoleted in Orphanet, and merged with MONDO_0015077 (Orphanet:100091) `Adrenal/paraganglial tumor`. I created a ticket #2199 to suggest merging these in Mondo.

The description (in OMIM) of MONDO_0008233 (OMIM:171300) `phaeochromocytoma` is:
Pheochromocytomas are catecholamine-secreting tumors that usually arise within the adrenal medulla.

(there is no text def in Mondo)

Currently MONDO_0008233 (OMIM:171300) `phaeochromocytoma`  is a descendent of `adrenal/paraganglial tumor`. These two terms cannot be equivalent, but I could:
-  add a dbxref to MONDO_0015077 (Orphanet:100091) `Adrenal/paraganglial tumor: OMIM:171300 Mondo:superClassOf 
- add a dbxref to MONDO_0008233 (OMIM:171300) `phaeochromocytoma`:  Orphanet:100091 MONDO:subClassOf

Would that work @drseb ?

![image](https://user-images.githubusercontent.com/6722114/96938941-7f5b6e80-1480-11eb-8250-9e77c903d121.png)

**Comment by pnrobinson** [comment]
I do not think it is the case that pheochromocytoma is *always* an adrenal/paraganglial tumor.
Also not that phaeo... is the UK spelling, but MONDO otherwise seems to prefer US spelling.
This needs to be revised, let's discuss it on an upcoming call.

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] relabel phaeochromocytoma to pheochromocytoma
- [ ] phaeochromocytoma should be an exact synonym
