### ISSUE TITLE
Harmonise representation of gene (products)

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2206]
Right now we use a lot of PR terms to denote gene products (proteins), see #2034.

As [recommended](https://github.com/monarch-initiative/mondo/issues/2034#issuecomment-709521152) by @cmungall, we should normalise these to use ncbi gene ID (i.e. replace all PR terms in logical axioms with their corresponding ncbi gene ID. 

- [ ] PR:000001002
- [ ] PR:000001003
- [ ] PR:000001004
- [ ] PR:000001006
- [ ] PR:000001012
- [ ] PR:000001013
- [ ] PR:000001014
- [ ] PR:000001015
- [ ] PR:000001020
- [ ] PR:000001024
- [ ] PR:000001083
- [ ] PR:000001084
- [ ] PR:000001203
- [ ] PR:000001254
- [ ] PR:000001255
- [ ] PR:000001289
- [ ] PR:000001293
- [ ] PR:000001307
- [ ] PR:000001308
- [ ] PR:000001318
- [ ] PR:000001332
- [ ] PR:000001338
- [ ] PR:000001343
- [ ] PR:000001345
- [ ] PR:000001380
- [ ] PR:000001381
- [ ] PR:000001408
- [ ] PR:000001444
- [ ] PR:000001460
- [ ] PR:000001479
- [ ] PR:000001481
- [ ] PR:000001483
- [ ] PR:000001786
- [ ] PR:000001800
- [ ] PR:000001809
- [ ] PR:000001833
- [ ] PR:000001836
- [ ] PR:000001839
- [ ] PR:000001843
- [ ] PR:000001858
- [ ] PR:000001859
- [ ] PR:000001865
- [ ] PR:000001867
- [ ] PR:000001869
- [ ] PR:000001874
- [ ] PR:000001879
- [ ] PR:000001880
- [ ] PR:000001886
- [ ] PR:000001889
- [ ] PR:000001892
- [ ] PR:000001896
- [ ] PR:000001898
- [ ] PR:000001903
- [ ] PR:000001932
- [ ] PR:000001935
- [ ] PR:000001944
- [ ] PR:000001945
- [ ] PR:000001963
- [ ] PR:000001969
- [ ] PR:000002001
- [ ] PR:000002037
- [ ] PR:000002039
- [ ] PR:000002065
- [ ] PR:000002112
- [ ] PR:000002977
- [ ] PR:000002978
- [ ] PR:000002979
- [ ] PR:000002980
- [ ] PR:000002981
- [ ] PR:000003457
- [ ] PR:000003460
- [ ] PR:000005178
- [ ] PR:000005307
- [ ] PR:000006169
- [ ] PR:000006427
- [ ] PR:000006537
- [ ] PR:000006611
- [ ] PR:000006786
- [ ] PR:000007050
- [ ] PR:000007431
- [ ] PR:000007547
- [ ] PR:000007857
- [ ] PR:000007858
- [ ] PR:000008826
- [ ] PR:000009127
- [ ] PR:000009132
- [ ] PR:000009143
- [ ] PR:000009651
- [ ] PR:000010730
- [ ] PR:000013016
- [ ] PR:000014781
- [ ] PR:000014782
- [ ] PR:000014783
- [ ] PR:000014785
- [ ] PR:000015322
- [ ] PR:000016043
- [ ] PR:000016156
- [ ] PR:000016401
- [ ] PR:000016654
- [ ] PR:000016798
- [ ] PR:000025402
- [ ] PR:000050388

**Comment by nicolevasilevsky** [comment]
@matentzn I think these PR terms are being used in the CL import, not in Mondo classes.

**Comment by matentzn** [comment]
Thank you @nicolevasilevsky 

Can you add to the agenda:
- Should we delete floating entities from imports? (I am thinking of a sparql query that deletes all classes from an import without a label)?

**Comment by matentzn** [comment]
- [ ] @matentzn Create yasgui query to go from MONDO to PR then level down to HGNC to ensemble then to the right to HGNC

**Comment by matentzn** [comment]
(works on ontobee)
