### ISSUE TITLE
Distal vs. proximal myopathy with early respiratory failure

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2208]
Trying to determine if both of these terms are still necessary?

MONDO:0011362   hereditary proximal myopathy with early respiratory failure; Links to OMIM:603689  &  OrphaNet: 178464   MONDO:0011859   Distal myopathy with early respiratory muscle involvement ; Links to OMIM:607569 &  Orphanet:34521; UMLS:C4518808 (MONDO:equivalentTo)

OMIM entry 607569  is now merged with 603689: "Myopathy, myofibrillar, 9, with early respiratory failure"
ORPHA:34521 points to UMLS: C1843633, which appears to be a dead CUI. (last active in UMLS release 2019AA)

**Comment by nicolevasilevsky** [comment]
Seems like
MONDO:0011859 Distal myopathy with early respiratory muscle involvement should be merged with MONDO:0011362 hereditary proximal myopathy with early respiratory failure

**Comment by annieolry** [comment]
Hi,
ORPHA:34521 Distal myopathy with early respiratory muscle involvement has been deprecated and moved to ORPHA:178464 Hereditary myopathy with early respiratory failure in September 2018.
Just wondering if you are using the latest Orphanet version.

**Comment by nicolevasilevsky** [comment]
Thanks @annieolry!
