### ISSUE TITLE
Suggested updates to current exactMatch xref MeSH ID

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#2212]
The following  MONDO terms have been highlighted in a recent data check where the listed MeSH ID exactMatch needs review, I have made suggestions below to review.

- [x] MONDO:0004691 autosomal dominant polycystic kidney disease
Currently closeMatch is parent MeSH term D007690 Polycystic Kidney Diseases, suggest change to child MeSH term D016891 Polycystic Kidney, Autosomal Dominant

- [x] MONDO:0012172 mitochondrial trifunctional protein deficiency
Currently closeMatch is D024741 Cardiomyopathy, Hypertrophic, Familial, suggest change to MeSH term D024741 Trifunctional Protein Deficiency With Myopathy And Neuropathy

- [x] MONDO:0013241 spinocerebellar ataxia type 30
Currently C537206 is listed as closeMatch - this is Spinocerebellar Ataxia 29, suggest change to MeSH term C575214 Spinocerebellar ataxia 30

- [x] MONDO:0005711 congenital diaphragmatic hernia
Currently C538080 is listed as closeMatch - this is Hernia, Diaphragmatic, suggest change to MeSh term D065630 Hernias, Diaphragmatic, Congenital

**Comment by nicolevasilevsky** [comment]
FYI - Trifunctional Protein Deficiency With Myopathy And Neuropathy is MESH:C566945

related to https://github.com/monarch-initiative/mondo/issues/2786
