### ISSUE TITLE
Suggested updates to someMONDO terms where xref MeSH IDs from closeMatch to exactMatch 

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#2213]
The following list are MONDO terms where xref MeSHID is currently defined as closeMatch, but I was wondering if they should be exactMatch?

- [x] anterior uveitis (disease); MONDO:0006651; D014606 
->_I am not sure, the text definitions are not exactly the same:
MeSH: Inflammation of the anterior uvea comprising the iris, angle structures, and the ciliary body.
Mondo: Inflammation of the iris and anterior chamber of the eye.
I'm not certain though, @lcdaugherty if you think these are equivalent, I am happy to add the exactMatch annotation._

- [x] pleural empyema (disease); MONDO:0018667; D016724
- [x] nevoid basal cell carcinoma syndrome; MONDO:0007187; D001478
- [x] familial lipoprotein lipase deficiency; MONDO:0009387; D008072
- [x] glycogen storage disease III; MONDO:0009291; D006010
- [x] blepharophimosis, ptosis, and epicanthus inversus syndrome; MONDO:0007201; C562419
- [x] autosomal dominant cerebellar ataxia; MONDO:0020380; D002524
-> _this is equiv to MONDO_0000437 'cerebellar ataxia'_

- [x] Kennedy disease; MONDO:0010735; D055534

**Comment by nicolevasilevsky** [comment]
Talked to Chris - make anterior uveitis equiv to Mondo
