### ISSUE TITLE
[NTR] Collagen VI-Related Myopathy

### ISSUE THREAD

**Issue by RedRiver1816** [monarch-initiative/mondo#2214]
**Preferred term label:**
collagen 6-related myopathy

**Synonyms:** 
collagen VI-related myopathy
collagen VI-related muscle disorder
collagen VI-related muscular dystrophy

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######):**
Collagen VI-Related Myopathy covers a wide spectrum of musculoskeletal phenotypes caused by dominant and recessive mutations in the three major collagen VI genes: _COL6A1_, _COL6A2_, and _COL6A3_. These variants lead to a variety of overlapping phenotypes, ranging from severe congenital muscle weakness, hypotonia, torticollis and contractures with loss or non-development of ambulation on one end and childhood to adult onset mild muscle weakness, stiffness, and joint hyperlaxity on the other. (PMID:21691338)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser):**
MONDO:0016148 (qualitative or quantitative defects of collagen 6)

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
MONDO:0008029 (Bethlem myopathy)
MONDO:0000355 (Ullrich congenital muscular dystrophy)
MONDO:0016111 (non-dystrophic myopathy with collagen 6 anomaly)

**Your nano-attribution (ORCID) or WG URL** https://clinicalgenome.org/affiliation/40031/ (Congenital Myopathies)

@nicolevasilevsky

**Comment by RedRiver1816** [comment]
Updating request status. Any further information necessary?

**Comment by nicolevasilevsky** [comment]
thanks for the nudge @RedRiver1816- I will try to work on this today!

**Comment by nicolevasilevsky** [comment]
@RedRiver1816 do you mean 'Bethlem myopathy 1' should be a subclass of collagen 6-related myopathy? 'Bethlem myopathy 2' has a defect in collagen 12, not collagen 6.

**Comment by nicolevasilevsky** [comment]
- [ ] to do: check the other subclasses and make sure they are col6 deficiencies.

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] 'obsolete non-dystrophic myopathy with collagen 6 anomaly'
- [ ] make a ticket - is myosclerosis a myopathy?
