### ISSUE TITLE
pleural mesothelioma (MONDO:0003308) incorrect exactMatch DOID:5157 benign pleural mesothelioma

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#2218]
Current:
pleural mesothelioma (MONDO:0003308) has exactMatch DOID:5157 benign pleural mesothelioma, but the term itself is broad and is parent to a malignant version, no I not sure if this is correct match?

**Comment by nicolevasilevsky** [comment]
good catch, thanks!
