### ISSUE TITLE
improve Mondo documentation

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2219]
- [x] update the landing page: https://mondo.readthedocs.io/en/latest/
- [x] make Rare Disease analysis in Mondo less prominent
- [x] https://mondo.readthedocs.io/en/latest/build-release/ - update content, combine with other release process page
- [ ] integrate developers guide with editors guide
- [x] add user facing content to http://obofoundry.org/ontology/mondo 
- [x] remove MOSS-cide content
- [ ] update: https://mondo.readthedocs.io/en/latest/editors-guide/e-design-patterns/

**Comment by nicolevasilevsky** [comment]
@matentzn 

do you think we want to include this content on the release documentation?

## Tests

See Makefile for details

* Robot reason - detects logically inconsistency and equivalence between names classes in Mondo
* Sparql checks
    * Standard obo
        * ...
    * Mondo specific
        * ...

Do we want to include this?

**Comment by matentzn** [comment]
Absolutely! I would love to see this, but not right this moment. I have now some ideas to simplify the whole QC business further!

**Comment by nicolevasilevsky** [comment]
I am going to close this, I think our Mondo documentation is serving us well at the moment.
