### ISSUE TITLE
should 'holoprosencephaly 13, x-linked' be a child of holoprosencephaly?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2223]
@ahamosh in Mondo, we think that MONDO_0026763 'holoprosencephaly 13, x-linked' be a child of MONDO_0016296 holoprosencephaly. 'holoprosencephaly 13, x-linked' is not part of the holoprosencephaly PS (https://omim.org/phenotypicSeries/PS236100). Is OMIM planning to add the type 13 to the PS?

Thanks!

cc @cmungall 
Related to https://github.com/monarch-initiative/mondo/pull/2201

**Comment by ahamosh** [comment]
Done.  Thanks for letting us know.  
Ada

**Comment by nicolevasilevsky** [comment]
Awesome, thanks @ahamosh!
