### ISSUE TITLE
should terms and XRefs for MIM numbers or phenotypic series be limited to genetic disorders

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2226]
Megan and I were looking again at porencephaly.

Brain small vessel disease - PS175780  is an XRef for porencephaly MONDO:0017410  rather than familial porencephaly MONDO_0020496

The membership of the phenotypic series suggests a better match for the XRef would be MONDO_0020496

How many other cases are there for an XREF  for OMIM not being connected to the familial concept when there is one?

**Comment by matentzn** [comment]
NOte to self:

design patter for PS:

if X is a pattern instance of the `PS` pattern and also `familial/inherited X` and if there is an instance of another pattern such that the filler for that pattern is X, you need flag that.

**Comment by nicolevasilevsky** [comment]
> Brain small vessel disease - PS175780 is an XRef for porencephaly MONDO:0017410 rather than familial porencephaly MONDO_0020496

It looks like this particular issue has been fixed.

@maglott, Nico and I are looking into your other question.
