### ISSUE TITLE
[NTR] Long COVID

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2228]
**Preferred term label:**
long COVID-19

**Synonyms**
long haul COVID-19
long-haul COVID-19

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
COVID-19 characterized by persistent symptoms in patients who recovered from the acute phase of the SARS-CoV-2 infection, which may include fatigue, coughing, dyspnea, clouding of mentation, sleep disturbances, exercise intolerance and autonomic symptoms including tachycardia upon mild exercise or standing, night sweats, temperature dysregulation, gastroparesis, constipation or loose stools, and peripheral vasoconstriction.

_This is just a quick first draft, we should refine this_

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
COVID-19

**Refs**
https://twitter.com/simoncgordon/status/1321135109572091905
https://jamanetwork.com/journals/jama/fullarticle/2768351
https://n.neurology.org/content/95/13/559.long#T1

**Comment by nicolevasilevsky** [comment]
@pnrobinson do you have thoughts on this?
thanks!

**Comment by pnrobinson** [comment]
@nicolevasilevsky I think this is a good cocept for Mondo.
However, the definition may not be always correct "who recovered from the acute phase of the SARS-CoV-2 infection" -- since I some individuals may go directly from acute to long-haul. Here is a slightly revised version:

```
A chronic disease triggered by acute COVID-19 infection that is characterized by persistent symptoms following the acute phase of the SARS-CoV-2 infection, which may include fatigue, coughing, dyspnea, clouding of mentation, sleep disturbances, exercise intolerance and autonomic symptoms including tachycardia upon mild exercise or standing, night sweats, temperature dysregulation, gastroparesis, constipation or loose stools, and peripheral vasoconstriction.
