### ISSUE TITLE
[NTR] Rapidly progressive primary central nervous system vasculitis

### ISSUE THREAD

**Issue by johannaest** [monarch-initiative/mondo#2229]
**Preferred term label:**
Rapidly progressive primary central nervous system vasculitis

**Synonyms**
Rapidly progressive PCNSV

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
an uncommon condition that affects the brain and spinal cord.
DOI: https://doi.org/10.1093/rheumatology/keq303

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
http://purl.obolibrary.org/obo/MONDO_0018882

**Comment by nicolevasilevsky** [comment]
@johannaest sorry for the delay, I hope to get to this soon. :)

**Comment by nicolevasilevsky** [comment]
I added this as MONDO_0100248
