### ISSUE TITLE
[NTR/gene] A20 Haploinsufficiency/TNFAIP3

### ISSUE THREAD

**Issue by johannaest** [monarch-initiative/mondo#2230]
**Preferred gene-related syndrome label**
A20 Haploinsufficiency

**Synonyms**
HA20

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
http://purl.obolibrary.org/obo/MONDO_0015710

**Definition**
Any immune dysregulation disease in which the cause of the disease is a mutation in the TNFAIP3 gene. 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
DOI: https://doi.org/10.1007/s10875-020-00792-9
PMID:32514655

**Comment by nicolevasilevsky** [comment]
@johannaest is this related to MONDO_0014761 'hereditary pediatric Behçet-like disease' at all?

[OMIM:616744](www.omim.org/616744)

**Comment by nicolevasilevsky** [comment]
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_476102

**Comment by nicolevasilevsky** [comment]
I think there is just a causal link - hereditary pediatric Behçet-like disease is caused by A20 Haploinsufficiency

**Comment by johannaest** [comment]
Hello,


there might be an association, but having hereditary pediatric Behçet-like
 disease is caused by A20 Haploinsufficiency isn't necessarily linked to A20 Haploinsuficency.


PMID:  29890348 


Von: Nicole Vasilevsky <notifications@github.com>
Gesendet: Samstag, 31. Oktober 2020 01:16
An: monarch-initiative/mondo
Cc: Est, Johanna Ligaya; Mention
Betreff: Re: [monarch-initiative/mondo] [NTR/gene] A20 Haploinsufficiency/TNFAIP3 (#2230)
 



I think there is just a causal link - hereditary pediatric Behçet-like disease is caused by A20 Haploinsufficiency
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by cmungall** [comment]
Is this not the same as https://www.omim.org/entry/616744 ?

**Comment by nicolevasilevsky** [comment]
@johannaest could you reply to Chris' comment above? Please also see his comment here: https://github.com/monarch-initiative/mondo/pull/2275#issuecomment-726995626

Thanks!

**Comment by johannaest** [comment]
A20 haploinsufficiency is a monogenic autoinflammatory disease with highly variable clinical manifestations. This extensive heterogeneity makes it difficult to set a clinical
 diagnostic criteria, and genetic sequencing is necessary for a definitive diagnosis.

A simple genotype- phenotype correlation does not exist, PMID:29317407​,
 PMID: 26642243​
​



Von: Nicole Vasilevsky <notifications@github.com>
Gesendet: Samstag, 14. November 2020 01:22
An: monarch-initiative/mondo
Cc: Est, Johanna Ligaya; Mention
Betreff: Re: [monarch-initiative/mondo] [NTR/gene] A20 Haploinsufficiency/TNFAIP3 (#2230)
 



@johannaest could you reply to Chris' comment above? Please also see his comment here:

#2275 (comment)
Thanks!
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
