### ISSUE TITLE
Need help with GARD definitions

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#224]
@gardinfocenter - I have some questions about the following terms:

- [albinism immunodeficiency](https://rarediseases.info.nih.gov/diseases/590/albinism-immunodeficiency) - do you think this [paper](https://rarediseases.info.nih.gov/diseases/590/albinism-immunodeficiency) is describing this disease?
- [amyoplasia mandibulofacial dysostosis](https://rarediseases.info.nih.gov/diseases/660/amyoplasia-mandibulofacial-dysostosis) - I can't find anything about this online

**Comment by GARDInfoCenter** [comment]
We believe that albinism immunodeficiency is Griscelli syndrome, so we retired the term "albinism immunodeficiency"

OMIM has information about Amelia cleft lip palate hydrocephalus iris at  https://www.omim.org/entry/601357 and https://rgd.mcw.edu/rgdweb/ontology/view.html?acc_id=DOID:9000201&offset=11.6015625 

Amyoplasia mandibulofacial dysostosis was also retired.  We were unable to find any literature for this one.  We believe it may be referring to Freeman-Sheldon syndrome.

**Comment by nicolevasilevsky** [comment]
Thanks! I made a note that those terms were retired and I will obsolete them in MONDO.
