### ISSUE TITLE
OMIM Phenotypic Series for CDG type I on two MONDO terms?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2248]
It looks like the OMIM Phenotypic series for type I CDGs has inappropriately been assigned to both the parent "congenital disorder of glycosylation" term AND the CDG type I term.  Is this intentional?
(PS212065 cross ref'd by MONDO:0015286 and MONDO:0005500)

In contrast: the OMIM PS PS212066  for CDG type II maps only to  MONDO:0005501.

**Comment by nicolevasilevsky** [comment]
Hi @kanems 

the dbxref on MONDO:0015286 'congenital disorder of glycosylation' is not an equivalent reference, it looks like it was brought in from the Disease Ontology (DO)- they had an xref to this OMIMPS. We would like to keep it there to maintain the provenance. Thee dbxref on MONDO:0005500 'congenital disorder of glycosylation type I' is an equivalence axiom, meaning this class is equivalent to the OMIMPS term.

Let me know if you have further questions.

Thanks!
