### ISSUE TITLE
nonpapillary Renal cell carcinoma & clear cell renal carcinoma

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2262]
There is a comment on MONDO:0007763 "nonpapillary renal cell carcinoma" about "consider merging into MONDO:0005005" ("clear cell renal carcinoma"). What is the status of this potential merge?

UMLS C0279702 "Conventional (Clear Cell) Renal Cell Carcinoma" maps the "nonpapillary RCC" terms from OMIM and HPO as synonyms, HPO treats these two terms as synonyms as well.

**Comment by nicolevasilevsky** [comment]
@kanems thanks for this ticket - looks like no work has begun on this yet.

@galyea-gard, do you have thoughts about this merger?

**Comment by nicolevasilevsky** [comment]
Note to self - emailed Lori and Lyuba at NCIT

**Comment by galyea-gard** [comment]
OMIM groups the several renal carcinomas that are not "papillary" under "nonpapillary".  Renal cancer is classified into clear cell RCC (the most common subtype) that can be hereditary (the one listed on Orphanet and in NCI thesaurus with Code C36260) or non-hereditary.  See NCI thesaurus for classification: https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&version=20.10d&code=C9385&ns=ncit&type=relationship&key=1015154550&b=1&n=0&vse=null 
I don't think that the nonpapillary Renal cell carcinoma & clear cell renal carcinoma are really synonyms.  NCI thesaurus does not have the term "non papillary renal cell carcinoma". Note that we don't have these terms in GARD but we will refer to NCI thesaurus as our primary source when dealing with cancer. Thanks! Gioconda
#

**Comment by nicolevasilevsky** [comment]
From Lori at NCIt:

Non-papillary RCC should definitely not be merged with clear cell RCC. If you can it would be best to eliminate the term non-papillary RCC.

Clear cell RCC and papillary RCC are not the only RCCs described. The list also includes the sarcomatoid RCC, chromophobe RCC, tubulocystic RCC and a wide variety of RCCs associated with translocations/gene fusions of various transcription factors including TFE3 and TFEB (MIT family translocations).

**Comment by nicolevasilevsky** [comment]
@kanems I am going to remove the comment, and we won't merge these terms.
Thanks!

**Comment by kanems** [comment]
Thank you all for clarifying!

**Comment by kanems** [comment]
I think there is an issue with the Orphanet X-ref: ORPHA:319276 is called "Clear cell renal carcinoma" and maps to UMLS C0279702, which is where the SNOMED and NCIT codes from MONDO:0005005 map.
move Orpha"319276 to  MONDO:0005005
