### ISSUE TITLE
capitalize roman numerals

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2269]
**Mondo term (ID Label)**
MONDO_0008659|transcobalamin i deficiency
MONDO_0010961|obesity due to prohormone convertase i deficiency
MONDO_0013422|type i complement component 8 deficiency

**Bug/Typo/Error description**
I did not do an exhaustive search, but found these looking for a lower case letter bounded by spaces that could be a roman numeral
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@matentzn I fixed these examples above, but is there a way to easily find all the cases of terms that should have capitalized roman numerals and automatically fix this?

If not, I can just keep an eye out for these and fix them as needed.

Thanks @maglott for reporting this issue!

**Comment by matentzn** [comment]
search for `\s(i?i?i|iv|v|vi+|i+x|x|x+i+)\s` remember to keep capitalisation `aA` sensitive and regex on.
