### ISSUE TITLE
Mitochondrial complex I deficiency, nuclear type 1

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2277]
I see the parent term mitochondrial complex I deficiency, nuclear type covers sub-types/children numbered between 2 and 34, but no term for type 1. This is represented by OMIM 252010 and has a unique genetic etiology (NDUFS4); the OMIM PS 252010 does certainly seem to belong on  MONDO:0009640, but I wonder if  there should be a separate child for "mitochondrial complex I deficiency, nuclear type 1" ?

Also, since these are nuclear-type mitochondrial deficiencies with multiple genetic etiologies, should "mitochondrial complex I deficiency, nuclear type" necessarily go in the hierarchy under "syndromic neurometabolic disease with X-linked intellectual disability? Just from checking a few of the entries on the OMIM PS, it looks like the genes are located at multiple autosomal loci, so they are not all X-linked.

**Comment by nicolevasilevsky** [comment]
@kanems good catch - yes, we should split OMIMPS:252010 and OMIM:252010

**Comment by nicolevasilevsky** [comment]
syndromic neurometabolic disease with X-linked intellectual disability is being inferred as a parent because mitochondrial complex I deficiency, nuclear type is a child of 'X-linked syndromic intellectual disability'. I'll exclude this parent and this will be fixed.

Thanks!!

**Comment by nicolevasilevsky** [comment]
@matentzn do we have a check (or warning) if a term has an OMIM and OMIMPS that are both annotated with MONDO:equivalentTo?

**Comment by nicolevasilevsky** [comment]
For the record, I think this was a mistake that I made, see this ticket: https://github.com/monarch-initiative/mondo/issues/1042

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] create new class 'mitochondrial complex I deficiency, nuclear type'
- [ ] create new class 'mitochondrial complex I deficiency, nuclear type, type 1'
- [ ] merge MONDO:0009640 'mitochondrial complex I deficiency, nuclear type' with 'mitochondrial complex I deficiency, nuclear type, type 1'
- [ ] make sure all the same parents (from Orphanet) are added to 'mitochondrial complex I deficiency, nuclear type, type 1'
