### ISSUE TITLE
Add term for the OMIM PS191830, renal hypoplasia/aplasia[NTR]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2283]
**Preferred term label:**
Renal hypodysplasia/aplasia

**Synonyms**
Renal agenesis/hypoplasia (HP:0008678)
Absent/small kidney
Absent/underdeveloped kidney

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Absence or underdevelopment of the kidney.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
http://purl.obolibrary.org/obo/MONDO_0018470

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
renal hypodysplasia/aplasia 1 (MONDO:0024519)
renal hypodysplasia/aplasia 2 (MONDO:0014319)
renal hypodysplasia/aplasia 3 (MONDO:0024520)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

Additional X-refs: 
UMLS CUI:C1857453
HPO: HP:0008678

**Comment by nicolevasilevsky** [comment]
We already have this:
MONDO_0018470 'renal agenesis (disease)'

Please reopen if anything else is needed.

**Comment by nicolevasilevsky** [comment]
Oh wait - I'll add the xrefs
