### ISSUE TITLE
Merge Status: MONDO:0013517 (beta thalassemia)

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2284]
On MONDO:0013517 (beta-thalassemia HBB/LCRB), there is an "editor note: consider merging into parent." What is the status of this merge?

**Comment by nicolevasilevsky** [comment]
I think we should remove this comment, based on discussion in this ticket https://github.com/monarch-initiative/mondo/issues/1756, it seems like this is a valid term.
