### ISSUE TITLE
[Revise logical def]  MONDO_0005120

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2286]
**Mondo term (ID and Label)**
MONDO_0005120/Drosophila C virus infection

**Suggested revision of logical definition**
Should this be a child of MONDO:0005583?  As far as I can tell there are no reports of the virus infecting humans.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
viral infectious disease is not restricted to humans though.
I can add the parent 'non-human animal disease', does that work?

**Comment by maglott** [comment]
Thanks, Nicole.  That helps because MedGen excludes all children of non-human animal disease for automatic processing.
