### ISSUE TITLE
Add RGD disease xrefs/equivalencies

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/mondo#23]
I think these are essentially re-ID'd from the CTD-OMIM file, but not 100% certain of what has been added/changed since that file was generated.
 
ftp://ftp.rgd.mcw.edu/pub/ontology/disease/RDO.obo
ftp://ftp.rgd.mcw.edu/pub/ontology/disease/

**Comment by nicolevasilevsky** [comment]
Out of scope. RGD uses DO.
