### ISSUE TITLE
familial thrombocytosis and essential thrombocythemia

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#230]
action items:

- [ ] MONDO_0008554 'thrombocythemia 1' should be a child of MONDO_0019111 'familial thrombocytosis' (per the OMIMPS)
- [ ] MONDO:0002249 'thrombocytosis disease' should be a parent of Essential thrombocythemia and Familial thrombocytosis

_updated 2021-10-26 NV_

----

quick review, my understanding is:

 * thrombocytosis is a finding
 * ET is a myeloproliferative neoplasm that causes thrombocytosis
 * ET was only recently classified as neoplasm by WHO so confusion may arise from older pubs
 * ET can be caused by somatic or germline mutations in a few different genes ([OMIM summary](https://www.omim.org/entry/187950))

We have some confusion at the moment about whether a term for familial thrombocytosis/thrombocythemia should exist and how it should be placed.

ORDO has two classes:

 * essential thrombocythemia http://www.orpha.net/ORDO/Orphanet_3318 *Essential thrombocythemia (ET) is a myeloproliferative neoplasm (MPN, see this term) characterized by a sustained elevation of platelet number (> 450 x 109/L) with a tendency for thrombosis and hemorrhage*
* familial thrombocytosis http://www.orpha.net/ORDO/Orphanet_71493 *Familial thrombocytosis is a type of thrombocytosis, a sustained elevation of platelet numbers, which affects the platelet/megakaryocyte lineage and may create a tendency for thrombosis and hemorrhage __but does not cause myeloproliferation__*

Based on the definitions these are disjoint classes differentiated by whether the degree of  myeloproliferation is considered neoplastic? This seems unusual.

Also: FT is linked to all 4 OMIMs in the phenotypic series for FT. ET has only 3 of these (lacks THCYTX)

**Comment by maglott** [comment]
Can this be resolved by treating Essential thrombocythemia and Familial thrombocytosis as children of MONDO_0002249 ?  
Seems to me the Familial thrombocytosis is equivalent to the implied familial nature of https://www.omim.org/phenotypicSeries/PS187950, and that the specifics of the familal forms should be indented under Familial thrombocytosis rather than being siblings.

**Comment by maglott** [comment]
Encountered this again with review of managment for NCBI.  Given that  familial thrombocytosis is an explicit term AND and an exact synonym for essential thrombocythemia, seems cleanup is warranted.
