### ISSUE TITLE
Is bilirubin induced brain injury in the newborn the same as BIND?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#231]
@gardinfocenter - 
is _bilirubin induced brain injury_ the same as Bilirubin-induced neurologic dysfunction (BIND)?
See paper: https://www.sfnmjournal.com/article/S1744-165X(14)00098-5/fulltext (PMID: 25585889)

**Comment by GARDInfoCenter** [comment]
We retired “ bilirubin-induced brain injury”. Bilirubin-induced neurologic dysfunction (BIND) is the term used for the neurologic abnormalities associated with kernicterus (which we already list).

**Comment by nicolevasilevsky** [comment]
Noted - thanks! :)
