### ISSUE TITLE
update MR to intellectual disability

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2310]
We still have labels and synonyms that use 'mental retardation', which should be updated to 'intellectual disability' and any synonym that uses MR should have a deprecate tag: https://mondo.readthedocs.io/en/latest/editors-guide/f-entities/#depracate-synonyms

Chris said this could probably be done via a SPARQL query.

Thanks @matentzn!

**Comment by cmungall** [comment]
or sed
