### ISSUE TITLE
[Obsolete] atrophy terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2312]
related to https://github.com/monarch-initiative/mondo/issues/528

I obsoleted 'degenerative disorder' on PR https://github.com/monarch-initiative/mondo/pull/2311

There were several atrophy terms that were children, which should possibly be obsoleted too and consider HPO terms instead:

MONDO term | HPO ID | HPO term | Proposed action
-- | -- | -- | --
atrophy of lacrimal gland | | n/a | New term request to HPO
atrophy of prostate | | n/a | New term request to HPO
'atrophic vulva' | | n/a | New term request to HPO
'Wallerian degeneration' | HP_0003378 | 'Axonal degeneration/regeneration' | 

_Update:_
I don't think we should obsolete MONDO_0003608 'optic atrophy' as it is equiv to an OMIMPS.

cc @cmungall @pnrobinson

**Comment by nicolevasilevsky** [comment]
cc @galyea-gard GARD has Wallerian degeneration, there is a comment on this term in Mondo: this may represent a process. Consider ceding to HPO

We welcome your comments - thanks!

**Comment by pnrobinson** [comment]
Wallerian degeneration is neither a disease nor a phenotype. I am not sure we can easily represent it -- https://en.wikipedia.org/wiki/Wallerian_degeneration   we need a pathophysiology ontology

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson! I won't add it as a synonym to HP_0003378 'Axonal degeneration/regeneration', but I could still add a consider annotation, since that term is related.

**Comment by cmungall** [comment]
Fine with obsoletion. I don't think the consider annotation buys us much.

We may want to coordinate with NCIT who model as a disease:

https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C85223

_A condition caused by degeneration, atrophy, and destruction of the distal part of a nerve fiber's axon and myelin, when continuity with the neural cell nucleus has been severed due to injury. Signs and symptoms include muscle weakness, altered sensation, and limb numbness. _

**Comment by nicolevasilevsky** [comment]
I'll follow up with NCIT, thanks!

**Comment by nicolevasilevsky** [comment]
Emailed NCIT 11/16/20

**Comment by galyea-gard** [comment]
Hi Nicole!  I believe we will retire this term, which is a mechanism of axon degeneration. Thanks!  Gioconda

**Comment by nicolevasilevsky** [comment]
NCIT recommends Mondo keep this valid term ['Wallerian degeneration']. It is the result of axon degeneration caused by trauma. It is a specific morphologic and biochemical process that results in the regeneration of the axon.

Decision - I will keep it and classify it.

**Comment by galyea-gard** [comment]
Hi Nicole!  For us, because we only will keep the rare or genetic disorders, most probably it will retired.  Thank you!  Gioconda

**Comment by nicolevasilevsky** [comment]
Sounds good, thanks @galyea-gard!
