### ISSUE TITLE
Kilquist Syndrome [NTR]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2323]
**Preferred term label:**
Kilquist Syndrome (source: https://www.omim.org/entry/619080)

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Kilquist syndrome (KILQS) is an autosomal recessive multisystem disorder characterized by neurologic, gastrointestinal, and secretory dysfunction. Affected individuals present at birth with hypotonia, feeding difficulties, mild dysmorphic features, and sensorineural hearing loss. They show poor overall growth associated with gastrointestinal anomalies such as gastroesophageal reflux or midgut malrotation, as well as profound global developmental delay with inability to sit or speak. Tear, sweat, and saliva production is also impaired, causing dry mouth and recurrent bronchial mucus plugging. Some of the clinical features are reminiscent of cystic fibrosis. (OMIM 619080; See also https://pubmed.ncbi.nlm.nih.gov/30740830/ and https://pubmed.ncbi.nlm.nih.gov/32754646/ )

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
(Unsure; possibly http://purl.obolibrary.org/obo/MONDO_0019589 "syndromic genetic deafness" MONDO:0019589 based on described phenotype?)

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@matentzn will this come in the next OMIM ingest? Thanks!

**Comment by nicolevasilevsky** [comment]
This is now in Mondo:
MONDO_0033664
