### ISSUE TITLE
Heritable pulmonary arterial hypertension

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2325]
Should heritable pulmonary arterial hypertension (MONDO:0017148) be a parent term to primary pulmonary hypertensions 1-4  rather than a sibling? 
Orphanet 275777 Maps to OMIM 178600 (PPH1) and  615342 (PPH3), 
UMLS C0340543 (Familial PPH, aka HPAH) appears to be a parent term to PPH1, PPH2, PPH3, PPH4, (and others) but child to "idopathic pulmonary hypertension" Supporting a more "nested" view of this PAH tree.

**Comment by nicolevasilevsky** [comment]
@cmungall is it okay to nest the OMIM terms lower in the hierarchy, and not directly below the OMIMPS?

![image](https://user-images.githubusercontent.com/6722114/101707659-81818880-3a40-11eb-8c14-5a50b3ffade0.png)

**Comment by cmungall** [comment]
surely all PSs are hereditary? i.e move the PS down one. And nest the OMIMs under this of course

These kinds of cases should be easy to check for automatically. Can you make a ticket? We'd auto add an axiom to all PSs to this effect, then the reasoner pipeline will alert us to everything needing attention

**Comment by nicolevasilevsky** [comment]
Chris shared this:
obo-sed.pl -r 'xref: OMIMPS.*equivalent' 's/name:/relationship: has_modifier MONDO:0021152 {source="TICKET"}\nname:/' mondo-edit.obo
@matentzn
