### ISSUE TITLE
Merge status? MONDO:0024462

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2326]
MONDO:0024462 
familial cutaneous melanoma

Has a note: "Editor note: consider merge with parent"
What is the status of this merge?

**Comment by nicolevasilevsky** [comment]
I'll look into this

**Comment by nicolevasilevsky** [comment]
This is the parent for susceptibility terms in OMIM, we are planning to discuss these with Ada on a call next month. @kanems if you don't mind, we'll revisit this ticket then.

**Comment by kanems** [comment]
That will be great, thanks!

**Comment by nicolevasilevsky** [comment]
related to #407

**Comment by nicolevasilevsky** [comment]
@kanems this is being addressed in #407, I will close this.
