### ISSUE TITLE
Typo - Sprengel anomaly (HP:0000912)

### ISSUE THREAD

**Issue by GARDInfoCenter** [monarch-initiative/mondo#233]
@nicolevasilevsky There is a typo for Sprengel anomaly (0000912). One of the synonyms is misspelled (High schoulder blade). Could we correct the spelling?

GARD received an inquiry from a person who would like to take a copy of the vascular EDS GARD page to her doctor and would like to see the term spelled correctly. 

How long before the change will be reflected through your database?

Thanks,
Maria

**Comment by nicolevasilevsky** [comment]
I fixed the typo. @pnrobinson any idea when the next release of HPO will be?
