### ISSUE TITLE
disease susceptibility should not be a subclass of the disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2334]
@matentzn please do a SPARQL query to find all susceptibility of classes and remove superclass assertions to the the parent disease. For example:

MONDO:0012863 `attention deficit-hyperactivity disorder, susceptibility to, 6` should not be a child of MONDO:0007743  `attention deficit-hyperactivity disorder`

cc @cmungall

**Comment by maglott** [comment]
How should susceptibilities be treated?  Are they phenotypes and not disorders?

**Comment by nicolevasilevsky** [comment]
Good question @maglott, I think that is a bigger question.
@pnrobinson opened this ticket (https://github.com/monarch-initiative/mondo/issues/496) a while ago suggesting we obsolete susceptibility terms.

For now, I think we'll move these OMIM susceptibility terms to children of Mendelian disease.

**Comment by cmungall** [comment]
I think you mean outside of Mendelian?

yes the susceptibilities should be outside the main hierarchy

**Comment by nicolevasilevsky** [comment]
right now, these OMIM terms are classified as Mendelian diseases too (such as 'attention deficit-hyperactivity disorder, susceptibility to, 6' is a child of Mendelian disease and 'attention deficit-hyperactivity disorder'.

I guess they should be asserted to be children of MONDO_0020573 'inherited disease susceptibility', yes?

**Comment by cmungall** [comment]
yes

we'll work towards making disease susceptibility and disease disjoint...
incremental progress

**Comment by pnrobinson** [comment]
@cmungall  Please do not do this. There is no disease called X susceptibility. The disease is simply "X". Once can only infer "X susceptibility if one figures out that say Y% people with a mutation in some gene have the disease where Y% is higher than in people without a mutation in the gene. But people with the mutation either have or do not have the disease. @ahamosh could we set up a call to discuss how MONDO should name the diseases where OMIM has X susceptibility? It would be good to agree upon and document our rules.

**Comment by maglott** [comment]
ClinVar has been inconsistent with this, and would appreciate consensus on a way to go forward.  When variants contribute to susceptibility to  disorder D, we have curated some to be an interpretation of susceptibility to disorder D, removing the record for "susceptibility to disorder D".  But we don't have enough curation resources to maintain all these, and thus  have let most be retained as phenotypes given that they are assigned IDs by OMIM, UMLS, and now Mondo.

**Comment by ahamosh** [comment]
This definitely requires a conversation. Some "susceptibility to" are for germline increased risk that requires additional factors (genetic or environmental), for example:  BRCA1 or BRCA2 and Breast and Ovarian Cancer.  Having the variant doesn't give you the disease, you need to accumulate more somatic mutations, but it significantly increases the risk.  Also UNC93B and HSV encephalitis: if you aren't exposed to HSV young, you won't get the encephalitis.  We won't be eliminating those. 

Let's set up a zoom to discuss. Please not next week.

**Comment by nicolevasilevsky** [comment]
@ahamosh we have weekly meetings scheduled on Fridays at 9am PT/12pm ET - are you available then? The meeting is canceled next week due to TG. If that doesn't work, we can find another time. Thanks!

**Comment by ahamosh** [comment]
Hi Nicole,  I have to run a clinical faculty meeting at 9 am on 12/4, but I can do 12/11 barring a patient emergency because I will be on call.  Can I have Joanna join?

**Comment by nicolevasilevsky** [comment]
Hi @ahamosh - great, I'll send you and Joanna an appointment - we'd love to have Joanna join!

**Comment by nicolevasilevsky** [comment]
- [x] check for 'predisposes towards'
- [ ] check for lexical pattern (susceptibility), such as MONDO_0012682 'susceptibility to infection due to TYK2 deficiency' and is a child of any disease that is not 'inherited disease susceptibility' (ie the parent of this class is: 'autosomal recessive mendelian susceptibility to mycobacterial diseases due to a partial deficiency') (or the superclass does not have the label 'susceptibility' in the name)
- [ ] check classes that have subset tag 'predisposition'

**Comment by nicolevasilevsky** [comment]
moved to a discussion: https://github.com/monarch-initiative/mondo/discussions/2672
