### ISSUE TITLE
autosomal recessive cutis laxa type 2, classic type

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2337]
I am confused by the distinction/cross references on
autosomal recessive cutis laxa type 2, classic type MONDO:0009054
and
autosomal recessive cutis laxa type 2A MONDO:0018163 .

OMIM 219200 https://www.omim.org/entry/219200  should maybe map to ARCL2A (not Classic type)? Same for GARD 0001638 https://rarediseases.info.nih.gov/diseases/1638/cutis-laxa-autosomal-recessive-type-2a 

Orphanet 357074  seems appropriately placed on the Classic type.

And why are the ARCL Type 2C and 2D children of the 2A/2 Classic? These have distinct molecular etiologies and would make more sense as siblings of ARCL2A.

Based on the cross-refernces and this page from NORD https://rarediseases.org/rare-diseases/cutis-laxa/ I suggest the following hierarchy:

(Multiple parent terms possible, no change)

1. -ARCL2A MONDO:0018163
    A.-ARCL2, CT MONDO:0009054 (aka ARCL Debre type, etc)
2.-ARCL2C
3.-ARCL2D

**Comment by nicolevasilevsky** [comment]
@kanems sorry for the delay, I hope to get to this soon. :)

**Comment by nicolevasilevsky** [comment]
@kanems
- I made OMIM:219200 equiv to 'autosomal recessive cutis laxa type 2A', as you requested.
- made GARD:0001638 equiv to 'autosomal recessive cutis laxa type 2A' as well
- moved synonyms from classic type to 'autosomal recessive cutis laxa type 2A'

Looks like Type 2C and 2D are no longer children of CT

![image](https://user-images.githubusercontent.com/6722114/106542814-5ef87280-64b9-11eb-8777-5f6123966d6c.png)
