### ISSUE TITLE
Need to see what has been obsoleted in Orphanet and sync

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2338]
review obsoleted terms in Orphanet and make sure they are obsoleted in Mondo too

Let @nicolevasilevsky if she can help 👍

**Comment by matentzn** [comment]
[ordo_deprecated.txt](https://github.com/monarch-initiative/mondo/files/5583544/ordo_deprecated.txt)

Can you manually check some of these please @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
I spot checked this list and it looks good!

**Comment by matentzn** [comment]
So how are we ideally going about this? I could Mark them for obsoletion (put a property on them like to-be-obsoleted true), but I can't obsolete them.. or do you just want to work down the list until it's done?

**Comment by nicolevasilevsky** [comment]
Oh, if it is not possible for you to bulk obsolete them, then yes, I can work down the list and manually obsolete them.

**Comment by nicolevasilevsky** [comment]
There isn't much of an advantage to giving them the 'obsoletion candidate' subset tag. I'll work on this asap.

**Comment by nicolevasilevsky** [comment]
I added a spreadsheet [here](https://docs.google.com/spreadsheets/d/1L1foI_s4hQkRxbJCdT_d9DW6Hnk8i4gR/edit#gid=601470673)

**Comment by nicolevasilevsky** [comment]
closing in favor of #3509
