### ISSUE TITLE
NTR: VEXAS syndrome

### ISSUE THREAD

**Issue by galyea-gard** [monarch-initiative/mondo#2342]
Hi Nicole:  I received a message from a NIH coding staff about a new syndrome known as "VEXAS syndrome" (please see:  https://pubmed.ncbi.nlm.nih.gov/33108101/).    The syndrome is already in OMIM: https://omim.org/entry/301054?search=VEXAS&highlight=vexas and it was researched by the NIAMS.  Please let me know if you can add this one and I will also add it to GARD.  Thank you! Gioconda

**Comment by cmungall** [comment]
We added this (this PR #2332) and will be in next release!

**Comment by galyea-gard** [comment]
Thank you Nicole!
