### ISSUE TITLE
Crisponi syndrome a synonym or distinct disorder?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2345]
"Cold induced sweating syndrome" MONDO:0015526 is a parent to 3 children conditions: "Crisponi syndrome" (aka cold induced sweating syndrome 1),  "cold induced sweating syndrome 2" and "cold induced sweating syndrome 3." However, "Crisponi syndrome" is given as a synonym for this parent term.

Can we clarify where "Crisponi syndrome" belongs? It is a synonymous term for broad parent, or the preferred name CISS1?

Also, OMIM 617055 now uses 'PERCHING Syndrome" as the preferred name for CISS3 (and CISS3 is a former name), so this should probably be updated in the synonyms.

**Comment by nicolevasilevsky** [comment]
This synonym on 'cold-induced sweating syndrome' is meant to be excluded:

![image](https://user-images.githubusercontent.com/6722114/101711615-c27d9b00-3a48-11eb-8aaa-ec840014779a.png)

This is similar to another ticket.

**Comment by nicolevasilevsky** [comment]
I updated the label - thanks for letting me know about that!
