### ISSUE TITLE
[NTR] Subtypes in MONDO

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#2360]
Open question:
Should we have two subtypes of Ichthyosis vulgaris, corresponding to a mild and severe form. We may need to bring Courtney into this discussion.

_Update 2022-11-30 by @nicolevasilevsky _

---

Ichthyosis vulgaris (https://omim.org/entry/146700) has currently one entry in MONDO (http://purl.obolibrary.org/obo/MONDO_0024304). However, heterozygote FLG mutation carriers have mild manifestations, while homozygous mutation carriers have more severe manifestations. For computational analysis, it would be good to have separate entries. Ideally this would be done together with OMIM. @ahamosh 
Can we discuss a strategy for this? There are many analogous examples.

**Comment by ahamosh** [comment]
Hi Peter,
The feeling in ClinGen is that if homozygous affected have the same kind (but more severe phenotype) to keep it as one disease.  OMIM has usually done the same thing, but not always.  We create a new phenotype if it is clinically different rather than more severe.  I am happy to discuss.  We should bring Joanna and Carol from OMIM in.  Might want to include Courtney Thaxton from ClinGen.  We need a consensus on phenotype names and lumping and splitting. (BTW have you joined the ClinGen Lumping and Splitting Work Group? We need your perspective there.)

**Comment by pnrobinson** [comment]
Hi Ada,
the reason for having two entities (which we can consider as one disease) is that it makes it easier to investigate genotype phenotype correlations, since databases etc often use the OMIM identifier to denote the disease entity. As always, there is more than one way of doing things, and if the community decides for lumping, then the HPO project will need to record this information in a separate field (and hopefully other databases would adopt the same schema). I did join the group, but after I had to miss the first meeting, I did not get further invitations ... I will contact Courtney again.

**Comment by mellybelly** [comment]
@nicolevasilevsky can we go through all the tickets and flag ones like this one with a new tag for "lumping and splitting" implementation guidelines? Obviously what we want to avoid is applying our classifications different in different contexts. Working with the lumping and splitting group will be a terrific way to operationalize and set up axiom consistency checks for Mondo as things mature.

**Comment by maglott** [comment]
Is the design option to retain a 1:1 relationship between MIM number and Mondo ID

**Comment by cmungall** [comment]
@nicolevasilevsky, What's the scope of this issue?

 - all subtyping relationships in mondo?
 - severity DPs
 - Ichthyosis vulgaris specifically

**Comment by nicolevasilevsky** [comment]
there is a case where we have two diseases that are distinguished by severity:
MONDO_0013930 'peroxisome biogenesis disorder 4A (Zellweger)'
'has modifier' some 'classic presentation'
'has modifier' some Severe

MONDO_0013931 'peroxisome biogenesis disorder 4B'
'has modifier' some 'non-classic presentation'
'has modifier' some Moderate

@sabrina and others discussed this on the Mondo curation call - we think it would make sense to have a triad with:
Ichthyosis vulgaris 
- severe ichthyosis vulgaris 
- mild ichthyosis vulgaris 

and we could a design pattern for this. And we'd add terms like this upon request by experts.
