### ISSUE TITLE
is myosclerosis a myopathy?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2361]
Currently MONDO_0009714 myosclerosis is a subclass of MONDO_0100225 'collagen 6-related myopathy' - is this the best parent?

related to https://github.com/monarch-initiative/mondo/issues/2214

**Comment by nicolevasilevsky** [comment]
@pnrobinson when you have a chance, could you look at this ticket? Thanks!

**Comment by pnrobinson** [comment]
AFAIK this disease (https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=289380) is a poorly characterized myopathy of unknown etiology. From the description in Orphaned, the expression of COL6 is reduced but this does not make it into a collagen 6 myopathy in the way that the remaining subclasses of the latter are. However, the COL6A2 gene (same as OMIM) is listed there. In addition to that, OMIM reports a single family with collagen 6-related Mendelian AR myosclerosis (https://omim.org/entry/255600). 
I am not sure whether the Orphaned and OMIM entries both refer to exactly the same thing, but it seems not crazy to merge the entries and primarily refer to the genetic etiology. If at a later time, more knowledge becomes apparent about non-Mendelian forms of the disease, we can add additional entries. It would be good to summarize this in the Mondo definition. @ahamosh thoughts?

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson!

@ahamosh the question for you is if [ORPHA:289380 Myosclerosis](https://www.orpha.net/consor/cgi-bin/Disease_Genes_Simple.php?lng=EN&LnkId=20719&Typ=Pat&diseaseType=Gen&from=rightMenu) is equivalent to [OMIM:255600 MYOSCLEROSIS, AUTOSOMAL RECESSIVE](https://omim.org/entry/255600)?

If you agree, my action item is to merge MONDO:0009714 myosclerosis and MONDO:0100225 'collagen 6-related myopathy'

**Comment by nicolevasilevsky** [comment]
OMIM states there is one family with this disease and are unsure if this is an actual disease. Whereas the ORDO class seems to be more assertive that this is a disease. OMIM has a question mark b/c it is only one family, Orphanet does not provide enough evidence that this is a legitimate disease.

 Ada noted that there were functional studied that were done but it is still questionable. Nothing has been reported since, which is skeptical.

@pnrobinson recommends proceeding with merging.

**Comment by cmungall** [comment]
Agree these should be merged

**Comment by nicolevasilevsky** [comment]
@sabrinatoro could you please add this to the list:
 merge MONDO:0009714 myosclerosis and MONDO:0100225 'collagen 6-related myopathy'

**Comment by sabrinatoro** [comment]
@nicolevasilevsky I am confused about this issue: 
- collagen 6-related myopathy (MONDO:0100225) = myopathy in any of the collagen VI genes: COL6A1, COL6A2, and COL6A3
- myosclerosis (MONDO:0009714) is specific to COL6A2; it is equivalent to OMIM:255600 and Orphanet:289380.

Are we really saying that these 2 concepts are the same? I agree that the omim and orphanet are the same concept, but I am not sure that the 2 mondo terms are.

Note: many things might have changed in the ontology since this issue, so it is possible that what I see currently does not reflect anymore what it was when this issue was created.

**Comment by nicolevasilevsky** [comment]
I'd have to read through all the comments to understand why we discussed merging these, but upon first glance, it does not look like these two mondo concepts are the same, I agree with you.

**Comment by sabrinatoro** [comment]
Based on my previous comment, I think that the current representation in the ontology is correct. I am closing this issue. We can re-open it if necessary.
