### ISSUE TITLE
[NTR/gene] map UniProtKB 2021_01 release to MONDO

### ISSUE THREAD

**Issue by Antonialock** [monarch-initiative/mondo#2362]
Hi,

for Uniprot release 2021-01 we require the following MONDO terms for mapping:

Not sure how the omim ingests work now on your end, so thought I'd raise this request. I have attached the DI defs after the table in case they are useful.
There were a few odd terms that are shown in the monarch explorer, but they are only associated with the MIM ID and a DO ID - not sure why they don't have a MONDO ID? (these terms have a DOID in the comments field  in the table below)

@nicolevasilevsky @matentzn 

UniProt Accession | Disease Name | OMIM | Comment
-- | -- | -- | --
DI-05918 | Coenzyme Q10 deficiency, primary, 9. | 619028 | DOID:0112138
DI-05920 | Vissers-Bodmer syndrome. | 619033 |  
DI-05922 | Neurodevelopmental disorder with progressive spasticity and brain white matter abnormalities. | 619026 |  
DI-05923 | Spastic paraplegia 83, autosomal recessive. | 619027 |  
DI-05924 | Myopathy, epilepsy, and progressive cerebral atrophy. | 619036 |  
DI-05925 | Myopathy, myofibrillar, 10. | 619040 | DOID:0112108
DI-05926 | Spinal muscular atrophy, infantile, James type. | 619042 |  
DI-05927 | Spermatogenic failure 44. | 619044 | DOID:0112109
DI-05928 | Mitochondrial complex IV deficiency, nuclear type 3. | 619046 |  
DI-05929 | Mitochondrial complex IV deficiency, nuclear type 4. | 619048 |  
DI-05930 | Mitochondrial complex IV deficiency, nuclear type 7. | 619051 |  
DI-05931 | Mitochondrial complex IV deficiency, nuclear type 8. | 619052 |  
DI-05932 | Mitochondrial complex IV deficiency, nuclear type 10. | 619053 |  
DI-05933 | Mitochondrial complex IV deficiency, nuclear type 11. | 619054 |  
DI-05934 | Mitochondrial complex IV deficiency, nuclear type 12. | 619055 |  
DI-05935 | Mitochondrial complex IV deficiency, nuclear type 14. | 619058 |  
DI-05936 | Mitochondrial complex IV deficiency, nuclear type 15. | 619059 |  
DI-05937 | Mitochondrial complex IV deficiency, nuclear type 16. | 619060 |  
DI-05938 | Mitochondrial complex IV deficiency, nuclear type 17. | 619061 |  
DI-05939 | Mitochondrial complex IV deficiency, nuclear type 18. | 619062 |  
DI-05940 | Mitochondrial complex IV deficiency, nuclear type 19. | 619063 |  
DI-05941 | Mitochondrial complex IV deficiency, nuclear type 20. | 619064 |  
DI-05942 | Mitochondrial complex IV deficiency, nuclear type 21. | 619065 |  

If helpful, here are the DI defs:

CREATED: DI-05918
ID   Coenzyme Q10 deficiency, primary, 9.
AC   DI-05918
AR   COQ10D9.
DE   A form of coenzyme Q10 deficiency, an autosomal recessive disorder
DE   with variable manifestations consistent with 5 major phenotypes. The
DE   phenotypes include an encephalomyopathic form with seizures and
DE   ataxia; a multisystem infantile form with encephalopathy,
DE   cardiomyopathy and renal failure; a predominantly cerebellar form with
DE   ataxia and cerebellar atrophy; Leigh syndrome with growth retardation;
DE   and an isolated myopathic form. COQ10D9 patients show cerebellar
DE   ataxia with cerebellar atrophy. Additional features include
DE   generalized tonic-clonic seizures, and cognitive disability. Disease
DE   onset is in the first decade of life.
DR   MIM; 619028; phenotype.
DR   MedGen; CN283411.
DR   MeSH; D028361.
KW   KW-1274:Primary mitochondrial disease.

CREATED: DI-05920
ID   Vissers-Bodmer syndrome.
AC   DI-05920
AR   VIBOS.
DE   An autosomal dominant disorder characterized by global developmental
DE   delay, intellectual disability of varying degree, speech delay, motor
DE   delay, and hypotonia. Abnormal growth, and cerebral, skeletal, muscle
DE   and soft tissue abnormalities are frequently observed. Many patients
DE   have behavioral problems, including anxiety, obsessive compulsive
DE   disorder, autism spectrum disorder and attention-deficit hyperactivity
DE   disorder.
DR   MIM; 619033; phenotype.
DR   MedGen; CN283412.
DR   MeSH; D065886.
KW   KW-0991:Mental retardation.
KW   KW-1268:Autism spectrum disorder.

CREATED: DI-05922
ID   Neurodevelopmental disorder with progressive spasticity and brain white matter abnormalities.
AC   DI-05922
AR   NEDSWMA.
DE   An autosomal recessive neurodevelopmental disorder characterized by
DE   developmental delay manifesting in infancy, inability to walk
DE   independently, mild to severe intellectual disability, poor overall
DE   growth, progressive microcephaly, and axial hypotonia. Additional
DE   variable features include brainstem and cerebellar involvement,
DE   seizures, joint contractures, ocular disturbances, episodic
DE   respiratory failure, and facial dysmorphism.
DR   MIM; 619026; phenotype.
DR   MedGen; CN283413.
DR   MeSH; D065886.
KW   KW-0991:Mental retardation.
//

CREATED: DI-05923
ID   Spastic paraplegia 83, autosomal recessive.
AC   DI-05923
AR   SPG83.
DE   A form of spastic paraplegia, a neurodegenerative disorder
DE   characterized by a slow, gradual, progressive weakness and spasticity
DE   of the lower limbs. Rate of progression and the severity of symptoms
DE   are quite variable. Initial symptoms may include difficulty with
DE   balance, weakness and stiffness in the legs, muscle spasms, and
DE   dragging the toes when walking. In some forms of the disorder, bladder
DE   symptoms (such as incontinence) may appear, or the weakness and
DE   stiffness may spread to other parts of the body. SPG83 is
DE   characterized by juvenile onset of progressive lower limb spasticity
DE   resulting in gait instability.
DR   MIM; 619027; phenotype.
DR   MedGen; CN283414.
DR   MeSH; D015419.
KW   KW-0890:Hereditary spastic paraplegia.
//

CREATED: DI-05924
ID   Myopathy, epilepsy, and progressive cerebral atrophy.
AC   DI-05924
AR   MEPCA.
DE   An autosomal recessive disorder characterized by severe, early lethal
DE   neurodegeneration, myasthenic and myopathic features, progressive
DE   cerebral atrophy with myelination defects, and intractable epilepsy.
DR   MIM; 619036; phenotype.
DR   MedGen; CN292948.
DR   MeSH; D065886.
KW   KW-0523:Neurodegeneration.
KW   KW-0887:Epilepsy.
KW   KW-0991:Mental retardation.
//

CREATED: DI-05925
ID   Myopathy, myofibrillar, 10.
AC   DI-05925
AR   MFM10.
DE   A form of myofibrillar myopathy, a group of chronic neuromuscular
DE   disorders characterized at ultrastructural level by disintegration of
DE   the sarcomeric Z disk and myofibrils, and replacement of the normal
DE   myofibrillar markings by small dense granules, or larger hyaline
DE   masses, or amorphous material. MFM10 is an autosomal recessive
DE   disorder characterized by muscle pain, cramping, exercise fatigue, and
DE   progressive muscle rigidity.
DR   MIM; 619040; phenotype.
DR   MedGen; CN293343.
DR   MeSH; D020914.
KW   KW-0911:Desmin-related myopathy.
//

CREATED: DI-05926
ID   Spinal muscular atrophy, infantile, James type.
AC   DI-05926
AR   SMAJI.
DE   An autosomal dominant form of spinal muscular atrophy, a group of
DE   neuromuscular disorders characterized by degeneration of the anterior
DE   horn cells of the spinal cord, leading to symmetrical muscle weakness
DE   and atrophy. SMAJI is a severe disease characterized by hypotonia
DE   manifesting in the first weeks or months of life, delayed motor
DE   development, motor regression, and muscle weakness and atrophy
DE   primarily affecting distal muscles. Additional variable features
DE   include feeding difficulties, poor overall growth, foot deformities,
DE   kyphosis, hyperlordosis, scoliosis, vocal cord dysfunction, and
DE   respiratory insufficiency.
DR   MIM; 619042; phenotype.
DR   MedGen; CN293370.
DR   MeSH; D009134.
KW   KW-0523:Neurodegeneration.
//

CREATED: DI-05927
ID   Spermatogenic failure 44.
AC   DI-05927
AR   SPGF44.
DE   An autosomal recessive infertility disorder caused by spermatogenesis
DE   defects and characterized by the presence of acephalic spermatozoa in
DE   the semen of affected individuals.
DR   MIM; 619044; phenotype.
DR   MedGen; CN293344.
DR   MeSH; D007248.
//

CREATED: DI-05928
ID   Mitochondrial complex IV deficiency, nuclear type 3.
AC   DI-05928
AR   MC4DN3.
DE   An autosomal recessive mitochondrial disorder characterized by
DE   cytochrome c oxidase deficiency. Clinical features include muscle
DE   weakness, hypotonia, ataxia, ptosis, metabolic acidosis, poor feeding,
DE   delayed motor development, anemia, sensorineural hearing loss, and
DE   cardiomyopathy.
DR   MIM; 619046; phenotype.
DR   MedGen; CN293390.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05929
ID   Mitochondrial complex IV deficiency, nuclear type 4.
AC   DI-05929
AR   MC4DN4.
DE   An autosomal recessive mitochondrial disorder characterized by
DE   hypotonia, encephalopathy, metabolic acidosis, poor feeding,
DE   hepatomegaly, and hypertrophic cardiomyopathy in some patients. Death
DE   occurs in infancy. Patient tissues show decreased levels and activity
DE   of mitochondrial respiratory complex IV.
DR   MIM; 619048; phenotype.
DR   MedGen; CN293391.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05930
ID   Mitochondrial complex IV deficiency, nuclear type 7.
AC   DI-05930
AR   MC4DN7.
DE   An autosomal recessive mitochondrial disorder characterized by
DE   encephalomyopathy resulting in variable clinical manifestations.
DE   Features include muscle weakness, gait disturbances,
DE   neurodegeneration, cognitive decline, metabolic acidosis, feeding
DE   difficulties, poor overall growth, cortical visual impairment, and
DE   hypertrophic cardiomyopathy. Serum lactate levels are increased.
DE   Patient tissues show decreased levels and activity of mitochondrial
DE   respiratory complex IV.
DR   MIM; 619051; phenotype.
DR   MedGen; CN293392.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05931
ID   Mitochondrial complex IV deficiency, nuclear type 8.
AC   DI-05931
AR   MC4DN8.
DE   An autosomal recessive mitochondrial disorder characterized by slowly
DE   progressive cognitive dysfunction, dystonia or visual impairment that
DE   appear after an uneventful early childhood. Additional features
DE   include gait difficulties, spasticity, dysarthria, hypotonia, and
DE   variable intellectual disability. Brain imaging shows white matter
DE   abnormalities in the basal ganglia. Serum lactate levels are
DE   increased. Patient tissues show decreased levels and activity of
DE   mitochondrial respiratory complex IV.
DR   MIM; 619052; phenotype.
DR   MedGen; CN293393.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05932
ID   Mitochondrial complex IV deficiency, nuclear type 10.
AC   DI-05932
AR   MC4DN10.
DE   An autosomal recessive mitochondrial disorder that manifests with
DE   neonatal neurological and respiratory distress. Clinical features
DE   include facial dysmorphism, hypotelorism, microphthalmia, an ogival
DE   palate, and severe metabolic acidosis. Death occurs in early infancy.
DE   Autoptic examination reveals brain hypertrophy, diffuse alteration of
DE   white matter myelination, numerous cavities in the parieto-occipital
DE   region, brainstem and cerebellum, as well as hepatomegaly,
DE   hypertrophic cardiomyopathy, renal hypoplasia, and adrenal
DE   hyperplasia. Patient tissues show decreased levels and activity of
DE   mitochondrial respiratory complex IV.
DR   MIM; 619053; phenotype.
DR   MedGen; CN293394.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05933
ID   Mitochondrial complex IV deficiency, nuclear type 11.
AC   DI-05933
AR   MC4DN11.
DE   An autosomal recessive mitochondrial disorder with onset in childhood
DE   or adolescence. MC4DN11 is characterized by walking difficulties,
DE   cerebellar ataxia, dystonia, choreoathetotic movements and dysarthria.
DE   Additional features may include sensory axonal neuropathy, cerebellar
DE   atrophy, and mild speech delay. Cognitive function is normal. Serum
DE   lactate levels are increased. Patient tissues show decreased levels
DE   and activity of mitochondrial respiratory complex IV.
DR   MIM; 619054; phenotype.
DR   MedGen; CN293395.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05934
ID   Mitochondrial complex IV deficiency, nuclear type 12.
AC   DI-05934
AR   MC4DN12.
DE   An autosomal recessive mitochondrial disorder with onset in early
DE   infancy. MC4DN12 features include poor overall growth, metabolic
DE   acidosis, profoundly delayed psychomotor development, seizures,
DE   hypotonia, and brain abnormalities. Death may occur in the first years
DE   of life. Serum lactate and creatine kinase levels are increased.
DE   Patient tissues show decreased levels and activity of mitochondrial
DE   respiratory complex IV.
DR   MIM; 619055; phenotype.
DR   MedGen; CN293396.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05935
ID   Mitochondrial complex IV deficiency, nuclear type 14.
AC   DI-05935
AR   MC4DN14.
DE   An autosomal recessive mitochondrial disorder with onset in early
DE   childhood. MC4DN14 is characterized by developmental delay, cognitive
DE   impairment, motor delay, abnormal gait, sensorimotor demyelinating
DE   polyneuropathy, exercise intolerance, obesity, and short stature.
DE   Serum lactate levels are marginally increased. Patient tissues show
DE   decreased levels and activity of mitochondrial respiratory complex IV.
DR   MIM; 619058; phenotype.
DR   MedGen; CN293397.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05936
ID   Mitochondrial complex IV deficiency, nuclear type 15.
AC   DI-05936
AR   MC4DN15.
DE   An autosomal recessive mitochondrial disorder with onset in infancy.
DE   MC4DN15 is characterized by global developmental delay, poor feeding,
DE   metabolic acidosis, short stature, microcephaly, proximal muscle
DE   weakness, and distal spasticity. Additional manifestations include
DE   scoliosis, primary pulmonary hypertension, refractory seizures, and
DE   inability to walk. Serum and CSF lactate levels are increased. Patient
DE   tissues show decreased levels and activity of mitochondrial
DE   respiratory complex IV.
DR   MIM; 619059; phenotype.
DR   MedGen; CN293384.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05937
ID   Mitochondrial complex IV deficiency, nuclear type 16.
AC   DI-05937
AR   MC4DN16.
DE   An autosomal recessive mitochondrial disorder with onset in infancy
DE   and variable manifestations. MC4DN16 features include feeding
DE   difficulties, poor overall growth, short stature, microcephaly,
DE   developmental regression, severe hypotonia, and seizures. Cerebral and
DE   cerebellar atrophy, and abnormal lesions in the basal ganglia can be
DE   observed on brain imaging. Patient tissues show decreased levels and
DE   activity of mitochondrial respiratory complex IV.
DR   MIM; 619060; phenotype.
DR   MedGen; CN293385.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05938
ID   Mitochondrial complex IV deficiency, nuclear type 17.
AC   DI-05938
AR   MC4DN17.
DE   An autosomal recessive mitochondrial disorder with highly variable
DE   clinical manifestations and severity. Clinical features vary from
DE   acute neurometabolic decompensation in late infancy to subtle
DE   neurological signs presenting in adolescence. Encephalopathic episodes
DE   are characterized by acute loss of developmental milestones including
DE   ability to walk or sit, loss of speech, episodes with somnolence and
DE   seizure, and pyramidal signs rapidly evolving into spastic
DE   tetraparesis. The clinical course subsequently tends to stabilize and
DE   in several subjects marked recovery of neurological milestones is
DE   observed over time. Brain imaging shows a cavitating leukodystrophy,
DE   predominantly involving the posterior cerebral white matter and the
DE   corpus callosum in the acute stage, after which the abnormalities
DE   partially improve and then stabilize. Patient tissues show variably
DE   decreased levels and activity of mitochondrial respiratory complex IV.
DR   MIM; 619061; phenotype.
DR   MedGen; CN293386.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05939
ID   Mitochondrial complex IV deficiency, nuclear type 18.
AC   DI-05939
AR   MC4DN18.
DE   An autosomal recessive, muscle-specific, mitochondrial disorder with
DE   onset in infancy. MC4DN18 is characterized by hypotonia, limb and
DE   facial muscle weakness, and high arched palate. Some patients have
DE   respiratory insufficiency at birth and cardiomyopathy. Patient
DE   skeletal muscle shows decreased levels and activity of mitochondrial
DE   respiratory complex IV.
DR   MIM; 619062; phenotype.
DR   MedGen; CN293387.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05940
ID   Mitochondrial complex IV deficiency, nuclear type 19.
AC   DI-05940
AR   MC4DN19.
DE   An autosomal recessive mitochondrial disorder with onset in infancy or
DE   early childhood. MC4DN19 is characterized by global developmental
DE   delay, impaired intellectual development, developmental regression,
DE   loss of acquired motor and language skills, and motor dysfunction.
DE   Patient tissues show decreased levels and activity of mitochondrial
DE   respiratory complex IV.
DR   MIM; 619063; phenotype.
DR   MedGen; CN293388.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05941
ID   Mitochondrial complex IV deficiency, nuclear type 20.
AC   DI-05941
AR   MC4DN20.
DE   An autosomal recessive mitochondrial disorder with onset in early
DE   infancy. MC4DN20 is characterized by pulmonary arterial hypertension,
DE   poor feeding, failure to thrive, hypotonia, delayed development,
DE   increased serum lactate and metabolic acidosis. Death in infancy
DE   occurs due to cardiorespiratory failure. Patient tissues show variably
DE   decreased levels and activity of mitochondrial respiratory complex IV.
DR   MIM; 619064; phenotype.
DR   MedGen; CN293389.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.
//

CREATED: DI-05942
ID   Mitochondrial complex IV deficiency, nuclear type 21.
AC   DI-05942
AR   MC4DN21.
DE   An autosomal recessive mitochondrial disorder with onset in infancy.
DE   MC4DN21 is characterized by congenital lactic acidosis,
DE   encephalopathy, global developmental delay, delayed speech, motor
DE   dysfunction, dystonia, and spasticity. Ataxia, peripheral neuropathy,
DE   and seizures may also occur. Patient tissues show variably decreased
DE   levels and activity of mitochondrial respiratory complex IV.
DR   MIM; 619065; phenotype.
DR   MedGen; CN293398.
DR   MeSH; D017237.
KW   KW-1274:Primary mitochondrial disease.

**Comment by matentzn** [comment]
Hey @Antonialock 

I just eyeballed 10 of them and they all, or at least the majority, of these terms will show up in the next release!

**Comment by nicolevasilevsky** [comment]
Yes, these will be available in the next release - I plan to do it on Wed this week.

**Comment by Antonialock** [comment]
thanks!
