### ISSUE TITLE
Lesch-Nyhan syndrome and hypoxanthine-guanine phosphoribosyltransferase deficiency

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2363]
"Lesch-Nyhan syndrome" MONDO:0010298 is both a child of "hypoxanthine-guanine phosphoribosyltransferase deficiency" MONDO:0016088 and has "hypoxanthine-guanine phosphoribosyltransferase deficiency" as an exact synonym. 
Which relationship is correct?

**Comment by nicolevasilevsky** [comment]
I excluded the synonyms
