### ISSUE TITLE
Mondo has xrefs to deprecated DO classes

### ISSUE THREAD

**Issue by stuppie** [monarch-initiative/mondo#237]
I don't know how prevalent this is or if this is the only one (haven't looked)

Example:
[pestis minor](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0000238) has [DOID:0050068](http://www.ontobee.org/ontology/DOID?iri=http://purl.obolibrary.org/obo/DOID_0050068) (MONDO:equivalentTo), which is deprecated.

This particular one looks like it was merged into bubonic plague, as it has an alternative ID of DOID:0050068

**Comment by cmungall** [comment]
Some of the DOID merges seem odd, e.g merging Cushing syndrome into primary hyperaldosteronism http://purl.obolibrary.org/obo/DOID_446 -- we will be keeping these distinct
