### ISSUE TITLE
Spastic paraplegia 35/FAHN 

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2378]
I am trying to figure out if there are duplicate entries for spastic paraplegia 35/fatty acid hydroxylase-associated neurodegeneration or if these are indeed distinct disorders.

_MONDO:0012866- hereditary spastic paraplegia 35._ Cross references: OrphaNet 171629 (Which in turn points to OMIM 612319), OMIM 612319, UMLS C3496228 and SCTID:764688002 (Note: this SNOMEDCT PT maps to UMLS C4707091 ) Has exact SYN of "FAHN"

_MONDO:0017999- fatty acid hydroxylase-associated neurodegeneration_ Cross references: OrphaNet 329308 (which in turn points to OMIM 612319 and UMLS C3668943), GARD 10810. Has exact Syn of "FAHN"

Can @ahamosh and @Orphanet please weigh in on these two diseases/names? Thanks!

**Comment by nicolevasilevsky** [comment]
_MONDO:0012866- hereditary spastic paraplegia 35_
There is an 'exclude' tag on the FAHN synonyms (which I guess doesn't prevent the synonyms from showing up in OLS- @cmungall and @matentzn is there anything we could do about that? Has this been discussed before?) 
The exclude tag means the synonym should be removed from public release but maintained in the edit version as a record of external usage.

_MONDO:0017999- fatty acid hydroxylase-associated neurodegeneration_
OrphaNet 329308 has a 'narrow term maps to a broader term' annotation on the mapping to OMIM 612319, so I don't think Orphanet is trying to say these are equivalent.



cc @ana-rath-orphanet @annieolry

**Comment by ahamosh** [comment]
OMIM considers FAHN the most severe (and rare) end of the spectrum of Spastic Paraplegia 35.  We did not separate.  Not sure how you want to handle it.

**Comment by matentzn** [comment]
Can you put on Qc agenda, I think we should consider to sparql remove excluded synonyms from the release, but there might be a better way I don't know about!

**Comment by kanems** [comment]
Sorry to rehash old news, but would OMIM consider changing the "alternate name" of FAHN into an "included" term instead of an alternate if it doesn't warrant its own OMIM entry but the community otherwise views it is a clinically distinct presentation? @ahamosh ?

**Comment by nicolevasilevsky** [comment]
Speaking to Ada now - she said they are likely the same thing. She can look into it further if needed.

**Comment by nicolevasilevsky** [comment]
@kanems I don't think there is any action here for Mondo, so I will close this. Please feel free to reopen if you'd like to discuss further, thanks! :)
