### ISSUE TITLE
OMIM PS105400 for ALS on multiple entries?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2379]
OMIMPS:105400 for Amyotrophic lateral sclerosis is showing up on two MONDO terms:

MONDO:0004976 , amyotrophic lateral sclerosis
and
MONDO:0005144, familial amyotrophic lateral sclerosis

And the children ALS types appear to be split between these two terms.  Is this because some ALS forms are NOT familial? 
In at least one tree view familial ALS is a child of the ALS term (see attached)
![ALS_MONDOTree_2Dec2020](https://user-images.githubusercontent.com/71083858/100934349-a0ba6c00-34bc-11eb-92a6-a09551e3780a.png)

Thanks for any clarification you can provide on the placement of the ALS types under different parent terms and where the OMIM PS "best" fits.

**Comment by nicolevasilevsky** [comment]
OMIMPS:105400 is **_not_** equivalent to MONDO_0004976. This xref comes from DO.
OMIMPS:105400 is equivalent to MONDO_0005144.

Does this answer your question?

**Comment by nicolevasilevsky** [comment]
@kanems I am closing this, please reopen if you have further questions.
