### ISSUE TITLE
retinopathy vs retinal disease

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#238]
[MONDO:0005283](http://purl.obolibrary.org/obo/MONDO_0005283) ! retinopathy
we treat as equiv to any disease of the retina

In NCIT this is defined as "Any disease or disorder of the retina", yet it is classified as NCIT:C27610  ! Non-Neoplastic Retinal Disorder

Should retinopathy include neoplastic diseases?

**Comment by nicolevasilevsky** [comment]
Looks like NCIt have separate terms for retinopathy (Code C62601) and retinal disorder (Code C26875), so perhaps we should separate these terms too?

**Comment by cmungall** [comment]
but my point is that the distinction doesn't make sense according to the text defs

```
     is_a NCIT:C26875 ! Retinal Disorder [DEF: "An abnormal structure or function of the retina and its associated tissues."]
      is_a NCIT:C27610 ! Non-Neoplastic Retinal Disorder
       is_a NCIT:C62601 ! Retinopathy ***  [DEF: "Any disease or disorder of the retina."]
```

I believe that NCIT:C26875 should say something like "An abnormal __non-neoplastic__ structure or function of the retina and its associated tissues.", and ideally the label would say the same

Also not we do not follow NCIT in making non-neoplastic bins

**Comment by nicolevasilevsky** [comment]
I see - I will add a ticket on the NCIt tracker to suggest they update the text definition and the label.

**Comment by nicolevasilevsky** [comment]
I submitted the change request to NCIT. Is there any other action required? Should we remove the NCIT dbxef on MONDO:0005283?

**Comment by nicolevasilevsky** [comment]
NCIT already changed the def:
Thank you for your inquiry. We have changed the definition to:

Any non-neoplastic pathologic conditions of the retina, including non-neoplastic structural anomalies.

**Comment by nicolevasilevsky** [comment]
to do: change label to 'retinal disease' and make retinopathy a synonym
