### ISSUE TITLE
update pattern for infectious disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2391]
dependent on https://github.com/oborel/obo-relations/pull/412

https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/infectious_disease_by_agent.yaml
- [x] relation should be 'disease has infectious agent'

Next:
- [ ] need to update the logical definitions in Mondo for the infectious disease terms (@matentzn)

**Comment by matentzn** [comment]
We should probably do this only after RO had another release..

**Comment by nicolevasilevsky** [comment]
@matentzn do you know how often RO does a release?

**Comment by matentzn** [comment]
I check wether perhaps I can just run RO releases.

**Comment by nicolevasilevsky** [comment]
I think this is done, closing.
