### ISSUE TITLE
change label of hereditary fructose intolerance to Fructosemia – HFI

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#240]
A user requested that we change the label of MONDO_0009249 _hereditary fructose intolerance_ to _Fructosemia – HFI_

@cmungall I'll go ahead and do this on a pull request, unless there are any objections. I'll make _hereditary fructose intolerance_  a synonym

**Comment by cmungall** [comment]
I think it's important to consult with others here. For inborn errors of metabolism we should check with ORDO

**Comment by pnrobinson** [comment]
I think that hereditary fructose intolerance is the preferred name. To my knowledge, affecteds only get increased amounts of fructose in the blood (fructosemia) if they in fact ingest foods with fructose/sucrose, and so the label "hereditary fructose intolerance"  also "makes more sense" to me.

**Comment by nicolevasilevsky** [comment]
Thanks Peter! I'll close this ticket then.
