### ISSUE TITLE
reclassify chromosomal disorders 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2409]
Follow groupings in wikipedia, see table: https://en.wikipedia.org/wiki/Turner_syndrome

![image](https://user-images.githubusercontent.com/6722114/101184229-52fd4b00-3605-11eb-91b0-0425d818488d.png)

compare with:
is_a: MONDO:0001967 {source="DOID:3491", source="MESH:D014424", source="NCIT:C26900"} ! gonadal dysgenesis
is_a: MONDO:0015218 {source="Orphanet:881"} ! syndromic developmental defect of the eye
is_a: MONDO:0015620 {source="Orphanet:881"} ! syndromic urogenital tract malformation
is_a: MONDO:0017000 {source="Orphanet:881"} ! X chromosome number anomaly with female phenotype
is_a: MONDO:0017975 {source="MESH:D014424", source="Orphanet:881"} ! sex chromosome disorder of sex development
is_a: MONDO:0017978 {source="Orphanet:881"} ! syndrome with disorder of sex development of gynecological interest
is_a: MONDO:0018402 {source="Orphanet:881"} ! female infertility due to gonadal dysgenesis
is_a: MONDO:0019721 {source="Orphanet:881"} ! syndromic renal or urinary tract malformation
is_a: MONDO:0019852 {source="Orphanet:881"} ! inherited primary ovarian failure
is_a: MONDO:0020165 {source="Orphanet:881"} ! syndromic epicanthus

**Comment by sabrinatoro** [comment]
Closing this issue as the project is almost over, and the main reclassification has been reviewed
