### ISSUE TITLE
[Merge] 'phosphoribosylpyrophosphate synthetase deficiency'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2414]
**Mondo term (ID and Label)**
MONDO:0043176 ['phosphoribosylpyrophosphate synthetase deficiency'](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0043176)

**Reason for deprecation**
Duplicate

**Term to be merged with**
MONDO:0010395 ['phosphoribosylpyrophosphate synthetase superactivity'](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0010395)

@galyea-gard
I think these two terms in Mondo are the same, not sure why the 'deficiency' term was create as a distinct entity from the 'superactivity' term. I added hyperlinks to OLS so you can easily see them.

Thanks!

**Comment by galyea-gard** [comment]
Phosphoribosylpyrophosphate synthetase deficiency:  They are two different disorders; In GARD we currently have the phosphoribosylpyrophosphate synthetase superactivity (we had  phophoribosylpyrophosphate synthetase deficiency as a synonym but I fixed this issue). Missense mutations in PRPS1 are rare and may result in increase or decrease in PRS-I activity (PRS-I deficiency is VERY rare (only 12 families described) and includes  Arts syndrome (GARD 8756), X-linked Charcot-Marie Tooth 5 (OMIM 311070 – we only have the parent term for this one ), and X-linked non-syndromic sensorineural deafness (OMIM 304500 – we don’t have this on GARD).  Thank you! Gioconda

**Comment by nicolevasilevsky** [comment]
Thank you @galyea-gard, I'll close this.
