### ISSUE TITLE
Missing MONDO -> EFO xref for Bronchitis

### ISSUE THREAD

**Issue by darintay** [monarch-initiative/mondo#2416]
**Mondo term (ID and Label):**
MONDO_0003781 (Bronchitis)
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0003781

**Xref that should be fixed (ID and label):**
EFO_0009661 (Bronchitis)
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009661

**Other comments:**
Not an expert here, but the terms seem identical in both ontologies, so I'm assuming they should be matched.
EFO has an xref to the MONDO term here, but MONDO is missing the xref to EFO.

**Comment by nicolevasilevsky** [comment]
you are correct @darintay, thank you!

I fixed this on a PR, it will be available in the next release.
