### ISSUE TITLE
"Spondyloepiphyseal dysplasia" and "brachyolima" Maroteaux type

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2425]
Are 
brachyolmia, Maroteaux type (MONDO:0013360), https://www.omim.org/entry/613678 
and
spondyloepiphyseal dysplasia, Maroteaux type (MONDO:0008473) https://www.omim.org/entry/184095
truly distinct disorders? 

UMLS Metathesaurus equate them under C3159322, but I am not familiar enough with this topic to know which is correct.

**Comment by nicolevasilevsky** [comment]
@ahamosh could you comment? Thank you!

@kanems looks like they are distinct diseases in Orphanet too:
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=93302
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=263482

**Comment by ahamosh** [comment]
Also from Joanna:
I believe they are different.  The SNOMED has 2 numbers for them and
OrphaNet has 2 numbers.

184095:
"(SED) of Maroteaux for a form of spondyloepiphyseal dysplasia with
manifestations limited to the musculoskeletal system and with other
features distinguishing it from Morquio syndrome of any type
X-linked SED tarda, brachyolmia, and spondylometaphyseal dysplasia
of Kozlowski."

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh and Joanna!

@kanems I will close this but please feel free to reopen if more discussion is needed.
