### ISSUE TITLE
Sugarman "syndrome" vs. "brachydactyly"

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2427]
UMLS has merged "Sugarman syndrome" aka "OFD III" and "Sugarman brachydactyly" into one concept (C0406726), potentially following MeSH's similar treatment of these two concepts (C557817).

However, OMIM, GARD and OrphaNet treat them as distinct concepts:  OFDIII (MIM 258850; OrphaNet 2752; GARD 10518) and Sugarman brachydactyly (MIM 272150, OrphaNet 498602, GARD 5058).  From the OMIM phenotypic description, these appear to be distinct disorders, but the literature is limited. 

Can anyone provide further insight into whether these are distinct disorders?

**Comment by nicolevasilevsky** [comment]
@ahamosh could you comment from OMIM's perspective?
@galyea-gard could you comment from GARD's perspective?

Thank you!

**Comment by ahamosh** [comment]
This is from Joanna:
This looks like a UMLS computed conflation.  Brachydactyly is not OFD.
This is similar to the Maroteaux problem yesterday.  I'll let the UMLS
know.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh.
I'll close this, but feel free to reopen @kanems if you'd like to discuss further.

**Comment by galyea-gard** [comment]
Hi!  GARD will most likely retire Sugarman syndrome because there are not any new descriptions since 1982, but it still will be reviewed . Thanks, Gioconda

**Comment by nicolevasilevsky** [comment]
From Joanna at OMIM:
My contact at the UMLS is splitting the conflated Maroteaux and
Sugerman entities.  The problem started with MESH and she has put in a
request at MESH to fix it there also.
