### ISSUE TITLE
check that OMIMPS are xref'd on heritable forms of disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2436]
related to:
https://github.com/monarch-initiative/mondo/issues/2325

Alll OMIM phenotypic series are hereditary, so they should be xref'd on the hereditary form of the disease.

These kinds of cases should be easy to check for automatically. We'd auto add an axiom to all PSs to this effect, then the reasoner pipeline will alert us to everything needing attention

obo-sed.pl -r 'xref: OMIMPS.*equivalent' 's/name:/relationship: has_modifier MONDO:0021152 {source="TICKET"}\nname:/' mondo-edit.obo

**Comment by nicolevasilevsky** [comment]
I think this is done?
cc @matentzn

**Comment by matentzn** [comment]
Not sure. Need to check in next meeting!

**Comment by nicolevasilevsky** [comment]
wait until after next release

**Comment by nicolevasilevsky** [comment]
this is working!
