### ISSUE TITLE
MONDO:0016424 into  MONDO:0011660[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2438]
**Mondo term (ID and Label)**
MONDO:0016424 , progressive sensorineural hearing loss-hypertrophic cardiomyopathy syndrome

**Reason for deprecation**
The only active cross-ref on this term is Orphanet:228012, which points to https://omim.org/entry/606346 , which is already mapped to MONDO:0011660. (UMLS CN201381 is not an active identifier, as far as I can tell.)

**Term to be merged with**
MONDO:0011660, autosomal dominant nonsyndromic deafness 22

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
from Gioconda (GARD):
We have this under Deafness, autosomal dominant nonsyndromic sensorineural 22, however I don’t think that the first term should be included here even so that OMIM includes it because the whole point here is that the deafness is not syndromic

**Comment by ana-rath-orphanet** [comment]
Hello, I disagree with the obsoletion if this entry: two different entities are represented in OMIM  606346 (clearly stated in the page as an 'inclusion' term). This entity is a syndromic one, even though there are very few cases.

**Comment by nicolevasilevsky** [comment]
Thanks @ana-rath-orphanet!

@kanems I will close this, since we'll follow Orphanet's advise and not merge, but please reopen if further action is needed.
