### ISSUE TITLE
Clark-Baraitser syndrome OMIM Xref update

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2457]
**Mondo term (ID and Label):**
MONDO:0010372, Clark-Baraitser syndrome

**Xref that should be fixed (ID and label):**
OMIM 300602 now points to 617752.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
need to merge:
MONDO:0010372, Clark-Baraitser syndrome

with MONDO_0030914 'intellectual disability, autosomal dominant 49'

**Comment by nicolevasilevsky** [comment]
thanks @kanems!

**Comment by nicolevasilevsky** [comment]
From Gioconda (GARD):
This was a great finding! We have this one duplicated with  AD intellectual disability 49;  I will fix this issue ASAP.
