### ISSUE TITLE
[Open Targets] Add synonyms from Genomics England phenotypes

### ISSUE THREAD

**Issue by ireneisdoomed** [monarch-initiative/mondo#2461]
Hello,

we have identified 6 terms from one of our sources where the phenotype indicated at source is present for the Orphanet ID that we map but not for the MONDO ID. 

It would be great if these could be potentially imported as a synonym so that we can downstream benefit from their inclusion in EFO and have a better mapping.

Cross reference | Synonym to be added | MONDO ID | MONDO Label
-- | -- | -- | --
http://www.orpha.net/ORDO/Orphanet_528105 | "HELIX syndrome" | http://purl.obolibrary.org/obo/MONDO_0033939 | hypohidrosis-electrolyte imbalance-lacrimal gland dysfunction-ichthyosis-xerostomia syndrome
http://www.orpha.net/ORDO/Orphanet_536471 | "Spondylodysplastic EDS" | http://purl.obolibrary.org/obo/MONDO_0034021 | spondylodysplastic Ehlers-Danlos syndrome
http://www.orpha.net/ORDO/Orphanet_536516 | "Myopathic EDS" | http://purl.obolibrary.org/obo/MONDO_0034022 | myopathic Ehlers-Danlos syndrome
http://www.orpha.net/ORDO/Orphanet_536545 | "Kyphoscoliotic EDS", "EDS VI" | http://purl.obolibrary.org/obo/MONDO_0034024 | kyphoscoliotic Ehlers-Danlos syndrome
http://www.orpha.net/ORDO/Orphanet_566231 | "Resistance to thyroid hormone alpha" | http://purl.obolibrary.org/obo/MONDO_0034216 | resistance to thyroid hormone due to a mutation in thyroid hormone receptor alpha

ORCID id: https://orcid.org/0000-0002-2417-7324

Thank you very much.

**Comment by nicolevasilevsky** [comment]
@ireneisdoomed thanks for your request! It actually brings up a bigger issue, where I think some of these terms should be merged with other Mondo terms:


MONDO ID | MONDO Label | Term to merge with (Mondo ID) | (Term to merge with (Mondo label)
-- | -- | -- | --
http://purl.obolibrary.org/obo/MONDO_0033939 | hypohidrosis-electrolyte imbalance-lacrimal gland dysfunction-ichthyosis-xerostomia syndrome | MONDO_0060564 'helix syndrome'
http://purl.obolibrary.org/obo/MONDO_0034021 | spondylodysplastic Ehlers-Danlos syndrome | MONDO_0007526 | 'Ehlers-Danlos syndrome progeroid type'
http://purl.obolibrary.org/obo/MONDO_0034022 | myopathic Ehlers-Danlos syndrome | MONDO_0014655 | 'Bethlem myopathy 2'

**Comment by nicolevasilevsky** [comment]
Peter emailed:
I am not sure about kyphoscoliotic EDS, OMIM is listing two subforms and so we would probably need to not merge the grouping term with subform 1

**Comment by nicolevasilevsky** [comment]
From Gioconda (GARD):
**Myopathic EDS** -  For this one, OMIM linked to a wrong Orpha ID, however Myopathic EDS is one of the official EDS subytpes. (Note: Orphanet page was updated on 12/15): ORPHA:536516; We don’t have this subtype in GARD but I plan on add it.

**Kyphoscoliotic  Ehlers-Danlos syndrome** – The Kyphoscoliotic Ehlers-Danlos syndrome 1 is a subtype of Kyphoscoliotic Ehlers-Danlos syndrome

**Spondylodysplastic Ehlers-Danlos syndrome**: In the 2017 EDS nosology, the entity “EDS progeroid type” is no longer listed and B4GALT7 and B3GALT6-related linkeropathies were grouped as spEDS together with patients harboring SLC39A13 mutations. https://ojrd.biomedcentral.com/articles/10.1186/s13023-017-0704-3

**Comment by nicolevasilevsky** [comment]
@ireneisdoomed Sorry for the delay on following up on this, I hope to get to it soon. If it's high priority, please let me know.

**Comment by ana-rath-orphanet** [comment]
Comment from the obsoletions table received: Keep Myopathic Ehlers-Daanlos syndrome as the preferred term, as per the official classification? Bethlem myopathy type 2 is not an agreed term, and it leads to confusion. Thank you

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] on 'Ehlers-Danlos syndrome, kyphoscoliotic type 1', there is an xref to Orphanet:1900, remove MONDO:superClassOf, this should be equiv to.
- [ ] do the 3 mergers listed [here](https://github.com/monarch-initiative/mondo/issues/2461#issuecomment-744976177)

**Comment by nicolevasilevsky** [comment]
@ireneisdoomed I added all the synonyms you requested, these changes will be available in the next release (March)

**Comment by ireneisdoomed** [comment]
Thank you very much @nicolevasilevsky. I'm very glad this ticket has triggered many actions. Have a lovely day!
