### ISSUE TITLE
Fibrous dysplasia[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2462]
**Mondo term (ID and Label)**

MONDO:0016640, fibrous dysplasia of bone

**Reason for deprecation**
Appears to be same concept (slightly different Xrefs, but same overall concept) as MONDO:0000845, fibrous dysplasia

**Term to be merged with**
MONDO:0000845, fibrous dysplasia 
(SCTID 254145001  might be retired or merged with 10623005 ? I cannot find a record of that first SCTID.)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
From Gioconda (GARD):
We already have this one as fibrous dysplasia but kept “fibrous dysplasia of the bone” as a synonym
