### ISSUE TITLE
vitreoretinal degeneration MONDO:0020248 

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2474]
**Mondo term (ID and Label):**
MONDO:0020248  "Vitreoretinal degeneration"

**Xref that should be fixed (ID and label):**
Orphanet 98670  https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=98670 is obsolete.  

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
Thanks @kanems!

Are you on our Mondo users mailing list? If not, could I add you? Could you share your email? (I'll delete it on here once I get it).

Thanks for all your tickets, they have been incredibly helpful in improving Mondo. :)

**Comment by kanems** [comment]
Yes, Nicole, I am on the mailing list (I get your “obsoletion candidates” and monthly release emails, so I presume that’s the list you mean.)  I’m happy to contribute to improving the ontology and resource. 😊

**Comment by nicolevasilevsky** [comment]
@kanems Oh good! :) (I didn't check the list before I asked you, haha!)
