### ISSUE TITLE
PBAT, obsoleted, no replacement

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#2479]
could not find cvterm for MONDO:0014964 - maybe obsolete? encephalopathy_progressive_early_onset_with_brain_atrophy_and_thin_corpus_callosum

has been obsoleted.
This is the name of the disease  causal gene  TBCD
https://www.omim.org/entry/617193

what would the replacement be?

**Comment by nicolevasilevsky** [comment]
MONDO:0044646 'early-onset progressive diffuse brain atrophy-microcephaly-muscle weakness-optic atrophy syndrome'

is the replacement.
