### ISSUE TITLE
Rajab interstitial lung disease with brain calcifications, obsoleted

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#2480]
Rajab interstitial lung disease with brain calcifications (RILDBC1; 613658),
has been obsoleted with no replacement.

https://www.omim.org/entry/613658
causative gene is FARSB

**Comment by nicolevasilevsky** [comment]
@ValWood this is in Mondo:
MONDO_0100215 'Rajab interstitial lung disease with brain calcifications 1'

**Comment by ValWood** [comment]
That's odd. When I search Monarch don't find this term.

I also wanted to ask, is there any reason in these cases why terms can't be merged so that  we don't need to reannotate?

**Comment by nicolevasilevsky** [comment]
@ValWood you are right! I know Monarch is not in sync with Mondo, it's a bit behind, I'll report this on the Monarch tracker.

In this case MONDO_0013346 is replaced by MONDO:0100215, I don't know why this isn't displayed in Monarch. I'll report this to Monarch.
