### ISSUE TITLE
[NTR] MULTIPLE CONGENITAL ANOMALIES-HYPOTONIA-SEIZURES SYNDROME 4

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#2481]
MULTIPLE CONGENITAL ANOMALIES-HYPOTONIA-SEIZURES SYNDROME 4

for PIGQ
https://www.omim.org/entry/618548?search=MULTIPLE%20CONGENITAL%20ANOMALIES-HYPOTONIA-SEIZURES%20SYNDROME%204&highlight=%22anomaly%7Chypotonia%7Cseizure%22%20%28anomalieshypotoniaseizure%7C%20%28multiple%7Cmultiplicity%29%20%28syndrome%7Csyndromic%29%20%29%204%20congenital

https://www.omim.org/entry/605754#animalModel

**Comment by ValWood** [comment]
You have syndrome 2 for PIGA, should be siblings

**Comment by nicolevasilevsky** [comment]
what is the ID for syndrome 2 for PIGA?

this term already exists in Mondo as MONDO_0032808 'developmental and epileptic encephalopathy, 77', I added the synonym

**Comment by ValWood** [comment]
The PIGA  related disease is:
multiple congenital anomalies-hypotonia-seizures syndrome 2 (MONDO:0010466)
