### ISSUE TITLE
[NTR] X-linked recessive mitochondrial myopathy, lactic acidosis, cognitive impairment and autistic features

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#2482]
X-linked recessive mitochondrial myopathy, lactic acidosis, cognitive impairment and autistic features

BenincÃ¡ C, Zanette V, Brischigliaro M, Johnson M, Reyes A, Valle DAD, J Robinson A, Degiorgi A, Yeates A, Telles BA, Prudent J, Baruffini E, S F Santos ML, R de Souza RL, Fernandez-Vizarra E, J Whitworth A, Zeviani M. | Related Articles
-- | --
  | Mutation in the MICOS subunit gene APOO (MIC26) associated with an X-linked recessive mitochondrial myopathy, lactic acidosis, cognitive impairment and autistic features. |  
  | J Med Genet. 2020 May 21;. [Epub ahead of print] |  
  | PMID: 32439808 [PubMed - as supplied by publisher]

I have been checking for a while and this is not in OMIM yet, can it still be added to MONDO?
(I mailed OMIM today)

**Comment by nicolevasilevsky** [comment]
yes, we can add this! we'll coordinate with OMIM after they add it.
cc @ahamosh

**Comment by nicolevasilevsky** [comment]
Actually, looks like we already have this term:
MONDO_0100138 'X-linked recessive mitochondrial myopathy'

I'll add a synonym
