### ISSUE TITLE
Use gencc associations

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#2492]
TSV:

https://search.thegencc.org/download

 - [ ] make sure that everything in this subset is tagged. We will need to carefully coordinate any obsoletions if the ID is used by GENCC
 - [ ] check this against all axioms in the ontology
 - [ ] decide on strength/confidence threshold
 - [ ] consider tsv2owl (possibly via kgx) and include in release. but coordinate with dipper on object properties @kshefchek 

The TSV has some issues but I have reported to gencc

**Comment by matentzn** [comment]
This seems like we can close it now - we will solve this on Monarch KG level. Our current strategy is to rely purely on OMIM.
