### ISSUE TITLE
Obsolete 'unclassified' terms

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2494]
Action item:
obsolete these terms:

**Done (on PR):**
id |  label | consider
-- | -- | -- 
MONDO_0017957 | 'unclassified autoinflammatory syndrome' | 'autoinflammatory syndrome'
MONDO_0020241 | 'unclassified familial retinal dystrophy' | 'inherited retinal dystrophy'
MONDO_0019299 | 'unclassified genetic skin disorder' | 'skin disease'
MONDO_0015192 | 'unclassified intestinal pseudoobstruction' | 'chronic intestinal pseudoobstruction'
MONDO_0020315 | 'unclassified myelodysplastic syndrome' | 'refractory cytopenia with multilineage dysplasia'
MONDO_0020313 | 'unclassified myelodysplastic/myeloproliferative disease' | 'myelodysplastic/myeloproliferative disease'
MONDO_0020244 | 'unclassified primitive or secondary maculopathy' | 'genetic macular dystrophy'
MONDO_0006475 | 'unclassified renal cell carcinoma' | 'renal cell carcinoma'
MONDO_0016665 | 'unclassified vasculitis' | vasculitis
MONDO_0009654 | 'mucopolysaccharidoses, unclassified types' | mucopolysaccharidosis

_updated 12/01/21 NV_

---

**Mondo term (ID and Label)**
MONDO:0008156/autosomal dominant osteopetrosis 2

**Suggested revision of logical definition**
I believe this should be removed from the classes of 

    unclassified primitive or secondary maculopathy and 
   hereditary optic neuropathy

**Your nano-attribution (ORCID)** 0000-0001-7451-446
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by cmungall** [comment]
Agreed and we should go further and obsolete similar grouping classes that
have 'unclassified' and disjunctions in the name

**Comment by sabrinatoro** [comment]
@maglott 
I'm Sabrina, a new curator who recently joined the Mondo team. 
We will address your issue as soon as possible. Thank you for your patience. 
If this is a high priority, please let me know and we can prioritize it. Thank you!
