### ISSUE TITLE
split: skin basal cell carcinoma

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#2495]
**Term to split:**

MONDO:0005341

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 

keep MONDO:0005341 but make a separate concept for the more general basal cell carcinoma

Follow NCIT and DPs

https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C3784

![image](https://user-images.githubusercontent.com/50745/103709797-3fc4fe80-4f68-11eb-8522-2752198803a8.png)

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonynms that end in "1", "2", etc. should move to subclass.

 - synonyms: case by case
 - xrefs: case by case

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

I am doing this in behalf of the Terminology & Ontology Ecosystem Workstream (call happening now), not sure how to attribute

**Comment by cmungall** [comment]
Also check

```
id: MONDO:0021607
name: eyelid seborrheic keratosis
def: "A seborrheic keratosis that involves the eyelid." [MONDO:patterns/location]
synonym: "basal cell papilloma of eyelid" EXACT [NCIT:C4356]
synonym: "basal cell papilloma of the eyelid" EXACT [NCIT:C4356]
synonym: "eyelid basal cell papilloma" EXACT [NCIT:C4356]
synonym: "eyelid seborrheic keratosis" EXACT [MONDO:patterns/location, NCIT:C4356]
synonym: "seborrheic keratosis of eyelid" EXACT [NCIT:C4356]
synonym: "seborrheic keratosis of the eyelid" EXACT [NCIT:C4356]
xref: NCIT:C4356 {source="MONDO:equivalentTo"}
xref: SCTID:231826004 {source="MONDO:equivalentTo"}
xref: UMLS:C0339109 {source="MONDO:equivalentTo", source="NCIT:C4356"}
is_a: MONDO:0008420 {source="MONDO:Redundant", source="MONDOLEX:0021607", source="NCIT:C4356"} ! seborrheic keratosis
intersection_of: MONDO:0008420 ! seborrheic keratosis
intersection_of: disease_has_location UBERON:0001711 ! eyelid
```

**Comment by cmungall** [comment]
Note:

![image](https://user-images.githubusercontent.com/50745/103713663-c6320e00-4f71-11eb-846c-f2625de22061.png)

one-child, bad-smell

when we try and replicate this in mondo we infer these are equivalent, as basal cells Ns are epithelial Ns. @nicolevasilevsky can you open an NCIT ticket?

**Comment by nicolevasilevsky** [comment]
created ticket in NCIT, closing here.
