### ISSUE TITLE
Errors on  bilateral striopallidodentate calcinosis MONDO:0008947

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2511]
This MONDO ID is supposed to represent the parent class of multiple types of basal ganglia degeneration with calcification, but currently lists the gene-specific subtype 1 as synonyms (this is a child of this term)

Synonyms to remove: 
basal ganglia calcification, idiopathic, type 1
idiopathic basal ganglia calcification 1

Xref errors: SCTID 110997000  maps to UMLS CUI: C0393590, Fahr's syndrome/disease, which, per the orphanet definition at the top of the page, is an erroneous alternate name.

**Comment by nicolevasilevsky** [comment]
thanks @kanems I'll work on this asap :)

**Comment by nicolevasilevsky** [comment]
good catch @kanems. You submit really great issues, thanks for your work to improve Mondo.
