### ISSUE TITLE
MONDO:0020802 is obsolete with subclass

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#2515]
**Mondo term (ID Label)**
MONDO:0020802 (obsolete_basal cell cancer)

**Bug/Typo/Error description**
This obsolete term still has the subclass of "basal cell carcinoma", which was picked up as an error in the EFO release build.

![image](https://user-images.githubusercontent.com/36990116/104894729-f95e9f00-596c-11eb-98fb-d6c4f62bff6c.png)

**Comment by nicolevasilevsky** [comment]
Thanks @zoependlington I'll look at this asap.
