### ISSUE TITLE
Add OWL definitions for chromosomal abnormalities

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#252]
E.g deletion of 7q36

can use NCIT chromosome band ontology + SO for deletions, duplications etc

**Comment by mellybelly** [comment]
@mbrush can you comment on this RE the little CHROMO ontology work?

**Comment by mbrush** [comment]
To support locating  genes/variants on chromosomal bands, we translated the UCSC bands file here into a t-box (class-level) ontological representation called Monochrom (Monarch Chromosome Ontology).
 
The ttl/owl file directly produced by dipper is [here](https://data.monarchinitiative.org/ttl/monochrom.ttl), but a version where I have merged it with GENO so the Monochrom classes are presented in clearer context is [here](https://github.com/monarch-initiative/GENO-ontology/blob/develop/docs/geno-monochrom.owl).  If you open this merged file in Protege, you can 
see Monochrom  content by browsing under chromosome, chromosomal arm, chromosomal region, chromosomal band. 

To get a sense for the partonomic relationships Mnochrom captures, I’d suggest starting at the class for the chromosome "**chr10 (Human)**" and following the has_subsequence axioms to:
 - the chromosomal arm "**chr10p(Human)**"
 - the chromosomal region "**chr10p1(Human)**"
 - and then the chromosomal bands of increasing precision from "**chr10p11(Human)**" to "**chr10p11.2(Human)**" to "**chr10p11.22(Human)**".
 
Species coverage in the latest monochrom.ttl seem only to include human, mouse, and rat  for  anything other than chromosomes. But the [Dipper code](https://github.com/monarch-initiative/dipper/blob/master/dipper/sources/UCSCBands.py) looks like several other species could be generated from the UCSC data.
 
At present, classes in Monochrom are minimally used in Dipper data - and I cant recall the driving use cases/data  sets for creating it (@kshefchek do you?). It as some issues to work out, but I think with a little work it could be improved/formalized and documented for release as a public resource, if we think this would be useful.

**Comment by cmungall** [comment]
This is great, let's get this registered with OBO. 3 species is a great start.

I'd recommend making a new github repo with the OSK and checking the files in there (or we could serve directly off the dipper output but I think I prefer keeping in GH)

**Comment by cmungall** [comment]
We can also use the GH repo for things like curated mappings to NCIT (and to Phil Lord's ontology?)

**Comment by cmungall** [comment]
It looks like we have genes and loci associated with CHR PURLs, e.g. 
https://scigraph-data.monarchinitiative.org/scigraph/graph/neighbors/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHR_9606chr10q22.3?depth=1&blankNodes=false&direction=BOTH&entail=false

E.g.

    

    <owl:NamedIndividual rdf:about="http://www.ncbi.nlm.nih.gov/gene/404686">
        <rdf:type rdf:resource="http://purl.obolibrary.org/obo/SO_0001500"/>
        <faldo:location>
            <rdf:Description rdf:nodeID="_:genid64409">
                <rdf:type rdf:resource="http://biohackathon.org/resource/faldo#Region"/>
                <faldo:begin>
                    <rdf:Description rdf:nodeID="_:genid64410">
                        <rdf:type rdf:resource="http://biohackathon.org/resource/faldo#FuzzyPosition"/>
                        <faldo:reference rdf:resource="https://monarchinitiative.org/MONARCH_GRCh38chr10"/>
                        <faldo:position rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">75900000</faldo:position>
                    </rdf:Description>
                </faldo:begin>
                <faldo:end>
                    <rdf:Description rdf:nodeID="_:genid64411">
                        <rdf:type rdf:resource="http://biohackathon.org/resource/faldo#FuzzyPosition"/>
                        <faldo:reference rdf:resource="https://monarchinitiative.org/MONARCH_GRCh38chr10"/>
                        <faldo:position rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">80300000</faldo:position>
                    </rdf:Description>
                </faldo:end>
            </rdf:Description>
        </faldo:location>
        <obo:RO_0002200 rdf:resource="http://purl.obolibrary.org/obo/OMIM_608078"/>
        <obo:RO_0002525 rdf:resource="http://purl.obolibrary.org/obo/CHR_9606chr10q22.3"/>
        <dc:description>between D10S1677 and D10S1753</dc:description>
    </owl:NamedIndividual>

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/discussions/2584

**Comment by sabrinatoro** [comment]
This project is done
