### ISSUE TITLE
48, XXYY syndrome (MONDO:0015028) incorrect exactmatch MeSH ID:D007713

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#2520]
I do not think MeSH:D007713 should be an exact match to 48, XXYY syndrome (MONDO:0015028).
Rather MeSH:D007713 should be an exact match to Klinefelter syndrome (MONDO:0006823)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems good catch.

@Orphanet @annieolry @ana-rath-orphanet the incorrect xfef came from Orphanet, FYI.
