### ISSUE TITLE
[Obsolete]MONDO:0008220, pepsinogen 3, group 1

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2521]
**Mondo term (ID and Label)**
MONDO:0008220, pepsinogen 3, group 1

**Reason for deprecation**

not a disease
**Suggested term to consider**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @maglott I'll send an email to the list to get community input.
