### ISSUE TITLE
[NTR] Paroxysmal familial ventricular fibrillation 

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2524]
**Preferred term label:**
Paroxysmal familial ventricular fibrillation 

**Synonyms**
Ventricular fibrillation, paroxysmal familial
Paroxysmal familial ventricular fibrillation (disorder)
Idiopathic ventricular fibrillation, non Brugada type (ORPHA:228140)

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
_No definition on UMLS C0340493, probably best to use ORPHANET's definition:_
A rare, genetic, cardiac rhythm disease characterized by ventricular fibrillation in the absence of any structural or functional heart disease, or known repolarization abnormalities. The presence of J waves is associated with a higher risk of nocturnal ventricular fibrillation events and a higher risk of recurrence.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Ventricular fibrillation https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0000190&viewMode=PreferredRoots&siblings=false 

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
MONDO:0011376  (Type 1 PFV.Fib.) **NOTE**: The "non Brugada type" name on this term should be moved to the new parent term requested here, as ORPHANET uses this name to refer to both OMIM 603829 (VF 1) and 612956 (VF 2)
MONDO:0013063 (type 2 PFV.Fib.)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems! I'll work on this asap

**Comment by nicolevasilevsky** [comment]
@kanems do you have an ORCID?
https://orcid.org/

**Comment by kanems** [comment]
Yes, but I am always too lazy to go look it up when I submit tickets 😃
0000-0001-5493-2602

**Comment by mellybelly** [comment]
@nicolevasilevsky perhaps we can come up with a workflow for frequent fliers so that they don't need to supply ORCIDS with every ticket?

**Comment by kanems** [comment]
I edited my GitHub profile to include my ORCID weblink (I don’t have a website, so it was easy enough to plug that in there) not sure if there is a way to pull info from that part of my profile..?

**Comment by nicolevasilevsky** [comment]
@kanems - that works, I can grab your ORCID from your profile going forward, thanks!
