### ISSUE TITLE
MONDO:0000865 congenital fiber-type disproportion

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2534]
The only X-ref on this entry in MONDO is DOID:0080102 (MONDO:equivalentTo)
Looking at that reference over on DiseaseOntology.org it cites 

> Xrefs | OMIM:255310
> Synonyms | CFTD [EXACT]

So I think this entry should be merged with MONDO:0009711 "congenital fiber-type disproportion myopathy"
Also NCIT C120046 has Preferred term of Congenital Fiber-Type Disproportion and syn. of Congenital Fiber-Type Disproportion Myopathy.

**Comment by nicolevasilevsky** [comment]
@kanems I agree. I'll email the users list.

Obsolete:
MONDO:0000865 'congenital fiber-type disproportion'

Term replaced by:
MONDO:0009711 'congenital fiber-type disproportion myopathy'
