### ISSUE TITLE
rules assigning XRefs to Orphanet

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2535]
If an Orphanet id, like https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=98810, maps to multiple MIM numbers, should that Orphanet id be an equivalent XRef to record specific to only 1 MIM number? 

In other words, should MONDO:0007326 have an exact reference to orphanet 98810?
Not sure how many cases there are like this, but NCBI keeps stumbling across cases and if there is going to be a general solution, we won't keep creating record-specific tickets.

Thanks.

**Comment by nicolevasilevsky** [comment]
This is a really good question @maglott. I'll look into this further and get back to you.

**Comment by nicolevasilevsky** [comment]
Immediate to do:
- [ ]  MONDO_0012629 'paroxysmal nonkinesigenic dyskinesia 2' should not be  a subclass of MONDO_0007326 'paroxysmal nonkinesigenic dyskinesia 1'

**Comment by sabrinatoro** [comment]
Hello @maglott 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
