### ISSUE TITLE
obsoletion of rare-X terms

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#254]
Currently we have many rare-X terms. The majority of these are axiomatized using the [rare](https://github.com/monarch-initiative/mondo/blob/master/src/patterns/rare.yaml) or [rare_genetic](https://github.com/monarch-initiative/mondo/blob/master/src/patterns/rare_genetic.yaml) DPs.

I propose these are obsoleted. 

This can be done with no loss of information by rewiring every reference to `rare-X` onto `X` (using OWL definition axioms) and downpropagating the differentium (has-modifier some rare) to subclasses (including axiom annotation to indicate source). This procedure is also known as T-Box unfolding.

The `has-modifier some rare` axioms may in future be replaced by more accurate quantitative prevalence axioms.

**Comment by cmungall** [comment]
cc @zoependlington - no timeline on this yet but wanted to loop you in well in advance

**Comment by zoependlington** [comment]
Thanks for the heads up @cmungall!
