### ISSUE TITLE
[NTR] Shrinking lung syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#2541]
**Preferred term label:**
shrinking lung syndrome

**Synonyms**
shrinking of the lung [broad]
vanishing lung syndrome [exact]
small lungs [related]

**Definition (free text, please give PubMed ID)**
A rare pulmonary complication of an underlying autoimmune disorder that is reported in association with systemic lupus erythematosus (SLE). Reduced lung volumes result in restrictive ventilatory defect and a preserved carbon monoxide transfer coefficient.  
Source: PMID:24836585

**Comment:** Chest x-ray often shows small but clear lungs. It is mostly presented in combination with diaphragmatic elevation and occasional basal atelectasis

**Parent term**
MONDO_0005275 'lung disease'

**Your nano-attribution (ORCID)**
lmu: chrapp, @mgriese, @kknoflach

Transferred form HPO tracker, please see

https://github.com/obophenotype/human-phenotype-ontology/issues/6437

**Comment by mgriese** [comment]
I had already commented in HPO that the terms are not synonyms, but different entities:

A)
Vanishing Lung (VLS) is also referred to as idiopathic giant bullous emphysema

Definition from "An Idiopathic Bullous Emphysema Mimicking Pneumothorax. Cureus 12(8): e9596. doi:10.7759/cureus.9596"
...... a rare manifestation of chronic obstructive pulmonary disease (COPD). Middle-aged tobacco smokers, younger marijuana users, and those with alpha-1-antitrypsin deficiency may especially be affected. The clinical and radiographic findings of VLS may initially be misinterpreted as spontaneous pneumothorax. High-resolution CT is the diagnostic imaging modality of choice in these patients and can help to differentiate VLS from pneumothorax. Such imaging also helps guide appropriate management. Management of VLS ranges from a conservative to a surgical approach depending upon patients’ comorbidities and candidacy for surgical resection. We present a case of a 64-year-old man with frequent hospitalizations for COPD exacerbation admitted with worsening shortness of breath and was found to have giant bullae mimicking a pneumothorax on the initial presentation.

is completely different from

B)
Shrinking lung syndrome
Definition and expalnation from PMID: 21686610
SLS, coined by Hoffbrand and Beck in 1965, is a rare pulmonary manifestation of SLE.1 The pathophysiology of SLS is unclear; a myopathic process affecting the diaphragm or intercostal muscles is thought to be the primary abnormality.2 Exercise intolerance over weeks to months is the common mode of presentation and is seen months to years after SLE is diagnosed. The respiratory dysfunction appears to be independent of the clinical course, duration and lupus antibodies (ANA and anti-DNA).3 Characteristic diagnostic findings include elevated diaphragms on imaging and restrictive lung volumes on pulmonary function tests.2 The absence of other pathological conditions is evidenced in most reports by normal V/Q scans, bronchoscopy and lung biopsies. Prognosis is generally good and most patients improve on increasing the dose of steroids aimed at the subclinical respiratory myositis-like process.3

**Comment by nicolevasilevsky** [comment]
thank you @mgriese! We'll make sure that this is added correctly.

**Comment by nicolevasilevsky** [comment]
@chrapp @kknoflach

could you please provide your ORCID and we'll add it to this term.
