### ISSUE TITLE
familial hypoaldosteronism

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2542]
**Mondo term (ID and Label):**
familial hypoaldosteronism/MONDO:0018541

**Xref that should be fixed (ID and label):**

https://www.omim.org/phenotypicSeries/PS103900

This should be removed from familial hypoaldosteronism and added to familial hyperaldosteronism MONDO:0016525
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
 0000-0001-7451-4467

**Other comments:**

**Comment by nicolevasilevsky** [comment]
thanks Donna, good catch!
