### ISSUE TITLE
Epilepsy, idiopathic generalized and  OMIM's cross references

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2543]
**Mondo term (ID and Label):**
MONDO:0010918, EIG1 references OMIM https://omim.org/entry/600669 which is named EIG and has an included title of EIG1
MONDO:0005579, EIG references https://omim.org/phenotypicSeries/PS600669, the phenotypic serices

**Xref that should be fixed (ID and label):**
I don't know what should be done, but NCBI has always honored the titles. Thus if the OMIM phenotypic series and the OMIM record have the same name, we make an exception and use both xrefs on the same label.  We have also make a distinction between included titles and the title of the record, and have not reported the MIM number for the included title.
So for now, we will keep PS600669 and 600669 as Xrefs for Epilepsy, idiopathic generalized and no xref from MIM for EIG1, but could be persuaded differently in the interest of consistency.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
I'll look into this asap :)

**Comment by sabrinatoro** [comment]
Hello @maglott 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
this is similar to: https://github.com/monarch-initiative/mondo/issues/1535
