### ISSUE TITLE
Rolandic epilepsy MONDO:0007295

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2545]
Rolandic epilepsy MONDO:0007295- what concept is trying to be captured here?
Current X-refs to UMLS and other terms are a wee-bit confusing (UMLS:C0376532 | UMLS:C2363129 | UMLS:CN200685)

1. Delete the CN200685 UMLS code (not active in MedGen, not sure where this identifier came from)
2.  Do you want this entry to be the generic parent term for all forms of "RE" or the "benign RE" term? 

-  You have UMLS CUIs for  Epilepsy, Rolandic (C0376532) which UMLS has as a parent term for multiple versions of Rolandic Epilepsy, including "benign Rolandic epilepsy" (UMLS C2363129).
-  The orphaNet term you cite (1945) points to two different OMIM terms (117100  & 245570), suggesting this term should have children that represent the 2 OMIM terms, at a minimum (unless OMIM believes they may be equivalent?)  
- The NCI (NCIT:C116538 ) and SNOMED_CT (44145005) x-refs here point to the "benign Rolandic epilepsy" term in UMLS. 

 Suggestion: Split this term into: 

- [ ] Rolandic Epilepsy (with the OrphaNet Xref pointing to multiple forms of RE and UMLS: C0376532) as a parent term

and make child(ren) term(s):

- [ ] Benign RE (OMIM 117100, UMLS C2363129), and maybe also 
- [ ] Epilepsy, rolandic with paroxysmal exercise-induced dystonia and writer's cramp" (UMLS C1842531 , OMIM 608105, ORPHA:163727)
- [ ] Rolandic Epilepsy, Mental Retardation, and Speech Dyspraxia, X-Linked" (UMLS:C1845070, OMIM:300643; ?ORPHA:163721?). 

Not sure if OMIM would put 245570 in this same hierarchy, but this is handled (at least partially) by UMLS to be a child of RE (based on syn of ROLANDIC EPILEPSY, MENTAL RETARDATION, AND SPEECH DYSPRAXIA), OrphaNet covers this OMIM term with ORPHA:163721.

**Comment by nicolevasilevsky** [comment]
Thanks for this ticket @kanems.
I'd like to ask for expert feedback before I proceed - @ahamosh @ana-rath-orphanet, would you mind reviewing these suggested changes and letting us know if you have any feedback?
Thank you!

**Comment by nicolevasilevsky** [comment]
> Delete the CN200685 UMLS code (not active in MedGen, not sure where this identifier came from)

I annotated this as MONDO:equivalentObsolete:
Used for cases where we have exact 1:1 matches between a live class in Mondo and an obsolete class in the source ontology.We want to avoid making an equivalence axiom (MONDO:equivalentTo) here. (I wanted to preserve the provenance though, hence I did not delete it).

**Comment by nicolevasilevsky** [comment]
From OMIM:
 The only entry that is solely Rolandic
epilepsy is 117100.  It is a clinical finding in the other entries
mentioned in the ticket and a finding in many more entries than the
ones mentioned.

Some patients with Rolandic epilepsy have been reported with GRIN2A
mutations, but it is often called atypical or is associated with other
clinical features.

**Comment by maglott** [comment]
Adding to this discussion:  https://omim.org/entry/117100 reports BENIGN EPILEPSY OF CHILDHOOD WITH CENTROTEMPORAL SPIKES; BECTS as an alternate name for  CENTRALOPATHIC EPILEPSY and as a an included title for https://www.omim.org/entry/245570.  Where does BECTS belong?

**Comment by sabrinatoro** [comment]
Hello @maglott 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
@kanems currently, BENIGN EPILEPSY OF CHILDHOOD WITH CENTROTEMPORAL SPIKES; BECTS are synonyms for 'rolandic epilepsy'.

I'm unsure what the action items are for this ticket - would you mind revisiting?

Thank you!

**Comment by kanems** [comment]
From what I am seeing on @ahamosh's comment and search of some other sources, it would seem that the concept on MONDO:0007295 is really the childhood onset 'benign Rolandic epilepsy" that is an isolated clinical presentation  (and according to https://www.ncbi.nlm.nih.gov/books/NBK534845/ and https://en.wikipedia.org/wiki/Rolandic_epilepsy, usually resolves on its own). But Ada's comment indicates that 'Rolandic epilepsy' (potentially defined as seizures originating in the Rolandic fissure?) can be a phenotype/finding in other disorders. 
**So are the names or RE and BRE truly equivalent?** 
Wikipedia, StatPearls and OrphaNet seem to support the equivalence, but UMLS (following MeSH it seems) has split these into two concepts (RE as a parent concept and BRE as ONE child, with Epilepsy, rolandic with paroxysmal exercise-induced dystonia and writer's cramp; and Rolandic Epilepsy, Mental Retardation, And Speech Dyspraxia, Autosomal Dominant; and Rolandic Epilepsy, Mental Retardation, and Speech Dyspraxia, X-Linked as siblings to BRE. Noting that UMLS also has children to the BRE term: Benign childhood epilepsy with centrotemporal spikes, non-refractory; Benign childhood epilepsy with centrotemporal spikes, refractory; Rolandic epilepsy, speech dyspraxia syndrome; Status epilepticus in benign Rolandic epilepsy) NCI Thesaurus doesn't have 'rolandic epilepsy' at all, only the BRE concept. 
Thus, trying to map the Mondo term hinges on whether the community agrees these should be **treated as synonyms** and the UMLS term relationships need to be reviewed **OR** if Mondo agrees that the 'finding' or general classification of rolandic epilepsy isn't the primary concept on their term and may be a useful concept to **keep distinct.** 
Also noting that at least some of the epilepsy community has a different preferred name entirely: https://www.epilepsy.com/learn/types-epilepsy-syndromes/childhood-epilepsy-centrotemporal-spikes-aka-benign-rolandic-epilepsy _"The official modern name is “childhood epilepsy with centrotemporal spikes” or CECTS. Yet, many people still just use the term benign rolandic epilepsy to refer to this syndrome."_

Also, the related question for OMIM: 
BENIGN EPILEPSY OF CHILDHOOD WITH CENTROTEMPORAL SPIKES, INCLUDED; BECTS, INCLUDED is on https://omim.org/entry/245570
and 
BENIGN EPILEPSY OF CHILDHOOD WITH CENTROTEMPORAL SPIKES; BECTS is an alt name on https://omim.org/entry/117100 
Hence @maglott 's question of "where does this belong?" I will submit this separately with OMIM via their website as well as clarifying the questions on this ticket.

**Comment by kanems** [comment]
Joanna from OMIM's reply to my website submission:

> FESD (245570) is a complex phenotype with several possible clinical manifestations (incl. BECTS) and is due to mutations in GRIN2A.  We have removed BECTS as an included title in 245570, as it is more appropriately discussed in the text of 245570 and is an alternate title for centralopathic epilepsy (117100).

**Comment by nicolevasilevsky** [comment]
I emailed Ada and Ingo on 01/19/21. @kanems based on what you said above, these seem like they should be two separate classes but let me see if I can get some expert opinions. :)

**Comment by nicolevasilevsky** [comment]
@kanems, from Ingo (an epilepsy expert):

Hi Nicole, 
neither of these suggestions!

The more modern term is childhood epilepsy with centrotemporal spikes and it's classified as a defined epilepsy syndrome. 

Here is a link how this is officially used in the epilepsy classifications:  https://epilepsydiagnosis.org/syndrome/ects-overview.html

**Comment by nicolevasilevsky** [comment]
@kanems I renamed this term to childhood epilepsy with centrotemporal spikes
