### ISSUE TITLE
MONDO:0007245 neurofibromatosis type 6

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2546]
**Mondo term (ID Label)**
MONDO:0007245 neurofibromatosis type 6

**Bug/Typo/Error description**
multiple typos in the synonyms and the definition, probably related to the display of the e with accent:  "multiple cafC)-au-lait syndrome"

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
thanks @kanems, there were a lot of typos! I think it's a Protege problem.
