### ISSUE TITLE
[NTR] Overgrowth syndrome and/or cerebral malformations due to abnormalities in MTOR pathway genes

### ISSUE THREAD

**Issue by abbe-Lai** [monarch-initiative/mondo#2547]
**Preferred term label:**
Overgrowth syndrome and/or cerebral malformations due to abnormalities in MTOR pathway genes

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
The disease caused by mosaic gain-of-function (GoF) several genes in the MTOR pathway (MTOR, PIK3CA, PIK3R2 and AKT3) are functionally the same despite significant phenotypic variability. These GoF variants result in overgrowth due to an over-activation of key genes in this pathway (PMID: 27860216). The phenotypic variability is generally attributed to the mosaic fraction and affected tissue types. For example, macrocephaly is noted if the variant is identified in the brain, but non symmetric overgrowth of that limb is noted when the variant is only present in the affected limb. The pathologies of the affected tissue often reveal similar characteristics such as cellular overgrowth. However, this is not always the case especially with focal cortical dysplasia. At times the characteristics pathologies are not present in the tissue but sampling biases are an issue. FCD resections often involve a very small area and so a very small amount of tissue is available for pathology and it is not guaranteed that lesional tissue is sent. Therefore, having a single disease term which can encompass the phenotypic variability yet provide a unifying molecular diagnosis name makes sense given the common functional mechanism. PMID: 22729224, PMID: 31441589, PMID: 22729223, PMID: 30349109

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

Disease or Disorder
Congenital abnormality
Developmental defect during embryogenesis 
overgrowth/obesity syndrome 

AND 

Disease or Disorder
Congenital abnormality
Developmental defect during embryogenesis 
Central Nervous system malformation

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

megalencephaly-polymicrogyria-postaxial polydactyly-hydrocephalus syndrome MONDO:0019375
megalencephaly-capillary malformation-polymicrogyria syndrome MONDO:0011240
macrocephaly-intellectual disability-neurodevelopmental disorder-small thorax syndrome MONDO:0014716
isolated focal cortical dysplasia MONDO:0019009
hemimegalencephaly MONDO:0020492

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
Brain Malformation Curation Expert Panel

**Comment by nicolevasilevsky** [comment]
Thanks @abbe-Lai I'll work on this asap

**Comment by nicolevasilevsky** [comment]
@abbe-Lai is CCND2 included in the MTOR pathway? This disease ('megalencephaly-polymicrogyria-polydactyly-hydrocephalus syndrome 3') would be a child of this proposed new term.

Also TSC1 and TSC2, these genes would be classified under this proposed new term (see https://omim.org/entry/607341).

Thank you for checking!

**Comment by abbe-Lai** [comment]
Hello,

Hello CCND2 most definitely would be appropriate for this term. MPPH3 would be the child term as well. However, for TSC1 and TSC2 this would likely be just one of the branches for these genes since they have other risks like cancer associated with TS.

We have not curated these genes yet though so before we make a finalized decision we will plan to curate these genes first? Would that be okay?

Best,
Abbe Lai, MS, CGC
Licensed Genetic Counselor
Coordinator, Brain Development and Genetics Clinic
Research Coordinator, Walsh Laboratory
Abbe.lai@childrens.harvard.edu<mailto:Abbe.lai@childrens.harvard.edu>
617-919-4371 | fax 617-919-2300 www.walshlab.org<http://www.walshlab.org/>

**Comment by nicolevasilevsky** [comment]
Hi @abbe-Lai - of course, take all the time you need. Please let me know when you are ready to proceed.

**Comment by abbe-Lai** [comment]
Hello Nicole,

We discussed this at our meeting today.

This disease term does apply to CCND2.

For TSC1 and TSC2 we felt that one of the branches for the tree could be this term. Given there are known cortical malformations in some of these patients and hemimegalencephaly has been seen for these cases in the mosaic state it makes sense.

best,
Abbe Lai, MS, CGC
Licensed Genetic Counselor
Coordinator, Brain Development and Genetics Clinic
Research Coordinator, Walsh Laboratory
Abbe.lai@childrens.harvard.edu<mailto:Abbe.lai@childrens.harvard.edu>
617-919-4371 | fax 617-919-2300 www.walshlab.org<http://www.walshlab.org/>

**Comment by nicolevasilevsky** [comment]
thanks! I'll work on this asap

**Comment by nicolevasilevsky** [comment]
@abbe-Lai I'm not totally sure if I follow. The hierarchy you proposed is displayed below

![image](https://user-images.githubusercontent.com/6722114/108949656-aafe8900-7619-11eb-8049-9fb74a7eeeb3.png)

'isolated focal cortical dysplasia type II' is equivalent to OMIM:607341, which includes mutations in MTOR and TSC1 and TSC2.

Is this okay?

**Comment by nicolevasilevsky** [comment]
@abbe-Lai I'm happy to have a call if that is easier!

**Comment by abbe-Lai** [comment]
Hello Nicole,

My apologies I completely missed this email. We do want isolated FCD do be under this term as well. We would not want to remove the association from MTOR TSC1 and TSC2 though. Is it okay to have this as a child term but still have it associated with those genes?

Best,
Abbe Lai

From: Nicole Vasilevsky ***@***.***>
Reply-To: monarch-initiative/mondo ***@***.***>
Date: Tuesday, February 23, 2021 at 11:59 PM
To: monarch-initiative/mondo ***@***.***>
Cc: "Lai, Abbe" ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] [NTR] Overgrowth syndrome and/or cerebral malformations due to abnormalities in MTOR pathway genes (#2547) [EXTERNAL]

* External Email - Caution *



@abbe-Lai<https://urldefense.com/v3/__https:/github.com/abbe-Lai__;!!NZvER7FxgEiBAiR_!4EQ5cv6ktjwZQtS3F-lyzYyjWSUoiq6gFKyez2YxBYmUpab1frLVnqyYKT1aWUCBbnniic9unw$> I'm happy to have a call if that is easier!

**Comment by nicolevasilevsky** [comment]
Thankss @abbe-Lai. I haven't had a chance to look at this closely yet, but I will do asap. :)

**Comment by abbe-Lai** [comment]
Hello Nichole,

I just wanted to follow up on this chain and see if there has been any updates on this?

Was there something you are missing from me?

Best,
Abbe Lai

From: Nicole Vasilevsky ***@***.***>
Reply-To: monarch-initiative/mondo ***@***.***>
Date: Friday, March 26, 2021 at 8:40 PM
To: monarch-initiative/mondo ***@***.***>
Cc: "Lai, Abbe" ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] [NTR] Overgrowth syndrome and/or cerebral malformations due to abnormalities in MTOR pathway genes (#2547) [EXTERNAL]

* External Email - Caution *



Thankss @abbe-Lai<https://urldefense.com/v3/__https:/github.com/abbe-Lai__;!!NZvER7FxgEiBAiR_!6UGiNLKMY4MPqvSP3RVJBSzQFhUMY7rL3JPFamIwLkemv4uLXp0upROiYGkLHMwmXvtQI9KsUQ$>. I haven't had a chance to look at this closely yet, but I will do asap. :)

**Comment by nicolevasilevsky** [comment]
Hi @abbe-Lai My apologies for the delay. I haven't had a chance to look at this yet but I will move it to the top of my priority list and try to get this in for the next release.

I don't think I'm waiting on you, I need to review this ticket again and will follow up with any questions, should they arise.

Thanks so much for your patience! :)

**Comment by nicolevasilevsky** [comment]
@abbe-Lai - I just looked at this. If I am understanding correctly, this new term and hierarchy are correct, yes?

![image](https://user-images.githubusercontent.com/6722114/118735530-7b64b480-b7f5-11eb-9994-5da33e82e13f.png)

Let me know if any other changes are needed, if not, I'll merge in these changes and they will be available in the next release at the end of the month/begnning of next month.

**Comment by abbe-Lai** [comment]
Hello,

That hierarchy looks good. What is the term that this one is under though? I do not see that on the image, is it congenital malformations?

Best,
Abbe Lai

From: Nicole Vasilevsky ***@***.***>
Reply-To: monarch-initiative/mondo ***@***.***>
Date: Tuesday, May 18, 2021 at 7:25 PM
To: monarch-initiative/mondo ***@***.***>
Cc: "Lai, Abbe" ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] [NTR] Overgrowth syndrome and/or cerebral malformations due to abnormalities in MTOR pathway genes (#2547) [EXTERNAL]

* External Email - Caution *



@abbe-Lai<https://urldefense.com/v3/__https:/github.com/abbe-Lai__;!!NZvER7FxgEiBAiR_!_PyqqvCZ1Z2pRJAk0kg2Vf2dwy-sMXZ-BKTk68QsSQN1AEbJCyWdMPbipACn3-JyK2uaJqLRJQ$> - I just looked at this. If I am understanding correctly, this new term and hierarchy are correct, yes?

[Image removed by sender. image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/6722114/118735530-7b64b480-b7f5-11eb-9994-5da33e82e13f.png__;!!NZvER7FxgEiBAiR_!_PyqqvCZ1Z2pRJAk0kg2Vf2dwy-sMXZ-BKTk68QsSQN1AEbJCyWdMPbipACn3-JyK2ueVXxFRQ$>

Let me know if any other changes are needed, if not, I'll merge in these changes and they will be available in the next release at the end of the month/begnning of next month.

**Comment by nicolevasilevsky** [comment]
Hi @abbe-Lai - this term has 4 parents, per your request above:
![image](https://user-images.githubusercontent.com/6722114/118835420-d50dc300-b877-11eb-94da-fe6454f4bbc4.png)

I'll go ahead and merge this in, but I can still make additional changes if needed before the release. Thank you so much for all your input and patience. :)

**Comment by abbe-Lai** [comment]
Hello,

That is perfect! Thank you so much.

Best,
Abbe Lai

On May 19, 2021, at 10:58, Nicole Vasilevsky ***@***.***> wrote:

﻿
* External Email - Caution *



Closed #2547<https://urldefense.com/v3/__https://github.com/monarch-initiative/mondo/issues/2547__;!!NZvER7FxgEiBAiR_!_DP_RcBndqCR0_Tl_n6O_p3CeDumPobo0lGUxsjG9WQ_VLLAqLIHmKhzzCl8ALeJ9QDAVPpdwQ$> via #2712<https://urldefense.com/v3/__https://github.com/monarch-initiative/mondo/pull/2712__;!!NZvER7FxgEiBAiR_!_DP_RcBndqCR0_Tl_n6O_p3CeDumPobo0lGUxsjG9WQ_VLLAqLIHmKhzzCl8ALeJ9QBv5wDzQg$>.

**Comment by abbe-Lai** [comment]
Hello Nichole,

I just wanted to check in and see if the Mondo term has been made for these genes yet?

Best,
Abbe Lai

From: Nicole Vasilevsky ***@***.***>
Reply-To: monarch-initiative/mondo ***@***.***>
Date: Wednesday, May 19, 2021 at 10:58 AM
To: monarch-initiative/mondo ***@***.***>
Cc: "Lai, Abbe" ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] [NTR] Overgrowth syndrome and/or cerebral malformations due to abnormalities in MTOR pathway genes (#2547) [EXTERNAL]

* External Email - Caution *



Closed #2547<https://urldefense.com/v3/__https:/github.com/monarch-initiative/mondo/issues/2547__;!!NZvER7FxgEiBAiR_!_DP_RcBndqCR0_Tl_n6O_p3CeDumPobo0lGUxsjG9WQ_VLLAqLIHmKhzzCl8ALeJ9QDAVPpdwQ$> via #2712<https://urldefense.com/v3/__https:/github.com/monarch-initiative/mondo/pull/2712__;!!NZvER7FxgEiBAiR_!_DP_RcBndqCR0_Tl_n6O_p3CeDumPobo0lGUxsjG9WQ_VLLAqLIHmKhzzCl8ALeJ9QBv5wDzQg$>.

**Comment by nicolevasilevsky** [comment]
Hi @abbe-Lai is this the term you are inquiring about:
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100283

Or was there something else needed?

Thanks!

**Comment by abbe-Lai** [comment]
That was the term!

Thank you so much. I was not able to find it.

Best,
Abbe lai

From: Nicole Vasilevsky ***@***.***>
Reply-To: monarch-initiative/mondo ***@***.***>
Date: Wednesday, June 16, 2021 at 12:04 AM
To: monarch-initiative/mondo ***@***.***>
Cc: "Lai, Abbe" ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] [NTR] Overgrowth syndrome and/or cerebral malformations due to abnormalities in MTOR pathway genes (#2547) [EXTERNAL]

* External Email - Caution *



Hi @abbe-Lai<https://urldefense.com/v3/__https:/github.com/abbe-Lai__;!!NZvER7FxgEiBAiR_!4LtoUr5Ps-EtK50U9jGViBKEg8xo3gMcneOFdKvcBMPdX8Ah1dI1K_cV7b2avq7mOwowpZYyZw$> is this the term you are inquiring about:
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100283<https://urldefense.com/v3/__https:/www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http*3A*2F*2Fpurl.obolibrary.org*2Fobo*2FMONDO_0100283__;JSUlJSU!!NZvER7FxgEiBAiR_!4LtoUr5Ps-EtK50U9jGViBKEg8xo3gMcneOFdKvcBMPdX8Ah1dI1K_cV7b2avq7mOwqI8kW2sA$>

Or was there something else needed?

Thanks!

**Comment by nicolevasilevsky** [comment]
Great!
