### ISSUE TITLE
Roberts-SC phocomelia syndrome/ESCO2

### ISSUE THREAD

**Issue by mbalzotti** [monarch-initiative/mondo#2553]
**Preferred gene-related syndrome label**
Roberts-SC phocomelia syndrome

**Synonyms**
Roberts syndrome
SC phocomelia syndrome

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Roberts syndrome (MONDO:0009997)

**Definition**
Any Roberts syndrome or SC phocomelia in which the cause of the disease is a mutation in the ESCO2 gene.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID:18411254

**Children terms (if applicable)** 

**Your nano-attribution (ORCID) or URL for a working group**

**Comment by mbalzotti** [comment]
@nicolevasilevsky This request is coming from the ClinGen Syndromic Disorders GCEP. We were hoping to merge Roberts syndrome with SC phocomelia syndrome as Roberts-SC phocomelia syndrome. Currently, SC phocomelia syndrome (MONDO:0010009) is organized under Roberts syndrome (MONDO:0009997) as a mild variant of Roberts syndrome. Please don't hesitate to reach out to me for any additional information. Thank you so much.

**Comment by nicolevasilevsky** [comment]
@mbalzotti There is an exact synonym on SC phocomelia syndrome that is Roberts-SC phocomelia syndrome (see [NCIT](https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&version=20.11e&code=C4681&ns=ncit&type=properties&key=null&b=1&n=0&vse=null)). 

I'm not sure I understand how your proposed term is different?

Thanks!

**Comment by mbalzotti** [comment]
@nicolevasilevsky - I believe the GCEP thinks that having a single entry with the blended name would be better than having two entries (Roberts syndrome - MONDO:0009997 and SC phocomelia syndrome - MONDO:0010009), even though they are synonymous, because the blended name, Roberts-SC phocomelia syndrome, would make it clear in future publications that the two disease entities are synonymous.

**Comment by nicolevasilevsky** [comment]
@mbalzotti I am unsure of the best approach here for Mondo, I need to ask @cmungall for advise.

Note:
Mondo currently has two separate classes. But both of these classes have an exact synonym of Roberts-SC phocomelia syndrome.
It's problematic that there are duplicate exact synonyms on both terms.

**Comment by nicolevasilevsky** [comment]
@ahamosh can we run this by you? This is our proposed solution:

create a grouping class: 
New term: Roberts-SC phocomelia syndrome
children:
-MONDO_0009997 'Roberts syndrome' (OMIM:268300)
-MONDO_0010009 'SC phocomelia syndrome' (OMIM:269000)

(as siblings)

per Mondo call 2021-02-19
cc @pnrobinson @cmungall

**Comment by nicolevasilevsky** [comment]
note to self - consider making a design pattern for this

**Comment by ahamosh** [comment]
Hi All,  Sorry for the delay. OMIM will call this Roberts SC phocomelia syndrome and combine the entries.  I will get the number back to you shortly (it will be merged into one of the existing entries).    Although the outcome for this query, making a parent with two children as siblings is the way that I would deal with many of the requests coming from ClinGen, but let's continue to discuss on a case by case (each one seems to be unique!)

**Comment by ahamosh** [comment]
FYI we will combine these 2 in 268300.
Thanks!

**Comment by nicolevasilevsky** [comment]
Great, thank you @ahamosh. I'll do the same in Mondo.
