### ISSUE TITLE
MONDO:0007522 Ehlers-Danlos syndrome, classic type

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2558]
**Mondo term (ID and Label):**
MONDO:0007522 Ehlers-Danlos syndrome, classic type

**Xref that should be fixed (ID and label):**
OMIM:130000 (Orphanet:287)

The OrphaNet page (287) points to TWO OMIM entries 130000 & 130010

So this term, as shown in MONDO, is actually the parent concept for both EDS Classic type 1 and type 2 and there isn't a specific OMIM PS# for classic EDS types (just the PS for all EDS types). So OMIM:130000 should be on MONDO:0019567.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
@kanems I agree, I'll fix this.

I wonder if we should obsolete MONDO_0007522 'Ehlers-Danlos syndrome, classic type', it seems this has been split into classic type 1 and 2 in OMIM ([type 1 ](https://omim.org/entry/130000)and [type 2](https://omim.org/entry/130010)).

@ahamosh @annieolry/ @ana-rath-orphanet / @Orphanet  @galyea what do you think?

**Comment by nicolevasilevsky** [comment]
although it looks like Orphanet obsoleted type 1, so maybe it's best to keep the grouping class to stay aligned with Orphanet?

**Comment by ahamosh** [comment]
Ok, my read of this is EDS 1 is now EDS, classic type.  OMIM has made EDS, classic 1 and classic 2 to distinguish COL5A1 and COL5A2. There is no clinical distinction between the two, just a split for molecular basis.

**Comment by ana-rath-orphanet** [comment]
Hello, Orphanet follows the international consensus classification of EDS https://doi.org/10.1002/ajmg.c.31552. Accordingly, Classical EDS (cEDS) is the single recognized entity, including  COL5A1, COL5A2 and COL1A1 cases.

**Comment by galyea-gard** [comment]
I agree. OMIM tends to have subtypes if the molecular basis is different but it is a single recognized entity.  Thanks! Gioconda

**Comment by nicolevasilevsky** [comment]
Thanks all! Appreciate your comments
