### ISSUE TITLE
split term: Waldenstrom macroglobulinemia

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2562]
**Term to split:**
MONDO:0007926 Waldenstrom macroglobulinemia
**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
Waldenstrom macroglobulinemia 
MACROGLOBULINEMIA, WALDENSTROM, SUSCEPTIBILITY TO, 1; WM1 (new term, make as a child to WM, sibling to WM2)

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonynms that end in "1", "2", etc. should move to subclass.
WM1 should have OMIM:153600 X-ref  (remove from Waldenstrom macroglobulinemia) and UMLS:C1835192 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Hi @kanems We are planning to discuss how to address terms like this that combine the disease and susceptibility to the disease, we have a meeting scheduled in a few weeks, so I'm going to put this on hold until after we meet and come up with a plan. 

Thanks for reporting this!

**Comment by kanems** [comment]
@nicolevasilevsky Any updates on this potential split?

**Comment by nicolevasilevsky** [comment]
Hi @kanems - On our call the other week, we weren't able to fully finish the conversation and decide how to address issues like this but I agree with your proposal to split these terms.
I'll do my best to get this in for the next release in early March. Thanks!

Summarizing the action plan below:

### We currently have:

MONDO_0007926 'Waldenstrom macroglobulinemia' ([OMIM:153600](https://omim.org/entry/153600), [ORPHA:33226](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=33226))
-MONDO_0012491 WM2 ([OMIM:610430](https://omim.org/entry/610430))

### Proposed change:

[new ID]: 'Waldenstrom macroglobulinemia' ([ORPHA:33226](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=33226))
-[new term]: macroglobulinemia, Waldenstrom, 1 [OMIM:153600](https://omim.org/entry/153600)
-MONDO_0012491 macroglobulinemia, Waldenstrom, 2 ([OMIM:610430](https://omim.org/entry/610430))

_(note, I will include the 'susceptibility to' synonyms from the OMIM records, as well as the other synonyms noted)_

and I will obsolete MONDO_0007926 'Waldenstrom macroglobulinemia' 

cc @cmungall and @ahamosh Let me know if you have any objections, thanks!
