### ISSUE TITLE
MONDO:0009710 myotonia congenita 

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2575]
Clarification request and some clean up needed.

It appears this term is meant to be the generic parent term to the AD and AR forms of myotonia congenita (NOT to be confused with “congential myotonia”) 

- [x] Syns are incorrect. Anything specific to “Thomsen” or “autosomal dominant form” should be on the AD form. “Thomsen and Becker disease” is the Orpha614 name, is an acceptable syn for “myotonia congenita” 

**X-ref problems:**
 - [ ] _MAYBE_ OMIM:255300 should not be on this term? it is a clinical description OMIM entry with no known etiology (as far as I can tell)  It could be a separate term under “congenital myopathy” with it’s own syn of BATTEN-TURNER CONGENITAL MYOPATHY but would X-ref to UMLS C0270960 “congenital myopathy (disorder)” Maybe move it to MONDO:0019952 ? 

- [x] SCTID 57938005 is “congential myotonia, autosomal dominant form” and probably belongs on MONDO:0008055 “myotonia congenita, autosomal dominant” 
- [x] Should probably replace with SCTID  726051002 “myotonia congentia” (I am opening a separate ticket with UMLS to get this moved to the right CUI)

- [x] MESH D009224 maps to many places/alt names including “Myotonia congenita”/ “Thomsens disease”/”generalized myotonia of Thomsen”/ “becker generalized myotonia” and I don’t know how useful it is to have this on any MONDO term as an exact match. 

OrphaNet 614 seems to be correct, as it refs OMIM 160800 (Myotonia Congenital, AD) and OMIM 255700 (Myotonia congenita, autosomal recessive) 
	Suggestion for OrphaNet (I'm not sure how to send this to OrphaNet direct, can we tag someone to look at this?): update UMLS CUIs to OrphaNet 614 also refs C2936781 (generalized myotonia of Thomsen) and C0751360 “becker generalized myotonia” aka Myotonia congentia AR. OR just use the one: C0027127 (which may be updated to clearly be the parent term for both AR and AD MC forms, if UMLS will make the change in the X-refs that I am requesting)

ONE UMLS CUI from the OrphaNet X-ref (UMLS:C0027127)  appears to be the current “best’ match for the parent MC concept, but UMLS has some redundant/criss-crossed terms/citations as well, so there seems to be a lot of confusion all around about these terms, I will follow up with UMLS independently.

@ana-rath-orphanet @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
> MAYBE OMIM:255300 should not be on this term? it is a clinical description OMIM entry with no known etiology (as far as I can tell) It could be a separate term under “congenital myopathy” with it’s own syn of BATTEN-TURNER CONGENITAL MYOPATHY but would X-ref to UMLS C0270960 “congenital myopathy (disorder)” Maybe move it to MONDO:0019952 ?

I'm not sure about this. My inclination is OMIM:255300 should be an equivalent xref on MONDO:0019952 'congenital myopathy'.

cc @ahamosh

**Comment by nicolevasilevsky** [comment]
from OMIM:
Carol has changed this to BATTEN-TURNER CONGENITAL MYOPATHY.  The
general "MYOPATHY, CONGENITAL" has been removed from the entry.

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
These terms should be split:
**New term 1:**
Label: Thomsen and Becker disease
syn: myotonia congenita
xrefs: 
Orphanet:614
DOID:2106
GARD:0012301
ICD10:G71.1
ICD10:G71.12
ICD9:359.22
MedDRA:10028655
MedDRA:10043461
MESH:D009224
NCIT:C84912
OMIM:160800
....
Keep all the existing xrefs as is except OMIM:255300

**New term 2:** 
Label: Batten-Turner congenital myopathy
xref: OMIM:255300
