### ISSUE TITLE
MONDO:0012455 Kleefstra syndrome

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2581]
**Mondo term (ID and Label):**
MONDO:0012455 
Kleefstra syndrome

**Xref that should be fixed (ID and label):**

- UMLS:C0795833 This CUI links to a term called KLEEFSTRA SYNDROME 1
Replacement UMLS concept: C4551771 "Kleefstra syndrome" (which is the parent for the "1" type)

- ORPHA:261494 points a term that has the generic name of "Kleefstra syndrome" but links only to the OMIM page and UMLS CUI for K.S. 1, suggest moving this OrphaNet concept to MONDO:0027407

The NCIT:C129976; MESH:C563043; and  SCTID:724207001 X-refs also map to the UMLS CUI for Kleefstra synd. 1 as they have synonyms for the 9q deletion. THe GARD concept GARD: 8672 also uses the 9q deletion terms as synonyms.  Also suggest moving them to the Type 1 child term. 
I know this sort of 'depletes' the parent term of X-refs, but it does clarify that this is a clinical description, agnostic of underlying molecular cause. As it current is represented in MONDO, it suggests all Kleeftra subtypes are associated with chr. 9q genetic variation, which is not the case for type 2. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
> ORPHA:261494 points a term that has the generic name of "Kleefstra syndrome" but links only to the OMIM page and UMLS CUI for K.S. 1, suggest moving this OrphaNet concept to MONDO:0027407

Since the orphanet record is for the generic class, I'd prefer to keep this xref in Mondo. We can ask Orphanet to revise their xref to OMIM, and xref to the phenotypic series instead: https://omim.org/entry/610253
cc @ana-rath-orphanet @Orphanet

**Comment by nicolevasilevsky** [comment]
thanks @kanems!
