### ISSUE TITLE
[Relabel] Remove "Hypermethioninemia due to" from disease entity

### ISSUE THREAD

**Issue by RedRiver1816** [monarch-initiative/mondo#2587]
**Mondo term (ID and Label):**
Hypermethioninemia due to adenosine kinase deficiency; MONDO:0013676

**Suggested new label:**
Adenosine kinase deficiency OR ADK deficiency

**Your nano-attribution (ORCID)**
Aminoacidopathy Expert Panel (https://www.clinicalgenome.org/affiliation/40011/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Although there are very few cases of ADK deficiency, there are more recognized phenotypes observed in these probands than the hypermethioninemia. Developmental delay, liver involvement, hypotonia, and dysmorphic features are all associated with this disease entity (PMIDs: 30477030, 33309011). Therefore, the naming should be reflective of the full spectrum of the disorder and the published literature.

**Comment by maglott** [comment]
I am concerned about defining what a Mondo ID represents.  I failed to speak up when gyrate atrophy was renamed to be Ornithine aminotransferase deficiency.  In this case, a relabeling will broaden the concept represented by the ID.  Seems if we want a general concept, a new record should be created for it.  Created a new node, not redefine an existing one. Just my opinion, of course.

**Comment by nicolevasilevsky** [comment]
Hi @RedRiver1816 thanks for the request, I will look at this more closely.

@maglott very good point, let me look into this further.

**Comment by nicolevasilevsky** [comment]
Looking at this - I agree with @maglott, we should obsolete this term and create a new term called 'adenosine kinase deficiency'.

I'll email the Mondo users list to make sure there are no objections.

cc @ana-rath-orphanet

**Comment by nicolevasilevsky** [comment]
@RedRiver1816 for now, I can create a new class called adenosine kinase deficiency

**Comment by nicolevasilevsky** [comment]
@RedRiver1816 
**is this text def okay:**

A rare inborn error of metabolism characterized by persistent hypermethioninemia with increased levels of S-adenosylmethionine and S-adenosylhomocysteine which manifests with encephalopathy, severe global developmental delay, mild to severe liver dysfunction, hypotonia and facial dysmorphism (most significant is frontal bossing, macrocephaly, hypertelorism and depressed nasal bridge). Epileptic seizures, hypoglycemia and/or cardiac defects (pulmonary stenosis, atrial and/or ventricular septal defect, coarctation of the aorta) may be associated. Clinical picture may range from neurological symptoms only to multi-organ involvement.

**And should the parents be:**
'neurometabolic disease'
'autosomal recessive non-syndromic intellectual disability'
'disorder of methionine catabolism'
'inborn disorder of methionine cycle and sulfur amino acid metabolism'

**Comment by RedRiver1816** [comment]
@nicolevasilevsky That all looks great! Let me know if you need any more info to finalize things.

**Comment by galyea-gard** [comment]
Hi!  We don't have this condition in GARD.  As we do not name diseases I would probably use as main term the name "Adenosine kinase deficiency" as per my review in Pubmed and include as synonyms the names that Orphanet (note that this was recently updated) and OMIM use which reflect the biochemical defect affecting methionine metabolism,

**Comment by nicolevasilevsky** [comment]
@RedRiver1816 This is all set, thanks! It will be available in the next release.
