### ISSUE TITLE
autosomal dominant polycystic kidney disease (MONDO:0004691) incorrect exactMatch UMLS CN119611 (not found)

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#2596]
Current:
autosomal dominant polycystic kidney disease (MONDO:0004691) has exactMatch UMLS CN119611 (unknown? I am not sure if this is a true UMLS, as I can't find an explanation to that title and the CN prefix is unusual?).
However, I suggest: UMLS CUI: C0085413 is currently a closematch but this is ADPKD and should be an exactmatch for autosomal dominant polycystic kidney disease (MONDO:0004691).
(UMLS CUI: C0022680 is correctly assigned close match as this is PKD)

**Comment by maglott** [comment]
This seems to be a specific aspect of 'CUI' that should be removed. MedGen currently reports https://www.ncbi.nlm.nih.gov/medgen/C0085413 for MONDO:0004691.  I'll send another list of CN CUI that could be purged.

**Comment by nicolevasilevsky** [comment]
thanks - this is on my to do list, I hope to get to it soon :)

**Comment by nicolevasilevsky** [comment]
![Uploading image.png…]()
