### ISSUE TITLE
Spastic Diplegia Cerebral Palsy or spastic diplegia

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2597]
UMLS makes a distinction between these concepts.
I see that the GARD link from spastic diplegia MONDO:0001167 goes to 
Spastic diplegia cerebral palsy

Was it agreed that there should be no distinction?  If so , we will contact UMLS.

**Comment by sabrinatoro** [comment]
Hello @maglott 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
'spastic diplegia' is a child of 'spastic cerebral palsy', so it inherits all the properties of spastic cerebral palasy, so I think these two concepts are equivalent.

I will close this but please reopen if you would like to revisit.

**Comment by kanems** [comment]
I think this term might need another look.
SCTID:281411007 is indeed "Spastic diplegia" however the UMLS CUI cited (C0270804) maps the SNOMED CT concept for "Diplegic cerebral palsy" SNOMEDCT_US, 58193001
Also HPO has a phenotype of the same preferred name: "Spastic diplegia HP:0001264" https://hpo.jax.org/app/browse/term/HP:0001264 so the preferred names from Mondo and HPO are causing a conflict in MedGen.

It would seem that Spastic diplegia is a phenotype, and 'Spastic diplegic cerebral palsy' is a specific presentation of CP with this clinical manifestation as a defining characteristic. 

Spastic diplegia, hemiplegia and monoplegia all seem like they would be more appropriate as phenotype descriptors, then the "cerebral palsy, spastic (hemi/mono/di)-plegia" concepts would be the disease entities under spastic cerebral palsy. (Also noting that spastic hemiplegia and monoplegia each have only one child in Mondo,  see screenshot below)
![image](https://user-images.githubusercontent.com/71083858/155372341-59b3c3bf-a042-47ee-a60b-95176706b343.png)

**Comment by sabrinatoro** [comment]
@nicolevasilevsky : This needs discussion. 
snomed and UMLS have 2 separate concepts: 
- SCTID:281411007 “spastic diplegia” ; UMLS:C0023882 “Little’s Disease”
- SCTID:58193001 "Diplegic cerebral palsy" ; UMLS:C0270804 "Spastic Diplegia Cerebral Palsy"

Some sources mention that "spastic diplegic cerebral palsy" also known as "spastic diplegia"
Though these concepts are both in the "disease" class of snomed and umls, should we separate them, one being phenotype, and the other being the actual disease?

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @ahamosh said:
spastic diplegia is a phenotypic feature
di-, tri-, quadriplegia are phenotypes

May need a neurologist to properly answer this question. @pnrobinson has a collaborator from the Shriner's project.

@ahamosh said that “spastic diplegia” and "Diplegic cerebral palsy" are the same as far as she can see. @pnrobinson will confirm with his neurologist collaborator.

**Comment by nicolevasilevsky** [comment]
diplegic means two weak limbs. diplegic is a phentypic description.

**Comment by nicolevasilevsky** [comment]
@pnrobinson will contact the CP doctors he knows and ask about this.

Tentative proposal per call with Peter, Ada, Sabrina and Nicole:

## Proposed hierarchy:
cerebral palsy
- some children terms genetic etiologies (from OMIM)
- CP due to hypoxic ischemic encephalopathy on the basis of history and possibly  PVL 
- idiopathic CP

PVL = Periventricular Leukomalacia 

## Action items

- [ ] 'spastic quadriplegic cerebral palsy'  is not a child of 'cerebral palsy'
- [ ]  obsolete the children terms that refer to phenotypic feature and add a consider that points to the HPO term

**Comment by sabrinatoro** [comment]
@kanems 
You are correct: many of the cerebral palsy terms could refer to either phenotypes or diseases. The current classification in Mondo requires a much deeper review, which will be done in #4767.
In the meantime, I added SNOMED:58193001 as a x-ref for 'spastic diplegia' (MONDO:0001167). 
Please let us know if you have any additional concerns. Thank you!
