### ISSUE TITLE
missing logical definitions from mondo.obo file

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2608]

**Comment by matentzn** [comment]
Maybe this is intended after all. There a a handful (1000 or so) logical definitions in mondo.obo - a quick search through the reveals to me that they are those defs that only have mondo references, such as:

```
intersection_of: MONDO:0020573 ! inherited disease susceptibility
intersection_of: predisposes_towards MONDO:0005229 ! bacterial infectious disease with sepsis
```

@cmungall can you please review whether the following are still the intended main release rules:

```
# PRE-RELEASES: MONDO IDs primary
#
# by default we use Elk to perform a reason-relax-reduce chain
# after that we annotate the ontology with the release versionInfo
$(ONT).owl: reasoned.owl
	$(ROBOT) merge -i $< annotate -V $(ONTURI)/releases/`date +%Y-%m-%d`/$(ONT).owl -o $@

# obo is self-contained
$(ONT).obo: reasoned.owl
	owltools --use-catalog $< --remove-imports-declarations --remove-dangling -o -f obo --no-check $@.tmp && $(obo-filter-axiom-header) $@.tmp > $@
```

**Comment by cmungall** [comment]
we dumbed down mondo.obo for OLS, e.g. no ECs between NCs

we do need to better document the different products. but it is common for the obo to be only the IDs in the main ontology

**Comment by matentzn** [comment]
But shouldn't we at least drop all ECs instead of keeping a random few that happen to contain only MONDO IDs?
