### ISSUE TITLE
migrate from Travis to GitHub actions

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2609]
want to migrate from Travis to GitHub actions, ie we want the Jenkins build commands to be executed by GitHub actions instead.

Action: 
- transfer the logic of travis such that when a PR is created, instead of using Travis, we use GitHub actions.
- review the sleeping commands - what is this?

To do:
- [ ] @matentzn give @jiaola access to Travis account

**Comment by matentzn** [comment]
This will involve, in particular, to figuring out how to replace the TRAVIS_*** environment variables. Maybe the best strategy is to set up a github actions workflow on a branch, and then just work with echo's to figure out which GH environment variables we need.

**Comment by jiaola** [comment]
Moved the qc process to github actions. See PR #2680. Will keep this ticket open for a few more days and clean up the travis/jenkins setup.

**Comment by matentzn** [comment]
Awesome works very well! Thank you! Lets have a tag for qc-call @nicolevasilevsky what do you think? That way we can just flag an issue we need to look at in person at the next QC call!

**Comment by matentzn** [comment]
We can review last weeks runs at the next call and then simply deactivate travis - that's all that's needed.
