### ISSUE TITLE
Predisposes to X should never be subclass to X

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2618]
We have around 170 cases where a disease X could predispose_towards another disease Y, for example:

```
[Term]
id: MONDO:0000065
name: microvascular complications of diabetes, susceptibility
comment: Editor note: relationship to diabetic angiopathy
subset: predisposition
synonym: "microvascular complications of diabetes" EXACT [OMIMPS:603933]
xref: DC:0000281 {source="MONDO:equivalentTo"}
xref: OMIMPS:603933 {source="MONDO:equivalentTo", source="DC:0000281"}
xref: UMLS:CN357508 {source="MONDO:equivalentTo"}
intersection_of: MONDO:0020573 ! inherited disease susceptibility
intersection_of: predisposes_towards MONDO:0005266 ! diabetic retinopathy
relationship: has_modifier MONDO:0021152 {source="OMIMPS:603933"} ! inherited
```

We want to make sure that if that is the case, X should never be a subclass of Y. So given the example above, MONDO:0000065 should not be a subclass of MONDO:0005266.

Steps:
1. Create a new sparql check. To do that copy and existing one (that ends in `-violation.sparql`). 
2. Implement the above as a query. So the sparql query will look for all instances where X predisposes_towards Y _and_ X subclassOf Y. Hopefully there are none.
3. Make a branch and make a pull request - which has the new query, and a single additional entry in `src/ontology/Makefile` (row 414, `CORE_CHECKS` variable)
4. Assign me as a reviewer.
5. Tip: A cool way to test sparql queries is @balhoff s Ubergraph. Here is [an example](https://api.triplydb.com/s/94_gw8GMZ). You can build a query in yasgui until you are happy and then copy it to mondo - that way you don't have to test your queries with ROBOT, which is more time consuming.

**Comment by nicolevasilevsky** [comment]
this is done, right?

**Comment by jiaola** [comment]
I think so. Can we close it?
