### ISSUE TITLE
Mondo Pattern Library 2.0

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2619]
All our logical patterns can be found [here](https://github.com/monarch-initiative/mondo/tree/master/src/patterns/dosdp-patterns). We want to achieve two things:

1. Standardise the patterns a bit better
2. Create beautiful, user friendly documentation for each of them

## Standardisation

Standardisation can be a bit tedious, and once we have a schema, @nicolevasilevsky and I can help with this.

- [X] Standardising the pattern order. (I have done that, the order should be ["pattern_name", "pattern_iri", "description", "contributors", "classes", "relations", "annotationProperties", "vars", "name", "annotations", "def", "equivalentTo"])
- [x] Standardising the pattern variable names. As you can see [here](https://github.com/monarch-initiative/mondo/blob/baa5a0310510f841ebe077191b3922233504ab77/src/patterns/dosdp-patterns/adenocarcinoma.yaml#L25), some patterns have ugly variable names, we really want to standardise. Standardise means: if the slot is a `disease` the variable should be named `disease` ([example](https://github.com/monarch-initiative/mondo/blob/baa5a0310510f841ebe077191b3922233504ab77/src/patterns/dosdp-patterns/allergic_form_of_disease.yaml#L31)). If the variable refers to a gene, the variable should be called "gene".
- [ ] Standardising the classes, relations, annotationProperties fields. Standardising means: the slot should use the appropriate id as a value. Good example [here](https://github.com/monarch-initiative/mondo/blob/baa5a0310510f841ebe077191b3922233504ab77/src/patterns/dosdp-patterns/allergic_form_of_disease.yaml#L19).
- [ ] Every pattern should have a good definition. Basically you paste a pattern in slack, and @nicolevasilevsky will come up with a description you can add. 
 
 ## Shiny Pattern Documentation System (dp2docs)
 
 Here, we want to have a beautiful markdown based page in our [readthedocs](https://mondo.readthedocs.io/en/latest/editors-guide/e-design-patterns/#design-patterns-for-neoplasms). We don't know yet the perfect way to do this, but in essence, we want:
 
 - [ ] A way to generate a great overview for patterns like [README.md](https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/README.md), which is generated by [this](https://github.com/monarch-initiative/mondo/blob/master/src/scripts/patterns_create_overview.py) script in our read the docs (a new sub page).
 - [ ] An individual page for each pattern which lays out the pattern in a beautiful way. The goal here is to have something really user friendly, that clinicians can be pointed to and that makes sense. 
 - [ ] Everything should be based on markdown. So ideally the _input is a directory of patterns, the output is a a set of markdown files_ that can be fiddled in to read the docs _and_ mkdocs or github pages directly.

**Comment by matentzn** [comment]
https://mondo.readthedocs.io/

**Comment by matentzn** [comment]
Step 1: Create automatically

/docs/

- create subdir /docs/editors-guide/patterns
- for every pattern, generate a nice markdown view of pattern in patterns dir
- generate a nice overview for all patterns

Step 2: 
- Group related patterns. 
- Option 1: category based (all patterns in `cancer` category are grouped together)
- Option 2: pattern relation based : patterns (in overview) are rendered in a tree according to their respective sub/super patterns.

**Comment by matentzn** [comment]
also replace all instances

disease: owl_thing 

disease: MONDO:0000001

and adjust the variable names.

-

**Comment by cmungall** [comment]
This is awesome

I'd like to discuss naming conventions

Naming vars after relations is better than ranges

**Comment by matentzn** [comment]
We will discuss at next qc call.

**Comment by nicolevasilevsky** [comment]
- [ ] need to make sure synonym pattern is not equivalent to the label

**Comment by nicolevasilevsky** [comment]
in discussion with @matentzn we decided to close this ticket in favor of smaller tickets.
