### ISSUE TITLE
MeSH query when ExactMatch same for two MONDO IDs amyopathic dermatomyositis MONDO:0043317 and juvenile dermatomyositis MONDO:0008054

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#2621]
Can there be two instances of ExactMatch for MeSH xref for two different MONDO ids?
amyopathic dermatomyositis MONDO:0043317 
ExactMatch 
**http://identifiers.org/mesh/C538250**

juvenile dermatomyositis MONDO:0008054
ExactMatch
**http://identifiers.org/mesh/C538250**
http://identifiers.org/mesh/C000598745 (> obsolete)

**Comment by nicolevasilevsky** [comment]
@lcdaugherty we should only have one exact match to an external source (with some rare exceptions that we call a 'proxy merge'). It looks like in the case you reported, one fo the MESH term is obsoleted, so I need to mark it as such in Mondo.

Thanks for reporting this - I'll fix it asap.

**Comment by nicolevasilevsky** [comment]
@lcdaugherty I don't see that http://identifiers.org/mesh/C538250 is an ExactMatch to juvenile dermatomyositis MONDO:0008054, where do you see that?
![image](https://user-images.githubusercontent.com/6722114/107443204-3e4d9f80-6aed-11eb-80e5-7d1f3c6c4583.png)

I annotated http://identifiers.org/mesh/C000598745 as equivalentObsolete.

**Comment by lcdaugherty** [comment]
@nicolevasilevsky I use OLS to view and get info info- it shows exactmatch C538250
[OLS_MONDO0008054.pdf](https://github.com/monarch-initiative/mondo/files/5971457/OLS_MONDO0008054.pdf).
Is this a version issue? Should I be looking elsewhere for this sort info?

**Comment by nicolevasilevsky** [comment]
@lcdaugherty you are right, I see that too! OLS is a good place to look, I am not sure why that shows up that way.

@cmungall @matentzn can you offer any insight?

In the mondo-edit file, I see this is marked as a directSiblingOf, not equivalentTo. Does OLS treat these as exact matches?

**Comment by matentzn** [comment]
Could it be an older version of Mondo in OLS?

**Comment by nicolevasilevsky** [comment]
Could be, but it is my understanding that OLS picks up the latest Mondo release each month

**Comment by matentzn** [comment]
You could open mondo.owl from the latest release in protege to confirm. If its correct there, I am confident that OLS did not pick up the latest release..

**Comment by nicolevasilevsky** [comment]
Ooooh the mondo.obo has this as an exact match:
![image](https://user-images.githubusercontent.com/6722114/107812168-24e26880-6d24-11eb-8694-fe6beee9bf2b.png)

**Comment by nicolevasilevsky** [comment]
so directSiblingOf is treated like an exact match?
that doesn't seem right to me...

**Comment by matentzn** [comment]
Definietly not! Prioritise for QC board!

**Comment by nicolevasilevsky** [comment]
Thanks @lcdaugherty for bringing this to our attention! :)

**Comment by nicolevasilevsky** [comment]
Nico ran the SKOS generation process and the exactMatch to the juvenile term does not appear to be there anymore.

to do:
- [ ] Double check in next release, and close.
