### ISSUE TITLE
need a check for cases of duplicate xrefs on Mondo terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2630]
Need a check for duplicate xrefs on Mondo terms. For example, an xref to an OMIM, Orphanet, etc class with an MONDO:equivalentTo annotation on more than one Mondo class.

Related to:
https://github.com/monarch-initiative/mondo/issues/1145

Not sure if this already exists? If yes, please close this.
(I feel like this does exist)

**Comment by joeflack4** [comment]
Going to defer to #1145 for the most part.
