### ISSUE TITLE
Replaced curies should not be literals

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/mondo#2636]
**Mondo term (ID Label)**

MONDO:0004589
N.A.  replaced  terms do not keep labels

**Bug/Typo/Error description**

replaced term is expressed as as string in the form of a curie instead of a curie
```
<http://purl.obolibrary.org/obo/MONDO_0004589> 
    <http://purl.obolibrary.org/obo/IAO_0100001>
      "MONDO:0019118"^^<http://www.w3.org/2001/XMLSchema#string> .

````
**Your nano-attribution (ORCID)**

orcid.org/0000-0003-0355-5581

**Comment by TomConlin** [comment]
Noting I suspect there may be 1,614 occurrences of 

    <URI>  <term replaced by> "literal"^^<http://www.w3.org/2001/XMLSchema#string> .

in the current release.

**Comment by cmungall** [comment]
I'm reassigning to @matentzn as this is a technical issue not a biological one

Let me try and restate to see if I understand:

Currently Mondo is consistent in how it uses IAO_0100001, with values being:

 1. A string literal containing a CURIE
 2. An untyped literal containing a CURIE
 3. A URI/rdf resource

If we look at other ontologies we see another options - eg FOODON uses URIs with anyURI literals.

Unfortunately there is no global consensus across OBO on how to use IAO_0100001. Achieving this consensus is outside the scope of Mondo. This is complicated by the behavior of obo2owl conversion (alt_ids in particular)

For now, tools should be written to be robust in the face of this variability. We could write something that normalizes the mondo output to one of the above forms, but this is not guaranteed to be consistent with all ontologies.

**Comment by TomConlin** [comment]
Noting that  Github (actions?) made the original issue assignment and attributed it to the issue author.

Mondo is indeed consistent and has no instances where the new/replacing term is anything but a literal, I should have added that I checked for this.  

Indeed adjusting  `IAO:0100001` to suggest or recommend  that 
```
    Use on obsolete terms, relating the term to another term that can be used as a substitute"
```
implies the two representations of "term" ought to be compatible in a machine setting is clearly not Mondo's problem.

Mondo could however be a shining example of reason and not opt for the least helpful representation just because it is not forbidden.

**Comment by matentzn** [comment]
Closing in favour of https://github.com/INCATools/ontology-development-kit/issues/642

this has to be solved for all ontologies at once.
