### ISSUE TITLE
Lennox-Gastaut syndrome MONDO:0016532 incorrect exactmatch MeSH C535500

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#2637]
Currently  Lennox-Gastaut syndrome MONDO:0016532 has two exactmatch xrefs for MeSH
MeSH C535500 Lennox-Gastaut syndrome
MeSH D065768 Epileptic encephalopathy, Lennox-Gastaut type
I think MeSH D065768 should be removed as an exact match from this MONDO entry

I would also query the exact match to http://identifiers.org/omim/606369 (MACROCEPHALY AND EPILEPTIC ENCEPHALOPATHY), given the subclasses for Lennox-Gastaut syndrome MONDO:0016532 are: 
childhood onset epileptic encephalopathy (MONDO:0014150) exactmatch OMIM:615369
developmental and epileptic encephalopathy, 31 (MONDO:0014598) exactmatch OMIM:616346
developmental and epileptic encephalopathy, 43 (MONDO:617113) exactmatch OMIM:617113

**Comment by nicolevasilevsky** [comment]
thanks @lcdaugherty, I'll work on this asap

**Comment by sabrinatoro** [comment]
Hello @lcdaugherty 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
https://meshb.nlm.nih.gov/record/ui?ui=D065768 is Lennox Gastaut Syndrome
https://meshb.nlm.nih.gov/record/ui?ui=C535500 is Epileptic encephalopathy, Lennox-Gastaut type

I think the annotations in Mondo are correct.

Closing, but please reopen if additional work is needed, thanks!
