### ISSUE TITLE
[NTR/TWIST1]

### ISSUE THREAD

**Issue by mhughes5** [monarch-initiative/mondo#2659]
**Preferred gene-related syndrome label**
TWIST1-related craniosynostosis 

**Synonyms**
MONDO:0007399

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0015469

**Definition**
Any craniosynostosis in which the cause of the disease is a mutation in the TWIST1 gene.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID:17343269

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
N/A

**Your nano-attribution (ORCID) or URL for a working group**
https://clinicalgenome.org/affiliation/40059/

**Comment by nicolevasilevsky** [comment]
@mhughes5 if this is synonyms with an existing Mondo term, why not use the existing Mondo term?

I can add TWIST1-related craniosynostosis as a synonym.

I do appreciate that the name 'craniosynostosis 1' is not very intuitive for users, but we do try to keep the naming consistent for terms that are part of an OMIM phenotypic series. You can see how the hierarchy looks below.

Thank being said though, if it is much preferred by our user community to have the primary label be TWIST1-related craniosynostosis, then I can update it.

![image](https://user-images.githubusercontent.com/6722114/107703505-94971b80-6c70-11eb-9a0c-045fd65cde90.png)

**Comment by mhughes5** [comment]
Hi @nicolevasilevsky, 
The Craniofacial malformations GCEP prefers to use gene-based naming because that is how their community is shifting. Changing this from craniosynostosis 1 is consistent with other recent requests (TCF12-related craniosynostosis, synonym craniosynostosis 3) and we expect to request more gene-centered terms in the near future. 
Thanks, 
Madeline

**Comment by nicolevasilevsky** [comment]
@mhughes5 - no problem! I updated this label.
