### ISSUE TITLE
OMIM terms should use primary OMIM label

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2660]
Need to normalize the names that come from OMIM.

Currently, the labels in Mondo do not necessarily match the names OMIM. We should use the primary label from OMIM, existing Mondo labels need to be updated.

Related
https://github.com/monarch-initiative/mondo/issues/1526

There is improper capitalization of Mondo labels in terms that come from OMIM (and Orphanet).

**Comment by matentzn** [comment]
@nicolevasilevsky please review this table:

there is a detail in the SPARQL query I cant figure out, so if this table looks safe to you, I will rename the diseases:
https://github.com/monarch-initiative/mondo/blob/master/src/ontology/reports/report-omim-abbreviation-replace.tsv

Safe in the sense: all labels (`?term_label`) will be replaced by their OMIM syns (`?related`).

**Comment by nicolevasilevsky** [comment]
@matentzn Can I edit the file?
we should call 'mental retardation, X-linked 49' 'intellectual disability, X-linked 49'

**Comment by matentzn** [comment]
Unfortunately no, you cant edit it..  fixing the capitalisation is easy I think (I hope!, but you will have to do the other ones).

**Comment by matentzn** [comment]
@nicolevasilevsky there are thousands of uses of `mental retardation` in Mondo - shouldn't we deal with them all at once?

**Comment by nicolevasilevsky** [comment]
yes, it would be great to deal with all the MR at once, i'll create a ticket
