### ISSUE TITLE
Broken link at https://mondo.monarchinitiative.org/

### ISSUE THREAD

**Issue by ahwagner** [monarch-initiative/mondo#2661]
The [MONDO homepage](https://mondo.monarchinitiative.org/) link to the [JSON Edition](http://purl.obolibrary.org/obo/mondo/mondo-with-equivalents.json) is broken.

**Comment by nicolevasilevsky** [comment]
mondo-with-equivalent is also broken

**Comment by nicolevasilevsky** [comment]
@matentzn these links are broken and they are broken on the OBO Foundry page too:
http://obofoundry.org/ontology/mondo.html

Do you know what the correct links are?

**Comment by matentzn** [comment]
The website does not use the PURLs which it really should. I don't know how to change the mondo website, but no ontology should ever be linked through its GitHub url; always purls! Our purl config changed recently; https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/mondo.yml

But that does not matter; how can I edit this website?

**Comment by nicolevasilevsky** [comment]
https://mondo.readthedocs.io/en/latest/editors-guide/mondo-website-editing/

**Comment by matentzn** [comment]
Fixed here: https://github.com/OBOFoundry/purl.obolibrary.org/pull/729

Double check it works and can be closed then!

**Comment by nicolevasilevsky** [comment]
fixed, thanks @matentzn!
