### ISSUE TITLE
split term:  hyperphosphatemic familial tumoral calcinosis

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2664]
**Term to split:**

hyperphosphatemic familial tumoral calcinosis MONDO:0008897

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
hyperphosphatemic familial tumoral calcinosis  (MONDO:0008897)
hyperphosphatemic familial tumoral calcinosis, 1 (MONDO TBD, should be a child of the term above, sib to HFTC 2 and 3, which are already children to the parent term.)

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonynms that end in "1", "2", etc. should move to subclass.
OMIM:211900

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@kanems I think this was already done per this ticket:
https://github.com/monarch-initiative/mondo/issues/962

We have:
![image](https://user-images.githubusercontent.com/6722114/109055004-7cbd8f80-7693-11eb-8d47-b99c9c626bc1.png)

Does this address your concerns?

I don't think this has been released yet, I plan to do a release next week

**Comment by sabrinatoro** [comment]
@kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by kanems** [comment]
This has been corrected and released, no further action needed.
