### ISSUE TITLE
congenital neuronal ceroid lipofuscinosis

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2665]
I am looking for clarification on congenital neuronal ceroid lipofuscinosis, MONDO:0008956 Some of the X-refs are getting me a bit confused.

-OMIM 214200 is a clinical description named "CEROID STORAGE DISEASE" alt name "LIPOFUSCIN STORAGE DISEASE" which doesn't seem to be equivalent to congenital NCL (an "included in" term from OMIM 610127)

-SNOMED 720830009 does say the preferred term is congenital neuronal ceroid lipofuscinosis, but also says CLN-10/Cathepsin-D deficiency specific etiology are synonyms for that same SNOMED code/concept. Same with the MESH C566438 term. I appreciate the effort made the split CLN10 out from the generic concept of congenital NCL here, especially since so many other groups try to lump them.

-FYI It looks like UMLS has term C1864670 for congenital NCL concept.

-->It seems the MIM entry214200  might be best handled as a separate child concept of congenital NCL, maybe a sib to CLN-10?

**Comment by nicolevasilevsky** [comment]
@ahamosh could I ask for your expert advice? 

The question is should OMIM:214200 CEROID STORAGE DISEASE be a child of MONDO_0008956 'congenital neuronal ceroid lipofuscinosis', or should it remain as an equivalent dbxref on MONDO_0008956 'congenital neuronal ceroid lipofuscinosis'?

The description on the OMIM record suggests that it may be equivalent to MONDO_0009744 'neuronal ceroid lipofuscinosis 1' (https://omim.org/entry/256730)?

**Comment by ahamosh** [comment]
Hi Nicole, I forwarded your question to Joanna and Carol.  I think this (214000) is an old entry that likely needs to be folded into 256730, but I want the database gurus to answer.

**Comment by nicolevasilevsky** [comment]
perfect, thanks @ahamosh!

**Comment by ahamosh** [comment]
214000 has been moved to 256730

**Comment by nicolevasilevsky** [comment]
thanks @ahamosh!

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
