### ISSUE TITLE
[Merge]PGBM1/MONDO:0014389 /MONDO:0018348

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2668]
**Mondo term (ID and Label)**

polyglucosan body myopathy type 1 vs. POLYGLUCOSAN BODY MYOPATHY 1 WITH OR WITHOUT IMMUNODEFICIENCY
**Reason for deprecation**
Is there really a distinction here? Both OMIM (POLYGLUCOSAN BODY MYOPATHY 1 WITH OR WITHOUT IMMUNODEFICIENCY) and Orphanet (polyglucosan body myopathy type 1) provide PGBM1 as the symbol.
Should there be a general review of labels containing 'with or without'?

**Term to be merged with**
see title
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Hi @maglott from what I can see, OMIM lists RBCK1 as the gene, and Orphanet has RBCK2 (see https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_397937).

I am not sure that these are equiv, and I also don't think they should be parent and child.

Would you mind double checking and let me know if you agree? Thanks!

**Comment by maglott** [comment]
I am confused.  When I go to https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=397937, and display the genes, I see RANBP2-type and C3HC4-type zinc finger containing 1 - RBCK1. 
Seems ordo and Orphanet differ.

**Comment by nicolevasilevsky** [comment]
@maglott I think I'm mistaken, looking again it looks like RBCK1 is a synonym of RANBP2-type and C3HC4-type zinc finger containing 1.

I do agree these terms are equivalent.

I'll send this out to the Mondo users list for comment, then will merge these.

**Comment by sabrinatoro** [comment]
@maglott 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] merge MONDO:0018348 'polyglucosan body myopathy type 1' with MONDO:0014389 'polyglucosan body myopathy 1 with or without immunodeficiency'
