### ISSUE TITLE
split term: <enter name>MONDO:0009989 and Goldmann-Favre syndrome

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2684]
**Term to split:**
enhanced S-cone syndrome
**Name for new terms:** 
enhanced S-cone syndrome and Goldmann-Favre syndrome
**List properties that should be moved to new term:**
If the clinical community agrees that these are distinct entities, then the munge of XRefs and labels under this MondoID should be cleaned up
* OMIM and Snomed make a disctinction between these concepts.
The definition of Goldmann-Favre syndrome (from Orphanet) seems to be displayed for enhanced S-cone syndrome
We are holding off a merge at NCBI until this is resolved with Mondo.

**Comment**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@ahamosh and @pnrobinson can you please give us your thoughts? Thanks!

**Comment by pnrobinson** [comment]
@nicolevasilevsky  This is a classic lumper/splitter debate. The OMIM entry's text differentiates the two diseases and the entry 268100 says it INCLUDES Goldmann-Favre syndrome. @ahamosh we should discuss whether we can reliably infer that INCLUDES means subtype, or if we should do a in depth analysis on the ClinGen lumper/splitter meetings.

**Comment by ahamosh** [comment]
Included is always a distinct entity as opposed to a synonym or alternate title.  It may or may not mean subtype.

**Comment by nicolevasilevsky** [comment]
So it sounds like these two terms should be split into two Mondo classes?

@cmungall should I xref Goldmann-Favre syndrome with the OMIM ID and MONDO:relatedTo?

**Comment by nicolevasilevsky** [comment]
talked to Chris - answer is yes
