### ISSUE TITLE
[Merge] MONDO:0019663 and MONDO:0013127

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2690]
**Mondo term (ID and Label)**
MONDO:0019663 "short rib-polydactyly syndrome, Saldino-Noonan type"
MONDO:0013127 "asphyxiating thoracic dystrophy 3"

**Reason for deprecation**
Both terms have syn of "short rib-polydactyly syndrome type 1/I" and according to https://www.omim.org/entry/613091, they are alternate names for the same condition.

**Term to be merged with**
MONDO:0013127 "asphyxiating thoracic dystrophy 3" (this already has the OMIM x-ref, seems to make sense to keep this one.)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems, I'll email the list before proceeding.
