### ISSUE TITLE
Should ALG13-CDG be a subClass of EIEE? (more generally: PS vs ORDO)

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#27]
[PS308350 / EIEE](https://omim.org/phenotypicSeries/PS308350):

![image](https://user-images.githubusercontent.com/50745/32986073-b4d810a2-cc7d-11e7-9335-4b267581cfcd.png)

The last entry is [300884](https://omim.org/entry/300884), for `?Congenital disorder of glycosylation, type Is` / `EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 36; EIEE36`.

(note that OMIM used to use the label 'Congenital Disorder of Glycosylation, Type Is' but now uses 'EPILEPTIC ENCEPHALOPATHY, EARLY INFANTILE, 36; EIEE36').

The only xref in Orphanet to this is [Congenital disorder of glycosylation type Is](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=324422). See also [in OLS](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_324422). Note the xref type is 'NTBT' (was 'nd' in a previous version).

Note also ORDO doesn't include this under EIEE:

![image](https://user-images.githubusercontent.com/50745/32986096-599cf90e-cc7e-11e7-88bd-67cbe8299661.png)

For EIEE, ORDO has no subtypes/parts, and has a set of OMIM BTNT xrefs that are a subset of the OMIM PS:

![image](https://user-images.githubusercontent.com/50745/32986104-8430b606-cc7e-11e7-9dfb-996a92065fda.png)

Thus far we have tended to follow ORDO rather than PS. For example here we have:

```
[Term]
id: MONDO:0010472
name: ALG13-CDG
def: "(Xq23)." [Orphanet:324422]
subset: ordo_disease {source="Orphanet:324422"}
synonym: "Cdg Is" RELATED [OMIM:300884]
synonym: "CDG syndrome type Is" EXACT [Orphanet:324422]
synonym: "CDG-Is" EXACT [Orphanet:324422]
synonym: "CDG1S" EXACT [Orphanet:324422]
synonym: "CDG1S" RELATED [OMIM:300884]
synonym: "Congenital disorder of glycosylation type 1s" EXACT [Orphanet:324422]
synonym: "Congenital disorder of glycosylation type Is" EXACT [Orphanet:324422]
synonym: "CONGENITAL DISORDER OF GLYCOSYLATION, TYPE Is; CDG1S" RELATED [OMIM:300884]
xref: ICD10:E77.8 {source="ORDO:324422/attributed", source="ORDO:324422/ntbt", source="Orphanet:324422"}
xref: OMIM:300884 {source="MONDO:equivalentTo", source="ORDO:324422/nd", source="MONDO:Leader", source="Orphanet:324422"}
xref: Orphanet:324422 {source="MONDO:equivalentTo", source="OMIM:300884"}
xref: UMLS:C3550904 {source="NCBI:mim2gene_medline", source="OMIM:300884"}
is_a: MONDO:0005500 {source="OMIM:300884"} ! congenital disorder of glycosylation type I
is_a: MONDO:0017740 {source="Orphanet:324422"} ! disorder of protein N-glycosylation
is_a: MONDO:0018287 {source="Orphanet:324422"} ! congenital disorder of glycosylation with epilepsy as a major feature
is_a: MONDO:0018288 {source="Orphanet:324422"} ! congenital disorder of glycosylation with hepatic involvement
```

Like ORDO, we do not classify as an EIEE.

In this particular case it seems that we should relabel this class to be consistent with OMIM, and make a subclass of EIEE to be consistent with PS.

In the general case we need to examine PS vs ORDO inconsistencies and evaluate on a case-by-case basis.

**Comment by nicolevasilevsky** [comment]
this can be closed, ALG13-CDG is a child of 'developmental and epileptic encephalopathy'
