### ISSUE TITLE
[Open Targets] Add synonyms from Genomics England phenotypes

### ISSUE THREAD

**Issue by ireneisdoomed** [monarch-initiative/mondo#2704]
Hello,

we have identified 3 terms from one of our sources where the phenotype indicated at source cannot be programmatically mapped to their correspondent MONDO IDs.

It would be great if these could be potentially imported as a synonym so that we can downstream benefit from their inclusion in EFO and have a better mapping.

Synonym to add | MONDO Term | MONDO Label | Xref
 -- | -- | -- | --
 "Autoinflammation with infantile enterocolitis" | http://purl.obolibrary.org/obo/MONDO_0014472 | periodic fever-infantile enterocolitis-autoinflammatory syndrome | Orphanet:436166
"Hemolytic anemia due to G6PD deficiency" | http://purl.obolibrary.org/obo/MONDO_0018750 | class I glucose-6-phosphate dehydrogenase deficiency | Orphanet:466026
"MYSM1 deficiency" | http://purl.obolibrary.org/obo/MONDO_0033683 | congenital progressive bone marrow failure-B-cell immunodeficiency-skeletal dysplasia syndrome | Orphanet:508542

ORCID id: https://orcid.org/0000-0002-2417-7324

Thank you very much.

**Comment by nicolevasilevsky** [comment]
will do!
