### ISSUE TITLE
Mondo.owl does not show all inference in the top level of the class hierarchy

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2732]
The release version (mondo.owl) has the asserted top level view, we would like to see the inferred view

![image](https://user-images.githubusercontent.com/6722114/109200677-be167380-7755-11eb-8483-f9be15b6a79c.png)

**Comment by matentzn** [comment]
Was OLS showing the wrong thing or mondo.owl?

**Comment by nicolevasilevsky** [comment]
mondo.owl

**Comment by matentzn** [comment]
Ok! thx

**Comment by nicolevasilevsky** [comment]
I think this can be closed? The top level hierarchy has changed since this ticket was created.
