### ISSUE TITLE
Merge MONDO:0012215 and MONDO:0008032?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2733]
Should MONDO:0008032 autosomal dominant limb-girdle muscular dystrophy type 1A and MONDO:0012215 
myofibrillar myopathy 3 be merged?
The MIM Number on MONDO:0008032 (OMIM:159000) has been merged with the MIM number on MONDO:0012215  (OMIM:609200) and OMIM cites https://pubmed.ncbi.nlm.nih.gov/30055862/ as reasoning for retiring the LGMD1A name/synonym. 

But I see Orphanet maintains distinct terms for both concepts, but both reference OMIM 609200. 
@ana-rath-orphanet @ahamosh

**Comment by nicolevasilevsky** [comment]
@kanems We tend to follow OMIM- when they merge terms, we follow suit. I'll add this to the list of obsoletion candidates and will email Mondo users to make sure there are no objections.
