### ISSUE TITLE
Mondo: formal protocol for obsoletions

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2738]
I would suggest this simple protocol:

1. Every obsolete term has `owl:deprecated true^^xsd:boolean`
2. Every obsoleted term without a replacement term has a label starting with `obsolete`, e.g `obsolete gene A`
3. A term with a replacement term does not have to have a label, but `replaced_by:` must be an `exact` replacement
4. Every term must have a `rdfs:seeAlso` to a GitHub issue. Where we don't have one for historical reason, we link a github discussion that invites people to ask for obsoletion reasons. seeAlso should have type `anyURI`, not `string`
5. Every term should have an obsoletion reason from taxonomy:
    - MergedTerm (better than to say duplicate)
    - ObsoletedInSource
    - IsPhenotypeAndNotDisease
    - OutOfScope

**Comment by matentzn** [comment]
Restrict properties? Currently no.

## Currently:

- consider:
- replaced_by:
- rdfs:seeAlso
- http://www.geneontology.org/formats/oboInOwl#hasAlternativeId
- http://www.geneontology.org/formats/oboInOwl#id
- http://www.geneontology.org/formats/oboInOwl#hasDbXref
- rdfs:comment
- http://www.geneontology.org/formats/oboInOwl#inSubset
- http://purl.obolibrary.org/obo/mondo#excluded_subClassOf
- http://www.w3.org/2004/02/skos/core#closeMatch
- http://www.w3.org/2004/02/skos/core#exactMatch
- http://purl.obolibrary.org/obo/IAO_0000231
- http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
- http://purl.obolibrary.org/obo/IAO_0000115
- http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym
- http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym
- http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
- http://www.geneontology.org/formats/oboInOwl#created_by

**Comment by nicolevasilevsky** [comment]
I love this

**Comment by matentzn** [comment]
@nicolevasilevsky can you start a github discussion with a nice text explaining why some terms may not have obsoletion reasons recorded for historical reasons, and inviting people to use the discussion to ask for the obsoletion reason of specific terms? The idea is basically, when we don't have a real obsoletion reason, why can link to this discussion, and people can ask there.

**Comment by matentzn** [comment]
Queries: 
- [all obsolete terms including relevant metadata](https://api.triplydb.com/s/6CIdNhSyp)

**Comment by matentzn** [comment]
Why and when are we using `alt_id` as opposed to `replaced_by`? This seems odd:

```
[Term]
id: MONDO:0022263
name: obsolete congenital hepatic fibrosis
alt_id: MONDO:0022266
property_value: seeAlso https://github.com/monarch-initiative/mondo/issues/399 xsd:anyURI
is_obsolete: true
replaced_by: MONDO:0018840
```

**Comment by matentzn** [comment]
All seeAlso We may have to make some slow progress on this:
https://docs.google.com/spreadsheets/d/13eIa2Ihe6ChwOjH0s-8hp0K9IGMtveIqpFTtVvuvWK4/edit

Maybe during QC calls?

**Comment by nicolevasilevsky** [comment]
@matentzn how is this?
https://github.com/monarch-initiative/mondo/discussions/2765

**Comment by nicolevasilevsky** [comment]
Documenting the tags we'll use:
MONDO:outOfScope

**Comment by nicolevasilevsky** [comment]
we will use IAO property:
IAO:0000231 has obsolescence reason

**Comment by matentzn** [comment]
Can we work on making sure to use the proper obsoletion reasons from IAO?

Currently, we have stuff like 

```
property_value: IAO:0000231 "terms merged" xsd:string
```

Which should really be using 

http://www.ontobee.org/ontology/OMO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000227

Is the problem that OBO format does not allow these?

**Comment by nicolevasilevsky** [comment]
We were having problems with it at one point, now I don't remember exactly what the issue was, but it was causing some kind of weird diff maybe?

We said we'd use strings for now, then go back and fix them all later to use individuals

**Comment by matentzn** [comment]
No worries, this was the problem: https://github.com/information-artifact-ontology/ontology-metadata/issues/81
