### ISSUE TITLE
[Revise hierarchy] According to Harrison's Principles of Internal Medicine, 20e

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2741]
Per the Mondo call on 02/26/21, I will take a pass at reclassifying a branch in Mondo according to the Harrison's textbook, as a pre-workshop effort.

https://accessmedicine.mhmedical.com/book.aspx?bookID=2129#191736950

**Comment by nicolevasilevsky** [comment]
See PR- I reclassified neuro terms.

**Comment by nicolevasilevsky** [comment]
[Notes from workshop](https://docs.google.com/document/d/1KXqGAZgZUbK-VnzcomnMbfAEq7WEeGxDaQ-EK8UUQZI/edit)

**Comment by sabrinatoro** [comment]
the only work left is the review of "connective tissue disease", which is not directly part of the Harrison view project.
