### ISSUE TITLE
policy for when a MIM number becomes gene-specific

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2747]
Not sure if this is the correct category, but I am looking for a statement of what MONDO does when a MIM number becomes gene-specific.

Case in point: 
https://www.omim.org/phenotypicSeries/PS614594
https://omim.org/entry/614594
MONDO:0019014

Will the XREF on MONDO:0019014 change from OMIM:614594 to OMIMPS:614594, with new children created for OMLS1, OMLS2 and OLMSX?
Or will MONDO:0019014 be renamed?  

I strongly advocate for the first option.

**Comment by matentzn** [comment]
Good question! Such policies are managed by @cmungall and @nicolevasilevsky 
So I will let them answer!

**Comment by cmungall** [comment]
I agree 1 is better but there is a 3rd option. We obsolete the ID and make
2 new IDs. This causes churn for people using the old id but we include
metadata eg consider tags and force people to make a choice when migrating
annotations

**Comment by maglott** [comment]
Good point.  Is 3 the policy?

**Comment by nicolevasilevsky** [comment]
Hi @maglott yes- that is the policy, there is more detail here:
https://mondo.readthedocs.io/en/latest/editors-guide/splitting-classes/

**Comment by nicolevasilevsky** [comment]
I think this can be closed, please reopen if there are more questions.

**Comment by maglott** [comment]
@cmungall , thanks for the link to the doc.
