### ISSUE TITLE
[Obsolete] 'chorea minor'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2749]
**Mondo term (ID and Label)**
'chorea minor'

**Reason for deprecation**
obsoleted in GARD
cc @galyea-gard

**Suggested term to consider**
http://purl.obolibrary.org/obo/MONDO_0001595
'choreatic disease'

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by galyea-gard** [comment]
Hi Nicole! Minor chorea was retired because it was duplicate of Sydenham's chorea; in addition, this synonym (minor chorea)  is currently not used anymore. Thank you! Gioconda
