### ISSUE TITLE
Question - Using Mondo to get a list of mendelian disorders

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/mondo#2760]
I'm wondering if it's possible if I could use Mondo to narrow down a list of Mendelian disorders.  I noticed there is a superclass (Mendelian disease, MONDO:0003847), but this is missing some diseases (such as Mendelian subtypes of Parkinson disease), and may potentially include diseases that are not Mendelian (https://github.com/monarch-initiative/mondo/issues/2759). cc @cmungall @pnrobinson @nicolevasilevsky

**Comment by cmungall** [comment]
So we should fix it so the class oi s either obsolete or complete!

**Comment by nicolevasilevsky** [comment]
It seems there are 10k subclasses of Mendelian diseases, does that seem right?

Both options seem like a lot of work, as many classes will be come orphaned if we obsolete Mendelian disease.

Could this be a topic for the workshop?

**Comment by cmungall** [comment]
We should infer it

**Comment by pnrobinson** [comment]
This number seems to be too high. OMIM now has 5619+1312+1657=8588 Mendelian or probably Mendelian diseases.
https://omim.org/statistics/entry
Depending on where one stands in the lumper/splitter debate, probably there are over 10K (e.g., the INCLUDED entries), but AFAIK we do not have them in MONDO (yet) and so probably there is something wrong here?

**Comment by nicolevasilevsky** [comment]
I'll need guidance how to set this up so it is inferred.

**Comment by nicolevasilevsky** [comment]
## [leprosy, susceptibility to, 2](http://purl.obolibrary.org/obo/MONDO_0011860) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [leprosy, susceptibility to, 2](http://purl.obolibrary.org/obo/MONDO_0011860) SubClassOf [leprosy](http://purl.obolibrary.org/obo/MONDO_0005124)
    - [leprosy](http://purl.obolibrary.org/obo/MONDO_0005124) SubClassOf [infectious disease with peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0016104)
      - [infectious disease with peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0016104) SubClassOf [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923)
        - [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) EquivalentTo [peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0005244) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
  - [leprosy, susceptibility to, 2](http://purl.obolibrary.org/obo/MONDO_0011860) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [PRKN](http://identifiers.org/hgnc/8607)
    - [PRKN](http://identifiers.org/hgnc/8607) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)


## [adult idiopathic neutropenia](http://purl.obolibrary.org/obo/MONDO_0011922) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [adult idiopathic neutropenia](http://purl.obolibrary.org/obo/MONDO_0011922) SubClassOf [acquired neutropenia](http://purl.obolibrary.org/obo/MONDO_0015822)
    - [acquired neutropenia](http://purl.obolibrary.org/obo/MONDO_0015822) EquivalentTo [neutropenia](http://purl.obolibrary.org/obo/MONDO_0001475) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
  - [adult idiopathic neutropenia](http://purl.obolibrary.org/obo/MONDO_0011922) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [GFI1](http://identifiers.org/hgnc/4237)
    - [GFI1](http://identifiers.org/hgnc/4237) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)


## [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [chronic polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0016170)
    - [chronic polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0016170) SubClassOf [chronic acquired demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016169)
      - [chronic acquired demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016169) EquivalentTo [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [chronic](http://purl.obolibrary.org/obo/PATO_0001863))
        - [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) EquivalentTo [peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0005244) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
  - [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [PMP22](http://identifiers.org/hgnc/9118)
    - [PMP22](http://identifiers.org/hgnc/9118) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)


## [acute motor axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020349) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [acute motor axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020349) SubClassOf [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691)
    - [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [PMP22](http://identifiers.org/hgnc/9118)
      - [PMP22](http://identifiers.org/hgnc/9118) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [acute motor axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020349) SubClassOf [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218)
    - [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218) SubClassOf [acute and subacute inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016137)
      - [acute and subacute inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016137) SubClassOf [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923)
        - [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) EquivalentTo [peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0005244) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
  - [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)


## [Lewis-Sumner syndrome](http://purl.obolibrary.org/obo/MONDO_0018826) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [Lewis-Sumner syndrome](http://purl.obolibrary.org/obo/MONDO_0018826) SubClassOf [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691)
    - [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [chronic polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0016170)
      - [chronic polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0016170) SubClassOf [chronic acquired demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016169)
        - [chronic acquired demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016169) EquivalentTo [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [chronic](http://purl.obolibrary.org/obo/PATO_0001863))
          - [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) EquivalentTo [peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0005244) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
    - [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [PMP22](http://identifiers.org/hgnc/9118)
      - [PMP22](http://identifiers.org/hgnc/9118) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)


## [acute inflammatory demyelinating polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0020347) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [acute inflammatory demyelinating polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0020347) SubClassOf [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691)
    - [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [PMP22](http://identifiers.org/hgnc/9118)
      - [PMP22](http://identifiers.org/hgnc/9118) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [acute inflammatory demyelinating polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0020347) SubClassOf [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218)
    - [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218) SubClassOf [acute and subacute inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016137)
      - [acute and subacute inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016137) SubClassOf [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923)
        - [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) EquivalentTo [peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0005244) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
  - [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)


## [amyotrophic neuralgia](http://purl.obolibrary.org/obo/MONDO_0008076) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [amyotrophic neuralgia](http://purl.obolibrary.org/obo/MONDO_0008076) SubClassOf [neuralgic amyotrophy](http://purl.obolibrary.org/obo/MONDO_0017362)
    - [neuralgic amyotrophy](http://purl.obolibrary.org/obo/MONDO_0017362) SubClassOf [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923)
      - [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) EquivalentTo [peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0005244) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
  - [amyotrophic neuralgia](http://purl.obolibrary.org/obo/MONDO_0008076) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [SEPTIN9](http://identifiers.org/hgnc/7323)
    - [SEPTIN9](http://identifiers.org/hgnc/7323) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)


## [renin-angiotensin-aldosterone system-blocker-induced angioedema](http://purl.obolibrary.org/obo/MONDO_0015057) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [renin-angiotensin-aldosterone system-blocker-induced angioedema](http://purl.obolibrary.org/obo/MONDO_0015057) SubClassOf [acquired angioedema](http://purl.obolibrary.org/obo/MONDO_0019624)
    - [acquired angioedema](http://purl.obolibrary.org/obo/MONDO_0019624) EquivalentTo [angioedema](http://purl.obolibrary.org/obo/MONDO_0010481) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
  - [renin-angiotensin-aldosterone system-blocker-induced angioedema](http://purl.obolibrary.org/obo/MONDO_0015057) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [XPNPEP2](http://identifiers.org/hgnc/12823)
    - [XPNPEP2](http://identifiers.org/hgnc/12823) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)


## [acute motor and sensory axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020348) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [acute motor and sensory axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020348) SubClassOf [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691)
    - [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [PMP22](http://identifiers.org/hgnc/9118)
      - [PMP22](http://identifiers.org/hgnc/9118) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [acute motor and sensory axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020348) SubClassOf [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218)
    - [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218) SubClassOf [acute and subacute inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016137)
      - [acute and subacute inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016137) SubClassOf [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923)
        - [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) EquivalentTo [peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0005244) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
  - [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)

# Axiom Impact 
## Axioms used 9 times
- [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152) [axioms.owl]
- [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152) [axioms.owl]

## Axioms used 7 times
- [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) EquivalentTo [peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0005244) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141)) [mondo.owl]

## Axioms used 5 times
- [PMP22](http://identifiers.org/hgnc/9118) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704) [hgnc_import.owl]
- [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [PMP22](http://identifiers.org/hgnc/9118) [mondo.owl]

## Axioms used 3 times
- [acute and subacute inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016137) SubClassOf [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) [mondo.owl]
- [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218) SubClassOf [acute and subacute inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016137) [mondo.owl]

## Axioms used 2 times
- [chronic acquired demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016169) EquivalentTo [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [chronic](http://purl.obolibrary.org/obo/PATO_0001863)) [mondo.owl]
- [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) SubClassOf [chronic polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0016170) [mondo.owl]
- [chronic polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0016170) SubClassOf [chronic acquired demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0016169) [mondo.owl]

## Axioms used 1 times
- [acquired neutropenia](http://purl.obolibrary.org/obo/MONDO_0015822) EquivalentTo [neutropenia](http://purl.obolibrary.org/obo/MONDO_0001475) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141)) [mondo.owl]
- [acquired angioedema](http://purl.obolibrary.org/obo/MONDO_0019624) EquivalentTo [angioedema](http://purl.obolibrary.org/obo/MONDO_0010481) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141)) [mondo.owl]
- [XPNPEP2](http://identifiers.org/hgnc/12823) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704) [hgnc_import.owl]
- [GFI1](http://identifiers.org/hgnc/4237) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704) [hgnc_import.owl]
- [SEPTIN9](http://identifiers.org/hgnc/7323) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704) [hgnc_import.owl]
- [PRKN](http://identifiers.org/hgnc/8607) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704) [hgnc_import.owl]
- [leprosy](http://purl.obolibrary.org/obo/MONDO_0005124) SubClassOf [infectious disease with peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0016104) [mondo.owl]
- [amyotrophic neuralgia](http://purl.obolibrary.org/obo/MONDO_0008076) SubClassOf [neuralgic amyotrophy](http://purl.obolibrary.org/obo/MONDO_0017362) [mondo.owl]
- [amyotrophic neuralgia](http://purl.obolibrary.org/obo/MONDO_0008076) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [SEPTIN9](http://identifiers.org/hgnc/7323) [mondo.owl]
- [leprosy, susceptibility to, 2](http://purl.obolibrary.org/obo/MONDO_0011860) SubClassOf [leprosy](http://purl.obolibrary.org/obo/MONDO_0005124) [mondo.owl]
- [leprosy, susceptibility to, 2](http://purl.obolibrary.org/obo/MONDO_0011860) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [PRKN](http://identifiers.org/hgnc/8607) [mondo.owl]
- [adult idiopathic neutropenia](http://purl.obolibrary.org/obo/MONDO_0011922) SubClassOf [acquired neutropenia](http://purl.obolibrary.org/obo/MONDO_0015822) [mondo.owl]
- [adult idiopathic neutropenia](http://purl.obolibrary.org/obo/MONDO_0011922) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [GFI1](http://identifiers.org/hgnc/4237) [mondo.owl]
- [renin-angiotensin-aldosterone system-blocker-induced angioedema](http://purl.obolibrary.org/obo/MONDO_0015057) SubClassOf [acquired angioedema](http://purl.obolibrary.org/obo/MONDO_0019624) [mondo.owl]
- [renin-angiotensin-aldosterone system-blocker-induced angioedema](http://purl.obolibrary.org/obo/MONDO_0015057) SubClassOf [disease has basis in dysfunction of](http://purl.obolibrary.org/obo/RO_0004020) some [XPNPEP2](http://identifiers.org/hgnc/12823) [mondo.owl]
- [infectious disease with peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0016104) SubClassOf [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) [mondo.owl]
- [neuralgic amyotrophy](http://purl.obolibrary.org/obo/MONDO_0017362) SubClassOf [acquired peripheral neuropathy](http://purl.obolibrary.org/obo/MONDO_0015923) [mondo.owl]
- [Lewis-Sumner syndrome](http://purl.obolibrary.org/obo/MONDO_0018826) SubClassOf [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) [mondo.owl]
- [acute inflammatory demyelinating polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0020347) SubClassOf [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) [mondo.owl]
- [acute inflammatory demyelinating polyradiculoneuropathy](http://purl.obolibrary.org/obo/MONDO_0020347) SubClassOf [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218) [mondo.owl]
- [acute motor and sensory axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020348) SubClassOf [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) [mondo.owl]
- [acute motor and sensory axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020348) SubClassOf [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218) [mondo.owl]
- [acute motor axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020349) SubClassOf [chronic inflammatory demyelinating polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0007691) [mondo.owl]
- [acute motor axonal neuropathy](http://purl.obolibrary.org/obo/MONDO_0020349) SubClassOf [Guillain-Barre syndrome](http://purl.obolibrary.org/obo/MONDO_0016218) [mondo.owl]



# Ontologies used: 
- axioms.owl (http://purl.obolibrary.org/obo/mondo/imports/axioms.owl)
- hgnc_import.owl (http://purl.obolibrary.org/obo/mondo/imports/hgnc_import.owl)
- mondo.owl (http://purl.obolibrary.org/obo/mondo.owl)

**Comment by nicolevasilevsky** [comment]
I did the following edits to address the build failures:

- renamed MONDO_0007691 to Guillain-Barre syndrome, familial (to match OMIM label)
- Excluded subclass from 'Guillain-Barre syndrome, familial'
  - excluded 'chronic polyradiculoneuropathy'
- Excluded subclass from 'acute inflammatory demyelinating polyradiculoneuropathy'
  - excluded 'Guillain-Barre syndrome, familial'
- Excluded subclass from 'nonimmune chronic idiopathic neutropenia of adults'
  - excluded 'acquired neutropenia'
  - added parent Mendelian disease
- Excluded subclass from 'amyotrophic neuralgia'
  - excluded neuralgic amyotrophy
- Excluded subclass from 'leprosy, susceptibility to, 2'
  - excluded leprosy
  - added parent 'inherited disease susceptibility'
- Removed subclassof axiom from 'renin-angiotensin-aldosterone system-blocker-induced angioedema'
  - removed 'disease has basis in dysfunction of' some XPNPEP2
  - Created new class for 'susceptibility to angioedema induced by ACE inhibitors', xref: OMIM:300909
- revise equiv axiom for 'autosomal recessive inherited pseudoxanthoma elasticum'
- create new class for 'chronic inflammatory demyelinating polyneuropathy', equiv to Orphanet:2932
- make Orphanet:2932 relatedTo on 'Guillain-Barre syndrome, familial'
- created new class 'chronic inflammatory demyelinating polyneuropathy' equiv to Orphanet:2932. Note - this was equiv to 'Guillain-Barre syndrome, familial' but there are no genes implicated in this disease, according to [orphanet](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=877&Disease_Disease_Search_diseaseGroup=2932&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Chronic-inflammatory-demyelinating-polyneuropathy&title=Chronic%20inflammatory%20demyelinating%20polyneuropathy&search=Disease_Search_Simple), and they also do not xref OMIM, so I think this should be its own class, with Lewis-Sumner syndrome as a child.
- moved Lewis-Sumner syndrome to be a child of 'chronic inflammatory demyelinating polyneuropathy'

**Comment by nicolevasilevsky** [comment]
OMIM:180200 was an exact synonym for Orphanet:790 Retinoblastoma, which is the grouping class ("...hereditary or non hereditary, unilateral or bilateral.") 
- make OMIM:180200 equiv to 'hereditary retinoblastoma' instead of retinoblastoma
