### ISSUE TITLE
MONDO:0100096 COVID-19 obsoleted exactmatch MeSH ID C000657245

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#2766]
MONDO:0100096 COVID-19 currently has ExactMatch for MeSH C000657245 but this seems have been obsoleted by MeSH (http://id.nlm.nih.gov/mesh/C000657245) and is now new MeSH D000086382 https://id.nlm.nih.gov/mesh/D000086382.html

links to https://github.com/monarch-initiative/mondo/pull/2265

**Comment by nicolevasilevsky** [comment]
thank you!

**Comment by dhimmel** [comment]
Ah COVID-19 has been promoted from a supplemental concept record (`C000657245`) to a topical descriptor (`D000086382`)!

**Comment by lcdaugherty** [comment]
@nicolevasilevsky according to http://purl.obolibrary.org/obo/MONDO_0100096,  the obsoleted MESH term is still extactMatch  MeSH C000657245

**Comment by sabrinatoro** [comment]
@lcdaugherty 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by lcdaugherty** [comment]
@sabrinatoro I would say this is high priority!  Thank you

**Comment by sabrinatoro** [comment]
@nicolevasilevsky @lcdaugherty 
I see in the ontology and on OLS that MeSH:C000657245 has: MONDO:equivalentObsolete.
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100096

I think this issue is resolved.

**Comment by lcdaugherty** [comment]
@nicolevasilevsky @sabrinatoro  
> OLS that MeSH:C000657245 has: MONDO:equivalentObsolete
I am sorry I do not understand this, can you please explain the reasoning for this?

This info in the database cross reference section, so does this mean that in addition to the ExactMatch data I need to cross reference the  database cross reference section to make sure it is a true ExactMatch? 

I am not sure this makes sense,  I would have thought the obsoletedMESH ID  would be removed from the ExactMatch section, or at the very least move to CloseMatch?
