### ISSUE TITLE
issues with ReadtheDocs - changes are not showing up 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2774]
Not sure who to assign this to:

I made some changes to this file (https://github.com/monarch-initiative/mondo/blob/master/docs/editors-guide/f-entities.md) and the changes are not showing up in RTD here: https://mondo.readthedocs.io/en/latest/editors-guide/f-entities/

See this PR:
https://github.com/monarch-initiative/mondo/pull/2769

**Comment by nicolevasilevsky** [comment]
Another issue:
The image is not showing up in this file:
https://github.com/monarch-initiative/mondo/blob/master/docs/developer-guide/release.md

**Comment by cmungall** [comment]
Do you mean mkdocs? We don't use rtd

**Comment by nicolevasilevsky** [comment]
Yes, that is what I mean - the editors guide

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] don't do alphabetical
- View Mondo:
AberOWL: http://aber-owl.net/ontology/MONDO/#/
BioPortal: https://bioportal.bioontology.org/ontologies/MONDO
OBO Foundry: http://obofoundry.org/ontology/mondo.html
Ontobee: http://www.ontobee.org/ontology/MONDO
Ontology Lookup Service: https://www.ebi.ac.uk/ols/ontologies/mondo
Monarch Initiative: https://monarchinitiative.org/disease/MONDO:0000001

- [ ] For browsing prioritize OLS and Monarch, but emphasize Monarch is often out of date

- [ ] presentations:
we should have just one canonical presentation

**Comment by nicolevasilevsky** [comment]
[ ] to do:
need to make it clearer which one you are in. You can't tell from these URLs which is for editors and which is for end-users. The banner on the editors guide just says "Mondo Documentation". And the editors guide contains sections like 'rare disease analysis' and a 'Developer guide' and 'changelog' that feel like they are in the wrong place.

**Comment by nicolevasilevsky** [comment]
to do - try logging into RTD and triggering

**Comment by nicolevasilevsky** [comment]
> to do - try logging into RTD and triggering

this is fixed, thanks to @cmungall and @matentzn 

I am going to close this ticket and move the website edits to another ticket b/c that is unrelated
