### ISSUE TITLE
Proxy merges when importing equvalencies

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2786]
10 proxy merges still slipped past the QC, which I noticed when I tried to tighten up the reasoning checks, not sure why:

- [x] MONDO:0006450 - MONDO:0007709
- [x] MONDO:0008078 - MONDO:0018208 - MONDO:0018975
- [x] MONDO:0008572 - MONDO:0018052 - MONDO:0020306
- [x] MONDO:0008751 - MONDO:0020489
- [x] MONDO:0011326 - MONDO:0016603
- [x] MONDO:0011849 - MONDO:0100231
- [x] MONDO:0012172 - MONDO:0016327 - MONDO:0024573
- [x] MONDO:0024573 - MONDO:0016327
- [x] MONDO:0019448 - MONDO:0000160
- [x] MONDO:0021849 - MONDO:0009155

You wouldn't see these in mondo.owl, but we need to close the QC hole for these asap. I am starting to investigate.

**Comment by matentzn** [comment]
Maybe @nicolevasilevsky this helps with tracking down the problem:
MONDO:0011849	MONDO:0100231	OMIM_607507
MONDO:0000721	MONDO:0018106	OMIMPS_278300
MONDO:0100231	MONDO:0011849	OMIM_607507
MONDO:0100241	MONDO:0002049	OMIMPS_313900
MONDO:0018106	MONDO:0000721	OMIMPS_278300
MONDO:0002049	MONDO:0100241	OMIMPS_313900

**Comment by nicolevasilevsky** [comment]
Thanks @matentzn, I will look into this
