### ISSUE TITLE
Potential reclassification of genetic cardiac tumor

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#279]
During our build of EFO 3 beta, we noticed that currently genetic cardiac tumor (MONDO:0017129) is classified as a subclass of heart cancer (MONDO_0001340). May I suggest reclassifying this as a subclass of heart neoplasm (MONDO_0021209) much like rare cardiac tumor (MONDO_0015673) instead?

**Comment by cmungall** [comment]
Thanks!

Additionally, I'm not sure sure about the name "genetic cardiac tumor", changed to "inherited". But really this classification includes Carney complex which is not itself a heart neoplasm but rather a syndrome in which heart myxomas are a feature.
