### ISSUE TITLE
merge children of EIEE1

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#28]
Currently this has 2 children reflecting the fact that Orphanet has 2 terms with an xref to  OMIM:308350 

This was the original kboom resolution:

![image](https://user-images.githubusercontent.com/50745/32986187-183f2b46-cc81-11e7-9aa2-8d12cc1edc94.png)

(see Google%20Drive/MonDO-kboom/target/img-OMIM_617132.png for full image)

These are the two Orphanet terms - note the NTBT xrefs to the same OMIM:

![image](https://user-images.githubusercontent.com/50745/32986185-fedafcac-cc80-11e7-9833-8eae895ccf63.png)

![image](https://user-images.githubusercontent.com/50745/32986190-44a05502-cc81-11e7-8282-8bc629632b4f.png)

@pnrobinson suggests merging the equivalent terms in MONDO into the parent: [EIEE1](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0010632)

**Comment by nicolevasilevsky** [comment]
looks like this has been done, this term does not have any children
