### ISSUE TITLE
A few more potential reclassifications?

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#280]
Just a couple more discrepancies we've noticed in the build of EFO version 3. I'm not 100% sure of the classification of both of these and they may not need reclassifying, so your input is appreciated!

Currently we have an import of methylcobalamin deficiency type cblDv1 ([Orphanet_308380](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_308380)) in EFO, which clashes with [MONDO_0017683](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0017683). I've tried to look into whether this disorder is with or without methylmalonic aciduria and it seems as if it is without methylmalonic aciduria, which matches the Orphanet classification and not the MONDO classification.

We also have an import of Palmoplantar keratoderma, Nagashima type ([Orphanet_140966](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_140966)). This causes problems in EFO as [MONDO_0014272](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0014272) has the parent class of nonepidermolytic palmoplantar keratoderma ([MONDO_0006588](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0006588)) alongside autosomal recessive isolated diffuse palmoplantar keratoderma ([MONDO_0020096](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0020096)). The Orphanet import of non-epidermolytic palmoplantar keratoderma ([Orphanet_2337](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_2337)) is classified as an autosomal dominant condition, which is causing discrepancies. MONDO_0006588 has an x-ref Orphanet:2337 (MONDO:equivalentTo).

Thanks!

**Comment by cmungall** [comment]
> Currently we have an import of methylcobalamin deficiency type cblDv1 (Orphanet_308380) in EFO, which clashes with MONDO_0017683. I've tried to look into whether this disorder is with or without methylmalonic aciduria and it seems as if it is without methylmalonic aciduria, which matches the Orphanet classification and not the MONDO classification.

agreed, this will be fixed

> We also have an import of Palmoplantar keratoderma, Nagashima type (Orphanet_140966). This causes problems in EFO as MONDO_0014272 has the parent class of nonepidermolytic palmoplantar keratoderma (MONDO_0006588) alongside autosomal recessive isolated diffuse palmoplantar keratoderma (MONDO_0020096). The Orphanet import of non-epidermolytic palmoplantar keratoderma (Orphanet_2337) is classified as an autosomal dominant condition, which is causing discrepancies. MONDO_0006588 has an x-ref Orphanet:2337 (MONDO:equivalentTo).

This will be fixed too. Looks like the offending axiom came from very early work on binning OMIMs into "disease clusters" (these axioms are tagged OMIM-DC, we should review any axioms that have only this as source)

We do have disjointness axioms to catch AD/AR discrepancies but we don't always assert AD/AR based on ORDO since there it sometimes means "can be AD/AR" (there are examples in ORDO where one disease has both). What do you do here?

**Comment by zoependlington** [comment]
Thanks @cmungall!

In EFO v2, we do not have any disjoint axioms to catch AD/AR, therefore in these cases we import ORDO as is and keep the asserted AD/AR. Now, with EFO 3 being built containing these AD/AR disjoint axioms, we're having to start to consider what to do with these terms, too.
