### ISSUE TITLE
 Friedreich ataxia MONDO:0009245

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2807]
Can Friedreich ataxia MONDO:0009245  be split to have the parental concept (including Orpha:95 and GARD:6468) on this term and then
--> create a new term for Friedreich ataxia 1 (MIM: 229300; & MeSH C565561; UMLS CUI: C1856689) 

I realize OMIM has FRDA and FRDA1 as alternate names for the same term, but we have users submitting on the general concept and separately on the FRDA1 sub-type and it would be nice to have distinct MONDO IDs for both terms.

**Comment by ValWood** [comment]
could not find cvterm for MONDO:0009245 - skipping annotation for SPCC1183.03c / friedreich_ataxia_1

what are the new term IDs?
I am wondering why, as the old term was specific for friedreich_ataxia_1 it could not be repurposed? This would make things easier as we wouldn't need to recurate.

**Comment by nicolevasilevsky** [comment]
The replacement term ID is: MONDO:0100339

What is cvterm?

We created a new ID because the meaning of the term changed. Here is more information about why we split terms:
https://mondo.readthedocs.io/en/latest/editors-guide/splitting-classes/

Closing but please reopen if you have any further questions, thanks!

**Comment by ValWood** [comment]
Sorry for being dim. Where can I see the new term def?
I tried monarch and OLS but I could not find it? do I need to use the Obo file?

**Comment by nicolevasilevsky** [comment]
it looks like this term does not have a definition! I can add one and it will be available in the next release.

**Comment by ValWood** [comment]
Hi Nicole,

1. Could you also provide defs for
Friedreich ataxia 1&2 (I need to figure out if I should move our annotation to a more specific term)
2. Should it be Friedreich's ataxia ? (not Friedreich ataxia )
3. Minor inconsistency. Note that one  child is upper case and one is lower.

thanks

Val

**Comment by nicolevasilevsky** [comment]
Absolutely - I will do all of the above :)

**Comment by ValWood** [comment]
I'm still a bit confused. I read 
https://mondo.readthedocs.io/en/latest/editors-guide/splitting-classes/
but in this case 2 new children were added. But the meaning of the original term , would not change so why did that need to be obsoleted and reinstated? 
Or if the old term really did represent one of the children, it could still remain, and have a new parent. Usually you would only need to obsolete if the meaning changes, and the existing term could be repurposed to the term with the same meaning. Just curious?

**Comment by kanems** [comment]
Hi @ValWood , regarding your question:
> 2. Should it be Friedreich's ataxia ? (not Friedreich ataxia )
I think the community is moving to a standard to drop the " 's " from diseases like Huntington's disease, Parkinson's disease and Freidreich's ataxia. That is what MedGen is implementing, to drop the sort of "eponymous" identification of these disorders as the preferred name for these disorders.

**Comment by ValWood** [comment]
OK thanks, interesting!

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
I think this is done. If anything else is needed, please reopen.
