### ISSUE TITLE
Merge items

### ISSUE THREAD

**Issue by stuppie** [monarch-initiative/mondo#281]
http://purl.obolibrary.org/obo/MONDO_0005318
http://purl.obolibrary.org/obo/MONDO_0004845

I think these are the same

**Comment by stuppie** [comment]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001676
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0008319

protoporphyria, erythropoietic
erythropoietic protoporphyria

**Comment by nicolevasilevsky** [comment]
Hi @stuppie Sorry for the super long delay getting to this ticket.

I will obsolete protoporphyria, erythropoietic.

Another ticket brought up the issue of canker sore and aphthous stomatitis, and it was decided these are different, I updated the definition of canker sore.

See https://github.com/monarch-initiative/mondo/issues/1262

**Comment by nicolevasilevsky** [comment]
> https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001676
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0008319

> protoporphyria, erythropoietic
erythropoietic protoporphyria

These have been updated, the latter class has been renamed to 'protoporphyria, erythropoietic, 1'

I believe this ticket can be closed.
