### ISSUE TITLE
tongue squamous cell carcinoma

### ISSUE THREAD

**Issue by stuppie** [monarch-initiative/mondo#282]
http://purl.obolibrary.org/obo/MONDO_0000500

The MESH and UMLS close matches can be removed as the exact matches are already there and correct.

**Comment by cmungall** [comment]
Should be done next release

There will be general improvements with the skos calls in the next release, as we've done a lot more work on mesh/umls integration.

**Comment by cmungall** [comment]
not quite done. The original thinking was to 're-annotate' xrefs that upstream sources may make, and to provide a clear interpretation of their semantics

On reflection it would be better to just filter noise as you suggest

I'm not sure this will be in the next release..

**Comment by cmungall** [comment]
Fixed in the specific case, and I believe in the general case too

I believe @cbizon had the same question

![image](https://user-images.githubusercontent.com/50745/45317065-b2835380-b4ed-11e8-8d8a-40b523db7692.png)
