### ISSUE TITLE
[Obsolete]  'unclassified cardiomyopathy'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2824]
**Mondo term (ID and Label)**
 'unclassified cardiomyopathy'

**Reason for deprecation**
too general/non-specific grouping class

**Suggested term to consider**
cardiomyopathy

**Comment by kallia-p** [comment]
'unclassified cardiomyopathy' was made obsolete. I removed SubclassOf all 3 children. When children were only SubClass Of unclassified cardiomyopathy I asserted 'cardiomyopathy' as the parent term i.e. Uhl anomaly didn't have any other parent term so I temporarily asserted it as SubClass Of cardiomyopathy. However after searching this term in OMIM (https://omim.org/entry/107970) I think it is similar to the Mondo term rdfs:label "arrhythmogenic right ventricular dysplasia 1" id "MONDO:0007152".  Could you please have a look at the OMIM link and let me know if you think it's a duplicate entry in which case we open another ticket for these two terms?
