### ISSUE TITLE
neuronal ceroid lipofuscinosis 6/4A ?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2825]
I am wondering about the distinction between CLN6 and CLN4A. They have the same molecular cause, but it seems ages of onset might be different? Is that why the are displayed as a Parent (4A) and child (6) relationship in MONDO? Is this the best relationship for these terms? (If anything I might think the relationship should be reverse based on the statement from OMIM below.)

Both exist as separate OMIM terms https://omim.org/entry/204300 (4A) and https://omim.org/entry/601780 (6)  but the CLN6 page states "CLN6 refers to CLN caused by mutation in the CLN6 gene, regardless of the age at onset. Thus, what was formerly called CLN4A, an adult-onset form of autosomal recessive neuronal ceroid lipofuscinosis, is now referred to as CLN6." 

OrphaNet maintains the distinction as well, and states that CLN6 is described under "Late infantile neuronal ceroid lipofuscinosis" https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=19114&disease=CLN6-disease&search=Disease_Search_Simple whereas CLN4A is described under "Adult neuronal ceroid lipofuscinosis"

Appreciate any clarification the community can give on these two terms!
@ana-rath-orphanet @ahamosh

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
@ahamosh could you please comment on this?

I don't think there is any action for Mondo.

Thanks!

**Comment by nicolevasilevsky** [comment]
There is action for us:
4A is now called 6B in OMIM. We need to review this- we may need a generic class and two children for type 6.
