### ISSUE TITLE
Visceral/total heterotaxy?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2826]
**Summary for discussion with Peter and Ada:**
See [comment](https://github.com/monarch-initiative/mondo/issues/2826#issuecomment-953250968) with figure below.

_updated 2021-10-27 NV_

----

I am trying to sort through the X-refs and mappings between MONDO:0018677 Visceral heterotaxy and its children. These are my thoughts/suggestions but I am open to other clarifications/explanations for the current structure.

The parent term of "visceral heterotaxy" (MONDO:0018677) seems to map appropriately to NCIT, OMIMPS and UMLS terms. 
But Situs ambiguus MONDO:0015522 maps to SNOMED 14821001, and SNOMED equates their own term with "Heterotaxy"/"heterotaxia". And the UMLS term that captures this SNOMED concept --“Situs ambiguus” C0266642 -- also maps the OMIM PS there.  So maybe the SNOMED term belongs on the parent header and these should be synonyms? I'm not finding a good definition for S.A. so I don't really know how this fits in the tree here, but the X-refs seem to suggest it needs further clarification or reorganization.

“Situs inversus” MONDO:0010029 should probably not X-ref OMIM:270100 , I think this would be better split out as its own concept, since this term has subsequent children and the OMIM term is a defined entity with one genetic cause/phenotype (Heterotaxy, visceral, 5).  

   Can "situs inversus totalis" then be split out as a child concept of this term?  The HPO concept for "totalis" (HP:0001696 ) is currently mapped to “Situs inversus” MONDO:0010029, however if any HPO term should be mapped to MONDO:0010029 , I would recommend "Abdominal situs inversus" HPO PT HP:0003363.

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
action items @sabrinatoro:

- [ ] SCIT:14821001 should be a dbxref on visceral heterotaxy (MONDO:0018677), MONDO:equivalentTo
- [ ] revise SCIT:14821001  xref on 'situs ambiguus' to MONDO:subClassOf
- [ ] obsolete “Situs inversus” MONDO:0010029, and create new class for situs inversus
- [ ] create new class heterotaxy, visceral, 5, dbxref OMIM:270100, MONDO:equivalentTo, child of 'visceral heterotaxy' 

> Can "situs inversus totalis" then be split out as a child concept of this term? The HPO concept for "totalis" (HP:0001696 ) is currently mapped to “Situs inversus” MONDO:0010029, however if any HPO term should be mapped to MONDO:0010029 , I would recommend "Abdominal situs inversus" HPO PT HP:0003363.

@kanems we used to have the term 'situs inversus totalis' in Mondo but it was obsoleted at some point and it looks like other sources combine these as we have done (ie, see Orphanet: https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_101063)

**Comment by ahamosh** [comment]
Hi all, I think that the OMIM Situs Inversus Viscerum alternate title on 270100 is an error.  This is a heterotaxy which is really a situs ambiguous rather than a situs inversus. Having folks look at it right now.

**Comment by nicolevasilevsky** [comment]
@sabrinatoro let's hold off on this for now until we hear back from Ada. I'll remove this from the Sept release.

**Comment by sabrinatoro** [comment]
@ahamosh 
Do you have any updates on this issue? 
Thank you!

**Comment by ahamosh** [comment]
Hi, yes, it is corrected in OMIM.  Situs Inversus Viscerum is now a formerly.
See below.  Thanks, Ada
# 270100
HETEROTAXY, VISCERAL, 5, AUTOSOMAL; HTX5

Alternative titles; symbols

SITUS INVERSUS VISCERUM, FORMERLY; SIV, FORMERLY

**Comment by sabrinatoro** [comment]
**parent term** 
id: MONDO:0018677
name: visceral heterotaxy
def: "A rare, genetic disorder in which symptoms are generally secondary to the abnormal location of the organs within the thoracic, abdominal, or peritoneal cavities. Anatomic and functional problems can include cardiac defects, intestinal malrotation leading to volvulus, biliary atresia, and various defects of the central nervous system, urinary tract, and skeleton."

**QUESTION for Ada and Peter:**
we have 2 child terms: 
- situs ambiguus (MONDO:0015522) = complete heterotaxy
- situs inversus (MONDO:0010029) = incomplete heterotaxy
Does it make sense to have these 2 child terms? or should situs ambiguus be merged to the parent term? 


Note: most of the UMLS ids report to anomalies, and not actual disease terms.

**Comment by nicolevasilevsky** [comment]
- situs ambiguus (MONDO:0015522) = heterotaxy is a syn. means not completely flipped. could be right sided, no spleen. left sides - polyspenia.
- situs inversus (MONDO:0010029) = everything as should be, but flipped (ie heart on right, etc). everything is fine otherwise.

**Comment by nicolevasilevsky** [comment]
visceral heterotaxy = heterotaxy

**Comment by sabrinatoro** [comment]
still to do: 
merge MONDO:0015522 (situs ambiguus) into MONDO:0018677 (visceral heterotaxy)
