### ISSUE TITLE
split term: mitochondrial DNA depletion syndrome 12

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2828]
**Term to split:**
MONDO:0014175 , mitochondrial DNA depletion syndrome 12

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
MONDO:0014175 , mitochondrial DNA depletion syndrome 12

*NEW* Mitochondrial DNA depletion syndrome 12b (cardiomyopathic type), autosomal recessive

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonyms that end in "1", "2", etc. should move to subclass.
OMIM: 615418
DOID_0080335
Add X-ref UMLS CUI: C3809443

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Additional comments**
Move MONDO:0014959 (mitochondrial DNA depletion syndrome 12a (cardiomyopathic type), autosomal dominant) and the new 12b terms to both be children of mitochondrial DNA depletion syndrome 12
Also note X-ref fix on mitochondrial DNA depletion syndrome 12a has DOID-0080130 : http://purl.obolibrary.org/obo/DOID_0080130 (remove from the 12 parent concept)

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
@kanems thanks for reporting this.
- I renamed MONDO:0014175 , mitochondrial DNA depletion syndrome 12 to MONDO:0014175 , mitochondrial DNA depletion syndrome 12B (cardiomyopathic type), autosomal recessive, because that is the name in OMIM
- I fixed the DO xrefs
thanks!
