### ISSUE TITLE
MIM 614204 names spread across multiple MONDO concepts

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2829]
I am trying to figure out how to best map:

> OMIM 614204, preferred name PSORIASIS 14, PUSTULAR; PSORS14
> 
> Alternative titles; symbols: 
> INTERLEUKIN 36 RECEPTOR ANTAGONIST DEFICIENCY; DITRA
> GENERALIZED PUSTULAR PSORIASIS; GPP
> PSORP
> ACRODERMATITIS CONTINUA OF HALLOPEAU
> PALMOPLANTAR PUSTULOSIS

I find: 
**MONDO:0015598** - acrodermatitis continua suppurativa of Hallopeau (X-refs Orphanet:163931 "Acrodermatitis continua of Hallopeau" )
**MONDO:0018452** - Deficiency of the interleukin-36 receptor antagonist (has a syn of "familial generalized pustular psoriasis", X-refs ORPHA:404546, which in turn cites OMIM: 614204) 
**MONDO:0013626** - psoriasis 14, pustular (This is where OMIM:614204 directly X-refs, but the SNOMED term 83839005 maps to Acrodermatitis continua of Hallopeau) 
**MONDO:0016597** - generalized pustular psoriasis (X-refs ORPHA:247353, which in turn cites OMIM: 614204 & 616106. I don't think this should be a child of the psoriasis 14, pustular term) 

I suggest that:
1, GPP term (MONDO:0016597) be moved up a level (direct child of MONDO:0005083, psoriasis), then given the children per the OrphaNet X-ref. 
2. Merge the other three MONDO IDs to represent the ONE OMIM# with multiple alternate names and external X-refs.

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
it looks like PSORIASIS 14, PUSTULAR is equivalent to INTERLEUKIN 36 RECEPTOR ANTAGONIST DEFICIENCY; DITRA in OMIM, so I think we should merge
MONDO:0018452  Deficiency of the interleukin-36 receptor antagonist with
MONDO:0013626 | psoriasis 14, pustular'

**Comment by nicolevasilevsky** [comment]
> MONDO:0013626 - psoriasis 14, pustular (This is where OMIM:614204 directly X-refs, but the SNOMED term 83839005 maps to Acrodermatitis continua of Hallopeau)

I made SNOMED term 83839005 a relatedTo dbxref on MONDO:0013626 - psoriasis 14, pustular and added it as equivalent To on Acrodermatitis continua of Hallopeau

**Comment by nicolevasilevsky** [comment]
Upon investigation, I think MONDO:0016597 generalized pustular psoriasis is equivalent to MONDO:0013626 psoriasis 14, pustular (see GRAD record): https://rarediseases.info.nih.gov/diseases/12819/generalized-pustular-psoriasis. I will merge these.

**Comment by nicolevasilevsky** [comment]
Thanks @kanems. I merged the three terms, as you suggested above, I merged them into MONDO:0013626 - psoriasis 14, pustular
