### ISSUE TITLE
add check to stop diseases like this from rising up to the top 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2832]
'regional odontodysplasia'
'segmental odontomaxillary dysplasia'

these should not be top level classes

is there a way to check for this and put up a warning?

**Comment by matentzn** [comment]
What do you mean by "rising to the top"? Higher than "Disease or Disorder"? Can you show a screenshot?

A test like this would be easy to make. We could say: all classes must be under one of the three Mondo root classes.

**Comment by nicolevasilevsky** [comment]
I meant it is a child of 'disease or disorder'

![image](https://user-images.githubusercontent.com/6722114/112025856-d8443700-8af2-11eb-98d3-47a67a19bea3.png)

**Comment by joeflack4** [comment]
I wonder if it's doing this because they're declared like that statically, or by some inference. Still a little new to this. I'm assuming these are mendelian diseases coming from OMIM? Do you think this should be an issue that I should add to [OMIM repo](https://github.com/monarch-initiative/omim/tree/main), or is something likely to be fixed here in the mondo repo?

**Comment by nicolevasilevsky** [comment]
I think this has been addressed with our recent reclassification efforts. I don't know if we really need a check for this, this is something that @sabrinatoro and I can keep an eye on.

I vote to close this issue.

cc @sabrinatoro

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I agree that this has been addressed with the reclassification efforts and we can close this issue.

The issue occurs when we obsolete a class/parent term and the children do not have any other parent. The only way to avoid such terms appearing at the high-level classification is to check what happens to the children when obsoleting a term. In other words, it is the curator's responsibility.

**Comment by nicolevasilevsky** [comment]
Agreed, I will close.
