### ISSUE TITLE
MONDO:0015601  X-linked intellectual disability, van Esch type

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2842]
Is MONDO:0015601  X-linked intellectual disability, van Esch type truly equivalent to MIM 301030 (Van Esch-O'Driscoll syndrome) ?
If so, I think it would be good to add the OMIM preferred name as a synonym on this term.
There are currently 2 concepts in UMLS for these names: VAN ESCH-O'DRISCOLL SYNDROME (C5193012) and X-linked intellectual disability Van Esch type (C4305072).

@ahamosh

**Comment by ahamosh** [comment]
As far as I can tell they are the same.  I will check with Joanna and Carol.

**Comment by ahamosh** [comment]
These are the same.

**Comment by kanems** [comment]
Thank you, Ada.

**Comment by kanems** [comment]
>  MONDO:0015601 X-linked intellectual disability, van Esch type truly equivalent to MIM 301030 (Van Esch-O'Driscoll syndrome) ?
If so, I think it would be good to add the OMIM preferred name as a synonym on this term.

@nicolevasilevsky : If the OMIM preferred name can get added as a Syn. to the MONDO term, this would close out my request.  (I have directly contacted UMLS to ask if the redundant CUIs can be merged on their end.)

**Comment by nicolevasilevsky** [comment]
@kanems the OMIM synonyms were already on that term, but I changed them to exact, instead of related.

Let me know if you'd like the label to be changed to `Van Esch-O'Driscoll syndrome`, I can do that.
