### ISSUE TITLE
[NTR] NEDMILG/Neurodevelopmental Disorder with Microcephaly, Impaired Language, and Gait Abnormalities

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#2845]
Neurodevelopmental Disorder with Microcephaly, Impaired Language, and Gait Abnormalities

**Synonyms**
NEDMILG

causative gene NARS1

**Definition**

see
https://www.omim.org/entry/108410#molecularGenetics

**Comment by nicolevasilevsky** [comment]
https://www.omim.org/entry/619091

@matentzn will this come in in an OMIM slurp?

**Comment by nicolevasilevsky** [comment]
talked to @matentzn and we are unsure why this is missing from the OMIM slurp, but I'll add this asap

**Comment by matentzn** [comment]
Wow this uncovered a bug in the ingest - thankfully not too major. Thanks. See #3009

**Comment by nicolevasilevsky** [comment]
Nice job @ValWood! You are improving Mondo in more ways than you may have realized :)
