### ISSUE TITLE
MONDO:0002520 acute hepatic porphyria

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2850]
**Mondo terms (ID and Label):**
MONDO:0002520 acute hepatic porphyria (and children, specifically: MONDO:0013000 porphyria due to ALA dehydratase deficiency)

This MONDO parent concept shares the specific preferred name from OMIM 612740; and UMLS maps this term to "Porphobilinogen synthase deficiency, UMLS CUI: C0268328" which is also where UMLS maps "Porphobilinogen synthase deficiency" SNOMEDCT_US 64081000.  Also the NCIT X-ref seems like it more closely maps with the OMIM entry (Acute Hepatic Porphyria (Code C133887): Synonyms: ALAD Deficiency, Delta-Aminolevulinate Dehydratase Deficiency, Porphobilinogen Synthase Deficiency) 

Would it be possible to rename the parent concept "Hepatic porphyria" with X-refs UMLS: C0162533, SNOMED ID 55056006, MESH D017094 instead of "acute hepatic porphyria"? 
Then have child terms of "chronic hepatic porphyria" etc. as currently displayed. (Also fixes the issue where the "chronic" form is a child of the "acute" form of the disease, which seem to me like that doesn't quite make sense.)

Renaming of the disease represented by OMIM 612740 to "porphyria due to ALA dehydratase deficiency" makes sense, but the OMIM preferred name is still Porphyria, acute hepatic, alternatively Doss hepatic porphyria, so MedGen/GTR runs into a conflict with using a parent concept for all the acute hepatic porphyrias and many of our users submit directly on the MIM names. 

@ahamosh- Would OMIM consider adjusting the preferred name on  OMIM 612740 to be a little more specific? Then MONDO can have a parent concept for AHPs, of which OMIM 612740 would be one type.

**Comment by nicolevasilevsky** [comment]
@ahamosh see above ^

**Comment by nicolevasilevsky** [comment]
@kanems I renamed MONDO_0002520 to hepatic porphyria and made acute hepatic porphyria a narrow synonym. I think that addresses all of your requests above.

MONDO_0013000 'porphyria due to ALA dehydratase deficiency' is a child (xref OMIM:612740)

**Comment by nicolevasilevsky** [comment]
I moved the xref to NCIT:C133887 acute hepatic porphyria to MONDO_0013000
