### ISSUE TITLE
MONDO:0009317, nonphotosensitive trichothiodystrophy ORPHA X-ref

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2852]
**Mondo term (ID and Label):**
MONDO:0009317,nonphotosensitive trichothiodystrophy

**Xref that should be fixed (ID and label):**
Update ORPHA:1245  to ORPHA:33364

(also the CUI from UMLS is C1955934, the other CUI from Orpha:33364 isn't current)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by kanems** [comment]
Correction: ORPHA 33364 is for the parent concept of trichothiodystrophy, I can't find a valid cross reference for nonphotosensitive trichothiodystrophy in UMLS or OrphaNet.

**Comment by nicolevasilevsky** [comment]
looks like this has been obsoleted in orphanet, I'll obsolete it in Mondo too
