### ISSUE TITLE
[Merge]'deafness-enamel hypoplasia-nail defects syndrome' and Heimler syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2857]
**Mondo term (ID and Label)**
 MONDO:0009325 'deafness-enamel hypoplasia-nail defects syndrome'

**Reason for deprecation**
duplicate

**Term to be merged with**
MONDO:0100229 Heimler syndrome

**Comment by nicolevasilevsky** [comment]
related to: https://github.com/monarch-initiative/mondo/issues/1490

**Comment by nicolevasilevsky** [comment]
- [ ] add axioms to Heimler 1 and heimler 2 (heimler syndrome and 'disease has dysfunction' some Gene)

**Comment by kanems** [comment]
I agree with this merge.
