### ISSUE TITLE
Typo in synonyms of MONDO:0008780

### ISSUE THREAD

**Issue by cthoyt** [monarch-initiative/mondo#2858]
**Mondo term (ID Label)**

`MONDO:0008780`

**Bug/Typo/Error description**

Typo in `OMIM` prefix in following synonym of OBO export:

`synonym: "amyotrophic lateral sclerosis 2" EXACT [DOID:0060194, OMIMl:205100]`

**Your nano-attribution (ORCID)**

https://orcid.org/0000-0003-4423-4370

**Comment by nicolevasilevsky** [comment]
thanks!
