### ISSUE TITLE
MONDO:0012048 endogenous depression/OMIM:608516

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2862]
**Mondo term (ID and Label):**
MONDO:0012048 endogenous depression

**Xref that should be fixed (ID and label):**
OMIM:608516  should maybe map to either "MAJOR DEPRESSIVE DISORDER; MDD" (MONDO:0002009) or the Alternative titles; symbols from OMIM-  UNIPOLAR DEPRESSION (MONDO:0005263)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
Hi @kanems this one is a bit complicated because it seems that OMIM combines several diseases in one record, where we separate them out in Mondo. 

I feel like this would be a good one to discuss with the larger group too.

**Comment by nicolevasilevsky** [comment]
to do (per discussion on Mondo call):
merge MONDO_0005263 unipolar depression with MONDO_0002009 major depressive disorder

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
