### ISSUE TITLE
OMIM:614163 (DELAYED SLEEP PHASE DISORDER, SUSCEPTIBILITY TO; DSPD)

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2863]
**Mondo term (ID and Label):**
MONDO:0013600 Insomnia (disease)

**Xref that should be fixed (ID and label):**
OMIM:614163 (DELAYED SLEEP PHASE DISORDER, SUSCEPTIBILITY TO; DSPD) move to MONDO:0024377 circadian rhythm sleep disorder, delayed sleep phase type, which lists the abbreviation DSPD [ DOID:0111141 ] 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
Maybe these should be merged? or reorganize to move the DSPD as a child term of "insomnia"?

**Comment by nicolevasilevsky** [comment]
I'm not sure if these are equivalent, I agree with your suggestion to move the OMIM xref to MONDO:0024377 circadian rhythm sleep disorder, delayed sleep phase type

I feel like this is one of those more complicated questions about susceptibility though. Maybe we could discuss at our upcoming workshop?

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
Discussed on Mondo curation call:

- [ ] create a new term: delayed sleep phase syndrome, susceptibility to

**parent:** inherited disease susceptibility
**label:** delayed sleep phase syndrome, susceptibility to
**defintion**: An inherited susceptibility or predisposition to developing delayed sleep phase syndrome.
**definition dbxref**: MONDO:patterns/inherited_susceptibility.yaml
**seeAlso**: `https://github.com/monarch-initiative/mondo/issues/2863`
**database cross reference**: OMIM:614163, source: MONDO:equivalentTo
**logical definition (Equivalent To):**

'inherited disease susceptibility'
 and ('disease has basis in dysfunction of' some CRY1)
 and ('predisposes towards' some 'circadian rhythm sleep disorder')

- [ ] on MONDO:0013600 Insomnia (disease), change source on dbxref to OMIM:614163 from MONDO:equivalentTo to MONDO:relatedTo

instructions to add new terms:
https://mondo.readthedocs.io/en/latest/editors-guide/add-new-terms/
