### ISSUE TITLE
MONDO:0011727 anorexia nervosa, susceptibility to, 1[Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2869]
**Mondo term (ID and Label)**
MONDO:0011727 anorexia nervosa, susceptibility to, 1

**Suggested revision and reasons**
Make a child of MONDO:0005351 anorexia nervosa instead of an "orphaned" child of Mendelian disease (MONDO:0003847)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I added a logical definition so this is now classified as an 'inherited disease susceptibility'
