### ISSUE TITLE
revisions to COVID-19 hierarchy

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2896]
Regarding current classification, from @cmungall 
is this the correct placement of long COVID-19? Is long covid a subtype of covid, or a consequence of it? We have a class 'post-viral disorder' where we have things like shingles (of course, long covid may not be a reactivation in the same way but the general principles re subtypes vs sequelae should apply)

proposed hierarchy from @pnrobinson:

SARS-CoV-2 infectious disease
-'acute COVID-19'
--'critical COVID-19 infection'
--'mild COVID-19 infection'
--'moderate COVID-19 infection'
--'presymptomatic COVID-19 infection'
--'severe COVID-19 infection'
-'long COVID-19'
-'MIS-A'
-'MIS-C'

**Comment by cmungall** [comment]
See the more general ticket #2893

**Comment by nicolevasilevsky** [comment]
Proposed hierarchy per Mondo call on 04/01/21:

**bold**= new term

**COVID-19 and sequelae**
-COVID-19
--Mild COVID-19
--Moderate COVID-19
-**sequelae of COVID-19**
--Long COVID-19
--'COVID-19–associated multisystem inflammatory syndrome in children'
---**acute COVID-19–associated multisystem inflammatory syndrome in children**
---**long COVID-19–associated multisystem inflammatory syndrome in children**
--'**COVID-19–associated multisystem inflammatory syndrome in adult'**
---**acute COVID-19–associated multisystem inflammatory syndrome in adult**
---**long COVID-19–associated multisystem inflammatory syndrome in adult**

**Comment by nicolevasilevsky** [comment]
from @mellybelly  
Additional synonyms for long-covid: post-acute sequelae of COVID-19, PASC, sequelae of COVID-19, long-haul COVID-19, long COVID-19

**Comment by jmcmurry** [comment]
Would love @tdbennett to take a look at this

**Comment by nicolevasilevsky** [comment]
relevant docs:
https://www.icd10monitor.com/arriving-soon-code-u09-9-post-covid-19-condition
https://www.aappublications.org/news/2020/09/01/coding090120

**Comment by nicolevasilevsky** [comment]
Note - see linked pull request for the current proposed hierarchy, also pasted below

![image](https://user-images.githubusercontent.com/6722114/113363977-3947e800-9307-11eb-9d0e-66bfcbae8582.png)

**Comment by byrdjb** [comment]
Could there be value in examining how preceding late complications of acute viral infections have been classified, for example situations enumerated in this paper? https://www.asmscience.org/content/book/10.1128/9781555815486.ch18

**Comment by pnrobinson** [comment]
I agree with @byrdjb -- this might help with the hierarchy for other infections

My one question about the COVID hierarchy is whether "asymptomatic COVID-19 infection" is really a disease? I acknowledge it might be useful to have as a term if somebody wants to use MONDO to hang data onto, but I do not think that you can have dis-ease if you have no symptoms.

**Comment by nicolevasilevsky** [comment]
Update - the current status of these revisions is as such. See screenshot:
![image](https://user-images.githubusercontent.com/6722114/113878887-dc1cbe00-976e-11eb-9958-10eff3541c51.png)

Summary of discussion via email:
- @mellybelly suggested using the preferred WHO naming for subtypes.
- from @pnrobinson:
there are a couple of difficult issues that I would like to discuss.

The "ambulatory" specification depends on availability of hospital beds, and it is probably best to just use "mild"?
This classification refers to a snapshot in time. i.e., Patient X has mild COVID-19 on Monday. But Patient X can develop severe COVID-19 on Tuesday. On the other hand, patient Y can have mild COVID-19 and recover, and in a sense, patient Y has had "pure" mild COVID-19 (one disease). Did patient X have two different diseases?
Thinking how we will try to model this computationally, if we are modelling an individual, it might be more useful to have some other way of saying that an individual has mild, moderate, severe at any one point in time? Although I agree it is useful to have these classes to hang data on.

- from @cmungall:
I agree with Peter

There are lots of issues with instantiating a disease-by-severity design pattern, in addition to the temporal issues Peter mentions. Do we do this for all diseases, or just some? what is the principle behind whether we instantiate the DP? How do we avoid annotation at multiple different levels, which is not inherently wrong, but potentially confusing.

- from @mellybelly 
I am not certain we need the subclasses of COVID-19 X severity, though it is certainly something that can be written about in the comments.
They are not considered different diseases by most people, though care IS managed quite differently.

_**Open question: **_
should we obsolete the children of COVID-19?

**Comment by byrdjb** [comment]
An observation of potential interest is that presymptomatic is a unique child in this hierarchy. That classification can be made only in retrospect since it first requires a 'state change' away from presymptomatic to symptomatic.

Do we intend to make a hierarchy constrained by what a clinician knows today, as opposed to things knowable only retrospectively? Or is that a non-issue?
