### ISSUE TITLE
Consider split of Ohtahara syndrome and EIEE

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#29]
Initial review performed by @pnrobinson 

## Ohtahara syndrome vs Early infantile epileptic encephalopathy

Excellent intro to phenomenology of seizures in infants:
http://onlinelibrary.wiley.com/doi/10.1046/j.1528-1157.43.s.3.4.x/pdf

### Early infantile epileptic encephalopathy (OMIM)

*Early infantile epileptic encephalopathy is a severe form of epilepsy first reported by Ohtahara et al. (1976). It is characterized by frequent tonic seizures or spasms beginning in infancy with a specific EEG finding of suppression-burst patterns, characterized by high-voltage bursts alternating with almost flat suppression phases. Approximately 75% of EIEE patients progress to 'West syndrome,' which is characterized by tonic spasms with clustering, arrest of psychomotor development, and hypsarrhythmia on EEG (Kato et al., 2007).*

The phenotypic series shows  ~60 Mendelian forms of Early infantile epileptic encephalopathy  (EIEE).

See also this ticket: https://github.com/monarch-initiative/mondo-build/issues/27

In addition, there are more genetic syndromes that include EIEE as a feature (Described in https://omim.org/entry/308350). 

### Orphanet

Early infantile epileptic encephalopathy					

Early infantile epileptic encephalopathy (EIEE), or Ohtahara syndrome, is one of the most severe forms of age-related epileptic encephalopathies, characterized by the onset of tonic spasms within the first 3 months of life that can be generalized or lateralized, independent of the sleep cycle and that can occur hundreds of times per day, leading to psychomotor impairment and death.

### Disease Ontology

infantile epileptic encephalopathy (DOID:2481)

The DO term has one child, early infantile epileptic encephalopathy 9, which maps to the correct OMIM term https://www.omim.org/entry/300088. However, it also has alt Ids (OMIM:300607,  OMIM:607208,  OMIM:609304,  OMIM:612164, OMIM:613402,  OMIM:613477,  OMIM:613720,  OMIM:613721,  OMIM:613722) that are other specific types of EIEE -- but they are far from complete. There is no definition of the term. It is therefore not clear if DOID:2481 intends to be a grouping term for all ~60 Mendelian forms of EIEE, or if it intends to be a grouping term for the 9 terms it has as an alt id, or why there are 9 alt ids and one child -- what distinction does DO make between alt ids and children -- as far as I can see all of the MIM ids are just particular genetic types of EIEE.

#### infantile epileptic encephalopathy

The label of the DO term is wrong. There is no “infantile” EE without “early infantile”, and there is no need to create a hierarchy of say “early” and “late” infantile epileptic encephalopathy in a way that would justify creating a grouping term called “infantile epileptic encephalopathy”.

## Ohtahara syndrome

Dr Ohtahara syndrome has the first to describe this syndrome in the literature.

Ohtahara, S., Ishida, T., Oka, E., Yamatogi, Y., Inoue, H., Karita, S., Ohtsuka, Y. On the specific age dependent epileptic syndrome: the early-infantile epileptic encephalopathy with suppression-burst. No to Hattatsu 8: 270-279, 1976. Note: Article in Japanese. 

It is currently an EXACT SYNONYM for EIEE; see:
https://www.epilepsy.com/learn/types-epilepsy-syndromes/ohtahara-syndrome
http://www.sciencedirect.com/science/article/pii/S0887899412002688
https://www.epilepsydiagnosis.org/syndrome/ohtahara-overview.html

# Summary

Based on the above it seems we want to keep them as the same concept

**Comment by cmungall** [comment]
See https://www.epilepsydiagnosis.org/

Proposed:

 * EIEE
    * Ohtahara
    * Early myoclonic encephalopathy

**Comment by nicolevasilevsky** [comment]
'Ohtahara syndrome' has been obsoleted, this can be closed.
