### ISSUE TITLE
Proposed Change to Subclassifications of Hypophosphatasia

### ISSUE THREAD

**Issue by mayherpatel** [monarch-initiative/mondo#2906]
**Mondo term (ID and Label):**
MONDO:0007798 (adult hypophosphatasia)
MONDO:0009428 (childhood hypophosphatasia)
MONDO:0009427 (infantile hypophosphatasia)
MONDO:0016606 (perinatal benign hypophosphatasia)

**Suggested new label:**

Currently, the above MONDO terms are subclassifications of the term hypophosphatasia (MONDO:0018570) and these subclasses are named based on the age of onset for hypophosphatasia (HPP)-associated features. Recently, the bone disorders field has been moving towards classifications of HPP that are based on the alleles and the severity of the phenotype. Therefore, the ClinGen Skeletal Disorders GCEP recommends an amendment for these terms.
 
We would like to make the above terms obsolete and replace them with the following terms:

1. Severe Hypophosphatasia

Severe hypophosphatasia is a rare, severe form of hypophosphatasia characterized by infantile rickets without elevated serum alkaline phosphatase (ALP) activity and a wide range of clinical manifestations due to hypomineralization. Individuals often present with these features in infancy or in the perinatal period.

2. Moderate Hypophosphatasia

Moderate hypophosphatasia is a rare, moderate form of hypophosphatasia characterized by defective mineralization of bone and/or teeth, premature loss of teeth with intact roots, and reduced serum alkaline phosphatase (ALP) activity. Individuals can present with this form of hypophosphatasia in infancy, childhood, or adulthood.

3. Mild Hypophosphtasia

Mild hypophosphatasia is the most common form of hypophosphatasia characterized by low alkaline phosphatase, unspecific clinical signs, and typically presents in individuals in adulthood.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

ClinGen Skeletal Disorders GCEP (https://www.clinicalgenome.org/affiliation/40065/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**

PMID: 32973344

**Comment by nicolevasilevsky** [comment]
@pnrobinson @ahamosh 
any objections to these new labels proposed by the ClinGen expert panel?

Maybe we should use 'attenuated' instead of mild (as has been previously proposed elsewhere)?

**Comment by pnrobinson** [comment]
I am not an expert in this field, but attenuated sounds like some factor is making a disease milder and so is a stronger statement than merely saying mild. What is the rationale for attenuated in this case?

**Comment by nicolevasilevsky** [comment]
In another conversation, @ahamosh was saying that describing a disease as mild may be offensive to a patient with that disease, so I believe the suggestion was to use attenuated instead.

Maybe using 'mild' in the label is okay in this case?

**Comment by ahamosh** [comment]
Hi All,  in the MPS group, patients were very offended by mild and so attenuated was used for mild. Severe, moderate and attenuated rather than mild.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh!

**Comment by nicolevasilevsky** [comment]
@kallia-p the action item here is to

**Add new terms:**
- [ ] Severe Hypophosphatasia
- [ ] Moderate Hypophosphatasia
- [ ] attenuated hypophosphtasia (add synonym mild hypophosphtaisia)

_(see definitions above.)_
The dbxref for the defs should be:
PMID: 32973344
and 
https://www.clinicalgenome.org/affiliation/40065/

**Obsolete these terms:**
- [ ] MONDO:0007798 (adult hypophosphatasia)
- [ ] MONDO:0009428 (childhood hypophosphatasia)
- [ ] MONDO:0009427 (infantile hypophosphatasia)
- [ ] MONDO:0016606 (perinatal benign hypophosphatasia)

for the 'consider' annotation for these terms, add consider for the 3 new terms you create above). See the obsolete instructions [here](https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#obsolete-a-class-using-protege-make-entity-obsolete-function)

**Comment by mayherpatel** [comment]
Hi Nicole,

After discussing with the ClinGen Craniofacial Malformations GCEP this is the group's response:

"The skeletal disorders GCEP reviewed this conversation and still feels that "mild" is a more appropriate disease term than "attenuated". The discussion was based on how the diagnosis would be managed clinically."

This decision was based on a vote from the entire group and discussing with the Expert Panel chair's. Would it be possible to have mild as the listed term and attenuated as a synonym? We are also happy to discuss this on a future call! Thank you!

**Comment by nicolevasilevsky** [comment]
sure thing, no problem! We'll use 'mild' as the primary label.

**Comment by kallia-p** [comment]
@nicolevasilevsky Hi Nicole, below is the editing workflow for term obsoletion as discussed in our meeting today. There is a little bit of confusion with a couple of terms to be obsoleted as they are written on the ticket request, details are under edits. 
We followed the workflow in the editors pages except that we added step 9: the annotation to 'consider the three new terms'.
Workflow:
Obsolete a class (manually)¶
1. Search for the class to be obsoleted.
2. Rename label to: obsolete [class name]. I missed this during the meeting but I added it after i.e. obsolete adult hypophosphatasia.
3. Add annotation owl:deprecated and indicate true (in literal).
4. Add annotation IAO_0000231 (has obsolescence reason - this is not labeled in Mondo) and either add an individual or add free text in the literal box, if there is not a suitable individual. (To add an individual, click the 'Entity IRI' tab, then click Individuals). We added has obsolescence reason 'out of scope'
5. Add SeeAlso with a link to the GitHub issue that requested the obsoletion. 
6. Remove superclass axioms.
7. If the class has children, remove the superclass assertions for the children.
8. If the term has database_cross_reference annotations and the source is annotated as MONDO:equivalentTo, change the source to source MONDO:obsoleteEquivalent (in the literal tab). Obsolete terms should never be equivalent.
9. Add annotation consider (not exactly as in the workflow from the editors page but you suggested to add to consider the three new terms for each term to be obsoleted)

Edits:
MONDO:0007798 (adult hypophosphatasia) - obsoleted as per our meeting. The only thing I noticed is that this term has exact synonym 'mild hypophosphatasia' which is one of the 3 new terms that we created. So I wonder if we are still OK to add the annotations to consider all  three new terms or consider just the 'mild hypophosphatasia' term. 
MONDO:0009428 (childhood hypophosphatasia) - obsoleted as per the term and workflow above with the addition of the annotation consider the 3 new terms.
MONDO:0009427 (infantile hypophosphatasia) - obsoleted as per the term above. The definition states severe so I wonder if we should just consider the annotation 'severe hypophosphatasia' only. This category has a child '*perinatal* lethal hypophosphatasia (MONDO:0016605)'  for which I removed the superclass assertion so now it is a child of 'hypophosphatasia'. But I wonder if this should be also obsoleted see typo in obsolete term no 4 as per user request below:
MONDO:0016606 (*perinatal* benign hypophosphatasia) - the ticket should actually say *prenatal* benign hypophosphatasia. Obsoleted as per the workflow.
I wonder if in the ticket meant to request both terms MONDO:0016605 and MONDO:0016606 to be obsoleted or do you think it is just a typo? Should we go back to the term requestor to clarify this?

**Comment by ValWood** [comment]
Hi Do you have the IDs for the new terms?
Thanks,

Val

**Comment by nicolevasilevsky** [comment]
severe hypophosphatasia MONDO_0600009
moderate hypophosphatasia MONDO_0600010
mild hypophosphatasia MONDO_0600011
