### ISSUE TITLE
Please delete axioms pointing to obsolete classes

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#2910]
1)
**Mondo term (ID Label)**
MONDO:0018907 craniopharyngioma

**Bug/Typo/Error description**
- [x] disease has feature some obsolete rare endocrine growth disease (MONDO:0019590)

2)
**Mondo term (ID Label)**
MONDO:0019138 bleeding diathesis due to a collagen receptor defect

**Bug/Typo/Error description**
- [x] Equivalent to: obsolete hemorrhagic disorder due to a qualitative platelet defect (MONDO:0017142) and disease caused by disruption of some collagen receptor activity
- [x] Subclass of: obsolete hemorrhagic disorder due to a qualitative platelet defect (MONDO:0017142)

3)
**Mondo term (ID Label)**
MONDO:0005902 peanut allergic reaction

**Bug/Typo/Error description**
- [x] Equivalent to: obsolete nut allergic reaction and disease has location some pigmented ciliary epithelial cell
- [x] Subclass of: obsolete nut allergic reaction

Could you please remove the axioms pointing to the recently obsoleted classes in parentheses? They are breaking EFO. I'll fix them there, and we'll release EFO on April 15th, so it'll be ok as long as ithey are fixed in Mondo before your next release please. Thanks.
(Also, is it possible that Mondo may need stricter automated checks in place, to avoid obsoleted classes creeping in again? :-) )

**Comment by nicolevasilevsky** [comment]
> Also, is it possible that Mondo may need stricter automated checks in place, to avoid obsoleted classes creeping in again? :-) 

Very good point!

@matentzn is this something we could implement?

**Comment by matentzn** [comment]
It is very hard to believe there is no check for that! We should probably prioritise moving to ROBOT report in ERROR mode.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky @matentzn 

> > Also, is it possible that Mondo may need stricter automated checks in place, to avoid obsoleted classes creeping in again? :-)

To be more precise I should have written "to avoid _references to_ obsoleted classes creeping in again". Also to specify, those references are not breaking the EFO build for us strictly speaking, but they are flagged as errors (not warnings) and they cause issue for our downstream consumers. Thank you Nicole for addressing my request so promptly. Have a good weekend everyone!

**Comment by matentzn** [comment]
Thanks a ton @paolaroncaglia . Indeed, there was no automatic check.. The last ROBOT reports shows these:

ERROR	deprecated_class_reference	blank node	owl:someValuesFrom	<http://purl.obolibrary.org/obo/MONDO_0019590>
ERROR	deprecated_class_reference	MONDO:0006872	rdfs:subClassOf	<http://purl.obolibrary.org/obo/MONDO_0005902>
ERROR	deprecated_class_reference	MONDO:0017142	rdfs:subClassOf	<http://purl.obolibrary.org/obo/MONDO_0019138>
ERROR	deprecated_class_reference	MONDO:0018907	owl:someValuesFrom	<http://purl.obolibrary.org/obo/MONDO_0019590>

Once this is fixed, it won't happen again, see #2915

**Comment by nicolevasilevsky** [comment]
I think these are all taken care of now. There are some cases where there is an excluded subclass pointing to an obsolete term, but I think that is okay?

'acquired primary ovarian failure'
![image](https://user-images.githubusercontent.com/6722114/114473797-beee5200-9ba9-11eb-95a6-6cbd1693bdc9.png)

**Comment by matentzn** [comment]
This is all done and can be closed! (ran tests again)
