### ISSUE TITLE
ROBOT report April 2021

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2916]
I will now switch ROBOT report to fail on ERROR, so we get the additional layer of security. Here some errors we need to take care off:

- [x] ERROR	duplicate_definition	MONDO:0100237	IAO:0000115	An instance of cutis laxa that is inherited.
- [x] ERROR	duplicate_definition	MONDO:0100238	IAO:0000115	An instance of cutis laxa that is inherited.
- [x] ERROR	deprecated_class_reference	blank node	owl:someValuesFrom	 <http://purl.obolibrary.org/obo/MONDO_0019590>
- [x] ERROR	deprecated_class_reference	MONDO:0006872	rdfs:subClassOf	<http://purl.obolibrary.org/obo/MONDO_0005902>
- [x] ERROR	deprecated_class_reference	MONDO:0017142	rdfs:subClassOf	<http://purl.obolibrary.org/obo/MONDO_0019138>
- [x] ERROR	deprecated_class_reference	MONDO:0018907	owl:someValuesFrom	<http://purl.obolibrary.org/obo/MONDO_0019590>

See also #2910

**Comment by nicolevasilevsky** [comment]
>  ERROR deprecated_class_reference blank node owl:someValuesFrom http://purl.obolibrary.org/obo/MONDO_0019590

what does this mean?

**Comment by nicolevasilevsky** [comment]
>  ERROR deprecated_class_reference MONDO:0006872 rdfs:subClassOf http://purl.obolibrary.org/obo/MONDO_0005902

Not sure what this means? Is this still an issue? Maybe it has been fixed.

**Comment by matentzn** [comment]
This can be closed, remaining items fixed in #2920

**Comment by nicolevasilevsky** [comment]
thank you!
