### ISSUE TITLE
NTR: Exudative vitreoretinopathy 7

### ISSUE THREAD

**Issue by alexhenrie** [monarch-initiative/mondo#292]
Should be a child of [exudative vitreoretinopathy](https://monarchinitiative.org/disease/MONDO:0019516). See https://www.omim.org/entry/617572

**Comment by alexhenrie** [comment]
Never mind, this term was recently added.

**Comment by cmungall** [comment]
Hi @alexhenrie - thanks a lot for contributing. It looks like you were super-unlucky in your timing and you made all your requests right before a release with a batch of new terms came out! Sorry about that!

**Comment by alexhenrie** [comment]
You're welcome, and I do regret the mixup. I checked all the other tickets I submitted to make sure that those terms are not in the latest Mondo.
