### ISSUE TITLE
OMIM:300100, Adrenoleukodystrophy

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2922]
**Mondo term (ID and Label):**
X-linked cerebral adrenoleukodystrophy, MONDO:0010247

**Xref that should be fixed (ID and label):**
OMIM:300100 (Orphanet:139396) 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
It seems to me that the MIM number should be moved to the parent concept (X-linked adrenoleukodystrophy, MONDO:0018544)  since this one term encompasses multiple forms of ALD. UMLS maps the MIM # to the same term with MESH D000326 (Adrenoleukodystrophy, C0162309)  I see OrphaNet maps OMIM 300100 specifically to X-linked cerebral adrenoleukodystrophy, but I'm not sure I understand why.

**Comment by nicolevasilevsky** [comment]
I agree, will fix

**Comment by nicolevasilevsky** [comment]
The mapping from Orphanet to OMIM is NTBT (narrow to broad term)
