### ISSUE TITLE
MONDO:0054559 CDGIIq and COG2-CDG [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2923]
**Mondo term (ID and Label)**
MONDO:0054559 congenital disorder of glycosylation, type IIq

**Reason for deprecation**
The CDGs are now named based on the genetic/molecular cause, and the type I/II and alphabetic letter nomenclature has been retired (though many papers will still acknowledge the "formerly known as..." in the abstract).  See https://www.ncbi.nlm.nih.gov/books/NBK453041/ 

**Term to be merged with**
MONDO:0018568, COG2-CDG

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by pnrobinson** [comment]
This is similar to the current discussion on naming. I think our policy is to use type IIq as the primary name (type IIq is caused by mutations in COG2).
@ahamosh thoughts?

**Comment by ahamosh** [comment]
Exactly what Peter said.  We (OMIM) are keeping the IIq.  We aren't going to lead with the gene when naming a disease.

**Comment by kanems** [comment]
I agree that leading with the gene name is not great practice, but that is what the CDG community seems to use. Thanks, all!

**Comment by pnrobinson** [comment]
@kanems I think it would be good to add the CDG community names as synonyms and to use the OMIM names as our primary labels -- with a few flaws that we should fix, they are an overall community standard and consistent across the "Mendeliome".

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
