### ISSUE TITLE
MONDO:0003157 Gorham disease [Rename]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2931]
**Mondo term (ID and Label):**
MONDO:0003157 Gorham disease

**Suggested new label:**
Disappearing bone disease (based on SNOMED_CT preferred name SCTID: 240161003)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
This concept may be related to MONDO:0007414 "Gorham-Stout disease" 

Based on the MESH definition for "Gorham disease" on this page: ("Syndromes of bone destruction where the cause is not obvious such as neoplasia, infection, or trauma. The destruction follows various patterns: massive (Gorham disease), multicentric (hajdu-cheney syndrome), or carpal/tarsal. ") this maybe should be a parent concept to Gorham-Stout (aka Gorham disease) with Hajdu-Cheney syndrome (UMLS C0917715, SCITD 63122002) as a second child term.

**Comment by nicolevasilevsky** [comment]
Note to self - I need to look into this more closely. 
'Gorham disease' and 'Gorham-Stout disease' may be the same?

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by sabrinatoro** [comment]
Based on definition and database_cross_references of the different terms the current MONDO:0003157 (Gorham disease) refers to a parent concept, which should have 2 children terms: 
- MONDO:0007414 "Gorham-Stout disease" (=massive destruction)
- MONDO:0007057 “acroosteolysis dominant type” (=Hajdu-cheney syndrome, multicentric)

The name "Gorham disease" refers to "massive osterolysis", i.e. MONDO:0007414 "Gorham-Stout disease"
