### ISSUE TITLE
MONDO:0016824 (infantile) myofibromatosis

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2933]
**Term to split:**
MONDO:0016824  myofibromatosis
**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
Myofibromatosis
Infantile myofibromatosis (set as a child of the above term)

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonynms that end in "1", "2", etc. should move to subclass.
OMIMPS:228550
Orphanet:2591
GARD:0002998
(Also add UMLS C0432284 and SCTID: 73767002) 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by sabrinatoro** [comment]
Splitting this term into  ‘Myofibromatosis’ and ‘Infantile myofibromatosis’ (which would be a child of myofibromatosis) would introduce a term with only 1 child, which will result in a QC check failure. 

Looking into this term (definition and publications), it looks like Myofibromatosis (MONDO:0016824) refers specifically to ‘infantile myofibromatosis’
**Therefore I suggest that we keep Myofibromatosis (MONDO:0016824) as is, but rename it ‘infantile myofibromatosis’ for clarity. @kanems and @nicolevasilevsky, would you agree?**
 
Note: The adult counterpart of infantile myofibromatosis is rare and is known as myofibroma. I couldn’t find any reference for this adult-onset disease in any databases (note that myofibroma (MONDO:0006312) also refers to an infantile disease). 
Does it make sense to create a new term for this adult version of the disease? If so, we can create a NTR for 'myofibroma, adult onset' (though we would have to think about the naming of this disease to avoid confusion between this new term and the existing myofibroma term)
some references: 
[here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4379250/)
[here](https://www.sciencedirect.com/science/article/abs/pii/S0363502315014653#:~:text=The%20adult%20counterpart%20of%20infantile%20myofibromatosis%20is%20known%20as%20myofibroma,of%20the%20head%20and%20neck.&text=Histologically%2C%20the%20biphasic%20pattern%20is,plump%20nuclei%20(mature%20myofibroblasts))

**Comment by kanems** [comment]
It seems the two terms may be used interchangeably. We can use the HPO concept for "myofibromatosis" and put a Mondo ID on the infantile form. I will follow up with UMLS to get their input/clarification on having separate CUIs for Infantile myofibromatosis and myofibromatosis (esp. when their x-ref'd terms use those terms synonymously, esp NCI:C3742. )

**Comment by nicolevasilevsky** [comment]
I agree @sabrinatoro. Also, it looks like OMIMPS:228550 is named Infantile myofibromatosis, so we should follow their label, and rename our class as such.

It seems like myofibroma and myofibromatosis may be used interchangeably in the adult form and it seems like this is a legitimate new class that should be added. 

@fragosog - could I ask you and the NCIt team your thoughts on this? Do you think there should be a new class for 'myofibroma, adult onset' and a grouping class for myofibroma? Do you think myofibroma and myofibromatosis are synonymous and should be grouped together? Thank you!

**Comment by sabrinatoro** [comment]
Note: 
I renamed Myofibromatosis (MONDO:0016824) to ‘infantile myofibromatosis’.
I will create a new GH issue if we want a new class for 'myofibroma, adult onset' and/or a grouping class for myofibroma?

**Comment by nicolevasilevsky** [comment]
let's leave this open until we hear back from NCIT

**Comment by nicolevasilevsky** [comment]
@sabrinatoro 
from the NCIT team:
The EVS NCIt Team has reviewed your comments. We recommend leaving myofibromatosis and myofibroma as is. The former is multifocal and the latter is solitary. Myofibroma usually occurs in infants/young children. Rare adult forms of myofibroma have also been described.

I think this can be closed.
