### ISSUE TITLE
New term request "Familial hemophagocytic lymphohistiocytosis"

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2934]
Another example: 
ORPHA:540 "Familial hemophagocytic lymphohistiocytosis" is currently mapped to MONDO:0009974 "familial hemophagocytic lymphohistiocytosis type 1" 
The Orpha:540 term maps to OMIM: 267700 , 603552 , 603553 , 608898 , 613101
ON MONDO:0009974, there is only 267700. Suggest making a new term for ORPHA:540 "Familial hemophagocytic lymphohistiocytosis", then setting the MIM subtypes as children of the orphaNet term.

_Originally posted by @kanems in https://github.com/monarch-initiative/mondo/issues/2693#issuecomment-805888503_

**Comment by kanems** [comment]
Orphanet:540 should have it's own term. and I think MIM number for phenotypic series: PS267700 would map to the same concept.

**Comment by sabrinatoro** [comment]
The term 'familial hemophagocytic lymphohistiocytosis type 1' (MONDO:0009974) needs to be split to(i.e obsoleted and replaced by ):
- familial hemophagocytic lymphohistiocytosis  - MONDO:0700058 (referring to Orphanet:540)
- familial hemophagocytic lymphohistiocytosis type 1 - MONDO:0700059 (OMIM:267700)

**Comment by sabrinatoro** [comment]
Hello @kanems
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by kanems** [comment]
Hi @sabrinatoro, I see this was closed recently, but the terms are not on the browser yet... will these new terms go out in the August release?

**Comment by sabrinatoro** [comment]
Hi @kanems 
Yes, these terms will be in the upcoming release, at the beginning of August. You will be able to see the terms in your browser as soon as it has updated (I know that OLS takes about a week to update after the release is out).
