### ISSUE TITLE
Antenatal Bartter syndrome [NTR]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2935]
**Preferred term label:**
Antenatal Bartter syndrome
(ORPHA:93604)

**Synonyms**
Bartter syndrome, furosemide type
Bartter syndrome, furosemide-amiloride type
Hyperprostaglandin E syndrome

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
"A phenotypic variant of Bartter syndrome presenting antenatally with maternal polyhydramnios, pre-term delivery and postnatally with polyuria, and nephrocalcinosis. Hypokalemic alkalosis, increased levels of plasma renin and aldosterone, low blood pressure and vascular resistance to angiotensin II are characteristically associated. Genotypically they comprise Type 1 and Type 2 Bartter syndrome" from Orpha:93604

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0015231 Bartter syndrome

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
Bartter syndrome types 1, 2 and 5 (MONDO:0011127; MONDO:0009424, MONDO:0010503)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

Note: this is another example for #2693 (the Orpha:93604 is currently lumped in with subtype 1_

**Comment by nicolevasilevsky** [comment]
@kanems looks like we already have this term in Mondo - I will look more closely at your ticket later though to make sure I'm properly answering the question here

MONDO_0011127 'Bartter disease type 1'
