### ISSUE TITLE
Duplicate exact synonyms spring clean

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2939]
During our last QC call we decided to finally tackle our duplicate exact synonym problem. This is how we will solve it:

- [ ] Finish fixing https://docs.google.com/spreadsheets/d/1oR9xh0Rifg-nUMu87cTjTT3-d9YcX6GELXFTEdlA_ho/edit#gid=0
- [ ] Update from master and merge #4958 when it passes

**Comment by matentzn** [comment]
Supercedes https://github.com/monarch-initiative/mondo/issues/1145

See also:
- https://github.com/monarch-initiative/mondo/issues/1745
- https://github.com/monarch-initiative/mondo/issues/2386
- https://github.com/monarch-initiative/mondo/issues/2629

**Comment by matentzn** [comment]
Here is the [google sheet](https://docs.google.com/spreadsheets/d/13eIa2Ihe6ChwOjH0s-8hp0K9IGMtveIqpFTtVvuvWK4/edit#gid=720772883)

**Comment by nicolevasilevsky** [comment]
@sabrinatoro perhaps we can work on this together. Assigning you just to remind us to look at this together when we're at Melissa's next week

**Comment by matentzn** [comment]
Sorry this is a huge list (between 500~700 cases). Maybe @sabrinatoro you could think of a better strategy to deal with this. 

[report-duplicate-exact-synonym.txt](https://github.com/monarch-initiative/mondo/files/7459462/report-duplicate-exact-synonym.txt)

BTW the old query still seems to work: https://api.triplydb.com/s/b0PyFNUkb

Trying to run this with ROBOT now.

**Comment by matentzn** [comment]
I made a much better query that suggests that there are only 300 cases left:

https://api.triplydb.com/s/HtSFrTMyL

**Comment by nicolevasilevsky** [comment]
this is the most up-to-date report: https://docs.google.com/spreadsheets/d/1R4bpzmxisn3Ia0tVMn5iYAk-xXGONUyHexOEOlqBRqM/edit#gid=1567692562

I suggest this approach:
- remove synonyms from obsolete terms
- if it is an abbreviation, just leave it
- for most other synonyms, the synonym scope can be change to broad for one of the synonyms in most cases

**Comment by nicolevasilevsky** [comment]
Note, we need to be careful with capitalization (see #4469)

**Comment by matentzn** [comment]
I would like to close this ticket with a QC check; can we spend 5 minutes during our call on Thursday to finish?

**Comment by nicolevasilevsky** [comment]
yes!

**Comment by nicolevasilevsky** [comment]
to do: review the remaining synonyms on the [list](https://docs.google.com/spreadsheets/d/1R4bpzmxisn3Ia0tVMn5iYAk-xXGONUyHexOEOlqBRqM/edit#gid=1567692562). If they are not abbreviations, they probably shouldn't both be exact.

Nico is going to send me an updated list.

**Comment by matentzn** [comment]
Maybe I did something wrong, I reran the pipeline and got 400 hits - maybe the query is wrong, can you review and let me know? (I added a new sheet after your one)

I have not yet excluded abbreviations, that should narrow it down.

**Comment by nicolevasilevsky** [comment]
Hey Nico,
Upon spot-checking the new spreadsheet, I think this looks correct. That would be great if you could filter out the abbreviations.

---
I came across a couple of cases (and there are probably more) where the synonym is deprecated - see:

Synonym: 
Cushing syndrome		
MONDO:0003009 Cushing syndrome dbxref: DOID:446

the dbxref from DOID:446 is deprecated.

Would it be possible to exclude these from the QC check too? this would probably narrow down the list too.

Thank you!

**Comment by nicolevasilevsky** [comment]
@matentzn also - the term labels in Column E ?term:label2 appear to be incorrect, they are the labels for term:label1

**Comment by matentzn** [comment]
Very difficult to exclude deprecated ones.. It will make the test much slower. Lets see what we get and work on it slowly slowly at our leasure.

**Comment by matentzn** [comment]
This is the current list:

https://github.com/monarch-initiative/mondo/blob/master/src/ontology/reports/report-duplicate-exact-synonym.tsv

**Comment by matentzn** [comment]
This is the current list:

https://github.com/monarch-initiative/mondo/blob/master/src/ontology/reports/report-duplicate-exact-synonym.tsv

**Comment by nicolevasilevsky** [comment]
thank you @matentzn I will work on this!

**Comment by nicolevasilevsky** [comment]
I think this is done @matentzn!

**Comment by matentzn** [comment]
I redid the analysis, and there are quite a few more cases, my guess is around 200, but could be less (don't be discouraged by the number of rows, there are many duplicates in the end. 456 means that at most 228 cases, but likely < 200. Best guess: 180):

https://docs.google.com/spreadsheets/d/1oR9xh0Rifg-nUMu87cTjTT3-d9YcX6GELXFTEdlA_ho/edit#gid=0

I updated the things in there first comment of this issue that need to be done to satisfy this ticket, and then that's it.

**Comment by nicolevasilevsky** [comment]
@matentzn in row 3, it is checking the label matches the synonym - but this is allowed right? This is the ClinGen preferred label, which we add as an exact synonym.

?entity | ?property | ?value
-- | -- | --
MONDO:0020720-MONDO:0010619 | rdfs:label-rdfs:label | X-linked hypophosphatemic rickets

**Comment by matentzn** [comment]
Not across classes!! Only within classes it is allowed..

**Comment by nicolevasilevsky** [comment]
Oh, I see what you mean. Thanks!
