### ISSUE TITLE
NTR: Fanconi Anemia Complementation Group W

### ISSUE THREAD

**Issue by alexhenrie** [monarch-initiative/mondo#294]
Should be a child of [Fanconi anemia](https://monarchinitiative.org/disease/MONDO:0019391). See https://www.omim.org/entry/617784

**Comment by cmungall** [comment]
This was added in the most recent release from last week:  [MONDO:0044325](http://purl.obolibrary.org/obo/MONDO_0044325) ! fanconi anemia, complementation group W

**Comment by alexhenrie** [comment]
The link you shared gives a 404 Not Found error. Where can I download last week's release from?

**Comment by alexhenrie** [comment]
OK, http://purl.obolibrary.org/obo/mondo.owl has the latest release. I downloaded this file and thought I was working from it, but I was actually working from an older release, sorry.
