### ISSUE TITLE
MONDO:0022672  autosomal dominant cataract [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2951]
**Mondo term (ID and Label)**
MONDO:0022672  autosomal dominant cataract

**Suggested revision and reasons**
Maybe Move this to be a direct child of  MONDO:0005129 "cataract (disease)" then set it to have children from the MIM PS116200 that are autosomal dominant inheritance? 
(MESH has a supplementary concept for Cataract, autosomal dominant, but it treats it as syn. with cataract 9, multiple types (MONDO:0011413), but this seems incorrect. )

Optionally: Obsolete this term. This GARD page is basically empty, it's hard to tell what disorder this citation is referring to. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
@nicolevasilevsky I reviewed this issue, and I am proposing the following. Please review and advise. Thank you! 

**MONDO:0022672 : autosomal dominant cataract** 
This term is already a direct child of MONDO:0005129 "cataract (disease)" 
However, it should get the Equivalent Axiom (patterns/autosomal_dominant): 
 ‘cataract (disease)’ and ‘'has modifier’ some ‘autosomal dominant inheritance’

**Children of 'autosomal dominant cataract'**
A list of possible children, and proposed updates can be found [here](https://docs.google.com/spreadsheets/d/1pF_kJodM50hTW_tV74pJZb6mKFcGoDe9C5vrWXYP5Cc/edit?usp=sharing) 
Note that these candidates were found by searching Mondo for the words "autosomal dominant" and "cataract"
