### ISSUE TITLE
MONDO:0010470  Baratela-Scott syndrome [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2961]
**Mondo term (ID and Label)**
MONDO:0010470  Baratela-Scott syndrome 

**Reason for deprecation**
The MIM number on this term has moved  (OMIM:300881 MOVED TO 615777) https://omim.org/entry/300881

**Term to be merged with**
MONDO:0014343 
Desbuquois dysplasia 2

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @kanems
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
