### ISSUE TITLE
[NTR] down syndrome children

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2972]
need to add DS children (or synonyms):

- Complete trisomy 21
- Mosaic trisomy 21
- Translocation Down syndrome
- Mosaic Translocation Down Syndrome
- Partial Trisomy 21 (only a part of chromosome 21 is present in 3 copies)

**Comment by nicolevasilevsky** [comment]
to do:
For these new terms, we'll need to look up definitions, decide on superclasses, etc.

**Comment by mellybelly** [comment]
@nicolevasilevsky perhaps we can have a special session with the INCLUDE data stewards to review these new terms

**Comment by nicolevasilevsky** [comment]
@mellybelly I love this idea!

**Comment by nicolevasilevsky** [comment]
@kallia-p I am going to remove this from the Curation board for now, I will work on the definitions and then you could add the terms later when it's ready to go.

**Comment by jaeddy** [comment]
Somewhat (maybe not totally related), one of our colleagues was recently asking about ontology terms for Alzheimer's disease patients with Down syndrome (or vice versa?). My rough understanding is that the intersection of those conditions represents a distinct disease and/or phenotype that would be helpful to describe in a standard way.

**Comment by nicolevasilevsky** [comment]
Per Angela:
there is Emory's coding as well:
Type of Trisomy 21:

1=standard trisomy 21
2=mosaic
3=trisomy 21 plus another chromosome variation including translocations'
4=other karyotype
5=likely to be standard trisomy 21 (includes chart review and parental report)
6=likely to be mosaic (includes chart review and parental report)
7=likely to be translocation (includes chart review and parental report)
8=Down syndrome only, type unknown
9=karyotype unknown/not available

Note- Nicole, Angela and Tracie R are scheduled to meet to discuss this on May 25.

**Comment by sabrinatoro** [comment]
related to #3160
