### ISSUE TITLE
Synonyms that equal a label should be removed

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2979]
See [here](https://api.triplydb.com/s/5NLruOV_O)

```
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?term ?related
WHERE 
{ 
  { 
    ?term oboInOwl:hasRelatedSynonym ?related ;
      rdfs:label ?related ;
      a owl:Class .
      [
         a owl:Axiom ;
           owl:annotatedSource ?term ;
           owl:annotatedProperty oboInOwl:hasRelatedSynonym ;
           owl:annotatedTarget ?related ;
           oboInOwl:hasDbXref ?xref ;
      ] .
    
    FILTER (isIRI(?term) && regex(str(?term), "^http://purl.obolibrary.org/obo/MONDO_"))
  }
}
```

There are about 500 such cases. The solution should be easy:

Just delete the synonym! (Right @cmungall?)

Thank you @kshefchek for reporting.

**Comment by nicolevasilevsky** [comment]
we should make them EXCLUDE 
Synonym to be removed from public release but maintained in edit version as record of external usage

**Comment by nicolevasilevsky** [comment]
per discussion w/ @matentzn, we will flag these all for exclusion

**Comment by matentzn** [comment]
exact/label is not a major problem.. Lets ignore that. Any other one however is a problem.
