### ISSUE TITLE
MONDO:0001948 Riedel's fibrosing thyroiditis [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2980]
**Mondo term (ID and Label)**
MONDO:0001948 Riedel's fibrosing thyroiditis  

**Reason for deprecation**
Per NCIT C35827 and ORPHA:64744, these terms are synonymous 

**Term to be merged with**
MONDO:0018992 IgG4-related thyroid disease 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
CUI from UMLS:C1335787 is no longer current, this X-ref should not be displayed as current/correct on the merged term.

**Comment by sabrinatoro** [comment]
Hello @kanems
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
