### ISSUE TITLE
MONDO:0004620 and MONDO:0020330 [Merge?]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2981]
**Mondo term (ID and Label)**
MONDO:0020330 classic Hodgkin lymphoma, lymphocyte-depleted type

**Reason for deprecation**
Seems to be redundant with second concept; based on Orpha:98846 mapping to UMLS and where UMLS maps the SCTID 118610003 .  But the NCIT C9125 is specific for the adult-onset form... so maybe this isn't a merge but rather a clean up of the names/concepts (Make Hodgkin's lymphoma, lymphocytic depletion clearly the "adult" onset form, set it as a child of the above term?)

**Term to be merged with**
MONDO:0004620  Hodgkin's lymphoma, lymphocytic depletion

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @kanems
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
