### ISSUE TITLE
reclassify micropthalmia, Lenz type

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2999]
**Mondo term (ID and Label)**
MONDO:0018924 / microphthalmia, Lenz type
MONDO:0010671/microphthalmia, syndromic 1
MONDO:0010261/microphthalmia, syndromic 2
MONDO:0100124/NAA10-related syndrome
**Reason for review**  (I think there is a merge in here somewhere, or maybe just revision of relationships)
Orphanet uses microphthalmia, Lenz type and provides the pointers to MCOPS1 and MCOPS2 in OMIM (https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=568), suggesting that Lenz type is defined by X-linked inhertance, to which NAA10 (type 1) and BCOR (type 2) contribute.  If that is the case, Lenz should not be a child of NAA10-related syndrome; only MCOPS1 should be and MONDO:0010261 should be sibling of MONDO:0010671

I am not sure of the distinction between MONDO:0100124/NAA10-related syndrome and MONDO:0010671/microphthalmia, syndromic 1, given that both are based on NAA10.  Are they just different labels for the same syndrome?

**Comment by sabrinatoro** [comment]
Hello @maglott 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
> I am not sure of the distinction between MONDO:0100124/NAA10-related syndrome and MONDO:0010671/microphthalmia, syndromic 1, given that both are based on NAA10. Are they just different labels for the same syndrome?

MONDO:0100124 NAA10-related syndrome is a grouping class that clingen requested.

@sabrinatoro and I addressed your other comments above, thanks for reporting this.
