### ISSUE TITLE
sparql query to generate equivalence axioms not working

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#3]
```
prefix owl: <http://www.w3.org/2002/07/owl#>


CONSTRUCT {
  ?c <http://www.w3.org/2002/07/owl#equivalentClass> ?xcURI 
}
WHERE {
 ?c <http://www.geneontology.org/formats/oboInOwl#hasDbXref> ?x .
 ?a <http://www.w3.org/2002/07/owl#annotatedSource> ?c .
 ?a <http://www.w3.org/2002/07/owl#annotatedProperty> <http://www.geneontology.org/formats/oboInOwl#hasDbXref> .
 ?a <http://www.w3.org/2002/07/owl#annotatedTarget> ?x .
 ?a <http://www.geneontology.org/formats/oboInOwl#source> ?v3 .
 FILTER (strStarts(?v3,"MONDO:equivalent"))
 BIND (
    uri(replace(
        concat("http://purl.obolibrary.org/obo/",
               replace(?x, ":", "_")),
        "http://purl.obolibrary.org/obo/Orphanet_",
        "http://www.orpha.net/ORDO/Orphanet_"))
    AS ?xcURI)
}



```

generates empty axioms

without the `URI(...)` it almost works, except literals are generated

**Comment by cmungall** [comment]
This is intentional, the first arg to replace is something like $OBO/Orphanet:nnn or $OBO/EFO:nnn. The former ones should be switched, the latter ones OK.

It does work as intended without the `uri`, expect they are literals. I wonder if jena sparql uri function is broken?

**Comment by balhoff** [comment]
Oh I see, I read it wrong. Have you tried IRI() or URI() instead of uri()?

**Comment by nicolevasilevsky** [comment]
@cmungall @balhoff has this been fixed? Can this be closed?

**Comment by balhoff** [comment]
I'm not sure.

**Comment by nicolevasilevsky** [comment]
This is a super old ticket, I will close. @cmungall please reopen if this is still needed.
