### ISSUE TITLE
classic Hodgkin lymphoma, mixed cellularity type MONDO:0020328[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3000]
**Mondo term (ID and Label)**
MONDO:0020328 classic Hodgkin lymphoma, mixed cellularity type 

**Reason for deprecation**
Appears to be redundant term for the same disease concept (ICD10:C81.2 is shared across both terms, disease names seem to be the same concept)

**Term to be merged with**
MONDO:0004633 Hodgkin's lymphoma, mixed cellularity

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @kanems
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
