### ISSUE TITLE
MONDO:0004604 & MONDO:0020329 lymphocyte rich Hodgkin lymphoma [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3001]
**Mondo term (ID and Label)**
classic Hodgkin lymphoma, lymphocyte-rich type MONDO:0020329 

**Reason for deprecation**
It seems like this is redundant with the term below.  Orphanet:98845 maps to UMLS: C1266194 and UMLS treats terms "Lymphocyte-rich classical Hodgkin lymphoma" (source SCITD 118607005, et al.) and "Hodgkin's disease, lymphocytic-histiocytic predominance" as synonyms. Also the syns on the term below include "lymphocyte rich Hodgkin lymphoma" 

**Term to be merged with**
MONDO:0004604 Hodgkin's lymphoma, lymphocytic-histiocytic predominance 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @kanems
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
