### ISSUE TITLE
[NTR] new lung terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3026]
On the Mondo call today we met with Matthias Griese- a pulmonary expert and he recommended additions of lung disease terms, outlined in this doc:
https://docs.google.com/document/d/1fP9eInb-xFvtuA7rJg-c8JInWA2pmTjy/edit#

@laurenechan and I will work on the exposure-related terms together.

Matthias' ORCID: https://orcid.org/0000-0003-0113-912X

cc @pnrobinson @cmungall

**Comment by nicolevasilevsky** [comment]
@kallia-p I created a spreadsheet [here](https://docs.google.com/spreadsheets/d/1dpe72J6lLvkPzieMqll6t_8UDePTPiKYXcowjDMW6rI/edit#gid=2145659858) with new terms that need to be added (see tab NewTerms). If you could start adding those terms, that would be great. I'll keep adding additional terms from my [notes](https://docs.google.com/document/d/1fP9eInb-xFvtuA7rJg-c8JInWA2pmTjy/edit#).

Any cell with yellow highlighting needs to be filled in - if you could look up definitions for term and add them as needed, that would be great, thank you.

**Comment by kallia-p** [comment]
@nicolevasilevsky See also updated spreadsheet.

**Comment by nicolevasilevsky** [comment]
Peter and I talked with Mattias today and have a new updated spreadsheet with lung terms that are needed. I'm closing this in favor of the new [spreadsheet](https://docs.google.com/spreadsheets/d/1Sz47Dk5TZvUh4xMEd6GqfHNqQcmI6BgW/edit#gid=361015257).
