### ISSUE TITLE
3q29 microduplication syndrome definition

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#3040]
**Mondo term (ID Label)**
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0012761

**Bug/Typo/Error description**
The definition states -- 3q29 microduplications are recently described chromosomal abnormalities with unclear clinical significance. 
and yet OMIM clearly states there is significance https://omim.org/entry/611936

Looking at the original publication, (https://pubmed.ncbi.nlm.nih.gov/18241066/), it seems there is clear enough evidence, even though this is only one family.

The Orphanet explanation states -- The clinical phenotype is extremely variable and the most consistent features are mild or moderate intellectual deficit and microcephaly.

The Orphanet definition (which is used here) appears to be simply out of date.

Possibly a better definition would be

3q29 microduplication is a chromosomal abnormality associated with variable clinical findings including mild or moderate intellectual deficit and microcephaly.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@kallia-p you can use Peter's ORCID as the definition source:
https://orcid.org/0000-0002-0736-9199
