### ISSUE TITLE
use Mondo to help merge OMIM and Orphanet for HPOA 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3042]
From @pnrobinson 
at some point we were thinking about merging annotations from OMIM and Orphanet but discarded that idea because there were too many divergences.
However, ORDO has a lot of diseases that are not in OMIM, such as the microduplications.
I wonder if there is some way of using MONDO to get all of the ORDO entries that are not related to OMIM entries (i.e., leave out OMIM leaf nodes, also leave out nodes such as Bardet Biedl syndrome that are superclass of leaf nodes).
This would make it easier for us to integrate things like this into the rest of the analysis pipeline
https://hpo.jax.org/app/browse/disease/ORPHA:261272

**Comment by matentzn** [comment]
Alright.

- Here is the [example](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0018452)
- [Here is the updated list](https://docs.google.com/spreadsheets/d/13eIa2Ihe6ChwOjH0s-8hp0K9IGMtveIqpFTtVvuvWK4/edit#gid=2109342463) (still needs a review)

**Comment by nicolevasilevsky** [comment]
This looks good to me!

**Comment by nicolevasilevsky** [comment]
@pnrobinson let us know if this is what you wanted, and if anything else is needed. :)
