### ISSUE TITLE
Insomnia

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#3060]
**Mondo term (ID Label)**
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0013600&viewMode=PreferredRoots&siblings=false

**Bug/Typo/Error description**

Insomnia is not a mental disorder -- remove this link

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
action item:
exclude superclassOf 'mental disorder'
