### ISSUE TITLE
disease by cell type

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#3062]
**Mondo term (ID Label)**
disease by cell type

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0044979&viewMode=PreferredRoots&siblings=true
**Bug/Typo/Error description**

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?disease by cell type
disease by cell type is a grand child of disease by subcellular system affected
This does not appear to be logical

**Comment by nicolevasilevsky** [comment]
This will be obsoleted in the December release:
https://github.com/monarch-initiative/mondo/issues/3661

closing this issue.
