### ISSUE TITLE
cardiac tuberculosis[Revise subclass]

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#3064]
**Mondo term (ID and Label)**
cardiac tuberculosis

**Suggested revision and reasons**
cardiac tuberculosis is currently listed as direct subclass of inflammatory disease but  this is not consistent for the majority of infectious diseases. We do not seem to have a clear policy for the relationship between infectious and inflammatory. I am not convinced that "inflammatory disease" is a good upper level class.  

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
This term has the equiv axiom
`tuberculosis
 and ('disease has inflammation site' some heart)`

which conforms to this pattern:
https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/inflammatory_disease_by_site.yaml

However, these tuberculosis children do not all use this pattern, most use the [location](https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/location.yaml) pattern. See:
- 'cutaneous tuberculosis'
- 'gastrointestinal tuberculosis'
- 'laryngeal tuberculosis'

I think we should change this class to use the location pattern too.

@kallia-p 
- [ ] could you change the Equivalent To axiom on 'cardiac tuberculosis' to:
`tuberculosis
 and ('disease has location' some heart)`

- [ ] And could you please also add an Equivalent To axiom to 'ocular tuberculosis':
`tuberculosis
 and ('disease has location' some eye)`

**Comment by kallia-p** [comment]
@nicolevasilevsky Done. Cardiac tuberculosis is now inferred as a SubClass Of heart disease and ocular tuberculosis is now inferred as an eye infectious disease which are both correct.

**Comment by kallia-p** [comment]
@nicolevasilevsky I mixed up the PR for two tickets which I accidentally did on one branch. issue_3064 branch was 2 commits the first one addresses #3064 but the 2nd commit addresses #3249. Not sure how I can fix this, sorry!
