### ISSUE TITLE
PrP systemic amyloidosis[Revise subclass]

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#3065]
**Mondo term (ID and Label)**
PrP systemic amyloidosis

This disease is not usually  considered a digestive system infectious disease. Where does this link come from?
See
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6369391/

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
the superclass assertion came from Orphanet, I excluded it. Thanks @pnrobinson!
