### ISSUE TITLE
atactic disorder[Revise subclass]

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#3066]
**Mondo term (ID and Label)**
atactic disorder. -- this is currently listed as central nervous system disease and yet one if its subclasses is sensory ataxia, which is a peripheral nervous system disease.

**Suggested revision and reasons**

Either revise the subhierarcy of atactic disease or place this class as a subclass of nervous system disease

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I'll revise this. We placed atactic disorder as a child of CNS because that is how it was classified in Harrison's. I'll move it to a subclass of 'nervous system disease'
