### ISSUE TITLE
Correct unexpected links to ENVO

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/mondo#3069]
**Mondo term (ID Label)**
N/A

**Bug/Typo/Error description**
In OLS, [when searching Mondo with the term 'depression'](https://www.ebi.ac.uk/ols/search?q=depression&ontology=mondo) the first result is a link to ENVO's term describing ```A landform sunken or depressed below the surrounding area.``` This is the [direct link to the term](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_00000309) as it is visualized in OLS. 

![Screen Shot 2021-05-13 at 6 08 22 PM](https://user-images.githubusercontent.com/1714621/118205872-39fb9000-b416-11eb-8cae-8b137f949874.png)

I am assuming this is a bug and we are inappropriately linking to an ENVO term (an import? an assertion?).  Understandably, the ENVO term is not wrong :wink:  but this describes some decreased elevation of terrain or a planitia in Mars - not a human disorder, so it is wrongly linked to Mondo. I am submitting this ticket to kindly ask that we look into correcting this.

This is what turns up in Protégé when you look for the term: 

![Screen Shot 2021-05-13 at 5 58 17 PM](https://user-images.githubusercontent.com/1714621/118205280-d0c74d00-b414-11eb-8921-98cd40c62557.png)

**Your nano-attribution (ORCID)**
0000-0001-8430-6039

h/t @pnrobinson

**Comment by nicolevasilevsky** [comment]
this will be solved by the linked ODK ticket
