### ISSUE TITLE
Discordance betwen HDO DOID and MONDO xfref DOID

### ISSUE THREAD

**Issue by vforget** [monarch-initiative/mondo#3070]
**Mondo term (ID and Label):**

MONDO_0004980, atopic eczema

**Xref that should be fixed (ID and label):**

 ICD10:L20.9 (DOID:3310) 
 ICD10:L20.81 (DOID:3310) 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
Not necessarily a bug, but at HDO (https://disease-ontology.org/) for DOID:3310 the ICD10 code reported is L20. L20.9 and L20.81 is not present. I would like to inquire how these two ICD10 codes got linked to DOID:3310.

**Comment by nicolevasilevsky** [comment]
Hi @vforget 
Thanks for the ticket and apologies for the delayed reply.

These xrefs came from DO when we originally created Mondo. Looking at DO in OLS, I see that they still xref both of these ICD codes (see [here](https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_3310).

![image](https://user-images.githubusercontent.com/6722114/123702805-72b1c600-d818-11eb-87d8-9d9cf9f6df49.png)

Let me know if there is anything further you'd like to discuss, or if you'd like any changes in Mondo. I will close this ticket.
Thank you!
