### ISSUE TITLE
review 'Jervell and Lange-Nielsen syndrome'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3073]
'Jervell and Lange-Nielsen syndrome' is a child of 'Jervell-Lange Nielsen syndrome' - should these be merged, or how did we get here?

Need to review.

**Comment by nicolevasilevsky** [comment]
@sabrinatoro assigning to you to review this, whenever you have a chance, no rush.

**Comment by sabrinatoro** [comment]
Jervell and Lange-Nielsen syndrome (MONDO:0009078) and Jervell-Lange Nielsen syndrome (MONDO:0002441) should be merged.

Jervell-Lange Nielsen syndrome (MONDO:0002441) comes from MESH:D029593, GARD:0003048, DOID:2842. This term represents the disease resulting  It results from mutation of KCNQ1 gene (Subtype 1 or JLN1) or the KCNE1 gene (Subtype 2 or JLN2). In other words, this is a "grouping term" for JLN.

Jervell and Lange-Nielsen syndrome (MONDO:0009078) was created as part of OMIM phenotypic series (OMIMPS), represented as grouping classes in Mondo. 

@nicolevasilevsky can we please discuss which term should be merged into which one? thank you!

**Comment by nicolevasilevsky** [comment]
yes, of course!
