### ISSUE TITLE
[Merge] MONDO:0030965 and MONDO:0030961 Olmsted syndrome 2

### ISSUE THREAD

**Issue by aholovenko** [monarch-initiative/mondo#3090]
**Mondo term (ID and Label)**
MONDO:0030965 - olmsted syndrome 2
MONDO:0030961 - Olmsted syndrome 2

**Reason for deprecation**
Same terms with same OMIM id.

**Term to be merged with**
MONDO:0030961 - Olmsted syndrome 2

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @aholovenko - looks like this term was ingested twice, and MONDO:0030965 was already obsoleted.
Thanks for reporting this!
