### ISSUE TITLE
ATP1A3- associated neurological disorders

### ISSUE THREAD

**Issue by brookepalus** [monarch-initiative/mondo#3091]
**Preferred gene-related syndrome label**
ATP1A3- associated neurological disorders

**Synonyms**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

**Definition**
This is a request for a new term for neurological disorders associated with ATP1A3. This is the nomenclature used in Gene Reviews, which give the following definition: ATP1A3-related neurologic disorders represent a clinical continuum in which at least three distinct phenotypes have been delineated: rapid-onset dystonia-parkinsonism (RDP); alternating hemiplegia of childhood (ACH); and cerebellar ataxia, areflexia, pes cavus, optic atrophy, and sensorineural hearing loss (CAPOS). However, some affected individuals have intermediate phenotypes or only a few features that do not fit well into one of these major phenotypes.

Mondo and OMIM list the same three disease entities in association with ATP1A3:  Dystonia 12, Alternating hemiplegia of childhood 2, and Cerebellar Ataxia, Areflexia, Pes Cavus, Optic Atrophy, And Sensorineural Hearing Loss (CAPOS). Using the ClinGen lumping and splitting guidelines, the ClinGen Syndromic Disorders GCEP determined that these three disease entities should be lumped together as a single entity. All three disease entities share overlapping features that can be considered a spectrum of disease, and there is no genotype-phenotype correlation (the same variants are associated with more than one disorder). 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID: 33762331
PMID: 31178018
PMID: 20301295

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by brookepalus** [comment]
Hi All, I want to check in regarding this Mondo ID request. Do you have an estimate for when the ID will be ready? This request is coming from ClinGen and we would like to publish the curation soon. 

Best,
Brooke

**Comment by nicolevasilevsky** [comment]
Hi @brookepalus - @sabrinatoro addded this term (thanks sabrina!) and the new ID is MONDO:0700002

It will be officially available in the next release, at the beginning of August.

**Comment by brookepalus** [comment]
Wonderful! Thank you, Nicole and Sabrina!
