### ISSUE TITLE
[NTR/ERF] ERF-related craniosynostosis

### ISSUE THREAD

**Issue by mayherpatel** [monarch-initiative/mondo#3092]
**Preferred gene-related syndrome label**

ERF-related craniosynostosis

**Synonyms**

MONDO:0010929 - craniosynostosis 4 

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

MONDO:0015469

**Definition**

Any craniosynostosis in which the cause of the disease is a mutation in the ERF  gene.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)

PMID: 23354439

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

N/A

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

https://clinicalgenome.org/affiliation/40059/

**Comment by nicolevasilevsky** [comment]
Hi @mayherpatel it seems this proposed class is equivalent to MONDO:0010929 - craniosynostosis 4, is it okay if I add this as a synonym?

**Comment by mayherpatel** [comment]
Yep, sounds good! I listed that term under synonym in the original request as well :)

**Comment by nicolevasilevsky** [comment]
Yes, I saw that- that was very helpful, thank you! 

Your requests are very clear, thanks for using the template, it makes it fast and easy for me. :)
