### ISSUE TITLE
MONDO:0014849 autosomal recessive nonsyndromic deafness 105[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3098]
**Mondo term (ID and Label)**
MONDO:0014849 autosomal recessive nonsyndromic deafness 105

**Reason for deprecation**
OMIM 616958 has been moved to MIM:608653 ; UMLS CUI C4310777 no longer exists.

**Term to be merged with**
MONDO:0012091 , 
autosomal recessive nonsyndromic deafness 32

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
