### ISSUE TITLE
MONDO:0014315 Mitchell-Riley syndrome[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3099]
**Mondo term (ID and Label)**
MONDO:0014315 Mitchell-Riley syndrome

**Reason for deprecation**
The MIM# on this term (OMIM:615710) is X-refed by Orphanet:293864 and CUI UMLS:C2748662, so I think they are synonymous.  (Please correct me if I am wrong, @ahamosh and @ana-rath-orphanet ) 

**Term to be merged with**
MONDO:0017400 hypoplastic pancreas-intestinal atresia-hypoplastic gallbalder syndrome

*Note: would prefer the MIM name as the primary, but as long as it's an exact syn on the merged term, we can appropriately map it in MedGen.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by ahamosh** [comment]
They are synonymous.

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
