### ISSUE TITLE
progressive supranuclear palsy SCTID

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3100]
**Mondo term (ID and Label):**
 MONDO:0019037 progressive supranuclear palsy

**Xref that should be fixed (ID and label):**
SCTID:28978003 (Actually maps to "Progressive supranuclear ophthalmoplegia," per UMLS's representation of SNOMED.  Is this the same as MONDO:0020257 "supranuclear oculomotor palsy"??)
SNOMED code for "progressive supranuclear palsy" (again, per UMLS's SNOMED map) is 192976002

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
This needs additional clinical review before making any changes. I am relying heavily on simple string matching, UMLS's mapping of the SCTIDs and hierarchies, and limited clinical descriptions provided in Metathesaurus and on Mondo.

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
this means you have some issue with moving your eyes. Progressive supranuclear ophthalmoplegia is a phenotype, there is a record in OMIM because there is a gene associated with this.

- [ ] 'progressive supranuclear palsy' is incorrectly classified as a genetic disease, should remove those superclasses. Exclude 'genetic dementia' and 'inherited neurodegenerative disorder'

**Comment by pnrobinson** [comment]
@ahamosh 
OMIM has [progressive supranuclear palsy](https://omim.org/entry/601104) and lists  STEELE-RICHARDSON-OLSZEWSKI SYNDROME  as a synonym, but other literature appears to regard the latter as an idiopathic non Mendelian disease , e.g., 
https://www.mjdrdypu.org/article.asp?issn=0975-2870;year=2013;volume=6;issue=3;spage=342;epage=345;aulast=Gokhale;type=3
Should we introduce some superclass for diseases that are primarily characterized by SNOP and then have two subclasses
Mendelian SNOP and Complex SNOP (or something like that). Also the above cited article appears to further subdivide  STEELE-RICHARDSON-OLSZEWSKI SYNDROME

**Comment by nicolevasilevsky** [comment]
Steele-Richardson-Olszewski disease may refer to all three subtypes, OMIM used this as an alternative name for only one subtype. There is not a PS. OMIM should create a PS.

Steele-Richardson-Olszewski disease should be an exact synonym for MONDO:0019037 'progressive supranuclear palsy'. and this should be equiv to OMIMPS when it is created.
