### ISSUE TITLE
[NTR] 0001 INTELLECTUAL DEVELOPMENTAL DISORDER, AUTOSOMAL DOMINANT 65 (OMIM)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3107]
**Preferred term label:**
0001 INTELLECTUAL DEVELOPMENTAL DISORDER, AUTOSOMAL DOMINANT 65

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**

OMIM, MIssing
https://www.omim.org/entry/609765#molecularGenetics

**Comment by ValWood** [comment]
https://www.omim.org/entry/610740#molecularGenetics
.0001 GLOBAL DEVELOPMENTAL DELAY WITH SPEECH AND BEHAVIORAL ABNORMALITIES
also seems to be missing?

**Comment by nicolevasilevsky** [comment]
@ValWood we have MONDO_0030995 'global developmental delay with speech and behavioral abnormalities' (equiv to OMIM:619243)

**Comment by ValWood** [comment]
thanks!
