### ISSUE TITLE
Alzheimer disease - exact match - Alzheimer disease pathway

### ISSUE THREAD

**Issue by cbizon** [monarch-initiative/mondo#3111]
**Mondo term (ID and Label):**
MONDO:0004975. Alzheimer Disease

**Xref that should be fixed (ID and label):**
This isn't an xref but a skos exactMatch:
```
          "pred" : "http://www.w3.org/2004/02/skos/core#exactMatch",
          "val" : "http://purl.obolibrary.org/obo/NCIT_C38778"
```
NCIT_C38778 is "Alzheimer's Disease Pathway KEGG" which is a "biochemical pathway" in NCI, not a "Disease, disorder or finding"

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
Is there a better choice for submitting issues like this than xref?

**Comment by nicolevasilevsky** [comment]
@cbizon Interesting! In the OWL file, it is not annotated as equivalentTo, so I think this is a bug that it is showing up as an exact match in [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004975). I am going to assign our development team to look into this.

These annotations are xrefs in the ontology file, so using this template works for me. Or you can use the 'bug' template.

Thanks for reporting this.

**Comment by sabrinatoro** [comment]
Hello @cbizon 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by cmungall** [comment]
Hi @cbizon 

What's best from the translator point of view? And perhaps the exactMatches are more palatable with the translator conflation strategy?

I think there are two perspectives here, and I think this could also apply to other pathway representations include PW, and the disease pathway subset of Reactome

1: the KEGG ID formally represents a pathway, which is a subclass of (or metaclass of) BiologicalProcess. We formulate the relationship as a logical axiom. There are two sub-options here:

1a: the KEGG/PW/Reactome named "X disease pathway" actually represents the normal process that is disrupted in X. Then the relation becomes something like arises-from-disruption of

1b: the KEGG/PW/Reactome named "X disease pathway" is actually an aberrant biological process, and the disease either causes the aaberrant BP to happen, ro happens as a result of it

I think 1b applies to reactome, but 1a to KEGG. So perhaps safest just to have something safe that conflates these distinctions.

2: concepts such as "Alzheimers pathway" or "Parkinsons pathway" are just constructs for talking about a range of different pathways and really the concept is the same as the concept of the disease itself. See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3102895 -- in this case we would retain exactMatch (we can think of skos relations as operating at the Shulz conflation layer and owl axioms at the OBO layer)

I think option 1 makes most sense from the POV of current MONDO development, but will take a bit of time to implement (I would like to make a boomer merger of PW and KEGG disease subsets and include as an import).

So in the interim let's just make them relatedMatches so no one is confused!

**Comment by cmungall** [comment]
made a new issue for PW import #3362

**Comment by cbizon** [comment]
Yeah, I think that these are both totally valid ways to think about things, but from (my?) Translator perspective, (1) is a better fit.  I agree on 1a vs 1b - it would be nice to have some kind of relationships that distinguished the two.

**Comment by cmungall** [comment]
Nico - I suggest closing yr PR and instead

`perl -npe 's@MONDO:equivalentTo@MONDO:relatedTo@ if m@^xref: KEGG@' mondo-edit.obo`

**Comment by cmungall** [comment]
made a new ticket for the PW axiomatization
#3362. 


we will kp this open til we change the kegg xrefs to relatedd
