### ISSUE TITLE
inherited/primary Fanconi (renotubular) syndrome[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3113]
Open question:

Is MONDO_0007600 'primary Fanconi syndrome' ([Orphanet:3337](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_3337)) equivalent to [OMIMPS:134600](https://omim.org/phenotypicSeries/PS134600)

genes | OMIM | Orphanet
-- | -- | --
EHHADH | x | x
SLC34A1 | x | x
NDUFAF6 | x | x
GATM | x | x
HNF4A | x | 

----

**Mondo term (ID and Label)**
MONDO:0007600 primary Fanconi syndrome (Orpha:3337)

**Reason for deprecation**
It seems like OrphaNet:3337 and OMIMPS:134600 are almost fully overlapping, with only ONE of the inherited Fanconi syndrome OMIM terms not being covered by Orpha:3337.The difference is FS type 4 (MIM: 616026) which has additional phenotypes in the description, so maybe this was intentional and they are not equivalent? 

@ahamosh @Orphanet @ana-rath-orphanet  Can you please weigh in? MedGen representation of these concepts and our Mondo term mapping will follow your decision.

**Term to be merged with**
MONDO:0100238 inherited Fanconi renotubular syndrome (OMIMPS : 134600)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
pinging @ahamosh

**Comment by nicolevasilevsky** [comment]
to do:
send Ada a question about this and she'll forward on to the OMIM team.

Sounds like the OMIMPS and Orphanet class are not the same
Orphanet mapping is correct to https://omim.org/entry/134600

**Comment by nicolevasilevsky** [comment]
@kanems upon talking to Ada today, she said the the OMIMPS and Orphanet class are not the same. But the Orphanet mapping is correct to https://omim.org/entry/134600. 

I will move Orphanet:3337 as a equiv xref to MONDO_0024525 'Fanconi renotubular syndrome 1'.
