### ISSUE TITLE
MONDO:0007704 osteoarthritis susceptibility 2 [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3121]
**Mondo term (ID and Label)**
MONDO:0007704 
osteoarthritis susceptibility 2

**Suggested revision and reasons**
Set as a child of MONDO:0005178, osteoarthritis like other osteoarthritis susceptibility terms. (Currently it's a bit of an "orphan" under 'inherited disease susceptibility' MONDO:0020573

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by kallia-p** [comment]
@nicolevasilevsky @kanems I want to highlight that the 'osteoarthritis susceptibility' numbered terms in Mondo are out of date. Osteoarthritis is a complex disease caused by many variants and historically some associations were published from linkage and candidate studies, few of which have been replicated in independent, more recent and better powered studies. I am happy to move this term under the parent term osteoarthritis but in general I think that the disease susceptibility convention of ascribing a complex disease to one gene because of historical underpowered studies with lack of replication is out of date. Happy to elaborate more on this matter.

**Comment by kallia-p** [comment]
@nicolevasilevsky I moved all orphan osteoarthritis susceptibility terms (1 , 2, 3, 5) under 'osteoarthritis'. Osteoarthritis susceptibility 4 and 6 were already grouped under parent term osteoarthritis. As an annotation source I added the corresponding OMIM ids keeping in line with osteoarthritis susceptibility 4 and 6.  Note that 4 and 6 don't have an Equivalent To axiom unlike 1, 2, 3, and 5 terms 
'inherited disease susceptibility'
 and ('disease has basis in dysfunction of' some gene)
 and ('predisposes towards' some osteoarthritis).

**Comment by kallia-p** [comment]
@nicolevasilevsky @matentzn It seems that the PR failed due to the Equivalent To axiom predisposes towards osteoarthritis (this axiom was already there before I added osteoarthritis as a subclass).

**Comment by nicolevasilevsky** [comment]
@kanems in Mondo, we decided we should not have a 'susceptibility to' term as a child of that term, so we removed the parent osteoarthritis from the other classes and all of these classes will be a child of 'inherited disease susceptibility'

**Comment by kanems** [comment]
@nicolevasilevsky Works for me. We will discuss at MedGen so we handle the hierarchies we were building from Mondo's model appropriately. 
Is this a decision specific to the 'osteoarthritis' portion of the hierarchy, or will all 'susceptibility to' terms get moved out to be "inherited disease susceptibility" children instead of children of the more generic disease term? Or is that still TBD?

**Comment by matentzn** [comment]
No answer to @kanems (sorry engineering department 😄 )

but check
https://github.com/monarch-initiative/mondo/issues/1395

**Comment by nicolevasilevsky** [comment]
> Is this a decision specific to the 'osteoarthritis' portion of the hierarchy, or will all 'susceptibility to' terms get moved out to be "inherited disease susceptibility" children instead of children of the more generic disease term? Or is that still TBD?

It is TBD. Unfortunately, we haven't had a chance to discuss susceptibility terms together as a team lately. It's still on our to do list!

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
I think this can be closed. Please reopen if any other action is needed.
