### ISSUE TITLE
Multiple new terms as subclasses of qualitative or quantitative defects of protein involved in O-glycosylation of alpha-dystroglycan (MONDO:0016155) (ClinGen expert panel request)

### ISSUE THREAD

**Issue by smcnulty13** [monarch-initiative/mondo#3123]
Currently, the subclasses of "qualitative or quantitative defects of protein involved in O-glycosylation of alpha-dystroglycan" (MONDO:0016155) include both groups of disorders and individual diseases. The ClinGen Limb Girdle Muscular Dystrophy Gene Curation Expert Panel proposes the addition of a number of new terms to add a subclass for each gene (FKRP, FKTN, POMGNT1, POMGNT2, POMT1, POMT2) with additional new child terms for each of the disease subtypes known to be associated with the gene (see mockup: [LGMD GCEP Proposed MONDO Structure.pdf](https://github.com/monarch-initiative/mondo/files/6587485/LGMD.GCEP.Proposed.MONDO.Structure.pdf)). For example, for the POMGNT2 gene:

qualitative or quantitative defects of protein involved in O-glycosylation of alpha-dystroglycan (MONDO:0016155)
--POMGNT2-related myopathies
----congenital muscular dystrophy-POMGNT2 related
----LGMD-POMGNT2 related
----muscle-eye-brain disease-POMGNT2 related

Please let me know if we can provide any additional information that would be helpful in considering these proposed terms. 

cc @courtneythaxton @Mohan-Shruthi

**Comment by smcnulty13** [comment]
@nicolevasilevsky

**Comment by sabrinatoro** [comment]
Hello @smcnulty13 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
Thanks @smcnulty13, we'll work on this asap.

**Comment by sabrinatoro** [comment]
@smcnulty13 I am working on this issue. It looks like some of the terms you requested might already be in Mondo. Could you please check the list below and let me know in these terms (the terms you requested and the Mondo terms) are indeed the same? 
If they are, I can make sure they will be classified in the ontology as requested. 
Thank you! 
LGMD-FKRP related myopathy = autosomal recessive limb-girdle muscular dystrophy type 2I (MONDO:0011787)
LGMD-FKTN related myopathy = autosomal recessive limb-girdle muscular dystrophy type 2M (MONDO:0012699)
LGMD-POMGNT1 related myopathy = autosomal recessive limb-girdle muscular dystrophy type 2O (MONDO:0013161)
LGMD-POMT1 related myopathy  =  autosomal recessive limb-girdle muscular dystrophy type 2K (MONDO:0012248)
LGMD-POMT2 related myopathy = autosomal recessive limb-girdle muscular dystrophy type 2N (MONDO:0013162)

**Comment by smcnulty13** [comment]
@sabrinatoro Thanks for looking into this! Yes, I agree the existing LGMD terms are the same. Ideally we could add a ClinGen-preferred synonym for each (e.g. "LGMD-FKRP related" or "FKRP-related LGMD" or "LGMD related to FKRP"). Does MONDO have a preference for how these synonyms are structured?

I believe some of the other child terms under the requested parent terms also exist. I've attached an Excel file with the MONDO term/ID, requested ClinGen-preferred synonym, and matching OMIM term/ID. 

Please let me know if I can provide additional information. Thanks!

[LGMD.GCEP.Proposed.Synonyms.xlsx](https://github.com/monarch-initiative/mondo/files/6932003/LGMD.GCEP.Proposed.Synonyms.xlsx)

**Comment by sabrinatoro** [comment]
@smcnulty13, 
Thank you very much for the document! This was extremely helpful, and it answered my next questions. 
I made sure that the ClinGen preferred synonyms were available for each terms, using the "ClinGen preferred" tag.
The changes will be available in the next Mondo release (early September).

**Comment by smcnulty13** [comment]
@sabrinatoro Thanks so much, Sabrina! Will the requested parent terms (e.g. "FKRP-related myopathies") encompassing these terms be available in September as well? We are hoping to use the parent terms for our curations in this ClinGen expert panel.

**Comment by sabrinatoro** [comment]
@smcnulty13 
Yes, the requested parents have also been created. Here is a screenshot of the ontology with the new terms and their children. Note that all these terms have the ClinGen synonyms with "ClinGen preferred" tag (e.g. "FKRP-related myopathy"), which you cannot see in this screenshot.
![Screen Shot 2021-08-05 at 8 14 58 AM](https://user-images.githubusercontent.com/12737987/128375296-f8662d4d-e077-4968-aad6-c4b77ee261ee.png)

**Comment by nicolevasilevsky** [comment]
@smcnulty13 we can share the new Mondo IDs with you if that is helpful. They will be available after the next release in early Sept.

**Comment by maglott** [comment]
Just wondering...  Is Mondo moving in the direction of classifying disorders by the altered gene product, instead of tagging in some way all relationships between genes and the disorders that may result from altered function or expression?

**Comment by nicolevasilevsky** [comment]
For ClinGen requests, we are adding new terms that use gene-based names. If it is an existing term (ie from OMIM), we are adding the gene-based names as synonyms and tagging the synonym as 'clingen preferred'.

**Comment by smcnulty13** [comment]
@sabrinatoro @nicolevasilevsky The September release timeline sounds great--thank you! If you're able to share the new Mondo IDs for the parent terms that would be very helpful. 

Is it possible to add a parent and child terms (also listed in the Excel document) for GMPPB under "qualitative or quantitative defects of protein involved in O-glycosylation of alpha-dystroglycan" following the same structure, as well? Apologies that this wasn't included in my initial request--we've since reviewed this gene within the LGMD expert panel. Thanks!

**Comment by courtneythaxton** [comment]
I do have one request. Please let's remove the term "mutation" from these terms @smcnulty13 . 

This is a movement in the genetic community to remove use of the term mutation, and rather use variation.

I think we can take this back to our expert panel if needed, but I the terms could follow the dyadic approach of gene- related myopathy. 

So:
FKRP related myopathy

**Comment by sabrinatoro** [comment]
@smcnulty13 
Here are the Mondo ID for the new terms ‘qualitative or quantitative defects of protein involved in O-glycosylation of alpha-dystroglycan’ (MONDO:0016155) : 
FKRP-related myopathy  -  MONDO:0700066
FKTN-related myopathy -  MONDO:0700067
POMGNT1-related myopathy - MONDO:0700068
POMGNT2-related myopathy - MONDO:0700069
POMT1-related myopathy - MONDO:0700070
POMT2-related myopathy -  MONDO:0700071
GMPPB-related myopathy - MONDO:0700084

**Comment by sabrinatoro** [comment]
@courtneythaxton 
Thank you for your comment and for letting us know about the movement in the genetic community to remove use of the term mutation.
These names (using "caused by mutation in Gene") follow a Mondo design pattern that we use when creating terms for diseases that are caused by a single mutation in a single gene ([see here](https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/disease_series_by_gene.yaml)).
We will revise this pattern such that we use names that agree with the community-preferred terminology. We will then update all the Mondo terms created based on the pattern accordingly.
