### ISSUE TITLE
neurofibromatosis type 1 MONDO:0018975 has two exactMatch MeSH xrefs (one is obsolete)

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3124]
Currently neurofibromatosis type 1 MONDO:0018975 has two exactMatch xrefs for MeSH

http://identifiers.org/mesh/C538607 OBSOLETE

http://identifiers.org/mesh/D009456 Neurofibromatosis 1

I think MeSH C538607 should be removed as an exact match from this MONDO entry

**Comment by sabrinatoro** [comment]
Hello @lcdaugherty 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
@lcdaugherty I marked it as MONDO:equivalentObsolete
