### ISSUE TITLE
MeSH query when ExactMatch same for two MONDO IDs tuberous sclerosis complex MONDO:0019341 and tuberous sclerosis MONDO:0001734 

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3129]
http://purl.obolibrary.org/obo/MONDO_0019341
tuberous sclerosis complex
has exactMatch http://identifiers.org/mesh/D014402

http://purl.obolibrary.org/obo/MONDO_0001734
tuberous sclerosis
has exactMatch http://identifiers.org/mesh/D014402
There is a comment:  Editor note: TODO check MONDO:0019341; consider placement under neoplastic syndrome

- Can **both* terms have  exactMatch http://identifiers.org/mesh/D014402? 
I think D014402 should be removed as exactMatch from tuberous sclerosis?

- Also, tuberous sclerosis complex and tuberous sclerosis have the same 'child' terms tuberous sclerosis 1 MONDO:0008612 and tuberous sclerosis 2 MONDO:0013199
Is this expected?

**Comment by sabrinatoro** [comment]
Hello @lcdaugherty 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
@lcdaugherty for some reason OLS displays an relatedTo xref as an exact match, this is a known issue. MESH:D014402 is a relatedTo on MONDO_0019341 tuberous sclerosis complex.

I agree that tuberous sclerosis 1 and 2 were incorrectly classified under tuberous sclerosis complex - this came from a broad to narrow annotation from Orphanet. I excluded these subclasses.

Thanks for reporting this.
