### ISSUE TITLE
Reverse proxy merges NCIT - make tickets at NCIT?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#3136]
I noticed these two reverse proxy merges during the work on #3130

NCIT:C8748,http://purl.obolibrary.org/obo/MONDO_0000503
NCIT:C136486,http://purl.obolibrary.org/obo/MONDO_0000503
NCIT:C70649,http://purl.obolibrary.org/obo/MONDO_0019468
NCIT:C4752,http://purl.obolibrary.org/obo/MONDO_0019468

I would quickly double check and if confirmed to be no bugs on our end, make a ticket on NCIT itself.

**Comment by nicolevasilevsky** [comment]
NCIT:C8748 is 'Stage 0 Lung Adenosquamous Carcinoma AJCC v6 and v7' and
NCIT:C136486 'Lung Adenocarcinoma In Situ' 

I would say these are not equiv and we should remove the MONDO:equivalentTo xref to NCIT:C8748 on MONDO_0000503 'lung adenocarcinoma in situ'

**Comment by nicolevasilevsky** [comment]
NCIT:C70649 is T-Cell Chronic Lymphocytic Leukemia and 
NCIT:C4752 is T-Cell Prolymphocytic Leukemia

NCIT:C70649 is T-Cell Chronic Lymphocytic Leukemia is obsolete, I will mark this as such in Mondo
