### ISSUE TITLE
familial infantile bilateral striatal necrosis MONDO:0010080

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3138]
I am struggling a little with this term and it's immediate tree members. I would appreciate some input from the community to see if we can clarify these concepts.  
->ORPHA:225154 maps to OMIM: 271930 and 500003 (X-ref on MONDO:0010080)
---But Orpha:1576 “infantile bilateral striatal necrosis” maps to the same MIM numbers. (And it’s X-ref’d on “infantile bilateral striatal necrosis” MONDO:0015518) So are these Orpha terms equivalent?
->There is a separate UMLS CUI for  “Familial infantile bilateral striatal necrosis” C4087174 and the CN201303 identifier is not an active concept in MedGen, so it should be removed.

There is an OMIM PS for Striatonigral degeneration - PS271930, but it includes OMIM 617054 (childhood-onset form) and OMIM 271930 (AR infantile onset form) the Mitochondrial form (500003) isn’t included, maybe an oversight in OMIM?

On a related note:
I’m not sure that the “infantile bilateral striatal necrosis” MONDO:0015518 term is well situated in it’s current location in the ontology (see screenshot) and the Xrefs seem to overlap with the X-refs on the above term. UMLS puts OMIM 271930 on CUI C0795996 (probably based on the name, which has an alternate name that matches this Mondo pref. name), so I'm not sure where to put this Mondo concept within MedGen.
![image](https://user-images.githubusercontent.com/71083858/121574091-ecae1680-c9f3-11eb-87d9-1f7a2c8e8809.png)

@ahamosh and @Orphanet @ana-rath-orphanet can you weigh in?

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
