### ISSUE TITLE
desmoplastic medulloblastoma ? [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3139]
**Mondo term (ID and Label)**
MONDO:0005547 
desmoplastic medulloblastoma

**Reason for deprecation**
I am not certain on this, but based on the descriptions on Mondo (A medulloblastoma characterized by the presence of nodular, collagenous areas which do not contain reticulin, surrounded by hypercellular areas which contain an intercellular reticulin fiber network. [ NCIT:P378 ]) and on Orpha:251863 desmoplastic and desmoplastic/nodular medulloblastoma are the same? Google returned this definition from at least one website: "The desmoplastic/nodular medulloblastoma is a histologic variant that usually arises in a cerebellar hemisphere and is defined by the presence of a _reticulin-rich stroma_ and _reticulin-poor, nodular, pale islands_ with expression of markers of neuronal differentiation..." 

**Term to be merged with**
MONDO:0016711 desmoplastic/nodular medulloblastoma 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
Emailed Lori Richardson on 08/31/21
