### ISSUE TITLE
MONDO:0010491

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#3141]

**Comment by maglott** [comment]
MONDO:0010491 is X-linked acrogigantism due to Xq26 microduplication and is a child of partial duplication of the short arm of chromosome X
It should be a child of MONDO:0017010, partial duplication of the long arm of chromosome X, given that q26 is on the long arm

**Comment by sabrinatoro** [comment]
Hello @maglott 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
