### ISSUE TITLE
OMIM 160750 X-ref?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3143]
**Mondo term (ID and Label):**
MONDO:0008054 
juvenile dermatomyositis

**Xref that should be fixed (ID and label):**
OMIM:160750

Based on the names from the MIM entry, I don't think this belongs on juvenile dermatomyositis. Perhaps it maps to Idiopathic inflammatory Myopathy MONDO:0020122. Or create a new term that is a child of IIM:
"familial idiopathic inflammatory myopathy" X-ref to the MIM number, UMLS:C3888318 and MESH: C000598744

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
I agree @kanems, this mapping is incorrect, thanks for reporting this.

@kallia-p could you please:
- [ ] change the source on the database cross reference to OMIM:160750 to MONDO:relatedTo (from MONDO:equivalentTo)

![image](https://user-images.githubusercontent.com/6722114/123692656-ee594600-d80b-11eb-8b45-efd434d9b4ae.png)

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by kanems** [comment]
Just a note of some potential X-refs for MONDO:0600023:
Idiopathic inflammatory myopathy, SNOMEDCT_US, 702380008
Idiopathic Inflammatory Myopathies, UMLS CUI: C0751356 ; MeSH D009220, NCI C116796
