### ISSUE TITLE
Typo in MONDO:0014531 - the label is misspelt 

### ISSUE THREAD

**Issue by asmvernon** [monarch-initiative/mondo#3144]
**Mondo term (ID Label)**
MONDO:0014531 

**Bug/Typo/Error description**
`amyotrohpic` is misspelt; it should read  `amyotrophic`

**Your nano-attribution (ORCID)**
0000-0001-9432-6447

**Comment by nicolevasilevsky** [comment]
thanks, I'll fix this :)
