### ISSUE TITLE
review classification of 'connective tissue disease'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3155]
'connective tissue disease'
Discussion: 
- there is no Dr for “connective tissue”
- Need to distinguish between 
  - rheumatologic (non-genetic)
  - genetic connective tissue disease
  - orthopedic diseases often includes connective tissues
These 3 should cover all bases: 
- Orthopedic disorder (new term, syn: Orthopaedic disorder) MONDO_0002081 'musculoskeletal system disease'	
- Rheumatologic disease ('rheumatologic disorder') MONDO_0005554
- 'hereditary connective tissue disorder' (syn: Heritable disorder of connective tissue) (under Mendelian) MONDO_0023603

Should be auto-classified 

related #2741

**Comment by nicolevasilevsky** [comment]
Need clarification of the action items

**Comment by sabrinatoro** [comment]
@pnrobinson  and @ahamosh  
I need some clarification on what to do on this issue (related to the reclassification of Mondo according to Harrison.
During the Mondo Workshop in April 2020, we discussed that the term 'connective tissue disease' should be removed as an upper class, and the children of this class should be relocated.  
Children: 'hereditary connective tissue disorder' (syn: Heritable disorder of connective tissue) should go under Mendelian. Other children terms should be reclassified under 'rheumatologic disorder' (MONDO0005554)- however, I don't know (1) which one should be reclassified under this term (assuming not all the children terms refer to 'rheumatologic disorder'), (2) where to put the terms which would not be classified under 'rheumatologic disorder'

1) Do we still think we need to remove 'connective tissue disease' as an upper class?
2) If so, where should the children terms go? (see a screenshot of this class below)

I understand it might be too much to discuss here. If so, we could set a meeting. Please let me know. 
Thank you! 

<img width="365" alt="Screen Shot 2021-07-15 at 9 09 24 AM" src="https://user-images.githubusercontent.com/12737987/125841123-caba1ef3-eff7-40df-9484-40bdb41a1a8f.png">

**Comment by ahamosh** [comment]
That is a mess!  It needs a call with a live open document.  Best if Peter and I are both there because we might have different opinions.

**Comment by pnrobinson** [comment]
I agree with @ahamosh  -- we need to have a live session to go through sections like this and clean them up. There is still a decent amount of work to be done!

**Comment by nicolevasilevsky** [comment]
Note - Nicole, Sabrina, Ada and Peter have two meetings scheduled with in August to discuss

**Comment by sabrinatoro** [comment]
This issue is not really part of the Harrison reclassification work. Removing the label.

**Comment by nicolevasilevsky** [comment]
Action items:

- [x] '47,XYY syndrome' is not a syndromic disease - _excluded this parent_
