### ISSUE TITLE
[Obsolete] disorder involving pain

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3163]
**Mondo term (ID and Label)**
disorder involving pain
MONDO:0021668

**Reason for deprecation**
not useful term
(see[Mondo April2021 workshop]( https://docs.google.com/document/d/1KXqGAZgZUbK-VnzcomnMbfAEq7WEeGxDaQ-EK8UUQZI/edit))

From workshop:
**Discussions**: 
- not useful term:  all diseases will involve pain
- These terms have : “has major feature” = pain
- most of these terms come from a neurological pain syndrome

**AI: Obsolete, subclasses should be neurologic pain issues** 

Related to #2741

**Comment by sabrinatoro** [comment]
We need to review children terms.

**Comment by nicolevasilevsky** [comment]
I listened to the recording again and this is what I gathered as action items:

- [ ] create new class **'neurological pain syndrome'**
- [ ] add synonyms:
- neurologic pain syndrome (exact)
- neurological pain disease (exact) 
- [ ] add logical def:
'nervous system disorder' and ('disease has major feature' some Pain)
- [ ] add subclassOf:
'realized in' some 'sensory perception of pain'

- [ ] **vaginismus** is not a neurological pain syndrome (per Ada). I looked at NCIT (see [here](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C78703), and they have this term classified as a child of 'Female reproductive system finding' and 'genitourinary signs and symptoms'. We don't have these types of findings and symptoms in Mondo, but I think this makes sense to have vaginismus as a child of 'disease of genitourinary system'.

- [ ] for the children of 'disorder involving pain' that have logical definitions/equivalence axioms that use 'disorder involving pain', change to 'disorder involving pain' to 'neurological pain syndrome'
for example: 'chronic pain syndrome' has the logical def:
'disorder involving pain' and ('has modifier' some chronic)'
 change it to 'neurological pain syndrome' and ('has modifier' some chronic)

- [ ] the other children of 'disorder involving pain' should be children of 'neurological pain syndrome'. 
- [ ] Obsolete 'disorder involving pain' and add the 'consider' annotation and add consider [your new neurological pain syndrome' class. _Note, you can add the URI in the IRI editor field here_
- [ ] If you use the 'Make entity obsolete, it should delete the subclassOf assertions to 'disorder involving pain' for all the children.

your new hierarchy should look like this:
![image](https://user-images.githubusercontent.com/6722114/123178781-c9945580-d43c-11eb-9054-e254658586a3.png)

**Comment by nicolevasilevsky** [comment]
@ahamosh we discussed this at the April Workshop.

I wonder if 'neurological pain syndrome' is the best label, as it seems like there is a more specific disease that uses this name: https://www.dignityhealth.org/sacramento/services/neurological-care/clinical-expertise/neurological-pain-syndromes#:~:text=A%20neurological%20pain%20syndrome%20is,not%20real%20feeling%20of%20pain.

Would neurological pain disease or neurological pain disorder be appropriate?

Here is a suggested definition:
A nervous system disorder that has pain as a major feature.

**Comment by ahamosh** [comment]
I agree that I would not call this a syndrome.  I prefer neurological pain disorder of the other two options.

**Comment by nicolevasilevsky** [comment]
thanks @ahamosh!
