### ISSUE TITLE
[Merge] glomuvenous malformation ?

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3168]
**Mondo term (ID and Label)**

+ | glomuvenous malformation

looks like a phenotypic description of

+ | familial glomangioma

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Hello @ValWood 
I recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by sabrinatoro** [comment]
Based on the definitions and reports, these terms could be merged,
HOWEVER, “In the past, glomuvenous malformations (GVM, MIM138000) were improperly called ‘‘glomangiomas’’ or ‘‘glomus tumours.’’ GVM are **vascular malformations** and should be distinguished from paragangliomas (MIM 115310,168000, and 605373) and from the (subungual) solitaryglomus tumours." (PMID: 15689436)

I suggest that we

- [ ] Merge 'familial glomangioma' (MONDO:0004424) into 'glomuvenous malformation' (MONDO:0007672)
- [ ] Exclude Subclass 'Glomangioma' based on PMID: 15689436
