### ISSUE TITLE
review fibromyalgia classification

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3170]
From the [April Mondo Workshop](https://docs.google.com/document/d/1KXqGAZgZUbK-VnzcomnMbfAEq7WEeGxDaQ-EK8UUQZI/edit)

'fibromyalgia' (MONDO:0005546)
- exclude superclass: myositis (this is incorrect)
- should be under “idiopathic disease” (see #3169 )

Related to #2741

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I saw another issue after excluding Subclass "myositis": 
fibromyalgia is inferred as being a subclass of "muscular disease" because it has the inferred logical axiom: 'disease or disorder' and ('disease has location' some 'muscle organ') 
This inference comes from the SubClass Of ('disease has location' some 'skeletal muscle organ'), source= EFO:0000784 (EFO:0000784='has_disease_location')
Fibromyalgia is characterized by muscle pain, but the "location" is not in the muscle (based on our discussion in the Mondo workshop).
Could you please advise on what to do? Can I remove the "disease-has-location some 'skeletal muscle organ' ? (the source for this axiom is strange...)
Thank you

**Comment by nicolevasilevsky** [comment]
We remove the subclassOf axiom:
relationship: disease_has_location UBERON:0014892 {source="EFO:0005687"} ! skeletal muscle organ
