### ISSUE TITLE
Thrombocythemia, X linked MONDO:0010301[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3172]
**Mondo term (ID and Label)**
Thrombocythemia, X linked MONDO:0010301

**Reason for deprecation**
OMIM has merged 300331 with 187950 "Thrombocythemia 1" and the UMLS CUI X-ref on this term has been retired.

**Term to be merged with**
Thrombocythemia 1 MONDO:0008554

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by kanems** [comment]
Actually, even though OMIM directs users to the 187950 term, there is no "X linked" locus on the thrombocythemia 1 page Phenotype-gene relationships table . Perhaps this entry should be deleted?
@ahamosh Any input here? This page (https://www.omim.org/entry/187950)  still points folks back to the 300331 entry for the "possible X-linked form," creating a bit of a loop for anyone looking for info on  X-linked thrombocythemia.

**Comment by ahamosh** [comment]
Bad link.  Will be corrected by morning.  Sorry.

**Comment by sabrinatoro** [comment]
Hello @kanems 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by kanems** [comment]
Upon closer review, MedGen has decided to delete the term with the old MIM number and "x-linked" term, as other CUIs and MIM numbers already represent the concepts. Since UMLS has deleted the CUI and the merged MIM term doesn't include "x-linked" in the alternate names, I think this might be a term to obsolete in the Mondo dictionary.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I think this issue should be : obsolete 'thrombocythemia, X-linked' (MONDO:0010301)
Do you agree? 
(Maybe a good first issue?)

**Comment by nicolevasilevsky** [comment]
yes, I agree it should be obsoleted (not merged). 

I think you and I should do the obsoletions, so let's not label it as a good first issue.

**Comment by galyea-gard** [comment]
Hi! X-linked thrombocythemia links to  https://omim.org/entry/313900 (it is considered a synonym of X-linked thrombocytopenia (THC1) as well as other websites such as MedlinePlus: https://medlineplus.gov/genetics/condition/x-linked-thrombocytopenia/ 
Orphanet: https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=852 (added normal platelets)
We have a page at GARD.  
In this case it may be better to merge it .  Thank you! Gioconda

**Comment by nicolevasilevsky** [comment]
@galyea-gard I don't see a mention of X-linked thrombo**cythemia** on the OMIM page (https://omim.org/entry/313900), I only see X-linked thrombo**cytopenia**. 

@sabrinatoro I think we should obsolete Thrombocythemia, X linked MONDO:0010301 and add a consider: Thrombocythemia 1 MONDO:0008554, since that is what OMIM points to, but it does not seem like they are the same terms.

@galyea-gard please let us know if you have any objections. Thanks!

**Comment by galyea-gard** [comment]
Hi!  I apologize I made a mistake here:  I meant to say that "Thrombocytopenia 1 is a synonym of X-linked thrombocytopenia".  Regarding the questions you have here in this ticket:

-  I agree that obsoleting (or deleting) X-linked thrombocythemia (MONDO:0010301 should be the best approach. 
- Thrombocythemia 1 (IOMIM187950) should be keep as a separate disorder (the original confusion in OMIM may have resulted from an article where the authors described a family with several affected males - but X-linked inheritance was excluded - See OMIM and this other one: https://pubmed.ncbi.nlm.nih.gov/11260062/ ). 

Thank you! Gioconda
