### ISSUE TITLE
NTR: idiopathic

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3177]
We need a new "disease characteristic" term to define the new "idiopathic disease" class https://github.com/monarch-initiative/mondo/issues/3169

Proposal: 
**Preferred term label:**
idiopathic

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
A characteristic of a disease in which the disease has an uncertain or unknown cause.

**Parent term**
disease characteristic (MONDO:0021125)

Note : we probably need to have an 'idiopathic vs non-idiopathic' class under 'disease characteristic'

**Comment by sabrinatoro** [comment]
@cmungall :
We don't think the term 'idiopathic' is used to refer to a phenotype, therefore @nicolevasilevsky and I think Mondo is the best place for this term (instead of PATO). 
Do you agree?

**Comment by cmungall** [comment]
pato is more general than phenotype, however, I think it's still good to
have this in the mondo characteristic hierarchy, it can always be moved
later. So go ahead and add, and let's make a yaml DP too
