### ISSUE TITLE
[NTR] Acute fibrinous and organizing pneumonia

### ISSUE THREAD

**Issue by Vineyardintern** [monarch-initiative/mondo#3179]
**Preferred term label:**
acute fibrinous and organizing pneumonia

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
A diffuse infiltrative pulmonary disease, characterized by presence of intra-alveolar fibrin and organizing pneumonia. (source: DOI https://doi.org/10.1183/13993003.congress-2015.PA817)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0005249

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
ORCID: 0000-0002-8134-1207

**Comment by sabrinatoro** [comment]
Hello @Vineyardintern 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by nicolevasilevsky** [comment]
this was for training purposes, closing
