### ISSUE TITLE
SPARQL idiopathic terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3180]
Could you please provide us a list of all the Mondo terms with 'idiopathic' in the label and their parents?
Thank you!

@sabrinatoro and I will:
- [x] review the list and determine which terms should use the pattern https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/idiopathic.yaml
- [x] some classes should just have the subclassOf axiom: 'has modifier' some idiopathic

related to #2750 

cc @sabrinatoro

**Comment by matentzn** [comment]
There you go:
https://docs.google.com/spreadsheets/d/13eIa2Ihe6ChwOjH0s-8hp0K9IGMtveIqpFTtVvuvWK4/edit#gid=674728682

**Comment by sabrinatoro** [comment]
I went through the list and updated it. @nicolevasilevsky, please review.
Please note that :
- I determined the classes which should **only** have the subclassOf axiom: 'has modifier' some idiopathic **based on the term definition** (i.e if there were no definition or no mention that the cause of the disease was unknown, the term was set to not get the subclass)
- 2 terms should get the Equivalent axiom but have 2 parents. Please advise on what to do with these. 
- Some terms are children/grand-children of a term which should get an equivalent axiom. I 'think' that these terms will get the 'idiopathic' modifier via inference. Please confirm and review. 
Thank you!

**Comment by nicolevasilevsky** [comment]
this is done, thanks all!
