### ISSUE TITLE
[NTR] Congenital alveolar dysplasia

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3190]
**Parent**: MONDO_0020295 'congenital pulmonary veins anomaly'
**Name:** Congenital alveolar dysplasia
**synonym (abbrev)**: CAD

**Children**:
Congenital alveolar dysplasia due to FGF10 
syn: CAD due to FGF10

Congenital alveolar dysplasia due to TBX4
syn: CAD due to TBX4

Related to #3026 

----
@mgriese
Is **Congenital alveolar dysplasia** different from **Congenital alveolar capillary dysplasia** (see [Orphanet](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=210122)) (and this Orphanet term is equivalent to [Alveolar capillary dysplasia with misalignment of pulmonary veins](https://omim.org/entry/265380) from OMIM, which is a separate class in Mondo (and in your [list](https://docs.google.com/document/d/1fP9eInb-xFvtuA7rJg-c8JInWA2pmTjy/edit#).)

If we add these diseases with gene variants, we'd want to coordinate with OMIM as well.

Thanks @mgriese!

**Comment by nicolevasilevsky** [comment]
Related to 
https://github.com/monarch-initiative/mondo/pull/3147

**Comment by nicolevasilevsky** [comment]
@mgriese pinging you, thank you!

**Comment by mgriese** [comment]
1) Congenital alveolar dysplasia is different from Congenital alveolar capillary dysplasia 
2) Congenital alveolar capillary dysplasia (see Orphanet) is an older term; more recently the condition is labelled Alveolar capillary dysplasia with misalignment of pulmonary veins
3) Alveolar capillary dysplasia without misalignment of pulmonary veins is sometimes observed and a rare condition; not well described. 
re 1) was associated with the two genes indicated above, re 2) is associated with FOXF1, re 3) has no confirmed association yet

**Comment by nicolevasilevsky** [comment]
Thanks @mgriese, very helpful!

@ahamosh FYI - I will add these diseases above that are associated with the respective genes.
