### ISSUE TITLE
[Revise subclass] missing neurodegenerative disease parent

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3193]
**Mondo term (ID and Label)**

These seem that they should be neurodegenerative diseases
https://www.pombase.org/term/MONDO:0008842
https://www.pombase.org/term/MONDO:0011457

**Comment by nicolevasilevsky** [comment]
Thanks @ValWood! We'll work on this.

**Comment by nicolevasilevsky** [comment]
Looks like some of the equivalent axioms need to be revised too. This is what we have right now:

![image](https://user-images.githubusercontent.com/6722114/123664446-32d4e980-d7ec-11eb-9e8f-3b6654250755.png)

**Comment by nicolevasilevsky** [comment]
Here are the proposed revisions:
![image](https://user-images.githubusercontent.com/6722114/123665643-53517380-d7ed-11eb-9860-1c3f646ec90a.png)

**Comment by nicolevasilevsky** [comment]
Action items:
- [ ] add superclass to MONDO_0011457, additional parent should be neurodegenerative disease, source: this ticket and https://orcid.org/0000-0001-6330-7526
- [ ] change source for dbxref on 'ataxia - telangiectasia-like disorder':
- NCIT:C132224 should be MONDO:superClassOf
- Orphanet:251347 should be MONDO:superClassOf
- [ ] add dbxrefs to 'ataxia-telangiectasia-like disorder 1':
- Orphanet:251347 source: MONDO:equivalentTo
- NCIT:C132224 source: MONDO:equivalentTo
