### ISSUE TITLE
[Revise text def]

### ISSUE THREAD

**Issue by tsneddon** [monarch-initiative/mondo#3207]
**Mondo term (ID and Label)**
MONDO:0044327 - polycystic liver disease 4 with or without kidney cysts

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
Per request of the ClinGen Cystic & CIliopathy GCEP, please connect MONDO:0044327 with the _LRP5_ gene eg:
"polycystic liver disease-4 with or without kidney cysts (PCLD4) is caused by heterozygous mutation in the _LRP5_ gene  (OMIM# 617875)"

**Comment by nicolevasilevsky** [comment]
Thanks @tsneddon, we'll take care of this.
