### ISSUE TITLE
need design patterns for new infectious disease classification

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3219]
related to #3217 

![image](https://user-images.githubusercontent.com/6722114/124192815-c02d6d80-da7a-11eb-811b-48c3c2529156.png)
![image](https://user-images.githubusercontent.com/6722114/124192827-c58ab800-da7a-11eb-9300-6d45ca2ac233.png)

**Comment by nicolevasilevsky** [comment]
related to: https://github.com/monarch-initiative/mondo/issues/3609
Note- rheumatic disorder is now a child of post-bacterial infection, but is a single child. We should investigate if other classes should be classified under this. And if there is a pattern we could create so we can auto-classify

**Comment by nicolevasilevsky** [comment]
patterns that are needed:

- [ ] 'disease caused by reactivation of latent infectious agent', example 'herpes zoster'

**Comment by nicolevasilevsky** [comment]
revisit 'post-viral disorder'
may need to request new object property from RO: 'disease is consequence of'

@sabrinatoro

**Comment by sabrinatoro** [comment]
Definition of the existing relation ‘disease has infectious agent’ = A relationship between a disease and an infectious agent where the **material basis of** the disease is an infection with some infectious agent.

@cmungall what does 'material basis of' mean? 

I am trying to determine whether  ‘disease has infectious agent’ should be a parent term for more precise relations representing that the infection is the direct or indirect cause of the disease. 

Note: Similarly, other disease relations have 'the physical basis of' in their definition. What does this mean? (e.g. 'disease has basis in dysfunction of' = A relation that holds between the disease and a material entity where **the physical basis of** the disease is a disorder of that material entity that affects its function.)

(note: maybe this particular comment should be in the RO repo. I can put it there if we feel that's where it should be)

**Comment by sabrinatoro** [comment]
@cmungall additional question: 
What would be the difference between 'disease arises from' and 'disease has basis in' ?
Thanks!

**Comment by nicolevasilevsky** [comment]
@sabrinatoro is there any other action needed or did that last PR finalize this ticket? Thanks!

**Comment by sabrinatoro** [comment]
@nicolevasilevsky I think this PR finalize this ticket. Closing.
