### ISSUE TITLE
Download Mondo and import owl into neo4j

### ISSUE THREAD

**Issue by Jordi-Valls** [monarch-initiative/mondo#3226]
Hi to everyone,

My name is Jordi Valls, and my question is about download mondo...

I click the following links that in github are available;
http://purl.obolibrary.org/obo/mondo.obo
http://purl.obolibrary.org/obo/mondo.json
http://purl.obolibrary.org/obo/mondo.owl

But unfortunately nothing happens...

The same from the last release:
https://github.com/monarch-initiative/mondo/releases/tag/v2021-06-01

So my question is about if I require to fill some requirement to use mondo or something happens with the links...
I just can download the mondo.json, .owl and .obo from this link:

http://obofoundry.org/ontology/mondo.html

Finally just I want to know if the formats of owl or json are ready to upload into neo4j platform, or I need to do some changes, because I try to upload the mondo.owl but seems that doesnt work properly.

Thanks for your time,

Jordi

**Comment by nicolevasilevsky** [comment]
Hi @Jordi-Valls,
This may be an issue with Chrome blocking downloads from an http URL. Can you try copying and pasting the links into a new browser and see if that works?
Thanks!
Nicole

**Comment by matentzn** [comment]
https://purl.obolibrary.org/obo/mondo.obo

**Comment by matentzn** [comment]
If you go to the last release and scroll down, you can download everything by clicking on the files! At least I can?

**Comment by Jordi-Valls** [comment]
Hi @matentzn its true I can download the files from the last relase :D thanks. Besides Is also true Nicole, if I use firefox I can download all files, maybe is something of my chrome browser, my apologise.

Finally, just in case, if you want to use the mondo.owl in neo4j, you have to use the following command to import the file in this platform:
CALL n10s.onto.import.fetch("file:///path/mondo.owl", "RDF/XML")

THanks for your help!

**Comment by nicolevasilevsky** [comment]
I think this can be closed, please reopen if there are any other questions. thanks!
