### ISSUE TITLE
remove the (disease) from Mondo labels

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3232]
- [x] remove the (disease) from Mondo labels
For example:
'leukemia (disease)'

- [x] Add annotation: OBO Foundry unique label: label

**Comment by matentzn** [comment]
That is not for me! YOu should be able to do that with the OBO file hacking we learned.

You can put this on one of our common meetings.

**Comment by nicolevasilevsky** [comment]
ok! :)
