### ISSUE TITLE
rename class "cell proliferation disease"

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3235]
From the [April Mondo Workshop](https://docs.google.com/document/d/1KXqGAZgZUbK-VnzcomnMbfAEq7WEeGxDaQ-EK8UUQZI/edit)

new name TBD

Related to #2741

**Comment by sabrinatoro** [comment]
Hello @pnrobinson and @ahamosh  
I have been reviewing the Mondo hierarchy according to Harrison's Principles of Internal Medicine, based on our discussions at the Mondo Workshop in April 2021.

It was mentioned that we should rename the class 'cell proliferation disorder' (MONDO:0045024).
Based on the definition, this class includes hyperplasia, neoplastic syndrome, and isolated neoplasm diseases, as well as precancerous conditions (i.e., any disorder that features disrupted cell proliferation)

The Harrison's chapter related to this Mondo Class is called "Cancer and Benign Tumors". Would 'benign tumors' include precancerous conditions?

Would you have any names suggestion? 
Thank you, I appreciate your help!

**Comment by ahamosh** [comment]
How about Cancer, precancer, and benign tumors?  I defer to @pnrobinson.

**Comment by pnrobinson** [comment]
I think that these concepts are not 100% precisely defined in the literature, but a benign tumor does not contain cancerous cells. There are some benign tumors that do not become cancerous, such as uterine fibroids, and so they are not considered precancerous. There is no simple definition of cancerous, cancer cells differ in many ways from benign cells (see e.g., https://www.cancer.gov/about-cancer/understanding/what-is-cancer). However, precancerous is defined as having abnormal cells that grow faster or are different from the cells normally in a tissue but do not yet satisfy the definition of cancerous.

All of this has to do in some way with cell  proliferation and so  'cell proliferation disorder' is technically correct, but is an unusual phrase that might not be recognized as meaning "benign and malignant tumors" upon cursory reading.

**Comment by pnrobinson** [comment]
For the purposes of MONDO, I am not convinced that we should divide diseases into the three classes benign, premalignant, and malignant, simply because a premalignant lesion can develop into a malignant lesion, and more importantly, any cancer disease will go through many many stages and we should not name the disease differently for each stage.

**Comment by pnrobinson** [comment]
I think that "Cancer and Benign Tumors" is the best label because everybody will immediately know what we are talking about. It is correct if we consider that a precancerous lesion is a stage of a cancer disease.

**Comment by ahamosh** [comment]
Totally agree!

**Comment by maglott** [comment]
How is this differentiated from neoplasm?
https://www.cancer.gov/publications/dictionaries/cancer-terms/def/neoplasm

**Comment by pnrobinson** [comment]
synonymous

**Comment by sabrinatoro** [comment]
Thank you for your feedback! 
I will rename this class 'Cancer and Benign Tumors', and add 'neoplasm' as a synonym.
