### ISSUE TITLE
add harrisons_view tag to appropriate terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3237]
Add this subset tag to the terms in the harrison view hierarchy in this slide:
https://docs.google.com/presentation/d/1LXnXo2nfavFPwrXXlXXRVt0Rk-j8eK-XRO-Wau7Kvr0/edit#slide=id.gdbbf3067a8_0_780 

Here is an example: 
(I did one)
https://github.com/monarch-initiative/mondo/pull/3236

**Comment by sabrinatoro** [comment]
summary of which terms should have the tag: https://docs.google.com/presentation/d/1y8Eh453V5JJQ4Q-LKkRjZ3HW4hA3Ql4MfDOTNbNPP44/edit?usp=sharing
