### ISSUE TITLE
Relabel MONDO:0008135

### ISSUE THREAD

**Issue by Mohan-Shruthi** [monarch-initiative/mondo#3238]
**Mondo term (ID and Label):** MONDO:0008135; optic atrophy with negative Electroretinograms

**Suggested new label:** OPTIC ATROPHY 13 WITH RETINAL AND FOVEAL ABNORMALITIES

**Your nano-attribution (ORCID)** ClinGen Glaucoma/Neuro-ocular Gene Curation Expert Panel
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)** This term has been updated in OMIM: https://omim.org/entry/165510

**Comment by nicolevasilevsky** [comment]
Thanks @Mohan-Shruthi! We'll fix this

**Comment by sabrinatoro** [comment]
Hello @Mohan-Shruthi 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!
