### ISSUE TITLE
Missing synonym for MONDO:0013624

### ISSUE THREAD

**Issue by Alx-Kouris** [monarch-initiative/mondo#3243]
**Mondo term (ID Label)**
MONDO:0013624

**Bug/Typo/Error description**
In the mondo.obo, the synonym Rafiq Syndrome for above ID is missing, whereas is mentioned here https://monarchinitiative.org/disease/MONDO:0013624.

**Comment by nicolevasilevsky** [comment]
@matentzn - that is really weird, do you know how that happened?
I can add it to the mondo-edit.obo file.

@Alx-Kouris thanks for reporting this!

**Comment by matentzn** [comment]
I dont think anything happened - afaik this synonym was never in Mondo!

@kshefchek is there another source of labels in Monarch? Perhaps the OMIM ingest itself?
