### ISSUE TITLE
[NTR] hydrosalpinx

### ISSUE THREAD

**Issue by jahilton** [monarch-initiative/mondo#3249]
**Preferred term label:**
hydrosalpinx

**Synonyms**
blocked fallopian tube
fallopian tube obstruction

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Blockage of a fallopian tube caused by a fluid buildup and dilation of the tube at its end.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002156

**Your nano-attribution (ORCID)**
0000-0002-1196-4871

**various references**
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C142886
https://doi.org/10.1016/j.bpobgyn.2019.01.011
https://fertilitynj.com/infertility/female-infertility/structural-causes/hydrosalpinx/
https://www.medicalnewstoday.com/articles/320677

**Comment by kallia-p** [comment]
@nicolevasilevsky I mixed up the PR for two tickets which I accidentally did on one branch. issue_3064 branch was 2 commits the first one addresses #3064 but the 2nd commit addresses #3249. Not sure how I can fix this, sorry!

**Comment by nicolevasilevsky** [comment]
No problem @kallia-p. I will take a look later.
