### ISSUE TITLE
Review 'polycystic liver disease' DBxref

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3264]
from #2693 
Another example: Orphanet:2924 is currently mapped to MONDO:0008265 polycystic liver disease 1, but I think it should probably go on MONDO:0000447 autosomal dominant polycystic liver disease; based on multiple OMIM mappings and same pref name on Mondo term with one of the Orphanet alt names.

To do: 
**MONDO:0000447 (autosomal dominant polycystic liver disease):** (parent term)
- [x] Add Orphanet:2924 ; MONDO:EquivalentTo
- [x] ~Remove OMIM:174050 : OMIMPS Mondo:Equivalent To~

**MONDO:0008265 (polycystic liver disease 1)** (child term)
- [x] Change Orphanet:2924 to MONDO:subClassOf

**Review other DBXref**
- [x] ICD10:Q44.6 - (refers to general term): change to MONDO:subClassOf on MONDO:0008265, add to MONDO:0000447 with Mondo:EquivalentTo
- [x] MedDRA:10010427- remove (refers to general term) change to MONDO:subClassOf on MONDO:0008265, add to MONDO:0000447 with Mondo:EquivalentTo
- [x] MedDRA:10048834- remove (refers to general term) change to MONDO:subClassOf on MONDO:0008265, add to MONDO:0000447 with Mondo:EquivalentTo
- [x] OMIM:617004 (refers to polycystic liver disease 2) change to MONDO:directSiblingOf (??) from MONDO:0008265

**Comment by lcdaugherty** [comment]
@sabrinatoro I don't understand, why was OMIMPS:174050 (MONDO:equivalentTo)  removed from http://purl.obolibrary.org/obo/MONDO_0000447  autosomal dominant polycystic liver disease
I thought this represented the subtypes of  autosomal dominant polycystic liver disease https://omim.org/phenotypicSeries/PS174050?

**Comment by sabrinatoro** [comment]
@lcdaugherty 
I reviewed my notes, and it looks like the checklist above is not correct-or at least not clear (copy/paste issue). 
What was actually done for MONDO:0000447 autosomal dominant polycystic liver disease was to: 
- Remove OMIM:174050 (specific term) equivalence (and make it a Mondo:superClassOf)
- Add the OMIMPS:174050 (the grouping term) as a "Mondo:Equivalent"

I confirmed that indeed OMIMPS:17405 remained here : http://purl.obolibrary.org/obo/MONDO_0000447

My apologies for the confusion.

**Comment by lcdaugherty** [comment]
@sabrinatoro thank you for for replying - phew!
