### ISSUE TITLE
Review 'paroxysmal nonkinesigenic dyskinesia 1' DBxref

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3265]
From #2693 
MONDO:0007326 paroxysmal nonkinesigenic dyskinesia 1
X-refs Orpha and one OMIM:
OMIM:118800 (Orphanet:98810)
...
Orphanet:98810 (OMIM:118800)
But the OrphaNet term has two OMIM X-refs (PNKD1 and PNKD1 OMIM: 118800 611147)

Suggested clean up: Keep MIM118800 here. Move Orphanet:98810 (and GARD 8722) to a new parent term of "Paroxysmal non-kinesigenic dyskinesia" (with subtypes 1 and 2 from OMIM)

(see @nicolevasilevsky comments in #2693):
Action items:
- [ ] create new term paroxysmal non-kinesigenic dyskinesia, xref Orphanet:98810 (and GARD 8722), parent of type 1 & 2
- [ ] obsolete 'paroxysmal nonkinesigenic dyskinesia 1' and create new class with same label, xref OMIM:118800

**Comment by ValWood** [comment]
hi,

what ids the new ID for MONDO:0007326 paroxysmal nonkinesigenic dyskinesia 1
?

**Comment by ValWood** [comment]
OLS still has
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0007326

**Comment by ValWood** [comment]
Can you add new terms and IDs to the tickets? It's really helpful for re-mapping.

**Comment by nicolevasilevsky** [comment]
Yes, we can do that! Thanks for the suggestion.
Cc @sabrinatoro 

The new IDs are:
MONDO_0700088 'paroxysmal nonkinesigenic dyskinesia'
MONDO_0700089 'paroxysmal nonkinesigenic dyskinesia 1'

It usually takes OLS about 7 days to update after the Mondo release, so I expect these will be visible in OLS in another day or two?

**Comment by ValWood** [comment]
Thanks, that will be really useful for locating the discussion. Our logs only give is the old ID  so it's a lot of chasing if there is no 'replaced by' term.

**Comment by nicolevasilevsky** [comment]
@ValWood we also have the 'consider' annotation, if there is not a 'replaced by'.

**Comment by ValWood** [comment]
Thanks, I don't think we use those, I have never seen one. That will help a lot if most obsoletions have them!
