### ISSUE TITLE
Request to collapse two RERE gene disease IDs

### ISSUE THREAD

**Issue by jennygoldstein** [monarch-initiative/mondo#327]
Hello, I am a ClinGen gene curator. When curating the RERE gene I noticed that there are two MonDO IDs associated with the same gene-disease entity. One ID can be found when searching with the MIM phenotype # for the gene (MIM#616975). This gives MONDO:0014857, "neurodevelopmental disorder with or without anomalies of the brain, eye, or heart; NEDBEH". Of note, RERE is the only gene associated with this phenotype. If MonDO is searched for "RERE", the ID is MONDO:0044630, “rere-related neurodevelopmental syndrome”, based on an Orphanet entry. These disease entities are the same. Is it possible to collapse these IDs into the same entry, preferably MONDO:0014857

## Suggested parent term: "rare genetic syndrome intellectual disability"

Thank you for your help.

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@jennygoldstein what is your ORCID?

**Comment by jennygoldstein** [comment]
It's 0000-0002-5655-9589
Thank you Nicole.

**Comment by nicolevasilevsky** [comment]
note to self, I think there may be a conflict with this PR
