### ISSUE TITLE
riboflavin deficiency OMIM:615026

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3272]
**Mondo term (ID and Label):**
maternal riboflavin deficiency MONDO:0014013

**Xref that should be fixed (ID and label):**
OMIM: 615026 --> move to ariboflavinosis aka vitamin B12 deficiency. MONDO:0004573 
(https://omim.org/entry/615026 renamed to Riboflavin deficiency, UMLS maps this MIM number to the same term as SCTID 20307000 Ariboflavinosis)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
- [ ] move OMIM:615026 xref to MONDO_0004573 ariboflavinosis
- [ ] on MONDO:0014013, OMIM xref should be MONDO:subClassOf
- [ ] 'maternal riboflavin deficiency' should be a child of ariboflavinosis
- [ ] add EXACT synonym to ariboflavinosis: riboflavin deficiency
- [ ] add excluded from QC check: http://purl.obolibrary.org/obo/mondo/sparql/qc/general/qc-single-child.sparql
