### ISSUE TITLE
[Merge] MONDO_0006448 'testicular teratoma (disease)'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3286]
**Mondo term (ID and Label)**
MONDO:0006448 'testicular teratoma (disease)'

**Reason for deprecation**
duplicate

**Term to be merged with**
MONDO:0018193 'testicular teratoma'

Are these two terms the same? They seem like the same to me. @paolaroncaglia and @zoependlington - MONDO:0006448 'testicular teratoma (disease)' is equiv to EFO:1000573

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,
Those 2 Mondo terms seem the same to me too. MONDO:0018193 is undefined, but its is_a parent is quite specific and informative. EFO:1000573 doesn't have annotations that ring a bell in terms of its users - based on its ID, I think it was part of a bulk addition via template, but @zoependlington even if it were added for UK Biobank they could work with a replacement, right? I can't find the ID in our GitHub tracker.
Thanks,
Paola
