### ISSUE TITLE
add idiopathic logical axioms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3289]
@sabrinatoro 
The next step to add idiopathic logical definitions is:
1. In the [spreadsheet](https://docs.google.com/spreadsheets/d/13eIa2Ihe6ChwOjH0s-8hp0K9IGMtveIqpFTtVvuvWK4/edit#gid=577155275), could you please add the parent classes for each term that should have an equivalence axiom in column C, see an example in row 20. (Rows 3-19)
2. Let Nico know when you are done, and he can automatically add all of these equivalence axioms and subclassOf axioms to the respective terms.
Thank you!

**Comment by sabrinatoro** [comment]
@matentzn 
Could you please automatically add the equivalence axioms and subclassOf axioms?
The list of terms is here: https://docs.google.com/spreadsheets/d/13eIa2Ihe6ChwOjH0s-8hp0K9IGMtveIqpFTtVvuvWK4/edit#gid=577155275
(see sheet called "idiopathic_template") 
Let me know if you have questions. 
Thank you!
