### ISSUE TITLE
[NTR/gene] Ectodermal dysplasia WNT10A related

### ISSUE THREAD

**Issue by brookepalus** [monarch-initiative/mondo#3293]
**Preferred gene-related syndrome label**
Ectodermal dysplasia WNT10A related

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

**Definition**
Lumping of the previous disease entities associated with WNT10A in OMIM, including: Odontoonychodermal dysplasia, Schopf-Schulz-Passarge syndrome, and Tooth agenesis, selective, 4. The new term should replace the associated Mondo terms for these three disease entities (MONDO:0009773, MONDO:0009145, and MONDO:0007881). This is a request from the ClinGen Syndromic Disorders GCEP. 

https://www.clinicalgenome.org/affiliation/40060/

**Comment by nicolevasilevsky** [comment]
@brookepalus is tooth agenesis a type of ectodermal dysplasia?

**Comment by nicolevasilevsky** [comment]
And did you want to merge all these existing classes into this term, or create a grouping class, where these terms would be children of Ectodermal dysplasia WNT10A related?

**Comment by nicolevasilevsky** [comment]
@brookepalus see questions above, thanks! 👀 ⬆️

**Comment by brookepalus** [comment]
Hi Nicole, my apologies for the delay. I was out of the office on vacation and am just now catching up on email. It is my understanding that ectodermal dysplasia and Tooth agenesis have overlapping phenotypes. The GCEP would like the terms merged if possible. Please let me know if you have any other questions!

**Comment by brookepalus** [comment]
From the biocurator: 

TA: hypotrichosis, agenesis of variable number of permanent teeth, dry skin, abnormal sweating, and nail abnormalities

ED: affecting the development and/or homeostasis of ectoderm-derived structures such as hair, nails, teeth and eccrine sweat glands (HED being the most common - Martínez-Romero et al. (2019)).

Overlapping phenotypes: Hair abnormalities, teeth abnormalities, sweat abnormalities, nail abnormalities, skin abnormalities

**Comment by nicolevasilevsky** [comment]
@brookepalus we try to align with OMIM in Mondo, so I'd like to check with @ahamosh to see if OMIM plans to lump all of these classes together as well. If yes, we'll do so in Mondo too.

@ahamosh could you please let me know when you have a chance?

Thanks!

**Comment by ahamosh** [comment]
Hi All,  OMIM will make OODD (257980) have an ectodermal dysplasia alternate title and be added to the phenotypic series (PS3015100).  We will keep selective tooth agenesis 4 (150400).  I am not sure whether we have been decided to lump or keep SSPS  (224750).  That is being looked at right now.  I think that Mondo could make an ectodermal disorders-wnt10a related or just give them the ectodermal dysplasia number we give them and then leave it to ClinGen to explain that they have chosen to lump for their reasons.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh!

@brookepalus hopefully it's okay with you if we have MONDO_0100358 'ectodermal dysplasia WNT10A related' as a grouping class and keep the three children to align with OMIM, see screenshot below.

We'll update this to align with Ada's changes above when they are ready in OMIM.

![image](https://user-images.githubusercontent.com/6722114/127695967-f6858dd0-c799-409c-a905-9c4e023a8099.png)

**Comment by brookepalus** [comment]
Yes, that is fine. Thank you!
