### ISSUE TITLE
MONDO:0010061 possible obsoletion

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3321]
Following from
https://github.com/monarch-initiative/mondo/issues/3222

https://monarchinitiative.org/disease/MONDO:0010061#causal-gene
also looks redundant with

MONDO:0013931 | peroxisome biogenesis disorder 4B

**Comment by nicolevasilevsky** [comment]
Hi @ValWood I see they share a gene, but it seems like the phenotypes are different, see the two OMIM records:
https://omim.org/entry/614863
https://omim.org/entry/271250

Please let me know if further action is required. Thanks!

**Comment by ValWood** [comment]
right, yes!
