### ISSUE TITLE
seeing multiple annotations in Mondo

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3328]
![image](https://user-images.githubusercontent.com/6722114/126218228-37f473a3-9180-4e63-9f94-b54ab2f7c2f7.png)

On this branch (issue-3170) (PR https://github.com/monarch-initiative/mondo/pull/3326)- I see two seeAlso annotations and three source annotations. I've seen duplicate source annotations on other branches, and sometimes I don't see it. I don't know which one we're supposed to use.

They are coming from different sources:
**Source:**
- http://purl.obolibrary.org/obo/mondo#source
- http://geneontology.org/formats/oboInOWl/#source
- http://geneontology.org/formats/oboInOWl#http://purl.obolibrary.org/obo/mondo#source

**SeeAlso:**
- http://geneontology.org/formats/oboInOWl#http://www.w3c.org/2000/01/rdf-schema#seeAlso
- http://www.w3c.org/2000/01/rdf-schema#seeAlso

**Comment by matentzn** [comment]
I cant confirm the `seeAlso` - it looks fixed on master. I fixed the rest in the above PR!

**Comment by nicolevasilevsky** [comment]
thank you @matentzn!
