### ISSUE TITLE
autosomal recessive cutis laxa type 2, classic type parentage

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3332]
autosomal recessive cutis laxa type 2, classic type (MONDO:0009054)
(3 causal genes) 

is classed as 
autosomal recessive cutis laxa type 2A (MONDO:0018163)

this seems incorrect, since MONDO:0018163 is more specific  (for ATP6V0A2  only)

Maybe a sanity. check for the number of associated genes would help identify these?
@cmungall

**Comment by nicolevasilevsky** [comment]
Thanks @ValWood! 

This is based on the orphanet classification: https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_357058&viewMode=All&siblings=false

We added the superclass axiom to 'autosomal recessive cutis laxa type 2A'
'disease has basis in dysfunction of' some ATP6V0A2
