### ISSUE TITLE
autosomal recessive cutis laxa type 2, classic type (MONDO:0009054), superclasses

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3333]
Follow on from https://github.com/monarch-initiative/mondo/issues/3332

It seems odd that 
autosomal recessive cutis laxa type 2, classic type (MONDO:0009054)
is a disorder of glycosylation.

It has 3 glycosylation parentages:

is_a congenital disorder of glycosylation with neurological involvement
is_a congenital disorder of glycosylation-related bone disorder
is_a congenital disorder of glycosylation with skin involvement

is this classification correct?
(it seems odd because the vacuolar ATPase isn't really related to glycosylation pathway- I looked through the list of phenotypes and I could not see anything mentioning glycosylation defects, although  the phenotypes "cutis laxis" is sometimes  due to glycosylation defects)

**Comment by nicolevasilevsky** [comment]
Thanks @ValWood.

Reviewing this class, I think we can exclude several parents on this term:

exclude superclassOf:
- [ ] 'congenital disorder of glycosylation with neurological involvement'
- [ ] 'congenital disorder of glycosylation with skin involvement'
- [ ] 'congenital disorder of glycosylation-related bone disorder'
- [ ] 'metabolic disease with epilepsy'
- [ ] 'syndromic neurometabolic disease with non-X-linked intellectual disability'

**Comment by nicolevasilevsky** [comment]
it seems like this has already been addressed, these terms are no longer parents. Closing.
