### ISSUE TITLE
Language impairment & language disorder

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#334]
I've noticed during the new EFO build that MONDO has language impairment (disease) (MONDO_0014184) as a subclass of specific language impairment (MONDO_0000724). Specific language impairment is a child of language disorder (MONDO_0004750), which I believe may potentially be the same as language impairment (disease) (MONDO_0014184)? See [here](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0014184). Thanks!

**Comment by nicolevasilevsky** [comment]
I think these terms are different. 'Language disorder' is defined as a group of disorders, whereas 'language impairment (disease)' is a more specific disease, and has the synonym, 'specific language impairment type 5', which seems more specific.

Do you agree?
