### ISSUE TITLE
Suggest new term: infantile/childhood-onset epilepsy syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#335]
## Preferred term label
infantile/childhood-onset epilepsy syndrome

## Textual definition
An epilepsy sydrome that has an onset during the infantile or childhood stage of life.

## Suggested parent term
MONDO_0015650 'epilepsy syndrome'

## Suggested children terms

[OMIMPS:617711 ! Epileptic encephalopathy, infantile or early childhood](https://www.omim.org/phenotypicSeries/PS617711) *** 
  is_a [OMIM:617711 ! Epileptic Encephalopathy, Infantile or Early Childhood, 1](https://www.omim.org/entry/617711)
  is_a [OMIM:617829 ! Epileptic Encephalopathy, Infantile or Early Childhood, 2](https://www.omim.org/entry/617829)
  is_a [OMIM:618012 ! Epileptic Encephalopathy, Infantile or Early Childhood, 3](https://www.omim.org/entry/618012)

## Attribution
http://orcid.org/0000-0001-5208-3432

## Note
Similar grouping terms like this already exist:
MONDO_0100022 'neonatal/infantile epilepsy syndrome' 
MONDO_0100030 'adolescent/adult-onset epilepsy syndrome'

**Comment by cmungall** [comment]
ah somehow I missed MONDO_0100022, thanks!

note the PS is for infantile or *early* childhood

 - https://omim.org/entry/617711 "characterized by delayed psychomotor development apparent in infancy"
 - https://omim.org/entry/617829 "characterized in most patients by onset of seizures in infancy or childhood" most of the cases seem to be infantile, e.g "At age 9 months, she developed febrile seizures"

so I don't think a new term is justified here. Fine to use MONDO_0100022 for these OMIMs? Can you check? potentially relabel neonatal/infantile/early childhood? Or just use the PS label?

**Comment by nicolevasilevsky** [comment]
I think it would be best to rename MONDO_0100022 to 'neonatal/infantile/early childhood-onset epilepsy syndrome'. I don't think the label 'Epileptic encephalopathy, infantile or early childhood' would be suitable for all the children of MONDO_0100022.

**Comment by nicolevasilevsky** [comment]
per the email conversation with Karl, Tristen and Ingo, they recommend creating the new class 'infantile/childhood-onset epilepsy syndrome', "Because you lose something if you create categories like "neonatal/infantile/early childhood/adolescent/etc.""

**Comment by nicolevasilevsky** [comment]
@cmungall are you okay with me adding this new class?
Will the subclasses be automatically imported from OMIM?

**Comment by cmungall** [comment]
See also #271

**Comment by nicolevasilevsky** [comment]
sounds like we don't need the new class 'infantile/childhood-onset epilepsy syndrome' at the moment. can we close this ticket?
