### ISSUE TITLE
OBO ConformsTo has two instances of part_of?

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3355]
Hi
I was browsing the ConformsTo tree and noticed there were two instances for part_of
I do not know if this is to be expected, one has so# but I've flagged it up just in case it was important

http://purl.obolibrary.org/obo/so#part_of

http://purl.obolibrary.org/obo/part_of

from : 
<img width="357" alt="part-of" src="https://user-images.githubusercontent.com/14925172/126762974-3925137c-dcde-4d5a-acf7-5afcc9122bde.png">

**Comment by nicolevasilevsky** [comment]
Hi @lcdaugherty - thanks for reporting this. Looks like one of these is coming from the sequence ontology (SO) import.

We discussed this on our Mondo call, and decided we will remove these SO properties from Mondo. @matentzn we just want to bring in the classes and labels from SO.
