### ISSUE TITLE
MONDO:0018965 Alport syndrome MONDO:0005334 hereditary nephritis both ExactMatch  MeSH:D009394

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3367]
http://purl.obolibrary.org/obo/MONDO_0018965 Alport syndrome

http://purl.obolibrary.org/obo/MONDO_0005334 hereditary nephritis

both have exactMatch
http://identifiers.org/mesh/D009394  Nephritis, Hereditary

Hereditary Nephritis seems to describe a group of conditions of which Alport Syndrome is the most common, but there does not seem to have any parent/child relationship between the MeSH term and Alport syndrome?

**Comment by nicolevasilevsky** [comment]
this is fixed now :)
