### ISSUE TITLE
Question regarding status of adrenal gland hyperfunction MONDO:0006640

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3376]
adrenal gland hyperfunction MONDO:0006640 
Has comment
"Editor note: consider obsoleting as is phenotypic feature" 
Will this be obsoleted or maintained? There is an active UMLS entry for the same concept, so if this will be maintained, GTR/MedGen will add the Mondo ID to our data.

**Comment by nicolevasilevsky** [comment]
If you will use this term, we'll keep it!

@sabrinatoro could you please remove the comment and add a seeAlso to this ticket? Thanks!
