### ISSUE TITLE
XPNPEP3 is part of a phenotypic series

### ISSUE THREAD

**Issue by tsneddon** [monarch-initiative/mondo#3381]
**Mondo term (ID and Label)**
MONDO:0013163 nephronophthisis-like nephropathy 1

**Synonym to be added**
NPHP-XPNPEP3

**Synonym subtype: ie, broad/exact/narrow/related**

**Database cross reference for the synonym** Such as PubMed ID (in the format PMID:XXXXXX) or a cross-reference to another ontology, like OMIM or Orphanet.
PMID:32660933
Would OMIM consider renaming to be consistent with it's phenotypic series ie Nephronophthisis 21?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
> Would OMIM consider renaming to be consistent with it's phenotypic series ie Nephronophthisis 21?

@ahamosh ⬆️ 👀

**Comment by nicolevasilevsky** [comment]
Thanks @tsneddon!

@kallia-p could you please add the exact synonym:
NPHP-XPNPEP3
dbxref: PMID:32660933
