### ISSUE TITLE
[NTR/gene] SEC61B-related polycystic liver disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3382]
- [x] add **Preferred gene-related syndrome label**
SEC61B-related polycystic liver disease

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
'autosomal dominant polycystic liver disease'

- [x] add **Definition**
Any autosomal dominant polycystic liver disease in which the cause of the disease is a mutation in the SEC61B gene.

- [x] add **Definition database cross reference**
PMID:29038287

- [x] add **seeAlso**:
https://github.com/monarch-initiative/mondo/issues/1882

- [x] need to import http://identifiers.org/hgnc/16993 (see instructions here: https://mondo.readthedocs.io/en/latest/editors-guide/import-terms-for-logical-axioms/. Note, you need to have Docker installed to run this, see instructions [here](https://mondo.readthedocs.io/en/latest/editors-guide/set-up-new-computer/#set-up-docker)

- [x] add logical def:
'autosomal dominant polycystic liver disease' and ('disease has basis in dysfunction of' some SEC61B)

cc @tsneddon

@ahamosh - do you think OMIM will add such a disease?
I see mention that this gene may be implicated in polycystic liver disease on this [page](https://omim.org/entry/609214?search=sec61b%20gene&highlight=gene%20sec61b#2)

**Comment by ahamosh** [comment]
We added the paper that described 2 patients, but did not established a gene-phenotype relationships because we think that more patients are need to prove the relationship. Also one of the 2 patients described also had a kidney cyst.

**Comment by tsneddon** [comment]
@ahamosh  OK - when more information is available, I'm assuming it will be added to the OMIM PS174050 phenotypic series as eg "Polycystic liver disease 5 with or without kidney cysts".

**Comment by ahamosh** [comment]
The number depends on when there is sufficient evidence.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh. @tsneddon we can go ahead and add this term to Mondo since your team needs it and we'll update it with the cross-reference to the OMIM ID, if one is created in the future.

**Comment by nicolevasilevsky** [comment]
@Vineyardintern I assigned this to you. Let me or @sabrinatoro know if you have any questions about the steps involved.
