### ISSUE TITLE
MONDO:0007057 acroosteolysis dominant type remove ExactMatch obsolete MeSH C531695 add C537586

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3390]
MONDO:0007057 acroosteolysis dominant type  
http://purl.obolibrary.org/obo/MONDO_0007057

exactMatch http://identifiers.org/mesh/C531695 is Obsolete term

Suggest:
Add exactMatch https://meshb-prev.nlm.nih.gov/record/ui?ui=C537586  Serpentine fibula polycystic kidney syndrome
Add Serpentine fibula polycystic kidney syndrome from related synonym to has exact synonym baed on ref: orphanet ORPHA:2853- 'This entity has been excluded from the Orphanet nomenclature of rare diseases and moved to Hajdu-Cheney syndrome'  and https://rarediseases.info.nih.gov/diseases/508/acroosteolysis-dominant-type, 'Serpentine fibula polycystic kidney syndrome' is listed as other names

I might be getting a bit lost in trying to resolve MeSH IDs, so please let me know if I am interpreting them wrong/if this is helpful at all to the MONDO resource given the disease concept of MeSH is an xref and not a source. Thank you!

**Comment by nicolevasilevsky** [comment]
This is very helpful @lcdaugherty, thanks for reporting this. We'll look into it asap.

**Comment by nicolevasilevsky** [comment]
@matentzn in OLS, this MESH term (MESH:C531695) is listed as an exact match, but it is not annotated as MONDO:equivalentTo in the mondo-edit.obo file, so it shouldn't be listed as an exact match in OLS.

**Comment by matentzn** [comment]
Seems to me this cross reference has no `MONDO:something` qualification (source property).. @nicolevasilevsky you should just add this (Mondo:related, or whatever the correct one is for this term)..
