### ISSUE TITLE
[Merge] MONDO:0018226 infantile epileptic-dyskinetic encephalopathy with MONDO:0010632 developmental and epileptic encephalopathy, 1

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3391]
IEE nomenclature and grouping is quite challenging, so I might be out on a limb here...but I came across this scenario whilst looking at what seems be an obsoleted MeSH term, and wondered if these two MONDO terms should be merged, with updates to the Database cross references and has exact synonyms?

**Term to be obsoleted** infantile epileptic-dyskinetic encephalopathy http://purl.obolibrary.org/obo/MONDO_0018226

**Reason for deprecation**
MeSH:C538670 (X-linked infantile spasm syndrome) is an obsoleted ID and seems to have been replaced with C567924 Infantile Epileptic-Dyskinetic Encephalopathy https://meshb.nlm.nih.gov/record/ui?ui=C567924 (Entry term includes 'X-linked infantile spasm syndrome')

The entry MONDO:0018226 Infantile Epileptic-Dyskinetic Encephalopathy http://purl.obolibrary.org/obo/MONDO_0018226 (ExactMatch Orphanet: 364063) should be merged with MONDO:0010632 developmental and epileptic encephalopathy, 1 http://purl.obolibrary.org/obo/MONDO_0010632 (ExactMatch OMIM:308350)

The term infantile epileptic-dyskinetic encephalopathy should be Exact Synonym and MeSH: C567924 as ExactMatch. 

**Term to be merged with** 
developmental and epileptic encephalopathy, 1 http://purl.obolibrary.org/obo/MONDO_0010632

**Comment by nicolevasilevsky** [comment]
@ihelbig could you comment on this? Is

MONDO:0018226 Infantile Epileptic-Dyskinetic Encephalopathy

the same as

MONDO:0010632 developmental and epileptic encephalopathy, 1

Thank you!

**Comment by nicolevasilevsky** [comment]
Hi @lcdaugherty 

Ingo Helbig said: I would neither merge nor obsolete at this point as both terms are not 100% correct and as this should be part of a larger restructuring of the MONDO terms. We have a meeting on ClinGen nomenclature soon, which may give us some guidance surrounding this! 

If you don't mind, I'll close this for now and wait until ClinGen epilepsy experts get back to us with recommendations as to how to restructure our naming in Mondo. 

thank you!

**Comment by lcdaugherty** [comment]
@nicolevasilevsky yes would prefer the restructuring option, thank you
