### ISSUE TITLE
fetal alcohol spectrum disorder(s) MONDO:0021720 and MONDO:0000408 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3393]
**Mondo term (ID and Label)**
MONDO:0021720 and MONDO:0000408 
fetal alcohol spectrum disorder(s) 

**Reason for deprecation**
I don't see why these should be split... UMLS CUI: C2985290 X-refs MESH: D063647 and this term itself uses both the singular and plural form as synonymous terms.

**Term to be merged with**
MONDO:0000408 seems to be the "most complete" term with a better defined set of hierarchical relationships and has the smaller ID, so I guess keep that one? Either way the merge goes is not that critical to me.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems, we'll aim to get this into the Sept release.
