### ISSUE TITLE
pachydermoperiostosis vs. primary hypertrophic osteoarthropathy

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3395]
Action item:

- [x] merge:
MONDO:0009799 pachydermoperiostosis with
MONDO:0016620 'primary hypertrophic osteoarthropathy'

Reason: duplicate

_updated by NV 2021-10-20_

-----

I am looking for clarification on these two terms: primary hypertrophic osteoarthropathy MONDO:0016620 and pachydermoperiostosis MONDO:0009799
On the Pachydermo. term, I see X-ref SCTID: 88220006 is a Mondo equivalent term. It looks like SNOMED themselves say this term is SYN with primary hypertrophic osteoarthropathy (at least per the UMLS display of these terms) and the MESH concept 
D010004 also uses the terms interchangeably. (https://www.ncbi.nlm.nih.gov/mesh/?term=D010004)
![image](https://user-images.githubusercontent.com/71083858/127392848-672a6e04-5479-481d-bb0c-65917a2eb676.png)
The OMIM PS for Hypertropic osteoarthropathy, primary - PS259100 and the Orphanet MIM x-refs on ORPHA:2796 seem to conflict on the defining subset of conditions of the these two terms. http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=2796 (Cranio-osteoarthropathy being the outlier) As such, I'm getting two different Mondo terms as valid matches for a single UMLS CUI : C0029411. 
@ahamosh and @ana-rath-orphanet @Orphanet (and anyone else who is more clinically educated than I am!) Can we get a consensus if these are synonyms (as implied by SNOMED and MESH) or if we can consider renaming so we get distinct SCTIDs for the ORPHANet subset? (Note: there is Pachydermoperiostosis-familial, UMLS CUI C0542418 which X-refs SCTID 254133005, but even that SCTID conflates Familial hypertrophic osteoarthropathy with familial pachydermoperiostosis, so it's kind of lousy work-around to actually clarifying the terms)

**Comment by ahamosh** [comment]
What I read in OMIM is that familial hypertrophic osteoarthropathy is synonymous with familial pachydermoperiostosis.  There are 2 responsible genes.  Variants in SLCO2A1 cause both dominant and recessive disease, variants in HPGD cause dominant disease.  The phenotypic manifestations range from bone and skin thickening, to bone only or skin only.  

Cranioosteoarthropathy is a separate condition due to biallelic mutation in the HPGD.

**Comment by nicolevasilevsky** [comment]
C0029411 is equiv to 'primary hypertrophic osteoarthropathy' and marked as a subClassOf on 'hypertrophic osteoarthropathy, primary, autosomal recessive, 1'.
