### ISSUE TITLE
neurodevelopmental disorder with cardiomyopathy, spasticity, and brain abnormalities (NEDCASB; 619121)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3410]
HI,

I don't find a term for NEDCASB in MONDO?

https://www.omim.org/entry/138450#molecularGenetics
In 5 patients from 4 unrelated families with neurodevelopmental disorder with cardiomyopathy, spasticity, and brain abnormalities (NEDCASB; 619121), Garcia-Cazorla et al. (2020) identified homozygous or compound heterozygous mutations in the SHMT2 gene (138450.0001-138450.0007).

Thanks
Val

**Comment by nicolevasilevsky** [comment]
Hi @ValWood this is it:
MONDO_0030866 'neurodevelopmental disorder with cardiomyopathy, spasticity, and brain abnormalities'

Please reopen if anything else is needed

**Comment by ValWood** [comment]
perfect, thanks. I was searching Monarch, I know I should use OLS but I prefer monarch to check other things and then forget to refer.

**Comment by ValWood** [comment]
Actually should this term be in Monarch now. I forgot about this ticket  and was searching on this term again yesterday.  
https://github.com/monarch-initiative/monarch-ui/issues/440

@matentzn  was looking at an import problem back in April?
https://github.com/monarch-initiative/mondo/issues/3009

Should this term be in Monarch now?

**Comment by matentzn** [comment]
Hey @ValWood ! We can only really control here what appears in Mondo - Monarch has a much slower update cycle, and its better to use https://github.com/monarch-initiative/helpdesk for questions about https://monarchinitiative.org/

**Comment by ValWood** [comment]
OK, no worries. I just wanted to check that the earlier problem was fixed and that wasn't the reason I could not find it yet. I thought there had. been a couple of releases, but I. think I am confusing MONDO releases with Monarch releases.

**Comment by matentzn** [comment]
Thats the one: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0030866

**Comment by nicolevasilevsky** [comment]
Good question! I don't see any reason not to add this term.

@pnrobinson @ahamosh @cmungall please let us know if you have any objections, thanks!

**Comment by ahamosh** [comment]
Neurodevelopmental disorder should be a superclass under Nervous system disorder.

**Comment by nicolevasilevsky** [comment]
Thank you @ahamosh!

**Comment by pnrobinson** [comment]
@ahamosh  I wonder if if would be a good idea to use OMIM phenotypic series, such as this https://omim.org/phenotypicSeries/PS309530, to arrange diseases that would be subclasses of a new term called **Neurodevelopmental disorder**?

**Comment by sabrinatoro** [comment]
I created a new term "neurodevelopmental disorder".
Chidren terms will be added under this new term in #3680

**Comment by ahamosh** [comment]
Hi @pnrobinson, sorry for the delay.  I think that all the IDs (Dominant, recessive and X-linked) could be added under this, but also all the NED* in OMIM. There are many.  Happy to discuss this complicated and difficult topic...
