### ISSUE TITLE
MONDO:0021141 "acquired"[Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3411]
**Mondo term (ID and Label)**
 MONDO:0021141 "acquired"

**Reason for deprecation**
It seems like this doesn't need to be maintained as a distinct disease concept, but supported rather as a descriptor of some diseases. Also Orpha409941 doesn't seem to exist anymore.

**Suggested term to consider**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
thanks @kanems! We use this term in the disease axioms, for terms like 'acquired angioedema', 'acquired aplastic anemia'. It is in the 'disease characteristic' branch. We don't want to obsolete it.

I still see it in Orphanet:
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_409941

(unless this is out of date).

I'll close this but please reopen if further action is needed.

**Comment by kanems** [comment]
@nicolevasilevsky - I don't see this one on Orphanet's main page when I search by OrphaID https://www.orpha.net/consor/cgi-bin/Disease_Search_Simple.php?lng=EN but I get the need to keep it in Mondo for disease axioms. @maglott - we should discuss if we need to do anything for our processing of Mondo concepts to keep this term private on MedGen/GTR.

**Comment by nicolevasilevsky** [comment]
I don't see it there either, but I downloaded their ontology from bioportal and I do see it there:
![image](https://user-images.githubusercontent.com/6722114/127701943-07173ad6-8d01-438e-95f3-7b4d9b541560.png)
