### ISSUE TITLE
split term: acrofrontofacionasal dysostosis MONDO:0008715

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3412]
**Term to split:**
acrofrontofacionasal dysostosis MONDO:0008715
**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
acrofrontofacionasal dysostosis MONDO:0008715
NT: acrofrontonacionasal dysostosis 1  (Set as a child of current term, sib to MONDO:0009402)

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonynms that end in "1", "2", etc. should move to subclass.
MIM 201180; UMLS C4551987
exact syn from parent concept to move: acrofrontofacionasal dysostosis type 1
ADD MESH: C538186

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I created a new subclass MONDO:0100044 acrofrontofacionasal dysostosis 1
