### ISSUE TITLE
Difference between red cell aplasia and pure red-cell aplasia?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3413]
Is there a difference between MONDO:0001705 pure red-cell aplasia and MONDO:0020113 red cell aplasia ?

The sources on UMLS CUI: C0034902 seem to occasionally equate these terms, as does HPO (from a phenotypic perspective). I am wondering if the Red cell aplasia term should be renamed to match the current OrphaNet preferred name ORPHA:98421 Primary acquired red cell aplasia. Seems like that would make sense and make for a more specific term preferred name since this is in the tree as a child of the acquired aplastic anemia concept.

**Comment by nicolevasilevsky** [comment]
Thanks for reporting this issue, @kanems. We can certainly change the label.

@pnrobinson or @ahamosh could you provide any advice on this? Thank you!

**Comment by ahamosh** [comment]
They are the same.  Use whichever term is currently used.

**Comment by nicolevasilevsky** [comment]
@kanems I relabeled MONDO:0020113 to Primary acquired red cell aplasia.

Did you want to request that these two terms are merged?

**Comment by kanems** [comment]
HI Nicole, I don't think these should be merged if one is now distinguished as an "acquired" form. The children of "pure red-cell aplasia" include all of the Diamond-Blackfan anemias, which are not acquired but genetic.
There are valid Snomed (50715003), MESH (D012010), and UMLS (C0034902) IDs for this "pure red-cell aplasia" term, so IMO there is some evidence to support it's existence as a disease concept.

**Comment by ahamosh** [comment]
Maybe there should be  an acquired red cell aplasia and a genetic or hereditary or monogenic red cell aplasia to distinguish at a high level.

**Comment by pnrobinson** [comment]
@ahamosh are there Mendelian diseases with isolated RBC aplasia? I thought this was rather a feature of many pleiotropic diseases.

**Comment by ahamosh** [comment]
DBA1 (MIM 105650) is listed with an alternate title of Hereditary Pure Red Cell Aplasia, but 3-50% of patients have other phenotypic features.  The other DBAs don't have the Hereditary Pure Red Cell Aplasia listed.  I am not sure what the right answer is here...

**Comment by pnrobinson** [comment]
I was not aware of that, thanks. Still, maybe we should have a superclass of Diamond Blackfan for this? Is there any useful grouping of DBA with other groups of diseases?

**Comment by nicolevasilevsky** [comment]
We currently have 'acquired aplastic anemia' and 'inherited aplastic anemia', with 'Diamond-Blackfan anemia' (OMIM phenotypic series) as a child, and the subtypes of DBA. I think this addresses all of the comments above, i am going to close this but please reopen if other action items are needed.

![image](https://user-images.githubusercontent.com/6722114/133647823-7441ad2a-b787-4498-a89c-09ce97b9c4fb.png)
