### ISSUE TITLE
[Obsolete] 'chemically-induced disorder'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3414]
**Mondo term (ID and Label)**
MONDO_0029001 'chemically-induced disorder'
MONDO_0045028 'radiation or chemically induced disorder'

**Reason for deprecation**
'chemically-induced disorder' is a grouping class from MeSH. There was discussion about moving this to a subclass of injury, but upon reviewing the children, the children are not really injuries. It doesn't seem like this grouping class is that useful.

'radiation or chemically induced disorder' is a grouping class we created.

Reason: out of scope

**Suggested term to consider**
injury
http://purl.obolibrary.org/obo/MONDO_0021178

see https://github.com/monarch-initiative/mondo/issues/922

cc @zoependlington

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
The only asserted class is "poisoning". I propose that we obsolete "'chemically-induced disorder' (MONDO:0029001), but keep "poisoning" as a high-level class (these are technically not disease or disorder, but are helpful to have), and tag with the "Harrison" subset.

**Comment by nicolevasilevsky** [comment]
sounds good!

**Comment by sabrinatoro** [comment]
part of #2741
