### ISSUE TITLE
[Revise subclass] 'radiation-induced disorder'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3415]
**Mondo term (ID and Label)**
'radiation-induced disorder'

**Suggested revision and reasons**
should this be a child of MONDO_0021178 injury?

related to https://github.com/monarch-initiative/mondo/issues/922
https://github.com/monarch-initiative/mondo/issues/3414

cc @zoependlington

**Comment by sabrinatoro** [comment]
Proposal: If we want to keep this class as an upper class, 'radiation-induced disorder' (MONDO:0043459) should be completely inferred (i.e should not have asserted child).
Currently, this term has 2 asserted children, which both could be updated such that they would be inferred in this subclass.

**Comment by sabrinatoro** [comment]
part of #2741
