### ISSUE TITLE
MONDO:0024293 polyposis, gastric, Dos Santos and de Magalhaes 1980 [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3416]
**Mondo term (ID and Label)**
MONDO:0024293 polyposis, gastric, Dos Santos and de Magalhaes 1980 

**Reason for deprecation**
The MIM number cross-referenced by this term has been merged with https://omim.org/entry/619182 and the CUI from UMLS is now called "Polyposis, Gastric"  and lists SCTIDs currently on MONDO:0008277 "stomach polyp"
![image](https://user-images.githubusercontent.com/71083858/127697086-f47590c0-bd33-42e8-943f-7f2b55da15ea.png)

**Suggested term to consider**
 MONDO:0008277 "stomach polyp" and include the polyposis concept?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I will merge MONDO_0024293 'polyposis, gastric, Dos Santos and de Magalhaes 1980' with MONDO_0017790 'gastric adenocarcinoma and proximal polyposis of the stomach', as OMIM did.
