### ISSUE TITLE
Obsolete term still in hierarchy (MONDO_0004589)

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#344]
Hi, just noticed a term (MONDO_0004589) pop up in our EFO 3 build as deprecated. Looks like it's been deprecated but still has parent classes and child classes/hasn't been fully replaced with the replacement term. See [here](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004589). Thanks!

**Comment by nicolevasilevsky** [comment]
thanks @zoependlington, I fixed this on a PR.

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,
It looks like the obsoleted term MONDO_0004589 still has children, see its entry in OLS where the MONDO version dated Sept 26th is loaded:
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004589
Could you (or someone else) please look into this? Many thanks - obsoleted terms sometimes come back to haunt you ;-)
