### ISSUE TITLE
[Revise subclass] 	trimethylaminuria is_a metabolic disease

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#3448]
**Mondo term (ID and Label)**
trimethylaminuria (MONDO:0011182)

**Suggested revision and reasons**

is_a metabolic disease (MONDO:0005066) of some sort?

**Comment by nicolevasilevsky** [comment]
Thanks @ValWood. We discussed this on the Mondo call and these are our action items, I'll work on this:

- keep the parent as a grouping class
- make the OMIM a subtype of the grouping class
- the OMIM and Orphanet are equiv (merge)
- there is a secondary class discussed on the NORD page, see: https://rarediseases.org/rare-diseases/trimethylaminuria/

add logical axiom: https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/inborn_metabolic_disrupts.yaml

**Comment by nicolevasilevsky** [comment]
@ValWood 
Please note the following changes:
MONDO_0011182 trimethylaminuria is a general grouping class
MONDO_0018767 'severe primary trimethylaminuria' is a subtype with a mutation in FMO3, and xrefs Orphanet and OMIM
We added MONDO_0100041 'secondary trimethylaminuria'
