### ISSUE TITLE
Include AML-NCIT terms

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3452]
terms are in the document here: 
https://docs.google.com/spreadsheets/d/1NZqf0uIzSeZ5XfVXePH0_iiR0WjyPS2ADSmK6uaYh9c/edit?usp=sharing

Note, this was requested by Deanne Taylor (@taylordm): https://orcid.org/0000-0002-3302-4610

**Comment by nicolevasilevsky** [comment]
@matentzn this looks good.
Can we make a couple edits - add source annotation on the subclassOf axiom
and add dbxref on the definitions?

If you can just tell me what the headers are for the ROBOT template, I can attempt to run this myself

(note to self, instructions here: https://mondo.readthedocs.io/en/latest/editors-guide/robot-template/)

**Comment by nicolevasilevsky** [comment]
Also, if Deanne needs this ASAP, I should probably run another mid-cycle release, yeah?

**Comment by matentzn** [comment]
I redid the PR, see comments here: https://github.com/monarch-initiative/mondo/pull/3463

I put placeholders in the columns (axiom annotations) you asked for, xrefs on defs and is a etc, make sure you review carefully.

**Comment by nicolevasilevsky** [comment]
Note, this was requested by Deanne Taylor: https://orcid.org/0000-0002-3302-4610

**Comment by nicolevasilevsky** [comment]
action items:
- [ ] Also, it is very important that open targets knows how to connect Deanne's data to these Mondo terms - make sure someone is on top of that somehow (send an email to @taylordm).
- [ ] Once she has approved, and OTAR strategy is clear, you merge, make a mid cycle release
- [ ] I will then work with @zoependlington to get the terms into EFO

**Comment by cmungall** [comment]
let's make a new ticket for alining to

https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C3171

![image](https://user-images.githubusercontent.com/50745/128576736-95e54f37-698d-40d8-b708-7a98dcd2cf42.png)

**Comment by nicolevasilevsky** [comment]
new ticket: #3472
