### ISSUE TITLE
[Obsolete] terms marked as 'obsoletion candidates'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3456]
term to obsolete ID | term to obsolete Label| term to consider ID | term to consider label
-- | -- | -- | --
<http://purl.obolibrary.org/obo/MONDO_0015119> | bronchopulmonary tumor | http://purl.obolibrary.org/obo/MONDO_0020641 | respiratory tract neoplasm'
<http://purl.obolibrary.org/obo/MONDO_0016254> | rare variants of adenocarcinoma of the corpus uteri | http://purl.obolibrary.org/obo/MONDO_0003629 | uterine corpus serous adenocarcinoma'
<http://purl.obolibrary.org/obo/MONDO_0016629> | hemorrhagic disorder due to a platelet anomaly | http://purl.obolibrary.org/obo/MONDO_0002243 | hemorrhagic disease'
<http://purl.obolibrary.org/obo/MONDO_0016632> | thrombotic disorder due to a coagulation factors defect | http://purl.obolibrary.org/obo/MONDO_0000831 | thrombotic disease'
<http://purl.obolibrary.org/obo/MONDO_0016635> | thrombotic disorder due to a platelet anomaly | http://purl.obolibrary.org/obo/MONDO_0000831 | thrombotic disease'
<http://purl.obolibrary.org/obo/MONDO_0016767> | cutaneous lichen planus | http://purl.obolibrary.org/obo/MONDO_0006572 | lichen planus'
<http://purl.obolibrary.org/obo/MONDO_0017141> | hemorrhagic disorder due to a constitutional thrombocytopenia | http://purl.obolibrary.org/obo/MONDO_0002243 | hemorrhagic disease'
<http://purl.obolibrary.org/obo/MONDO_0017663> | inherited tremor disorder | http://purl.obolibrary.org/obo/MONDO_0005395 | movement disorder'
<http://purl.obolibrary.org/obo/MONDO_0018729> | genetic vascular tumor | http://purl.obolibrary.org/obo/MONDO_0024296 | vascular neoplasm'
<http://purl.obolibrary.org/obo/MONDO_0019183> | inherited odontologic disease | http://purl.obolibrary.org/obo/MONDO_0006999 | tooth disease'
<http://purl.obolibrary.org/obo/MONDO_0019993> | congenital renal artery stenosis | http://purl.obolibrary.org/obo/HP:0001920 | Renal artery stenosis
<http://purl.obolibrary.org/obo/MONDO_0020092> | rare idiopathic male infertility | http://purl.obolibrary.org/obo/MONDO_0005372 | male infertility'

related to https://github.com/monarch-initiative/mondo/issues/1405

**Comment by nicolevasilevsky** [comment]
instructions for obsoleting terms is here:
https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#obsolete-a-class-without-merging

**Comment by nicolevasilevsky** [comment]
I did not obsolete congenital renal artery stenosis per https://github.com/monarch-initiative/mondo/issues/1741. I removed the obsoletion candidate tag.

**Comment by larrybabb** [comment]
@nicolevasilevsky I didn't see `congenital renal artery stenosis` from the obsoleted terms above in the release notes with the september release. Can you verify and let me know if that was simply an oversight when crafting the release notes or did that not make it into the release?

**Comment by nicolevasilevsky** [comment]
Hi @larrybabb - this wasn't obsoleted after all, due to this ticket: https://github.com/monarch-initiative/mondo/issues/1741
