### ISSUE TITLE
Obsolete term: asymptomatic dengue MONDO:0000259

### ISSUE THREAD

**Issue by daniwelter** [monarch-initiative/mondo#346]
I'm trying to trace why the term "asymptomatic dengue" (MONDO:0000259) was obsoleted, and when. We mapped some data in the Human Cell Atlas to it and discovered yesterday that our validation against the term is now failing, so are trying to update to a better mapping but there is no information on why the term was obsoleted and what it's been replaced with.

**Comment by cmungall** [comment]
Apologies for this. We should have a general principle regarding 
asymptomic diseases - are these really diseases?

Nicole, can you reinstate the class?

Now that we are past our initial phase and the MONDO has settled into a 
stable state we should have a standard announce policy prior to 
obsoletion.

**Comment by nicolevasilevsky** [comment]
yes, will do!
