### ISSUE TITLE
[NTR] congenital right-sided heart lesions

### ISSUE THREAD

**Issue by kallia-p** [monarch-initiative/mondo#3461]
We have had a request by the GWAS catalog team to add congenital right-sided heart lesions http://www.ebi.ac.uk/efo/EFO_0600032

**Preferred term label:**
congenital right-sided heart lesions

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Serious heritable structural anomalies of the right side of the heart, including pulmonary atresia, tricuspid valve disease and Ebstein's anomaly, and right ventricular outflow tract obstruction and/or pulmonary stenosis, that are present from birth.
Definition dbxref could be EFO:0600032

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
http://purl.obolibrary.org/obo/MONDO_0019512

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
orcid.org/0000-0002-5460-8025

**Comment by nicolevasilevsky** [comment]
sounds good! @kallia-p would you like to go ahead and add this?

**Comment by kallia-p** [comment]
@nicolevasilevsky In MONDO we have congenital left-sided heart lesions which is equivalent to the EFO term congenital left-sided heart lesions. I 've assigned this to me.

**Comment by nicolevasilevsky** [comment]
yes, i saw that!

Thanks @kallia-p!

**Comment by nicolevasilevsky** [comment]
Hi @kallia-p do you plan to add this term, or I can go ahead and do it if you prefer.

**Comment by kallia-p** [comment]
@nicolevasilevsky @matentzn 

Hi both, QC failed this PR https://github.com/monarch-initiative/mondo/runs/3731090962?check_suite_focus=true

make: *** [sparql_test_edit] Error 1
Makefile:464: recipe for target 'sparql_test_edit' failed
Error: Process completed with exit code 2.

**Comment by nicolevasilevsky** [comment]
the error is actualy this:
`FAIL Rule ../sparql/qc/general/qc-permitted-properties.sparql: 1 violation(s)
term,property,value
http://purl.obolibrary.org/obo/MONDO_0600027,http://purl.obolibrary.org/obo/mondo#created_by,http://orcid.org/0000-0002-5460-8025`

I believe it is because your created_by property is incorrect, once you fix this in preferences as outlined in https://github.com/monarch-initiative/mondo/pull/3721, this should not happen again.

I'll fix this on this PR.
