### ISSUE TITLE
Create the Harrison view 

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3465]
All the tickets for the Harrison work have been completed. 

Please create the Harrison view. The high-level terms in this view should be the terms tagged with  "in_subset ‘harrisons view’ "

**Comment by sabrinatoro** [comment]
assigning to @matentzn, but feel free to assign to someone else.

**Comment by matentzn** [comment]
Please mention to me during QC call - will do it right then and there.

**Comment by sabrinatoro** [comment]
duplicate of #3535
