### ISSUE TITLE
ontologize the variables in these spreadsheets

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#347]
This folder contains NJ Health Spreadsheets and Documents, which are related to the COPDGene Data:
https://drive.google.com/drive/u/0/folders/1CEbC3XqsQGkstwaDoYyXLn_302gVQiLP

**Comment by nicolevasilevsky** [comment]
@cmungall is this still needed?

**Comment by ashokohio** [comment]
Nicole, It will be great if you can do that, because it will contribute directly to one of our deliverables for DATA STAGE.

**Comment by nicolevasilevsky** [comment]
Hi @ashokohio- I am finished curating this spreadsheet: https://docs.google.com/spreadsheets/d/1_uiBeHlE7wtoOPJqG9H7PPU6ipGOjVHIDIxA8jtMxxo/edit#gid=476143062

Could you please review and let me know if there are any issues?

I'll work on the other spreadsheets as well.

**Comment by nicolevasilevsky** [comment]
Ok - looks like the other two spreadsheets were almost the same as the first one, I added the ontology mappings to those spreadsheets as well. I think I am done for now, but please reopen this ticket if anything else is needed.
