### ISSUE TITLE
Availability of TSV/CSV version of this ontology

### ISSUE THREAD

**Issue by LucaCappelletti94** [monarch-initiative/mondo#3474]
Hello,

I wanted to add this ontology to the set of graphs that can be automatically retrieved when using [Ensmallen](https://github.com/AnacletoLAB/ensmallen_graph), and to do so I would need a stable URL where the various versions of the ontology are hosted in a TSV-like format (like the [STRING graphs](https://stringdb-static.org/download/) for instance).

Is there already one such thing? If no, would it be possible to make the ontology available like this?

Best,
Luca Cappelletti

**Comment by LucaCappelletti94** [comment]
Closing issue per suggestion of @matentzn.

**Comment by matentzn** [comment]
For posterity, this should be discussed as: "should all ontologies provide a KGX release"?
