### ISSUE TITLE
MONDO:0100096 COVID-19 when MONDO:equivalentObsolete xref but remains as ExactMatch?

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3497]
@nicolevasilevsky @sabrinatoro

re: #2766

OLS that MeSH:C000657245 has: MONDO:equivalentObsolete
I am sorry I do not understand this, can you please explain the reasoning for keeping the obsoleted MESH ID as an ExactMatch?

MONDO:equivalentObsolete is the database cross reference section, so does this mean that in addition to the ExactMatch data do I also need to cross reference the database to make sure it is a true ExactMatch?

I am not sure this makes sense, I would have thought the obsoleted MESH ID would be removed from the ExactMatch section, or at the very least move to CloseMatch?

I might not have understood this fully, so hopefully you can explain the reasoning. Thank you!

**Comment by nicolevasilevsky** [comment]
This _should_ be fixed now. I will check this after the November release.

**Comment by lcdaugherty** [comment]
@nicolevasilevsky thank you - fingers crossed! :)
