### ISSUE TITLE
MONDO:0010829 CARASIL syndrome incorrect ExactMatch DOID:13945. Possible subclass relationship revision needed MONDO:0007432 cerebral arteriopathy with subcortical infarcts and leukoencephalopathy

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3505]
**Mondo term (ID and Label):**
MONDO:0010829 C**AR**ASIL syndrome
http://purl.obolibrary.org/obo/MONDO_0010829
has exact synonym 'cerebral autosomal recessive arteriopathy with subcortical infarcts and leukoencephalopathy'

**Xref that should be fixed (ID and label):**
Currently this entry has ExactMatch DOID:13945  https://www.disease-ontology.org/term/DOID:13945/
Although the same causative gene HTRA1, this DOID represents the 'cerebral **autosomal dominant** arteriopathy with subcortical infarcts and leukoencephalopathy'

OMIM PS series explains this group well: https://omim.org/phenotypicSeries/PS125310
Currently there seems to be some mix up between the HRTA1 subtypes that result from different MOI (AR/AD) and the descriptions for type1 (CADASIL1-NOTCH3-MOI AD) and type 2 (CADASIL2-HTRA1 MOI AD) and where these are placed with CARASIL syndrome (HTRA1- MOI-AR), so this might indicate some revision of terms under MONDO:0007432 cerebral arteriopathy with subcortical infarcts and leukoencephalopathy

<img width="741" alt="mondo_0007432" src="https://user-images.githubusercontent.com/14925172/129021953-301441e1-efe8-462f-b785-b84c3f68b594.png">

**Other comments:**
Linked to  #1486

**Comment by sabrinatoro** [comment]
looking at the classification:
![Screen Shot 2021-09-20 at 3 24 16 PM](https://user-images.githubusercontent.com/12737987/134086893-fe495f00-99a1-4605-a3ae-ab7f74e6686f.png)
- parent term =  MONDO:0007432 = DOID:13945  = OMIMPS:125310 
**(no DO annotation in the Mondo record --> to be added)**  
  - type1 (Notch3) = MONDO:0000914 = DOID:0111035 = OMIM:125310 → ok
  - type2 (HTRA) = MONDO:0014768 = DOID:0111036 = OMIM:616779 → ok
      - CARASIL syndrome = subtype of HTRA = OMIM:600142 - MONDO:0010829 
            **(not in DO --> xref to be removed from MONDO:0010829)**

To Do: 

- [ ] add DOID:13945 as MONDO:equivalentTo  for MONDO:0007432 
- [ ] DOID:13945 should not be MONDO:equivalentTo  for MONDO:0010829
- [ ] Need to communicate with OMIM to check whether OMIM:616779 and OMIM:600142 are should remain 2 different records, or should be merged

**Comment by sabrinatoro** [comment]
@ahamosh 
I want to confirm that these 2 records, OMIM:616779 and OMIM:600142, refer indeed to 2 different diseases, even though the same gene is affected. The corresponding Mondo terms are parent/child (see previous comment). Is it correct? 
Thank you!
