### ISSUE TITLE
polycystic liver disease refinement required : MONDO:0000447 autosomal dominant polycystic liver disease and MONDO:0008265 Polycystic liver disease 1 obsolete ExactMatches and incorrect Exact Synonym

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#3528]
I still seem to be on an ongoing quest to try and resolve some polycystic liver disease issues, this time caused by an Exactmatch xref and has Exactsynonym
I have made some suggestions below to try to resolve this, but you might have a better grasp of what is going on, so wanted to flag it up in the hope it can be resolved- thank you!

**Mondo term (ID and Label):**
MONDO:0000447 autosomal dominant polycystic liver disease http://purl.obolibrary.org/obo/MONDO_0000447

**Xref that should be fixed (ID and label):**
MONDO:0000447 autosomal dominant polycystic liver disease has ExactMatch to DOID:0050770 https://www.disease-ontology.org/term/DOID:0050770/ 
The DOI term name polycystic liver disease is represented by two xrefs 
GARD:9457 https://rarediseases.info.nih.gov/diseases/9457/index  'polycystic liver disease' Other Names: 'Isolated polycystic liver disease'; 'Isolated autosomal dominant polycystic liver disease'; PCLD
OMIM:174050 https://www.omim.org/entry/174050 'Polycystic liver disease 1'

So it looks like the DOID is representing both MONDO:0000447 autosomal dominant polycystic liver disease http://purl.obolibrary.org/obo/MONDO_0000447 and  MONDO:0008265 http://purl.obolibrary.org/obo/MONDO_0008265 Polycystic liver disease 1.
I think because of this association is causing confusion with the associated Exact synonyms 'isolated polycystic liver disease' and 'isolated congenital polycystic liver disease' as they are being associated as has Exact synonym to MONDO:0008265 polycystic liver disease 1 when I think these synonyms are better placed in MONDO:0000447 autosomal dominant polycystic liver disease?

**Mondo term (ID and Label):**
MONDO:0008265 Polycystic liver disease 1 http://purl.obolibrary.org/obo/MONDO_0008265
**Xref that should be fixed (ID and label):**
Has an ExactMatch to UMLS C4255088, however this seems to be obsoleted, as it is no longer found so should be removed
Also, has ExactSynonym 'isolated polycystic liver disease', which I do not think belongs to MONDO:0008265 Polycystic liver disease 1 - rather the parent term MONDO:0000447 autosomal dominant polycystic liver disease

**Xref that should be fixed (ID and label):**
Remove ExactMatch to the obsoleted UMLS:C4255088 from MONDO:0008265 Polycystic liver disease 1 
Remove synonym 'isolated polycystic liver disease'
Add as ExactSynonym to MONDO:0000447 autosomal dominant polycystic liver disease http://purl.obolibrary.org/obo/MONDO_0000447- see below for more info)
Also reconsider  'isolated congenital polycystic liver disease' as an ExactMatch for MONDO:0008265 Polycystic liver disease 1

Why could this isolated polycystic liver disease be added a synonym to MONDO:0000447 autosomal dominant polycystic liver ?
MONDO:0000447 autosomal dominant polycystic liver disease has ExactMatch to another UMLS C0158683: Polycystic liver disease http://linkedlifedata.com/resource/umls/id/C0158683, looking at one of the alternative labels (page 4….) it lists  ’Isolated polycystic liver disease from MeSH (no id).
MONDO:0000447 autosomal dominant polycystic liver disease has an ExactMatch https://meshb.nlm.nih.gov/record/ui?ui=C536330 this includes  'Entry Term(s) Isolated autosomal dominant polycystic liver disease; Isolated polycystic liver disease'.  Adding 'isolated polycystic liver disease'  is also supported by ORPHA:2924 Isolated polycystic liver disease being ExactMatch in MONDO:0000447 autosomal dominant polycystic liver disease

**Other comments:**
links to 'polycystic liver disease' DBxref #3264

**Comment by lcdaugherty** [comment]
Great thank you @nicolevasilevsky @sabrinatoro - I could be well off the mark with my suggestions but sometimes it is hard to find logic in a magic-merry-go-round of disease terms. I  am hoping you can help untangle  how ADPLD and PLD1 are being defined, no pressure! :)

**Comment by nicolevasilevsky** [comment]
- I made  'isolated polycystic liver disease' and 'isolated congenital polycystic liver disease' broad synonyms on 'polycystic liver disease 1'
- I made UMLS:C4255088 equivalentObsolete
I think that addresses everything, please let me know if not. Thanks!
