### ISSUE TITLE
New Term Request: Focal segmental glomerulosclerosis and neurodevelopmental syndrome 

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#3530]
**Preferred term label: Focal segmental glomerulosclerosis and neurodevelopmental syndrome 

**Synonyms: none exist

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######):"Focal segmental glomerulosclerosis and neurodevelopmental syndrome (FSGSNEDS) is characterized by global developmental delay and renal dysfunction manifest as proteinuria and nephrotic syndrome apparent from infancy or early childhood. Some patients present with renal disease, whereas others present with developmental delay and develop renal disease later in childhood. Renal biopsy shows focal segmental glomerulosclerosis (FSGS), but the course of the disease is variable: some patients have transient proteinuria and others require renal transplant. Neurodevelopmental features are also variable, with some patients having only mildly impaired intellectual development, and others having a severe developmental disorder associated with early-onset refractory seizures or epileptic encephalopathy. Additional features, including feeding difficulties, poor overall growth, and nonspecific dysmorphic facial features, are commonly observed (summary by Assoum et al., 2018 and Weng et al., 2021)." (OMIM, MIM:619428)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): Perhaps we can discuss the best parent term for this new disease term. I am unsure as of this time.

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?: Not as of right now.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/): ClinGen Intellectual Disability and Autism GCEP

**Comment by nicolevasilevsky** [comment]
Hi @tibingaman- thanks for this request.

This term is in OMIM (https://omim.org/entry/619428), so we'll be adding it to Mondo in a future OMIM ingest. I am not sure of the timeline for the next ingest, but we may be able to get this in before the next release in September.

Thanks!

cc @matentzn and @sabrinatoro

**Comment by tibingaman** [comment]
Thanks, Nicole! I'll keep an eye out for this release.


All the best,
Taylor

Taylor Bingaman
she/her/hers
Genetic Counseling Assistant
Geisinger ADMI
Lewisburg, PA 17837
570-522-9430

[signature_1478927014]

From: Nicole Vasilevsky ***@***.***>
Sent: Wednesday, August 18, 2021 4:32 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Bingaman, Taylor I. ***@***.***>; Author ***@***.***>
Subject: [External] Re: [monarch-initiative/mondo] New Term Request: Focal segmental glomerulosclerosis and neurodevelopmental syndrome (#3530)

External: Be careful with links and files. If suspicious, alert the Information Security Office. Questions? Call 570-271-8092


Hi @tibingaman- thanks for this request.

This term is in OMIM (https://omim.org/entry/619428<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fomim.org%2Fentry%2F619428&data=04%7C01%7Ctibingaman%40geisinger.edu%7C1ecc4b60c3544ee510bc08d962872dfd%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637649155002376122%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YGnMDzn1H1KlmBLGZSUP7e3SJoOxzjsbgFlMsvxCaHs%3D&reserved=0>), so we'll be adding it to Mondo in a future OMIM ingest. I am not sure of the timeline for the next ingest, but we may be able to get this in before the next release in September.

Thanks!

cc @matentzn<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmatentzn&data=04%7C01%7Ctibingaman%40geisinger.edu%7C1ecc4b60c3544ee510bc08d962872dfd%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637649155002376122%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PNsiZrnqK4m7A6dOoUSHtEKQ%2B18idTmW2k776HYs3VA%3D&reserved=0> and @sabrinatoro<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsabrinatoro&data=04%7C01%7Ctibingaman%40geisinger.edu%7C1ecc4b60c3544ee510bc08d962872dfd%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637649155002386114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2WmIwWZyf%2BKBokyAfbARmnIrt8J1goFpe9iInNovytI%3D&reserved=0>

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmonarch-initiative%2Fmondo%2Fissues%2F3530%23issuecomment-901410690&data=04%7C01%7Ctibingaman%40geisinger.edu%7C1ecc4b60c3544ee510bc08d962872dfd%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637649155002386114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Bqajj5JD8KkWRETMcO5Hev%2FoWNu87GcxsRbG0VdmieQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPJCH56YB4B5ERO3V5PIVSLT5QKCTANCNFSM5CMTBNCQ&data=04%7C01%7Ctibingaman%40geisinger.edu%7C1ecc4b60c3544ee510bc08d962872dfd%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637649155002396109%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3CmeINYLl6Az%2Fv21EnlaX5%2FmrmrcoZpNECCQxcLtd8o%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctibingaman%40geisinger.edu%7C1ecc4b60c3544ee510bc08d962872dfd%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637649155002396109%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uSY81FdGa6Dc0th%2BVDkVggvmUp7%2Fgk1cgKXv2K2xfXY%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Ctibingaman%40geisinger.edu%7C1ecc4b60c3544ee510bc08d962872dfd%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637649155002406105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O%2FvNuxqPYaN5J8X%2FtZf29Iu8VG5lSOOVo0S3jR82lfs%3D&reserved=0>.


IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you. Geisinger Health System utilizes an encryption process to safeguard Protected Health Information and other confidential data contained in external e-mail messages. If email is encrypted, the recipient will receive an e-mail instructing them to sign on to the Geisinger Health System Secure E-mail Message Center to retrieve the encrypted e-mail.

**Comment by nicolevasilevsky** [comment]
@tibingaman for some reason this term did not come in in the latest OMIM ingest, so I just added it manually, and it will be in the release tomorrow.
The new ID is: MONDO:0100111

Note - you may not see it in OLS for another week.

Thanks for your patience!

**Comment by tibingaman** [comment]
No worries. Thanks, Nicole!

**Comment by nicolevasilevsky** [comment]
Hi @tibingaman FYI - the release is not quite done, hopefully, it will be out later today. Thanks!
