### ISSUE TITLE
[Merge] MONDO_0035363 'IRF2BPL-related regressive neurodevelopmental disorder-dystonia-seizures syndrome'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3541]
**Mondo term (ID and Label)**
MONDO_0035363 'IRF2BPL-related regressive neurodevelopmental disorder-dystonia-seizures syndrome'

**Reason for deprecation**
I think this is equivalent with [OMIM:618088](https://omim.org/entry/618088) MONDO_0060759 'neurodevelopmental disorder with regression, abnormal movements, loss of speech, and seizures'.

@ahamosh there is not a mapping yet between OMIM and Orphanet, but this is a new term in [Orphanet](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_597623) (Orphanet:597623), it came in with the newest Orphanet sync. Do you think these two are equivalent?
Thanks!

**Term to be merged with**
MONDO_0060759 'neurodevelopmental disorder with regression, abnormal movements, loss of speech, and seizures'

**Comment by ahamosh** [comment]
Yes, I do.

**Comment by nicolevasilevsky** [comment]
thank you @ahamosh!
