### ISSUE TITLE
Question re: oculocutaneous albinism type 8

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3546]
this term is meant to be added in the Orphanet sync:

[Term]
id: MONDO:0035364
name: oculocutaneous albinism type 8
subset: ordo_disease
synonym: "OCA8" EXACT [Orphanet:597733]
is_a: MONDO:0000001 {source="Orphanet:597733"} ! disease or disorder
is_a: MONDO:0018910 {source="Orphanet:597733"} ! oculocutaneous albinism
xref: Orphanet:597733 {source="MONDO:equivalentTo"} ! oculocutaneous albinism type 8

@ahamosh is this equivalent to MONDO_0030899 'oculocutaneous albinism type 8' (https://omim.org/entry/619165)?

Orphanet doesn't have much info about this term, so I can't be sure. I would guess at some point Orphanet will map this to OMIM?

**Comment by ahamosh** [comment]
Not entirely sure that I understand the questions, but OCA type VIII is the same as OCA8.  It looks like all the different OCAs are distinguished with the work Type.  OCA8 is due to DCT. It is mapped to 619965 in orphanet.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh. I'll add this Orphanet xref as an equivalent xref on MONDO_0035364 'oculocutaneous albinism type 8'
