### ISSUE TITLE
QC check to check that we use dbxef instead of source

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3547]
This is wrong: property_value: source GARD:0008722 xsd:string {source="MONDO:equivalentTo"}
It should be: xref: GARD:0008722 {source="MONDO:equivalentTo"}

thanks!

cc @sabrinatoro

**Comment by matentzn** [comment]
This check is very difficult to generalise.. How would you phrase it? This particular problem that you mention here is solved by #3560 

A step further would be to check a whitelist for properties. These are the ones we are currently using. I could get QC to cry when you accidentally use one not in that list?

-  dce:creator
-  dce:date
-  IAO:0000115
-  IAO:0000231
-  IAO:0100001
-  mondo:excluded_subClassOf
-  mondo:excluded_synonym
-  mondo:pathogenesis
-  mondo:related
-  oboInOwl:consider
-  oboInOwl:created_by
-  oboInOwl:creation_date
-  oboInOwl:hasAlternativeId
-  oboInOwl:hasBroadSynonym
-  oboInOwl:hasDbXref
-  oboInOwl:hasExactSynonym
-  oboInOwl:hasNarrowSynonym
-  oboInOwl:hasRelatedSynonym
-  oboInOwl:id
-  oboInOwl:inSubset
-  owl:deprecated
-  rdfs:comment
-  rdfs:isDefinedBy
-  rdfs:label
-  rdfs:seeAlso
-  RO:0002161
-  skos:broadMatch
-  skos:closeMatch
-  skos:exactMatch
-  skos:narrowMatch

**Comment by matentzn** [comment]
I have added this check now to https://github.com/monarch-initiative/mondo/pull/3560

I am pretty convinced that the combination of these checks will cover 99.9% of the problems. Lets close this here and reopen when a new issue arises and I will rethink.

**Comment by nicolevasilevsky** [comment]
Cool, thank you @matentzn!
