### ISSUE TITLE
publish mondo-base

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/mondo#355]
It looks like `mondo-base.owl` is created in the makefile, but it doesn't seem to be published. Can you make it available?

**Comment by nicolevasilevsky** [comment]
@balhoff is this still needed?

**Comment by balhoff** [comment]
Looks like it is now being published at `http://purl.obolibrary.org/obo/mondo/mondo-base.owl`! So it was fixed at some point along the way.

It should be added to the products listing at OBO Foundry (as `mondo/mondo-base.owl`).
