### ISSUE TITLE
the duplicate source annotation is back

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3559]
I don't know if it was something I did?

Can we get rid of it again and make sure the wrong one hasn't be accidentally used?

cc @sabrinatoro

**Comment by matentzn** [comment]
No, there is a check, but these are very special cases of broken that were not covered. Opened the PR #3560 to fix

**Comment by nicolevasilevsky** [comment]
thank you, Nico!
