### ISSUE TITLE
PRPS1 deficiency disorders

### ISSUE THREAD

**Issue by agrant9394** [monarch-initiative/mondo#357]
For new term requests, please provide the following information:

## Preferred term label

PRPS1 deficiency disorders

## Synonyms

PRPS1-related CMTX5/Arts syndrome/XLNSHL

## Textual definition

Individuals with PRPS1 variants that cause decreased or impaired function of the PRPS1 enzyme have a range of peripheral neuropathies that can include features of Charcot-Marie Tooth syndrome, Arts syndrome, or nonsyndromic hearing loss.

## Suggested parent term

peripheral neuropathy (MONDO:0005244)

## Additional Analysis of disease

Individuals, both male and female, have been reported with familial missense variants in the PRPS1 gene. These patients have been described in the literature as having a range of phenotypes characterized as Arts syndrome, Charcot Marie Tooth syndrome, and non-syndromic hearing loss segregating in an X-linked pattern (Robusto 2015 25182139). Severity and presence of phenotypes makes it difficult to separate the non-syndromic and syndromic forms of hearing loss disorders associated with this gene. PMIDs (25182139, 25785835, 20021999, 27886419, 17701900, 25491489, 27256512)

## Notes

This term was suggested by a geneticist from the ClinGen Hearing Loss EP and has been used in HGMD to describe patients with variants in PRPS1.

**Comment by nicolevasilevsky** [comment]
@agrant9394 is this synonym one term: PRPS1-related CMTX5/Arts syndrome/XLNSHL?

**Comment by nicolevasilevsky** [comment]
Added this term on this PR: https://github.com/monarch-initiative/mondo/pull/360
(I accidentally referenced the wrong ticket on the commit message)

**Comment by agrant9394** [comment]
@nicolevasilevsky apologies for the delay, the ORCID of the ClinGen geneticist is  https://orcid.org/0000-0003-0927-6057 and yes the synonym that I provided would be one term. I see that the ticket is closed, should the term have appeared on the MONDO site?

**Comment by nicolevasilevsky** [comment]
Hi @agrant9394 - no worries - I will update the ORCID on this term. There is a new release of MONDO and this term is included, but I don't see it appearing in OLS or Ontobee yet, I think it takes some time.

The new ID is: MONDO_0100061
