### ISSUE TITLE
[Obsolete] 'qualitative or quantitative defects of collagen 6'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3573]
**Mondo term (ID and Label)**
MONDO_0016148 'qualitative or quantitative defects of collagen 6'

**Reason for deprecation**
ORDO grouping class that is grouping just one child term - out of scope.

**Suggested term to consider**
MONDO_0004603 collagenopathy

**Comment by sabrinatoro** [comment]
part of #3155
