### ISSUE TITLE
[Obsolete] MONDO_0019686 'type 2 collagen-related bone disorder'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3574]
**Mondo term (ID and Label)**
MONDO_0019686 'type 2 collagen-related bone disorder'

**Reason for deprecation**
ORDO grouping class that is not entirely working in Mondo. According to Peter, you don't have a type 2 collagen defect and then just get bone disorders.

**Suggested term to consider**
MONDO_0004603 collagenopathy

**Comment by sabrinatoro** [comment]
part of #3155

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/3698

**Comment by nicolevasilevsky** [comment]
closing this, it is a duplicate of #3698
