### ISSUE TITLE
[Obsolete] MONDO_0019687 'type 11 collagen-related bone disorder'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3575]
**Mondo term (ID and Label)**
MONDO_0019687 'type 11 collagen-related bone disorder'

**Reason for deprecation**
ORDO grouping class - out of scope for Mondo

**Suggested term to consider**
MONDO_0004603 collagenopathy

**Comment by sabrinatoro** [comment]
part of #3155
