### ISSUE TITLE
[Obsolete] MONDO_0005569 'cartilage disease'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3576]
**Mondo term (ID and Label)**
MONDO_0005569 'cartilage disease'

**Reason for deprecation**
Uncertain if this grouping class is needed, the children can be classified elsewhere.
Discussed on call with @ahamosh and @pnrobinson (and @sabrinatoro)

**Suggested term to consider**
MONDO_0003816 'articular cartilage disease' or 'disease or disorder'

**Comment by sabrinatoro** [comment]
part of #3155
