### ISSUE TITLE
Review classification of ‘Huntington disease’

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#358]
While reviewing the branch of 'neurodegenerative disease', I came across a potential issue with ‘Huntington disease’ that is present in both EFO and MONDO (as the term derives from the same ORDO one in both ontologies). Ideally we'd want to address the issue in both ontologies and in a consistent way. So could we please have your feedback on the following:

In EFO (3) and MONDO, ‘Huntington disease’ is a subclass of

Genetic neurodegenerative disease with dementia
Neurodegenerative disease with chorea
Huntington disease and related disorders
eye degenerative disease
Oculomotor apraxia or related oculomotor disease

Also, in MONDO,
disease has feature some dementia

It looks like the eye-related problems are among symptoms/early markers of Huntington disease, but classifying that way doesn’t feel correct and may derive from the peculiar way that ORDO uses ‘part of’ (see https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_399).

I’d suggest replacing
‘Huntington disease’ subclass of ‘eye degenerative disease’/’Oculomotor apraxia or related oculomotor disease’
with
‘Huntington disease’ has feature some ‘eye degenerative disease’/’Oculomotor apraxia or related oculomotor disease’

What do you think?
Thanks!

Paola Roncaglia
ORCID: 0000-0002-2825-0621

**Comment by nicolevasilevsky** [comment]
that makes sense to me, I created a PR: https://github.com/monarch-initiative/mondo/pull/360

**Comment by paolaroncaglia** [comment]
Thanks @nicolevasilevsky ! I'll keep an eye on the pull request.
