### ISSUE TITLE
make list of Mondo terms that EBI/Open targets

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3586]
- please make a list of Mondo terms that EBI/EFO are using
- please make a special list for Open Targets therapeutic area

**Comment by matentzn** [comment]
Full list here:
https://github.com/EBISPOT/efo/blob/master/src/ontology/iri_dependencies/mondo_terms.txt

**Comment by matentzn** [comment]
List of therapeutic areas:
https://github.com/EBISPOT/otar_profiler/blob/master/templates/disease_p_ta.txt

**Comment by nicolevasilevsky** [comment]
@matentzn I added this to our agenda to work on a workflow to automatically check EFO terms against Mondo obsoletion candidates

**Comment by nicolevasilevsky** [comment]
This is done, thank you!!
