### ISSUE TITLE
Correct placement of overlap/overlapping syndromes

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#359]
Hi @cmungall and @nicolevasilevsky ,

I’m working on a request to represent overlap/overlapping syndromes in EFO (see ticket https://github.com/EBISPOT/efo/issues/27 and review https://www.sciencedirect.com/science/article/pii/S1568997212001218), and I have a general question for you please. Based on the review above and on a first look at the literature on one of those overlapping syndromes (rhupus), it seems that part of the medical field acknowledges those disorders as disease entities in their own right, whether they express specific antibodies or not (“...In some OS a specific autoantibody has been identified, supporting the hypothesis that these syndromes are not a mere association of two or more CTD in the same patient, but a well defined clinical entity with specific clinical characteristics”). Do you have any opinion on how representative of the field this statement is? Because if it is accepted, at least to some degrees, it seems that it would be safer and more correct NOT to classify ‘overlap syndrome of x and y’ as subclass of ‘x’ and ‘y’, but, rather, to capture with a different axiom the fact that ‘overlap syndrome of x and y’ shares some features with ‘x’ and ‘y’. I’m asking because I’m not sure if you’ve addressed this matter already - I could only find few cases of overlap syndromes named as such in MONDO, e.g.:

http://purl.obolibrary.org/obo/MONDO_0044739 (no definition, but it looks like one of the two overlapping diseases is a parent of the term)

and

Children of http://purl.obolibrary.org/obo/MONDO_0016663 (where it looks like the overlapping diseases are not parents of the terms)

We plan to add more overlap/overlapping syndromes to EFO, and we’d like to hear your thoughts on this, so as to facilitate alignment on both sides, if possible.

Thanks,

Paola Roncaglia
ORCID: 0000-0002-2825-0621

**Comment by nicolevasilevsky** [comment]
Hi @paolaroncaglia 
To be honest, I have not heard of 'overlapping syndrome before, so I can't properly comment on how representative of the field this statement is in the review article you shared.

On this site [here](https://www-sciencedirect-com.liboff.ohsu.edu/topics/medicine-and-dentistry/overlap-syndrome)- they provide some specific examples of overlapping syndromes, like  'Primary Sclerosing Cholangitis-Autoimmune hepatitis' (PSC-AIH) or 'Obstructive Lung Disease' and COPD. Looks like we don't have many of these combined diseases represented in MONDO.

I don't believe we've addressed this issue in MONDO yet, it would be great to coordinate our efforts. Let's wait for @cmungall to comment.

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,

Thanks for your feedback. Unfortunately I can't access the link you provided (due to the OHSU library gateway), but the syndromes you mention sound familiar based on my initial reading on the subject. For example the EFO ticket that this request stems from discusses asthma-COPD overlap syndrome among others. It looks like these syndromes fall within the specific areas of interest of our Open Targets collaborators, and so may end up being EFO-specific terms, but it would surely be good to hear of @cmungall has any thoughts on this when he's back. 

Thanks!

**Comment by cmungall** [comment]
My tendency would be to avoid dual is_a parentage and to assert other relationships (e.g. shares_features_of). Would be good to hear of use cases, what OT users would expect in queries for asthma, etc

**Comment by paolaroncaglia** [comment]
@cmungall 
Thanks for your feedback, glad to hear that. I will be updating the relevant EFO ticket with use cases and I hope to get some feedback from OT, if so it will all be posted as comments to https://github.com/EBISPOT/efo/issues/27 if you'd like to follow that thread.

**Comment by msincan** [comment]
@paolaroncaglia I would not consider the detection of the certain antibody in three different recognized diseases as evidence for that antibody causing all of those diseases neither would I, necessarily, consider the detection of a specific antibody with a new disease concept in a "disease is_casued_by antibody" relationship. 
A certain antibody may interact with many receptors, or receptors found in various tissues/cells and cause pleiotropic effects and/or the antibody may have a target (RASopathies, Steroid receptor) that has intermediate pleitropic effects. For example, if the antibody is an "anti-double-stranded DNA" antibody, then the antibody may have systemic and unspecific effects similar to a chemotherapeutic drug that acts by binding to DNA molecules. Lab findings (i.e. biomarkers) do not always point to a causative agent.

**Comment by paolaroncaglia** [comment]
@msincan thank you!

**Comment by paolaroncaglia** [comment]
@msincan thank you!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky @cmungall 
FYI, I'll close this ticket. I'd opened it to get feedback from your side on overlapping syndromes, and now that the feedback is there, it's linked to an EFO ticket. Thanks.
