### ISSUE TITLE
Ito hypomelanosis/ Nevus of Ito[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3598]
**Mondo term (ID and Label)**
Ito hypomelanosis MONDO:0010302

**Reason for deprecation**
Appears to be redundant with Nevus of Ito? NCI C7582 says these terms are synonyms; Mondo says both terms have "hypomelanosis of Ito" as exact synonyms. But is this correct? UMLS seems to take NCI's data and equate these terms on a single cui as well.
![image](https://user-images.githubusercontent.com/71083858/131563094-41c5ff98-5a09-4ded-9899-f0de5650490c.png)

**Term to be merged with**
Nevus of Ito MONDO:0016985 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@kanems GARD treats these as two separate diseases, so let me check with them first.

@galyea-gard do you agree that these two terms should be merged? Thanks!

**Comment by nicolevasilevsky** [comment]
Emailed Gioconda on 11/29/21

**Comment by nicolevasilevsky** [comment]
From Gioconda:
We are going to review hipomelanosis of Ito (it was obsoleted from Orphanet); we may still keep the term because we do receive many inquiries about it but it does not represent a unique entity.  Regarding nevus of Ito I did see that NCI groups them as synonyms but they are different concepts.  Thank you! Gioconda

**Comment by nicolevasilevsky** [comment]
@kanems based on Gioconda's response, we think we should keep both terms in Mondo, as hypomelanosis of Ito is still being used by patients.

We made hypomelanosis of Ito a related synonym on 'nevus of Ito'.

Thanks!
