### ISSUE TITLE
Question about MONDO_0011649

### ISSUE THREAD

**Issue by jpgourdine** [monarch-initiative/mondo#36]
In this case, we think AVSD OMIM 606215 is equivalent to the Orphanet 98722. 
What should be the next step ? Should we delete the AVSD MONDO:0011649
class in protege or merge with Atriventricular Septal defect MONDO_0020290   ?
<img width="1186" alt="screen shot 2017-12-05 at 2 10 27 pm" src="https://user-images.githubusercontent.com/16328677/33633543-18313480-d9c6-11e7-8fe7-3d210f2a350a.png">

**Comment by cmungall** [comment]
What's the basis for this?

MONDO:0020290 denotes the generic class of AVSD. Is this really true for 
OMIM:606215. We have to look beyond names.

**Comment by nicolevasilevsky** [comment]
From what I can tell, [OMIM:606215 _AVSD_](https://www.omim.org/entry/606215) is the same as the generic MONDO class (MONDO:0020290). MONDO:0020290 _atrioventricular septal defect_ already xrefs [OMIM:606215 _AVSD_](https://www.omim.org/entry/606215) as well. 

I think the problems may be here: 

- MONDO:0020290 _atrioventricular septal defect_ has xrefs to:
  - [OMIM:606217 ATRIOVENTRICULAR SEPTAL DEFECT, SUSCEPTIBILITY TO, 2; AVSD2](https://www.omim.org/entry/606217?search=606217&highlight=606217), which I think is incorrect, and should be removed.
  - [OMIM:600309 ATRIOVENTRICULAR SEPTAL DEFECT 3; AVSD4](https://www.omim.org/entry/600309?search=600309&highlight=600309), which I think is also incorrect, and should be removed.
  - [OMIM:614430 ATRIOVENTRICULAR SEPTAL DEFECT 4; AVSD4](https://www.omim.org/entry/614430?search=614430&highlight=614430), which I think is also incorrect, and should be removed.
  - [OMIM:614474 ATRIOVENTRICULAR SEPTAL DEFECT 5; AVSD4](https://www.omim.org/entry/614474?search=614474&highlight=614474), which I think is also incorrect, and should be removed.
  - [OMIM:615779 CONGENITAL HEART DEFECTS, MULTIPLE TYPES, 4; CHTD4](https://www.omim.org/entry/615779?search=615779&highlight=615779), which I think is also incorrect, and should be removed.

I think the reason for all of these xrefs is Orphanet, they cross reference all these OMIM terms on their [Atrioventricular canal defect record](http://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=13739&Disease_Disease_Search_diseaseGroup=98722&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Atrioventricular-canal-defect&title=Atrioventricular-canal-defect&search=Disease_Search_Simple).

- OMIM combines the term 'ATRIOVENTRICULAR SEPTAL DEFECT, SUSCEPTIBILITY TO, 1, INCLUDED; AVSD1' on the [OMIM:606215 AVSD](https://www.omim.org/entry/606215) record.
  - MONDO:0011649 _AVSD_ has a related synonym 'Atrioventricular Septal Defect, Susceptibility To, 1' with an xref to [OMIM:606215 AVSD](https://www.omim.org/entry/606215). Maybe this is okay though, I'm not sure if another disease called AVSD1 actually exists or if this is a proper synonym for AVSD.

**Comment by cmungall** [comment]
https://omim.org/entry/606215 is a specific form. I know it's confusingly labeled but I think this is the only coherent way to treat it. It has a local 1p31-p21. If we make this a property of the superclass then it is inherited by the subclasses some of which are associated with different chromosomes.

We may actually choose to actively eliminate these as loci not diseases but either way it's not equivalent no matter what the name is.

Note the xrefs for all the other forms are fine. xrefs have no strict meaning. What we care about is the logical interepretation of the xrefs (subClassOf/superClassOf/equivalentTo). We currently denote these using source annotations as described in the editors guide. We should only be paying attention to these not the xrefs themselves (unless the xrefs are truly a mistake and there is nothing in common at all)
