### ISSUE TITLE
[NTR] Add 'Mendelian connective tissue disorder' grouping class?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3606]
**Preferred term label:**
 Mendelian connective tissue disorder

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Mendelian disorder

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
group terms like:
'Ehlers-Danlos syndrome'
'Marfan and Marfan-related disorder'
'progeroid and marfanoid aspect-lipodystrophy syndrome'
'connective tissue disorder due to lysyl hydroxylase-3 deficiency'

@pnrobinson 
@ahamosh suggested this new grouping class - we wanted to get your feedback, what do you think?

cc @cmungall

**Comment by pnrobinson** [comment]
The term ``Hereditary disorder of connective tissue`` seems to be most commonly used and I would suggest it be our primary label. 
for instance
https://www.nature.com/articles/gim201056

@ahamosh  Thoughts?

I do not think that "Mendelian connective tissue disorder" is a commonly used term and could be a synonym. There is always a discussion of diseases that are not 100% Mendelian, and my guess would be that some of the diseases in OMIM, such as hypermobility-type EDS will turn out to be multifactorial (at least to the extent of having important genetic modifiers). Therefore, it might be good to have "Mendelian connective tissue disorder" as a NARROW synonym. I do not think that our knowlege about these diseases is currently sufficient for us to be more specific in Mondo.

**Comment by nicolevasilevsky** [comment]
sounds good, thanks for the feedback @pnrobinson and @ahamosh!

**Comment by ahamosh** [comment]
Totally agree with heritable disorder of connective tissue.  Wasn't thinking that way in the context of yesterday's discussion.

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/3570

**Comment by nicolevasilevsky** [comment]
FYI - this term already exists in Mondo:
MONDO:0023603

I renamed it to 'hereditary disorder of connective tissue' and added Mendelian connective tissue disorder as a synonym
