### ISSUE TITLE
[Revise subclass] 'TAFRO syndrome'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3610]
**Mondo term (ID and Label)**
'TAFRO syndrome'
Update the label to Castleman-Kojima disease

**Suggested revision and reasons**
autoimmune disease

to do:
look at papers to see if there is a genetic cause.
If so, add parent Mendelian disease (for a monogenic cause). Can add the gene too (disease has dysfunction in some GENE)

**Comment by sabrinatoro** [comment]
I couldn't find evidence of a gene being involved in this syndrome.
