### ISSUE TITLE
update obsoletion with comments sparql to concatenate 'See Also'

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#3621]
I created a sparql query to report the terms with the "obsoletion candidate" tag. The report includes 'comment' and 'seeAlso' (see [here](https://github.com/monarch-initiative/mondo/blob/master/src/sparql/reports/obsoletioncandidates-withcomment.sparql))
This query works fine, but, we see that some terms have 2 "seeAlso" and these are reported in 2 separate lines, each line corresponding to one "seeAlso").

To do: update query to report all the "seeAlso" of the same term in the same line.

**Comment by sabrinatoro** [comment]
@matentzn 
I used "GROUP_CONCAT" to report all the "seeAlso" of a same term in the same line (instead of duplicated the line): https://api.triplydb.com/s/hIszbKy7D

Somehow, the query is a "bad query".
I looked at examples and documentation I can find online, but I cannot figure out what is wrong in the updated query (link above). 
Can you help, please? (whenever you have a moment, there is no urgency) 
Thank you!

**Comment by matentzn** [comment]
I dont know why, but SPARQL didnt like the un-concatenated comment field; this works:
https://api.triplydb.com/s/7s3ybFJyb

**Comment by matentzn** [comment]
Annoying - but probably not avoidable without major work. You could have two separate queries (one with comment, with seeAlso _only_).

**Comment by sabrinatoro** [comment]
yeah, I suspected it would be more complicated than it sounds... Thank you for your help!

@nicolevasilevsky, let's talk and figure out what would be best.

**Comment by nicolevasilevsky** [comment]
Yeah, let's not put everything into the comment. I think it's okay to leave it how it was. It's easy enough to review and then delete the duplicates if we don't need them.
