### ISSUE TITLE
Mondo release notes from yesterday are the same as last month

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#3630]
As per subject. I was investigating the deprecated Mondo mappings that break the EFO build following yesterday's Mondo release, and hence the list of obsoleted terms in the release notes, and they didn't look the same as I expected from the EFO mappings and from https://github.com/monarch-initiative/mondo/issues/3456.

**Comment by nicolevasilevsky** [comment]
Oh dear! Thanks for reporting this, I'll look into it

**Comment by nicolevasilevsky** [comment]
This is fixed now, @paolaroncaglia! Thanks again for catching this.
https://github.com/monarch-initiative/mondo/releases/tag/v2021-09-01

**Comment by paolaroncaglia** [comment]
> This is fixed now, @paolaroncaglia! Thanks again for catching this.

My pleasure :-D Thank you, @nicolevasilevsky , for fixing so quickly!
