### ISSUE TITLE
 X-linked spermatogenic failure 1 MONDO:0056795 child of Sertoli cell-only syndrome ?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3633]
**Mondo term (ID and Label)**
MONDO:0056795  X-linked spermatogenic failure 1

**Suggested revision and reasons**
Based on the definition and hierarchy from http://www.ontobee.org/ontology/DOID?iri=http://purl.obolibrary.org/obo/DOID_0070189 and OMIM https://www.omim.org/entry/305700, it seems like this is a sub-type of Sertoli cell-only syndrome. 
(Currently, UMLS maps OMIM:305700 to "Congenital absence of germinal epithelium of testes," UMLS CUI: C1384583 and uses the synonym "Sertoli-cell-only syndrome" but this may be because they are following OMIM's alternate names on the term. It's unclear, but it also affects MedGen mapping of the Mondo term)

@ahamosh Would OMIM agree that "X-linked spermatogenic failure 1" is one form of "Sertoli cell-only syndrome" as suggested by the DOID hierarchy linked above?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by ahamosh** [comment]
Yes, OMIM has sertoli-cell only syndrome as an alternate title on 305700.
