### ISSUE TITLE
split term: antiphospholipid syndrome

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3634]
**Term to split:**
MONDO:0007140 Antiphospholipid syndrome

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
Familial antiphospholipid syndrome (as a child of the original term)

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonynms that end in "1", "2", etc. should move to subclass.
OMIM:107320 (MONDO:equivalentTo)
add MSH: C531622
add UMLS CUI: C2930802
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Discussed on Mondo call and we'll proceed with this split, we'll aim to do this for the December release.
