### ISSUE TITLE
review cases in HPO OMIM omit file and consider obsoleting in Mondo

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3637]
We need to consider obsoleting terms from OMIM that are in the HPO omit file:
https://github.com/monarch-initiative/hpo-annotation-data/blob/master/rare-diseases/annotated/omit-list.txt

**Comment by nicolevasilevsky** [comment]
@sabrinatoro to you want to start working on this. We'll need to determine if these diseases are not in fact diseases and if they should be obsoleted, and if they should be obsoleted, we should add them to this [spreadsheet](https://docs.google.com/spreadsheets/d/1tt1Wk70j9XiHLV1vKQyNiHhaazh286pobpJk1ecSCCg/edit#gid=505727337), and then add obsoletion_candidate tags to all of them via ROBOT.

**Comment by sabrinatoro** [comment]
terms are reviewed  [here](https://docs.google.com/spreadsheets/d/1H1NFRZor1t5nhZjht5d_1r9H_8xsUIanSq6tirr9rqs/edit?usp=sharing)
Most OMIM ids are 
- equivalent to an obsolete MONDO term
- not referred in Mondo. 

Terms that need review are Mondo terms with 
- other dbxref from orphanet,GARD, DO  (--> should keep)
- dbxref to MESH and/or UMLS which refer to diseases at MESH/UMLS (should we keep?)
- dbxref to MESH and/or UMLS which refer to not-diseases (e.g "finding") (should we obsolete?)

**Comment by nicolevasilevsky** [comment]
I reviewed this file and will mark the terms for obsoletion where appropriate.

Open questions:

1. There are a few terms that are susceptibilities, I think we should keep these and make sure they are in the susceptibility branch.

ID | term
-- | --
MONDO:0011805 | asthma-related traits, susceptibility to, 1
MONDO:0010113 | thalidomide susceptibility
MONDO:0010783 | Alzheimer disease, susceptibility to, mitochondrial
MONDO:0013733 | accelerated tumor formation, susceptibility to
MONDO:0013876 | basal cell carcinoma, susceptibility to, 7

2. For these two classes - I wonder if these are still considered proper diseases? @ahamosh do you recommend that we keep these or obsolete them in Mondo?

OMIM ID | Mondo ID | Label
-- | -- | --
OMIM:615489 | MONDO:0014207 | age related macular degeneration 14
OMIM:162380 | MONDO:0008085 | neuropathy, hereditary sensorimotor, with upper motor neuron, visual pathway and autonomic disturbance

**Comment by nicolevasilevsky** [comment]
To do (after March release)
- [ ] obsolete the classes in this [spreadsheet](https://docs.google.com/spreadsheets/d/1jIdUr9LFgb0fU2RWiUgItwbWUr0oY2Knz0G2FK6a2aU/edit#gid=654469874) using this [workflow](https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#simple-mass-obsoletion-pipeline)
