### ISSUE TITLE
MONDO:0008284 polyposis of gastric fundus without polyposis coli

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3640]
**Mondo term (ID and Label):**
MONDO:0008284 polyposis of gastric fundus without polyposis coli

**Xref that should be fixed (ID and label):**
OMIM:175505 (MONDO:equivalentTo) - Remove. OMIM has merged this term with OMIM:619182 
(The MESH and CUI identifiers are still active.)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
to do:
Make OMIM:175505 MONDO:equivalentObsolete
