### ISSUE TITLE
[Merge] hyperinsulinemic hypoglycaemia and hyperinsulinemic hypoglycemia

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#3649]
**Mondo term (ID and Label)**
hyperinsulinemic hypoglycaemia/MONDO:0018619

**Reason for deprecation**

hyperinsulinemic hypoglycemia/MONDO:0005803 appears to be the same concept, although certainly treed differently

**Term to be merged with**
hyperinsulinemic hypoglycemia/MONDO:0005803

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
dependent on #3977
