### ISSUE TITLE
proposed merge: MONDO:0044923 acute myeloid leukemia with mutated NPM1 and MONDO:0018437 acute myeloid leukemia with NPM1 somatic mutations

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#365]
Proposed merge of these two terms: 

[Term]
id: MONDO:0044923
name: acute myeloid leukemia with mutated NPM1
def: "An acute myeloid leukemia with mutation of the nucleophosmin gene.
It is usually associated with normal karyotype and frequently has
myelomonocytic or monocytic features. It usually responds to induction
therapy." [NCIT:C82431]
synonym: "acute myeloid leukemia with cytoplasmic nucleophosmin" EXACT
[NCIT:C82431]
synonym: "acute myeloid leukemia with mutated NPM1" EXACT [NCIT:C82431]
synonym: "AML with mutated NPM1" EXACT [NCIT:C82431]
synonym: "NPMc+ AML" EXACT [NCIT:C82431]
xref: NCIT:C82431 {source="MONDO:equivalentTo"}
xref: ONCOTREE:AMLNPM1 {source="MONDO:equivalentTo"}
xref: UMLS:C2826177 {source="MONDO:equivalentTo"}
is_a: MONDO:0018874 {source="NCIT:C82430",
source="NCIT:C82431/inferred", source="ONCOTREE:AMLNPM1/inferred"} !
acute myeloid leukemia

[Term]
id: MONDO:0018437
name: acute myeloid leukemia with NPM1 somatic mutations
def: "Acute myeloid leukemia with NPM1 somatic mutations is a subtype of
acute myeloid leukemia with recurrent genetic abnormalities
characterized by clonal proliferation of myeloid blasts harboring
mutations of the NPM1 gene in the bone marrow, blood and other tissues.
It is associated with multilineage dysplasia, involving the myeloid,
monocytic, erythroid, and megakaryocytic cell lineages. Patients usually
present with leukocytosis, thrombocytosis and nonspecific symptoms
related to ineffective hematopoesis (fatigue, bleeding and bruising,
recurrent infections, bone pain), with frequent extramedullary
involvement typically presenting as gingival hyperplasia and
lymphadenopathy." [Orphanet:402026]
subset: ordo_disease {source="Orphanet:402026"}
synonym: "AML with NPM1 somatic mutations" EXACT [Orphanet:402026]
xref: ICD10:C92.0 {source="ORDO:402026/ntbt", source="Orphanet:402026"}
xref: Orphanet:402026 {source="MONDO:equivalentTo"}
xref: SCTID:763309005 {source="MONDO:equivalentTo"}
is_a: MONDO:0020078 {source="Orphanet:402026"} ! acute myeloid leukemia
with recurrent genetic anomaly

The NCIT class doesn't explicitly say somatic mutations but can this be assumed?

**Comment by nicolevasilevsky** [comment]
cc @fragosog

**Comment by fragosog** [comment]
Hi @nicolevasilevsky , consulted with one of the editors.  This concept (and others like it) are not specific for somatic mutations, can include germline.  Not an expert but in this particular case it doesn't look like germline variants are playing a role.  Want me to double-check?  It might be a blanket-case concept.

**Comment by cmungall** [comment]
can you check?

It would be good if we can all agree on a single named concept for each of these diseases (across ORDO, NCIT, and others). If there exists both somatic and germline then perhaps ORDO would be open to generalizing their existing classes.

Ot if the community feels it's really important to have distinct named classes for the generic, somatic and germline versions that can be done too

**Comment by NCIEVS** [comment]
OK, in this particular case, the editor is not aware of germline variants of consequence, but she can't exclude creating germline variant subclasses in the future.  Looks like a merge won't work.  Not sure that ORDO would adopt a similar generic superclass creation guideline, it might be useful but if most of the variants of interest are somatic maybe adds too much content for the bang you get back?

**Comment by nicolevasilevsky** [comment]
I think this can be closed.
