### ISSUE TITLE
Can someone comment on these clinical grouping classes?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#3659]
https://github.com/EBISPOT/otar_profiler/blob/master/templates/newterms.tsv

I would particularly like to know why they do not exist in Mondo (genuine).

**Comment by matentzn** [comment]
cc @dosumis @zoependlington

**Comment by cmungall** [comment]
Some of these we used to have but recently obsoleted

id: MONDO:0024297
name: obsolete nutritional or metabolic disease
def: "A collective term for nutritional disorders resulting from poor absorption or nutritional imbalance, and metabolic disorders resulting from defects in biosynthesis (ANABOLISM) or breakdown (CATABOLISM) of endogenous substances." [MESH:D009750]
comment: Editor note: consider expanding to include endocrine
xref: ICD10:E00.E90 {source="MONDO:obsoleteEquivalent"}
xref: MESH:D009750 {source="MONDO:obsoleteEquivalent"}
xref: UMLS:C0028715 {source="MONDO:obsoleteEquivalent"}
property_value: IAO:0000231 "out of scope" xsd:string
property_value: seeAlso https://github.com/monarch-initiative/mondo/issues/3157 xsd:string
is_obsolete: true
consider: MONDO:0005066
consider: MONDO:0005137

**Comment by nicolevasilevsky** [comment]
We decided to not act on this ticket, but when the issue is raised by one of our stakeholders directly, we'll revisit.
