### ISSUE TITLE
proposed merge: MONDO:0044924  acute myeloid leukemia with mutated CEBPA and MONDO:0017894 acute myeloid leukemia with CEBPA somatic mutations

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#366]
[Term]
id: MONDO:0044924
name: acute myeloid leukemia with mutated CEBPA
def: "An acute myeloid leukemia with mutations of the CEBPA gene."
[NCIT:C82433]
synonym: "Acute myeloid Leukemia with mutated CEBPA" EXACT [NCIT:C82433]
synonym: "Acute myeloid Leukemia with non-germline mutated CEBPA" EXACT
[NCIT:C82433]
synonym: "AML with mutated CEBPA" EXACT [NCIT:C82433]
synonym: "non-familial acute myeloid leukemia with mutated CEBPA" EXACT
[NCIT:C82433]
xref: NCIT:C82433 {source="MONDO:equivalentTo"}
xref: UMLS:C2826178 {source="MONDO:equivalentTo"}
is_a: MONDO:0018874 {source="NCIT:C82430",
source="NCIT:C82433/inferred"} ! acute myeloid leukemia

[Term]
id: MONDO:0017894
name: acute myeloid leukemia with CEBPA somatic mutations
def: "Acute myeloid leukemia with CEBPA somatic mutations is a subtype
of acute myeloid leukemia with recurrent genetic abnormalities,
characterized by clonal proliferation of myeloid blasts harboring
somatic mutations of the CEBPA gene in the bone marrow, blood and,
rarely, other tissues. It can present with anemia, thrombocytopenia, and
other nonspecific symptoms related to ineffective hematopoesis (fatigue,
bleeding and bruising, recurrent infections, bone pain) and/or
extramedullary site involvement (gingivitis, splenomegaly)."
[Orphanet:319480]
subset: ordo_disease {source="Orphanet:319480"}
synonym: "AML with CEBPA somatic mutations" EXACT [Orphanet:319480]
xref: ICD10:C92.0 {source="ORDO:319480/ntbt", source="Orphanet:319480",
source="ORDO:319480/attributed"}
xref: OMIM:601626 {source="Orphanet:319480", source="MONDO:subClassOf"}
xref: Orphanet:319480 {source="MONDO:equivalentTo"}
xref: SCTID:764855007 {source="MONDO:equivalentTo"}
is_a: MONDO:0020078 {source="Orphanet:319480"} ! acute myeloid leukemia
with recurrent genetic anomaly
property_value: confidence "0.0" xsd:double

Note: NCIT class doesn't explicitly say somatic mutations but can this be assumed?

**Comment by nicolevasilevsky** [comment]
cc @fragosog

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/365

**Comment by fragosog** [comment]
Hi @nicolevasilevsky , just saw this
> Note: NCIT class doesn't explicitly say somatic mutations but can this be assumed?
Oh yes, it does say that this particular instance is non-germline.

**Comment by nicolevasilevsky** [comment]
Thanks @fragosog. We will merge these terms.

**Comment by nicolevasilevsky** [comment]
Note to self, from Lori Whiteman at NCIT:
Acute myeloid leukemia with mutated CEBPA and acute myeloid leukemia with CEBPA somatic mutations are synonyms, they should be merged.
