### ISSUE TITLE
create tickets for merge candidates

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#367]
There are multiple classes with rdfs:comments discussing a potential merge

@nicolevasilevsky can you make a ticket for each one of these. The title would be "merge: A with B". You can just copy the text from the comment. However, if you want to add your own notes and do your own checks go ahead.

The ticket should also have the 'obsolete' label

I suggest just putting "merge" into the search box in Protege and seeing what you find

In future we should have a specific annotation property for indicating this

**Comment by nicolevasilevsky** [comment]
sure thing!

**Comment by nicolevasilevsky** [comment]
I think I am all done with this. :)
