### ISSUE TITLE
Juvenile polyposis syndrome[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3685]
**Mondo term (ID and Label)**
MONDO:0008276 generalized juvenile polyposis/juvenile polyposis coli

**Reason for deprecation**
MONDO:0008276 generalized juvenile polyposis/juvenile polyposis coli has these X-refs
Orphanet:329971 (OMIM:174900)
OMIM:174900 (Orphanet:329971)
UMLS:CN204230 (MONDO:equivalentTo)
DOID:0050787 (MONDO:equivalentTo)
ICD10:D12.6 (Orphanet:329971)
 -- Orpha:329971 maps to TWO OMIM numbers:174900 and 175050 
 -- CN204230 isn't a valid CUI from UMLS or MedGen. (Bad X-ref)
 -- Term IRI: http://purl.obolibrary.org/obo/DOID_0050787  is called " juvenile polyposis syndrome" (Wrong Mondo term)
 -- ICD10:D12.6 is pretty broad and probably not useful to get the level of specificity for how to map these concepts.
  
 (At a minimum, if Mondo wants to keep the Orpha:329971 term, it should not be 1:1 with MIM:174900, it should list both MIM numbers that Orphanet references.) 
 

**Term to be merged with**
 Suggest MERGE MONDO:0008276 and MONDO:0017380 (juvenile polyposis syndrome) 
OR move MIM:174900 and DOID:0050787 to MONDO:0017380 (juvenile polyposis syndrome) 
   In my view, it is OK to have MIM:174900 on this higher-level concept for a couple of reasons: 1: that entry includes THREE different disorders, and JPS is linked to two different loci on the MIM record, so it is a pretty 'broad' entry already, and 2: the primary name on the MIM entry matches the preferred name from Mondo.  
I realize my point 1 above goes against the usual rule of if an OrphaNet ID points to >1 MIM number, the MIM numbers should exist as x-refs on children concepts to the parent concept, but I think that MIM number is an exception since it's so inclusive.

Also, minor point to fix X-ref on MONDO:0017380:
UMLS CUI is C0345893 (Not CN239474) 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by kanems** [comment]
@ana-rath-orphanet and @ahamosh I would appreciate your perspectives on this issue to harmonize all the different names/groupings of the JPS concepts. I am open to other solutions beyond what I proposed above.

**Comment by nicolevasilevsky** [comment]
> (At a minimum, if Mondo wants to keep the Orpha:329971 term, it should not be 1:1 with MIM:174900, it should list both MIM numbers that Orphanet references.)

Orpha:329971 is equivalent to MONDO_0008276 'generalized juvenile polyposis/juvenile polyposis coli'
Orphanet:2929 is a subclass of MONDO_0008276 'generalized juvenile polyposis/juvenile polyposis coli'

**Comment by nicolevasilevsky** [comment]
I made these changes:
- MONDO_0017380 'juvenile polyposis syndrome' is equiv to OMIM:174900
- MONDO_0008276 'generalized juvenile polyposis/juvenile polyposis coli' is a subclass of OMIM:174900
- MONDO_0008278 'juvenile polyposis/hereditary hemorrhagic telangiectasia syndrome' is equivalent to OMIM:175050, which has a mutation in one gene (SMAD4), so it can't be a child of MONDO_0017380 'juvenile polyposis syndrome', which has two genes affected (SMAD4 and BMPR1A). I made this a sibling of MONDO_0017380 'juvenile polyposis syndrome'
