### ISSUE TITLE
Cyclosporiasis/ Cyclosporosis

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3694]
**Mondo term (ID Label)**
MONDO:0005725 cyclosporiasis
MONDO:0016212 cyclosporosis

**Bug/Typo/Error description**
Both terms are defined as being caused by infection with  "Cyclospora cayetanensis." 
MONDO:0005725 definition is sourced from [ NCIT:C128409 ]
MONDO:0016212 definition is sourced from [ Orphanet:210 ]

UMLS C0343398 "Cyclosporiasis" has two definitions: MSH D021866 says it is "Infection with parasitic protozoa of the genus CYCLOSPORA. It is distributed globally and causes a diarrheal illness. Transmission if waterborne." and NCI C128409 again cites specific infection by Cyclospora cayetanensis. 
SCTID: 716860005 "Cyclosporosis" defines that condition as caused by infection with Cyclospora cayetanensis. 

I am going to open separate tickets with UMLS and NCI. But the Mondo definitions don't make sense as currently displayed unless these terms are equivalent. Will update here as I get additional info from NCI thesaurus team.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by kanems** [comment]
My NCI inquiry:
> To whom it may concern, This NCI term (C128409 - &quot;Cyclosporiasis&quot; ) seems to be either misspelled or incorrectly defined. UMLS Metathesaurus has mapped this concept to CUI C0343398, which MSH D021866 defines as being caused by any member of the genus CYCLOSPORA. Meanwhile, UMLS C4274225 &quot;cyclosporosis&quot; and SNOMED CT 716860005 define that concept as being attributed to infection by cyclospora cayetanensis. 
I hope you can provide some clarity regarding this concept.
Thank you for your consideration and time.  -Megan 

NCI's response:

> Hi, The definition in question belongs to MeSH. NCI Thesaurus is unable to change it. The other definitions are correct. Are you needing to use the MeSH definition? (NCI Enterprise Vocabulary Services, Nicole Thomas, PhD)

**Comment by nicolevasilevsky** [comment]
Thanks for reporting this @kanems.

I think these terms are equivalent, I think we should merge MONDO_0016212 cyclosporosis into MONDO_0005725 cyclosporiasis (and use the logical def  below).

'infectious disease'
 and ('disease has infectious agent' some 'Cyclospora cayetanensis')

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson!
