### ISSUE TITLE
Merge: MONDO:0006702 & MONDO:0100007 @kanems

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3697]
to do:
@nicolevasilevsky merge 'chronic inflammatory demyelinating polyneuropathy' into 'chronic inflammatory demyelinating polyradiculoneuropathy'.

The open question for Peter and Ada is below (https://github.com/monarch-initiative/mondo/issues/3697#issuecomment-942655630). I moved this to a separate ticket: https://github.com/monarch-initiative/mondo/issues/4070

_updated 2022-11-30 by @nicolevasilevsky_

---

@kanems 
we renamed MONDO:0007691 to 'Guillain-Barre syndrome, familial', it should be available in the next release (early September)

We want to use the OMIM preferred labels for Mondo terms, we'll work on cleaning this up. Based on Ada's response too, we'll work on retroactively splitting out the terms that are 'included' in OMIM entries, as these should be separate classes, as noted above.

Thanks for bringing this to our attention! It will take some time as our developer Dazhi is working on improving the OMIM ingest workflow.

_Originally posted by @nicolevasilevsky in https://github.com/monarch-initiative/mondo/issues/2808#issuecomment-902980425_

---

From kanems:
Now Mondo has two concepts for ORPHA:2932 "chronic inflammatory demyelinating polyneuropathy" aka "Chronic inflammatory demyelinating polyradiculoneuropathy" Suggest a merge into MONDO:0006702 to obsolete the redundant term MONDO:0100007

**Comment by pnrobinson** [comment]
There are some problems here @nicolevasilevsky @kanems 

1. Guillain-Barre syndrome, familial (MONDO:0007691) -- there is a familiar (Mendelian form) of Guillain-Barre syndrome (GBS), see [OMIM:139393](https://omim.org/entry/139393). However, most cases are not Mendelian. The definition of the familial (Mendelian) form is this: A chronic monophasic, progressive or relapsing symmetric sensorimotor disorder characterized by progressive muscular weakness with impaired sensation, absent or diminished tendon reflexes and elevated cerebrospinal fluid (CSF) proteins. However, this definition is appropriate for GBS in general and does not describe the Mendelian form. I would suggest adapting the deinition in OMIM if @ahamosh agrees.

Def. A form of Guillain-Barre syndrome (GBS) that occurs in persons or families with a genetic predisposition to the acute (AIDP) or chronic (CIDP) forms of GBS. Note that GBS is considered to be a complex multifactorial disorder with both genetic and environmental factors, and families with clear Mendelian inheritance have been rarely reported: a mutation in the PMP22 gene (601097) on chromosome 17 was identified in a single family with the acute (AIDP) and chronic (CIDP) forms of inflammatory demyelinating polyneuropathy.

**Comment by pnrobinson** [comment]
chronic inflammatory demyelinating polyneuropathy seems to be a separate disease category, I do not think that GBS belongs as a subtype

**Comment by pnrobinson** [comment]
see also https://github.com/monarch-initiative/mondo/issues/2830, I think these are the same issue actually, we can probably close the older one
