### ISSUE TITLE
merge 'type 2 collagen-related bone disorder' and 'collagenopathy type 2 alpha 1'

### ISSUE THREAD

**Issue by azankl** [monarch-initiative/mondo#3698]
The group terms 'type 2 collagen-related bone disorder' (MONDO:0019686) and 'collagenopathy type 2 alpha 1' (MONDO:0022800) describe the same thing (disorders caused by mutations in type II collagen). They also contain (almost) the same disorders. I would keep the term 'type 2 collagen-related bone disorder' (MONDO:0019686). All disorders under MONDO:0022800 should be listed under MONDO:0019686 (I think they already are). MONDO:0022800 should also be placed under the same ancestors as MONDO:0019686. Then MONDO:0019686 can be removed.
Some disorders under MONDO:0022800 are not caused by type II collagen mutations (or at least its controversial), but I would place them there for now anyway. I will open separate tickets to discuss the controversial disorders under MONDO:0022800.

**Comment by matentzn** [comment]
Best have @nicolevasilevsky manage my tickets, but that you @azankl for the issue :)

**Comment by nicolevasilevsky** [comment]
Hi @azankl. thanks for reporting this. To clarify, you want to merge MONDO:0019686 'type 2 collagen-related bone disorder' with MONDO:0022800 'collagenopathy type 2 alpha 1', right?

**Comment by azankl** [comment]
Hi @nicolevasilevsky. Yes, 'type 2 collagen-related bone disorder' (MONDO:0019686) and 'collagenopathy type 2 alpha 1' (MONDO:0022800) should be merged. I would also change the name of MONDO:0022800 to 'type 2 collagenopathy'. This is a term commonly used.

**Comment by azankl** [comment]
Also, as outlined in my original comment, the child and ancestor relationships of 'type 2 collagen-related bone disorder' (MONDO:0019686) and 'collagenopathy type 2 alpha 1' (MONDO:0022800) should be merged as well. So the ancestor terms of MONDO:0019686 should be added as ancestors of MONDO:0022800 during the merge.
