### ISSUE TITLE
Question on MONDO_0011996

### ISSUE THREAD

**Issue by jpgourdine** [monarch-initiative/mondo#37]
In the OMIM record, the two terms LEUKEMIA, CHRONIC MYELOID OMIM 608232 and LEUKEMIA, CHRONIC MYELOID, ATYPICAL .
On the MONDO class MONDO:0011996 chronic myelogenous leukemia, there is the related synonym Leukemia, Chronic Myeloid, Atypical (which xrefs OMIM:608232). Should this xref be removed?
<img width="764" alt="screen shot 2017-12-05 at 2 55 07 pm" src="https://user-images.githubusercontent.com/16328677/33635335-6e19e922-d9cc-11e7-9bf3-249f01938696.png">

**Comment by cmungall** [comment]
What's the basis for this?

**Comment by nicolevasilevsky** [comment]
Looks like OMIM is combining the two terms on one record (atypical CML and CML), hence there is the related synonym on the MONDO class Chronic granulocytic leukemia. 

I think we should remove the related synonym:
![image](https://user-images.githubusercontent.com/6722114/33745736-8aed0a96-db6d-11e7-8fa8-486a49c759af.png)

If this is correct, I can walk JP through how to do this.
