### ISSUE TITLE
add to GitHub actions: run reports for the things in the edit file before they are released

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3707]
Per the Mondo call, can we create a pipeline in GitHub actions that runs everyday and puts edit file changes into a TSV file and we can share that with our users (ClinGen, EFO, etc.)

**Comment by nicolevasilevsky** [comment]
https://github.com/monarch-initiative/mondo/actions/workflows/diff.yaml

**Comment by nicolevasilevsky** [comment]
example diff: https://github.com/monarch-initiative/mondo/blob/master/src/ontology/reports/mondo_diff.md

**Comment by nicolevasilevsky** [comment]
@matentzn I think this can be closed?

**Comment by matentzn** [comment]
not yet, but is a 10 minute job at our next meeting if you can raise it!
