### ISSUE TITLE
equiv between '2p21 microdeletion syndrome' and 3 other classes

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3777]
'2p21 microdeletion syndrome' is inferred to be equivalent to three other classes:
'hypotonia-cystinuria syndrome type 1'
'homozygous 2p21 microdeletion syndrome'
'hypotonia-cystinuria syndrome'

I think this may be caused by the new axioms using monochrome - this isn't right though, is it? I'm surprised the qc checks didn't catch this.

**Comment by matentzn** [comment]
how did you find these? robot does not..

**Comment by nicolevasilevsky** [comment]
Hm, that link doesn't work, here is a screenshot:
![image](https://user-images.githubusercontent.com/6722114/136854319-25819de4-9da7-4910-8418-4043e6fb7a91.png)

**Comment by cmungall** [comment]
this is from a check that ensures all subClassOfs are proper subClassOfs https://douroucouli.wordpress.com/2018/09/04/debugging-ontologies-using-owl-reasoning-part-2-unintentional-entailed-equivalence/

**Comment by nicolevasilevsky** [comment]
related to: https://github.com/monarch-initiative/mondo/issues/3664

**Comment by nicolevasilevsky** [comment]
Per @cmungall's guidance, I ran the [check for unsatisfiable classes](https://mondo.readthedocs.io/en/latest/editors-guide/check-for-unsatisfiable-classes/) and this was in Protege:

![image](https://user-images.githubusercontent.com/6722114/136862673-525a48f5-3667-4099-bf85-94569d58140d.png)

![image](https://user-images.githubusercontent.com/6722114/136862684-44467d62-9799-4085-898d-5bb6bceff627.png)

![image](https://user-images.githubusercontent.com/6722114/136862722-21e244f7-04a6-4ec9-85ff-0e6363ac48bb.png)

![image](https://user-images.githubusercontent.com/6722114/136862746-9d4cacc3-7e71-4681-9fdc-b727f1f10e86.png)

**Comment by nicolevasilevsky** [comment]
Note - in the 3rd explanation, Chris spotted this:
![image](https://user-images.githubusercontent.com/6722114/136863294-3a0f9b4c-783c-4f7c-9c5f-0318a04b295f.png)

He noted there is a comment in the mondo-edit file:

id: MONDO:0011669
name: hypotonia-cystinuria syndrome
def: “Hypotonia-Cystinuria syndrome (HCS) is a rare syndrome including neonatal and infantile hypotonia and failure to thrive, cystinuria type 1 and nephrolithiasis, growth retardation due to growth hormone deficiency, and minor facial dysmorphism.” [Orphanet:163690]
comment: Editor note: check this. ORDO has type 1 as a superclass. Also check wether is_a: MONDO:0016538 is appropriate. 

This comes from Orphanet:
![image](https://user-images.githubusercontent.com/6722114/136863364-7e19057c-5c43-4b67-8842-0bb83cfa4d4d.png)

It is incorrect for a generic class to be a child of a type 1 class. **Action item:** fix this in Mondo.

**Comment by cmungall** [comment]
OK there may be more work to do than a simple merge. The axiomatization is revealing all kinds of other issues

e.g. I was suspicious of this:

![image](https://user-images.githubusercontent.com/50745/136865262-0584aba5-7446-4cd7-a390-379b24bfb5cf.png)

here is the explanation:

![image](https://user-images.githubusercontent.com/50745/136865231-c9b35220-6203-46c7-8b81-44a2caa333ed.png)
