### ISSUE TITLE
need to create tickets for Chris' editor comments

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3784]
When Chris created Mondo, he added a lot of comments with editor notes.

They all say "Editor note: ...."

Could one of you do a SPARQL query to get all of the terms that have an Editor note please? Chris requested that we create tickets for these.

Thanks!

**Comment by cmungall** [comment]
Can you not search in protege?

**Comment by matentzn** [comment]
@sabrinatoro should be able to do this :) If problems share yasgui link and I will finish it. You should give it a go @nicolevasilevsky actually!
