### ISSUE TITLE
various mucopolysaccharidosis classification issues

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#3785]
This grouping does no work:

id: MONDO:0019302
name: mucopolysaccharidosis with skin involvement
subset: disease_grouping
subset: ordo_group_of_disorders {source="Orphanet:79388"}
synonym: "MPS with skin involvement" EXACT [Orphanet:79388]
xref: Orphanet:79388 {source="MONDO:equivalentTo"}
is_a: MONDO:0019249 {source="MONDO:cjm"} ! mucopolysaccharidosis
is_a: MONDO:0019301 {source="Orphanet:79388"} ! metabolic disease with skin involvement

single child:

![image](https://user-images.githubusercontent.com/50745/136886547-a1f75d15-5ecf-4cfd-801a-9b5590414795.png)

merge into child. Also we need to get rid of many of these "D with P" groupings

MPSPS is classified incorrectly 

![image](https://user-images.githubusercontent.com/50745/136886799-2e45b5d4-3c0f-4962-bc7d-3f227e91d99b.png)

This is not an LSD hence cannot be a subtype of MPS, which is classified as an LSD:

See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7013929/

OMIM doesn't place in the MPS phenotypic series https://omim.org/entry/617303

We need a general DP for X-like. Sometimes we do

 * X or X-like
    * X
    * X-like

sometimes we feel there is insufficient reason to group, and X and X-like are not connected via shared is-a but instead by shares-features-with 

I think this one should be obsoleted: 

![image](https://user-images.githubusercontent.com/50745/136887412-636fb6e1-d1d4-4fc2-8b57-c1f86592fdda.png)

see
https://omim.org/entry/252700

no new evidence since 1980

**Comment by nicolevasilevsky** [comment]
Action items:
- [ ] exclude http://purl.obolibrary.org/obo/MONDO_0019249 (source MONDO:cjm) as a superclass for 'mucopolysaccharidosis-like syndrome with congenital heart defects and hematopoietic disorders'
- [ ] we need a general DP for X-like:
X or X-like
X
X-like
Note in the pattern: sometimes we feel there is insufficient reason to group, and X and X-like are not connected via shared is-a but instead by shares-features-with
- [ ] create grouping class:
'mucopolysaccharidosis or mucopolysaccharidosis-like '
- [ ] mucopolysaccharidosis should be a child
- [ ] 'mucopolysaccharidosis-like syndrome with congenital heart defects and hematopoietic disorders' should be a child
