### ISSUE TITLE
[Merge] MONDO:0019302

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3787]
**Mondo term (ID and Label)**
MONDO:0019302 mucopolysaccharidosis with skin involvement

**Reason for deprecation**
grouping class with a single child. It is a synonym for the child term.

**Term to be merged with**
MONDO_0010674 'mucopolysaccharidosis type 2'

related to https://github.com/monarch-initiative/mondo/issues/3785

**Comment by larrybabb** [comment]
@nicolevasilevsky Several ClinGen users noted that the term that you are merging this into `MONDO_0010674 'mucopolysaccharidosis type 2'` has been flagged for obsoletion in the Dec 30, 2021 release. They believe this is an error and would like clarification from you. 
Also the planned obsoletion date on `MONDO_0010674 'mucopolysaccharidosis type 2'` is 1/1/2021 which is last year. 

Please let us know if `MONDO_0010674 'mucopolysaccharidosis type 2'` is really planned for obsoletion or not and when. If it is, please let us know the replacement term.

**Comment by nicolevasilevsky** [comment]
@larrybabb thanks to your team for catching this error! These annotations should have been removed when I did the merger, this was an error on my part.
This term will not be obsoleted, I'll fix this and the fix will be available in the next release in early Feb.
Thanks!
