### ISSUE TITLE
merge MONDO_0011326 'citrullinemia, type II, adult-onset' with MONDO_0016603 'citrullinemia type II'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#379]
consider merge MONDO_0011326 'citrullinemia, type II, adult-onset' with parent class, MONDO_0016603 'citrullinemia type II'

**Comment by kanems** [comment]
What is the status of this merge? The OrphaNet cross-ref on MONDO:0016603 points back to the same concepts on MONDO:0011326 "citrullinemia, type II, adult onset" so it would seem most sources agree these are equivalent concepts.

**Comment by nicolevasilevsky** [comment]
@ahamosh do you have any objections to merging this with the parent term 'citrullinemia type II'? Orphanet has 'citrullinemia type II adult onset' as synonyms. Or do you think we need a distinct class?

Thanks!

**Comment by ahamosh** [comment]
They are different manifestations, but the same deficiency.  Some with adult manifestations had some manifestations in the neonatal period.  Let me talk with Joanna and the team see what they say.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh!

**Comment by nicolevasilevsky** [comment]
@ahamosh gentle reminder to follow up with Joanna, thank you!

**Comment by ahamosh** [comment]
Hi Nicole, I did ask and then forgot to post here.  This is what Joanna said: Citrullinemia type II - I think the adult onset is significantly different from the neonatal onset.  The adults have sudden onset disease.  Do internal medicine docs know about this?  It is interesting that some people don't manifest disease until much later in life.  

Some states (and countries) now screen for citrulline in the newborn period, this will detect the neonatal and childhood onset.  These kids will still be at risk for adult onset (range is 11-70 years). Making sure that people can find this as separate phenotype may be helpful to facilitate diagnosis.  They are the same underlying biochemical defect.  I think that we (OMIM) will keep these separate entries.

**Comment by nicolevasilevsky** [comment]
Thank you @ahamosh! :)

**Comment by nicolevasilevsky** [comment]
@kanems as OMIM will keep these as separate concepts, Mondo will too.
