### ISSUE TITLE
MONDO:0012356 glomerulocystic kidney disease with hyperuricemia and isosthenuria [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3800]
**Mondo term (ID and Label)**
MONDO:0012356 glomerulocystic kidney disease with hyperuricemia and isosthenuria 

**Reason for deprecation**
OMIM 609886 MOVED TO 162000 AND 137920 

**Suggested term to consider**
? Since the disease represented by the MIM number is split into two, not sure if there is a clear merge or if this should just be obsoleted. The other OMIM numbers are presumably already in Mondo and the CUI may not be active following the 2021AB release from UMLS.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
this is already tagged for obsoletion:
https://github.com/monarch-initiative/mondo/issues/1880#issuecomment-909821947

I will close this ticket. This will be obsoleted in the December release.
