### ISSUE TITLE
obsolete MONDO_0008331 'pseudopapilledema (disease)'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#381]
MONDO_0008331 'pseudopapilledema (disease)' has a comment: May be merged in future as this represents a phenotypic feature

**Comment by nicolevasilevsky** [comment]
@pnrobinson do you think this should be obsoleted from Mondo?

**Comment by pnrobinson** [comment]
This is a phenotypic feature and belongs in the HPO, see eg.https://www.ncbi.nlm.nih.gov/books/NBK538291/

**Comment by nicolevasilevsky** [comment]
perfect, thanks @pnrobinson!
