### ISSUE TITLE
proposal to more explicitly separate human and non-human diseases

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3855]
- we should have 'Human disease' and 'non-human animal disease'
- For non-human diseases we could replace is_a relationship to human diseases with 'variant of' or 'homolog of' (relation is TBD)
  - eg feline leukemia would not be a subclass of leukemia, but it would have the superclassOf assertion 'variant of' some leukemia
- also add existential restrictions to non-human diseases that says they are non-human
- Add synonyms for human diseases disease (human)

Open question:
Will we mirror the top level hierarchy for non-human diseases?
- For every class under non-human disease, take superclass and make ortholog for that, eg 'Brown-Pearce carcinoma', need non-human carcinoma 
  - Define as an epithelial cancer

- [x] need to do sparql query 
?D isa* NHAD, ?D isa ?S, not ?S isa* NHAD

**Comment by matentzn** [comment]
Unfortunately, this needs more action items.

From the meeting:
- [ ] We should annotate clearly human disease with human taxon constraints and then work our way up. there will be some ambiguous cases along the line.
- [ ] Some grouping classes will stay species-neutral

**Comment by nicolevasilevsky** [comment]
related:

_From @jmcmurry on August 17, 2016 22:50_

Related to https://github.com/monarch-initiative/monarch-disease-ontology/issues/59 for human diseases, we should be able to append taxon to animal diseases. This will be needed for downstream enhancements to site search. https://github.com/monarch-initiative/monarch-app/issues/1317

<img width="462" alt="screen shot 2016-08-17 at 3 48 53 pm" src="https://cloud.githubusercontent.com/assets/3658863/17756038/53c88e3a-6492-11e6-91be-48d821deb09c.png">


_Copied from original issue: monarch-initiative/monarch-disease-ontology-RETIRED#144_
_Copied from old Mondo issue: https://github.com/monarch-initiative/mondo/issues/190_

**Comment by sabrinatoro** [comment]
ROBOT merge template: 
sh run.sh make TEMPLATE_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vTH9cFh2xadQnAOMUk920g-nzyrjtw06OpzlErksSqNhJk7rFRCcPDE1K2fVzIlyI1g_0TOnt0n7osF/pub?gid=7444001&single=true&output=tsv" merge_template -B

**Comment by sabrinatoro** [comment]
PR in progress: 
- https://github.com/monarch-initiative/mondo/pull/5387
- https://github.com/monarch-initiative/mondo/pull/5397

**Comment by sabrinatoro** [comment]
Discussion: 
- #5387 : proposed strategy
  - explanation [here](https://www.youtube.com/watch?v=6aFufszAa_g)
- Comments from Chris (copied from Slack)
  - we want to add the disjointness ASAP as that will reveal issues
     Discussion: 
     - how about the diseases which could be in both human and non-human (e.g infectious diseases)? Would they have to live exclusively outside the specific branches? ie infectious disease that can be both human or non-human will never be found in these specific branches?
     - yes. I appreciate this does get complicated though, maybe simpler if we always have both human and nh forms, and no cross-species grouping
  - having a separate grouping that sits outside the disjoint pair is fine
  - we’d want patterns/logical defs for e/g/ “leukemia, feline”. Your axioms are correct but they could be strengthened
  - I suggest a few groupings like “bacterial skin disease, non-human” and analogizing it, so there is a 2hop between the specific cattle disease and the human grouping
  - it’s really tempting to say “skin disease, it’s so generic, it should cover both”, but that way lies complex lattices. IMO it’s simplest if we just stay the course with two disjoint is-a hierarchies, and get into the habit of thinking of analog-of as another way of grouping
  - you are hitting on a fundamentally confusing thing in the current way, where “horse disease” means “can be in horses”, which we can’t really axiomatize
  - in contrast I think “human disease” should mean only in human
  - I think having “general malaria” will be confusing. If we start going this route we will have a complex lattice to maintain. And there is no need. If people want to group under “malaria” you just pick the human exemplar and use is-a and cross-species-analog as your hierarchical predicates
  - I’m not too worried about the terminological part. We can auto-add “, human” to any class in the human branch that has a non-human analog. We may still want the default release to be terminologically human-centric though
  - "bird disease" : These are truly avian diseases and having a logical in-taxon is fine
  - "goat disease" : I think it’s the sub-mammalian groupings that are problematic
      - We could rename it to “disease that may afflict goats”. But really “goat disease” in this sense does zero work for us. Just make sure things have present-in-taxon weak annotations, and people who want maybe-goat-disease can query on this
  - Minor: you have ‘immune system disorder, non-human’ and (‘disease has basis in feature’ some ‘simian immunodeficiency virus infection’)
  - I prefer having generic human be the genus… but I appreciate some people find that kind of hiddengciization confusing
 


- updated PR: #5397

**Comment by sabrinatoro** [comment]
There might still be some improvements to be made, but this issue can be closed.
