### ISSUE TITLE
merge MONDO_0008040 'transient myeloproliferative syndrome (disease)' 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#386]

**Comment by cmungall** [comment]
merge a term with itself? :-)

can you also include the labels in the ticket title?

**Comment by nicolevasilevsky** [comment]
oops! This is a mistake. Sure, I can add the labels in the ticket title. I just added all the tickets and I'm going back through and adding more details now.

**Comment by nicolevasilevsky** [comment]
actually the comment on this class does say to merge it with itself! (Editor note: merge with MONDO:0008040).

It is probably meant to say something else. Maybe MONDO_0020076 'myeloproliferative neoplasm'?

**Comment by cmungall** [comment]
maybe it was already merged and I forgot to remove the comment?

**Comment by nicolevasilevsky** [comment]
perhaps. should I remove the comment?

**Comment by cmungall** [comment]
please do, thx!
