### ISSUE TITLE
MONDO:0006609 seborrheic infantile dermatitis 

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3880]
**Mondo term (ID and Label):**

seborrheic infantile dermatitis MONDO:0006609

**Xref that should be fixed (ID and label):**
C0221244 (UMLS) this is a better match for the parent concept of "seborrheic dermatitis" (SD)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
 C0343047 is for "Complement component 5 deficiency" which X-refs SNOMED 7297005 'Generalized seborrheic dermatitis of infants,' 'Leiner's disease,' and 'Infantile seborrheic dermatitis' (But this UMLS CUI is problematic, since it equates OMIM 609536 https://www.omim.org/entry/609536?search=609536&highlight=609536 with the concept of infantile SD, so I will follow up with UMLS separate to split the MIM number and related concepts out, since that condition has multiple symptoms beyond just dermatitis.)
Alternatively, C0263233 is for "cradle cap" 

Also, this term (MONDO:0006609) has an exact synonym of "Pityriasis capitis" but this is a separate concept in Mondo: MONDO:0024348 which I am struggling to find a good definition for (PMID: 32416039 indicates it is a more severe form of dandruff and https://www.ncbi.nlm.nih.gov/books/NBK551707/ indicates it's a mild form of SD) UMLS Maps SCTID:400201008  to Seborrheic dermatitis of scalp, CUI: C0221244) So Maybe SD (MONDO:0006608) needs a new child term, the concept for Pityriasis capitis aka Seborrheic dermatitis of scalp, CUI: C0221244, which then has a child of 'infantile SD'?

**Comment by nicolevasilevsky** [comment]
![issue-3380](https://user-images.githubusercontent.com/6722114/139984260-f963d494-7954-461a-ad61-2d16166ce6fb.jpg)

@kanems what if we just moved the UMLS:C0221244 (Pityriasis capitis) to MONDO_0024348 'pityriasis capitis' ?

**Comment by nicolevasilevsky** [comment]
note to self, here is another article: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4852869/

**Comment by nicolevasilevsky** [comment]
This article suggests these are separate diseases (as we have them currently classified: https://jamanetwork.com/journals/jamadermatology/fullarticle/479236.

**Comment by kanems** [comment]
https://www.aad.org/public/diseases/a-z/seborrheic-dermatitis-overview Suggests that SD is a broad term, of which cradle cap is an infantile sub-type. So I think the relationships are correct in Mondo, but this is what I think needs to be done:

- [ ] Reject "Pityriasis capitis" as an exact synonym on MONDO:0006609 seborrheic infantile dermatitis 
- [ ] Reject UMLS:C0221244 "Seborrheic dermatitis of scalp" from X-refs on MONDO:0006609 seborrheic infantile dermatitis  (or change nature of the relationship from equivalent/exact to close? this UMLS CUI doesn't limit to an infantile onset/presentation

> @kanems what if we just moved the UMLS:C0221244 (Pityriasis capitis) to MONDO_0024348 'pityriasis capitis' ?
Yes, I think this would work because SNOMED 400201008 maps to this CUI in UMLS, syns: Dandruff, Furfuracea from the SCTID. 
Do we want to add MONDO_0024348 'pityriasis capitis'  to the branch under seborrheic dermatitis, as a sibling to the infantile form? If we're confident (enough) that this is synonymous with Dandruff, then it would have a syn of "Seborrheic dermatitis of scalp" (which is UMLS's preferred name for this CUI). I Don't know the differences between _exanthem_ and _dermatitis_ to know if being in both of those branches of "skin disease" is incorrect or not.

**Comment by pnrobinson** [comment]
Pityriasis capitis commonly known as dandruff. It is a mild manifestation of seborrheic dermatitis. I do not think that a dermatologist would equate dandruff with a disease entity that is a subform of seborrheic dermatitis, and I am not sure that it is proper to regard it as a disease in its own right. Possibly it should be obsoleted and created as an HPO term. Do we have a dermatologist we can ask?

**Comment by nicolevasilevsky** [comment]
Based on this article (https://pubmed.ncbi.nlm.nih.gov/32416039/), this is considered a disease:
"Pityriasis capitis commonly known as dandruff is one of the most common and widely seen dermatological **disease** that affects majority of the world population."
