### ISSUE TITLE
merge MONDO_0003571 'labyrinthine dysfunction' with MONDO_0002467 inner ear disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#389]
Editor note: TODO merge with inner ear disorder

**Comment by cmungall** [comment]
I don't think this should be a merge. concepts are not equivalent

http://eioftx.com/vertigo-balance/balance-disorders/labyrinthine-dysfunction/

but by all means, obsolete, and have 2 considers, one to the parent mondo, the other to an hpo
