### ISSUE TITLE
synpolydactyly same as Polysyndactyly ?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3919]
**Mondo term (ID and Label)**
synpolydactyly MONDO:0021651 

**Synonym to be added**
Polysyndactyly
(Maybe?? the definitions seem to be the same, but maybe I am missing some nuance.)
**Synonym subtype: ie, broad/exact/narrow/related**
exact

**Database cross reference for the synonym** Such as PubMed ID (in the format PMID:XXXXXX) or a cross-reference to another ontology, like OMIM or Orphanet.

NCI, Polysyndactyly (C125597) "DEFINITION: A rare anatomical malformation characterized by polydactyly (extra fingers or toes) and syndactyly (webbed fingers or toes)."

Also SNOMED_CT 84598000 and UMLS CUI C0265553 map with the NCI  code and definition above in Metathesaurus.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Let's ask @pnrobinson and @ahamosh.

These seem to be synonymous to me too but there are separate Wikipedia pages for these terms (https://en.wikipedia.org/wiki/Polysyndactyly and https://en.wikipedia.org/wiki/Synpolydactyly) and I can't find any reference to these being used synonymously.

**Comment by ahamosh** [comment]
So synpolydactyly is used more frequently.  The separate entity in Wikipedia for polysyndactyly is used for crossed polysyndactyly where it is one family with post-axial polydactyly of the hands and pre-axial polydactyly of the feet. That is null entry in OMIM.   The other polysyndactyly entries in OMIM are syndromic.

**Comment by kanems** [comment]
Just adding this for reference... NCI seems to distinguish between these two terms with regard to 1. **cause** and 2. **disease vs. phenotype**. So these are not equivalent it seems. MedGen will have to make  CN identifier for synpolydactyly parent concept, UMLS has no appropriate CUI for it.

https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=21.10d&ns=ncit&code=C75003&key=n115691217&b=1&n=null
"Preferred Name:  Synpolydactyly

Definition:  A _rare genetic disorder_ characterized by malformations in the hands and feet. The abnormalities include increased number of fingers and toes and fusion of digits into one large digit."  (Genetic variation causes this, subtypes are listed in OMIM associated with HOXD13, FBLN1, etc) NCI points to UMLS C2699746, but this is the entry for the syndromic type 1 form. UMLS does not appear to have a separate cui for the concept of synpolydactyly that isn't linked to a specific gene.

https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&version=21.10d&code=C125597&ns=ncit&type=properties&key=null&b=1&n=0&vse=null
"Preferred Name:  Polysyndactyly

Definition:  A rare _anatomical malformation_ characterized by polydactyly (extra fingers or toes) and syndactyly (webbed fingers or toes)." (Agnostic of cause, just the clinical finding/observation) Maps to UMLS C0265553 but NCIT points to C3808274 (UMLS merged that into the other CUI in 2020 release)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems. I will look at this more closely asap.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky looking at Mondo, things are slightly more complicated... So I want to double check: 
1) adding synonym and references: 
NCIT C125597 ("Preferred Name: Polysyndactyly")
SNOMED_CT 84598000 
UMLS CUI C0265553 
→ all of these are Mondo:equivalentTo to polysyndactyly 4 (MONDO:0008272)

Should I 
- [ ] move these IDs to synpolydactyly (MONDO:0021651) ?
note that this term currently has Mondo:equivalentTo NCIT:C75003; We would keep the NCIT which refers to the disorder (and not to the anomaly), which would be  NCIT:C75003.
- [ ] add "polysyndactyly" as an exact synonym


2) classification: 
- Should polysyndactyly 4 (MONDO:0008272) be a child of "polysyndactyly/synpolydactyly" (MONDO:0021651)?
- Should other "polysyndactyly" terms also be children. For instance: crossed polysyndactyly (MONDO:0008286)

**Comment by pnrobinson** [comment]
The two terms are synonymous, but I would suggest that we revise the primary labels in MONDO. For instance, now the names of the children of this term in the definition are not the same as the names of the child terms
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0017425&viewMode=PreferredRoots&siblings=false

Also, I think it is not accurate that these diseases are "just" hands, as suggested by "preaxial polydactyly of fingers"

**Comment by nicolevasilevsky** [comment]
@sabrinatoro I agree with your plan of action, please go ahead.

Also, could you look at 'synpolydactyly type 1' and 'synpolydactyly type 3', they are children of 'syndactyly type 2', which seems odd.

**Comment by sabrinatoro** [comment]
I think 
syndactyly type 2 (MONDO:0019683) - (has_exact_synonym : synpolydactyly)
should be merged into 
synpolydactyly (MONDO:0021651)

New issue: #4285
