### ISSUE TITLE
merge MONDO_0018368 'primary peritoneal serous/papillary carcinoma' with MONDO:0003817 peritoneal serous papillary adenocarcinoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#392]
merge MONDO_0018368 'primary peritoneal serous/papillary carcinoma' with MONDO:0003817 peritoneal serous papillary adenocarcinoma

**Comment by nicolevasilevsky** [comment]
from NCIT:
For peritoneal serous papillary adenocarcinoma, we don’t see any term that is supposed to be merged to it. If your intent is  to make this term obsolete, it would be a mistake. This is a valid term.

**Comment by nicolevasilevsky** [comment]
action item:

- [ ] remove comment

**Comment by nicolevasilevsky** [comment]
Followed up with NCIT by email on 05/26 for clarification. I think they misread this ticket initially. I updated the label and comment.

**Comment by nicolevasilevsky** [comment]
From NCIT:
These concepts should be merged.  We recommend “primary peritoneal serous papillary adenocarcinoma” as the concept name.
FYI, the parent concept  for this term should be “primary peritoneal serous adenocarcinoma”.

**Comment by cmungall** [comment]
See also https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4176875/
