### ISSUE TITLE
Document the "changes" documentation

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#3920]
We should document the new changes documentation in the developers pages, and think about how we can generalise this in the long run across all of OBO using KGCL and perhaps even webhooks.

https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1630

I really like this new approach we worked out with Larry, but we should streamline it and offer it to other users.

**Comment by nicolevasilevsky** [comment]
Nico and I decided not to prioritize this for now, we'll do it on demand
