### ISSUE TITLE
Enable docs.yml GA workflow to push to protected master

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#3922]
Make sure https://github.com/monarch-initiative/mondo/blob/master/.github/workflows/docs.yaml

can push to `master` branch.

```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/monarch-initiative/mondo
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/monarch-initiative/mondo'
Error: Process completed with exit code 1.
```

Example of a failed run: https://github.com/monarch-initiative/mondo/runs/4070956389?check_suite_focus=true

Problem is that we have the master branch protected against commits, so somehow we need to "allow" GH actions to do it despite that.

**Comment by matentzn** [comment]
I kinda would prefer if this would instead create a pull request rather than push straight to master.

**Comment by joeflack4** [comment]
This looks like my wheelhouse.

**Comment by matentzn** [comment]
I fixed this by using PRs instead for now (sorry, I did this because I am fixing a larger issue I need to take care of).
