### ISSUE TITLE
[Merge] MONDO:0004058 pancreatic cholera

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#3946]
**Mondo term (ID and Label)**
MONDO:0004058 pancreatic cholera

**Reason for deprecation**
duplicates. I need to double check but I think these are equivalent.

**Term to be merged with**
MONDO:0019960 VIPoma

**Comment by nicolevasilevsky** [comment]
upon further investigation, these are not the same.
VIPoma is a tumor and pancreatic cholera is a syndrome.

**Comment by kanems** [comment]
Will the obsoletion and merge comments be removed from the EBI display for MONDO:0004058 ?

**Comment by nicolevasilevsky** [comment]
yes, after the release
