### ISSUE TITLE
merge MONDO_0006719 'cystic lymphangioma' with MONDO_0009761 cystic hygroma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#395]

**Comment by nicolevasilevsky** [comment]
From GARD:
Cystic hygroma:  I think the main term cystic hygroma is adequate. We already have this as the main term (cystic lymphangioma is a synonym)

**Comment by ahamosh** [comment]
agreed, cystic hygroma is the word you want.

**Comment by nicolevasilevsky** [comment]
related to #1208
