### ISSUE TITLE
OMIMPS:209850 and OMIM:209850 mapping?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#3954]
**Mondo term (ID and Label):**
MONDO:0005260 autism 

**Xref that should be fixed (ID and label):**
OMIM: PS:209850 
This is tricky because this is the PS for autism susceptibility that is already an X-ref on MONDO:0020836. But since Mondo:0005260 has no children terms, it may be more reasonable to map OMIM:209850 primary concept ('autism') to the Mondo entry for "autism" (following UMLS's association with the NCIT and HPO concept with that MIM number on CUI C0004352).  OMIM:206850 has the "included" concept for the specific susceptibility locus, so it also belongs on that term.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
OMIMPS:209850 is relatedTo on MONDO:0005260 autism and is equivalent on MONDO_0020836 'autism, susceptiblity to'.

I agree with your suggestion and I made OMIM:209850  equivalentTo on MONDO:0005260 autism
