### ISSUE TITLE
merge MONDO_0007929 'Epstein syndrome' with MONDO:0007954 May-Hegglin anomaly

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#396]
consider merge MONDO_0007929 'Epstein syndrome'  with MONDO:0007954 May-Hegglin anomaly

**MONDO_0007929 'Epstein syndrome'** 
def: An autosomal dominant disorder characterized by thrombocytopenia, giant platelets, nephritis, and deafness; it is associated with mutation of the MYH9 gene. 

**MONDO:0007954 May-Hegglin** 
def: An autosomal dominant disorder characterized by the triad of thrombocytopenia, giant platelets, and characteristic inclusions in peripheral blood leukocytes. It is characterized by varying degrees of thrombocytopenia that may be associated with purpura and bleeding; it is associated with mutation of the MYH9 gene.

**Comment by nicolevasilevsky** [comment]
From GARD:
Both Epstein Anomaly and May-Hegglin anomaly are actually under MYH9-related disorder (which we already have)

**Comment by ahamosh** [comment]
OMIM has merged all of these as: # 155100. MACROTHROMBOCYTOPENIA AND GRANULOCYTE INCLUSIONS WITH OR WITHOUT NEPHRITIS OR SENSORINEURAL HEARING LOSS; MATINS

We are not using gene symbols in disease names.
