### ISSUE TITLE
merge MONDO_0018045 'Hoyeraal-Hreidarsson syndrome' with MONDO:0010584 'dyskeratosis congenita, X-linked'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#397]

**Comment by nicolevasilevsky** [comment]
From GARD:
Hoyeraal-Hreidarsson syndrome: The reason why they are planning on merging Hoyeraal-Hreidarsson syndrome into the X-linked DC is probably because OMIM included Hoyeraal-Hreidarsson syndrome under X-linked DC on 2013.  However, Orphanet (2019) has it as a separate condition and some cases may be inherited as AR.  Also  GR (2019) and GHR (2019)  still mention it as a unique condition. It makes sense, in my opinion, I would not merge it and will  keep the term Hoyeraal-Hreidarsson syndrome separated, because it has a much more severe phenotype than other forms of DC.

**Comment by nicolevasilevsky** [comment]
Action item:
- [ ] remove comment, do not merge.

**Comment by ahamosh** [comment]
Just to clarify HHS is an included and therefore distinct phenotype within the DKC entry.
