### ISSUE TITLE
merge MONDO_0022263 'congenital hepatic fibrosis' with MONDO:0018840 'isolated congenital hepatic fibrosis'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#399]

**Comment by nicolevasilevsky** [comment]
From GARD:
Congenital Hepatic Fibrosis:  Orphanet has the term “isolated congenital hepatic fibrosis” while most sources (GR, GHR, Medscape, UpToDate, most relevant Pubmed articles) have congenital hepatic fibrosis.  I think we can change it to isolated congenital hepatic fibrosis because congenital hepatic fibrosis may occur alone (in which case it is called isolated congenital hepatic fibrosis). As per GHR: More frequently, it occurs as a feature of genetic syndromes that also affect the kidneys, such as polycystic kidney disease (PKD).

**Comment by ahamosh** [comment]
I am not sure if this exists.
