### ISSUE TITLE
[NTR] hepatic fibrosis (disease)

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#4000]
cc @idazucchi (original request: https://github.com/HumanCellAtlas/ontology/issues/96)

Dear Mondo editors, 
The Human Cell Atlas would like to request a disease term please, to represent fibrotic liver disease as needed for [this paper](https://www.cell.com/cell-reports/fulltext/S2211-1247(19)31324-5?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2211124719313245%3Fshowall%3Dtrue). We're aware that there is a term for 'Hepatic fibrosis' in HP, but the HCA schema cannot accommodate phenotype terms at present, and the paper specifically refers to "human fibrotic liver disease" and "fibrotic diseases" (as well as liver fibrosis). I realize we're in a grey zone here, but there are precedents of disease terms in Mondo like 'breast fibrosis', 'endomyocardial fibrosis' etc. so I'm wondering if you'd agree to creating this one too, possibly with a link to HP:0001395 'Hepatic fibrosis'. It could be named 'hepatic fibrosis (disease)' to distinguish it from the phenotype term, or 'fibrotic liver disease':

**Preferred term label:**
hepatic fibrosis (disease)
or
fibrotic liver disease

**Synonyms**
fibrotic liver disease
or
hepatic fibrosis (disease);
liver fibrosis (disease)

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
A liver disease characterized by the presence of excessive fibrous connective tissue in the liver.
PMID:31722201 (the same paper HCA is wrangling, above)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0005154 liver disease

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
Not really, but MONDO:0018840 'isolated congenital hepatic fibrosis' ("A congenital disorder usually inherited in an autosomal recessive pattern. It affects the hepatobiliary system and the kidneys. It is characterized by liver fibrosis, portal hypertension, and renal cysts. [ NCIT:C97071 ]") might be linked to HP:0001395 'Hepatic fibrosis'.

**Your nano-attribution (ORCID)**
http://orcid.org/0000-0002-4900-7575 (Ida's)
http://orcid.org/0000-0002-2825-0621 (mine)

Thank you,
Paola and Ida

**Comment by nicolevasilevsky** [comment]
sure thing @paolaroncaglia 

Note to self, this should probably be a child:
MONDO_0018840 'isolated congenital hepatic fibrosis'

**Comment by paolaroncaglia** [comment]
Thanks @nicolevasilevsky , you're faster than light! :-)
