### ISSUE TITLE
OMIM:104300 preferred name from OMIM is ALZHEIMER DISEASE

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4013]
**Mondo term (ID and Label):**
MONDO:0007088 Alzheimer disease type 1

**Xref that should be fixed (ID and label):**
OMIM:104300 preferred name from OMIM is ALZHEIMER DISEASE
Thus it seems it should map to MONDO:0004975
This OMIM entry covers several phenotype terms and describes the other genetic predisposition/risk types, so it seems appropriate to have it on the higher level concept. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
https://omim.org/entry/104300

**Comment by nicolevasilevsky** [comment]
I need to look at this more closely but I think the included entry should be split out.

**Comment by nicolevasilevsky** [comment]
Question for Ada - will OMIM create a phenotypic series for AD?

**Comment by nicolevasilevsky** [comment]
Talked to Ada on 02/08/22:
OMIM will create a Phenotypic series for AD 1, 2, 3, 4

They may get divided into early and late onset. This may take some time for OMIM to do this.

In the near term, Type 1 can get divided into AD type 1 and the generic.
