### ISSUE TITLE
OMIM: 189800, included name is used rather than preferred

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4015]
**Mondo term (ID and Label):**
MONDO:0008585 HELLP syndrome 

**Xref that should be fixed (ID and label):**
OMIM:189800 (MONDO:equivalentTo)
OMIM's preferred/primary name is PREECLAMPSIA/ECLAMPSIA 1; PEE1

Alternative titles; symbols
PREG1
PEE
TOXEMIA OF PREGNANCY
(HELLP is an included term on this OMIM entry)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
Thanks @kanems. I split out 'preeclampsia/eclampsia 1' to be its own term.
