### ISSUE TITLE
merge  MONDO_0002840 'eosinophilic gastritis' with MONDO_0016129 'eosinophilic gastroenteritis'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#403]
consider merge of MONDO_0002840 'eosinophilic gastritis' with parent term, MONDO_0016129 'eosinophilic gastroenteritis'

**Comment by nicolevasilevsky** [comment]
From GARD:
We had this one under eosinophilic enteropathy.  I changed to eosinophilic gastroenteritis which is much more accurate.  I also changed the names in the Q&As but I think this one needs updates:  https://www.uptodate.com/contents/eosinophilic-esophagitis-eoe-genetics-and-immunopathogenesis?search=eosinophilic-esophagitis-eoe-genetics-and-immunopathogenesisimmunopathogenesis%20underlying%20EoE.&source=search_result&selectedTitle=1~150&usage_

**Comment by ahamosh** [comment]
the gastritis is a subset of gastroenteritis.  Also are you considering this as distinct from eosinophilis esophagitis?

**Comment by nicolevasilevsky** [comment]
@ahamosh Yes, from my understanding, eosinophilic gastritis is distinct from eosinophilis esophagitis

**Comment by nicolevasilevsky** [comment]
looks like 'eosinophilic gastritis' and 'eosinophilic gastroenteritis' are synonyms according to NORD:
https://rarediseases.org/rare-diseases/eosinophilic-gastroenteritis/

**Comment by ahamosh** [comment]
gastritis is stomach inflammation.  gastroenteritis is stomach and intestine inflammation.  They are not exact synonyms.   I am not sure that this is important, but they are not exactly the same.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh! I won't merge them.
