### ISSUE TITLE
? split term:  peripheral primitive neuroectodermal tumor ?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4039]
**Term to split:**
peripheral primitive neuroectodermal tumor MONDO:0018271

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
Peripheral primitive neuroectodermal neoplasm (or tumor)
Peripheral neuroepithelioma 

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonyms that end in "1", "2", etc. should move to subclass.
_Peripheral neuroepithelioma_  seems like it should exist as a separate concept, per HP:0006717  , SNOMED  254764001, the "included" disease concept on OMIM 612219, and UMLS C3489398

(UMLS C0684337, HP:0030067, SNOMED 73676002 would support the concept of peripheral neuroectodermal tumor as a separate concept.)

Notably, NCI seems to think these are synonymous, as Mondo currently displays (NCIT: C9341) but this is in conflict with HPO and SNOMED, so I'm not sure what is correct here. For now, MedGen will put the neuroectodermal term from Mondo on the CUI and SNOMED code as described above, but split the neuroepithelioma term out for clarification of how UMLS maps the HPO concepts. 

Would be very happy for any clarification from HPO et al on the distinction/similarity of these terms. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I'd like to inquire with NCIT about this. I'll ask them and get back to you @kanems

**Comment by nicolevasilevsky** [comment]
If we do split this, we'll just bud/create a new class but we won't obsolete and recreate the original term, so I am removing th obsoletion candidate tag.

**Comment by nicolevasilevsky** [comment]
Hi @kanems 

NCIT responded: As per our pathologists, Peripheral neuroepithelioma is an absolute synonym for peripheral primitive neuroectodermal tumor.

We aim to follow NCIT for representation of cancers in Mondo, so I'll keep this as a synonym but will add a comment and a link to this ticket on the term inself.

Thanks!
