### ISSUE TITLE
MONDO:0008698 achalasia

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4055]
**Mondo term (ID and Label):**
MONDO:0008698 achalasia

**Suggested new label:**
Achalasia, familial esophageal 
(corresponding with the OMIM preferred name, clearly distinguishing it from the generic concept; would then map only to UMLS CUI: C1860213)
Would be a very targeted fix for broader issue raised in #861 https://github.com/monarch-initiative/mondo/issues/861 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
I think it would be useful/important to distinguish the familial form from the generic concept (HP:0002571, UMLS CUI: C0014848)

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] create new class for achalasia, familial esophageal

it should not be a child of 'idiopathic achalasia' though (achalasia is a child of idiopathic achalasia)
