### ISSUE TITLE
DIABETES INSIPIDUS, NEUROHYPOPHYSEAL TYPE

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4068]
I am looking for clarification on mapping of OMIM: 304900, DIABETES INSIPIDUS, NEUROHYPOPHYSEAL TYPE.

ORPHA:30925 "Hereditary central diabetes insipidus" says it matches to two OMIM numbers: 304900 and 125700 "DIABETES INSIPIDUS, NEUROHYPOPHYSEAL" (both the OrphaNET id and this second OMIM number are on MONDO:0007450) However, I couldn't find any hits on the OMIM number 304900 in Mondo. 
@ahamosh Does OMIM want to maintain OMIM 304900? If this is a distinct clinical presentation vs. 125700, would it be possible to modify the name of the MIM term and thus clarify the distinction?

**Comment by nicolevasilevsky** [comment]
Peter recommends obsoleting this term in Mondo.
From OMIM:
An X-linked form of neurohypophyseal diabetes insipidus ([304900](https://omim.org/entry/304900)) has been suggested, but the evidence is weak.

**Comment by nicolevasilevsky** [comment]
Looks like this was already done, MONDO_0010582 is obsolete
'obsolete diabetes insipidus, neurohypophyseal type, X-linked inheritance'
