### ISSUE TITLE
merge MONDO_0024462 'familial cutaneous melanoma' with MONDO_0005012 'cutaneous melanoma (disease)'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#407]

**Comment by cmungall** [comment]
what is the justification for this?

these are different concepts

```
id: MONDO:0024462
name: familial cutaneous melanoma
def: "An instance of cutaneous melanoma (disease) that is caused by an inherited modification of the individual's genome." [MONDO:patterns/hereditary]
comment: Editor note: consider merge with parent
synonym: "hereditary cutaneous melanoma (disease)" EXACT [MONDO:patterns/hereditary]
xref: OMIMPS:155600 {source="MONDO:equivalentTo"}
intersection_of: MONDO:0005012 ! cutaneous melanoma (disease)
intersection_of: has_modifier MONDO:0021152 ! inherited
```

if the decision is that we don't need a familial subclass and we want to just have the generic subclass, this is fine, but it's not a merge as the concepts are not equivalent

(unless we are saying there are no non-familial cases of this melanoma which seems unlikely)

**Comment by nicolevasilevsky** [comment]
There is a comment on the class:
Editor note: consider merge with parent

**Comment by nicolevasilevsky** [comment]
Perhaps the comment was suggesting a merge with the other parent - MONDO_0018961 'familial melanoma'.

**Comment by nicolevasilevsky** [comment]
from ncit:
Familial cutaneous melanoma and cutaneous melanoma should not be merged. Familial cutaneous melanoma is a distinct hereditary cutaneous melanoma caused by germline mutations in CDKN2a or CDK4 genes and is associated with increased incidence of pancreatic cancer.

**Comment by nicolevasilevsky** [comment]
I am going to remove the comment and update the definition of Familial cutaneous melanoma

**Comment by nicolevasilevsky** [comment]
Should we add SubClassOf assertions to MONDO_0018961 'familial melanoma'?

'disease has basis in dysfunction of' some CDKN2A
'disease has basis in dysfunction of' some CDK4

I am unsure is this is the correct approach because the mutations can be in either gene.

**Comment by nicolevasilevsky** [comment]
Also, should we add SubClassOf assertion:
'predisposes towards' some 'pancreatic cancer'

**Comment by nicolevasilevsky** [comment]
Looking at this again, I do think that MONDO_0024462 'familial cutaneous melanoma' (https://omim.org/phenotypicSeries/PS155600) is equivalent to MONDO_0018961 'familial melanoma' (https://rarediseases.info.nih.gov/diseases/3460/hereditary-melanoma, [Orphanet:618](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_618))

@ahamosh would you mind looking at this? Thank you!

**Comment by ahamosh** [comment]
Hi Nicole, OMIM is treating all the germline (and therefore possibly familial or hereditary) malignant cutaneous melanomas in the same series.  So, yes, equivalent, but we are separating each one by gene (as we do).

**Comment by nicolevasilevsky** [comment]
Note to self - this will be addressed with https://github.com/monarch-initiative/mondo/discussions/2672

**Comment by nicolevasilevsky** [comment]
All of the children of 'familial cutaneous melanoma' in the [OMIMPS](https://omim.org/phenotypicSeries/PS155600) are susceptibility.

I think we should move this branch to a child of 'inherited disease susceptibility.

revise logical def to

'inherited disease susceptibility'
 and ('predisposes towards' some 'cutaneous melanoma')

**Comment by nicolevasilevsky** [comment]
emailed Sharon Plon to inform her on 09/03/21
