### ISSUE TITLE
MONDO:0011140 benign familial neonatal-infantile seizures [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4073]
**Mondo term (ID and Label)**
MONDO:0011140 benign familial neonatal-infantile seizures

**Suggested revision and reasons**
OrphaNet https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=140927 says 140927 is a 1:1 equivalent with OMIM 607745 (MONDO:0042499, benign familial neonatal-infantile seizures 1) 

but GARD 856 points back to OrphaNet 306 https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=306 which is a broader term and points to multiple OMIM records... so I don't really know what's going on here. I would appreciate someone else taking another look at this.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by kanems** [comment]
Circling back around to this topic, some more issues I am seeing/suggesting changes to the Mondo display:
MONDO:0011140 benign familial neonatal-infantile seizures =  Orphanet:140927 (MONDO:equivalentTo) ; Orphanet says this term is a 1:1 with OMIM: 607745, but this is already mapped to MONDO:0011904 seizures, benign familial infantile, 3
Suggest a MERGE of MONDO:0011140 and MONDO:0011904

**Comment by nicolevasilevsky** [comment]
to do:
merge MONDO:0011140 and MONDO:0011904

Command:
sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0011140 MONDO:0011904 -o -f obo mondo-edit.obo
