### ISSUE TITLE
merge MONDO_0019625 'familial thoracic aortic aneurysm and aortic dissection' with OMIMPS

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#408]
On the comment for MONDO_0019625 'familial thoracic aortic aneurysm and aortic dissection', it says to merge with the OMIM phenotypic series: MONDO_0011769 'familial aortic dissection'

**Comment by courtneythaxton** [comment]
Hi @nicolevasilevsky we currently have 23 gene curations on the ClinGen website that use MONDO_0019625. 

See: https://search.clinicalgenome.org/kb/conditions/MONDO_0019625

I have emailed members of our software team for inquiries on how to handle a change like this, as well as talking with the Expert Panel. I hope to be able to update you on this possible change soon.

**Comment by nicolevasilevsky** [comment]
From GARD:
We have Familial thoracic aortic aneurysm and dissection with Familial thoracic aortic dissection as a synonym.  Orphanet also have Familial thoracic aortic aneurysm and aortic dissection which is more accurate for the clinical features.

**Comment by courtneythaxton** [comment]
Thanks @nicolevasilevsky , I will take this information back to the group to see if we have anymore feedback. So just so that I get my understanding straight, the MONDO:0019625 will still be a valid ID (i.e. it is not be deleted), however the nomenclature or title will change to familial aortic dissection. Is that correct?

**Comment by courtneythaxton** [comment]
Or will the MONDO:0019625 now become MONDO_0011769? @nicolevasilevsky 

Thanks!

**Comment by nicolevasilevsky** [comment]
I think we'll want to keep MONDO:0019625 'familial thoracic aortic aneurysm and aortic dissection' and obsolete MONDO_0011769 'familial aortic dissection'

Would that work for you, @courtneythaxton ?

**Comment by courtneythaxton** [comment]
Yes that would work for me @nicolevasilevsky. Thank you for your responsiveness and feedback!

**Comment by ahamosh** [comment]
Glad to see this chain. The point is to avoid dissection! 
Thanks,
Ada
