### ISSUE TITLE
Confusion on nonepidermolytic palmoplantar keratoderma terms

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4095]
Rather than reopening #3108 , I wanted to open a new ticket to request review of just a couple of these terms because we are running into issues trying to map **MONDO:0006588 "nonepidermolytic palmoplantar keratoderma"** and **MONDO:0010962 "diffuse nonepidermolytic palmoplantar keratoderma"** in MedGen. 

The preferred name on MONDO:0006588  matches the OMIM preferred name for 600962 (but this maps to MONDO:0010962). 

So I am reviewing the X-refs on these Mondo IDs in hopes that a better nomenclature/distinction can be made between the grouping concept and the gene-specific forms.... as best I can tell, historically these have been mixed up/used interchangeably until the molecular cause was determined to be two different loci. So I appreciate the need for a parent concept and the two gene-specific children, but I don't think the X-refs as they are currently mapped are correct, nor do the names align with the X-refs. My attached notes hopefully document how mixed up the different cross-references are here, but we certainly need medical review of these two/three concepts to determine what the correct names/concepts are that should be represented. If I can find a good review of these disorders I'll post the article as a comment.

[nonepidermolytic palmoplantar keratoderma_XRefNotes.txt](https://github.com/monarch-initiative/mondo/files/7645451/nonepidermolytic.palmoplantar.keratoderma_XRefNotes.txt)

## _Notes are pasted below:_

nonepidermolytic palmoplantar keratoderma MONDO:0006588
Orphanet:2337 (MONDO:equivalentTo) "Non-epidermolytic palmoplantar keratoderma"
  SYNS: Synonym(s):
  Autosomal dominant diffuse palmoplantar keratoderma, Norrbotten type
  Diffuse palmoplantar keratoderma, Bothnian type
  NEPPK
  X-refs: OMIM: 600231 "PALMOPLANTAR KERATODERMA, BOTHNIAN TYPE; PPKB"
  UMLS: C1833030 "PALMOPLANTAR KERATODERMA, NONEPIDERMOLYTIC" (and UMLS says this CUI matches HP:0007404, OMIM: 600962, and MESH C563422) 
        C1838359 "Diffuse palmoplantar keratoderma, Bothnian type" (UMLS x-refs MESH C536173 and OMIM 600231) 
   GARD: 1862  "Diffuse palmoplantar keratoderma, Bothnian type"
DOID:0050428 (MONDO:equivalentTo) : "nonepidermolytic palmoplantar keratoderma" with exact syns "Thost-Unna Syndrome; Unna-Thost Syndrome; tylosis; diffuse nonepidermolytic palmomplantar keratoderma"
ICD10:Q82.8 (Orphanet:2337) (Not evaluated)
SCTID:716105001 (MONDO:equivalentTo) "Autosomal dominant diffuse palmoplantar keratoderma Norrbotten type" syn of Non-epidermolytic palmoplantar keratoderma; Definition: "This syndrome has manifestation of a diffuse non-epidermolytic palmoplantar keratoderma with frequent fungal infections. Prevalence in the general population is estimated at 1 in 40,000 but is much higher in northern Sweden. Transmission is autosomal dominant and the causative gene has been localized to chromosome 12q11-q13. (SNOMEDCT_US)"
EFO:1000743 (MONDO:equivalentTo) (Not evaluated, not sure what this resource is and there is no link from Mondo)

diffuse nonepidermolytic palmoplantar keratoderma MONDO:0010962
OMIM:600962 (Orphanet:530838) "PALMOPLANTAR KERATODERMA, NONEPIDERMOLYTIC; NEPPK" aka PPKNE
    NONEPIDERMOLYTIC PALMOPLANTAR KERATODERMA
    KERATODERMA, NONEPIDERMOLYTIC PALMOPLANTAR
    TYLOSIS (though perhaps this is an instance of OMIM using a more general concept as an alternate name)
Orphanet:496 (OMIM:600962) "Thost-Unna palmoplantar keratoderma" X-refs GARD 5186 (but OrphaNet has note: "This entity has been excluded from the Orphanet nomenclature of rare diseases and moved to Epidermolytic palmoplantar keratoderma." So maybe this should be obsoleted in Monodo X-ref?)
GARD:0005186 (OMIM-shared) "Unna-Thost palmoplantar keratoderma" and GARD defines it as "Unna-Thost palmoplantar keratoderma is inherited in an autosomal dominant pattern and caused by genetic changes in the KRT1 gene." and X-refs Palmoplantar keratoderma, nonepidermolytic, NEPPK. Online Mendelian Inheritance of Man (OMIM). September 2009; http://omim.org/entry/600962. **Accessed 10/12/2011.**
Orphanet:530838 (MONDO:equivalentTo) "KRT1-related diffuse nonepidermolytic keratoderma" points to OMIM 600962, and thank you that this is not Mondo's preferred name.

Related Mondo term:  
palmoplantar keratoderma, Bothnian type  MONDO:0010849
Points to OMIM: 600231;  PALMOPLANTAR KERATODERMA, BOTHNIAN TYPE; PPKB
and GARD:0001862 (OMIM-shared)

Clean up idea:
There is the Orphanet term  "Autosomal dominant isolated diffuse palmoplantar keratoderma ORPHA:98349" which could be the parent concept to OMIM:600962 and OMIM: 600231 since they are both AD inhertiance. Then 'dissolve' MONDO:0006588 and move the X-refs to the appropriate gene-specific terms, maybe adjust some of the names from X-refs to "related synonyms" to clarify which type is which?

**Comment by sabrinatoro** [comment]
I reviewed the descriptions in OMIM, and the orphanet/OMIM mappings. I think these are the correct ids: 

  | OMIM | Orphanet | Gene | From omim description
-- | -- | -- | -- | --
MONDO:0010962 diffuse nonepidermolytic palmoplantar keratoderma | 600962 | ORPHA:530838 | KRT1 | diffuse nonepidermolytic palmoplantar keratoderma (NEPPK)
MONDO:0010849 palmoplantar keratoderma, Bothnian type | 600231 | ORPHA:2337 | AQP5 | diffuse Bothnian type of NEPPK (PPKB)
*MONDO:0013073 palmoplantar keratoderma, nonepidermolytic, focal 1 | 613000 | [ORPHA:448264 =isolated focal, map to 2 omim: 613000  616400) | KRT16 | focal form of NEPPK
*MONDO:0014272palmoplantar keratoderma, Nagashima type | 615598 | ORPHA:140966 | SERPINB7 | diffuse Nagashima type of NEPPK (PPKN)
*MONDO:0014327 palmoplantar keratoderma, nonepidermolytic, focal or diffuse | 615735 | ORPHA:402003 | KRT6C | form of NEPPK

All these terms should have a common parent (terms with * in table above do not share a parent): 
nonepidermolytic palmoplantar keratoderma (MONDO:0006588)
Note that we need to review and find the correct x-refs for this term such that it represents the parent term. 

@nicolevasilevsky, could you review this when you have a moment. If it sounds good, I will make the changes in the ontology. Thank you.

**Comment by nicolevasilevsky** [comment]
This looks okay to me. @kanems is it okay with you?

**Comment by kanems** [comment]
@sabrinatoro and @nicolevasilevsky yes, I agree with Sabrina's excellent and very clear table with one parent term that is agnostic of inheritance pattern. Thanks!

**Comment by nicolevasilevsky** [comment]
Thanks @kanems! @sabrinatoro please go ahead!

**Comment by sabrinatoro** [comment]
I want to make sure our classification is correct. 
Currently in Mondo: 
'nonepidermolytic palmoplantar keratoderma' (MONDO:0006588) (NEPPK) 
_is a child of_ 
'isolated diffuse palmoplantar keratoderma' (MONDO:0017667)

@ahamosh 
Is this correct? is NEPPK always 'diffuse'? 

If yes, then in addition to split/merge, we need to rename labels according to disease-by-gene pattern.
If no, then we need to review classification.

**Comment by ahamosh** [comment]
I think so.  honestly, just read all the information and am still somewhat confused...
Ada

**Comment by sabrinatoro** [comment]
I reviewed the terms once again, looking specifically at their inheritance mode and whether they are diffuse or focal. I am taking back what I said above :-) 
The current terms and their parents are ok, except for the following terms: 

1) 'palmoplantar keratoderma, Bothnian type' (MONDO:0010849)
This term should be a child of 'autosomal dominant isolated diffuse palmoplantar keratoderma' (MONDO:0020093).
Also, this term should have MondoEquivalentTo: Orphanet:2337  (and this xref should be removed from MONDO:0006588)

2) 'nonepidermolytic palmoplantar keratoderma' (MONDO:0006588) should be merged into 'diffuse nonepidermolytic palmoplantar keratoderma' (MONDO:0010962)
The parent term, 'autosomal dominant isolated diffuse palmoplantar keratoderma' (MONDO:0020093), is correct
