### ISSUE TITLE
Question about "narrowMatch" properties disappearing

### ISSUE THREAD

**Issue by Sean-Ontoforce** [monarch-initiative/mondo#4109]
They used to be in the "skos" part of the OWL. Are they gone forever? Or where the resources updated and does the current release just happen to have none of them?
I can still find some "broadMatches", so it might be the latter.
Or is there a plan to phase these things out entirely and only keep the exactMatches?

E.g. for http://purl.obolibrary.org/obo/MONDO_0001744

It used to be annotated with: 
<skos:narrowMatch rdf:resource="http://purl.obolibrary.org/obo/NCIT_C34639"/>
<skos:closeMatch rdf:resource="http://identifiers.org/snomedct/193544008"/>
<skos:closeMatch rdf:resource="http://identifiers.org/snomedct/270882001"/>
+ some skos:exactMatches

Now only the "skos:exactMatch" annotations remain.

Thanks in advance!

**Comment by nicolevasilevsky** [comment]
Hi @Sean-Ontoforce - thanks for reporting this. We'll look into this and get back to you asap.

**Comment by matentzn** [comment]
@Sean-Ontoforce Wow sorry about that, this was an accident during a pipeline revision. You should see the matches again after the next release! Thank you for reporting!

**Comment by nicolevasilevsky** [comment]
Thanks @Sean-Ontoforce!
