### ISSUE TITLE
Obsolete-some high-level grouping classes AND review children terms

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4111]
This issue is part of the November 2021 Mondo workshop [here](https://docs.google.com/document/d/18Vhp12ZzbDvmcqB2I_VoswMPa8hPgs5zNPoGI-t2lqc/edit?usp=sharing)

**Mondo term (ID and Label)**
disease of cell nucleus
hip region disease
abdominal and pelvic region disorder
head or neck disease/disorder
limb disorder
thoracic disease
pigmentation disease - _NV: I added the obs tag_

**Reason for deprecation**
This is a grouping class- it is difficult to maintain the children terms and it was determined that is no longer needed.

**!!! We need to review and make sure that all the children terms have another parent**

**Comment by sabrinatoro** [comment]
Note that we might want to create a new issue for each term being obsoleted, especially if children become orphane and need to be reclassified

**Comment by sabrinatoro** [comment]
Breast disease: 
Children are a mix of neoplasm and post-partum,...

TODO: 
- [ ] Keep this as a high-level term
- [ ] Review children (some should have more than one parent (e.g breast neoplasm)

**Comment by nicolevasilevsky** [comment]
I wonder if we should add jaundice as a grouping class (see NCIT: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C3143&lang=en&viewMode=All&siblings=false)

[MESH](https://meshb.nlm.nih.gov/record/ui?ui=D007567) classifies neonatal jaundice as a child of MONDO_0024288 hyperbilirubinemia

**Comment by pnrobinson** [comment]
Both jaundice and hyperbilirubinemia are not diseases, they should be HPO terms. jaundice is a manifestation of hyperbilirubinemia, which has a ton of different causes.
neonatal jaundice is a disease (phenotypic feature plus implied etiology).

**Comment by ahamosh** [comment]
I agree with Peter, except that neonatal jaundice can have many etiologies.  The disease entity is really neonatal jaundice due to ABO incombatibility.  Otherwise the list is very long.

**Comment by sabrinatoro** [comment]
@pnrobinson @ahamosh Thank you for your answers. I however have more questions. 
 
The Mondo term 'neonatal jaundice' (disease) includes terms with different etiologies: due to accelerated destruction of erythrocytes, liver immaturity,...
This is the current classification: 
![Screen Shot 2022-02-10 at 12 01 09 PM](https://user-images.githubusercontent.com/12737987/153488735-3cef569f-c491-47fb-a387-6e5a5c792ab8.png)

Therefore, 'neonatal jaundice due to ABO incompatibility' would refer to a more specific term. Is this right? 
Should we instead obsolete the grouping term "neonatal jaundice", and create more specific terms which would be defined by their etiologies?

Thank you in advance!

**Comment by ahamosh** [comment]
I would get rid of this as a disease.
Ada

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicolevasilevsky** [comment]
@sabrinatoro I think we should obsolete these two terms as well (children of thoracic disease, which will become orphaned after thoracic disease is obsoleted):
MONDO_0015879 'non-syndromic diaphragmatic or thoracic malformation'
MONDO_0015880 'syndromic diaphragmatic or thoracic malformation'

I'll add them to the list for June obsoletion

**Comment by ahamosh** [comment]
I agree.

**Comment by sabrinatoro** [comment]
New issues were created for the remaining obsoletion. I think this issue can be closed.
