### ISSUE TITLE
Make 'psychiatric disorder' high-level term

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4112]
This issue is part of the November 2021 Mondo workshop [here](https://docs.google.com/document/d/18Vhp12ZzbDvmcqB2I_VoswMPa8hPgs5zNPoGI-t2lqc/edit?usp=sharing)

'psychiatric disorder' (MONDO:0002025) is currently a child of 'nervous system disorder'.
It should be made a high level term.

Note: 
- we might have to review the current EquivalentTo
- we should review the discussions on this subject in EFO

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I need some help with this issue.
How can I make this term a high-level term without missing the relation to "nervous system disorder"? 
Should this be done via a tag, and it will be done downstream? Or can we have it "both ways" in protege?
Thanks!

**Comment by nicolevasilevsky** [comment]
I guess the question is if we want psychiatric disorder to still be a child of nervous system disorder. If we add 'disease or disorder' as a parent, it will not show up in the inferred view. 

I'm not sure what the best answer is, can you check with Peter, Chris and Nico?
