### ISSUE TITLE
Make 'reproductive system disease' a high-level term

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4113]
This issue is part of the November 2021 Mondo workshop [here](https://docs.google.com/document/d/18Vhp12ZzbDvmcqB2I_VoswMPa8hPgs5zNPoGI-t2lqc/edit?usp=sharing)

'reproductive system disease' (MONDO:0005039) is currently a child of 'disease of genitourinary system'.
It should be made a high level term.

Note: 
- We might want to obsolete  'disease of genitourinary system' (MONDO:0021145). If so, this issue might need to be renamed "obsolete MONDO:0021145"
- we should review the discussions on this subject in EFO

**Comment by sabrinatoro** [comment]
@nicolevasilevsky
I need some help with this issue.
How can I make this term a high-level term without missing the relation to "disease of genitourinary system"?
Should this be done via a tag, and it will be done downstream? Or can we have it "both ways" in protege?
Thanks!

**Comment by nicolevasilevsky** [comment]
@sabrinatoro sounds like we may want to obsolete disease of genitourinary system, so the action item would be just to remove that as the parent class.

I don't know that we necessarily need to have a connection between reproductive system disease and genitourinary system, do we?

In Uberon, genitourinary system is logically defined as:
'anatomical system'
 and ('has part' some 'reproductive system')
 and ('has part' some 'renal system')

So there is that relationship encoded in the logic.

If this doesn't answer your question, could you please follow up with Chris and Peter? Thanks!

**Comment by nicolevasilevsky** [comment]
action item:
- [ ] obsolete genitourinary system
