### ISSUE TITLE
add "congenital" axioms to 'congenital abnormality' children terms

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4114]
This issue is part of the November 2021 Mondo workshop [here](https://docs.google.com/document/d/18Vhp12ZzbDvmcqB2I_VoswMPa8hPgs5zNPoGI-t2lqc/edit?usp=sharing)

Review children of 'congenital abnormality' and add axiom : ‘has modifier’ some congenital

Note that 'congenital abnormality' has already been obsoleted

**Comment by nicolevasilevsky** [comment]
we need o sparql for congenital in the label and then set up a ROBOT template (either for an equiv axiom or sublcassOf axiom, I think it may vary case by case)

**Comment by sabrinatoro** [comment]
This is a duplicate of #4069 
closing
