### ISSUE TITLE
deep (seated) dermatophytosis [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4128]
**Mondo term (ID and Label)**
MONDO:0018335 deep dermatophytosis

**Reason for deprecation**
Appears to be the same concept as 
MONDO:0021660 deep seated dermatophytosis
(UMLS maps HP:0032515 and NCI C35073 to the same CUI: C1395264 and ORPHA:397587 also points to this CUI) 

**Term to be merged with**
MONDO:0021660 deep seated dermatophytosis

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
note to self:
sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0018335 MONDO:0021660 -o -f obo mondo-edit.obo
