### ISSUE TITLE
short(-)rib(-)polydactyly syndrome type 3 and Verma-Naumoff names?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4148]
I am trying to understand the nomenclature & differences/similarities between OMIM and OrphaNet as they related to these Mondo terms, the alternate names on these terms (and the names on the external sources) seem very similar:
**MONDO:0019664;**  PREF name: short rib-polydactyly syndrome, Verma-Naumoff type
exact syn: short rib-polydactyly syndrome type 3
(This mondo term X-refs ORPHA:93271, which says OMIM 613091 is one of many OMIM concepts that map to the OrphaNet ID, so presumably this is a broader term?)

**MONDO:0013127** PREF name: asphyxiating thoracic dystrophy 3
Mondo exact syn: Verma-Naumoff syndrome
OMIM PREF name: SHORT-RIB THORACIC DYSPLASIA 3 WITH OR WITHOUT POLYDACTYLY alt names: (from OMIM 613091) SHORT RIB-POLYDACTYLY SYNDROME, TYPE III (SRPS3) and VERMA-NAUMOFF SYNDROME (Is this an instance of OMIM using more generic descriptors in the alt names field to assist users who might want to find the more specific forms?)

I would appreciate it if @ahamosh and @ana-rath-orphanet and their teams could take a look and help me understand this out so we can accurately represent these concepts in MedGen.

**Comment by ahamosh** [comment]
Hi @kanems, We think that all of these conditions are one with slightly different flavors of no significance.  An alternated title in OMIM is a synonym.  If we think it is different, it is an included or preferably spun out to a new entry.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh!

@kanems is there any action required for Mondo or can this be closed?

**Comment by nicolevasilevsky** [comment]
@kanems I will close this but please reopen if needed.

**Comment by kanems** [comment]
Sorry for the delay in getting back to this ticket. Based on Ada's comment:

> We think that all of these conditions are one with slightly different flavors of no significance
Should these mondo terms be merged?

> MONDO:0019664; PREF name: short rib-polydactyly syndrome, Verma-Naumoff type
exact syn: short rib-polydactyly syndrome type 3
(This mondo term X-refs ORPHA:93271, which says OMIM 613091 is one of many OMIM concepts that map to the OrphaNet ID, so presumably this is a broader term?)

MONDO:0013127 PREF name: asphyxiating thoracic dystrophy 3
Mondo exact syn: Verma-Naumoff syndrome
OMIM PREF name: SHORT-RIB THORACIC DYSPLASIA 3 WITH OR WITHOUT POLYDACTYLY alt names: (from OMIM 613091) SHORT RIB-POLYDACTYLY SYNDROME, TYPE III (SRPS3) and VERMA-NAUMOFF SYNDROME

**Comment by ahamosh** [comment]
We lumped the asphyxiating thoracic dystrophy with the short-rib-polydactyly to make short-rib thoracic dysplasia with or without polydactyly.  We did this for all of them.  Yes, merge.

**Comment by nicolevasilevsky** [comment]
thanks @ahamosh!

Note to self, action item:
merge
MONDO:0019664 and MONDO:0013127

**Comment by sabrinatoro** [comment]
added to the merge list, will have to wait until June milestone
