### ISSUE TITLE
merge MONDO_0019097 'rare hemorrhagic disorder due to a constitutional platelet anomaly' into parent

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#415]
consider merge of MONDO_0019097 'rare hemorrhagic disorder due to a constitutional platelet anomaly' with parent (there are multiple parents but I think it means this one: MONDO_0016629 'rare hemorrhagic disorder due to a platelet anomaly')

**Comment by cmungall** [comment]
go one step further. We don't want any diseases prefixed by "rare "

**Comment by nicolevasilevsky** [comment]
from Peter:

I do not like the label "rare hemorrhagic...due to a". What is "rare"? Can't we say something like "Mendelian platelet disease"

**Comment by nicolevasilevsky** [comment]
Looking at this more closely, I think it should just be renamed to remove the 'rare' and add a subClass Of assertion 'has modifier' some rare.

A constitutional cytogenetic abnormality is that which occurs from birth.

**Comment by nicolevasilevsky** [comment]
The children should be renamed too to remove the 'rare'
