### ISSUE TITLE
OMIMPS:608808 no longer exists (??)

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4150]
**Mondo term (ID and Label):**

MONDO:0019443
dextro-looped transposition of the great arteries

**Xref that should be fixed (ID and label):**
 OMIMPS:608808 (MONDO:equivalentTo) 
(Trying to link to https://www.omim.org/phenotypicSeries/PS608808 from MedGen/GTR's data and it shows "Invalid phenotypic series number") OMIM 608808 has recent edits (Sept 2021) and looks like renaming of some other OMIM terms led to dissolution of the PS. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
Hi @kanems this is a question for OMIM. I'll forward this on to Ada.

**Comment by nicolevasilevsky** [comment]
I'll mark OMIMPS:608808 as MONDO:equivalentObsolete in Mondo

**Comment by ahamosh** [comment]
We took out the dextro-looped transposition of the great arteries from MED13L, because the missense variants reported had no functional data to support the validity.  We no longer have PS608808.
