### ISSUE TITLE
how to handle synonyms from Orphanet slurp

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4163]
If a source ontology deletes a synonym, do we want to keep provenance or is it more important to be current?

Eg
If there is a dbxref to Orphanet on a synonym, and then Orphanet deletes that synonym, do we want to remove the Orphanet xref or somehow retain that provenance?

**Comment by matentzn** [comment]
Needs to be top of the list QC call

**Comment by nicolevasilevsky** [comment]
we need to decide between two things:
1. do we design the merge pipeline n a way that we keep ourselves current w/ external sources
2. do we design provenance such that we always keep the provenance from the source

**Comment by nicolevasilevsky** [comment]
Lower priority - capture the historic provenance
