### ISSUE TITLE
(Cutaneous) Mastocytosis, OMIM X-ref

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4164]
**Mondo term (ID and Label):**
MONDO:0007950
mastocytosis

**Xref that should be fixed (ID and label):**
 OMIM:154800 (Orphanet:98292) 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
The OMIM Preferred name for this term is MASTOCYTOSIS, CUTANEOUS (MASTC)
Systemic mastocytosis is an "included" term.
This is another one of these policy-type questions: will Mondo be following the OMIM preferred name for mapping OMIM records, or the overall concept/phenotype(s) associated with the OMIM entry? I can see an argument in favor of keeping the MIM number on the parent concept since the OMIM entry reflects both cutatneous and systemic presentations, but from a 'rules' based understanding of Mondo:OMIM relationships, the mapping based on preferred name is currently inconsistent for this term. 
For now, MedGen/GTR will continue to map the OMIM number based on the preferred name because that's how our workflow and policies are set, but we are open to participating in discussions of how OMIM prefers these more expansive terms to be represented and making case-by-case exceptions as needed.

**Comment by nicolevasilevsky** [comment]
@kanems I agree with your assessment and I think OMIM:154800 should remove to the subclass.
