### ISSUE TITLE
merge MONDO_0018708 'squamous cell carcinoma of the oral tongue' with MONDO_0000500 'tongue squamous cell carcinoma' 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#418]
consider merge MONDO_0018708 'squamous cell carcinoma of the oral tongue' with MONDO_0000500 'tongue squamous cell carcinoma' (parent class)

**Comment by cmungall** [comment]
Let's keep these separate: https://www.webmd.com/cancer/tongue-cancer-facts#1

Uberon has:

id: UBERON:0010032
name: anterior part of tongue
def: "The portion of the tongue in front of the terminal sulcus. At the apex, thin and narrow, it is directed forward against the lingual surfaces of the lower incisor teeth. It is derived primarily from the first pharyngeal arch." [Wikipedia:Anterior_tongue]
xref: Wikipedia:Anterior_tongue
property_value: development_notes "The lateral lingual swellings grow and fuse with eachother, encompassing the tuberculum impar to provide the ectodermally derived mucosa of the anterior 2/3 of the tongue" xsd:string
property_value: external_ontology_notes "check NCIT" xsd:string {external_ontology="NCIT"}
xref: FMA:229084 ! anterior part of tongue
xref: NCIT:C32130 ! Apex of the Tongue
synonym: "anterior 2/3 of the tongue" RELATED [Wikipedia:Anterior_tongue]
synonym: "anterior 2/3 of tongue" RELATED [Wikipedia:Anterior_tongue]
synonym: "anterior two thirds of the tongue" RELATED [Wikipedia:Anterior_tongue]
synonym: "apex linguae" RELATED [Wikipedia:Anterior_tongue]
synonym: "apex of the tongue" RELATED [Wikipedia:Anterior_tongue]
synonym: "buccal part of the tongue" RELATED [Wikipedia:Anterior_tongue]
synonym: "front of the tongue" RELATED [Wikipedia:Anterior_tongue]
synonym: "oral part of the tongue" RELATED [Wikipedia:Anterior_tongue]
intersection_of: UBERON:0000064 ! organ part
intersection_of: part_of UBERON:0001723 ! tongue
intersection_of: develops_from UBERON:0006260 {source="ISBN10:1607950324"} ! lingual swellings
synonym: "pars anterior dorsi linguae" RELATED LATIN [Wikipedia:Anterior_tongue]
property_value: http://xmlns.com/foaf/0.1/depicted_by http://upload.wikimedia.org/wikipedia/commons/4/4c/Illu04_tongue.jpg
xref: UMLS:C0226946 {source="ncithesaurus:Apex_of_the_Tongue"}
disjoint_from: UBERON:0010033 {source="lexical"} ! posterior part of tongue
xref: EMAPA:37437 {source="MA:th"} ! tongue anterior part


But FMA also has a separate class for "oral part of tongue". I'm not sure how much a strict division matters here

**Comment by cmungall** [comment]
See also:

https://rarediseases.org/rare-diseases/tongue-cancer/

_Tongue cancers are oral cancers that are **differentiated by their location in the mouth and on the tongue**_ ... _The characteristics of these two cancers are quite **distinct**, and reflect the differences in their origins_

But note if we do keep we need to keep it's sib

**Comment by nicolevasilevsky** [comment]
action item:
- [ ] remove comment

**Comment by nicolevasilevsky** [comment]
> But note if we do keep we need to keep it's sib

MONDO_0018708 'squamous cell carcinoma of the oral tongue' does not have a sibling
