### ISSUE TITLE
Absence of xref in MONDO:0019313, lymphatic malformation

### ISSUE THREAD

**Issue by seoanezonjic** [monarch-initiative/mondo#4183]
**Mondo term (ID and Label):**
MONDO:0019313 => lymphatic malformation

**Xref that should be fixed (ID and label):**
Absence of the xref: 
Orphanet:79452 Milroy disease

**Your nano-attribution (ORCID)**
0000-0002-3020-1415 

**Other comments:**
I'm currently working in a paper using Monarch resources. Testing a set of relations I realized that one gene involved with my pathology was missed. Tracking this issue, I've found in the MONDO obo file (data-version: releases/2021-12-01/reasoned.owl.owl)  the following for MONDO:0019313

```
id: MONDO:0019313
name: lymphatic malformation
def: "Primary lymphedema is caused by anatomic or functional defects in the lymphatic system, resulting in chronic swelling of body parts and lymphatic-system malformation." [PMID:22831870]
subset: ordo_disease {source="Orphanet:79452"}
synonym: "hereditary lymphedema" EXACT [MONDO:patterns/hereditary]
synonym: "lymphedema, hereditary" EXACT [OMIMPS:153100]
xref: DOID:0050580 {source="MONDO:equivalentTo"}
xref: GARD:0007220 {source="MONDO:superClassof", source="Orphanet-shared"}
xref: ICD10:Q82.0 {source="ORDO:79452/attributed", source="ORDO:79452/ntbt", source="MONDO:equivalentTo", source="Orphanet:79452"}
xref: ICD9:757.0 {source="DOID:0050580"}
xref: OMIMPS:153100 {source="MONDO:cjm", source="MONDO:equivalentTo"}
xref: SCTID:254199006 {source="MONDO:equivalentTo"}
is_a: MONDO:0016229 {source="MONDO:Redundant", source="Orphanet:79452", source="Orphanet:79452/inferred"} ! genetic vascular anomaly
is_a: MONDO:0019175 {source="MONDOLEX:0019313", source="Orphanet:79452", source="Orphanet:79452/inferred"} ! primary lymphedema
intersection_of: MONDO:0019297 ! lymphedema
intersection_of: has_modifier MONDO:0021152 ! inherited
property_value: exactMatch DOID:0050580
property_value: exactMatch http://identifiers.org/snomedct/254199006
property_value: exactMatch https://omim.org/phenotypicSeries/PS153100
```
I build a dictionary orphanet-mondo terms using the xref property so I can retrieve the genes associated with the orphanet disease using the monarch resources. Inspecting this mondo term there is evidence that is derived from the Orphanet:79452 entry. Furthermore, checking the definition of this ORPHA disease makes sense with the MONDO definition. Why is missing this xref? Other MONDO terms could be affected?
Thank you in advance
Pedro Seoane

**Comment by seoanezonjic** [comment]
To recover the lost relations, I've developed a script to detect which MONDO terms are affected by this feature. Except the following list, the terms that have the attribute _subset: ordo_disease {source=}_  pointing to an orphanet id also have a concordant xref attribute:

```
MONDO:0007691   Orphanet:2932
MONDO:0008044   Orphanet:36899
MONDO:0008315   Orphanet:1331
MONDO:0010768   Orphanet:206484
MONDO:0011376   Orphanet:228140
MONDO:0011705   Orphanet:538
MONDO:0012205   Orphanet:228169
MONDO:0014659   Orphanet:464724
MONDO:0015062   Orphanet:100075
MONDO:0015067   Orphanet:100080
MONDO:0015068   Orphanet:100081
MONDO:0015353   Orphanet:139536
MONDO:0019072   Orphanet:69665
MONDO:0019313   Orphanet:79452
MONDO:0019478   Orphanet:86893
MONDO:0019947   Orphanet:97238
MONDO:0024677   Orphanet:97279
MONDO:0100288   Orphanet:53540
MONDO:0700089   Orphanet:98810
```
I don't now if other subsets could present this problem as I checked only for Orphanet references.
Thank you in advance
Pedro Seoane

**Comment by nicolevasilevsky** [comment]
Hi @seoanezonjic Thanks for your ticket. Did you mean to say absence?

I'll take a look at this asap and will get back to you with any questions.

**Comment by seoanezonjic** [comment]
Hi @nicolevasilevsky 
Yes, I mean absence or missing attribute. Sorry for my misspelling.

**Comment by nicolevasilevsky** [comment]
Hi @seoanezonjic 
Orphanet:79452 is a equivalent xref on MONDO_0007919 'lymphatic malformation 1'. This mapping comes from [OMIM:153100](https://omim.org/entry/153100).

**Comment by nicolevasilevsky** [comment]
Hi @seoanezonjic I'm not sure I understand the question on this ticket, but maybe this will help clarify.
In Mondo, we add database cross references (dbxrefs) to terms that are either from external sources or asserted by us (Mondo curators). The dbxrefs have semantic annotations to note the relationship of the mapping to the term:
- MONDO:equivalentTo: This is interpreted strongly as an OWL equivalence axiom.
- MONDO:relatedTo: Used when a term is not equivalent but similar.
- MONDO:subClassOf: This is interpreted strongly as an OWL subclass of axiom.
- MONDO:superClassOf: This is interpreted strongly as an OWL superclass of axiom.

Read more about it here:
https://mondo.readthedocs.io/en/latest/editors-guide/f-entities/#axiom-annotations

Let me know if you'd like to discuss further. Thanks!

**Comment by seoanezonjic** [comment]
Hi @nicolevasilevsky 
I''ll illustrate my problem with a simplified version of example in first post:
```
id: MONDO:0019313
name: lymphatic malformation
def: "Primary lymphedema is caused by anatomic or functional defects in the lymphatic system, resulting in chronic swelling of body parts and lymphatic-system malformation." [PMID:22831870]
subset: ordo_disease {source="Orphanet:79452"}
xref: DOID:0050580 {source="MONDO:equivalentTo"}
xref: GARD:0007220 {source="MONDO:superClassof", source="Orphanet-shared"}
xref: ICD10:Q82.0 {source="ORDO:79452/attributed", source="ORDO:79452/ntbt", source="MONDO:equivalentTo", source="Orphanet:79452"}
xref: ICD9:757.0 {source="DOID:0050580"}
xref: OMIMPS:153100 {source="MONDO:cjm", source="MONDO:equivalentTo"}
xref: SCTID:254199006 {source="MONDO:equivalentTo"}
is_a: MONDO:0016229 {source="MONDO:Redundant", source="Orphanet:79452", source="Orphanet:79452/inferred"} ! genetic vascular anomaly
is_a: MONDO:0019175 {source="MONDOLEX:0019313", source="Orphanet:79452", source="Orphanet:79452/inferred"} ! primary lymphedema
```
In this record is clearly stated the relation between MONDO:0019313 and Orphanet:79452. But if I attend to xref: ID lines (not seeing the sources attributes) a direct relation `xref: Orphanet:79452` not exists :

```
xref: DOID:0050580 
xref: GARD:0007220 
xref: ICD10:Q82.0 
xref: ICD9:757.0 
xref: OMIMPS:153100 
xref: SCTID:254199006 
```
However, when checked the obo file for the attribute `subset: ordo_disease {source=} ` (as stated in my comment https://github.com/monarch-initiative/mondo/issues/4183#issuecomment-996214631), excepting the 19 listed records if the term has the `subset: ordo_disease {source=} ` line it has a `xref: Orphanet:N` line. I expect a constant behaviour, if a MONDO term is related with a Orphanet id, the term must have a `xref: Orphanet:N` line or if other attribute is used (for example  `subset: ordo_disease {source=}`) I need to know what exact attribute I have to check if the xref field not behave as expected. I think that the MONDO ilustrated here needs the line:
`xref: Orphanet:79452 {....}` 
If you say that the term no need this field, I would like to understand the reason of this (to me) weird use of the xref label to no perform the same misunderstanding in the future.
Thank you in advance
Pedro Seoane

**Comment by nicolevasilevsky** [comment]
Hi @seoanezonjic We're looking into this. What file are you looking at? Are you looking at the released mondo.obo file?
Thanks!

**Comment by seoanezonjic** [comment]
Hi @nicolevasilevsky 
I had this  problem with the obo file from http://purl.obolibrary.org/obo/mondo.obo at time of my first post (16 Dec 2021). I don't know if the current release has the same issue if you want I could check it.
Thanks!

**Comment by seoanezonjic** [comment]
Hi @nicolevasilevsky 
I had this  problem with the obo file from http://purl.obolibrary.org/obo/mondo.obo at time of my first post (16 Dec 2021). I don't know if the current release has the same issue if you want I could check it.
Thanks!

**Comment by matentzn** [comment]
@seoanezonjic While this may look confusing at first sight, 

```
subset: ordo_disease {source="Orphanet:79452"}
```

is not evidence for a mapping, merely historical provenance. This could indicate that once in the past, 

```
id: MONDO:0019313
name: lymphatic malformation
```

was mapped to `Orphanet:79452`, but it is certainly possible that we have moved the mapping to a different, more suitable term.

As you can see in mondo.obo,`Orphanet:79452` was determined to be a more specific term than `MONDO:0019313`, i.e. a "superclass" - later in the process:

```
id: MONDO:0019313
name: lymphatic malformation
...
xref: Orphanet:79452 {source="MONDO:superClassOf", source="DOID:0050580"}
```

In fact, it is mapped to a more specific class now:

```
[Term]
id: MONDO:0007919
name: lymphatic malformation 1
def: "Any hereditary lymphedema in which the cause of the disease is a mutation in the FLT4 gene." [MONDO:patterns/disease_series_by_gene]
.....
xref: Orphanet:79452 {source="MONDO:equivalentTo", source="OMIM:153100"}
```

This is important: in order to build a dictionary, you *should be using only the skos:exactMatch, NOT xrefs*!

```
property_value: exactMatch https://omim.org/phenotypicSeries/PS153100
```

Let me know if you have further questions.

**Comment by seoanezonjic** [comment]
Hi @matentzn 
I have to point several questions:
1) I have pointed the `subset: ordo_disease {source="Orphanet:79452"}` attribute because was the first line that has relation evidence between the mentioned Orphanet code and the mondo id. There are 4 other lines in my example that gives some kind of evidence of this connection.
2) The important point, in the current MONDO release there is the expected field `xref: Orphanet:79452 {source="MONDO:equivalentTo", source="DOID:0050580"} ` ! In my example, this line not exists.
3) Why use property_value and not xref? In other ontologies as GO or HPO, the xref field is used to connect to other nomenclatures and the property_value field not appears or it is no used is this way. Is specific this attribute use in MONDO ontology?
Thanks!

**Comment by matentzn** [comment]
@seoanezonjic thank you for your interest and good questions:

:-)

1. This "evidence", no matter how much of it there is, is still just provenance, i.e. coming from earlier states of Mondo. Even if it is confusing, you should ignore it. The only exception is if you think that from a medical perspective, we have mapped a term wrongly (i.e. you looked at the ORDO and Mondo concept, and think that medically, we made a mistake). 
2. Yes! I don't know why that is in your example - the http://purl.obolibrary.org/obo/mondo.obo is the one you should look at.
3. That is a really good question, and I could give you a very long answer to this. But long story cut short: xrefs have _unspecified precision_. That means that it has, in practice, been used to closely connect two entities even if they are only broadly or narrowly connected. We are making a huge push away from hasDbXref (`xref` in OBO) now towards skos, to force people that provide a mapping to explicitly state the precision (exact, narrow, broad, related, close, etc). For many use case, only exact mappings are useful - hence are push in this direction.

**Comment by nicolevasilevsky** [comment]
Hi @seoanezonjic I will close this ticket now, but this is subject is of interest us, so please feel free to open new issues if anything else is needed. Thanks for reporting this. Best,
Nicole
