### ISSUE TITLE
merge MONDO_0040679 'urothelial carcinoma' with TC carcinoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#419]
consider merge of MONDO_0040679 'urothelial carcinoma' with TC carcinoma (I think this is the ID: MONDO_0006451)

**Comment by pnrobinson** [comment]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0006451 is Thymic carcinoma, which is NOT a synonym.

It looks the the MONDO Thymus carcinoma part only partially reflects NCI
https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=20.02d&ns=ncit&code=C7569&key=n1452933576&b=1&n=null#

Probably this needs some work.
