### ISSUE TITLE
[Revise subclass] mitochondrial myopathy-cerebellar ataxia-pigmentary retinopathy syndrome

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#4190]
**Mondo term (ID and Label)**

mitochondrial myopathy-cerebellar ataxia-pigmentary retinopathy syndrome MONDO:0044714

**Suggested revision and reasons**

Should this have  "muscular dystrophy" MONDO:0020121 as a parent?

PMID:31463572 Bi-allelic loss-of-function variants in MSTO1 manifest clinically with a remarkably consistent phenotype of childhood-onset muscular dystrophy.....

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-6330-7526

**Comment by sabrinatoro** [comment]
> PMID:31463572 Bi-allelic loss-of-function variants in MSTO1 manifest clinically with a remarkably consistent phenotype of childhood-onset muscular dystrophy.....

To me, it means that this disease present the _phenotype_ 'muscular dystrophy' (HP:0003560), but I don't know whether it is enough to define this disease as a "muscular dystrophy" disease. 

@pnrobinson and @ahamosh : do you think "mitochondrial myopathy-cerebellar ataxia-pigmentary retinopathy syndrome" (MONDO:0044714) is a "muscular dystrophy" (MONDO:0020121)
Here is the OMIM entry: https://omim.org/entry/617675
Thanks!

**Comment by ahamosh** [comment]
This is a mitochondrial depletion syndrome causing myopathy, corticospinal tract and cerebellar involvement.  It is much more than a muscular dystrophy because of brain and other neurologic involvement.

**Comment by pnrobinson** [comment]
YMMV but I think that when most clinicians speak of muscular dystrophy they refer to diseases in which muscular dystrophy is the only (or primary) feature. I think this is what Ada is implying above?

**Comment by ahamosh** [comment]
I wouldn't characterize this as a "muscular dystrophy". Peter, who knew you were so hip?

**Comment by pnrobinson** [comment]
"hip": Ada, you must be thinking of somebody else 😄 but I appreciate the thought!

**Comment by ValWood** [comment]
ok!

**Comment by sabrinatoro** [comment]
Thank you @ahamosh and @pnrobinson for your quick response! 

@ValWood, I am closing this issue.
