### ISSUE TITLE
SOP : dbxrefs of obsolete classes when merging

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4196]
_[following Mondo QC call, Dec 17 2021]_

The merging/obsoleting documentation was updated and includes the following: 
- "The dbxrefs should stay with the obsoleted class and not be moved to the replacement term."
- "Retain all of the **database_cross_references** on the obsoleted term. Any annotations to MONDO:equivalentTo should be changed to MONDO:obsoleteEquivalent."

I am questioning why all the database-cross references should be retained on the obsoleted terms **when merging terms**. The whole reason for merging terms is because they represent the same concept, and therefore the database-cross references should be moved to the live term, except for the DBxref which has "MONDO:equivalentTo" to the same source in both the live and the obsolete term

1) Should we instead : "move all the DBxref to the live term BUT retain the DBxref on the obsoleted term when the DBxref is 1) MONDO:equivalentTo SourceX, 2) there is already a MONDO:equivalentTo SourceX on the live term."
The DBxref on the obsoleted term would then be changed to "MONDO:obsoleteEquivalent".

2) Some annotations (e.g. synonyms, or DBxref if question to 1. is yes) have their own DBxref/source. These DBxref/source might refer to an obsoleteEquivalent that stayed on the obsolete term. That is weird.

(I will add some screenshots)

**Comment by sabrinatoro** [comment]
Example: merging MONDO:0016891 into MONDO:0008013
On the live "MONDO:0008013" term: 
1) 2 Mondo:equivalentTo Orphanet:
MONDO:0008013 - dbxref = Orphanet:261112 {source="DOID:0060732", source="MONDO:equivalentTo", source="OMIM:158170"}
MONDO:0016891 - dbxref =  Orphanet:261929 {source="MONDO:equivalentTo"}
MONDO:0008013 - dbxref = Orphanet:261112 {source="DOID:0060732", source="MONDO:equivalentTo", source="OMIM:158170"}

![Screen Shot 2021-12-17 at 2 02 59 PM](https://user-images.githubusercontent.com/12737987/146613947-94a2e1a9-1707-4d2b-815d-8bee23a8f81d.png)

**-- > Orphanet:261929 should stay on (obsolete)MONDO:0016891 as {source="MONDO:obsoleteEquivalent"}**


2) On the live MONDO:0008013 : These synonyms and other dbXrefs refer to [Orphanet:261929] which has not been brought up to this term (isn't this weird?) 

![Screen Shot 2021-12-17 at 2 04 03 PM](https://user-images.githubusercontent.com/12737987/146614182-23d41af5-bf24-448a-95fa-a778f8a9e4d3.png)

![Screen Shot 2021-12-17 at 2 04 31 PM](https://user-images.githubusercontent.com/12737987/146614186-cf1f47c0-6c09-43f3-a676-ec202f5d1af5.png)

**Comment by matentzn** [comment]
Good question.

I think we were wrong in our call about this, but the question is even more complex, when you consider the opposite case (MONDO:0008013 gets obsoleted - what happens _then_ to all the xrefs?).

My suggestion, but needs to be ratified by @cmungall:

# ALT 1

1. *If the source id is obsolete* (i.e. in the case of a `Mondo:equivalentObsolete` xref on the Mondo ID _that is deprecated_), we change the xref to `Mondo:obsoleteEquivalentObsolete` but do _not_ move it.
2. *If the source id is live*, we move it to the new ID, but as `MONDO:equivalentTo`, not `MONDO:obsoleteEquivalent`. 
3. We drop the concept of `MONDO:obsoleteEquivalent` altogether.

We could also:

# ALT 2: Only what's LIVE matters

1. Move _all_ xrefs to the live class. If the source class is live its : MONDO:equivalentTo. If the source class is obsolete: Mondo:equivalentObsolete.
2. We could persist a _redundant_ xref `Mondo:obsoleteEquivalent` on the obsoleted MONDO class if the source concept is life, and an `obsoleteEquivalentObsolete` if the source concept is obsolete. This way, we never lose provenance. In other words, `Mondo:obsoleteEquivalent` and `Mondo:obsoleteEquivalentObsolete` are totally redundant - just there for provenance.

I think the second solution is cleaner and easier to understand and communicate. Also, it means much less work for you fixing stuff, as much stuff can be done automatically.

**Comment by nicolevasilevsky** [comment]
default - if it is a merge - things could move across, i.e., we should continue what we have been doing with owl toolsl merger.

**Comment by matentzn** [comment]
Lets discuss this again in a 1:1 :)

**Comment by nicolevasilevsky** [comment]
I think this can be closed? Please reopen if there are still questions
