### ISSUE TITLE
merge MONDO_0007324 chorea

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#420]
there is an comment on this class MONDO_0007324 chorea, says consider merge

maybe into it's parent MONDO_0001595 'choreatic disease'

**Comment by pnrobinson** [comment]
This seems reasonable.
A bigger problem is that

chorea -> huntington-disease like symptom -> dementia
thus chorea is a dementia which is not true.

I would suggest obsoleting the class "Huntington-disease like symptom"!

**Comment by nicolevasilevsky** [comment]
I can remove the superclass assertion to 'Huntington disease-like syndrome'. This is related to #https://github.com/monarch-initiative/mondo/issues/834

**Comment by nicolevasilevsky** [comment]
see [spreadsheet](https://docs.google.com/spreadsheets/d/1s-jaBDNbJmQtv38uPrXOy7yiKZxbYJ940mfZeUt-T8U/edit#gid=510128657)
