### ISSUE TITLE
MONDO:0007064, adenosine deaminase deficiency - review?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4200]
I am wondering about MONDO:0007064, adenosine deaminase deficiency, This term seems to encompass a lot of different concepts and it seems like these may need a split or some descriptive clarification if they are all equivalent. There are two main issues that I think are unclear at this point:

1. Name "adenosine deaminase deficiency" indicates the disease is primarily an enzyme deficiency, but [OMIM](https://omim.org/entry/102700) and OrphaNet x-refs both use names that emphasize the "severe combined immunodeficiency" aspect and then include "ADA deficiency" as a causative role. 

This is kind of picky, but there are other cases where the enzyme deficiency and the associated clinical presentation are differentiated, so it may be helpful to clarify the primary focus of this term on the disease presentation rather than the molecular/enzymatic cause? Or separate out the clinical presentation(s) as children if the main idea is the enzyme deficiency?

2. [OMIM 102700](https://omim.org/entry/102700) has the preferred and alternate names as follow: 
- severe combined immunodeficiency, autosomal recessive, T cell-negative, B cell-negative, NK cell-negative, due to adenosine deaminase deficiency 
- alternates:
  - SCID DUE TO ADA DEFICIENCY
  - ADA-SCID
  - SCID DUE TO ADA DEFICIENCY, EARLY-ONSET 
- Included entities:  
  - SCID DUE TO ADA DEFICIENCY, DELAYED ONSET 
  - SCID DUE TO ADA DEFICIENCY, LATE-ONSET
  - ADENOSINE DEAMINASE DEFICIENCY, PARTIAL
  - PARTIAL ADA DEFICIENCY

This suggests the OMIM entry has two presentations: early onset ('classic') SCID due to ADA deficiency and late-onset SCID due to partial ADA deficiency (thus suggesting the complete deficiency is associate with the early onset?) But I'm not sure if the Late onset is inherently equivalent to the partial enzyme deficiency 

@ahamosh Can you weigh in on this? MeSH C531816 lumps the partial deficiency and late onset, and thus so does UMLS for all of the 'included' terms on this OMIM entry. But is a partial deficiency always/mostly associated with a later onset enough to justify that lumping?

**Comment by nicolevasilevsky** [comment]
this may be related to https://github.com/monarch-initiative/mondo/discussions/4304

**Comment by nicolevasilevsky** [comment]
Talking to Ada:
SCID due to partial ADA deficiency is included because it's not lethal immediately, it comes on later in life (ie they are not newborns). (Newborns need a bone marrow transplant.)

The late onset phenotype is still an immunodeficiency because you don't have enough ADA.

Ada does not recommend separating these. Mondo will change the label to use OMIM label.

**Comment by nicolevasilevsky** [comment]
> But is a partial deficiency always/mostly associated with a later onset enough to justify that lumping?

Yes. (from Ada)
