### ISSUE TITLE
MONDO:0001569 acoustic neuroma and MONDO:0016754  vestibular schwannoma[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4201]
**Mondo term (ID and Label)**
MONDO:0016754  vestibular schwannoma

**Reason for deprecation**
this is a synonym for Acoustic neuroma (according to SNOMED CT : 126949007)

**Term to be merged with**
MONDO:0001569 acoustic neuroma

(also MONDO:0002553 "cerebellopontine angle tumor" says Vestibular schwannoma is a representative example type of tumor, but it doesn't appear to be a child of this concept)
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0016754 MONDO:0001569 -o -f obo mondo-edit.obo
