### ISSUE TITLE
MONDO:0003127 embryoma[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4206]
**Mondo term (ID and Label)**
MONDO:0003127 embryoma

**Reason for deprecation**
NCIT uses these terms as synonyms on C8997, both map to C0936282 in UMLS

**Term to be merged with**
MONDO:0005565 blastoma
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
There is an editor note on embryoma:
 consider merging with parent class. Wikipedia says: It is not a precise term, and it is not commonly used in modern medical literature. Embryomas have been defined as: "Adult neoplasms expressing one or more embryo-exclusive genes"
