### ISSUE TITLE
merge MONDO_0009730 nephrosialidosis with MONDO_0009738 sialidosis type 2

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#421]
consider merge of MONDO_0009730 nephrosialidosis with MONDO_0009738 sialidosis type 2

**Comment by pnrobinson** [comment]
MONDO_0009730 seems to come from
https://omim.org/entry/256150
The issue is that this OMIM entry is "legacy" and it is no longer possible to actually know what disease the publications referred to. It is not a big problem to merge it though.
