### ISSUE TITLE
merge MONDO_0004818 'benign neurilemmoma'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#422]
there is a comment on MONDO_0004818 'benign neurilemmoma' to consider a merge, but the class to be merged into is not specified.

Note, there is not a text def.

Maybe it is meant to be merged with the parent: MONDO_0002546 schwannoma
def: A benign, usually encapsulated slow growing tumor composed of Schwann cells. It affects peripheral and cranial nerves. It recurs infrequently and only rare cases associated with malignant transformation have been reported.

**Comment by pnrobinson** [comment]
This suggestion jibes with NCI
https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&version=20.02d&code=C3269&ns=ncit&type=synonym&key=n494182563&b=1&n=0&vse=null
