### ISSUE TITLE
MONDO:0018115 Epidermal nevus syndrome(s) [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4222]
**Mondo term (ID and Label)**
MONDO:0018115 Epidermal nevus syndrome(s)

**Suggested revision and reasons**
I think this term (or at least the preferred name) should be used for a grouping term to cover many concepts. MedGen mapping was running into trouble with this Mondo ID and MONDO:0008097 (linear nevus sebaceous syndrome) possibly because of the "formerly" name of ENS from OMIM, but this led me to do a little more digging and realized there are a lot of entries in UMLS, MeSH and OrphaNet that aren't really in agreement. I'm hoping the community can review and each contributing database can amend their terms as needed.
According to NORD https://rarediseases.org/rare-diseases/epidermal-nevus-syndromes/ and DermNetNZ https://dermnetnz.org/topics/epidermal-naevus-syndromes, ENS is a whole class of disorders, and LNSS/SCHIMMELPENNING-FEUERSTEIN-MIMS SYNDROME is one subtype. 

And the X-refs for the Mondo concept left me with more questions than clarity, unfortunately, these are the 'breadcrumbs' from trying to follow the X-refs and the subsequent cross-referenced source(s):

MONDO:0018115; epidermal nevus syndrome
Mondo X-ref | Source Name | X-ref mapping
-- | -- | -- 
SCTID:239112008 | Epidermal nevus syndrome | UMLS maps this SNOMED code to C4552097 (Nevus Sebaceous of Jadassohn, which includes the X-ref for OMIM: 163200; but UMLS maps multiple SNOMED codes to this same CUI, which seems incorrect.)
Orphanet:35125 | Epidermal nevus syndrome (AKA epidermal hamartoma syndrome/ Orpha maps to C0334082 | UMLS C0334082: **"NEVUS, EPIDERMAL (disorder)"**, Orphanet:35125 also points to MeSH:C536114  (the following term was not found in MeSH: C536114.) and, [MeSH D054000](https://www.ncbi.nlm.nih.gov/mesh/?term=D054000) **Nevus, Sebaceous of Jadassohn**
    
But this MeSH term is on UMLS CUI: C4552097 as well as C3179502, C0265329, C0362030, and C0473574 so this MeSH entry may be too broad to be informative in defining any particular term/concept unless ONLY the preferred name is used.)

@ana-rath-orphanet : can the OrphaNet team review the name/cross-reference information on Orphanet:35125 ?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by kanems** [comment]
Also, please check the spelling on MONDO:0008097 "linear nevus sebaceus syndrome" should it be "Linear nevus sebace_o_us syndrome" ?

**Comment by nicolevasilevsky** [comment]
@sabrinatoro are you working on this? If so, I'll reassign it to you. Or I'm happy to work on it too.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky, so far, I only updated the typo in the label. I haven't gone deep down into this issue yet. 
I was planning to do it next month (since it is due for April), but if you want to do it earlier, please go ahead :-)

**Comment by nicolevasilevsky** [comment]
I drew this out below:

![image](https://user-images.githubusercontent.com/6722114/159783045-6a39551c-9c57-42fe-acf1-1f6b28cfe28e.png)

**Comment by nicolevasilevsky** [comment]
@kanems I'm not sure what the specific question is for Mondo? Is the question to ask the Orphanet team to review their mappings? I can send an email to them if so.
Thanks!

**Comment by kanems** [comment]
Yes, if Orphanet can be contacted to weigh in, that would be great.
And I am still concerned that this name is used for a lower level concept in Mondo when other groups/authors indicate this should be a broader, grouping term.
From NORD’s page:
>“The term “epidermal nevus syndrome” has generated significant controversy and confusion in the medical literature. Originally, the term was used to denote a disorder that was actually several different disorders erroneously grouped together. In the recent past, the term was used to denote a specific disorder now known as Schimmelpenning syndrome. However, the term epidermal nevus syndrome could be correctly applied to several different disorders. Therefore, the umbrella term “epidermal nevus syndromes” now represents a group of distinct disorders that have in common the presence of one of the various types of epidermal nevi. However, there is so far no general agreement how to classify the types of this diverse group of disorders, adding to the confusion within the medical literature. These disorders are quite different from one another and are not “variants” of each other as is sometimes mistakenly stated in the medical literature. In the future, as the genetic molecular basis of these disorders is better understood, the classification may change or expand. This report follows the classification from a review by Happle (J Am Acad Dermatol 2010).”  <
https://pubmed.ncbi.nlm.nih.gov/20542174/ (part I) and https://pubmed.ncbi.nlm.nih.gov/20542175/ (Part II)  (Happle is the author of both the NORD entry and the reviews, so

This page from New Zealand has a different author, also last updated in 2010 https://dermnetnz.org/topics/epidermal-naevus-syndromes  But this page also infers this is not a single specific entity : “ Epidermal naevus syndromes refer to the co-existence of a keratinocytic epidermal naevus<https://dermnetnz.org/topics/epidermal-naevi/> or an organoid naevus with other abnormalities in the skin and other organs. They are sometimes called systematised epidermal naevi. They reflect mosaicism<https://dermnetnz.org/topics/cutaneous-mosaicism/>, in which there are two distinct cell lines with different genetics and are due to postzygotic mutation. The epidermal naevus syndromes usually arise sporadically, with the exception of CHILD syndrome, which is familial. Several authors have commented that the term 'epidermal naevus syndrome' is outdated now that the genetic causes are known for many of the disorders.”

All this said, I am not a dermatologist so I don’t know what the standard is in that field. Whatever Mondo decide to do with these, MedGen will report.

**Comment by nicolevasilevsky** [comment]
Emailed David at Orphanet on 04/20/22

**Comment by nicolevasilevsky** [comment]
Hi @kanems 
We haven't heard back from Orphanet. I see in the latest version of Orphanet, they have epidermal nevus syndrome as a child of disease (see [here](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_35125).

I propose we make it a child of Mondo 'syndromic disorder' and I can link to this link, so people are aware of the controversy around this term?

Does that work?

Thanks!

**Comment by kanems** [comment]
That sounds like a good solution. Thanks!

From: Nicole Vasilevsky ***@***.***>
Sent: Tuesday, May 3, 2022 9:20 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Kane, Megan (NIH/NLM/NCBI) [C] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] MONDO:0018115 Epidermal nevus syndrome(s) [Revise subclass] (Issue #4222)


Hi @kanems<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkanems&data=05%7C01%7Cmegan.kane%40nih.gov%7C474954a61dba487e953408da2d6c26c9%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637872239784548745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wExErFvFOuHxNwGYptluUMYFaf6lvvfdbTqYJ%2BwjayY%3D&reserved=0>
We haven't heard back from Orphanet. I see in the latest version of Orphanet, they have epidermal nevus syndrome as a child of disease (see here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ebi.ac.uk%2Fols%2Fontologies%2Fordo%2Fterms%3Firi%3Dhttp%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_35125&data=05%7C01%7Cmegan.kane%40nih.gov%7C474954a61dba487e953408da2d6c26c9%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637872239784704545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uXlCLdD0LTEdFKooi4Z4J3BWuZj9Vv1c3E9kmRs3FQY%3D&reserved=0>.

I propose we make it a child of Mondo 'syndromic disorder' and I can link to this link, so people are aware of the controversy around this term?

Does that work?

Thanks!

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmonarch-initiative%2Fmondo%2Fissues%2F4222%23issuecomment-1116849001&data=05%7C01%7Cmegan.kane%40nih.gov%7C474954a61dba487e953408da2d6c26c9%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637872239784704545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VP4suWZnmDYmG4sO2f3sACwXv9prLjmX2OiDqxXXz%2B8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ6KOUV3N57BSZ4DFGMS4NTVIHGCLANCNFSM5K2ZQDVQ&data=05%7C01%7Cmegan.kane%40nih.gov%7C474954a61dba487e953408da2d6c26c9%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637872239784704545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2w7cHR5kN2EnlQ2PKTXICOYeYKWm9LmlQInO1j4fC9o%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
