### ISSUE TITLE
merge MONDO_0004819 'indolent myeloma'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#423]
there is a note to consider merging MONDO_0004819 'indolent myeloma', but the class to be merged with is not specified.

There is not a text def for indolent myeloma.

Maybe it is meant to be merged with MONDO_0009693 'plasma cell myeloma'.

**Comment by pnrobinson** [comment]
Not sure these are exact synonyms (https://www.ncbi.nlm.nih.gov/pubmed/12057049) but I doubt that this is the current terminology. Can we get this from NCIT?

**Comment by nicolevasilevsky** [comment]
Yeah, I am not sure what this was meant to be merged with (when that comment was written). I'll rename to 'Indolent Plasma Cell Myeloma' (the NCIt preferred name) and remove that comment.
