### ISSUE TITLE
MONDO:0100244  paroxysmal nocturnal hemoglobinuria (vs. acquired form: MONDO:0100245)

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4232]
**Mondo term (ID and Label):**
MONDO:0100245, acquired paroxysmal nocturnal hemoglobinuria seems to have X-refs that belong to the parent concept; and maybe some other X-refs need to be reviewed and maybe moved?

**Xref that should be fixed (ID and label):**
SCTID 1963002
HP:0004818

Also ORPHA:447 appears to be equivalent to the OMIMPS:300818. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by sabrinatoro** [comment]
> Also ORPHA:447 appears to be equivalent to the OMIMPS:300818.
I don't think ORPHA:447 is equivalent to OMIMPS:300818.
Definition of ORPHA:447 suggests that it is an acquired disorder. 
OMIMPS:300818 refers to a phenotypic series of inherited disorders.

**Comment by sabrinatoro** [comment]
Here is the source of the confusion: 
OMIMPS:300818 refers to a phenotypic series. In this series, the terms (OMIM:300818 and OMIM:615399) are actually "susceptibility terms" (though "susceptibility" is not in name). Therefore variations in the genes associated with these entries conferred _susceptibility_ to the disease, and therefore we cannot say that this disease is "inherited". 

@ahamosh : 
Does OMIMPS:300818 represent the "susceptibility to Paroxysmal nocturnal hemoglobinuria"? 
or does it represent "Paroxysmal nocturnal hemoglobinuria", and  OMIM:300818 and OMIM:615399 are "susceptibility" to that disease? 
Thanks!

**Comment by sabrinatoro** [comment]
@ahamosh : could you take a look at the previous comment and give us your opinion, please? Thank you!

**Comment by ahamosh** [comment]
300818 is always acquired as a somatic mutation in PIGA.  615399 is an autosomal dominant susceptibility where it looks like a second hit to the other PIGT allele is required for manifestation of disease.  Both are paroxysmal nocturnal hemoglobinuria.  Neither disease is inherited per se.  Does this make sense?

**Comment by sabrinatoro** [comment]
Thank you @ahamosh ! Yes, it make sense, thank you! 
I will update the ontology accordingly.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I cannot find evidence that we need an "acquired" versus "inherited" version of the disease. I would say that the best thing to do would be to merge these terms.
However, "paroxysmal nocturnal hemoglobinuria" was obsoleted in order to create these more specific 'acquired' and 'inherited' terms. I cannot find a GH issue referring to this splitting.
Can you please advise?

**Comment by nicolevasilevsky** [comment]
I can't find a ticket as to why these terms were split either. Based on this ticket, merging these terms makes sense to me.

**Comment by sabrinatoro** [comment]
to do: 
acquired paroxysmal nocturnal hemoglobinuria (MONDO:0100245) and inherited paroxysmal nocturnal hemoglobinuria (MONDO:0100243) should be merged to paroxysmal nocturnal hemoglobinuria (MONDO:0100244)

**Comment by sabrinatoro** [comment]
There is a lot of reasoning and QC behind terms with relation to a gene and terms with OMIM/OMIMPS x-ref. 
This issue requires #4675 to be closed before it can be resolved. 

FYI @nicolevasilevsky: I am setting this issue for the next release (hopefully we can get #4675 by then), and I will update the time of obsoletion for these terms merging.

**Comment by sabrinatoro** [comment]
closed with https://github.com/monarch-initiative/mondo/pull/4800#pullrequestreview-950566683
