### ISSUE TITLE
merge MONDO_0016747 'primary melanoma of the central nervous system' with meningeal melanoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#424]
consider merging MONDO_0016747 'primary melanoma of the central nervous system' with meningeal melanoma.

Note - there is not a class in MONDO named meningeal melanoma, there is MONDO_0004512 'meningeal melanomatosis' (def: A meningeal melanoma with secondary diffuse meningeal spread. (WHO)) and there is MONDO_0003222 'central nervous system melanocytic neoplasm' (def: A primary tumor of the central nervous system that arises from leptomeningeal melanocytes. It may present as a diffuse proliferative leptomeningeal process (often as a component of the neurocutaneous melanosis complex) or as a distinct mass lesion.)

**Comment by pnrobinson** [comment]
Primary melanoma of the CNS does not have "secondary diffuse meningeal spread", at least not provably so (https://www.ncbi.nlm.nih.gov/pubmed/20627582). I am not sure if these are truly exact synonyms. Can we ask somebody at NCI?

**Comment by nicolevasilevsky** [comment]
from NCIt:

A primary CNS melanoma may arise from either the meninges or other anatomical structures in the CNS (e.g. primary cerebral melanoma); therefore the terms ‘primary CNS melanoma’ and ‘meningeal melanoma’ are not synonyms. Additionally, primary meningeal melanoma (typically a solitary lesion) is not synonymous with meningeal melanomatosis (a typically multifocal, metastatic lesion).
