### ISSUE TITLE
unexpected changes are introduced when editing the ontology

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4249]
When I edit Mondo, some changes (which I didn't make) are also introduced:
src/ontology/mondo-edit.properties
![Screen Shot 2022-01-04 at 4 57 58 PM](https://user-images.githubusercontent.com/12737987/148144096-fbe35a88-ced8-489d-a6f0-8e7ee7459825.png)

**Comment by sabrinatoro** [comment]
It appears that a "mondo-edit.properties" file is created every time I make an edit. 
I might be a problem with my setting since Nicole hasn't seen this issue when editing.

**Comment by nicolevasilevsky** [comment]
try to determine when it is introduced during the editing process

**Comment by sabrinatoro** [comment]
This file is created every time I make any change in protege and then save it. 
The type of change I make does not seem to make a difference.

**Comment by matentzn** [comment]
This is I believe created by the installation of a sparql plugin. Which are the last 3 plugins you installed in Protege?

**Comment by sabrinatoro** [comment]
@matentzn 
I don't understand what you are asking. 
Originally, I added the ELK plugin. 
I have not added anything (that I know of - there are always new things to add every time I open protege) since the original installation.
Where can I see what plugins are installed?

**Comment by marijane** [comment]
@sabrinatoro You can see what plugins are installed in the Plugins tab of the Preferences pane. Many of these get installed by default.

The culprit you're looking for is the Ontop OBDA Protege plugin, which is a repeat offender when it comes to generating extra files on save, I recall both @nicolevasilevsky and I ran into this in the past when we were working on the contributor roles ontology, and she's probably already removed it from her installation, which would explain why she can't reproduce it.

Uninstalling Protege plugins involves removing the plugin's .jar file from the plugins folder in your Protege installation (how to do this depends on whether you are on a Windows machine or a Mac). But you can also work around the problem by adding the .properties file to your .gitignore.

**Comment by sabrinatoro** [comment]
Thank you so much @marijane ! 
I indeed had the "Ontop OBDA Protege plugin". I removed it and the issue was resolved. Thank you! 

Note: the name of the .jar was something like 
"it_unibz_inf_ontop..." (I should have copied the name before removing it)
@nicolevasilevsky @matentzn
