### ISSUE TITLE
merge MONDO_0000844 'spondyloepimetaphyseal dysplasia' with MONDO:0016761 spondyloepiphyseal dysplasia and spondyloepimetaphyseal dysplasia

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#425]
consider merging MONDO_0000844 'spondyloepimetaphyseal dysplasia' with MONDO:0016761 spondyloepiphyseal dysplasia and spondyloepimetaphyseal dysplasia

From comments: Obsolete in ORDO, consider merge with MONDO:0016761 spondyloepiphyseal dysplasia and spondyloepimetaphyseal dysplasia

**Comment by pnrobinson** [comment]
This: MONDO:0016761 'spondyloepiphyseal dysplasia and spondyloepimetaphyseal dysplasia' seems to be a suboptimal label.
I would suggest that we really should base our labels on the nosology of the skeletal dysplasia working group. There is a new edition here.
https://www.ncbi.nlm.nih.gov/pubmed/31633310
The term they use is spondylo-epi-(meta)-physeal dysplasia
