### ISSUE TITLE
MONDO:0020347 and MONDO:0007691 [Merge? or fix x-ref?]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4252]
**Mondo term (ID and Label)**
MONDO:0020347 acute inflammatory demyelinating polyradiculoneuropathy

**Reason for deprecation**
Orphanet:98916 Acute inflammatory demyelinating polyradiculoneuropathy maps 1:1 with OMIM: 139393 GUILLAIN-BARRE SYNDROME, FAMILIAL; GBS

The SNOMED code on MONDO:0007691 'Guillain-Barre syndrome, familial' is SCTID:716723000, PT "Acute inflammatory demyelinating polyradiculoneuropathy"

OMIM 139393 has Preferred name of GUILLAIN-BARRE SYNDROME, FAMILIAL; GBS and Alternative titles; symbols of POLYNEUROPATHY, INFLAMMATORY DEMYELINATING, ACUTE; AIDP

- [x] (Also please update the abbreviation on MONDO:0007691 Guillain-Barre syndrome, familial: remove "CIDP" since that refers to the Chronic form, which is an "included" but separate concept on the OMIM entry, as discussed in ticket #2808) https://github.com/monarch-initiative/mondo/issues/2808 

**Term to be merged with**
MONDO:0007691 Guillain-Barre syndrome, familial  ?? Not sure if this is a merge or X-ref fix, see notes below.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Additional notes**
I imagine that AIDP could present without a genetic predisposition, so maybe this is an X-ref remapping rather than merge, but at a minimum, the Orphanet X-refs suggest it should be mapped with the OMIM record in Mondo.  The mapping of NCIT entries in UMLS seems to be at odds with NCI's own mapping of the concept to UMLS, so I cannot figure out from those hierarchies which concept goes where... 
C116926 and C26790 both map to UMLS's Acute Infective Polyneuritis, UMLS CUI: C3542501 (depending on whether you are looking at the NCIT browser or UMLS browser). 
UMLS has split the OMIM records across multiple terms, Guillain-Barre Syndrome, Familial C4083008 and Acute Inflammatory Demyelinating Polyneuropathy C4551910 are the ones relevant to this ticket.  So maybe it's just a matter of cleaning up Orphanet 98916 mapping in Mondo (or asking if Orpha wants to review their entry for AIDP)?

**Comment by nicolevasilevsky** [comment]
Adding to Feb release to review this ticket and decide the best course of action. If we decide to merge, we'll need to add an obs tag to it and leave it open for two months.

**Comment by nicolevasilevsky** [comment]
> Orphanet:98916 Acute inflammatory demyelinating polyradiculoneuropathy maps 1:1 with OMIM: 139393 GUILLAIN-BARRE SYNDROME, FAMILIAL; GBS

Orphanet:98916 does not have a 1:1 mapping with [OMIM:139393](https://omim.org/entry/139393). It is BTNT (ORPHA code's Broader Term maps to a Narrower Term).

**Comment by nicolevasilevsky** [comment]
I don't think these two terms should be merged, they seem like different classes to me.

**Comment by nicolevasilevsky** [comment]
I will close this when I merge the PR but please feel free to reopen if more discussion is needed, thanks!
