### ISSUE TITLE
tagging xrefs for orphanet

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#4258]
MedGen has been treating any xref tagged as 
<oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Orphanet:137888</oboInOwl:hasDbXref> as a valid DbXref for the MondoID. 
In the latest release, we found this tagging present on children of the parent term as well as the parent, e.g. on
MONDO_0000107 and its children
MONDO_0011234
MONDO_0013013
MONDO_0013845
MONDO_0014312

Is this going to continue? 
MedGen, GTR, and ClinVar expect an identifier from Orphanet to be valid for only one concept, i.e. a submission identified as Orphanet:137888 should be treated as a submission for MONDO_0000107. 

We plan to add coding to ignore any xref for Orphanet_id that is the same as the xref for a parent concept, but wonder if the tagging on these could be changed , e.g. from <oboInOwl:hasDbXref> to something like 
<oboInOwl:hasRelatedDbXref>, if that would be clearer for all.

**Comment by nicolevasilevsky** [comment]
Hi @maglott 
Orphanet is a MONDO:equivalentTo on the parent class and MONDO:subClassOf on the children terms, so this is not meant to be interpreted as them all being equivalent.

There are a lot of cases like this.

I'm not sure how to best address this, but I'll bring this up with @cmungall and @matentzn. Nico is currently out of office though, so it may be a few weeks before we're able to address this. I'll follow up with more questions if needed, thanks!

**Comment by maglott** [comment]
Thanks, Nicole. When I looked at the XML that is what I realized we should have been doing; we will fix our data integration steps to make certain we import as equivalent only for MONDO:equivalentTo.  But I have to say it still seems easy to interpret that hasDbXref  belongs to the MondoID

**Comment by nicolevasilevsky** [comment]
Yes, I see what you mean.

It is done this way because we wanted to capture all the dxrefs from other sources, hence we added the source annotations (equiv, subclassOf, etc.) I think most of us interpret dbxref to mean equivalent but it's not always the case.

Is there any other action needed or can I close this?

PS - Happy new year!

**Comment by maglott** [comment]
Happy new year to you, too!
As far as NCBI is concerned, we will deal with this.  Up to you if you want to make it more explicit in the tag name whether the dbxref is equivalent or related.

**Comment by nicolevasilevsky** [comment]
Ok! I'll discuss it with Chris and Nico. :)

**Comment by maglott** [comment]
@nicolevasilevsky , I guess you can close this.  Based on Nico's comment on https://github.com/monarch-initiative/mondo/issues/4183,  we are looking into using skos instead.

**Comment by nicolevasilevsky** [comment]
Ok, thanks @maglott!
