### ISSUE TITLE
MONDO:0006928 and MONDO:0100450 [Revise]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4259]
**Mondo term (ID and Label)**
MONDO:0006928 proliferative vitreoretinopathy
(and parent term MONDO:0100450 CAPN5 vitreoretinopathy)

**Suggested revision and reasons**
OMIM 193235 seems to be equivalent with the CAPN5 vitreoretinopathy term, and right now that parent has only one child, so it seems like these should merge, but I think perhaps my merge request https://github.com/monarch-initiative/mondo/issues/3110 might have relied too heavily upon UMLS' mapping of terms. Upon review, I think there are really two concepts here but the terms as they exist seem muddied: 
-a Phenotype of proliferative vitreoretinopathy
-a Clinical disorder that presents with proliferative vitreoretinopathy, inherited in an AD fashion due to mutations in CAPN5. (ADNIV, VNRI, CAPN5-VR...)

770791000 SNOMED CT (http://purl.bioontology.org/ontology/SNOMEDCT/770791000 , _Autosomal dominant neovascular inflammatory vitreoretinopathy_) definition is "A rare genetic vitreoretinal degeneration characterised by a slowly progressive vitreoretinopathy with onset during the second or third decade of life. The disease initially presents as autoimmune uveitis with reduction in the b-wave on electroretinography, and progresses with development of photoreceptor degeneration, vitreous haemorrhage, cystoid macular oedema, retinal neovascularisation, intraocular fibrosis, secondary glaucoma, and retinal detachment leading to phthisis and complete blindness. Caused by heterozygous mutation in the CAPN5 gene on chromosome 11q14." So this looks like it belongs with OMIM 193235 (and thus Orpha 329211 goes here as well, it's 1:1 with the OMIM entry) The SNOMED code is on Autosomal dominant neovascular inflammatory vitreoretinopathy UMLS CUI: C4721549;
 Also DOID 9719 www.ontobee.org/ontology/DOID?iri=http://purl.obolibrary.org/obo/DOID_9719 appears to be consistent with the mendelian AD disease.

There is SNOMED CT for _proliferative vitreoretinopathy:_ http://purl.bioontology.org/ontology/SNOMEDCT/232016005 (SNOMED term has children of anterior and posterior prolif. vitreoretinopathy) , This name maps to UMLS C0242852  which merges multiple concepts
MESHD018630 appears to be a more general description of proliferative vitreoretinopathy https://www.ncbi.nlm.nih.gov/mesh/?term=D018630

EFO 1001129  seems to span both concepts.

So perhaps proliferative vitreoretinopathy as a phenotype description (agnostic of underlying genetic or other causes) should be the parent concept (with the x-refs as outlined above) and then the CAPN5 vitreoretinopathy term can be the child term. And it seems the remaining x-refs for Autosomal dominant neovascular inflammatory vitreoretinopathy concepts described above could/should be moved to the CAPN5 term? Unless the ClinGen panel reports there are Autosomal recessive forms for vitreoretinopathy due to CAPN5 variation? But the definition provided on MONDO:0100450 is that the disorder is Autosomal dominant, so maybe these _are_ a merge until there is clinical evidence to support an AR form of the disease?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
emailed Jenny Goldstein on 02/05/22

**Comment by nicolevasilevsky** [comment]
sent f/u email on 04/20/22

**Comment by nicolevasilevsky** [comment]
Jenny emailed on 05/04/22 and said she'd get back to us asap.

**Comment by nicolevasilevsky** [comment]
emailed 07/27/22

**Comment by nicolevasilevsky** [comment]
Hi @kanems I am reviewing this request and I think we should proceed with your suggestion (hopefully I am interpreting this correctly):

- [ ] merge [proliferative vitreoretinopathy](http://purl.obolibrary.org/obo/MONDO_0006928) and [CAPN5-related vitreoretinopathy](http://purl.obolibrary.org/obo/MONDO_0100450) (I agree that these seem to be equivalent
- [ ] create new parent class that is a generic 'proliferative vitreoretinopathy' term.

We'll keep MONDO:0100450 'CAPN5-related vitreoretinopathy' because that is being used by ClinGen (cc @jennygoldstein )

Feedback welcome! Thanks for your patience with this

**Comment by sabrinatoro** [comment]
> create new parent class that is a generic 'proliferative vitreoretinopathy' term.
@nicolevasilevsky what would this generic term be a parent of CAPN5-related vitreoretinopathy? I don't see other children for this potential new parent term.

**Comment by nicolevasilevsky** [comment]
> @nicolevasilevsky what would this generic term be a parent of CAPN5-related vitreoretinopathy? I don't see other children for this potential new parent term.

yes

**Comment by sabrinatoro** [comment]
@nicolevasilevsky : 
I cannot find good evidence to create a parent term called  "vitreoretinopathy".
All I can find in the literature is "Proliferative vitreoretinopathy" (PVR) which is a major complication of rhegmatogenous retinal detachment (RRD).
"proliferative vitreoretinopathy" was in Mondo and was merged (this issue). 
It is unclear that the other "vitreoretinopathy" terms (exudative vitreoretinopathy) can be grouped under a general "vitreoretinopathy". Therefore, if we are created a new parent term:
1) what would its definition be
2) would "exudative vitreoretinopathy" be included under this parent term? 
Thank you!

**Comment by nicolevasilevsky** [comment]
My understanding is the suggestion was to create a generic class 'proliferative vitreoretinopathy' and [CAPN5-related vitreoretinopathy](http://purl.obolibrary.org/obo/MONDO_0100450) would be a child.

looks like vitreoretinopathy is a phenotype in HPO: https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0007773

**Comment by nicolevasilevsky** [comment]
as @kanems mentioned above, it looks like some of the other terminologies have a more generic proliferative vitreoretinopathy class that could be a parent of [CAPN5-related vitreoretinopathy](http://purl.obolibrary.org/obo/MONDO_0100450) would be a child.
