### ISSUE TITLE
merge MONDO_0000156 trigonocephaly with MONDO_0018065 isolated trigonocephaly

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#427]
consider merging MONDO_0018065 isolated trigonocephaly with parent class, MONDO_0000156 trigonocephaly

**Comment by pnrobinson** [comment]
debatable if this is a disease entity as defined. Cross-ref the HPO term.

**Comment by annieolry** [comment]
ORPHA:2983 Isolated trigonocephaly is an ORPHA code recognised and asked by ERN-CRANIO for coding patients in HIS in Europe. I would keep it

**Comment by nicolevasilevsky** [comment]
@pnrobinson MONDO_0000156 trigonocephaly has the superclass: 'disease has major feature' some Trigonocephaly

@annie thanks for your feedback, we'll keep the term. I removed the comment that mentioned considering merging with parent.
