### ISSUE TITLE
"thrombocytopenia-absent radius syndrome" should not be a "syndrome caused by partial chromosomal deletion"

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4273]
Based on https://www.omim.org/entry/274000 :
Albers et al. (2012) reported that 51 of 55 cases of TAR syndrome had a 200-kb deletion on 1q21 while 2 had a truncation (605313.0004) or frameshift (605313.0003) (null) mutation in the RBM8A gene on 1 allele.

While in most cases, "thrombocytopenia-absent radius syndrome" is due to a partial chromosomal deletion, it is not in all cases. 
Therefore I believe that this term should not be a child of  "syndrome caused by partial chromosomal deletion". 
(@nicolevasilevsky, do you agree?) 

addresses #3664

**Comment by nicolevasilevsky** [comment]
Yes!
