### ISSUE TITLE
MONDO:0011692, basal ganglia calcification, idiopathic, 2

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4277]
**Mondo term (ID and Label):**
MONDO:0011692, basal ganglia calcification, idiopathic, 2

**Xref that should be fixed (ID and label):**
OMIM:606656 (MONDO:equivalentTo) (This should be obsoleted?)
 Per OMIM:
^ 606656 MOVED TO 213600

ORPHA:1980 points to multiple OMIM numbers, perhaps this term should be remapped to the parent concept "Bilateral striopallidodentate calcinosis"

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
MESH:C537657 (MONDO:equivalentTo)
UMLS:C1847731 (OMIM:606656)
are both still valid, but UMLS CUI only cites the MeSH entry now. (Since OMIM's entry was incorporated into 213600 on October 14, 2019, it seems UMLS and MeSH will maintain this record.)

**Comment by nicolevasilevsky** [comment]
If OMIM merged these, we should follow suit. Merge:
MONDO:0011692 with MONDO:0024538
