### ISSUE TITLE
merge MONDO_0007600 'primary Fanconi syndrome' with MONDO_0001083 'Fanconi syndrome'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#428]
consider merge of MONDO_0007600 'primary Fanconi syndrome' with parent MONDO_0001083 'Fanconi syndrome'

**Comment by pnrobinson** [comment]
I think it would be better to use the OMIM name for Fanconi syndrome: Fanconi renotubular syndrome (note this has subtypes). This will ensure that people do not get it mixed up with Fanconi anemia.

**Comment by annieolry** [comment]
Secondary forms of Fanconi syndrome also exist. So Fanconi syndrome and primary fanconi syndrome are not equivalent. Depending on the willingness to represent secondary forms and/or to merge etiologies of this clinical syndrome, it could be preferable to keep only primary form or keep the clinical syndrome with both forms (primary and secondary).

**Comment by nicolevasilevsky** [comment]
thanks for the feedback @pnrobinson and @annieolry 

I renamed MONDO_0001083 'Fanconi syndrome' and removed the comment on MONDO_0007600 'primary Fanconi syndrome'  because it sounds like we don't want to obsolete that term.
