### ISSUE TITLE
[Merge] syndactyly type 2 into synpolydactyly

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4285]
**Mondo term (ID and Label)**
syndactyly type 2 (MONDO:0019683)

**Reason for deprecation**
These terms seem to represent the same disease. 
Actually, syndactyly type 2 (MONDO:0019683) has_exact_synonym : synpolydactyly

**Term to be merged with**
synpolydactyly (MONDO:0021651)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

from #3919

**Comment by nicolevasilevsky** [comment]
Command:
sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0019683 MONDO:0021651 -o -f obo mondo-edit.obo
