### ISSUE TITLE
MONDO:0005678 bovine respiratory disease complex [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4286]
**Mondo term (ID and Label)**
MONDO:0005678 bovine respiratory disease complex

**Suggested revision and reasons**
This should be a child of MONDO:0005583 "non-human animal disease" 
The MeSH provided definition indicates this a cattle-borne disease: A multifactorial disease of cattle resulting from complex interactions between environmental factors, host factors, and pathogens. The environmental factors act as stressors adversely affecting the immune system and other host defenses and enhancing transmission of infecting agents. [ MESH:D048090 ]

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
I updated the parentage.
