### ISSUE TITLE
obsolete MONDO_0001012 breast fibroadenosis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#429]
MONDO_0001012 'breast fibroadenosis'

from comments:
Editor note: check this consider merge

Note, the class with which it should be merged is not specified.

**Comment by nicolevasilevsky** [comment]
I think the consideration is to merge with MONDO_0005219 'breast fibrocystic disease'

**Comment by nicolevasilevsky** [comment]
This article says "It is now accepted that fibroadenosis is not a disease."

It also says:
"Fibroadenosis is a term used to cover a spectrum of histological changes whcih are seen bothh in association with clinically palpable lumps in the breast and in breasts which are normal on examination. These histopathological changes include fibrosis, adenosis, microcysts, and epithelial hyperplasia."

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2429655/?page=1


Maybe this should be added as a phenotype to HPO?
cc @pnrobinson

**Comment by nicolevasilevsky** [comment]
pinging @pnrobinson

**Comment by pnrobinson** [comment]
See
https://hpo.jax.org/app/browse/term/HP:0010619

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson!

I think this should be obsoleted and add consider HP:0010619
