### ISSUE TITLE
MONDO:0021179  proteostasis deficiencies

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4316]
**Mondo term (ID and Label):**
MONDO:0021179  proteostasis deficiencies

**Xref that should be fixed (ID and label):**
UMLS:C2718001 (MONDO:equivalentTo)
This maps to "Protein Misfolding Disorders" which is a child of Proteostasis deficiencies in UMLS.

If the term is to be specific for Proteostasis deficiencies, use instead
UMLS CUI: C2718000
(FYI MeSH D057165 spans both CUIs, but the preferred name is the broader concept)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
Should Synucleinopathies UMLS CUI: C5191670, MeSH D000080874 also be a child of this term? UMLS and MeSH include this as a narrower concept (Closest match in Mondo is MONDO:0000510, synucleinopathy)
UMLS and MeSH also report "TDP-43 Proteinopathies"  (C2718017 and D057177) as a child of proteostasis deficiency.

**Comment by sabrinatoro** [comment]
1st part of the issue:

UMLS:C2718000 also maps to MESH:D057165, BUT UMLS:C2718000 is a "cell or molecular dysfunction" (semantic types). 
(the current equivalent UMLS:C2718001 is of semantic types "Disease or Syndrome" at UMLS)
Therefore I think that UMLS:C2718000 should be added to MONDO:0021179 as a MONDO:relatedTo
(@nicolevasilevsky, what do you think?)

**Comment by sabrinatoro** [comment]
Additionally:
1) synucleinopathy (MONDO:0000510)
Add Mondo:equivalent: UMLS:C5191670 ; MeSH:D000080874

2) create new term: TDP-43 proteinopathy
**parent**: proteostasis deficiencies (MONDO:0021179)
**Mondo:equivalent**: UMLS:C2718017 ; MESH:D057177
**definition** : (from MESH:D057177)
Disease characterized by the presence of abnormally phosphorylated, ubiquitinated, and cleaved DNA-binding protein TDP-43 in affected brain and spinal cord. Inclusions of the pathologic protein in neurons and glia, without the presence of AMYLOID, is the major feature of these conditions, thus making these proteinopathies distinct from most other neurogenerative disorders in which protein misfolding leads to brain amyloidosis. Both frontotemporal lobar degeneration and AMYOTROPHIC LATERAL SCLEROSIS exhibit this common method of pathogenesis and thus they may represent two extremes of a continuous clinicopathological spectrum of one disease.

**Comment by nicolevasilevsky** [comment]
> Therefore I think that UMLS:C2718000 should be added to MONDO:0021179 as a MONDO:relatedTo
I agree, as this is not an actual disease in UMLS
