### ISSUE TITLE
merge MONDO_0009148 'Rosselli-Gulienetti syndrome' with MONDO_0007124 'ankyloblepharon-ectodermal defects-cleft lip/palate syndrome'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#432]
MONDO_0009148 'Rosselli-Gulienetti syndrome'

From comments in ontology:
obsolete in Orphanet. Wikipedia suggests a merge: it has been suggested that this syndrome, AEC syndrome (MONDO_0007124 'ankyloblepharon-ectodermal defects-cleft lip/palate syndrome') and Rapp–Hodgkin syndrome may be variations of the same disease

**Comment by annieolry** [comment]
Here is Orphanet's reason for Obsolescence:
Following expert Eleidi A. Chautard-Freire-Maia: The four patients originally described by Rosselli and Gulienetti are probably affected by distinct disorders. Patient 1 presents generalized hypotrichosis, light hair, seborrheic dermatitis of the scalp, nail dystrophy, cleft of the soft palate, cutaneous syndactyly and ectrodactyly, unilateral kidney and ureter agenesis. Patients 2 and 3 are a brother and sister showing pytiriasic skin changes, follicular hyperkeratosis, nail dystrophy, ear lobe hypoplasia, cleft of the soft palate, fistula of the lower lip, thumb hypo/aplasia, popliteal pterygium, genital anomalies (scrotal hypoplasia in the boy, labial hypoplasia in the girl). Patient 4 shows prominent forehead, blepharophimosis, a small nose, nail dystrophy, cutaneous syndactly III-V at hands and II-IV at feet. Actual knowledge on the molecular basis of ectodermal dysplasias suggests that Patient 1 may be affected by a TP63-related disorder, Patients 2 and 3 are reasonable examples of  poplyteal pterygium syndrome, while Patient 4 strongly resembles oculo-dento-digital syndrome. (February 2016)

**Comment by nicolevasilevsky** [comment]
@ahamosh Orphanet merged these into two terms, but they are still separate terms in OMIM. Will OMIM consider merging these two terms?
Thanks!

**Comment by nicolevasilevsky** [comment]
pinging @ahamosh

**Comment by ahamosh** [comment]
I don't think that we can know anything about Rosselli-Gulienetti syndrome.  We will remove the % sign showing that we cannot determine its distinctness from another entry, but we can't merge them because we cannot determine what any of those three families had.

**Comment by nicolevasilevsky** [comment]
We will follow OMIM, thanks @ahamosh!
