### ISSUE TITLE
Map Orphanet's non-rare diseases to Mondo (list included)

### ISSUE THREAD

**Issue by Sean-Ontoforce** [monarch-initiative/mondo#4349]
Orphanet seems to have several non-rare diseases in it's ontology, simply labeled as e.g. "_NON-RARE IN EUROPE: Melanoma_" (Which is just regular Melanoma then).
Seems like none of these diseases are mapped to any other ontology and no other equivalency mapping out there seems to cover these.
Would it be possible for MONDO to cover/map these? Or is there a reason to leave these diseases as-is?
Our team's already gone over the list of these Orphanet resources and added the appropriate MONDO IDs where possible.
Mind you that there were some Orphanet resources we were not able to map to any MONDO equivalent.
I've left those out of the list below (I'll create another ticket if necessary to add those diseases to MONDO).
It's quite the list, I know :sweat_smile: 

Orphanet ID | Mondo ID | Label (from Orphanet) | Synonym (from Orphanet)
-- | -- | -- | --
Orphanet:924 | MONDO:0007035 | NON RARE IN EUROPE: Acanthosis nigricans |  
Orphanet:464463 | MONDO:0005036 | NON RARE IN EUROPE: Adenocarcinoma of stomach |  
Orphanet:415268 | MONDO:0005061 | NON RARE IN EUROPE: Adenocarcinoma of the lung |  
Orphanet:3153 | MONDO:0005488 | NON RARE IN EUROPE: Adolescent idiopathic scoliosis |  
Orphanet:99888 | MONDO:0003924 | NON RARE IN EUROPE: Adrenocortical adenoma |  
Orphanet:85142 | MONDO:0014200 | NON RARE IN EUROPE: Aldosterone-producing adenoma | Primary aldosteronism due to Conn adenoma \| Aldosterone-secreting adenoma \| Aldosteronoma \| Conn adenoma
Orphanet:238616 | MONDO:0004975 | NON RARE IN EUROPE: Alzheimer disease |  
Orphanet:825 | MONDO:0005306 | NON RARE IN EUROPE: Ankylosing spondylitis | Ankylosing spondylarthritis \| Bechterew syndrome
Orphanet:36297 | MONDO:0005351 | NON RARE IN EUROPE: Anorexia nervosa |  
Orphanet:80 | MONDO:0007140 | NON RARE IN EUROPE: Antiphospholipid syndrome | Hughes syndrome \| Antiphospholipid antibody syndrome \| Familial lupus anticoagulant
Orphanet:1162 | MONDO:0005259 | NON RARE IN EUROPE: Asperger syndrome |  
Orphanet:625 | MONDO:0009755 | NON RARE IN EUROPE: Atypical mole | Dysplastic nevus \| Clark nevus
Orphanet:106 | MONDO:0005258 | NON RARE IN EUROPE: Autism |  
Orphanet:462 | MONDO:0007810 | NON RARE IN EUROPE: Autosomal dominant ichthyosis vulgaris |  
Orphanet:1232 | MONDO:0013662 | NON RARE IN EUROPE: Barrett esophagus |  
Orphanet:97562 | MONDO:0007709 | NON RARE IN EUROPE: Benign familial hematuria |  
Orphanet:34145 | MONDO:0005342 | NON RARE IN EUROPE: Berger disease | IgA nephropathy
Orphanet:1244 | MONDO:0007194 | NON RARE IN EUROPE: Bicuspid aortic valve |  
Orphanet:157980 | MONDO:0001187 | NON RARE IN EUROPE: Bladder cancer |  
Orphanet:93393 | MONDO:0007217 | NON RARE IN EUROPE: Brachydactyly type A3 | Brachymesophalangy V \| Brachydactyly-clinodactyly
Orphanet:93385 | MONDO:0007222 | NON RARE IN EUROPE: Brachydactyly type D |  
Orphanet:50838 | MONDO:0007275 | NON RARE IN EUROPE: Carpal tunnel syndrome |  
Orphanet:555 | MONDO:0005130 | NON RARE IN EUROPE: Celiac disease | Celiac sprue \| Gluten intolerance \| Gluten-induced enteropathy \| Coeliac disease \| Gluten-sensitive enteropathy \| Idiopathic steatorrhea \| Nontropical sprue \| Coeliac sprue
Orphanet:164 | MONDO:0000820 | NON RARE IN EUROPE: Cerebral cavernous malformations | Brain cavernous hemangioma
Orphanet:1983 | MONDO:0005404 | NON RARE IN EUROPE: Chronic fatigue syndrome | Myalgic encephalomyelitis \| Chronic fatigue immune dysfunction syndrome
Orphanet:1002 | MONDO:0043537 | NON RARE IN EUROPE: Cluster headache | Erythroprosopalgia of Bing \| Ciliary neuralgia \| Red migraine \| Horton headache \| Erythromelalgia of the head \| Histaminic cephalalgia \| Histamine headache \| Histamine cephalalgia \| Migrainous neuralgia \| Cluster migraine
Orphanet:466667 | MONDO:0005575 | NON RARE IN EUROPE: Colorectal cancer |  
Orphanet:206 | MONDO:0005011 | NON RARE IN EUROPE: Crohn disease |  
Orphanet:1648 | MONDO:0007488 | NON RARE IN EUROPE: Dementia with Lewy body | Lewy body dementia \| DLB \| Diffuse Lewy body disease \| Cortical Lewy body disease
Orphanet:243377 | MONDO:0005147 | NON RARE IN EUROPE: Diabetes mellitus type 1 | Insulin-dependent diabetes mellitus
Orphanet:243761 | MONDO:0001134 | NON RARE IN EUROPE: Essential hypertension |  
Orphanet:529819 | MONDO:0008327 | NON RARE IN EUROPE: Exfoliation syndrome | Pseudoexfoliation syndrome \| XFS
Orphanet:276271 | MONDO:0014448 | NON RARE IN EUROPE: Familial dysalbuminemic hyperthyroxinemia | Bisalbuminemia
Orphanet:426 | MONDO:0017774 | NON RARE IN EUROPE: Familial hypobetalipoproteinemia |  
Orphanet:155 | MONDO:0024573 | NON RARE IN EUROPE: Familial isolated hypertrophic cardiomyopathy | Familila or idiopathic hypertrophic obstructive cardiomyopathy
Orphanet:2794 | MONDO:0005349 | NON RARE IN EUROPE: Familial otosclerosis |  
Orphanet:336 | MONDO:0006761 | NON RARE IN EUROPE: Fibromuscular dysplasia of arteries |  
Orphanet:41842 | MONDO:0005546 | NON RARE IN EUROPE: Fibromyalgia |  
Orphanet:459690 | MONDO:0001153 | NON RARE IN EUROPE: Gender dysphoria |  
Orphanet:357 | MONDO:0007745 | NON RARE IN EUROPE: Gilbert syndrome | Hyperbilirubinemia type 1 \| Familial cholemia
Orphanet:362 | MONDO:0040671 | NON RARE IN EUROPE: Glucose-6-phosphate-dehydrogenase deficiency | Favism \| G6PD deficiency
Orphanet:100642 | MONDO:0004277 | NON RARE IN EUROPE: Gonorrhea |  
Orphanet:855 | MONDO:0007699 | NON RARE IN EUROPE: Hashimoto thyroiditis | Hashimoto hypothyroidism
Orphanet:139498 | MONDO:0021001 | NON RARE IN EUROPE: Hemochromatosis type 1 | C282Y/C282Y hemochromatosis \| Classic hemochromatosis \| HFE-related hemochromatosis
Orphanet:862 | MONDO:0003233 | NON RARE IN EUROPE: Hereditary essential tremor |  
Orphanet:387 | MONDO:0006559 | NON RARE IN EUROPE: Hidradenitis suppurativa | Fox den disease \| Ectopic acne \| Pyoderma fistulans significa \| Verneuil disease \| Acne inversa
Orphanet:89939 | MONDO:0100161 | NON RARE IN EUROPE: Hyperkalemic renal tubular acidosis | Renal tubular acidosis type 4
Orphanet:413 | MONDO:0007761 | NON RARE IN EUROPE: Hyperlipoproteinemia type 4 | HLP type 4 \| Familial hypertriglyceridemia
Orphanet:2227 | MONDO:0005486 | NON RARE IN EUROPE: Hypodontia | Tooth agenesis
Orphanet:2810 | MONDO:0005665 | NON RARE IN EUROPE: Idiopathic facial palsy | Bell palsy
Orphanet:651 | MONDO:0005712 | NON RARE IN EUROPE: Idiopathic infantile nystagmus | Congenital idiopathic nystagmus \| Motor congenital nystagmus
Orphanet:69127 | MONDO:0001341 | NON RARE IN EUROPE: Immunoglobulin A deficiency | SIgAD \| Selective immunoglobulin A deficiency
Orphanet:83449 | MONDO:0006802 | NON RARE IN EUROPE: Inappropriate antidiuretic hormone secretion syndrome | SIADH
Orphanet:464293 | MONDO:0011191 | NON RARE IN EUROPE: Infantile capillary hemangioma |  
Orphanet:319684 | MONDO:0013461 | NON RARE IN EUROPE: Inosine triphosphate pyrophosphatase deficiency |  
Orphanet:2335 | MONDO:0015486 | NON RARE IN EUROPE: Isolated keratoconus |  
Orphanet:459696 | MONDO:0100076 | NON RARE IN EUROPE: Juvenile idiopathic scoliosis |  
Orphanet:484 | MONDO:0006823 | NON RARE IN EUROPE: Klinefelter syndrome | 47,XXY syndrome
Orphanet:319681 | MONDO:0006065 | NON RARE IN EUROPE: Lactase non-persistence in adulthood |  
Orphanet:33409 | MONDO:0007899 | NON RARE IN EUROPE: Lichen sclerosus | Lichen sclerosus et atrophicus
Orphanet:411533 | MONDO:0005105 | NON RARE IN EUROPE: Melanoma |  
Orphanet:45360 | MONDO:0007972 | NON RARE IN EUROPE: MeniÞre disease |  
Orphanet:411969 | MONDO:0004955 | NON RARE IN EUROPE: Metabolic syndrome |  
Orphanet:802 | MONDO:0005301 | NON RARE IN EUROPE: Multiple sclerosis |  
Orphanet:521399 | MONDO:0011122 | NON RARE IN EUROPE: Non rare obesity |  
Orphanet:64738 | MONDO:0002305 | NON RARE IN EUROPE: Non rare thrombophilia |  
Orphanet:33271 | MONDO:0013209 | NON RARE IN EUROPE: Non-alcoholic fatty liver disease | NAFLD
Orphanet:415300 | MONDO:0000499 | NON RARE IN EUROPE: Non-arteritic anterior ischemic optic neuropathy | NAION
Orphanet:488201 | MONDO:0005233 | NON RARE IN EUROPE: Non-small cell lung cancer | NSCLC
Orphanet:280110 | MONDO:0005382 | NON RARE IN EUROPE: Paget disease of bone | Osteitis deformans
Orphanet:319705 | MONDO:0005180 | NON RARE IN EUROPE: Parkinson disease |  
Orphanet:319698 | MONDO:0010564 | NON RARE IN EUROPE: Partial color blindness, deutan type | Partial achromatopsia, deutan type \| Deuteranopia
Orphanet:319691 | MONDO:0010565 | NON RARE IN EUROPE: Partial color blindness, protan type | Partial achromatopsia, protan type
Orphanet:706 | MONDO:0011827 | NON RARE IN EUROPE: Patent arterial duct | Patent ductus arteriosus \| Persistent patency of the arterial duct
Orphanet:58208 | MONDO:0005904 | NON RARE IN EUROPE: Pericarditis |  
Orphanet:120 | MONDO:0008228 | NON RARE IN EUROPE: Pernicious anemia | Acquired pernicious anemia \| Biermer anemia \| Biermer disease \| Addison-Biermer anemia \| Juvenile onset pernicious anemia
Orphanet:2870 | MONDO:0008231 | NON RARE IN EUROPE: Peyronie syndrome | Induratio penis plastica
Orphanet:26823 | MONDO:0010896 | NON RARE IN EUROPE: Pigment-dispersion syndrome |  
Orphanet:3185 | MONDO:0008487 | NON RARE IN EUROPE: Polycystic ovary syndrome | PCOS \| Stein-Leventhal syndrome
Orphanet:466673 | MONDO:0041052 | NON RARE IN EUROPE: Post-herpetic neuralgia |  
Orphanet:449262 | MONDO:0013214 | NON RARE IN EUROPE: Primary bile acid malabsorption |  
Orphanet:619 | MONDO:0005387 | NON RARE IN EUROPE: Primary ovarian failure | Premature ovarian failure
Orphanet:40050 | MONDO:0011849 | NON RARE IN EUROPE: Psoriatic arthritis |  
Orphanet:284130 | MONDO:0008383 | NON RARE IN EUROPE: Rheumatoid arthritis |  
Orphanet:3140 | MONDO:0005090 | NON RARE IN EUROPE: Schizophrenia |  
Orphanet:378 | MONDO:0010030 | NON RARE IN EUROPE: Sj÷gren syndrome | Sjögren-Gougerot syndrome \| Sicca syndrome
Orphanet:458713 | MONDO:0000724 | NON RARE IN EUROPE: Specific language impairment |  
Orphanet:489 | MONDO:0006460 | NON RARE IN EUROPE: Thyroglossal duct cyst | Thyroglossal tract cyst
Orphanet:856 | MONDO:0007661 | NON RARE IN EUROPE: Tourette syndrome | Gilles de la Tourette syndrome \| Tourette disease \| GTS
Orphanet:35056 | MONDO:0011182 | NON RARE IN EUROPE: Trimethylaminuria | Fish-odor syndrome
Orphanet:771 | MONDO:0005101 | NON RARE IN EUROPE: Ulcerative colitis | Ulcerative proctosigmoiditis
Orphanet:319658 | MONDO:0001071 | NON RARE IN EUROPE: Unexplained intellectual disability |  
Orphanet:1480 | MONDO:0002070 | NON RARE IN EUROPE: Ventricular septal defect | Interventricular communication \| VSD
Orphanet:3435 | MONDO:0008661 | NON RARE IN EUROPE: Vitiligo |  
Orphanet:97354 | MONDO:0007020 | NON RARE IN EUROPE: Wernicke encephalopathy | Dementia due to thiamine deficiency
Orphanet:907 | MONDO:0008685 | NON RARE IN EUROPE: Wolff-Parkinson-White syndrome | Ventricular familial preexcitation syndrome

ORCID-ID in case it's necessary
 0000-0002-9584-9618

**Comment by nicolevasilevsky** [comment]
Hi @Sean-Ontoforce, thanks so much for this, this is great. I'll work on adding these mappings to Mondo.

**Comment by nicolevasilevsky** [comment]
I created a [spreadsheet here](https://docs.google.com/spreadsheets/d/1tt1Wk70j9XiHLV1vKQyNiHhaazh286pobpJk1ecSCCg/edit#gid=274159492)
