### ISSUE TITLE
[Merge] myofibrillar myopathy 1

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4370]
!!! Need more detailed inspection!

**Mondo term (ID and Label)**
MONDO:0014129

**Reason for deprecation**
MONDO:0014129 equivalent DOID:0110286 is alternative ID for DOID:0080092 corresponds to MONDO:0011076
Similarly, OMIM:615325 (equivalent) was moved to OMIM:601419 which is equivalent to myofibrillar myopathy 1

**Term to be merged with**
MONDO:0011076

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
note to self - assigning to April milestone to look into this further (I will add an obs tag later)

**Comment by nicolevasilevsky** [comment]
I agree these should be merged. I added to the list to add an obs tag.

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo --obsolete-replace MONDO:0014129 MONDO:0011076 -o -f obo mondo-edit.obo`
