### ISSUE TITLE
'central diabetes insipidus' subclass of 'rare neurologic disease'?

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#438]
Hi,

This axiom sounds incorrect: 
'central diabetes insipidus' subclass of 'rare neurologic disease'
http://purl.obolibrary.org/obo/MONDO_0015790
possibly because of the hypothalamus bit in the definition? 
"Central diabetes insipidus (CDI) is a hypothalamus-pituitary disease characterized by polyuria and polydipsia due to a vasopressin (AVP) deficiency. It can be inherited or acquired (hereditary CDI and acquired CDI; see these terms). [ Orphanet:178029 ]"
But it doesn't seem to come from Orphanet
http://www.orpha.net/ORDO/Orphanet_178029
At any rate, I'd suggest to remove the parentage. Otherwise 'central diabetes insipidus' would descend from 'nervous system disorder' ("A non-neoplastic or neoplastic disorder that _affects_ the brain, spinal cord, or peripheral nerves. [ NCIT:C26835 ]").
(I know you plan to obsolete rare disease terms, but as I recall there is no timeline yet.)

Thanks,

Paola
https://orcid.org/0000-0002-2825-0621

**Comment by cmungall** [comment]
I agree it sounds odd.

I'm wondering how we can deal with the pituitary gland in a principled way

I think the uberon representation is correct:

![image](https://user-images.githubusercontent.com/50745/47162874-d727d380-d2c2-11e8-94a2-95e74873c07b.png)

other inferences that come from this seem sound, e.g. this morphological abnormality in MP

![image](https://user-images.githubusercontent.com/50745/47163094-47cef000-d2c3-11e8-934a-0c25b4b9421f.png)

yet it's still odd to think of CDI as a neurological disease, as it doesn't involve neurons firing etc.

(the "rare" part can be ignored for now, we'd have this problem if we just had "neurological disease")

some solutions

 - make neurological disease logical def involve GO nervous system process or similar; but it would still be a subclass of nervous system disease
 - change uberon so the relationship is not part_of but instead located_in

?

**Comment by paolaroncaglia** [comment]
@cmungall 
Thanks for your prompt reply. The problem here is how to axiomatise diseases that originate in an anatomical entity but affect other systems, in this case the endocrine system. The simplest solution here would be to change Uberon so that the pituitary gland is part_of the endocrine system and located_in the brain. But some resources consider the gland a part of the brain and others don't, so... it would probably be more correct to find a general solution - how do you treat other diseases that originate from abnormalities of neuroendocrine glands but do not affect the nervous system? (Sorry, I don't have time to look into this right now, thanks!)

**Comment by cmungall** [comment]
At the moment any other neuroendocrine disease would get the same inference. We can always avoid making this a subclass of nervous system disorder where the disease affects an organ system rather than originating from it. But in this case it seems to arise from an abnormality in the gland.

Changing the anatomy relation: I worry we get into trying to support many subjective fuzzy scenarios. What about brain vasculature?

Maybe if we avoid labels like 'neurological' and instead make groupings that are more explicitly about the anatomy. How do we feel about classification under "disorder of nervous system"?

**Comment by paolaroncaglia** [comment]
@cmungall 
Thanks. I’ve read a bit more reading on the pituitary gland and on central diabetes insipidus. Here are my thoughts: 

The pituitary gland originates from both the ectoderm and the neuroectoderm, so I agree that it’s not only located in the brain but also a legitimate part of it. (And yes, not having to modify the anatomical relationships keeps you away from fuzzy cases.) Of course the gland is still part of the endocrine system too.

CDI stems from a malfunctioning of the pituitary gland. So, it is indeed a disorder where a part of the brain is affected - and of the endocrine system too. The Wikipedia entry is quite strong on the “neuro” connection of CDI: “Central diabetes insipidus, also called neurogenic diabetes insipidus, is a type of diabetes insipidus due to a lack of vasopressin (ADH) production in the brain. (...) It is also known as neurohypophyseal diabetes insipidus, referring to the posterior pituitary (neurohypophysis), which is supplied by the hypothalamus in the brain. This condition has only polyuria in common with diabetes and although not mutually exclusive, with most typical cases, the name diabetes insipidus is a misleading misnomer. A better name might be "hypothalamic-neurohypophyseal ADH deficiency".”

So now I’m at peace with logically connecting CDI to disorders of the nervous system. But I’m wondering if creating an intermediate class of ‘neuroendocrine system disease’ would make the connection more agreeable and, especially, be helpful as a grouping class:

‘central diabetes insipidus’ subclass of ‘neuroendocrine system disease’
‘neuroendocrine system disease’ subclass of ‘nervous system disorder’ and ‘endocrine system disease’

Thanks!

**Comment by cmungall** [comment]
@nicolevasilevsky can you add 'neuroendocrine disease', you can use UBERON:0010133 neuroendocrine gland in the OWL def, follow the disease_has_location pattern
