### ISSUE TITLE
create pipeline to regenerate terms from DOSDP patterns

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4381]
- When someone changes a pattern, we want this to trigger a github action to compile this into OWL and merge the resulting file with mondo-edit.obo
- Nico needs to build this pipeline

**Comment by nicolevasilevsky** [comment]
related to Lauren's work to change patterns for poisoning terms: https://github.com/monarch-initiative/mondo/pulls/laurenechan

**Comment by matentzn** [comment]
Fixed by #4385
