### ISSUE TITLE
Children´s interstitial lung disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#4389]
See https://github.com/obophenotype/human-phenotype-ontology/issues/6682

Synonyms
chILD; chILD syndrome

Definition (free text, please give PubMed ID)
Interstital lung disease (ILD) in children; used synonym to Diffuse parenchymal lung disease (DPLD) in children or pediatric DPLD. The terms chILD or chILD syndrome (not preferred) have been coined to memorize easily and to identify a phenotype that requires prompt and expert evaluation.
PMID: 23905526

Parent term (use hpo.jax.org/app)
Interstital lung disease

Diseases characterized by this term ? (e.g. Orphanet or OMIM number)
PMID: 26408013

**Comment by nicolevasilevsky** [comment]
I think we have this: MONDO_0017014 interstitial lung disease specific to childhood

I will add synonyms and the xref

**Comment by nicolevasilevsky** [comment]
@pnrobinson what do you mean by:
used synonym to Diffuse parenchymal lung disease (DPLD) in children or pediatric DPLD. 

should Diffuse parenchymal lung disease (DPLD) be a separate term? Or a synonym for interstitial lung disease specific to childhood?

**Comment by nicolevasilevsky** [comment]
no other action needed
