### ISSUE TITLE
Logical issues demonstrated by ELK 0.5

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/mondo#439]
ELK 0.5 (unreleased snapshot) adds support for object property ranges, and has revealed some  cryptic issues (also in [Uberon](https://github.com/obophenotype/uberon/issues/1455) and [GO](https://github.com/geneontology/go-ontology/issues/16524)). MONDO has 8000+ unsatisfiable classes when checked with ELK 0.5.

The majority of these (more than 6000) are the result of the logical definition for [bone development disease](http://purl.obolibrary.org/obo/MONDO_0005497), which uses [disease has location](http://purl.obolibrary.org/obo/RO_0004026) with object [bone development](http://purl.obolibrary.org/obo/GO_0060348) (a process rather than a continuant).

There are issues with some other properties as well.

**Comment by nicolevasilevsky** [comment]
I think this has been resolved now
