### ISSUE TITLE
Vetting of definitions

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#44]
- [ ] produce report of definitions to check @cmungall
 - [ ] coordinate sourcing of definitions @nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
@cmungall I should wait for you to provide me with the report, yes?

**Comment by nicolevasilevsky** [comment]
@cmungall is this still something you'd like me to do?

**Comment by nicolevasilevsky** [comment]
@cmungall is this still something we need to do?

**Comment by cmungall** [comment]
I don't remember the context of this
