### ISSUE TITLE
[KCNH1 associated disorder/KCNH1]

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#4410]
**Preferred gene-related syndrome label**: KCNH1 associated disorder
For example: NAA10-related syndrome

**Synonyms**: none

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**: Unsure

**Definition**: Any neurodevelopmental disorder in which the cause of the disease is a mutation in the KCNH1 gene. Variants in KCNH1 cause significant neurodevelopmental disabilities that lie along a phenotypic spectrum ranging from non-syndromic to syndromic. The most common phenotypes associated with variants in KCNH1 include intellectual disability, seizures, hypotonia, absence or hypoplasia of nails, and gingival enlargement. Hypoplastic terminal phalanges of fingers and toes, proximal placement and long thumb, and long toes present less frequently. 

Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene. For example: Any congenital myopathy in which the cause of the disease is a mutation in the TPM3 gene.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######): PMIDs: 25915598, 25420144, 33811134

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term?: Yes, Zimmerman-Laband syndrome 1 (MONDO:0024526) and Temple-Baraitser syndrome (MONDO:0012735) should be child terms of this new term. There is no distinct phenotypic difference, mechanism of disease (GoF), or inheritance pattern (AD) between these two disease entities. Additionally, the term "ID with or without epilepsy without the distinctive feature of ZLS/TBS" has also been associated with variants in this gene in the literature (PMID: 33811134) however, I don't think that term is available in Mondo. There are recurrent variants across all three disease entities leading us to believe this is likely a spectrum of disease.

**Your nano-attribution (ORCID) or URL for a working group**: https://clinicalgenome.org/affiliation/40006/ 
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Hi @tibingaman we already have this term in Mondo:
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100124

Would you like any changes to the existing term?
