### ISSUE TITLE
MONDO:0044784 and/or MONDO:0006086 [Revise text def]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4415]
**Mondo term (ID and Label)**
MONDO:0006086 angiomyxoma
and
MONDO:0044784 myxoma

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
The definitions from NCIT on these two terms are not super helpful in determining a difference in these concepts,  but I am inclined to agree these are distinct concepts. 
From what I have been able to find online, it would seem that perhaps that 'myxoma' is the parent concept/class of tumor _or_ a type of myxoid tumor that primarily presents in the heart (with 'myxoid' phenotype characteristics being shared among all subtype) and 'angiomyxoma' is a subtype that can be further described as superficial or deep/aggressive but affects/involved blood vessels. 
https://en.wikipedia.org/wiki/Myxoma and https://en.wikipedia.org/wiki/Aggressive_angiomyxoma and https://www.cancerresearchuk.org/about-cancer/other-conditions/angiomyxoma

noting that  UMLS has currently lumped these terms on the same CUI (C0027149), possible following MeSH using Myxoma and angiomyxoma interchangeably? (https://www.ncbi.nlm.nih.gov/mesh/?term=D009232 ) So I will follow up with them and request they split since NCIT and SNOMED maintain separate codes for these concepts.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I cannot figure out what the actual difference between these terms is. I looked for reviews, and I didn't find more information. 
Myxoma is most frequently found in the heart (e.g. atrial myxomas), but could occur in other places in the human body, such as the skeletal muscles (intramuscular myxomas), the eye (ocular or conjunctival myxoma), and the skin (cutaneous myxoma)
Angiomyxoma could be 'superficial' or 'aggressive'. 
Based on the name, I would assume that Angiomyxoma would be a myxoma of blood vessel, BUT I couldn't find anything that clearly report this. 

Do you think we should talk to a cancer expert?

**Comment by sabrinatoro** [comment]
Response from NCIT:
Angiomyxomas have a prominent vascular component in contrast to myxomas. We modified the  textual definition of angiomyxoma to include this differentiating feature: A benign soft tissue neoplasm characterized by the presence of neoplastic spindle and stellate cells, and vascular proliferation in a myxoid stroma.
