### ISSUE TITLE
metabolic syndrome (X) and abdominal obesity-metabolic syndrome concepts? [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4425]
**Mondo term (ID and Label)**
MONDO:0004955   metabolic syndrome
MONDO:0011565   metabolic syndrome X
MONDO:0000816   abdominal obesity-metabolic syndrome (and it's OMIM-sourced children)

**Suggested revision and reasons**

- [x] Update name of MONDO:0011565 to reflect OMIM's preferred name: Abdominal obesity-metabolic syndrome 1
- [x] Restructure terms so that MONDO:0000816 abdominal obesity-metabolic syndrome  is a child (somehow) of MONDO:0004955   metabolic syndrome (based on name and the genetic predisposition inherent in the OMIM terms, this seems a more specific form of metabolic syndrome?)
- [x] Remove MONDO:0014352  abdominal obesity-metabolic syndrome 3 as a direct child of MONDO:0004955 metabolic syndrome (under restructuring proposed above it would be a child of the OMIM PS, and thus a 'grandchild' of M.S.)
- [ ] Potentially other clarification/merge of "metabolic syndrome X" relative to the other concepts on this ticket.

NCIT C84442 uses Metabolic syndrome and Metabolic syndrome X as synonyms. I cannot find a clear distinction on the difference between these two concepts. 
SNOMED data also seems to support these as synonyms/alt names? https://bioportal.bioontology.org/ontologies/SNOMEDCT/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F237602007&jump_to_nav=true 
Metabolic syndrome X is an alternate name to OMIM 605552, "Abdominal obesity-metabolic syndrome 1", but is this the only concept in OMIM that could be classified as Metabolic Syndrome X? The text on the OMIM page for 605552 suggests that metabolic syndrome X may be synonymous with the name on the OMIM PS? 

> ...is sometimes called metabolic syndrome X ([Reaven, 1988](https://www.omim.org/entry/605552#20)) or abdominal obesity-metabolic syndrome ([Bjorntorp, 1991](https://www.omim.org/entry/605552#4)). 

https://www.nhlbi.nih.gov/health-topics/metabolic-syndrome NHLBI suggests that "metabolic syndrome" is the same as "syndrome X" so it's not a huge leap that Metabolic syndrome X is just another permutation of this same 'parent' concept for this cluster of clinical findings with a genetic component., Thus the OMIM PS is a more specific subset of metabolic syndrome because there are specific loci implicated for the genetic component; other forms are yet to be determined/mapped and could still be children to metabolic syndrome without existing in OMIM. 

I am open to other solutions or clarifications on these terms, but this is what I could glean from older papers and OMIM.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@kanems I agree with your assessment that probably metabolic syndrome X refers to the parent/more general class. Let me confirm with @ahamosh.

@ahamosh, the question is:
Metabolic syndrome X is an alternative label for the class 'abdominal obesity-metabolic syndrome 1' ([OMIM:605552](https://omim.org/entry/605552)), which is part of the OMIMPS [OMIMPS:605552](https://omim.org/phenotypicSeries/PS605552). Are Megan and I correct in thinking that Metabolic Syndrome X is an alternative title for the grouping class 'metabolic syndrome'? [NCIT](https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/multiple_search.jsf) uses these terms synonymously.

**Comment by nicolevasilevsky** [comment]
proposed merger:
MONDO:0004955 into MONDO:0000816

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo --obsolete-replace MONDO:0004955 MONDO:0000816 -o -f obo mondo-edit.obo`
