### ISSUE TITLE
MONDO:0014225 hemochromatosis type 5

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4427]
**Mondo term (ID and Label):**
MONDO:0014225 hemochromatosis type 5

**Xref that should be fixed (ID and label):**
[OMIM:615517 (Orphanet:247790)](https://omim.org/entry/615517)
I think this is equivalent to the concept represented by the Mondo entry.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
@kanems [OMIM:615517](https://omim.org/entry/615517) is already an equiv xref.

Please reopen if needed.
