### ISSUE TITLE
MONDO:0008042 myoclonus and ataxia[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4429]
**Mondo term (ID and Label)**
MONDO:0008042 myoclonus and ataxia

**Reason for deprecation**
Editor note on EBI display says "consider merging into MONDO:0008945" and OMIM [OMIM:159700 (MONDO:equivalentTo)](https://omim.org/entry/159700) has merged/MOVED TO [213400](https://www.omim.org/entry/213400)

**Term to be merged with**
MONDO:0008945  myoclonic cerebellar dyssynergia

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0008042 MONDO:0008945 -o -f obo mondo-edit.obo`
