### ISSUE TITLE
Consider Parasitic Rachipagus

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/mondo#443]
DOI: 10.21608/ESJ.2016.4013

parking here for now

**Comment by nicolevasilevsky** [comment]
Here is another paper:
ncbi.nlm.nih.gov/pubmed/16410089

This is interesting but I am not sure if it is in scope for Mondo. NCIt has conjoined twins as a subclass of 'finding': https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C98903&viewMode=All&siblings=false

I am going to close this, but please reopen if needed.
