### ISSUE TITLE
Microcephaly, facial dysmorphism, renal agenesis, and ambiguous genitalia syndrome

### ISSUE THREAD

**Issue by WallaceKa** [monarch-initiative/mondo#444]
For new term requests, please provide the following information:

## Preferred term label
Microcephaly, facial dysmorphism, renal agenesis, and ambiguous genitalia syndrome
(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition
OMIM MIM#618142   https://omim.org/entry/618142 
the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/tbn)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id
@nicolevasilevsky @courtneythaxton 
Note: This is a ClinGen curation and needs an immediate MONDO ID for curation purposes.

**Comment by nicolevasilevsky** [comment]
@cmungall will new entries in OMIM be automatically pulled into MONDO or should I manually add this?

**Comment by cmungall** [comment]
Sorry for the delay.

Added with MONDO:0020647 - will be in next release

@nicolevasilevsky can show you the procedure later. But in general it's OK to go ahead and add the class, we can fill in details like xrefs later.
