### ISSUE TITLE
MONDO:0019511 & MONDO:0008073 familial juvenile hyperuricemic nephropathy type 1[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4444]
**Mondo term (ID and Label)**
MONDO:0019511 autosomal dominant medullary cystic kidney disease with hyperuricemia

**Reason for deprecation**
-Orphanet:209886 (OMIM:162000) from MONDO:0008073 ; I cannot find an active entry for this Orpha code, obsoleted? Orpha now says Orphanet:88950 is exact match with OMIM:162000 and the OMIM name is on MONDO:0008073.
GeneReviews article supports the merge;  https://www.ncbi.nlm.nih.gov/books/NBK1356/ (noting this portion of the Nomenclature section which has been helpful in determining how many concepts are unique and should be maintained in MedGen)
>  "...Terms previously used to refer to ADTKD-UMOD that are no longer in use:
> Familial juvenile hyperuricemic nephropathy 1
> Medullary cystic kidney disease 2 (MCKD2)
> UMOD-associated kidney disease"
-OMIM 162000 points to this page in GARD: https://rarediseases.info.nih.gov/diseases/10679/disease 
-Both diseases are linked to UMOD variants.

**Term to be merged with**
MONDO:0008073 familial juvenile hyperuricemic nephropathy type 1

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

Would be open to other suggestions to clean up/distinguish these terms from one another. Based on previous requests from ClinGen, it seems like these terms have been reviewed multiple times. (#1880 #1878 and #2140)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0019511 MONDO:0008073 -o -f obo mondo-edit.obo`
