### ISSUE TITLE
MONDO:0004684 MONDO:0016036 (Ledderhose and plantar fibromatosis) ? [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4451]
**Mondo term (ID and Label)**
MONDO:0016036  Ledderhose disease

**Reason for deprecation**
Both SNOMED and NCI treat these terms as synonyms (13370002  and C4680)

**Term to be merged with**
MONDO:0004684  plantar fibromatosis

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0016036 MONDO:0004684 -o -f obo mondo-edit.obo`
