### ISSUE TITLE
MONDO:0023000 dobrow syndrome and MONDO:0017980 syngnathia multiple anomalies [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4453]
**Mondo term (ID and Label)**
MONDO:0023000 dobrow syndrome 

**Reason for deprecation**
This is the preferred name on http://www.orpha.net/ORDO/Orphanet_3262, which is mapped 1:1 with MONDO:0017980 syngnathia multiple anomalies
GARD https://rarediseases.info.nih.gov/diseases/5092/disease points to the Orphanet entry for Dobrow, as well.

X-refs that could be added to the merged term
UMLS: C5190737
SNOMEDCT 782940006

**Term to be merged with**
MONDO:0017980 syngnathia multiple anomalies

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0023000 MONDO:0017980 -o -f obo mondo-edit.obo`
