### ISSUE TITLE
MONDO:0018756 should not be high-level class

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4468]
euthyroid Graves orbitopathy (MONDO:0018756) has become a high-level term, probably from a previous term obsoletion.

Based on ols, this term was a child of 'autoimmune disease'.

@nicolevasilevsky can you retrace what happened and why 'euthyroid Graves orbitopathy' lost its 'autoimmune disease' parent?

**Comment by nicolevasilevsky** [comment]
not sure but it must have happened recently because it is a child of autoimmune disease in OLS.

Can you please add it back and you can use this reference as the source:
PMID:28427469

https://pubmed.ncbi.nlm.nih.gov/28427469/

thanks!
