### ISSUE TITLE
MONDO:0044719 and MONDO:0018229 preferred and exact synonyms overlap

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4469]
MONDO:0018229  Stevens-Johnson syndrome has "erythema multiforme Major" as an exact synonym, but this is a separate term in Mondo, (MONDO:0044719, erythema multiforme major) and based on NCI, OrphaNet and UMLS mappings, these are indeed distinct concepts (SJS is apparently a more narrow form of EMM?) 

- [x] Remove erythema multiforme Major as an exact syn. on SJS

**Comment by matentzn** [comment]
@nicolevasilevsky please specify the QC check you would like for this issue.

@kanems thank you. @nicolevasilevsky coordinates my work, I usually do not look at issue trackers :)

**Comment by nicolevasilevsky** [comment]
I thought we did have a QC check for checking if an exact synonym matches a label, but maybe this was missed because of the capitalization?

**Comment by kanems** [comment]
Related example that supports the QC check missing overlaps due to capitalization:
http://purl.obolibrary.org/obo/MONDO_0001493 
MONDO:0001493  chronic pulmonary heart disease has Exact synonym "Cor pulmonale" but the Mondo term itself is also a child of "cor pulmonale" MONDO:0004596

**Comment by nicolevasilevsky** [comment]
@kanems I'll make the fixes for the issues you noted. The bigger issue will be solved as part of our synonym spring clean (https://github.com/monarch-initiative/mondo/issues/2939).

**Comment by nicolevasilevsky** [comment]
note to self, action items:
- [ ]  Remove erythema multiforme Major as an exact syn. on SJS
- [ ] Cor pulmonale should be a broad synonym on 'chronic pulmonary heart disease'
