### ISSUE TITLE
[Merge] 'autosomal recessive Mendelian susceptibility to mycobacterial diseases due to partial IFNgammaR1 deficiency'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4472]
**Mondo term (ID and Label)**
MONDO:0017901 'autosomal recessive Mendelian susceptibility to mycobacterial diseases due to partial IFNgammaR1 deficiency'

**Reason for deprecation**
potential duplicate - need to check. @sabrinatoro could you please look into this and if you agree, add this to the merger list. Thanks!

**Term to be merged with**
MONDO_0008856 'immunodeficiency 27A'

**Comment by sabrinatoro** [comment]
I agree, these 2 terms should be merged. 
Actually, Orphanet:319569 maps to OMIM:209950.

**Comment by nicolevasilevsky** [comment]
Looking at this more closely, the Orphanet mapping is narrow to broad ([OMIM:209950 (NTBT (ORPHA code's Narrower Term maps to a Broader Term))](https://omim.org/entry/209950))

I don't think these should be merged
