### ISSUE TITLE
[Obsolete] Antithrombin III deficiency MONDO:0013144

### ISSUE THREAD

**Issue by kristyleelowdermilk** [monarch-initiative/mondo#4475]
**Mondo term (ID and Label)**
Antithrombin III deficiency MONDO:0013144

**Reason for deprecation**
This is an outdated term. There is no antithrombin I or II deficiency, so this should be referred to as antithrombin deficiency (PMID: 19141163, 31697819, 28317092, 30005274); https://medlineplus.gov/genetics/condition/hereditary-antithrombin-deficiency/; https://rarediseases.info.nih.gov/diseases/6148/hereditary-antithrombin-deficiency); https://rarediseases.org/rare-diseases/antithrombin-deficiency/.  However, there are type I (quantitative) and type II (qualitative) defects within antithrombin deficiency.  They are caused by different variants within the SERPINC1 gene, and should all be considered antithrombin deficiency.

**Suggested term to consider**
Antithrombin deficiency

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
0000-0002-8338-7989

**Comment by nicolevasilevsky** [comment]
@kristyleelowdermilk this term is still being used by many other terminologies ([OMIM](https://omim.org/entry/613118), [Orphanet](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_82), [NCIT](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C98815)). I'm not sure that we want to obsolete it. 

We could rename it, [GARD](https://rarediseases.info.nih.gov/diseases/6148/hereditary-antithrombin-deficiency) uses the primary label Hereditary antithrombin deficiency.

**Comment by kristyleelowdermilk** [comment]
Hi Nicole,

According to the experts I work with on the ClinGen Thrombosis Variant Curation Expert Panel<https://clinicalgenome.org/affiliation/50064/>, this term should be obsolete.  There is no antithrombin I or antithrombin II deficiency, and it was misnamed decades ago.  However, I completely understand the concern about its use on prominent resource websites.  While the correct thing to do is make the term obsolete, it would help us simply to have a Mondo ID that is correct, so changing the terminology to “hereditary antithrombin deficiency” or “antithrombin deficiency” will serve our needs at this time.  Eventually, it would be nice to set this straight, but I imagine this would be a big undertaking to obsolete this term.

Thanks so much for all you do for us in ClinGen!!!

Kristy

Kristy Lee, MS, CGC
Genetic Counselor
Associate Professor
Department of Genetics
UNC Chapel Hill
P: 919-843-3158
F: 919-966-4151
***@***.***

**Comment by nicolevasilevsky** [comment]
Hi @kristyleelowdermilk I spoke our to team's medical expert, Peter Robinson and he confirmed that this term is still in use in the clinical community and advised against obsoleting it. We are very grateful for all of the ClinGen curators too and really appreciate your expert advice. :)

For now, I'll relabel the term to hereditary antithrombin deficiency

I will update the definition too.

Thank you!

**Comment by kristyleelowdermilk** [comment]
That sounds like a great compromise, Nicole.  Thanks so much and have a great weekend!

Kristy

Kristy Lee, MS, CGC
Genetic Counselor
UNC Chapel Hill
919-843-3158
________________________________
