### ISSUE TITLE
Bug: broken link to OrphaNet/ORDO from "exactMatch" 

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4479]
**Mondo term (ID Label)**
This seems to be happening on several pages, but here is one instance i ran into today on the EBI display for http://purl.obolibrary.org/obo/MONDO_0016525 
MONDO:0016525  familial hyperaldosteronism

**Bug/Typo/Error description**
The URLs that should link to external sources in the "Term Information" bar on the right-hand side (example: Orphanet 371861) instead ALL point to  "https://www.ebi.ac.uk/ols/ontologies/mondo/$1"  [http://www.orpha.net/ORDO/Orphanet_371861](https://www.ebi.ac.uk/ols/ontologies/mondo/$1) 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by kanems** [comment]
( I see there is a gitHub/issue tracker for OLS, but I don't know the technical details well enough to report the bug directly to them._ @matentzn seems to be an active contributor, though.

**Comment by matentzn** [comment]
Great @kanems thanks a ton! Your issue was on point, I opened it here. https://github.com/EBISPOT/OLS/issues/551

No Mondo issue though, so I will close it here.
