### ISSUE TITLE
obsolete 'pigmentation disease' (MONDO:0006600)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4480]
derived from #4111 (see comments in that issue). 
to do: 
- [x] reclassify orphan children 'reticulate pigment disorder' to MONDO:0019288 {source="OMIMPS:179850", source="https://orcid.org/0000-0002-4142-7153"} ! skin pigmentation disorder
- [x] remove Equivalent axiom of 'skin pigmentation disorder' (MONDO:0019288) that includes 'pigmentation disease'
- [x] obsolete 'neonatal jaundice' (MONDO:0006584): this is a phenotype, and the disease term includes too many different disease types (ie ~due to immune problem-destruction of erythrocytes, and ~due to liver immaturity)
- [x] create new term: "neonatal jaundice due to ABO incompatibility"
- [x] 'perinatal jaundice due to hepatocellular damage' (MONDO:0006595) should have parent 'liver disorder'
- [x] obsolete 'pigmentation disease'

**Comment by nicolevasilevsky** [comment]
@sabrinatoro when you obsolete pigmentation disease and neonatal jaundice, please use this workflow:

https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#simple-mass-obsoletion-pipeline
