### ISSUE TITLE
Regarding the use of MONDO

### ISSUE THREAD

**Issue by Lawhy** [monarch-initiative/mondo#4488]
Hi,

I am very interested in using MONDO as a data source and reference for ontology alignment, but I have two technical questions:
1. When extracting the reference mappings (of equivalence), should I just extract them from both `owl:equivalentTo` and `sko:exactMatch` (because they do not seem to be overlapped)?
2. Will it be possible to extract any individual ontologies from MONDO to set up pair-wise alignment, or should we download the original ontologies?

Many thanks for your help!

**Comment by matentzn** [comment]
Hey @Lawhy!

Thank you for your interest. I would recommend to use the skos:exactMatch properties in mondo.owl. We will also provide you with the reference SSSOM tables soon when they are ready (cc @hrshdhgd), so you can pull then without a shadow of a doubt.

Mondo does not fully represent the structure of the external ontologies (only synonyms, ids and sometime subclassOf axioms). Depending on your use case, you will have to pull the sources by yourself.. It depends what you want to do with the alignment!

**Comment by Lawhy** [comment]
Hi @matentzn,

Many thanks for your reply. I am actually doing automatic ontology alignment and found MONDO a good resource for setting up benchmarks, so may I ask will it be possible to provide links to each individual ontology used in MONDO? I know that there is a Source page, but I am not sure which version of each particular ontology is used; I would like to conduct experiments on data that conform to your work.

**Comment by matentzn** [comment]
@Lawhy Ah, this sounds amazing, unfortunately we will have to disappoint you here - we are still in the process of migrating the mappings to the current versions of the source. Some of our source have been only aligned as a one off in the last 4/5 years, others synced sporadically - we are up to date with OMIM, and reasonably up to date with ORDO (maybe 1, 2 versions behind ORDO), but we were doing a bad job of keeping metadata such as version numbers used for the alignments. I will raise this issue at our next Mondo call to ask, but my feeling right now is that if you need version metadata, it will be a while. However, I am working on it as we speak, so there is a chance this "while" will last only to around May. No promises though.

**Comment by Lawhy** [comment]
I see, but you said that OMIM and ORDO are pretty up-to-date, so could I at least get the version numbers or approximate ones for these ontologies because I will need to download the correct ones for experiments.

**Comment by matentzn** [comment]
There is no "OMIM" ontology though with a version, but we can supply you with one. Yeah sure, go ahead. I would think ORDO 3.8 should be covered. You can use this version of OMIM if you want for your experiments: https://github.com/monarch-initiative/omim - it will be covered to about ~99 % (we have not looked at the latest release yet, but it will be good enough to get started).

Feel free to contact me via email as well so I can give you a few more pointers privately (nicolas dot matentzoglu gmail).

**Comment by matentzn** [comment]
Can be closed, please open new ticket for specific requests!
