### ISSUE TITLE
Merge MONDO:0008940 and MONDO:0013722[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4516]
**Mondo term (ID and Label)**
MONDO:0008940  endosteal sclerosis-cerebellar hypoplasia syndrome

**Reason for deprecation**
Per OMIM: ^ 213002
MOVED TO [614381](https://omim.org/entry/614381)
And endosteal sclerosis-cerebellar hypoplasia syndrome is now an alternate name for OMIM:614381 
**Term to be merged with**
MONDO:0013722 hypomyelinating leukodystrophy 8 with or without oligodontia and-or hypogonadotropic hypogonadism
(Apologies if this is redundant, I did not see the merged OMIM number in the "OMIM slurp" ticket)
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0008940 MONDO:0013722 -o -f obo mondo-edit.obo`
