### ISSUE TITLE
Missing SSSOM mappings

### ISSUE THREAD

**Issue by Lawhy** [monarch-initiative/mondo#4522]
Hi @matentzn ,

I found that the extracted SSSOM mappings are incomplete, e.g., the pair of MONDO-OMIMPS is missing.

**Comment by matentzn** [comment]
Thank you @Lawhy 

@hrshdhgd I am assigning you since you are working on reviving this branch - basically make sure that the OMIM sssom tables include not only OMIM, but also OMIMPS prefix terms.

**Comment by nicolevasilevsky** [comment]
@hrshdhgd I assigned this to the June milestone but please feel free to move back if that is unrealistic. Thanks!

**Comment by matentzn** [comment]
It's realistic.. can be done any time @hrshdhgd feels like, I would kinda like this sorted earlier.

**Comment by nicolevasilevsky** [comment]
this was fixed by @joeflack4 and @matentzn:  https://github.com/monarch-initiative/mondo/blob/master/src/ontology/mappings/mondo_exactmatch_omimps.sssom.tsv

note, there are also some non-exact matches to OMIMPS

Thanks! :)
