### ISSUE TITLE
Fix: Illegal ICD10 Codes

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo#4524]
## Description
During my ICD10CM analysis, I found these.

_Nico said:_
> These showed up. We need to fix them manually.
https://docs.google.com/spreadsheets/d/1KMTF7aUAeamVr_vZQSKxoJF28itRT4ZXUIiHcr8pFzk/edit

## Related issues
#628

**Comment by matentzn** [comment]
Concretely:

Go through all the codes in `prefixOriginal:code` column and figure out what on the https://www.icd10data.com/ site they were supposed to refer to. You can use search in protege to find any related Mondo terms.

**Comment by nicolevasilevsky** [comment]
@joeflack4 and @matentzn can you clarify what needs to be done? Should I fix these in Mondo?

**Comment by cmungall** [comment]
Note these odd "+"s and "*"s come from ORDO.
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_100067

Clearly they should not be part of the actual ID itself and ORDO is using
some kind of ad-hoc expression language. I think it's worth (a small amount
of) investigating what they are trying to do and seeing if there is a way
to represent this another way.

**Comment by matentzn** [comment]
I think this is what needs to be done:

Given this example: `MONDO:123 --> ICD10:E35.1*`

1. Based on the bad code you try to figure out what the correct mapping is, e.g `MONDO:123 --> ICD10:E35.1` or whatever code you think.
2. The correct code should be changed to `ICD10CM:E35.1`
3. The expression language pattern (where a _correct_ code is postfixed by a symbol like `*`, `+` etc) one should be changed to `ICD10EXP:` for now, e.g `MONDO:123 --> ICD10EXP:E35.1*`, and no `MONDO:equivalent***` should be on it (or if it has to, then "related"). This part is independent of the two above.

Does this make sense? I see this can be quite daunting, but I am happy to discuss tomorrow!

**Comment by nicolevasilevsky** [comment]
to do:
- all fo the + and * should be changed to ICD10EXP, but I need to review these and make sure there is at least one correct code if possible.

**Comment by joeflack4** [comment]
Just curious, is `ICD10EXP:` a new prefix that should resolve to some URI base? Is it a problem if it doesn't?

**Comment by matentzn** [comment]
No, we should filter these out before release.. We just don't want to loose the province atm!

**Comment by matentzn** [comment]
These are removed by ../sparql/update/delete-axiom-annotations-by-prefix.ru

This ticket is dealt with by @nicolevasilevsky @sabrinatoro @joeflack4

good job all.
