### ISSUE TITLE
Manually map 5 ORDO codes

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#4525]
The old slurping pipeline has a problem with these, thank you for mapping:

- [x] Orphanet:377791 ! morphological anomaly - _this is added as a subset tag in Mondo_
- [x] Orphanet:557494 ! subtype of a disorder - _I really have no idea what to do with this!_ 
- [x] Orphanet:377789 ! malformation syndrome. _Should we do a proxy merge with MONDO_0019755 'developmental defect during embryogenesis' ([Orphanet_93890](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_93890)_)?
- [x] Orphanet:557492 ! group of disorders - _I really have no idea what to do with this either!_ 
- [x] Orphanet:557493 ! disorder- _Maybe we should do a proxy merge with [Orphanet:377788](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_377788), which is a child of disorder in Orphanet and equiv to 'disease or disorder' in Mondo_

Given their massive impact, can you make sure that all of these:

- have an equivalent Mondo term
- that is potentially obsolete (that does not matter to me, whether it is obsolete or not)

You can get their metadata from here: https://www.ebi.ac.uk/ols/ontologies/ordo

I think when this is done we can at least start syncing up with the latest ORDO, even while the new pipeline is not done.

**Comment by nicolevasilevsky** [comment]
@matentzn see my comments above, I should ask Chris about these.
Are you suggesting that we just add them to Mondo as "born obsolete" though?

**Comment by matentzn** [comment]
I think having them enter as born obsolete is totally fine, but yeah, best to check in with Chris.

**Comment by nicolevasilevsky** [comment]
action item: bring in all these terms as born obsolete
