### ISSUE TITLE
NTR: Malignant Spindle Cell Neoplasm

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#453]
NTR: Malignant Spindle Cell Neoplasm
This term is in NCIT, can we import it into MONDO?
NCIT:C27091

**Comment by cmungall** [comment]
hmm, this class is kind of odd, 

SCN has a single child (bad smell), and that child has no additional subclasses

```
   is_a NCIT:C3262 ! Neoplasm
    is_a NCIT:C7062 ! Neoplasm by Special Category
     is_a NCIT:C27263 ! Spindle Cell Neoplasm *** 
      is_a NCIT:C27091 ! Malignant Spindle Cell Neoplasm
```

There are many other neoplasms in ncit that seem like they *should* be classified here but are not, can you investigate?
