### ISSUE TITLE
Ingest manually curated ICD10CM mappings into Mondo

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#4535]
From @nicolevasilevsky [spreadsheet](https://docs.google.com/spreadsheets/d/1cZPUReTl34Vu2a03tm2921ehARiIpp4fjeQfS27XzKA/edit#gid=0)

**Comment by nicolevasilevsky** [comment]
need to turn this into a ROBOT template, best to do this together

**Comment by nicolevasilevsky** [comment]
@matentzn can this be closed?
