### ISSUE TITLE
Document curation rules for ICD10CM mappings

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#4536]
We need to know precisely:

1. What were you thinking when aligning exact matches. Did you have doubts?
2. How did you decide not to map a term? Which one? (neoplasm, injury, etc)
3. What difficulties arose during the manual mapping process (the more detail the better)
4. Can you try to formulate your curation method, i.e. what did you do exactly to determine whether two terms could be mapped?

**Comment by matentzn** [comment]
I think we need something like this from Orphanet:

https://www.orpha.net/orphacom/cahiers/docs/GB/Orphanet_ICD10_coding_rules_R1_Nom_ICD_EP_06.pdf

What do you think?

**Comment by sabrinatoro** [comment]
@matentzn 
I think it would be a very good thing to have something like the Orphanet document. 
It looks like a lot of work, but I think it is important so we document everything we do, and it also will record our process, which is important when sharing the mappings.

**Comment by sabrinatoro** [comment]
Curation rules are in the "CurationRules" in the spreadsheet [here](https://docs.google.com/spreadsheets/d/1cZPUReTl34Vu2a03tm2921ehARiIpp4fjeQfS27XzKA/edit#gid=231452953)

@matentzn please take a quick look whenever you have a moment and let me know if these are understandable and in a clear format. Thanks

**Comment by matentzn** [comment]
I already looked them over last weekend and I _love_ what I can learn from them. I would kinda like you to present this a bit at the next ODK talk, also so that @cmungall can chime in on this.

**Comment by matentzn** [comment]
(Issue can be closed)
