### ISSUE TITLE
MONDO:0015681/MONDO:0001726  childhood disintegrative disorder/disease ? [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4537]
**Mondo term (ID and Label)**

MONDO:0001726  childhood disintegrative disease

**Reason for deprecation**
I am not sure I understand why there is a distinction between these two concepts? 
Both cite "Heller('s) syndrome" as an exact synonym in Mondo. 

NOTE the SNOMEDCT code on MONDO:0001726 is 61831009 , which is "Induced psychotic disorder" and does not seem to match the concept, this should probably not be maintained.

**Term to be merged with**
MONDO:0015681  childhood disintegrative disorder

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0001726 MONDO:0015681 -o -f obo mondo-edit.obo`

- [ ] remove SCTID:61831009 as an equiv xref
