### ISSUE TITLE
Automate pattern and qc docs in GH actions

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#4564]
@nicolevasilevsky I can do this in 5 min during a call of your choosing.

**Comment by nicolevasilevsky** [comment]
I added this to our one-on-one agenda

**Comment by joeflack4** [comment]
I came across this while looking to open a GH action related issue.

Is this one still relevant or maybe it is already completed? 5 min sounds pretty quick.

**Comment by nicolevasilevsky** [comment]
if it is still open, we probably didn't do it, but I'm not sure if it is still needed

**Comment by matentzn** [comment]
We dealt with this here: https://github.com/monarch-initiative/mondo/blob/master/.github/workflows/docs.yaml

All done.

**Comment by matentzn** [comment]
Thanks @joeflack4 for chasing and helping us close issues!
