### ISSUE TITLE
Retire OMIM:103470 and Orphanet:352740 on MONDO:0018138

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4581]
**Mondo term (ID and Label):*
MONDO:0018138  
ocular albinism with congenital sensorineural hearing loss
**Xref that should be fixed (ID and label):**
https://omim.org/entry/103470 "103470
MOVED TO [193510](https://omim.org/entry/193510) AND [606952](https://omim.org/entry/606952)"

Orphanet:352740 is marked as child of deprecated disorder in OLS and has this text on OrphaExpert link  "This entity has been excluded from the Orphanet nomenclature of rare diseases and moved to [Waardenburg syndrome type 2](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=895)"

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
DOID exact match X-ref seems to still be active, but may be worth reviewing if this should be merged or obsoleted in Mondo.

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] obsolete 'ocular albinism with congenital sensorineural hearing loss'
consider: MONDO:0008671 'Waardenburg syndrome type 2A' and MONDO:0011749 'oculocutaneous albinism type 1B'
