### ISSUE TITLE
[NTR] 'liver abscess' and 'intersphincteric abscess'

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#4593]
Hi, stemming from an HCA request (https://github.com/HumanCellAtlas/ontology/issues/103), would you please consider adding the following two terms, both as subclasses of MONDO:0005227 'abscess':

**Term 1 label**
liver abscess
HP has HP:0100523 'Liver abscess', so you may prefer to label the new Mondo term 'liver abscess (disease)'?

**Synonyms**
hepatic abscess

**Definition**
An abscess in the liver.
WikipediaVersioned:Liver_abscess&oldid=1061021667
(i.e. https://en.wikipedia.org/w/index.php?title=Liver_abscess&oldid=1061021667)

**Parent term**
Equivalent to: 
MONDO:0005227 'abscess' and disease has location some UBERON:0002107 'liver'

**Dbxref**
SNOMEDCT: Abscess of liver (27916005)
NCIT:C99089 Liver Abscess

**Your nano-attribution (ORCID)**
0000-0002-2658-1136 (HCA submitter's); 
0000-0002-2825-0621 (mine)

**Term 2 label**
intersphincteric abscess

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
An abscess contained between the internal and external anal sphincters.
WikipediaVersioned:Anorectal_abscess&oldid=1066372272
(i.e. https://en.wikipedia.org/w/index.php?title=Anorectal_abscess&oldid=1066372272)

**Parent term**
MONDO:0005227 'abscess'
Ideally this should be Equivalent to: MONDO:0005227 'abscess' and disease has location something, but there's no Uberon term to represent the intersphincteric space, and I'm not sure that one is needed. So perhaps just leave as subclass of abscess, to avoid delaying term creation? 

**Dbxref**
SNOMEDCT: Intersphincteric abscess (235795007)

**Your nano-attribution (ORCID)**
0000-0002-2658-1136 (HCA submitter's); 
0000-0002-2825-0621 (mine)

Thank you!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky on behalf of HCA, thank you so much for tagging this issue as priority. I noticed that's in the May release milestone. Is that early May please? Asking so I can give an estimate to HCA (so they know in relation to their own release schedule). Thank you.

**Comment by nicolevasilevsky** [comment]
Yes, early May.
