### ISSUE TITLE
revise capitalization of clingen preferred AP

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4596]
clingen would like it to be ClinGen preferred

are there any issues with having capitals in APs @matentzn ?

**Comment by matentzn** [comment]
Its a bit of an odd request, usually you only change the labels of a property, not the ID.. But I guess we could make an exception if you think its necessary..

**Comment by nicolevasilevsky** [comment]
I meant to just change the label, sounds like there aren't any issues with the label being 'ClinGen preferred' instead of 'clingen preferred'?

**Comment by matentzn** [comment]
the label (rdfs:label) can be whatever you like!

**Comment by nicolevasilevsky** [comment]
great, thank you Nico!

**Comment by sabrinatoro** [comment]
Let's wait a second: 
1) we are not talking about the rdfs:label, we are talking about "hasSynonymType"
2) they are talking about wanting something like "ClinGen discussed entity" (or something like this). 

I think we should clarify what they want before making any changes.

**Comment by matentzn** [comment]
@sabrinatoro steps in and is probably right :) we can discuss in QC call!

**Comment by nicolevasilevsky** [comment]
@sabrinatoro was there a decision at the end of that meeting- I didn't note that they ever made a decision as to what they wanted the label to be called or if they wanted it to be displayed. @matentzn we are still not showing the 'clingen preferred' label in the release files, right?

If there aren't any proper action items for us at the moment, I think this ticket can be closed until they let us know what it is the want. (But we should remember that they want clingen to be displayed as ClinGen, not lowercase).

**Comment by matentzn** [comment]
YEs, clingen preferred are still removed, and feel free to change the label to whatever you want! The label, NOT the property.

**Comment by nicolevasilevsky** [comment]
I just changed the label to be "ClinGen preferred" and we can change it to whatever they want if they decide they want something else in the future. Since this is not being shown in the released files, this is just for internal use and a reminder to ourselves that they would like the ClinGen label to be in CamelCase.

**Comment by nicolevasilevsky** [comment]
I just changed the label to be "ClinGen preferred" and we can change it to whatever they want if they decide they want something else in the future. Since this is not being shown in the released files, this is just for internal use and a reminder to ourselves that they would like the ClinGen label to be in CamelCase.
