### ISSUE TITLE
Major prefix cleanup

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#4597]
To prepare for our upcoming syncing efforts, I finally got around to do some major cleanups of the usage of prefixes in Mondo.

#4595 

I am have cleaned up quite a bit, but I need some help figuring out what to do with these:

- [x] CSP2005
- [x] MTHICD9_2006
- [x] ORDO
- [x] MONDOLEX
- [ ] MONDORULE
- [x] OWLReasoner
- [ ] DC-OMIM
- [x] ISBN-13
- [x] NCBI
- [x] NCI2004_11_17
- [x] Rename ICD10 to ICD10CM
- [ ] NIFSTD (should be removed)
- [ ] MTH (should be removed)

**Comment by matentzn** [comment]
Here is the respective QC query underway: https://api.triplydb.com/s/FKtpmWBZd

The idea is to totally standardise the use of `source` and `hasDbXref` in Mondo and provide formal prefix maps with documentation for users.

**Comment by matentzn** [comment]
Some notes to self: https://docs.google.com/spreadsheets/d/1QWP2e37BulM3BIHs0B3pTJiYRb5ouUdxuNboHrKpXlM/edit#gid=1581971360

**Comment by nicolevasilevsky** [comment]
Remove:

- CSP2005 (From DO, and these have been removed)
- MTHICD9_2006 (From DO, and these have been removed)
- ORDO - in axiom annotation, we retain the original orphanet axiom annotations and we did it using the ORDO prefix. We can harmonize these to use the Orphanet prefix
- MONDOLEX - that was a rule for lexical matching, can be removed, eg X disease 1 is_a disease
- MONDORULE 
- OWLReasoner - (side note, we need a solution for this across OBO, in OMO). **KEEP**
- DC-OMIM (Disease-cluster OMIM)
- ISBN-13 - Nico will sort this out
- NCBI - we want to use mim2gene as provenance here. **KEEP**
- NCI2004_11_17
