### ISSUE TITLE
central sleep apnea

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#46]
* https://omim.org/entry/107640 APNEA, CENTRAL SLEEP
 * https://omim.org/entry/207720 APNEA, CENTRAL SLEEP (incl. SLEEP APNEA, LETHAL CENTRAL)

we have a grouping

[MONDO:0004731](http://purl.obolibrary.org/obo/MONDO_0004731) ! central sleep apnea

should the OMIMs be two distinct subclasses? Merged? Should they be treated as distinct case reports about the same disease?

**Comment by nicolevasilevsky** [comment]
Wow - the case report for OMIM:207720 is very sad. 

Based on reading these entries, they seem like different diseases, where OMIM:207720 is a lethal form of sleep apnea, and it maybe should have the synonym 'subacute necrotizing encephalomyopathy'.

**Comment by nicolevasilevsky** [comment]
looks like these terms have been merged, so I will close this
