### ISSUE TITLE
Request IDs for Tyrosine Hydroxylase deficiency

### ISSUE THREAD

**Issue by jennygoldstein** [monarch-initiative/mondo#460]
Hello,
We would like to request three new MONDO IDs, rename one MONDO description, and request some reorganization around the phenotypes caused by tyrosine hydroxylase (TH) deficiency. I have attached a slide to explain the proposed changes. Further information supporting this request can be found in Furakawa and Kish, GeneReviews, PMID 20301610). The 5 requests are listed individually below.

## Request 1: 
Request for a new MONDO ID for tyrosine hydroxylase deficiency

## Preferred term label: 
Tyrosine hydroxylase deficiency

## Synonyms: 
TH deficiency, tyrosine 3-monooxygenase deficiency

## Textual definition
Tyrosine hydroxylase (TH) deficiency is an autosomal recessive disorder characterized by a spectrum of phenotypic features, based on severity and response to levodopa. It can be broadly categorized into TH-deficient dopa-responsive dystonia (mild, with dramatic and sustained response to levodopa), TH-deficiency infantile parkinsonism with motor delay (severe, with incomplete response to levodopa), and TH-deficiency infantile encephalopathy (very severe, with little to no response to levodopa) (PMID 20301610).

## Suggested parent terms: 
This should be listed under "Neurometabolic disease" (MONDO: 0019058), and "inborn error of neurotransmitter metabolism and transport" (MONDO: 0019219)

## Request 2: 
Rename "autosomal recessive dopa-responsive dystonia" (MONDO: 0011551)
## Preferred term label: 
TH-deficient dopa-responsive dystonia.

## Synonyms: 
Those currently listed for "autosomal recessive dopa-responsive dystonia" (MONDO ID: 0011551) , but please remove "tyrosine hydroxylase-deficient dopa-responsive dystonia" and "tyrosine hydroxylase deficiency" from the synonym list, and please add "autosomal recessive dopa-responsive dystonia".

## Suggested parent term: 
Tyrosine hydroxylase deficiency (when created based on Request 1 above), and those terms which are already parents of  "autosomal recessive dopa-responsive dystonia" (MONDO: 0011551)

## Attribution: 
ORCID 0000-0002-5655-9589

## Request 3: 
Request for a new MONDO ID for TH-deficient infantile parkinsonism and motor delay

## Preferred term label: 
TH-deficient infantile parkinsonism and motor delay

## Synonyms: 
None

## Suggested parent term: 
Tyrosine hydroxylase deficiency (when created based on Request 1 above)

## Attribution: 
ORCID 0000-0002-5655-9589

## Request 4: 
Request for a new MONDO ID for TH-deficient progressive infantile encephalopathy

## Preferred term label: 
TH-deficient progressive infantile encephalopathy

## Suggested parent term: 
Tyrosine hydroxylase deficiency (when created based on Request 1 above)

## Attribution: 
ORCID 0000-0002-5655-9589

## Request 5: 
Remove "autosomal recessive dopa-responsive dystonia" (MONDO: 0011551) (which we are asking to be renamed as "TH-deficient dopa-repsonsive dystonia", per request 2) from being a child term of "cerebral organic aciduria". Based on input from the ClinGen Inborn Errors of Metabolism working group, this disorder should not be classified as an organic aciduria.

Thank you very much
[MONDO request_TH deficiency.pptx](https://github.com/monarch-initiative/mondo/files/2567460/MONDO.request_TH.deficiency.pptx)
 for you help. Please et me know if there are any questions. 

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
**Request 1:**
tyrosine hydroxylase deficiency is a synonym for MONDO_0011551 'autosomal recessive dopa-responsive dystonia'

**Comment by nicolevasilevsky** [comment]
**request 1**: added added new term: tyrosine hydroxylase deficiency MONDO_0100064
**request 2**: I made the changes requested above
**request 3**: added new term MONDO_0100065 'TH-deficient infantile parkinsonism and motor delay'. 
**request 4**: added new term MONDO_0100066 'TH-deficient progressive infantile encephalopathy',
**request 5**: MONDO: 0011551 is inferred to be a child of cerebral organic aciduria - I pasted the explanation from Protege below.

![image](https://user-images.githubusercontent.com/6722114/48294842-c3900880-e43b-11e8-8b0e-b3dd44f08948.png)

**Comment by nicolevasilevsky** [comment]
Note on request 2:
I removed syn tyrosine hydroxylase-deficient dopa-responsive dystonia (xref: Orphanet:101150) from MONDO ID: 0011551, but should it be used somewhere else instead? Or do we not want this term in MONDO at all?

**Comment by jennygoldstein** [comment]
I agree Nicole. Thanks for checking.

**Comment by nicolevasilevsky** [comment]
Great, closing this issue
