### ISSUE TITLE
Proposal: Make MONDO root inherit from independent continuant

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#461]
Pros:

 * Many people find inheriting from disposition to be strange, to say the least
 * Many text definitions are written as if they are physical things
 * would make HPO axiomatization easier

Cons:

 * ICs in particular MEs have properties like mass, shape, temperature. While it's natural to think of physical properties of neoplasms, aneurysms etc, it's odd to talk of these properties as applying to infections, syndromes, "brain disorder". But then the same may be true of AO terms for scattered/aggregates like "immune system". The natural subclass of IC would be material entity, but we may want to leave this open (BFO hierarchy is open) to allow for an IC that is neither site nor ME, but has properties of an ME
 * breaks with OGMS (though we could make obo-foundry-unique-label of "disorder" for all things currently labeled "disease"

Details:

 * experience for most users would remain identical
 * need to check how would affect EFO integration
 * we already differ from other disease resources that overload is_a, we tend to use disease-has-feature more; this means our hierarchy already makes more sense from an IC point of view
 * need to ensure that we have no `X-syndrome SubClassOf {neoplasm,aneurysm,..}` and that these are replaced by `X-syndrome SubClassOf {disease-has-feature,...} some {...}`
 * NCIT is uncommitted so equivalence axioms could remain as-is
 * We have buffered ourselves to some extent by using `disease-foo` relations, which forms a bridge to bfo commitment, but these currently have domains in RO that would need generalized (also these should be relabeled `disorder-foo`)
 * We do use some relations like realized_by directly, these would need changed
 * We use has-phenotype to link MONDO to HPO in Monarch, this is buffered already; but we may want to make this a more descriptive relation; see below
 * Change equivalenace axiom at MONDO_0000001 from OGMS_0000031 (disease) to disorder (OGMS_0000045)
 * Ensure terminological consistency. We currently use disease/order somewhat interchangeably. We should be more consistent, but go with community usage, and always include synonyms. But I don't think we can adopt the ogms terminological stance that disorders are the basis of disease (we can accept the axioms, but if the community uses disease/disorder interchangeably we must accept)
 * We may want to retain some things under disposition, e.g. genuine predispositions

The has-phenotype relation could be axiomatized as:

`D SubClassOf has-phenotype some P => (organism and has-part some D) SubClassOf has-disposition some realized-by some results-in some P`

**Comment by cmungall** [comment]
Thinking through some cases

 * neoplasm: either a contiguous mass of neoplastic cells (plus enclosing microenvironment), or  a scattered aggregate eg blood
 * cancer: consider renaming to "malignant neoplasm" to emphasize ME aspect
 * infectious disorder / infection: in IDO this is a ME that includes other organisms as part (thus overlaps with the human, and is part of the extended organism) http://purl.obolibrary.org/obo/IDO_0000586
 * syndrome: an object aggregate
 * inflammation: ME
 * abscess, aneurysm, infarct, ulcer, cataract, cyst: ME

**Comment by dosumis** [comment]
Do we need a single, BFO compliant root for Mondo?   Would it be better to have multiple BFO roots - depending on the branch?

I'd like to understand how this fits with various use cases such as:

1. Annotating a piece of tumour (e.g. used in PDX; input to transcriptomics (HCA); Use in imaging).   - parts are continuants.
2. Annotating a human patient with the cancer they have (Needed for HCA - must be clearly distinct from reference to tumour sample.)
3. Annotating a description of disease progression / recovery - parts may be temporal slices.


CC @simonjupp

**Comment by pnrobinson** [comment]
It seems to me that a disease is not a physical entity itself, rather it is a change in an entity. 
```
A disposition is a realizable dependent continuant that typically causes a specific process in the object in which it inheres when the  object is  introduced  into  certain specific  circumstances.  In  addition,  these  processes  occur  as  a  result  of  the object’s physical structure (Jansen, 2007). 
A  disposition  invariably  leads  to  a  certain  result given certain  circumstances.  Consider:  the  disposition  of  a  car windshield  to  break  if  struck  with  a  sledgehammer  moving 
at  100  feet  per  second;  the  disposition  of  a  cell  to  become 
diploid  following  mitosis;  the  disposition  of  a  magnet  to 
produce an electrical field. 
Contrasted  with  a  disposition  is  a tendency,  which  is  a realizable  dependent  continuant  that  potentially  (not invariably  or definitely) causes a specific process in the object  in 
which  it  inheres  when  the  object  is  introduced  into  certain 
specific  circumstances  as  a  result  of  the  object’s 
physical structure property
```
Disposition seems at least a little closer to disease although to be honest I think having a completely new "superclass" within the BFO would be the best idea of all. One of the problems with some of the theories such as OGMS is that they assume that all reality can be described in the existing BFO categories....

**Comment by cmungall** [comment]
> I'd like to understand how this fits with various use cases such as:

Annotating a description of disease progression / recovery - parts may be temporal slices.

> Annotating a piece of tumour (e.g. used in PDX; input to transcriptomics (HCA); Use in imaging). - parts are continuants.
Fits with neoplasm is_a ME

> Annotating a human patient with the cancer they have (Needed for HCA - must be clearly distinct from reference to tumour sample.)
The semantics can be pushed into the annotation relation

> Annotating a description of disease progression / recovery - parts may be temporal slices.

yes, with either derivation/transformation (benign neoplasm to malignant) or causal relations between MEs (e.g. diabetes causing retinopathy)

We can explore the multi-root idea, but what I would like to avoid is having shadow hierarchies, e.g. malignant neoplasms as MEs, then a parallel cancer branch

**Comment by pnrobinson** [comment]
I would say that neoplasm being a physical part is the phenotype (HPO term), whereas the disease is not the same thing.

**Comment by cmungall** [comment]
hmm, at the moment all phenotypes follow the same pattern where they PATO-centric (or rather has-part some PATO).

Note that if we made some classes in HPO MEs then we can no longer have subClassOf connecting them. This is maybe fine for Neoplasm, as it forms it's own branch in HPO. 

but what would we do with things like Anuerysms? In HPO are these MEs or Qs? Currently they are mixed in with morphology

```
    is_a HP:0030680 ! Abnormality of cardiovascular system morphology
     is_a HP:0025015 ! Abnormal vascular morphology
      is_a HP:0002617 ! Dilatation
       is_a HP:0004942 ! Aortic aneurysm *** 
```

**Comment by dosumis** [comment]
CC @matentzn

**Comment by dosumis** [comment]
> We can explore the multi-root idea, but what I would like to avoid is having shadow hierarchies, e.g. malignant neoplasms as MEs, then a parallel cancer branch.

I don't see this as a problem, as long as it is entirely patternised.  WIth sufficient axiomatization for annotation (e.g. mapping from HCA schema to triples), we can potentially bridge between branches.

**Comment by dosumis** [comment]
I'd still like to see an enumerated set of use cases - especially with regard to how to deal with disease processes.  I'm scared of the pretzel logic that might result from e.g. treating inflamation or cancer progression in the context of Mondo only defining MEs.

**Comment by cmungall** [comment]
> I don't see this as a problem, as long as it is entirely patternised. WIth sufficient axiomatization for annotation (e.g. mapping from HCA schema to triples), we can potentially bridge between branches.

I can't see any way of doing this without introducing massive confusion. How would the disease structures be named for the disposition with material basis 'neoplasm'? I just don't see the use case for naming both.

> I'd still like to see an enumerated set of use cases - especially with regard to how to deal with disease processes. I'm scared of the pretzel logic that might result from e.g. treating inflamation or cancer progression in the context of Mondo only defining MEs.

We can have a separate process branch. Of course some like inflammatory processes would be in GO. But metastasis and pathological processes would belong in MONDO or an analogous ontology. The NCIT division between pathological process and disease/disorder makes sense here.

```
 / NCIT:C17828 ! Biological Process
  is_a NCIT:C16956 ! Pathologic Process *** 
   is_a NCIT:C17747 ! Disease Progression
    is_a NCIT:C17609 ! Tumor Progression
     is_a NCIT:C19987 ! Cancer Progression
   is_a NCIT:C18264 ! Pathogenesis
    is_a NCIT:C18121 ! Tumorigenesis
     is_a NCIT:C19387 ! Cancer Cell Growth
   is_a NCIT:C19388 ! Cancer Cell Growth Regulation
    is_a NCIT:C26040 ! Tumor Suppression
    is_a NCIT:C29895 ! Inhibition of Cancer Cell Growth
     is_a NCIT:C21019 ! Suppression of Cancer Cell Invasion
   is_a NCIT:C21065 ! Cell Stress Process
    is_a NCIT:C21066 ! Cellular Stress
    is_a NCIT:C21067 ! Cellular Stress Response
   is_a NCIT:C21188 ! Tumor-Associated Process
    is_a NCIT:C17609 ! Tumor Progression
     is_a NCIT:C19987 ! Cancer Progression
```

**Comment by dosumis** [comment]
> > > We can explore the multi-root idea, but what I would like to avoid is having shadow hierarchies, e.g. malignant neoplasms as MEs, then a parallel cancer branch.

> > I don't see this as a problem, as long as it is entirely patternised.  With sufficient axiomatization for annotation (e.g. mapping from HCA schema to triples), we can potentially bridge between branches.

> I can't see any way of doing this without introducing massive confusion. How would the disease structures be named for the disposition with material basis 'neoplasm'? I just don't see the use case for naming both.

Me neither.  I'm not dogmatically pushing 3 terms for everything - I think the choice of terms to add should all be use-case driven.  In the case of cancer, I can see clear use cases for distinguishing ME and process but not disposition (despite the esoteric upper-ontology arguments for this).  In contrast, I can think of reasonable use cases for treating genetic diseases as predispositions.

**Comment by cmungall** [comment]
OK, good, I agree.

Yes, there are definitely some diseases that seem like they might more naturally fit as predispositions. I think it would be hard to do that in the general case for genetic diseases. We often have a triad of genericX, inheritedX and acquiredX, it would be odd to sequester the inherited form in its own branch. But for things like OMIM susceptibility entries, there is a good argument that should be treated differently. But equally these could be treated as MEs at the chromosomal level.

**Comment by nicolevasilevsky** [comment]
Can this be closed?

**Comment by nicolevasilevsky** [comment]
It's been 3.5 years since there were any comments, so I will close this ticket. Please reopen if needed.
