### ISSUE TITLE
tenosynovial giant cell tumor, diffuse type and pigmented villonodular synovitis [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4610]
**Mondo term (ID and Label)**
MONDO:0024686  tenosynovial giant cell tumor, diffuse type

**Reason for deprecation**
NCIT: [C3401](http://purl.obolibrary.org/obo/NCIT_C3401) 
and Orphanet:66627 suggest these terms are synonyms.
UMLS maps them to the same CUI- C0039106

**Term to be merged with**
MONDO:0006906 pigmented villonodular synovitis (though NCI says this is an 'antiquated synonym' https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/concept_details.jsf?dictionary=NCI_Thesaurus&version=22.02d&code=C3401&ns=ncit&type=synonym&key=null&b=1&n=0&vse=null# )

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
note to self:
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0024686 MONDO:0006906 -o -f obo mondo-edit.obo`

**Comment by nicolevasilevsky** [comment]
Thanks @kanems I'll use tenosynovial giant cell tumor, diffuse type as the primary label

**Comment by nicolevasilevsky** [comment]
@kanems upon a closer look, I am not sure these two terms should be merged. The definitions say one is benign and the other is aggressive and infiltrating.

**Comment by nicolevasilevsky** [comment]
I'll ask NCIt what their throughts are.

**Comment by nicolevasilevsky** [comment]
From NCIT:
The NCI Thesaurus group does not have any direct input to Mondo.

In NCI Thesaurus we have Pigmented Villonodular Synovitis as a synonym with 'tenosynovial giant cell tumor, diffuse type' and it is classified as benign.

**Comment by nicolevasilevsky** [comment]
@kanems I'll wait to see what Orphanet says too, but sounds like you are correct and these should be merged.

**Comment by nicolevasilevsky** [comment]
Upon looking more closely at Orphanet, I see Pigmented villonodular synovitis is a synonym of Tenosynovial giant cell tumor (Orphanet:66627).

I will follow NCIt and do the merger as you proposed, thanks @kanems!
