### ISSUE TITLE
Suggestions for new x-ref with SNOMED-CT and MedDRA

### ISSUE THREAD

**Issue by nbosc** [monarch-initiative/mondo#4614]
ID | x-refs
MONDO:0100053 | MedDRA:10002198
MONDO:0100053 | SCTID39579001
MONDO:0005149 | MedDRA:10037400
MONDO:0021553 | MedDRA:10028527
MONDO:0018109 | MedDRA:10019772
MONDO:0001117 | MedDRA:10027496
MONDO:0021084 | MedDRA:10047518
MONDO:0015346 | MedDRA:10084303

Thanks

**Comment by nicolevasilevsky** [comment]
[ROBOT template](https://docs.google.com/spreadsheets/d/1GaBIuyVvTbQlFIWB7Y6I2d_IuIPQNCV4q_hix2lBPQk/edit#gid=1650269388)
