### ISSUE TITLE
tyrosinemia of the newborn classification

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#4615]
this looks odd:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/50745/158416603-ff5686bf-beaf-4c4a-971d-79c1b184bc1c.png">

I think the classification is likely correct but the labeling should be changed

**Comment by nicolevasilevsky** [comment]
I reclassified tyrosemia of newborn as a child of tyrosemia:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/6722114/204411701-dc185164-c8f5-44c3-a25d-31d4565e3d35.png">

**Comment by nicolevasilevsky** [comment]
please reopen if other action items are needed
