### ISSUE TITLE
MONDO:0008791 isolated anencephaly/exencephaly ? [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4616]
**Mondo term (ID and Label)**
MONDO:0008791 isolated anencephaly/exencephaly

**Reason for deprecation**
"[comment](https://www.ebi.ac.uk/ols/search?q=comment&exact=true&type=property&ontology=mondo)
This will be obsoleted in the 2021-12-01 release. The term will be split into two terms: MONDO:8000007 anencephaly 1 and MONDO:0023893 anencephaly. "
But then lower down it says "[scheduled for obsoletion on or after](https://www.ebi.ac.uk/ols/search?q=scheduled%20for%20obsoletion%20on%20or%20after&exact=true&type=property&ontology=mondo)
2022-12-01"
(So the scheduled obsoletion dates seem to vary by year- 2021 vs 2022)

And Aencephaly seems to be MONDO:0000819 , not MONDO:0023893.

**Suggested term to consider**
Aencephaly  MONDO:0000819 ?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems, these are probably typos, I'll look into this asap

**Comment by nicolevasilevsky** [comment]
Hm, okay, seems like some of this was already done - we already created the anencephaly class that is equivalent to the OMIMPS (OMIMPS:206500).

I will just rename 'isolated anencephaly/exencephaly' to anencephaly 1, because that corresponds to gene-specific form of the disease.
