### ISSUE TITLE
term reclassification : review

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4620]
When obsoleting high-level terms, I had to reclassify some terms that didn't have parents. 
@pnrobinson  and @ahamosh could you please check that the following reclassifications are correct, please? If they are not correct, please advise. Thank you! 

- **'celiac trunk compression syndrome'** (MONDO:0017388) 
was made a child of : 'cardiovascular disorder' (MONDO:0004995) 
based on :  https://www.ncbi.nlm.nih.gov/books/NBK470601/

- **'fibroosseous pseudotumor of the digits'** (MONDO:0004482)
was made a child of :  benign soft tissue neoplasm (MONDO:0044335) 
based on : https://pubmed.ncbi.nlm.nih.gov/26388010/

**Comment by pnrobinson** [comment]
seems reasonable to me.

**Comment by sabrinatoro** [comment]
Thank you @pnrobinson
