### ISSUE TITLE
MONDO:0004983 'azoospermia'

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4623]
**Mondo term (ID and Label)**
MONDO:0004983 'azoospermia'

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
Current def: 'Complete absence of spermatozoa in the semen.' [ NCIT:P378 ] (I cannot find P378 in NCI Thesaurus)

I am really unsure what to do with this term, because both the name and definition seem to be inconsistent with synonym ("spermatogenic failure" from the OMIM PS258150) and children terms (e.g.: MONDO:0009461  'male infertility due to large-headed multiflagellar polyploid spermatozoa' which is, by definition provided from Mondo, not the Absence of sperm, but rather presence of sperm with abnormal morphology (though it is not explicitly stated that these are observed in semen) )

Perhaps this should be a rename /revise textual definition combo request?
Use the name "spermatogenic failure" ? 
And/Or add ORPHA:399775 "Male infertility with spermatogenesis disorder" (I cannot find where else this might be mapped in Mondo) 

***potential Definition***: from https://disease-ontology.org/?id=DOID:0070188 - "A male infertility characterized by disruption of the process of sperm development from diploid cells into mature haploid spermatozoa." https://pubmed.ncbi.nlm.nih.gov/30656449/ 

This would be sufficiently broad to describe multiple clinical observations (abnormally formed or absent sperm) and multiple causes.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I think azoospermia should be split out into a separate class and this class should be equivalent to the OMIMPS spermatogenic failure.

- [ ] rename azoospermia to spermatogenic failure to match OMIMPS
- [ ] rename MONDO_0009461 'male infertility due to large-headed multiflagellar polyploid spermatozoa' to spermatogenic failure 5 (to match OMIM)
- [ ] create new class for azoospermia
