### ISSUE TITLE
MONDO:0006832 and MONDO:0016358 [Merge or restructure?]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4633]
**Mondo term (ID and Label)**
MONDO:0016358 limited cutaneous systemic sclerosis
and/or MONDO:0006832  limited scleroderma

**Reason for deprecation**
Evidence supporting a Merge: 
- UMLS treats these two as synonyms (SCIT 299276009 and 298285004 are both on C0748540)
- ORPHA: 220402 "Limited cutaneous systemic sclerosis"   Points to UMLS C0748540 as "exact" match and says this is a "subtype of systemic sclerosis"
- MeSH: D045745 "Scleroderma, Limited" aka "Limited systemic scleroderma" definition is  "The least progressive form of SYSTEMIC SCLERODERMA with _skin_ thickening restricted to the face, neck and areas distal to the elbows and/or knees, sparing the trunk.  The CREST SYNDROME is a form of limited scleroderma." So while 'cutaneous' involvement may not be specified in the disease name, it seems to be inherent in the disease definition. 

Evidence supporting restructuring:
- SNOMED 299276009 at http://purl.bioontology.org/ontology/SNOMEDCT/299276009 is displayed a broader
term to  298285004  (However, that is the ONLY child concept)

Evidence suggesting SOME kind of review: CREST syndrome (MONDO:0019563) is a child of BOTH MONDO:0006832 and MONDO:0016358

A couple of references to review- https://www.uofmhealth.org/conditions-treatments/rheumatology/classification-scleroderma
 This classifies System Scleroderma as either _Diffuse_ or _Limited_ based on location of the affected skin (limited spares the trunk) This is supported by the pre-print PDF of this article- https://pubmed.ncbi.nlm.nih.gov/35131402/ "SSc is clinically classified as limited cutaneous (lc)SSc and diffuse cutaneous (dc)SSc, each with a distinct distribution of skin involvement, systemic manifestations and prognosis." )

**Term to be merged with**
Again, not sure if this is a merge or a restructure, but I think the evidence favors a Merge (perhaps after contacting SNOMED?); probably could use another set of eyes to review these concepts and Xrefs. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@sabrinatoro when you have a chance, could you review this and determine if we should merge these terms.
@kanems thanks for reporting this.

**Comment by sabrinatoro** [comment]
I agree : 'limited scleroderma'(MONDO:0006832) appears to be the same concept as 'limited cutaneous systemic sclerosis' (MONDO:0016358) and therefore these terms should be merged.
