### ISSUE TITLE
Identified 6 prefixes not recognized by Bioregistry

### ISSUE THREAD

**Issue by cthoyt** [monarch-initiative/mondo#4638]
The following 6 prefixes aren't recognized by the Bioregistry:

| prefix       |   count | example_node_id                                | example_xref                                                                       |
|--------------|---------|------------------------------------------------|------------------------------------------------------------------------------------|
| PO_GIT       |      43 | http://purl.obolibrary.org/obo/PO_0009012      | PO_GIT:185                                                                         |
| NIFSTD       |      18 | http://purl.obolibrary.org/obo/MONDO_0005035   | NIFSTD:birnlex_12633                                                               |
| SUBSET_SIREN |      15 | http://purl.obolibrary.org/obo/FOODON_03309823 | SUBSET_SIREN:F9823                                                                 |
| url          |       3 | http://purl.obolibrary.org/obo/MONDO_0019754   | url:https://rarediseases.info.nih.gov/diseases/9644/multicentric-castleman-disease |
| SCITD        |       1 | http://purl.obolibrary.org/obo/MONDO_0100470   | SCITD:991000119106                                                                 |
| MTH          |       1 | http://purl.obolibrary.org/obo/MONDO_0011438   | MTH:217                                                                            |

1. I think `PO_GIT` refers to the plant ontology's git. If these are imported terms, then I guess they shouldn't be reported here.
2. NIFSTD is from the neurolex/birnlex/etc. that is super difficult to figure out.  Could use https://bioregistry.io/registry/birnlex
3. Not sure what SUBSET_SIREN is at all. If it's imported from FOODON then I guess it's not possible to address this in MONDO
4. URL probably should be written a different way. 
5. SCITD looks like a typo for SCTID. 
6. Not sure what MTH is

**Comment by matentzn** [comment]
Will be Fixed By #4597

**Comment by matentzn** [comment]
@cthoyt:

- PO_GIT: Issue need to be filed here https://github.com/Planteome/plant-ontology/issues
- SUBSET_SIREN: Need to be filed here: https://github.com/FoodOntology/foodon/issues

**Comment by cthoyt** [comment]
I think I tried to convince the PO team to stop doing this and to use better relationships to directly link to their issue tracker, unsuccessful. No idea about the other one. Would rather someone else take care of this if possible

**Comment by cthoyt** [comment]
SIREN has been resolved in https://github.com/biopragmatics/bioregistry/pull/718
