### ISSUE TITLE
[Obsolete] MONDO_0015879 'non-syndromic diaphragmatic or thoracic malformation' and MONDO_0015880 'syndromic diaphragmatic or thoracic malformation'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4648]
**Mondo term (ID and Label)**
MONDO_0015879 'non-syndromic diaphragmatic or thoracic malformation'
MONDO_0015880 'syndromic diaphragmatic or thoracic malformation'

**Reason for deprecation**
Orphanet grouping class that groups by features. Out of scope for Mondo

**Suggested term to consider**
MONDO:0015929 thoracic malformation
MONDO:0005728  'diaphragm disorder'

Related to https://github.com/monarch-initiative/mondo/issues/4111

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
We should make sure to go through the children before we obsolete. I think it will require some reclassification.
