### ISSUE TITLE
Is intellectual disability, XMEN-linked 88 a typo?

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#4677]
**Mondo term (ID and Label):**
MONDO:0010454/ intellectual disability, XMEN-linked 

**Suggested new label:**
intellectual disability, X-linked 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**

**Comment by nicolevasilevsky** [comment]
I think so!
