### ISSUE TITLE
merge MONDO:0009412 scurvy

### ISSUE THREAD

**Issue by sierra-moxon** [monarch-initiative/mondo#4684]
**Mondo term (ID and Label)**
MONDO:0006661 ascorbic acid deficiency
MONDO:0009412 scurvy

**Reason for deprecation**
MONDO has different terms for Ascorbic Acid Deficiency and Scurvy, with no relation between them that I can see.    I am out of my depth here, but I notice many sources treat these as the same.  Does anybody understand why they're considered distinct in MONDO?

**Your nano-attribution (ORCID)**
0000-0002-9491-7674 - Christopher Bizon

If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
MESH has 2 different entries 
D001206 (Ascorbic acid deficiency) and D012614 (scurvy)
According to MESH:
- Ascorbic acid deficiency frequently develops into SCURVY in young children fed unsupplemented cow's milk exclusively during their first year. It develops also commonly in chronic alcoholism.
- Scurvy: severe deficiency of vitamin C

For what I can say, the difference between these 2 terms is the severity of the deficiency. 
If we decide to keep these terms separate, we should make 'scurvy' a child of 'ascorbic acid deficiency' (though we would have a single child issue)

**Comment by nicolevasilevsky** [comment]
I think these should be merged based on a literature search, it seems like these are used synonymously, like Sierra said ([PMID:29630239](https://www.ncbi.nlm.nih.gov/books/NBK493187/)).

MONDO:0006661 ascorbic acid deficiency is obsoleted in DO.
