### ISSUE TITLE
Question: should obsoleted classes contain equivalence axioms?

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/mondo#469]
I'm noticing some obsoleted classes still contain equivalentClass axioms to other classes, and therefore end up as clique leaders in scigraph:
https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/MONDO:0023807

https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/neighbors/MONDO%3A0023807?depth=1&blankNodes=false&relationshipType=equivalentClass&direction=BOTH

Is this intended or a bug in the pipeline?  This is for the 10-26-18 release.

**Comment by cmungall** [comment]
not intended. These should be skos exact match but not equivalent

**Comment by kshefchek** [comment]
two more:
MONDO:0009117
MONDO:0011750
