### ISSUE TITLE
Glutaric acidemia IIA, B, C

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#4691]
[NAA10-related syndrome](https://omim.org/entry/231680?search=231680&highlight=231680)

Can we related subterms such as multiple acyl-CoA dehydrogenase deficiency, mild type
to the OMIM subtypes Glutaric acidemia IIA, B, C ?

**Comment by nicolevasilevsky** [comment]
@pnrobinson are you asking for the included terms in the [OMIM entry](https://omim.org/entry/231680) to be split out as separate terms in Mondo?

I see we have 'multiple acyl-CoA dehydrogenase deficiency, mild type' and 'multiple acyl-CoA dehydrogenase deficiency, severe neonatal type' in Mondo that come from Orphanet, but I don't know which subtype that corresponds with.
