### ISSUE TITLE
[Merge] MONDO:0005982 tinea infection and 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4700]
**Mondo term (ID and Label)**
MONDO:0005982 tinea infection

**Reason for deprecation**
@sabrinatoro can you look into this - are these two terms equivalent? There is an editor not on tinea infection to obsolete it. Related to #3811 

**Term to be merged with**
MONDO:0002041 'fungal infectious disease'

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I don't think these terms should be merged. 'tinea infection' (MONDO:0005982) is a 'fungal infectious disease' that is specific to the skin. 
I suggest that we : 
- add equivalent to   'tinea infection' (MONDO:0005982): 'fungal infectious disease' and 'disease has location' some skin
- add the following children to  'tinea infection' (MONDO:0005982)
  - tinea favosa - MONDO:0005983
  - deep seated dermatophytosis - MONDO:0021660
  - dermatophytosis - MONDO:0004678

**Comment by nicolevasilevsky** [comment]
Sounds great, thanks @sabrinatoro! I'll assign this to you, please go ahead with the proposed action items.
