### ISSUE TITLE
Potter Sequence

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#471]
We currently have an entry for Potter Syndrome, GARD includes 3 subtypes. Should these be added? What is the relationship to OMIM:263200?

https://rarediseases.info.nih.gov/diseases/4462/potter-sequence
https://en.wikipedia.org/wiki/Potter_sequence

Is this a disease or a co-occurrence of phenotypes?

HPO has Potter facies, which would be an individual endophenotype

**Comment by nicolevasilevsky** [comment]
@GARDinfocenter and @ahamosh 
Do you think it would be accurate to classify these terms as subclasses of MONDO_0001558 'Potter syndrome'?

-MONDO_0001558 'Potter syndrome'
--MONDO_0033004 'polycystic kidney disease 4'
--MONDO_0018470 'renal agenesis (disease)'
--MONDO_0008263 'polycystic kidney disease 1'

@GARDinfocenter, Chris mentioned above that you have 3 subtypes - are those the subtypes listed above correct? I got those from the wikipedia article that Chris linked above.

Thanks!

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky -There seems some debate among the community as to whether Potter sequence and Potter syndrome should be used interchangeably. Some feel that "syndrome" is not the best term to use. For this reason, GARD has decided to list Potter sequence as the primary term and Potter syndrome and Oligohydramnios sequence as synonyms to it. 

Potter sequence refers to a characteristic group of features that result from the lack of the amniotic fluid and has many causes, including all the ones mentioned above as well as others. Therefore, we do not consider the above subtypes. We think that the concept of subtypes may have arisen from the numbering system that has been proposed by some to differentiate the different "forms" of Potter sequence. 

Although we do not list MONDO_0033004 'polycystic kidney disease 4', MONDO_0018470 'renal agenesis (disease)', and MONDO_0008263 'polycystic kidney disease 1 as subtypes of Potter sequence. We do acknowledge that these are diseases in which Potter sequence can be observed.  We currently list polycystic kidney disease and renal agenesis. 

Thanks,
Maria

**Comment by nicolevasilevsky** [comment]
Thank you Maria (@GARDInfoCenter)!

Action items:
- [ ] relabel to Potter sequence
- [ ] make Potter syndrome an exact syn

I will **not** add subclasses to Potter sequence, as I mentioned above.

There does seem to be a causal relationship between polycystic kidney disease and renal agenesis, I will add axioms to encode this and @cmungall can let me know if this is the correct approach.

@GARDInfoCenter I noticed a typo on your [webpage](https://rarediseases.info.nih.gov/diseases/4462/potter-sequence):
In some cases, the primary cause of Potter sequence a genetic abnormality. 
Should be:
In some cases, the primary cause of Potter sequence **_is_** a genetic abnormality.

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky Thanks. We'll fix the typo.

**Comment by nicolevasilevsky** [comment]
Talking to Shahim, sounds like the casual relationships I added were not the correct approach. He is going to look at this further.
