### ISSUE TITLE
New term: CSGALNACT1 deficiency

### ISSUE THREAD

**Issue by jpgourdine** [monarch-initiative/mondo#474]
## Preferred term label
CSGALNACT1   deficiency

## Synonyms
chondroitin sulfate N-acetylgalactosaminyltransferase-1 deficiency

## Textual definition

CSGALNACT1-deficiency is a congenital disorder of glycosylation (CDG) due to a large intragenic deletion, and a p.Pro384Arg missense mutation in CSGALNACT1 resulting in prenatal‐onset disproportionate short stature, joint laxity, and radiographic findings typical ([PMID: 27599773](https://doi.org/10.1002/humu.23070 ))

## Suggested parent term

http://purl.obolibrary.org/obo/MONDO_0003847

## Attribution
https://orcid.org/0000-0001-9969-8610

**Comment by nicolevasilevsky** [comment]
additional syn: Desbuquois dysplasia associated with CSGALNACT1

**Comment by nicolevasilevsky** [comment]
@jpgourdine - this definition is not a complete sentence, could you update it? thanks!

**Comment by nicolevasilevsky** [comment]
@jpgourdine please see Peter's comments on #475

**Comment by nicolevasilevsky** [comment]
not sure if this is still need, I am closing the ticket but please reopen if needed.
