### ISSUE TITLE
PIGQ-CDG 

### ISSUE THREAD

**Issue by jpgourdine** [monarch-initiative/mondo#475]
For new term requests, please provide the following information:

## Preferred term label
PIGQ-CDG

## Synonyms

severe early-onset epilepsy associated with PIGQ mutation

## Textual definition

severe early-onset epilepsy with a burst-suppression electroencephalogram consistent with Ohtahara Syndrome (PMID: 24463883)
## Suggested parent term

 http://purl.obolibrary.org/obo/MONDO_0002320

## Attribution
http://orcid.org/0000-0001-9969-8610

**Comment by nicolevasilevsky** [comment]
@jpgourdine 
Looking at this paper, it seems like this is a novel mutation seen in Ohtahara Syndrome, which is MONDO_0016021 'early infantile epileptic encephalopathy'

Do you think this should be a synonym?

**Comment by jpgourdine** [comment]
Let me look into it.

**Comment by jpgourdine** [comment]
Not synonym but maybe sibling as Ohtahara Syndrome is [ARX-related epileptic encephalopathy](https://www.ncbi.nlm.nih.gov/pubmed/19738637) while not PIGQ.

**Comment by nicolevasilevsky** [comment]
maybe we could remove the superclass assertion for MONDO_0015921 'arx-related epileptic encephalopathy'? Looks like this comes from Orphanet.

**Comment by pnrobinson** [comment]
This a an n=1 case where OMIM has said -- hold off until we see a second case to be sure of this disease association. 
According to OMIM, Epileptic encephalopathy, early infantile, 1 is the recommended name for a disease related to mutation in ARX. The disease has an alternative name of Ohtahara Syndrome. Therefore, the definition (severe early-onset epilepsy with a burst-suppression electroencephalogram consistent with Ohtahara Syndrome) does not make sense. 
In general, we really should defer to OMIM as the naming authority. If we start to make new names like this it will cause infinite confusion in the community.
OMIM has also very convincingly argued against the use of gene names in disease names and I completely agree.
We really need to write down policies for this -- if we do things piecemeal with different decisions in each issue, we will wind up with a completely inconsistent ontology. 
I would suggest closing this item with no new term. At most it is an n=1 case.

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson! 

For @jpgourdine's paper, he has a supplemental table that has a list of genetic diseases related to glycans, and he listed all the associated Mondo IDs for each disease. Do you think he should just indicate N/A for the Mondo ID, or remove this disease from the list?

This is related to #479, which is a similar type of disease. @ShahimEssaid and I created a PR to added this term today, but sounds like we should discuss if we actually want to add this disease? There are a lot of similar diseases in this branch - that are named after mutations in specific genes that cause a 'congenital disorder in glycosylation'

**Comment by pnrobinson** [comment]
The genetics community largely regards OMIM as the authority about naming. We should not rename diseases in this way. At most, they should be related synonyms. Have we looked in OMIM to see if these diseases are already there? Also, we still need to have a strategy for n=1 cases, which should not be registered as full fledged diseases. I would

**Comment by mellybelly** [comment]
We need a strategy for n-of-1 and coordination with OMIM, Orphanet, and other resources. This is part of the Phenomics grant, but we can get started on a plan in the meantime. Agree about not using gene names in disease names, however glycan diseases may need some additional rules. @jpgourdine

**Comment by nicolevasilevsky** [comment]
Not sure if this is still needed, so I am going to close this ticket. Please reopen if needed.
