### ISSUE TITLE
IgG4-related hepatopathy

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4759]
**Mondo term (ID and Label):**
MONDO_0019528 'IgG4-related hepatopathy'

**Suggested new label:**
Inflammatory pseudotumor of the liver

I don't know where the label  'IgG4-related hepatopathy' came from but it seems incorrect. The Orphanet label is Inflammatory pseudotumor of the liver.

Should also review the parent classification and consider reclassifying this term.

**Comment by sabrinatoro** [comment]
I agree, I cannot find where the "IgG4-related" comes from. 
the only x-ref is orphanet:90003. This x-ref does not refer to IgG4 at all. 
I think this term should be renamed.
