### ISSUE TITLE
MedGen conflicts in OMIM:Mondo mappings

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4769]
Hi @nicolevasilevsky et al!
We are preparing some reports regarding OMIM:Mondo relationships that seem to differ between MedGen and Mondo's mappings. In reviewing our data we have a few different types of conflicts: 1) Both Mondo and MedGen have the MIM number but disagree on where it should map relative to a CUI/Mondo ID based on names and other X-refs; 2) Mondo does not report the MIM number at all; 3) MedGen does not report the MIM number at all (out of scope for MedGen- potentially not an active disease/condition record)

Before we finalize the reports for these three groups, we want to understand what is in scope for Mondo from OMIM. From category 2 above, there are these groups of terms:
- Blood group phenotypes
- Quantitative trait loci -type named records (In OMIM they may display with % symbol, so these are phenotypes/conditions with unknown molecular basis)
- Terms that are closer to phenotype descriptions rather than disease entities (i.e. https://www.omim.org/entry/128950) which are most likely in scope for HPO
- Drug metabolism/response phenotypes ( i.e. https://www.omim.org/entry/100675 ) 
- True disease records 
Are any of these out of scope for Mondo?

**Comment by nicolevasilevsky** [comment]
Hi @kanems 
here is a list of excluded OMIM classes in Mondo: https://github.com/monarch-initiative/mondo/blob/master/src/ontology/omim-exclusion-set.obo

This list was last updated in 2020, and we did not document our reasons at that time. 

@kanems If you'd like to discuss this further, could you attend one of our weekly calls to further explain what is needed? Thank you!

**Comment by kanems** [comment]
@nicolevasilevsky - this is helpful, thank you. I'll see what we can do to filter out these items before sending the reports. 
I also have not forgotten @matentzn 's pending invitation to discuss the CUI mapping conflicts on #4680  but I am waiting for a response from our developers that someone would be available for a call with you all. Presumably Fridays are your standing meeting times?

**Comment by nicolevasilevsky** [comment]
Yes! Friday at 9am PT/12pm ET. (note, we won't have a call on Friday, 05/06). It would be great if you were available to join one of our calls too. :)

Is it okay if I close this ticket?

**Comment by kanems** [comment]
@nicolevasilevsky if it's easier, sure, but we are hoping to have OMIM mapping conflicts ready to report in a week or so. I can make a new ticket at that time.

**Comment by nicolevasilevsky** [comment]
Sounds good, thanks @kanems! :)
