### ISSUE TITLE
SSR3-CDG

### ISSUE THREAD

**Issue by jpgourdine** [monarch-initiative/mondo#479]
For new term requests, please provide the following information:

## Preferred term label
SSR3-CDG

## Synonyms

SSR3 deficiency

## Textual definition

SSR3 deficiency combines clinical phenotypes such as Seizure, Intelectual Disability,  developmental delay, microcephaly and abnormal brain structure

PMID: 28484880 

[PMID: 27010055](https://www.ncbi.nlm.nih.gov/books/NBK453018/)

--
## Suggested parent term

 http://purl.obolibrary.org/obo/MONDO_0005500

## Attribution

http://orcid.org/0000-0001-9969-8610

**Comment by nicolevasilevsky** [comment]
additional syn: SSR3 congenital disorder of glycosylation

**Comment by nicolevasilevsky** [comment]
Revised def:
A congenital disorder of glycosylation with a SSR3 deficiency that affects the brain, lungs and  gastrointestinal system, and presents with clinical phenotypes such as seizures, intellectual disability, developmental delay, microcephaly and abnormal brain structure.

**Comment by nicolevasilevsky** [comment]
Shahim added this term as MONDO_0300000, it is pending approval
