### ISSUE TITLE
Make use of "MONDO:otherHierarchy" xref sources?

### ISSUE THREAD

**Issue by sierra-moxon** [monarch-initiative/mondo#4794]
**Mondo term (ID and Label):**
(MONDO:0000313, hypophosphatemia)

**Xref that should be fixed (ID and label):**
HP:0002148 {source:"MONDO:otherHierarchy} 

**Your nano-attribution (ORCID)**

0000-0002-8719-7760 @sierra-moxon via 
0000-0002-9491-7674 - @cbizon
--

**Other comments:**

Really, this is a question ticket...

Is it possible that the otherHierarchy tag for this is made more precise, to indicate when the HP term is "the 100% full phenotype for that disease"?  
Alternatively, could we have a skos match type for this kind of HP term listed in the file as well?  (similar to the NCIT xref in this term example where we also have a property_value of "exact match").

the use case stems from the NCATS Translator project where a user could find annotations either from a disease or phenotype point of view (we could enable this via mappings like this one as long as we knew what kind of mapping we were using, aka: exact, narrow, broad, don't-use, etc.).

**Comment by sierra-moxon** [comment]
@sabrinatoro - this is the ticket I hope captures the use case w/re to 'otherHierarchy' tags this morning. :)

**Comment by sabrinatoro** [comment]
tagging @nicolevasilevsky and @matentzn

**Comment by nicolevasilevsky** [comment]
Great question @sierra-moxon. I'll add this to our technical call agenda and discuss with @matentzn and @cmungall

**Comment by matentzn** [comment]
We will add an SSSOM export for MONDO-HP, but this wont happen before mid May; it will happen!

**Comment by matentzn** [comment]
Closing in favour of #4838
