### ISSUE TITLE
merge MONDO_0011910 'autosomal dominant limb-girdle muscular dystrophy type 1C' with MONDO_0019947 'rippling muscle disease 2'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#480]
Obsolete MONDO_0011910 'autosomal dominant limb-girdle muscular dystrophy type 1C'. Should be replaced by MONDO_0019947 'rippling muscle disease 2'.

OMIM 607801 moved to 606072, see  https://omim.org/entry/607801

From [Donna Maglott's slides](https://docs.google.com/presentation/d/14rlypao32KhtnQp92OFPqOpZmeTHInZEXR7_7boNy9Y/edit#slide=id.p10)

**Comment by cmungall** [comment]
Can you go ahead and make a PR for this? Note after you run the merge command we may want to mark the LGMD syns as deprecated.

What are @ORDO's plans here? This is still in the current orphanet:

https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=265

**Comment by nicolevasilevsky** [comment]
created PR #481 

How do we mark synonyms as deprecated?

**Comment by nicolevasilevsky** [comment]
should I have moved all the existing synonyms from the term that was obsoleted to term it was replaced with?

**Comment by cmungall** [comment]
See granulomatosis with polyangiitis for examples of deprecated syn axiom annotations
