### ISSUE TITLE
spinal muscular atrophy, type 1 MONDO:0009669 question on exactmatch synonym spinal muscular atrophies of childhood, which itself represents more than one subtype

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#4808]
**Mondo term (ID and Label):**
spinal muscular atrophy, type 1 
http://purl.obolibrary.org/obo/MONDO_0009669

**Xref that should be fixed (ID and label):**
[has exact synonym] spinal muscular atrophies of childhood - should this be deleted / or move to a new MONOD:ID?

**Other comments:**
looking at the xrefs linked https://www.ontobee.org/ontology/DOID?iri=http://purl.obolibrary.org/obo/DOID_13137 
https://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C98670
https://www.ontobee.org/ontology/DOID?iri=http://purl.obolibrary.org/obo/DOID_0060160

I am not sure spinal muscular atrophy, type 1 MONDO:0009669 should have 'spinal muscular atrophies of childhood' as an exactatch

I think the issue might come from https://meshb-prev.nlm.nih.gov/record/ui?ui=D014897 that lumps all subtypes together eg: not just SMA type 1 which currently  MONDO:0009669 represents and includes <Infantile spinal muscular atrophy> which is a synonym from ORDO/OMIM

So my question is should <spinal muscular atrophies of childhood> remain as an exactmatch in MONDO:0009669 spinal muscular atrophy, type 1, or/and should <spinal muscular atrophies of childhood>  have it's own new MONDO: ID? (although I am not convinced by that!)

**Comment by sabrinatoro** [comment]
According to OMIM, there are 4 types of SMA depending on the age of onset, the maximum muscular activity achieved, and survivorship: 
- type I, severe infantile acute SMA, or Werdnig-Hoffman disease; 
- type II (253550), or infantile chronic SMA; 
- type III (253400), juvenile SMA, or Wohlfart-Kugelberg-Welander disease; 
- type IV (271150), or adult-onset SMA.
There are therefore several SMA types that are recognized as 'spinal muscular atrophies of childhood' 

I agree that 'spinal muscular atrophies of childhood' should not be an exact synonym for 'spinal muscular atrophy, type 1' (MONDO:0009669]
I suggest that the synonym type be changed to "broad synonym"


In addition, the x-ref DOID:0060160 should not be "MONDO:equivalentTo" as it refers to the grouping parent term "childhood spinal muscular atrophy", grouping that we do not use in the Mondo classification.
 
@nicolevasilevsky: do you agree?

**Comment by nicolevasilevsky** [comment]
yes, I agree!
