### ISSUE TITLE
Primary label in OLS is abbreviation (LFS3)

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#482]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0012234

This appears to have been retired
Synonym:
LI-Fraumeni syndrome 3, Moved to 151623, LI-Fraumeni syndrome 3; LFS3, MOVED to 151623

-- consider if we need to add a Q/C step to check for OMIM "Moved to" entries, which will almost always require revision of the MONDO term.

**Comment by nicolevasilevsky** [comment]
these terms should be merged, I created a new ticket:
https://github.com/monarch-initiative/mondo/issues/1329
