### ISSUE TITLE
[Revise text def] autosomal recessive LGMD type 2Z (MONDO: 0014977)

### ISSUE THREAD

**Issue by marwa-elnagheeb** [monarch-initiative/mondo#4824]
**Mondo term (ID and Label)**
autosomal recessive limb-girdle muscular dystrophy type 2Z (MONDO: 0014977)

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
An autosomal recessive condition caused by pathogenic variant(s) of the POGLUT1 gene, encoding protein O-glucosyltransferase 1. It is characterized by progressive muscular dystrophy, primarily affecting the proximal muscles, resulting in difficulty walking. A characteristic finding of “inside-to-outside” fatty degeneration on muscle imaging has been noted in patients.

**Attribution:**
This is a request from the ClinGen LGMD GCEP.

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Supporting evidence: Servian-Morilla et al., 2020 (PMID: 1897643) and Servian-Morilla et al., 2016 (PMID: 27807076). 

Please also note that a separate request ticket has been submitted to update a portion of the Mondo term from 'type 2Z' to 'type R1' to reflect new nomenclature and reformed classifications of LGMDs (Straub et al., 2018, PMID: 30055862).

**Comment by sabrinatoro** [comment]
renaming issue is: https://github.com/monarch-initiative/mondo/issues/4822
