### ISSUE TITLE
capitalization questions in this path

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#4830]
**Mondo term (ID Label)**
MONDO:0022410

**Bug/Typo/Error description**
Should the highlighted examples be capitalized?
![image](https://user-images.githubusercontent.com/17743017/164542502-3d2d4c30-9b05-4ecf-8f39-376f92681b1d.png)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
> Should the highlighted examples be capitalized?

Yes! I'll fix
