### ISSUE TITLE
olecranon bursitis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#486]
Bursitis is not a bone disease, the bursa is a fluid-filled sac or saclike cavity, especially one countering friction at a joint.

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001557

**Comment by nicolevasilevsky** [comment]
this is not classified as a bone disease, it is a child of bursitis, limb disorder, and enthesopathy.

I think this can be closed.

**Comment by nicolevasilevsky** [comment]
Please reopen if needed :)
