### ISSUE TITLE
obsoleted exact match  MeSH ID for multifocal choroiditis  MONDO:0023833

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#4861]
**Mondo term (ID and Label):**
multifocal choroiditis
MONDO:0023833
http://purl.obolibrary.org/obo/MONDO_0023833

**Xref that should be fixed (ID and label):**
[database cross reference]
MESH:C537374 (MONDO:equivalentTo)

[exactMatch]
http://identifiers.org/mesh/C537374

**Other comments:**
MESH:C537347 has been obsoleted by MeSH
https://meshb.nlm.nih.gov/searchsearchMethod=FullWord&searchInField=ui&sort=&size=20&searchType=exactMatch&from=0&q=C537374
in favour of D000080364 
https://meshb.nlm.nih.gov/record/ui?ui=D000080364 

Do you want these sorts of MeSH instances reported?

Do you have any way of getting a monthly obsoleted list of IDs from MeSH and a list of replacement MeSH_IDs (I have asked but did not get an answer) so this sort of thing can be updated as a bulk update within MONDO (for those that are exact-match) 

Do I assume that a concept will default always to a descriptor (I don't think this is the case- as I see both in MONDO so assume there are some 'rare' events where MeSH reuse an ID but change the name)?

Sorry, I know you are not MeSH resource, but the resource seems to cause a lot headaches when trying to reconcile the entity type around disease! (to be expected, I know)
also links to #2073

**Comment by nicolevasilevsky** [comment]
Hi @lcdaugherty thanks for reporting this. I'll check in with Nico on our technical team about your questions and get back to you asap.

**Comment by nicolevasilevsky** [comment]
Note to self: I updated the xref for 'multifocal choroiditis'.

- [ ] Action item - question:
 
Do you want these sorts of MeSH instances reported?

Do you have any way of getting a monthly obsoleted list of IDs from MeSH and a list of replacement MeSH_IDs (I have asked but did not get an answer) so this sort of thing can be updated as a bulk update within MONDO (for those that are exact-match)

**Comment by lcdaugherty** [comment]
#2073

**Comment by nicolevasilevsky** [comment]
Hi @lcdaugherty, we would love it if you reported issues like these for now. If possible, if you could provide the issues in a google spreadsheet, that would be great.

We don't currently have a workflow to keep the MESH ingest up to date. It is on our list but it is not a super high priority at the moment.

I will close this ticket, but please reopen if you have additional questions.
