### ISSUE TITLE
Remove outdated terminology related to FMR1 and Fragile X

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/mondo#4883]
Please update FMR1 gene and any other terminology related to fragile x which contains, or references through abbreviation, the word 'retardation', which is outdated and offensive terminology. 

Please see this Cells article: https://www.mdpi.com/2073-4409/11/6/1044.

As a result of this article, HGNC has updated their definition of FRAXA to:
**fragile site, folic acid type, rare, fra(X)(q27.3) A** 
[Gene symbol report | HUGO Gene Nomenclature Committee (genenames.org)](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:3945)

And HGNC has updated **FMR1** to **Fragile X messenger ribonucleoprotein 1** [Gene symbol report | HUGO Gene Nomenclature Committee (genenames.org)](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:3775)

As it is understood, the fragile x protein (FMRP) will be updated in UniProt in line with the new gene definition, becoming **Fragile X messenger ribonucleoprotein 1**.

Updating the FRAXA, FMR1 and FMRP definitions is making a huge difference to how fragile x is perceived and understood around the world. Thank you for your help in updating the Mondo database, removing all references to mental retardation.

_Ticket submitted by: 
The Fragile X Society
Fragile X International_

**Comment by nicolevasilevsky** [comment]
Thanks for reporting this - we tried to replace all the usage of that word across Mondo but this must have crept in! I'll fix it asap
