### ISSUE TITLE
[Merge] MONDO:0004033	familial ovarian carcinoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4889]
**Mondo term (ID and Label)**
MONDO:0004033 | familial ovarian carcinoma

**Reason for deprecation**
duplicate

**Term to be merged with**
MONDO:0016248	familial ovarian cancer

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0004033 MONDO:0016248 -o -f obo mondo-edit.obo`

**Comment by kanems** [comment]
I apologize for not catching this on the obsoletion candidate list before this was released, but I don't think it's correct to equate ovarian carcinoma with ovarian cancer. (Generally speaking, even though 'carcinoma' may be used interchangeably with cancer in oncology community when that is the vast majority of  cases, I think it's appropriate to maintain the general vs. specific distinction if there are _any_ other subtypes under that cancer concept.)
https://magazine.medlineplus.gov/article/3-types-of-ovarian-cancer-explained#:~:text=There%20are%20three%20types%20of,outer%20surface%20of%20the%20ovary
also see https://www.cancer.gov/types/ovarian/hp (PDQs exist for multiple types of ovarian cancers, suggests that clinical management of these sub-types are different)
. I think MONDO:0004033 should be retained as an active, child entity to MONDO:0016248 (Not to mention that merging these two would say that MONDO:0004436 is a child of 'carcinoma' and while i'm not an oncologist or pathologist, I don't think carcinoma and lipoma are histologically/molecularly the same.

**Comment by nicolevasilevsky** [comment]
Thanks @kanems! I can create a new term for familial ovarian carcinoma, it will be available in the next release.
