### ISSUE TITLE
[Merge] MONDO:0009997	Roberts syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4901]
**Mondo term (ID and Label)**
MONDO:0009997	Roberts syndrome

**Reason for deprecation**
duplicate

**Term to be merged with**
MONDO:0100253	Roberts-SC phocomelia syndrome

**Comment by nicolevasilevsky** [comment]
I need to revisit this, see: https://github.com/monarch-initiative/mondo/issues/2553
https://omim.org/entry/268300

Also, the grouping class 'non-syndromic limb reduction defect' does not seem correct. This is related to the primary bone dysplasia ticket, see [spreadsheet](https://docs.google.com/spreadsheets/d/1gZjzQ1lW8tBcqVowHC_P_Vbka2Ghrwc9YS3MZQL3_2M/edit#gid=1522282848)

**Comment by nicolevasilevsky** [comment]
'SC phocomelia syndrome' should be merged into 'Roberts-SC phocomelia syndrome' as well. I added it to the obsoletion list.

**Comment by nicolevasilevsky** [comment]
> Also, the grouping class 'non-syndromic limb reduction defect' does not seem correct. This is related to the primary bone dysplasia ticket, see [spreadsheet](https://docs.google.com/spreadsheets/d/1gZjzQ1lW8tBcqVowHC_P_Vbka2Ghrwc9YS3MZQL3_2M/edit#gid=1522282848)

I think this is correct, I don't remember why I thought otherwise.

**Comment by nicolevasilevsky** [comment]
I don't think these should be merged. Closing. If anyone disagrees, please reopen, thanks!

**Comment by kanems** [comment]
Hi Nicole: why did you opt not to merge SC phocomelia syndome with the broader roberts-sc phocomelia syndrome? I dont see current sources in Mondo to support MONDO:0100282 as a separate concept anymore.

**Comment by nicolevasilevsky** [comment]
@kanems I'll look into this and get back to you asap.

**Comment by nicolevasilevsky** [comment]
Looking into this again, I do agree that MONDO:0009997 Roberts syndrome should be merged with MONDO:0100253 Roberts-SC phocomelia syndrome, this is what OMIM has done. (I don't remember my reasoning for closing this before).

**Comment by nicolevasilevsky** [comment]
it seems like 'SC phocomelia syndrome' should be merged into 'Roberts-SC phocomelia syndrome' as well, per OMIM.
