### ISSUE TITLE
Zlotogora-Ogur syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#492]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0009151

This is a complex syndrome that has OFC as a feature, but it should not be classiified as a type of OFC!

**Comment by nicolevasilevsky** [comment]
In OMIM, this is called CLEFT LIP/PALATE-ECTODERMAL DYSPLASIA SYNDROME https://www.omim.org/entry/225060

**Comment by nicolevasilevsky** [comment]
and Orphanet has renamed this to Orphanet:3253 Cleft lip/palate-ectodermal dysplasia syndrome

**Comment by nicolevasilevsky** [comment]
MONDO_0017911 'cleft lip/palate-ectodermal dysplasia syndrome' has been obsoleted from Orphanet, I'll merge it with MONDO_0009151 'Zlotogora-Ogur syndrome', following Orphanet
