### ISSUE TITLE
MONDO:0020718 congenital short bowel syndrome 1

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4921]
**Mondo term (ID and Label):**
MONDO:0020718 congenital short bowel syndrome 1

**Suggested new label:**
congenital short bowel syndrome, autosomal recessive
or
congenital short bowel syndrome due to CLMP variation (or mutation or loss of function or...?)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
OMIM calls it "Congenital short bowel syndrome", but since that would conflict with the Orphanet parent term, I could understand adding the inheritance pattern or a gene identifier or something else to make the distinction in Mondo (and prevent naming multiplicity/confusion for your end users ;-) ) but I don't see any use of "1" in OMIM for this disease record and it suggests there are other subtypes

Also the CUI x-ref needs updating: UMLS:C0021847  is for generic concept of "Intestinal Pseudo-Obstruction" and I don't think UMLS has a sufficiently narrow CUI for the AR form represented by the MIM record (distinct from the Orphanet term for 2 MIM records). May just need to drop the CUI x-ref for now. MedGen has generated a CN id, we can discuss the details of sharing those on our upcoming call.

**Comment by nicolevasilevsky** [comment]
good point, I'm not sure where the label with '1' came from!
