### ISSUE TITLE
Missing breast cancer sub-types

### ISSUE THREAD

**Issue by Odemsh** [monarch-initiative/mondo#4933]
I believe there are some breast cancer subtypes that are missing from the ontology:
- Triple positive breast cancer - or as it is referred to by the NCCN breast cancer guideline "HR-positive HER2 positive breast cancer"
- Hormone receptor-positive breast cancer (or HR-positive HER2-negative breast cancer) - this should include both estrogen-receptor and progesterone-receptor positive breast cancer

Additionally, while the progesterone receptor-positive\negative and HER2 positive\negative breast carcinoma are children of the "breast carcinoma by gene expression profile" term, the estrogen-receptor-positive\negative breast cancer is a direct child of the higher-level "breast carcinoma" term. 
It would be good to have some consistency here.

**Comment by sabrinatoro** [comment]
@Odemsh 
The changes will be in the next Mondo version as soon as we release it, which will be around July 1st, 2022.
It usually takes OLS (https://www.ebi.ac.uk/ols/ontologies/mondo) about 1-2 weeks after the release to display the latest version.
