### ISSUE TITLE
glaucoma 1, open angle, G

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#4936]
**Mondo term (ID Label)**
[glaucoma 1, open angle, G](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0012357&lang=en&viewMode=PreferredRoots&siblings=false) and related terms
[Glaucoma 1, open angle, I](https://omim.org/entry/609745) is not a hereditary form of glaucoma, it is a locus that confers increased risk for the complex (common) form of glaucoma. Also, the various grades of glaucoma (B-H) do not represent different diseases and are difficult to measure in the clinic (discussion with Dr Ladewig) and also are not specifically related to Glaucoma 1, open angle, I]

**Bug/Typo/Error description**
Suggestion -- 1) obsolete Glaucoma 1, open angle, I -- it is a susceptibility locus for the disease [open-angle glaucoma](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005338&lang=en&viewMode=PreferredRoots&siblings=false) rather than a separate disease
2) obsolete all of its subclasses, they are also not separate diseases
@ahamosh do you agree about the distinction between susceptibility locus and disease?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I'll go ahead and obsolete these terms. If there are further revisions needed, we can address them on another ticket, thanks!

**Comment by ValWood** [comment]
Hi,

there seems to be quite a lot of evidence that WDR36 is a causative gene for 
open angle, G (obsolete MONDO:0012357) 

PMID: 34681019
PMID: 29540704 Juvenile onset open-angle glaucoma (JOAG) 
PMID: 29104481 

val

**Comment by ValWood** [comment]
I guess it isn't conclusive and it's only an association at present.
