### ISSUE TITLE
[NTR] ClinGen Retina GCEP new terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4937]
See [spreadsheet](https://docs.google.com/spreadsheets/d/1LzszXSZACiwizWiuk3ctFLHGjG8JUwr5/edit#gid=928103981)

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/3898

**Comment by nicolevasilevsky** [comment]
@jennygoldstein

I have a question about this term:
NYX-related congenital stationary night blindness

From what I can see, there is nothing different about this from the existing Mondo class MONDO:0010690 'congenital stationary night blindness 1A'. I added this as an exact synonym and updated the def to match your definition, and added the parent class to that term: 'inherited retinal dystrophy'.

Thanks!

**Comment by jennygoldstein** [comment]
Hi Nicole,

That sounds fine. Thank you for checking.

Jenny

**Comment by jennygoldstein** [comment]
Hi Nicole,
I am so sorry - I misunderstood your last question. Is it possible to make the label "NYX-related congenital stationary night blindness" and have 'congenital stationary night blindness 1A' as a synonym? MONDO:0010690 

Thank you, and many apologies for any confusion.

Jenny

**Comment by nicolevasilevsky** [comment]
Hi @jennygoldstein Our team discussed this on the Mondo curation call and for a disease that is part of an OMIM phenotypic series, we want to use the OMIM names for consistency. In this case, congenital stationary night blindness 1A is part of the OMIM phenotypic series MONDO:0044749 'X-linked congenital stationary night blindness'. 

Thanks for understanding!

**Comment by nicolevasilevsky** [comment]
@jennygoldstein please let me know if you'd like to discuss further, I can reopen the ticket.

**Comment by jennygoldstein** [comment]
Hi @nicolevasilevsky,
Thanks very much for following up on the disease entity for NYX. In discussing this with the Retina GCEP, we totally understand that this is part of a phenotypic series in OMIM and not wanting to change the disease entity for that reason. However, we wondered if we could please discuss further. The dyadic (gene-disease) naming approach is being supported by the ClinGen Disease Naming Advisory Committee. Dr. Hamosh is a member of that group. However, I do not know if or when OMIM may adopt the dyadic disease-naming approach. Perhaps we could talk with Dr. Hamosh and other DNAC members? I would be happy to coordinate any discussion that could be helpful in this regard. Please let me know what you think.
Thanks again, Nicole, for all of your help in dealing with our many requests.

**Comment by nicolevasilevsky** [comment]
Hi @jennygoldstein - let me discuss with our team and I will get back to you. :)

**Comment by nicolevasilevsky** [comment]
Hi @jennygoldstein - We are open to having a conversation with your developers to figure out ways to have the ClinGen preferred label show up, or another possible solution is having a particular release file for you that displays the labels that are preferred by ClinGen. Do you think those solutions could work? We are happy to meet on a call to discuss further as well. Thank you!

**Comment by nicolevasilevsky** [comment]
emailed Jenny on 08/17/22 to inquire about having a call

**Comment by nicolevasilevsky** [comment]
@sabrinatoro I think this can be closed
