### ISSUE TITLE
Create annotation structure for placement and ranking in UI

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/mondo#494]
In the polyhierarchy, we need the ability to specify which of the parents is most important to display first. For example, syndrome should be the primary parent for Marfan.

cc: @simonjupp

**Comment by nicolevasilevsky** [comment]
closing here, added to Monarch UI github

**Comment by cmungall** [comment]
Shouldn't be hardcoded in Ui. Shoukd be metadata others eg OLS can use
