### ISSUE TITLE
[Move parentage] diverticulosis, small-intestinal

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#4946]
**Mondo term (ID and Label)**
[diverticulosis, small-intestinal](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0009119)
In general, diverticulosis is not a Mendelian disease and this entry relates to [OMIM:223320 ](https://omim.org/entry/223320), which does not clearly document a case of Mendelian diverticulosis.

In general, diverticulosis can be seen as a feature of a number of genetic diseases (and for this reason it is an HPO term). It is also correct to consider diverticulosis as a disease entity. The actual etiologies are not clear but low-fiber diet is a risk factor. 

I would suggest that [digestive system disorder](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004335&lang=en&viewMode=PreferredRoots&siblings=false) is a better parent term. 

@ahamosh 

**Reason for deprecation**

**Suggested term to consider**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by ahamosh** [comment]
Totally.  Diverticulosis is not Mendelian and is a digestive disease.
