### ISSUE TITLE
primary bone dysplasia

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#4948]
**Mondo term (ID Label)**
primary bone dysplasia

**Bug/Typo/Error description**
The relevant grouping is by the skeletal dysplasia nosology, which includes Mendelian diseases
https://pubmed.ncbi.nlm.nih.gov/31633310/

If there are any non-genetic disorders, we should place them somewhere else. Having this class be non-Mendelian is not useful.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
action items:
- [ ] review the 42 grouping classes in this [spreadsheet](https://docs.google.com/spreadsheets/d/1UCB8Vxnw5HajyHsjpNL_MxPI63QKAKaR/edit#gid=1522282848) with Mondo IDs - many will need a new Mondo ID. This will need to be done manually.
- [ ] Add new Mondo terms via a ROBOT template
- [ ] associate the OMIM ID with the grouping (reclassify existing terms)

**Comment by nicolevasilevsky** [comment]
@pnrobinson is abnormal mineralization disorder the same as MONDO:0001068 osteomalacia?

The children of this class in the nosology are:

- Hypophosphatasia, perinatal lethal, infantile and juvenile forms
- Hypophosphatasia, juvenile and adult forms
- Hypophosphatemic rickets, X-linked
- Hypophosphatemic rickets, autosomal dominant
- Hypophosphatemic rickets, autosomal recessive, type 1 (ARHR1)
- Hypophosphatemic rickets, autosomal recessive, type 2 (ARHR2)
- Hypophosphatemic rickets with hypercalciuria, X-linked
- Hypophosphatemic rickets with hypercalciuria, autosomal recessive (HHRH)
- Vitamin D-dependent rickets, type 1A
- Vitamin D-dependent rickets, type 1B
- Vitamin D-dependent rickets, type 2A
- Vitamin D-dependent rickets, type 2B
- Familial hyperparathyroidism, types 1-4
- Neonatal hyperparathyroidism, severe form
- Neonatal hyperparathyroidism, transient form
- Familial hypocalciuric hypercalcemia with transient neonatal hyperparathyroidism
- Calcium pyrophosphate deposition disease (familial chondrocalcinosis) type 2
- Cutaneous skeletal hypophosphatemia syndrome

**Comment by nicolevasilevsky** [comment]
@pnrobinson @cmungall do want to add these new grouping classes:
- cleidocranial dysplasia and related disorders
- osteopetrosis and related disorders

or just classify the children under MONDO:0007340	cleidocranial dysplasia and MONDO:0017198 osteopetrosis, respectively?

**Comment by nicolevasilevsky** [comment]
Note - some of the grouping classes in the nosology are in Orphanet and were obsoleted in Mondo. I will un-obsolete them.

**Comment by nicolevasilevsky** [comment]
> @pnrobinson @cmungall do want to add these new grouping classes:
> 
> * cleidocranial dysplasia and related disorders
> * osteopetrosis and related disorders
> 
> or just classify the children under MONDO:0007340 cleidocranial dysplasia and MONDO:0017198 osteopetrosis, respectively?

I added the classes as children of MONDO:0007340 cleidocranial dysplasia and MONDO:0017198 osteopetrosis
