### ISSUE TITLE
acute disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#4950]
**Mondo term (ID Label)**

**Bug/Typo/Error description**
acute disease seems to comprise diseases that have "acute" in their label but this is only a subset of diseases that are actually acute.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
We'll work on this:
- query for anything that is not under acute disease and has the label 'acute'
- add subclassOf axiom 'has modifier' some acute
