### ISSUE TITLE
disease susceptibility

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#496]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0042489

This is not a disease and should be obsoleted

**Comment by nicolevasilevsky** [comment]
moving this to a discussion:
https://github.com/monarch-initiative/mondo/discussions/2672
