### ISSUE TITLE
MONDO:0009812  osteomalacia, sclerosing, with cerebral calcification and MONDO:0009821 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4966]
**Mondo term (ID and Label)**
MONDO:0009812  osteomalacia, sclerosing, with cerebral calcification

**Reason for deprecation**
OMIM: ^ 259660
MOVED TO [259775](https://www.omim.org/entry/259775)

**Term to be merged with**
MONDO:0009821  lethal osteosclerotic bone dysplasia

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo --obsolete-replace MONDO:0009812 MONDO:0009821 -o -f obo mondo-edit.obo`
