### ISSUE TITLE
[Obsolete] head disorder term + some children

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4968]
following #4621 
'head disorder' should be obsoleted, but there are some children that do not have other parents, and look like they should be obsoleted:

MONDO ID | labels | obsoletion reason
-- | -- | --
MONDO:0044987 | face disorder | grouping term
MONDO:0005482 | molar-incisor hypomineralization | phenotype
MONDO:0006858 | mouth disorder | grouping term
MONDO:0044999 | scalp disorder | grouping term

**Comment by sabrinatoro** [comment]
@nicolevasilevsky could you make sure that obsoleting these terms would make sense? 

Note to self, we will need to figure out parentage for some children of these terms

**Comment by sabrinatoro** [comment]
**children of "head disorder", potential more terms to obsolete:** 
MONDO ID | labels | obsoletion reason | issue? 
-- | -- | -- | --
MONDO:0002022 | disorder of orbital region | grouping term | children: "eye adnexa disorder" need new parent
MONDO:0006858 | mouth disorder | grouping term | children need parent


**Children of "mouth disorder", should be obsoleted?** 
MONDO ID | labels | obsoletion reason | issue? 
-- | -- | -- | --
MONDO:0004748 | lip disorder | grouping term | none- all children have other parents
MONDO:0044992 | mouth mucosa disorder | grouping term | none- all children have other parents


**Children of "mouth disorder",  need new parent:** 
- florid cemento-osseous dysplasia (MONDO:0019368)
- oral leukoedema (MONDO:0006880)
- salivary gland disorder (MONDO:0001142)
- tongue disorder (MONDO:0001165)
- tooth disorder (MONDO:0006999)


@nicolevasilevsky, I think that we should review this in one of our calls. Maybe at a quarterly 2h call as we need experts feedback?

**Comment by nicolevasilevsky** [comment]
sounds good!

**Comment by sabrinatoro** [comment]
I kept "mouth disorder" (MONDO:0006858) as it is a group of disorders (ie oral disease) (see [here](https://www.cdc.gov/oralhealth/conditions/index.html) and [here](https://www.mayoclinic.org/healthy-lifestyle/adult-health/in-depth/dental/art-20047475)


'disorder of orbital region' (MONDO:0002022) was also kept. We can review later.
