### ISSUE TITLE
[Obsolete] carpal region disorder

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4974]
**Mondo term (ID and Label)**
MONDO:0044998
carpal region disorder

**Reason for deprecation**
term based on location, not real disorder

**Comment by sabrinatoro** [comment]
@nicolevasilevsky would you agree with the obsoletion of this term?

**Comment by nicolevasilevsky** [comment]
Yeah, it doesn't seem terribly useful and it has no children. How did the decision to obsolete this come about? I don't have any objections, just curious.

**Comment by sabrinatoro** [comment]
I obsoleted the parent term (hand disorder), and this became of orphan term, with no parents

**Comment by nicolevasilevsky** [comment]
Ah got it! I agree with your assessment :)

**Comment by nicolevasilevsky** [comment]
I am going to link this here, for our future reference: https://github.com/monarch-initiative/mondo/issues/4621
