### ISSUE TITLE
Atlantic cod allergy

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#498]
This is currently listed under Infectious disease.
I would say that "Atopy" or "Allergy" is a disease, and individual allergies are phenotypic features, it is unlikely that an individual has just one specific allergy, and if somebody has 20 allergies, like I had as a kid, then we would be modelling them as having 20 distinct diseases.

**Comment by nicolevasilevsky** [comment]
@matentzn I thought we worked on a similar ticket like this together at one point.

I put this on our to do list.

**Comment by pnrobinson** [comment]
I do not think that Allergy to X should be called a disease. Usually, people with Allergies have sensitivity to more than one antigen. So there would be few people to actually have ``Atlantic cod allergy``, instead, one person would have Atlantic, Pacific Cod, Shrimp, Swordfish,... Allergy. This entire subsection should be revised.

Probably the only diseases are things like
Allergic rhinitis
Allergic asthma
Atopic eczema
Anaphylaxis
"Atopic disposition" (possibly with subtypes such as Food allergies)

@ahamosh thoughts?

**Comment by ahamosh** [comment]
I agree and view this as Peter does.

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson and @ahamosh!

Sounds like the action item is to obsolete the X allergy terms. Looks like most of these come from DO.

cc @cmungall

**Comment by mellybelly** [comment]
+1; allergies should be dealt with outside of mondo

**Comment by cmungall** [comment]
yes, obsolete all following the allergic-to-X pattern (do you know how to do batch obsoletions?) but coordinate with eg EFO, they are using some, I think most of these have HPO replacements but check

```
[Term]
id: MONDO:0002497
name: food allergy
def: "Gastrointestinal disturbances, skin eruptions, or shock due to allergic reactions to allergens in food." [MESH:D005512]
synonym: "allergic disease from food material" EXACT  []
synonym: "allergy of food material" EXACT  [MONDO:patterns/allergy]
synonym: "food hypersensitivity" EXACT  [CSP2005:1525-0902, DOID:3044]
synonym: "food material allergic disease" EXACT  [MONDO:patterns/environmental_stimulus]
xref: COHD:4188027
xref: DOID:3044
xref: ICD9:995.3
xref: MESH:D005512
xref: SCTID:414285001
xref: EFO:1001890
is_a: MONDO:0005271 ! allergic disease
relationship: RO:0004028 FOODON:00002403 ! realized in response to stimulus
intersection_of: MONDO:0005271 ! allergic disease
intersection_of: RO:0004028 FOODON:00002403 ! realized in response to stimulus

[Term]
id: MONDO:0005741
name: egg allergy
def: "Allergic reaction to eggs that is triggered by the immune system." [MESH:D021181]
synonym: "allergy of egg" EXACT  [MONDO:patterns/allergy]
synonym: "allergy to eggs" EXACT  [DOID:4377]
synonym: "egg allergic disease" EXACT  []
xref: COHD:442116
xref: DOID:4377
xref: EFO:0007248
xref: ICD9:V15.03
xref: MESH:D021181
xref: SCTID:91930004
xref: UMLS:C0559469
is_a: MONDO:0002497 ! food allergy
relationship: RO:0004028 FOODON:03420194 ! realized in response to stimulus
intersection_of: MONDO:0005271 ! allergic disease
intersection_of: RO:0004028 FOODON:03420194 ! realized in response to stimulus

[Term]
id: MONDO:0006872
name: nut allergic reaction
def: "Allergic reaction to tree nuts that is triggered by the immune system." [MESH:D021184]
synonym: "nut allergy" RELATED  [DOID:4379]
synonym: "022 tree nuts (tn) (ccpr) allergic disease" EXACT  []
synonym: "allergy of 022 tree nuts (tn) (ccpr)" EXACT  [MONDO:patterns/allergy]
synonym: "allergy to nuts" EXACT  [DOID:4379]
synonym: "nut allergic reaction" EXACT  [DOID:4379]
xref: DOID:4379
xref: EFO:1001066
xref: MESH:D021184
xref: SCTID:91934008
xref: UMLS:C0577620
is_a: MONDO:0002497 ! food allergy
relationship: RO:0004028 FOODON:03400685 ! realized in response to stimulus
intersection_of: MONDO:0005271 ! allergic disease
intersection_of: RO:0004028 FOODON:03400685 ! realized in response to stimulus

[Term]
id: MONDO:0007021
name: wheat allergic disease
def: "Allergic reaction to wheat that is triggered by the immune system." [EFO:1001243]
synonym: "wheat allergic reaction" RELATED  [DOID:3660]
synonym: "wheat allergy" RELATED  [DOID:3660]
synonym: "allergic disease from wheat based food product" EXACT  []
synonym: "allergy of wheat based food product" EXACT  [MONDO:patterns/allergy]
synonym: "allergy to wheat" EXACT  [DOID:3660]
synonym: "wheat based food product allergic disease" EXACT  [MONDO:patterns/environmental_stimulus]
xref: DOID:3660
xref: EFO:1001243
xref: ICD9:995.3
xref: MESH:D021182
xref: SCTID:420174000
xref: UMLS:C0949570
is_a: MONDO:0002497 ! food allergy
relationship: RO:0004028 FOODON:00001141 ! realized in response to stimulus
relationship: RO:0004028 NCBITaxon:4564 ! realized in response to stimulus
intersection_of: MONDO:0005271 ! allergic disease
intersection_of: RO:0004028 FOODON:00001141 ! realized in response to stimulus
```

**Comment by nicolevasilevsky** [comment]
[spreadsheet here](https://docs.google.com/spreadsheets/d/12xlKSTwsMMiujzA-M5CqMdtaiH-T-N8mm5_0I1HQ-uE/edit#gid=833835031)

**Comment by nicolevasilevsky** [comment]
Discussing on the Curation call - we are reopening this.

Action item: we should obsolete the rest of the subclasses of [allergic disease](http://purl.obolibrary.org/obo/MONDO_0005271).
- use OAK or SPARQL to get a list of all of these
- use KGCL or [mass obsoletion workflow](https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#simple-mass-obsoletion-pipeline)

- [ ] update exclusion list to exclude all of the allergy terms in Mondo
- [ ] see Peter's comment above about which terms to retain

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/5856

**Comment by nicolevasilevsky** [comment]
We discussed at Mondo F2F meeting that we would obsolete allergy to x terms that come from DO.

**Comment by nicolevasilevsky** [comment]
closing this in favor of https://github.com/monarch-initiative/mondo/issues/5914
