### ISSUE TITLE
new disease association HEATR3 

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#4980]
HEATR3  PMID: 35213692 MONDO:0015253

"Our study uncovers a new pathophysiological mechanism leading to DBA driven by biallelic HEATR3 variants and the destabilization of a nuclear import protein important for ribosome biogenesis."

**Comment by nicolevasilevsky** [comment]
@ValWood MONDO:0015253 Diamond-Blackfan anemia is a grouping class that groups all of the subtypes with specific gene variations. I don't think we want to add this gene association to the grouping class.

**Comment by ValWood** [comment]
It does seem to be causative, but I assume just not yet assigned a  specific gene name label ? Happy for it to close. I will make this association for the ortholog at PomBase. It makes sense biologically. 

https://rarediseases.org/rare-diseases/anemia-blackfan-diamond/#causes
Diamond Blackfan anemia is caused by changes (mutations) in ribosomal protein genes in about 80-85% of those affected. In the remaining 10-15% of patients, no abnormal genes have yet been identified.

**Comment by ValWood** [comment]
Also, there are quite a few other causative genes annotated only yo the parent:
https://monarchinitiative.org/disease/MONDO:0015253#causal-gene

**Comment by ValWood** [comment]
Here, I think the grouping class is the disease ? the individual diseases are all in the form
Diamond Blackfan anemia caused by gene "blah"

**Comment by nicolevasilevsky** [comment]
closing this here - I opened a new ticket in monarch/helpdesk
