### ISSUE TITLE
review x-ref for COACH syndrome 1

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#4986]
**Mondo term (ID and Label):**
 http://purl.obolibrary.org/obo/MONDO_0008996
COACH syndrome 1

**Xref that should be fixed (ID and label):**
It looks like most (maybe all) of the x-ref which are not omim should be on the parent term "COACH syndrome" instead of the "COACH syndrome 1" which refers to the disease with variation in a specific gene

**Comment by sabrinatoro** [comment]
@cmungall and @nicolevasilevsky 
Currently, all of the Mondo:Equivalent x-refs (except for the omim xref) for 'COACH syndrome 1' (MONDO:0008996) refer to the parent grouping term 'COACH syndrome'. The current textual definition also refers to the parent term. However, the EquivalentTo axiom refers to the type 1. 

What would be the best and least confusing path forward (and more importantly,  the path that would ensure the correctness of the current annotations)?
- option 1: keep 'COACH syndrome 1' as MONDO:0008996 and update x-ref and textual definition
- option 2: obsolete MONDO:0008996, and create a new term for 'COACH syndrome 1' (similar to splitting) with the correct x-ref (the x-refs and synonyms for the general terms can be added to the general term). 

I personally am leaning towards option 2 since I am overly careful and the concept of the term is very confusing, and therefore this term could have been used to annotate both the general COACH syndrome and the more specific COACH type 1. However, I would like your opinion. Thanks!

**Comment by nicolevasilevsky** [comment]
I like your conservative approach. Looks like I created the grouping class, maybe in response to this ticket: https://github.com/monarch-initiative/mondo/issues/3991

I am surprised that OMIM does not have a phenotypic series for this.
