### ISSUE TITLE
bone fracture

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#499]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005315

Bone fracture is a disease of connective tissue from a logical point of view, but this is not how a clinical would conceptualize it. We should reorganize this hierarchy.

**Comment by nicolevasilevsky** [comment]
see related ticket:
https://github.com/obophenotype/human-phenotype-ontology/issues/3889

**Comment by nicolevasilevsky** [comment]
we should consider moving the fracture terms to HPO

cc @cmungall and @pnrobinson

**Comment by nicolevasilevsky** [comment]
- [ ] bone fracture should be child of injury only 
- [ ] 'Chitty Hall Webb syndrome' should have bone fracture as a phenotype
