### ISSUE TITLE
Apparent mineralocorticoid excess (syndrome) MONDO:0006657 & MONDO:0009025 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#4993]
**Mondo term (ID and Label)**

Apparent mineralocorticoid excess syndrome MONDO:0006657
**Reason for deprecation**
Appears to be the same condition as OMIM 218030
(UMLS has two CUIs, pointing to two different NCI concepts - 11 Beta-Hydroxysteroid Dehydrogenase Type 2 Deficiency
NCI PT C131083 ; and Syndrome of Apparent Mineralocorticoid Excess, NCI PT C123231 )

**Term to be merged with**
MONDO:0009025
(although the direction of the merge is not important) 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo --obsolete-replace MONDO:0006657 MONDO:0009025 -o -f obo mondo-edit.obo`
