### ISSUE TITLE
Validate low confidence IDs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#5]
For this you will need  MonDO-kboom in google drive - sync to your hard drive.

Work through class-confidence.tsv in order.

For each row, check linked-eoo-rpt.html. The image should be clickable.

If you think the existing resolution OK, remove confidence annotation.

If there are problems to be resolved, resolve

All the above can be done on a single PR

For difficult ones, open a ticket here.

__UPDATE__

Clarification on "Work through class-confidence.tsv in order."

the goal is to spend most time on lowest confidence classes. Of the 6k, 1435 have confidence>1.0, meaning the solution chosen was 2x better than next kboom option. The high priority ones are the ultra-low confidence ones (<0.005), of which there are only 73.

**Comment by cmungall** [comment]
Example:

first line in report:

```
<http://purl.obolibrary.org/obo/MONDO_0000868>  "mitochondrial DNA depletion syndrome 6"^^<http://www.w3.org/2001/XMLSchema#string>     "0.0"^^<http://www.w3.org/2001/XMLSchema#double>
```

find in file:


![image](https://user-images.githubusercontent.com/50745/31843794-c5ae4ed6-b5a9-11e7-8e33-fd4b0ea1a34b.png)

look at image:

![image](https://user-images.githubusercontent.com/50745/31843800-d7ed624e-b5a9-11e7-8f2d-dad267fc2d55.png)

weirdness caused by a bad xref.

This is a tricky one

I think https://omim.org/entry/256810 MITOCHONDRIAL DNA DEPLETION SYNDROME 6 (HEPATOCEREBRAL TYPE); MTDPS6 ==  Orphanet_255229 Navajo neurohepatopathy

https://omim.org/entry/271245 MITOCHONDRIAL DNA DEPLETION SYNDROME 7 (HEPATOCEREBRAL TYPE); MTDPS7 ==  Orphanet_1186 Infantile onset spinocerebellar ataxia

![image](https://user-images.githubusercontent.com/50745/31844060-5869332a-b5ab-11e7-9ce6-60fb9fe587c1.png)

See the commit message attached for resolution

**Comment by cmungall** [comment]
The xrefs here are reversed to how they should be:

```
[Term]
id: DOID:0050556
name: infantile onset spinocerebellar ataxia
namespace: disease_ontology
synonym: "OHAHA SYNDROME" EXACT []
xref: OMIM:271245 ! MTDPS7
is_a: DOID:0050950  ! autosomal recessive cerebellar ataxia

[Term]
id: DOID:0080126
name: mitochondrial DNA depletion syndrome 7
namespace: disease_ontology
xref: OMIM:256810 ! MTDPS6 // navajo neuropathy
is_a: DOID:700  ! mitochondrial metabolism disease
```

**Comment by cmungall** [comment]
Another one:

```
<http://purl.obolibrary.org/obo/MONDO_0009039>  "Baller-Gerold syndrome"^^<http://www.w3.org/2001/XMLSchema#string>     "0.0"^^<http://www.w3.org/2001/XMLSchema#double>
```

![image](https://user-images.githubusercontent.com/50745/31844446-9799f514-b5ad-11e7-8319-b1606cab611b.png)

The xref here is totally wrong, these have nothing to do with eachother!

![image](https://user-images.githubusercontent.com/50745/31844439-8b8b11cc-b5ad-11e7-902d-c4c12bf98b07.png)

**Comment by nicolevasilevsky** [comment]
@cmungall I just made a couple changes, but I am not sure if I am doing the pull requests correctly.

Is there some documentation somewhere on how to do a proper pull request? Either on the command line or I use SourceTree.

**Comment by cmungall** [comment]
@nicolevasilevsky - I don't see any PRs. These would show up in the section above:

![image](https://user-images.githubusercontent.com/50745/32362169-8107618e-c024-11e7-9f54-af31c8b08b3f.png)

I'm afraid I can't help with sourcetree. The docs we use in GO for PRs are all here: http://go-ontology.readthedocs.org/ but these assume command line

**Comment by nicolevasilevsky** [comment]
@cmungall is this ticket still relevant, or can this be closed?

**Comment by nicolevasilevsky** [comment]
This ticket is really old and I think no longer relevant. I am closing, please reopen if still needed.
