### ISSUE TITLE
MONDO:0022018 Borrone di Rocco Crovato syndrome & MONDO:0009579  Frank-Ter Haar syndrome[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5000]
**Mondo term (ID and Label)**
MONDO:0022018 Borrone di Rocco Crovato syndrome

**Reason for deprecation**
Per OMIM, 211170 MOVED TO [249420](https://www.omim.org/entry/249420)
and "Borrone syndrome was described as a severe progressive multisystem disorder with features overlapping those of FTHS, including thick skin, acne conglobata, osteolysis, gingival hypertrophy, brachydactyly, camptodactyly, and mitral valve prolapse. Although it was initially thought to be a distinct phenotype, mutations in the FTHS-associated gene SH3PXD2B have been identified in patients diagnosed with Borrone syndrome. " 

**Term to be merged with**
MONDO:0009579 Frank-Ter Haar syndrome

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

(I will be recommending/requesting UMLS merge Borrone Di Rocco Crovato syndrome CUI: C1859406 with Ter Haar syndrome CUI: C1855305, which would move MeSH C536577 in the UMLS mappings.)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo --obsolete-replace MONDO:0022018 MONDO:0009579 -o -f obo mondo-edit.obo`
