### ISSUE TITLE
[Revise subclass] aplastic anemia should not be a subclass of telomere syndrome

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#5003]
**Mondo term (ID and Label)**

aplastic anemia (MONDO:0015909)
is currently a child of "telomere syndrome"

**Suggested revision and reasons**

I suspect this is unintentional. I don't think they are related?

**Comment by nicolevasilevsky** [comment]
Hi @ValWood according to this paper, aplastic anemia is a type of telomere syndrome:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6035054/

Please let me know if you disagree. Thanks!

**Comment by ValWood** [comment]
The paper says
Shortened telomeres are commonly associated with bone marrow failure syndromes including aplastic anemia.
I think it is only a subset.

I have 52 genes annotated to aplastic anemia causing disease gene orthologs and most have nothing to do with telomere syndromes (most are ribosomal protein). Only 2 are telomere maintenance (ter1&trt1)

https://www.pombase.org/results/from/id/438861ab-0d4f-408f-884d-cd1d62c51632

**Comment by nicolevasilevsky** [comment]
Ok- sounds like I should remove telemore syndrome as a parent of aplastic anemia? Thanks for clarifying, Val!
