### ISSUE TITLE
split term: newborn respiratory distress syndrome MONDO:0009971

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5005]
**Term to split:**
newborn respiratory distress syndrome MONDO:0009971

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
RESPIRATORY DISTRESS SYNDROME IN PREMATURE INFANTS

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonynms that end in "1", "2", etc. should move to subclass.
OMIM 267450
UMLS CUI: C1968593
and Add: MeSH  C566881

(This should be a child concept to newborn respiratory distress syndrome, which SNOMED defines as having multiple potential causes, including prematurity, maternal diabetes, C-section delivery or 'idiopathic')

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
option 1 sounds good, thanks @sabrinatoro!
