### ISSUE TITLE
osteoporosis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#502]
This is now classified as a bone resorption disease which is wrong. It is a bone turn over disease and lack of new bone formation is prob most important. This is the danger of classifying by pathophysiology!!

**Comment by kallia-p** [comment]
@nicolevasilevsky Just double-checking what exactly needs to be done here. The source annotation for the osteoporosis superclass bone resorption classifies is as a bone resorption disease http://purl.obolibrary.org/obo/DOID_11476 whereas other ontologies i.e. NCIt as a bone metabolism disease . I think Peter says that the DOID classification is a strong statement given that osteoporosis is caused by an imbalance between bone resorption and bone formation in favour of resorption and fromk this i deduct that suggests that the parent class should be bone remodelling disease? Note that we have two terms for osteoporosis HP:0000939 and MONDO:0005298.

**Comment by kallia-p** [comment]
@pnrobinson Hi Peter pls see comment above, do you mean that the parent class for osteoporosis should be bone remodelling disease?

**Comment by pnrobinson** [comment]
@kallia-p I think it is a bad idea to use pathophysiology based classes to structure MONDO. It is relatively rare that we actually understand the pathophysiology of diseases enough to say that the main parent would be, and if we wanted to include links for all relevant pathophysiology, each disease would have numerous parents.
ICD uses this superclass for osteoporosis

Disorders of bone density and structure

I think that we should revise the corresponding areas of MONDO

**Comment by nicolevasilevsky** [comment]
@pnrobinson there isn't a class called 'Disorders of bone density and structure' - is it okay to classify osteoporosis under 'bone disease'?

**Comment by pnrobinson** [comment]
Why don't we try to figure out what the major categories are under bone
boine disease
-'Disorders of bone density and structure' -
-Fracture
-bone metastasis
-osteomyelitis
-etc

**Comment by nicolevasilevsky** [comment]
Sounds good! @kallia-p this is an area you know about, right? Could you propose a new classification? Thank you!

**Comment by kallia-p** [comment]
@nicolevasilevsky @pnrobinson I pasted a couple of screenshots with the major categories under bone disease. 

![image](https://user-images.githubusercontent.com/77484553/123665808-879a5380-d830-11eb-8ebd-4b890c6b8f84.png)
![image](https://user-images.githubusercontent.com/77484553/123666083-ce884900-d830-11eb-87fd-d1a14541933d.png)

The Mondo superclass 'bone disease' has children 'bone remodelling disease' which includes osteoporosis and we also have 'disease of bone structure' though this class contains children with deformities in veterbrae which in ICD are classified as 'dorsopathies'. Adopting the ICD classification 'Disorders of bone density and structure' would entail essentially to pull these together under a new class and review all other bone diseases that are common in Mondo and ICD. https://icd.who.int/browse10/2019/en#/M80-M85

Nicole and I are think it would be a good idea if the three of us discuss this in a call, maybe a curation call that Peter is around?

**Comment by kallia-p** [comment]
@nicolevasilevsky @pnrobinson 

Also to mention that in other ontologies osteoporosis is a child of

bone metabolism
http://purl.obolibrary.org/obo/NCIT_C3298
http://purl.obolibrary.org/obo/OMIT_0011030

bone resorption
http://purl.obolibrary.org/obo/DOID_11476

decreased bone mass
http://purl.obolibrary.org/obo/MP_0000066

reduced bone mineral density
http://purl.obolibrary.org/obo/HP_0000939

**Comment by kallia-p** [comment]
@nicolevasilevsky @pnrobinson @cmungall Chris also thinks that it is worth adding a intermediate class 'Disorders of bone density and structure' under 'bone disease' with child 'bone remodelling disease' if we decide to keep the latter (to be discussed).  'Diseases of bone structure' id "MONDO:0000836", a child of 'bone disease', is missing a definition and according to Chris would be a candidate for obsoletion. 'Diseases of bone structure' includes only diseases with abnormalities in skeletal morphology 'disease has major feature' some 'Abnormality of skeletal morphology'. In ICD some of these are classified as 'dorsopathies'.

**Comment by pnrobinson** [comment]
Disorders of bone modelling will likely have abnormalities of density and or structure. In general I do not think it is a good idea to use pathophysiology as the axis of classification. Why is it not enough to have 'Disorders of bone density and structure' ?
