### ISSUE TITLE
review children of 'type 1 diabetes mellitus'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5033]
@ahamosh - looking at the children of MONDO:0005147 'type 1 diabetes mellitus', I think these are susceptibilities to type 1 diabetes, is that correct? I linked the respective OMIM records below.

- ['type 1 diabetes mellitus 1'](https://omim.org/entry/222100) - note, this is an included entry
- ['type 1 diabetes mellitus 10'](https://omim.org/entry/601942)
- ['type 1 diabetes mellitus 11'](https://omim.org/entry/601208)
- ['type 1 diabetes mellitus 12'](https://omim.org/entry/601388)
- ['type 1 diabetes mellitus 13'](https://omim.org/entry/601318)
- ['type 1 diabetes mellitus 15'](https://omim.org/entry/601666)
- ['type 1 diabetes mellitus 17'](https://omim.org/entry/603266)
- ['type 1 diabetes mellitus 18'](https://omim.org/entry/605598)
- ['type 1 diabetes mellitus 19'](https://omim.org/entry/610155)
- ['type 1 diabetes mellitus 2'](https://omim.org/entry/125852)
- ['type 1 diabetes mellitus 20'](https://omim.org/entry/612520)
- ['type 1 diabetes mellitus 21'](https://omim.org/entry/612521)
- ['type 1 diabetes mellitus 22'](https://omim.org/entry/612522)
- ['type 1 diabetes mellitus 23'](https://omim.org/entry/612622)
- ['type 1 diabetes mellitus 24'](https://omim.org/entry/613006)
- ['type 1 diabetes mellitus 3'](https://omim.org/entry/600318)
- ['type 1 diabetes mellitus 4'](https://omim.org/entry/600319)
- ['type 1 diabetes mellitus 5'](https://omim.org/entry/600320)
- ['type 1 diabetes mellitus 6'](https://omim.org/entry/601941)
- ['type 1 diabetes mellitus 7'](https://omim.org/entry/600321)
- ['type 1 diabetes mellitus 8'](https://omim.org/entry/600883)

**Comment by ahamosh** [comment]
These are all susceptibilities and GWAS hangovers...

**Comment by nicolevasilevsky** [comment]
thanks @ahamosh!
