### ISSUE TITLE
neoplasm of femur

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#504]
This is a direct child of bone disease but there are lots of different bone cancers.

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0021579

**Comment by cmungall** [comment]
Huh, this is odd, but whatever caused this is fixed in the forthcoming release:

![image](https://user-images.githubusercontent.com/50745/49241566-0569fa00-f3bd-11e8-8004-3bbfdfa6de36.png)
