### ISSUE TITLE
[Revise subclass] Ontology term: non-dystrophic myopathy (MONDO:0016110) descendants

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#5045]
**Mondo term (ID and Label)**

Ontology term: non-dystrophic myopathy (MONDO:0016110)

Is defined
A group of rare skeletal muscle ion-channel disorders caused by genetic mutations in the sodium and chloride channel genes. It is characterized by altered membrane excitability resulting in skeletal muscle stiffness. This group of myotonias is distinct from myotonic dystrophy because of the absence of systemic features or progressive weakness.

But most of the descendants involve diseases that are not caused by mutations in sodium and ion channels

For example

autosomal dominant distal axonal motor neuropathy-myofibrillar myopathy syndrome (a yeast shock protein)
autosomal dominant mitochondrial myopathy with exercise intolerance
cap myopathy  (tropomyosin)
congenital fiber-type disproportion myopathy (multiple cytoskeleton proteins)
Dorfman-Chanarin disease (phospholipase)
And many many more

**Comment by ValWood** [comment]
There appear to be multiple defs of non-dystrophic myopathy ,,  i.e

'Non-dystrophic myopathy' includes all diseases of muscle excludingthose genetically determined primary degenerative myopathies, collectively known as Muscular Dystrophy. disorders of muscle of varied aetiology. generalised disease of connective tissues.

Nondystrophic myotonias (NDM) are muscle disorders caused by genetic abnormalities in certain muscle cell membrane proteins. Individuals with NDM experience limited muscle relaxation, which causes pain, weakness, and impaired physical activity.

It seems likely that  these groupings  are quite old, and that now not all myotonias  can be classified as myotonic or non myotonic  based on the original definitions.

**Comment by sabrinatoro** [comment]
@pnrobinson and @ahamosh 
Could you please share your thoughts on this issue? 
Is "non-dystrophic myopathy" defined as caused by genetic mutations in the sodium and chloride channel genes? Or is it defined based on other criteria? 
Thank you!

**Comment by pnrobinson** [comment]
"non-dystrophic myopathy"  is like Not-Otherwise Specified in ICD. Probably this is not a good class to have in Mondo (agreeing with @ValWood )

**Comment by sabrinatoro** [comment]
Thank you @pnrobinson 

I have added "non-dystrophic myopathy" to the obsoletion list. 
TO DO:
- [ ] review children terms, could probably be children of "myopathy"
- [ ] obsolete "non-dystrophic myopathy" (MONDO:excludeGroupingClass)
