### ISSUE TITLE
[Revise subclass] hereditary neoplastic syndrome (MONDO:0015356)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#5046]
**Mondo term (ID and Label)**

hereditary neoplastic syndrome (MONDO:0015356)
is not a descendant of  neoplastic syndrome 

is there a reason for that?

**Comment by nicolevasilevsky** [comment]
@ValWood this is defined as the inherited predisposition toward getting a tumor, so it is a disease susceptibility, not a type of neoplasm.

**Comment by nicolevasilevsky** [comment]
Please let me know if you have further questions or if I can close this ticket - thanks!

**Comment by ValWood** [comment]
neoplastic syndrome is defined:

Definition | Parents
-- | --
A broad classification for disorders in which the development of neoplasms typically occur in association with a characteristic set of signs or symptoms. These disorders may be inherited or acquired.

hereditary neoplastic syndrome  is_a hereditary neoplastic syndrome?

**Comment by nicolevasilevsky** [comment]
Good point, thanks!
I see NCIT has this classified this way too, I'll add this superclass.
