### ISSUE TITLE
olecranon bursitis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#505]
Not really a bone disease. I would suggest that the upper level term should be skeletal disease rather than bone disease. Also, the parent term might be somehting like bursitis?

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001557

**Comment by cmungall** [comment]
+1

Nicole, change site of inflammation of elbow joint

Note it's already a subclass of bursitis, but indirectly. We should 
obsolete the dumb occupational origin grouping.

**Comment by nicolevasilevsky** [comment]
@cmungall, what do you mean by "change site of inflammation of elbow joint"?

**Comment by cmungall** [comment]
Sorry, I meant change site *to*, i.e. the uberon class
