### ISSUE TITLE
[Revise subclass] 'partial trisomy 21' 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5054]
A couple questions came up on the INCLUDE call today:

Should 'partial trisomy 21' be a child of 'trisomy 21'?

Should 'trisomy 21' have the following children?

- 'partial trisomy 21'
- 'translocation Down syndrome'

cc @mellybelly

**Comment by sabrinatoro** [comment]
No, 'partial trisomy 21' should not be a child of 'trisomy 21'.
The concepts of trisomy and partial trisomy are very much different: trisomy=presence of an additional full chromosome , and it does not include "extra copy of part of a chromosome"

Instead, "down syndrome" was used as a grouping term. It is defined as the "presence of a third (partial or total) copy of chromosome 21". It is the parent of 
- partial trisomy 21
- trisomy 21 (=additional full chromosome)
- translocation down syndrome.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
this issue can be closed unless there is disagreement with the classification. Though the classification and the concept of "trisomy" versus "partial trisomy" follow the SO concepts

**Comment by nicolevasilevsky** [comment]
Thanks @sabrinatoro. Let me share this with the INCLUDE team and see if they have any feedback

**Comment by lopierra** [comment]
Thanks - it makes sense for Down Syndrome to be the parent. But where do `complete trisomy 21` and `mosaic trisomy 21` fit?

**Comment by nicolevasilevsky** [comment]
@lopierra you can see the classification of [complete trisomy 21](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0700030) and [mosaic trisomy 21](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0700127) at the hyperlinked terms.

They are both descendants of Down Syndrome.

Does this answer your question?

**Comment by monicacecilia** [comment]
Yes, we can close. 
Leaving here for added clarity
<img width="349" alt="Screen Shot 2022-06-21 at 11 14 37 AM" src="https://user-images.githubusercontent.com/1714621/174869963-363c9be1-5ccf-4b22-9bd4-f98a57c3e1f1.png">
