### ISSUE TITLE
GASTROINTESTINAL DEFECTS AND IMMUNODEFICIENCY SYNDROME 2 [NTR]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5059]
**Preferred term label:**
Gastrointestinal defects and immunodeficiency syndrome  2

**Synonyms**
MULTIPLE INTESTINAL ATRESIA WITH OR WITHOUT LEUKOPENIA x-ref: see https://www.omim.org/entry/619708

Source: OMIM 619708 

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Gastrointestinal defects and immunodeficiency syndrome-2 (GIDID2) is a severe autosomal recessive developmental disorder characterized by multiple intestinal atresia apparent soon after birth. Affected infants have a distended abdomen and do not pass meconium. There is some evidence of inflammatory bowel disease. Death occurs in the first weeks of life. Some patients may also have immunodeficiency (summary by [Salter et al., 2021](https://www.omim.org/entry/619708#1)).

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0030831   gastrointestinal defect and immunodeficiency syndrome
**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
(Apologies if this is already covered by an OMIM slurp, I couldn't find this MIM # by searching GitHub)

**Comment by nicolevasilevsky** [comment]
@kanems we already have this term:
MONDO:0030669 'gastrointestinal defects and immunodeficiency syndrome 2'

Maybe we brought it in after you made this request? 

I'll add the definition - thanks for that.
