### ISSUE TITLE
MONDO:0019777 Carpenter-Waziri syndrome [Obsolete?/X-ref update?/restructure subclass?]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5061]
**Mondo term (ID and Label)**
MONDO:0019777 Carpenter-Waziri syndrome 

**Reason for deprecation**
Carpenter-Waziri syndrome, ORPHA:93973 x-ref is no longer valid.
... "Summary
This entity has been excluded from the Orphanet nomenclature of rare diseases and moved to [Alpha-thalassemia-X-linked intellectual disability syndrome](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=847)"
 Also this is an exact syn on OMIM:309580 

**Suggested term to consider**
MONDO:0010663  X-linked intellectual disability-hypotonic face syndrome 

**Other comments**
 OMIM 309580 is now called "INTELLECTUAL DISABILITY-HYPOTONIC FACIES SYNDROME, X-LINKED, 1" 
Maybe the better action is to move OMIM 309580 to MONDO:0019777 and rename based on OMIM pref/syns. ? The UMLS CUI for the "type 1" record is C4759781

Reading the OMIM description more closely I see this is a lot more complicated than just obsoleting or remapping an X-ref, looks like it should be restructured somehow to group these concepts:

1) 'X-linked intellectual disability-hypotonic facies syndrome' is synonymous with 
Carpenter-Waziri synd.,  
Holmes-Gang synd., 
Smith-Fineman-Myers syndrome
and "X-linked mental retardation[intellectual disability] with spastic paraplegia"
 -->All these syndromes were found to be caused by mutation in the _XH2_ gene 

2) X-linked intellectual disability-hypotonic facies syndrome-1 (MRXFH1) --> caused by mutation in the _ATRX_ gene

3) X-linked alpha-thalassemia/mental retardation syndrome (ATR-X; [301040](https://www.omim.org/entry/301040)) is an allelic disorder with a similar phenotype with the addition of alpha-thalassemia and Hb H inclusion bodies in erythrocytes. (SO I guess it get an extra parent to group also under alpha-thalassemias) ?

Term to remove from this branch:
"Juberg-Marsidi syndrome [MONDO:0019776] (see [309590](https://www.omim.org/entry/309590)) was previously thought to be the same as X-linked intellectual disability-hypotonic facies syndrome; however, affected individuals from that original family were found to have a pathogenic mutation in the HUWE1 gene ([300697](https://www.omim.org/entry/300697))."

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

@ahamosh - does OMIM have plans to create a separate record for the XLIDHFS concept in 1) above that are associated with _XH2_ variation? And if I have misinterpreted the summary from OMIM, please feel free to set the record straight on what concepts should be grouped or not.

**Comment by nicolevasilevsky** [comment]
@kanems thanks for all your research on this.

It looks like XH2 is a synonym for ATRX, see https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:886

**Comment by nicolevasilevsky** [comment]
This is what is in OMIM:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/6722114/177876755-0781b888-be3f-4f67-a4f2-afbb5bee5705.png">

**Comment by nicolevasilevsky** [comment]
I think we should:
- [ ] merge MONDO:0019777 'Carpenter-Waziri syndrome', MONDO:0019775 'Chudley-Lowry-Hoar syndrome' and MONDO:0019778 'Smith-Fineman-Myers syndrome' into MONDO:0010663 'X-linked intellectual disability-hypotonic face syndrome'
- [ ] rename MONDO:0010663 'X-linked intellectual disability-hypotonic face syndrome' to the current OMIM label 'INTELLECTUAL DISABILITY-HYPOTONIC FACIES SYNDROME, X-LINKED, 1' (not in CAPS though)
- Obsolete these classes, because they are obsolete in Orphanet:
- [ ] MONDO:0019776 'Juberg-Marsidi syndrome'
- [ ] MONDO:0019779 'Renier-Gabreels-Jasper syndrome'

**Comment by nicolevasilevsky** [comment]
sh run.sh owltools --use-catalog mondo-edit.obo --obsolete-replace MONDO:0019777 MONDO:0010663 -o -f obo mondo-edit.obo
