### ISSUE TITLE
CD4 deficiency: MONDO:0022620 and MONDO:0030981 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5062]
**Mondo term (ID and Label)**
CD4 deficiency: MONDO:0022620 

**Reason for deprecation**
this is a synonym on OMIM 619238

**Term to be merged with**
MONDO:0030981  immunodeficiency 79
(which interestingly already has an exact syn of "CD4 Deficiency") 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo --obsolete-replace MONDO:0022620 MONDO:0030981 -o -f obo mondo-edit.obo`
