### ISSUE TITLE
12q14 microdeletion syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#507]
12q14 microdeletion syndrome is characterised by mild intellectual deficit, failure to thrive, short stature and osteopoikilosis.

This really should not be classified as a bone disease, bone/skeletal features are part of the . disease but it is a multisystem disease.

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019784

**Comment by nicolevasilevsky** [comment]
Action item: 
- [ ] exclude superclasses:
'syndromic intellectual disability'
'primary bone dysplasia with increased bone density'

**Comment by nicolevasilevsky** [comment]
@kallia-p I don't see those inferred parents when the two superclasses are excluded:

![image](https://user-images.githubusercontent.com/6722114/117927351-f5091980-b2ae-11eb-8221-26661feec8f1.png)

Perhaps your reasoner was out of date? Please see my comments on the PR. If you still see the inferred parents when you remove those additional parents, let me know, there may be some other underlying issue.
