### ISSUE TITLE
Rename disease->disorder in labels for terms that conform to `patterns/location.yaml`

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#508]
Action items:
@joeflack4 
- [x] Please create this SPARQL query for conforms to `pattern/location.yaml` 
- [x] and has word ‘disease’ in label. Add to `src/sparql/update`
- [x] Bind label with regex replace pattern from disease to disorder
- [x] Delete old label
- [x] Insert new label

(if you have time to do this before the end of the month, that would be awesome, but no worries if not)

_updated 10/21/21 NV_

----

It is unclear why we use disease vs disorder in these term names. We should be consistent.

**Comment by nicolevasilevsky** [comment]
- [ ] make sure patterns have synonyms for disease or disorder
- [ ] sparql query for all the terms that have disease or disorder in the label (@matentzn)
- [ ] review on the curator call and consider which label to use

**Comment by nicolevasilevsky** [comment]
@pnrobinson I propose that we rename all the classes that are created via the Mondo design pattern (such as MONDO:patterns/location) to disorder, eg 'adrenal cortex disease' would be 'adrenal cortex disorder'.

We can update the patterns to use disorder as the primary label and disease as the synonym.

here is a [report](https://docs.google.com/spreadsheets/d/1Vj3IoLgJjEg7wxc-e-N5AZydMiQodA4hwkacaURrVC0/edit#gid=399746062) of all the terms with disease in the label in Mondo

**Comment by nicolevasilevsky** [comment]
Discussed on the Mondo call and we can go ahead and do this.
Send an email on the Mondo users list to make sure there are no objections.

**Comment by nicolevasilevsky** [comment]
consider renaming root class to disorder?

**Comment by pnrobinson** [comment]
@nicolevasilevsky  -- sounds good. Note sure if we should take a vote for disorder vs disease -- to my ears, these words sound close enough to being synonyms that it is not worth fighting over and we could make corresponding synonyms for all relevant labels. There are those who see a distinction, though, and so we should make sure we have gotten consensus before moving forward!

**Comment by nicolevasilevsky** [comment]
sounds good, @pnrobinson. @sabrinatoro and I will contact the Mondo users list before moving forward. Thank you!

**Comment by joeflack4** [comment]
## Questions
1. Where is the source file I run it against? _(I checked https://github.com/monarch-initiative/mondo/releases but couldn't find any RDF file for Mondo)_
2. Any advice on how I utilize [`location.yaml`](https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/location.yaml)? _(It seems like I can use some information here and literally copy/paste some of it into my SPARQL query in order to help me identify the correct nodes, but I'm not sure if I should use all the information, or just some, and if just some, which to use, and how.)_

**Comment by nicolevasilevsky** [comment]
1. The source file is mondo-edit.obo. Have you done SPARQL queries for Mondo before? We always use https://yasgui.triply.cc/# (but I'm not sure how it knows to query the mondo-edit.obo file....)
2. any term that has this annotation: dcterms:conformsTo http://purl.obolibrary.org/obo/mondo/patterns/location.yaml

**Comment by joeflack4** [comment]
So far I have a query that is returning some results from Yasgui, but they're all EFO terms, not Mondo.

- Yasgui url: https://api.triplydb.com/s/NS016japs
- Endpoint: https://stars-app.renci.org/ubergraph/sparql
- Query:
```sparql
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
# PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT * WHERE { 
  ?cls rdfs:label ?term_label .
  
  ?cls dcterms:conformsTo <http://purl.obolibrary.org/obo/mondo/patterns/location.yaml> .
  #  ?cls dcterms:conformsTo ?value .  # many results      
  # ?cls dcterms:conformsTo <http://purl.obolibrary.org/obo/mondo/patterns/acute.yaml>  # 2 results
  # ?cls dcterms:conformsTo "http://purl.obolibrary.org/obo/mondo/patterns/location.yaml" .  # 0 results
  
  FILTER NOT EXISTS { ?cls owl:deprecated "true"^^xsd:boolean . }
  # FILTER( !isBlank(?cls) && regex(str(?cls), "^http://purl.obolibrary.org/obo/MONDO_"))  # 0 results
  # FILTER (isIRI(?cls) && regex(str(?cls), "^http://purl.obolibrary.org/obo/MONDO_"))  # 0 results
} 
```

**Comment by matentzn** [comment]
As per slack: Yasgui only for prototyping of query - if it does roughly what you think it should, it needs to go into the Mondo Makefile pipeline as described on slack.
