### ISSUE TITLE
UROD

### ISSUE THREAD

**Issue by wchankey** [monarch-initiative/mondo#5128]
**Preferred gene-related syndrome label** UROD-related inherited porphyria

**Synonyms** N/A

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)** https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019142

**Definition** Any inherited porphyria in which the cause of the disease is monoallelic or biallelic variants in the UROD gene.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)** N/A (although please note that OMIM denotes the two children terms as synonyms under MIM 176100, https://www.omim.org/entry/176100)

**Children terms (if applicable)** Familial porphyria cutanea tarda (MONDO:0008296) and hepatoerythropoietic porphyria (MONDO:0019799) are existing terms that should be re-classified as children underneath this new proposed term. Please note that the mode of inheritance for the combined term should be semidominant, as familial porphyria cutanea tarda cases tend to harbor monoallelic UROD variants while hepatoerythropoietic porphyria cases tend to harbor biallelic UROD variants.

**Your nano-attribution (ORCID) or URL for a working group** https://clinicalgenome.org/affiliation/40097/ (This new term has been proposed by the ClinGen General IEM Gene Curation Expert Panel, which is affiliated with the Inborn Errors of Metabolism Clinical Domain Working Group.)

**Comment by wchankey** [comment]
Dear Dr. Vasilevsky,

Thank you for reviewing this new proposed term. We've attached slides detailing the research that led the ClinGen General Inborn Errors of Metabolism Gene Curation Expert Panel to recommend combining familial porphyria cutanea tarda (MONDO:0008296) and hepatoerythropoietic porphyria (MONDO:0019799) under a single term entitled "UROD-related inherited porphyria." We appreciate your time and consideration of our request.

Sincerely,
William Hankey
Biocurator

[06_24_22_UROD_pre-curation_results.pptx](https://github.com/monarch-initiative/mondo/files/9031218/06_24_22_UROD_pre-curation_results.pptx)

**Comment by wchankey** [comment]
Hi Dr. Vasilevsky,

Just a quick note to say thank you for completing this request to add the term UROD-related inherited porphyria to Mondo! Am looking forward to seeing the entry when it becomes available,

William


From: Nicole Vasilevsky ***@***.***>
Date: Friday, July 8, 2022 at 11:46 AM
To: monarch-initiative/mondo ***@***.***>
Cc: Hankey, William Charles IV ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] UROD (Issue #5128)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Closed #5128<https://github.com/monarch-initiative/mondo/issues/5128> as completed via #5151<https://github.com/monarch-initiative/mondo/pull/5151>.

**Comment by nicolevasilevsky** [comment]
You are so welcome, @wchankey!
We will run the release on Aug 01, and then you should see the new term in OLS a few days later. I'm not sure if you are on the Mondo email list - I can add you if you like (please send me your email) and we'll send an email when the release is done.

**Comment by wchankey** [comment]
That would be great if you could add my email to the list when you have a chance ***@***.***). Although I have a related assignment due a little bit after Aug 01 that will remind me to check the term in OLS around that time, so no problem either way. Thank you for your help!

William



From: Nicole Vasilevsky ***@***.***>
Date: Friday, July 8, 2022 at 6:52 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Hankey, William Charles IV ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] UROD (Issue #5128)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

You are so welcome, @wchankey<https://github.com/wchankey>!
We will run the release on Aug 01, and then you should see the new term in OLS a few days later. I'm not sure if you are on the Mondo email list - I can add you if you like (please send me your email) and we'll send an email when the release is done.
