### ISSUE TITLE
OMIMPS split terms July release- updated in OLS yet?

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#5134]
Hi
Would I expect to see these changes mention #4864  yet the current OLS? 
Currently I can not see them OLS: http://purl.obolibrary.org/obo/MONDO_0011108

from #4864 
id: MONDO:0011108
name: Stüve-Wiedemann syndrome
relationship: seeAlso https://github.com/monarch-initiative/mondo/issues/4521
relationship: seeAlso https://github.com/monarch-initiative/mondo/issues/4864
is_obsolete: true
replaced_by: MONDO:0800043

Thank you

**Comment by matentzn** [comment]
@lcdaugherty 

This would be an OLS ticket: https://github.com/EBISPOT/OLS/issues

It seems like this is an issue with refreshing OLS rather than with Mondo!

**Comment by lcdaugherty** [comment]
@matentzn thanks - sorry I am an occasional user, so thanks will put the bug there and close this.

**Comment by matentzn** [comment]
No problem, keep the issues coming! It's very valuable to see and hear everything!

**Comment by nicolevasilevsky** [comment]
@lcdaugherty I just did the release on Friday and it takes a few days for OLS to pick up the latest release - so let's check OLS again later this week.

**Comment by nicolevasilevsky** [comment]
@lcdaugherty I see the new terms now in OLS.
