### ISSUE TITLE
Make new repo for reviewing disease-phenotype annotations

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/mondo#516]
Lets create a new repo for reviewing disease phenotype annotations. Suggest we start with annotations for which we have determined equivalency between OMIM and Orphanet. We could ideally sort by date of the annotation, as well as by other features (lets brainstorm here).

The goal is to do this as a pilot, to illustrate the diversity in the curation process across different groups, and help people come up with a consensus process and QC guidelines. We can then discuss how to distribute the curation and priorities. 

@pnrobinson @jmcmurry

**Comment by nicolevasilevsky** [comment]
This ticket is very old, not sure if this is still needed. Please reopen if needed.
