### ISSUE TITLE
[Merge] terms with editors note

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5166]
MONDO ID | 	Label	| Potential term to merged with ID	| Potential term to merged with label	| Note | PR
-- | -- | -- | -- | -- | --
MONDO:0000237	| erysipeloid	| MONDO:0006752	| Erysipelothrix rhusiopathiae infectious disease'	|  Editor note: consider merging with parent | https://github.com/monarch-initiative/mondo/pull/5453
MONDO:0000561	| spinocerebellar ataxia type 16 | 	MONDO:0011694	| spinocerebellar ataxia type 15/16'	| Editor notes: Consider merging into 15/16 | https://github.com/monarch-initiative/mondo/pull/5454
MONDO:0001524	| globe disease	| MONDO:0005328	| eye disorder'	| Editor note: Consider merging with parent | https://github.com/monarch-initiative/mondo/pull/5457
MONDO:0002454	| thyroid adenoma	| MONDO:0005032	| follicular thyroid adenoma'	| Editor note: consider merging with follicular thyroid adenoma | https://github.com/monarch-initiative/mondo/pull/5459
MONDO:0004721	| liver neoplasm	| MONDO:0024477	 | 	liver and intrahepatic bile duct neoplasm'	 | 	Editor note: consider merging with liver and intrahepatic bile duct neoplasm | https://github.com/monarch-initiative/mondo/pull/5460
MONDO:0004935	| acquired carotenemia	| MONDO:0021162	| carotenemia | 	Editor note: consider merging into parent. An explicit acquired subclass was created for consistency with DO | https://github.com/monarch-initiative/mondo/pull/5876
MONDO:0005218	| muscular disease	| MONDO:0003939	| muscle tissue disorder'	| Editor note: consider merging with child | https://github.com/monarch-initiative/mondo/pull/5875
MONDO:0005410	| acute graft vs. host disease	| MONDO:0020546	| acute graft versus host disease'	| Editor note: consider merging with parent | done
MONDO:0007806	| hypotrichosis 4	| MONDO:0018631	| Marie Unna hereditary hypotrichosis' | Editor note: consider merging into MUHH | https://github.com/monarch-initiative/mondo/pull/5877
MONDO:0011751	| COPD, severe early onset	| MONDO:0005002	| chronic obstructive pulmonary disease'	| Editor note: consider merging to parent | done
MONDO:0015077	| adrenal/paraganglial tumor	| MONDO:0021227	| adrenal gland neoplasm'	| Editor note: consider merging | done
MONDO:0016251	| salivary gland type cancer of the breast	| MONDO:0003185	| adenoid cystic breast carcinoma'	| Editor note: consider merging with mammary adenoid cystic carcinoma
MONDO:0016808	| mitochondrial DNA depletion syndrome, hepatocerebral form	| MONDO:0014943	| mitochondrial DNA depletion syndrome 15 (hepatocerebral type);'	| Editor note: consider merging with MONDO:0014943
MONDO:0018303	| generalized isolated dystonia	| MONDO:0000476	| generalized dystonia'	| Editor note: consider merging with generalized dystonia if no complex forms
MONDO:0018351	| adenocarcinoma of penis	| MONDO:0002653	| Paget disease of the penis'	| Editor note: consider merging with Paget disease of penis
MONDO:0018527	| osteoclastic giant cell tumor of pancreas	| MONDO:0006479	| osteoclastic giant cell tumor of pancreas'| 	Editor note: consider merging with MONDO:0006479
MONDO:0021257	| glomus jugulare neoplasm	| MONDO:0021064	| jugulotympanic paraganglioma'	| Editor note: consider merging with jugulotympanic paraganglioma
MONDO:0021664	| cervical aortic arch | MONDO:0017991	| Takayasu arteritis'	| Editor note: consider merging with MONDO:0017991

related to https://github.com/monarch-initiative/mondo/issues/3811

- [x] Review MONDO:0011191	capillary infantile hemangioma- Editor note: consider merging or making class explicitly for inherited forms. Note also Orphanet equiv is obsolete

**Comment by nicolevasilevsky** [comment]
@sabrinatoro could you try to make slow progress on this each month or so?

**Comment by kanems** [comment]
I have Questions on why some of these were merged....

- [ ] MONDO:0016251 was merged with MONDO:0003185 ?  The Orphanet term seems to be broader than the merged target
ORPHA:213557: Salivary gland type cancer of the breast
Def: "Salivary gland type cancer of the breast describes a group of uncommon neoplasms, usually seen in the salivary glands but occurring in the breast, with a variable clinicopathologic spectrum and divided into those with myoepithelial differentiation and those without. This group includes _mammary adenoid cystic carcinoma, adenoid cystic carcinoma (see this term),_ mucoepidermoid carcinoma, acinic cell carcinoma, polymorphous low-grade adenocarcinoma and oncocytic carcinoma.
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=213557
The merged term has NCI which is included in the Orphanet definition as one sub-type? https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C5130

- [ ] MONDO:0016808 with MONDO:0014943. 
The Orphanet term seems broader than the one genetic subtype represented by OMIM 617156. Mitochondrial DNA depletion syndrome, hepatocerebral form is listed on Orphanet's site as a grouping term: https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=254871 And the OMIM Phenotypic series for Mito DNA depletion syndrome https://www.omim.org/phenotypicSeries/PS603041 has 4 different entries that list "hepatocerebral form" as part of OMIM's preferred name.

**Comment by kanems** [comment]
Working my way through some more of these cases that we were unable to map automatically... I am also wondering why MONDO:0011191 capillary infantile hemangioma and MONDO:0100300 hereditary capillary infantile hemangioma are separate concepts now? The only X-ref I am finding (in our download of the latest release) for MONDO:0011191 is UMLS C1865871, which is also where UMLS maps the OMIM and MeSH records on MONDO:0100300, so based on the mapping in UMLS, these are the same concept. 
UMLS has C4317089 for "Infantile Hemangioma" based on the NCI term: C6645, which may be a more appropriate CUI for the infantile presentation that isn't necessarily heritable.

**Comment by nicolevasilevsky** [comment]
thanks, @kanems! I'll take a look at this asap and I can unmerge them if needed before the next release.

As always, I appreciate your careful eye on Mondo! 😃

**Comment by nicolevasilevsky** [comment]
> Working my way through some more of these cases that we were unable to map automatically... I am also wondering why MONDO:0011191 capillary infantile hemangioma and MONDO:0100300 hereditary capillary infantile hemangioma are separate concepts now? The only X-ref I am finding (in our download of the latest release) for MONDO:0011191 is UMLS C1865871, which is also where UMLS maps the OMIM and MeSH records on MONDO:0100300, so based on the mapping in UMLS, these are the same concept. UMLS has C4317089 for "Infantile Hemangioma" based on the NCI term: C6645, which may be a more appropriate CUI for the infantile presentation that isn't necessarily heritable.

@kanems I will create  separate ticket to merge 'hereditary capillary infantile hemangioma' with 'capillary infantile hemangioma'.

Thanks!
