### ISSUE TITLE
Disease not present in Phenotype Profile Search tool

### ISSUE THREAD

**Issue by GenomiskDiagnostik** [monarch-initiative/mondo#5175]
# If your bug report is about Mondo, please file a ticket here instead: https://github.com/monarch-initiative/mondo/issues

## Describe the problem with the Monarch website or APIs

The search for disease: monogenic diabetes MONDO:0015967, does not yield a functional search in tool, and such it it not possible to generate catalogue of phenotypes to run similarity test on.

## Expected behavior

To generate a list of associated HPO-terms, and the option to generate similarity analysis

## To reproduce

Paste either: monogenic diabetes or MONDO:0015967 into tool search bar.

## Screenshots

If applicable, add screenshots to help illustrate the problem.

## Additional context

Add any other context about the issue that you feel may be important. e.g. browser version, time of day.

**Comment by kevinschaper** [comment]
I think this might be an api/solr problem rather than an ontology problem. If I search with either `MONDO:0015967` or `monogenic diabetes` - it will come back as the first result, but if I paste either into the autocomplete box in the phenotype comparison tool, they don't appear. The site-wide autocomplete does return them, so I think I need to look into the difference between them.

**Comment by vincerubinetti** [comment]
I'm not sure if I understand the problem 100% or if this will answer your question, but...

It seems like I am not using the `has_phenotype` flag anywhere in my code for UI 3.0. That seems to be what's causing the issue?

Your particular example of `MONDO:0015967` shows up in the (3.0) node search tool and the phenotype explorer tool. The 3.0 phenotype tool works significantly different than the 2.0 one. If you search `MONDO:0015967` in the 3.0 phenotype tool, you'll get (what I think is) the right result, but if you click on it, the app will alert you that there are no phenotypes associated with it to add to the comparison:

![image](https://user-images.githubusercontent.com/8326331/178800624-0aee4742-2535-4272-a2ea-6796cc8b43f1.png)

**Comment by kevinschaper** [comment]
That's perfect @vincerubinetti!

**Comment by nicolevasilevsky** [comment]
thanks @kevinschaper and @vincerubinetti - does this address the question? can this be closed?

**Comment by GenomiskDiagnostik** [comment]
Dear Nicole,

I think the issue has been solved, thank you.




Best regards


Thomas Lindestrand-Hansen
Molecular Biology, MSc, PhD

Zealand University Hospital, Roskilde
Dep. of Clinical Biochemistry
Clinical Molecular Biology Unit
Sygehusvej 10
4000 Roskilde

Phone:     +45 46 32 32 00
Mobile:     +45 93 56 98 06

Direct e-mail  ***@***.******@***.***>


***@***.***


www.regionsjaelland.dk

Fra: Nicole Vasilevsky ***@***.***
Sendt: 20. juli 2022 00:38
Til: monarch-initiative/mondo ***@***.***>
Cc: Thomas Lau Lindestrand-Hansen ***@***.***>; Author ***@***.***>
Emne: Re: [monarch-initiative/mondo] Disease not present in Phenotype Profile Search tool (Issue #5175)

Forsigtig: Ekstern mail

thanks @kevinschaper<https://github.com/kevinschaper> and @vincerubinetti<https://github.com/vincerubinetti> - does this address the question? can this be closed?
