### ISSUE TITLE
[NTR/gene] DPH5-related diphthamide-deficiency syndrome

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#5178]
**Preferred gene-related syndrome label**

DPH5-related diphthamide-deficiency syndrome

**Synonyms**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

"neurodevelopmental disorder" or one of its children

**Definition**

I'm not  sure, have you got any info on what should be included in the definition?

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)

  | Shankar  SP, Grimsrud K, Lanoue L, Egense A, Willis B, Hörberg J, AlAbdi L,  Mayer K, Ütkür K, Monaghan KG, Krier J, Stoler J, Alnemer M, Shankar PR,  Schaffrath R, Alkuraya FS, Brinkmann U, Eriksson LA, Lloyd K, Rauen KA. | Related Articles
-- | -- | --
  | A novel DPH5-related diphthamide-deficiency syndrome causing embryonic lethality or profound neurodevelopmental disorder.
  | Genet Med. 2022 Apr 27;. [Epub ahead of print]
  | PMID: 35482014 [PubMed -

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
note to self:
DPH5 HGNC:24270
