### ISSUE TITLE
non-histaminic angioedema

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#518]
I do not think that this is necessarily systemic, but it can be localized. However, the term is classified as a systemic disease.

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] exclude superclass 'systemic or rheumatic disease'

**Comment by kallia-p** [comment]
@nicolevasilevsky Excluded 
![image](https://user-images.githubusercontent.com/77484553/117805680-29e68380-b251-11eb-9252-d98b17b95c4c.png)
