### ISSUE TITLE
Schmitt-Gillenwater-Kelly syndrome and Radial hypoplasia-triphalangeal thumbs-hypospadias-maxillary diastema syndrome[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5204]
**Mondo term (ID and Label)**
MONDO:0042915 Schmitt-Gillenwater-Kelly syndrome 

**Reason for deprecation**
SNOMED CT 716092007 uses "Schmitt Gillenwater Kelly syndrome" and "Radial hypoplasia and triphalangeal thumb with hypospadias and maxillary diastema syndrome" as synonyms.

**Term to be merged with**
MONDO:0008357  Radial hypoplasia-triphalangeal thumbs-hypospadias-maxillary diastema syndrome

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0042915 MONDO:0008357 -o -f obo mondo-edit.obo`
