### ISSUE TITLE
[NTR/gene] 

### ISSUE THREAD

**Issue by GullyBurns** [monarch-initiative/mondo#5210]
**Preferred gene-related syndrome label**
PIK3CA-related overgrowth syndrome

**Synonyms**
PROS

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0019716

**Definition**
Any overgrowth syndrome in which the cause of the disease is a mutation in the PIK3CA gene. 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID:25557259
See also: https://www.prosspectrum.com/

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
* Fibroadipose hyperplasia or Overgrowth (FAO) - [MONDO:0017812]
* Hemihyperplasia Multiple Lipomatosis (HHML), [MONDO:0017177] 
* Scoliosis/Skeletal and Spinal (CLOVES) syndrome, [MONDO:0013038]
* macrodactyly [MONDO:0007962]
* Segmental progressive overgrowth syndrome with fibroadipose hyperplasia [MONDO:0017812] 
* Megalencephaly-Capillary Malformation (MCAP or M-CM) [MONDO:0011240]
* Dysplastic Megalencephaly (DMEG) - mentioned in definition but not in either Monarch or ORDO.

**Your nano-attribution (ORCID) or URL for a working group**
0000-0003-1493-865X

Note - this is a high level disease grouping that I've seen people in our Rare as One cohort talk about and it's not represented in MONDO but does have a designation in ORDO: https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=530313

**Comment by nicolevasilevsky** [comment]
Hi @GullyBurns! Looks like we do have this term: MONDO:0035162 'PIK3CA-related overgrowth syndrome'

I can classify the children under it, as you suggested above.

**Comment by GullyBurns** [comment]
OK. That's interesting. I was searching for it on the Monarch webpage (not the ontology) and couldn't find it there. Apologies.

**Comment by GullyBurns** [comment]
The extra terms were from a cursory read of  PMID:25557259 and may need some additional discussion for precise definitions. Would it be worth attempting to connect to members of the Rare as One community about this?

**Comment by nicolevasilevsky** [comment]
> 
OK. That's interesting. I was searching for it on the Monarch webpage (not the ontology) and couldn't find it there. Apologies.

No worries! You are right, it is not in Monarch. Monarch is not fully synched up with the latest version of Mondo. I suggest using OLS: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0035162

**Comment by nicolevasilevsky** [comment]
> The extra terms were from a cursory read of PMID:25557259 and may need some additional discussion for precise definitions. Would it be worth attempting to connect to members of the Rare as One community about this?

That would be great to connect with the Rare as One experts to add definitions to these terms. Would you mind sending them an email and include me and I can coordinate a call. Thanks @GullyBurns!

**Comment by nicolevasilevsky** [comment]
@GullyBurns I think Dysplastic Megalencephaly (DMEG) is a phenotype, I'll make a ticket on the HPO tracker
