### ISSUE TITLE
Mirror Movements 1 and/or Agenesis of the Corpus Callosum

### ISSUE THREAD

**Issue by ErinRiggs** [monarch-initiative/mondo#5219]
**Mondo term (ID and Label):** Mirror Movements 1 (MONDO:0008002)

**Suggested new label:** Mirror Movements 1 and/or Agenesis of the Corpus Callosum

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
Requested by the ClinGen Brain Malformations GCEP (https://www.clinicalgenome.org/affiliation/40020/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Evidence demonstrates that individuals with heterozygous variants in DCC may have congenital mirror movements and/or agenesis of the corpus callosum (not with or without- some individuals do not demonstrate mirror movements and only have corpus callosum defects, even within the same family) (PMIDs: 28250454, 30666715, 31697046, 33209984).

**Comment by nicolevasilevsky** [comment]
Hi @ErinRiggs 
This request is similar to https://github.com/monarch-initiative/mondo/issues/4937
For a disease that is part of an OMIM phenotypic series, we want to use the OMIM names for consistency. 'mirror movements 1' is part of a OMIM phenotypic series that is named similarly.

Would it be okay if I added this as a synonym?

As noted on the other ticket, we are open to having a conversation with your developers to figure out ways to have the ClinGen preferred label show up, or another possible solution is having a particular release file for you that displays the labels that are preferred by ClinGen. Do you think those solutions could work? We are happy to meet on a call to discuss further as well. Thank you!

**Comment by ErinRiggs** [comment]
Yes, absolutely please leave that term as a synonym - we just wanted the top level term changed as there are some people that do not have mirror movements but do have the ACC.

I'd be happy to talk about the labels again on another call, but my main concern is I feel uncomfortable with ClinGen systems needing to keep track of when they are displaying the current top-level MONDO term vs. when they might need to display an alternate label (and how confusing this may be for users), but perhaps I have misunderstood!

**Comment by nicolevasilevsky** [comment]
discussed with ClinGen: we can add this as a new class/parent of Mirror Movements 1

**Comment by ErinRiggs** [comment]
Hi @nicolevasilevsky when can we expect to see this term available on MONDO OLS?  Our curator is looking for it to finish her entry :) 

cc: @bryannavanhoute

**Comment by nicolevasilevsky** [comment]
Hi @ErinRiggs - there seems to be a problem, this term was added to Mondo on Aug 25 but I don't see it in the released file. The ID is:
MONDO:0100515

I'll look into this and let you know asap. I am currently traveling and attending conferences this week, so I may not have a chance to look into until next week, thanks for your patience.

**Comment by nicolevasilevsky** [comment]
@ErinRiggs I just ran the Mondo release and confirmed it is in the release file (https://github.com/monarch-initiative/mondo/releases/tag/v2022-10-03). 

It should be in OLS within a few days.

**Comment by ErinRiggs** [comment]
Thank you Nicole!

Erin Rooney Riggs, MS, CGC
Assistant Professor
Autism & Developmental Medicine Institute
Geisinger
***@***.***
________________________________
From: Nicole Vasilevsky ***@***.***>
Sent: Tuesday, September 27, 2022 12:50 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Riggs, Erin ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [monarch-initiative/mondo] Mirror Movements 1 and/or Agenesis of the Corpus Callosum (Issue #5219)

External: Be careful with links and files. If suspicious, alert the Information Security Office. Questions? Call 570-271-8092


Hi @ErinRiggs<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FErinRiggs&data=05%7C01%7Ceriggs%40geisinger.edu%7C8766aad3dec249b9cff208daa0b0c679%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637998978366687795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6%2F9nFur6eXl%2BAUekQlB0%2BNNcp0PFN3nm1ra2h7uw%2BV4%3D&reserved=0> - there seems to be a problem, this term was added to Mondo on Aug 25 but I don't see it in the released file. The ID is:
MONDO:0100515

I'll look into this and let you know asap. I am currently traveling and attending conferences this week, so I may not have a chance to look into until next week, thanks for your patience.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmonarch-initiative%2Fmondo%2Fissues%2F5219%23issuecomment-1259851076&data=05%7C01%7Ceriggs%40geisinger.edu%7C8766aad3dec249b9cff208daa0b0c679%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637998978366844033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ldN1N%2BFXx%2FSdIMtXhB51fA5jq9fenogM7wlOHvJ3GuQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFJTFCORHEJWD5IMPIASC3WAMXWRANCNFSM55B4OR7A&data=05%7C01%7Ceriggs%40geisinger.edu%7C8766aad3dec249b9cff208daa0b0c679%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637998978366844033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VGtllu9bWYIeCmAvX2ZAw%2FxYH%2FDLANqjBOEUhyxAbEs%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you. Geisinger Health System utilizes an encryption process to safeguard Protected Health Information and other confidential data contained in external e-mail messages. If email is encrypted, the recipient will receive an e-mail instructing them to sign on to the Geisinger Health System Secure E-mail Message Center to retrieve the encrypted e-mail.
