### ISSUE TITLE
Remove  http://purl.obolibrary.org/obo/MONDO_0011892 (epilepsy label)

### ISSUE THREAD

**Issue by ihelbig** [monarch-initiative/mondo#523]
For Epilepsy working group: 
should this be removed?

**Comment by nicolevasilevsky** [comment]
I'm not sure what the action item is. @ihelbig is this still needed? (Apologies for the long delay)

**Comment by ihelbig** [comment]
Ok to remove due to lack of gene validity

**Comment by nicolevasilevsky** [comment]
@ihelbig Sorry, I'm still unclear. Do you mean you recommend that this term should be obsoleted?

cc @ahamosh

**Comment by ihelbig** [comment]
Yes, that’s ok.

**Comment by ahamosh** [comment]
Is there a question a question in here for me?
Thanks,
Ada

Ada Hamosh, MD, MPH
Dr. Frank V. Sutland Professor
McKusick-Nathans
Department of Genetic Medicine (DGM)
Clinical Director, DGM
Scientific Director, OMIM
Johns Hopkins University
Blalock 1007
600 N. Wolfe St
Baltimore, MD 21287-4922
Phone:  410-614-3313
Fax: 410-367-3231 (Please Note new FAX number)
ahamosh@jhmi.edu

Assistant:  Heather Dozier
phone:  410-955-6641
e-mail:  hdozier1@jhmi.edu

________________________________

**Comment by nicolevasilevsky** [comment]
@ahamosh yes- are you okay with obsoleting this class in Mondo?
Thank you!

**Comment by nicolevasilevsky** [comment]
@ahamosh I see this is still in OMIM. Do you think we should obsolete it in Mondo? Will you obsolete it or keep it in OMIM?
Thanks!

**Comment by ahamosh** [comment]
Hi Nicole, can you define what this is?  "This" is still in OMIM above.  I tried reading the string and am still uncertain.  Sorry!

**Comment by nicolevasilevsky** [comment]
Hi - apologies! I meant [OMIM:607682](https://omim.org/entry/607682) EPILEPSY, IDIOPATHIC GENERALIZED, SUSCEPTIBILITY TO, 9; EIG9

(MONDO_0011892 'epilepsy, idiopathic generalized, susceptibility to, 9')

**Comment by ahamosh** [comment]
We are going to keep this in OMIM.  While the evidence is very weak, there is no evidence against.  It may disappear someday, but not yet.

**Comment by nicolevasilevsky** [comment]
We like to follow OMIM, we'll keep it too, thanks!
