### ISSUE TITLE
[NTR] microdeletion syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5236]
@sabrinatoro for the INCLUDE project, the pediatric cancer data commons (PCDC) has a survey question asking about microdeletion syndrome (it is written as: ExtracardiacFindings_MICRODELETION_SYNDROME_PRESENT)

Do you think this could be a synonym for MONDO:0000761 'syndrome caused by partial chromosomal deletion'?

There seems to be description in the literature of this as a proper disease:
- https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/microdeletion-syndrome
- https://en.wikipedia.org/wiki/Microdeletion_syndrome

If we added this, it seems like we'd want to axiomatize all the more specific microdeletion disorders using this class.

cc @lopierra

**Comment by nicolevasilevsky** [comment]
Similar question for microduplication

Would this be the same as MONDO:0000762 'syndrome caused by partial chromosomal duplication'?

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
At first and quick glance, I think these are the same. I will review the publications you added in the description and confirm though.

**Comment by nicolevasilevsky** [comment]
Thanks @sabrinatoro!

**Comment by sabrinatoro** [comment]
These are the same. I will add them as exact synonyms

**Comment by nicolevasilevsky** [comment]
Thanks @sabrinatoro!
