### ISSUE TITLE
Cole-Carpenter syndrome 

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#524]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0014573

Neither of the Cole-Carpenter syndrome should be classified as collagenopathies (they are not caused by mutations in a collagen gene)

I would suggest that many of these diseases should be classified as Hereditary bone disease (we may need to debate the primary label).

**Comment by nicolevasilevsky** [comment]
@pnrobinson what is the superclass that should be removed here?
'osteogenesis imperfecta'?

thanks!

**Comment by pnrobinson** [comment]
Cole Carpinter shared some features with Osteogenesis imperfecta, but to my knowledge, these diseases are not actually classified as subtypes of  Osteogenesis imperfecta. I am not an expert, @ahamosh do you know?

**Comment by ahamosh** [comment]
They have bone fragility, but I don't think they are osteogenesis imperfecta.  I am not an expert, either.

**Comment by nicolevasilevsky** [comment]
thank you both!
