### ISSUE TITLE
eye disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#525]
eye disease is currently listed as a type of head disease
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005328

while this is obviously true in a sense, this is not how MDs subdivide the cheese. There are some head and neck surgeons, but they do not see eye disease. 

"Disease of the eye" should be a top level term.
I know it is not logical, but the appendages of the eye also belong here, since eye doctors tend to see patients with diseases of the eyelids as well.

**Comment by paolaroncaglia** [comment]
@pnrobinson @cmungall @nicolevasilevsky 
We EFO people would also be interested in this, as our main users also like to think of 'eye disease' and 'head and neck disease' as two separate areas coexisting at high level. Are there any updates from your side, please? Thanks!

**Comment by paolaroncaglia** [comment]
(Tagging @simonjupp and @zoependlington so they can follow too.)

**Comment by paolaroncaglia** [comment]
Hi, 
Following up on this ticket, about the general issue of the 'head or neck disease/disorder' branch, see @pnrobinson 's comment above. EFO is questioning the general usefulness of 'nose disease' (see https://github.com/ebispot/efo/issues/639), so I was wondering if there's any update on that topic. Thanks.

**Comment by cmungall** [comment]
We can obsolete nose disease

Can someone advise on what the exclusion list is for head disease (and
should it be head + neck)? Scalp/skin? Brain/NS?

**Comment by pnrobinson** [comment]
Why exactly do we want to obsolete this category?
In any case if we take standard medical usage, then we would want to have a category for 
Ear/Nose/Throat disease (Otorhinolaryngological disorder)
Underneath that there are various options, but Nasal disorder (syn nose disease) would not seem out of place. There are variants like this also
http://www.ucihealth.org/medical-services/ear-nose-throat-ent/nose-sinus-disorders

**Comment by nicolevasilevsky** [comment]
@pnrobinson how to do propose reclassifying 'eye disease'? Should we remove the superclassOf assertion for 'disease of orbital region' and just leave it as a subclass of 'disease of visual system'?

We already have MONDO_0024623 'otorhinolaryngologic disease' with synonyms 'ear, nose and throat disorder' and 'ear, nose or throat disorder', ENT disease, etc. I can add the synonym 'ear/nose/throat disease'.

Do we want to obsolete 'nose disease'? Or rename it to 'nasal disorder' and make it a subclass of MONDO_0024623 'otorhinolaryngologic disease'?

**Comment by pnrobinson** [comment]
I would suggest eye diseases should be right under disease. We should not make it a subclass of  'disease of orbital region'  because (1) it is not always true and (2) ophthalmologists would not think of looking here. 
As discussed in another issue, I would suggest nasal disorder should be a subclass of 'otorhinolaryngologic disease'

**Comment by nicolevasilevsky** [comment]
I can assert 'eye disease' to be a subclass of 'disease or disorder' but it is still inferred to be a child of 'disease of orbital region' and 'disease of visual system' because of the logical definitions.

![image](https://user-images.githubusercontent.com/6722114/70006062-a899a600-1520-11ea-80b0-12f9825aa56a.png)

![image](https://user-images.githubusercontent.com/6722114/70006102-c7983800-1520-11ea-9db9-215f33595f20.png)

![image](https://user-images.githubusercontent.com/6722114/70006133-de3e8f00-1520-11ea-850a-a8771774a0e2.png)

I created this PR: https://github.com/monarch-initiative/mondo/pull/1010

**Comment by pnrobinson** [comment]
This is logically correct.
However, I think that a browser should not display this unless the user actually wants to see these inferred is-a relations, which will not be enlightening or useful to clinical users.
So, all is fine, I think....

**Comment by cmungall** [comment]
If it's inferred it's in the release version for all to see

If we have a problem with the inference then there are standard ways to fix
this. Change the logical definition such that it matches intent, or change
the upstream ontology. Or simply obsolete grouping classes if they are not
useful, or have them in an anti-slim.

is disease of orbital region a useful grouping? If so, what is the
definition? If we want a definition that excludes the globe (or globe plus
appendages, or any other such list) then we can define such a structure.

Apologies when I suggested obsoletion of disease of nose I was thinking of
external nose, but disease of the whole nose/nasal skeleton this is more
reasonable. But if we want this to include all the paranasal sinuses then
we need a broader term here as I don't think these are considered
anatomically part of the nose.

**Comment by pnrobinson** [comment]
There are several questions here
(1) How to display the ontology for a specific group. For an MD, they have basically memorized all anatomy and do not need an ontology to know the eye is in the orbit etc.. My best guess is that they will want to see a hierarchy that matches clinical use, i.e., what medical specialty sees what kind of disease. Researchers may want to see more inferences. So, we should consider having flexible release files, e.g., mondo-clinical.json and mondo-everything-inferred.json
(2) Ophthalmologists probably will see most diseases of the orbital region as well, but not all. For instance, if you have a skin disease that affects that region it would be seen by a dermatologist, and there is probably also overlap with ENT.

**Comment by cmungall** [comment]
How would the flexible release files be displayed? Most people use an
existing hosted browser such as OLS, BioPortal, or the monarch site. Having
separate json files would only help the subset of opthalmologists that are
comfortable looking at json.

I think having subsets (metaclasses) and working with groups like OLS here
may be the way to go

**Comment by pnrobinson** [comment]
I would suggest that we implement a MONDO browser on the Monarch UI with these features.
At some point, the HPO webpage will start to use Mondo, hopefully in the nearish future, and then we will also implement some clinically useful browsing tools. We need to discuss how to move forward as a group with all of this, not sure that issues/email is the best way, but there is no immediate rush.

**Comment by nicolevasilevsky** [comment]
> is disease of orbital region a useful grouping? If so, what is the
definition? 

'disease of orbital region' was created based on Mondo patterns and has two children:
MONDO_0000462 'eye adnexa disease'
MONDO_0020150 'rare palpebral, lacrimal system and conjunctival disease'

It seems like these two children could be reclassified as children of 'eye disease' and we could obsolete 'disease of orbital region'?

**Comment by cmungall** [comment]
On Tue, Dec 3, 2019 at 1:08 PM Nicole Vasilevsky <notifications@github.com>
wrote:

> is disease of orbital region a useful grouping? If so, what is the
> definition?
>
> 'disease of orbital region' was created based on Mondo patterns and has
> two children:
> MONDO_0000462 'eye adnexa disease'
> MONDO_0020150 'rare palpebral, lacrimal system and conjunctival disease'
>
You're just looking at the asserted view, there are more:
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002022

But my question wasn't about existing children, more about what are the
clinically expected children and how does that differ from the logical view?


> It seems like these two children could be reclassified as children of 'eye
> disease' and we could obsolete 'disease of orbital region'?
>
Note that currently eye disease is defined in terms of uberon:eyeball, so
it wouldn't include eyebrows or lacrimal system

**Comment by nicolevasilevsky** [comment]
Fair enough. I can't really comment on how clinicians would expect to see eye diseases classified.

Let me know what I can do to help fix this (if anything).

**Comment by paolaroncaglia** [comment]
Note for self, @zoependlington and @nicolevasilevsky : at this stage, EFO will not suggest specific edits in the area of Mondo 'eye disease'. I will however keep the 'EFO' tag in this ticket as the general discussion is of interest to us. Of course, feel free to close if no action item is required on the Mondo side. Thanks!

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall are there any action items on this ticket? would it be okay to close?

**Comment by nicolevasilevsky** [comment]
I will just close this, please reopen if needed
