### ISSUE TITLE
Add canine part of NCIT + other non-human animal NCiT terms

### ISSUE THREAD

**Issue by diatomsRcool** [monarch-initiative/mondo#5252]
Is it possible to import the canine portion of NCIT? Would like to have this for a collaboration with veterinarians exploring translational medicine in cancer between humans and dogs - also for using dogs as sentinel species. This is related to the veterinary workshop we had in 2022.

**Comment by diatomsRcool** [comment]
any progress to report to the canine phenotype group in the meeting tomorrow?

**Comment by sabrinatoro** [comment]
no progress to report. I looked at the list, and I am investigating how we could bring the whole non-human neoplasm branch into mondo. 
It will take some time.

**Comment by sabrinatoro** [comment]
I updated this issue title to include more non-human animal neoplasm terms. 

I did not add ALL the non-human animal neoplasm terms. For this first part, I focused on: 
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9994213d-7fff-daf8-28c5-60702ab5bee4"><div dir="ltr" style="margin-left:0pt;" align="left">

Term label | NCIT id |  
-- | -- | --
Bovine Neoplasm | http://purl.obolibrary.org/obo/NCIT_C134527 | +children terms
Canine Neoplasm | http://purl.obolibrary.org/obo/NCIT_C134526 | +children terms
Equine Experimental Organism Diagnosis | http://purl.obolibrary.org/obo/NCIT_C134535 | +children terms
Feline Experimental Organism Diagnosis | http://purl.obolibrary.org/obo/NCIT_C134528 | +children terms
Chicken Neoplasm | http://purl.obolibrary.org/obo/NCIT_C135005 | +children terms
Fish Melanoma | http://purl.obolibrary.org/obo/NCIT_C135006 | Only this term
Porcine Leukemia | http://purl.obolibrary.org/obo/NCIT_C141365 | Only this term
Porcine Lymphoma | http://purl.obolibrary.org/obo/NCIT_C134786 | Only this term
Sheep Lung Adenocarcinoma | http://purl.obolibrary.org/obo/NCIT_C147532 | Only this term

</div></b>

**Comment by sabrinatoro** [comment]
ROBOT template: https://docs.google.com/spreadsheets/d/e/2PACX-1vSdOTOynPFnN22kIMXlRjpYiff77NI0kC_vRh2m9SYvKZxpKMV4b2geTjTQJIagYDxXLNq6I_NAL9nL/pub?gid=940579250&single=true&output=tsv

and [here](https://docs.google.com/spreadsheets/d/1PpxvnbEkrL5D2G1dAoLEvzrA9ZHjRTGfogX6JI693zM/edit#gid=940579250)

**Comment by sabrinatoro** [comment]
Update NCIT inclusion and exclusion list to ensure synchronization: 
- add the main branch to the NCIT synchronization sparql
- exclude the terms that should not be included (exclusion code: species out of scope)

@matentzn : Which sparql query should be updated? Is it 
(1) https://github.com/monarch-initiative/mondo/blob/master/src/sparql/signature/ncit-subclass-of-disease.sparql
(2) ???? (I remember the query you showed on the technical call was different than the one in (1), but I cannot find it)
Thanks!

**Comment by matentzn** [comment]
(2) and (3) for sure. 

A syntax like:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dbpedia2: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# For SNOMED, we are only interested in the Disease or Disorder branch
SELECT DISTINCT ?term ?label ?deprecated
WHERE {
  VALUES ?roots {<http://purl.obolibrary.org/obo/NCIT_C2991> <http://purl.obolibrary.org/obo/NCIT_C134533>}
  { 
    { 
     ?s1 ?p1 ?term . 
     ?term rdfs:subClassOf* ?roots .
     OPTIONAL {
       ?term rdfs:label ?label
     }
     OPTIONAL {
       ?term owl:deprecated ?deprecated
     }
    }
    UNION
    { 
      ?term ?p2 ?o2 . 
      ?term rdfs:subClassOf* ?roots .
      OPTIONAL {
        ?term rdfs:label ?label
      }
      OPTIONAL {
        ?term owl:deprecated ?deprecated
      }
    }
  }
}
```

Should work, but need to test with robot locally.

**Comment by sabrinatoro** [comment]
@joeflack4 : before closing this issue, the last piece missing is whether you need to add the new exclusion code in your code somewhere
The new exclusion code is:  MONDO:excludeSpeciesoutofscope
It was added  our source of truth [here](https://docs.google.com/spreadsheets/d/18V-_j4b22LzCytxFEM3pBEl6-_ODJY06gpUwH0F6JVY/edit#gid=1644570180) and [here](https://mondo.readthedocs.io/en/latest/editors-guide/exclusion-reasons/).

**Comment by joeflack4** [comment]
@sabrinatoro Roger that. I may or may not need to change any code for this. Will look into it this week.

**Comment by joeflack4** [comment]
Yeah you can close this. I don't think I need to add `MONDO:excludeSpeciesoutofscope` anywhere. The script will accept any exclusion code that you write in the exclusion table files; it doesn't check for validity right now. Sorry I didn't follow up on this.

**Comment by sabrinatoro** [comment]
Thank you! Closing now
