### ISSUE TITLE
[NTR] Complex neurodevelopmental disorder with motor features

### ISSUE THREAD

**Issue by ErinRiggs** [monarch-initiative/mondo#5253]
**Preferred term label:** Complex neurodevelopmental disorder with motor features

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**  A disorder that involves more than one phenotype associated with the central nervous system, including but not limited to intellectual disability, autism, and seizures (epilepsy). Additionally, the disorder features at least one phenotype associated with motor function, including but not limited to spasticity, hypo- or hypertonia, dyskinesia, choreo-athetosis, or ataxia.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**  Complex neurodevelopmental disorder (MONDO:0100038)

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)  This is being requested by the ClinGen Cerebral Palsy GCEP (https://www.clinicalgenome.org/affiliation/40113/).

**Comment by nicolevasilevsky** [comment]
Emailed Erin on 08/15/22 to inquire about meeting to discuss the use case for this term.

**Comment by nicolevasilevsky** [comment]
@ErinRiggs I added this term:
ID: MONDO:0100516

<img width="926" alt="image" src="https://user-images.githubusercontent.com/6722114/186534208-5978d1cc-303e-409a-b0d8-b308cbcea682.png">

Please let me know if any children should be added or if you'd like any revisions. It will be available in the Sept release. Thanks!

**Comment by ErinRiggs** [comment]
Great!  Right off the bat, I know we plan to use this for the genes EMC1 and ADD3.  When is the September release (end of month, beginning of month, etc.)?

The only change I would make is changing the word "conventional" in "conventional diagnosis" to "clinical."

Thanks,
Erin

Erin Rooney Riggs, MS, CGC
Assistant Professor
Autism & Developmental Medicine Institute
Geisinger
***@***.***
________________________________
From: Nicole Vasilevsky ***@***.***>
Sent: Wednesday, August 24, 2022 5:25 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Riggs, Erin ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [monarch-initiative/mondo] [NTR] Complex neurodevelopmental disorder with motor features (Issue #5253)

External: Be careful with links and files. If suspicious, alert the Information Security Office. Questions? Call 570-271-8092


@ErinRiggs<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FErinRiggs&data=05%7C01%7Ceriggs%40geisinger.edu%7C6e8a7af4b7704519873108da861f94ff%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637969767458429214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=67WiOvuYjyuaf8Pot%2BxUE0Fn5A8bFMNhGFHQp2Y3p30%3D&reserved=0> I added this term:
ID: MONDO:0100516

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6722114%2F186534208-5978d1cc-303e-409a-b0d8-b308cbcea682.png&data=05%7C01%7Ceriggs%40geisinger.edu%7C6e8a7af4b7704519873108da861f94ff%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637969767458429214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FN0h0xBD9cb%2FfIsIa47MSwor756l6SKaGNvV0qOFm%2FE%3D&reserved=0>

Please let me know if any children should be added or if you'd like any revisions. It will be available in the Sept release. Thanks!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmonarch-initiative%2Fmondo%2Fissues%2F5253%23issuecomment-1226511662&data=05%7C01%7Ceriggs%40geisinger.edu%7C6e8a7af4b7704519873108da861f94ff%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637969767458429214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YPj6XDwvT1i1Gq1ahumnf1r7osAJ%2FVf1t%2FqdzcMDWqE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFJTFFVNYWKHBRZNIQK6Z3V22OONANCNFSM55XHYQHA&data=05%7C01%7Ceriggs%40geisinger.edu%7C6e8a7af4b7704519873108da861f94ff%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637969767458429214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PU4LQIJ5SQNtlRbWuuDyk6DUKbpBFj6tuCFBAnFsC6I%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you. Geisinger Health System utilizes an encryption process to safeguard Protected Health Information and other confidential data contained in external e-mail messages. If email is encrypted, the recipient will receive an e-mail instructing them to sign on to the Geisinger Health System Secure E-mail Message Center to retrieve the encrypted e-mail.

**Comment by nicolevasilevsky** [comment]
Thanks @ErinRiggs , I updated the comment.

When you have a chance, could you let me know if these terms would be appropriate children of this new term:

**Comment by ErinRiggs** [comment]
Sorry Nicole I didn't see your question earlier (I was just in here checking the status of this request) - yes, those two terms would be appropriate to add as children!

**Comment by icordovaG** [comment]
Hi, just following up on this. I'm still not seeing the MONDO term MONDO:0100516 complex neurodevelopmental disorder with motor features as being active. However, I see that it was added in the above comments, was it removed again?

**Comment by nicolevasilevsky** [comment]
Hi @icordovaG I confirmed that this term is in the latest release. Are you looking in OLS? OLS has an old version Mondo at the moment, they told me it would be updated on Oct 18, I believe.

**Comment by icordovaG** [comment]
Hi @nicolevasilevsky, I'm still not seeing this entry. Can you confirm that the release was yesterday or was there possibly a delay? 
Thank you

**Comment by kanems** [comment]
@icordovaG I've been waiting for the OLS update, too. Looks like it finally processed... https://www.ebi.ac.uk/ols/ontologies/mondo 
Version: 2022-10-11
Number of terms: 44643
Last loaded: Tue Oct 18 14:46:32 BST 2022

**Comment by icordovaG** [comment]
Hi @kanems, thanks I'm seeing it here now!
