### ISSUE TITLE
Disable create ongoing diffs workflow on forks

### ISSUE THREAD

**Issue by dhimmel** [monarch-initiative/mondo#5255]
I have a fork of `monarch-initiative/mondo` for the sole purpose of making occasional contribution. Just got an email from GitHub:

> [GitHub] The "Create ongoing diffs" workflow in dhimmel/mondo has been disabled
> Scheduled workflows are disabled automatically after 60 days of repository inactivity

We can see that my fork has [been running](https://github.com/dhimmel/mondo/actions/workflows/diff.yaml) "Create ongoing diffs" on a weekly basis:

![image](https://user-images.githubusercontent.com/1117703/183506588-8c378c9f-355b-44be-a0d2-e3c91f14912c.png)

The schedule configuration is at

https://github.com/monarch-initiative/mondo/blob/ed82d2ce4e48a8137d9b752e3945bd16233d25a4/.github/workflows/diff.yaml#L1-L5

This takes a considerable amount of compute for something that most users with forked repos don't care about. So would it make sense to only run "Create ongoing diffs" on `monarch-initiative/mondo`?

Happy to submit a PR if that makes sense?

**Comment by nicolevasilevsky** [comment]
Thanks @dhimmel! Let me talk to Nico about this and I'll get back to you later this week.

**Comment by matentzn** [comment]
1000% I didnt not know that forks would execute workflows the same way! This particular one is totally irrelevant for forks. Happy to take a PR!

**Comment by dhimmel** [comment]
Okay I synced my fork to include a5d1b3c7acafc08b4021aed4ad6f9ff94f0cafaa. If we wait a week and don't see any new scheduled workflow runs at https://github.com/dhimmel/mondo/actions/workflows/diff.yaml?query=event:schedule then we'll know this worked.

**Comment by nicolevasilevsky** [comment]
thanks! :)

**Comment by nicolevasilevsky** [comment]
@dhimmel have you had a chance to check this yet? Please feel free to close whenever it is done, thanks!
