### ISSUE TITLE
Question on naming age-of-onset disorders

### ISSUE THREAD

**Issue by Anne-Pariser** [monarch-initiative/mondo#526]

**Comment by Anne-Pariser** [comment]
No doubt a naive question, but soliciting your thoughts on syndromes generally named by age of onset which may be different diseases (e.g., CLN2 CLN7) vs severity of single enzyme or protein amount/copies (infantile-onset Pompe vs late-onset, SMA types 1, 2 or 3) vs. type of mutation (missense, CRIM negative)

**Comment by maglott** [comment]
I'm also looking for ideas for best practices for trying to capture age of onset as a descriptor.
I've noticed, for example, that OMIM is starting the add the same alternate name to multiple records, e.g. CORNEAL DYSTROPHY, FUCHS ENDOTHELIAL, LATE-ONSET.  I notice these are represented as 'hasRelatedSynonym' in the json (ignoring that I still consider 'related synonym' as a contradiction in terms) but should these phrases be considered as phrases to support searching and not as 'names'?

**Comment by mellybelly** [comment]
it would be great to use the same structure as HPO and Phenopackets for age of onset. 
@julesjacobsen @drseb can you provide some recommendations?
@cmungall we should finalize/document developmental stages alignments between HPO and the stages ontology work, never quite completed that...

**Comment by cmungall** [comment]
We can add more DPs such as this one:
https://github.com/monarch-initiative/mondo/blob/master/src/patterns/adult.yaml

We can standardize nomenclature in there

re: "related synonym". Yes a lot of people have brought this up, perhaps we
should have used a related synonym of "synonym" (this goes back to GO
2001-ish). The gradation is incredibly useful though.

**Comment by nicolevasilevsky** [comment]
I don't think any other action is needed here. Please reopen if we should add additional onset modifiers.
