### ISSUE TITLE
MONDO:0005272 refractory anemia (plus possible revision to all subtypes of MONDO:0018881 myelodysplastic syndrome)

### ISSUE THREAD

**Issue by lcdaugherty** [monarch-initiative/mondo#5268]
**Mondo term (ID and Label):**
MONDO:0005272 refractory anemia

**Suggested new label:**
myelodysplastic syndrome with single lineage dysplasia

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**

The definition for 'refractory anemia' represented in MONDO is based on WHO data 2001 classification (via NCIT/Orphanet) http://purl.obolibrary.org/obo/MONDO_0005272

However, in the current, more recent WHO classification (2016), the term 'refractory anemia' is not used any more, and has been replaced with 'myelodysplastic syndrome with single lineage dysplasia' (MDS with single lineage dysplasia).

'refractory anemia' seems to be encompassed as a subtype of 'myelodysplastic syndrome with single lineage dysplasia' - in this case the single lineage being erythroid, and also representing the most common form of dysplasia within the class.

Another possibly it is that 'refractory anemia' is  actually a phenotype in some of each new subtypes eg: MDS with isolated 5q- syndrome has anemia, and can only present with anemia, but can be considered with refractory anemia?

This revision might affect MONDO:0018881 'myelodysplastic syndrome' subtypes, due to all definitions relating to (WHO, 2001) [ via NCIT] and this group of diseases are all subsets : ordo_group_of_disorders / ordo_disease, so it might need further input from Orphanet for revision?

Supporting evidence: 
- PMID/publications
https://pubmed.ncbi.nlm.nih.gov/27776290/
https://www.intechopen.com/chapters/64871
https://www.pathologyoutlines.com/topic/bonemarrowneoplasticMDSWHO.html
- WHO (2016)
https://www.pathologyoutlines.com/topic/bonemarrowneoplasticMDSWHO.html
- AJMC, January 4, (2022)
https://www.ajmc.com/view/identifying-myelodysplastic-syndromes-subtypes

**Comment by nicolevasilevsky** [comment]
@sabrinatoro I am assigning this to you. I marked it for the October release since it may require some research and may be a bigger ticket. Thanks!

**Comment by sabrinatoro** [comment]
Based on https://www.intechopen.com/chapters/64871, the following should be do/reviewed:

Mondo | Mondo name | renaming based on WHO 2016 | additional to-do
-- | -- | -- | --
MONDO:0005272 | refractory anemia' | MDS with single lineage dysplasia (MDS-SLD) | **[ ] RE-CLASSIFY** as it is not a "multilineage dysplasia"    **[ ] review definition** as "MDS-SLD includes refractory anemia (unilineage erythroid dysplasia), refractory neutropenia (unilineage dysgranulopoiesis), and refractory thrombocytopenia (unilineage dysmegakaryocytopoiesis)."   **[ ] add synonyms**: Refractory cytopenia with unilineage dysplasia (RCUD), refractory anemia (RA), refractory neutropenia (RN), and refractory thrombocytopenia (RT)
MONDO:0019453 | refractory cytopenia with multilineage dysplasia' | MDS with multilineage dysplasia (MDS-MLD) | _[already a synonym]_
MONDO:0019157 | acquired idiopathic sideroblastic anemia' | MDS with ring sideroblasts (MDS-RS) | _[already a synonym]_
MONDO:0007925 | chromosome 5q deletion syndrome' | Myelodysplastic syndrome associated with isolated del(5q) |  
MONDO:0019454 | myelodysplastic syndrome with excess blasts' | _ok_ |  
MONDO:0015040 | myelodysplastic syndrome with excess blasts-1' | _ok_ |  
MONDO:0015041 | myelodysplastic syndrome with excess blasts-2' | _ok_ |  
MONDO:0018881 | myelodysplastic syndrome' | _ok_ | **add synonym:** MDS, unclassifiable (MDS-U)
MONDO:0044874 | refractory cytopenia of childhood' | _ok_ |

**Comment by kanems** [comment]
I think some of the X-refs on MONDO:0005272 need to be reviewed/moved or removed...
-NCIT:C2872 (MONDO:equivalentTo) is still "Refractory Anemia" but NCIT has this term: Myelodysplastic Syndrome with Single Lineage Dysplasia (Code C82591) and I think this may be a better match for the Mondo record?
-UMLS:C0002893 (Orphanet:98826/e) is "Refractory anemias" https://uts.nlm.nih.gov/uts/umls/concept/C0002893 but UMLS maps the NCIT term to "Refractory cytopenia with unilineage dysplasia" UMLS CUI: C2826318
-SCTID:109996008 (MONDO:equivalentTo) is "Refractory anemia (clinical)" preferred, but with an alt name/finding of "Myelodysplastic syndrome: Refractory anemia, without ringed sideroblasts, without excess blasts (disorder)" and I'm not sure, but maybe it doesn't fit on this Mondo concept? (either case, UMLS maps it to yet another CUI: C2981142, suggesting they think it is a distinct concept from either CUI above) Maybe a better match is "Refractory cytopenia with unilineage dysplasia" SCTID 1153345005 (this is a parent to these other concepts in SNOMED CT :Refractory anemia, Refractory neutropenia, Refractory thrombocytopenia; which suggests this is a closer match conceptually given the new WHO definition and grouping provided on Mondo)
