### ISSUE TITLE
mental disorder

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#527]
The two classifications of mental disorder are debatable.

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005084

It is not the case that every mental disorder is a psychiatric disorder, and this link is wrong.

Logically it is the case that every mental disorder is a brain disorder, but there are many cases of mental disorder where it is not possible to identify the "cause" in the brain, and so I am not sure this is the best primary classification. I do not have an easy answer right now, but this needs TLC.

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/130

**Comment by nicolevasilevsky** [comment]
moved to discussion: https://github.com/monarch-initiative/mondo/discussions/2678
