### ISSUE TITLE
[IFT140-related recessive ciliopathy/IFT140]

### ISSUE THREAD

**Issue by wchankey** [monarch-initiative/mondo#5273]
**Preferred gene-related syndrome label**
IFT140-related recessive ciliopathy

**Synonyms**
Narrow synonym #1 = short-rib thoracic dysplasia 9 with or without polydactyly (MONDO:0009964)
Narrow synonym #2 = retinitis pigmentosa 80 (MONDO:0054708)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
ciliopathy

**Definition**
Any ciliopathy in which the cause of the disease is biallelic variants in the _IFT140_ gene.

**Definition source** (Please give PubMed ID, if applicable, in format PMID:#######)
The definition source is the work of the ClinGen Retina Gene Curation Expert Panel. An excerpt from this group's evidence summary is copied and pasted here:  "The *IFT140* gene was first reported in relation to autosomal recessive cases of Mainzer-Saldino syndrome or the clinically overlapping Jeune syndrome in 2012 (Perrault et al., PMID: 22503633). Affected individuals with causal biallelic variants in IFT140 have since been identified in a number of other publications, with syndromic cases most often referred to as short-rib thoracic dysplasia 9 with or without polydactyly (PMID: 23418020), and non-syndromic cases typically diagnosed with Leber congenital amaurosis or retinitis pigmentosa 80 (PMID: 26216056). Some of the causal *IFT140* variants overlap between cases with different diagnoses, and a single affected family can include both ocular and syndromic cases (PMID: 26359340). Per criteria outlined by the ClinGen Lumping & Splitting Working Group, we found the molecular mechanism (biallelic loss of function in the IFT140 gene product) and mode of inheritance (autosomal recessive) to be consistent among unrelated patients diagnosed with either short-rib thoracic dysplasia 9 with or without polydactyly (MIM#: 266920), Leber congenital amaurosis, or retinitis pigmentosa 80 (MIM#: 617781). The phenotypic variability between them appeared to represent a spectrum of disease rather than separate disease entities. Therefore, these cases have been lumped into a single disease entity, referred to as IFT140-related recessive ciliopathy."

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
Although the proposed term is a lumped disease entity combining short-rib thoracic dysplasia 9 with or without polydactyly (MONDO:0009964) and retinitis pigmentosa 80 (MONDO:0054708), it may function better as a replacement for these terms rather than as a parent to them.

**Your nano-attribution (ORCID) or URL for a working group**
https://clinicalgenome.org/affiliation/40072/

**Comment by wchankey** [comment]
Thank you Dr. Vasilevsky for reviewing this request when you have time.

**Comment by nicolevasilevsky** [comment]
@wchankey sure thing, thanks for this request. We should be able to add this for the next release on Sept 01.

**Comment by wchankey** [comment]
Perfect, thank you Dr. Vasilevsky!


From: Nicole Vasilevsky ***@***.***>
Date: Monday, August 15, 2022 at 11:56 AM
To: monarch-initiative/mondo ***@***.***>
Cc: Hankey, William Charles IV ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] [IFT140-related recessive ciliopathy/IFT140] (Issue #5273)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@wchankey<https://github.com/wchankey> sure thing, thanks for this request. We should be able to add this for the next release on Sept 01.

**Comment by nicolevasilevsky** [comment]
Hi @wchankey I am looking at this more closely. We aim to follow OMIM with their disease names and representations, so I will let OMIM know about your request to merge/lump short-rib thoracic dysplasia 9 with or without polydactyly (MONDO:0009964) and retinitis pigmentosa 80 (MONDO:0054708) into this new class. For now, I'll add your new term and add those terms as children.

If OMIM merges them into one class, we'll follow suit.

Thanks!

@ahamosh please see above, thanks! 👀

**Comment by wchankey** [comment]
Hi Dr. Vasilevsky,

That seems like a smart strategy to consult OMIM about potentially merging/lumping the two diseases associated with IFT140. Thanks for letting me know!

William


From: Nicole Vasilevsky ***@***.***>
Date: Monday, August 15, 2022 at 5:03 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Hankey, William Charles IV ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] [IFT140-related recessive ciliopathy/IFT140] (Issue #5273)

Hi @wchankey<https://github.com/wchankey> I am looking at this more closely. We aim to follow OMIM with their disease names and representations, so I will let OMIM know about your request to merge/lump short-rib thoracic dysplasia 9 with or without polydactyly (MONDO:0009964) and retinitis pigmentosa 80 (MONDO:0054708) into this new class. For now, I'll add your new term and add those terms as children.

If OMIM merges them into one class, we'll follow suit.

Thanks!

@ahamosh<https://github.com/ahamosh> please see above, thanks! 👀

**Comment by nicolevasilevsky** [comment]
I added this as id: MONDO:0100509. It will be available in the Sept release

**Comment by ahamosh** [comment]
Hi Nicole,  OMIM will not be lumping entries into ciliopathy.  This should remain as an upper-level term with OMIM children.  For IFT140, there are clearly individuals with isolated RP, so the distinct entities should not be lumped.  Fine to lump for gene-level curation, but even for variant level curation, the committees should be careful.

**Comment by wchankey** [comment]
Hi Dr. Hamosh,

Thank you for your reply to help reach the right answer about IFT140’s relationships to isolated RP and syndromic cases. The solution you described matches well with the findings of the Retina GCEP too. (Although the group found the sum of the evidence to favor lumping under ciliopathy for gene-level curation, we definitely came across families in the literature with isolated RP where other phenotypes had been screened for and not found.) I was hoping to bother you with a quick follow-up question to clarify:  Since the Retina group was hoping for IFT140-related recessive ciliopathy to be created as a new term in Mondo, would you recommend that it be designed as an upper-level term under “ciliopathy” with “Retinitis pigmentosa 80” and “Short-rib thoracic dysplasia 9 with or without polydactyly” as children? Thank you for your time!

Bill


From: ahamosh ***@***.***>
Date: Tuesday, August 16, 2022 at 10:53 AM
To: monarch-initiative/mondo ***@***.***>
Cc: Hankey, William Charles IV ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] [IFT140-related recessive ciliopathy/IFT140] (Issue #5273)

Hi Nicole, OMIM will not be lumping entries into ciliopathy. This should remain as an upper-level term with OMIM children. For IFT140, there are clearly individuals with isolated RP, so the distinct entities should not be lumped. Fine to lump for gene-level curation, but even for variant level curation, the committees should be careful.

**Comment by ahamosh** [comment]
Precisely, curate to the upper level, but describe the phenotype based on the child terms and potentially curate the variants to the child terms if they breed true.

**Comment by wchankey** [comment]
Thanks for writing back, this is helpful. The group has been a little bit nervous that lumping for genes like this might put the variant curators in a more difficult position, but this sounds like the right solution to that. Thank you!

From: ahamosh ***@***.***>
Date: Tuesday, August 16, 2022 at 3:37 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Hankey, William Charles IV ***@***.***>, Mention ***@***.***>
Subject: Re: [monarch-initiative/mondo] [IFT140-related recessive ciliopathy/IFT140] (Issue #5273)

Precisely, curate to the upper level, but describe the phenotype based on the child terms and potentially curate the variants to the child terms if they breed true.

**Comment by nicolevasilevsky** [comment]
I added this new term with the existing Mondo class as children. Thanks @ahamosh and @wchankey
