### ISSUE TITLE
Degenerative disease is wrong

### ISSUE THREAD

**Issue by ahamosh** [monarch-initiative/mondo#528]
Everything under degenerative disease is not a disease but a feature or a process
 http://purl.obolibrary.org/obo/MONDO_0024236

**Comment by ahamosh** [comment]
@nicolevasilevsky

**Comment by cmungall** [comment]
Nicole, can you review these? I tackled some in the previous release. Also coordinate with NCIT as they have a similar grouping

**Comment by nicolevasilevsky** [comment]
Currently, all the children of degenerative disease look okay to me, with the exception of MONDO_0006044 nephrosclerosis- I just removed the superclass from that term in a PR. 

Otherwise, I think everything looks okay? @ahamosh would you mind checking?

**Comment by cmungall** [comment]
Hi @nicolevasilevsky, if you want @ahamosh to evaluate do you want to include a screenshot or some kind of table file dump?

**Comment by nicolevasilevsky** [comment]
@ahamosh you can see the children of degenerative disorder here: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0024236

Note, I removed nephrosclerosis from this branch.

**Comment by nicolevasilevsky** [comment]
I think all the direct children of degenerative disorder look okay. Looking more closely at some of the children, these terms may be incorrectly classified as children of **neurodegenerative disease:**
- MONDO_0006497 'cerebral palsy'
- MONDO_0009196 'ermine phenotype'

**Comment by cmungall** [comment]
Can you go ahead and make a PR to fix these. Also look at the axiom annotations to determine why the classification was made and report to upstream sources. I did this with the first, see: https://github.com/NCI-Thesaurus/thesaurus-obo-edition/issues/45

**Comment by nicolevasilevsky** [comment]
Ada sent me an email and said: 
"I don't think that degenerative disease is useful.  I agree that what you removed is completely wrong, but atrophy is really degenerative, at least in my mind..."

**Comment by cmungall** [comment]
happy to lose it (but keep more specific classes like ND disease)

**Comment by nicolevasilevsky** [comment]
Ok - I am going to create PRs to remove the superclass assertions for MONDO_0006497 'cerebral palsy' and MONDO_0009196 'ermine phenotype', and will obsolete the term MONDO_0024236 'degenerative disorder'.

**Comment by cmungall** [comment]
Thanks for removing the incorrect assertions

Re: obsoletions, we should poll a wider group of people, it's not necessarily wrong, one option would be just to exclude it from a core slim

**Comment by nicolevasilevsky** [comment]
@zoependlington @paolaroncaglia 
do you have any objections to obsoleting 'degenerative disorder'? I don think it would be replaced by anything else, just obsoleted.

**Comment by cmungall** [comment]
I think we have to look at the subclasses as well - the PR has some issues as it loses logical axiomatization for subclasses, but many of the subclasses look like they should be phenotypes
