### ISSUE TITLE
Spondyloepiphyseal dysplasia (MONDO_0016761) does NOT involve the metaphyses

### ISSUE THREAD

**Issue by azankl** [monarch-initiative/mondo#5280]
**Mondo term (ID and Label)**
[Spondyloepiphyseal dysplasia MONDO_0016761](http://purl.obolibrary.org/obo/MONDO_0016761)

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
An osteochondrodysplasia that results in abnormalities of bone growth located in vertebral column, located in epiphysis
or
An osteochondrodysplasia that results in abnormalities of bone growth located both in the vertebral column and the epiphyses of long bones.

My first definition is based on the original definition, sounds a bit clunky, but this might be intentional (is that a Dead Simple OWL Design Pattern?)

The latter definition is more expressive and human readable.

The important point is that abnormalities in the metaphyses are not included in the definition of Spondyloepiphyseal Dysplasia. An osteochoendrodysplasia with abnormalities in the spine, epiphyses and metaphyses is called Spondylo-epi-metaphyseal dysplasia (synonyms: spondyloepimetaphyseal dysplasia or SEMD).

This means that Spondylo-epi-metaphyseal dysplasia (and its abbreviation SEMD) are not synonyms of Spondyloepiphyseal dysplasia.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
[0000-0001-8612-1062](https://orcid.org/0000-0001-8612-1062)

**Comment by nicolevasilevsky** [comment]
Hi @azankl thanks for the ticket! It looks like original definition comes from DO (DOID:0080027) and also has xrefs to Wikipedia (http://en.wikipedia.org/wiki/Spondyloepimetaphyseal_dysplasia) and Orphanet (http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=252).

I'll update the def to:
An osteochondrodysplasia that results in abnormalities of bone growth located both in the vertebral column and the epiphyses of long bones.

**Comment by nicolevasilevsky** [comment]
I made spondylo-epi-(meta)-physeal dysplasia a narrow synonym, is this correct (it is more specific)?

**Comment by nicolevasilevsky** [comment]
Are the synonyms 'spondyloepiphyseal dysplasia and spondyloepimetaphyseal dysplasia' and 'SED and SEMD' correct? these seem more specific and maybe this should be a child class?

**Comment by nicolevasilevsky** [comment]
The DO xref is to spondyloepimetaphyseal dysplasia
(see: https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_0080027)

I noted this Mondo term is broader than the DO term.

**Comment by azankl** [comment]
Yes, we need a MONDO class 'spondyloepimetaphyseal dysplasia' (Synonym: SEMD). There are a number of SEMD subtypes that should be children of this new class (e.g. MONDO_0011335, MONDO_0010076, basically any disorder that has 'spondyloepimetaphyseal dysplasia' as part of its name).

Spondyloepimetaphyeal dysplasia should be a sibling of Spondyloepiphyseal Dysplasia, not a child.

Spondylo-epi-(meta)-physeal dysplasia means the metaphyseal changes are optional, would say that is a broader synonym for both spondyloepiphyseal dysplasia and spondyloepimetaphyseal dysplasia, as it can potentially cover both of these classes

The DO xref for Spondyloepiphyseal dysplasia (MONDO_0016761) should be Spondyloepiphyseal dysplasia (DOID:0112280)
