### ISSUE TITLE
various issues with 'spondyloepiphyseal dysplasia congenita' MONDO:0008471

### ISSUE THREAD

**Issue by azankl** [monarch-initiative/mondo#5285]
**Mondo term (ID Label)**
spondyloepiphyseal dysplasia congenita MONDO:0008471

**Bug/Typo/Error description**
'spondyloepiphyseal dysplasia tarda, X-linked; SEDT' is NOT an exact synonym of MONDO:0008471
'spondyloepiphyseal dysplasia tarda, X-linked' is a separate disease: MONDO:0010737
would remove the synonym from MONDO:0008471

'late spondyloepiphyseal dysplasia' is NOT an exact synonym of MONDO:0008471 either,
its a synonym for MONDO_0019667
would remove the synonym from MONDO:0008471

'spondyloepiphyseal dysplasia congenita' is listed as an exact synonym of MONDO:0008471,
but 'spondyloepiphyseal dysplasia congenita' is already the preferred name of MONDO:0008471, so its not really a synonym
this synonym can be removed

the 'related synonyms':
- spondyloepiphyseal dysplasia, congenital type
- SED congenita
are exact synonyms of MONDO:0008471

the ICD URL: https://icd.codes/icd10cm/Q77.7 creates a '404 Not Found' error
The ICD code Q77.7 is a broadMatch for MONDO:0008471 (MONDO:0008471 is more specific than Q77.7)

I would make 'congenital spondyloepiphyseal dysplasia' a related synonym, not an exact synonym.
'congenital spondyloepiphyseal dysplasia' just means a spondyloepiphyseal dysplasia of congenital onset, while 'Spondyloepiphyseal Dysplasia Congenita' refers specifically to the COL2A1-related disorder with this name.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
0000-0001-8612-1062

**Comment by nicolevasilevsky** [comment]
thanks @azankl, I made these updates.
