### ISSUE TITLE
Rename has-modifier predicate used to link disease to temporal aspects

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#5286]
We use has_modifier a lot for linking diseases to aspects of the disease

this is mis-named, it doesn't "modify" the disease

**Comment by nicolevasilevsky** [comment]
add to Nicole/Nico 1:1 mtg

- [ ] fix the design patterns (@matentzn)
- [ ] replace 'has modifier' with 'has characteristic'
