### ISSUE TITLE
Proposal for non-human animal disease branch in Mondo

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5291]
We discussed this on the Mondo technical call:

## Summary

We decided to separate non-human animal diseases in a separate branch in Mondo (under the existing class MONDO:0005583 'non-human animal disease') and create a new grouping class 'human disease' under 'disease or disorder'. We'll import NCIT terms directly and use the existing NCIT IDs. @diatomsRcool our decision currently is to not mint new Mondo IDs for the animal terms, but the NCIT IDs should be used in annotations.

 ## Action items

- [x] create new class human disease, make disjoint with MONDO:0005583 'non-human animal disease'
- [ ] import NCIT:C22187 'Experimental Organism Diagnosis' branch under MONDO:0005583 'non-human animal disease'. **Note: if new terms are needed, requests should be made to NCIT**
- [x] need to untangle existing non-human animal diseases that are currently classified under human diseases
- [x]  Need design pattern: (something like) Any disease in taxon that minics/is analog of human disease. 
    - [ ] need new relation 'analog of' (_should this go in Mondo or be a request to RO?_)

  ````
    [disease] 
    and ('in taxon' some [NCBITaxon] 
    and ('analog of' some ['human disease']))
    ````

## Technical working group

- [ ] extend mondo release pipeline to expand the taxon constraints

related to https://github.com/monarch-initiative/mondo/issues/3855 (blocked by this ticket at the moment)

cc @diatomsRcool @cmungall @matentzn @mellybelly @pnrobinson

**Comment by nicolevasilevsky** [comment]
- [ ] add logical definitions for grouping classes using the new pattern
- [ ] run reasoner and see how it classifies the hierarchy

**Comment by matentzn** [comment]
@sabrinatoro I think you can close this issue now - it should be replaced by more fine grained issues.

**Comment by sabrinatoro** [comment]
yes, I think this issue can be closed as we now have more specific issues. Thank you for bringing my attention to it!
