### ISSUE TITLE
"not a tumor"  -- Autoimmune lymphoproliferative syndrome 

### ISSUE THREAD

**Issue by MorganSimiluk** [monarch-initiative/mondo#530]
Perhaps this is "is-a" overloading?

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0017979#
 ALPS is not a tumor, but "has a feature" that can include tumor.

**Comment by cmungall** [comment]
you're absolutely right, we'll fix this
