### ISSUE TITLE
insomnia

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#531]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0013600

insomnia should be classified as a mental disorder. 

The other parent, sleep-wake disorder is not a synonym for sleep disorder, but it is a specific kind of sleep disorder. There should be some term "sleep disorder", and sleep wake disorder should be a child of that, as should insomnia

**Comment by nicolevasilevsky** [comment]
suggested new term:
**Label:** sleep disorder
**Parent:** nervous system disorder
**Def:** Conditions characterized by disturbances of usual sleep patterns or behaviors. 
**Xref:** MESH:D012893

To do: removed related synonym, 'sleep disorder' from MONDO_0003406 'sleep-wake disorder'

**Comment by nicolevasilevsky** [comment]
@cmungall should I revise the def of sleep-wake disorder and create a new class for the NCIt term sleep disorder (NCIT_C3376)?

**Comment by nicolevasilevsky** [comment]
this is now dependent on PR https://github.com/monarch-initiative/mondo/pull/867

see related ticket https://github.com/monarch-initiative/mondo/issues/866
