### ISSUE TITLE
Mitochondrial disease naming

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5313]
@ahamosh did I capture this correct (from your comment on the P1 call):

The expert community wants to use the label: disease-related primary mitochondrial disease. Need to agree upon and define a naming convention.

**Comment by maglott** [comment]
Sorry, but what does that label mean? related to a primary mitochondrial disease? Not quite a disease but disease-related? How can something be disease-related and also a disease?  Trying to speak for others who also do not know the context of the label.

**Comment by ahamosh** [comment]
This was a debate and we can't accept it (though have not succeeded yet in persuading others).  The example fell out of Optic Atrophy 1.  Marni Falk wants to call all primary mitochondrial diseases "primary mitochondrial disease". If ever there was a need for an ontology and using it, this is it. The cannot be a disease name on the top of an ontology.

**Comment by ahamosh** [comment]
of a hierarchy tree, not an ontology.  Sorry!

**Comment by nicolevasilevsky** [comment]
Got it, thanks for clarifying @ahamosh! I'll close this ticket because there are no action items a the moment, but now we have this documented.
