### ISSUE TITLE
Add `object_label` column to mondo.sssom.tsv

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#5329]
OAK has a method to add labels to a tables on the fly. I don't know if this works for sssom files - it should.

Can we try to modify [this Make goal](https://github.com/monarch-initiative/mondo/blob/master/src/ontology/mondo.Makefile#L442)

add an `object_label` column using  OAK?

This file is my primary concern, but it should work for all sssom files:

https://github.com/monarch-initiative/mondo/blob/master/src/ontology/mappings/mondo.sssom.tsv

This file should be used as the dictionary:

https://github.com/monarch-initiative/mondo-ingest/releases/latest/download/mondo-ingest.owl

**Comment by hrshdhgd** [comment]
Documenting Solution:

```
mondo_sssom = "../ontology/tmp/mondo.sssom.tsv"
msdf_mondo = parse_sssom_table(mondo_sssom)

# Use OAK to get 'object_label'
ontology_resource = OntologyResource(slug='../ontology/tmp/merged.db', local=True)
oi = SqlImplementation(ontology_resource)

msdf_mondo.df['object_label'] = msdf_mondo.df['object_id'].apply(lambda x: oi.label(x))

```

**Comment by cmungall** [comment]
Discuss with @hrshdhgd 

- the quickest solution involves a simple curl/wget to pull the mondo-ingest.owl from the ingest repo, and make a sqlite from it
- you could use oak fill-table rather than writing new code

longer term we may wish to include labels for objects in mondo-edit, either as labels on uncommitted nodes, or as axiom annotations

**Comment by hrshdhgd** [comment]
I just tried implementing `fill-table` by the following command:

```
runoak -i tmp/mondo-ingest.db fill-table tmp/mondo.sssom.tsv
```
and it gave the following error:
```
oaklib/utilities/table_filler.py", line 126, in parse_table
    m = LIST_PATTERN.match(v)
TypeError: expected string or bytes-like object
```
My intuition says it works only on a tsv table (`msdf.df`) and not on a `msdf`. Would that be a correct conclusion?

**Comment by cmungall** [comment]
```
Options:
  --allow-missing / --no-allow-missing
                                  Allow some dependent values to be blank,
                                  post-processing  [default: no-allow-missing]
```

**Comment by cmungall** [comment]
of course you should follow up and ask why UMLS:C0444868 is not in the ingest.db. We expect a few to be missing due to general asynchrony of releases and so forth but the majority should be findable

**Comment by hrshdhgd** [comment]
About 134,393 `object_id`s have no `object_label`s

About 34,156 `object_id`s have `object_label`s

**Comment by matentzn** [comment]
This all sounds correct. Mondo ingest only contains a fraction of the source ontologies. In particular not UMLS. Having oak wrap translators node normalizer or some such to get labels for all ids in the world would be great, but for now, this what you have here is ok!

**Comment by hrshdhgd** [comment]
Added issue https://github.com/INCATools/ontology-access-kit/issues/313
