### ISSUE TITLE
Policy:  consider representing explicit abbreviation/full name relationships for terms

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#534]
If an abbreviation is specific to a term, retain that relationship  rather than lumping all the abbreviations 

e.g. 
ARTHROGRYPOSIS MULTIPLEX CONGENITA, DISTAL, TYPE I has an abbreviation AMCD1
https://omim.org/entry/108120

**Comment by nicolevasilevsky** [comment]
@maglott - I fixed this instance you mentioned above.

@matentzn I know we've talked about this but don't remember the answer - is there a way to go through and split out all the OMIM synonyms that are followed by an abbrevation?

Thanks!

**Comment by matentzn** [comment]
Yes! This will be fixed when I start working on the OMIM ingest again!

**Comment by nicolevasilevsky** [comment]
Ok great, I am going to close this ticket.
