### ISSUE TITLE
These terms used to be "DNA repair disorders" 

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#5347]
The following terms used to be DNA repair disorders, but they are no longer , I'm not sure why. They are all caused by defects in DNA repair.

1. ataxia, early-onset, with oculomotor apraxia and hypoalbuminemia (MONDO:0008842)

https://pubmed.ncbi.nlm.nih.gov/20687492/#:~:text=EAOH%2FAOA1%20is%20characterized%20by,horn%20and%20dorsal%20root%20ganglia.

2. Nijmegen breakage syndrome-like disorder (MONDO:0013118)
https://pubmed.ncbi.nlm.nih.gov/23684796/
https://pubmed.ncbi.nlm.nih.gov/19409520/

3. ataxia-telangiectasia-like disorder 2 (MONDO:0014399)
https://pubmed.ncbi.nlm.nih.gov/16961074/
https://pubmed.ncbi.nlm.nih.gov/33718381/

Bloom syndrome (& Werner)
https://rarediseases.org/rare-diseases/bloom-syndrome/
"he genetic abnormality in Bloom syndrome causes problems with DNA repair, resulting in a high number of chromosome breaks and rearrangements"

4. spinocerebellar ataxia, autosomal recessive, with axonal neuropathy
https://pubmed.ncbi.nlm.nih.gov/31723605/

**Comment by nicolevasilevsky** [comment]
@ValWood is your suggestion to directly assert these as children of [DNA repair disease](http://purl.obolibrary.org/obo/MONDO_0021190)?

thanks!

**Comment by ValWood** [comment]
Yes, they no longer have this parent (although. they used to)?

**Comment by nicolevasilevsky** [comment]
I added them! :) I plan to run the release tomorrow.
