### ISSUE TITLE
MONDO:0019443 and DTGA sub-types[Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5348]
**Mondo term (ID and Label)**
MONDO:0019443 dextro-looped transposition of the great arteries
MONDO:0013463  dextro-looped transposition of the great arteries 3

**Suggested revision and reasons**
- [x] MONDO:0013463  dextro-looped transposition of the great arteries 3: OMIM 613854 has been renamed:
CONGENITAL HEART DEFECTS, MULTIPLE TYPES, 6; CHTD6 Suggest this should not be a child of MONDO:0019443; Current correct parent appears to be MONDO:0000119 congenital heart defects, multiple types.

- [x] And OMIM 608808 is now called:  TRANSPOSITION OF THE GREAT ARTERIES, DEXTRO-LOOPED; DTGA
(No longer preferentially designated as "1" subtype)  and the MIM record now reports 'association' with MED13L, but they are pending confirmation. I don't know if it would make sense to merge MONDO:0012128 with the parent (MONDO:0019443), since there are OrphaNet sourced children of the DTGA concept. This probably needs to be reviewed more closely but all in all, this Mondo term may need to be renamed.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems I'm not sure if we want to merge the terms at this time, I did relabel the terms to match OMIM.
