### ISSUE TITLE
psychosocial short stature

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#535]
This should not be classified as a developmental disorder, even though logically it is that to a certain extent. There should be some subhierarchy of child abuse/neglect-related diseases. I did not see any of these terms at first glance

Here is a review article
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4288037/

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/130
