### ISSUE TITLE
Update the exclusion code of obsoleted terms in Mondo

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#5357]
related to #5271
We need to update incorrect exclusion codes that are sources of the obsolescence reason of Mondo obsoleted terms.

To Do: (as per discussion with Nico)

- [ ] remove the existing obsolescence reasons + source/exclusion codes
ROBOT template (remove): https://docs.google.com/spreadsheets/d/e/2PACX-1vQ8cszVqBNOeClD6uFif3QRHn0Ud_Cyt_gylyTTFJ-RoJaOwNWS7Qv3c516bJoTBaKT1WLagSQ7CQqS/pub?gid=0&single=true&output=tsv
- [ ] add the new obsolescence reasons + source/exclusion codes
ROBOT template (add): https://docs.google.com/spreadsheets/d/e/2PACX-1vQ8cszVqBNOeClD6uFif3QRHn0Ud_Cyt_gylyTTFJ-RoJaOwNWS7Qv3c516bJoTBaKT1WLagSQ7CQqS/pub?gid=365804501&single=true&output=tsv

The main spreadsheet is [here](https://docs.google.com/spreadsheets/d/1-AfFDxCqs9YemdPZW5vDCTMHsovdNEgRYA5MYEJ_CW4/edit#gid=0)

Note: We need to be aware of the "SPLIT=|", especially when removing the existing annotations

**Comment by sabrinatoro** [comment]
@matentzn we can work on this during our 1:1

**Comment by matentzn** [comment]
Ok!
