### ISSUE TITLE
[Merge]'histidine metabolism disease'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5364]
**Mondo term (ID and Label)**
[histidine metabolism disease](http://purl.obolibrary.org/obo/MONDO_0004738)

**Reason for deprecation**
These terms are duplicates

**Term to be merged with**
[disorder of histidine metabolism](http://purl.obolibrary.org/obo/MONDO_0019228)

related to #4985

**Comment by sabrinatoro** [comment]
@nicolevasilevsky is this already done? I am not finding a term called "disorder of histidine metabolism"

**Comment by nicolevasilevsky** [comment]
it is MONDO:0019228

The terms are hyperlinked to OLS (I used the 'Copy as Markdown' function in Protege. I'm not sure why it has the wrong label!)

**Comment by sabrinatoro** [comment]
Thank you! Adding it to the list.
