### ISSUE TITLE
[NTR] Adhesive capsulitis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5366]
**Preferred term label:**
Adhesive capsulitis

**Synonyms**
frozen shoulder (Layperson)

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Adhesive capsulitis is a painful inflammatory process leads to a mechanical block in active and passive range of motion (ROM) of the shoulder. Adhesive capsulitis of the shoulder is characterized by functional loss of passive and active shoulder motion. This inflammatory process results in fibroblastic proliferation and extensive scar tissue formation. Fibroblastic proliferation, a late phase of the inflammatory process involved in tissue repair, leads to thickening, fibrosis, and adhesion of the capsule to itself and the humerus.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@pnrobinson we already have this term: [frozen shoulder](http://purl.obolibrary.org/obo/MONDO_0006763)

I added a synonym and updated the definition.

Thanks!
