### ISSUE TITLE
glycogen storage disease was renamed

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#5376]
glycogen storage disease 	

was renamed to  "disorder of glycogen metabolism"

 but these diseases are called "glycogen storage diseases"   

disorder of glycogen metabolism seems a bit less specific. There could potentially  be diseases of glycogen metabolism that are  not storage diseases.

I could not find a ticket providing the rationale for the change.

**Comment by nicolevasilevsky** [comment]
Hi @ValWood we are revising this hierarchy to match the expert-recommended classification outlined in this paper (https://onlinelibrary.wiley.com/doi/abs/10.1002/jimd.12348), see related ticket:
https://github.com/monarch-initiative/mondo/issues/4985

The ticket is linked on these terms, can you see that?

glycogen metabolism disorder is an exact synonym, so I thought it was okay to rename this term to glycogen storage disease. Do you think these should be separate classes?

Thanks!

**Comment by ValWood** [comment]
I think this one is OK.
