### ISSUE TITLE
MONDO:0800153 | urea cycle disorder or inherited hyperammonemia 

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#5378]
MONDO:0800153 | urea cycle disorder or inherited hyperammonemia | A disorder of amino acid metabolism that has its basis  in the disruption of the urea cycle and/or there is an inherited  increased concentration of ammonia in the blood.

This seems a strange grouping term.

MONDO:0800153 | urea cycle disorder
is a collection of  specific diseases

Is  inherited hyperammonemia  a specific disease?
 inherited hyperammonemia  sound like a phenotype "increased concentration of ammonia in the blood."

What was the rationale for the grouping?
Which disease genes (other than urea cycle disorder ) cause inherited hyperammonemia

**Comment by nicolevasilevsky** [comment]
Hi @ValWood we are revising this hierarchy to match the expert-recommended classification outlined in this paper (https://onlinelibrary.wiley.com/doi/abs/10.1002/jimd.12348), see related ticket:
https://github.com/monarch-initiative/mondo/issues/4985

**Comment by nicolevasilevsky** [comment]
the authors listed the genes in the table in their paper

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/6722114/189739498-7e552a25-f009-45ec-b5e7-68a38fbf2d4f.png">

**Comment by nicolevasilevsky** [comment]
does this answer your question?

**Comment by ValWood** [comment]
Yes!

In this case, should the def be

MONDO:0800153 | urea cycle disorder or inherited hyperammonemia |
 A disorder of amino acid metabolism that has its basis in the disruption of the urea cycle a OR [an inherited hyperammonemia, any specific disease which causes an inherited increased concentration of ammonia in the blood].

To make it clearer that this is a disease classification, not a disease plus a phenotype (it's actually diseases identified by phenotype, which is fine as long as they are defined as diseases)

**Comment by nicolevasilevsky** [comment]
thanks @ValWood, I updated the definition.
