### ISSUE TITLE
mondo-with-equivalents.json file not present in 9-06 release

### ISSUE THREAD

**Issue by plweller3** [monarch-initiative/mondo#5379]
**Mondo term (ID Label)**

**Bug/Typo/Error description**
The mondo-with-equivelents.json file is missing.  All the links on the various pages, including the monarch pages and readme in this github, all reference it, and when selected, all return with an error.  As this file is widely used for data input, please clarify if this  is something that will be corrected soon, or if this file being removed.  If the latter, can you at least provide it for the 9-06 release so we can have a little time to prepare an altternative?  Thanks!

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Hi @plweller3 I'll look into this and get back to you asap. Thanks for reporting this issue.

**Comment by nicolevasilevsky** [comment]
Hi @plweller3 - some release files were not uploaded correctly and this is now fixed. My apologies for any inconvenience and thanks for reporting this and bringing it to our attention.

**Comment by plweller3** [comment]
Thank you!
