### ISSUE TITLE
Mondo constraint checking (GCIs, Modifiers) not working

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#5384]
In mondo-edit:

GCIs:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/7070631/189892082-30ef9712-86f8-4129-b4ce-1b7fdd535c3e.png">

Example def:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/7070631/189892431-b6bb4492-ae2b-44d2-9a5e-16464a648968.png">

Constraint checking cant happen if relation is different.

- [x] Update all GCIs in Mondo (basically all uses of the "has modifier" relationship) to use characteristic of
- [x] Check why the relation is called "bearer of" rather than "characteristic of" (probably some outdated import)

**Comment by nicolevasilevsky** [comment]
yes it is called bearer of due to the imports:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/6722114/190223160-a409e3b5-1120-4e88-88d1-d96b4a8bdaad.png">

- ecto
- envo
- maxo
- foodon
- pato
