### ISSUE TITLE
Edit to US Rare Disease Definition

### ISSUE THREAD

**Issue by achenNCATS** [monarch-initiative/mondo#540]
For this [term's definition](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0021136), I would edit the US wording. They do not technically have to be **Americans**. According to the [Rare Diseases Act of 2002](https://history.nih.gov/research/downloads/pl107-280.pdf), the definition is "any disease or condition that affects less than 200,000 **persons** in the United States."

**Comment by cmungall** [comment]
agreed.

This will become a bit moot after we implement #254 and all "rare X" terms become obsolete, and we stop baking rare classification into the ontology. However, if it's useful to continue housing the "rare" modifier and a consensus definition we're happy to do this

**Comment by achenNCATS** [comment]
Sounds good. I will leave it up to the experts to decide on the implementation of [#254](https://github.com/monarch-initiative/mondo/issues/254). Thanks!
