### ISSUE TITLE
Typo in gene description text

### ISSUE THREAD

**Issue by PabloBotas** [monarch-initiative/mondo#5401]
**Mondo term (ID Label)**
https://monarchinitiative.org/gene/HGNC:2151

**Bug/Typo/Error description**
The is a simple typo repeating "cause of" in the description of the gene. Specifically in this line: Defects in this gene are a cause of cause of retinitis pigmentosa type 45.

Not sure if this is on your responsibility or you are taking this from somebody else.

**Your nano-attribution (ORCID)**
https://orcid.org/my-orcid?orcid=0000-0001-7090-9648

**Comment by nicolevasilevsky** [comment]
Hi @PabloBotas I shared this with the Monarch team, this is an issue in Monarch, not the Mondo disease ontology. Thanks for reporting this and someone will address it. I will close here, thanks!

cc @putmantime @monicacecilia @sagehrke

**Comment by PabloBotas** [comment]
Ok, good to know! Where should these things be reported?
