### ISSUE TITLE
Relabel MONDO:0011291 with name ALG6-CDG1C

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#5402]
**Mondo term (ID and Label):**
MONDO:0011291 
Congenital disorder of glycosylation type 1C 

**Suggested new label:**
ALG6-CDG1C

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
ID/Autism GCEP https://clinicalgenome.org/affiliation/40006/

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Requesting name change to be consistent with the way other CDGs are now labeled in MONDO. For example, MONDO: 0100068 and MONDO:0300000. The previous name can be kept as a synonym. 

CC: @erinriggs

**Comment by ErinRiggs** [comment]
Hi @nicolevasilevsky - per our email conversation, let's change this rename request to "ALG6-congenital disorder of glycosylation."

cc: @icordovaG

**Comment by icordovaG** [comment]
Additional ID needing review: 0100068
