### ISSUE TITLE
Action item: Create list of GitHub tags for dissemination to the wider ontological groups

### ISSUE THREAD

**Issue by courtneythaxton** [monarch-initiative/mondo#541]
As a follow up from the MonDO workshop, create a list of the GitHub handles for each of the major contributors and send out an email, so that all are aware of the handles and being able to add them to tickets where needed. 

thanks,
@courtneythaxton

**Comment by courtneythaxton** [comment]
I see th eAssignee list, but maybe even categorizing which individuals belong to which entity, i.e. courtneythaxton is ClinGen, ahamosh is OMIM, etc


Or if the large entities can create generic handles, like Orphanet, OMIM, ClinGen, etc and have those handles go back to the person in charge of this effort, if possible, but recognizing this might not be effectual or possible.

**Comment by nicolevasilevsky** [comment]
I can create a list with everyone's name, GitHub handle and affiliation - where should I share this though? (I don't think we want to make it public, do we? But if that was okay, we could add it to this repo somewhere)

**Comment by courtneythaxton** [comment]
I would suggest to send it out to the names on the MonDO workshop email list, as this would be the individuals that participated in this workshop.

**Comment by nicolevasilevsky** [comment]
I will do that!

**Comment by nicolevasilevsky** [comment]
I sent this list out via email to the list
