### ISSUE TITLE
Synonyms not returned in OLS search API

### ISSUE THREAD

**Issue by marius-mather** [monarch-initiative/mondo#5416]
I'm attempting to use Mondo via the OLS API, particularly the search endpoint as I'd like to get good results if users enter synonyms for terms, as well as showing the user those synonyms. 

Using the search endpoint currently, it doesn't seem to be possible to get synonyms returned in the search results, even when specifiying it in the fieldList , e.g. https://www.ebi.ac.uk/ols/api/search?q=gallbladder%20disorder&queryFields=label,synonym,annotations&fieldList=id,iri,label,synonym,annotations&ontology=mondo

Instead, I have to then grab each individual term from a different endpoint, and find the synonyms in term -> annotation -> has_exact_synonym

Is it possible to configure the synonym field in the ontology metadata so that synonyms work correctly? I'm trying to understand the different configurations/processes involved. It looks like synonyms work in some OLS search results because the `synonym_property` has been set, e.g. EFO has a [config file](https://github.com/EBISPOT/efo/blob/master/ols/ols-config.yaml) with:

```yaml
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
```

I haven't been able to work out whether adding this field to the [metadata](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/mondo.md) on OBOFoundry will work - or whether additional configuration is needed.

Any thoughts on whether this can be achieved?

**Comment by nicolevasilevsky** [comment]
Hi @marius-mather sorry for the long delay. I this still an issue?

**Comment by marius-mather** [comment]
Hi @nicolevasilevsky - I think I eventually figured out that I could get the synonyms from the API using `has_exact_synonym_annotation` in the `fieldList` when searching - so synonyms are available from the OLS API, just not in an obvious place. But maybe this just needs documenting rather than a change to the OLS config?

**Comment by nicolevasilevsky** [comment]
Sure, we can document this!

We have this documentation:
https://mondo.readthedocs.io/en/latest/editors-guide/f-entities/#synonyms

Would you know to look here? It's linked from our website too (https://mondo.monarchinitiative.org/pages/editors/)

On the readthedocs site, there is a section called Users Corner - I should make that more prominent on the website.

Any other advice about improving our documentation is welcomed!

**Comment by nicolevasilevsky** [comment]
I updated our website, closing
