### ISSUE TITLE
corneal disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#542]
update: to do: ask again in Slack after the holidays. _updated 12/22/21_

---
update: the Uberon dependency was fixed, but now it is dependent on the Uberon release. Note to self to check back on this in the future.

There was an Uberon release in mid-November but this was not fixed. I sent this message in Slack:
per Uberon ticket [#1779](https://github.com/obophenotype/uberon/issues/1779), I removed the superclass assertion of surface structure from cornea in Uberon (which is needed for Mondo # 542. However, I still see this superclass assertion in uberon.owl. and in the uberon-edit.obo file, this superclass is still there, coming from the NBO and PATO imports. Not sure how this should be addressed, any help is appreciated, thanks!

_Updated 2021-11-16 NV_

----

corneal disease is mistakenly listed as a child of integumentary system disease

**Comment by nicolevasilevsky** [comment]
![image](https://user-images.githubusercontent.com/6722114/106823515-f08cef00-6635-11eb-940d-17bcb9e4402e.png)

this comes from Uberon. @pnrobinson do you want to submit a ticket to Uberon?

**Comment by pnrobinson** [comment]
@nicolevasilevsky @cmungall @matentzn  Am I correct to assume that the problem in UBERON is that surface structure is a subclass of integumental system, but actually it should be the other way around?

**Comment by nicolevasilevsky** [comment]
Yes, I believe that is the case, surface structure is a subclass of integumental system in Uberon. I'm not sure what the correct classification is though.

**Comment by cmungall** [comment]
Oh dear this is a terrible uberon error

Let's just get rid of surface structure,  it is a silly grouping

**Comment by nicolevasilevsky** [comment]
Thanks @dosumis for creating the ticket in Uberon :)
