### ISSUE TITLE
[NTR] Body-stalk anomaly

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5422]
**Preferred term label:**
Body-stalk anomaly

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Body stalk anomaly (BSA) is a very rare anomaly (1 in 14,000 to 42,000 pregnancies; 1 in 7500 fetuses from 10 to 14 weeks of gestation) characterized by a complex anomaly of the anterior abdominal wall, severe kyphoscoliosis, rudimentary umbilical cord, and anatomical defects of the pelvis and lower limbs.
PMID:33115503

https://jmedicalcasereports.biomedcentral.com/articles/10.1186/s13256-020-02509-3

Synonyms: body stalk anomaly (BSA), limb body wall complex (LBWC), or body stalk complex

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

diaphragmatic or abdominal wall malformation -- HOWEVER, it does not make sense to have an "OR" term here, we should split diaphragmatic malformation and abdominal wall malformation

There's a related orphanet term 2369

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@pnrobinson Limb body wall complex is the label for MONDO:0016528 [limb body wall complex](http://purl.obolibrary.org/obo/MONDO_0016528) (equivalent to Orphanet:2369).

You said above these terms are related but not the same.

Should limb body wall complex be a related synonym for body-stalk anomaly?
