### ISSUE TITLE
Relabel Request for MONDO:0018760 "WAC-related facial dysmorphism-developmental delay-behavioral abnormalities syndrome"

### ISSUE THREAD

**Issue by ARosselClinGen** [monarch-initiative/mondo#5424]
**Mondo term (ID and Label):**
WAC-related facial dysmorphism-developmental delay-behavioral abnormalities syndrome (MONDO:0018760)

**Suggested new label:**
DeSanto-Shinawi syndrome (MONDO:0018760)

**Your nano-attribution (ORCID)**
This relabel is requested by the ClinGen ID/Autism GCEP: https://clinicalgenome.org/affiliation/40006/

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
In the literature, this syndrome is referred to as DeSanto-Shinawi syndrome. Additionally, patient support networks (https://www.dessh.org/) use the term DeSanto-Shinawi syndrome and have expressed concern about the negative connotation of the word "wack," which sounds the same as the current MonDO term.
Additionally, the phrase "developmental delay" is not appropriate for individuals over the age of six. There are currently adults with intellectual disability who have DeSanto-Shinawi syndrome (PMID:25356899).
DeSanto-Shinawi syndrome is also caused by 10p11.21p12.31 microdeletions (PMID:35266333, PMID:22258158, PMID:18080323) and describing the disease using the gene name does not adequately capture these individuals. 

Preferred synonyms include: "DESSH syndrome" and the original term "WAC-related facial dysmorphism-developmental delay-behavioral abnormalities syndrome"

Child terms should be "facial dysmorphism-developmental delay-behavioral abnormalities syndrome due to WAC point mutation" (MONDO:0014741) and “facial dysmorphism-developmental delay-behavioral abnormalities syndrome due to 10p11.21p12.31 microdeletion” (MONDO:0017283).

We will be requesting a relabel term for MONDO:0014741 and MONDO:0017283 as well.

CC: @ErinRiggs

**Comment by nicolevasilevsky** [comment]
@ARosselClinGen DeSanto-Shinawi syndrome is the preferred name in OMIM for [facial dysmorphism-developmental delay-behavioral abnormalities syndrome due to WAC point mutation](http://purl.obolibrary.org/obo/MONDO_0014741)

is is appropriate to rename this term instead of [WAC-related facial dysmorphism-developmental delay-behavioral abnormalities syndrome](http://purl.obolibrary.org/obo/MONDO_0018760)?

**Comment by nicolevasilevsky** [comment]
I looked at the other tickets and now I better understand the request. I believe this is what you asked for:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/6722114/193954075-4214db36-6941-4496-b166-845d9fc520f6.png">

I updated the synonyms accordingly.
