### ISSUE TITLE
Relabel MONDO:0017283 "facial dysmorphism-developmental delay-behavioral abnormalities syndrome due to 10p11.21p12.31 microdeletion"

### ISSUE THREAD

**Issue by ARosselClinGen** [monarch-initiative/mondo#5427]
**Mondo term (ID and Label):**
facial dysmorphism-developmental delay-behavioral abnormalities syndrome due to 10p11.21p12.31 microdeletion (MONDO:0017283)

**Suggested new label:**
DeSanto-Shinawi Syndrome due to 10p11.21p12.31 microdeletions (MONDO:0017283)

**Your nano-attribution (ORCID)**
This relabel is requested by the ClinGen ID/Autism GCEP: https://clinicalgenome.org/affiliation/40006/

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
In the literature, this syndrome is referred to as DeSanto-Shinawi syndrome. Additionally, patient support networks (https://www.dessh.org/) use the term DeSanto-Shinawi syndrome and have expressed concern about the negative connotation of the word "wack," which sounds the same as the current MonDO term.
Additionally, the phrase "developmental delay" is not appropriate for individuals over the age of six. There are currently adults with intellectual disability who have DeSanto-Shinawi syndrome (PMID:25356899).
DeSanto-Shinawi syndrome is also caused by 10p11.21p12.31 microdeletions (PMID:35266333, PMID:22258158, PMID:18080323). Patients with microdeletions have similar phenotypes to those with point mutations, although experts in the ID/Autism GCEP have noted that these patients' presentations may be more severe. 

Preferred synonyms include: "DESSH syndrome due to 10p11.21p12.3 microdeletions" and the original term "facial dysmorphism-developmental delay-behavioral abnormalities syndrome due to 10p11.21p12.31 microdeletion"

CC: @ErinRiggs

**Comment by nicolevasilevsky** [comment]
Thanks @ARosselClinGen - we will work on this asap. :)
