### ISSUE TITLE
Moyamoya and down syndrome

### ISSUE THREAD

**Issue by vanessaboulanger** [monarch-initiative/mondo#544]
Down syndrome entry refers to moyamoya but the moyamoya entry doesn't refer to an association with down syndrome: 

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0016820

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0008608

**Comment by annieolry** [comment]
Down syndrome appears in a group entitled "Moyamoya syndrome". This is coming from Orphanet, however the prefered label is currently different in Orphanet: "Rare disorder with a moyamoya angiopathy".
Down syndrome has been classified as such following this publication: PMID: 25733922

**Comment by nicolevasilevsky** [comment]
@vanessaboulanger My apologies for the super long delay. I think this has been resolved, but please reopen if this is not the case.
Thanks for reporting this ticket to Mondo.
