### ISSUE TITLE
add qc check for two replaced by annotations

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5440]
I accidentally added two replaced by annotations and the QC check did not fail. Could we add a check for this?

<img width="546" alt="image" src="https://user-images.githubusercontent.com/6722114/193427400-f33a756c-beba-405e-b87f-4d01678a9188.png">

**Comment by matentzn** [comment]
Ok I designed the check:

https://github.com/INCATools/ontology-development-kit/issues/703

Can you add it to Mondo? if there are now instructions on how to add a check anywhere in the docs lemme know, I will write a few bullets.

**Comment by nicolevasilevsky** [comment]
Thanks Nico, will do 😄

**Comment by nicolevasilevsky** [comment]
I don't think we have proper instructions on how add a check to Mondo in the docs, but I would just save a text file with this content in it in the folder: mondo/src/sparql/qc/mondo, right?

I'll also update this page:
https://mondo.readthedocs.io/en/latest/editors-guide/quality-control-tests/

**Comment by matentzn** [comment]
I think they also need to be named in some way, i.e. starting with `qc-` and ending with `.sparql` :) But yes, that is it!
