### ISSUE TITLE
Mondo version on EBI?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5461]
**Mondo term (ID Label)**
(all Mondo on https://www.ebi.ac.uk/ols/ontologies/mondo )

**Bug/Typo/Error description**
I know it sometimes takes a few days for EBI to update to the current Mondo release, but am I going nuts or is it really still showing the August 2022 release on EBI?  
![image](https://user-images.githubusercontent.com/71083858/194386770-42d88b50-f417-4275-8cad-9bdc13a9c91f.png)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
There was a problem with some of the release files in the last release (sept) and maybe OLS did not pick up the Sept release?

I just did the Oct release on Monday, so I think it should be available in OLS any day now. I'll keep this ticket open and check back tomorrow.

**Comment by nicolevasilevsky** [comment]
@kanems please see: https://github.com/EBISPOT/OLS/issues/642

**Comment by kanems** [comment]
OLS is now updated, and it looks like they grabbed the release from the 11th, too. I'm all set
