### ISSUE TITLE
cardiogenic shock

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5462]
**cardiogenic shock*

**cardiac shock**
ORPHA:97292
MedDRA: 10007625
ICD-10: R57.0

**Decreased cardiac output and evidence of tissue hypoxia in the presence of adequate intravascular volume.**

**shock**

**cardiogenic shock, hypovolemic shock, septic shock, anaphylactic shock (listed as Mondo synonym of anaphylaxis but not synonymous)

**ORCID: 0000-0001-7151-1615

**Comment by nicolevasilevsky** [comment]
Lewis wrote in an email: I would keep it as a heart disorder for now as that is the primary cause for the shock, but it could have 2 parents: heart AND vascular. There really probably should be a “shock” parent under “vascular” with cardiogenic, anaphylactic, hypovolemic, and neurogenic as the children.

TO DO :arrow_up:

**Comment by nicolevasilevsky** [comment]
I believe the request is:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/6722114/204414083-8c6d7394-92c1-46e4-a69b-54c065c628d2.png">

yellow= new term request to Mondo
red outline = term exists in HPO

these shock terms exist in NCIT and SNOMED. I'm uncertain if these are proper diseases though or phenotypes?

**Comment by nicolevasilevsky** [comment]
@OOPD-LJF we will close this ticket, as cardiogenic shock is considered a phenotype. Please let us know if you have any objections, thanks!

**Comment by OOPD-LJF** [comment]
No objections. Agree with that assessment. Thanks @nicolevasilevsky
