### ISSUE TITLE
infectious disease ?= peach allergy

### ISSUE THREAD

**Issue by MorganSimiluk** [monarch-initiative/mondo#547]
Peach allergy is an infectious disease?  Is there a citation for this?

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0000785

**Comment by balhoff** [comment]
## [peach allergy](http://purl.obolibrary.org/obo/MONDO_0000785) SubClassOf [infectious disease](http://purl.obolibrary.org/obo/MONDO_0005550) ##

  - [peach allergy](http://purl.obolibrary.org/obo/MONDO_0000785) EquivalentTo [allergic disease](http://purl.obolibrary.org/obo/MONDO_0005271) and ([realized in response to stimulus](http://purl.obolibrary.org/obo/RO_0004028) some [Prunus persica](http://purl.obolibrary.org/obo/NCBITaxon_3760))
    - [Prunus persica](http://purl.obolibrary.org/obo/NCBITaxon_3760) SubClassOf [Prunus](http://purl.obolibrary.org/obo/NCBITaxon_3754)
      - [Prunus](http://purl.obolibrary.org/obo/NCBITaxon_3754) SubClassOf [Amygdaleae](http://purl.obolibrary.org/obo/NCBITaxon_721805)
        - [Amygdaleae](http://purl.obolibrary.org/obo/NCBITaxon_721805) SubClassOf [Maloideae](http://purl.obolibrary.org/obo/NCBITaxon_171637)
          - [Maloideae](http://purl.obolibrary.org/obo/NCBITaxon_171637) SubClassOf [Rosaceae](http://purl.obolibrary.org/obo/NCBITaxon_3745)
            - [Rosaceae](http://purl.obolibrary.org/obo/NCBITaxon_3745) SubClassOf [Rosales](http://purl.obolibrary.org/obo/NCBITaxon_3744)
              - [Rosales](http://purl.obolibrary.org/obo/NCBITaxon_3744) SubClassOf [fabids](http://purl.obolibrary.org/obo/NCBITaxon_91835)
                - [fabids](http://purl.obolibrary.org/obo/NCBITaxon_91835) SubClassOf [rosids](http://purl.obolibrary.org/obo/NCBITaxon_71275)
                  - [rosids](http://purl.obolibrary.org/obo/NCBITaxon_71275) SubClassOf [Pentapetalae](http://purl.obolibrary.org/obo/NCBITaxon_1437201)
                    - [Pentapetalae](http://purl.obolibrary.org/obo/NCBITaxon_1437201) SubClassOf [Gunneridae](http://purl.obolibrary.org/obo/NCBITaxon_91827)
                      - [Gunneridae](http://purl.obolibrary.org/obo/NCBITaxon_91827) SubClassOf [eudicotyledons](http://purl.obolibrary.org/obo/NCBITaxon_71240)
                        - [eudicotyledons](http://purl.obolibrary.org/obo/NCBITaxon_71240) SubClassOf [Mesangiospermae](http://purl.obolibrary.org/obo/NCBITaxon_1437183)
                          - [Mesangiospermae](http://purl.obolibrary.org/obo/NCBITaxon_1437183) SubClassOf [Magnoliophyta](http://purl.obolibrary.org/obo/NCBITaxon_3398)
                            - [Magnoliophyta](http://purl.obolibrary.org/obo/NCBITaxon_3398) SubClassOf [Spermatophyta](http://purl.obolibrary.org/obo/NCBITaxon_58024)
                              - [Spermatophyta](http://purl.obolibrary.org/obo/NCBITaxon_58024) SubClassOf [Euphyllophyta](http://purl.obolibrary.org/obo/NCBITaxon_78536)
                                - [Euphyllophyta](http://purl.obolibrary.org/obo/NCBITaxon_78536) SubClassOf [Tracheophyta](http://purl.obolibrary.org/obo/NCBITaxon_58023)
                                  - [Tracheophyta](http://purl.obolibrary.org/obo/NCBITaxon_58023) SubClassOf [Embryophyta](http://purl.obolibrary.org/obo/NCBITaxon_3193)
                                    - [Embryophyta](http://purl.obolibrary.org/obo/NCBITaxon_3193) SubClassOf [Streptophytina](http://purl.obolibrary.org/obo/NCBITaxon_131221)
                                      - [Streptophytina](http://purl.obolibrary.org/obo/NCBITaxon_131221) SubClassOf [Streptophyta](http://purl.obolibrary.org/obo/NCBITaxon_35493)
                                        - [Streptophyta](http://purl.obolibrary.org/obo/NCBITaxon_35493) SubClassOf [Viridiplantae](http://purl.obolibrary.org/obo/NCBITaxon_33090)
                                          - [Viridiplantae](http://purl.obolibrary.org/obo/NCBITaxon_33090) SubClassOf [Eukaryota](http://purl.obolibrary.org/obo/NCBITaxon_2759)
                                            - [Eukaryota](http://purl.obolibrary.org/obo/NCBITaxon_2759) SubClassOf [cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567)
                                              - [cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567) SubClassOf [root](http://purl.obolibrary.org/obo/NCBITaxon_1)
    - [allergic disease](http://purl.obolibrary.org/obo/MONDO_0005271) EquivalentTo [disease or disorder](http://purl.obolibrary.org/obo/MONDO_0000001) and ([disease has basis in disruption of](http://purl.obolibrary.org/obo/RO_0004021) some [type I hypersensitivity](http://purl.obolibrary.org/obo/GO_0016068))
  - [infectious disease](http://purl.obolibrary.org/obo/MONDO_0005550) EquivalentTo [disease or disorder](http://purl.obolibrary.org/obo/MONDO_0000001) and ([realized in response to stimulus](http://purl.obolibrary.org/obo/RO_0004028) some [root](http://purl.obolibrary.org/obo/NCBITaxon_1))

**Comment by balhoff** [comment]
Problem with definition of infectious disease?

**Comment by cbizon** [comment]
I notice that this is true for many (all?) specific allergies like "TImothy Hay Allergy" and "Atlantic Cod Allergy" too

**Comment by cmungall** [comment]
Apologies that this has been sitting here for so long unaddressed! @balhoff is correct, it's a high level axiomatization issue. Easily fixed, I will do it.

was experimenting with disjointness between allergic and infectious but there are a few exceptions that are valid, e.g. allergic aspergillosis

![image](https://user-images.githubusercontent.com/50745/54092086-5a26f480-435e-11e9-993c-1eef69d20c5c.png)
