### ISSUE TITLE
thyroid eye disease

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5472]
**Preferred term label: thyroid eye disease**

**Synonyms: TED; Graves’ eye disease; Graves’ ophthalmopathy; Graves’ orbitopathy; thyroid-associated ophthalmopathy**

**Definition: progressive inflammation and damage to tissues around the eyes, especially extraocular muscle, connective, and fatty tissue occurring in patients with hyperthyroidism or a history of hyperthyroidism due to Graves’ disease (PMID:20181974)**

**Parent term: disorder of visual system AND autoimmune disease**

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term? N/A

**Your nano-attribution (ORCID): 0000-0001-7151-1615**

**Note: There is an entry for "Euthyroid Graves orbitopathy" but the more common presentation is with hyperthyroidism.**

**Comment by nicolevasilevsky** [comment]
This is equivalent to:
[endocrine exophthalmos](http://purl.obolibrary.org/obo/MONDO_0001509)

I'll add these as synonyms.
