### ISSUE TITLE
myocardial disorder

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#548]
This term is mistakenly classified as a musculoskeletal system disease

**Comment by cmungall** [comment]
I have seen some sources include all muscle tissue types under musculoskeletal system, including cardiac. Others restrict to skeletal muscles + skeleton; this latter makes sense to me, see https://github.com/obophenotype/uberon/issues/77 - do we have a definitive reference for this?

**Comment by nicolevasilevsky** [comment]
this would need to be changed in Uberon. Do we want to do that, or can this be closed?

**Comment by pnrobinson** [comment]
In general usage, the heart muscle is not considered part of the musculoskeletal system. Most clinicians would think it a mistake if heart wasa put under musculoskeletal system.

**Comment by nicolevasilevsky** [comment]
I'll have to ask @cmungall for guidance what to do here. And I'll add it to our workshop board.

**Comment by nicolevasilevsky** [comment]
this was addressed in Uberon, we need to wait for the Uberon release.

**Comment by nicolevasilevsky** [comment]
In Uberon, myocardium is part of some 'musculature of body', that is where this inference is coming from. I don't think this is incorrect?

![image](https://user-images.githubusercontent.com/6722114/150450997-3bf57659-7b4c-4d15-8b2b-7412caa5c989.png)

**Comment by pnrobinson** [comment]
It would probably be better to keep the three types of muscle separate (cardiac, smooth, and skeletal), and have a term such as 'skeletal musculature of body'. As mentioned above, this is an odd association that does not correspond to conventional ways of classification.

**Comment by nicolevasilevsky** [comment]
@pnrobinson if we change myocardium in Uberon to have the superclass: part of some 'cardiac muscle tissue', then we'd get the inference in Mondo that myocardial disorder is an inferred subclass of 'muscle tissue disease'.
Does that work?

The text def of myocardial disorder is:
A disorder that affects the muscle tissue of the heart. Representative examples include myocardial infarction, myocarditis, and cardiomyopathy.

**Comment by pnrobinson** [comment]
As mentioned, this is not the way a typical clinical would classify things. I think we need to do some work in Mondo. Could we discuss this at the next meeting with Chris & team?

**Comment by nicolevasilevsky** [comment]
Yes, I'll add to the Mondo curation agenda.

**Comment by nicolevasilevsky** [comment]
action item:
remove superclassOf assertion on myocardium in uberon
'part of' some 'musculature of body'

**Comment by nicolevasilevsky** [comment]
This has been resolved with the new Uberon import.
