### ISSUE TITLE
Addressing the has_modifier relation

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/mondo#5481]
**Suggested revision and reasons**
On a recent Monarch Data call (18-Aug), the subject of addressing the `has_modifier` relation in Mondo was brought up again. @cmungall mentioned it in the context of ensuring all predicates map to something in BioLink.
Are there any updates to this? 
Any specific actions you think we should be taking, Chris? 
FYI: @sierra-moxon 👀 ⬆️ 
(originally submitted [here](https://github.com/monarch-initiative/mondo/issues/2133#issuecomment-1265808151))

**Your nano-attribution (ORCID)**
0000-0001-8430-6039

**Comment by monicacecilia** [comment]
Response from @sierra-moxon: 
I believe our discussion around that term was in the context of how to represent inheritance (coming from HP) on disease nodes in the monarch graph (we weren't sure how to attribute a property on a node in the graph, independently from the attribution of the edge between nodes).  I believe we settled on representing "inheritance" as a `biolink:genetic inheritance` category(node, class) instead of as a property (slot) on the disease node itself.  

There are also terms in MONDO that are annotated with inheritance, using a "has_modifier" property, I believe.  I think the idea here was to use a more specific property than `has_modifier` for this.  But I am not sure of the relation of that discussion to this ticket, specifically. :) 

(Originally submitted [here](https://github.com/monarch-initiative/mondo/issues/2133#issuecomment-1266024340))

**Comment by monicacecilia** [comment]
Response from @nicolevasilevsky: 
@sierra-moxon we recently change the relation between a disease and inheritance to 'has bearer' instead of 'has modifier', just FYI. :)

(Originally submitted [here](https://github.com/monarch-initiative/mondo/issues/2133#issuecomment-1266127547))

**Comment by monicacecilia** [comment]
Dear @sierra-moxon, @matentzn: 
Does the update to `has_bearer` in any way require updates on the BioLink end? 
And is the new relation a sufficiently specific property?

If this is n longer an issue, then we can close. 

Thanks!

**Comment by matentzn** [comment]
@nicolevasilevsky this is a @cmungall question do Friday.

**Comment by nicolevasilevsky** [comment]
I already added it to the agenda :)

**Comment by nicolevasilevsky** [comment]
@monicacecilia @sierra-moxon please see our design patterns for mode of inheritance in Mondo:
https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/autosomal_dominant.yaml
https://github.com/monarch-initiative/mondo/blob/master/src/patterns/dosdp-patterns/autosomal_recessive.yaml

We can invite Kevin and Sierra to a future call to discuss further.

I'll close this, please reopen if there are other action items.
