### ISSUE TITLE
rheumatologic disorder

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#549]
rheumatologic disorder is currently classified as a musculoskeletal disease, but I think it should be its own primary disease class, since many of the rheumatologic diseases such as lupus have many non-musculoskeletal manifestations.

**Comment by cmungall** [comment]
fixed in source

is classification under connective tissue disease ok? I would like to revise the whole connective tissue disease classification to be more precise

ncit also classifies as immune system disease, but I think this is not true of all?

**Comment by pnrobinson** [comment]
In Harrisons, this is probably "Disorders of immune mediated injury", which is under "Disorders of the joints and adjacent tissues". 
You might be thinking of Collagen disease, which is an older term (https://en.wikipedia.org/wiki/Collagen_disease), but connective tissue disease is ambiguous, since it can also be taken to mean hereditary diseases of connective tissue, which are completely different. 
"Autoimmune Disorders of Connective Tissue" might be a decent category, but it is unclear if if should be a parent or (probably) a synonym.
I think this probably needs F2F TLC... :-0
