### ISSUE TITLE
neoplastic meningitis

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5495]
**Preferred term label: neoplastic meningitis**

**Synonyms: carcinomatous meningitis, leptomeningeal carcinoma, leptomeningeal carcinomatosis, leptomeningeal metastasis, meningeal carcinomatosis, meningeal metastasis**

**Definition: spread of tumor cells to leptomeninges (pia and arachnoid) and subarachnoid space, and their dissemination through the cerebrospinal fluid (CSF); The most common primary tumors metastasizing to the leptomeninges are breast and lung carcinomas, melanoma, aggressive non-Hodgkin lymphoma, and acute lymphocytic leukemia. PMID: 29535794**

**Parent term: cancer or benign tumor AND nervous system disorder (under non-infectious meningitis)**

**Children terms: N/A**

**Your nano-attribution (ORCID): 0000-0001-7151-1615**

**Comment by nicolevasilevsky** [comment]
hi @OOPD-LJF 
The label seems like it matches MONDO:0021322 [malignant tumor of meninges](http://purl.obolibrary.org/obo/MONDO_0021322).

But the synonym seem like they could each be more specific new terms. For example, meningeal metastasis, seems like it may be different term? Could be a child of MONDO:0024883 [metastatic neoplasm](http://purl.obolibrary.org/obo/MONDO_0024883)?

**Comment by OOPD-LJF** [comment]
Thanks Nicole. Malignant tumor of meninges is a primary tumor like a meningioma, but neoplastic meningitis is a metastatic occurrence, with cancer cells seeding the meninges and CSF from other primary tumors or hematologic cancers like leukemia. I saw that entry, but I believe they are different entities. I think the synonyms do not need to be their own new terms. I do think it should be a child of MONDO:0024883 [metastatic neoplasm](http://purl.obolibrary.org/obo/MONDO_0024883).

**Comment by nicolevasilevsky** [comment]
Talked to Ada, need to confer with an expert
