### ISSUE TITLE
hyphema

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5497]
**Preferred term label: hyphema**

**Synonyms: N/A**

**Definition: the accumulation of red blood cells (RBCs) in the anterior chamber of the eye; the most common cause is blunt trauma, though spontaneous hyphemas can occur in the setting of sickle cell disease or other increased bleeding states (PMID:29939579)**

**Parent term: disorder of visual system --> eye disorder**

**Children terms: N/A**

**Your nano-attribution (ORCID): 0000-0001-7151-1615**

**Comment by sabrinatoro** [comment]
'hyphema' appears to be a phenotype.
@OOPD-LJF, would you agree?

**Comment by OOPD-LJF** [comment]
Agree

**Comment by sabrinatoro** [comment]
Thank you! Closing this issue.
