### ISSUE TITLE
malignant pleural effusion

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5498]
**Preferred term label: malignant pleural effusion**

**Synonyms: N/A**

**Definition: infiltration of cancer cells into pleural tissue; MPEs commonly complicate patients with lung cancer and malignant mesothelioma but can also complicate metastatic cancers (from lung or distant sites), lymphoma, and other hematologic malignancies. (PMID: 25610100)**

**Parent term: cancer or benign tumor --> cancer-related condition AND respiratory system disorder**

**Children terms: N/A**

**Your nano-attribution (ORCID): 0000-0001-7151-1615**

**Comment by sabrinatoro** [comment]
NCIT:C9432 refers to 'Malignant Pleural Effusion' as a "Finding": 
Definition:  A collection of fluid in the pleural cavity resulting from malignant disease. Malignant pleural effusions often contain free-floating malignant cells.

The suggested definition refers to "infiltration of cancer cells into pleural tissue"

It looks like this term is more of a phenotype than a disease. 
@OOPD-LJF, would you agree?

**Comment by OOPD-LJF** [comment]
Agree this is more of a phenotype. Thanks.

**Comment by sabrinatoro** [comment]
Thank you! Closing this issue.
