### ISSUE TITLE
Hauptmann-Thannhauser and EDMD

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#55]
https://www.ncbi.nlm.nih.gov/pubmed/12376891 *Hauptmann-Thannhauser muscular dystrophy and differential diagnosis of myopathies associated with contractures*

"Hauptmann-Thannhauser muscular dystrophy is due to mutations in the **LMNA** gene...**Autosomal-dominant** Hauptmann-Thannhauser muscular dystrophy and **X-chromosomal Emery-Dreifuss muscular dystrophy** are not clearly distinguishable by phenotypic criteria."

Note: paper is in German... @pnrobinson 

OMIM bundles HT into EDMD2: https://omim.org/entry/181350?search=Hauptmann-Thannhauser&highlight=hauptmann%20thannhauser%20hauptmannthannhauser

Note the medgen entry for this appears to be confused unless I am mistaken, it mixes X-linked and AD forms:
https://www.ncbi.nlm.nih.gov/medgen/?term=C0410190

EDMD1 (X) EMD  UMLS:C0751337 https://omim.org/entry/310300
EDMD2 (AD) LMNA  UMLS:C0410190  https://omim.org/entry/181350
EDMD3 (AR) LMNA  UMLS:C2750035 https://omim.org/entry/616516

Should we have separate entry for HT or bundle with EDMD2 as OMIM has done?

**Comment by cmungall** [comment]
__UPDATE__ I think the confusion in the medgen annotation may be due to our annotation! see linked ticket

**Comment by cmungall** [comment]
I have add HT in the edit version but we may decide to merge

**Comment by nicolevasilevsky** [comment]
Consider obsoleting MONDO_0021570 'Hauptmann-Thannhauser muscular dystrophy'
merge with
MONDO_0021569 'Emery-Dreifuss muscular dystrophy 2, autosomal dominant'
