### ISSUE TITLE
arthritis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#550]
arthritis is currently classified as a rheumatological disorder, but not all of the subclasses of arthritis are rheumatologic. This needs to be restructured.

**Comment by nicolevasilevsky** [comment]
@pnrobinson The superclass of 'rheumatologic disorder' comes from EFO. Would it be sufficient to exclude this superclass?

**Comment by pnrobinson** [comment]
I think that for instance rheumatoid arthritis is a valid subclass of arthritis but not vice versa so I would remove the EFO superclass.

Also, I think that ``Arthritis`` is the proper label for the phenotypic feature. The label for the grouping term in MONDO should probably be ``Arthritic joint disease`` with arthritis as a synonym.
