### ISSUE TITLE
MONDO:0017454 triphalangeal thumb-polysyndactyly syndrome

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5501]
**Mondo term (ID and Label):**
MONDO:0017454 triphalangeal thumb-polysyndactyly syndrome

**Xref that should be fixed (ID and label):**
Add? OMIM 190605 https://www.omim.org/entry/190605 
What is Mondo doing with OrphaNet:2950? https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=2950 "This entity has been excluded from the Orphanet nomenclature of rare diseases and moved to [Tibial hemimelia-polysyndactyly-triphalangeal thumb syndrome](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=988)"

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
I am struggling to differentiate between the diseases on https://omim.org/entry/174500 and https://www.omim.org/entry/190605   Clearly these are highly similar phenotypes, linked to the same underlying molecular cause, so probably a fuzzy spectrum but OMIM has determined they are different enough to warrant splitting to two records. (Also,  OMIM 's alt name on 174500 conflicts with 190605 al name, so MedGen will have to figure out which record gets that name...  right now it's on the term with the Mondo ID and obsolete OrphaID, but should either of these MIM#s map to this Mondo record??)

**Comment by sabrinatoro** [comment]
Based on my analysis, this is what should be done:
**1) MONDO:0017454-’triphalangeal thumb-polysyndactyly syndrome'**
_(currently Orphanet:2950, but this orphanet was replaced by orphanet:988)_
to do:
[ ] make Orphanet:2950 : MONDO:equivalentOBSOLETE
       - Based on the definition, the orphanet replacement is not appropriate (it is more specific) to be equivalent to this MONDO term. 
       - In orphanet, Orphanet:2950 is mapped to OMIM:174500, but it does not look appropriate based on the definition 
[ ] OMIM:190605 should be added as an Equivalent

**2) MONDO:0008572, MONDO:0020306, MONDO:0018052 should be merged**
- Based on the orphanet definition, MONDO:0008572 and MONDO:0020306 refer to the same disease. 
- Based on orphanet record replacement, MONDO:0018052 should be merged to MONDO:0020306
![Mondo 5501](https://user-images.githubusercontent.com/12737987/200638775-c98e1d53-ee9d-4fca-a1c0-695fd2840078.jpg)
x-ref to review:
- Orphanet:3332 (= OMIM:188740) → was replaced with ORPHA:988 → should be MONDO:equivalentObsolete
- MESH:C566046 should be “preferred”  
- UMLS:CN204341 → should be MONDO:equivalentObsolete

**3) OMIM:174500 vs OMIM:190605**
- note that OMIM:174500 has RIPHALANGEAL THUMB, INCLUDED; TPT, INCLUDED
- these 2 terms do share some synonyms. It is unclear what the difference between these 2 terms is. 
To do: ask @ahamosh

**Comment by nicolevasilevsky** [comment]
sounds like a good plan!

**Comment by sabrinatoro** [comment]
OMIM:174500 and OMIM:190605 are 2 different entries in omim:
a variation in the enhancer leads to a change in the shh pathway in the hand development. The outcome is due to "chance", but the outcome is different, and therefore 2 different entries were created

**Comment by sabrinatoro** [comment]
I think this issue is done and can be closed
