### ISSUE TITLE
Sensorineural hearing loss

### ISSUE THREAD

**Issue by heidirehm** [monarch-initiative/mondo#551]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005365
 
In the OLS link above, there is no entry for sensorineural hearing loss but its in the MONDO-Edit file

Also the term "deafness" is used interchangeably throughout many of the entries under "hearing loss" but deafness is only profound hearing loss and does not encompass milder forms of hearing loss. So ideally the term "deafness" should be replaced with hearing loss as many of the forms of syndromic and nonsyndromic hearing loss do not have deafness, but milder hearing loss. This fix is also needed in OMIM and I've discussed with Ada

**Comment by cmungall** [comment]
We can do a mass replace, keeping deafness as synonym (narrow, not exact?). We did a similar thing with MR->ID

**Comment by heidirehm** [comment]
Chris,

 

I went through the ontology under hearing loss to decide if you should do a full search and replace for all uses. I think that’s probably not quite what we want because there are some syndromes where the formal name includes deafness and we don’t want to change that either because patients are in fact deaf in that particular syndrome and/or because the name is historical (e.g. KID syndrome which is keratitis-ichthyosis-deafness syndrome). I started going through all of the syndromes under “syndromic genetic deafness” and began listing ones you shouldn’t change but it’s a lot of work to copy and paste and my conclusion is that you should not change any of these syndrome names. So you’d change everything in the tree pictured below including all branches but not the one branch I highlighted in blue. For that you’d change “syndromic genetic deafness” to “syndrome genetic hearing loss” but then not touch the items under syndromic genetic deafness.

I did give some thought to the terminal branches under nonsyndromic hearing loss as these could be considered named diseases such as “autosomal dominant nonsyndromic deafness 1” in OMIM. However, these are not the names used by the genetic hearing loss community as can be seen on the website maintained by the hearing loss community here: https://hereditaryhearingloss.org/ so I think its fine to change these nonsyndromic names to be consistent with what the community actually uses despite the OMIM entries. The original issue probably arose because the loci were labeled “DFN” but the whole field now calls all of these loci “nonsyndromic hearing loss” loci despite the DFN locus symbols.

 

Let me know if this plan makes sense.

 

Thanks, Heidi

 



 

syndromic genetic deafness

Charcot-Marie-tooth disease-deafness-intellectual disability syndrome

Hirschsprung disease-deafness-polydactyly syndrome

autosomal dominant keratitis-ichthyosis-deafness syndrome

ichthyosiform erythroderma, corneal involvement, and deafness

ichthyosis, hystrix-like, with deafness

retinitis pigmentosa-deafness syndrome

ocular albinism with congenital sensorineural deafness

albinism-deafness syndrome

more but I got tired of cutting and pasting!!!!

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] change everything in the tree pictured above including all branches but not the one branch I highlighted in blue. For that you’d change “syndromic genetic deafness” to “syndrome genetic hearing loss” but then not touch the items under syndromic genetic deafness.
- [ ] for terms under nonsyndromic hearing loss: review the names used by the genetic hearing loss community as can be seen on the website maintained by the hearing loss community here: https://hereditaryhearingloss.org/ 
- [ ] change these nonsyndromic names to be consistent with what the community actually uses despite the OMIM entries.

**Comment by nicolevasilevsky** [comment]
partial list from above:
- [ ] syndromic genetic deafness
- [ ] Charcot-Marie-tooth disease-deafness-intellectual disability syndrome
- [ ] Hirschsprung disease-deafness-polydactyly syndrome
- [ ] autosomal dominant keratitis-ichthyosis-deafness syndrome
- [ ] ichthyosiform erythroderma, corneal involvement, and deafness
- [ ] ichthyosis, hystrix-like, with deafness
- [ ] retinitis pigmentosa-deafness syndrome
- [ ] ocular albinism with congenital sensorineural deafness

albinism-deafness syndrome

**Comment by nicolevasilevsky** [comment]
to do:
all the children of 'nonsyndromic genetic hearing loss' should be renamed to 'hearing loss' instead of deafness. I will ask Nico to help me with this.
