### ISSUE TITLE
Request to not obsolete “syndromic constitutional thrombocytopenia” (MONDO:0018795)

### ISSUE THREAD

**Issue by justyneross** [monarch-initiative/mondo#5518]
The ClinGen Hemostasis/Thrombosis GCEP would like to maintain the “syndromic constitutional thrombocytopenia” (MONDO:0018795) term. It is currently used for one curation (with the gene RAP1B). We feel this is an appropriate term for this emerging disease entity, the evidence is too limited at this time to create a disease entity term specific to the RAP1B related syndromic thrombocytopenia. However, the parent term of inherited thrombocytopenia (MONDO:0100241), suggested as the alternative term to consider, is too broad and does not acknowledge the syndromic nature of the disease, which includes congenital brain malformations and dysmorphic features. Therefore we would like to maintain the “syndromic constitutional thrombocytopenia” (MONDO:0018795).

nano-attribution (ORCID) https://orcid.org/0000-0002-7437-8060

**Comment by justyneross** [comment]
We have received notification that this term is again on the obsoletion list to take place on September 1st, 2023. Please confirm this will not be obsoleted.

**Comment by nicolevasilevsky** [comment]
Apologies! We are doing a review of existing terms and considering obsoleting certain terms and this slipped onto our list but we will ensure it is not obsoleted.
