### ISSUE TITLE
OMIM 613735 mapping

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5521]
**Mondo term (ID and Label):**

MONDO:0013396   chromosome 1p32-p31 deletion syndrome

**Xref that should be fixed (ID and label):**

https://omim.org/entry/613735
OMIM's preferred name for this is on MONDO:0100478 (brain malformations with or without urinary tract defects) 

the "included' OMIM concept is CHROMOSOME 1p32-p31 DELETION SYNDROME

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
Thanks @kanems 

I changed the annotation to OMIM on MONDO:0013396 chromosome 1p32-p31 deletion syndrome, we are now using MONDO:includedEntryInOMIM on 'included' entries.

I added OMIM:613735 as an exact xref on [brain malformations with or without urinary tract defects](http://purl.obolibrary.org/obo/MONDO_0100478), this term was previously requested by ClinGen.
