### ISSUE TITLE
Request to rename and split "Parkinsonism-dystonia, infantile, 1"

### ISSUE THREAD

**Issue by lindsworls** [monarch-initiative/mondo#5523]
Hello,

My name is Lindsay and I am a member of the ClinGen General Inborn Errors of Metabolism Gene Curation Expert Panel. Recently, I curated the gene-disease relationship between SLC6A3 and Parkinsonism-Dystonia, Infantile, 1. Throughout this project, I noticed that this disease does not always present in infancy. In the more recent literature on this condition, some authors are suggesting the presentation of this disease is more of a spectrum, with onset ranging from infancy to adulthood ([GeneReviews](https://www.ncbi.nlm.nih.gov/books/NBK442323/), [Case](https://pubmed.ncbi.nlm.nih.gov/24613933/)). As a GCEP, we have approved the name "SLC6A3-Related Dopamine Transporter Deficiency Syndrome." Would it be possible to create this term in place of "Parkinsonism-Dystonia, Infantile, 1?"

Furthermore, I would also like to discuss the possibility of adding 2 child terms for SLC6A3-related DTDS. As seen in GeneReviews, the group experts and I liked the idea of adding "Classic Dopamine Transporter Deficiency Syndrome" and "Atypical Dopamine Transporter Deficiency Syndrome" to the database. This would allow us to take the old name, "Parkinsonism-Dystonia, Infantile, 1" and make it a synonym to "Classical Dopamine Transporter Deficiency Syndrome" instead of disposing of it completely.  

I have attached an example summary statement for each proposed term. Thank you for considering our suggestions, and I look forward to discussing this further. 

Best,
Lindsay

[SLC6A3-related DTDS MONDO.docx](https://github.com/monarch-initiative/mondo/files/9842712/SLC6A3-related.DTDS.MONDO.docx)

**Comment by nicolevasilevsky** [comment]
@sabrinatoro please go ahead with whatever you think is the best approach

**Comment by lindsworls** [comment]
Hi Sabrina and Nicole,

Thank you so much for following up on my request. I agree that "Classical Dopamine Transporter Deficiency Syndrome" with the x-ref of OMIM:613135 sounds good. 

I was also wondering, would it be possible to add "SLC6A3-related Dopamine Transporter Deficiency Syndrome" as a parent term for the renamed entry? My thought process is that it would be nice to have a term which encompasses all cases of DTDS, and "Classical DTDS" only includes infantile cases. My group would greatly appreciate this new term because we have curated and approved a definitive gene-disease relationship between SLC6A3 and DTDS in probands with a spectrum of onset (ranging from infants to adults). Would adding this parent term allow the current annotation (MONDO:0054835) to stay in tact?

Thank you so much again for your time and consideration with regards to my request. 

Best,
Lindsay

**Comment by sabrinatoro** [comment]
![Mondo #5523](https://user-images.githubusercontent.com/12737987/204119514-de557733-81da-4988-9188-109bf45944c0.jpg)

!! need to review synonyms and x-ref for MONDO:0013150 - 'parkinsonism-dystonia, infantile'
