### ISSUE TITLE
transplantation-related disease

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5525]
**Preferred term label:** transplantation-related disease

**Synonyms:** post-transplant complications; post-transplantation disease

**Definition:** complications (organ-specific and/or systemic) arising in preparation of, or in response to, transplantation of solid organs or hematopoietic stem cells

**Parent term:** **_NEW_** parent request: transplantation-related disease

**Children terms (**_existing_**):** posttransplant acute limbic encephalitis; post-transplant lymphoproliferative disease; engraftment syndrome; (**_NEW as higher level branches_**): solid organ transplant-related disease; hematopoietic stem cell transplant (HSCT)-related disease; (**_NEW as lower level leaves_**): delayed graft function of solid organ transplant; solid organ transplant rejection; solid organ transplant ischemia/reperfusion injury; hematopoietic stem cell transplant graft failure; hematopoietic stem cell transplant conditioning

**Your nano-attribution (ORCID):** 0000-0001-7151-1615

Wanted to start the conversation on this topic/issue - please let me know if you have questions, concerns, suggestions.

**Comment by OOPD-LJF** [comment]
I was thinking we should also add existing children terms of graft versus host disease (#0013730), acute graft versus host disease (#0020546), and chronic graft versus host disease (#0020547) to "transplant-related disease" as well. We could probably put it under "hematopoietic stem cell transplant (HSCT)-related disease" but there are reports of solid organ-related GVHD too.

**Comment by nicolevasilevsky** [comment]
complication after organ transplantation is an ORDO term that will be added in the ORDO slurp

**Comment by sabrinatoro** [comment]
## Proposed classification:
**transplantation-related disease (NEW)**
**-- post-transplantation related disease (???)**  
    ---- posttransplant acute limbic encephalitis (MONDO:0015595)
    ---- post-transplant lymphoproliferative disease (MONDO:0019088)
    ---- delayed graft function of solid organ transplant (NEW)
    ---- solid organ transplant rejection (NEW)
    ---- solid organ transplant ischemia/reperfusion injury (NEW)
    ---- hematopoietic stem cell transplant graft failure (NEW)
    ---- hematopoietic stem cell transplant conditioning (NEW)
    ---- engraftment syndrome	MONDO:0043358
    ---- graft versus host disease	MONDO:0013730
         ------- acute graft versus host disease	MONDO:0020546
         ------- chronic graft versus host disease	MONDO:0020547
 **-- disease related to preparation for transplantation (???)**  _- maybe not needed_  
    ---- hematopoietic stem cell transplant conditioning  (NEW)

**-- solid organ transplant-related disease (NEW)**  
    ---- delayed graft function of solid organ transplant (NEW)
    ---- solid organ transplant rejection (NEW)
    ---- solid organ transplant ischemia/reperfusion injury (NEW)
    
**-- hematopoietic stem cell transplant (HSCT)-related disease (NEW)**  
    ---- hematopoietic stem cell transplant graft failure (NEW)
    ---- hematopoietic stem cell transplant conditioning (NEW)
    ---- engraftment syndrome	MONDO:0043358
    ---- graft versus host disease	MONDO:0013730  
          ------- acute graft versus host disease	MONDO:0020546
          ------- chronic graft versus host disease	MONDO:0020547


## Note to self: 
- might want to make a relation to a MAxO term
- need to create a dos-dp for these terms.

**Comment by sabrinatoro** [comment]
@OOPD-LJF , I have a lot of questions (or points to be clarified): 
**1- parent term: transplantation-related disease**
- The suggested synonyms (ie “post-transplantation disease”) are not quite correct since this term definition includes “preparation of” or “in response to” transplantation
- Mondo is an ontology for disease or disorder. Therefore I would update the definition to : “disease or disorder arising in preparation of or in response to transplantation of solid organs or hematopoietic stem cells”
Do you agree with this definition? 

**2- Additional classification**
Should we create a grouping term for “post-translation related disease” and “disease related to preparation for transplantation”? Is there more than one term for “disease related to preparation for transplantation”? 

**3- “solid organ transplant-related disease”**
We should refer to an UBERON term for ‘solid organ’ (either in Mondo or via MAxO). 
What is a “solid organ”? Transplantation terms in MAxO refer to “organ transplantation” with “organ = UBERON:0000062”. (see image below). Is a “bone marrow” a “solid organ”? If not, maybe a term referring to “compound organ” (http://purl.obolibrary.org/obo/UBERON_0003103) would be better?
![Screenshot 2022-12-20 at 4 39 47 PM](https://user-images.githubusercontent.com/12737987/208793676-5c840b5d-23d2-4fac-abd8-9911fdfb0ca5.png)

  
**4- definitions**
We need definitions for all the new terms. We also need to make sure that terms added into Mondo should refer to disease/disorder. Therefore, we need to be clear about the definition of the following terms, and make sure they refer to disease/disorder:
- hematopoietic stem cell transplant conditioning
- hematopoietic stem cell transplant graft failure
- delayed graft function of solid organ transplant
- solid organ transplant rejection
- solid organ transplant ischemia/reperfusion injury

**Comment by OOPD-LJF** [comment]
@sabrinatoro thanks for getting to these requests and excellent questions. Here are my responses:
1) See the response to #2 below – I no longer think that there is a distinct disease related to the conditioning process, so I may stay with a synonym of "post-transplantation disease" and go with this as our definition: “complications (organ-specific and/or systemic) arising in response to transplantation of solid organs or hematopoietic stem cells”

2) As much as I’d like “disease related to preparation for transplantation” to be included in Mondo (because there are quite a few orphan drug designations related to this), after some thought, I’m not sure it’s really a distinct disease. It’s more like the requests we discussed regarding procedural designations – I don’t think there’s a disease or disorder related to the conditioning process. I really may keep the grouping as “post-transplantation disease” or “transplantation-related disease”

3) Bone marrow is not a solid organ – bone marrow transplant is synonymous with hematopoietic stem cell transplant. “Solid organ” would refer to essentially everything else on that list. I don’t think “compound organ” would necessarily be wrong and the definition “ Anatomical structure that has as its parts two or more multi-tissue structures of at least two different types and which through specific morphogenetic processes forms a single distinct structural unit demarcated by bona fide boundaries from other distinct anatomical structures of different types” seems appropriate (although some of the subgroups of compound organ do not apply, like “caudal-fin organ” and “future tongue”)

4) Definitions (these are mine, but I would want input from specialists/experts):
•	hematopoietic stem cell transplant conditioning - REMOVE
•	hematopoietic stem cell transplant graft failure - lack of initial engraftment of transplanted cells (primary graft failure) or loss of transplanted cells after initial engraftment (secondary graft failure)
•	delayed graft function of solid organ transplant - failure of a solid organ transplant to function immediately
•	solid organ transplant rejection - when transplanted tissue is rejected by the recipient's immune system, which destroys the transplanted tissue. Transplant rejection can be lessened by determining the molecular similitude between donor and recipient and by use of immunosuppressant drugs after transplant. Can occur within minutes to months after transplantation.
•	solid organ transplant ischemia/reperfusion injury - the paradoxical exacerbation of cellular dysfunction and death, following restoration of blood flow to previously ischemic tissues

Hope this helps. Please let me know if you have questions. Have a good holiday!
Lewis

**Comment by sabrinatoro** [comment]
I have reviewed this issue. There is a lot to discuss, please share your thoughts here. 

1) I think we could create the following new term (please review the definition)
New term: **disease related to transplantation**
xref: SNOMED:429054002; UMLS:C1998172
Definition: Disease that occurs as a consequence of immunosuppression in a recipient of a solid organ or bone marrow allograft, or as a consequence of the transplantation. 

Questions: 
1.1. is the definition correct? 
1.2. do we need to create terms for "disease related to solid organ transplantation" and "disease related to hematopoietic stem cell transplant"? [note, we should create these terms if we want to use them for annotations, I don't think we need to create them just for classification purposes]


2) I am struggling with the following term as they don't seem to refer to a disease, but to "something that happens to the transplant" or "complications" (which is not diseases per se), at least based on the suggested definitions. 
- hematopoietic stem cell transplant graft failure 
- delayed graft function of solid organ transplant
- solid organ transplant rejection
- solid organ transplant ischemia/reperfusion injury

If these should be considered as diseases, we should make sure that the definitions reflect this (e.g. disease that develop as a consequence of organ rejection).
A potential argument to do so is the following terms in SNOMED:
- Disorder affecting transplanted structure (disorder) (SNOMED:429490004, UMLS:C1997168)
-- Transplanted organ failure (disorder) (SNOMED:269295009, UMLS:C0345469)
-- Transplanted organ rejection (disorder) (SNOMED:213148006, UMLS:C0345468)

However, other terms are clearly not considered disease/disorder in other sources, eg: Graft Rejection = Failure of transplanted tissue to become functional or operational, often as a result of destruction by the host's immune system. (UMLS:C0018129, NCIT:C75570) 

Questions: 
2.1 Should the 4 terms mentioned above be in Mondo? If so, we need definitions to clearly refer to a disease

@OOPD-LJF @nicolevasilevsky

**Comment by OOPD-LJF** [comment]
Thanks @sabrinatoro. I will try to answer your questions, but honestly, I am not an expert in this area and this issue should probably be posed to transplant experts.
1.1. One issue with this definition is with the word "allograft". Some bone marrow transplants will be "autografts" (cells from the patient). I may just say, "Disease that occurs as a consequence of immunosuppression in a recipient of a solid organ or bone marrow **transplant**, or as a consequence of the transplantation."
1.2. Again, I'm not sure of the process on your end, but I would think from a hierarchy perspective, it would make sense to have separate terms for "disease related to solid organ transplantation" and "disease related to hematopoietic stem cell transplant" - I don't know the difference between annotation and classification, so I defer on this decision to you and your team.
2. I think I agree with the idea that these are less specific diagnoses and more complications of transplantation and could all fall under "disease related to transplantation" (or the more specific "disease related to solid organ transplantation" and "disease related to hematopoietic stem cell transplant" if you add them). Maybe those specific complications could be included in the definitions for "disease related to solid organ transplantation" and "disease related to hematopoietic stem cell transplant"? For example: "_Complications of solid organ transplantation include delayed graft function, rejection, and ischemia/reperfusion injury_" Is that acceptable?

Again, I defer to experts in the field to decide whether each of those specific complications/diagnoses are distinct diseases or would just be considered complications of the transplantation (and if they think they are distinct, I would ask for their definitions). As long as there is a Mondo entry for "disease related to transplantation" and possibly diseases related to the specific types of transplantation (i.e., solid organ and HSCT), I don't know if those other terms need their own entries in Mondo. Thanks - appreciate your consideration.

**Comment by sabrinatoro** [comment]
Thank you @OOPD-LJF . 
I added : 
- MONDO:0700220 - disease related to transplantation
- MONDO:0700221 - disease related to solid organ transplantation  (with a comment about possible complications)
- MONDO:0700222 - disease related to hematopoietic stem cell transplant
