### ISSUE TITLE
poisonings

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5528]
Multiple (12) recommendations for additions to poisonings in attached spreadsheet. Please let me know if you have questions

[POISONINGS.Github_MONDO.Recommendations.xlsx](https://github.com/monarch-initiative/mondo/files/9862763/POISONINGS.Github_MONDO.Recommendations.xlsx)

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/3809

**Comment by nicolevasilevsky** [comment]
@OOPD-LJF, I am working on these. I may have some additional questions.

my first question:
radioactive material contamination does not sound like a disease. Do you mean radiation poisoning? Would this be the same as [radiation injury](http://purl.obolibrary.org/obo/MONDO_0043458) (defined as: Harmful effects of non-experimental exposure to ionizing or non-ionizing radiation in vertebrates.)

**Comment by nicolevasilevsky** [comment]
instead of the label `chemotherapy-induced complications`, could we use `chemotherapy-induced toxicity`?

**Comment by OOPD-LJF** [comment]
i think "chemotherapy-induced toxicity" would work well.

**Comment by nicolevasilevsky** [comment]
Note to self, this is a [ROBOT template](https://docs.google.com/spreadsheets/d/12zfxOUBr6l8rFkfVEm3J1tnoRHZz00aop6XoH3YE55k/edit#gid=0) to add these terms

**Comment by nicolevasilevsky** [comment]
Great! I'll remove 'radioactive material contamination' from the list.

**Comment by nicolevasilevsky** [comment]
@OOPD-LJF - this fell to the bottom of my to do list, but I am revisiting it now. There are three terms left that have not been added:

- local anesthetic systemic toxicity
- nerve agent exposure
- fire ant sensitivity

I'll work on these with @sabrinatoro.

**Comment by nicolevasilevsky** [comment]
@OOPD-LJF I added these as:
MONDO:0100331 nerve agent poisoning
MONDO:0100335 local anaesthetic poisoning
MONDO:0100341 fire ant poisoning

**Comment by OOPD-LJF** [comment]
Thanks @nicolevasilevsky and team.

**Comment by nicolevasilevsky** [comment]
Thank you for your patience and contributions! :)
