### ISSUE TITLE
pulmonary hypertension, neonatal, susceptibility to

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5530]
**Mondo term (ID and Label):** pulmonary hypertension, neonatal, susceptibility to [MONDO: 0014151]

**Suggested new label:** pulmonary hypertension, neonatal OR persistent pulmonary hypertension in the newborn

**Your nano-attribution (ORCID):** 0000-0001-7151-1615
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.):**
 Shouldn't be "susceptibility to" - just the disease/condition;
Definition: PPHN is characterized by elevated pulmonary vascular resistance, resulting in right-to-left shunting of blood and hypoxemia. (See: Lakshminrusimha S & Keszler M. Persistent Pulmonary Hypertension of the Newborn. Neoreviews (2015) 16 (12): e680–e692.)

**Comment by nicolevasilevsky** [comment]
@OOPD-LJF this term is equivalent an OMIM term that is the disease susceptibility, not the proper disease: https://omim.org/entry/615371

I can create a new class that is the proper disease:
label:
pulmonary hypertension, neonatal

synonym:
persistent pulmonary hypertension in the newborn

**Comment by nicolevasilevsky** [comment]
note to self, equiv to NCIT:C4732
