### ISSUE TITLE
hand-foot syndrome

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5531]
**Preferred term label: hand-foot syndrome**

**Synonyms: palmar-plantar erythrodysesthesia**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######): a side effect of some chemotherapy drugs that can cause redness, swelling and blistering on the palms of the hands and soles of the feet.**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): skin disorder**

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID): 0000-0001-7151-1615**

**Comment by sabrinatoro** [comment]
x-refs: 
NCIT:C27177
UMLS:C0549410
MESH:D060831

synonym: 
Palmar-Plantar Erythrodysthesia (NCIT:C27177)

definition: 
A condition characterized by redness, pain, swelling, and tingling in the palms of the hands or the soles of the feet. It may appear as a side effect to chemotherapy agents.
NCIT:C27177
