### ISSUE TITLE
intrauterine fetal demise

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5532]
**Mondo term (ID and Label):** 
pregnancy disorder with abortive outcome (ID # 0041526)

**Synonym to be added:** 
intrauterine fetal demise (IUFD); intrauterine fetal death; stillbirth

**Synonym subtype: ie, broad/exact/narrow/related:** 
exact

**Database cross reference for the synonym:** Such as PubMed ID (in the format PMID:XXXXXX) or a cross-reference to another ontology, like OMIM or Orphanet.

 32491465

**Your nano-attribution (ORCID):** 

0000-0001-7151-1615

**Comment by sabrinatoro** [comment]
@cmungall @hrshdhgd 
I think you could use this issue for your demo ontobot.

**Comment by nicolevasilevsky** [comment]
related to: https://github.com/monarch-initiative/mondo/issues/6254
