### ISSUE TITLE
obstetric/neonatal diseases

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5533]
Multiple (7) recommendations for additions to obstetric/perinatal diseases in attached spreadsheet. Please let me know if you have questions.
[OB_NEONATAL.Github_MONDO.Recommendations.xlsx](https://github.com/monarch-initiative/mondo/files/9871356/OB_NEONATAL.Github_MONDO.Recommendations.xlsx)

**Comment by sabrinatoro** [comment]
I think that the majority of the requested terms should be phenotypes (and most of them are already HP terms), and not diseases (ie they might not belong in Mondo). 
@pnrobinson could you please take a look and share your thoughts? Thank you! 
copy of the list is here: https://docs.google.com/spreadsheets/d/1sy3amsLN7xAyy81tfuxlClOh8G4A7tqDnKuiXvW-Zdg/edit#gid=0

**Comment by pnrobinson** [comment]
These do look more like HP terms. If one of the features occurs in isolated fashion then it may be regarded operationally as a disease. At some point we need to define an ontology of "symptom complex" I guess, let's talk about this in 2023!

**Comment by OOPD-LJF** [comment]
@sabrinatoro - thanks again for tackling these and @pnrobinson for considering them. I see that they could be considered phenotypes, but I still think they are also distinct diseases similar to others that are in Mondo:
- intraventricular hemorrhage (IVH) is similar to subarachnoid hemorrhage (MONDO: 0005099)
- neonatal sepsis is similar to neonatal anemia (MONDO: 0001240), neonatal leukemia (MONDO: 0004354), etc
- Group B strep is just a specific type of streptococcal infection (MONDO: 0021680)
- neonatal seizures - as I noted in my spreadsheet, Mondo has "neonatal epilepsy syndrome" (MONDO:0020070), "benign familial neonatal epilepsy" (MONDO:0002016), and "benign neonatal seizures" (MONDO:0016027), but these are syndromes. Neonatal seizures may not be "benign" and may have a pathological underlying cause as noted in the cited article. It could be an isolated diagnosis.
I agree that postpartum hemorrhage (PPH) may be a HP term. I found a synonym for DWMI - periventricular leukomalacia (PVL) - DWMI may need to be added as a synonym because it is a more current term. I would like to discuss preterm birth further - I feel like it is a "disease or disorder" but would be interested in other's thoughts.
Thanks again for entertaining my issues. Look forward to discussing in the new year.

**Comment by sabrinatoro** [comment]
from Mondo Medical Expert Meeting (230223):

**intraventricular hemorrhage (IVH)**
- this is a feature of "prematurity"
- other "hemorrhage" terms should be reviewed : https://github.com/monarch-initiative/mondo/issues/5956

**neonatal sepsis**
- is a disease and should be added into Mondo (check if there is a OMIM id)
- the HP term should be reviewed

**neonatal seizures:** 
- 'benign neonatal seizures' is a disease. However, other types of neonatal seizures would probably be a sign of epilepsy, but a child with seizures (and nothing else) would not have a diagnosis.
- we will review the "seizures" terms in Mondo and consult experts: https://github.com/monarch-initiative/mondo/issues/5957

**Comment by sabrinatoro** [comment]
summary: 
NTR | resolution 
-- | --
diffuse white matter injury (DWMI) | Add synonym to MONDO:0015742 ('periventricular leukomalacia')
neonatal sepsis | New: MONDO:0700058
group B Streptococcal infection | New: MONDO:0700207
intraventricular hemorrhage (IVH) | use HP:0030747 (Preterm intraventricular hemorrhage)
postpartum hemorrhage (PPH) | maybe new HP term - sibbling of 'antepartum hemorrhage' (HP:0025328)
preterm birth | use HP:0001622
neonatal seizures | use HP:0032807

**Comment by matentzn** [comment]
Its been merged and released last week!
