### ISSUE TITLE
constitutional delay of growth and puberty

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5534]
**Preferred term label: constitutional delay of growth and puberty**

**Synonyms: constitutional growth delay**

**Definition: transient state of hypogonadotropic hypogonadism associated with prolongation of childhood phase of growth, delayed skeletal maturation, delayed and attenuated pubertal growth spurt, and relatively low insulin-like growth factor-1 secretion. (PMID: 23087852])**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): disorder of development or morphogenesis**

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID): 0000-0001-7151-1615**

**Comment by sabrinatoro** [comment]
It looks like "constitutional delay of growth and puberty" could be in Mondo based on 
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3475892/
- https://www.researchgate.net/figure/Elements-for-the-differential-diagnosis-between-CDGP-and-CHH-in-males_tbl1_348893334
- This term is in snomed as a disorder: https://www.ebi.ac.uk/ols/ontologies/snomed/terms?iri=http%3A%2F%2Fsnomed.info%2Fid%2F237813007
