### ISSUE TITLE
spasticity due to spinal cord injury or multiple sclerosis

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5536]
**Preferred term label: spasticity due to spinal cord injury or multiple sclerosis**

**Synonyms**

**Definition: uncontrolled tightening or contracting of the muscles due to spinal cord injury or multiple sclerosis**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser): nervous system disorder**

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID): 0000-0001-7151-1615**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
"spasticity" is a phenotype or a symptom, and not a disease. Therefore, it should not been added in Mondo.
@OOPD-LJF, please let me know if you disagree.

**Comment by OOPD-LJF** [comment]
I agree - the diseases are spinal cord injury and MS - the spasticity is a phenotype/symptom of those diseases.

**Comment by sabrinatoro** [comment]
Thank you! This issue can be closed.
