### ISSUE TITLE
Iatrogenic disease: Procedure-related complications

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5540]
Seven recommendations for broad categories of procedure-related complications (under the parent of iatrogenic disease) in attached spreadsheet. Please let me know if you have questions - again, I understand that this may not fit well into this system but would be happy to discuss further. Thanks.
[PROCEDURES.Github_MONDO.Recommendations.xlsx](https://github.com/monarch-initiative/mondo/files/9889072/PROCEDURES.Github_MONDO.Recommendations.xlsx)

**Comment by nicolevasilevsky** [comment]
discussed this on the Mondo call and determined this is out scope
