### ISSUE TITLE
Morton neuroma

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5541]
**Preferred term label: Morton neuroma**

**Synonyms: Morton metatarsalgia, interdigital neuritis, Morton entrapment, interdigital neuralgia, interdigital neuroma, interdigital nerve compression syndrome, and intermetatarsal neuroma**

**Definition (PMID: 29262171): compressive neuropathy of the forefoot interdigital nerve chiefly due to compression and irritation at the plantar aspect of the transverse intermetatarsal ligament. It is not a true neuroma as the condition is degenerative rather than neoplastic. The most common location for Morton neuroma is between the 2nd and 3rd metatarsals**

**Parent term: nervous system disorder --> peripheral nervous system disorder --> neuroma**

**Children terms N/A**

**Your nano-attribution (ORCID): 0000-0001-7151-1615**

**Comment by sabrinatoro** [comment]
dbxref: NCIT:C4075
