### ISSUE TITLE
opioid-induced constipation

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5542]
**Preferred term label: opioid-induced constipation (OIC)**

**Synonyms: none**

**Definition (PMID: 29630236): OIC may present immediately when a patient takes the opioid, or it may present gradually during opioid therapy.**

**Parent term: constipation disorder**

**Children terms N/A**

**Your nano-attribution (ORCID): 0000-0001-7151-1615**

**Comment by nicolevasilevsky** [comment]
if this is considered a disorder, this is in scope for Mondo
