### ISSUE TITLE
baclofen withdrawal syndrome

### ISSUE THREAD

**Issue by OOPD-LJF** [monarch-initiative/mondo#5544]
**Preferred term label: baclofen withdrawal syndrome**

**Synonyms: none**

**Definition (PMID:12048649): abrupt withdrawal of baclofen therapy (intrathecal or oral) can result in high fever, altered mental status (including agitation, insomnia, confusion, delusions, hallucinations, seizures, visual changes, or psychosis), and potentially profound muscular rigidity that sometimes progresses to fatal rhabdomyolysis**

**Parent term: nervous system disorder**

**Children terms: not applicable**

**Your nano-attribution (ORCID): 0000-0001-7151-1615**

**Comment by nicolevasilevsky** [comment]
note- baclofen is a non-opiod muscle relaxant for pts with Cerebral Palsy and other related diseases. Frequently pts are taking this long-term and will experience withdrawal if they are stopped suddenly

Do we want to add all of the other common withdrawal syndromes? (like seratonin syndrome that is an outcome of stopping SSRI)

- should we create a class for medication withdrawal syndrome? Substance withdrawal has the connotation of addictive or illegal drugs
- do we need a grouping class 'withdrawal syndrome', add 'substance withdrawal' as a child + 'medication withdrawal syndrome' as children
- consider making existing term broader [substance withdrawal syndrome](http://purl.obolibrary.org/obo/MONDO_0005567)

**Comment by sabrinatoro** [comment]
- I reviewed the definition of the parent term "substance-related disorder", and ensured that it includes alcohol, drugs, medications
- I updated the definition of "substance withdrawal syndrome" to make the term broad and ensure that the definition includes alcohol, drugs, and medications (note that the original definition was a bit complicated and might have included medication)
- created the new "baclofen withdrawal syndrome"

Note for the future: other withdrawal syndrome terms (e.g. "serotonin syndrome") will be created on an "as needed" basis.

**Comment by OOPD-LJF** [comment]
Thank you @sabrinatoro and @nicolevasilevsky
