### ISSUE TITLE
[Revise subclass] DeSanto-Shinawi Syndrome due to 10p11.21p12.31 microdeletions (MONDO:0017283)

### ISSUE THREAD

**Issue by ARosselClinGen** [monarch-initiative/mondo#5546]
**Mondo term (ID and Label)**
DeSanto-Shinawi Syndrome due to 10p11.21p12.31 microdeletions (MONDO:0017283)

**Suggested revision and reasons**
We would like DeSanto-Shinawi Syndrome due to 10p11.21p12.31 microdeletions (MONDO:0017283) to be a child term of DeSanto-Shinawi syndrome (MONDO:0018760) rather than DeSanto-Shinawi syndrome due to WAC point mutations (MONDO:0014741). \

The microdeletion Mondo term is a more descriptive label that can be used to describe the cause of DeSanto-Shinawi syndrome (MONDO:0018760). It is not the cause of nor the descendent of point mutations in the WAC gene. DeSanto-Shinawi syndrome due to WAC point mutations (MONDO:0014741) is instead another specific way to identify the kind of variant underlying DESSH.

**Your nano-attribution (ORCID)**
Requested on behalf of the ClinGen ID/Autism GCEP: https://clinicalgenome.org/affiliation/40006/

CC: @ErinRiggs

**Comment by nicolevasilevsky** [comment]
No problem @ARosselClinGen, we'll take care of this for the next release.

**Comment by ARosselClinGen** [comment]
Thank you, Nicole!
