### ISSUE TITLE
remove "obsoletion candidate" tag from obsoleted terms

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#5558]
a lot of obsoleted terms still have the "obsoletion candidate" tag. 
we should remove these tag when the term is obsoleted

**Comment by sabrinatoro** [comment]
list of all terms with the "obsoletion candidate" list is: [here](https://docs.google.com/spreadsheets/d/1-X5d2Ep4EuBRUakh1NvtQw5_r-2ZoEsLOKhQMF-WZHY/edit#gid=0)

**Comment by nicolevasilevsky** [comment]
I can work on this with Nico

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I am seeing conflicting information about the following 2 terms: 
MONDO:0100387 - acute myeloid leukemia, Monosomy 7
MONDO:0100376 - acute myeloid leukemia, t(9;11)(p21.3;q23.3)

These have the "obsoletion tag". 
Based on #3583, these terms were to be merged, but we decided to not merge them. But based on your table review, I understand that we might want to obsolete them (and add a date). 
Can you please confirm which should be done? (I think we need to keep and remove the obsoletion tag, but I want to double check) Thank you!

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
Should we update the obsoletion dates for the one that has a "past date"? (since we say "will be obsolete on or after", it might be ok to leave it as such)

**Comment by sabrinatoro** [comment]
part of #5561
