### ISSUE TITLE
Review obsoletion candidates

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#5561]
We should review the list of obsoletion candidates and update the obsoletion date, do the obsoletion, or remove the obsoletion tag. (let's call it "end of the year clean-up").
The list of obsoletion candidates with the GH issues is here: 
https://docs.google.com/spreadsheets/d/1-X5d2Ep4EuBRUakh1NvtQw5_r-2ZoEsLOKhQMF-WZHY/edit#gid=2084320747.

**Comment by nicolevasilevsky** [comment]
@sabrinatoro did you already review this list? Should I just review it next and then we can work on removing the tags where needed?

**Comment by sabrinatoro** [comment]
@nicolevasilevsky I need to remove the tags and the obsoletion dates for some. 
I would like for you to review 1) whether it is true that we agree on not obsoleting, 2) what to do with the one that has not been obsoleted yet (maybe we need to discuss this during a call)/

**Comment by sabrinatoro** [comment]
@nicolevasilevsky
I am seeing conflicting information about the following 2 terms:
MONDO:0100387 - acute myeloid leukemia, Monosomy 7
MONDO:0100376 - acute myeloid leukemia, t(9;11)(p21.3;q23.3)

These have the "obsoletion tag".
Based on https://github.com/monarch-initiative/mondo/issues/3583, these terms were to be merged, but we decided to not merge them. But based on your table review, I understand that we might want to obsolete them (and add a date).
Can you please confirm which should be done? (I think we need to keep and remove the obsoletion tag, but I want to double check) Thank you!

Should we update the obsoletion dates for the one that has a "past date"? (since we say "will be obsolete on or after", it might be ok to leave it as such)

**Comment by nicolevasilevsky** [comment]
Let's not obsolete them based on #3583. I will remove the obs tag.

**Comment by nicolevasilevsky** [comment]
@sabrinatoro is there further action needed for this or can it be closed?

I think you took care of everything?

**Comment by sabrinatoro** [comment]
@nicolevasilevsky it is all done. (I thought it would close with the last PR). 
Closing now. Thank you!
