### ISSUE TITLE
[NTR] CHRNG-associated hypo-akinesia disorder of prenatal onset

### ISSUE THREAD

**Issue by ARosselClinGen** [monarch-initiative/mondo#5563]
**Preferred term label:**
CHRNG-associated hypo-akinesia disorder of prenatal onset

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
CHRNG-associated hypo-akinesia disorder of prenatal onset is a term used to describe the spectrum of presentations resulting from biallelic protein-altering variation in CHRNG.  CHRNG is a subunit of the nicotinergic acetylcholine receptor (AChR), which is present in skeletal muscle at the neuromuscular junction. CHRNG encodes for the gamma subunit of AChR, which is present during fetal development, and is gradually replaced by the epsilon subunit in the late fetal and perinatal period and persists through adulthood (PMID:16826520).  Fetal AChR is critical for establishing muscle-axon interface and neuromuscular junctions as well as prenatal neuromuscular signal transduction.    

Inactivation of the receptor during early development leads to prenatal hypo-akinesia; subsequent phenotypes are a consequence of this hypo-akinesia and are thought to be dependent upon timing and severity of the anomaly at the neuromuscular junction. A range of phenotypes varying in severity (including both lethal and non-lethal presentations) have been reported, but typically include joint contractures, pterygia, dysmorphic features, vertebral and thoracic anomalies, and additional variable abnormalities. There are no clear genotype-phenotype correlations between the lethal and non-lethal presentations of this spectrum; both inter- and intra-familial variability have been reported, with the same variants being observed in both lethal and non-lethal cases (PMIDs: 30868735, 22167768, 16826520, 16826531, etc.).

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Note to MONDO team: we would like your advice on structuring the parent/child terms for this new term.  Currently, the parent term “multiple pterygium syndrome” (MONDO: 0017415) has children that include “AR multiple pterygium syndrome” (MONDO:0009926) and “lethal multiple pterygium syndrome” (MONDO: 0009668).  What we are trying to convey is that our new term encompasses BOTH AR multiple pterygium syndrome AND lethal multiple pterygium syndrome but is not the only possible cause of either of these presentations.

**Children terms (if applicable)** 
See comment above.

**Your nano-attribution (ORCID)**
Submitted on behalf of ClinGen's Prenatal Gene Curation Expert Panel
https://www.clinicalgenome.org/affiliation/40106/

Cc: @ErinRiggs, @sng2140

**Comment by nicolevasilevsky** [comment]
@ARosselClinGen I added a comment that says this term encompasses BOTH AR multiple pterygium syndrome AND lethal multiple pterygium syndrome but is not the only possible cause of either of these presentations.
