### ISSUE TITLE
Relabel request for Partial epilepsy (MONDO:0005384)

### ISSUE THREAD

**Issue by ARosselClinGen** [monarch-initiative/mondo#5564]
**Mondo term (ID and Label):**
Partial epilepsy (MONDO:0005384)

**Suggested new label:**
Focal epilepsy

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
Requested on behalf of the ClinGen Epilepsy GCEP: https://clinicalgenome.org/affiliation/40005/

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
The updated term for partial epilepsy is now focal epilepsy, according to the International League Against Epilepsy Nosology and Definitions Taskforce (PMID: 35503725, 28276062).

Cc: @ErinRiggs

**Comment by ARosselClinGen** [comment]
Hi Nicole! I saw this was tagged for the December release--do you anticipate any delays or interruptions due to the holidays, or is the release still likely to come out in December as planned? We are working to decide when to move forward with publishing a curation on our end, and are planning on waiting if the relabel will be released in the coming weeks. Thanks!

**Comment by nicolevasilevsky** [comment]
Hi @ARosselClinGen 
We don't anticipate any delays - we plan to run the release on Thursday, Dec 01.

cc @sabrinatoro 

If any issues arise, we'll notify folks via the Mondo users email list.
