### ISSUE TITLE
deSanctis Cacchione syndrome

### ISSUE THREAD

**Issue by pjbrooksphd** [monarch-initiative/mondo#557]
DeSanctis-Cacchione Stndrome is listed as 
A rare autosomal recessive inherited syndrome. It is characterized by xeroderma pigmentosum, mental retardation, dwarfism, hypogonadism, and neurologic abnormalities.

it is a type of xeroderma pigmentosum

However, if I click the box under inherited disease, xeroderma pigmentosum is not listed.

.For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/tbn)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by nicolevasilevsky** [comment]
Hi @pjbrooksphd sorry for the long delay in addressing this ticket.

I see xeroderma pigmentosum is classified as a 'hereditary photodermatosis', which is classified as an inherited disease. I think this addresses your issue.

If not, please reopen.

Thanks for reporting this to Mondo.
