### ISSUE TITLE
Distinguishing between disease and phenotypic features in MonDO

### ISSUE THREAD

**Issue by courtneythaxton** [monarch-initiative/mondo#559]
Suggest that all MonDO disease, not be labeled with "(disease)", and to make a clear distinction between a disease and phenotype/phenotypic feature, to highlight the phenotypic features. 

For example, MonDO shows glutaric acuduria (disease) MONDO:0000129 and it has an equivalent of the HPO term glutaric acuduria (HP:0003150). These are two different entities, in which the disease has multiple phenotypes associated included the finding of the phenotypic features of increased glutamic acid in the urine (glutaric aciduria). In this case it might be useful to leave the (disease) off of the MonDO disease entity, and associate the HPO as being a phenotypic feature: i.e. glutamic aciduira (phenotype).

@nicolevasilevsky @cmungall @mellybelly @pnrobinson @Orphanet @ahamosh

**Comment by pnrobinson** [comment]
In cases such as this, it might be an idea to rename the HPO term to Increased urine glutaric acid concentration, even though logically glutaric acuduria can also be parsed as a phenotypic feature.

**Comment by nicolevasilevsky** [comment]
see
 https://github.com/monarch-initiative/mondo/discussions/2598

**Comment by nicolevasilevsky** [comment]
@courtneythaxton we have removed the (disease) from the labels in Mondo. I'll close this but please reopen a new ticket if any action items are needed.
Thank you! :)
