### ISSUE TITLE
Missing OMIM IDs

### ISSUE THREAD

**Issue by ashimiblessing** [monarch-initiative/mondo#5605]
Hello,
While parsing the current release I noticed that it has > 2000 OMIM IDs lesser than the previous release. Is this by design?

**Comment by sabrinatoro** [comment]
Thank you @ashimiblessing for letting us know. 

@matentzn, @joeflack4, @hrshdhgd : could any of you create a report between the current and the previous release? The report should include:
- all the OMIM id (MONDO:equivalentTo) that are in one release and not the other
- the corresponding Mondo term ID, 
- the corresponding Mondo term label
- (if easily possible) the name of the OMIM term. 
I think it would be a good start to troubleshoot the issue. Thank you!

**Comment by matentzn** [comment]
@ashimiblessing Thank you for your issue.

Can you tell us:

1. Which file did you use (http://purl.obolibrary.org/obo/mondo.owl)
2. Can you give us an example of 2-3 missing OMIM terms?
3. How did you determine them missing, did you check a diff, or look for missing hasDbXref?

**Comment by joeflack4** [comment]
I am going to hold off on this for now pending some of the checks that Nico and Sabrina have asked for / are looking into.

Some of this could be terms that are now being explicitly excluded from Mondo. Or it could be something to do with the https://github.com/monarch-initiative/omim ingest as well. There will also be a new release of that ingest very soon. Note that these ingests pull from the https://omim.org/ API, which can change daily, so some of the differences may be a result of that as well.

**Comment by matentzn** [comment]
@ashimiblessing I made an analysis, but @sabrinatoro you should digg a bit deeper.

This is a rough diff based on grep, i.e. how many OMIM: related annotations where dropped across the past 4 Mondo versions.

```
September 9 to October 3
Removed:
      65
Added:
      34

October 3 to October 11
Removed:
    3001
Added:
     555

October 11 to November 1
Removed:
      15
Added:
      23

September 6 to November 1
Removed:
    3081
Added:
     612
```

It is clear the relevant diff is `October 3 to October 11`.

Digging a little bit into it, it seems that by far the majority of the xrefs where sourced from Orphanet and involved btnt. `"Orphanet:2309/btnt"`.

@sabrinatoro to solve the issue entirely:

- [ ] digg out the PR/issues where dropping these was decided
- [ ] Determine if they are really dropped, because, I can see them still in the edit file, or at least, the 3 cases I cherry picked. Find the diff attached

[diff_1003_1011_omim.txt](https://github.com/monarch-initiative/mondo/files/10012063/diff_1003_1011_omim.txt)

**Comment by sabrinatoro** [comment]
In this issue (https://github.com/monarch-initiative/mondo/issues/5468), we decided to get rid of any xref that is known for sure not to be MONDO:equivalentTo for OMIM only. This issue is not closed, though we might have already done the work. 
@matentzn Going through the PR, it looks like this one (https://github.com/monarch-initiative/mondo/pull/5466) could be the one that removed these xref for OMIM if they were not Equivalent. This is the only PR I could find that could make sense, but the dates do not match. So if it is not the correct PR, I can investigate deeper.

**Comment by nicolevasilevsky** [comment]
@sabrinatoro do you need help with this? I suspect it could have been some mistake I made during the Oct 03 release....

**Comment by nicolevasilevsky** [comment]
Upon looking at this - I agree with Sabrina. At some point we decided not to display the the non-equivalent xrefs, for example:

this is a term in the mondo-edit.obo

```
[Term]
id: MONDO:0000127
name: geleophysic dysplasia
def: "Geleophysic dysplasia is a rare skeletal dysplasia characterized by short stature, prominent abnormalities in hands and feet, and a characteristic facial appearance (described as \"happy'')." [Orphanet:2623]
subset: ordo_malformation_syndrome {source="Orphanet:2623"}
synonym: "geleophysic dwarfism" EXACT [Orphanet:2623]
synonym: "geleophysic dwarfism syndrome" RELATED [MONDO:cjm]
xref: DOID:0111724 {source="MONDO:equivalentTo"}
xref: GARD:0002449 {source="MONDO:equivalentTo"}
xref: ICD10CM:Q87.1 {source="Orphanet:2623", source="Orphanet:2623/attributed", source="Orphanet:2623/ntbt"}
xref: ICD9:759.89 {source="MONDO:relatedTo", source="MONDO:i2s"}
xref: MedDRA:10063361 {source="Orphanet:2623", source="Orphanet:2623/e"}
xref: MESH:C537677 {source="Orphanet:2623", source="Orphanet:2623/e"}
xref: OMIM:231050 {source="Orphanet:2623", source="Orphanet:2623/btnt"}
xref: OMIM:614185 {source="Orphanet:2623", source="Orphanet:2623/btnt"}
xref: OMIM:617809 {source="https://orcid.org/0000-0001-8612-1062"}
xref: OMIMPS:231050 {source="MONDO:equivalentTo"}
xref: Orphanet:2623 {source="MONDO:equivalentTo"}
xref: SCTID:28557005 {source="MONDO:equivalentTo"}
xref: UMLS:C3489726 {source="Orphanet:2623", source="MONDO:notFoundInDiseaseSubset", source="Orphanet:2623/e"}
is_a: MONDO:0019695 {source="Orphanet:2623"} ! acromelic dysplasia
relationship: has_characteristic MONDO:0021152 {source="OMIMPS:231050"} ! inherited
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/4666 xsd:anyURI
```


and this is the term in the Oct 11 release


```
[Term]
id: MONDO:0000127
name: geleophysic dysplasia
def: "Geleophysic dysplasia is a rare skeletal dysplasia characterized by short stature, prominent abnormalities in hands and feet, and a characteristic facial appearance (described as \"happy'')." [Orphanet:2623]
subset: ordo_malformation_syndrome {source="Orphanet:2623"}
synonym: "geleophysic dwarfism" EXACT [Orphanet:2623]
synonym: "geleophysic dwarfism syndrome" RELATED [MONDO:cjm]
xref: DOID:0111724 {source="MONDO:equivalentTo"}
xref: GARD:0002449 {source="MONDO:equivalentTo"}
xref: ICD9:759.89 {source="MONDO:relatedTo", source="MONDO:i2s"}
xref: MedDRA:10063361 {source="Orphanet:2623", source="Orphanet:2623/e"}
xref: OMIMPS:231050 {source="MONDO:equivalentTo"}
xref: Orphanet:2623 {source="MONDO:equivalentTo"}
xref: SCTID:28557005 {source="MONDO:equivalentTo"}
is_a: MONDO:0019695 {source="Orphanet:2623"} ! acromelic dysplasia
property_value: closeMatch http://identifiers.org/meddra/10063361
property_value: exactMatch DOID:0111724
property_value: exactMatch http://identifiers.org/snomedct/28557005
property_value: exactMatch https://omim.org/phenotypicSeries/PS231050
property_value: exactMatch Orphanet:2623
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/4666 xsd:anyURI
```

(but I guess this didn't apply to MEDDRA?)

**Comment by nicolevasilevsky** [comment]
I think these are the notes where we discussed this on Oct 01, 2022

<img width="596" alt="image" src="https://user-images.githubusercontent.com/6722114/202351533-533332d5-2fd6-4df7-80f1-9ea4061804d0.png">

**Comment by matentzn** [comment]
Yes, I think this is all correct and expected, no bug. Can one of you explain the decision to @ashimiblessing, then the issue can be closed.

**Comment by nicolevasilevsky** [comment]
@ashimiblessing in the release version of Mondo, we are now displaying the equivalent OMIM mappings, we stripped out all of the non-equivalent (non-exact) mapping from the release version (but they are still visible in the edit file, should you ever want to see them).

Please reopen if further action it needed or if you have further questions.

Thanks for reporting this!

**Comment by ashimiblessing** [comment]
Thanks everyone!
