### ISSUE TITLE
remove `http://purl.obolibrary.org/obo/excluded_subClassOf`

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/mondo#5614]
Mondo has an annotation property `http://purl.obolibrary.org/obo/mondo#excluded_subClassOf`. This issue is not about that term.

There is an object property `http://purl.obolibrary.org/obo/excluded_subClassOf` which was probably added accidentally. It looks like it's only used with [X-linked mandibulofacial dysostosis](http://purl.obolibrary.org/obo/MONDO_0010539). The five usages should be converted to the above annotation property.

**Comment by nicolevasilevsky** [comment]
thanks @balhoff, I can fix this
