### ISSUE TITLE
SPLIT OMIMPS terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5619]
[Term]
id: MONDO:0031329
name: craniofacial dysmorphism, skeletal anomalies, and impaired intellectual development syndrome
xref: OMIMPS:213980 {source="MONDO:equivalentTo"} ! craniofacial dysmorphism, skeletal anomalies, and impaired intellectual development syndrome

[Term]
id: MONDO:0031415
name: Carey-Fineman-Ziter syndrome
xref: OMIMPS:254940 {source="MONDO:equivalentTo"} ! carey-fineman-ziter syndrome
is_a: MONDO:0003847{ source="https://orcid.org/0000-0001-5208-3432"} ! Mendelian disease
relationship: has_characteristic MONDO:0021152 {source="OMIMPS:212093"} ! inherited

[Term]
id: MONDO:0031632
name: developmental delay with short stature, dysmorphic facial features, and sparse hair
xref: OMIMPS:616901 {source="MONDO:equivalentTo"} ! developmental delay with short stature, dysmorphic facial features, and sparse hair
relationship: has_characteristic MONDO:0021152 {source="OMIMPS:256550"} ! inherited

see [spreadsheet](https://docs.google.com/spreadsheets/d/1tt1Wk70j9XiHLV1vKQyNiHhaazh286pobpJk1ecSCCg/edit#gid=1780554610)

**Comment by nicolevasilevsky** [comment]
# Action items

## Obsolete

- [ ] MONDO:0008952 | cerebrofaciothoracic dysplasia'
- [ ] MONDO:0009700 | Carey-Fineman-Ziter syndrome
- [ ] MONDO:0014824 | developmental delay with short stature, dysmorphic facial features, and sparse hair

## Add new terms

[Term]
id: MONDO:0031329
name: craniofacial dysmorphism, skeletal anomalies, and impaired intellectual development syndrome
xref: OMIMPS:213980 {source="MONDO:equivalentTo"} ! craniofacial dysmorphism, skeletal anomalies, and impaired intellectual development syndrome
is_a: MONDO:0003847{ source="OMIMPS:213980"} ! Mendelian disease
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/5619 xsd:anyURI

[Term]
id: MONDO:0800385
name: ccraniofacial dysmorphism, skeletal anomalies, and impaired intellectual development 1
def: "A rare syndrome characterized by facial dysmorphism, intellectual deficit and costovertebral abnormalities." [Orphanet:1394, https://orcid.org/0000-0001-5208-3432]
subset: gard_rare
subset: ordo_malformation_syndrome {source="Orphanet:1394"}
synonym: "cerebro facio thoracic dysplasia" RELATED [GARD:0001210]
synonym: "cerebrofaciothoracic dysplasia" EXACT CLINGEN_PREFERRED [GARD:0001210, OMIM:213980]
synonym: "CFSMR" RELATED DEPRECATED [MONDO:Lexical, OMIM:213980]
synonym: "CFSMR1" EXACT [MONDO:Lexical, OMIM:213980]
synonym: "pascual-Castroviejo syndrome" RELATED [GARD:0001210]
synonym: "pascual-Castroviejo syndrome type 1" EXACT [Orphanet:1394]
xref: GARD:0001210 {source="MONDO:equivalentTo"}
xref: ICD10CM:Q87.5 {source="Orphanet:1394/attributed", source="Orphanet:1394/ntbt", source="Orphanet:1394"}
xref: MESH:C565862 {source="MONDO:equivalentTo"}
xref: OMIM:213980 {source="GARD:0001210", source="Orphanet:1394/e", source="MONDO:equivalentTo", source="Orphanet:1394"}
xref: Orphanet:1394 {source="OMIM:213980", source="MONDO:equivalentTo"}
xref: SCTID:720635002 {source="MONDO:equivalentTo"}
xref: UMLS:C1859252 {source="OMIM:213980", source="MONDO:ncbi_mim2gene_medline", source="MONDO:notFoundInDiseaseSubset", source="Orphanet:1394"}
relationship: excluded_subClassOf MONDO:0000508 {source="MONDO:Redundant", source="Orphanet:1394"} ! syndromic intellectual disability
relationship: excluded_subClassOf MONDO:0015159 {source="Orphanet:1394"} ! multiple congenital anomalies/dysmorphic syndrome-intellectual disability
relationship: excluded_subClassOf MONDO:0018454 {source="MONDO:0019711-obsoleted", source="https://github.com/monarch-initiative/mondo/pull/2571/"} ! dysostosis of genetic origin
**is_a: MONDO:0003847{ source="[https://orcid.org/0000-0001-5208-3432"}](https://orcid.org/0000-0001-5208-3432%22%7D) ! Mendelian disease**
relationship: has_characteristic MONDO:0021136 {source="MONDO:0015162", source="MONDO:0015983"} ! rare
property_value: confidence "9.0" xsd:double
property_value: seeAlso https://rarediseases.info.nih.gov/diseases/1210/cerebro-facio-thoracic-dysplasia xsd:anyURI {source="GARD:0001210"}
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/5619 xsd:anyURI

[Term]
id: MONDO:0031415
name: Carey-Fineman-Ziter syndrome
xref: OMIMPS:254940 {source="MONDO:equivalentTo"} ! carey-fineman-ziter syndrome
is_a: MONDO:0003847{ source="OMIMPS:254940"} ! Mendelian disease
relationship: has_characteristic MONDO:0021152 {source="OMIMPS:212093"} ! inherited
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/5619 xsd:anyURI

[Term]
id: MONDO:0031632
name: developmental delay with short stature, dysmorphic facial features, and sparse hair
xref: OMIMPS:616901 {source="MONDO:equivalentTo"} ! developmental delay with short stature, dysmorphic facial features, and sparse hair
is_a: MONDO:0003847{ source="OMIMPS:616901"} ! Mendelian disease
relationship: has_characteristic MONDO:0021152 {source="OMIMPS:256550"} ! inherited
property_value: IAO:0000233 https://github.com/monarch-initiative/mondo/issues/5619 xsd:anyURI

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
be aware that some new IDs have been used for other terms between when this issue was created and now. 
For instance, MONDO:0800386 was to be used for 'Carey-Fineman-Ziter syndrome 1'. However, it has been used recently for 'organophosphate poisoning'.
The main problem is that, when preparing for the obsoletion of MONDO:0009700(Carey-Fineman-Ziter syndrome), users would use the ID shown in the comments, ie MONDO:0031415 or MONDO:0800386 which is not the correct id anymore. 
Same for : 
- MONDO:0800387
- MONDO:0800385
- MONDO:0800386

TO DO: 
since these ID have already been used for new terms (which were already released), we need to assign new ids for these post-splits terms and update the comments for the obsoletion candidate

PS: I did not update anything at this point, because I don't know where the master for this id range is, and I don't want to add to the confusion.

**Comment by ValWood** [comment]
It seems that 
https://monarchinitiative.org/disease/MONDO:0014824
is split into 2 terms.  Do both of these terms apply to  DPH1?
I can't trace this info and the new term is not yet in OLS.

**Comment by ValWood** [comment]
right so it shouldn't be replace by ? should be consider ? (I would need MONDO:0800438  not MONDO:0031632 to be specific for DPH1 ortholog.

**Comment by nicolevasilevsky** [comment]
Good point, I will change this to consider. Thanks!
