### ISSUE TITLE
MONDO:0007175 PR interval, variation 1N

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5632]
**Mondo term (ID and Label):**
PR interval, variation 1N
MONDO:0007175 
**Suggested new label:**
PR interval, variation in 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Based on the description from the OMIM page, I'm pretty sure this entry is describing the variation in length of the PR interval, which is described as having "a substantial heritable component." https://www.omim.org/entry/108980 As currently labeled in Mondo, it looks like this is a variation sub-type 1N.

**Comment by nicolevasilevsky** [comment]
ha, this is a funny typo, thanks for catching that!
