### ISSUE TITLE
merge MONDO:0022566 BEST1 retinopathy

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#564]
Comes from https://rarediseases.info.nih.gov/diseases/10301/best1-retinopathy

is this a grouping for the various BEST1 eye diseases, or should be merged?

**Comment by nicolevasilevsky** [comment]
@cmungall what term are you suggesting that MONDO:0022566 BEST1 retinopathy be potentially merged with? Seems like this term could be merged with MONDO_0012733 'autosomal recessive bestrophinopathy'

I think this approach would make sense, as opposed to using this term as a grouping class.

**Comment by cmungall** [comment]
MONDO:0007931

**Comment by nicolevasilevsky** [comment]
Got it- thanks! I'll merge this.

**Comment by nicolevasilevsky** [comment]
@maglott - @cmungall suggested that I draw out some sketches of what it would look like to use Best1 retinopathy as a grouping class.

The diagram below shows what is currently implemented in PR #596, with Best1 retinopathy being merged with 'vitelliform macular dystrophy 2'. (note, I didn't include all the multiple parentage and all of the intermediate classes in the diagram)

![image](https://user-images.githubusercontent.com/6722114/50182522-630aab80-02c4-11e9-8b47-9aa66cd5f5e0.png)

If Best1 retinopathy were to be a grouping class, would it be something like this?
![image](https://user-images.githubusercontent.com/6722114/50182667-cbf22380-02c4-11e9-96ae-fd4bd63bca70.png)

**Comment by maglott** [comment]
First, I am not certain how GARD defines BEST1 retinopathy.  If BEST1 retinopathy is indeed all retinopathy resulting from mutations in BEST1,  then it seems   BEST1  retinopathy is a MONDO_009118.  OMIM lists multiple retinopathies for BEST1 https://www.omim.org/entry/607854, some of which you have suggested to point to MONDO_022566

**Comment by nicolevasilevsky** [comment]
It doesn't look like GARD has a definition for BEST1 retinopathy on their [disease page](https://rarediseases.info.nih.gov/diseases/10301/best1-retinopathy).

Here is an article about BEST1 retinopathy: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2253971/?tool=pubmed

From what I can tell, a disease or grouping class called BEST1 retinopathy doesn't already exist. 

I think MONDO_009118 'inherited retinal dystrophy' is a more general class than BEST1 retinopathy.

In the current pending pull request, I merge BEST1 retinopathy with MONDO:0007931 'vitelliform macular dystrophy 2', per @cmungall's suggestion above.

**Comment by maglott** [comment]
bq. I think MONDO_009118 'inherited retinal dystrophy' is a more general class than BEST1 retinopathy.
Agreed.  That is what I was trying to convey.
As for what GARD intends for this term, should they be asked to clarify.  Thanks for the the reference.

**Comment by nicolevasilevsky** [comment]
@gardinfocenter - when you have a chance, could you comment on how you intend the term 'BEST1 retinopathy' to be defined? See comments above.

Thanks!

**Comment by GARDInfoCenter** [comment]
We will get back to you. Thanks!

**Comment by maglott** [comment]
Thanks for reviewing. Sorry to have slowed this but I think the rename helps
