### ISSUE TITLE
MONDO_0007818 has an obsolete OMIM reference

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5640]
**Mondo term (ID Label)**
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0007818

**Bug/Typo/Error description**
 UMLS:C1840265 (OMIM:146840)
OMIM:147060 (Orphanet:2314/e) 

-- the OMIM id 146840 is "moved to" (obsolete). (https://omim.org/entry/146840?search=146840&highlight=146840)

We should have a q/c routine to check for obsoleted OMIM IDs with every release (I found this by chance)
@matentzn

**Comment by matentzn** [comment]
@joeflack4 this issue is an indication that we should prioritise our deprecation slurp.

**Comment by joeflack4** [comment]
I located 91 mapped deprecated terms in Mondo out of 1,345 deprecated OMIM terms.

Analysis and outputs in PR: https://github.com/monarch-initiative/mondo-ingest/pull/108

**Comment by matentzn** [comment]
Nice one @joeflack4

**Comment by nicolevasilevsky** [comment]
This has been fixed
