### ISSUE TITLE
SPARQL query for list of rare diseases

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5642]
@sabrinatoro when you have a chance, could you please do a query for the list of rare diseases in Mondo and share it with Gioconda? (See email)

Thanks!

**Comment by sabrinatoro** [comment]
the list was created on November 30th, 2022. And it is : 
[rarediseases_list_221130.txt](https://github.com/monarch-initiative/mondo/files/10127359/rarediseases_list_221130.txt)
