### ISSUE TITLE
Parents of MONDO:0018982 'Niemann-Pick disease type C'

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#565]
Stemming from https://github.com/EBISPOT/efo/issues/292

Niemann-Pick disease type C is a metabolic disorder (a sphingolipidosis) that may result in severe phenotypes affecting several systems, especially neurological symptoms. However, in MONDO some of the current parents of the term (http://purl.obolibrary.org/obo/MONDO_0018982), presumably derived from Orphanet (http://www.orpha.net/ORDO/Orphanet_646), seem incorrect (e.g. 'unclassified primitive or secondary maculopathy', 'supranuclear oculomotor palsy'). The classification of the Orphanet term in EFO is not exactly the same but presents similar issues (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_646). We've already removed the parentage to 'neoplasm', and would like to fix the other parents, and it would be better to do this consistently with MONDO. Could you please revise the hierarchy of MONDO:0018982 and let us know what you think of e.g. the maculopathy and palsy parents?

Thanks!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky @cmungall 
FYI, we may want to discuss this ticket at our next EFO-MONDO call, along with our EFO epic https://github.com/EBISPOT/efo/issues/322.

**Comment by paolaroncaglia** [comment]
Same issue as broader topic in https://github.com/monarch-initiative/mondo/issues/834

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I realized I am not totally clear - which superclasses would you like to be removed from MONDO:0018982 'Niemann-Pick disease type C'?

- 'unclassified primitive or secondary maculopathy', 
- 'supranuclear oculomotor palsy'

Any others?

Thanks!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky (Happy Thanksgiving, no hurry...):

> @paolaroncaglia I realized I am not totally clear - which superclasses would you like to be removed from MONDO:0018982 'Niemann-Pick disease type C'?
> 
>     * 'unclassified primitive or secondary maculopathy',
> 
>     * 'supranuclear oculomotor palsy'
> 
> 
> Any others?
> 
> Thanks!

I think that all of the current parents are incorrect and should be removed, except for 'Niemann-Pick disease'. The ancestry to specific metabolic disorders is already inherent in the parentage of 'Niemann-Pick disease' itself. Thanks!
