### ISSUE TITLE
[NTR/gene] Hereditary inclusion-body myopathy

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5658]
**Preferred gene-related syndrome label**
[NTR/gene] Hereditary inclusion-body myopathy

See
https://pubmed.ncbi.nlm.nih.gov/25149037/

rename inclusion myopathy (allof the diseases are hereditary).
Also, 
revise congenital myopathy according to https://ijponline.biomedcentral.com/articles/10.1186/s13052-017-0419-z

Also add term 
Genetic Muscle Disorders:
with these three main children
[Muscular dystrophies](https://www.kennedykrieger.org/patient-care/conditions/muscular-dystrophy): Duchenne, Becker, Facioscapulohumeral, Myotonic, Congenital, Distal, Emery-Dreifuss, Oculopharyngeal, Limb Girdle
    [Congenital myopathies](https://www.kennedykrieger.org/patient-care/conditions/congenital-myopathy): Central Core, Myotubular, Nemaline, Ullrich/Bethlem, RyR1
    [Metabolic muscle diseases](https://www.kennedykrieger.org/patient-care/conditions/metabolic-myopathies): Mitochondrial Myopathy, Pompe Disease, McArdles Disease, Carnitine Palmitoyl Transferase Deficiency

**Comment by galyea123** [comment]
Hi Sabrina!  Will it be possible to add RYR1-Related Diseases as a synonym for this condition?  PS:  We have a NORD report.  Thank you, Gioconda (If needed I can submit a ticket)
