### ISSUE TITLE
[Revise subclass] Smith-Magenis syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5659]
**Mondo term (ID and Label)**
Smith-Magenis syndrome

**Suggested revision and reasons**

Is not ALWAYS a deletion

A number sign (#) is used with this entry because Smith-Magenis syndrome (SMS) is caused in most cases (90%) by a 3.7-Mb interstitial deletion in chromosome 17p11.2. The disorder can also be caused by mutations in the RAI1 gene ([607642](https://omim.org/entry/607642)), which is within the Smith-Magenis chromosome region.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I excluded the parent chromosome 17p deletion
