### ISSUE TITLE
Zollinger-Ellison syndrome should not be classified as a subtype of tumor/neoplasm

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#566]
@zoependlington @paolaroncaglia in EFO we have

```
    is_a EFO:0000408 ! disease
     is_a EFO:0000616 ! neoplasm
      is_a EFO:0007549 ! Zollinger-Ellison Syndrome *** 
```

this is an example of is-a overloading, due you have objections to making the relationship has-feature

**Comment by cmungall** [comment]
also: Peutz-Jeghers

![image](https://user-images.githubusercontent.com/50745/49321925-ad67ec00-f4bf-11e8-8826-f286fe0e4887.png)

**Comment by zoependlington** [comment]
Thanks for letting us know @cmungall! I've created a ticket on our tracker (https://github.com/EBISPOT/efo/issues/322) so we can look into it/discuss.

**Comment by nicolevasilevsky** [comment]
looks like Peutz-Jeghers has already been addressed
