### ISSUE TITLE
[Revise text def] Mallory-Weiss syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5660]
**Mondo term (ID and Label)**
Mallory-Weiss syndrome

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
-- this is not a primary hemorrhagic disease unlss we want to list every disease where you can have bleeding.

-- also it would be good to have a superclass for hereditary bleeding diseases (currently, we only have something like this for platelets). 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
> also it would be good to have a superclass for hereditary bleeding diseases (currently, we only have something like this for platelets).

@pnrobinson I will open a separate ticket for this
