### ISSUE TITLE
Review superclass for chronic mucocutaneous candidiasis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5661]
**Mondo term (ID and Label)**
chronic mucocutaneous candidiasis
-- this term comprises mainly Mendelian diseases
-- however, it is not a subclass of [inborn errors or immunity](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0003778&lang=en&viewMode=PreferredRoots&siblings=false)

**Comment by pnrobinson** [comment]
The entire IEI subhierarchy needs to be revised!

**Comment by sabrinatoro** [comment]
@pnrobinson : I made 'chronic mucocutaneous candidiasis' a subclass of 'inborn errors or immunity'. 
Please let me know if there is anything else to be done for this issue (except for the revision of the subhierarchy of IEI, which will be done separately). Thank you!
