### ISSUE TITLE
[Revise subclass] orofacial clefting syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5665]
**Mondo term (ID and Label)**
orofacial clefting syndrome

**Suggested revision and reasons**

All of the subclasses are genetic and yet there is no corresponding parentage

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
this seems like an orphanet grouping class that is grouping terms based on phenotypes. 

is there a true disease that is called orofacial clefting syndrome?

Maybe this grouping class should be obsoleted?

Here is a related article
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2825080/

**Comment by nicolevasilevsky** [comment]
talking to Ada, this could be renamed to 'mendelian syndromes with cleft lip/palate' and make it a child of Mendelian disease
