### ISSUE TITLE
[Revise subclass] DNA repair disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5666]
**Mondo term (ID and Label)**
DNA repair disease

**Suggested revision and reasons**

all of these diseases are Mendelian. The current parent does not reflect that.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
should DNA repair disease be a child of Mendelian Disease? All of the children appear to be classified as inherited diseases based on other parents, from what I can tell.

@pnrobinson could you clarify what the action item is?

**Comment by nicolevasilevsky** [comment]
talking to Ada:
'Lynch syndrome' is a DNA repair disease

see:
https://omim.org/phenotypicSeries/PS120435
- [ ] note - a lot of these terms were renamed to Lynch syndrome [number]. These should be renamed in Mondo

- [ ] 'DNA repair disease' should be a child of Mendelian disease
