### ISSUE TITLE
retinitis pigmentosa

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5667]
**Mondo term (ID Label)**
retinitis pigmentosa

**Bug/Typo/Error description**
retinitis pigmentosa is not a subclass of glycolysis disorder

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@pnrobinson this was added based on the classification in the recent paper you shared (see https://github.com/monarch-initiative/mondo/issues/4985)

I can exclude this superclass. Please reopen this ticket if you would like to add it back.
