### ISSUE TITLE
A few potential disease duplications

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#567]
I'm catching up on mappings from the last few MONDO releases and have come across the following potential duplicate terms:

- Conjunctival disorder (MONDO_0006170) and conjunctival disease (MONDO_0002932) - both mapped to EFO_1000203 (Conjunctival Disorder)
- vitreous disease (MONDO_0004860) and vitreous body disorder (MONDO_0044137) - both mapped to EFO_0008624 (vitreous body disease)

**Comment by nicolevasilevsky** [comment]
Conjunctival disorder (MONDO_0006170) and conjunctival disease (MONDO_0002932) should be merged.

vitreous disease (MONDO_0004860) and vitreous body disorder (MONDO_0044137) seem like different terms though. I see MONDO_0044137 is equiv to EFO_0008624 (vitreous body disease), but I don't see a mapping in the mondo-edit.owl file of MONDO_0004860 to EFO_0008624, am I missing something here?

**Comment by zoependlington** [comment]
Oops! I think the mapping is just in our EFO 3 file, I'll edit this. Sorry!
