### ISSUE TITLE
[Revise subclass] encephalopathy, neonatal severe, with lactic acidosis and brain abnormalities

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#5671]
**Mondo term (ID and Label)**
encephalopathy, neonatal severe, with lactic acidosis and brain abnormalities

@ahamosh 
This disease is currently not classified anywhere in Mondo.

Is there a reason that this is not part of this phenotypc series?
developmental and epileptic encephalopathy

Otherwise, would there be a case to be made for a new Mondo class to cover Mendelian diseases such as developmental and epileptic encephalopathy whose primary clinical manifestation is encephalopathy?

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Sure, I'll add it now

**Comment by nicolevasilevsky** [comment]
> Is there a reason that this is not part of this phenotypc series?
developmental and epileptic encephalopathy

speaking to Ada, she said this is not in the DEE PS because these patients do not all have seizures.
Ada defines DEE as having seizures and the brain is bad.

This sounds like a bad brain and they may seize.

**Comment by nicolevasilevsky** [comment]
> Otherwise, would there be a case to be made for a new Mondo class to cover Mendelian diseases such as developmental and epileptic encephalopathy whose primary clinical manifestation is encephalopathy?

speaking to Ada - there are a lot of encephalopathies that are susceptibilities. There are some encephalopathies that are not DEE.

This could be another category and the distinction would be they are not seizing as their primary symptom.

New term:
Mendelian encephalopathy

Note- there is qualitative difference from DEE.

Note to self:
- [ ] add DEE as syn for 'developmental and epileptic encephalopathy'
