### ISSUE TITLE
weird equivalence class axioms and subclass axioms?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5697]
From Sarah A:

While running my experiments on mondo I found some weird equivalence class axioms and subclass axioms with the subject being an annotation assertion. For my work I'm removing those axioms. Yet, I'm not sure what they mean, and if those are meant to be part of MONDO or they have to be removed. here are some examples:

EquivalentClasses(Annotation(<http://www.geneontology.org/formats/oboInOwl#source> \"NCIT:C4381\"^^xsd:string) <http://purl.obolibrary.org/obo/MONDO_0002229> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/MONDO_0005626> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0004026> <http://purl.obolibrary.org/obo/UBERON_0000992>)) )

"SubClassOf(Annotation(<http://www.geneontology.org/formats/oboInOwl#source> \"DOID:0080297\"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#source> \"OMIM:617808\"^^xsd:string) <http://purl.obolibrary.org/obo/MONDO_0033492> <http://purl.obolibrary.org/obo/MONDO_0015802>)": [
        "http://purl.obolibrary.org/obo/DOID_0080297",
        "http://purl.obolibrary.org/obo/MONDO_0033492"

"SubClassOf(Annotation(<http://www.geneontology.org/formats/oboInOwl#source> \"MONDO:Redundant\"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#source> \"Orphanet:178469\"^^xsd:string) <http://purl.obolibrary.org/obo/MONDO_0015802> <http://purl.obolibrary.org/obo/MONDO_0000509>)"

"SubClassOf(Annotation(<http://www.geneontology.org/formats/oboInOwl#source> \"DOID:0060072\"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#source> \"DOID:0060084/inferred\"^^xsd:string) A
nnotation(<http://www.geneontology.org/formats/oboInOwl#source> \"DOID:0060085/inferred\"^^xsd:string) Annot
ation(<http://www.geneontology.org/formats/oboInOwl#source> \"EFO:0002422\"^^xsd:string) Annotation(<http://
[www.geneontology.org/formats/oboInOwl#source](http://www.geneontology.org/formats/oboInOwl#source)> \"ICD10CM:D10-D36\"^^xsd:string) Annotation(<http://www.geneon/
[tology.org/formats/oboInOwl#source](http://tology.org/formats/oboInOwl#source)> \"MONDO:Redundant\"^^xsd:string) Annotation(<http://www.geneontology.org/
/formats/oboInOwl#source> \"NCIT:C3677/inferred\"^^xsd:string) <http://purl.obolibrary.org/obo/MONDO_0005165
> <http://purl.obolibrary.org/obo/MONDO_0005070>)"

SubClassOf(Annotation(<http://www.geneontology.org/formats/oboInOwl#source> \"Orphanet:34592\"^^xsd:str
ing) <http://purl.obolibrary.org/obo/MONDO_0011476> <http://purl.obolibrary.org/obo/MONDO_0018814>)

**Comment by matentzn** [comment]
These axioms are valid. Basically, you have a normal axiom

```
SubClassOf(http://purl.obolibrary.org/obo/MONDO_0015802 http://purl.obolibrary.org/obo/MONDO_0000509)"
```

Which is furthermore _annotated_ with the following axiom annotations:

```
Annotation(http://www.geneontology.org/formats/oboInOwl#source "MONDO:Redundant"^^xsd:string) Annotation(http://www.geneontology.org/formats/oboInOwl#source "Orphanet:178469"^^xsd:string) 
```

Leading to:

```
SubClassOf(Annotation(http://www.geneontology.org/formats/oboInOwl#source "MONDO:Redundant"^^xsd:string) Annotation(http://www.geneontology.org/formats/oboInOwl#source "Orphanet:178469"^^xsd:string) http://purl.obolibrary.org/obo/MONDO_0015802 http://purl.obolibrary.org/obo/MONDO_0000509)
```

 Maybe its easier to see whats happening in RDFXML:

```
<owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/MONDO_0002229"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2002/07/owl#equivalentClass"/>
        <owl:annotatedTarget>
            <owl:Class>
                <owl:intersectionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/MONDO_0005626"/>
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0004026"/>
                        <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000992"/>
                    </owl:Restriction>
                </owl:intersectionOf>
            </owl:Class>
        </owl:annotatedTarget>
        <oboInOwl:source rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCIT:C4381</oboInOwl:source>
    </owl:Axiom>
```

You can clearly see here that `<oboInOwl:source rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCIT:C4381</oboInOwl:source>` serves as an axiom annotation on top of the primary `equivalentClass` axiom.

@nicolevasilevsky you can send a link to this ticket to the reporting user! Thank you!
