### ISSUE TITLE
update OMIM xrefs - obsolete OMIM terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5698]
The terms in this [spreadsheet](https://docs.google.com/spreadsheets/d/1mOqRP5VV2Gh1WcX2njC2OhUHVxfY3ZXdE7kvboCmg2A/edit#gid=411661859) are obsolete in Mondo.

These need to be marked as MONDO:equivalentObsolete in Mondo (live class in Mondo and an obsolete class in the source ontology.)

- [ ] @sabrinatoro  please use the unmerge/replace workflow to update these source annotations?
- [x] please add the documentation on this workflow to our editors guide

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
Can you please confirm that the current annotations in the spreadsheet have the OMIM annotation as "MONDO:equivalent"? 

The workflow documentation is here: https://mondo.readthedocs.io/en/latest/editors-guide/bulk-removal/

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
How did you get this list? 
In order to update the annotation, I need to know what the annotations originally are. It looks like many of these annotations are currently "MONDO:ObsoleteEquivalent", and some (~20) are "MONDO:equivalentTo"
TO DO: 
-[ ] get the updated list with the current source
-[ ] update the new source (I think that "MONDO:ObsoleteEquivalent" would have to be changed to MONDO:obsoleteEquivalentObsolete)

**Comment by nicolevasilevsky** [comment]
@sabrinatoro - it is from here:
https://github.com/monarch-initiative/mondo-ingest/pull/108/files#diff-b0d295ecd7d05fde88526ba07223a9bfbc08cc572d5ead04804bd3d49d2741b5

the file is: [src/ontology/reports/omim_mapped_deprecated_terms.robot.template.tsv](https://github.com/monarch-initiative/mondo-ingest/pull/108/files#diff-b0d295ecd7d05fde88526ba07223a9bfbc08cc572d5ead04804bd3d49d2741b5)

**Comment by nicolevasilevsky** [comment]
Just spot checking this, I think the MONDO classes have been obsoleted, as well as the OMIM classes, so I think they need this annotation on the OMIM xref: MONDO:obsoleteEquivalentObsolete

**Comment by sabrinatoro** [comment]
Thank you @nicolevasilevsky 
In order to update the annotations, I still need to know what the current source is. I will do some sparql query (etc) and figure it out.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky : Looking into this more carefully, the situation is much more complicated than expected. For whatever reasons, a lot of these MONDO terms (I check about 10 of them, obsolete or not obsolete) have the OMIM x-ref twice, once with "MONDO:equivalentObsolete", and once with either "MONDO:obsoleteEquivalentObsolete" or "MONDO:equivalentTo".
This is a sign (imo) that there was a problem with the slurp. 

This should be cleaned up:  we need to ensure that there is only 1 same omim id per MONDO term (though I am surprised this wasn't caught up by the QC).
CCing @matentzn and @joeflack4 as it looks very suspicious and they can advice on the best way forward (maybe a new issue in the other tracker?). 

Some screenshots: 
![Screenshot 2022-12-13 at 2 56 06 PM](https://user-images.githubusercontent.com/12737987/207463588-a163f7ea-ca10-4bd4-8e25-c0ed3d9c7f83.png)

![Screenshot 2022-12-13 at 2 53 49 PM](https://user-images.githubusercontent.com/12737987/207463614-25a50b04-f479-4819-98e2-84d141516efc.png)

**Comment by nicolevasilevsky** [comment]
I can help manually review these and clean them up. I think if we run 
```
sh run.sh make NORM
mv NORM mondo-edit.obo
```

it should merge the duplicate xrefs - I will try that. And then I think QC will catch it.

**Comment by nicolevasilevsky** [comment]
hm, no, that didn't do anything....

Aside from manually reviewing these and fixing them, I don't know what else to do.

**Comment by sabrinatoro** [comment]
UPDATE: 
when the OMIM x-ref has more than 1 source, the removal and update of the annotation does not work.
--> need to update manually

**Comment by nicolevasilevsky** [comment]
thanks for doing this @sabrinatoro !
