### ISSUE TITLE
Mondo metabolomics definitions

### ISSUE THREAD

**Issue by jpgourdine** [monarch-initiative/mondo#57]
Hi @cmungall ,
Let me know what are the next steps needed for Mondo in relation to glycomics and metabolimics

**Comment by cmungall** [comment]
let's start more generally with metabolomics [i changed the title of the ticket]

can you look under metabolic disease and find terms missing OWL definitions (3-bar `=` in Protege). Use GO terms if possible. Request new GO terms if not present. Add missing design patterns too

 See also https://github.com/monarch-initiative/mondo-build/tree/master/src/patterns#mechanistic-etiology

**Comment by nicolevasilevsky** [comment]
I can help with this! I am going to go through a few examples, to make sure I understand the workflow, and will also write up some documentation to help JP.

**Comment by nicolevasilevsky** [comment]
@jpgourdine FYI, the GO tracker is here: https://github.com/geneontology/go-ontology/issues

**Comment by nicolevasilevsky** [comment]
@cmungall it doesn't look like all of the GO terms are imported into MONDO, is that correct? 

For MONDO_0009116 lactose intolerance (disease), I think the logical def should be:
'metabolic disease'
 and ('disease caused by disruption of' some GO_0005988)

GO_0005988 is lactose metabolic process

Is there any easy way I can MIREOT in the missing GO term?

(The labels are not displaying for me for the imported terms, just the IDs.)

**Comment by cmungall** [comment]
Pipeline is same as for other ontologies - you can add to the terms.txt 
and use make

**Comment by nicolevasilevsky** [comment]
To clarify, I would add the URI to go_terms.txt in the folder mondo-build/src/ontology/imports?

I am not set up to run the make file. If I add the terms I need, could you run the make file for me? Or are there some instructions on how to set up your computer so I can run the make file?

Thanks!

**Comment by nicolevasilevsky** [comment]
@cmungall I downloaded owltools based on Peter's instructions in the [HPO workbench documentation](http://hpo-workbench.readthedocs.io/en/latest/latest.html#building-owltools).

Is there any documentation about how to run the make file to add terms for GO? 

I no longer see the file go_terms.txt in the MONDO GitHub repo too - was it removed?

**Comment by nicolevasilevsky** [comment]
This request is now obsolete.
