### ISSUE TITLE
[NTR] TUBB2A-related Tubulinopathy

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#5700]
**Preferred term label:**
TUBB2A-related Tubulinopathy 

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
A tubulinopathy syndrome often associated with microtubule dysfunction, malformations of the corpus callosum, enlarged ventricles, dysgyria, abnormal basal ganglia, cerebellar vermis hypoplasia/dysplasia, and decreased white matter, due to heterozygous variants in TUBB2A. Individuals may present with variable combinations of malformations of the corpus callosum, enlarged ventricles, dysgyria, abnormal basal ganglia, cerebellar vermis hypoplasia/dysplasia, and decreased white matter. Epilepsy, speech impairment, and motor impairment are also frequent features. 

*** Also, please update the definition of tubulinopathy to be:
A nervous system disorder characterized by complex cortical malformations including in most cases dysmorphic basal ganglia and/or corpus callosum in which the cause of the disease is a variation in a tubulin gene. 
- Please let me know if I should make an additional ticket for this change. 

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
 “tubulinopathy” and “complex neurodevelopmental discord with motor features”

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
Intellectual Disability and Autism ClinGen GCEP 
https://clinicalgenome.org/affiliation/40006/ 

@ErinRiggs

**Comment by maglott** [comment]
What if there is homozygosity for variants in TUBB2A in an individual with Tubulinopathy?  Is heterozygosity required?

**Comment by icordovaG** [comment]
As of now, there are no reported cases of biallelic patients.
Thanks for checking.

From: maglott ***@***.***>
Sent: Thursday, December 1, 2022 2:34 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Cordova, Ineke ***@***.***>; Author ***@***.***>
Subject: [External] Re: [monarch-initiative/mondo] [NTR] (Issue #5700)

External: Be careful with links and files. If suspicious, alert the Information Security Office. Questions? Call 570-271-8092


What if there is homozygosity for variants in TUBB2A in an individual with Tubulinopathy? Is heterozygosity required?

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmonarch-initiative%2Fmondo%2Fissues%2F5700%23issuecomment-1334475066&data=05%7C01%7Cicordova%40geisinger.edu%7C985fe785137b4d4d421508dad3e3bcb7%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C638055272319642938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EHU4CQt2H6hICedpmXoHRU088qJKYqvpQmbbye7tyIk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3GNW3OPOUET4JYYAVDCCBLWLEKT5ANCNFSM6AAAAAASRFTFGQ&data=05%7C01%7Cicordova%40geisinger.edu%7C985fe785137b4d4d421508dad3e3bcb7%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C638055272319642938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7gGBsKsy2cYL%2B36kHFE43ljw0FJZ0PFrEgWbiZIdF2U%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>


IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you. Geisinger Health System utilizes an encryption process to safeguard Protected Health Information and other confidential data contained in external e-mail messages. If email is encrypted, the recipient will receive an e-mail instructing them to sign on to the Geisinger Health System Secure E-mail Message Center to retrieve the encrypted e-mail.

**Comment by sabrinatoro** [comment]
Note for the record: 
the new suggested definition is more general than the existing one, therefore, we can safely update the definition without compromising the correctness of potentially existing annotations.
