### ISSUE TITLE
Obsoletion TSV Release file has links to non-mondo sites?

### ISSUE THREAD

**Issue by larrybabb** [monarch-initiative/mondo#5713]
The mondo_obsoletioncandidates.tsv file that is provided with each release has 5 columns: `mondo_id, label, comment, issue, obsoletion_date`.  For the most part the "issue" column provides a link to the mondo github issue that is the source for the reason for obsoletion. However sometimes, a NIH rarediseases.info site is referenced. 

It would be very helpful if the `issue` value was always the MONDO issue that was the source behind the obsoletion.  For example in the Dec 01.2022 release the record

```
mondo_id | label | comment | issue | obsoletion_date
MONDO:0008952 | cerebrofaciothoracic dysplasia | This will be obsoleted in the 2023-02-01   release. The term ... | https://rarediseases.info.nih.gov/diseases/1210/cerebro-facio-thoracic-dysplasia | 2/1/23
```

Seems to have been produced from the mondo issue [#5619](https://github.com/monarch-initiative/mondo/issues/5619). It seems like it would be more consistent and logical to provide the mondo issue link under the `issue` column.

Is this intentional or a bug?  If it is a bug, can we get an estimate on when it might be corrected.

**Comment by matentzn** [comment]
Thanks for reporting this @larrybabb - this was a consequence of a move to use a different annotation property during curation, and failure to update our reporting pipeline, which is all done in #5715, including QC to guard against future mistakes.
