### ISSUE TITLE
MONDO:0800129 autoinflammatory disease, X-linked

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5717]
**Mondo term (ID Label)**
MONDO:0800129 autoinflammatory disease, X-linked

**Bug/Typo/Error description**
[has exact synonym](https://www.ebi.ac.uk/ols/search?q=has_exact_synonym&exact=true&type=property&ontology=mondo)
NEMO deleted exon 5 syndrome|autoinflammatory syndrome, X-linked

Why is there a | in the middle of this exact synonym? 
Based on this PubMed article (cited by OMIM) https://pubmed.ncbi.nlm.nih.gov/35289316/ the suggested name by those authors is 
"NEMO deleted exon 5 autoinflammatory syndrome" or "NDAS"  

Would it be possible to avoid using | in Mondo's character strings for names? We report the Mondo exact Syns on MedGen in our downloads and use the | as our delimiter in the downloaded tables, so this row in our data ends up with an extra column.
If Mondo has good reason to keep this, we can work around it, but figured I would ask before asking our devs to fix this overall in the data flow.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by adrianamalheiro** [comment]
It would also be helpful to us to know when (or if) this issue will be resolved so we can better prepare to process your next release. Thanks.

**Comment by nicolevasilevsky** [comment]
@kanems this is a typo, we'll fix it.

@adrianamalheiro we should be able to get to this soon and the changes will be visible in the January release (which is planned for Jan 03).

**Comment by adrianamalheiro** [comment]
Appreciate the solution and the update @nicolevasilevsky !
