### ISSUE TITLE
MONDO:0030711 anemia, congenital dyserythropoietic, IIA IIIB, autosomal recessive

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5718]
**Mondo term (ID and Label):**
MONDO:0030711 anemia, congenital dyserythropoietic, IIA IIIB, autosomal recessive

**Suggested new label:**
Anemia, congenital dyserythropoietic, type IIIb, autosomal recessive (to align with OMIM's preferred name)

OMIM does not call this IIA and Mondo has 0 other sources for this term; what is the rationale behind the IIA component of the name? I do not see this in OrphaNet or OMIM. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**

**Comment by nicolevasilevsky** [comment]
The label and synonym were attributed to OMIM, so maybe they either previously used that name, or it was added as a mistake. I relabeled the term and marked the synonyms as historic and discouraged/
