### ISSUE TITLE
revisit issues 4549 and OMIM:137215  and Orphanet:26106

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#5720]
OMIM:137215 is now defined as DIFFUSE GASTRIC AND LOBULAR BREAST CANCER SYNDROME; DGLBC, based on the gene CDH1.

A submitter to ClinVar wants to represent the relationship between Hereditary diffuse gastric cancer (e.g. Orphanet:26106) and CTNNA1 but does not want to use OMIM 137215 because that is now specific to CDH1. 

MONDO:0007648 seems to mix a generic record (Orphanet's)  with the syndrome defined by CDH1.
Should there be 2 records?
1. Hereditary diffuse gastric cancer/Orphanet:26106
2. DIFFUSE GASTRIC AND LOBULAR BREAST CANCER SYNDROME/OMIM 137215  (CDH1)

I'll leave it to the cancer experts to decide whether NCIT:C43295 (adenocarcinoma) should be equated with gastric cancer (non-specified)

**Comment by nicolevasilevsky** [comment]
Thanks @maglott. I agree with your suggestions. 

I will remove the xref to OMIM:137215  on MONDO:0007648 'hereditary diffuse gastric adenocarcinoma', as this seems like the more generic version of this disease (I will keep the xrefs to Orphanet:26106 and NCIT:C43295 - both of these ontologies use cancer and adenocarcinoma as synonyms).

I will make OMIM:137215 equivalent to CDH1-Related Diffuse Gastric and Lobular Breast Cancer

**Comment by nicolevasilevsky** [comment]
I will make 'diffuse gastric and lobular breast cancer syndrome with or without cleft lip and/or palate' a new class, since it is an 'included' entry on the OMIM record.

related to [#5612 ](https://github.com/monarch-initiative/mondo/issues/5507)
