### ISSUE TITLE
remove over-classification under diabetes mellitus

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#5723]
There are a lot of terms classified under here, these originally came from ORDO "other rare diabetes mellitus". When we obsoleted this, everything was rewired to DM, when it should have instead been reviewed

I propose to change these in bulk to a different relationship. I can do this via KGCL

**Comment by nicolevasilevsky** [comment]
just delete the incorrect superclass assertions, don't need to worry about excluding superclasses

**Comment by nicolevasilevsky** [comment]
discussed with Nico - probably fastest to just replace is_a text with relationship: excluded_subClassOf in text file
