### ISSUE TITLE
[NTR] Microcephaly with intellectual disability 

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#5725]
**Preferred term label:**
Microcephaly with intellectual disability 

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**

Microcephaly with Neurodevelopmental Phenotypes is a condition characterized by both microcephaly and atypical neurodevelopment, without other commonly reported non-brain related phenotypes. 

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
microcephaly

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
Microcephaly 1, primary, autosomal recessive - needs to be moved out of it's current location as a (grand)child of "isolated microcephaly

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
Intellectual Disability and Autism GCEP 
https://clinicalgenome.org/affiliation/40006/

@ErinRiggs

**Comment by nicolevasilevsky** [comment]
@icordovaG is 'Microcephaly 1, primary, autosomal recessive' not an 'isolated congenital microcephaly'?



<img width="362" alt="image" src="https://user-images.githubusercontent.com/6722114/207422286-69a2259e-26f7-4419-b71d-b88c71023d87.png">

**Comment by icordovaG** [comment]
I do not believe so

From: Nicole Vasilevsky ***@***.***>
Sent: Tuesday, December 13, 2022 12:11 PM
To: monarch-initiative/mondo ***@***.***>
Cc: Cordova, Ineke ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [monarch-initiative/mondo] [NTR] Microcephaly with intellectual disability (Issue #5725)

External: Be careful with links and files. If suspicious, alert the Information Security Office. Questions? Call 570-271-8092


@icordovaG<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FicordovaG&data=05%7C01%7Cicordova%40geisinger.edu%7C858070ad67094f6187d108dadd3db477%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C638065554348757562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ynucu%2F%2BrbF5%2BftzzKAmVs5kHqz19oAygz03LaQJR3ak%3D&reserved=0> is 'Microcephaly 1, primary, autosomal recessive' not an 'isolated congenital microcephaly'?

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6722114%2F207422286-69a2259e-26f7-4419-b71d-b88c71023d87.png&data=05%7C01%7Cicordova%40geisinger.edu%7C858070ad67094f6187d108dadd3db477%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C638065554348757562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z1kuO0Q2dlwTfI6%2FoFEd3equrnfsWkiupZyZCnnvFEU%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmonarch-initiative%2Fmondo%2Fissues%2F5725%23issuecomment-1349540946&data=05%7C01%7Cicordova%40geisinger.edu%7C858070ad67094f6187d108dadd3db477%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C638065554348757562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zAPP7hqF6BGw8Roiwc05iGK8lE2b0rFGQkYdTGdlpg4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3GNW3LWQ7ZUTA47TQQONCLWNDC2NANCNFSM6AAAAAAS4DE7WA&data=05%7C01%7Cicordova%40geisinger.edu%7C858070ad67094f6187d108dadd3db477%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C638065554348757562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9l%2Fpl0LMc%2BFxC5NklhviWK5PtgfGGOlZCWqkMMP0guw%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>


IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you. Geisinger Health System utilizes an encryption process to safeguard Protected Health Information and other confidential data contained in external e-mail messages. If email is encrypted, the recipient will receive an e-mail instructing them to sign on to the Geisinger Health System Secure E-mail Message Center to retrieve the encrypted e-mail.

**Comment by nicolevasilevsky** [comment]
Hi @icordovaG - reviewing this, it seems like 'microcephaly 1, primary, autosomal recessive' is appropriately classified as a subclass of 'autosomal recessive primary microcephaly', which is a subclass of 'isolated congenital microcephaly'. A synonym of 'isolated congenital microcephaly' is primary microcephaly and the definition seems consistent with the description of  'microcephaly 1, primary, autosomal recessive' on the OMIM page: https://omim.org/entry/251200

I am inclined to leave it as is. Please feel free to reopn this ticket if you disagree.
Thanks!
Nicole

**Comment by icordovaG** [comment]
Hi @nicolevasilevsky, is it possible to add Microcephaly 1, AR as a child of both this new term as well as keep it under AR primary microcephaly?

**Comment by nicolevasilevsky** [comment]
sure thing! I added this, it will be available in the next release in early April
