### ISSUE TITLE
[NTR] infantile-onset epilepsy

### ISSUE THREAD

**Issue by ARosselClinGen** [monarch-initiative/mondo#5740]
**Preferred term label:** infantile-onset epilepsy

**Synonyms** None requested at this time

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)** Epilepsy starting in the first 12 months of life, including self-limiting and refractory seizures, and epilepsies with and without developmental disorders.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)** Epilepsy (MONDO:0005027)

**Children terms (if applicable)** I believe MONDO:0100023, MONDO:0100024, MONDO:0019486 (and its child terms) can be switched over to child terms of this new term, rather than neonatal/infantile epilepsy syndromes. The Epilepsy Gene Curation Expert Panel wants to be cognizant of the difference between syndromic and non-syndromic disease terms, and these terms do not appear to necessitate syndromic presentation. 

**Your nano-attribution (ORCID)** Requested on behalf of ClinGen's Epilepsy Gene Curation Expert Panel.

CC" @ErinRiggs

**Comment by nicolevasilevsky** [comment]
@ARosselClinGen, just to confirm, this is different from MONDO:0020071 'infantile epilepsy syndrome'?

This is defined as: An epilepsy syndrome that occurs between 28 days to one year of life.

There is a comment that says:
This type of grouping class represents an older way of classifying diseases and represented here https://www.epilepsydiagnosis.org/index.html.

**Comment by ARosselClinGen** [comment]
@nicolevasilevsky Thanks for checking in! The GCEP reviewed the various existing syndromic epilepsy terms and did not feel that they were an appropriate label for one of the genes we are currently curating, as there is no evidence supporting a syndromic presentation. So this term is different in a rather small semantic way that the group finds important. :)
