### ISSUE TITLE
Remove OBA from list of imports and ensure "disease_has_feature" not used in conjunction with attributes

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#5755]
There is only one axiom, and that does not make sense:

```
[Term]
id: MONDO:0000250
....
relationship: disease_has_feature OBA:1001084 ! feces osmolality
```

A feature should be a phenotype, not an associated trait/attribute. For that, if necessary, we should coin a different relation, like "disease_affects_trait" or some such.

**Comment by nicolevasilevsky** [comment]
Add new HPO class
HP:0032485
