### ISSUE TITLE
CSGALNACT1-CDG

### ISSUE THREAD

**Issue by jpgourdine** [monarch-initiative/mondo#576]
For new term requests, please provide the following information:

## Preferred term label

CSGALNACT1-CDG

## Synonyms

CSGALNACT1 deficiency, Desbuquois dysplasia with CSGALNACT1 mutation

## Textual definition

Mild skeletal dysplasia with joint laxity and the radiological features of Desbuquois dysplasia due to a loss‐of‐function mutation in Chondroitin Sulfate N‐acetylgalactosaminyltransferase‐1  (CSGALNACT1)
PMID: 27599773
## Suggested parent term

http://purl.obolibrary.org/obo/MONDO_0015426 

## Attribution

http://orcid.org/0000-0001-9969-8610

**Comment by nicolevasilevsky** [comment]
@jpgourdine 
is this a duplicate with #474?

**Comment by jpgourdine** [comment]
Just realizing that, yes it is.
