### ISSUE TITLE
Change in disease nomenclature for MONDO:0011581

### ISSUE THREAD

**Issue by courtneythaxton** [monarch-initiative/mondo#577]
The ClinGen Cardiovascular Dilated Cardiomyopathy Gene Curation Expert Panel recommends a change in the disease nomenclature from MONDO:0011581 from dilated cardiomyopathy with woolly hair and keratoderma **to:** 

**_Arrhythmogenic cardiomyopathy with woolly hair and keratoderma_**

In reviewing the literature and the ClinGen lumping and splitting guidelines, the group of experts recognized that the heart phenotype extends beyond dilated cardiomyopathy. From the disease assertions represented on OMIM, we have lumped MIM 607450 ([MONDO:0011831](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0011831)), MIM 605676 ([MONDO:0011581](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0011581)), MIM 615821 ([MONDO:0014355](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0014355)), and MIM 612908 ([MONDO:0013034](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0013034)) under this term. 

**Note, the MIM 605676 ([MONDO:0011581](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0011581)) is the parent term that is requested for the nomenclature change. The remaining disease entities would be children terms under MONDO:0011581) **

## Synonyms

dilated cardiomyopathy with woolly hair and keratoderma
Carvajal Syndrome

## Textual Definition

Desmoplakin is encoded by the DSP gene and is a member of the plakin family of cell adhesion molecules that are responsible for the formation and maintenance of desmosomes (PMID:23911551). Variation in DSP is associated with cardiomyopathic manifestations that include: (1) seemingly isolated arrhythmogenic right ventricular cardiomyopathy (ARVC) that is atypical and can show left ventricle dominance, or be present in the left and right ventricle simultaneously; and (2) dilated cardiomyopathy. Cutaneous phenotypes including woolly hair and/or keratoderma can present along with the cardiomyopathy, but are noted as less penetrant features. 

## Attribution

Please attribute this change with the ClinGen Cardiovascular Dilated Cardiomyopathy Gene Curation Expert Panel 

@nicolevasilevsky @cmungall @pnrobinson @ahamosh @Orphanet

**Comment by ahamosh** [comment]
We at OMIM are reviewing this information and additional papers.  We think at a minimum cardio-ectodermal (rather than cardio-cutaneous) should be considered, as these patients have skin, hair, and teeth problems.

**Comment by courtneythaxton** [comment]
Hi All, 

Just to bring this back around, I wanted to know where we could move on this disease nomenclature. 

@ahamosh, are you suggesting the use of cardio-ectodermal be used in place of the proposed "Arrhythmogenic cardiomyopathy with woolly hair and keratoderma" outlined above?

Or rather, you are okay with thhe terminology change of "Arrhythmogenic cardiomyopathy with woolly hair and keratoderma" and that you would rather have the suggested parent term of "cardiocutaneous syndrome" be "cardio-ectodermal".

Thank you,
@courtneythaxton 

@nicolevasilevsky @cmungall @pnrobinson @ahamosh @Orphanet

**Comment by ahamosh** [comment]
Hi All,

So sorry that I keep dropping this.  I think that this should be cardio-ectodermal because it is hair and skin and not just skin.

Thanks,

Ada


Ada Hamosh, MD, MPH
Dr. Frank V. Sutland Professor
McKusick-Nathans Institute of Genetic Medicine (IGM)
Clinical Director, IGM
Scientific Director, OMIM
Johns Hopkins University
Blalock 1007
600 N. Wolfe St
Baltimore, MD 21287-4922
Phone:  410-614-3313
Fax: 410-614-9246
ahamosh@jhmi.edu

Assistant:  Heather Dozier
phone:  410-955-6641
e-mail:  hdozier1@jhmi.edu

________________________________

**Comment by courtneythaxton** [comment]
Hi All, 

The ClinGen ARVC GCEP is finalizing their gene curations and is in need of this pending disease entity nomenclature change. WE would dike to change the current disease nomenclature for MONDO:0011581 to "Arrhythmogenic cardiomyopathy with woolly hair and keratoderma".

In addition, we would like to add a new parent term of Cardioectodermal syndrome, as per ticket request 578 ([ticket#578](https://github.com/monarch-initiative/mondo/issues/578)).

If this could be done soon, by the end of July 31, we would greatly appreciate it. 

Thanks,
@courtneythaxton 

@mellybelly @cmungall @nicolevasilevsky @pnrobinson @ahamosh @Orphanet

**Comment by nicolevasilevsky** [comment]
@courtneythaxton I relabeled MONDO:0011581 to Arrhythmogenic cardiomyopathy with woolly hair and keratoderma. Pending PR

**Comment by nicolevasilevsky** [comment]
To clarify, you would like to request the new term
**Label:** Cardio-ectodermal** syndrome
Could you please suggest the parent class and a text definition with a source?

I will create this class and add these terms as children:
(1) MONDO:0011581
(2) MONDO:0012506 (arrhythmogenic right ventricular dysplasia 11) covering the gene DSC2
(3) MONDO:0011017 (Naxos disease) covering the gene JUP

Thanks!

**Comment by courtneythaxton** [comment]
Hi @nicolevasilevsky 

Yes! According to the original ticket for this new term (ticket#578[https://github.com/monarch-initiative/mondo/issues/578](url). we had the following information:

##Suggested parent term

This disease ontology class would come as an intermediate node under the parent node "Syndromic disease (MONDO:0002254" as we discussed in the MonDO workshop in November.

##Suggested child terms
The child terms to fall under this new term would be the following:
(1) MONDO:0011581 (Ticket 577, renamed to Arrhythmogenic cardiomyopathy with woolly hair and keratoderma) covering the gene DSP

(2) MONDO:0012506 (arrhythmogenic right ventricular dysplasia 11) covering the gene DSC2

(3) MONDO:0011017 (Naxos disease) covering the gene JUP

More gene may potentially fall under this new terminology.

##Textual definition

Cardioectodermal syndromes are those in which phenotypic manifestations occur in the heart, skin, and/or hair (PMID: 27933191). Variation in the genes of interest may occur in both an autosomal dominant inheritance pattern, or in an autosomal recessive inheritance pattern which may result in an  earlier and/or more severe phenotypic presentation.

**Comment by nicolevasilevsky** [comment]
Ah, thanks! I'll add this now!
