### ISSUE TITLE
MONDO:0800318	Emery-dDeifuss muscular dystrophy 6, x-linked

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5771]
**Mondo term (ID Label)**
MONDO:0800318	Emery-dDeifuss muscular dystrophy 6, x-linked

**Bug/Typo/Error description**
_Emery-dDeifuss_ muscular dystrophy 6, x-linked
should this be
Emery-_Dreifuss_ ?

**Your nano-attribution (ORCID)**

**Comment by maglott** [comment]
And with X capitalized?

**Comment by kanems** [comment]
I just noticed there is still a typo in this name:
"Emery-**Deifuss** muscular dystrophy 6, X-linked" should be 
"Emery-**Dreifuss** muscular dystrophy 6, X-linked"

**Comment by nicolevasilevsky** [comment]
thank @kanems, I fixed this!
