### ISSUE TITLE
Creation of a new disease ontology class: Cardiocutaneous syndrome

### ISSUE THREAD

**Issue by courtneythaxton** [monarch-initiative/mondo#578]
The ClinGen Cardiovascular Dilated Cardiomyopathy Gene Curation Expert Panel would like to request the creation of a new disease ontology class: **Cardiocutaneous syndrome**

These disease entities are syndromic in nature and involve the heart, skin, and hair. 

## Suggested parent term

This disease ontology class would come as an intermediate node under the parent node "Syndromic disease (MONDO:0002254" _**as we discussed in the MonDO workshop in November.**_

##Suggested child terms
The child terms to fall under this new term would be the following:
(1) MONDO:0011581 ([Ticket 577](https://github.com/monarch-initiative/mondo/issues/577), renamed to Arrhythmogenic cardiomyopathy with woolly hair and keratoderma) **covering the gene DSP**

(2) MONDO:0012506 (arrhythmogenic right ventricular dysplasia 11) **covering the gene DSC2**

(3) MONDO:0011017 (Naxos disease) **covering the gene JUP**

More gene may potentially fall under this new terminology.

## Textual definition
Cardiocutaneous syndromes are those in which phenotypic manifestations occur in the heart, skin, and/or hair (PMID: 27933191).  Variation in the genes of interest may occur in both an autosomal dominant inheritance pattern and autosomal recessive, which may lead to earlier and/or more severe phenotypic presentation. 

## Synonyms

 **Of note, I would really appreciate input from @ahamosh @pnrobinson @Orphanet on the creation of this term and what should be considered to be part of this. Thank you.**

@nicolevasilevsky @cmungall @mellybelly

**Comment by courtneythaxton** [comment]
Hi all,

I"m bringing this back up to the top of the email chain hopefully. I know @ahamosh was considering the cardioectadermal syndrome to include the tooth agenesis that could be part of the spectrum.

what do you all feel about either of these terms?
@pnrobinson @Orphanet 

@cmungall @nicolevasilevsky @mellybelly

**Comment by nicolevasilevsky** [comment]
@cmungall I can add this new term and hierarchy, if it looks okay to you

**Comment by cmungall** [comment]
yes thanks!

**Comment by nicolevasilevsky** [comment]
I added the new term MONDO_0100071 'cardiocutaneous syndrome' (pending pull request).

Do we want to add 'cardioectadermal syndrome' as well? @ahamosh?

**Comment by courtneythaxton** [comment]
Please see comment on [ticket 577.](https://github.com/monarch-initiative/mondo/issues/577) We agree with Ada hams and will go with the disease nomenclature of Cardio-ectodermal syndrome, and would like to include the following orphan terms under this new branch:
The child terms to fall under this new term would be the following:
(1) MONDO:0011581 (Ticket 577, renamed to Arrhythmogenic cardiomyopathy with woolly hair and keratoderma) covering the gene DSP

(2) MONDO:0012506 (arrhythmogenic right ventricular dysplasia 11) covering the gene DSC2

(3) MONDO:0011017 (Naxos disease) covering the gene JUP

Thanks,
@courtneythaxton 

@mellybelly @cmungall @nicolevasilevsky @ahamosh @pnrobinson @Orphanet

**Comment by nicolevasilevsky** [comment]
I think this ticket can be closed, the action items have been moved over to #577

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet please see this ticket and related ticket #577 regarding the new term: MONDO_0100080 cardioectodermal syndrome
