### ISSUE TITLE
Malformed reference in MONDO:0000890

### ISSUE THREAD

**Issue by jsstevenson** [monarch-initiative/mondo#5780]
**Mondo term (ID Label)**

MONDO:0000890

Zika virus congenital syndrome

**Bug/Typo/Error description**

This is sort of a combination of a typo and an xref issue, but the reference to `MESH:MESH:1622152` seems erroneous (duplicated namespace, and also [doesn't appear to be a valid reference otherwise](https://www.ncbi.nlm.nih.gov/mesh/?term=1622152)). I don't typically see MeSH LUIs without a leading alphabetic character -- maybe this was supposed to be from a different source? 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

https://orcid.org/0000-0002-2568-6163

**Comment by sabrinatoro** [comment]
Thank you for reporting this typo, @jsstevenson

**Comment by jsstevenson** [comment]
Thanks for the quick turnaround! However, unless I'm missing something (which I probably am), I don't know if removing the extra "MESH:" prefix is enough to fix this -- `1622152` doesn't match expected LUI patterns for MeSH concepts (see eg https://bioregistry.io/registry/mesh, I believe MeSH IDs have to start with a `C` or `D`) and I haven't been able to find a second MeSH record for Zika-related things other than the existing `MESH:D000071243` xref (definitely nothing under basic variations of `1622152`).

**Comment by sabrinatoro** [comment]
Thank you @jsstevenson. 
When doing more research, I couldn't find an entry in MESH for Zika congenital syndrome (they have only a related disease "Zika Virus Infection")
I suspect there was originally an entry (maybe with a temporary id?) that was removed and included in "Zika Virus Infection".  
I think this MESH x-ref should be removed (ie made "obsolete at the source" - assuming it was at the source at one point). 
@nicolevasilevsky any additional thoughts? is it possible that there was some id with this pattern? (and therefore is it correct to say "obsolete at the source"?

**Comment by nicolevasilevsky** [comment]
yes, use MONDO:equivalentObsolete
