### ISSUE TITLE
**MONDO:0015924 pulmonary arterial hypertension**

### ISSUE THREAD

**Issue by carriewelch** [monarch-initiative/mondo#5781]
**Mondo term (ID and Label)**

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@carriewelch do you have a specific request regarding this term? The comment field above is blank. Thanks!

**Comment by carriewelch** [comment]
This is a ClinGen request from the PH GCEP. The definition should include mean pulmonary artery pressure >20 mmHg (PMID:30545973) and include the subclass "PAH with overt features of venous/capillaries involvement (PVOD/PCH)" (PMID:30545973).

**Comment by nicolevasilevsky** [comment]
Thanks @carriewelch. We'll revise this before the next release in early February.

**Comment by nicolevasilevsky** [comment]
Hi @carriewelch looking at this more closely, we need additional information. We'll probably have to push this back to the March release.

Could you please:
1) provide a definition for MONDO:0015924 pulmonary arterial hypertension

the current definition is:

Pulmonary arterial hypertension (PAH) is a group of diseases characterized by elevated pulmonary arterial resistance leading to right heart failure. PAH is progressive and potentially fatal. PAH may be idiopathic and/ or familial, or induced by drug or toxin (drug-or toxin-induced PAH) or associated with other diseases like congenital heart disease, connective tissue disease, HIV, schistosomiasis, portal hypertension (PAH associated with other disease).

could you let us know how you would prefer it to read?

2) Could you please provide a text definition for the new term you requested, PAH with overt features of venous/capillaries involvement ?

Thanks!

**Comment by carriewelch** [comment]
Nicole,
Thanks for following up on this. See suggested edits below.
Carrie

From: Nicole Vasilevsky ***@***.***>
Date: Tuesday, January 24, 2023 at 6:17 PM
To: monarch-initiative/mondo ***@***.***>
Cc: carriewelch ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] **MONDOO:0015924 pulmonary arterial hypertension** (Issue #5781)

Hi @carriewelch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarriewelch&data=05%7C01%7Ccbw13%40cumc.columbia.edu%7Cee9671da27594332f52608dafe6126f0%7Cb0002a9b0017404d97dc3d3bab09be81%7C0%7C0%7C638101990475387272%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fv2k1K0RJcD%2BlfBXor4ubEWxV2wi%2F3b%2BhH4z89%2BdktY%3D&reserved=0> looking at this more closely, we need additional information. We'll probably have to push this back to the March release.

Could you please:

  1.  provide a definition for MONDO:0015924 pulmonary arterial hypertension

the current definition is:

Pulmonary arterial hypertension (PAH) is a group of diseases characterized by mean pulmonary artery pressure >20 mmHg (PMID:30545973) and elevated pulmonary arterial resistance leading to right heart failure. PAH is progressive and potentially fatal. PAH may be idiopathic and/ or familial, have overt features of venous/capillary involvement (pulmonary veno-occlusive disease, PVOD/pulmonary capillary hemangiomatosis, PCH) (PMID:30545973), induced by drug or toxin (drug-or toxin-induced PAH), or associated with other diseases like congenital heart disease, connective tissue disease, HIV, schistosomiasis, portal hypertension (PAH associated with other disease).

could you let us know how you would prefer it to read?

  1.  Could you please provide a text definition for the new term you requested, PAH with overt features of venous/capillaries involvement ?

Thanks!

**Comment by nicolevasilevsky** [comment]
Hi @carriewelch I don't see  your responses to the questions. Could you please paste them in as a comment on GitHub?

Thank you!
Nicole

**Comment by carriewelch** [comment]
Nicole - Here is a suggested edit, new text highlighted in bold.
Carrie

Pulmonary arterial hypertension (PAH) is a group of diseases characterized by **mean pulmonary artery pressure >20 mmHg (PMID:30545973)** and elevated pulmonary arterial resistance leading to right heart failure. PAH is progressive and potentially fatal. PAH may be idiopathic and/ or familial, **have overt features of venous/capillary involvement (pulmonary veno-occlusive disease, PVOD/pulmonary capillary hemangiomatosis, PCH) (PMID:30545973)**, induced by drug or toxin (drug-or toxin-induced PAH), or associated with other diseases like congenital heart disease, connective tissue disease, HIV, schistosomiasis, portal hypertension (PAH associated with other disease).

**Comment by carriewelch** [comment]
Nicole,
I just posted my response on GitHub.
Carrie

From: Nicole Vasilevsky ***@***.***>
Date: Wednesday, January 25, 2023 at 10:48 AM
To: monarch-initiative/mondo ***@***.***>
Cc: carriewelch ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] **MONDOO:0015924 pulmonary arterial hypertension** (Issue #5781)

Hi @carriewelch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarriewelch&data=05%7C01%7Ccbw13%40cumc.columbia.edu%7C187b6ff544494da3a50608dafeeb8c93%7Cb0002a9b0017404d97dc3d3bab09be81%7C0%7C0%7C638102584897470414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LSHUX%2FfOX0lDzhfSbrXuJbsR%2B7ZlHm3HdAep7s1Jmmk%3D&reserved=0> I don't see your responses to the questions. Could you please paste them in as a comment on GitHub?

Thank you!
Nicole

**Comment by nicolevasilevsky** [comment]
perfect, thank you!

Lastly, could you please provide a text definition for the new term you requested, PAH with overt features of venous/capillaries involvement ?

**Comment by carriewelch** [comment]
Nicolle,
I attempted to do that with spelling out the diseases (in the parentheses). Is there something else wanted?

Also, I think it should be “venous/capillary involvement” rather than “venous/capillaries involvement.” I forgot to correct my text earlier.
Carrie

From: Nicole Vasilevsky ***@***.***>
Date: Wednesday, January 25, 2023 at 10:57 AM
To: monarch-initiative/mondo ***@***.***>
Cc: carriewelch ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] **MONDOO:0015924 pulmonary arterial hypertension** (Issue #5781)

perfect, thank you!

Lastly, could you please provide a text definition for the new term you requested, PAH with overt features of venous/capillaries involvement ?

**Comment by carriewelch** [comment]
Thanks!
Carrie

From: Nicole Vasilevsky ***@***.***>
Date: Wednesday, January 25, 2023 at 11:04 AM
To: monarch-initiative/mondo ***@***.***>
Cc: carriewelch ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] **MONDOO:0015924 pulmonary arterial hypertension** (Issue #5781)

oh, I see! I missed it.

Thanks, I'll try to get this added before the Feb release

**Comment by nicolevasilevsky** [comment]
@carriewelch 
I revised the def:

name: pulmonary arterial hypertension
def: "A group of diseases characterized by mean pulmonary artery pressure >20 mmHg and elevated pulmonary arterial resistance leading to right heart failure. PAH is progressive and potentially fatal. PAH may be idiopathic and/ or familial, or induced by drug or toxin (drug-or toxin-induced PAH) or associated with other diseases like congenital heart disease, connective tissue disease, HIV, schistosomiasis, portal hypertension (PAH associated with other disease)."

I added the new term:
id: MONDO:0100217
name: pulmonary arterial hypertension with overt features of venous/capillaries involvement
def: "PAH with overt features of venous/capillary involvement (pulmonary veno-occlusive disease, PVOD/pulmonary capillary hemangiomatosis, PCH)." [PMID:30545973]

Please let me know if you'd like further changes

**Comment by carriewelch** [comment]
Nicole,
I’m not sure I understand – I thought “PAH with overt features of venous/capillary involvement” was going to be part of the PAH definition, not a separate entity?

Pulmonary arterial hypertension (PAH) is a group of diseases characterized by mean pulmonary artery pressure >20 mmHg (PMID:30545973) and elevated pulmonary arterial resistance leading to right heart failure. PAH is progressive and potentially fatal. PAH may be idiopathic and/ or familial, have overt features of venous/capillary involvement (pulmonary veno-occlusive disease, PVOD/pulmonary capillary hemangiomatosis, PCH) (PMID:30545973), induced by drug or toxin (drug-or toxin-induced PAH), or associated with other diseases like congenital heart disease, connective tissue disease, HIV, schistosomiasis, portal hypertension (PAH associated with other disease).

Carrie


From: Nicole Vasilevsky ***@***.***>
Date: Friday, January 27, 2023 at 10:11 AM
To: monarch-initiative/mondo ***@***.***>
Cc: carriewelch ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] **MONDOO:0015924 pulmonary arterial hypertension** (Issue #5781)

@carriewelch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarriewelch&data=05%7C01%7Ccbw13%40cumc.columbia.edu%7C54feca04ae6045bb7f9208db0078b114%7Cb0002a9b0017404d97dc3d3bab09be81%7C0%7C0%7C638104290601452076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7uSnFhIlW2KvSSpiJBpBqAyTa60GXT8VtIJDZvztmt4%3D&reserved=0>
I revised the def:

name: pulmonary arterial hypertension
def: "A group of diseases characterized by mean pulmonary artery pressure >20 mmHg and elevated pulmonary arterial resistance leading to right heart failure. PAH is progressive and potentially fatal. PAH may be idiopathic and/ or familial, or induced by drug or toxin (drug-or toxin-induced PAH) or associated with other diseases like congenital heart disease, connective tissue disease, HIV, schistosomiasis, portal hypertension (PAH associated with other disease)."

I added the new term:
id: MONDO:0100217
name: pulmonary arterial hypertension with overt features of venous/capillaries involvement
def: "PAH with overt features of venous/capillary involvement (pulmonary veno-occlusive disease, PVOD/pulmonary capillary hemangiomatosis, PCH)." [PMID:30545973]

Please let me know if you'd like further changes

**Comment by nicolevasilevsky** [comment]
I misunderstood, I thought you wanted a new subclass. I will revise this! Thanks for getting back to me.

**Comment by nicolevasilevsky** [comment]
@carriewelch just to confirm, I added this definition:


name: pulmonary arterial hypertension
def: "Pulmonary arterial hypertension (PAH) is a group of diseases characterized by mean pulmonary artery pressure >20 mmHg and elevated pulmonary arterial resistance leading to right heart failure. PAH is progressive and potentially fatal. PAH may be idiopathic and/ or familial, have overt features of venous/capillary involvement (pulmonary veno-occlusive disease, PVOD/pulmonary capillary hemangiomatosis, PCH), induced by drug or toxin (drug-or toxin-induced PAH), or associated with other diseases like congenital heart disease, connective tissue disease, HIV, schistosomiasis, portal hypertension (PAH associated with other disease)." [Orphanet:182090, PMID:30545973]

and added synonyms to this class:
synonym: "PAH with overt features of venous/capillaries involvement" NARROW [PMID:30545973]
synonym: "PVOD/PCH" NARROW ABBREVIATION [PMID:30545973]

Above you asked for a subclass (hence I added a new term) but I believe you meant synonyms? Could you please confirm?

Thanks,
Nicole

**Comment by carriewelch** [comment]
Nicole,
This is a bit confusing to me. PVOD/PCH are subclasses of PAH. But so are IPAH, HPAH, drug- or toxin-induced PAH, and PAH associated with other diseases. Since the latter were lumped under the broader term “PAH,” my ClinGen expert panel thought PVOD/PCH should also be lumped. But technically, they are all subclasses not “synonyms” of PAH.

I wasn’t involved in the initial MONDO definition of PAH and I don’t think any of my panel members were either. When it was brought to our attention that the definition of PAH was being edited to include and list IPAH, HPAH, drug- or toxin-induced PAH, and PAH associated with other diseases, we thought it was misleading to leave out PVOD/PCH.

Does this make sense? Do you agree to leave it as your newly edited version which matches what I sent you?

Carrie

From: Nicole Vasilevsky ***@***.***>
Date: Friday, January 27, 2023 at 2:44 PM
To: monarch-initiative/mondo ***@***.***>
Cc: carriewelch ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] **MONDOO:0015924 pulmonary arterial hypertension** (Issue #5781)

I misunderstood, I thought you wanted a new subclass. I will revise this! Thanks for getting back to me.

**Comment by nicolevasilevsky** [comment]
Hi @carriewelch,

I need further clarification. This is what is currently in Mondo:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/6722114/215189422-76285321-4dc7-4e0a-b574-60c982e7c2fa.png">

The subclasses of pulmonary arterial hypertension are:
'drug- or toxin-induced pulmonary arterial hypertension'
'Eisenmenger syndrome'
'idiopathic and/or familial pulmonary arterial hypertension'

Could you spell out the acronyms above; are these terms in Mondo? If so, could you please share the corresponding Mondo ID's? 

The original definition of PAH comes from Orphanet (Orphanet:422).

I need clarification on what the request is in this ticket. I'm happy to have a call if that will help.

Best,

Nicole

**Comment by carriewelch** [comment]
Nicole,
Sorry to be so difficult/dense about this! There should be at least two more subclasses at the same level as
-Eisenmenger syndrome
-drug- and toxin-induced pulmonary arterial hypertension
-idiopathic and/or familial pulmonary arterial hypertension

The additional subclasses are:
-overt features of venous/capillary involvement (pulmonary veno-occlusive disease, PVOD/pulmonary capillary hemangiomatosis, PCH) MONDO:0018554

-secondary to other diseases like congenital heart disease, connective tissue disease, HIV, schistosomiasis, portal hypertension (PAH associated with other disease)

Does this help?
Carrie




From: Nicole Vasilevsky ***@***.***>
Date: Friday, January 27, 2023 at 3:25 PM
To: monarch-initiative/mondo ***@***.***>
Cc: carriewelch ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] **MONDO:0015924 pulmonary arterial hypertension** (Issue #5781)

Hi @carriewelch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarriewelch&data=05%7C01%7Ccbw13%40cumc.columbia.edu%7C6ef549d2b0654ead541908db00a4a78c%7Cb0002a9b0017404d97dc3d3bab09be81%7C0%7C0%7C638104479419673324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=os1PWAUTDroJPCFjycqZIPBXlrFbnlXwQqIMvG7j7PQ%3D&reserved=0>,

I need further clarification. This is what is currently in Mondo:

[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6722114%2F215189422-76285321-4dc7-4e0a-b574-60c982e7c2fa.png&data=05%7C01%7Ccbw13%40cumc.columbia.edu%7C6ef549d2b0654ead541908db00a4a78c%7Cb0002a9b0017404d97dc3d3bab09be81%7C0%7C0%7C638104479419673324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nPiyZoUIlxu8%2BltGOwJuRtaiKlalieK%2BkFt4OpU%2FA00%3D&reserved=0>

The subclasses of pulmonary arterial hypertension are:
'drug- or toxin-induced pulmonary arterial hypertension'
'Eisenmenger syndrome'
'idiopathic and/or familial pulmonary arterial hypertension'

Could you spell out the acronyms above; are these terms in Mondo? If so, could you please share the corresponding Mondo ID's?

The original definition of PAH comes from Orphanet (Orphanet:422).

I need clarification on what the request is in this ticket. I'm happy to have a call if that will help.

Best,

Nicole

**Comment by nicolevasilevsky** [comment]
@carriewelch I need further clarification. This is what we have:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/6722114/215196079-7e4bb360-f506-4f0f-a052-5a99bfcd2b03.png">

Do you want MONDO:0018554 'pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis' to be a subclas of MONDO:0015924 'pulmonary arterial hypertension', like in the picture below?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/6722114/215197145-c159c81e-289c-4c39-b9a3-85082f263a51.png">

You said there are two subclasses that should be added as children but you only listed one MONDO ID above. Do you need a new term? If yes, could you please provide the following information as a list:

- Label
- Definition
- Definition source (like a PMID)
- Your ORCID
- Any synonyms

(in GitHub, you can create a list by hitting return and adding a dash and space in front of each line, or use this button:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/6722114/215198120-f514a8d4-adb9-4c68-9883-65398b4afc56.png">


Thanks!
Nicole

**Comment by carriewelch** [comment]
Yes!
For the 2nd one, I will need to think about how to list the group of other diseases. However, I didn’t add that one to the definition. “PAH associated with other diseases like…” was part of the original updated definition that I was alerted to by ClinGen.
Carrie

From: Nicole Vasilevsky ***@***.***>
Date: Friday, January 27, 2023 at 4:04 PM
To: monarch-initiative/mondo ***@***.***>
Cc: carriewelch ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] **MONDO:0015924 pulmonary arterial hypertension** (Issue #5781)

@carriewelch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarriewelch&data=05%7C01%7Ccbw13%40cumc.columbia.edu%7C55c5d827aa674e1576c808db00aa1620%7Cb0002a9b0017404d97dc3d3bab09be81%7C0%7C0%7C638104502734073266%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z53QxT%2BvY64LmBbL8YxWsPAFvFrDs85SlDQ5j1P6BJA%3D&reserved=0> I need further clarification. This is what we have:

[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6722114%2F215196079-7e4bb360-f506-4f0f-a052-5a99bfcd2b03.png&data=05%7C01%7Ccbw13%40cumc.columbia.edu%7C55c5d827aa674e1576c808db00aa1620%7Cb0002a9b0017404d97dc3d3bab09be81%7C0%7C0%7C638104502734073266%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MkvIeF5JhcChxfaeUaM5pBEVbEv7XRmxJnn%2FGRdIM5o%3D&reserved=0>

Do you want MONDO:0018554 'pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis' to be a subclas of MONDO:0015924 'pulmonary arterial hypertension', like in the picture below?

[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6722114%2F215197145-c159c81e-289c-4c39-b9a3-85082f263a51.png&data=05%7C01%7Ccbw13%40cumc.columbia.edu%7C55c5d827aa674e1576c808db00aa1620%7Cb0002a9b0017404d97dc3d3bab09be81%7C0%7C0%7C638104502734073266%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wsjNVbGn3dtPBxoYa%2ByhF%2B6KQVMgRZ59wyXq%2BtX93z8%3D&reserved=0>

You said there are two subclasses that should be added as children but you only listed one MONDO ID above. Do you need a new term? If yes, could you please provide the following information as a list:

  *   Label
  *   Definition
  *   Definition source (like a PMID)
  *   Your ORCID
  *   Any synonyms

(in GitHub, you can create a list by hitting return and adding a dash and space in front of each line, or use this button:

[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6722114%2F215198120-f514a8d4-adb9-4c68-9883-65398b4afc56.png&data=05%7C01%7Ccbw13%40cumc.columbia.edu%7C55c5d827aa674e1576c808db00aa1620%7Cb0002a9b0017404d97dc3d3bab09be81%7C0%7C0%7C638104502734073266%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fu5kTmreMLCP12iqwhejzA2hVWDMOz6LXLmOfnrh5xg%3D&reserved=0>

Thanks!
Nicole

**Comment by nicolevasilevsky** [comment]
Please clarify, do you want to add a new term to Mondo? Or just reclassify MONDO:0018554 'pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis' to be a subclass of MONDO:0015924 'pulmonary arterial hypertension' ?

Thanks!

**Comment by carriewelch** [comment]
Just reclassify MONDO:0018554 'pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis' to be a subclass of MONDO:0015924 'pulmonary arterial hypertension'

Thanks!
Carrie

From: Nicole Vasilevsky ***@***.***>
Date: Friday, January 27, 2023 at 4:15 PM
To: monarch-initiative/mondo ***@***.***>
Cc: carriewelch ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [monarch-initiative/mondo] **MONDO:0015924 pulmonary arterial hypertension** (Issue #5781)

Please clarify, do you want to add a new term to Mondo? Or just reclassify MONDO:0018554 'pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis' to be a subclass of MONDO:0015924 'pulmonary arterial hypertension' ?

Thanks!

**Comment by nicolevasilevsky** [comment]
You got it! 

This will be available in the next release. Thanks for helping clarify the request. Have a great weekend!
