### ISSUE TITLE
replaced by tag for hepatocellular_carcinoma is just "disease", seems wrong?

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#5783]
MONDO:0004721 is obsolete (replaced by: MONDO:0024477) - skipping annotation for SPBC530.09c / hepatocellular_carcinoma

**Comment by nicolevasilevsky** [comment]
why does it seem wrong, @ValWood? Could you provide more details?

**Comment by ValWood** [comment]
Apologies. I was getting "disease" when I searched this so I misinterpreted the replacement term!
Closing!
