### ISSUE TITLE
MONDO:0009809 multicentric osteolysis, nodulosis, and arthropathy[Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5784]
**Mondo term (ID and Label)**
MONDO:0009809 multicentric osteolysis, nodulosis, and arthropathy

**Suggested revision and reasons**
This looks like it should be a child of 
MONDO:0018298 multicentric osteolysis-nodulosis-arthropathy spectrum
Rather than a sibling.
Also MONDO:0010201 Winchester syndrome seems like it should also be a child of Mondo:0018298 (based on Orphanet 371428 mapping to the 2 MIM numbers associated with these to Mondo IDs.) 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by galyea123** [comment]
Hi Nicole!   I was recently reviewing MONA syndrome too. 

In the 2[023 revision of the Nosology of Skeletal Disorders](https://onlinelibrary.wiley.com/doi/10.1002/ajmg.a.63132) the group 29 (Osteolysis group) of the skeletal disorders include "**Multicentric osteolysis, nodulosis and arthropathy (MONA), MMP2-related**" (which includes Winchester-Torg syndrome and nodulosis-arthropathy-osteolysis syndrome NOS) and "**Multicentric osteolysis, nodulosis and arthropathy (MONA), MMP14-related**" .

As you know, Orphanet list "Winchester syndrome" under the "Multicentric osteolysis, nodulosis and arthropathy spectrum".

We are trying to decide in NORD if we should have one report entitled "Multicentric osteolysis, nodulosis and arthropathy spectrum" that includes the MMP2 related conditions as well as the MMP14-related conditions (Winchester syndrome) or if we will continue having two different reports, one report for “Multicentric Osteolysis Nodulosis and Arthropathy (MONA)”(which is actually the “MMP2-Related Multicentric Osteolysis, Nodulosis, and Arthropathy” with the synonyms: Torg Syndrome, Torg-Winchester Syndrome), and another report for Winchester syndrome (MMP14-Related Multicentric Osteolysis, Nodulosis, and Arthropathy).

Winchester syndrome has the same phenotypic features as MONA, and the only difference is the genetic cause and it can be considered part of the MONA spectrum of diseases. If we continue to have two reports, we can have some wording in both the reports and clarify that they may be part of the MONA spectrum.  As a pro for having the two different reports, by reviewing the medical literature and as per OMIM we found that the Winchester syndrome term is still in use in the medical literature.

Winchester syndrome synonym is “MMP14-Related Multicentric Osteolysis, Nodulosis, and Arthropathy” and it should not include Winchester-Grossman syndrome and  Torg-Winchester syndrome as synonyms as they are listed for MONA.

Thank you!,  Gioconda

**Comment by nicolevasilevsky** [comment]
@galyea123 
- I added the synonym “MMP14-Related Multicentric Osteolysis, Nodulosis, and Arthropathy” to Winchester syndrome
- I removed Winchester-Grossman syndrome and Torg-Winchester syndrome from Winchester syndrome
