### ISSUE TITLE
Replace "Mitchell syndrome" with "ACOX1 Dysregulation"

### ISSUE THREAD

**Issue by Mohan-Shruthi** [monarch-initiative/mondo#5785]
**Mondo term (ID and Label):** MONDO:0030073; Mitchell syndrome

**Suggested new label:** ACOX1 Dysregulation

**Your nano-attribution (ORCID)** https://clinicalgenome.org/affiliation/40049/

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)** The ClinGen peroxisomal disorders expert panel suggested the addition of "ACOX1 Dysregulation" as a synonym to "Mitchell syndrome" via #5083. Upon further discussion, we recommend replacing the label with "ACOX1 Dysregulation".

**Comment by sabrinatoro** [comment]
In accordance to the [Mondo disease naming conventions](https://mondo.monarchinitiative.org/pages/disease-naming/), a "ClinGen preferred" tag was added to the "ACOX1 dysregulation" synonym of MONDO:0030073
