### ISSUE TITLE
Should Orphanet:98301 ! Laminopathy be equivalent to MONDO:0021106

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/mondo#579]
Currently this is in our data but goes uncategorized,
https://scigraph-data.monarchinitiative.org/scigraph/graph/Orphanet:98301
https://github.com/NCATS-Tangerine/kgx/issues/94

**Comment by cmungall** [comment]
Yes, they should be declared equivalent

However, MONDO tracks ORDO which is on a 6 month cycle. 

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_98301

(no results as of today)

This should be in the Feb 2019 ORDO release

Dipper uses the orphanet xml which is updated more frequently.

Perhaps MONDO should track the XML / dipper ttl?

**Comment by nicolevasilevsky** [comment]
fixed
