### ISSUE TITLE
question about MONDO:0009136

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#5794]
I have
pombe NOP10 annotated to 
	Dyskeratosis Congenita, Autosomal Recessive 1	MONDO:0009136

This seems to be correct:
https://www.omim.org/entry/606471#molecularGenetics

but the description is
A dyskeratosis congenita that has material basis in an autosomal recessive mutation of NOLA3 on chromosome 15q14.
Is that correct?

**Comment by ValWood** [comment]
NOP10 https://monarchinitiative.org/gene/HGNC:14378
NOLA3 https://monarchinitiative.org/variant/OMIM:606471.0001#gene

are the same gene but have separate entries in Monarch?

**Comment by ValWood** [comment]
Should proba bly move to the Monarch helpdesk?

**Comment by nicolevasilevsky** [comment]
yes, if the question is about the genes in Monarch, please add this ticket to the Monarch helpdesk. I will close this here.

**Comment by ValWood** [comment]
Note,  you can transfer tickets between trackers using 'transfer issue' which should display at the bottom right of the ticket if you have admin rights on the repository.
v
