### ISSUE TITLE
Multiple obsolete OrphaIDs: potentially still in Mondo?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5795]
**Mondo term (ID and Label):**
(see below)

**Xref that should be fixed (ID and label):**
OrphaNet IDs (See list)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
MedGen curation of our stored OrphaIDs (which we have pulled most recently from Mondo's mappings) uncovered a large number of obsoleted OrphaNet IDs that were still current in our system. I didn't check all of the Mondo IDs below, but it looked like most that I did check still listed the indicated OrphaID as a current , exact match to the Mondo concept. Please review these X-refs in Mondo.

_Question:_ What is the indication on the Mondo data files if an X-ref is obsolete? I may need to ask our developers to ensure our Mondo processing doesn't add these obsoleted x-refs back to our current data.

ORPHA | Mondo ID
-- | --
ORPHA1428 | MONDO_0008207
ORPHA94095 | MONDO_0010069
ORPHA459353 | MONDO_0007361
ORPHA1533 | MONDO:0009038
ORPHA2343 | MONDO_0007861
ORPHA3133 | MONDO_0008606
ORPHA163892 | MONDO_0015588
ORPHA63440 | MONDO_0018971
ORPHA95458 | MONDO_0007001
ORPHA34526 | MONDO_0018100
ORPHA946 | MONDO_0019796
ORPHA93604 | MONDO_0100343
ORPHA163918 | MONDO_0015594
ORPHA276402 | MONDO:0017179
ORPHA306519 | MONDO:0017625
ORPHA35098 | MONDO:0018113
ORPHA139420 | MONDO:0015343
ORPHA158661 | MONDO_0015550
ORPHA158665 | MONDO_0015596
ORPHA163924 | MONDO_0015596
ORPHA217601 | MONDO_0016332
ORPHA247861 | MONDO_0016618
ORPHA329252 | MONDO_0017995
ORPHA79459 | MONDO_0019317
ORPHA89841 | MONDO_0019521
ORPHA96164 | MONDO_0019901
ORPHA102284 | MONDO_0015160
ORPHA163903 | MONDO_0015591
ORPHA171201 | MONDO_0015731
ORPHA171215 | MONDO_0015733
ORPHA247846 | MONDO_0016616
ORPHA306446 | MONDO_0017619
ORPHA306474 | MONDO_0017621
ORPHA306522 | MONDO_0017626
ORPHA329341 | MONDO_0018003
ORPHA91133 | MONDO_0019603
ORPHA99069 | MONDO_0020409
ORPHA163898 | MONDO_0015590
ORPHA226310 | MONDO_0016412
ORPHA306436 | MONDO_0017618
ORPHA306462 | MONDO_0017620
ORPHA306486 | MONDO_0017622
ORPHA34527 | MONDO_0018101
ORPHA498700 | MONDO_0044683
ORPHA163908 | MONDO_0015592
ORPHA98253 | MONDO_0020068

**Comment by nicolevasilevsky** [comment]
If an external xref is obsolete, we mark it as **MONDO:equivalentObsolete** (live class in Mondo and an obsolete class in the source ontology) or **MONDO:obsoleteEquivalentObsolete* (Both are obsolete (in Mondo and the source)

**Comment by nicolevasilevsky** [comment]
thanks for reporting this @kanems, I updated these xrefs
