### ISSUE TITLE
incoherencies arising from syndromic vs nonsyndromic disjointness

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#58]
## prune belly (ordo)

![image](https://user-images.githubusercontent.com/50745/35082677-0814d7e2-fbd0-11e7-93ba-424dee643198.png)

The ORDO hierarchy here is a little odd in general:

![image](https://user-images.githubusercontent.com/50745/35082854-d5e78976-fbd0-11e7-8a38-fd7e1b4ccaf4.png)

## polymicrogyria

![image](https://user-images.githubusercontent.com/50745/35082883-f76dc98e-fbd0-11e7-9c6c-f0a3ee151f56.png)

ordo hierarchy is unusual 
![image](https://user-images.githubusercontent.com/50745/35082936-398ef856-fbd1-11e7-8928-9c43b2d51c7d.png)

##  multiple intestinal atresia

![image](https://user-images.githubusercontent.com/50745/35083148-7dbb7396-fbd2-11e7-83fb-cd2e03d03aac.png)

from ordo:

![image](https://user-images.githubusercontent.com/50745/35083174-ad2c8494-fbd2-11e7-9015-ced54fd1983d.png)

## Axenfeld Rieger

![image](https://user-images.githubusercontent.com/50745/35083253-0614c6d4-fbd3-11e7-9a1d-ae1d4006dfd8.png)

## cloacal exstrophy

![image](https://user-images.githubusercontent.com/50745/35083475-3a9e23e0-fbd4-11e7-9db7-341ea7c7c34f.png)

## nodular neuronal heterotopia

![image](https://user-images.githubusercontent.com/50745/35083603-cb411524-fbd4-11e7-9712-5f52045d82ac.png)

**Comment by nicolevasilevsky** [comment]
We think has been addressed, closing.
