### ISSUE TITLE
Revise classification of ‘brain hypoxia - ischemia’

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#580]
Stemming from https://github.com/EBISPOT/efo/issues/297

MONDO has ‘brain hypoxia - ischemia’ as a subclass of 'brain disease', presumably inherited from EFO. FYI, in EFO we reclassified it under the phenotype branch, as follows:
‘brain hypoxia-Ischemia’ -> subclass of 'hypoxia' and 'ischemia' instead of 'brain disease';
change def. from "A disorder characterized by a reduction of oxygen in the blood..." to "A reduction of oxygen in the blood...";
see the EFO ticket for background/rationale. Another case of disease vs. phenotype...

Thanks!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky @cmungall 
FYI, another one for discussion at our next EFO-MONDO meeting. :-)

**Comment by maglott** [comment]
MeSH has brain hypoxia - ischemia has under brain ischemia
 https://www.ncbi.nlm.nih.gov/mesh/68020925
