### ISSUE TITLE
[Obsolete] MONDO:0015594 non-paraneoplastic limbic encephalitis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5801]
**Mondo term (ID and Label)**
MONDO:0015594 non-paraneoplastic limbic encephalitis

**Reason for deprecation**
obsolete in orphanet, it is an orphanet grouping class

**Suggested term to consider**
TBD

**Comment by sabrinatoro** [comment]
note that all the children of these terms will have to be moved under 'limbic encephalitis'.
