### ISSUE TITLE
create rare disease view/slim

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5812]
See curation call notes on 20 Jan 23

Sabrina and I met with Gioconda (@galyea123) and the NORD team- they need for a rare disease subset/slim of Mondo for an internal use case. (They are building an intranet site where personnel can identify their expertise and they want to use Mondo to generate a list of rare diseases that their users can view the hierarchy and select their area of expertise.)

Sabrina previously shared a list of rare diseases in Mondo. Gioconda is reviewing this list and marking terms that should not be considered rare diseases.

Action items:
- [ ] @galyea123 will send us her curated list of rare diseases
- [ ] @galyea123 will share her criteria for determining if a term is a rare disease or not.
- [ ] @sabrinatoro add subclassOf axiom to rare disease terms: 'has bearer' some rare (source: https://orcid.org/0000-0001-9310-0163)
- [ ] @sabrinatoro to work with tech team to create a rare disease view/slim
- [ ] create a slim or Mondo view for rare diseases

_Question_: New Mondo view/slim for rare disease: how do you get the parent class in this version of Mondo? Do we need to add a tag for these view?

**Comment by sabrinatoro** [comment]
@matentzn 
I assumed this was similar to the "Harrison View" and that adding a "tag" was the way to go. 
- Is it the correct way to do it? 
- in order to get the main classification in this view/slim (e.g. "neurological disease" should be in that slim, but it is not a rare disease itself), do we need to add a tag on the parent terms, or is there another way to do it? 
Thank you!

**Comment by matentzn** [comment]
Use subset tag if there are exceptions to the rule, i.e. all `has bearer some rare` except for XYZ. I think it makes sense to develop a rare disease subset, and we can do this also semi automatically (i.e. tagging all disease that are `has bearer some rare` except X).

**Comment by matentzn** [comment]
Yea close. No concrete action items we need to still deal with.
