### ISSUE TITLE
Creation of disease term: Hearing impairment and infertile male syndrome

### ISSUE THREAD

**Issue by rebecca-siegert** [monarch-initiative/mondo#583]
For new term requests, please provide the following information:

## Preferred term label

Hearing impairment and infertile male syndrome

## Synonyms

HIIMS

## Textual definition

Hearing impairment and infertile male syndrome is characterized by segregation of nonsyndromic hearing loss in females and hearing loss with infertility in males. Affected males have been reported to have low count to absent sperm, immobile sperm, and/or sperm with abnormal morphology (Imtiaz et al. 2018, PMID 29293958).  

## Suggested parent term

syndromic genetic deafness MONDO:0019589

## Additional Information

After curating the available literature associated with the CDC14A gene, there appear to be two distinct diseases that segregate with autosomal recessive variants. AR variants in CDC14A segregate in at least two families with nonsyndromic hearing loss in which affected males have fathered children (Imtiaz et al. 2018, PMID 29293958). Additionally, there are at least five families that segregate with AR variants in CDC14A in which affected females have nonsyndromic hearing loss and affected males have hearing loss and infertility (Imtiaz et al. 2018, PMID 29293958). While OMIM uses one disease term for this gene, "Deafness, autosomal recessive 32, with or without immotile sperm," MONDO does not currently have a code for the combined phenotypes of hearing impairment and infertility in males. The HIIMS term has been proposed by Imtiaz et al. 2018, PMID 29293958.

**Comment by cmungall** [comment]
@nicolevasilevsky make sure all of the additional information above is captured

**Comment by nicolevasilevsky** [comment]
@rebecca-siegert what is your ORCID, so I can add attribution to this new term?

**Comment by nicolevasilevsky** [comment]
@cmungall I added a comment, is that sufficient?

**Comment by rebecca-siegert** [comment]
my ORCID is https://orcid.org/0000-0003-1245-3907
