### ISSUE TITLE
GALT transferase deficiency

### ISSUE THREAD

**Issue by mweaver88** [monarch-initiative/mondo#5834]
**Mondo term (ID and Label)**
0009258 classic galactosemia

**Synonym to be added**
transferase deficiency

**Synonym subtype: ie, broad/exact/narrow/related**
related

**Database cross reference for the synonym** Such as PubMed ID (in the format PMID:XXXXXX) or a cross-reference to another ontology, like OMIM or Orphanet.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@mweaver88 do you have an ORCID?

**Comment by mweaver88** [comment]
Hi,

I believe this is my ORCID ID:
0000-0002-9731-6356

Thanks,
Meredith

Meredith Weaver, PhD, ScM, CGC
American College of Medical Genetics & Genomics
Ph: 301-718-9603
***@***.******@***.***>

**Comment by nicolevasilevsky** [comment]
thank you!
