### ISSUE TITLE
Develop a standard template for bulk ID submissions and an SOP that mandates its use

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#5848]
Dealing with mass curation (adding for example 100 chromosomal diseases at once) should be done using structured curated tables (manual mass curation is too time consuming to be supported moving forward). During our face 2 face, we decided to develop a set of templates for streamlining submissions. 

At first we need a minimimal core template. I will build that.

Then we need to extend the minimal core template for specific branches in the ontology (like, say, adding chromosomal diseases need a "chromosome" reference, etc). @pnrobinson will help doing that!

**Comment by nicolevasilevsky** [comment]
- [ ] @sabrinatoro and @pnrobinson to work together to create requirements
- [ ] develop a template that clinicians can contribute their new term requests or requests for classification @matentzn @sabrinatoro 
- [ ] test out the spreadsheet with clinical terms
- [ ] @mellybelly @jmcmurry create workflow for creating a micropublication of some sort for any clinical contribution (like a zenodo DOI or other micropublication

Goal: draft done by March 01

**Comment by pnrobinson** [comment]
[matentzn](https://github.com/matentzn)
I would suggest we not be too complex for the first step.
For many clinical societies, there is one superclass (that does not need to be represented in the spreadsheet), with subgroups and with leaf terms. So...these are the columns

    Parent Term Label (existing Mondo term is possible)
    Parent Term Id (if available)
    Child Term Label (if available)
    Child Term Id (if available)
    Child Term definition
    Child Term synonyms (separated by ";")
    PubMed citations
    contributor name (we need to get ORCIDs also but not here)

**Comment by matentzn** [comment]
Exactly what I was thinking!

**Comment by matentzn** [comment]
@sabrinatoro I think it is best if you create a template with the columns @pnrobinson indicated here. You can hand it for me for review - Dont name the disease "child" though, that is simply the disease. Looks totally standard stuff!

**Comment by sabrinatoro** [comment]
@matentzn 
here it is: https://docs.google.com/spreadsheets/d/1i2jtarPqbGpsDREYU64N-ogwavOrqsXzKEK9JJNyYSg/edit#gid=0
The document is in our shared folder, so you should have access to it. 
Note that I added/modified a few things

**Comment by nicolevasilevsky** [comment]
this looks great @sabrinatoro, thanks for doing this!

**Comment by matentzn** [comment]
This looks very nice. Can we add one row of example values, and one row with the actual template strings? No rush on this, we can do this slowly slowly!

**Comment by sabrinatoro** [comment]
@matentzn : 
>one row with the actual template strings

Do you mean the string for the robot template?

**Comment by matentzn** [comment]
Yes, like `A oboInOwl:source` or `SC %`! :)

**Comment by sabrinatoro** [comment]
@matentzn 
Please take a look (it is on row 3 instead of row 2, because I wanted to leave the instructions close to the main title). Note that I think there will be some interaction with a curator before something is submitted. For example, 
- the "additional information" requirements will need to be added depending on the submission. 
- any children would have to be added in a new row (?)
- the PMID would need to be added for the definition, and the parent source, and the children source. However, I don't think we should expect that submitter will add the same information in 2-3 different columns (or add it without format errors). 
Therefore, I think this template should be the base for other use-case-specific ones.

**Comment by matentzn** [comment]
Awesome! I made one small correction, the rest looks great!

I asked about the children on slack (robot channel), I don't know.

**Comment by matentzn** [comment]
@sabrinatoro as a last step, I would upload the template as a TSV to `src/templates` directory, add a small documentation page for users "How to request multiple new disease terms in Mondo?" and add a guide (where to find the file, how to fill it in). When @nicolevasilevsky and you agree on the wording, you can send an email to the Mondo mailing list with these instructions.

**Comment by jmcmurry** [comment]
getting a micropublication is trivial; the question is whether they're at a volume that necessitates the Zenodo API or whether periodic manual submissions get it done. Please advise @nicolevasilevsky

**Comment by matentzn** [comment]
I think for now a manual guide (do this do that xyz) is sufficient. I don't even know what micropublication means in this context.

**Comment by jmcmurry** [comment]
How small are we talking? A single term?

**Comment by matentzn** [comment]
This is not about arbitrary term additions - this is about having a major effort to adding terms related to a specific use case using a template - so I would say the addition should be significant to merit a nanopub. Maybe just explain how to go about this, and then we can develop an SOP on when to execute it.

**Comment by nicolevasilevsky** [comment]
thanks @jmcmurry and @matentzn!

**Comment by jmcmurry** [comment]
Apologies, I'm not sure where [zenodo upload instructions](https://www.youtube.com/watch?v=S1qK_TA52e4) end and 'how to go about it' begins. Could you explain what you think is missing. I think if you've got a template, and it is manual, all that needs doing is to upload it, add contributors, publish and then grab that DOI and round trip it back to where the artifact is typically accessed (in order to facilitate citation)

**Comment by matentzn** [comment]
@jmcmurry This is what I thought and all I needed to know! THANKS!

**Comment by matentzn** [comment]
Since this is almost done, @sabrinatoro, could you add the template to the repo as described above? Then we can mention this on our RPPR.

**Comment by nicolevasilevsky** [comment]
@matentzn this is done:
https://mondo.readthedocs.io/en/latest/editors-guide/bulk-request/

@sabrinatoro added this to the repo:
https://github.com/monarch-initiative/mondo/blob/master/src/templates/Mondo_bulk_submission.tsv

this issue can be closed

**Comment by matentzn** [comment]
Awesome I will close it then - follow up tickets can be made if needed.
