### ISSUE TITLE
Creating a comprehensive curation guide for Mondo

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#5849]
We have a lot of documentation on curating Mondo in https://mondo.readthedocs.io/en/latest/. We want to more carefully interweave general design guides with our current pattern documentation. The goal is to be able for a clinician to browse to a section on "Epilepsy" and get a carefully crafted guide on how we model epilespsy terms in Mondo (80% driven by design pattern docs, but augmented by a bit of explanatory and motivating prose).

- [x] @pnrobinson can you provide a good table of contents to start from for a guide like this?
- [ ] @nicolevasilevsky and @matentzn to build a prototype

In today's face 2 face, we went into depth in how we would do this for Epilepsy. We can try to break down major sections in Mondo and build specific sub-sections for these in our guide.

**Comment by nicolevasilevsky** [comment]
this is done, closing
