### ISSUE TITLE
rename root term to "disease"

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#5858]
discuss at the F2F
- "disease" and "disorder" are used interchangeably in the community. 
- the root term is to be renamed "disease" with "disorder" as the "disease or disorder" is weird
- for terms in Mondo, we will follow the community and use either "disease", or "disorder" based on what the community uses

To do:
- [ ] define this term
- [x] update labels in DOSDP patterns and any documentation

**Comment by nicolevasilevsky** [comment]
@matentzn FYI 👀

**Comment by nicolevasilevsky** [comment]
To do:
we need a human-readable definition. Notes from F2F meeting:
Disease versus, according to Ada:

- Disease is a process (continuant)
- Disorder is a fixed thing, like achrondysplasia (occurent)
- Condition is ‘i don’t want to label it’
- Everyone uses them interchangeably. Mondo will continue to utilize them interchangeably.

Peter's definition of a disease:
a disease is an entity has all four of the following features:

- an etiology (whether identified or as yet unknown)
- a time course
- a set of phenotypic features
- if treatments exist, there is a characteristic response to them

**Comment by matentzn** [comment]
Seems the words occurrent and continuant are reversed. Does Peters definition apply to disease AND disorder then? What would be great if we had a single definition that defines clearly what our root concept means.

**Comment by nicolevasilevsky** [comment]
per COB disease call - we want to move forward with renaming this term to disease. We will need to define it though

**Comment by nicolevasilevsky** [comment]
The outstanding action item on this ticket is to define disease, but this seems like something that will require a lot of community discussion before a decision is reached.

I will close this because the primary action item to relabel this term in done.
