### ISSUE TITLE
infectious disease should not be a separate branch

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#5859]
from F2F: 
infectious disease should not be separate from human and from non-human: all the infectious diseases that occur in non-human have a different name (and is a different disease) in human. 
--> split the infectious disease branch, and create 
1) infectious disease affecting human
2) infectious disease affecting non-human

**Comment by kanems** [comment]
@sabrinatoro This may impact how MedGen processes this set of Mondo data, can you update this ticket with the proposed new structure (and IDs, if possible) for these new Mondo terms? We want to make sure we keep the human infectious diseases but do not display the non-human ones on our public pages. Thank you!

**Comment by sabrinatoro** [comment]
Hi @kanems 
Currently, the infectious disease branch is distinct from the human disease (and non-human animal disease) branch(es). The idea is to bring it under human disease, and therefore infectious diseases will be part of human disease. 
All the non-human animal infectious diseases will get out of the current infectious disease branch and get their own, under the "non-human animal disease". 
I don't think it will affect your processing, BUT I will share the proposed structure asap. (and I will not merge until I hear from you that it is ok). 
Thank you for reaching out!

**Comment by kanems** [comment]
@sabrinatoro thank you for keeping us in the loop regarding this update. I think it's good to group all the human diseases together. I am coordinating with our developers and will ask them to review the new structure once it's posted here. We're primarily working off of the main Mondo ID for human-specific infectious diseases when we process the Mondo data so we can process infectious disease concepts as a separate category in our database, so if there will be a new set of Mondo IDs for the newer concepts/structure,  that would be super helpful for us.

**Comment by jananiravi** [comment]
@sabrinatoro, I will await your new structure soon. In the meantime, would these be categorized as 'zoonotic diseases' that indicate transmission/host-switching and that the same pathogens have shown documented pathologies in humans and non-humans? Or just as human infectious and non-human infectious? What I'm trying to understand here, is, for e.g., _Mycobacterium tuberculosis_ causes human TB and _M. bovis_ causes bovine TB. They are not even caused by the same bug but in this case closely related. So, are we going to map human<-->non-human equivalents based on the shared pathology or the exact underlying pathogen causing both? Not sure if this sounds clarifying or confusing. Happy to elaborate as needed! thank you!!

**Comment by sabrinatoro** [comment]
@kanems : please review the new classification in [this PR](https://github.com/monarch-initiative/mondo/pull/5882). (note that we will not merge this PR until you had a chance to review it)
In summary: 
- 'infectious disease or post-infectious disorder' (MONDO:0100336) has been made specific to human (=child of 'human disease or disorder'-MONDO:0700096)
- a new class was created for infectious diseases specific to non-human animals: 'infectious disease, non-human animal' (MONDO:0700049)
- All the diseases that affect non-human animals (and previously children of MONDO:0100336) were reclassified under the new MONDO:0700049
- In order to classify better the 'infectious disease, non-human animal', we created new terms specific to non-human animals, for example: 'bacterial infectious disease, non-human animal' (MONDO:0700050), 'viral infectious disease, non-human animal' (MONDO:0700053), etc
- we did add relation between the human and the non-human animal diseases that are analogous. For example, 'bacterial infectious disease, non-human animal' (MONDO:0700050) = 'non-human animal disease' and ('cross-species analog' some 'bacterial infectious disease')

If you only want to have the human diseases, including infectious diseases affecting human specifically, these will be all under the main parent 'human disease or disorder' (MONDO:0700096).

Please let me know if you have any questions or concerns. Thank you very much!

**Comment by nicolevasilevsky** [comment]
@kanems do you know how to view a branch in Protege? If not, I'm happy to have call with you and show you the revisions. (I can also send you some instructions how to do so- you will need to download the Protege software and ideally, GitHub Desktop too, they are both free to download)

**Comment by nicolevasilevsky** [comment]
Thanks for doing this @sabrinatoro, this is a big task!

**Comment by sabrinatoro** [comment]
@jananiravi, in addition to the comment above, I wanted to have a specific comment related to the connection between human and non-human infectious diseases. 

We decided (after conversations during our F2F meeting) that infectious diseases in human and non-human animals are different, even though the same agent is responsible for the infection.
That being said, we are making a connection between human diseases and non-human diseases that are analogous (= mostly the same except that they occur in different species). 
For example, 'pneumonia, non-human animal'(MONDO:0700110) = 'non-human animal disease' and ('cross-species analog' some pneumonia) where 'pneumonia' (MONDO:0005249) is the human disease. 

Please let me know if you have any questions, if you disagree, or if you think we should discuss this modeling further! 

Note that we have a term: zoonosis (MONDO:0025481) that is currently a human disease, but some zoonotic diseases, such as 'anaplasmosis' have a 'human' version, and a 'non-human' version, with a connection between them. 
We need to figure out what to do with that specific "zoonosis' term.

**Comment by kanems** [comment]
@sabrinatoro Thank you for all this! Just want to clarify to ensure I understand the changes:
1. human infectious disease parent concept will have the same Mondo ID? currently the top 
level ID term is   http://purl.obolibrary.org/obo/MONDO_0100336 and this will now reside under "human disease or disorder"

> i.e. 'infectious disease or post-infectious disorder' (MONDO:0100336) has been made specific to human (=child of 'human disease or disorder'-MONDO:0700096)

2. will Viral diseases still be split out separate from all other infectious diseases? (Not that I am suggesting that branch be changed, just trying to understand the plan.)

I see there is also a ticket to obsolete "infectious disease or post-infectious disorder" https://github.com/monarch-initiative/mondo/issues/5861 that looks to be slated for the April release that may also impact the Mondo IDs, I'll leave my questions for that issue on that ticket so as not to confuse this issue....

**Comment by sabrinatoro** [comment]
@kanems 
1. this is correct, the human infectious disease MONDO:0100336 will keep the same ID and reside under "human disease or disorder. 
2. We will discuss on our next call how to proceed with the different terms once we go ahead with the obsoletion of "infectious disease or post-infectious disorder", and we will update the other issue (https://github.com/monarch-initiative/mondo/issues/5861) with the plan. We will definitely make sure that everything is sound with you before we go ahead with the obsoletion (and therefore we might push the obsoletion to a later time).

**Comment by nicolevasilevsky** [comment]
@kanems we are going to go ahead and merge these changes (which will be available in the March release) and we are discussing the plan about obsoleting 'infectious disease or post-infectious disorder' and will keep you updated on that ticket.

**Comment by kanems** [comment]
@nicolevasilevsky great, thank you! I'll monitor the other ticket.

**Comment by jananiravi** [comment]
Thanks, @sabrinatoro. Makes sense. Yes, I've more Qs on zoonoses -- can you tag me in that discussion?
