### ISSUE TITLE
[Obsolete] 'infectious disease or post-infectious disorder'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5861]
**Mondo term (ID and Label)**
'infectious disease or post-infectious disorder'

**Reason for deprecation**
at the Mondo F2F we decided we do not want this term, terms are being incorrectly classified, Melissa's hate 'or' in a label.

**Suggested term to consider**
create a new class: 'post-infectious immune dysfunction disease'. The vast majority of post-infectious diseases are autoimmune.

**Comment by jananiravi** [comment]
Hi Nicole, quick qn: could you clarify 'The vast majority of post-infectious diseases are autoimmune'? thanks!

**Comment by kanems** [comment]
@nicolevasilevsky do you anticipate that in resolving that ticket you will obsolete Mondo_0100336 and replace it with new concepts/IDs for 'infectious disease' and 'post-infectious disorder' ?

**Comment by nicolevasilevsky** [comment]
> Hi Nicole, quick qn: could you clarify 'The vast majority of post-infectious diseases are autoimmune'? thanks!

We discussed this at our face-to-face meeting last week and our medical experts noted that most post-infectious diseases are due to an autoimmune component. But it this will probably not apply to all post-infectious disorders. We could add it as a narrow synonym for post-infectious disease.

> do you anticipate that in resolving this ticket you will obsolete Mondo_0100336 and replace it with new concepts/IDs for 'infectious disease' and 'post-infectious disorder' ?

Discussing with @sabrinatoro now. 

- We will keep MONDO:0005550 infectious disease as it's current class.
- We will keep MONDO:0021670 'post-infectious disorder' (which will be the consider term when obsolete 'infectious disease' and 'post-infectious disorder' 
- @sabrinatoro and I think we should also obsolete 'viral disease or post-viral disorder' and consider MONDO:0021674 'post-viral disorder'
- [ ] @nicolevasilevsky add to list ⬆️ 

The hierarchy would look like:
human disease or disorder
-infectious disease
-post-infectious disease
--'post-viral disorder' (this classification already exists)

### Questions:

1. @sabrina has an open question about the logical axiom on 'post-infectious disorder', is this correct?
2. where do we classify MONDO:0100318 'SARS-CoV-2-related disease'. Could this be a child of 'human disease or disorder'?
    2a.  can we obsolete MONDO:0100318 'SARS-CoV-2-related disease'?
- [ ] Sabrina suggested creating a separate issue and getting feedback from Melissa, N3C users, Mondo users (@sabrinatoro to do)

**Comment by nicolevasilevsky** [comment]
we discussed this on the curation call, we'll obsolete infectious disease or post-infectious disorder but there is still the open question about the logical def above

**Comment by sabrinatoro** [comment]
@nicolevasilevsky should we close this issue (after PR is merged) or leave it open? 
I think what remains is part of the major review and branch remodel of infectious/post-infectious diseases.

**Comment by nicolevasilevsky** [comment]
we have an open ticket for this branch review:
https://github.com/monarch-initiative/mondo/issues/5420

I will close this

**Comment by jananiravi** [comment]
@nicolevasilevsky, thanks for these massive updates! I read the linked issues as well. I see that a few InfDs are now part of infectious (I think this means human_infectious), while a few others are part of non-human-animal-infectious.

For example, I was looking at TB, and [bovine TB](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0025136) was related to TB but disappeared while the ontologies were restructured. Any plan to discuss the confusing Zoonoses angle and bring bovine_tb and others also under human when there's primary or secondary human infection?

I understand why this was done, but I have a few Qs. Can I set up a brief time to chat with you (or please let me know when this is discussed, and I will join the call)?

**Comment by nicolevasilevsky** [comment]
Hi @jananiravi - sure thing, we'd be happy to discuss. We are focusing on mass obsoletion of Orphanet terms through the end of October, but we can revisit this in early November, if that works for you. @sabrinatoro and @katiermullen will be the best people for this discussion, as they have been working on the non-human disease branch.
