### ISSUE TITLE
[NTR]: Cardiac malformation reporting system (Von Praagh) Notation?

### ISSUE THREAD

**Issue by taylordm** [monarch-initiative/mondo#5871]
Need guidance on how to request this system to be supported in MONDO short of trying to list each individual term as a term request (there are many combinations).

Happy to be available for a discussion about this system of notations and how we can support them in MONDO. 

I have also posted this to Peter Robinson for HPO consideration.

This is a somewhat complicated but commonly used clinical cardiac malformation reporting system  (Von Praagh)  that uses a “normal” condition as one of the categorical conditions for each entry in the triplet -- see attached image which comes in from the last paper linked below.

These are just a few examples below listed out of that system, that are already in Kids First.

And it’s unfortunate that lowercase L is used alongside big-I, so user beware.
 
{A,d,d} visceroatrial situs ambiguous, ventricular D loop, D great artery malposiiton
{A,l,d} visceroatrial situs ambiguous, ventricular L loop, D great artery malposiiton
{A,l,l} visceroatrial situs ambiguous, ventricular L loop, L great artery malposiiton
{A,x,d} visceroatrial situs ambiguous, unknown loop, D great artery malposiiton
{I,l,i} visceroatrial situs inversus; ventricular L loop,  inversus-normal great arteries.
{S,d,A} visceroatrial situs solitus, ventricular D loop, A great artery malposition
{S,d,d} visceroatrial situs solitus, ventricular D loop, D great artery malposiiton
{S,l,A} visceroatrial situs solitus, ventricular L loop, A great artery malposition
{S,l,d} visceroatrial situs solitus, ventricular L loop, D great artery malposiiton
{S,l,l} visceroatrial situs solitus,  ventricular L loop,  L-normal great arteries.
{S,x,l} visceroatrial situs solitus,  unknown ventricular loop,  L-normal great arteries.
 
 
Papers that cover this system:

https://www.ahajournals.org/doi/pdf/10.1161/01.CIR.56.2.139 

https://thoracickey.com/anatomy-and-classification-of-congenital-heart-disease/

https://web.archive.org/web/20160507120152id_/http://pubs.rsna.org:80/doi/pdf/10.1148/rg.332125086
 
So in these cases from Kids First, it’s not so clear cut -- as in the first piece of the triplet, they’re using a majority choice as seen in the top section of the image attached.

<img width="711" alt="VonPraagh_Notation" src="https://user-images.githubusercontent.com/11062794/217070016-1c7eaee4-cb1a-47c7-aacb-3e3651cc6a59.png">

(to be filled out later!)
**Preferred term label:**

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@taylordm should we keep this ticket open?

I'll leave it open for another month but if we don't hear back, we'll close it (but you can always reopen it when it is ready to be addressed).

Thanks!
