### ISSUE TITLE
MONDO:0010783 Alzheimer disease, susceptibility to, mitochondrial

### ISSUE THREAD

**Issue by MariaLivia** [monarch-initiative/mondo#5879]
Dear MONDO curators,

I am working at UniProt and contacting you about the term MONDO:0010783 ‘Alzheimer disease, susceptibility to, mitochondrial’ which correspond to OMIM phenotype entry #502500. This term has been made obsolete in MONDO (issue https://github.com/monarch-initiative/mondo/issues/4363). As it refers to a disease phenotype and we still need this term in UniProt, would it be possible to restore it ?
Thank you very much for your help
Best regards,
Livia

**Comment by nicolevasilevsky** [comment]
Hi @MariaLivia - yes! I restored this, the new ID is MONDO:0100295

It will be available in the March release (around March 01). Are you on our mailing list? I can add you, if not.

Best,
Nicole

**Comment by MariaLivia** [comment]
Dear Nicole,
thank you very much.
It would be great if you add me to your mailing list.
Best regards,
Livia
