### ISSUE TITLE
ask Maria Della Rocca about adding Global Genes to Mondo users list

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5895]
- [x] ask Maria Della Rocca about adding Global Genes to Mondo users list - _emailed 2023-02-09_
- [ ] Once we have approval, add here (@sabrinatoro):
https://mondo.monarchinitiative.org/pages/users/

**Comment by sabrinatoro** [comment]
@nicolevasilevsky, could you please tag me (or assign to me) once you got approval, please?

**Comment by nicolevasilevsky** [comment]
> @nicolevasilevsky, could you please tag me (or assign to me) once you got approval, please?

yep!

**Comment by nicolevasilevsky** [comment]
I emailed her twice and have not heard back, so I will close this for now.
