### ISSUE TITLE
[Obsolete] 'SARS-CoV-2-related disease' (MONDO:0100318)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#5899]
**Mondo term (ID and Label)**
'SARS-CoV-2-related disease'
MONDO:0100318 

**Reason for deprecation**
This term is a grouping term for 'COVID-19' and 'post-COVID-19 disorder'. 

'COVID-19' (MONDO:0100318) is a 'viral infectious disease'
'post-COVID-19 disorder' (MONDO:0100320) is a 'post-viral disorder'
'viral infectious disease' and 'post-viral disorder' are two different branches in Mondo. 'SARS-CoV-2-related disease' was meant to group these two covid-19 viral and post-viral concepts. However, this term will not have a place in the ontology once we obsolete the term 'infectious disease or post-infectious disorder' (MONDO:0100336) -see #5861 

**Question to Mondo users:** 
would it be ok to obsolete this grouping term? The consequence of this decision would be that one would have to query for both 'covid-19' and 'post-COVID-19 disorder' in order to get all the 'covid-19' related annotations. 

If there is a need for a term grouping 'covid-19' and 'post-covid-19 disorder' (and therefore we should NOT obsolete 'SARS-CoV-2-related disease'), where do you think this term should be classified in the Mondo ontology since it is neither an infectious disease nor a post-viral disorder.

**Comment by kanems** [comment]
I have checked with the MedGen, GTR and ClinVar teams, we do not need this term, OK to obsolete. Thank you!

**Comment by nicolevasilevsky** [comment]
also should obsolete 'infectious disease or post-infectious disorder'
https://github.com/monarch-initiative/mondo/issues/5861

**Comment by nicolevasilevsky** [comment]
also need to obsoelte viral disease or post-viral disorder
 https://github.com/monarch-initiative/mondo/issues/5861

I will work on these in May, for the June release
