### ISSUE TITLE
add logical def to hyperprolactinemia (disease) 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#59]
need new GO term, term request here: https://github.com/geneontology/go-ontology/issues/14893 

MONDO_0005804 hyperprolactinemia (disease)
Text def: Abnormally high level of prolactin in the blood.

I believe the logical definition should be:
'metabolic disease'
 and ('disease caused by disruption of' some 'prolactin metabolic process')

**Comment by nicolevasilevsky** [comment]
need to MIREOT GO:0120122 prolactin metabolic process

**Comment by nicolevasilevsky** [comment]
actually, I am not so sure about this logical def, although there are some terms that have logical definitions composed this way, such as:

MONDO_0021162 carotenemia 
metabolic disease' and ('disease caused by disruption of' some 'carotenoid metabolic process')

@cmungall can you give me some feedback? thank you!

**Comment by cmungall** [comment]
First: is this term a disease or finding or both?

It's in HPO and NCIT treats it as a finding, so one option would be to obsolete it from MONDO.

But we don't yet have a strong policy here [need a ticket for this], but it seems reasonable to treat this as a distinct condition that progresses over time and gives rise to features so let's keep it in for now.

The owl definition of this one would be trivially the phenotype

We might want to also add info about the etiology so the first thing to do is have a look at the liteature. It seems this disease has many possible causes?
