### ISSUE TITLE
[Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5906]
**Mondo term (ID and Label)**
MONDO:0013736  
myopathy, centronuclear, 3

**Reason for deprecation**
C3280703 last appeared in the 2019AA version of the UMLS. It was mapped to a related CUI: [C4551952](https://uts.nlm.nih.gov/uts/umls/concept/C4551952).
OMIM 614408
MOVED TO [160150](https://www.omim.org/entry/160150)
"The mutation in the MYF6 gene that was reported to cause a form of CNM, formerly designated CNM3, has been reclassified as a variant of unknown significance; see [159991.0001](https://www.omim.org/entry/159991#0001)."

**Suggested term to consider**
Not sure. OMIM merged to the CNM1 concept, so maybe MONDO:0008048 AD CNM ? (but the OMIM preferred name doesn't show up on this term)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
thanks @kanems I will merge MONDO:0013736 myopathy, centronuclear, 3 into MONDO:0008048 'autosomal dominant centronuclear myopathy', following OMIM

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/6239
