### ISSUE TITLE
rare genetic primary immunodeficiency

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#591]
To my understanding, "primary immunodeficiency" is Mendelian. Therefore, consider merging this with its parent:
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0015138

Also, the hierarchy underneath needs work. I would suggest we base the hierarchy on the scheme in this article. We can then work out the details with our immunology collaborators.

https://www.ncbi.nlm.nih.gov/pubmed/23657403

**Comment by nicolevasilevsky** [comment]
this has been obsoleted
