### ISSUE TITLE
revise allergy branch

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5914]
Creating a new ticket that combines https://github.com/monarch-initiative/mondo/issues/498 and https://github.com/monarch-initiative/mondo/issues/5856.

## Action items:
- [ ] obsolete granular allergy terms (obsoletion tags have already been added)
- [ ] @sabrinatoro you mentioned that you wanted to create a new pattern that would group the remaining terms by location, right?

### Exclusion reason:
- [ ] create exclusion reason “MONDO:excludeAllergy”. This new exclusion term needs to be defined and added to the exclusion code list (and communicated to the technical team)
- [ ] add exclusion reason here too: https://docs.google.com/spreadsheets/d/18V-_j4b22LzCytxFEM3pBEl6-_ODJY06gpUwH0F6JVY/edit#gid=1644570180
- [ ] Also, we need to update the excluded term list in the ingest (@sabrinatoro can do it and work with Joe to update DO update)

**Comment by sabrinatoro** [comment]
@nicolevasilevsky I have questions/comments about the MONDO:excludeAllergy code added [here](https://mondo.readthedocs.io/en/latest/editors-guide/exclusion-reasons/#exclusion-reasons)

- the code name should be "allergy" not "phenotype"
- is "allergy" considered a phenotype? (if so, it would need to be under phenotype). 
- in the "notes", it would be helpful to add what "allergy" terms are added, versus which one are not added. 
- generally, I am not sure I understand fully which term would be in Mondo and which one wouldn't. I think we talked about adding "some" terms (I need to review my notes). We should have a very clear description of what is "allergy", and which one we are excluded.

**Comment by nicolevasilevsky** [comment]
discussed on curation call - Sabrina is going to put together a proposal for how to handle allergy terms.
This affects the mapping/sync because we need to know how to handle allergy terms from external ontologies and if they should be diseases or phenotypes.

**Comment by sabrinatoro** [comment]
to do: 
- [ ] add exclusion code "MONDO:excludeAllergy"
- [ ] update exclusion list 
- [ ] update exclusion document

- [ ] add "MONDO:mondoIsNarrowerThanSource" for terms that are too specific so we keep track of these mappings
- [ ]  de-obsolete MONDO:0002497 food allergy 

- [ ] obsolete all children terms of "food allergy" (to do: list of all the terms to be obsoleted as these obsoletions are spread through several issues)

**Comment by sabrinatoro** [comment]
Terms to obsolete: 
Mondo ID | label | consider or replaced by?
-- | -- | --
MONDO:0000770 | shellfish allergy' | MONDO:0700226 - food allergy
MONDO:0005902 | peanut allergic reaction' | MONDO:0700226 - food allergy
MONDO:0005849 | milk allergic reaction' | MONDO:0700226 - food allergy
MONDO:0000769 | chicken egg allergy | MONDO:0700226 - food allergy
MONDO:0000778 | fruit allergy | MONDO:0700226 - food allergy
MONDO:0000781 | cherry allergy | MONDO:0700226 - food allergy
MONDO:0000782 | Indian plum allergy | MONDO:0700226 - food allergy
MONDO:0000783 | orange allergy | MONDO:0700226 - food allergy
MONDO:0000784 | melon allergy | MONDO:0700226 - food allergy

@nicolevasilevsky should it be "consider" or "replaced by"?

**Comment by nicolevasilevsky** [comment]
consider
