### ISSUE TITLE
autism susceptibility (to) 1[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5919]
**Mondo term (ID and Label)**
MONDO:0020643  autism susceptibility 1

**Reason for deprecation**
These appear to be the same concept. One is a string used in genemap2 file, other is the "included" name on https://www.omim.org/entry/209850 but I do not see anything on the MIM record that suggests there are 2 different susceptibilty loci for AUTS1 .

**Term to be merged with**
MONDO:0800416 autism, susceptibility to, 1

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

@ahamosh is the "susceptibility 1" entry in the GeneMap file a typo or are these intended to be distinct concepts?

**Comment by nicolevasilevsky** [comment]
I agree, we'll merge these
