### ISSUE TITLE
Uberon unsatisfiable classes [Revise subclass]

### ISSUE THREAD

**Issue by Daniel-Olson** [monarch-initiative/mondo#5921]
**Mondo term (ID and Label)**
ERROR There are 6 unsatisfiable classes in the ontology.
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/UBERON_0005478
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/UBERON_0009570
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/UBERON_0009576
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/UBERON_0009577
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/UBERON_0009578
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/UBERON_0006846

**Suggested revision and reasons**
I believe that In the latest Uberon release the above terms were moved from 'material entity' to 'immaterial entity'. The classes are now disjoint between MONDO/Uberon but an import refresh should probably fix the issue.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
![image](https://user-images.githubusercontent.com/19192179/219128160-d27c620d-9eec-4c94-8b2e-62595d604bc7.png)

**Comment by nicolevasilevsky** [comment]
@Daniel-Olson to clarify, you see this as unsatisfiable in CPONT, not in Mondo, right?

**Comment by nicolevasilevsky** [comment]
@matentzn @cmungall - looks like the hierarchy in Mondo differs from what is in Uberon currently:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/6722114/219132678-5a541d5e-e1c0-41f2-93bf-ea59807cc381.png">

<img width="292" alt="image" src="https://user-images.githubusercontent.com/6722114/219132730-c4b39116-945b-43fa-9016-cc9fdb10674d.png">

**Comment by matentzn** [comment]
@nicolevasilevsky - I think we should switch CPONT to use base files, similar to what we did in CL. I can help with that process. These kind of issues should not happen in an application ontology (this is not an issue in Mondo).

A quick fix for CPONT is, as @Daniel-Olson suggests, to refresh the Uberon import, but I would recommend prioritisting the base file usage.

**Comment by nicolevasilevsky** [comment]
Thank you @matentzn! I'll close this issue here and open an issue in the CPONT issue tracker.
