### ISSUE TITLE
neuronal ceroid lipofuscinosis, late infantile [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#5922]
**Mondo term (ID and Label)**
MONDO:0800297 neuronal ceroid lipofuscinosis, late infantile

**Reason for deprecation**
Seems to be redundant (at least in name) with MONDO:0015674  late infantile neuronal ceroid lipofuscinosis
However, the Orphanet x-ref on this is ORPHA:168491 which points to multiple OMIM records; So it seems the Orphanet concept is all CLNs that have 'late infantile' onset regardless of genotype; and it's unclear to me if the MIM 'included' concept 'LINCL' is supposed to be connecting the former classification of "CLNs by age of onset" to the "CLNs by gene" newer classification approach. https://omim.org/entry/204500 
>The CLNs were originally classified broadly according to age at onset, with CLN2 as the late infantile-onset (LINCL) form with onset between 2 and 4 years of age. With the identification of molecular defects, however, the CLNs are now classified numerically according to the underlying gene defect. CLN2 refers to CLN caused by mutation in the CLN2 gene, regardless of the age at onset.

**Term to be merged with**
MONDO:0015674  late infantile neuronal ceroid lipofuscinosis

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems. We'll review this more closely.

**Comment by sabrinatoro** [comment]
discussed on the Expert call on Jan 25, 2024: 

The "other entities represented" in OMIM:204500, NEURONAL CEROID LIPOFUSCINOSIS, LATE INFANTILE, INCLUDED; LINCL, INCLUDED, should be removed from the OMIM record. 

@ahamosh, as per our discussions on the call, please remove NEURONAL CEROID LIPOFUSCINOSIS, LATE INFANTILE, INCLUDED; LINCL, INCLUDED from this "Other entities represented in this entry" in the omim record OMIM:204500.


To do: obsolete MONDO:0800297 based on MONDO:excludeObsoleteSource (obsoletion reason: http://purl.obolibrary.org/obo/OMO_0001000, source MONDO:excludeObsoleteSource)
