### ISSUE TITLE
[NTR] need genetic terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5952]
Related to https://github.com/monarch-initiative/mondo/issues/5539

- hereditary heart disease (syn: cardiogenetic)
- hereditary kidney disease (syn: nephrogenetic)
- hereditary neurological disease (syn: neurogenetic)
    - central neurogenetic
    - peripheral neurogenetic

~hereditary syndromic disease~
etc
....
def: a hereditary disease that is isolated to the specific organ system

discussed on curation call on 2023-02-23 and 2023-03-23

cc @sabrinatoro

**Comment by nicolevasilevsky** [comment]
there are a number of genetic grouping classes that are tagged for obsoletion, I think we should remove the obsoletion tag and reconsider if we want to obsolete these

@sabrinatoro's questions

- what is “genetic diseases”? are they the same as “inherited”?
- if ordo grouped diseases based on inherited/genetic reason, do it make sense or not? I really dislike the “de-obsoletion” of terms (this has very bad consequences to users), so let’s at least think about it before obsoleting these terms.

[mondo_obsoletioncandidates (8).xlsx](https://github.com/monarch-initiative/mondo/files/10913708/mondo_obsoletioncandidates.8.xlsx)

**Comment by nicolevasilevsky** [comment]
- need to make sure the patterns and definitions are updated
- we should use term 'hereditary' instead of genetic

**Comment by nicolevasilevsky** [comment]
keep an eye on this term and make sure it is not classified under monogenic class
'Usher syndrome, type 1D/F'

**Comment by pnrobinson** [comment]
@nicolevasilevsky  @ahamosh 
_**Suggestion**_
label: hereditary neurological disease (syn: neurogenetic) 
def: A heterogeneous group of genetic conditions, with Mendelian (autosomal dominant, recessive, or X-linked) or chromosomal etiology that are characterized by abnormalities in brain, spinal cord, nerves or muscles.
CHILD-- 
Label: Heritable neuromuscular disease
Definition: A heterogeneous group of genetic conditions, with Mendelian (autosomal dominant, recessive, or X-linked) or chromosomal etiology that are characterized by characterized by progressive muscle degeneration and weakness. 
CHILD 2 
Label: Heritable neurological disease
Definition: A heterogeneous group of genetic conditions, with Mendelian (autosomal dominant, recessive, or X-linked) or chromosomal etiology that are characterized by progressive muscle degeneration and weakness.

**Comment by pnrobinson** [comment]
@nicolevasilevsky @sabrinatoro @ahamosh 
Suggestion
Cardiogenetic disease
A heterogeneous group of genetic conditions, with Mendelian (autosomal dominant, recessive, or X-linked) or chromosomal etiology that are characterized by abnormalities in the cardiovascular system.PMID:32341133

**Comment by pnrobinson** [comment]
@nicolevasilevsky @sabrinatoro @cmungall 
sorry to be pushy but we could really use this reorganization for L4CI. If you agree to the above and would show me briefly how you would like me to do a pull request I can work on this or maybe we can do a hacking session?

**Comment by nicolevasilevsky** [comment]
Hi Peter - 
we can definitely get these terms in for the next release. 

1. I can add these myself tomorrow
2. You can add them yourself on a branch using Protege and do a PR, you have an ID range (see below) (here are instructions on how to do a PR in Mondo: https://mondo.readthedocs.io/en/latest/editors-guide/d-github-pr-workflow/)

Datatype: idrange:15

        Annotations: 
            allocatedto: "Peter Robinson"

        EquivalentTo: 
            xsd:integer[>=0100000, <= 1000999]

3. You can add them via our new bulk request form, instructions are here: https://mondo.readthedocs.io/en/latest/editors-guide/bulk-request/
4. You can also use KGCL to add new terms (this is new, we've only done some minimal testing with this, but it seemed to work for me when I tried it): https://mondo.readthedocs.io/en/latest/editors-guide/make-simple-changes/
5.

**Comment by nicolevasilevsky** [comment]
since this is urgent, I'll plan to add these myself tomorrow if I don't hear back. But you are welcome to directly edit Mondo on a branch and make a PR anytime. Let us know if any of the instructions linked above are not clear and if you'd like one of us to walk you through the process on a call.

**Comment by pnrobinson** [comment]
@nicolevasilevsky  -- I will do a PR, but prob will only get to it on Sat AM! We also need to rearrange some of the existing terms that are hereditary!

**Comment by nicolevasilevsky** [comment]
ok, fantastic! @sabrinatoro plans to run the release on Monday. @sabrinatoro if you get to it before I do, could you review and merge Peter's PRs, so they get in to this next release?

Or we can push the release back one day too. We don't want to make you wait another month.

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] need non-inherited class for 'focal segmental glomerulosclerosis' (note NCIT def seems to be isolated or primary) - MONDO:0005363

**Comment by nicolevasilevsky** [comment]
_Updated 2023-06-20_ 

## Open Action items

- [ ] add 'hypertensive nephropathy' to the OMIM omit list (_does this mean we want to obsolete this term?_) or revise to a mendelian form (ask Ada)
- [ ] add new terms (_confirm with Peter_):
   - [ ] label: hereditary neurological disease (syn: neurogenetic)
def: A heterogeneous group of genetic conditions with Mendelian (autosomal dominant, recessive, or X-linked) or chromosomal etiology characterized by abnormalities in the brain, spinal cord, nerves, or muscles.
   - [ ] Label: heritable neuromuscular disease
   parent: hereditary neurological disease
Definition: A heterogeneous group of genetic conditions with Mendelian (autosomal dominant, recessive, or X-linked) or chromosomal etiology that is characterized by progressive muscle degeneration and weakness.
      - [ ] review this article for children of neuromuscular diseases: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5004840/
   - [ ] Add term:
Label: Heritable neurological disease
Definition: A heterogeneous group of genetic conditions, with Mendelian (autosomal dominant, recessive, or X-linked) or chromosomal etiology that are characterized by progressive muscle degeneration and weakness.
   - [ ] Add term: Cardiogenetic disease
A heterogeneous group of genetic conditions, with Mendelian (autosomal dominant, recessive, or X-linked) or chromosomal etiology that are characterized by abnormalities in the cardiovascular system.PMID:32341133

**Comment by nicolevasilevsky** [comment]
_Updated 2023-08-08_

We will address this after we do the mass ORDO obsoletion.

Note to self, add this term:

[Term]
id: MONDO:0100521
name: hereditary neurological disease
def: "A heterogeneous group of genetic conditions with Mendelian (autosomal dominant, recessive, or X-linked) or chromosomal etiology characterized by abnormalities in the brain, spinal cord, nerves, or muscles." [https://orcid.org/0000-0002-0736-9199]
synonym: "neurogenetic disease" EXACT [https://orcid.org/0000-0002-0736-9199]
is_a: MONDO:0005071 {source="https://orcid.org/0000-0002-0736-9199"} ! nervous system disorder
intersection_of: MONDO:0005071 ! nervous system disorder
intersection_of: has_characteristic MONDO:0021152 ! inherited
property_value: http://purl.org/dc/terms/creator https://orcid.org/0000-0001-5208-3432
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/5952" xsd:anyURI

**Comment by nicolevasilevsky** [comment]
> add 'hypertensive nephropathy' to the OMIM omit list or revise to a mendelian form (ask Ada)

this is already a child of 'hereditary disease', so it is inferred to be a Mendelian form. I will leave this for now.
