### ISSUE TITLE
create GitHub issue template for KGLC templates

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5955]
See instructions below

- Open a new issue with the description of the request.
 - In the description, ontobot looks for the phrase `Hey ontobot!, apply: `
 - This phase should be followed by bullets of KGCL (Knowledge Graph Change Language) commands
 - For e.g.:

 ```
Hey ontobot! apply:
- create broad synonym 'ABCD' for MONDO:0001234
```

- Commands that are functional as of now:
  - create broad synonym 'ABCD' for MONDO:0001234
  - create exact synonym 'ABCD' for MONDO:0001234
  - create narrow synonym 'ABCD' for MONDO:0001234
  - create related synonym 'ABCD' for MONDO:0001234
  - obsolete MONDO:0001234 with replacement MONDO:0001234
  - create node MONDO:0001234 'label of the class'
  - rename MONDO:0001234 from 'old label' to 'new label'

**Comment by nicolevasilevsky** [comment]
for now, create templates for adding synonyms or changing labels.

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/issues/5953

**Comment by nicolevasilevsky** [comment]
could tell a user to use a TEMP ID like TEMP:0000001

**Comment by nicolevasilevsky** [comment]
I believe we decided we were not going to do this and @hrshdhgd would create KGCL with structured issue template instead (per tech call on 03/31/23)

**Comment by hrshdhgd** [comment]
This should be done. Give it a shot @nicolevasilevsky . If not here, it should work on my fork.

**Comment by nicolevasilevsky** [comment]
Thanks @hrshdhgd, I will give it a try :)
