### ISSUE TITLE
Mapping issue: lexical matching on exact synonym with "ambiguous" synonym type

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#5985]
subject_id | subject_label | predicate_id | object_id | object_label | mapping_justification | mapping_tool | confidence | subject_match_field | object_match_field | match_string | comment |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MONDO:0000437 | cerebellar ataxia | MONDO:equivalentTo | NCIT:C26702 | Ataxia | semapv:LexicalMatching | oaklib | 0.8 | oio:hasExactSynonym | rdfs:label | ataxia | LEXMATCH |   |   |   |   |   |   |   |   |   |   |   |   |   |  

The lexical match here is made between the label of the source and the "exact synonym" in Mondo. 
In this case, the synonym type is "ambiguous", and the match is not correct. 

I "think" that it requires us to review all "exact synonyms" and make sure that "**exact** synonyms" do NOT have a "ambiguous" synonym type. 
@nicolevasilevsky, is there any reason why an "exact synonym" could have "ambiguous" type? If this sounds like a curation issue, I will move this issue to the Mondo repo.

**Comment by matentzn** [comment]
> I "think" that it requires us to review all "exact synonyms" and make sure that "exact synonyms" do NOT have a "ambiguous" synonym type.

Agreed. Ambiguous should be relegated to "close" - we can do this with regex hacking in our next 1:1

**Comment by sabrinatoro** [comment]
From the call on March 2, 2023
example: when people use "ataxia", they refer to "cerebellar ataxia". Therefore 'ataxia' is an exact synonym. But since 'ataxia' is also used in "spinal ataxia", 'vestibular ataxia',... which is why we use the tag "ambiguous"
Therefore "exact synonym" is the correct synonym type. 
--> Maybe it is ok, but we need to review the mapping made based on this synonym (and/or not make matches on these synonyms?).

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I think I can close this issue, as I don't think there are any open action items. Do you agree?

**Comment by nicolevasilevsky** [comment]
yes!
