### ISSUE TITLE
MONDO:0001449: review synonym type for 'Lymphocytic Meningitis'

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#5987]
From Mapping work: 
Lymphocytic Meningitis is currently an exact synonym for MONDO:0001449 - lymphocytic choriomeningitis

I don't think this is correct: 
NCIT:C174114 (https://ncithesaurus.nci.nih.gov/ncitbrowser/pages/concept_details.jsf) define Lymphocytic Meningitis: 
Meningitis in which lymphocytes predominate in the cerebrospinal fluid.

This is more general than "MONDO:0001449 - lymphocytic choriomeningitis" which is due to a viral infection

To do: change synonym type to "broad synonym"

**Comment by nicolevasilevsky** [comment]
this is already done

<img width="757" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/4dc4fb4b-9bf0-44b1-8e30-f031aefc706a">
