### ISSUE TITLE
OWLEntityRenamer ignores some URIs, leaving ghost alt_ids

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#6]
See: https://github.com/monarch-initiative/monarch-disease-ontology/issues/411

Probably need a change in owltools to explicitly rename these.

Until then, hack out the ghost IDs

**Comment by nicolevasilevsky** [comment]
@cmungall is this still needed?

**Comment by nicolevasilevsky** [comment]
🎂
