### ISSUE TITLE
MONDO:0008941 has no parent

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6000]
MONDO:0008941 - 'hepatic fibrosis-renal cysts-intellectual disability syndrome'
The only parent for this term is "disease". At a minimum, it should be classified under 'human disease'. But it really should have a better parent. 

@nicolevasilevsky , I am assigning you as it looks like it might be related to the "intellectual disability" terms work you have been doing.

**Comment by nicolevasilevsky** [comment]
this is probably my fault! I will fix it, thanks for reporting
