### ISSUE TITLE
[Revise subclass]

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#6022]
**Mondo term (ID and Label)**
@ahamosh 
Should [Intellectual developmental disorder with dysmorphic facies and ptosis](https://omim.org/entry/617333) , current Mondo entry  [MONDO_0015022](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0015022),
be made a child of [syndromic intellectual disability](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0000508) ?

**Comment by ahamosh** [comment]
Yes, but those children could use some structure...
