### ISSUE TITLE
[Revise subclass] Cockayne

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#6023]
@ahamosh 

Would we not want to classify [Cockayne syndrome ](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0016006)
as a [progeroid syndrome](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0015333) as its primary classification?

**Comment by ahamosh** [comment]
I think given the company it would keep in progeroid syndromes, it belongs there.  I am not certain of primary vs other parentage.  I never really understand that.

**Comment by nicolevasilevsky** [comment]
I will add progeroid syndrome as a parent of [Cockayne syndrome](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0016006).

There is no way to indicate a primary classification though.

**Comment by nicolevasilevsky** [comment]
ok, got it! Will do.
