### ISSUE TITLE
[Revise subclass] Structural heart defects and renal anomalies syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#6024]
@ahamosh 
Should we make

[Structural heart defects and renal anomalies syndrome](https://omim.org/entry/617478), MONDO term [MONDO:0044321](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0044321) 
as subclass of [multiple congenital anomalies/dysmorphic syndrome without intellectual disability](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0015161&lang=en&viewMode=PreferredRoots&siblings=false)?

Currently it is just a subclass of Mendelian disease

**Comment by ahamosh** [comment]
Yes, according to the hierarchy that I am looking at.
