### ISSUE TITLE
Tuberous sclerosis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#6025]
@ahamosh 

To my knowledge [tuberous sclerosis](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001734&lang=en&viewMode=PreferredRoots&siblings=false) is not considered a neurodegenerative disorder.
Should we remove this subclass relation?

**Comment by ahamosh** [comment]
I agree, TS is not a neurodegenerative disorder.

**Comment by nicolevasilevsky** [comment]
thanks, I'll take care of this
