### ISSUE TITLE
Revise classification of MONDO:0003569 'cranial nerve neuropathy'

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#603]
MONDO:0003569 'cranial nerve neuropathy' is currently a subclass of 'nervous system disorder'.
But cranial nerves are part of the peripheral nervous system, so 'cranial nerve neuropathy' should be a child of the more granular 'peripheral nervous system disease'. Thanks.

**Comment by cmungall** [comment]
The challenge here is cranial "nerve" II, see

https://github.com/obophenotype/uberon/issues/298#issuecomment-328315480

I think all solutions are equally horrible here, open to suggestions!

**Comment by paolaroncaglia** [comment]
@cmungall 
Sorry for the late reply. I don't really have any suggested solution in alternative to your 'compromise' in UBERON. But I won't close this ticket as I see that Nicole has it as a card in her "To do" GH project. Thanks!
