### ISSUE TITLE
Add Additional Information to Rare Disease Terms

### ISSUE THREAD

**Issue by sRobertsNORD** [monarch-initiative/mondo#6033]
Please add gene mutation information to the rare disease terms. @matentzn

**Comment by matentzn** [comment]
This is now done in #5829 

Thanks @sRobertsNORD for the request. Feel free to review the added gene mutations in this file:
https://github.com/monarch-initiative/mondo/blob/subsets-system/src/ontology/subsets/mondo-rare.json

The URL will change though so this is only for testing.
