### ISSUE TITLE
add Exscientia to Mondo users list on website

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6042]
Exscientia is an AI-driven pharmatech company committed to discovering, designing and developing the best possible drugs in the fastest and most effective manner.

should be added here:
https://mondo.monarchinitiative.org/pages/users/

**Comment by sabrinatoro** [comment]
@nicolevasilevsky : do you have a website for Exscientia ?

**Comment by nicolevasilevsky** [comment]
here you go:
https://www.exscientia.ai/
