### ISSUE TITLE
review 'aarskog syndrome'

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6047]
2 terms: 
MONDO:0007030 - 'autosomal dominant Aarskog syndrome'
MONDO:0010589 - 'Aarskog-Scott syndrome, X-linked'

1) the x-refs were moved around from one term to another. We need to review that these xrefs are correct and also review the synonyms

2) do we need a grouping term? DO (DOID:0111824) and Orphanet (orphanet:915) have one

3) are these 2 diseases actually different diseases? should these be merged?

**Comment by nicolevasilevsky** [comment]
+1 to adding a grouping term.

autosomal dominant and x-linked are different modes of inheritance. I don't think they should be merged

**Comment by cmungall** [comment]
should the AR form also be included?

Let's be very careful with leaf node primary labels to avoid any confusion

**Comment by sabrinatoro** [comment]
There is already a grouping term for the AR term, AD, and x-linked. 
I added DO as an x-ref.
