### ISSUE TITLE
Creation of term: healthy volunteer

### ISSUE THREAD

**Issue by lefailla** [monarch-initiative/mondo#605]
For new term requests, please provide the following information:

## Preferred term label

Healthy Volunteer

## Synonyms

Healthy Participant, Healthy Patient, Healthy Person

## Textual definition

This is a healthy person serving as a control in a research study.

## Suggested parent term

MeSH Heading: Healthy Volunteers
https://meshb.nlm.nih.gov/record/ui?ui=D064368

## Attribution

https://orcid.org/0000-0002-1382-4768

**Comment by nicolevasilevsky** [comment]
@cmungall I spoke to @lefailla on the phone today - they are mapping phenotype and disease information for patients with immunological disorders, and have some patients who are used as healthy controls. This term currently exists in MeSH, and they are thinking about converting their MeSH mappings to MONDO instead. Not sure if we could add this type of term to MONDO?

**Comment by cmungall** [comment]
It's definitely out of scope for MONDO. I would say it's OK to use a mixture of IDs, with MONDO IDs for disease and IDs from other sources for other concepts.

If an OBO ID is required, you could request a MESH equivalent in OBI or OGMS, but I don't think this necessarily helps @lefailla

**Comment by RS060115** [comment]
Thanks for the comments Nicole and Chris. We are trying very hard to use a single unifying ontology for our large study of patients with genetic diseases. But it sounds like you are saying that control subjects (who can also have phenotypes) would not have an identifying label in MONDO. Is this correct?

**Comment by cmungall** [comment]
This is correct. If I may suggest, I think it's a good idea to design the architecture around the ability to use a set of ontologies that are complementary and work together rather than a single ontology. Also might you not want to use HPO to describe these patients?

**Comment by nicolevasilevsky** [comment]
I think this can be closed. Please reopen if needed.
