### ISSUE TITLE
ORPHA:459061 mapping & Developmental delay with short stature, dysmorphic facial features, and sparse hair 2

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6051]
**Mondo term (ID and Label):**
MONDO:0800438 developmental delay with short stature, dysmorphic facial features, and sparse hair 1

**Xref that should be fixed (ID and label):**
ORPHA:459061 "Craniofacial dysplasia-short stature-ectodermal anomalies-intellectual disability syndrome" http://www.orpha.net/ORDO/Orphanet_459061 
This maps to two MIM #s, OMIM: [616901](http://omim.org/entry/616901)  [620062](http://omim.org/entry/620062) and should probabaly move to  MONDO:0031632 developmental delay with short stature, dysmorphic facial features, and sparse hair; which is the PS with these exact same 2 children. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
Also MONDO:0031632 developmental delay with short stature, dysmorphic facial features, and sparse hair should have a second child: "[Developmental delay with short stature, dysmorphic facial features, and sparse hair 2](https://www.omim.org/entry/620062)" OMIM 620062

**Comment by nicolevasilevsky** [comment]
@kanems I added the new term.

I think the Orphanet xref is correct because the Orphanet term references the DPH1 gene as the implicated gene. The xrefs to OMIM are broad to narrow mappings:
https://www.ebi.ac.uk/ols4/ontologies/ordo/classes/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_459061
