### ISSUE TITLE
Merge request for RASopathy + Noonan Syndrome and Noonan-related Syndrome

### ISSUE THREAD

**Issue by larrybabb** [monarch-initiative/mondo#606]
For new term requests, please provide the following information:

There are two terms
[MONDO:0021060](https://monarchinitiative.org/disease/MONDO:0021060) (RASopathy) with no equivalent ids
and
[MONDO:0020297](https://monarchinitiative.org/disease/MONDO:0020297) (Noonan Syndrome and Noonan-Related Syndromes) which originates from [Orphanet:98733](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=98733)

The ClinGen consortium's RASopathy Variant Curation Expert Panel relies on MONDO with their tooling to perform expert curations in this domain. When curation users lookup 'RASopathy' in MONDO they get the first MONDO id above.  However, the end result needs to be shared in ClinVar. Since ClinVar is driven by MedGen and not MONDO, they map the "Orphanet:98733" term to "RASopathy" as an equivalent.  ClinVar requires the submitters to use MedGen or Orphanet or OMIM or MeSH ids during submission. The ClinGen tooling is designed to rely on MONDO's equivalent ids to find a match that is suitable for ClinVar.

When we hit situations like this, we think it would be best for the overall community to be able to work with the resource that is able to provide the best solution. We request that MONDO merge these two terms as they appear to be equivalent or make the argument for keeping them separate and thus requesting Orphanet or OMIM to create an equivalent term that would allow better harmony with downstream system's like ClinVar and ClinGen.

Please let us know if this is possible.

**Comment by cmungall** [comment]
@Orphanet do you agree and will you consider adding a synonym "RASopathy" to Orphanet:98733?

The list of classified diseases
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_98733

Corresponds with the classic RASopathies: https://rasopathiesnet.org/rasopathies/syndromes/

**Comment by larrybabb** [comment]
Has there been any progress or updates to report on this request?

**Comment by cmungall** [comment]
Not sure if the obsolete label was an accident or because we consider merges to involve deprecation

@nicolevasilevsky can you coordinate with orphanet on this one?

**Comment by annieolry** [comment]
Noonan Syndrome and Noonan-Related Syndrome ORPHA:98733 could very likely be renamed rasopathies if we add NF1 and legius to this group. Before doing so, we need to reassess the different annotations/ressources linked to this group for consistency.

**Comment by nicolevasilevsky** [comment]
Thanks @annieolry. @cmungall what are the next steps for us? Should we wait until Orphanet has renamed their terms, or should we move forward with merging these classes in MONDO?

**Comment by annieolry** [comment]
As Rasopathy and Noonan-Related Syndrome are concepts slightly different, they will have different Orpha numbers in the next ORDO release (Rasopathy ORPHA:536391 and Noonan Syndrome and Noonan-Related Syndrome ORPHA:98733). The first one including the second one and also Neurofibromatosis type 1 ORPHA:636, Legius syndrome ORPHA:137605 and Capillary malformation-arteriovenous malformation ORPHA:137667.

**Comment by maglott** [comment]
I see this has not been touched after Orphanet created  ORPHA:536391.  What are the next steps?  Thanks.

**Comment by larrybabb** [comment]
> I see this has not been touched after Orphanet created ORPHA:536391. What are the next steps? Thanks.

Yes, ClinGen is anxious to resolve this on their downstream systems that rely on both MONDO and MedGen. This is particularly troublesome for ClinGen in that they have an expert domain group focused on Rasopathies and would like to consolidate the representation of all of the various ontological and hierarchical associations between the sub-classifications of these diseases.  If there's anything ClinGen can do to assist with the integration of this solution between Orphanet and Monarch so that it is available to downstream users, please let us know.

**Comment by cmungall** [comment]
@nicolevasilevsky can you add the equivalence axioms to Orphanet:536391 and check for consistency with ORDO structure

**Comment by nicolevasilevsky** [comment]
@cmungall not sure what you are asking for?

**Comment by nicolevasilevsky** [comment]
I just need to add an xref to RASopathy (Orphanet:536391)
source: this ticket

**Comment by larrybabb** [comment]
@maglott Hey can you help me understand how long it may take MedGen to ingest this change once it is released?

The ClinGen Rasopathy group has been waiting on this for a while and we'd love to remove our workarounds for having a MONDO rasopathy term that does not map equivalently to a MedGen id. (We are currently using the "noonan and noonan related syndrome" orphanet id which is currently aliased as "Rasopathy" in Medgen.

Any ideas or direction on who I can get this info from would be appreciated.

@nicolevasilevsky Do you have any estimates on when this will be available in EBI OLS or MonarchIntiative's website?

**Comment by maglott** [comment]
@larrybabb , we have no automated exchange set up, so the mention is the best way to move this along.
If I understand you correctly,  MedGen needs to  split ORPHA:98733 out of RASopathy, so Noonan will be under both RASopathy and Noonan and Noonan related syndrome

**Comment by larrybabb** [comment]
@maglott Here's the classification hierarchy that Orphanet ended up with (which will be reflected and mapped into MONDO - once the linked pull requests associated to this thread is committed.)

![orpha-ras1](https://user-images.githubusercontent.com/959003/61460653-29268400-a93d-11e9-9a29-7ad55c0a170e.png)


And here's how Noonan and Noonan Related Syndrome's children were impacted (if at all)

![orpha-ras2](https://user-images.githubusercontent.com/959003/61460802-7f93c280-a93d-11e9-9161-178a1375dac1.png)

**Comment by maglott** [comment]
OK, I now see that the MONDO changes were not merged yet.  
Sure, MedGen will add a term for Noonan and Noonan related syndrome and move the Orphanet ID there.

**Comment by nicolevasilevsky** [comment]
@larrybabb I created a pull request with the changes and am waiting for @cmungall to review and merge it. Mondo is released around the first of every month and OLS is released around the 15th of each month - so the edits should be visible in OLS then. 

@cmungall or @kshefchek when will changes in Mondo be visible in Monarch? I don't know the answer to the question.

**Comment by larrybabb** [comment]
@nicolevasilevsky after this change will **Noonan Syndrome** be removed from **Rasopathy** as a child? In Orphanet's ontology **Noonan Syndrome** is not a **Rasopathy** child element. Also, will **Noonan and Noonan-Related Syndromes** end up as a child of **Rasopathy** in MONDO, so that all of these concepts end up with a consistent set of associations and thus equivalent conceptual meaning to the domain experts that would like to apply these terms in the knowledge they are building and ClinGen and sharing publicly in ClinVar?

**Comment by nicolevasilevsky** [comment]
Hi @larrybabb 

'Noonan Syndrome' is still a child of 'Rasopathy'
![image](https://user-images.githubusercontent.com/6722114/62957095-f9866280-bda8-11e9-847c-c066452616ec.png)

'Noonan Syndrome' is also classified as a child of 'Noonan syndrome and Noonan-related syndrome' (which is not a child of Rasopathy)
![image](https://user-images.githubusercontent.com/6722114/62957348-774a6e00-bda9-11e9-8c25-5b1e69648ec5.png)

In Orphanet, it looks like 'Noonan Syndrome' is a child of 'Noonan and Noonan-Related Syndrome', which is a child of 'Noonan Syndrome':
![image](https://user-images.githubusercontent.com/6722114/62957192-233f8980-bda9-11e9-876e-fd20b74b99a9.png)

I am unsure if we properly addressed this ticket, but I am a bit confused what is needed.

Orphanet:536391 RASopathy is now equivalent to MONDO_0021060 RASopathy

**Comment by larrybabb** [comment]
I really think this is outside my area of expertise, but I feel fairly certain that folks will be quite confused if **Noonan syndrome and Noonan-related syndrome** is a child of Rasopathy in Orphanet but not in MONDO.  When the Rasopathy expert group asked to have the Rasopathy Orpha id associated with the Rasopathy mondo term (originating from EFO I think?), I believe they presumed that MONDO would follow the prefered hierarchical/ontological structure for Rasopathy in Orphanet.  They still seem quite different, which from my perspective makes the concepts seem quite different.  Doesn't the association to terms (parent and children) give meaning to the concept itself? If so, then how can we claim equivalence if they share very different hierarchical relationships?

So sorry for all the questions and confusion. I'm simply trying to help the ClinGen users understand how we can leverage MONDO to represent the organization of diseases that best represents the way they understand the concepts in play.

**Comment by larrybabb** [comment]
In reviewing the thread above, I believe @annieolry from Orphanet made a decision to add the Rasopathy->"Noonan syndrome and Noonan-related syndrome"->Noonan Syndrome structure versus renaming or merging the Rasopathy and "Noonan syndrome and Noonan-related syndrome" concepts together. This may be where the more comprehensive change in Mondo got lost.

From the [Mar 20 comment](https://github.com/monarch-initiative/mondo/issues/606#issuecomment-474863421) above: 

>As Rasopathy and Noonan-Related Syndrome are concepts slightly different, they will have different Orpha numbers in the next ORDO release (Rasopathy ORPHA:536391 and Noonan Syndrome and Noonan-Related Syndrome ORPHA:98733). The first one including the second one and also Neurofibromatosis type 1 ORPHA:636, Legius syndrome ORPHA:137605 and Capillary malformation-arteriovenous malformation ORPHA:137667.

**Comment by nicolevasilevsky** [comment]
@larrybabb thanks for clarifying! I will

**Comment by nicolevasilevsky** [comment]
The PR was merged, so I think this can be closed now
