### ISSUE TITLE
Mondo to genes

### ISSUE THREAD

**Issue by fjlogrono** [monarch-initiative/mondo#607]
Is there any way to get out of a mondo code, a list of genes?

There is a call in the monarch API, but the result is too complex to extract a list of genes for each disease code.

It would also be interesting to be able to use OMIM or MGI code, which is what this call returns:
https://monarchinitiative.org/analyze/phenotype.json?input_items

That is, from a code MONDO, OMIM, or MGI, to obtain a list of genes.

**Comment by cmungall** [comment]
You can use biolink for this: https://api.monarchinitiative.org/api/

**Comment by fjlogrono** [comment]
Thank you. I already knew the API, but there are many cases where there is no result, or it is too complex. That's what I said
An example that does not appear:
OMIM: 614280 -> MONDO: 0013665 -> Epilepsy, Juvenile Myoclonic, Susceptiblity To, 9
