### ISSUE TITLE
FATTY LIVER DISEASE, NONALCOHOLIC, SUSCEPTIBILITY TO, 1 is not a disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#608]
http://omim.org/entry/613282

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0021105

NAFLD1 and NAFLD2 are not diseases they are suceptibility loci that should be assigned to the disease 

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0013209

THere are still many instances of this mistake in MONDO!

**Comment by nicolevasilevsky** [comment]
We are meeting with Ada in January to work on susceptibility terms and make a proper plan, I am going to close this because it should be addressed in our big push.
