### ISSUE TITLE
create DOS-DP patterns for non-human diseases

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6085]
we need templates for non-human diseases. 
These templates would probably be the same as for the human counterpart.

**Comment by sabrinatoro** [comment]
@cmungall and @matentzn I have some questions. Could you please advise? Thank you!
(If this is too long to discuss here, I could bring this up on a call.)

**Question 1:** 
- pattern 1: species-specific disease (e.g. dog diseases)
- pattern 2: infectious disease (e.g 'disease has primary infectious agent' some 'infectious agent')

Do we need a 3rd pattern for "infectious disease in a specific species"? or can we mix the 2 patterns? 


**Question 2:**
We already follow a pattern to relate non-human diseases to their human analogs ("cross-species analog" some 'human disease').
Should a non-human disease have 2 equivalents? for example: 
'infectious disease, non-human animal'
= 'non-human animal disease' and ('cross-species analog' some 'infectious disease')
= 'non-human animal disease' and ('disease has infectious agent' some root)

Note: I am not 100% sure that the "cross-species analog" relation is correct since I don't think it is 100% correct to be passed to the children terms, but this is a different conversation for another issue/time.

**Comment by matentzn** [comment]
> Note: I am not 100% sure that the "cross-species analog" relation is correct since I don't think it is 100% correct to be passed to the children terms, but this is a different conversation for another issue/time.

I think you are right, and I would like to suggest to delete this relationship right after the initial classification is computed. We should not expose the "cross-species analog" relationship to our users, instead, we can use the relationship to classify the diseases and then use sparql to simply add regular mapping predicates to the release files (annotation level) which do not inherit down. If you raise this issue we can solve it in about 20 minutes.

For question 1, the lazy main answer is: generally we only need one pattern (pattern 1) for all diseases. This assumes that there is always an infectious disease counterpart in the human branch that can be used. My assumption is that for your use case, there is not; so you want to add a non-human disease which does not have a human counterpart?

This is best discussed in a call.

**Comment by sabrinatoro** [comment]
From my 1:1 with Nico: 
- we would use the "cross-species analog" relation to get the classification, but we would remove it as part of the release process (ie we would keep the classification but not the relation which would (and should not) get passed to the children)

- RE: DOS-DP pattern: 
    - for all the **non-human diseases that have a "cross-species analog"**: 
          - the pattern should be to use the "cross-species analog" axiom
          - we need to "materialize" the relations used in the human patterns so that the Equivalent in human diseases are inferred to the non-human disease. 
          - example: 'disease has location' (RO:0004026) : add the "SuperProperty Of" (Chain) `'cross-species analog' o 'disease has location' SubPropertyOf: 'disease has location'`

   - for the **non-human diseases that do NOT have an analog in human**:
         - we should create a script that would clone all the human-centric patterns and update them to use the "non-human disease" terms
         - we would therefore only have to maintain human-centric patterns
        

@matentzn could you please review this summary to make sure I got it correctly? (feel free to edit directly if it is easiest).  Thank you !

**Comment by matentzn** [comment]
Yes it is possible, but on closer that, I noticed that the correct pattern here (that is compatible with the normal cross species approach) is:

```
Non-human animal disease and 'has cross-species analog' some {HUMAN DISEASE PATTERN}
```

Which means for example:

```
Non-human animal disease and 'has cross-species analog' some infectious disease and has infectious agent some coronavirus
```

Which means it cannot be represented in OBO format (too complex). Big problem, you will have to check with Chris again.

So we need too discuss this with Chris. For now, don't let this block you though and just add subclass axioms wherever no cross-species analog exist, and maybe add a subset tag or something so we can easily find and curate those when we find a solution.

**Comment by sabrinatoro** [comment]
See DOSDP for genetic disease here: https://github.com/monarch-initiative/mondo/pull/7277

**Comment by sabrinatoro** [comment]
Note that most existing patterns use "MONDO:0000001" for the "disease" variable. MONDO:0000001 is the parent term of "human disease" and "non-human disease", and therefore the pattern could be use for both human and non-human diseases. 

This simplify the creation of pattern for non-human animal diseases, especially since these patterns were to be the same as the human counterparts. 

**TO DO:** review the patterns and make sure that the description is updated to include both human and non-human animal.

**Comment by sabrinatoro** [comment]
pattern for genetic diseases here: https://github.com/monarch-initiative/mondo/pull/7277

**Comment by sabrinatoro** [comment]
Genetic disease pattern is done. 
I am closing this issue and will create more specific one(s) as needed.
