### ISSUE TITLE
disease susceptibility should not be a subclass of disease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#609]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0042489

I would recommend deleting the term disease susceptiblity and all of the children -- this is probably something that we should code in annotations. If we keep the term, then we would need one X susceptibility term for each disease X, right? @cmungall

**Comment by mellybelly** [comment]
Agreed, it should not be a subclass, and we should have the same post-composed logic for anyone wanting to make that annotation as we do internal to MONDO for commonly used precomposed terms.

**Comment by cmungall** [comment]
Still have a few classified as both a disease and a susceptibility e.g.

https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=293822
=
 https://www.omim.org/entry/614456 MELANOMA, CUTANEOUS MALIGNANT, SUSCEPTIBILITY TO, 8; CMM8
