### ISSUE TITLE
Can't load MONDO from PURL

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/mondo#610]
Trying to load MONDO directly from `http://purl.obolibrary.org/obo/mondo.owl` within Protégé results in an error:

```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I am able to download it using `curl`, but it seems like this could be a problem for users.

**Comment by cmungall** [comment]
Does it work with robot / owlapi?

**Comment by balhoff** [comment]
Good point—should have checked that. This works:

```
robot convert -I 'http://purl.obolibrary.org/obo/mondo.owl' -o mondo.ofn
```

So I should probably take this over to a Protégé issue. I'd be curious if you also have this problem using Protégé.

**Comment by cmungall** [comment]
May be the same as this, which is fixed in the latest Protege: https://github.com/protegeproject/protege/issues/817

**Comment by balhoff** [comment]
Still happens with Protégé 5.5.0-beta-8.

**Comment by balhoff** [comment]
Someone else is seeing the same Protege error: https://github.com/protegeproject/protege/issues/849

**Comment by matthewhorridge** [comment]
@balhoff, just to let you know, this is fixed in the 5.5.0-beta-9-SNAPSHOT

**Comment by balhoff** [comment]
Excellent, thank you!

**Comment by nicolevasilevsky** [comment]
closing, please reopen if needed
