### ISSUE TITLE
Non-simple property used in cardinality restriction

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/mondo#611]
MONDO asserts that `disease has basis in feature` is transitive, and RO asserts that `disease has basis in feature` is a subproperty of `has phenotype`. RO also asserts that the inverse of `has phenotype`, `phenotype of` is a functional property.

Because of the transitivity of a subproperty of its inverse, `phenotype of` becomes a ["non-simple property"](https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#The_Restrictions_on_the_Axiom_Closure), and this is incompatible with being used in a cardinality restriction (i.e. being functional).

The transitivity is not in RO.

**Comment by cmungall** [comment]
OK, we should remove the transitivity and make this direct

**Comment by nicolevasilevsky** [comment]
there is a not a property called `disesae has basis in feature`, there is `disease arises from feature`, is that what you meant @balhoff?

**Comment by nicolevasilevsky** [comment]
Oh! This property has two labels!
![image](https://user-images.githubusercontent.com/6722114/54399779-37a61b80-467d-11e9-9ebc-4e480f15ee31.png)

I thought Protege wouldn't let you save the ontology when you have two labels. One of these should be a synonym?

**Comment by mellybelly** [comment]
Protege lets you do that but its against best practice in OBO

**Comment by nicolevasilevsky** [comment]
to do:
remove the label that comes from MONDO and rename the ID to match the RO label

**Comment by mellybelly** [comment]
@cmungall the rdfs:label asserted on this property in the MONDO file is "disease arises from feature", rather than "disease has basis in feature" which is in RO. Can you please replace all usages to use only the RO rdfs label? Also fix the id
