### ISSUE TITLE
add new OMIM + Orphanet terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6133]
[OMIM terms to be added](https://docs.google.com/spreadsheets/d/164M99rbBZ5W3qTdhTk_egBaWdFX0rMnm2l1oMIRuMls/edit#gid=397716875)

**Comment by nicolevasilevsky** [comment]
almost done, the last thing to do is revisit the terms in the [revisit tab](https://docs.google.com/spreadsheets/d/164M99rbBZ5W3qTdhTk_egBaWdFX0rMnm2l1oMIRuMls/edit#gid=1090735904).

Note to self, there is a pending PR with open questions: 
https://github.com/monarch-initiative/mondo/pull/6132

**Comment by nicolevasilevsky** [comment]
Orpahent terms to be added:
https://docs.google.com/spreadsheets/d/164M99rbBZ5W3qTdhTk_egBaWdFX0rMnm2l1oMIRuMls/edit#gid=2040379428

**Comment by nicolevasilevsky** [comment]
note to self, add rejected mappings to this spreadsheet
https://docs.google.com/spreadsheets/d/1_Y7zQSOgmrWCPbcz2LkesH1OwtIgyqXDpshMEc_pMmQ/edit#gid=0

**Comment by nicolevasilevsky** [comment]
@sabrinatoro I added a couple rejected OMIM terms to the [Mondo mappings](https://docs.google.com/spreadsheets/d/1_Y7zQSOgmrWCPbcz2LkesH1OwtIgyqXDpshMEc_pMmQ/edit#gid=0) spreadsheet - do I need to do anything else?

I have a question about the terms below - do you think we should add them to Mondo or reject them?

1. schistosoma mansoni infection, susceptibility/resistance to | OMIM:181460
2. fatty liver disease, protection from | OMIM:620116

**Comment by sabrinatoro** [comment]
Thank you @nicolevasilevsky 
yes, these rejected omim should also be added to the .tsv file, as explained [here](https://mondo.readthedocs.io/en/latest/editors-guide/exclusion-reasons/)
"Exclusion lists are in the .tsv format and maintained in this folder: mondo-ingest/src/ontology/config/. Each source has its own term exclusion list(e.g [mondo-ingest/src/ontology/config/icd10cm_exclusions.tsv](https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/config/icd10cm_exclusions.tsv))"

Let me know if you want me to do it.

**Comment by nicolevasilevsky** [comment]
@sabrina
I have a question about the terms below - do you think we should add them to Mondo or reject them?

schistosoma mansoni infection, susceptibility/resistance to | OMIM:181460
fatty liver disease, protection from | OMIM:620116

(Note to self, these are in this [spreadsheet](https://docs.google.com/spreadsheets/d/164M99rbBZ5W3qTdhTk_egBaWdFX0rMnm2l1oMIRuMls/edit#gid=1090735904))

**Comment by sabrinatoro** [comment]
OMIM:181460
This term is not a disease term. Also, no genes are associated with it, which I think would disqualify it (since we are only adding genetic sensitivity terms, right?). So I would add it to the exclusion list. I would use the exclusion code "MONDO:excludeRiskFactor"

OMIM:620116
I don't think this is a disease term. I would exclude it with the exclusion code "MONDO:excludeRiskFactor" (though we should update the description to say "increases or decreases the chance of developing a disease". 

@nicolevasilevsky, would you agree?

**Comment by nicolevasilevsky** [comment]
yep, sounds good! I'll add these to the exclusion list, thanks!
