### ISSUE TITLE
create a new 'new term request' template based on OBO foundry yaml file

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6145]
see
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/.github/ISSUE_TEMPLATE/new-ontology.yml

- can add validation, like ORCID format
- @hrshdhgd and @matentzn may be able to combine this with KGCL

**Comment by nicolevasilevsky** [comment]
I created the new template:
https://github.com/monarch-initiative/mondo/blob/master/.github/ISSUE_TEMPLATE/add-term.yml

It's awesome, I love it. 😍

**Comment by matentzn** [comment]
Action items?

**Comment by nicolevasilevsky** [comment]
the action item is to use KGCL, if someone asks for a new term, the KGCL pipeline would create a PR with the new term. I think we investigated this but I'm not sure if this is still something we want to do? This can be closed if so.

**Comment by matentzn** [comment]
@hrshdhgd how did we leave this issue? Can we make it that ontobot has to be deliberately triggered? A term request is made, then a curator says "Hey ontobot, make it so!"

And then the PR is created;

**Comment by hrshdhgd** [comment]
I think I already implemented this. Let me check.

**Comment by matentzn** [comment]
My question was more: 

1. User creates issue
2. Only if mondo curator says: ok, lets make a PR, it tells ontobot to do so

Does this logic exist?

**Comment by hrshdhgd** [comment]
Nope, that was never established as far as I know.

**Comment by matentzn** [comment]
Lets close this issue and revisit one the day of reckoning comes.
