### ISSUE TITLE
Protege setup documentation

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#6151]
The documentation for setting up Mondo in Protege is really excellent.
However, it seems like the new Protege version (5.5) is now doing the id-ranges **automatically** and so part of the documentation needs to be revided - 
https://mondo.readthedocs.io/en/latest/editors-guide/a-protege-setup/

- [x] Set up Docker[¶](https://mondo.readthedocs.io/en/latest/developer-guide/set-up-docker/#set-up-docker)
Check back soon. -- would be nice to address this

**Comment by nicolevasilevsky** [comment]
to do:

update Mondo documentation and OBO Academy

The new version looks at the ID range file and matches your user name in Protege to the names in the file to automatically set up your ID range. Thus as long as this information matches you no longer need to set the ID range. You will get a message if your user name does not match one in the file asking you to pick an ID range.
