### ISSUE TITLE
juvenile cataract-microcornea-renal glucosuria syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#6158]
**Mondo term (ID Label)**
juvenile cataract-microcornea-renal glucosuria syndrome

**Bug/Typo/Error description**
This term is inferred to be an inherited kidney disorder, as are tons of other "wrong" assertions. Could we discuss what the problem is, I am completely confused.

For some reason, I did not see this and it makes the branch I was working on difficult to merge. However, the majority of the assertions are probably things we do not want here. I cannot start fixing this without understanding where the false inferences are coming from.

Honestly it is not easy to work on this if key assertions like this are left only to the reasoner -- it is not possible to move things around in the inferred view. The inference that is done in this way will tend to make a completely flat hierarchy under inherited kidney disorder, and this is just not very useful. Can we do this in another way? I have no idea how to combine both methods.

I think I need to abort the branch I am working on @matentzn @cmungall is there some way of fixing this?

**Comment by nicolevasilevsky** [comment]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/6722114/229649728-61c8bdd0-f671-4359-bb01-233844f24c48.png">
if you click on the question mark next to the inferred parent, Protege will give you an explanation as to why the classification was inferred

here is the explanation

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/6722114/229649824-30765f1f-bfb1-4098-9dfa-de4df123613b.png">

the parent 'nephropathy secondary to a storage or other metabolic disease' comes from Orphanet, and we can exclude this. We're in the process of reviewing all of the parents that come from Orphanet, it's a slow process.

**Comment by nicolevasilevsky** [comment]
@pnrobinson I excluded the superclass 'nephropathy secondary to a storage or other metabolic disease' from all of its children, and this should clean up the 'inherited kidney disorder' branch a bit - I think there are still some diseases that probably don't belong there still.

If you could pull the file after i merge the PR (#6159) and look at the mondo-edit.obo file and tell me which classes are incorrectly classified as a child of 'inherited kidney disorder', I can work on cleaning it up.

**Comment by nicolevasilevsky** [comment]
I think this has been addressed, we cleaned up this branch. Closing.
