### ISSUE TITLE
[Obsolete] 'Mendelian syndromes with cleft lip/palate'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6162]
**Mondo term (ID and Label)**
'Mendelian syndromes with cleft lip/palate' MONDO:0015335

**Reason for deprecation**
Orphanet grouping class that groups by feature

**Suggested term to consider**
MONDO:0003847 'hereditary disease'

@sabrinatoro do you agree?

**Comment by sabrinatoro** [comment]
I agree! :-) 
Thank you!
