### ISSUE TITLE
Review rare disease list from NORD

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6167]
Gioconda reviewed the Rare Disease list from Mondo and has marked some of the conditions for removal or review as well as I have included some comments. 
https://docs.google.com/spreadsheets/d/1zVP6vwhOndT-NZ9dpoQ2bzm6uO4wGCgF/edit#gid=355540054

We should review this list and make changes in Mondo accordingly.

**Comment by nicolevasilevsky** [comment]
I added this to the May milestone, but we can push it back if you need more time. And/or we can work on it together on a curation call.

**Comment by sabrinatoro** [comment]
After reviewing the list of diseases to remove from the RD list, here are several points to consider:
For the following, I assume that all the terms on this list have the "bearer_of some rare" axiom. This might not be correct- some might be "rare" because they are in the gard rare subset.
We will have to think about the best strategy because there are a lot of terms (ie it will take a long time to do this manually), and some axioms are not "straight forward"

1) some terms have been obsoleted in orphanet. We would need to update these x-refs 
2) some terms have the rare axiom from a parent or previous parent, so we will have to review these separately (ie understanding where the rare disease tag comes from and go from there)
3) some terms with the rare axiom are grouping terms. But removing that axiom would also remove the axiom on the children with should keep their RD status.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky and @matentzn 
Am I correct in saying that we decided to add the "NORD rare subset" annotation, and therefore we do not need to update Mondo to reflect the rare disease axioms? 
Does this include "new rare" diseases from NORD (ie we will not add these axioms)?

If everything above is correct, I think this issue can be closed

**Comment by matentzn** [comment]
Yes, I think we dont need a blanket enormous ticket to deal with this issue!

I think on a piece of paper, we do neet to decide what "our" definition is, but that is something for a workshop/discussion

**Comment by nicolevasilevsky** [comment]
@sabrinatoro do you still have open questions? Or do you want to close this ticket?

**Comment by nicolevasilevsky** [comment]
Discussed with Sabrina on curation call and she said it can be closed
