### ISSUE TITLE
ABCA4 Retinopathy MONDO:0800406

### ISSUE THREAD

**Issue by kristyleelowdermilk** [monarch-initiative/mondo#6168]
Hello,

Courtney Thaxton was just requesting to correct the spelling of "retinopathy". Could we change this name back to "ABCA4-related retinopathy" please?

Thanks for considering-

Kristy Lee

**Comment by nicolevasilevsky** [comment]
My bad! Apologies, I will fix it. :)

**Comment by kristyleelowdermilk** [comment]
No worries!  I totally could see how that happened!!

Thanks so much-

Kristy

Kristy Lee, MS, CGC
Genetic Counselor
Associate Professor
Department of Genetics
UNC Chapel Hill
P: 919-843-3158
F: 919-966-4151
***@***.***
