### ISSUE TITLE
Cerebral cortical atrophy HP:0002120 feature of medullary cystic kidney disease?

### ISSUE THREAD

**Issue by GARDInfoCenter** [monarch-initiative/mondo#618]
Medullary cystic kidney disease 1 is currently listed as 1 of the 164 diseases associated with cerebral cortical atrophy (HP:0002120). See attached download from HPO. We have not found any information indicating an association between the two. Additionally, we received an email from a leading researcher in the field stating that this is incorrect. 

Please take a look.

@GARDInfoCenter
ORCID: https://orcid.org/0000-0002-6548-5200
[CerebralCorticalAtrophy_MedullaryCysticKidneyDisease1.xlsx](https://github.com/monarch-initiative/mondo/files/2792466/CerebralCorticalAtrophy_MedullaryCysticKidneyDisease1.xlsx)

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky wanted to check in on this issue. GARD received another e-mail from the same leading expert in kidney diseases we previously referenced. He is concerned that the HPO table has not been updated yet. Do you know whether any progress has been made on this issue? 

Thanks,
@GARDInfoCenter

**Comment by nicolevasilevsky** [comment]
Sorry for the delay, I'll make sure this is posted on the HPO annotations tracker and try to address this ASAP

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter I deleted this annotation, it must have been added as a mistake. Thanks for following up.
