### ISSUE TITLE
[Merge] MONDO:0033211 'diencephalic-mesencephalic junction dysplasia syndrome' 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6197]
**Mondo term (ID and Label)**
MONDO:0033211 'diencephalic-mesencephalic junction dysplasia syndrome' 

**Reason for deprecation**
duplicate

**Term to be merged with**
MONDO:0017868 'diencephalic-mesencephalic junction dysplasia'

**Your nano-attribution (ORCID)**
see: https://github.com/monarch-initiative/mondo/pull/6183

**Comment by dhimmel** [comment]
Thanks @nicolevasilevsky!

Is there a semi-automated process for merging terms? Am interested to learn the contribution workflow here.

**Comment by nicolevasilevsky** [comment]
Yeah, we use owltools:
https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#merge-terms

You can read all of our documentation on this site if you are interested :)
