### ISSUE TITLE
Issues with MONDO:0100009

### ISSUE THREAD

**Issue by eedoh01** [monarch-initiative/mondo#6198]
Hi,

Our curator is unable to use the term above for a ClinGen curation for the ClinGen Congenital Heart Disease GCEP. Our curation needs to be added to ClinGen site as soon as possible? Is there anyway issues with this term can be addressed?

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
Hi @eedoh01 - I see you opened and then closed this issue, has the problem been resolved?
Best,
Nicole
