### ISSUE TITLE
Multiple New Term Requests for MONDO-See Attachment

### ISSUE THREAD

**Issue by lefailla** [monarch-initiative/mondo#620]
Please see attached document.
[New MONDO Terms for GitHub.xlsx](https://github.com/monarch-initiative/mondo/files/2818674/New.MONDO.Terms.for.GitHub.xlsx)

**Comment by nicolevasilevsky** [comment]
@lefailla I moved this spreadsheet into a [google doc](https://docs.google.com/spreadsheets/d/1NGFnxYTGgxSL8D_ZRe6oDHnmt6PrTZNsA3wm3N25v1c/edit#gid=137597887).

I will take a look and may have some comments or questions for you - I'll let you know.

Thanks!

**Comment by lefailla** [comment]
Great! Thank you!

Laura

**Comment by nicolevasilevsky** [comment]
@lefailla - please see the spreadsheet, a few of these terms are phenotypes and terms already exist in the human phenotype ontology - I added links in column F. A few of the terms are already in MONDO, and I added the MONDO IDs and labels in column F.

I have some specific questions about some of the terms, which I'll add as comments below.

**Comment by nicolevasilevsky** [comment]
There are some term requests for infectious agents:
Norovirus
Methicillin-Resistant Staphyococcus Aureus

@lefailla - did you mean 'norovirus infectious disease' and 'methicillin-resistant staphyococcus aureus infectious disease'?

**Comment by lefailla** [comment]
Hi Nicole,

I've added some additional comments to the spreadsheet. That's fine to call
them "infectious disease".  Please let us know if you have any additional
questions.

Thanks,

Laura

**Comment by nicolevasilevsky** [comment]
@lefailla sorry for the delay on working on this, I hope to get to it soon.

**Comment by lefailla** [comment]
No problem.  Thanks for following up.

Laura

**Comment by nicolevasilevsky** [comment]
@ShahimEssaid if you'd like to help with this, please note which terms you add on the google doc, linked above

**Comment by nicolevasilevsky** [comment]
@cmungall and @mellybelly - the first term request on this list is:

**Label:** STAT1 Gain of Function (susceptibility to chronic mucocutaneous candidiasis and autoimmunity)
**Synonym:** STAT1 Gain of Function 
**Definition:** The STAT1 protein helps keep the immune system in balance by controlling the IL-17 pathway. When the STAT1 protein is turned on (activated), it blocks (inhibits) this pathway. In contrast to its inhibitory role in the IL-17 pathway, the STAT1 protein helps promote other immune processes called the interferon-alpha/beta (IFNA/B) and interferon-gamma (IFNG) signaling pathways. The IFNA/B pathway is important in defense against viruses, and the IFNG pathway helps fight a type of bacteria called mycobacteria, which includes the bacterium that causes tuberculosis.
**Source:** https://ghr.nlm.nih.gov/gene/STAT1#conditions

I don't see any other similar terms in MONDO, that are named 'gene gain of function'. Is this a suitable disease to add? It seems to be a cause of MONDO_0015279 'chronic mucocutaneous candidiasis (disease)'
see: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5702932/

Maybe we need to add this to the text def or logical def?

**Comment by nicolevasilevsky** [comment]
@cmungall and @mellybelly 
I have a question about rhinovirus - is rhinovirus synonymous with enterovirus?
See: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=12059&lvl=3&p=mapview&p=has_linkout&p=blast_url&p=genome_blast&lin=f&keep=1&srchmode=1&unlock

**Comment by maglott** [comment]
I vote for any 'gain of function' (GOF) to be a treated as a phenotype/clinical feature rather than a name of a disease.  I know it is a fuzzy boundary, but the abstract of the paper states the GOF leads to chronic mucocutaneous Candidiasis disease, not 'is' chronic mucocutaneous Candidiasis disease

**Comment by cmungall** [comment]
This is a protein

**Comment by nicolevasilevsky** [comment]
@lefailla apologies, this fell off my radar! Are these new terms still needed in Mondo? I can work on this now.

**Comment by nicolevasilevsky** [comment]
Hi @lefailla is this still needed? It fell off my radar again. If yes, I'll prioritize, if not, I'll close. Thank you!
