### ISSUE TITLE
MONDO:0008448 spheroid body myopathy; OMIM 182920

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6203]
**Mondo term (ID and Label):**
MONDO:0008448 spheroid body myopathy

**Xref that should be fixed (ID and label):**
OMIM 182920 is no longer active, has been merged with 609200
MYOPATHY, MYOFIBRILLAR, 3; MFM3, but OrphaNet and GARD still use SBM as their preferred labels, 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
thanks @kanems 

I think MONDO:0008448 spheroid body myopathy should be merged with MONDO:0012215 'myofibrillar myopathy 3' since they were merged in OMIM

**Comment by nicolevasilevsky** [comment]
note to self:

`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0008448 MONDO:0012215 -o -f obo mondo-edit.obo`
