### ISSUE TITLE
Review leukoencephalopathy with vanishing white matter/CACH branch

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6216]
OMIM has recently created an entry that uses "Cree Leukoencephalopathy" as an alternate name (https://www.omim.org/entry/620315), but this is used as a preferred name on MONDO:0020507 (we have to have unique names for submissions to ClinVar or GTR, which is how I found this particular case)

It looks like, perhaps, ORPHA:99854 is equivalent to OMIM PS603896 (based on all 5 EIF2B subunits mapping to both terms).   https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=99854 & https://omim.org/phenotypicSeries/PS603896
Also OMIM 603896 has been renamed ("Leukoencephalopathy with vanishing white matter 1, with or without ovarian failure") so the OMIM x-ref on MONDO:0011380 should also be updated.

**Comment by nicolevasilevsky** [comment]
@ahamosh is [CACH syndrome](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=135) in Orphanet equivalent to the OMIMPS for [Leukoencephalopathy with vanishing white matter](https://www.omim.org/phenotypicSeries/PS603896)?

**Comment by nicolevasilevsky** [comment]
Note to self, these are the 5 subtypes of [Leukoencephalopathy with vanishing white matter](https://www.omim.org/phenotypicSeries/PS603896). These have not been added to Mondo yet.

- OMIM:620313 Leukoencephalopathy with vanishing white matter 3, with or without ovarian failure
- OMIM:620314 Leukoencephalopathy with vanishing white matter 4, with or without ovarian failure
- OMIM:620315 Leukoencephalopathy with vanishing white matter 5, with or without ovarian failure
- OMIM:603896Leukoencephalopathy with vanishing white matter 1, with or without ovarian failure
- OMIM:620312 Leukoencephalopathy with vanishing white matter 2, with or without ovarian failure

**Comment by nicolevasilevsky** [comment]
emailed David at Orphanet:
<img width="1319" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/a59c0994-3aa2-4dbd-b220-f98865e99982">

**Comment by nicolevasilevsky** [comment]
@sabrinatoro 
FYI - there is one outstanding mapping for OMIM (https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/lexmatch/unmapped_omim_lex.tsv) but I am unclear OMIM:620315	leukoencephalopathy with vanishing white matter 5 should be mapped to MONDO:0020507 Cree leukoencephalopathy	or if it should be it's own term. Hopefully I can get some clarification from Orphanet before proceeding.

**Comment by nicolevasilevsky** [comment]
We haven't heard back from Orphanet, I sent them another message on 2023-08-22.

**Comment by ahamosh** [comment]
VWM5 and Cree Leukoencephalopathy are the same condition. The mappings are out of date and incorrect in Orphanet.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh!
