### ISSUE TITLE
Placement of some paralysis terms

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#622]
Hi,

I need to import MONDO:0003757 paraplegia and MONDO:0001590 quadriplegia, and I came across a possible inconsistency in the placement of some paralysis terms in MONDO.

MONDO has: 
nervous system disorder <- palsy <- paraplegia
However, it also has:
nervous system disorder <- central nervous system disease <- hemiplegia
nervous system disorder <- central nervous system disease <- quadriplegia

(EFO has the same as MONDO but lacking paraplegia and quadriplegia:
nervous system disease <- palsy
nervous system disease <- central nervous system disease <- hemiplegia)

Shouldn’t paraplegia, hemiplegia and quadriplegia all be under ‘palsy’?
And should their ancestor be central nervous system disease or rather nervous system disorder? Simply put, my understanding is that the originating damage is to the spine (CNS), but the nerves going down to the limbs are also affected because they don’t communicate with the CNS any more.
Thanks in advance for looking into this.

**Comment by nicolevasilevsky** [comment]
> And should their ancestor be central nervous system disease or rather nervous system disorder?

In Mondo, 'nervous system disease' is a synonym for 'nervous system disorder'
