### ISSUE TITLE
CBL-related disorder

### ISSUE THREAD

**Issue by agrant9394** [monarch-initiative/mondo#623]
For new term requests, please provide the following information:

## CBL-related disorder

The ClinGen RASopathy Expert Panel would like this term to replace the term:
Noonan syndrome-like disorder with juvenile myelomonocytic leukemia  MONDO:0013308. We understand that "gene-related disorder" terms are of last resort, but the phenotypic spectrum associated with this gene is variable and experts have described this RASopathy only in context of the gene, CBL.

## Synonyms

Noonan-like syndrome, NSLL, Cbl mutation-associated syndrome

## Textual definition

CBL-related disorder is a genetic condition caused by pathogenic variants in the Cbl ubiquitin ligase gene, (CBL; HGNC:1541). Due to the proposed mechanism indicating the CBL gene's relationship to the RAS-MAPK pathway and the phenotypic presentation similar to that of the RASopathies, CBL-related disorder should be considered a RASopathy disorder. Though there is a wide spectrum of phenotypic variability, broadly, patients with CBL-related disorder have presented with developmental delay, intellectual disability, neurodevelopmental alterations, prenatal lymphatic anomalies, cardiac malformations as well as vascular anomalies particularly affecting the brain (e.g. Moya-moya arteriopathies), craniofacial features indicative of a RASopathy, hypotonia, feeding difficulties, edema of the legs, musculoskeletal and respiratory thorax abnormalities, ectodermal features including cafe-au-lait spots, immunological and hematological disorders and susceptibility to tumors diagnosed as juvenile myelomonocytic leukemia (JMML) that is usually self-remitting. Note tumor risk beyond JMML has not yet been thoroughly assessed. Due to the clinical presentation of a broad spectrum of these and other phenotypes in patients with variants in CBL, these conditions are currently defined by experts in reference to the causal gene, CBL (PMID's: 20619386, 25283271, 25358541, 28589114, 28414188, 28343148, 24458550, 29259247, 26911351, 21901340, 25952305)"

## Suggested parent term

"Noonan syndrome and Noonan-related syndrome", to be replaced by "RASopathy"

http://purl.obolibrary.org/obo/MONDO_0020297

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/mondo)

## Attribution

This term, description and proposal was developed and reviewed by the ClinGen RASopathy Expert Panel
ORCid's:
Lisa Vincent https://orcid.org/0000-0003-1348-7738
Bruce Gelb https://orcid.org/0000-0002-6559-2858
Danielle Azzariti https://orcid.org/0000-0002-2635-9172
Helene Cave https://orcid.org/0000-0003-2840-1511
Mitchell Dillon https://orcid.org/0000-0001-6671-2252
Andrew Grant https://orcid.org/0000-0002-5791-6891
Karen Gripp https://orcid.org/0000-0001-8200-1733
Jennifer A. Lee https://orcid.org/0000-0003-2890-7483
Heather Mason-Suares https://orcid.org/0000-0002-0146-4881
Katherine Rauen https://orcid.org/0000-0003-1719-7228
Brad Williams https://orcid.org/0000-0002-2827-6880
Martin Zenker https://orcid.org/0000-0003-1618-9269
Kathryn Garber https://orcid.org/0000-0001-9069-3901
Marco Tartaglia https://orcid.org/0000-0001-7736-9672

**Comment by nicolevasilevsky** [comment]
@agrant9394 would ClinGen be able to create a URL that points to the members of the ClinGen RASopathy Expert Panel, that we can reference in our ontology? If not, we can set one up. Thanks!
