### ISSUE TITLE
Missing relationship KCNH2 - long QT syndrome

### ISSUE THREAD

**Issue by lindenb** [monarch-initiative/mondo#6236]
Hi, (sorry I didn't find a template for my issue)

I was playing with http://purl.obolibrary.org/obo/MONDO_0002442 (**long QT syndrome**)  and I was surprised by the absence of relationship with **KCNH2** http://identifiers.org/hgnc/6251 

as far as I can see, KCNH2 is only listed for "short QT syndrome" ( https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fidentifiers.org%2Fhgnc%2F6251 ) but KCNH2 should be listed as a  genetic cause of "long QT syndrome" see https://www.omim.org/entry/152427

Thanks
P.

**Comment by nicolevasilevsky** [comment]
Thanks @lindenb - we will fix this.
