### ISSUE TITLE
Neurofibromatosis 1 parent term RASopathy, merge with neurofibromatosis-Noonan syndrome

### ISSUE THREAD

**Issue by agrant9394** [monarch-initiative/mondo#624]
On behalf of the ClinGen RASopathy Expert Panel, it has been suggested that neurofibromatosis type 1 MONDO:0018975 is a RASopathy. We would like to merge this term with neurofibromatosis-Noonan syndrome  MONDO:0011035 and make one of its parent terms "Noonan syndrome and Noonan-related syndrome" http://purl.obolibrary.org/obo/MONDO_0020297 which we would like to be changed to "RASopathy" and merged with the unlinked version of RASopathy, MONDO:0021060. This last merge has already been requested under #606 

## Attribution

Lisa Vincent https://orcid.org/0000-0003-1348-7738
Bruce Gelb https://orcid.org/0000-0002-6559-2858
Danielle Azzariti https://orcid.org/0000-0002-2635-9172
Helene Cave https://orcid.org/0000-0003-2840-1511
Mitchell Dillon https://orcid.org/0000-0001-6671-2252
Andrew Grant https://orcid.org/0000-0002-5791-6891
Karen Gripp https://orcid.org/0000-0001-8200-1733
Jennifer A. Lee https://orcid.org/0000-0003-2890-7483
Heather Mason-Suares https://orcid.org/0000-0002-0146-4881
Katherine Rauen https://orcid.org/0000-0003-1719-7228
Brad Williams https://orcid.org/0000-0002-2827-6880
Martin Zenker https://orcid.org/0000-0003-1618-9269
Kathryn Garber https://orcid.org/0000-0001-9069-3901
Marco Tartaglia https://orcid.org/0000-0001-7736-9672

**Comment by annieolry** [comment]
This overlapping phenotype continues to be described as such in the recent literature (for instance Ekvall et al, 2014. PMID: 24357598; Vurallı et al, 2016. PMID: 26758488), and are not perfectly included in Neurofibromatosis type 1 as affected patients need appropriate management of Noonan syndrome. 
Orphanet will keep two distinct ORPHA numbers to be able to describe this specific clinical presentation.

**Comment by nicolevasilevsky** [comment]
Thanks @annieolry!

@agrant9394, sorry for the delayed reply! I think Mondo would prefer to follow Orphanet and keep these entities separate.
