### ISSUE TITLE
create rare disease slim

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6245]
30 terms to include all the rare diseases

**Comment by sabrinatoro** [comment]
The suggested grouping terms/slim 'category' for rare diseases are here: 
https://docs.google.com/spreadsheets/d/1Xg3to5ThdQjM6YY6gZ-oE3DFRlU6OwZ_EmejRPJ3W4g/edit#gid=0

@matentzn : I cannot check whether these terms cover all the rare diseases (running the subset requires too much memory that my computer cannot handle). Could you please send me something I can review? Thank you!

**Comment by matentzn** [comment]
Will have to be done in a meeting

**Comment by sabrinatoro** [comment]
@matentzn We are still working on a few things, but I think this issue can be closed. Would you agree?
