### ISSUE TITLE
ClinGen G6PD expert panel suggestion

### ISSUE THREAD

**Issue by mweaver88** [monarch-initiative/mondo#6252]
The ClinGen G6PD variant curation expert panel suggested the following carefully crafted wording changes to two MONDO ID's. @nicolevasilevsky 

To Map on top of: GCPD Deficiency (MONDO: 0005775)
G6PD deficiency – Proposed language:
An X-linked genetic condition caused by alterations in the gene G6PD that result in moderately to severely decreased activity levels of the enzyme glucose-6-phosphate dehydrogenase. Most individuals with G6PD deficiency are asymptomatic. Individuals with G6PD variants that cause G6PD deficiency are at risk for acute hemolytic anemia in response to certain medication exposures, chemical exposures, infections, or consumption of fava beans.
 
To Map on top of: anemia, nonspherocytic hemolytic, due to G6PD deficiency (MONDO: 0010480)
G6PD deficiency, with chronic non-spherocytic hemolytic anemia (CNSHA) – Proposed language:
An X-linked genetic condition caused by alterations in the gene G6PD that result in severely decreased activity levels of the enzyme glucose-6-phosphate dehydrogenase.  Individuals with hemizygous G6PD variants associated with CNSHA have CNSHA. Individuals with G6PD variants that cause CNSHA are at risk for acute hemolytic anemia in response to certain medication exposures, chemical exposures, infections, or consumption of fava beans.

**Comment by sabrinatoro** [comment]
Response to this issue is here: https://github.com/monarch-initiative/mondo/issues/7890
