### ISSUE TITLE
Incorrect synonym of MONDO:0021166 ‘inflammatory disease’

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#626]
MONDO:0021166 ‘inflammatory disease’ has the exact synonym “anatomical structureitis”. This is very cute and presumably the product of an automated script, but you might want to remove it so it doesn’t get propagated… 
Some children of ‘inflammatory disease’ seem to be equally affected, e.g. ‘conjunctivitis’ (inflammation of conjunctiva) has the exact synonym “conjunctivaitis”. Perhaps consider removing synonyms generated by that script, or reviewing them :-) if they are a feature of MONDO rather than inherited from elsewhere. Thanks!

**Comment by cmungall** [comment]
oh dear! will be fixed

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia good catch, there were over 100 of those synonyms (with some pretty funny sounding names). I removed them all, @cmungall could you please review/merge the PR?
