### ISSUE TITLE
[Obsolete] LI-FRAUMENI SYNDROME 2

### ISSUE THREAD

**Issue by MarcyERichardson** [monarch-initiative/mondo#6260]
**Mondo term (ID and Label)**
# 609265
LI-FRAUMENI SYNDROME 2; LFS2

**Reason for deprecation**
This gene disease association is soundly refuted

**Suggested term to consider**
Rebranding for CHEK2 is currently underway with current consensus renaming of "CHEK2-related cancer predisposition"
I believe there may already be a request in place for this update. This request is to mostly remove the LFS2 association

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
0000000246264920

**Comment by sabrinatoro** [comment]
Thank you @MarcyERichardson 
Just to make sure I understand the request. 
You are requesting that we remove the gene association (in this case CHECK2). Is that correct?

**Comment by MarcyERichardson** [comment]
I think the term LFS2 is also obsolete. There is only LFS (and it’s associated with only TP53).

Marcy Richardson, PhD

Associate Director, Clinical Research

Ambry Genetics
Direct 949.457.4658
***@***.******@***.***>
www.AmbryGen.com<http://www.AmbryGen.com/>


[http://www.ambrygen.com/resources/signature/logo.png]


Confidentiality Notice: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, copying, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by nicolevasilevsky** [comment]
Ok, so we should obsolete MONDO:0012233 'Li-Fraumeni syndrome 2'?

We'll mark this as an obsoletion candidate. Reason: MONDO:excludeHistoricalDisease

**Comment by MarcyERichardson** [comment]
Than you-perfect!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Megfrone** [comment]
We had also submitted this and told it was a duplicate. Thank you both for working on this! One additional question/comment: does this mean Li Fraumeni Syndrome and Li Fraumeni Syndrome 1 will be merged into one MONDO ID? Right now there is confusion as the two are used interchangeably. Thank you!

**Comment by MarcyERichardson** [comment]
I would vote to merge LFS1 and LFS2 into a single MONDOID that references TP53 ONLY.

Marcy

Marcy Richardson, PhD

Associate Director, Clinical Research

Ambry Genetics
Direct 949.457.4658
***@***.******@***.***>
www.AmbryGen.com<http://www.AmbryGen.com/>


[http://www.ambrygen.com/resources/signature/logo.png]


Confidentiality Notice: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, copying, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by nicolevasilevsky** [comment]
Hi @MarcyERichardson - thanks for this recommendation, I'll look into this. I'm traveling this week but I can look into this asap and I'll let you know if I have any questions.

We appreciate your and @Megfrone's expert help. :)

**Comment by Megfrone** [comment]
Well yes there is LFS1 (MONDO 0007903), LFS2 (MONDO 0012233), and then a separate mondo ID for Li Fraumeni Syndrome (MONDO 0018875) and they all should be collapsed and reference TP53 only. (Of note, there is also a LFS-like Mondo ID (0800290)).

**Comment by nicolevasilevsky** [comment]
note to self, review this with @sabrinatoro to ensure we're doing the right approach

**Comment by Megfrone** [comment]
Hello! The TP53 VCEP is getting ready to resume curation and just wanted clarity on which MONDO ID we should plan on using for future curations. With MONDO 0012233 being obsoleted LFS1 (0007903) and LFS (0018875) are redundant.

**Comment by nicolevasilevsky** [comment]
Hi @Megfrone - please use MONDO:0018875

**Comment by nicolevasilevsky** [comment]
I am addressing this on this ticket:
https://github.com/monarch-initiative/mondo/issues/6269

closing this one.
