### ISSUE TITLE
Request for new term [Lissencephaly spectrum disorder with complex brainstem malformation]

### ISSUE THREAD

**Issue by Bryannavanhoute** [monarch-initiative/mondo#6271]
### Label

lissencephaly spectrum disorder with complex brainstem malformation

### Synonym type

None

### Definition

Lissencephaly spectrum disorder with complex brainstem malformation manifests as posterior predominant pachygyria (ranging from mild severity to classic lissencephaly) and brainstem malformations which include brainstem dysplasia (typically with reduced anteroposterior thickness and transverse broadening of the pons/medulla) and midline crossing defects (anterior commissure, transverse pontine fibers, pyramidal tract, callosum hypoplasia).

### Parent term

MONDO:0018838 lissencephaly spectrum disorders

### Children term(s)

MONDO:0032677 lissencephaly 9 with complex brainstem malformation

### Website URL

https://www.clinicalgenome.org/affiliation/40020/

### Additional comments

@erinriggs

**Comment by Bryannavanhoute** [comment]
Hi Nicole, I can't seem to find this new term. I believe it states this was to be in the June release. Would you be able to tell me the MONDO ID?

Thank you!

**Comment by nicolevasilevsky** [comment]
MONDO:0100472

https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0100472
