### ISSUE TITLE
Unusual syntax in some ICD10 database cross-references?

### ISSUE THREAD

**Issue by turbomam** [monarch-initiative/mondo#628]
I ran a SPARQL query to compare some MonDO database cross-references to the `skos:notation`s of the terms in  <http://bioportal.bioontology.org/ontologies/ICD10CM>

Out of ~ 100,000 cross-references, it looks like there are only ~ 300 that don't match perfectly, a smaller number of unique mismatches, and probably just a small number of patterns.

1. Could someone please address `obo:MONDO_0017775`'s reference to ICD10:A24.4, which doesn't appear to be in use anymore?
1. What do  `+` and `*` mean as suffixes?  The standard regular expression rules "at least one additional charter" and "potentially additional characters"?

s | o | strafter | replacement | reason
-- | -- | -- | -- | --
obo:MONDO_0000819 | ICD10:00.0 | 00.0 | Q00.0 | Missing character
obo:MONDO_0013946 | ICD10:23.0 | 23.0 | E23.0 | Missing character
obo:MONDO_0000916 | ICD10:A00.A09 | A00.A09 | A00-A09 | Period based range
obo:MONDO_0005550 | ICD10:A00.B99 | A00.B99 | A00-B99 | Period based range
obo:MONDO_0018076 | ICD10:A15.A19 | A15.A19 | A15-A19 | Period based range
obo:MONDO_0017775 | ICD10:A24.4 | A24.4 |   | Retired?
obo:MONDO_0018059 | ICD10:A39.0+ | A39.0+ |   |  
obo:MONDO_0006015 | ICD10:E35.1* | E35.1* |   |  

```
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select *
where {
    graph obo:mondo.owl {
        ?s oboInOwl:hasDbXref ?o .
        filter(contains(?o, "ICD10"))
    }
    graph <http://data.bioontology.org/ontologies/ICD10CM/> {
        bind(strafter(?o, "ICD10:") as ?strafter)
        minus {
            ?s2 skos:notation ?strafter
        }
    }
}
```

**Comment by joeflack4** [comment]
Related to: https://github.com/monarch-initiative/mondo-ingest/issues/11

**Comment by matentzn** [comment]
Closing in favour of https://github.com/monarch-initiative/mondo-ingest/issues/11, and it is almost fixed now.
