### ISSUE TITLE
MONDO:0024677 pancreatic insulinoma & MONDO:0005048 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6281]
**Mondo term (ID and Label)**
MONDO:0024677 pancreatic insulinoma

**Reason for deprecation**
These seem to be the same concept. UMLS maps both NCI codes to the same CUI: C0021670 (as well as mapping MeSH D007340 to this CUI, also)

**Term to be merged with**
MONDO:0005048  pancreatic insulin-producing neuroendocrine tumor
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

Also, SNOMEDCT code 302822000 is reported by UMLS as obsolete.

**Comment by nicolevasilevsky** [comment]
note to self
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0024677 MONDO:0005048 -o -f obo mondo-edit.obo`

**Comment by nicolevasilevsky** [comment]
@kanems this would cause a proxy merge between two NCIT terms, and we defer to NCIT for representation of cancer terms. Let me check with them before proceeding with this merge.

**Comment by nicolevasilevsky** [comment]
@kanems I checked with NCIT and they said these two terms should remain separate concepts:

From email:

"Our pathologists say that these two tumors are not the same. They should not be merged."

"The two tumors are not the same. Pancreatic insulin-producing neuroendocrine tumor subsumes pancreatic insulinoma . Not all pancreatic insulin-producing tumors manifest with the endocrine syndrome of insulin overexpression- when they do, they are called insulinomas."

**Comment by nicolevasilevsky** [comment]
I will close this issue.
