### ISSUE TITLE
Ensure all rare OMIMs are classified under rare disease

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#629]
Related to #170 

We want to make sure that any rare OMIMs are classified under rare disease (note we will later obsolete this grouping class, but we will retain a property).

The 4th column here shows there are many OMIMs that are not categorized as rare

![image](https://user-images.githubusercontent.com/50745/53455785-8d719700-39e0-11e9-936b-7106d10f45dc.png)

From https://github.com/monarch-initiative/mondo-analysis/blob/master/Mondo_Analysis_seaborn.ipynb

I believe the default for any mendelian should probably be rare

**Comment by nicolevasilevsky** [comment]
@cmungall is there a way to give me a list of all the OMIM diseases that are not classified as rare diseases but should be?

I can then add this superclass assertion in Protege.

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @ShahimEssaid said they can help with this too

**Comment by nicolevasilevsky** [comment]
@cmungall, Deepak sent me a list of all the OMIM diseases that are not classified as rare-should all of these diseases should have the super class assertion rare disease? Should I do this manually in Protégé? I'm happy to do so, but just want to make sure there not a way to do it automatically, as doing this manually will take some time.

**Comment by pnrobinson** [comment]
@nicolevasilevsky can you send me this list?

**Comment by nicolevasilevsky** [comment]
Sure thing - I uploaded it to google drive here: https://docs.google.com/spreadsheets/d/1x9VCToGoEOY9XIYOc4IDDAA450dvmuADy_G5QI7tZRo/edit#gid=1666029332

**Comment by cmungall** [comment]
Let's first obsolete any new entries in
https://github.com/monarch-initiative/hpo-annotation-data/blob/master/rare-diseases/annotated/omit-list.txt,
we can script this

**Comment by pnrobinson** [comment]
Would it be better to just drop the "rare" as an upper level classifier? We could instead add an attribute such as prevalence, which could be set to either Orphanet's prevalence or just "rare" (some ontology term) for OMIM entries for which we have no specific data.

**Comment by pnrobinson** [comment]
@cmungall @nicolevasilevsky  -- the categorization "is rare" in this file seems to be often wrong (unless it is being used as a flag to denote legacy or entries otherwise deemed to be of low quality)

**Comment by mellybelly** [comment]
It seems to me we'd want the upper classifier but only populate it based on inference from an attribute. I don't know that all OMIM diseases should be considered Rare? we need to know prevalence to determine that. Sorry if i missed something, agree with Peter.

**Comment by mellybelly** [comment]
Things like sickle cell anemia and Tay–Sachs disease are not really rare (though obviously both demographic dependent).

**Comment by cmungall** [comment]
Yes, remember there is a ticket for obsoleting all rare-X terms (replace
with a property) including the rare root, we are just using this now
because that is what was required for the analysis. Anything currently
classified under rare comes from ORDO, you can see the complete provenance
as axiom annotations in the OWL version.

**Comment by pnrobinson** [comment]
I would say that sickle and Tay Sachs *are* rare, in the biological sense, and certainly each of these diseases is rare in most populations. It does not make sense to use the prevalence as something that is extremely meaningful!

**Comment by mellybelly** [comment]
well, ~2% of Nigerian kids are born with Sickle cell disease. rare worldwide, but not in some places ;-). We need to refine the model and definitions to build  this on the fly. Big project to do well...

**Comment by nicolevasilevsky** [comment]
is there an open action item here?

**Comment by nicolevasilevsky** [comment]
can this be closed?
