### ISSUE TITLE
[NTR] NKX2-1

### ISSUE THREAD

**Issue by elliebroeren** [monarch-initiative/mondo#6296]
**Preferred gene-related syndrome label**
*NKX2-1* related choreoathetosis and congenital hypothyroidism with or without pulmonary dysfunction

**Synonyms**
N/A

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
[syndromic hypothyroidism](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0015778&lang=en&viewMode=PreferredRoots&siblings=false) 

**Definition**
The NKX2-1 gene is located on chromosome 14 at 14q13.3 and encodes the NK2 homeobox 1 protein, a transcription factor that binds and activates thyroid specific genes. NKX2-1 was first reported in relation to autosomal dominant NKX2-1 related choreoathetosis and congenital hypothyroidism with or without pulmonary dysfunction in 1998.

**Definition source 
Devriendt et al., 1998, PMID: 9565498

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
N/A

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by elliebroeren** [comment]
> @elliebroeren do you have an ORCID I could add to this new term?
Yes! It is 0009-0009-9147-3105

**Comment by nicolevasilevsky** [comment]
thanks!
