### ISSUE TITLE
MONDO:0007779 autosomal dominant Opitz G/BBB syndrome[Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6312]
**Mondo term (ID and Label)**
MONDO:0007779 autosomal dominant Opitz G/BBB syndrome

**Reason for deprecation**
Orphanet and OMIM have both obsoleted/merged their records that this Mondo ID points to as x-refs and UMLS has also retired their CUI for this concept. 

**Suggested term to consider**
MONDO:0800025 TEEBI HYPERTELORISM SYNDROME 1

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@M-casado, thanks for reporting this, we'll look into it.

**Comment by nicolevasilevsky** [comment]
I added [MONDO_0017138](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0017138) as a term to consider.
