### ISSUE TITLE
Do not create proxy merges when merging

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#6331]
An example of a recent Mondo PR that created a proxy merge:

- #5438.  

I think the merge is justified according to the analysis in the issue:

- #5061.

however, we end up with this:

```
xref: Orphanet:73220 {source="MONDO:equivalentTo", source="MONDO:preferredExternal", source="OMIM:309580"}
xref: Orphanet:93971 {source="MONDO:equivalentTo", source="OMIM:309580"}
xref: Orphanet:93973 {source="MONDO:equivalentTo", source="OMIM:309580"}
xref: Orphanet:93974 {source="MONDO:equivalentTo", source="OMIM:309580"}
```

This is not correct, because the other 3 Orphanets are all obsolete, so this is a fake proxy merge, and we should:

- these should be `equivalentObsolete`
- there is no need for busy-work making a `preferredExternal` in this case, because there is only one true equivalence

Currently these false equivalencies are playing havoc with our attempts to use boomer (cc @balhoff @matentzn @hrshdhgd )

Fortunately there is an easy solution: we just write a script that changes equivalentTo to equivalentObsolete if the external is obsolete.

But I am guessing the workflow that originally created this was:

- curator did a merge in protege or owltools, which propagates the xrefs+annotations
- PR failed because this resulted in a proxy merge with no preferred member
- It is too tedious two change the existing 3 xrefs, so the curator instead opted to keep this a fake proxy merge and instead tagged one external

The way to avoid this situation in the first place is to regularly change equivalentObsolete to preferredExternal, and to ideally do this before tackling merges.

**Comment by matentzn** [comment]
The immediate problem is solved, but before closing this I would like to 

- [ ] Organise a separate call between @sabrinatoro @nicolevasilevsky and me to discuss and review existing high priority proxy merges

**Comment by nicolevasilevsky** [comment]
we have a meeting scheduled on 06/23

**Comment by matentzn** [comment]
I think this is our "proxy" issue for reviewing the proxy merges, no? Or do we have another one for that?

**Comment by nicolevasilevsky** [comment]
No,  I don't think there is another issue. Ok, let's keep this open until we are done reviewing the proxy merges.

@sabrinatoro the spreadsheet is [here](https://docs.google.com/spreadsheets/d/1G98Zs1MOJBXcIZKdjxsEHmAqWCm-M_XL_cmLZCUItg4/edit#gid=0).

**Comment by nicolevasilevsky** [comment]
we are done reviewing proxy merges, closing
