### ISSUE TITLE
Dyadic approach to disease names

### ISSUE THREAD

**Issue by azankl** [monarch-initiative/mondo#6333]
The 2023 Skeletal Dysplasia Nosology has started using the dyadic approach to disease naming:
https://onlinelibrary.wiley.com/doi/10.1002/ajmg.a.63132

I would prefer a slightly different approach, where disorders that only have a single gene associated do not need to list that gene in their name, e.g. MONDO:000703 should be called 'Achondroplasia', instead of 'Achondroplasia, FGFR3-associated'.

Does MONDO have specific rules about how to name diseases? Who decides how a disease will be named (or more specifically, what the preferred label should be)?

See also my related question about Capitalisation of disease names (https://github.com/monarch-initiative/mondo/issues/6332#issue-1747173728)

**Your nano-attribution (ORCID)**
0000-0001-8612-1062

**Comment by nicolevasilevsky** [comment]
Hi @azankl - we have a disease naming document here:
https://mondo.monarchinitiative.org/pages/disease-naming/

Please let us know if there are further questions and feel free to reopen

**Comment by azankl** [comment]
Hi @nicolevasilevsky I just noticed that MONDO seems to have started using the dyadic approach after all, for example MONDO:0014299  `schwannomatosis 2` was renamed to `LZTR1-related schwannomatosis` in the latest release. Do you have a document/policy that explains how exactly you apply this? For example, is there a rule if the gene should precede or follow the disease name (I found `LZTR1-related schwannomatosis`, but also `congenital muscular dystonia SLC6A5-related, cattle (MONDO:1012684)`). Is the naming scheme different for human and other animals? Also, do you advocate adding the gene to the disease name, even if it is the only known disease name? For example, I prefer `Achondroplasia` to `Achondroplasia, FGFR3 related`.
