### ISSUE TITLE
MONDO:0007543 enolase, sperm specific[Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6337]
**Mondo term (ID and Label)**
MONDO:0007543 enolase, sperm specific

**Reason for deprecation**
The OMIM record cited for this is a GENE, not a disease or phenotype. This should not be in Mondo as a disorder.
https://omim.org/entry/131375 

**Suggested term to consider**
None.

**Question for Mondo team**
Would it be possible to remove this before the July release? I know the standard protocol is to give folks time to weigh in, but this is pretty clearly not a disease entry and should not be represented as such. MedGen will have to suppress this record somehow until Mondo resolves this.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Hi @kanems - yes, very good point. I will obsolete this now and will update our guidelines for cases like this.
