### ISSUE TITLE
Reasoning errors currently in the master branch

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#634]
There are a whole bunch of classes showing up under nothing when I reason the ontology with Elk, and I think the error may be due to the equiv axiom on bone development disease.
_edit: it is not just an error with bone development disease. I am unable to figure out the underlying issue._

Shahim and I looked at a bunch of previous commits, back through January, and see these errors in all the commits.

I didn't notice them showing up until after I had been editing for a while too (so I either forgot to run the reasoner each time, or I somehow missed them at first.)

Here are screenshots of one explanation:
![image](https://user-images.githubusercontent.com/6722114/53851886-f1620580-3f74-11e9-8582-99e62c02c2ae.png)

![image](https://user-images.githubusercontent.com/6722114/53852049-6cc3b700-3f75-11e9-8de1-b66eab2e3940.png)

![image](https://user-images.githubusercontent.com/6722114/53852062-7816e280-3f75-11e9-8fb8-0d0692ce7a4a.png)

![image](https://user-images.githubusercontent.com/6722114/53852077-82d17780-3f75-11e9-9545-09d7cbd33e61.png)

**Comment by nicolevasilevsky** [comment]
We see these errors when we checked out the branch b30f0ec

**Comment by cmungall** [comment]
disease_has_location should never be used in conjunction with a process, it's range in an anatomical entity.

The curious thing is why these didn't show up before

Use disease_has_basis_in_disruption_of for diseases that are due to something going wrong with a process

**Comment by nicolevasilevsky** [comment]
Note - these errors are only visible when running ElK 0.5.0 SNAPSHOT. I switched back to Elk 0.3.4 and don't see these errors.

**Comment by nicolevasilevsky** [comment]
I think this is resolved
