### ISSUE TITLE
Exclude UMLS mappings from mondo.sssom.tsv

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#6343]
One way to do it is #6342

**Comment by nicolevasilevsky** [comment]
Note - 2023-06-23: On technical call, we decided not to do this for now and to fold in Megan's suggestions (there is a massive file with corrections) and then re-run the analysis to see how many proxy merges are left.

To do - we should find Megan's file

**Comment by nicolevasilevsky** [comment]
this is in progress, revisit in 2 weeks

**Comment by matentzn** [comment]
This is now finished since the last release, thank you Megan!
