### ISSUE TITLE
Amend update_deprecated pipeline

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#6345]
@joeflack4, can you turn this comment into an `sed` command? I provide some pseudocode below. This does not work, and also causes a bug if the second `source=` block is the last in the OBO xref (e.g. `xref: OMIM:601251 {source="MONDO:equivalentObsolete", source="GARD:0010117", source="MONDO:obsoleteEquivalentObsolete"}`). We do _not_ want the `,` before the `}` symbol. 

```suggestion
	sed -i 's/(.*)source="MONDO:equivalentObsolete"(.*)source="MONDO:obsoleteEquivalentObsolete"(.*)/$1source="MONDO:obsoleteEquivalentObsolete"$2$3/g' mondo-edit.obo || true
```

_Originally posted by @matentzn in https://github.com/monarch-initiative/mondo/pull/6344#discussion_r1225835604_

**Comment by joeflack4** [comment]
Hey Nico. Just want to verify my understand It looks like you're asking me to fix the `deprecated_annotation_merging ` [goal](https://github.com/monarch-initiative/mondo/pull/6344#discussion_r1225835604) as you described, using something that works and is similar to the `sed` example that you posted in the above code snippet?

**Comment by matentzn** [comment]
Yes, the PR resulting from this issue should be exactly 1 Line of code added to that goal in the Makefile.
