### ISSUE TITLE
MONDO:0019082 "pemphigoid" alt name

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6355]
**Mondo term (ID Label)**
MONDO:0019082 bullous pemphigoid

**Bug/Typo/Error description**
This record includes a synonym of "pemphigoid" in our latest download , but this is the preferred term on MONDO:0850301. I don't think it should be a syn on one term and pref. name on another.

Also MONDO_0850301 could probably add an x-ref of SNOMED CT 86142006

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
thanks @kanems - I excluded that synonym so it will not be visible in the release version of Mondo and I added the SNOMED xref, thanks!
