### ISSUE TITLE
Newer Orphanet-sourced terms mix[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6356]
**Mondo term (ID and Label)**

mondo_id (newer, to merge) | name | Ref | ID | Mondo_Id (older, to merge into) | name | Ref | ID
-- | -- | -- | -- | -- | -- | -- | -- |
MONDO_0858986 | autosomal dominant spastic paraplegia type 80 | Orphanet | 631068 | MONDO_0032737 | spastic paraplegia 80, autosomal dominant | OMIM | 618418
MONDO_0858987 | autosomal recessive spastic paraplegia type 82 | Orphanet | 631073 | MONDO_0032906 | spastic paraplegia 82, autosomal recessive | OMIM | 618770
MONDO_0858988 | autosomal recessive spastic paraplegia type 83 | Orphanet | 631076 | MONDO_0033614 | spastic paraplegia 83, autosomal recessive | OMIM | 619027
MONDO_0858989 | autosomal recessive spastic paraplegia type 84 | Orphanet | 631079 | MONDO_0030482 | spastic paraplegia 84, autosomal recessive | OMIM | 619621
MONDO_0858990 | autosomal recessive spastic paraplegia type 85 | Orphanet | 631082 | MONDO_0030512 | spastic paraplegia 85, autosomal recessive | OMIM | 619686
MONDO_0858991 | autosomal recessive spastic paraplegia type 86 | Orphanet | 631085 | MONDO_0030673 | spastic paraplegia 86, autosomal recessive | OMIM | 619735
MONDO_0858992 | autosomal recessive spastic paraplegia type 87 | Orphanet | 631088 | MONDO_0031019 | spastic paraplegia 87, autosomal recessive | OMIM | 619966

**Reason for deprecation**
The data in Orphanet for 631076 (as an example) is showing as still in development, and OMIM doesn't link to this Orphanet ID yet, but based on the strings, these look to be the same conditions, in the pairwise relationship outlined in the table above. 

**Term to be merged with**
Pairs:
mondo_id (to merge) | Mondo_Id (to keep)
-- | --
MONDO_0858986	| MONDO_0032737
MONDO_0858987	| MONDO_0032906
MONDO_0858988	| MONDO_0033614
MONDO_0858989	| MONDO_0030482
MONDO_0858990	| MONDO_0030512
MONDO_0858991	| MONDO_0030673
MONDO_0858992	| MONDO_0031019

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
with checkboxes

- [ ] MONDO_0858986 | MONDO_0032737
- [ ] MONDO_0858987 | MONDO_0032906
- [ ] MONDO_0858988 | MONDO_0033614
- [ ] MONDO_0858989 | MONDO_0030482
- [ ] MONDO_0858990 | MONDO_0030512
- [ ] MONDO_0858991 | MONDO_0030673
- [ ] MONDO_0858992 | MONDO_0031019

**Comment by kanems** [comment]
Hi, These pairs still need to be merged in Mondo as of today:
 MONDO_0858989 | MONDO_0030482
 MONDO_0858990 | MONDO_0030512
 MONDO_0858991 | MONDO_0030673
 MONDO_0858992 | MONDO_0031019

**Comment by nicolevasilevsky** [comment]
I will take care of these merges:
- [ ] MONDO:0858989 | MONDO:0030482
- [ ] MONDO:0858990 | MONDO:0030512
- [ ] MONDO:0858991 | MONDO:0030673
- [ ] MONDO:0858992 | MONDO:0031019

**Comment by nicolevasilevsky** [comment]
- [ ] sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0858989 MONDO:0030482 -o -f obo mondo-edit.obo

- [ ] sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0858990 MONDO:0030512 -o -f obo mondo-edit.obo

- [ ] sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0858991 MONDO:0030673 -o -f obo mondo-edit.obo

- [ ] sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0858992 MONDO:0031019 -o -f obo mondo-edit.obo
