### ISSUE TITLE
Reasoning error: infective arthritis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#636]
MONDO_0042485 is currently inferred as a subclass under owl:Nothing when running ELK.

I think the issue is with the equiv axiom on this term, but I'm not sure what the fix is. @cmungall can you provide guidance?

![image](https://user-images.githubusercontent.com/6722114/53917295-0e501480-4019-11e9-8759-60dffa0a0bf6.png)

**Comment by nicolevasilevsky** [comment]
related to #634

**Comment by balhoff** [comment]
I think also related to #547

**Comment by nicolevasilevsky** [comment]
Note - these errors are only visible when running ElK 0.5.0 SNAPSHOT. I switched back to Elk 0.3.4 and don't see these errors.

**Comment by nicolevasilevsky** [comment]
fixed
