### ISSUE TITLE
Relabel MONDO:0000596

### ISSUE THREAD

**Issue by sierra-moxon** [monarch-initiative/mondo#6364]
**Mondo term (ID and Label)**
MONDO:0000596, bestiality

**Reason for deprecation**
I don't see it any longer in the https://www.psychiatry.org/File%20Library/Psychiatrists/Practice/DSM/APA_DSM-5-Contents.pdf table of contents as a disorder

**Suggested term to consider**
zoophilia as a term name instead of bestiality (zoophilia is currently a synonym). 

**Your nano-attribution (ORCID)**
[0000-0002-8719-7760](http://orcid.org/0000-0002-8719-7760)

**Comment by nicolevasilevsky** [comment]
@sierra-moxon would the preference be to obsolete these term or rename it to zoophilia? We can remove the label bestiality and add it as a deprecated synonym that would not be displayed in the release.

**Comment by nicolevasilevsky** [comment]
@sierra-moxon see question above :eyes:

**Comment by sierra-moxon** [comment]
Yes, I think that sounds great to me.  It's a hard one to decide the best approach!

**Comment by nicolevasilevsky** [comment]
Which one? :)  obsolete this term or rename it to zoophilia?

**Comment by sabrinatoro** [comment]
Until we know more about whether this is an actual disease or not (which will require experts), I think we should rename the disease, especially since the term has some x-ref to DO and SCTID.

**Comment by nicolevasilevsky** [comment]
Thanks @sabrinatoro, I can take care of this.

**Comment by nicolevasilevsky** [comment]
@sierra-moxon the ID you referenced above is for 'paraphilic disorder' (MONDO:0000596), but I think the term you want to relabel is MONDO:0004759 bestiality.

I will relabel this to zoophilia
