### ISSUE TITLE
Create Translator UI subset of MONDO terms

### ISSUE THREAD

**Issue by sierra-moxon** [monarch-initiative/mondo#6365]
I'll add to this ticket as folks at Translator explore the ontology, if that is ok?  Translator would like to have a subset of MONDO that excludes terms that don't match their use cases. 

Exclusion rules:
any disease or disorder that is this term or a subclass_of or part_of this term: https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0000947?lang=en

any disease or disorder that is this term or a subclass_of or part_of this term:
https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0000595?lang=en

any disease or disorder that is this term or a subclass_of or part_of this term:
https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0001500?lang=en

**Comment by nicolevasilevsky** [comment]
@sierra-moxon can you comment on the advantage of us creating a specific translator subset vs us giving you two lines of code that achieve the same thing as a preprocessing step for Translator?

**Comment by nicolevasilevsky** [comment]
@sierra-moxon do you think we should actually obsolete these terms that you'd like to exclude in your subset? @sabrinatoro noted we probably need to review the psychiatric disorder branch in Mondo. (There is a related discussion for this: https://github.com/monarch-initiative/mondo/discussions/2678)

**Comment by sierra-moxon** [comment]
Hi @nicolevasilevsky - @matentzn  and I met this morning and he showed me the code to create this -- it works great! :) Thank you both for the help here.  I think we can make this standalone code work for Translator, the benefits here are that Translator folks can work on their own timeline to add/remove terms from the subset.  The drawbacks are that Translator is using a non-official subset from Mondo (but its probably ok).  I'll let you know if there are any concerns with this.  

[monarch-initiative/mondo-translator](https://github.com/monarch-initiative/mondo-translator-subset)

**Comment by nicolevasilevsky** [comment]
that's so cool! Will you be able to update the subset based on the Mondo releases?

Should we close this ticket?

**Comment by sierra-moxon** [comment]
Per the obsoletion questions, I think https://github.com/monarch-initiative/mondo/issues/6366, https://github.com/monarch-initiative/mondo/issues/6364 cover a couple of instances that I found that I think should be obsoleted (and these are included in this exclusion list).  I would agree that the branch itself should be refactored a bit; there are terms not in Mondo that are in the DSM-5 PDF and others that have been changed.

**Comment by sierra-moxon** [comment]
I'm going to close this one as completed! thanks so much again @matentzn!
