### ISSUE TITLE
[Obsolete] gender dysphoria

### ISSUE THREAD

**Issue by sierra-moxon** [monarch-initiative/mondo#6366]
**Mondo term (ID and Label)**
MONDO:0001153, gender dysphoria

**Reason for deprecation**
Gender dysphoria is not considered a disease but rather a diagnostic term used to describe the distress an individual may experience when their gender identity differs from their assigned sex at birth. The removal of the term "disorder" reflects a more contemporary understanding and recognition of gender diversity and seeks to reduce the stigmatization of individuals with gender incongruence.

Alternatively, changing the definition to reflect the diagnostic nature of the term, might be ok?
**Suggested term to consider**

**Your nano-attribution (ORCID)**
[0000-0002-8719-7760](http://orcid.org/0000-0002-8719-7760)

**Comment by sierra-moxon** [comment]
Note also that Diagnostic and Statistical Manual of Mental Disorders (DSM-5) the term "Gender Identity Disorder" (MONDO:0001500) has been replaced with "Gender Dysphoria." 

But is still used as a diagnostic term rather than a disease to treat or cure or otherwise ameliorate.  
Its not clear to me if this is a distinction that can be formalized in MONDO?

**Comment by sierra-moxon** [comment]
The definition here for a subclass of this term does make sense to me :) -- please help us MONDO experts! :) 
 https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0001693?lang=en

**Comment by nicolevasilevsky** [comment]
@sierra-moxon - we discussed this on the curation call and we'll proceed with obsoleting 'gender dysphoria'.

we will also tag 'ego-dystonic sexual orientation' and 'gender identity disorder' for obsoletion. Eric Sid noted that these terms may have been in DSM-IV and may not be in DSM-V. These are not treatable conditions.

to do:
- [ ] create obs ticket for the terms above
