### ISSUE TITLE
leukemia is a "musculoskeletal system disorder"

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6370]
When adding non-human diseases, we realized that leukemia is classified as a "musculoskeletal system disorder", which is weird (and Katie and I think it shouldn't be). 

This classification comes from the fact that leukemia has the SC:
'disease has location' some 'bone marrow'
and
- bone marrow : 'has part' some 'bone element'
- 'bone element' is part of 'skeletal system'

@nicolevasilevsky can we please discuss how we should resolve this? I think I should just remove the SC, but I don't think that there is a "excluded subclass of" equivalent for axiom.

**Comment by nicolevasilevsky** [comment]
I agree that the best approach is to remove the subclassOf axiom.
