### ISSUE TITLE
Request for new term [Pythiosis]

### ISSUE THREAD

**Issue by katiermullen** [monarch-initiative/mondo#6371]
### Label

pythiosis

### Synonym type

None

### Definition

A granulomatous disease caused by the aquatic organism PYTHIUM insidiosum and occurring primarily in horses, cattle, dogs, cats, fishes, and rarely in humans. It is classified into three forms: ocular, cutaneous, and arterial. 

db-xref
MESH:D058968

### Parent term

MONDO:0005550 infectious disease

### ORCID Identifier

https://orcid.org/0000-0002-5002-8648

### Additional comments

The cross-species analog term is
MONDO:0025510 pythiosis, non-human animal

**Comment by ericsid** [comment]
Limited evidence on Pythium insidiosum infections in humans - see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8879638/
