### ISSUE TITLE
Concatenated Equivalent To statement

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6377]
Term: '14q32 duplication syndrome' (MONDO:0014707)

The Equivalent To looks like the concatenation of 2 different Equivalent statements.
<img width="452" alt="Screenshot 2023-06-21 at 8 13 13 AM" src="https://github.com/monarch-initiative/mondo/assets/12737987/65c819bd-27c1-4c4c-83a3-a9033a6fe96e">

I suspect the "inherited disease susceptibility" part was added computationally (maybe via a ROBOT template?). And therefore, there might be other terms with similar errors. 

To Do: 
- make a list of terms with these incorrect Equivalent To 
- review and update automatically.

**Comment by matentzn** [comment]
Lets discuss in 1:1

**Comment by nicolevasilevsky** [comment]
can you document some brief notes from your discussion here, I am curious :)

**Comment by nicolevasilevsky** [comment]
maybe we should add a disjointness axiom between inherited disease susceptibility and disease and then an axiom like this would throw errrors

**Comment by sabrinatoro** [comment]
We talked about making the susceptibility branch and the main disease branch disjointed... however some diseases could be both disease and susceptibility to other disease, so I don't know that it is a good idea in the long run. We should discuss this in a future call.

**Comment by nicolevasilevsky** [comment]
that is true, there are some examples of that, see this ticket: https://github.com/monarch-initiative/mondo/issues/2784
