### ISSUE TITLE
Change curie map for semapv: `#   semapv: https://w3id.org/semapv/` => `#   semapv: https://w3id.org/semapv/vocab/`

### ISSUE THREAD

**Issue by hrshdhgd** [monarch-initiative/mondo#6401]
This is in accordance to the update made on the sssom-py side via https://github.com/mapping-commons/sssom-py/pull/381 .

Without this updated in `mondo.sssom.tsv`, the mondo-ingest pipeline will break. What would be the correct way of doing this here, @matentzn ?

**Comment by matentzn** [comment]
I think this needs a rerun of the pipeline with the latest SSSOM. I will kick of w new ODK release! Good thinking!
