### ISSUE TITLE
Regenerate MONDO

### ISSUE THREAD

**Issue by hrshdhgd** [monarch-initiative/mondo#6412]
Here's the gist: 

1. Get resources from [here](https://github.com/monarch-initiative/mondo-ingest/releases/tag/v2023-06-14)
2. Filter out logical axioms:
  - `robot filter --input mondo.owl --axioms logical mondo.owl`
3. `robot merge` DOID, OMIM, NCIT and result from [2] -> `merged.owl`
4. Run `boomer` with `merged.owl` and ptable from `mondo.sssom.tsv`[**only ontologies mentioned in [3]**] as inputs.
5. Extract base file from the resultant owl file 
  - `robot remove --input tmp/RESULTANT.owl --base-iri http://purl.obolibrary.org/obo/MONDO_ --axioms external --trim true -o mondo-base.owl`
6. Get subclass relationships with ONLY MONDO IDs.
7. Merge with result from [2]

**Comment by nicolevasilevsky** [comment]
cc @sabrinatoro

**Comment by matentzn** [comment]
This wont happen for now; Lets reopen if there is a viable strategy
