### ISSUE TITLE
[Revise subclass] Consider if adenoma of pancreas should be a subclass of adenoma

### ISSUE THREAD

**Issue by rleaman** [monarch-initiative/mondo#6414]
**Mondo term (ID and Label)**
MONDO:0019668, adenoma of pancreas

**Suggested revision and reasons**
MONDO:0019668, adenoma of pancreas, seems to be a type of adenoma. But it is not a subset/descendant of MONDO:0004972, adenoma. Its only parent is MONDO:0021040, pancreatic neoplasm, which does not imply adenoma.

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-3296-5766

**Comment by nicolevasilevsky** [comment]
thanks @rleaman, I added this parent
