### ISSUE TITLE
split 'bleeding diathesis due to thromboxane synthesis deficiency'

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6419]
MONDO:0013524
'bleeding diathesis due to thromboxane synthesis deficiency'

The orphanet x-ref (Orphanet:220443) refers to the disease
The OMIM x-ref (OMIM:614009) refers to the disease susceptibility. 

I think we need to "split" this term and have a 'disease' and a 'disease susceptibility term. 

 @nicolevasilevsky do you agree? 

Unfortunately, we will probably have to obsolete this term and create 2 new one because there is currently no clear meaning for MONDO:0013524

**Comment by sabrinatoro** [comment]
related to #6416

**Comment by sabrinatoro** [comment]
Other example: 
id: MONDO:0011876
name: juvenile absence epilepsy

**Comment by nicolevasilevsky** [comment]
I agree

**Comment by nicolevasilevsky** [comment]
see https://mondo.readthedocs.io/en/latest/editors-guide/f-entities/#susceptibility-terms

**Comment by nicolevasilevsky** [comment]
> Other example: id: MONDO:0011876 name: juvenile absence epilepsy

I will create a separate ticket for this
