### ISSUE TITLE
nongoitrous euthyroid hyperthyrotropinemia

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#642]
For new term requests, please provide the following information:

## Preferred term label

nongoitrous euthyroid hyperthyrotropinemia

## Synonyms

(e.g., Absent spleen)

## Textual definition
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5206697/

## Suggested parent term
MONDO:0009043

**Comment by nicolevasilevsky** [comment]
Hi @maglott, reading this paper, it's not clear to me if this disease is different from Resistance to thyrotropin. 

Should this disease be defined as RTSH with the presence of mutations in the DUOX2 gene?

Thanks!

**Comment by nicolevasilevsky** [comment]
@maglott pinging you again :)

**Comment by maglott** [comment]
Sorry not to have responded sooner.  I asked requested the term because I did not know if a distinction should be made between 'nongoitrous euthyroid hyperthyrotropinemia' (as a submitter provided it to ClinVar) and  RTSH.  I am not an endocrinologist.

**Comment by nicolevasilevsky** [comment]
Thanks and no worries, @maglott. I'm not sure either!

@pnrobinson @cmungall @mellybelly could any of you take a look at this and make a suggestion, or suggest someone we could ask for help?
Thanks!

**Comment by pnrobinson** [comment]
I do not think this should be classified as a separate disease. "nongoitrous euthyroid hyperthyrotropinemia" is a description of three clinical entities, and is close to being a clinical syndrome/group, but in this case the patient being described has this https://omim.org/entry/607200.
We might want to consider nongoiterous thyroid dyshormonogenesis  as a grouping class for this diseases  and others like it though.

**Comment by pnrobinson** [comment]
It seems that "Congenital nongoiterous hypothyroidism" is used to describe this group of diseases. They are not necessarily euthyroid. This is a synonym for this grouping class
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0010132&viewMode=All&siblings=false
I would suggest NOT adding the "euthyroid"
