### ISSUE TITLE
[Revise logical def] Fragile X Syndrome disease has feature some Autism (HP term)

### ISSUE THREAD

**Issue by sierra-moxon** [monarch-initiative/mondo#6428]
**Mondo term (ID and Label)**
MONDO:0010383 ; Fragile X Syndrome

**Suggested revision of logical definition**
Not sure if this is a logical definition change, or another kind of ticket.  It struck me as a bit odd to see Autism as a phenotype of a disease.  If this kind of relation is needed in the ontology, I can sort of see using "[autistic behavior](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0000729&lang=en&viewMode=PreferredRoots&siblings=false#  )" as the HP term instead.  

**Your nano-attribution (ORCID)**
https://zfin.org/ZDB-PERS-030520-1 via NCATS Translator

**Comment by sierra-moxon** [comment]
per your request for a ticket @sabrinatoro :)

**Comment by nicolevasilevsky** [comment]
@sierra-moxon I think we can remove this subclassOf axiom
