### ISSUE TITLE
familial long QT syndrome

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#6434]
**Mondo term (ID Label)**
familial long QT syndrome
https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0019171

this is not necessarily congenital (also, under congenital heart disease we usually understand structural defects).
it is also not syndromic.

We are still missing the genetic heart disease term.

**Bug/Typo/Error description**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
this has all been addressed
<img width="642" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/78745783-78da-4f24-a608-b72d8ee0c2ec">
