### ISSUE TITLE
Incorrect synonyms in MONDO_0009376 (carbamoyl phosphate synthetase I deficiency disease)

### ISSUE THREAD

**Issue by anjaf** [monarch-initiative/mondo#6435]
**Mondo term (ID Label)**
MONDO_0009376 (carbamoyl phosphate synthetase I deficiency disease)

**Bug/Typo/Error description**
The term has two wrong synonyms: "carbamoyl-phosphate synthase" and "deficiency disease"
(Perhaps this was a parsing error.)

**Your nano-attribution (ORCID)**
0000-0002-8674-0039

**Comment by nicolevasilevsky** [comment]
Thanks @anjaf, we will address this as soon as we can.
