### ISSUE TITLE
Clarifying questions/X-refs; MONDO:0010173 and Mayer-Rokitansky-Kuster-Hauser syndrome(s)

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6438]
**Mondo term (ID and Label):**
 MONDO:0010173 Mayer-Rokitansky-Kuster-Hauser syndrome type 1

**Xref that should be fixed (ID and label):**
1. SNOMED CT [8793008](http://identifiers.org/snomedct/8793008) looks like it should actually be on the parent concept of MRKH syndrome/ Rokitansky sequence
![image](https://github.com/monarch-initiative/mondo/assets/71083858/b6bef580-d131-4702-a8a4-661c6bc29065)

2. OMIM's pref name on 277000 is "MAYER-ROKITANSKY-KUSTER-HAUSER SYNDROME" (abbreviated as MRKH) and it describes multiple, related phenotypes in the Description, so I don't know that it is correct to map this OMIM record to "type 1" child term, perhaps it should also move to the parent concept?  

- I see that Orphanet ORDO:247775 points to 277000 as 'exact' and Orpha's term is "...type 1" but I think this equivalency should be reviewed? 

UMLS X-refs that I think may be the best matches (but UMLS also has multiple CUIs for the parent concept, I think, I will follow up with them separately)
MRKH syndrome: C0431648 / C1698581
MRKH1 : C5566555
MRKH2: C4305568 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
Summary of Requests, pending review/discussion from @ahamosh and @Orphanet @ana-rath-orphanet  et al.

- [ ] Move SNOMEDCT 8793008 to MONDO:0017771
- [ ] Add "Rokitansky sequence" (source- SNOMED CT 8793008)) and "Rokitansky Kuster Hauser syndrome" (Source: MeSH C537371) syns to MONDO:0017771
- [x] ? Move OMIM 277000 to MONDO:0017771 ? Pending review by Orphanet ?

**Comment by nicolevasilevsky** [comment]
thanks @kanems!

**Comment by sabrinatoro** [comment]
Question to OMIM: 
Does OMIM:277000 represent a specific disease  ('Mayer-Rokitansky-Kuster-Hauser syndrome type 1') or a "grouping term" ?

**Comment by sabrinatoro** [comment]
On the Expert call (Jan 25, 2024): 
OMIM:277000 represents 'Mayer-Rokitansky-Kuster-Hauser syndrome type 1'
@ahamosh, please update the OMIM record to show this disease name (ie 'Mayer-Rokitansky-Kuster-Hauser syndrome type 1'). Thank you!

**Comment by sabrinatoro** [comment]
To do:  ? Move OMIM 277000 to MONDO:0017771 ? Pending review by Orphanet ?
See previous comment, the OMIM ID is correct.

**Comment by sabrinatoro** [comment]
I did: 
- moved the SCTID to the more general term - MONDO:0017771
- Added UMLS x-refs to MONDO:0017771 and children (notes that these might also be part of the x-refs import from MedGen)
- Added synonyms as requested (note that the suggested MESH id is equivalent to a parent term "mullerian aplasia", and not to MONDO:0017771. Therefore, to avoid confusion, the orcid instead of the MESH-id as a x-ref for the synonym)

**Comment by sabrinatoro** [comment]
Note: Based on [here](https://www.ncbi.nlm.nih.gov/medgen/140915) and Orphanet:247775, Rokitansky sequence refers to type1, and not to parent term as suggested by SCTID:8793008.
