### ISSUE TITLE
MONDO:0011790 | Amish lethal microcephaly

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#6445]
**Mondo term (ID and Label)**

MONDO:0011790 | Amish lethal microcephaly

**Suggested revision and reasons**

Should this be is_A microcephaly (MONDO:0001149)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
thanks @ValWood - we'll address this as soon as we can
