### ISSUE TITLE
[NTR/PRKAG2] PRKAG2-related cardiomyopathy

### ISSUE THREAD

**Issue by awaddell01** [monarch-initiative/mondo#6446]
**Preferred gene-related syndrome label**
PRKAG2-related cardiomyopathy

**Synonyms**
PRKAG2 syndrome, PRKAG2 cardiac syndrome, PRKAG2 cardiomyopathy

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0005217

**Definition**
A metabolic heart condition characterized by variable cardiac hypertrophy, ventricular pre-excitation, and aberrant glycogen storage in the cardiac tissue due to a pathogenic variant in PRKAG2 that results in a net anabolic effect in cardiac cells.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID:29298659

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
MONDO:0010946
MONDO:0009867
MONDO:0008685

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0009-0007-0138-2054

This request is being made on behalf of the ClinGen Hereditary Cardiovascular Disease GCEP. 
@courtneythaxton 
@nicolevasilevsky 
@ahamosh

**Comment by nicolevasilevsky** [comment]
thanks @awaddell01 - we'll address this as soon as we can

**Comment by cmungall** [comment]
I tried this with curategpt and discovered that the term already existed

http://purl.obolibrary.org/obo/MONDO_0010946

I think adding synonyms to this term as requested should close this

**Comment by awaddell01** [comment]
@cmungall The HCVD GCEP would prefer if the new name could replace the term from your message above, along with changing the definition rather than adding as a synonym if possible. I'll add the link for the ClinGen webpage for the group below:
https://www.clinicalgenome.org/affiliation/40104/

**Comment by ahamosh** [comment]
II think they want to move this up the hierarchy to cardiomyopathy as opposed to just hypertrophic cardiomyopathy.  Is that correct?
