### ISSUE TITLE
Goldberg-Shprintzen syndrome

### ISSUE THREAD

**Issue by Bryannavanhoute** [monarch-initiative/mondo#6456]
**Mondo term (ID and Label):**
MONDO:0012280 Goldberg-Shprintzen megacolon syndrome

**Suggested new label:**
Goldberg-Shprintzen syndrome

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
Requested by the ClinGen Brain Malformations GCEP (https://www.clinicalgenome.org/affiliation/40020/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**

**Comment by nicolevasilevsky** [comment]
thanks @Bryannavanhoute - we'll address this as soon as we can

**Comment by sabrinatoro** [comment]
Note: there is another disease with almost the same name: 
Shprintzen-Goldberg syndrome (MONDO:0008426)
These are 2 different diseases according to OMIM.

**Comment by nicolevasilevsky** [comment]
@sabrina:

OMIM has GOLDBERG-SHPRINTZEN SYNDROME and GOLDBERG-SHPRINTZEN MEGACOLON SYNDROME as synonyms and the former is the preferred label, so I think we should proceed with this request.
