### ISSUE TITLE
New term request from NORD

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6461]
These terms were requested by NORD. 

@nicolevasilevsky, could you please review these and let me know if you think these terms should be added in Mondo. I am especially questioning the last one. 

We also need to follow-up about which terms should be classified underneath these if we were to create them.

PRRT2-Associated Paroxysmal Movement Disorders
Definition: (as per NORD report) PRRT2-associated paroxysmal movement disorders are a group of rare
movement and seizure disorders caused by changes (disease-causing variants or mutations) in the
PRRT2 gene. They include a spectrum of specific disorders including paroxysmal kinesigenic dyskinesia
(PKD), benign familial infantile epilepsy (BFIE), paroxysmal kinesigenic dyskinesia with infantile
convulsions (PKD/IC) and hemiplegic migraine (HM). In addition, PRRT2 pathogenic variants have been
identified in other childhood-onset movement disorders and different types of seizure conditions, such
as paroxysmal torticollis, episodic ataxia and familial paroxysmal non-kinesigenic dyskinesia. It’s
important to note that these disorders can also have different genetic causes.
References: https://rarediseases.org/rare-diseases/prrt2-associated-paroxysmal-movement-
disorders/#references and also: https://pubmed.ncbi.nlm.nih.gov/32916768/ and
https://www.frontiersin.org/articles/10.3389/fneur.2021.629747/full#B9

EEF1A2-Related Neurodevelopmental Disorder
Definition: (as per NORD report): EEF1A2-related neurodevelopmental disorder is a very rare disorder
caused by harmful variants in the EEF1A2 gene that have arisen spontaneously. There are many
different types of these variants, and the effects are very variable, sometimes even in children with the
same variant. Most children, but not all, will have epilepsy, developmental delay, and intellectual
disability. Some also have challenging behaviors and/or movement disorders.
Note that this condition is also known as: Developmental and epileptic encephalopathy 33 MONDO
14625:
https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%25
2Fobo%252FMONDO_0014625 OMIM 616409
(Another condition that may also have some overlapping features is Intellectual developmental disorder,
autosomal dominant 38 DOID:0070068 OMIM: 616393)
References: https://rarediseases.org/rare-diseases/eef1a2-related-neurodevelopmental-
disorder/#references

ZC4H2-Associated Rare Disorders
Definition: (as per NORD report):  is an ultra-rare genetic condition with central and peripheral
nervous system involvement caused by harmful changes (pathogenic variants) of
the ZC4H2 gene. ZC4H2 is located on the X chromosome and encodes the ZC4H2 (zinc finger
C4H2-type containing) protein essential for normal development. ZARD can manifest in a broad
range of clinical severity. Clinical presentations of affected individuals who carry the same
pathogenic ZC4H2 gene variant can vary within families and between families. 1-3  Males and
females can be affected.
References: https://rarediseases.org/rare-diseases/zard/#references

**Comment by galyea123** [comment]
Hi Sabrina and Nicole: Thank you for the follow-up! 

As commented, the EEF1A2-Related Neurodevelopmental Disorder is also known as Developmental and epileptic encephalopathy 33 MONDO
14625: link: https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%25 

For the ZC4H2-associated disorders we do not need to add a new term. MONDO already list this condition as Wieacker-Wolff syndrome.  I would ask to add ZC4H2-associated disorders as a synonym. Thank you! Gioconda

**Comment by sabrinatoro** [comment]
- Other neurodevelopmental disease are due to a variation in EEF1A2. Therefore EEF1A2-Related Neurodevelopmental should not be added as a synonym. 

- [ ] add exact synonym: "ZC4H2-associated disorder" to Mondo 'Wieacker-Wolff syndrome (spectrum)' (MONDO:0025445); use the following reference: https://rarediseases.org/rare-diseases/zard/#references
According to OMIM, the 2 children of this Mondo term are both associated with ZC4H2, and no other diseases are reported to be associated with this gene. Therefore I think it is ok to add "ZC4H2-associated disorder" as a synonym.

**Comment by sabrinatoro** [comment]
To do (2) :  create a new term: PRRT2-Associated Paroxysmal Movement Disorders
@galyea123 , could you please help with the classification?

- what should the parent term be?  
- what should the children be? according to the definition you proposed, the children should be paroxysmal kinesigenic dyskinesia (PKD), benign familial infantile epilepsy (BFIE), paroxysmal kinesigenic dyskinesia with infantile convulsions (PKD/IC), hemiplegic migraine (HM). However, when these terms exist in Mondo, they are not associated with the PRRT2 gene. 

Thank you!

**Comment by galyea123** [comment]
I think that paroxysmal movement disorder can be the parent term. ORDO:306768 or maybe classify all of these terms as "gene-related disorders"

As per the children, all of these conditions have more than one cause, as per example, paroxysmal kinesigenic dyskinesia (PKD) can be caused by different gene mutations and other factors. https://translationalneurodegeneration.biomedcentral.com/articles/10.1186/s40035-021-00231-8 

The following GeneReview article may be useful: https://www.ncbi.nlm.nih.gov/books/NBK475803/ 

Thank you!  Gioconda

Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
this can be closed, this is done. I linked the wrong issue on the PR
