### ISSUE TITLE
SMA

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6462]
I wanted to let you know that we noticed that the SMN III is not connected to the causative gene (SMNI) in MONDO but the other subtypes are.  Also, SMN1 should be SMNI to be consisted with the nomenclature using Roman numerals that you have.

**Comment by sabrinatoro** [comment]
Thank you Gioconda! :-)

**Comment by nicolevasilevsky** [comment]
@galyea123 could you please share the Mondo IDs for the terms you are referring to? Thanks!

**Comment by galyea123** [comment]
MONDO:0009672 for SMA III
MONDO:0009669 for spinal muscular atrophy, type 1
