### ISSUE TITLE
[Obsolete] MONDO:0008807 'apnea, central sleep'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6463]
**Mondo term (ID and Label)**
MONDO:0008807 'apnea, central sleep'

**Reason for deprecation**
@ahamosh is this a historic disease or is it still valid? The records are quite old:
https://omim.org/entry/207720
https://omim.org/entry/107640

**Suggested term to consider**
MONDO:0004731 'central sleep apnea syndrome'

**Comment by sabrinatoro** [comment]
Added to the list of terms to obsolete for October release. 
However, **we should get answer from @ahamosh before going ahead with the obsoletion**.

**Comment by nicolevasilevsky** [comment]
@ahamosh :eyes: - see question [above](https://github.com/monarch-initiative/mondo/issues/6463#issue-1816437315)

**Comment by ahamosh** [comment]
These aren't really free-standing disease and they certainly aren't monogenic, except for central hypoventilation syndrome which is its own entity.

**Comment by nicolevasilevsky** [comment]
thanks @ahamosh!
