### ISSUE TITLE
a xref ID to MedDRA is a UMLS ID

### ISSUE THREAD

**Issue by sh-ikeda** [monarch-initiative/mondo#6490]
**Mondo term (ID and Label):**
MONDO:0018872 acute megakaryoblastic leukemia

**Xref that should be fixed (ID and label):**
Only this entry has a UMLS ID (C0023462) as the cross reference to MedDRA.
The correction is [10060556](http://purl.bioontology.org/ontology/MEDDRA/10060556).

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-1357-5159

**Other comments:**

**Comment by nicolevasilevsky** [comment]
Thanks @sh-ikeda for the ticket, we'll address this as soon as we can.
