### ISSUE TITLE
TCF7L2-Related Neurodevelopmental Disorder

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6497]
This is a NORD report https://rarediseases.org/rare-diseases/145702/ and there is evidence mentioned in OMIM about this condition: PubMed: [34003604] (https://pubmed.ncbi.nlm.nih.gov/34003604/)

Definition: TCF7L2-related neurodevelopmental disorder (TRND) is a newly discovered disorder caused by a change (variant or mutation) in the TCF7L2 gene. This mutation may be responsible for developmental delays in childhood, intellectual disability, autism, myopia, ADHD, abnormal physical features and other problems. There is a wide spectrum of severity for individuals affected with TRND. Many of the symptoms of TRND overlap with other neurodevelopmental disorders. TRND must be diagnosed with a genetic test and cannot be diagnosed by symptoms alone.
Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene. For example: Any congenital myopathy in which the cause of the disease is a mutation in the TPM3 gene.
Source:  NORD report https://rarediseases.org/rare-diseases/145702/ 

Relevant resources
Simons Searchlight Community – [TCF7L2 Facebook group](https://www.facebook.com/groups/1139405743462265)
TRND Network
TRND Network – [trndnetwork.org](https://trndnetwork.org/)
TRND Network – [Facebook group](https://www.facebook.com/groups/660397525174033/)

**Comment by nicolevasilevsky** [comment]
Hi @galyea123 - thank for the ticket, we'll address it as soon as we can, we'll likely get this term in for the September release.
