### ISSUE TITLE
[Revise text def]

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#6502]
**Mondo term (ID and Label)**

Complex neurodevelopmental disorder with motor features MONDO:0100516

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**

A complex neurodevelopmental disorder that involves more than one phenotype associated with the central nervous system, including but not limited to intellectual disability, autism, and seizures (epilepsy). Additionally, the disorder features at least one phenotype associated with motor function, including but not limited to spasticity, hypo- or hypertonia, dyskinesia, choreo-athetosis, or ataxia.

This term is similar to cerebral palsy, but this is for individuals that do not have a clinical diagnosis. There is a subset of cases that encompass both complex neurodevelopmental disorders and motor features.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

inicalgenome.org/affiliation/40006/

**Comment by megankraus** [comment]
I just want to clarify that the only revision here is changing the word "kids" in the original definition to "cases" which I agree with.
