### ISSUE TITLE
split term: 'intellectual disability-macrocephaly-hypotonia-behavioral abnormalities syndrome'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6531]
**Term to split:**
MONDO:0014602 'intellectual disability-macrocephaly-hypotonia-behavioral abnormalities syndrome'

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 

1. Houte-Janssens syndrome [https://omim.org/phenotypicSeries/PS616355](https://omim.org/phenotypicSeries/PS616355)
2. Hogue-Janssens syndrome 1 [https://omim.org/entry/616355](https://omim.org/entry/616355), which is currently MONDO:0014602 'intellectual disability-macrocephaly-hypotonia-behavioral abnormalities syndrome'

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
Houte-Janssens syndrome https://omim.org/phenotypicSeries/PS616355
is already in Mondo: MONDO:0957553
Should this issue become 
- review of X-ref for MONDO:0014602, and review the classification?

**Comment by nicolevasilevsky** [comment]
Seems like the OMIMPS was added after I created this ticket (I'm guessing?)

Looks like 'intellectual disability-macrocephaly-hypotonia-behavioral abnormalities syndrome' should be renamed and made a child of MONDO:0957553

I can take care of this
