### ISSUE TITLE
erythrokeratoderma variabilis (et) progressivaMONDO:0017681 or MONDO:0017851 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6534]
**Mondo term (ID and Label)**
erythrokeratoderma variabilis progressiva MONDO:0017681

**Reason for deprecation**
I am struggling to understand how this is clinically distinct from MONDO:0017851 erythrokeratodermia variabilis which includes the same abbreviation "EKVP" as the other record.
The OrphaNet term https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=308166 describes at least some of the same causative genes as outlined on the OMIM PS https://www.omim.org/phenotypicSeries/PS133200 the 'expert' summary in Ordo shows it hasn't been updated since 2015, so it's possible that they are the same concept?

**Term to be merged with**
MONDO:0017851 erythrokeratodermia variabilis 
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@kanems thanks for the ticket! We'll look into this asap.

**Comment by nicolevasilevsky** [comment]
I agree that these seem like the same disease. I'll proceed with the merge and assign @sabrinatoro to review.
