### ISSUE TITLE
ICD10 subset of MONDO?

### ISSUE THREAD

**Issue by kara-liu** [monarch-initiative/mondo#6536]
Hello. I am trying to do a ICD10 -> MONDO mapping. It seems that a significant number of ICD10 codes are not covered under MONDO. I note that there are some purposely excluded ICD10 codes (as covered / documented in the FAQ [here](https://mondo.monarchinitiative.org/pages/faq/)), but there are many that are on that list that have no mapping I'm aware of (ie. A40.1 Sepsis due to streptococcus, group B). There are also several examples where the "names" match perfectly but no ICD10 code or UMLs corresponding is listed (ie. epidemic louse-borne typhus). What is the best way to achieve that mapping, given that one should exist?  

Using UMLs, I am achieving about a 20% mapping rate, but I feel like it should be a bit higher (not 100% due to the excluded terms, but def much higher than 20%).

**Comment by matentzn** [comment]
@kara-liu 

Mondo indeed integrates multiple external ontologies, but currently with a focus on rare disease. 

We are mostly up to date with Orphanet, OMIM, Human Disease Ontology, GARD, soon MedGen. ICD10 is on our list, indeed, we have a pipeline and a timeline for this, but we have not updated ICD10 in a few years. Sorry about that! 

Bridges between ICD10 and "normal" ontologies are always a bit painful. I am not sure which map is the most trustworthy right now that would allow you to bridge into Mondo! Sorry about that!

**Comment by kara-liu** [comment]
@matentzn Thank you so much for getting back to me! I am wondering if there is a comprehensive list of all ICD10 codes that are covered by MONDO (or equivalently, a list of all codes that are excluded but that contains more than the "excluded list" from the FAQ page). Mu

**Comment by kara-liu** [comment]
@matentzn Thank you so much for getting back to me! I am wondering if there is a comprehensive list of all ICD10 codes that are covered by MONDO (or equivalently, a list of all codes that are excluded but that contains more than the "excluded list" from the FAQ page). Mu

**Comment by matentzn** [comment]
@kara-liu you can get them using SPARQL:

https://api.triplydb.com/s/z8zB21B2A

I provided some comments in the query, let me know if you need more help!

**Comment by kara-liu** [comment]
@matentzn This is amazing! Thank you so much.

**Comment by matentzn** [comment]
Glad we could help!
