### ISSUE TITLE
Issue with food allergies linked to 'infectious disease'

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#654]
Looking at MONDO:000555 'infectious disease', many of its children are food allergies. Presumably due to the axiom 'realized in response to stimulus', e.g., 
'apple allergy' is equivalent to 'realized in response to stimulus some Malus domestica'.
Not sure if this has been reported before. Thanks!

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I believe this was fixed recently, can you do a pull on the most recent version of MONDO and double check? I don't see food allergies as children of infectious disease anymore. (Or are you looking in OLS? It may not be updated there yet)

**Comment by nicolevasilevsky** [comment]
Here is a screenshot:
![image](https://user-images.githubusercontent.com/6722114/55097809-d8330d00-5079-11e9-945c-5af61165fc69.png)

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky thanks for your reply. I am seing food allergy terms as children of MONDO 'infectious disease' in both OLS and Ontobee; both have the version dated 2018-12-02 loaded. Was there a more recent MONDO release? I didn't think so, in that case your fix won't be visible yet. (Not sure when you're planning your next release, BTW.) Feel free to close this ticket, thanks!

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia there has been a new Mondo release and I believe the hierarchy should look correct now in OLS :)

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky yes, there are no food allergies under infectious disease any more! Thanks.
