### ISSUE TITLE
Request to expand the definition of DOORS syndrome

### ISSUE THREAD

**Issue by rebecca-siegert** [monarch-initiative/mondo#655]
On behalf of the ClinGen Hearing Loss and Epilepsy Gene Curation Expert Panels, I am requesting an expanded definition of DOORS syndrome (MONDO:0009079). 

## Expanded Textual definition

DOORS syndrome (also known as DOOR syndrome) is a multiple congenital anomalies-intellectual disability syndrome characterized by sensorineural hearing los (deafness), onychodystrophy, osteodystrophy, mild to profound intellectual disability, and seizures. Isolated seizure disorders and isolated hearing loss have also been reported in individuals as a proposed spectrum of DOORS syndrome. 

## ClinGen joint Hearing Loss and Epilepsy Expert Panels evidence summary

Autosomal recessive TBC1D24-related syndromes show marked phenotypic pleiotropy, with multi-system involvement and severity spectrum ranging from isolated deafness, to benign myoclonic epilepsy restricted to childhood with complete seizure control and normal intellect, to early-onset epileptic encephalopathy with severe developmental delay and early death. There is no distinct phenotypic correlation with pathogenic variant type or location yet, but patterns are emerging (Balestrini 2016). Sensorineural hearing loss is a key feature of DOORS syndrome, which is characterized by deafness, onychodystrophy, osteodystrophy, mental retardation, and seizures (Campeau 2014). Isolated seizure disorders without any reported deafness have also been seen (Balestrini 2015). In contrast, two of the families reported to have nonsyndromic hearing loss caused by variants in TBC1D24 were shown to have no history of seizures (Rehman 2014). Further, two independent reports identified the same variant in TBC1D24 to be segregating in an autosomal dominant manner with nonsyndromic hearing loss (Azaiez 2014, Zhang 2014). Currently there is not enough evidence to treat nonsyndromic hearing loss or isolated seizures as distinct conditions, especially because those affected with DOORS syndrome have both hearing loss and seizure phenotypes. 

## References

PMIDs: 25769375, 26371875, 25557349, 24291220, 24729539, 24729547

@ahamosh @Orphanet @pnrobinson @nicolevasilevsky @cmungall @mellybelly

**Comment by maglott** [comment]
sensorineural hearing los (deafness), should likely be sensorineural hearing loss (deafness),
