### ISSUE TITLE
[Revise logical def] 'monogenic epilepsy'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6550]
**Mondo term (ID and Label)**
MONDO:0015653 'monogenic epilepsy'

**Suggested revision of logical definition**
I don't think the logical axiom makes sense:

epilepsy
 and ('bearer of' some inherited)

inherited could be any type of inheritance, not just monogenic. It is causing some incorrect inferences.

@sabrinatoro do you agree?

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I agree, the logical axiom does not represent "monogenic epilepsy" because of all the reasons you mentioned. We should remove it.

**Comment by nicolevasilevsky** [comment]
I'll fix this, thanks!
