### ISSUE TITLE
Request for new term [self-limited neonatal seizures ]

### ISSUE THREAD

**Issue by JoyeuseMuj** [monarch-initiative/mondo#6554]
### Label

self-limited neonatal seizures 

### Synonyms

SeLNE

### Synonym type

exact

### Definition

A neonatal/infantile epilepsy syndrome where seizures start in the neonate between day 4 and 7 of life and are often unilateral clonic events that recur and may alternate sides from seizure to seizure. Seizures can be repetitive over hours to days. Seizures remit by 4-6 months of age. A proportion of those affected may have seizures in later life. The child is expected to have normal developmental progress. This is distinguished from familial neonatal epilepsy  on the basis of family history. These entities may have similar genetic etiologies, with de novo mutations responsible for the lack of family history in self-limited neonatal seizures.

https://www.epilepsydiagnosis.org/syndrome/self-limited-neonatal-overview.html

### Parent term

neonatal/infantile epilepsy syndrome

### ORCID Identifier

https://orcid.org/0009-0008-4499-6539

### Additional comments

Related to https://github.com/monarch-initiative/mondo/issues/5957

**Comment by nicolevasilevsky** [comment]
@JoyeuseMuj thanks for reporting this, I'll work on this asap
