### ISSUE TITLE
infantile epilepsy syndrome

### ISSUE THREAD

**Issue by JoyeuseMuj** [monarch-initiative/mondo#6556]
**Mondo term (ID and Label):**

infantile epilepsy syndrome'
**Suggested new label:**

neonatal/infantile epilepsy syndrome

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0009-0008-4499-6539

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
https://www.epilepsydiagnosis.org/index.html

**Comment by nicolevasilevsky** [comment]
I don't remember why we wanted to relabel this but we already have a term called 'neonatal/infantile epilepsy syndrome' (MONDO:0100022). 

It looks like the https://www.epilepsydiagnosis.org/index.html website is down at the moment. I'll revisit this later.

**Comment by nicolevasilevsky** [comment]
this matches what is on the website:
<img width="730" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/37479e4a-0131-44d8-af9c-294272beb26d">

But appears to be already done.
