### ISSUE TITLE
split term: Oculopharyngeal muscular dystrophy

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6561]
**Term to split:**
MONDO:0008116 Oculopharyngeal muscular dystrophy

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 

Oculopharyngeal muscular dystrophy (OMIMPS:164300)
[Oculopharyngeal muscular dystrophy 1](https://omim.org/entry/164300)
[Oculopharyngeal muscular dystrophy 2](https://omim.org/entry/620460) - _this should be added in the migration_

see https://omim.org/phenotypicSeries/PS164300

**Comment by sabrinatoro** [comment]
@nicolevasilevsky, I think it is already done based on what I see in the ontology. Can we close?
