### ISSUE TITLE
issue with build timing out

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#657]
The build is timing out after 50 minutes, and causing the build to fail. Not sure why the build is taking so long to run, this seems unusual.

**Comment by nicolevasilevsky** [comment]
See: https://docs.travis-ci.com/user/customizing-the-build/

**Comment by nicolevasilevsky** [comment]
Additional info: https://github.com/travis-ci/travis-ci/issues/2736

**Comment by cmungall** [comment]
@dougli1sqrd how did you fix before?

**Comment by nicolevasilevsky** [comment]
here is an example of a PR where the build timed out:
https://github.com/monarch-initiative/mondo/pull/660

**Comment by ShahimEssaid** [comment]
@cmungall  I'm trying to add timestamps to the log output to know where the time is spent. I need to adjust the .travis.yml and/or the run.sh wrapper script. Do you remember why docker is invoked again in the wrapper script? I'm still learning about Docker and Travis but my understanding is that Travis's "script:" commands are ran in the Docker container and there is no need to invoke the container again in the wrapper script. I see in the history of .travis.yml that you used to invoke the build that way, and in the .travis.yml script: section but later switched to the wrapper and another invocation of a docker container. What is the reason for doing this?  The commit note only said that you were switching to a wrapper script. One guess is that the wrapper is useful for local builds but I don't think the Travis build should also invoke the wrapper. I'll experiment with this on a branch but I also wanted your input if you remember the details.

**Comment by cmungall** [comment]
@dougli1sqrd you went down this path can you advise?

**Comment by ShahimEssaid** [comment]
@dougli1sqrd I think I misassumed that Travis runs the "script:" commands in the Docker container. It looks like that's not the case. Please disregard above questions.

**Comment by dougli1sqrd** [comment]
in go-ontology we have a little script called `stamp.sh `:
```
#!/bin/bash
shift
time sh -c "$*"
```

Then in the go-ontology makefile we set the shell to be `stamp.sh`. stamp just passes along the arguments directly into shell, but first we ask it to time the command. We set the shell in make early on in the makefile with:
```
SHELL=./stamp.sh
```

Then we get time output for each make command. Maybe that will help? We also changed the docker command to extend the "no log output" timeout. But 50 minutes is a long time. I forget exactly in go-ontology what ended up decreasing the time. Perhaps it was a more efficient reasoning change or something. I do not recall now.

**Comment by cmungall** [comment]
Thanks for the tip @dougli1sqrd  - @ShahimEssaid shall we try incorporating this to the MONDO makefile to better diagnose the issue?

**Comment by nicolevasilevsky** [comment]
this is no longer an issue
