### ISSUE TITLE
postpone obsoletion of ATR-X related syndrome (MONDO:0016980) and KAT6B-realted multiple congenital anomalies syndrome (MONDO:0036042)

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6572]
From Ineke Cordova

Erin and I saw that MONDO is going to eliminate the disease entity terms “ATR-X related syndrome” (MONDO:0016980) and “KAT6B-realted multiple congenital anomalies syndrome (MONDO:0036042). In the linked spreadsheets, there were also no suggested disease entities to use instead. Are there any official alternatives from your end? Or, do we need to bring this back to our group?

**Comment by nicolevasilevsky** [comment]
We don't have terms we'd recommend, we can keep these terms if they are being used by ClinGen.

**Comment by nicolevasilevsky** [comment]
Action item for @sabrinatoro or me:

- [ ] remove from the obsoletion list and add the new tag that Sabrina will create

**Comment by nicolevasilevsky** [comment]
@ErinRiggs 👀

**Comment by nicolevasilevsky** [comment]
note [ATR-X-related syndrome](https://www.orpha.net/consor/www/cgi-bin/OC_Exp.php?Expert=263355) is obsolete in Orphanet

**Comment by nicolevasilevsky** [comment]
dependent on
https://github.com/monarch-initiative/mondo/issues/6547

**Comment by icordovaG** [comment]
Hi Nicole, 

For ATR-X-related syndrome we're going to go ahead and take your suggestions of replacing it with 'alpha thalassemia-X-linked intellectual disability syndrome'. As for KAT6B-realted multiple congenital anomalies syndrome (MONDO:0036042), we would like to continue to use this term. Please remove it from the obsoletion list. Thank you for your help on this!

@ErinRiggs

**Comment by icordovaG** [comment]
Hi Nicole, 

I just got a notification that the KAT6B term was obsoleted. Per the conversation above, I thought that we had taken this term off of the list. Should I submit another ticket to get it added again?

@ErinRiggs

**Comment by sabrinatoro** [comment]
Dear @icordovaG, thank you for reporting this. 
We lost track of this request to remove these terms from the obsoletion list. We deeply apologize. 
I have reversed the obsoletion of these terms, and you should be able to see them again (with their original ID), during our next release, early January 2024. 
Thank you for your patience and understanding. 
Sabrina
