### ISSUE TITLE
New OMIM data and existing Mondo record: ACTB-ASSOCIATED SYNDROMIC THROMBOCYTOPENIA

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6597]
OMIM has a new record and includes an alt name that matches the primary record name in Mondo. My question is whether these two are the same, and does Mondo plan to map the new OMIM record to the existing Mondo ID? OR are they distinct concepts (the ClinGen record is broader? ) and the MIM record will get a new Mondo ID that is a child of the existing term?

OMIM 620475 (uses 'ACTB-ASSOCIATED SYNDROMIC THROMBOCYTOPENIA' as an alternate name) 
Mondo:0100433 

It looks like ClinGen hasn't yet evaluted/curated the new MIM number either: https://search.clinicalgenome.org/kb/conditions/MONDO:0100433 

MedGen's got a naming conflict here, so we'll follow the preferred names from Mondo and OMIM for now and keep separate until I hear otherwise.

**Comment by nicolevasilevsky** [comment]
@miajsullivan - is this term the same as the new OMIM term? Can we add the OMIM ID as an xref?

Thanks!

related to https://github.com/monarch-initiative/mondo/issues/4019

**Comment by nicolevasilevsky** [comment]
Excellent, thanks so much @miajsullivan, I appreciate the quick reply!

@kanems, I'll add the OMIM ID as an xref.
