### ISSUE TITLE
Creation of broader disease entity for MED12 related disorder(s)

### ISSUE THREAD

**Issue by courtneythaxton** [monarch-initiative/mondo#66]
For new term requests, please provide the following information:

This request in on behalf of the ClinGen Id/Autism Gene Curation expert panel. Following precuration of this gene we find that the disease entities is broader in nature than the subparts and request for a collapse of terms associated with MED12 into a broader parent term. 

## List of Disease Groups

Orphan/ child terms for collapse into broader parent term:
1. Lujan-Fryns syndrome, aka. X-linked intellectual disability with marfanoid habitus (MONDO:0010655)
2. Ohdo syndrome, X-linked aka. blepharophimosis-intellectual disability syndrome, MKB type, (MONDO:0010477)
3. Opitz-Kaveggia syndrome, aka. FG syndrome 1 (MONDO:0010590)

## Synonyms

(e.g., Absent spleen)

## Textual definition

Subtypes of the heterogeneous, eponymously named Lujan-Fryns syndrome, X-linked Ohdo syndrome, and Optiz-Kaveggia/ FG syndrome are caused by mutations in the gene MED12. The common and most penetrant phenotype shared amongst these disease entities is intellectual disability, with dysgenesis or agenesis of the corpus callosum, blepharophimosis, and marfanoid habitus  having variable phenotypic expressivity.  

## Suggested parent term

MED12-related intellectual disability syndrome

## List of references supporting
The PMIDs in support of this collapse are: 28369444, 28544239, 24123922,   28794916

## Analysis of how other disease IDs relate:
The most penetrant phenotype among all of the MED12 related disease entities is intellectual disability; but due to the absence of clearly defined and/or distinct differences in molecular mechanism, coupled with noted phenotypic variability (both intra- and inter-familial) these entities appear to be part of a broader disease entity.

As an additional measure I have attached the precuration information that was collected to determine the "lumping" of the asserted disease entities.
[MED12_ID-Autism_Precuration_CLT_1-12-18.xlsx](https://github.com/monarch-initiative/mondo-build/files/1679010/MED12_ID-Autism_Precuration_CLT_1-12-18.xlsx)

If you would like a nanoattribution, please indicate your ORCID id

**Comment by nicolevasilevsky** [comment]
To clarify, @courtneythaxton are you suggesting a new parent/grouping class 'MED12-related intellectual disability syndrome' with these terms as children:

- Lujan-Fryns syndrome, aka. X-linked intellectual disability with marfanoid habitus (MONDO:0010655)
- Ohdo syndrome, X-linked aka. blepharophimosis-intellectual disability syndrome, MKB type, (MONDO:0010477)
- Opitz-Kaveggia syndrome, aka. FG syndrome 1 (MONDO:0010590)
- Should MONDO_0002010 FG syndrome be grouped here too?

Would this just go under MONDO_0002254 syndromic disease?

**Comment by courtneythaxton** [comment]
Hi Nicole,

Thank you for your query. I am a biocurator with ClinGen and work with Melissa Haendel on the lumping and splitting group for defining new disease entities.  I contacted Chris Mungall on this query, and must admit this is a beta testing of how to do this, so my apoloigies if there are several emails.

As to your questions:
1)  yes we would like to make MED12-related Intellectual disability syndrome the parent term, and incoporate the Lujan Fryns, Ohdo syndrome X-linked, and Optiz-KAveggia, FG syndrome as orphan terms under this new parent ontology.

2) Yes, FG syndrome (MONDO_0002010) should be grouped here (and is an acronym for the Optiz-Kaveggia).

3) I think that the experts in the ID/Autism group I am working under would suggest to have this under X-linked syndromic intellectual disability (MONDO:0020119), as it present along the same lines as ATRX-related syndrome, and Aarskog-Scott.

Thank you and please let me know if there is any other information you need.

FYI, I attached to the github issue our excel spreadsheet that was filled out during our precuration process, and has information concerning the lumping and splitting, PMIDS, overlapping variants, MIM phenotypes, etc.

Many thanks!

Courtney

Courtney Thaxton, Ph.D.
Biocurator
Dept. of Genetics
120 Mason Farm Road
5100 B, Genetic Medicine Building
CB#7264
University of North Carolina,
Chapel Hill, NC 27599
919-843-3549




On Jan 30, 2018, at 3:34 PM, Nicole Vasilevsky <notifications@github.com<mailto:notifications@github.com>> wrote:


To clarify, @courtneythaxton<https://github.com/courtneythaxton> are you suggesting a new parent/grouping class 'MED12-related intellectual disability syndrome' with these terms as children:

  *   Lujan-Fryns syndrome, aka. X-linked intellectual disability with marfanoid habitus (MONDO:0010655)
  *   Ohdo syndrome, X-linked aka. blepharophimosis-intellectual disability syndrome, MKB type, (MONDO:0010477)
  *   Opitz-Kaveggia syndrome, aka. FG syndrome 1 (MONDO:0010590)
  *   Should MONDO_0002010 FG syndrome be grouped here too?

Would this just go under MONDO_0002254 syndromic disease?

**Comment by courtneythaxton** [comment]
Hi @nicolevasilevsky, I am adding @erinriggs to this conversation thread as she is the coordinator for the ClinGen ID/Autism curation group as well as Neurodevelopmental Disorders clinical domain. 

Thanks!
Courtney

**Comment by nicolevasilevsky** [comment]
@cmungall I will go ahead and implement this request as a pull request

**Comment by nicolevasilevsky** [comment]
@courtneythaxton is this your orcid:  https://orcid.org/0000-0002-6733-369X

**Comment by courtneythaxton** [comment]
Yes, @nicolevasilevsky that is my orchid.
