### ISSUE TITLE
GNB1-related neurodevelopmental disorder

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#6600]
**Preferred gene-related syndrome label**
For example: NAA10-related syndrome
GNB1-related neurodevelopmental disorder

**Synonyms**
autosomal dominant non-syndromic ID 42 

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
autosomal dominant non-syndromic intellectual disability AND autosomal dominant syndromic intellectual disability. If it is not possible to put it under both, please put it under 'intellectual disability, autosomal dominant’, thank you!

**Definition**
Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene. For example: Any congenital myopathy in which the cause of the disease is a mutation in the TPM3 gene.

A neurodevelopmental disorder caused by heterozygous variants in GNB1 and characterized by global developmental delay, intellectual disability, hypotonia, structural brain abnormalities, and seizures. Other less common findings include dystonia, visual impairment, behavior problems, growth delay, craniofacial defects, and genitourinary abnormalities in males. In the literature, variants in GNB1 have been reported under the disease entity ‘Intellectual developmental disorder, autosomal dominant 42’ (MIM# 616973). The term ‘GNB1-related neurodevelopmental disorder’ is now used to better account for the presence of phenotypes seen in addition to developmental delay or intellectual disability.

Similar to the SETD2 term, please let me know if I should submit this one under the other "add term" option as the definition isn't standard. 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
Expert opinion

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

https://clinicalgenome.org/affiliation/40006/

@ErinRiggs

**Comment by nicolevasilevsky** [comment]
Hi @icordovaG - we are making a big push at the moment to clean up classifications in Mondo and so some mass obsoletions and that is going to be the focus of the curation team over the next couple months, so we are going to be delayed in addressing new term requests such as this. We'll aim to get this in for the November release. If that causes any hardship though, please let us know. Thanks!

**Comment by icordovaG** [comment]
Yes - thank you!

**Comment by nicolevasilevsky** [comment]
I will close this ticket but please reopen id anything else is needed. Thanks!

**Comment by icordovaG** [comment]
Hi Nicole, apologies, I believe I misunderstood your question. This term "GNB1-related neurodevelopmental disorder" should be added as a synonym for this term with the updated definition and location in the ontology as provided above. Is this possible?

Thank you!

**Comment by icordovaG** [comment]
Hi Nicole, I see that this term was added as a synonym but the definition was not updated. Also, we were also hoping that 'GNB1-related neurodevelopmental disorder' would be the front name/main name and ID 42 would be listed as a synonym for this term. Could that be updated in the next release? Thanks!

**Comment by nicolevasilevsky** [comment]
Hi @icordovaG - I overlooked the new definition, my apologies, I will add it now, it should be in the next release.

With regard to the name, we aim to use the OMIM names as the preferred names, you can read more about our disease naming policies here: https://mondo.monarchinitiative.org/pages/disease-naming/

If you have further questions about the disease names, please let us know.

**Comment by icordovaG** [comment]
Hi Nicole, 

Could you also update the location in the ontology based on the original request? After review, we saw that this gene has both non-syndromic and syndromic presentations. 

Thanks!

**Comment by nicolevasilevsky** [comment]
Yes! I updated this.
