### ISSUE TITLE
review rare diseases in Tudor's spreadsheet

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#662]
to do: sort through the yellow highlighted areas in the is_rare column in Tudor's spreadsheet

@cmungall will give a precise SOP later

**Comment by cmungall** [comment]
For each one highlighted yellow, remove the axiom subClassOf modifier some rare, and remove the subset gard_rare, if present.

If the source is gard, make a separate ticket for gard

If the source is ordo, make a ticket on the ordo tracker

(we can reuse the same ticket in both cases)

I suggest bundling into a single PR, try a few, I will check

**Comment by nicolevasilevsky** [comment]
Ok- this makes sense. There are only 4 classes in the is_rare column that are highlighted yellow and only two are marked FALSE, so I will edit those two, per your instructions above and make tickets for GARD.

The other two are marked is_rare TRUE, so should those have the axiom subClassOf modifier some rare added?


class | class_label | synonyms | GARD | NCIT | OMIM | DOID | Orphanet | is_leaf | is_rare | TIO_confirmed | TIO_questioned | comment
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MONDO:0003414 | skin pilomatrix carcinoma | pilomatrix carcinoma of   skin\|Pilomatrical carcinoma\|Trichomatrical carcinoma\|calcified epithelial   carcinoma of Malherbe\|calcifying epitheliocarcinoma\|invasive   pilomatrixoma\|malignant pilomatricoma\|matrical carcinoma\|pilomatricoma,   malignant\|pilomatrix carcinoma\|pilomatrix carcinoma of the skin\|pilomatrix   skin carcinoma |   | NCIT:C4114 |   | DOID:5376 | Orphanet:499182 | TRUE | TRUE |   | x | very rare https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5403507/
MONDO:0006044 | nephrosclerosis | renal sclerosis | GARD:0007179 |   |   | DOID:11664 |   | FALSE | FALSE |   | x | neither rare, nor leaf term.    Malignant and benign nephrosclerosis should be leaf terms.    https://www.revistanefrologia.com/en-nephrosclerosis-the-cinderella-chronic-kidney-articulo-X2013251410035776
MONDO:0020510 | idiopathic syringomyelia |   |   |   |   |   | Orphanet:99858 | TRUE | TRUE |   | x | http://weillcornellbrainandspine.org/condition/syringomyelia
MONDO:0008093 | nevus, epidermal | Epidermal Nevus\|nevus,   epidermal\|nonepidermolytic keratinocytic nevus\|Nevus sebaceous\|Nevus,   Keratinocytic, nonepidermolytic\|Nevus, woolly hair | GARD:0013025 | NCIT:C4088 | OMIM:162900 | DOID:0111162 |   | FALSE | FALSE |   | x | "Epidermal nevi are estimated to occur in 1 to 3 in 1,000   people"    https://ghr.nlm.nih.gov/condition/epidermal-nevus

**Comment by cmungall** [comment]
Very good yes. We also want to credit Tudor with these axioms

**Comment by nicolevasilevsky** [comment]
It seems to be the case that neither MONDO:0008093 nevus, epidermal or MONDO:0006044 nephrosclerosis are marked as rare in MONDO.

**Comment by nicolevasilevsky** [comment]
I think this is done.
