### ISSUE TITLE
Request for new synonym [neurofibromatosis type i]

### ISSUE THREAD

**Issue by DnlRKorn** [monarch-initiative/mondo#6623]
### Mondo term

MONDO:0018975 / neurofibromatosis type 1

### Synonyms

neurofibromatosis type i

### Synonym type

exact

### Additional comments

Very small issue, found when I couldn't do exact synonym matching on this term.

**Comment by nicolevasilevsky** [comment]
Hi @DnlRKorn - thanks for reporting this. As you know, we are focused on a [mass obsoletion](https://github.com/monarch-initiative/mondo/issues?q=is%3Aissue+is%3Aopen+label%3A%22mass+obsoletion%22) effort this month, and will look at this more closely in November or later. We appreciate your patience.

**Comment by nicolevasilevsky** [comment]
thanks @DnlRKorn, I added this. 

Is this your ORCID: https://orcid.org/0000-0002-1780-9872?
