### ISSUE TITLE
Typo created bad synonym for thyroid hormone plasma membrane transport defect (MONDO:0008568)

### ISSUE THREAD

**Issue by rleaman** [monarch-initiative/mondo#6624]
MONDO:0008568 (thyroid hormone plasma membrane transport defect) contains an EXACT synonym of just "defect", imported from OMIM:188560. 

It appears that there is an extraneous newline in the names/synonyms for OMIM:188560 (https://www.omim.org/entry/188560?search=188560&highlight=188560), which caused the synonym "HYPERTHYROXINEMIA, EUMETABOLIC, DUE TO T4 PLASMA MEMBRANE TRANSPORT DEFECT" to be imported as two separate EXACT synonyms: "hyperthyroxinemia, Eumetabolic, due to T4 plasma Membrane Transport" and "defect". The very short EXACT synonym "defect" causes errors in tools using the lexical information in MONDO.

https://orcid.org/0000-0003-3296-5766

**Comment by nicolevasilevsky** [comment]
wow, that is bad! Thank you for catching this @rleaman!
