### ISSUE TITLE
Remove/revise synonym for "childhood bladder carcinoma" (MONDO:0022578)

### ISSUE THREAD

**Issue by rleaman** [monarch-initiative/mondo#6625]
MONDO:0022578, childhood bladder carcinoma

Term is defined as a bladder carcinoma during childhood. 

Lists an EXACT synonym "bladder cancer" (source NCIT:C118816), which is more broad than the definition and does not differentiate it from urinary bladder carcinoma, MONDO:0004986. 

https://orcid.org/0000-0003-3296-5766

**Comment by nicolevasilevsky** [comment]
Hi @rleaman - thanks for reporting this. We are focused on a [mass obsoletion](https://github.com/monarch-initiative/mondo/issues?q=is%3Aissue+is%3Aopen+label%3A%22mass+obsoletion%22) effort this month, and will look at this (and your [other open tickets](https://github.com/monarch-initiative/mondo/issues/created_by/rleaman)) more closely in November or later. We appreciate your patience.

**Comment by nicolevasilevsky** [comment]
Thanks @rleaman, I fixed the synonym scope.
