### ISSUE TITLE
add recordings from outreach calls to website

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6626]
@sagehrke do you have the recordings from the recent Mondo outreach calls (Megan and Courtney's need to be added)

thanks!

@iimpulse

**Comment by sagehrke** [comment]
Hi all! Yes, the recordings have been uploaded to the Google Drive folder. I wasn't chasing uploading them to the webpage until we had a consensus of YouTube vs no YouTube, which was only just recently resolved on September 6, 2023. 
You can find the link to the upload folder in the [agenda](https://docs.google.com/document/d/16eMB-x3iANHfiTxw7vUXFoTHtdxscjnfVQ_OrRsnzvE/edit) or here is the direct [folder link](https://drive.google.com/drive/folders/1qsqteFng74C7Kvm2BdIoDASWOaWaqEjN). 
If ya'll would like my assistance getting them added to the webpage, please let me know! I know Nicole mentioned some nuances that may be a bit tricky the first time through. Cheers!

**Comment by nicolevasilevsky** [comment]
thanks so much @sagehrke! 💟 

Yes, editing the website seems somewhat finicky, I am able to do it but I want to make sure others can as well. I assigned this to @sabrinatoro and @twhetzel to give it a go, but if you'd like to try too, @sagehrke, please do.

The instructions are here:
https://mondo.readthedocs.io/en/latest/editors-guide/mondo-website-editing/

**Comment by nicolevasilevsky** [comment]
if folks have issues with editing the website, maybe we should consider how it is set up (right now on it is on a branch called gh-pages). @iimpulse can maybe help with the set up.

**Comment by twhetzel** [comment]
I'm working through some set-up issues in order to get this running, but hopefully will sort out today.

**Comment by nicolevasilevsky** [comment]
awesome, thank you!

**Comment by twhetzel** [comment]
I'm still having config issues in order to get `bundle exec jekyll serve -l` to run. Is there any "Mondo" documentation on the config?

**Comment by twhetzel** [comment]
The links are updated now. I was not able to get the web site to run locally to preview changes but checked these with Nicole to make sure the individual video links were added and not links to the folder.

At least to write this somewhere for now, to get the actual video link:
- click on video in GDrive
- click on right-hand side 3 dots
- click on "Share"
- go to the bottom of the newly opened window and click on "Copy Link" to get the link that _should_ be used in the Mondo web site for the link to the recording

**Comment by twhetzel** [comment]
Closing now
