### ISSUE TITLE
causal disease genes missing "hereditary disease" (MONDO:0003847)"

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#6646]
**Mondo term (ID and Label)**
I see quite a lot of single-gene causal diseases that aren't classed as hereditary

e.g

Definition | Parents
-- | --
Any interstitial nephritis in which the cause of the disease is a mutation in the FAN1 gene.

**Suggested revision and reasons**

Presumably, if you could identify all the terms with in which the cause of the disease is a mutation in the XXX gene.

Could have this parent?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by ValWood** [comment]
Another one:


Definition | Parents
-- | --
A syndrome mainly characterized by severe growth retardation and microcephaly. It is a new form of cohesinopathy showing defects in sister chromatid cohesion and hypersensitivity to chemicals that induce replication stress, thus combining distinct cytogenetic features seen in Roberts syndrome and Fanconi anemia, respectively. It has material basis in homozygous or compound heterozygous mutation in the DDX11 gene on chromosome 12p11. [PMID:26089203, PMID:23033317, PMID:20137776, PMID:21490908]

</div>Warsaw breakage syndrome (MONDO:0013252)
Definition	Parents
A syndrome mainly characterized by severe growth retardation and microcephaly. It is a new form of cohesinopathy showing defects in sister chromatid cohesion and hypersensitivity to chemicals that induce replication stress, thus combining distinct cytogenetic features seen in Roberts syndrome and Fanconi anemia, respectively. It has material basis in homozygous or compound heterozygous mutation in the DDX11 gene on chromosome 12p11. [[PMID:26089203](http://www.ncbi.nlm.nih.gov/pubmed/26089203), [PMID:23033317](http://www.ncbi.nlm.nih.gov/pubmed/23033317), [PMID:20137776](http://www.ncbi.nlm.nih.gov/pubmed/20137776), [PMID:21490908](http://www.ncbi.nlm.nih.gov/pubmed/21490908)]

**Comment by ValWood** [comment]
Another...

Definition | Parents
-- | --
A syndrome characterized by a unique combination of cardiac arrhythmias and intestinal pseudo-obstruction. It has material basis in the mutated SGOL1 protein. Distinctive clinical features include atrial dysrhythmias, sick sinus syndrome (SSS) and valve anomalies and chronic intestinal pseudo-obstruction (CIPO). [PMID:25282101]

</div>chronic atrial and intestinal dysrhythmia (MONDO:0014528)
Definition	Parents
A syndrome characterized by a unique combination of cardiac arrhythmias and intestinal pseudo-obstruction. It has material basis in the mutated SGOL1 protein. Distinctive clinical features include atrial dysrhythmias, sick sinus syndrome (SSS) and valve anomalies and chronic intestinal pseudo-obstruction (CIPO). [[PMID:25282101](http://www.ncbi.nlm.nih.gov/pubmed/25282101)]

**Comment by matentzn** [comment]
omg.. It was an easy fix, but this should have never happened. Please make sure that when you close this issue here, that you have some system in place that will prevent something like this happening again: https://github.com/monarch-initiative/mondo/pull/6931/files

**Comment by nicolevasilevsky** [comment]
need to check in the release that this is fixed, then this can be closed

**Comment by nicolevasilevsky** [comment]
this looks like it is fixed. Thanks for reporting this @ValWood and for your help @matentzn
