### ISSUE TITLE
New term template

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#665]
I would suggest not using "Asplenia", it is a phenotype rather than a disease, I think. We could use something that is clearly a disease, such as Noonan syndrome

**Comment by cmungall** [comment]
Yep, we'll completely overhaul these see https://github.com/INCATools/ontology-development-kit/issues/162 @nicolevasilevsky maybe you can work with Nomi on this?

**Comment by nicolevasilevsky** [comment]
sure, I can work on this.
