### ISSUE TITLE
Mass Obsoletion: focus on branch 'upper digestive tract disorder' (MONDO:0044991)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6650]
Branch: 'upper digestive tract disorder' (MONDO:0044991)

Terms to obsolete: 

obsoletion candidate ID | obsoletion candidate name
-- | --
http://purl.obolibrary.org/obo/MONDO_0015207 | non-syndromic esophageal malformation
http://purl.obolibrary.org/obo/MONDO_0015208 | syndromic esophageal malformation
http://purl.obolibrary.org/obo/MONDO_0019513 | esophageal malformation
http://purl.obolibrary.org/obo/MONDO_0019619 | duplication of the esophagus

**Comment by nicolevasilevsky** [comment]
instructions: https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#simple-mass-obsoletion-pipeline
