### ISSUE TITLE
mass obsoletion: feature requests/issues with pipeline

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6653]
1. mass obsoletion pipeline:
- we need the pipeline to remove the comments
- add source to obsoletion reasons 

2. why did we lose the labels for has obsoletion reason and term tracker item?

**Comment by sabrinatoro** [comment]
Maybe this is related to the import update? 
![Screenshot 2023-09-15 at 14 45 08](https://github.com/monarch-initiative/mondo/assets/12737987/98863f8a-9fce-471b-9f03-86a929609c26)

**Comment by nicolevasilevsky** [comment]
seems like the terms are being rewired, we don't want this. We only want the term to be obsoleted and no new parents assigned.

**Comment by matentzn** [comment]
@twhetzel as you so effectively figured out the rewiring issue, I will leave the ticket to you!

Point 2 may be a bit harder; i would for now just try to add imports/omo_import.owl back as an import and see if it resolves the issue. If so assign me as reviewer on PR and I will tell you what else is needed.

**Comment by nicolevasilevsky** [comment]
@twhetzel I updated the makefile and this new pipeline works as expected (it is not rewiring), I created a PR here:
https://github.com/monarch-initiative/mondo/pull/6670

We can look at this PR together this afternoon and I'll show you how to do the review.

Great job, impressive work! ⭐

**Comment by nicolevasilevsky** [comment]
@matentzn there are still two open issues on this ticket:

1. mass obsoletion pipeline:

- [ ] we need the pipeline to remove the comments
- [ ] add source to obsoletion reasons

2. we need the labels for 'has obsoletion reason' and 'term tracker item'

**Comment by matentzn** [comment]
I know, In the comment above I assigned it to Trish! @twhetzel reach out to me if you need help!

**Comment by matentzn** [comment]
@twhetzel In the end @nicolevasilevsky and I dealt with it in our call yesterday! Sorry about the goose chase.

**Comment by twhetzel** [comment]
sorry, still getting my github notifications sorted out and missed this bit about further requests :( 
i reviewed the edit file changes in the PR, i can dig further into the code updates too
