### ISSUE TITLE
Nijmegen breakage syndrome MONDO:0009623 parents not recessive/ query metabolic 

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#6659]
**Mondo term (ID and Label)**

This is classed as autosomal recessive, but it's autosomal dominant, see below from OMIM:

**Suggested revision and reasons**

They analyzed samples from 47 children with first relapse of ALL for mutations in all 16 exons of the NBS1 gene and identified 4 novel amino acid substitutions in 7 children. Germline origin of an I171V ([602667.0007](https://www.omim.org/entry/602667#0007)) mutation was confirmed in 3 patients, whereas another change, D95N, was present only in leukemic cells. **No additional mutations were found on the second allele in any of these 7 patients**. 

[Tanzarella et al. (2003)](https://www.omim.org/entry/602667#28) found that **heterozygous individuals** from 3 unrelated NBS families with distinct gene deletion mutations had spontaneous chromosome instability (chromatid and chromosomal breaks as well as rearrangements) in blood lymphocytes, but their lymphoblastoid cell lines were not different from controls in x-ray G2 sensitivity. Immunoprecipitation of nibrin detected the normal and variant proteins in carriers from all 3 families.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

Also, what is the Monarch definition of ",metabolic disease" (another parent)? This isn't what most would probably consider  canonical metabolism (algthough to be fair GO classes as "DNA metabolism"

**Comment by nicolevasilevsky** [comment]
@ValWood- this is classified as autosomal recessive in OMIM:
https://omim.org/entry/251260

<img width="805" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/d40a51de-7706-49c1-8992-5d607641f0a0">

**Comment by nicolevasilevsky** [comment]
> Also, what is the Monarch definition of ",metabolic disease" (another parent)? This isn't what most would probably consider canonical metabolism (algthough to be fair GO classes as "DNA metabolism"

Do you mean the Mondo definition? It is

A congenital disorder (due to inherited enzyme abnormality) or acquired (due to failure of a metabolically important organ) disorder resulting from an abnormal metabolic process.
Source: NCIT:C3235

**Comment by nicolevasilevsky** [comment]
@ValWood - please let me know if further action is required or if this can be closed.

**Comment by ValWood** [comment]
OK, I must be misinterpreting the description, probably have a germ one mutation pus an acquired mutation, it isn't completely clear!

Re metabolism, noted, that your definition is broad, I'll keep this in mind.

Will close!
