### ISSUE TITLE
remove subclass: muscular disease classified as skeletal disease

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#666]
cc @paolaroncaglia @zoependlington 

This comes from EFO:

https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002970

![image](https://user-images.githubusercontent.com/50745/55672968-7f454f00-5899-11e9-8c03-cbac6dc8853d.png)

**Comment by paolaroncaglia** [comment]
@cmungall thanks for spotting this, we'll fix it in time for our release next week. I'll open a ticket in EFO now.

**Comment by paolaroncaglia** [comment]
@cmungall should be fixed now and visible after April 15.
