### ISSUE TITLE
HAND2 related congenital heart defects

### ISSUE THREAD

**Issue by eedoh01** [monarch-initiative/mondo#6667]
Gene Name (HGVS Approved): HAND2

Synonyms: DHAND, DHAND2, Thing2, Hed, bHLHa26, HLH transcription factor HAND2
EP Approved Term: 
Definition (Include relevant PMIDs): A heart disease that is present at birth. Representative examples include tetralogy of fallot and ventricular septal defect (PMIDs: 26865696, 26676105). 
Suggested Parent Term:
MONDO:0005453

**Your nano-attribution (ORCID) or URL for a working group**
https://clinicalgenome.org/affiliation/40130/#:~:text=The%20Congenital%20Heart%20Disease%20Expert,the%20purview%20of%20another%20GCEP.

**Comment by nicolevasilevsky** [comment]
Hi @eedoh01 - thanks for reporting this. We are focused on a [mass obsoletion](https://github.com/monarch-initiative/mondo/issues?q=is%3Aissue+is%3Aopen+label%3A%22mass+obsoletion%22) effort this month, and will look at this (and your [other open tickets](https://github.com/monarch-initiative/mondo/issues/created_by/eedoh01)) more closely in November or later. We appreciate your patience.
