### ISSUE TITLE
[mass Obsolete] infectious disease children

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6671]
http://purl.obolibrary.org/obo/MONDO_0005550 | infectious disease | http://purl.obolibrary.org/obo/MONDO_0020069 | chronic encephalitis | MONDO:0020069
-- | -- | -- | -- | --
http://purl.obolibrary.org/obo/MONDO_0005550 | infectious disease | http://purl.obolibrary.org/obo/MONDO_0016125 | infectious, fungal or parasitic myopathy | MONDO:0016125
http://purl.obolibrary.org/obo/MONDO_0005550 | infectious disease | http://purl.obolibrary.org/obo/MONDO_0017234 | inherited prion disease | MONDO:0017234
http://purl.obolibrary.org/obo/MONDO_0005550 | infectious disease | http://purl.obolibrary.org/obo/MONDO_0035561 | sporadic human prion disease | MONDO:0035561

note: chronic encephalitis was done on PR: https://github.com/monarch-initiative/mondo/pull/6670

**Comment by jananiravi** [comment]
@nicolevasilevsky @sabrinatoro, I have a few questions. Could you tell me when this will be discussed (which meeting)? If it's not too much trouble, I would love to hop on this call.

**Comment by nicolevasilevsky** [comment]
Hi @jananiravi - I'd be happy to discuss your questions with you. Do you have availability this week?

**Comment by jananiravi** [comment]
Yes, I do: http://bit.ly/janani-cucal (e.g., Fri 11a MT or Thu 11.30a MT)

**Comment by nicolevasilevsky** [comment]
Update, I talked to Janani and her questions do not pertain to the mass obsoletion of infectious diseases but rather the modeling of human and non-human infectious diseases. She'll follow up with Katie and Sabrina.

**Comment by sabrinatoro** [comment]
Spreadsheet to review: 
https://docs.google.com/spreadsheets/d/10-arJXZ8KhdUYyAIX8b23sTGTkYZ_sIrLa7BrCfG7yc/edit#gid=1933162704

**Comment by sabrinatoro** [comment]
@nicolevasilevsky, @katiermullen or @twhetzel 
The spreadsheet is ready for review. Thank you.

**Comment by katiermullen** [comment]
@sabrinatoro I reviewed this spreadsheet and had only one comment. I saw your note: "at this point, the PR has too many conflicts, it is easier to update the spreadsheet. I will check what parental decisions were made in the PR."

Happy to review again if needed :)

**Comment by sabrinatoro** [comment]
Thank you everyone. 
I will take a look soon!

**Comment by sabrinatoro** [comment]
Note: there are 2 terms: 
prion disease	(MONDO:0005429) : could be inherited or infectious disease, classified as a "neurological disorder"
human prion disease (MONDO:0018926) : infectious disease

I added the parent "prion disease" for the children who are related in mutation in the prion protein (because it fits the definition of "prion disease".
More clean-up and review is needed as part of #6774

**Comment by sabrinatoro** [comment]
There are some comments from the community that should be reviewed, but this is future work. This issue can be closed for now.
