### ISSUE TITLE
TRPM3-Related Neurodevelopmental Disorder

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6682]
We are working on a NORD report for this condition.  It is listed in OMIM as Neurodevelopmental disorder with hypotonia, dysmorphic facies, and skeletal anomalies, with or without seizures (https://www.omim.org/entry/620224). There is also a GeneReview:  https://www.ncbi.nlm.nih.gov/books/NBK589387/

Thank you, Gioconda Alyea

**Comment by nicolevasilevsky** [comment]
@galyea123 this was recently added to Mondo, you can see it here:
https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0859365

**Comment by galyea123** [comment]
Thank you Nicole!
