### ISSUE TITLE
Plan for MONDO equivalent xrefs

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/mondo#6688]
Hi @sabrinatoro sorry to bother you during your very busy push towards November releases. I've just been reading these issues on about removing MONDO DB xrefs and associated synonyms for now:
https://github.com/EBISPOT/ols4/issues/369
https://github.com/EBISPOT/ols4/issues/368
https://github.com/monarch-initiative/mondo/issues/6292

Will MONDO DB xrefs that indicate equivalent mappings make a return? I understand they are not true exact semantic matches but we find the OMIM and ORDO xrefs useful for our registries

**Comment by matentzn** [comment]
@peupeubangbang I will try to answer on Sabrinas behalf while she is travelling;

We are by no means removing the equivalent mappings - they are all in Mondo, and still are. Can I ask how you interact with Mondo, through OLS? Or do you download the file?

The exact mapping at the moment are redundant: they are both xrefs, and skos:exactMatch. We will likely only maintain skos:exactMatch.


But I think your issue relates more to https://github.com/EBISPOT/ols4/issues/502. OLS is not showing _any_ mappings right now! Its a bug that will be resolved soon.

**Comment by peupeubangbang** [comment]
Thanks @matentzn! That makes perfect sense as yes we normally interact via OLS
