### ISSUE TITLE
Request for change in the title/description for MONDO:0013579

### ISSUE THREAD

**Issue by jennygoldstein** [monarch-initiative/mondo#669]
We are requesting a change in the title/description for MONDO:0013579 from "developmental delay due to methylmalonate semialdehyde dehydrogenase deficiency" to "methylmalonate semialdehyde dehydrogenase deficiency". 
In discussion with experts in the ClinGen Aminoacidopathy Gene Curation Expert Panel, it was felt that "methylmalonate semialdehyde dehydrogenase deficiency" was a more appropriate descriptor for this condition because the condition is characterized by many clinical symptoms in addition to developmental delay. Furthermore, the OMIM description for this condition is "methylmalonate semialdehyde dehydrogenase deficiency" (MIM# 614105).

All other information for this entry can remain as is. 
 
Thank you for your consideration.

ORCID id: 0000-0002-5655-9589

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall any objections to this revision? I will create a PR and make these edits asap.
