### ISSUE TITLE
[mass Obsolete] children of idiopathic disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6691]
http://purl.obolibrary.org/obo/MONDO_0700007 | idiopathic disease | http://purl.obolibrary.org/obo/MONDO_0008347 | idiopathic and/or familial pulmonary arterial hypertension
-- | -- | -- | --
http://purl.obolibrary.org/obo/MONDO_0700007 | idiopathic disease | http://purl.obolibrary.org/obo/MONDO_0016352 | idiopathic inherited hypercalciuria

**Comment by twhetzel** [comment]
@nicolevasilevsky I don't see `idiopathic inherited hypercalciuria` in the PR for https://github.com/monarch-initiative/mondo/pull/6703

**Comment by nicolevasilevsky** [comment]
good catch. :) the script threw up an error and it was because that term was already obsoleted, hence I did not obsolete it on the linked PR.
