### ISSUE TITLE
[mass Obsolete] otorhinolaryngologic disease terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6694]
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0017240 | acrodysostosis with multiple hormone resistance
-- | -- | -- | --
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0016647 | autosomal recessive Stickler syndrome
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0015385 | external auditory canal aplasia/hypoplasia
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0018562 | hereditary otorhinolaryngological malformation
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0018187 | hereditary syndromic Pierre Robin syndrome
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0015504 | larynx anomaly
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0015503 | nose and cavum anomaly
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0015482 | otomandibular dysplasia
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0015323 | teratogenic Pierre Robin syndrome
http://purl.obolibrary.org/obo/MONDO_0024623 | otorhinolaryngologic disease | http://purl.obolibrary.org/obo/MONDO_0015505 | tracheal anomaly

MONDO:0017240
MONDO:0016647
MONDO:0015385
MONDO:0018562
MONDO:0018187
MONDO:0015504
MONDO:0015503
MONDO:0015482
MONDO:0015323
MONDO:0015505

**Comment by twhetzel** [comment]
For `hereditary otorhinolaryngological malformation` I can not find one of it's direct children `intractable diarrhea-choanal atresia-eye anomalies syndrome` in the diff.
