### ISSUE TITLE
Request for change in the title/description for MONDO:0009603 (HIBCH)

### ISSUE THREAD

**Issue by jennygoldstein** [monarch-initiative/mondo#670]
Similar to request #669, we are requesting a change in the title/description for MONDO:0009603 from "neurodegeneration due to 3-hydroxyisobutyryl-CoA hydrolase deficiency" to "3-hydroxyisobutyryl-CoA hydrolase deficiency". In discussion with experts in the ClinGen Aminoacidopathy Gene Curation Expert Panel, it was felt that "3-hydroxyisobutyryl-CoA hydrolase deficiency" was a more appropriate descriptor for this condition because the condition is characterized by many clinical symptoms in addition to neurodegeneration. Furthermore, the OMIM description for this condition is "3-hydroxyisobutyryl-CoA hydrolase deficiency" (MIM# 250620). 
All other information for this entry can remain as is. 

Thank you for your consideration. 

ORCID id: 0000-0002-5655-9589
--

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall I will go ahead and make this change on a PR, let me know if there are any objections
