### ISSUE TITLE
NACC1-related neurodevelopmental disorder with epilepsy, cataracts and episodic irritability

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#6700]
**Preferred gene-related syndrome label**
For example: NAA10-related syndrome
NACC1-related neurodevelopmental disorder with epilepsy, cataracts and episodic irritability

**Synonyms**
N/A
**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
neurodevelopmental disorder, complex neurodevelopmental disorder, and intellectual disability 

**Definition**
Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene. For example: Any congenital myopathy in which the cause of the disease is a mutation in the TPM3 gene.

A neurodevelopmental disorder caused by heterozygous variants in NACC1 and characterized by developmental delay, intellectual disability, epilepsy, cataracts, feeding difficulties, and recurring episodes of extreme irritability. Other phenotypes include hypotonia, delayed myelination, microcephaly, stereotypic hand movements, gastrointestinal tract issues, and sleeping problems. 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
Expert discussion among the chairs of the ClinGen Intellectual Disability and Autism GCEP. 

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
N/A
**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

https://clinicalgenome.org/affiliation/40006/

@ErinRiggs

**Comment by nicolevasilevsky** [comment]
Hi @icordovaG - thanks for reporting this. We are focused on a [mass obsoletion](https://github.com/monarch-initiative/mondo/issues?q=is%3Aissue+is%3Aopen+label%3A%22mass+obsoletion%22) effort this month, and will look at this (and your [other open tickets](https://github.com/monarch-initiative/mondo/issues/created_by/icordovaG)) more closely in November or later. We appreciate your patience. 😄
