### ISSUE TITLE
Autosomal Recessive Hyper IgE Syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6707]
### Label

Autosomal Recessive Hyper IgE Syndrome

### Synonym type

None

### Definition

The disorder is characterized by the triad of highly elevated levels of IgE in serum, recurring abscesses of the skin, and recurrent pneumonia AR-HIES is inherited as an autosomal recessive trait and the first symptoms include the development of a dry, red, flaky skin rash (eczema).

### Parent term

 Hyper-IgE syndrome

### Children term(s)

OMIM: 243700  615816  618282  618523  618944

### Website URL

https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=641368

### Additional comments

Hi!  I was not able to find this condition on MONDO, only subtypes.

**Comment by nicolevasilevsky** [comment]
Hi @galyea123 
We have this term: MONDO:0957426 'autosomal recessive hyper-IgE syndrome'

Please reopen if further action is needed
