### ISSUE TITLE
familial caudal dysgenesis

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6713]
MONDO:0010831

The link to Orphanet (Orphanet:1768) is not right.  It should be linked to https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=3174

**Comment by galyea123** [comment]
Hi Nicole!  It looks that the issue may be in ORPHANET as they has two different ways of landing in this page: https://www.orpha.net/consor/cgi-bin/Disease_Search.php?data_id=3174
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=1768
So, you may be good to close this one as the Orpha code linked to the disease is ORPHA 1768.
Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
thanks @galyea123!
