### ISSUE TITLE
TRPV4-related bone disorder RELABEL

### ISSUE THREAD

**Issue by RyanFWebb** [monarch-initiative/mondo#6715]
**Mondo term (ID and Label):**
[TRPV4-related bone disorder](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0018240)
MONDO:0018240

**Suggested new label:**
TRPV4-related skeletal dysplasia

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
0009-0003-2127-3550

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
I am requesting this relabel on behalf of ClinGen's Skeletal Disorders GCEP.

**Comment by nicolevasilevsky** [comment]
@RyanFWebb this tag is actually tagged for obsoletion, as it is a grouping class that groups together other disorders. Is this being used by your group?

cc @sabrinatoro

**Comment by RyanFWebb** [comment]
@nicolevasilevsky @sabrinatoro Yes, we plan to use this tag to group together brachyolmia (MONDO:0015262), spondylometaphyseal dysplasia, Kozlowski type (MONDO:0008477), spondyloepimetaphyseal dysplasia, Maroteaux type (MONDO:0008473), and metatropic dysplasia (MONDO:0007986).

We will be taking down the four separate curations we currently have published to ClinGen's website in substitute of a single curation with the title "TRPV4-related skeletal dysplasia".
