### ISSUE TITLE
Request for new term 'metabolic dysfunction-associated steatohepatitis'

### ISSUE THREAD

**Issue by tzukuo-evotec** [monarch-initiative/mondo#6716]
### Label

metabolic dysfunction-associated steatohepatitis

### Synonyms

mash

### Synonym type

related

### Definition

Metabolic dysfunction-associated steatohepatitis (MASH, formerly known as nonalcoholic steatohepatitis or NASH) is a type of fatty liver disease. It often develops due to a metabolic disorder, such as obesity or diabetes, resulting in a toxic buildup of fat in the liver. It is the most severe form of [metabolic dysfunction-associated steatotic liver disease](https://www.verywellhealth.com/how-dangerous-is-non-alcoholic-fatty-liver-disease-2223390) (MASLD, formerly known as nonalcoholic fatty liver disease or NAFLD).

### Parent term

MONDO:0004790 fatty liver disease, MONDO:0002251 hepatitis

### Website URL

https://www.verywellhealth.com/non-alcoholic-steatohepatitis-nash-5196357#toc-symptoms

**Comment by nicolevasilevsky** [comment]
HI @tzukuo-evotec - thanks for this ticket. As I noted on another ticket, we'll address this in or after November due to other priorities this month. Thanks for your patience!

**Comment by tzukuo-evotec** [comment]
Hi @nicolevasilevsky ,
Thank you for the message and efforts.

**Comment by nicolevasilevsky** [comment]
@tzukuo-evotec 

I think we should rename MONDO:0007027 'non-alcoholic steatohepatitis' to the label you requested above.

Please let me know if you have any objections, thanks!

**Comment by nicolevasilevsky** [comment]
Hi @tzukuo-evotec, we'll keep the old name as a synonym, so people will be able to find this term. I'll take care of this now and it should be available in the next release, which will be next week.
