### ISSUE TITLE
Request for new term 'metabolic dysfunction-associated steatotic liver disease'

### ISSUE THREAD

**Issue by tzukuo-evotec** [monarch-initiative/mondo#6718]
### Label

metabolic dysfunction-associated steatotic liver disease

### Synonyms

MASLD

### Synonym type

related

### Definition

Metabolic dysfunction-associated steatotic liver disease (MASLD, formerly known as nonalcoholic fatty liver disease or NAFLD) is a type of liver disease that is not caused by alcohol. It typically does not cause symptoms in the early stages, but it can cause health problems due to fat accumulation, inflammation, and scarring in the liver.

### Parent term

MONDO:0004790 fatty liver disease

### Website URL

https://www.verywellhealth.com/how-dangerous-is-non-alcoholic-fatty-liver-disease-2223390

**Comment by nicolevasilevsky** [comment]
Hi @tzukuo-evotec, thanks for the ticket. We are focused on a [mass obsoletion](https://github.com/monarch-initiative/mondo/issues?q=is%3Aissue+is%3Aopen+label%3A%22mass+obsoletion%22) effort this month, and will look at this more closely in November or later. We appreciate your patience.

**Comment by tzukuo-evotec** [comment]
Thank you for the message and efforts.

**Comment by tzukuo-evotec** [comment]
Thank you for the update, @nicolevasilevsky . It looks fine for me. Could you please also ensure that people unaware of the new name can find the disease (e.g., including the old name in the synonyms)? Furthermore, may I know when the change will be accessible to the public?
