### ISSUE TITLE
collagen 6-related myopathy

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6720]
I am suggesting to change the term name: 

Current term in MONDO: collagen 6-related myopathy MONDO:0100225

New label: Collagen VI-Related Dystrophies (as per GeneReviews myopathy is not really the feature but a muscular dystrophy) - Also notice the conditions included in the classification are still listed in Orphanet as separate conditions - I also sent a message to Orphanet.

https://www.ncbi.nlm.nih.gov/books/NBK1503/

**Comment by nicolevasilevsky** [comment]
@galyea123, thanks for the ticket. As I believe you know, we are focused on a [mass obsoletion](https://github.com/monarch-initiative/mondo/issues?q=is%3Aissue+is%3Aopen+label%3A%22mass+obsoletion%22) effort this month, and will look at this (and your other [open tickets](https://github.com/monarch-initiative/mondo/issues/created_by/galyea123)) more closely in November or later. We appreciate your patience.

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________

**Comment by nicolevasilevsky** [comment]
@galyea123 this term was requested by @RedRiver1816 and the ClinGen Congenital Myopathies expert panel, let me ask them about this revision.

@RedRiver1816, could you please comment if the term you requested is the same as the term above? Or perhaps should we add a separate term that is labeled Collagen VI-Related Dystrophy?

Thanks!

Related to: https://github.com/monarch-initiative/mondo/issues/2214

**Comment by RedRiver1816** [comment]
Hi @nicolevasilevsky, Thanks for the ping! Unfortunately I'm no longer a member of the Congenital Myopathies GCEP. In my opinion the reasoning above is relatively sound to use the term "dystrophies" as opposed to "myopathy", however it also might be prudent to contact a current member of the GCEP (https://clinicalgenome.org/affiliation/40031/). Hopefully one of them is still active on here and can chime in!

**Comment by nicolevasilevsky** [comment]
@justyneross, could you please comment on this if you have a moment?

**Comment by Mohan-Shruthi** [comment]
@nicolevasilevsky The ClinGen Limb-girdle muscular dystrophy (now [Muscular Dystrophies and Myopathies](https://clinicalgenome.org/affiliation/40151/)) GCEP would prefer the term "myopathy" for the Collagen-6-related disorders. We collaborated with the Congenital Myopathies GCEP on these curations, and both panels prefer it to be "myopathy".

**Comment by galyea123** [comment]
Hi!  The reason why GR is using the term "dystrophy" is related to the histologic changes that are found in the muscle biopsy and the progressive nature of the individual conditions included in the Collagen-6 related disorders.

Please see:

https://www.ncbi.nlm.nih.gov/books/NBK1503/
https://pubmed.ncbi.nlm.nih.gov/18351526/
https://www.ninds.nih.gov/health-information/disorders/muscular-dystrophy    Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
@galyea123 I added this as a synonym. Thank you!
