### ISSUE TITLE
Mass obsoletion strategy

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6731]
A summary of all the branches to review can be found [here](https://docs.google.com/spreadsheets/d/1xTfYCOCGKx_svNT8PirgGDiCINV7IDqzhBk76DNe150/edit#gid=0)

1. Create a **MASTER document with ALL the branches and ALL the children of obsoletion candidates**
- This will allow to check children which are in multiple branches
- Sabrina will review this master document and split it in “bite sizes”. These bite sizes will be: 
           - Review only children which will become orphan or leave the branch
           - Each reviewer will have “one unit of review” which will be a branch or part of a branch (depending on the amount of children to review)

2. **Reviewers**: 
**to-do:** 
    - For orphan-to-be terms: find a parent (within the branch or outside the branch, whichever makes more sense)
    - For terms that will leave the branch: check whether the term should remain in the branch. If so, find a parent in the branch (it is ok if it is “high level”, ie parent is not as specific as could be)

**How?** 
3 new columns: 
    - Mondo ID for the new parent term
    - (optional, but easier for review): new parent term name
    - ORCID and/or PMID
Note: if more than one parent should be added, create new columns (ie only 1 parent per column)

**Notes:** 
    - we are not reviewing the terms that will remain in the branch (this work will be for a later full branch review)
    - new parents do not have to be "as precise as possible" (this will be for a later full branch review)
    - The “ancestor” columns in the spreadsheet can help with finding new parents
    - Some children will be in multiple branches. (Sabrina to review the master branch and make sure these are taken into consideration when creating the "unit of review")

3. **Implementation**
When a reviewer is done with their "unit of review", we will
- obsolete all the obsoletion candidates in their "unit of review", 
- update classification based on new parentage, 
- create a PR and resolve errors in checks (we expect these to be mostly single child error checks)
- merge the PR

**Comment by sabrinatoro** [comment]
work to create the review spreadsheet is here: 
https://github.com/monarch-initiative/mondo/pull/6648

**Comment by nicolevasilevsky** [comment]
[Video describing mass obsoletion review](https://drive.google.com/file/d/1Be2Uh3bi-ni8bUOTlhxn6YvD31bEsDgX/view)

**Comment by sabrinatoro** [comment]
Spreadsheets to review are [here](https://drive.google.com/drive/folders/1prTU0Wv5OGY-Hw3uSej2v3_XeyaDEYZH). Each issue for each branch also has a link to the branch-specific spreadsheet. 

Note: we decided against a master spreadsheet

**Comment by sabrinatoro** [comment]
General notes about the process [here](https://docs.google.com/document/d/17cuTd7E89ccfUWOfvJTLheGzViw2zFA8DeztKrcxtGY/edit)

**Comment by sabrinatoro** [comment]
I think this issue can be closed.
