### ISSUE TITLE
PATO_0000051 built as both an object property and a Class. 

### ISSUE THREAD

**Issue by gabbysantos** [monarch-initiative/mondo#6737]
**Mondo term (ID Label)**
[PATO_0000051]

**Bug/Typo/Error description**
[PATO_0000051] is built as both a class and a object property. This is seen in the owl file, and also on OLS. I think the class [PATO_0000051] in this case is the correct modelling, as the class is expected and the object property has no metadata or usage. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Hi @gabbysantos - thanks for reporting. yes, this is strange! I'll talk to my team about it and we'll get back to you.

**Comment by nicolevasilevsky** [comment]
@twhetzel reassigning this to you. We've discussed this and I believe the solution was to update imports. Can you close this when this has been addressed? Thanks!

**Comment by twhetzel** [comment]
Based on https://github.com/monarch-initiative/mondo/issues/6712, the imports should be able to be updated now and will work with @sabrinatoro to get this done.

**Comment by twhetzel** [comment]
Fixed with https://github.com/monarch-initiative/mondo/pull/6961
