### ISSUE TITLE
Mass Obsoletion: focus on branch 'immune system disorder' (MONDO:0005046)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6747]
branch:  'immune system disorder' (MONDO:0005046)

terms to obsolete: 
obsoletion candidate ID | obsoletion candidate label
-- | --
http://purl.obolibrary.org/obo/MONDO_0015822 | acquired neutropenia
http://purl.obolibrary.org/obo/MONDO_0015818 | aggressive primary cutaneous B-cell lymphoma
http://purl.obolibrary.org/obo/MONDO_0016599 | autosomal dominant secondary polycythemia
http://purl.obolibrary.org/obo/MONDO_0016536 | autosomal recessive lymphoproliferative disease
http://purl.obolibrary.org/obo/MONDO_0018720 | common cystic lymphatic malformation
http://purl.obolibrary.org/obo/MONDO_0016495 | functional variant of Guillain-Barre syndrome
http://purl.obolibrary.org/obo/MONDO_0015975 | hyper-IgM syndrome with susceptibility to opportunistic infections
http://purl.obolibrary.org/obo/MONDO_0015976 | hyper-IgM syndrome without susceptibility to opportunistic infections
http://purl.obolibrary.org/obo/MONDO_0015132 | immunodeficiency predominantly affecting antibody production
http://purl.obolibrary.org/obo/MONDO_0017036 | Langerhans cell histiocytosis in childhood and adulthood
http://purl.obolibrary.org/obo/MONDO_0020537 | occupational allergic alveolitis
http://purl.obolibrary.org/obo/MONDO_0015823 | primary immunodeficiency due to a defect in adaptive immunity
http://purl.obolibrary.org/obo/MONDO_0015135 | primary immunodeficiency due to a genetic defect in innate immunity
http://purl.obolibrary.org/obo/MONDO_0015133 | quantitative and/or qualitative congenital phagocyte defect
http://purl.obolibrary.org/obo/MONDO_0016494 | regional variant of Guillain-Barre syndrome
http://purl.obolibrary.org/obo/MONDO_0018745 | superficial pemphigus
http://purl.obolibrary.org/obo/MONDO_0019520 | syndromic lymphedema
http://purl.obolibrary.org/obo/MONDO_0016493 | variant of Guillain-Barre syndrome

**Comment by nicolevasilevsky** [comment]
[Spreadsheet is here](https://docs.google.com/spreadsheets/d/1sM0jLlQQAfaO4NzuB588QF8kjWdy3ZsJZy29-TJol1U/edit#gid=1407578343)

**Comment by nicolevasilevsky** [comment]
Hi @LCCarmody - I review the orphaned classes and it looks good. I made one comment.

Do you want to proceed with reviewing the 'leaves the branch' terms?

**Comment by LCCarmody** [comment]
Sorry, I missed this message. And I'm not sure what 'reviewing the 'leaves the branch' terms' means, exactly... Same process just see if it is correct?

**Comment by nicolevasilevsky** [comment]
Yes - similar process. Your [spreadsheet](https://docs.google.com/spreadsheets/d/1sM0jLlQQAfaO4NzuB588QF8kjWdy3ZsJZy29-TJol1U/edit#gid=1407578343) is filtered on terms that leave the branch. This means that when we obsolete their parent(s), they will no longer be a type of immune system disorder. The goal is to review the terms, definitions, etc. and decide if they should be a type of immune system disorder (either a child of that parent class or something more specific in that branch) or if it is okay if they leave the branch. You can look at the other parents the term has in columns F-I or you can look at it in the ontology. 

If you think it should have a new parent that is in the immune system disorder branch, please add the new parent like before.

If you think it's okay to leave the branch, just leave columns K-N blank but assign your curator confidence, so we know you looked at it.

Thanks @LCCarmody !

**Comment by nicolevasilevsky** [comment]
no problem, @LCCarmody! Thanks for doing this!

**Comment by LCCarmody** [comment]
just finished. Have a few uncertainties.

**Comment by nicolevasilevsky** [comment]
@LCCarmody  I am done reviewing, do you want to review my comments and let me know if you have any questions?

**Comment by LCCarmody** [comment]
Sorry, if i wasn't clear I am done reviewing. I agreed with Nicole's review--just had some questions about what is a feature. I added in all the requests. @sabrinatoro @nicolevasilevsky

**Comment by sabrinatoro** [comment]
There are some comments from the community that should be reviewed, but this is future work. This issue can be closed for now.
