### ISSUE TITLE
merge Leigh syndrome with parent

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#675]
LS into LD

Consider first the intended semantics of MONDO:0009723 equivalentTo OMIM:256000, is this a specific form or the generic form?

**Comment by cmungall** [comment]
OMIM currently lumps diseases with different etiologies: https://www.omim.org/entry/256000

We could make subtypes for these easily

It seems possible that at one point they will select one to go with the 256000, we should then go back and check our equivalence axioms

**Comment by pnrobinson** [comment]
Leigh syndrome is the more common term. I have not heard people say Leigh disease. This is a distinct issue from the genetic subtypes. For this refer to OMIM phenoseries

**Comment by courtneythaxton** [comment]
I agree with @pnrobinson. the ClinGen Mitochondrial Disease Gene Curation Expert Panel has chosen to curate under the MONDO ID MONDO:0009723, specifically for the nomenclature of Leigh Syndrome.
