### ISSUE TITLE
Mass Obsoletion: focus on branch 'nervous system disorder' (MONDO:0005071)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6752]
branch: 'nervous system disorder' (MONDO:0005071)
Terms to obsolete: 

obsoletion candidate ID | obsoletion candidate label
-- | --
http://purl.obolibrary.org/obo/MONDO_0016179 | acquired amyloid peripheral neuropathy
http://purl.obolibrary.org/obo/MONDO_0020125 | acquired neuromuscular junction disease
http://purl.obolibrary.org/obo/MONDO_0016375 | acquired peripheral movement disorder
http://purl.obolibrary.org/obo/MONDO_0016172 | acquired sensory ganglionopathy
http://purl.obolibrary.org/obo/MONDO_0020343 | alpha-crystallinopathy
http://purl.obolibrary.org/obo/MONDO_0017241 | AP4-related intellectual disability and spastic paraplegia
http://purl.obolibrary.org/obo/MONDO_0015921 | ARX-related epileptic encephalopathy
http://purl.obolibrary.org/obo/MONDO_0034901 | ATP13A2-related parkinsonism
http://purl.obolibrary.org/obo/MONDO_0016980 | ATR-X-related syndrome
http://purl.obolibrary.org/obo/MONDO_0038268 | autoimmune neurological channelopathy
http://purl.obolibrary.org/obo/MONDO_0015360 | autosomal dominant hereditary axonal motor and sensory neuropathy
http://purl.obolibrary.org/obo/MONDO_0015359 | autosomal dominant hereditary demyelinating motor and sensory neuropathy
http://purl.obolibrary.org/obo/MONDO_0015365 | autosomal dominant hereditary sensory and autonomic neuropathy
http://purl.obolibrary.org/obo/MONDO_0016224 | autosomal dominant proximal spinal muscular atrophy
http://purl.obolibrary.org/obo/MONDO_0015088 | autosomal dominant pure spastic paraplegia
http://purl.obolibrary.org/obo/MONDO_0015089 | autosomal recessive complex spastic paraplegia
http://purl.obolibrary.org/obo/MONDO_0016109 | autosomal recessive distal myopathy
http://purl.obolibrary.org/obo/MONDO_0008406 | autosomal recessive Emery-Dreifuss muscular dystrophy
http://purl.obolibrary.org/obo/MONDO_0015361 | autosomal recessive hereditary demyelinating motor and sensory neuropathy
http://purl.obolibrary.org/obo/MONDO_0015366 | autosomal recessive hereditary sensory and autonomic neuropathy
http://purl.obolibrary.org/obo/MONDO_0014753 | autosomal recessive optic atrophy
http://purl.obolibrary.org/obo/MONDO_0015090 | autosomal recessive pure spastic paraplegia
http://purl.obolibrary.org/obo/MONDO_0016647 | autosomal recessive Stickler syndrome
http://purl.obolibrary.org/obo/MONDO_0018775 | axonal hereditary motor and sensory neuropathy
http://purl.obolibrary.org/obo/MONDO_0015586 | benign familial mesial temporal lobe epilepsy
http://purl.obolibrary.org/obo/MONDO_0015144 | brain inflammatory disease
http://purl.obolibrary.org/obo/MONDO_0016115 | bulbospinal muscular atrophy of adulthood
http://purl.obolibrary.org/obo/MONDO_0016114 | bulbospinal muscular atrophy of childhood
http://purl.obolibrary.org/obo/MONDO_0017104 | central nervous system cystic malformation
http://purl.obolibrary.org/obo/MONDO_0015915 | cerebellar malformation
http://purl.obolibrary.org/obo/MONDO_0016054 | cerebral malformation
http://purl.obolibrary.org/obo/MONDO_0019213 | cerebral organic aciduria
http://purl.obolibrary.org/obo/MONDO_0016169 | chronic acquired demyelinating polyneuropathy
http://purl.obolibrary.org/obo/MONDO_0020069 | chronic encephalitis
http://purl.obolibrary.org/obo/MONDO_0016170 | chronic polyradiculoneuropathy
http://purl.obolibrary.org/obo/MONDO_0018788 | COL4A1 or COL4A2-related cerebral small vessel disease
http://purl.obolibrary.org/obo/MONDO_0018277 | congenital muscular dystrophy with cerebellar involvement
http://purl.obolibrary.org/obo/MONDO_0018279 | congenital muscular dystrophy without intellectual disability
http://purl.obolibrary.org/obo/MONDO_0018144 | congenital myasthenic syndromes with glycosylation defect
http://purl.obolibrary.org/obo/MONDO_0020256 | congenital trochlear nerve palsy
http://purl.obolibrary.org/obo/MONDO_0020132 | cranial nerve and nuclear aplasia
http://purl.obolibrary.org/obo/MONDO_0015141 | disorder of medulla oblongata
http://purl.obolibrary.org/obo/MONDO_0016899 | Duchenne and Becker muscular dystrophy
http://purl.obolibrary.org/obo/MONDO_0016708 | embryonal tumor of neuroepithelial tissue
http://purl.obolibrary.org/obo/MONDO_0013742 | familial mesial temporal lobe epilepsy with febrile seizures
http://purl.obolibrary.org/obo/MONDO_0016495 | functional variant of Guillain-Barre syndrome
http://purl.obolibrary.org/obo/MONDO_0016116 | generalized bulbospinal muscular atrophy
http://purl.obolibrary.org/obo/MONDO_0017114 | global cerebellar malformation
http://purl.obolibrary.org/obo/MONDO_0957009 | hereditary posterior fossa malformation
http://purl.obolibrary.org/obo/MONDO_0018831 | HTRA1-related cerebral small vessel disease
http://purl.obolibrary.org/obo/MONDO_0018779 | hypercontractile muscle stiffness syndrome
http://purl.obolibrary.org/obo/MONDO_0018743 | immune-mediated acquired neuromuscular junction disease
http://purl.obolibrary.org/obo/MONDO_0016756 | inherited nervous system cancer-predisposing syndrome
http://purl.obolibrary.org/obo/MONDO_0017234 | inherited prion disease
http://purl.obolibrary.org/obo/MONDO_0020238 | inherited vitreous-retinal disease
http://purl.obolibrary.org/obo/MONDO_0035002 | isolated inherited retinal disorder
http://purl.obolibrary.org/obo/MONDO_0016815 | Leigh syndrome with leukodystrophy
http://purl.obolibrary.org/obo/MONDO_0016816 | Leigh syndrome with nephrotic syndrome
http://purl.obolibrary.org/obo/MONDO_0015591 | limbic encephalitis associated with antibodies to cell membrane antigens
http://purl.obolibrary.org/obo/MONDO_0020131 | malformation of the cerebellar hemispheres
http://purl.obolibrary.org/obo/MONDO_0020130 | malformation of the cerebellar vermis
http://purl.obolibrary.org/obo/MONDO_0017090 | midline cerebral malformation
http://purl.obolibrary.org/obo/MONDO_0019758 | midline interhemispheric variant of holoprosencephaly
http://purl.obolibrary.org/obo/MONDO_0017656 | motor stereotypies
http://purl.obolibrary.org/obo/MONDO_0018791 | Moyomoya angiopathy
http://purl.obolibrary.org/obo/MONDO_0016428 | multiple sclerosis variant
http://purl.obolibrary.org/obo/MONDO_0019486 | myoclonic epilepsy of infancy
http://purl.obolibrary.org/obo/MONDO_0017059 | neural tube closure defect
http://purl.obolibrary.org/obo/MONDO_0016726 | neuronal tumor
http://purl.obolibrary.org/obo/MONDO_0015145 | neurovascular malformation
http://purl.obolibrary.org/obo/MONDO_0016592 | non-hereditary degenerative ataxia
http://purl.obolibrary.org/obo/MONDO_0016173 | non-paraneoplastic sensory ganglionopathy
http://purl.obolibrary.org/obo/MONDO_0015219 | non-syndromic central nervous system malformation
http://purl.obolibrary.org/obo/MONDO_0016701 | oligoastrocytic tumor
http://purl.obolibrary.org/obo/MONDO_0020506 | ovarioleukodystrophy
http://purl.obolibrary.org/obo/MONDO_0016174 | paraneoplastic sensory ganglionopathy
http://purl.obolibrary.org/obo/MONDO_0018329 | persistent combined dystonia
http://purl.obolibrary.org/obo/MONDO_0016721 | pineal tumor of neuroepithelial tissue
http://purl.obolibrary.org/obo/MONDO_0020133 | posterior fossa malformation
http://purl.obolibrary.org/obo/MONDO_0020345 | presynaptic congenital myasthenic syndrome
http://purl.obolibrary.org/obo/MONDO_0016738 | primary germ cell tumor of central nervous system
http://purl.obolibrary.org/obo/MONDO_0016744 | primary melanocytic tumor of central nervous system
http://purl.obolibrary.org/obo/MONDO_0017651 | primary myoclonus
http://purl.obolibrary.org/obo/MONDO_0035014 | primary orthostatic disorder
http://purl.obolibrary.org/obo/MONDO_0018283 | primary qualitative or quantitative defects of alpha-dystroglycan
http://purl.obolibrary.org/obo/MONDO_0018580 | PURA-related severe neonatal hypotonia-seizures-encephalopathy syndrome
http://purl.obolibrary.org/obo/MONDO_0017914 | pure or complex autosomal dominant spastic paraplegia
http://purl.obolibrary.org/obo/MONDO_0017915 | pure or complex autosomal recessive spastic paraplegia
http://purl.obolibrary.org/obo/MONDO_0017916 | pure or complex X-linked spastic paraplegia
http://purl.obolibrary.org/obo/MONDO_0016152 | qualitative or quantitative defects of calpain
http://purl.obolibrary.org/obo/MONDO_0016196 | qualitative or quantitative defects of emerin
http://purl.obolibrary.org/obo/MONDO_0016157 | qualitative or quantitative defects of fukutin
http://purl.obolibrary.org/obo/MONDO_0016200 | qualitative or quantitative defects of glucosamine (UDP-N-acetyl)-2-epimerase/N-acetylmannosamine kinase
http://purl.obolibrary.org/obo/MONDO_0016150 | qualitative or quantitative defects of integrin alpha-7
http://purl.obolibrary.org/obo/MONDO_0016149 | qualitative or quantitative defects of merosin
http://purl.obolibrary.org/obo/MONDO_0016201 | qualitative or quantitative defects of myotilin
http://purl.obolibrary.org/obo/MONDO_0016154 | qualitative or quantitative defects of myotubularin
http://purl.obolibrary.org/obo/MONDO_0016183 | qualitative or quantitative defects of protein glycosyltransferase-like
http://purl.obolibrary.org/obo/MONDO_0016182 | qualitative or quantitative defects of protein O-mannose beta1, 2N-acetylglucosaminyltransferase
http://purl.obolibrary.org/obo/MONDO_0018529 | qualitative or quantitative defects of Torsin-1A-interacting protein 1
http://purl.obolibrary.org/obo/MONDO_0017302 | qualitative or quantitative defects of troponin
http://purl.obolibrary.org/obo/MONDO_0016494 | regional variant of Guillain-Barre syndrome
http://purl.obolibrary.org/obo/MONDO_0022407 | retinal ciliopathy due to mutation in Bardet-Biedl gene
http://purl.obolibrary.org/obo/MONDO_0022405 | retinal ciliopathy due to mutation in nephronophthisis gene
http://purl.obolibrary.org/obo/MONDO_0022397 | retinal ciliopathy due to mutation in the retinitis pigmentosa-1 gene
http://purl.obolibrary.org/obo/MONDO_0022399 | retinal ciliopathy due to mutation in the RPGR gene
http://purl.obolibrary.org/obo/MONDO_0022400 | retinal ciliopathy due to mutation in the RPGRIP gene
http://purl.obolibrary.org/obo/MONDO_0022404 | retinal ciliopathy due to mutation in Usher gene
http://purl.obolibrary.org/obo/MONDO_0016355 | semilobar holoprosencephaly
http://purl.obolibrary.org/obo/MONDO_0017218 | septopreoptic holoprosencephaly
http://purl.obolibrary.org/obo/MONDO_0017629 | sodium channelopathy-related small fiber neuropathy
http://purl.obolibrary.org/obo/MONDO_0018550 | spastic paraplegia-optic atrophy-neuropathy and spastic paraplegia-optic atrophy-neuropathy-related disorder
http://purl.obolibrary.org/obo/MONDO_0035561 | sporadic human prion disease
http://purl.obolibrary.org/obo/MONDO_0020346 | synaptic congenital myasthenic syndrome
http://purl.obolibrary.org/obo/MONDO_0020240 | syndromic retinitis pigmentosa
http://purl.obolibrary.org/obo/MONDO_0034954 | syndromic vitreoretinopathy
http://purl.obolibrary.org/obo/MONDO_0016493 | variant of Guillain-Barre syndrome
http://purl.obolibrary.org/obo/MONDO_0020339 | X-linked complex spastic paraplegia
http://purl.obolibrary.org/obo/MONDO_0018451 | X-linked distal hereditary motor neuropathy
http://purl.obolibrary.org/obo/MONDO_0018222 | X-linked intellectual disability due to GRIA3 anomalies
http://purl.obolibrary.org/obo/MONDO_0017912 | X-linked pure spastic paraplegia

**Comment by sabrinatoro** [comment]
Spreadsheet here: https://docs.google.com/spreadsheets/d/1Kju7OyUw8l-5n1nfRKUn3t0193XXs8y9BupzBtmYWAI/edit#gid=1960015202

**Comment by sabrinatoro** [comment]
@nicolevasilevsky @twhetzel (also adding @katiermullen as I think she can help review the spreadsheet).

I am done with the "nervous system disorder" review of the spreadsheet (both orphan and leaves the branch). Please take a look whenever you can, as there are a few low-medium confidence. 

Whenever the review of the spreadsheet is done, I can go through the obsoletion pipeline. 
Thank you!

**Comment by sabrinatoro** [comment]
IMPORTANT NOTE:
I think we should not obsolete MONDO:0016054 - cerebral malformation after all. 
All the children are really "brain malformation". We might, in the future, review all the "malformation" terms in favor to a HPO term, but as for now, this term is the best for what we need. Please comment if you agree/disagree.

**Comment by sabrinatoro** [comment]
'Human prion disease' (MONDO:0018926)  and 'prion disease' (MONDO:0005429) should probably be merged. New issue: https://github.com/monarch-initiative/mondo/issues/6774

**Comment by nicolevasilevsky** [comment]
@sabrinatoro  - I just have one comment on here for you to review before this is ROBOT'd

**Comment by sabrinatoro** [comment]
There are some comments from the community that should be reviewed, but this is future work. This issue can be closed for now.
