### ISSUE TITLE
Mass Obsoletion: focus on branch 'reproductive system disorder' (MONDO:0005039)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6753]
branch 'reproductive system disorder' (MONDO:0005039)

Terms to Obsolete: 
obsoletion candidate ID | obsoletion candidate label
-- | --
http://purl.obolibrary.org/obo/MONDO_0017961 | 46,XX disorder of gonadal development
http://purl.obolibrary.org/obo/MONDO_0020039 | 46,XX disorder of sex development induced by androgens excess
http://purl.obolibrary.org/obo/MONDO_0017963 | 46,XX disorder of sex development induced by endogenous maternal-derived androgen
http://purl.obolibrary.org/obo/MONDO_0017964 | 46,XX disorder of sex development induced by exogenous maternal-derived androgen
http://purl.obolibrary.org/obo/MONDO_0019593 | 46,XX disorder of sex development induced by fetal androgens excess
http://purl.obolibrary.org/obo/MONDO_0017962 | 46,XX disorder of sex development induced by fetoplacental androgens excess
http://purl.obolibrary.org/obo/MONDO_0019608 | 46,XX disorder of sex development induced by maternal-derived androgen
http://purl.obolibrary.org/obo/MONDO_0017966 | 46,XY disorder of gonadal development
http://purl.obolibrary.org/obo/MONDO_0019597 | 46,XY disorder of sex development due to isolated 17,20-lyase deficiency
http://purl.obolibrary.org/obo/MONDO_0017974 | 46,XY disorder of sex development induced by maternal-exposure to endocrine disruptors
http://purl.obolibrary.org/obo/MONDO_0017969 | 46,XY disorder of sex development of endocrine origin
http://purl.obolibrary.org/obo/MONDO_0015860 | anomaly of puberty or/and menstrual cycle
http://purl.obolibrary.org/obo/MONDO_0016072 | anomaly of puberty or/and menstrual cycle of genetic origin
http://purl.obolibrary.org/obo/MONDO_0015853 | deficient breast volume or number
http://purl.obolibrary.org/obo/MONDO_0015852 | excess breast volume or number
http://purl.obolibrary.org/obo/MONDO_0957024 | hereditary 46,XX disorder of sex development
http://purl.obolibrary.org/obo/MONDO_0957025 | hereditary 46,XY disorder of sex development
http://purl.obolibrary.org/obo/MONDO_0019505 | hypomyelination-hypogonadotropic hypogonadism-hypodontia syndrome
http://purl.obolibrary.org/obo/MONDO_0018393 | male infertility with azoospermia or oligozoospermia due to single gene mutation
http://purl.obolibrary.org/obo/MONDO_0018575 | microcephalic primordial dwarfism-insulin resistance syndrome
http://purl.obolibrary.org/obo/MONDO_0017173 | non-syndromic male infertility due to sperm motility disorder
http://purl.obolibrary.org/obo/MONDO_0015932 | non-syndromic urogenital tract malformation of female
http://purl.obolibrary.org/obo/MONDO_0015933 | non-syndromic urogenital tract malformation of male
http://purl.obolibrary.org/obo/MONDO_0015829 | non-syndromic uterovaginal malformation
http://purl.obolibrary.org/obo/MONDO_0015846 | syndromic uterovaginal malformation
http://purl.obolibrary.org/obo/MONDO_0015837 | Unicervical bicornuate uterus
http://purl.obolibrary.org/obo/MONDO_0015828 | uterovaginal malformation

**Comment by katiermullen** [comment]
Spreadsheet [here](https://docs.google.com/spreadsheets/d/17z5-YR6QVWdo2nft3N_UvGkI0rMhByGpZR_UC60J1mU/edit#gid=1859619485)

@sabrinatoro @nicolevasilevsky @twhetzel Please review "orphaned" and "leaves the branch" terms

**Comment by nicolevasilevsky** [comment]
Thanks @katiermullen! I can review this

**Comment by nicolevasilevsky** [comment]
@katiermullen this looks great. There were a few diseases that I assigned to a more specific parent. Please take a look and let me know if you disagree. Otherwise this is ready or mass obs pipeline

cc @sabrinatoro

**Comment by katiermullen** [comment]
@nicolevasilevsky I agree with your more specific parent assignments. Thank you!

**Comment by sabrinatoro** [comment]
There are some comments from the community that should be reviewed, but this is future work. This issue can be closed for now.
