### ISSUE TITLE
[Revise text def]

### ISSUE THREAD

**Issue by madysoncbrown** [monarch-initiative/mondo#6756]
**Bilateral frontoparietal polymicrogyria MONDO:0011738**

**Bilateral frontoparietal polymicrogyria (BFPP) is a descriptive term reflecting increased gyral folding in the frontoparietal regions as determined by magnetic resonance imaging. It has subsequently been shown to represent a cobblestone malformation on histopathology. BFPP typically presents with hypotonia, developmental delay, moderate to severe intellectual disability, pyramidal signs, epileptic seizures, non-progressive cerebellar ataxia, deconjugate gaze, and/or strabismus. **

**https://www.clinicalgenome.org/affiliation/40020/**

**Comment by nicolevasilevsky** [comment]
Hi @madysoncbrown - thanks for this ticket. We'll work on this in November or later, thank you for your patience.

**Comment by nicolevasilevsky** [comment]
Thanks @madysoncbrown, I updated this definition.
