### ISSUE TITLE
SF3B4-related acrofacial dysostosis/ SF3B4

### ISSUE THREAD

**Issue by eedoh01** [monarch-initiative/mondo#6760]
**Preferred gene-related syndrome label**
 SF3B4-related acrofacial dysostosis

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

MONDO:0018237

**Definition**
This is a congenital malformation syndrome characterized by mandibulofacial dysostosis and anterior upper-limb defects, though occasionally, lower-limb defects have also been reported. Intrafamilial variability has been observed along with phenotype variability and severity including shoulder and pelvic girdle hypoplasia, fibular hypoplasia and eleven ribs 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID: 22541558, 24003905, 24715698, 27622494

**Your nano-attribution (ORCID) or URL for a working group**

https://clinicalgenome.org/affiliation/40059/

**Comment by nicolevasilevsky** [comment]
Thanks @eedoh01. We will address this in or after November, thanks for your patience.

**Comment by eedoh01** [comment]
Thanks @nicolevasilevsky! Have a great day
