### ISSUE TITLE
Update "affected status" rules

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6762]
I missed the fact that we sometimes end up with only “disease” as a parent. Could you please update the spreadsheet so that you follow the rules below: 
New rules: 
- **_(unchanged)_** if there is at least 1 (not obsoletion candidate) term in Col F (=other direct parents in branch) AND, if there is only  (whatever parents are in Col G -”other direct parents NOT in branch”) --> STAYS IN THE BRANCH
- if there is NO (not obsoletion candidate) term in Col F (=other direct parents in branch) AND at least 1 term in Col G (=other direct parents NOT in branch) that is not obsoletion candidate, and/or “disease” (MONDO:0000001), and/or “human disease” (MONDO:0700096)** --> LEAVES THE BRANCH
- **if there is NO (not obsoletion candidate) term in F AND NO term in G --> ORPHAN**
- **if there is NO (not obsoletion candidate) term in F AND the only parents in Col G = “disease” (MONDO:0000001) and/or “human disease” (MONDO:0700096) and/or an obsoletion candidate--> ORPHAN**

**Comment by hrshdhgd** [comment]
Logic added .... should I update the spreadsheets or what do you recommend be the next steps?

**Comment by matentzn** [comment]
I dont know which spreadsheet is where now but be careful not to overwrite the spreadsheets in circulation that are being worked on!

**Comment by hrshdhgd** [comment]
I agree, hence waiting on directions and taking no actions.

**Comment by nicolevasilevsky** [comment]
discussed on tech call - Harshad will upload this code 

example: MONDO:0033853 congenital cataract-severe neonatal hepatopathy-global developmental delay syndrome (in [endocrine spreadsheet](https://docs.google.com/spreadsheets/d/17m7z02utbMDhGzazrJJJFL98pzZfbXg_kPxi6RYLezE/edit#gid=289446069))

**Comment by hrshdhgd** [comment]
[New results in a separate directory in gdrive.](https://drive.google.com/drive/folders/1Y53Tb9k6K0KVGikbdRd079FyPw2f56Jc)

**Comment by twhetzel** [comment]
Closing this ticket since the files are created.
