### ISSUE TITLE
check children with multiple same parents

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6763]
So children of obsoletion candidates are in different branches and reported in different spreadsheets. 
Several curators may review the same child separately and give it the same parent. Therefore, after we merge all PRs, we might have children with several identical parents, with different sources (which should be orcid or PMID)

To do: after all obsoletions are done and PRs are merged, check for children with the multiple same parent, and consolidate these parents (ie keep only one parent with all the sources)

**Comment by nicolevasilevsky** [comment]
We discussed this on the curation call today and I am unsure if ROBOT will add an additional parent if one already exists or will it throw an error?

Also, I wonder if there is a QC check for this?

Lastly, would `sh run.sh make NORM` fix this?

**Comment by nicolevasilevsky** [comment]
I tested this - if two curators review the same child separately and give it the same parent, then ROBOT will not add the same parent twice (and it won't throw an error).

**Comment by nicolevasilevsky** [comment]
we should try to add the same parent twice with two different ORCID IDs

**Comment by nicolevasilevsky** [comment]
confirmng - if we add two parents with different ORCIDs, we just need to run

```
sh run.sh make NORM
mv NORM mondo-edit.obo
```

and this will merge the two superclasses into one

**Comment by twhetzel** [comment]
My believe the above commands are executed as the last steps within the `mass_obsolete2` pipeline: 
```
$(MAKE) NORM
mv NORM $(SRC)
```

If yes, can we close this ticket?

**Comment by nicolevasilevsky** [comment]
yes, this can be closed
