### ISSUE TITLE
[Obsolete] MONDO:0010123	absent thumb-short stature-immunodeficiency syndrome

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/mondo#6770]
**Mondo term (ID and Label)**

MONDO:0010123 | absent thumb-short stature-immunodeficiency syndrome

**Reason for deprecation**
"An exceedingly rare, autosomal recessive immune disease characterized by thumb aplasia, short stature with skeletal abnormalities, and combined immunodeficiency described in three sibships from two possibly related families. The skeletal abnormalities included unfused olecranon and the immunodeficiency manifested with severe chickenpox and chronic candidiasis. **No new cases have been reported since 1978.**"

This is the definition--which appears accurate. I do not see another paper beyond the 1978 paper.

**Suggested term to consider**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

https://orcid.org/0000-0001-7941-2961

**Comment by twhetzel** [comment]
I'm not clear on why this is being obsoleted, because it is too rare? It is still documented in many other resources.

**Comment by LCCarmody** [comment]
Issue being that it comes from a single old source. It just happens that one source has been propagated. Given the age of it and the lack of additional evidence, it is likely this is actually another disease. If there is still a need in the community, then by all means, keep it.
