### ISSUE TITLE
updates to mass obsoletion pipeline (new feature request)

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6771]
@twhetzel can you add the functionality:

replace 
MONDO:equivalentObsolete 

with
MONDO:obsoleteEquivalentObsolete

thank you! 🌷

**Comment by nicolevasilevsky** [comment]
maybe the fix is to add 
`BIND(REPLACE(str(?source), "MONDO:equivalentObsolete", "MONDO:obsoleteEquivalentObsolete") as ?new_source)`
to line 90

?

**Comment by nicolevasilevsky** [comment]
you could practice obsoleting this term

[Term]
id: MONDO:0000224
name: acquired carbohydrate metabolism disease
def: "An acquired metabolic disease that is has its basis in the disruption of carbohydrate metabolism." [https://orcid.org/0000-0002-6601-2165]
synonym: "carbohydrate metabolism disease" RELATED [DOID:0050013]
xref: DOID:0050013 {source="MONDO:equivalentObsolete"}
intersection_of: MONDO:0006504 ! acquired metabolic disease
intersection_of: disease_has_basis_in_disruption_of GO:0005975 ! carbohydrate metabolic process

**Comment by twhetzel** [comment]
The fix was a little different than in the comment above. I tested with:
```
MONDO:0008406
MONDO:0013742
```
