### ISSUE TITLE
review mass obsoletion pipeline - can it ignore terms that have already been obsoleted?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6772]
the [mass obsoletion pipeline](https://mondo.readthedocs.io/en/latest/editors-guide/mass-obsoletion/#2-mass-obsolete-terms) will throw an error if terms in the list have already been obsoleted.

Submitting a new feature request to see if we can get the pipeline to ignore these so we don't have to go back and manually remove these from the list

cc @matentzn

**Comment by matentzn** [comment]
@twhetzel let me know if you have questions about this issue!

**Comment by nicolevasilevsky** [comment]
this is a blocker for the mass obsoletion workflow. We'll wait for this to be addressed before we proceed with the mass obsoletion process.
