### ISSUE TITLE
myelofibrosis [Revise subclass]

### ISSUE THREAD

**Issue by DnlRKorn** [monarch-initiative/mondo#6776]
**Mondo term (ID and Label)**
myelofibrosis - MONDO:0044903

**Suggested revision and reasons**

**Revision:** Make myelofibrosis a subclass of myeloproliferative neoplasm/MONDO:0020076 

**Reason:** List of and descriptions of myelofibrosis as a myeloproliferative neoplasm

-https://www.lls.org/myeloproliferative-neoplasms/myelofibrosis
-https://www.mayoclinic.org/diseases-conditions/myelofibrosis/symptoms-causes/syc-20355057
-https://rarediseases.org/videos/myelofibrosis/

We may want to reach out to this professor who's doing research into myelofibrosis 
https://science.byu.edu/directory/richard-watt

**Your nano-attribution (ORCID)**:
0000-0002-1780-9872 and
0000-0002-2957-8792

**Comment by nicolevasilevsky** [comment]
Thanks @DnlRKorn, I added the superclass.
