### ISSUE TITLE
Malignant glioma

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6780]
MONDO:0100342 Malignant glioma

Gliomas are cancerous tumors, therefore malignant glioma should not be a separate entity (or benign glioma)
https://www.nccn.org/patients/guidelines/content/PDF/brain-gliomas-patient.pdf
Note that I called the NCI as well and they are working on this but they confirmed the above statements.

Glioma

ORCID
0000-0001-9310-0163

**Comment by nicolevasilevsky** [comment]
Thanks @galyea123, we will address this. It may not be until the January release.

**Comment by galyea123** [comment]
After additional communication with the NCI they are now clarifying that low grade gliomas are in fact considered benign tumors, but there is still much confusion as they have some contradictory information (see also: https://www.nccn.org/patients/guidelines/content/PDF/brain-gliomas-patient.pdf).  I believe that we should way until this issue is clarified and should still keep "malignant glioma" as well for now. Thank you!

**Comment by nicolevasilevsky** [comment]
sounds good, @galyea123! I will close this but we can revisit it later if needed. 
Best,
Nicole
