### ISSUE TITLE
Relabel: OPTN-related open angle glaucoma 

### ISSUE THREAD

**Issue by Mohan-Shruthi** [monarch-initiative/mondo#6781]
**Mondo term (ID and Label):** MONDO:0007665; glaucoma 1, open angle, E

**Suggested new label:** OPTN-related open angle glaucoma 

**Your nano-attribution (ORCID)** https://clinicalgenome.org/affiliation/40077/
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**  Individuals with a specific heterozygous pathogenic variant are reported with normal tension glaucoma, a subtype of open-angle glaucoma. The mode of inheritance and molecular mechanism are distinct from another disorder related to this gene, amyotrophic lateral sclerosis (ALS).

**Comment by Mohan-Shruthi** [comment]
Thanks, Nicole. I'll get the GCEP's input and get back to you.

**Comment by nicolevasilevsky** [comment]
Hi @Mohan-Shruthi have you had a chance to follow up with the GCEP about this open question? Thank you! :)

**Comment by Mohan-Shruthi** [comment]
Hi Nicole. Thank you for your patience. I have updates from the group on this request. We can go ahead and introduce this as a new class. The definition is "Any open angle glaucoma in which the cause of the disease is a mutation in the OPTN gene." We could include the OMIM term as a synonym: "glaucoma 1, open angle, E."

**Comment by nicolevasilevsky** [comment]
Hi @Mohan-Shruthi - thank you! I'll work on this and it should be available in the next release (early April)

**Comment by Mohan-Shruthi** [comment]
Thank you very much!

Best,
Shruthi
-----------------------------
Shruthi Mohan, Ph.D.
ClinGen Senior Biocurator
Berg Lab | Department of Genetics | UNC - Chapel Hill
919-843-3549 | ***@***.***
