### ISSUE TITLE
Relabel: PXDN-related ocular dysgenesis

### ISSUE THREAD

**Issue by Mohan-Shruthi** [monarch-initiative/mondo#6782]
**Mondo term (ID and Label):** MONDO:0010015; [anterior segment dysgenesis 7]

**Suggested new label:** PXDN-related ocular dysgenesis

**Your nano-attribution (ORCID)** https://clinicalgenome.org/affiliation/40077/
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)** PXDN is also related to microphthalmia that forms a spectrum of disease along with anterior segment dysgenesis.

**Comment by nicolevasilevsky** [comment]
Thanks @Mohan-Shruthi, we'll work on this in November (or later). Thanks for your patience!

**Comment by nicolevasilevsky** [comment]
@Mohan-Shruthi we prefer to use the OMIM labels but we can add this as a synonym with a ClinGen preferred subset tag.
