### ISSUE TITLE
[NTR/gene] CYP1B1-related glaucoma with or without anterior segment dysgenesis

### ISSUE THREAD

**Issue by Mohan-Shruthi** [monarch-initiative/mondo#6783]
**Preferred gene-related syndrome label** CYP1B1- related glaucoma with or without anterior segment dysgenesis

**Synonyms**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)** MONDO:0000365; primary congenital glaucoma

**Definition** Any primary congenital glaucoma in which the cause of the disease is a mutation in the CYP1B1 gene. 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######) PMID:23767995, PMID: 24099281, PMID: 9097971

**Children terms (if applicable)** MONDO:0009277; Glaucoma 3A, MONDO:0020367; juvenile open angle glaucoma, MONDO:0015016; anterior segment dysgenesis 6

**Your nano-attribution (ORCID) or URL for a working group** https://clinicalgenome.org/affiliation/40077/

**Comment by nicolevasilevsky** [comment]
Thanks @Mohan-Shruthi, we'll work on this in November (or later). Thanks for your patience!
