### ISSUE TITLE
Vitiligo

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6788]
MONDO:0008661

The links to Orphanet an OMIM are not correct Orphanet:247871 (OMIM:193200)
Also, vitiligo (per se)  is not a rare condition.

**Comment by nicolevasilevsky** [comment]
Thanks @galyea123!

**Comment by nicolevasilevsky** [comment]
@sabrinatoro the rare annotation is coming from Orphanet.

**Comment by sabrinatoro** [comment]
I think this issue is solved. The x-refs looks ok, and this disease is not in any rare disease subset
.
