### ISSUE TITLE
[Obsolete] MONDO:0957404	pyogenic autoinflammatory syndrome of childhood

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/mondo#6789]
**Mondo term (ID and Label)**

MONDO:0957404 | pyogenic autoinflammatory syndrome of childhood

**Reason for deprecation**

Can't identify papers or sources that use this category
**Suggested term to consider**

Unclear since the grouping term is also being obsoleted.
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0000-0001-7941-2961

**Comment by twhetzel** [comment]
I don't understand the proposed reason for deprecation, however Orphanet mentions this is a grouping term[https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=324942] which there was some strategic refinement work done in Mondo in the Fall 2023 to remove these types of terms so that seems reasonable to remove this one.

[1] https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=324942

**Comment by sabrinatoro** [comment]
I don't know whether it is correct to obsoleted this term. Let's add experts to see whether it is indeed a real disease or not.

**Comment by twhetzel** [comment]
I converted the PR to a Draft following Sabrina's comment to add this the call with the medical experts.

**Comment by sabrinatoro** [comment]
**Issue summary:** 
- MONDO:0957404 - 'pyogenic autoinflammatory syndrome of childhood'
- x-ref: [Orphanet:324942](https://www.orpha.net/consor/www/cgi-bin/OC_Exp.php?Expert=324942), 
         - characterize a disease but a group of diseases 
- No children in Mondo

**Question to Experts:** 
To your knowledge, is there an actual disease called "pyogenic autoinflammatory syndrome of childhood"? 

**Action Item:**
- if yes, keep term
- if no, go ahead with obsoletion with obsoletion reason: Mondo grouping term

**Comment by sabrinatoro** [comment]
Discussed on the Mondo curation call on 25-01-2024.
If we cannot find a paper reporting this disease, and if this term is reported to be a grouping term in Orphanet, it should be obsoleted.
