### ISSUE TITLE
[Obsolete] MONDO:0957405	granulomatous autoinflammatory syndrome of childhood

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/mondo#6790]
**Mondo term (ID and Label)**
MONDO:0957405 | granulomatous autoinflammatory syndrome of childhood

**Reason for deprecation**
Not common use, few references

**Suggested term to consider**
unknown. orphanet says it is a group of disorders. May just separate into the disorders

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0000-0001-7941-2961

**Comment by nicolevasilevsky** [comment]
@sabrinatoro assigning this to you to review and determine if obsoletion is the right approach

**Comment by sabrinatoro** [comment]
We do not obsolete terms based on their common use or number of references (which is typical of a rare disease). This term has cross references to orphanet and a GARD, and was reviewed by a medical expert. Therefore, I don't think this term should be obsoleted.
@LCCarmody and @nicolevasilevsky, if you disagree, please reopen this issue. Thank you.
