### ISSUE TITLE
Request for new term midface hypoplasia

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#6794]
### Label

midface hypoplasia

### Synonyms

midfacial hypoplasia

### Synonym type

exact

### Definition

A condition characterized by decreased growth of the midface, specifically the bones and soft tissues in the central part of the face.

### Parent term

disorder of facial skeleton, MONDO:0023369

### ORCID Identifier

https://orcid.org/0000-0002-3458-4839

### Additional comments

References:
- https://www.stlouischildrens.org/conditions-treatments/midfacial-hypoplasia
- https://www.sciencedirect.com/topics/medicine-and-dentistry/midface-hypoplasia

**Comment by twhetzel** [comment]
@nicolevasilevsky is this added to the ROBOT template for new terms to be added into the upcoming Dec release?

**Comment by sabrinatoro** [comment]
@twhetzel and @nicolevasilevsky 
I think this is a phenotype and not a disease, and therefore it shouldn't be added in Mondo. 
Is there an argument to consider this as disease?

**Comment by nicolevasilevsky** [comment]
I suspect Trish needs this for INCLUDE

**Comment by twhetzel** [comment]
It can be closed for Mondo.
