### ISSUE TITLE
Request for new term bilateral coxa valga

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#6795]
### Label

bilateral coxa valga

### Synonym type

None

### Definition

A condition where both hip joints have an increased angle between the neck of the femur and the shaft of the femur. 

### Parent term

hereditary disease, MONDO:0003847 

### ORCID Identifier

https://orcid.org/0000-0002-3458-4839

### Additional comments

reference: https://www.physio-pedia.com/Coxa_Vara_/_Coxa_Valga

needed for Kids First

**Comment by twhetzel** [comment]
@nicolevasilevsky is this added to the ROBOT template for new terms to be added into the upcoming Dec release?

**Comment by nicolevasilevsky** [comment]
Yep! My template is here:
https://docs.google.com/spreadsheets/d/1sLt1sFvfomRWclyESg-1tq9nWInf3msb7pQGyYxA7lo/edit#gid=2063035843

But I won't be able to get these new terms added before the December release, I am aiming for the Jan release.

Do you want this new term added today (before the Dec release)? I can add it for you, if needed (or feel free to add it yourself, if you like. I can review your PR)

**Comment by nicolevasilevsky** [comment]
@twhetzel 
What do you think about the parent:
MONDO:0018230 'skeletal dysplasia' 
Definition: Any Mendelian diseases that affects growth and development of the skeleton.

**Comment by twhetzel** [comment]
I am still looking at this, but one thing I have realized is that it is not always a hereditary disease and can occur to people later in life (e.g. an injury to the hip, cerebral palsy, knock-knees, rickets, or a number of other medical conditions).

**Comment by sabrinatoro** [comment]
@twhetzel and @nicolevasilevsky 
This term seems to refer to a phenotype and not a disease. I don't think it should be added into Mondo as is.

**Comment by twhetzel** [comment]
@sabrinatoro since you mentioned this seems to refer to a phenotype and not a disease, do you prefer this be closed?

**Comment by sabrinatoro** [comment]
@twhetzel This issue can be closed unless you (the requester) and/or the Mondo team want to have additional discussions and argue that this term should be added to Mondo.

**Comment by twhetzel** [comment]
That's fine, I'll close and submit to HPO.
