### ISSUE TITLE
Request for new term stenosis of the external auditory canal

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#6797]
### Label

stenosis of the external auditory canal

### Synonyms

ear canal stenosis, stenosis of the auditory canal

### Synonym type

exact

### Definition

A narrow ear canal, where the eardrum can still be viewed but the canal is narrower than normal.

### Parent term

MONDO:0019755 developmental defect during embryogenesis

### ORCID Identifier

https://orcid.org/0000-0002-3458-4839

### Additional comments

Reference: https://coastalearnoseandthroat.com/services/ear-surgery/ear-canal-stenosis-and-atresia/

**Comment by twhetzel** [comment]
@nicolevasilevsky are these added to the ROBOT template for new terms to be added into the upcoming Dec release?

**Comment by nicolevasilevsky** [comment]
I added it to the [spreadsheet](https://docs.google.com/spreadsheets/d/1sLt1sFvfomRWclyESg-1tq9nWInf3msb7pQGyYxA7lo/edit#gid=2063035843) but it will be in the Jan release, not December. Do you need this sooner?

**Comment by sabrinatoro** [comment]
@twhetzel and @nicolevasilevsky 
This sounds like a phenotype more than a disease. I question whether this term should be added in Mondo.

**Comment by twhetzel** [comment]
There are a number of "stenosis" of some anatomical location terms in MONDO currently. Are there plans to remove these other terms at some point?

**Comment by twhetzel** [comment]
During the [Curation call](https://docs.google.com/document/d/1wXBv1Bh4JmdqPCbQyu78ZyrITpxQTAQi1odNO-0aPcw/edit) on Jan 4, 2024 it was decided this term should not be added to Mondo.
