### ISSUE TITLE
mondo.json 'meta' field missing on September release for about 5000 nodes?

### ISSUE THREAD

**Issue by RichJackson** [monarch-initiative/mondo#6799]
Hi there

The September release seems to be substantially different from the August one. For instance: 

August:

```
{
      "id" : "http://purl.obolibrary.org/obo/HP_0000518",
      "lbl" : "Cataract",
      "type" : "CLASS",
      "meta" : {
        "definition" : {
          "val" : "A cataract is an opacity or clouding that develops in the crystalline lens of the eye or in its capsule.",
          "xrefs" : [ "HPO:probinson" ]
        },
        "comments" : [ "Note that some ophthalmologists call any opacity in the lens a cataract, while others restrict the term to lens opacities that impair vision. We use the term to refer to the first meaning (any lens opacity)." ],
        "subsets" : [ "http://purl.obolibrary.org/obo/hp.obo#hposlim_core" ],
        "synonyms" : [ {
          "pred" : "hasExactSynonym",
          "val" : "Cataracts"
        }, {
          "synonymType" : "http://purl.obolibrary.org/obo/hp.obo#layperson",
          "pred" : "hasExactSynonym",
          "val" : "Clouding of the lens of the eye",
          "xrefs" : [ "orcid.org/0000-0002-6548-5200" ]
        }, {
          "synonymType" : "http://purl.obolibrary.org/obo/hp.obo#layperson",
          "pred" : "hasExactSynonym",
          "val" : "Cloudy lens",
          "xrefs" : [ "ORCID:0000-0001-6908-9849" ]
        }, {
          "pred" : "hasExactSynonym",
          "val" : "Lens opacities"
        }, {
          "pred" : "hasExactSynonym",
          "val" : "Lens opacity"
        } ],
        "xrefs" : [ {
          "val" : "Fyler:4865"
        }, {
          "val" : "MSH:D002386"
        }, {
          "val" : "SNOMEDCT_US:128306009"
        }, {
          "val" : "SNOMEDCT_US:193570009"
        }, {
          "val" : "SNOMEDCT_US:247053007"
        }, {
          "val" : "UMLS:C0086543"
        }, {
          "val" : "UMLS:C1510497"
        } ],
        "basicPropertyValues" : [ {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#hasAlternativeId",
          "val" : "HP:0001113"
        }, {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#hasAlternativeId",
          "val" : "HP:0007825"
        }, {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#hasAlternativeId",
          "val" : "HP:0010700"
        }, {
          "pred" : "http://www.geneontology.org/formats/oboInOwl#hasOBONamespace",
          "val" : "human_phenotype"
        } ]
      }
```

September:

```
{
      "id" : "http://purl.obolibrary.org/obo/HP_0000518",
      "lbl" : "Cataract",
      "type" : "CLASS"
    }
```

The meta field on HP nodes is no longer present? Is this intentional?

**Comment by RichJackson** [comment]
Thanks for getting back to me. We use Mondo in a bioNLP application https://github.com/AstraZeneca/KAZU, and make extensive use of the synonym data mondo contains for NER/Entity linking. Is there a simple way to backfill this feature?

**Comment by matentzn** [comment]
Cool! And your pipeline requires synonym data on terms that are not diseases? The synonym data on the Mondo Disease IDs should be entirely unaffected.

**Comment by RichJackson** [comment]
Actually, we were using synonym data from non-mondo disease IDs too - for instance, in the above described case, we were able to use synonyms from HP_0000518 such as "Cloudy lens". Presumably there's no way to get these back, without querying the HPO source separately?

**Comment by nicolevasilevsky** [comment]
> Thanks for getting back to me. We use Mondo in a bioNLP application https://github.com/AstraZeneca/KAZU, and make extensive use of the synonym data mondo contains for NER/Entity linking. Is there a simple way to backfill this feature?

@RichJackson could we add you to our list of Mondo users on our website?:
https://mondo.monarchinitiative.org/pages/users/

**Comment by matentzn** [comment]
@RichJackson 

I think it is cleaner if you use the HPO source directly for HPO information. It is probably also more up-to-date, and gives you richer context for the terms (more children etc). I would also suggest that you make HP is absolutely critical for biomedical text mining.

We have build an integrated Phenomics ontology which contain both, and more: https://github.com/monarch-initiative/phenio

This could also be an option for you to try!

**Comment by RichJackson** [comment]
Thanks for the info! Closing this now.
