### ISSUE TITLE
Create a jupyter notebook for Mondo processing with OAK

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#6805]
Create a jupyter notebook (src/scripts/notebooks/mondo.ipynb with the following features:

- [x] A nice header (first cell) saying something like "code examples interacting with Mondo"
- [x] An explanation on how to install OAK (links to docs)
- [x] Code cell 1: An example of loading mondo (`:obo` selector) in python, not CLI (!)
- [x] Code cell 2: Traversing through all children of "tuberculosis" (look up ID on OLS) and extract the following features from each term:
    - [x] Cross-species analog relation (its an annotation property, not sure how it looks in OAK)
    - [x] conformsTo relation to pattern (blocked by #6806)
    - [x] A list of all children
    - [x] A list of all parents
    - [x] The label
    - [x] A list of all disease mappings
- [x] Code cell 3: print the results for a single term that exhibits all of the above (will need to search for one).

For all cells, add a few words explanatory text what we do here. Format nicely. This is for our Data Science users.

When done, assign to Sabrina to link from user docs (make a more comprehensive user doc for how users can use OAK with Mondo).

**Comment by matentzn** [comment]
@hrshdhgd this is needed for a user ideally before the end of the coming week. Let me know if you have difficulties prioritising this, we can allocate it to someone else.

**Comment by hrshdhgd** [comment]
What do you want the source file to be?
1. released MONDO
2. `src/ontology/tmp/mondo-ingest.db` in the project.

**Comment by hrshdhgd** [comment]
Also the current annotation properties that exist are:
```owl
<http://purl.org/spar/cito/citesAsAuthority>
<http://swrl.stanford.edu/ontologies/3.3/swrla.owl#isRuleEnabled>
<https://w3id.org/biolink/vocab/category>
<https://w3id.org/biolink/vocab/has_evidence>
IAO:0000111
IAO:0000112
IAO:0000113
IAO:0000114
IAO:0000115
IAO:0000116
IAO:0000117
IAO:0000118
IAO:0000119
IAO:0000142
IAO:0000231
IAO:0000232
IAO:0000233
IAO:0000234
IAO:0000411
IAO:0000412
IAO:0000424
IAO:0000425
IAO:0000426
IAO:0000427
IAO:0000589
IAO:0000596
IAO:0000597
IAO:0000598
IAO:0000599
IAO:0000600
IAO:0000601
IAO:0000602
IAO:0000603
IAO:0000700
IAO:0006011
IAO:0006012
IAO:0010000
IAO:0100001
MONDO:exclusionReason
OMO:0001001
OMO:0002000
RO:0001900
RO:0002175
RO:0002259
RO:0002575
RO:0002579
RO:0002581
RO:0002582
RO:0004049
RO:0004050
RO:0040042
dce:contributor
dce:coverage
dce:creator
dce:date
dce:description
dce:format
dce:identifier
dce:language
dce:publisher
dce:relation
dce:rights
dce:source
dce:subject
dce:title
dce:type
dct:contributor
dct:creator
dct:description
dct:isVersionOf
dct:license
dct:source
dct:title
foaf:homepage
obo:ro/subsets#ro-eco
obo:valid_for_go_annotation_extension
obo:valid_for_go_gp2term
obo:valid_for_go_ontology
obo:valid_for_gocam
oio:SubsetProperty
oio:consider
oio:created_by
oio:creation_date
oio:date
oio:default-namespace
oio:hasBroadSynonym
oio:hasDbXref
oio:hasExactSynonym
oio:hasNarrowSynonym
oio:hasOBOFormatVersion
oio:hasRelatedSynonym
oio:hasSynonymType
oio:id
oio:inSubset
oio:saved-by
oio:source
owl:deprecated
protege:defaultLanguage
rdfs:comment
rdfs:label
rdfs:seeAlso
skos:broadMatch
skos:closeMatch
skos:exactMatch
skos:narrowMatch
skos:relatedMatch
```

**Comment by nicolevasilevsky** [comment]
oops! didn't mean to close this :)

**Comment by matentzn** [comment]
@twhetzel given the time-sensitive nature of this, I am reassigning this to you now; @hrshdhgd has made a start in the linked PR. This is regarding the meeting you and me were in earlier this week!

**Comment by cmungall** [comment]
https://incatools.github.io/ontology-access-kit/packages/interfaces/basic.html#oaklib.interfaces.basic_ontology_interface.BasicOntologyInterface.ontology_metadata_map

**Comment by hrshdhgd** [comment]
oaklib command: `term-metadata`

**Comment by twhetzel** [comment]
@matentzn For "An example of loading mondo (:obo selector) in python, not CLI (!)" - do you mean load Mondo as: `!runoak --input sqlite:obo:mondo`?

**Comment by matentzn** [comment]
I meant proper python, like "from oaklib import get_descendants" (this is just a guess". Runoak is what I mean by "CLI".

**Comment by twhetzel** [comment]
What are the expectations on how a user will get and create a ".db" version of mondo? Will they need to clone the mondo repo and run `make` commands? And do these commands need to be in the notebook?

Also, should the last released version of mondo be the source file?

**Comment by twhetzel** [comment]
@matentzn I pushed an update for WIP.

Questions for the requirements for this demo notebook:
- For ancestors and descendants, is the intent this is simply the call of ancestors and descendants for a curie of interest, e.g. `adapter.descendants([curie], predicates=[IS_A])`?
  - Can this call be limited to `IS_A` for now with a note the user can add in additional predicates if interested?
- Are the only annotations and relations on each curie to include:
  - curie
  - label  
  - cross-species analog relation
  - conformsTo relation
  - dbxrefs (disease mappings)

**Comment by matentzn** [comment]
> For ancestors and descendants, is the intent this is simply the call of ancestors and descendants for a curie of interest, e.g. adapter.descendants([curie], predicates=[IS_A])?

Yes, good enough! Thank you!

> Are the only annotations and relations on each curie to include:

Sounds good for a first draft! Thank you!
