### ISSUE TITLE
Neurodevelopmental disorder with hearing loss and spasticity

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6817]
### Label

Neurodevelopmental disorder with hearing loss and spasticity

### Synonyms

AFG2B-related disorder

### Synonym type

exact

### Definition

Neurodevelopmental disorder with hearing loss and spasticity (NEDHLS) is characterized by hearing loss, global developmental delay/impaired intellectual development, spastic-dystonic cerebral palsy, focal or generalized epilepsy, and microcephaly. Some children present with hypotonia ([Richard et al., 2021](https://www.omim.org/entry/619616#1))

### Parent term

Neurodevelopmental disorder and also syndromic hearing loss

### ORCID Identifier

0000-001-9310-0163

### Website URL

https://www.omim.org/entry/619616https://www.spatafoundation.org/the-genes

**Comment by nicolevasilevsky** [comment]
@galyea123 

This has been added (likely after you created this ticket):
MONDO:0859206 'neurodevelopmental disorder with hearing loss and spasticity'

Please reopen if anything else is needed

**Comment by galyea123** [comment]
Thank you Nicole!
