### ISSUE TITLE
CHD8 overgrowth syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6823]
### Label

CHD8 overgrowth syndrome

### Synonyms

CHD8-related neurodevelopmental disorder with overgrowth, CHD8-related intellectual disability-autism-macrocephaly-tall stature syndrome, Intellectual developmental disorder with autism and macrocephaly

### Synonym type

exact

### Definition

CHD8-related neurodevelopmental disorder with overgrowth (CHD8-NDD) is characterized by generalized overgrowth, developmental delay / intellectual disability (DD/ID), autism spectrum disorder (ASD), neuropsychiatric issues, neurologic problems, sleep disturbance, and gastrointestinal issues The most common findings are the development of macrocephaly (most often during infancy) and tall stature (most typically during puberty), which is often accompanied by ASD and/or DD/ID. Most, if not all, affected individuals have some degree of DD, most commonly speech and motor delays. When present, ID is most often in the mild-to-moderate range. Sleep disturbance is characterized by difficulty with both initiation (delayed sleep onset) and maintenance (frequent night awakenings) of sleep. The most common gastrointestinal issue is constipation with or without periods of diarrhea. Less common features are hypotonia (about 30% of affected individuals), seizures (10%-15%), dystonia (rare), and Chiari I malformation (rare). https://www.ncbi.nlm.nih.gov/books/NBK585456/   https://pubmed.ncbi.nlm.nih.gov/31980904/

### Parent term

Multiple congenital anomalies/dysmorphic syndrome-intellectual disability 

### ORCID Identifier

0000-001-9310-0163

### Website URL

https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=31733

**Comment by galyea123** [comment]
Related to ticket 6823 I forgot to mention that a former name autism, susceptibility to, 18 was listed in MONDO.  MONDO:0014017  See also OMIM: https://omim.org/entry/615032

**Comment by nicolevasilevsky** [comment]
@galyea123 

CHD8 overgrowth syndrome is a synonym of MONDO:0014017 'intellectual developmental disorder with autism and macrocephaly' currently.

I will update the synonym 'autism, susceptibility to, 18' to note that it is historic and no longer should be used.

I don't believe a new term is needed, do you agree?

**Comment by galyea123** [comment]
Agree.  I will consider adding all the synonyms as per Orphanet and OMIM. Thank you Nicole.
