### ISSUE TITLE
Create updated spreadsheet for mass obsoletion review (4 branches)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6830]
This issue is for the technical team, and should be done **AFTER ALL THE MASS OBSOLETION FOR BRANCHES WERE DONE AND MERGED.** (Sabrina or Trish or Nicole will let you know when it is ready)

### Context: 
We have been reviewing the effects of term obsoletion on their children. We are using the spreadsheet created by Harshad (issue number something), choosing parents for children to become orphan/leaves the branch after the obsoletion. 
After reviewing the spreadsheet, we added these new parents and obsoleted terms going ontology branch by branch. 

There are 4 ontology branches for which we could get this review "for free" because most (or all?) of the terms to be obsoleted in these branches have already been obsoleted in other branches (the obsoleted terms were in multiple branches of the ontology).

### To do: 
For the following 4 ontology branches, recreate the spreadsheets by using an updated list of "terms to be obsoleted" that includes only terms that have not been obsoleted yet. (note: please create NEW spreadsheet, and do not remove the previous/existing spreadsheets)

**Ontology branches:** 
branch ID | branch name
-- | --
MONDO:0021147 | disorder of development or morphogenesis
MONDO:0003847 | hereditary disease
MONDO:0002254 | syndromic disease
MONDO:0024458 | disorder of visual system

**Terms to be obsoleted:** 
Please use the original term to be obsoleted list (list can also be found [here](https://docs.google.com/spreadsheets/d/1xTfYCOCGKx_svNT8PirgGDiCINV7IDqzhBk76DNe150/edit#gid=1075815818), in the tab called "terms to obsolete (230913)), and filter out all the terms that are currently obsoleted in the ontology, and keep the one with the "obsoletion candidate" tag (some terms have been removed from the original obsoletion list). 
Note: there is a possibility that this list of terms left to be obsoleted might be very small. 

**Spreadsheets:** 
run the same code as previously (Harshad's code) for the 4 branches above, using the list of terms to be obsoleted above. 
The spreadsheet includes: all children of terms to be obsoleted + their parents in and outside the branch + their ancestors in and outside the branch.

**Comment by hrshdhgd** [comment]
The results can be found [here](https://drive.google.com/drive/folders/1Wsx8rwOjWgHjsSDKmW4U0QcfYJIwWR5C)

**Comment by sabrinatoro** [comment]
Thank you @hrshdhgd 
Could you please re-run them again, but remove the following from the list of terms to be obsoleted (they have been removed from the obsoletion candidate list):
MONDO:0019054
MONDO:0015338
MONDO:0019713
MONDO:0015337

THANK YOU!

**Comment by twhetzel** [comment]
@sabrinatoro can this be closed?

**Comment by sabrinatoro** [comment]
Yes, this has been done. Closing.
