### ISSUE TITLE
[Merge] MONDO:0000075 'neuronopathy, distal hereditary motor'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6845]
**Mondo term (ID and Label)**
MONDO:0000075 'neuronopathy, distal hereditary motor'

**Reason for deprecation**
I think these are the same, just Orphanet spells the term as neuropathy and OMIM spells it as neur**on**opathy (neuro vs neuron -opathy)

**Term to be merged with**
MONDO:0018894 'distal hereditary motor neuropathy'

**Comment by nicolevasilevsky** [comment]
@sabrinatoro @twhetzel can you review and see if you agree?

**Comment by twhetzel** [comment]
Based on some general searching and the [OMIM page](https://www.omim.org/entry/600794) and [this article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5373778/) (`Inclusion of patients was based on the presence of a motor neuropathy/neuronopathy...`), it looks like these two terms are the same. 

However, for the more general terms [this article](https://www.news-medical.net/health/Neuronopathy-and-neuropathy-Whats-the-difference.aspx) does mention a difference between neur**on**opathy and neuropathy.

**Comment by nicolevasilevsky** [comment]
@twhetzel if you feel comfortable, you can go ahead and merge these two terms.

**Comment by twhetzel** [comment]
This was already added into the ROBOT_AddObsTagForMerge template. @nicolevasilevsky do you want to be Assignee then since I gather you added this?

**Comment by nicolevasilevsky** [comment]
you are right! Sabrina will add the obsoletion tag befoe the release, then we can merge this on or after Feb 01. I'm happy to have you be the assignee and work on this in/after Feb if that works for you.

**Comment by twhetzel** [comment]
Sure, I can stay as the Assignee and do the next step in/after Feb.

**Comment by twhetzel** [comment]
@nicolevasilevsky should this be in a March 2024 Milestone? I thought this change would be done _after_ the Feb release?

**Comment by nicolevasilevsky** [comment]
the obsoletion tag:
<img width="260" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/a3556aeb-3890-4b0c-9a41-683da71884b5">

so you can work on it this month if you like (or later)

**Comment by twhetzel** [comment]
As noted on Slack, I need help to get `owltools` installed to run the merge command from 

I followed the owltools install instructions [here](https://github.com/owlcollab/owltools/wiki/Install-OWLTools#downloading-the-jar-and-script) but the owltools command is not found when I run `owltools -h`

**Comment by twhetzel** [comment]
After watching the videos I see the correct command and have a ticket to update the docs and have submitted a PR for this ticket.
