### ISSUE TITLE
Request for new synonym [Huppke-Brendel syndrome]

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6849]
### Mondo term

MONDO:0013772

### Synonyms

Huppke-Brendel syndrome

### Synonym type

exact

### Additional comments

related to https://github.com/monarch-initiative/mondo/issues/6765

**Comment by twhetzel** [comment]
@nicolevasilevsky there is an updated [comment](https://github.com/monarch-initiative/mondo/issues/6765#issuecomment-1798556243) to pause on this change until expert panel review.
