### ISSUE TITLE
revise children of 'myopathy caused by variation in FKRP'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6851]
there are children that are incorrectly classified under this term, as pointed out by Shruthi at ClinGen.

cc @twhetzel

**Comment by nicolevasilevsky** [comment]
this is the current hierarchy:
<img width="437" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/57eee25e-3755-4aad-9b13-ebec16555f05">

**Comment by Mohan-Shruthi** [comment]
Thanks for sharing, Nicole. I can't see it in the screenshot, so apologies if it's already there. There would be three children terms for FKRP. According to OMIM (https://www.omim.org/entry/606596?search=FKRP&highlight=fkrp), the 'muscular dystrophy-dystroglycanopathy type A5' would also be one of the children terms.

**Comment by nicolevasilevsky** [comment]
@Mohan-Shruthi I updated the screenshot above. I'll send it to you by email too.

**Comment by Mohan-Shruthi** [comment]
Hi Nicole. Thanks for the updated screenshot. Yes, these are the three phenotypes. The limb-girdle phenotype (type C5) was designated as "autosomal recessive limb-girdle muscular dystrophy type 2I" in your previous screenshot. I think we can keep it that way to be consistent with the other dystroglycanopathy genes in Mondo, such as FKTN, POMT1, etc. So, it would be great if you could please change "muscular dystrophy-dystroglycanopathy (limb-girdle), type C5" back to "autosomal recessive limb-girdle muscular dystrophy type 2I".
