### ISSUE TITLE
[NTR/gene] SPEN

### ISSUE THREAD

**Issue by elliebroeren** [monarch-initiative/mondo#6860]
**Preferred gene-related syndrome label**
SPEN-related neurodevelopmental disorder

**Synonyms**
Radio-Tartaglia syndrome

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
[Mendelian neurodevelopmental disorder](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100500) 

**Definition**
Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene. For example: Any congenital myopathy in which the cause of the disease is a mutation in the TPM3 gene.
The clinical profile of this disease includes developmental delay/intellectual disability, autism spectrum disorder, anxiety, aggressive behavior, attention deficit disorder, hypotonia, brain and spine anomalies, congenital heart defects, high/narrow palate, facial dysmorphisms, and obesity/increased BMI, especially in females (PMID: 33596411). 

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
N/A

**Attribution**
This is a request from the ClinGen Syndromic Disorders GCEP.

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
thanks @elliebroeren!
We'll work on this as soon as we can, likely we'll get it in for the January release.

**Comment by nicolevasilevsky** [comment]
@elliebroeren we have this disease entity in Mondo:
MONDO:0859143 'Radio-Tartaglia syndrome'

we can add this as a synonym and add your definition. Thank you!

**Comment by elliebroeren** [comment]
Hi Nicole, if you could add this as a synonym that would be great, thank you!
