### ISSUE TITLE
Request for new term [Pallister-Hall-like syndrome]

### ISSUE THREAD

**Issue by elliebroeren** [monarch-initiative/mondo#6861]
### Label

Pallister-Hall-like syndrome

### Synonym type

None

### Definition

Pallister-Hall-like syndrome (PHLS) is a pleiotropic autosomal recessive disorder characterized by phenotypic variability. Patients exhibit postaxial polydactyly as well as hypothalamic hamartoma, cardiac and skeletal anomalies, and craniofacial dysmorphisms. Hirschsprung disease has also been observed (PMIDs: 30497210, 32413283).  

OMIM notes that Pallister-Hall syndrome is an autosomal dominant disorder with features overlapping those of PHLS, caused by mutation in the GLI3 gene.

### Parent term

MONDO:080006

### Website URL

https://clinicalgenome.org/affiliation/40060/

**Comment by nicolevasilevsky** [comment]
Hi @elliebroeren - this term already exists in Mondo: MONDO:0009436 'congenital hypothalamic hamartoma syndrome', it is an exact synonym.

Would you like revisions to this existing term?

**Comment by nicolevasilevsky** [comment]
No worries! I'll close this ticket. 

Happy holidays!
