### ISSUE TITLE
`mondo-base.obo`: MONDO IDs do not match between `$xref` and `$id`

### ISSUE THREAD

**Issue by bschilder** [monarch-initiative/mondo#6873]
I'm using the "mondo-base.obo" object read into R as an [`ontologyIndex` object](https://cran.r-project.org/package=ontologyIndex).

In working with this object, I've noticed some unexpected features. Namely, the MONDO IDs in the `$xref` slot do not seem to match up with those listed in  the`$id` slot. I'd expect that all MONDO IDS in any of the slots should at least be present in the `$id` slot.

**Mondo term (ID Label)**

[xref_ids.csv](https://github.com/monarch-initiative/mondo/files/13366845/xref_ids.csv)

**Bug/Typo/Error description**

```R
remotes::install_github("neurogenomics/HPOExplorer")
mondo <- HPOExplorer::get_mondo()

# Only 18 MONDO IDs are missing names, which is ok
>     sum(is.na(mondo$name))
[1] 18
# 10273 MONDO IDs are missing definitions; less ok but still manageable
>     sum(is.na(mondo$def))
[1] 10273
> 

# Get MONDO IDs listed in `$xref`
> xref_ids <- unique(names(unlist(mondo$xref)))
# Get total number of xref IDs
> length(xref_ids)
[1] 101231
# Almost all of these xref MONDO IDs (~100k) are missing in the `$id` slot! in theory all IDs should be in the `$id` slot
>     sum(!xref_ids %in% names(mondo$id))
[1] 98468
# Same missing rate in the name slot
>     sum(!xref_ids %in% names(mondo$name))
[1] 98468
# Same missing rate in the def slot
>     sum(!xref_ids %in% names(mondo$def))
[1] 98468
> 
````

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-5949-2191

Thanks in advance for your help.

**Comment by twhetzel** [comment]
Hi Brian - thanks for the ping on this issue. I've been looking into this and have a few questions and comments.

What is the source of the Mondo ontology file used? I've looked at the number of terms without labels or definitions in the latest release of Mondo and do not get the same count as mentioned in the initial post. 

In the "xref_ids.csv" file, the Mondo IDs vary in length from 13, 14, and 15 characters long while they should be 13 characters long (MONDO: and then a 7 digit number). Amongst the IDs that are 13 characters long, there are at least a few obsolete terms in the file, e.g. MONDO:8000034. Deprecated terms in MONDO have the annotation owl:deprecated with value true [1] and of the Mondo terms with xrefs in the latest release, 3,210 of these are obsoleted.

For other valid IDs in the "xref_ids.csv" file, e.g. MONDO:0000005, what are the values you get for $xref and $id? 


[1] https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#obsolete-a-class-manually

**Comment by matentzn** [comment]
I Never saw this, and I didn't realise @bschilder was interested in Mondo at all! Yep I can discuss it with him when I meet him.

**Comment by twhetzel** [comment]
Oh, I thought your ping to him here (https://github.com/neurogenomics/RareDiseasePrioritisation/issues/33#issuecomment-1838608600) was related to Mondo as well

**Comment by matentzn** [comment]
We determined this is not a Mondo related problem, but related to the r toolkit!

**Comment by twhetzel** [comment]
Thanks both for the update. Please see other issues with the IDs as mentioned earlier https://github.com/monarch-initiative/mondo/issues/6873#issuecomment-1840275671

**Comment by matentzn** [comment]
Yeah I confirmed that with Brian in the meeting, many ids don't even exist. He will look into it!

**Comment by bschilder** [comment]
> For other valid IDs in the "xref_ids.csv" file, e.g. MONDO:0000005, what are the values you get for $xref and $id?

@twhetzel here's a reprex you can quickly run in R:
```R
> if(!require("ontologyIndex")) BiocManager::install("ontologyIndex")
> mondo <- ontologyIndex::get_OBO("https://github.com/monarch-initiative/mondo/releases/download/v2023-09-12/mondo-base.obo", extract_tags = "everything")

 > mondo$xref["MONDO:0000005"]
$`MONDO:0000005`
[1] "OMIMPS:203655"

> mondo$id["MONDO:0000005"]
  MONDO:0000005 
"MONDO:0000005" 
```

**Comment by bschilder** [comment]
Tagging who i think may be the author of `ontologyIndex` @daniel-jg
- https://github.com/cran/ontologyIndex/blob/master/DESCRIPTION

**Comment by twhetzel** [comment]
@bschilder that looks correct for `MONDO:0000005`. Since Nico mentioned that it was determined the issue is with the R toolkit, can this ticket remain closed since it is not an issue with Mondo?


![Screenshot 2023-12-10 at 6 26 25 PM](https://github.com/monarch-initiative/mondo/assets/2167174/8a8fb856-8f88-4f66-8951-cc1270e0da53)
