### ISSUE TITLE
Mass Obsoletion: focus on branch 'hereditary disease' (MONDO:0003847)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6877]
branch: hereditary disease' (MONDO:0003847)

Terms to obsolete: 

CURIE | obsoletion candidate label
-- | --
MONDO:0019597 | 46,XY disorder of sex development due to isolated 17,20-lyase deficiency
MONDO:0017240 | acrodysostosis with multiple hormone resistance
MONDO:0017422 | adactyly of hand
MONDO:0018239 | aggrecan-related bone disorder
MONDO:0020343 | alpha-crystallinopathy
MONDO:0016072 | anomaly of puberty or/and menstrual cycle of genetic origin
MONDO:0100343 | antenatal Bartter syndrome
MONDO:0017241 | AP4-related intellectual disability and spastic paraplegia
MONDO:0015921 | ARX-related epileptic encephalopathy
MONDO:0016980 | ATR-X-related syndrome
MONDO:0017670 | autosomal dominant diffuse mutilating palmoplantar keratoderma
MONDO:0015360 | autosomal dominant hereditary axonal motor and sensory neuropathy
MONDO:0015359 | autosomal dominant hereditary demyelinating motor and sensory neuropathy
MONDO:0015365 | autosomal dominant hereditary sensory and autonomic neuropathy
MONDO:0020093 | autosomal dominant isolated diffuse palmoplantar keratoderma
MONDO:0016224 | autosomal dominant proximal spinal muscular atrophy
MONDO:0015088 | autosomal dominant pure spastic paraplegia
MONDO:0016599 | autosomal dominant secondary polycythemia
MONDO:0017270 | autosomal ichthyosis syndrome
MONDO:0015089 | autosomal recessive complex spastic paraplegia
MONDO:0016109 | autosomal recessive distal myopathy
MONDO:0008406 | autosomal recessive Emery-Dreifuss muscular dystrophy
MONDO:0015361 | autosomal recessive hereditary demyelinating motor and sensory neuropathy
MONDO:0015366 | autosomal recessive hereditary sensory and autonomic neuropathy
MONDO:0020096 | autosomal recessive isolated diffuse palmoplantar keratoderma
MONDO:0016536 | autosomal recessive lymphoproliferative disease
MONDO:0014753 | autosomal recessive optic atrophy
MONDO:0015090 | autosomal recessive pure spastic paraplegia
MONDO:0016647 | autosomal recessive Stickler syndrome
MONDO:0015679 | autosomal thrombocytopenia with normal platelets
MONDO:0018384 | avascular necrosis of genetic origin
MONDO:0018775 | axonal hereditary motor and sensory neuropathy
MONDO:0015586 | benign familial mesial temporal lobe epilepsy
MONDO:0019138 | bleeding diathesis due to a collagen receptor defect
MONDO:0044655 | c12orf65-related combined oxidative phosphorylation defect
MONDO:0019213 | cerebral organic aciduria
MONDO:0017448 | congenital absence/hypoplasia of fingers excluding thumb
MONDO:0017447 | congenital absence/hypoplasia of thumb
MONDO:0018888 | congenital cornea plana
MONDO:0018292 | congenital disorder of glycosylation-related bone disorder
MONDO:0018277 | congenital muscular dystrophy with cerebellar involvement
MONDO:0018279 | congenital muscular dystrophy without intellectual disability
MONDO:0018144 | congenital myasthenic syndromes with glycosylation defect
MONDO:0015765 | congenital myopathy with cores
MONDO:0018701 | congenital nemaline myopathy
MONDO:0020375 | coralliform cataract
MONDO:0017922 | deafness-onychodystrophy syndrome
MONDO:0020118 | dense granule disease
MONDO:0018318 | disorder of asparagine metabolism
MONDO:0018579 | disorder of ketone body transport
MONDO:0017709 | disorder of lipid absorption and transport
MONDO:0017745 | disorder of O-mannosylglycan synthesis
MONDO:0017743 | disorder of O-N-acetylgalactosaminylglycan synthesis
MONDO:0017744 | disorder of O-xylosyl/N-acetylgalactosaminylglycan synthesis
MONDO:0017742 | disorder of O-xylosylglycan synthesis
MONDO:0017760 | disorder of other vitamins and cofactors metabolism and transport
MONDO:0017756 | disorder of pterin metabolism
MONDO:0016579 | dominant hypophosphatemia with nephrolithiasis or osteoporosis
MONDO:0016899 | Duchenne and Becker muscular dystrophy
MONDO:0018454 | dysostosis of genetic origin
MONDO:0800094 | dysostosis with brachydactyly with extraskeletal manifestations
MONDO:0800093 | dysostosis with brachydactyly without extraskeletal manifestations
MONDO:0800085 | dysostosis with predominant craniofacial involvement
MONDO:0800075 | dysostosis with predominant vertebral with and without costal involvement
MONDO:0800090 | ectrodactyly with and without other manifestations
MONDO:0020197 | EEC syndrome and related syndrome
MONDO:0036192 | EN1-related dorsoventral syndrome
MONDO:0035685 | epidermolysis bullosa simplex with extracutaneous involvement
MONDO:0035684 | epidermolysis bullosa simplex without extracutaneous involvement
MONDO:0015385 | external auditory canal aplasia/hypoplasia
MONDO:0015470 | familial isolated dilated cardiomyopathy
MONDO:0019150 | familial isolated restrictive cardiomyopathy
MONDO:0013742 | familial mesial temporal lobe epilepsy with febrile seizures
MONDO:0957024 | hereditary 46,XX disorder of sex development
MONDO:0957025 | hereditary 46,XY disorder of sex development
MONDO:0021034 | hereditary alopecia
MONDO:0033947 | hereditary angioedema with normal C1Inh
MONDO:0017132 | hereditary ATTR amyloidosis
MONDO:0015509 | hereditary biliary tract disease
MONDO:0800092 | hereditary inflammatory or rheumatoid-like osteoarthropathy
MONDO:0018188 | hereditary intestinal polyposis
MONDO:0018340 | hereditary isolated aplastic anemia
MONDO:0957001 | hereditary mixed dermis disorder
MONDO:0018562 | hereditary otorhinolaryngological malformation
MONDO:0015508 | hereditary parenchymatous liver disease
MONDO:0957009 | hereditary posterior fossa malformation
MONDO:0017057 | hereditary thrombocytopenia with normal platelets
MONDO:0016229 | hereditary vascular anomaly
MONDO:0015975 | hyper-IgM syndrome with susceptibility to opportunistic infections
MONDO:0015976 | hyper-IgM syndrome without susceptibility to opportunistic infections
MONDO:0018779 | hypercontractile muscle stiffness syndrome
MONDO:0017049 | hypomyelination neuropathy-arthrogryposis syndrome
MONDO:0019505 | hypomyelination-hypogonadotropic hypogonadism-hypodontia syndrome
MONDO:0016352 | idiopathic inherited hypercalciuria
MONDO:0015132 | immunodeficiency predominantly affecting antibody production
MONDO:0019224 | inborn disorder of gamma-aminobutyric acid metabolism
MONDO:0019227 | inborn disorder of glycerol metabolism
MONDO:0017129 | inherited cardiac tumor
MONDO:0018538 | inherited digestive cancer-predisposing syndrome
MONDO:0017128 | inherited digestive tract tumor
MONDO:0035645 | inherited gynecological cancer-predisposing syndrome
MONDO:0017263 | inherited ichthyosis syndromic form
MONDO:0025511 | inherited neuroendocrine tumor
MONDO:0017262 | inherited non-syndromic ichthyosis
MONDO:0017234 | inherited prion disease
MONDO:0017891 | inherited renal cancer-predisposing syndrome
MONDO:0015950 | inherited skin tumor
MONDO:0017127 | inherited soft tissue tumor
MONDO:0020238 | inherited vitreous-retinal disease
MONDO:0017420 | intercalary limb defects
MONDO:0018114 | isolated brachycephaly
MONDO:0018796 | isolated constitutional thrombocytopenia
MONDO:0015337 | isolated craniosynostosis
MONDO:0017667 | isolated diffuse palmoplantar keratoderma
MONDO:0017673 | isolated focal palmoplantar keratoderma
MONDO:0016361 | isolated hereditary giant platelet disorder
MONDO:0035002 | isolated inherited retinal disorder
MONDO:0016520 | isolated Klippel-Feil syndrome
MONDO:0016805 | isolated oxidative phosphorylation complex disorder
MONDO:0018113 | isolated plagiocephaly
MONDO:0016518 | isolated punctate palmoplantar keratoderma
MONDO:0018112 | isolated scaphocephaly
MONDO:0017429 | joint formation defects
MONDO:0034024 | kyphoscoliotic Ehlers-Danlos syndrome
MONDO:0016815 | Leigh syndrome with leukodystrophy
MONDO:0016816 | Leigh syndrome with nephrotic syndrome
MONDO:0019718 | lethal chondrodysplasia
MONDO:0017676 | marginal papular palmoplantar keratoderma
MONDO:0016794 | maternally-inherited mitochondrial myopathy
MONDO:0019697 | mesomelic and rhizo-mesomelic dysplasia
MONDO:0017950 | microcephalic primordial dwarfism
MONDO:0018575 | microcephalic primordial dwarfism-insulin resistance syndrome
MONDO:0019758 | midline interhemispheric variant of holoprosencephaly
MONDO:0019692 | multiple epiphyseal dysplasia and pseudoachondroplasia
MONDO:0019693 | multiple metaphyseal dysplasia
MONDO:0016797 | multiple mitochondrial DNA deletion syndrome
MONDO:0022409 | nephropathy-associated ciliopathy
MONDO:0034671 | non-syndromic complex polydactyly
MONDO:0019713 | non-syndromic limb reduction defect
MONDO:0019714 | non-syndromic polydactyly, syndactyly and/or hyperphalangy
MONDO:0034670 | non-syndromic postaxial polydactyly
MONDO:0034669 | non-syndromic preaxial polydactyly
MONDO:0017421 | non-syndromic terminal limb defects
MONDO:0020275 | oculocutaneous or ocular albinism
MONDO:0018385 | osteochondrosis of genetic origin
MONDO:0020506 | ovarioleukodystrophy
MONDO:0800091 | overgrowth or tall stature syndrome with skeletal involvement
MONDO:0020178 | palpebral lentiginosis
MONDO:0019712 | patellar dysostosis
MONDO:0019689 | perlecan-related bone disorder
MONDO:0018329 | persistent combined dystonia
MONDO:0020345 | presynaptic congenital myasthenic syndrome
MONDO:0800089 | primary bone dysplasia with disorganized development of skeletal components
MONDO:0800084 | primary bone dysplasia with increased bone density
MONDO:0800086 | primary bone dysplasia with multiple joint dislocations
MONDO:0015485 | primary hereditary glaucoma
MONDO:0015823 | primary immunodeficiency due to a defect in adaptive immunity
MONDO:0015135 | primary immunodeficiency due to a genetic defect in innate immunity
MONDO:0020524 | primary parathyroid hyperplasia
MONDO:0017828 | primary renal tubular acidosis
MONDO:0017914 | pure or complex autosomal dominant spastic paraplegia
MONDO:0017915 | pure or complex autosomal recessive spastic paraplegia
MONDO:0017916 | pure or complex X-linked spastic paraplegia
MONDO:0016157 | qualitative or quantitative defects of fukutin
MONDO:0016183 | qualitative or quantitative defects of protein glycosyltransferase-like
MONDO:0016182 | qualitative or quantitative defects of protein O-mannose beta1, 2N-acetylglucosaminyltransferase
MONDO:0015133 | quantitative and/or qualitative congenital phagocyte defect
MONDO:0034217 | resistance to thyroid hormone due to a mutation in thyroid hormone receptor beta
MONDO:0022407 | retinal ciliopathy due to mutation in Bardet-Biedl gene
MONDO:0022405 | retinal ciliopathy due to mutation in nephronophthisis gene
MONDO:0022397 | retinal ciliopathy due to mutation in the retinitis pigmentosa-1 gene
MONDO:0022399 | retinal ciliopathy due to mutation in the RPGR gene
MONDO:0022400 | retinal ciliopathy due to mutation in the RPGRIP gene
MONDO:0022404 | retinal ciliopathy due to mutation in Usher gene
MONDO:0020216 | secondary dysgenetic glaucoma
MONDO:0035075 | secondary early-onset glaucoma of genetic origin
MONDO:0016355 | semilobar holoprosencephaly
MONDO:0017218 | septopreoptic holoprosencephaly
MONDO:0017146 | sickle cell disease and related diseases
MONDO:0016667 | sickle cell disease associated with an other hemoglobin anomaly
MONDO:0019699 | slender bone dysplasia
MONDO:0017629 | sodium channelopathy-related small fiber neuropathy
MONDO:0018550 | spastic paraplegia-optic atrophy-neuropathy and spastic paraplegia-optic atrophy-neuropathy-related disorder
MONDO:0019688 | sulfation-related bone disorder
MONDO:0020346 | synaptic congenital myasthenic syndrome
MONDO:0800095 | syndrome with synostosis or other joint formation defect
MONDO:0020148 | syndromic aniridia
MONDO:0015338 | syndromic craniosynostosis
MONDO:0016565 | syndromic genetic obesity
MONDO:0020211 | syndromic keratoconus
MONDO:0020240 | syndromic retinitis pigmentosa
MONDO:0034954 | syndromic vitreoretinopathy
MONDO:0019176 | trichorhinophalangeal syndrome type I or III
MONDO:0018240 | TRPV4-related bone disorder
MONDO:0800087 | type 11 collagen-related bone disorder
MONDO:0016803 | unspecified inborn mitochondrial disorder
MONDO:0020339 | X-linked complex spastic paraplegia
MONDO:0018451 | X-linked distal hereditary motor neuropathy
MONDO:0018222 | X-linked intellectual disability due to GRIA3 anomalies
MONDO:0017912 | X-linked pure spastic paraplegia

**Comment by katiermullen** [comment]
@sabrinatoro this branch is ready for review. 

Please note my review process:

1. Terms with OMIM xref's were kept in branch thanks @matentzn for helping with this!
2. First, I assigned the terms with OMIM xrefs to the most specific parent as possible, then I realized this would take a long time, so I assigned these terms to the parent 'Hereditary Disease' MONDO:0003847.
3. For the terms that did not have an OMIM xref, if the term or definition contained language to suggest that they were hereditary, e.g. genetic disease, inherited, hereditary, autosomal dominant or autosomal recessive, I assigned them the parent 'Hereditary Disease' MONDO:0003847.
4. For the terms that did not have an OMIM xref and no terminology to suggest they were hereditary, I recommended that they leave the branch.

**Comment by sabrinatoro** [comment]
@katiermullen, Awesome job! 
Please review my comments. 

In addition to your review process, and assuming we can trust the original classification (e.g all children of "MONDO:0016229 - TO_BE_OBSOLETED->hereditary vascular anomaly" are indeed hereditary), I suggest that we keep all the children of terms to be obsoleted in the branch when these terms to be obsoleted contain language like "inherited, autosomal dominant, hereditary".

**Comment by katiermullen** [comment]
@sabrinatoro thank you for the review! I agree with your comments and made the suggested changes.

**Comment by sabrinatoro** [comment]
Thank you @katiermullen. 
I will create a PR first thing on Monday.

**Comment by sabrinatoro** [comment]
There are some comments from the community that should be reviewed, but this is future work. This issue can be closed for now.
