### ISSUE TITLE
Mass Obsoletion: focus on branch 'syndromic disease' (MONDO:0002254)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6878]
Branch: 'syndromic disease' (MONDO:0002254)

Terms to obsolete: 

CURIE | obsoletion candidate label
-- | --
MONDO:0100343 | antenatal Bartter syndrome
MONDO:0017241 | AP4-related intellectual disability and spastic paraplegia
MONDO:0018496 | ARX-related encephalopathy-brain malformation spectrum
MONDO:0016980 | ATR-X-related syndrome
MONDO:0017270 | autosomal ichthyosis syndrome
MONDO:0015089 | autosomal recessive complex spastic paraplegia
MONDO:0016647 | autosomal recessive Stickler syndrome
MONDO:0018144 | congenital myasthenic syndromes with glycosylation defect
MONDO:0016121 | congenital myotonia
MONDO:0017922 | deafness-onychodystrophy syndrome
MONDO:0020197 | EEC syndrome and related syndrome
MONDO:0035682 | fibrous dysplasia/McCune-Albright syndrome
MONDO:0016495 | functional variant of Guillain-Barre syndrome
MONDO:0017955 | granulomatous autoinflammatory syndrome
MONDO:0018538 | inherited digestive cancer-predisposing syndrome
MONDO:0035645 | inherited gynecological cancer-predisposing syndrome
MONDO:0017263 | inherited ichthyosis syndromic form
MONDO:0017891 | inherited renal cancer-predisposing syndrome
MONDO:0018574 | intellectual disability-expressive aphasia-facial dysmorphism syndrome
MONDO:0036042 | KAT6B-related multiple congenital anomalies syndrome
MONDO:0034024 | kyphoscoliotic Ehlers-Danlos syndrome
MONDO:0015591 | limbic encephalitis associated with antibodies to cell membrane antigens
MONDO:0019758 | midline interhemispheric variant of holoprosencephaly
MONDO:0016174 | paraneoplastic sensory ganglionopathy
MONDO:0020345 | presynaptic congenital myasthenic syndrome
MONDO:0018580 | PURA-related severe neonatal hypotonia-seizures-encephalopathy syndrome
MONDO:0017954 | pyogenic autoinflammatory syndrome
MONDO:0016494 | regional variant of Guillain-Barre syndrome
MONDO:0016355 | semilobar holoprosencephaly
MONDO:0017218 | septopreoptic holoprosencephaly
MONDO:0018550 | spastic paraplegia-optic atrophy-neuropathy and spastic paraplegia-optic atrophy-neuropathy-related disorder
MONDO:0020346 | synaptic congenital myasthenic syndrome
MONDO:0035689 | syndrome of reduced sensitivity to thyroid hormone
MONDO:0020148 | syndromic aniridia
MONDO:0015246 | syndromic anorectal malformation
MONDO:0034661 | syndromic biliary atresia
MONDO:0020215 | syndromic corneal dystrophy
MONDO:0015338 | syndromic craniosynostosis
MONDO:0020165 | syndromic epicanthus
MONDO:0015208 | syndromic esophageal malformation
MONDO:0015210 | syndromic gastroduodenal malformation
MONDO:0016565 | syndromic genetic obesity
MONDO:0020210 | syndromic hyperopia
MONDO:0015778 | syndromic hypothyroidism
MONDO:0015212 | syndromic intestinal malformation
MONDO:0020211 | syndromic keratoconus
MONDO:0019520 | syndromic lymphedema
MONDO:0020157 | syndromic palpebral coloboma
MONDO:0015222 | syndromic respiratory or mediastinal malformation
MONDO:0020240 | syndromic retinitis pigmentosa
MONDO:0015620 | syndromic urogenital tract malformation
MONDO:0015846 | syndromic uterovaginal malformation
MONDO:0019176 | trichorhinophalangeal syndrome type I or III
MONDO:0018782 | type 1 interferonopathy
MONDO:0016493 | variant of Guillain-Barre syndrome
MONDO:0020339 | X-linked complex spastic paraplegia
MONDO:0018222 | X-linked intellectual disability due to GRIA3 anomalies

**Comment by katiermullen** [comment]
@sabrinatoro ready for review. Please consider keeping 'autosomal recessive complex spastic paraplegia' as a grouping term in the future if you think it is appropriate.

**Comment by sabrinatoro** [comment]
@katiermullen I agree with your review. 

WRT to keeping 'autosomal recessive complex spastic paraplegia' as a grouping term in the future: 
We removed all classifications based on hereditary "type" (e.g. autosomal recessive). We can of course bring this term back in the future if we have a use case for it. 

Thank you! this is ready for PR!

**Comment by sabrinatoro** [comment]
There are some comments from the community that should be reviewed, but this is future work. This issue can be closed for now.
