### ISSUE TITLE
Bulk request for MONDO IDs

### ISSUE THREAD

**Issue by acoffey26** [monarch-initiative/mondo#6882]
Hi, 
I have 9 diseases/disorders I would like to request a MONDO ID for based on gene curations performed using the ClinGen framework
[Mondo_bulk_submission_ILMN_17_Nov_2023.xlsx](https://github.com/monarch-initiative/mondo/files/13392038/Mondo_bulk_submission_ILMN_17_Nov_2023.xlsx)
. I have filled in the template for bulk submissions as directed - see attached.
Thank you in advance for your help!
Best wishes,
Alison

**Comment by nicolevasilevsky** [comment]
thank you @acoffey26. We'll review these soon and let you know if we have any questions.

**Comment by nicolevasilevsky** [comment]
@acoffey26 to confirm, you want to replace the definition for MONDO:0100061 'PRPS1 deficiency disorder'?

**Comment by acoffey26** [comment]
Sorry should have deleted that row!

Please start from row 5.

Thank you,

Alison


***@***.***


Alison Coffey, PhD
Senior Manager, Clinical Genomics,
Illumina Services Laboratory, San Diego
Medical Genomics Research
858.202.4500
***@***.******@***.***>
www.illumina.com<http://www.illumina.com/>

***@***.***

***@***.***<https://www.facebook.com/illuminainc/>    ***@***.*** <https://www.linkedin.com/company/illumina>     ***@***.*** <https://twitter.com/illumina>

**Comment by nicolevasilevsky** [comment]
sounds good, thanks!

**Comment by nicolevasilevsky** [comment]
@acoffey26 Is there a clingen working group URL that I can associate with these requests?

**Comment by acoffey26** [comment]
We are requesting these for internal gene curations performed using the ClinGen framework but they will be presented to the Syndromic Disorders GCEP over time. Does that help?
https://clinicalgenome.org/affiliation/40060/

We come under the “Other” group
https://clinicalgenome.org/working-groups/clinical-domain/other/
***@***.***


Alison Coffey, PhD
Senior Manager, Clinical Genomics,
Illumina Services Laboratory, San Diego
Medical Genomics Research
858.202.4500
***@***.******@***.***>
www.illumina.com<http://www.illumina.com/>

***@***.***

***@***.***<https://www.facebook.com/illuminainc/>    ***@***.*** <https://www.linkedin.com/company/illumina>     ***@***.*** <https://twitter.com/illumina>

**Comment by nicolevasilevsky** [comment]
perfect, thanks!

**Comment by nicolevasilevsky** [comment]
@acoffey26 
Another question:
The spreadshseet specifies that MONDO:0010011 schizencephaly should be a child of COL4A1-related disorders but I don't see evidence of COL4A1 being involved in this term on the OMIM page: https://omim.org/entry/269160

Is this a mistake or if not, could you please provide evidence of that?

Thank you!

**Comment by nicolevasilevsky** [comment]
@acoffey26 
There is a request for MONDO:0009974 'familial hemophagocytic lymphohistiocytosis type 1' to be a child of FHL1-related myopathy, but this does not seem correct to me. Could you confirm and provide evidence? Thanks!

**Comment by nicolevasilevsky** [comment]
@acoffey26 
for KIF7-related ciliopathies, this code was added to be a child, but this is not a valid ID:
MONDO:00111778

**Comment by acoffey26** [comment]
Hi,

Thank you for your email re a problem with ID MONDO:00111778.

Please accept my apologies, this was a typo on our part and the ID should be MONDO:0011778.

Please let me know if you have any further questions re this ID,

Thank you for your help,

Best wishes,

Alison

***@***.***


Alison Coffey, PhD
Senior Manager, Clinical Genomics,
Illumina Services Laboratory, San Diego
Medical Genomics Research
858.202.4500
***@***.******@***.***>
www.illumina.com<http://www.illumina.com/>

***@***.***

***@***.***<https://www.facebook.com/illuminainc/>    ***@***.*** <https://www.linkedin.com/company/illumina>     ***@***.*** <https://twitter.com/illumina>

**Comment by acoffey26** [comment]
Hi,

Thank you for your enquiry re the inclusion of MONDO:0009974 'familial hemophagocytic lymphohistiocytosis type 1' to be a child of FHL1-related myopathy.

We reviewed our request and agree that this is not a suitable child term for FHL1-related myopathy so would ike to revise our request and remove this term. The edited child terms for FHL1-related myopathy are now suggested as:

X-linked myopathy with postural muscle atrophy|myopathy, reducing body, X-linked, childhood-onset|myopathy, reducing body, X-linked, early-onset, severe|Uruguay Faciocardiomusculoskeletal syndrome|X-linked scapuloperoneal muscular dystrophy| X-linked Emery-Dreifuss muscular dystrophy

MONDO:0010401|MONDO:0010415|MONDO:0010414|MONDO:0010292|MONDO:0010400|MONDO:0010680


Many thanks for your help,

Best wishes,

Alison
***@***.***


Alison Coffey, PhD
Senior Manager, Clinical Genomics,
Illumina Services Laboratory, San Diego
Medical Genomics Research
858.202.4500
***@***.******@***.***>
www.illumina.com<http://www.illumina.com/>

***@***.***

***@***.***<https://www.facebook.com/illuminainc/>    ***@***.*** <https://www.linkedin.com/company/illumina>     ***@***.*** <https://twitter.com/illumina>

**Comment by acoffey26** [comment]
Dear Nicole,

Thank you for your email and enquiry re MONDO:0010011 schizencephaly being a child of COL4A1-related disorders.

We listed schizencephaly  as a child term based on a reference to schizencephaly in OMIM and a publication listed in GeneReviews.

If you open up the clinical synopsis page in OMIM for the disorders associated with COL4A1 ( https://www.omim.org/clinicalSynopsis/table?mimNumber=180000,614519,611773,175780,618564), schizencephaly is listed under BRAIN SMALL VESSEL DISEASE 1 WITH OR WITHOUT OCULAR ANOMALIES; BSVD1 in the section on Central Nervous System.

It is also discussed in PMID: 23225343 (see attached) which describes the finding of variants in COL4A1 in individuals with schizencephaly and suggests the expansion of phenotypic spectrum of COL4A1-related disorders to include schizencephaly.

I hope this provides enough evidence for the inclusion of schizencephaly as a child term, please let me know if you have any further questions and we will be happy to help.

Thank you for your help and careful review,

Best wishes,

Alison

***@***.***


Alison Coffey, PhD
Senior Manager, Clinical Genomics,
Illumina Services Laboratory, San Diego
Medical Genomics Research
858.202.4500
***@***.******@***.***>
www.illumina.com<http://www.illumina.com/>

***@***.***

***@***.***<https://www.facebook.com/illuminainc/>    ***@***.*** <https://www.linkedin.com/company/illumina>     ***@***.*** <https://twitter.com/illumina>

**Comment by nicolevasilevsky** [comment]
> Hi, Thank you for your enquiry re the inclusion of MONDO:0009974 'familial hemophagocytic lymphohistiocytosis type 1' to be a child of FHL1-related myopathy. We reviewed our request and agree that this is not a suitable child term for FHL1-related myopathy so would ike to revise our request and remove this term. The edited child terms for FHL1-related myopathy are now suggested as: - X-linked myopathy with postural muscle atrophy - myopathy, reducing body, X-linked, childhood-onset - myopathy, reducing body, X-linked, early-onset, severe - Uruguay Faciocardiomusculoskeletal syndrome - X-linked scapuloperoneal muscular dystrophy - X-linked Emery-Dreifuss muscular dystrophy MONDO:0010401|MONDO:0010415|MONDO:0010414|MONDO:0010292|MONDO:0010400|MONDO:0010680 Many thanks for your help, Best wishes, Alison

Hi @acoffey26 
According to OMIM, the gene EMD is implicated in 'X-linked Emery-Dreifuss muscular dystrophy'. Only this class ('X-linked myopathy with postural muscle atrophy') is stated to have an FHL1 variation.

**Comment by nicolevasilevsky** [comment]
I added MONDO:0018829 'familial schizencephaly' as a child of 'COL4A1-related disorder'

**Comment by nicolevasilevsky** [comment]
I revised 'COL4A1-related disorder' to be a child of 'hereditary disease' and removed the parent 'vascular disorder' because the vascular phenotypes seem to be only a component of this disease and not every child term is a vascular disorder. This was causing 'familial schizencephaly' to be incorrectly inferred as a child of 'neurovascular disorder'.

**Comment by nicolevasilevsky** [comment]
If this is closed and there are still changes needed, please feel free to reopen this ticket, thanks!
