### ISSUE TITLE
Add xrefs to NORD

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#6883]
Along with the request to include xrefs to ClinGen (#6595), this should also be done for NORD. 

Email sent to request this information.

**Comment by twhetzel** [comment]
The file was received and placed in the Mondo gDrive for further review/processing.

**Comment by twhetzel** [comment]
The file is in the Mondo shared drive in Community provided files.

**Comment by matentzn** [comment]
Prerequisite:

- #7232

**Comment by matentzn** [comment]
This has long been finished.
