### ISSUE TITLE
Rearrange top level of MONDO

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#689]
@cmungall @mellybelly @nicolevasilevsky  I would like to propose that we start to rearrange the top levels of MONDO to clean up infelicities and errors. I would like to start by working on the various classes for genetic disease. Is this acceptable and if so what is the best way of doing things? Should I make a proposal on the tracker and then make a PR?

**Comment by nicolevasilevsky** [comment]
That seems like a good approach to me, @pnrobinson. I can help implement the changes via pull requests too, once we have all agreed on the proposal.

**Comment by cmungall** [comment]
Yes, let's start with the proposal - main concern is to have something that is easily maintained.

**Comment by maglott** [comment]
Where /what is tracker?  I am interested

**Comment by nicolevasilevsky** [comment]
The issue tracker in this repo. Peter will create a new ticket.

**Comment by maglott** [comment]
Thanks.

**Comment by pnrobinson** [comment]
@cmungall I will start next week. But what do you mean by "easily maintained"? I am hoping that once the top levels are good, there will not be much additional maintenance, or will we have to worry about kboom type changes in the future?

**Comment by nicolevasilevsky** [comment]
closing this - I move this to: https://github.com/monarch-initiative/mondo/discussions/2673
