### ISSUE TITLE
Two entities in MONDO are data properties and classes at the same time while they are not in the original PATO ontology

### ISSUE THREAD

**Issue by Odessit007** [monarch-initiative/mondo#6890]
**Mondo term (ID Label)**
These are not the MONDO terms per se but they are listed in the `mondo.owl` file:
* http://purl.obolibrary.org/obo/PATO_0000051
* http://purl.obolibrary.org/obo/PATO_0000070

**Bug/Typo/Error description**
The terms above have a dual type in the `mondo.owl` file: they are both owl:ObjectProperty and owl:Class. These are the only such terms in `mondo.owl` and they are both classes (and not data properties) in `pato.owl`. This dual typing caused failure for one of the tools that my team is using to parse ontology files so I decided to check if this is an intended behavior or maybe a bug in MONDO.

I used this SPARQL query on `mondo.owl` and `pato.owl` to get such "dual" terms:
```
SELECT ?subject
WHERE {
   ?subject rdf:type owl:ObjectProperty .
   ?subject rdf:type owl:Class .
}
```

**Your nano-attribution (ORCID)**
0009-0007-5695-534X

Thanks in advance for your comments.

**Comment by nicolevasilevsky** [comment]
Hi @Odessit007, thanks for reporting this. I believe this is related to these tickets (https://github.com/monarch-initiative/mondo/issues/6737 and https://github.com/monarch-initiative/mondo/issues/6712). @twhetzel is working on these, I assigned this ticket to her.
Thanks!

**Comment by Odessit007** [comment]
Thanks a lot.
Those two issues are indeed about the same problem with the same entities so please, feel free to close my issue if you find it not useful.

As far as I searched over the OWL docs, this simultaneous class/property usage is legitimate so I also raised an issue in our tool's repo. But from the two issues shared by you I conclude that it's also a bug in MONDO so is there any estimate for when this might be fixed on MONDO side?

**Comment by twhetzel** [comment]
Fixed with https://github.com/monarch-initiative/mondo/pull/6961
