### ISSUE TITLE
get GitHub contributors to include them as authors

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6899]
@matentzn please get a list of the github contributors who could be potential authors on the Mondo paper, thanks!

**Comment by matentzn** [comment]
Please use responsibly and avoid another nightmare like HPO:

https://docs.google.com/spreadsheets/d/1WRBPc6v0KTOpFlg4mQMxM6Cv0EL2lY8_1g5CNssxSlU/edit#gid=0

**Comment by nicolevasilevsky** [comment]
thank you, @matentzn. This can be closed
