### ISSUE TITLE
Make a github team that contains all internal contributors

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#6906]
See eg https://github.com/orgs/monarch-initiative/teams?query=mondo (or search for ontologies)

I need a team that has all the Monarch _internal_ contributors for Mondo listed, so I can generate statistics about how many external contributions we get. I am currently using https://github.com/orgs/monarch-initiative/teams/monarch-ontology-team to generate stats like

From 2020-01-01 to 2023-12-31

| Event | Total | Internal | Internal (%) | External | External (%) |
| -------- | -------- | -------- | -------- | -------- | -------- |
| Contributors | 205 | 18 |  8.78 | 187 |  91.22 |
| Issues opened | 2318 | 984 |  42.45 | 1334 |  57.55 |
| Issues closed | 2511 | 2374 |  94.54 | 137 |  5.46 |
| Pull requests opened | 3438 | 2680 |  77.95 | 758 |  22.05 |
| Pull requests closed | 3471 | 3244 |  93.46 | 227 |  6.54 |
| Pull requests merged | 3090 | 2938 |  95.08 | 152 |  4.92 |
| Comments | 8046 | 5573 |  69.26 | 2473 |  30.74 |
| Commits | 8568 | 7543 |  88.04 | 1025 |  11.96 |
| Releases | 52 | 37 |  71.15 | 15 |  28.85 |

**Comment by nicolevasilevsky** [comment]
Nico and I did this.
