### ISSUE TITLE
[Revise logical def]

### ISSUE THREAD

**Issue by groliver** [monarch-initiative/mondo#692]
**Mondo term (ID and Label)**
MONDO:0007052
growth hormone secreting pituitary adenoma 1

**Suggested revision of logical definition**
Add Phenotype linkage: Cutis gyrata of scalp
HP:0010541

More specific linkage than current link only to: Thickened skin
HP_0001072

references:
https://www.ncbi.nlm.nih.gov/pubmed/13277033
https://www.nejm.org/doi/full/10.1056/NEJMicm1811350?query=featured_secondary

ORCID:
https://orcid.org/0000-0001-5106-8935

**Comment by nicolevasilevsky** [comment]
@cmungall would the appropriate thing to do here be add superclass assertions:
'disease causes feature' some 'Cutis gyrata of scalp'
'disease causes feature' some 'Thickened skin'
