### ISSUE TITLE
MONDO:0002063 breast papillomatosis [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#6930]
**Mondo term (ID and Label)**
MONDO:0002063 breast papillomatosis 

**Reason for deprecation**
NCI C6977; DOID1634 and UMLS [C1332636](http://linkedlifedata.com/resource/umls/id/C1332636) are all obsolete.
UMLS CUI C1332636 was merged into C0346156 "benign neoplasm of breast" 
But the NCI thesaurus suggests on their entry for Breast Papillomatosis (Code C6977) Retired Concept "See: https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=ncit&amp;ns=ncit&amp;code=C5201 Breast Intraductal Papillomatosis," which seems to be narrower in scope. 

**Suggested term to consider**
MONDO:0000620 breast benign neoplasm
The children of this obsolete concept would thus just move up one level in the tree and be direct children of this 'grandparent' concept. 
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems! We'll add this to the list and obsolete it in a couple months.
