### ISSUE TITLE
Benign essential blepharospasm

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#6932]
### Label

Benign essential blepharospasm

### Synonyms

Primary focal dystonia affecting the orbicularis oculi muscles

### Synonym type

None

### Definition

Benign essential blepharospasm is a condition characterized by abnormal blinking or spasms of the eyelids. Symptoms may begin as eye twitching and blinking and there may be symptoms of eye irritation. Eventually, BEB causes involuntary closure of the eyes. The exact cause of BEB is unknown. Susceptibility to benign essential blepharospasm may be associated with a microsatellite marker to the dopamine receptor DRD5 gene. The disorder is one of a group of disorders collectively known as adult-onset focal dystonia. Benign essential blepharospasm is different from the common, temporary eyelid twitching that can be caused by fatigue, stress, or caffeine. Treatment of BEB consists of oral drug therapy, focal injections of botulinum toxin (four different brands are available in the USA) or surgery to remove eyelid muscle.

### Parent term

Focal dystonia

### ORCID Identifier

0000-001-9310-0163

### Website URL

https://medlineplus.gov/genetics/condition/benign-essential-blepharospasm/#causes

**Comment by galyea123** [comment]
This is also in GARD.  OMIM has a page on susceptibility to benign essential blepharospasm  https://omim.org/entry/606798
MONDO already list blepharospasm and links it to the OMIM page.

**Comment by nicolevasilevsky** [comment]
got it! Will do!
