### ISSUE TITLE
Brooks Wisniewski Brown syndrome and MENTAL RETARDATION, X-LINKED, SYNDROMIC, TURNER TYPE; MRXST

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#696]
OMIM recently created https://www.omim.org/entry/309590, moving both OMIM:300612 (BROOKS-WISNIEWSKI-BROWN SYNDROME) and  OMIM:300706 into that record.

Both GARD and Orphanet retain a distinction between 
X-linked intellectual disability, Brooks type
and 
X-linked intellectual disability, Turner type

Is this one disorder or two?

**Comment by kanems** [comment]
@ahamosh Can you weigh in on this OMIM merge where others have maintained separate records for these X-linked disorders?

**Comment by nicolevasilevsky** [comment]
cc @galyea-gard

**Comment by galyea-gard** [comment]
After reviewing these we will retire the Brooks Wisniewski Brown syndrome (when we finish updating) and leave only the Turner type, now that the molecular cause was found.  Thank you Nicole!

**Comment by nicolevasilevsky** [comment]
@galyea-gard thanks! What is the GARD ID for the Turner type?

**Comment by galyea-gard** [comment]
Hi Nicole!  It is 5604.  Thank you! Gioconda
