### ISSUE TITLE
review susceptibility terms in Mondo

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#699]
Related to https://github.com/EBISPOT/efo/issues/275

As per our call today, we should review the children of MONDO_0042489 'disease susceptibility'

To do:
- @nicolevasilevsky and @cmungall to create a spreadsheet - _done_
- @nicolevasilevsky and @pnrobinson should review the terms

**Comment by nicolevasilevsky** [comment]
Spreadsheet is here: https://docs.google.com/spreadsheets/d/13Fs1ajbRwaCWNhDgcN0kIfhUmQ2ioCFBj0CwZIEAbZQ/edit#gid=948762561

**Comment by maglott** [comment]
I tried to review the spreadsheet but do not have access. ClinVar and GTR try to represent susceptibilty as a qualifier for the relationship between a disease term and an allele or gene. ClinVar and GTR have been trying to avoid treating 'susceptibility to disease name ' or 'disease name, susceptibility' as a distinct disease name  Is that what is being reviewed?

**Comment by nicolevasilevsky** [comment]
@maglott you should have access now

**Comment by nicolevasilevsky** [comment]
@pnrobinson and I are planning to review these terms and will potentially obsolete them. @maglott please feel free to comment on the spreadsheet, thanks for any feedback.

**Comment by maglott** [comment]
Yes, thanks

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky @pnrobinson @cmungall , 
I’m confused about the strategy here.
Is the plan to obsolete all children of MONDO:0042489 ‘disease susceptibility’? If so, would MONDO keep ‘disease susceptibility’ itself? 
Or is the plan to review all ‘susceptibility’ terms in MONDO and remove any link between them and ‘disease or disorder’, but keep a branch of disease susceptibility that is separate from disease?
In the latest public release of MONDO, at a quick glance I can see two settings:
One where ‘susceptibility’ terms are only children or descendants of ‘disease susceptibility’, e.g. MONDO:0021024 ‘malaria, susceptibility to’;
And another where ‘susceptibility’ terms are children or descendants of ‘disease or disorder’, e.g. MONDO:0010340 ‘Asperger syndrome, X-linked, susceptibility to, 1’ (which is a subclass of ‘Asperger syndrome’ in Ontobee but not in OLS??) or MONDO:0012082 ‘ASPG1’ (UMLS ‘ASPERGER SYNDROME, SUSCEPTIBILITY TO, 1’) (which is a subclass of ‘Asperger syndrome’ in both Ontobee and OLS).
I agree that the latter setting seems incorrect (i.e. susceptibility to disease shouldn't be a disease).
Thanks!

**Comment by pnrobinson** [comment]
There are many meanings of the word susceptibility (as it is used in disease databases)
1. to refer to an allele that confers some susceptibility to a polygenic (complex) disease. A disease such as Asthma for instance currently has 733 such loci (https://www.ebi.ac.uk/gwas/efotraits/EFO_0000270). OMIM has 10 loci for asthma (https://omim.org/entry/600807?search=asthma&highlight=asthma) -- these tend to be the higher effect loci, I believe, but in principle the loci are not different from the 733 in GWAS catalog and (presumably) hundreds or thousands of additional loci yet to be discovered. There is no reason to have a separate MONDO entry for each of these loci.
2. Susceptibility to a cancer that is inherited as a Mendelian trait. The classic example is BRCA1 (https://omim.org/entry/604370). This is essentially the other end of the spectrum to diseases such as asthma, but also the clinical aspects of this disease susceptibility are different in important ways fr4om other cancer susceptibility loci such as BRCA2.
3. Susceptibility to infectious disease. This can be inherited as a Mendelian trait, but one will obvious can only get the disease if one is exposed to the corresponding agent
4. Susceptibility to birth defect. For instance, cleft palate. This is very similar to the asthma example except that possibly the role of the environment is less. 

Probably there are other examples. I would suggest that separate Mondo entries for items 2 and 3 above are correct, and that the entries for 1 and 4 should be rolled up.

**Comment by paolaroncaglia** [comment]
Thanks @pnrobinson .

**Comment by cmungall** [comment]
@paolaroncaglia as a first pass we will be moving classes under 'disease susceptibility' (and deferring commitment on what this means, e.g. a locus or just a general bfo disposition), we can then decide later whether it is worthwhile having these in ontologic form vs just obsoleting.

**Comment by nicolevasilevsky** [comment]
closing this ticket, moving to the discussion: https://github.com/monarch-initiative/mondo/discussions/2672
