### ISSUE TITLE
Consider additional sources for chromosomal rearrangement diseases

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/mondo#7]
@pnrobinson please advise

Was looking at [dbCRID](http://c1.accurascience.com/dbCRID/) but it is out of date; 
Many others listed on that page. 

Some of these should come in via standard dipper for gene/pheno associations but need to ensure MONDO terms are all present.

**Comment by nicolevasilevsky** [comment]
@pnrobinson feel free to close if you see fit

**Comment by pnrobinson** [comment]
Do we have a list of existing sources? If so I will see if there are any others to be added!

**Comment by nicolevasilevsky** [comment]
For the children of 'complex chromosomal rearrangement', the terms come from:
orphanet
ICD9 and 10
GARD
MESH
NCIT
OMIM
SCT
UMLS

**Comment by nicolevasilevsky** [comment]
related to https://github.com/monarch-initiative/mondo/discussions/2584

**Comment by nicolevasilevsky** [comment]
This is out of scope, closing. We've axiomatized chromosomal diseases with monochrome.
