### ISSUE TITLE
ensure that all of the “new” cardiac diseases get added to MONDO 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#70]
ensure that all of the “new” cardiac diseases get added to MONDO with HPO annotations in our gold standard (and/or ingest from this source). 

See paper: https://ojrd.biomedcentral.com/articles/10.1186/s13023-018-0765-y

**Comment by nicolevasilevsky** [comment]
looks like all the disease terms in [PhenoDis](http://mips.helmholtz-muenchen.de/phenodis/) are in MONDO expect two:

- Orphanet:90022 Cardiomyopathy-renal anomalies
- Orphanet:93567 Pediatric systemic sclerosis

@cmungall do we want manually add these terms, or is there a reason why they are not imported from Orphanet?

@pnrobinson I think that all of the cardio terms in this PhenoDis are from Orphanet and OMIM. A lot of these diseases are already annotated with HPO terms. I only looked at a few examples of annotations by PhenoDis, but in at least one case, there were a lot more annotations in their file than what we have. For example, [Steinert myotonic dystrophy ](http://mips.helmholtz-muenchen.de/pheno/disease/show/3548) has 84 HPO terms annotated to it, and we have 25. Maybe you'd like to take a look at this and think about the best way to proceed?

cc @mellybelly

**Comment by cmungall** [comment]
Orphanet:90022 not in ORDO https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_90022

AFAICR the ORDO OWL is lagging behind the live Orphanet by some time, I thought we had a ticket for this, but I can't find it. @siiraa @Orphanet, who is in charge of making the ORDO OWL and is there plans to make a new version?

**Comment by Orphanet** [comment]
Dear all,
ORDO have a specific timeline. The data on the Orphanet’s website are updated on daily basis, monthly on Orphadata.org and twice a year as ORDO (the next version will be online nextweek)
Best regards

**Comment by mellybelly** [comment]
@nicolevasilevsky we should probably add the new HPO annotations to those diseases with attribution to PhenoDis; conversely we can re-curate as I know that we will want to do manual QA on these anyway (we can still attribute to the PhenoDis pub too). @pnrobinson @drseb what are your thoughts?

**Comment by pnrobinson** [comment]
These look like high quality annotations. You can download an excel file, but we will definitely need to Q/C and check the format, I would be careful with automatic ingests before we have checked everything.

---

The information in this email, including attachments, may be confidential and is intended solely for the addressee(s). If you believe you received this email by mistake, please notify the sender by return email as soon as possible.

**Comment by cmungall** [comment]
I suggest moving this to the hpo-annotation tracker. There is no specific dependency on MONDO at this stage. Keep the source disease IDs in the annotation files as we do now (I don't know whether we want to merge into existing small files or make a separate folder, but that's an hpoa-annotation issue). They get merged into MONDO classes downstream (no different than what is currently the case for annotations to OMIM and Orphanet).

It is useful to know ahead of time which ones might fall out with no MONDO IDs, so thanks for the initial analysis @nicolevasilevsky! 

@Orphanet thanks for the info. Is there a reason for the current cycle? For MONDO purposes we may want to track Orphadata (monthly), not sure if it's easiest to run the OWL generation script ourselves or use  the XML directly

**Comment by paolaroncaglia** [comment]
@cmungall
I see that Orphanet has already replied to your question. FYI, Sira is away until Feb 19th. Thanks.

**Comment by nicolevasilevsky** [comment]
@pnrobinson reminder the action item from our meeting today was for you to contact this group and see if they want to contribute to our annotations

**Comment by nicolevasilevsky** [comment]
@pnrobinson per our discussion today on the phenotype call, you are meant to follow up with this group about getting their annotations into the HPOA

**Comment by nicolevasilevsky** [comment]
>
Orphanet:90022 Cardiomyopathy-renal anomalies
Orphanet:93567 Pediatric systemic sclerosis

these have been obsoleted in Orphanet.

We're doing regular Orphanet slurps now
