### ISSUE TITLE
MSX1-related tooth agenesis with or without orofacial cleft

### ISSUE THREAD

**Issue by eedoh01** [monarch-initiative/mondo#7034]
**Preferred gene-related syndrome label**
MSX1-related tooth agenesis with or without orofacial cleft 

**Synonyms**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

**Definition**
 A common developmental disease characterized by varying severity of tooth agenesis that may be seen in combination with orofacial clefting in some individuals 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID: 27699475, 35877402

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
https://clinicalgenome.org/affiliation/40059/

**Comment by nicolevasilevsky** [comment]
@eedoh01 I believe this is the same as MONDO:0007129 'tooth agenesis, selective, 1'?
