### ISSUE TITLE
[Revise subclass]  DICER1-related tumor predisposition (MONDO:0100216)  vs pleuropulmonary blastoma (MONDO:0011014)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7051]
**Mondo term (ID and Label)**

Replacement suggested for
MONDO:0017288 is obsolete 
is (replaced by: MONDO:0100216) DICER1-related tumor predisposition 
Definition
Parents
Pathogenic germline variation in DICER1 confers an autosomal dominant predisposition to tumor formation at multiple primary sites, including pleuropulmonary blastoma, pulmonary cysts, thyroid gland neoplasia, ovarian tumors, and cystic nephroma. Other syndromic features such as macrocephaly have been described.

But should 
pleuropulmonary blastoma (MONDO:0011014)
Definition
Parents
A malignant neoplasm affecting the lungs and/or the pleura. Pleuropulmonary blastoma is seen in children. Microscopically, the tumor may show features of chondrosarcoma, leiomyosarcoma, rhabdomyosarcoma, liposarcoma, or undifferentiated sarcoma. In approximately 25% of patients with pleuropulmonary blastoma, there are other lesions or neoplasms that may affect patients or their families, including lung or kidney cysts, and ovarian or testicular neoplasms. **Heterozygous germline mutations in DICER1 gene have been identified in families harboring pleuropulmonary blastomas.**

Be a superclass?
I'm unsure, because pleuropulmonary blastoma (MONDO:0011014) seems to describe the disease etiology better (although imprecisely i.e. it should be "originating from the lungs or pleura". 
Dicer appears to be only known causative gene identified (although only in 2 out of 3 cases)

As written, MONDO:0100216) DICER1-related tumor predisposition 
could be a gene-specific grouping term for different types of cancer predispositions associated with Dicer? but it really only aligns with pleuropulmonary blastoma (MONDO:0011014)

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
related to [#7562](https://github.com/monarch-initiative/mondo/issues/7562)

**Comment by sabrinatoro** [comment]
From report from the ClinGen team in [this issue](https://github.com/monarch-initiative/mondo/issues/6515):
"Note that OMIM also plans to merge OMIM601200 and OMIM138800 into this new entity - DICER1-related tumor predisposition."
Until OMIM merges these terms, I will make the mondo terms corresponding to these terms subclasses of DICER1-related tumor predisposition. Therefore the classification will be:
DICER1-related tumor predisposition (MONDO:0100216)
--- 'pleuropulmonary blastoma' (MONDO:0011014, OMIM:601200)
--- 'goiter, multinodular 1, with or without Sertoli-Leydig cell tumors'(MONDO:0007681, OMIM:138800)
