### ISSUE TITLE
query replacement for fatal hypertrophic cardiomyopathy

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7052]
MONDO:0017336 is obsolete (consider: MONDO:0100133) -fatal_infantile_hypertrophic_cardiomyopathy_due_to_mitochondrial_complex_i_deficiency

The replacement seems to lose critical information, as there is no mention of fatal/infantile

A type of mitochondrial disease characterized by macrocephaly (large head) with progressive leukodystrophy, encephalopathy, hypertrophic cardiomyopathy, myopathy, liver disease, Leigh syndrome, Leber hereditary optic neuropathy, and some forms of Parkinson disease. The disease is caused by mutations in any of many genes and the inheritance pattern depends on the responsible gene.

and although cardiomyopathy is mentioned the definition is not specific enough for this disease (and there is not cardiomyopathy superclass)

There seem to be quite a lot of publications discussing this specific disease classification
https://pubmed.ncbi.nlm.nih.gov/?term=%22fatal+infantile+hypertrophic+cardiomyopathy%22&sort=date&size=50

**Comment by nicolevasilevsky** [comment]
@ValWood what is the specific action needed here?

It looks like we followed Orphanet in obsoleting this term and pointing to the 'consider' term that they indicated (https://www.orpha.net/consor/www/cgi-bin/OC_Exp.php?Expert=289527).

Would you like this term to be reinstated?

**Comment by ValWood** [comment]
This seems to be a gene specific disorder of NDUFAF1 In OMIN it is called
https://www.omim.org/entry/606934#molecularGenetics
0001 MITOCHONDRIAL COMPLEX I DEFICIENCY, NUCLEAR TYPE 11
so maybe a descendants of MONDO:0100133 are required not to lose the specificity?

**Comment by nicolevasilevsky** [comment]
Hi @ValWood could you please clarify what the specific action item needed is? Thank you.

**Comment by ValWood** [comment]
It's OK, I found the term I needed, it's

MONDO:0032617 mitochondrial complex 1 deficiency, nuclear type 11
