### ISSUE TITLE
MONDO:0800199 Angelman syndrome chromosome region[Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7067]
**Mondo term (ID and Label)**
MONDO:0800199 Angelman syndrome chromosome region

**Reason for deprecation**
I think that this is referring to the locus rather than a clinical phenotype. https://www.omim.org/entry/105830 
"Approximately 70% of AS cases result from de novo maternal deletions involving chromosome **15q11.2-q13**; approximately 2% result from paternal uniparental disomy of 15q11.2-q13; and 2 to 3% result from imprinting defects. A subset of the remaining 25% are caused by mutations in the gene encoding the ubiquitin-protein ligase E3A gene (UBE3A; [601623](https://www.omim.org/entry/601623)) ([Kishino et al., 1997](https://www.omim.org/entry/105830?search=105830&highlight=105830#65))." 
@ahamosh Am I reading into this correctly? While the Gene-Phenotype table on the OMIM page shows UBE3 as the associated gene; the locus 15q11.2-q13 is the "Angelman syndrome chromosome region" ?

**Suggested term to consider**
MONDO:0007113 (Angelman syndrome)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
I agree that this is a chromosome region and not a disease and should be obsoleted
