### ISSUE TITLE
ocular (cicatricial) pemphigoid MONDO:0008109 & MONDO:0020548 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7069]
**Mondo term (ID and Label)**
MONDO:0020548 ocular pemphigoid

**Reason for deprecation**
Some of the x-refs on MONDO:0020548 ocular pemphigoid seem to map to MONDO:0008109 ocular cicatricial pemphigoid, but I am also wondering if these two concepts are similar enough to be merged?

at least one source in UMLS metathesaurus suggests not to merge ..
SNOMEDCT_US has "Benign mucous membrane pemphigoid" (34250006) with a syn of "Ocular pemphigoid" and then narrower/child concept of "Ocular cicatricial pemphigoid" (https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/314757003)"  But there are a lot of CUIs in UMLS with very similar names like these concepts, so it may be just too many variations for their system to cleanly map?

But then again, the StatPearls chapter for this disorder uses the OP name for title, then OCP in defining the condition: https://www.ncbi.nlm.nih.gov/books/NBK526100/ 

  Orphanet [Orphanet:99922](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=99922) and GARD 8759 should, at minimum, move to MONDO:0008109.

**Term to be merged with**
MONDO:0008109 Ocular cicatricial pemphigoid
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
Adding these terms on the list of terms to merge, but we should first confirm whether or not these terms represent the same concept

**Comment by katiermullen** [comment]
Agree with the merging of MONDO:0020548 ocular pemphigoid into MONDO:0008109 Ocular cicatricial pemphigoid based on the references stated. 

It seems as though Ocular pemphigoid/Ocular cicatricial pemphigoid should be a child of SNOMEDCT_US "Benign mucous membrane pemphigoid" (34250006).
