### ISSUE TITLE
question: MONDO:0008458 spinocerebellar ataxia type 2

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#707]
MONDO:0008458 spinocerebellar ataxia type 2 merges two DO terms:

DOID:0050955 spinocerebellar ataxia type 2 
DOID:0060204 amyotrophic lateral sclerosis type 13

Both of these diseases are included on the same OMIM record, but not sure if that means they are the same?

related to #703

**Comment by nicolevasilevsky** [comment]
Same question with:

MONDO:0014076 dyskeratosis congenita, autosomal recessive 5 merges two DO terms:
DOID:0070020 autosomal dominant dyskeratosis congenita 4 
DOID:0070022 autosomal recessive dyskeratosis congenita 5

Both of these diseases are included on the same OMIM record, but not sure if that means they are the same?

**Comment by pnrobinson** [comment]
https://www.omim.org/entry/183090 means that SCA2 is considered a disease, but that certain mutations in ATXN2 can increase susceptibility but not in and of themselves cause ALS. So, ALS13 is a susceptibility locus and should not be represented as a disease. SCA2 should be its own Mondo term.

**Comment by pnrobinson** [comment]
autosomal dominant dyskeratosis congenita 4/5: I am not sure why the OMIM record includes two diseases linked to the same gene, the record does not state this afaics.

**Comment by nicolevasilevsky** [comment]
@pnrobinson here is the link to the OMIM record, where both the 4 and 5 are mentioned:
https://www.omim.org/entry/615190?search=615190&highlight=615190

**Comment by pnrobinson** [comment]
@nicolevasilevsky I saw that, but I still do not know what the rationale is for having two disease types. We should check some of the referenced literature.

**Comment by nicolevasilevsky** [comment]
Ah, I see! I will look at the references, as you suggested, thanks!

**Comment by lcdaugherty** [comment]
@nicolevasilevsky I think 'amyotrophic lateral sclerosis type 13' http://purl.obolibrary.org/obo/DOID_0060204 be removed as ExactMatch from MONDO:0008458 spinocerebellar ataxia type 2
(It also has ExactMatch http://purl.obolibrary.org/obo/DOID_0050955  spinocerebellar ataxia type 2 which is the correct DOID)

**Comment by nicolevasilevsky** [comment]
thanks @lcdaugherty, I made this change
