### ISSUE TITLE
MONDO:0013159	 muscular dystrophy-dystroglycanopathy (congenital with intellectual disability), type B1[Revise subclass]

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7073]
**Mondo term (ID and Label)**

MONDO:0013159 | muscular dystrophy-dystroglycanopathy (congenital with intellectual disability), type B1

(https://www.pombase.org/term/MONDO:0013159)

**Suggested revision and reasons**

add as a subclass of
MONDO:0013159 | muscular dystrophy-dystroglycanopathy (congenital with intellectual disability), type B1

**Comment by nicolevasilevsky** [comment]
@ValWood can you clarify the request? Above you are asking for a class to be a subclass of itself, which I am guessing is a typo :)

**Comment by ValWood** [comment]
no idea!
Maybe I meant B
https://www.pombase.org/term/MONDO:0000172
but it al looks ok to me now! I cant see any problem
