### ISSUE TITLE
Relabel term kidney medullary carcinoma (MONDO:0006260)

### ISSUE THREAD

**Issue by sumirp** [monarch-initiative/mondo#7099]
**Mondo term (ID and Label):**
MONDO:006260 kidney medullary carcinoma

**Suggested new label:**
SMARCB1-deficient renal medullary carcinoma

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0000-0002-1216-4761

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Pubmed ID: 36645398, 35853783

**Comment by nicolevasilevsky** [comment]
Hi @sumirp 
This class is a more general class that is equivalent to https://www.ebi.ac.uk/ols4/ontologies/ncit/classes?short_form=NCIT_C7572

We can add a subclass that is equivalent to https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C189247?lang=en

**Comment by sumirp** [comment]
Hi @nicolevasilevsky yes I agree.
