### ISSUE TITLE
[Obsolete] pancreatic insufficiency, combined exocrine

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#710]
**Mondo term (ID and Label)**
MONDO:0009834

**Reason for deprecation**
OMIM  deprecated https://www.omim.org/entry/260450 and OMIM  seems to have been the only source for the term in UMLS and MeSH
**Suggested replacement or term to consider**
Should this be retained as in independent disorder?  
Is it valid to refer all queries for that term to https://www.omim.org/entry/243800

**Comment by pnrobinson** [comment]
But we should have a term for Exocrine pancreatic insufficiency? This is a disease group.

**Comment by nicolevasilevsky** [comment]
OMIM moved this to JOHANSON-BLIZZARD SYNDROME; JBS MONDO_0009479.

I will merge it with this term.

We do have a class for 'exocrine pancreatic insufficiency': MONDO_0001684
