### ISSUE TITLE
MHC class II deficiency: SCID or non-Severe CID

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#711]
ORDO has SCID and non-SCID

![image](https://user-images.githubusercontent.com/50745/58443742-c46f4b80-80a8-11e9-99ce-0652ef90be56.png)

MHC class II deficiency is in the ns-CID branch rather than SCID:

![image](https://user-images.githubusercontent.com/50745/58443764-e9fc5500-80a8-11e9-96c9-fa7db2739f3e.png)

Others such as DO classify as a SCID:

![image](https://user-images.githubusercontent.com/50745/58443779-09937d80-80a9-11e9-9e10-c5c38acbe598.png)

As does NCIT:

![image](https://user-images.githubusercontent.com/50745/58443809-46f80b00-80a9-11e9-8dc5-eea68f780fc7.png)

On the surface this appears to be a contribution. We might expect the two ORDO classes to be disjoint, and if we equivalenceify the NCIT and DOID by name we end up with a contradiction.

We previously picked this up in the kboom analysis of this class here https://github.com/monarch-initiative/monarch-disease-ontology-RETIRED/issues/181 but didn't follow up

According to

https://www.jacionline.org/article/S0091-6749(14)00797-0/fulltext

_Although MHC class II deficiency is not considered classical SCID according to the International Union of Immunological Societies classification criteria, patients usually present with clinical findings of typical CID. **..[snip]...** Comparing annual reports regarding the prevalence of the different subtypes of SCIDs revealed an approximately 5% frequency of MHC class II in the Canadian survey_

Thus the term "SCID" can be considered ambiguous between "classic SCID" and "'general' SCID". This kind of semantic slippage is common and one of the challenges in aligning disease ontologies.

Currently MONDO follows ORDO here. I would like to make labels and definitions clearer and to fix equivalence axioms. I think if people generally use SCID in the inclusive sense, then if we want a class for the classical strict sense then we should call that "classical SCID"

cc @pnrobinson

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
I think the issue here is to figure out whether 'MHC class II deficiency' should be a child of 'SCIT' (as it is in DO and NCIT), or 'non-SCIT' (as it is in orphanet). 
1) is this what this issue is about? 
2) I cannot find what a "non-SCIT" is (is it a combined T cell and B cell immunodeficiency caused by a defect in immune cells different from the infection-fighting immune cells? or is it a non combined T and B cells immunodeficiency (either only T or B cells). 

Can you figure it out? or should we add this to be discussed with Ada and Peter? 
Thank you!

**Comment by nicolevasilevsky** [comment]
Could you bring it up with Chris on the curation call? Thanks!

**Comment by cmungall** [comment]
I don't have anything further to add at this stage

**Comment by nicolevasilevsky** [comment]
Sounds like Sabrina is on the right track then?

**Comment by pnrobinson** [comment]
I do not think this disease is a type of SCID (with "D" not "T"), although it is a sever disease. Also, I believe that there are four genetic subclasses, e.g. https://omim.org/entry/209920, and we should coordinate this with the way OMIM represents these diseases @ahamosh

**Comment by nicolevasilevsky** [comment]
- [ ] rename 'non-severe combined immunodeficiency' to non-SCID combined immunodeficiency

**Comment by nicolevasilevsky** [comment]
we should reclassify the terms according to the paper in this discussion:
https://github.com/monarch-initiative/mondo/discussions/4304

This issue will be address with this project above.
