### ISSUE TITLE
cleaning up excluded_subclassOf axioms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#7114]
1. delete all excluded_subclassOf axioms without provenance because the purpose of the excluded_subClassOf was to keep the provenance of superclass assertions (https://mondo.readthedocs.io/en/latest/editors-guide/g-logical-axioms/#excluded-subclassof)
    - some of these may come back with the synchronization 
3. because I added the majority of the excluded_subclassOf axioms, Nico and I are adding my ORCID as the source to the existing excluded_subclassOf axioms, related to https://github.com/monarch-initiative/mondo/issues/7101

cc @matentzn

**Comment by nicolevasilevsky** [comment]
@matentzn do we still need to do the first bullet - delete all excluded_subclassOf axioms without provenance?

Or are there no longer any excluded_subclassOf axioms without provenance?

If that is the case, this can be closed then, yeah?

**Comment by matentzn** [comment]
Yes, can be closed. This issue is addressed.
