### ISSUE TITLE
Batch Orphanet X-refs request

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7116]
**Mondo term (ID and Label):**
I found a few discrepancies in Orphanet ID mapping. Please let me know if the data below is unclear, but this seemed simpler than 4 different tickets for relatively straightforward X-ref updates.

**Xref that should be fixed (ID and label):**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kanems/AppData/Local/Temp/4/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kanems/AppData/Local/Temp/4/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Orphanet ID | Current Mondo ID | Proposed new Mondo ID | Rationale
-- | -- | -- | --
ORPHA1662 | MONDO:0800042 | MONDO:0031213 | Orphanet maps to >1 OMIM #, should move to the parent rather than   genetic subtype.
ORPHA2273 | MONDO:0100213 | MONDO:0100212 | Orphanet maps to >1 OMIM #, should move to the parent rather than   genetic subtype.
ORPHA275761 | MONDO:0019149 | MONDO:0800449 | This refers to a 'continuum' of presentation, is a parent to 2 other   Orpha IDs.
ORPHA75234 | none? | MONDO:0019149 | This is the correct Orpha ID for 'cholesteryl ester storage disease'

</body>

</html>

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by cmungall** [comment]
I'd do some label cleanup at the same time. E.g. MONDO:0100213 sounds a bit
generic "IFAP syndrome with or without BRESHECK syndrome" (in fact the name
is logically indistinguishable from the parent). This should be renamed to
be consistent with the OMIM name "IFAP syndrome **1** with or without
BRESHECK syndrome"
