### ISSUE TITLE
Request for new term [craniofacial microsomia 2]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7117]
### Label

craniofacial microsomia 2

### Synonym type

None

### Definition

Craniofacial microsomia-2 (CFM2) is caused by homozygous or heterozygous mutation in the FOXI3 gene on chromosome 2p11 (OMIM, 620444)

### Parent term

MONDO:0007712 

### Website URL

https://www.omim.org/entry/620444

### Additional comments

MONDO:0007712 is currently the parent for craniofacial microsomia 1 (MONDO:0015397),   but I think that really a new term is needed for "craniofacial microsomia" for the OMIM PS https://www.omim.org/phenotypicSeries/PS164210

**Comment by nicolevasilevsky** [comment]
@kanems this will be added as part of our OMIM migration (to add new terms from OMIM). It's on our radar, hopefully we'll be able to get to this soon.

Thanks!

**Comment by sabrinatoro** [comment]
This term was added in the February release. 
Mondo ID = MONDO:0958194
