### ISSUE TITLE
Question about (Waldenstrom) Macroglobinemia

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7120]
MONDO:0005190 (macroglobulinemia) and MONDO:0100280 (Waldenstrom macroglobulinemia)

Is there a benefit to maintaining these as separate concepts in Mondo? Is there a form of Macroglobulinemia that isn't Waldenstrom? 
I see there are distinct SNOMEDCT codes for 'macroglobulinemia' ([190817009](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/190817009) ) vs.  Waldenstrom macro. ([35562000](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/35562000) or with the umlauted O spelling: 190818004) 
But MeSH and a few other sources in UMLS seem to treat these as interchangeable or simply don't have a standalone concept for "macroglobulinemia." 

At a minimum, should the structure of the 'inborn errors of metabolism' branch be reviewed to see if these 2 terms should be perhaps more closely related? 
(I have no answers here, only questions for experts who may know better... but UMLS lumps these two but are split in Mondo, so I am trying to resolve a CUI mapping for UMLS.)

**Comment by sabrinatoro** [comment]
Discussion on the Experts call (Jan 25, 2024): 
1) These terms refer to neoplastic diseases; therefore, we should trust NCIT.
In NCIT: 
- Waldenstrom Macroglobulinemia (MONDO:0100280) is listed in [NCIT](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C80307). Therefore we should keep this term
- macroglobulinemia (MONDO:0005190), or primary macroglobulinemia, is not listed in NCIT and, therefore, does not appear to be a disease. We should, therefore, obsolete this term.

**Comment by sabrinatoro** [comment]
@zoependlington 
Please see the comment above: it was suggested that macroglobulinemia (MONDO:0005190) be obsoleted as it is not a disease according to NCIT (this term most likely represents a phenotype)

I see that this term has a cross-reference to EFO (EFO:0002616). Could you please share your opinion before we move forward with an observation? 
Is EFO:0002616 equivalent to 'Waldenstrom macroglobulinemia'? (in this case, we should merge the terms) 
Or is it referring to a phenotype? (in this case, we would obsolete the Mondo term on the basis that it is not a disease).

Thank you for sharing your opinion!

**Comment by zoependlington** [comment]
Hi @sabrinatoro MONDO:0005190 (macroglobinemia) is mapped and merged with EFO:0002616 (macroglobinemia) and is currently used by Open Targets (see here: https://platform.opentargets.org/disease/EFO_0002616/associations).

Currently we have the following mapping for Waldenstrom macroglobulinemia:
Mondo ID | EFO ID | Mondo label | EFO label
-- | -- | -- | --
http://purl.obolibrary.org/obo/MONDO_0100280 | http://www.ebi.ac.uk/efo/EFO_0009441 | Waldenstrom macroglobulinemia | Waldenstrom macroglobulinemia

We can break the mapping and merge on our end for MONDO:0005190 (macroglobinemia) and EFO:0002616 (macroglobinemia) and review the EFO term to potentially move to our phenotype branch instead - no worries about obsoleting from us!

**Comment by sabrinatoro** [comment]
Thank you @zoependlington.

To do: obsolete MONDO:0005190 (macroglobulinemia) on the basis that it is a phenotype and not a disease
