### ISSUE TITLE
Request for new term [clonal hematopoiesis]

### ISSUE THREAD

**Issue by brian-mott** [monarch-initiative/mondo#7137]
### Label

clonal hematopoiesis

### Synonyms

clonal hematopoiesis

### Synonym type

exact

### Definition

Cellular proliferation of hematopoietic cells where a substantial proportion of the cells is derived from a single hematopoietic stem cell lineage.
http://purl.obolibrary.org/obo/NCIT_C162188
https://pubmed.ncbi.nlm.nih.gov/34215849/

### Parent term

MONDO:0060782 premalignant hematological system disease

### Additional comments

Ideally there would be a child term, clonal hematopoiesis of indeterminate potential, to match the NCIT ontology
https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C158547?lang=en

**Comment by nicolevasilevsky** [comment]
note to self:
https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C162188

**Comment by twhetzel** [comment]
This seems more like a phenotype than a disease to me, "Clonal hematopoiesis is characterized by the over-representation of blood cells derived from a single clone." from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8050831/

**Comment by twhetzel** [comment]
@sabrinatoro given the comment above, can you confirm that you want this added as a disease term?

**Comment by sabrinatoro** [comment]
This term is in NCIT in the disease branch, and therefore this is a good argument for adding this term as a disease. 
The term label sounds like a phenotype (and in reality, we would probably have a disease and a phenotype with the same name), but we made sure that the definition clearly states that the concept in Mondo refers to a disease (in this case, a precancerous condition).
