### ISSUE TITLE
MONDO:0850302 & MONDO:0000642 Intracranial/brain meningioma[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7138]
**Mondo term (ID and Label)**
MONDO:0000642 brain meningioma

**Reason for deprecation**
C0349604 from UMLS and 302820008 from SNOMEDCT and a few other sources in UMLS treat intracranial meningioma and meningioma of brain as synonyms.

Not sure if that is correct or if there is a clinically/biologically relevant distinction... the patient-focused portion of the American Association of Neurological Surgeons equates "brain tumors" with "intracranial tumors"  https://www.aans.org/en/Patients/Neurosurgical-Conditions-and-Treatments/Brain-Tumors 

**Term to be merged with**
MONDO:0850302 intracranial meningioma

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
I

**Comment by sabrinatoro** [comment]
I am added these terms on the merge list, but we should check with experts before we make the merge.

**Comment by katiermullen** [comment]
Agree that the term MONDO:0000642 brain meningioma should be merged with MONDO:0850302 intracranial meningioma. 

"These tumors originate from the [meninges](http://en.wikipedia.org/wiki/Meninges), the membrane-like structures that surround the brain and spinal cord." https://www.aans.org/en/Patients/Neurosurgical-Conditions-and-Treatments/Brain-Tumors
