### ISSUE TITLE
diseases should not be at root level

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#716]
This was a consequence of the obsoleting "rare disease", we should find a home for these

**Comment by nicolevasilevsky** [comment]
For some of these, could we just we just reclassify them (assert subclasses), like:

ID | Label | Current parent | Suggested parent
-- | -- | -- | -- |
MONDO_0019103 | 'benign exophthalmos syndrome' | 'disease or disorder' (source is orphanet)| 'syndromic disease'
MONDO_0010947 | 'Budd-Chiari syndrome' |'disease or disorder' (source is orphanet) | 'syndromic disease'
MONDO_0017388 | 'celiac trunk compression syndrome' | 'disease or disorder' (source is orphanet) |'syndromic disease'

There are more, these are just some examples

**Comment by nicolevasilevsky** [comment]
I should review these in Orphanet and change the subClassOf assertions

**Comment by nicolevasilevsky** [comment]
questions:

- [ ] 'cell proliferation disorder' is inferred to be a subclass of 'disease or disorder' because of its logical def
