### ISSUE TITLE
MONDO:0003954 Angiokeratoma of Fordyce & MONDO:0020597 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7169]
**Mondo term (ID and Label)**
Angiokeratoma of Fordyce MONDO:0003954 

**Reason for deprecation**
sources in Mondo seem to use these as synonyms (leading to Mondo treating one as a syn of the other) 

**Term to be merged with**
Angiokeratoma of scrotum   MONDO:0020597

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
The definition of 'Angiokeratoma of Fordyce' MONDO:0003954 in Mondo is an angiokeratoma that is located on the scrotum or vulva. PMID: [36193055](https://pubmed.ncbi.nlm.nih.gov/36193055) states the lesions are more common in males, but can occur in females. Thus, I do not think that the terms Angiokeratoma of Fordyce MONDO:0003954 and Angiokeratoma of scrotum MONDO:0020597 are synonyms. I think Angiokeratoma of scrotum MONDO:0020597 should remain a child of Angiokeratoma of Fordyce MONDO:0003954, but maybe the synonyms need to be revised?

**Comment by nicolevasilevsky** [comment]
@kanems @katiermullen 
Fordyce-type angiokeratoma of scrotum is a narrow synonym for 'angiokeratoma of Fordyce', so I think it's okay.

I removed the obsoletion candidate tag from 'angiokeratoma of scrotum'
