### ISSUE TITLE
MONDO:0023232 Giant cell myocarditis  & MONDO:0018008 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7170]
**Mondo term (ID and Label)**
Giant cell myocarditis MONDO:0023232

**Reason for deprecation**
UMLS treats the Orphanet/Idiopathic term equivalent to other sources that are the general 'GCM' concept on C0264856 (Definition on Orphanet suggests there are some forms rooted in autoimmune disorder/trigger, so it is more 'agnostic' of cause than truly saying it completely unknown )

**Term to be merged with**
Idiopathic Giant cell myocarditis MONDO:0018008 
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
According to this reference PMID: [33458585](https://pubmed.ncbi.nlm.nih.gov/33458585), not all giant cell myocarditis (GCMc) cases are idiopathic: 

"GCMc can be idiopathic or occur in various conditions, such as infection (tuberculosis, syphilis, pneumocystis jirovecii parvovirus, coxsackie), inflammation, drug sensitivity, hypersensitivity and vasculitis. At least one group of the condition is considered as an autoimmune disease in 19% of patients in some registries that co-manifest with other autoimmune diseases such as inflammatory bowel disease, cryofibrinogenemia, optic neuritis, Hashimoto thyroiditis, rheumatoid arthritis, Takayasu arteritis, temporal arteritis, myasthenia gravis (MG), alopecia totalis, vitiligo, orbital myositis, autoimmune hepatitis, Guillain-Barré syndrome, systemic lupus erythematosus, Sjögren’s and pernicious anemia."

Thus, I am not sure if 'Giant cell myocarditis' MONDO:0023232 and 'Idiopathic Giant cell myocarditis' MONDO:0018008 should be merged.
