### ISSUE TITLE
Proposal: add synonym 'Cerebral visual impairment, CVI, Cortical visual impairment, Cortical/cerebral visual impairment' for cortical blindness

### ISSUE THREAD

**Issue by kgcl-change-request** [monarch-initiative/mondo#7173]
## Hey ontobot! apply:

* create exact synonym 'Cerebral visual impairment, CVI, Cortical visual impairment, Cortical/cerebral visual impairment' for MONDO:0001385

---

Comment: New synonym proposals based on content in HPO, see https://bioportal.bioontology.org/ontologies/HP/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0100704

This request comes from BioPortal user: twhetzel

**Comment by cmungall** [comment]
@twhetzel can you do this again breaking this into 4 different requests

(yes, this is clunky, we will work on the UI to make this easier for but for now the agent doesn't parse the commas)

**Comment by twhetzel** [comment]
Do you mean make 4 individual synonym proposals from BioPortal?

**Comment by cmungall** [comment]
That's right! It is clunky, but we will improve the UI for this (cc @hrshdhgd) for now the goal is to start building up confidence and familiarity with the system, both via the bioportal UI and via direct issues.

Or if you like you could manually just make a new issue, use the magic invocation and just make a bullet list for each synonym addition, and we can find another example to do via the UI

**Comment by twhetzel** [comment]
The synonyms were resubmitted individuall:
https://github.com/monarch-initiative/mondo/issues/7338

https://github.com/monarch-initiative/mondo/issues/7337

https://github.com/monarch-initiative/mondo/issues/7334

https://github.com/monarch-initiative/mondo/issues/7333
