### ISSUE TITLE
Acquired/secondary polycythemia NCI x-ref

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7176]
**Mondo term (ID and Label):**
acquired polycythemia MONDO_0002438

**Xref that should be fixed (ID and label):**
[Secondary Polycythemia NCI C27178] (https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C27178?lang=en)[NCIT](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C27178)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
This X-ref and the syn should move to secondary polycythemia MONDO_0020115

**Comment by nicolevasilevsky** [comment]
@kanems the NCIT xref is not equivalent, it is noted as a directSiblingOf (indicating it is a sibling term). I deprecated the synonym so it should not be visible in the release file.

Let me know if this does not sufficiently addresses this ticket - thanks!
