### ISSUE TITLE
MONDO:0002368 synonyms and conflict with MONDO:0006302

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7179]
**Mondo term (ID Label)**
papillary serous cystadenocarcinoma MONDO_0002368

**Bug/Typo/Error description**
includes a synonym that is the same pref name as MONDO:0006302 micropapillary serous carcinoma

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@kanems this is a narrow synonym on papillary serous cystadenocarcinoma MONDO_0002368 and it is being used by DO and NCIT, so I would prefer to leave it as is. If this is causing issues for you, please feel free to reopen this ticket, thanks!
