### ISSUE TITLE
Obsolete spasmodic dystonia

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7187]
Spasmodic dystonia

Obsolete in Orphanet  https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=93961

This entity has been obsoleted from the Orphanet nomenclature of rare diseases.

Instead, consider using [Focal, segmental or multifocal dystonia](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=1866)

Of note: Primary dystonia, DYT4 type](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=98805)
 is characterized by predominantly laryngeal dystonia (manifesting as whispering dysphonia) and cervical dystonia (manifesting as torticollis).

0000-001-9310-0163

**Comment by sabrinatoro** [comment]
Orphanet:93961 has a source "MONDO:equivalentObsolete"

Question to experts: is "Spasmodic dystonia" an actual disease? If so, we should keep the term. If not, we should obsolete it on the basis that it is not a disease.

**Comment by galyea123** [comment]
Hi Sabrina!  Just wanted to let you know I also sent a message to Orphanet to know more about the history of the decision in obsoleting the term laryngeal dystonia.

Thank you, Gioconda

**Comment by galyea123** [comment]
Hi Sabrina!

After contacted Orphanet to clarify the reason for obsoletion I learned that they obsoleted the term 'Laryngeal dyskinesia' (Laryngeal dystonia) back in 2004, after an expert review who stated that "the pure focal forms like laryngeal dystonias are not diseases but clinical manifestations occurring mostly alone or simultaneously in hereditary dystonias". They decided to keep only the genetic forms under ORPHA1866 (Focal, segmental or multifocal dystonia). <https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=1866>

Useful sources included by Orphanet : PMID:17242025 (2007) 'Do primary adult-onset focal dystonias share aetiological factors?'<https://pubmed.ncbi.nlm.nih.gov/17242025/> and PMID:37476305 (2023) 'Phenotypic Variability in Acquired and Idiopathic Dystonia'<https://pubmed.ncbi.nlm.nih.gov/37476305/>


Thank you, Gioconda Alyea

**Comment by sabrinatoro** [comment]
Thank you @galyea123, this is extremely helpful!

**Comment by nicolevasilevsky** [comment]
@sabrinatoro what is the action for this? does it need to be obsoleted/added to the list?

**Comment by sabrinatoro** [comment]
@nicolevasilevsky I am still going back and forth about whether this term should be actually obsoleted or not. It is obsoleted in orphanet, but it still exists in other resources. So the action item is to make the decision on obsoletion or not. Then we can move forward accordingly.

**Comment by galyea123** [comment]
Hi Sabrina!  I agree that this is a hard one, as per my review I see that there are many sources that consider it to be a disease and not a clinical manifestation.  Because of that I contacted Orphanet and asked for a review (their assessment was in 2004).   If you decide to keep it, the following sources will be helping as supporting evidence.  I do think this case is very helpful to exemplify the challenges when a disease is obsoleted in Orphanet and we found evidence that may be still worth keeping the condition.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8205448/
https://www.nidcd.nih.gov/health/spasmodic-dysphonia
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5536965/
https://aao-hnsfjournals.onlinelibrary.wiley.com/doi/10.1177/0194599817728521
https://www.researchgate.net/publication/343898191_The_prevalence_and_clinical_features_of_spasmodic_dysphonia_A_review_of_epidemiological_surveys_conducted_in_Japan
https://emedicine.medscape.com/article/864079-overview#a7
https://www.aans.org/en/Patients/Neurosurgical-Conditions-and-Treatments/Dystonia
https://dystonia-foundation.org/what-is-dystonia/types-dystonia/spasmodic-dysphonia/
Thank you, Gioconda

**Comment by sabrinatoro** [comment]
I added a comment on MONDO:0000485 (spasmodic dystonia) to indicate that we discussed this term and determined that it refers to a disease. I also added the GH tracker link, so we can get back at a future time if necessary.
