### ISSUE TITLE
MONDO:0004964 & MONDO:0019476 Peripheral T-cell lymphoma [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7188]
**Mondo term (ID and Label)**
MONDO:0004964 Peripheral T-cell lymphoma, not otherwise specified

**Reason for deprecation**
UMLS puts these on same CUI
 NCIT has other sub-types grouped under this term (intent seems to be a broader concept without specific subtype markers/morphology)

**Term to be merged with**
MONDO:0019476 Peripheral T-cell lymphoma
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by twhetzel** [comment]
@kanems is MONDO:0019476 the correct Mondo ID? The label for this is 'primary cutaneous peripheral T-cell lymphoma not otherwise specified' not 'Peripheral T-cell lymphoma'. Also, what CUI do you see where these are the same?

**Comment by kanems** [comment]
Hi @twhetzel yes, that's the right Mondo ID, I copied the SNOMED CT preferred name from our database by error, whoops!
The merge suggestion is MONDO:0004964 (peripheral T-cell lymphoma, not otherwise specified) & MONDO:0019476 (primary cutaneous peripheral T-cell lymphoma not otherwise specified)
Here is a screenshot from UMLS's Metathesaurus browser that shows their concept mappings for C0079774 (the CUI is highlighted in the URL at the top, x-refs I often see in Mondo and we treat as authoritative are also highlighted)
![image](https://github.com/monarch-initiative/mondo/assets/71083858/dc85b06b-315d-4a53-b3e5-11af16b65c84)

**Comment by sabrinatoro** [comment]
**(2024-03-28 Mondo expert call):** 
We might need to talk to a Tcell expert

**Comment by twhetzel** [comment]
We have discussed this further and at this time we believe MONDO:0004964 (peripheral T-cell lymphoma, not otherwise specified) & MONDO:0019476 (primary cutaneous peripheral T-cell lymphoma not otherwise specified) to represent two different T-cell populations.

**Comment by kanems** [comment]
Thanks for this decision, MedGen will keep these separate as well.

**Comment by galyea123** [comment]
Hello,  just adding to the discussion for more clarification on this issue please see: https://www.cancer.gov/types/lymphoma/hp/peripheral-t-cell-lymphoma-pdq#_1481  Thank you, Gioconda Alyea
