### ISSUE TITLE
MONDO:0022414 allain-babin-demarquez syndrome[Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7190]
**Mondo term (ID and Label)**
MONDO:0022414 [allain-babin-demarquez syndrome](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0022414)
**Reason for deprecation**
Orphanet and GARD no longer have any references to this condition; I cannot find any entries in UMLS using the name(s) on this entry either. 

**Suggested term to consider**
OrphaNet says they merged to ORPHA:102285 , which is on MONDO:0015161

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Agree with the rationale for obsoletion. 

Suggested term to consider is MONDO:0015161 as mentioned by @kanems.
