### ISSUE TITLE
MONDO:0042924 Vagneur-Triolle-Ripert syndrome[Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7191]
**Mondo term (ID and Label)**
MONDO:0042924 Vagneur-Triolle-Ripert syndrome

**Reason for deprecation**
There are no sources for this entry. I cannot find any entry in UMLS by this preferred name or the synonym. The only pubmed article I can find with "Vagneur Triolle Ripert" search is https://pubmed.ncbi.nlm.nih.gov/1410904/ which references Gorham disease in the title. 

**Suggested term to consider**
None.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Agree with the rationale to obsolete this term based on no existing sources for it.
