### ISSUE TITLE
Say Carpenter syndrome MONDO:0042902 [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7192]
**Mondo term (ID and Label)**
Say Carpenter syndrome MONDO:0042902 

**Reason for deprecation**
No x-refs on this Mondo entry. Points to NORD subset, and I find this link- https://rarediseases.org/gard-rare-disease/say-carpenter-syndrome/ but it points back to an entry in GARD that no longer exists. 
I do not find any reasonable matches for this name in PubMed search, either.

**Suggested term to consider**
None.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
need to check about the rare disease subsets before obsoleting

**Comment by twhetzel** [comment]
Verified this is ok to obsolete.
