### ISSUE TITLE
Request for new term [Hemiplegic migraine-developmental and epileptic encephalopathy spectrum]

### ISSUE THREAD

**Issue by ARosselClinGen** [monarch-initiative/mondo#7195]
### Label

hemiplegic migraine-developmental and epileptic encephalopathy spectrum

### Synonym type

None

### Definition

A spectrum in which individuals may present with phenotypes ranging from hemiplegic migraines without epilepsy to developmental and epileptic encephalopathy with or without episodic hemiplegia or other forms of paresis. Symptoms and severity may vary within families.

### Parent term

MONDO:0100062 developmental and epileptic encephalopathy, MONDO:0018925 familial or sporadic hemiplegic migraine

### Website URL

https://clinicalgenome.org/affiliation/40005/

### Additional comments

We are hoping to have two parent terms (listed in the Parent term field). This request is being submitted on behalf of the ClinGen Epilepsy Gene Curation Expert Panel, and is intended to capture the phenotypic spectrum associated with genes like _ATP1A2_ (PMIDs: 24096472, 18056581, 33880529).

CC: @ErinRiggs

**Comment by nicolevasilevsky** [comment]
will add with [ROBOT template](https://docs.google.com/spreadsheets/d/1PzCakL380vKgPmiKx78X0OR_3yszzuS7ytHztiIvZVc/edit#gid=1650269388)
