### ISSUE TITLE
Non-human animal disease term obsoletion

### ISSUE THREAD

**Issue by katiermullen** [monarch-initiative/mondo#7200]
Resolve whether non-human animal disease terms should be obsoleted if the cross-species analog term in humans is obsoleted. 

Example is: MONDO:1010034 cleft lip with or without cleft palate, non-human animal

The cross-species analog term has been obsoleted.

**Comment by katiermullen** [comment]
Discussed at non-human animal disease call on 2024-01-26. Depends on the reason why the term is obsoleted in the human branch.

**Comment by sabrinatoro** [comment]
Can we close this issue or is there any action items?
