### ISSUE TITLE
MONDO:0043079 acute articular rheumatism  & MONDO:0017767 rheumatic fever[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7202]
**Mondo term (ID and Label)**
MONDO:0043079 acute articular rheumatism

**Reason for deprecation**
The SNOMED CT code on this Mondo record ([81077008](http://identifiers.org/snomedct/81077008)) maps to the same CUI as multiple concepts for Rheumatic fever. UMLS, following MeSH and MedDRA (another source for UMLS), say these are the same. I could see an argument that the acute rheumatic arthritis is just one symptom seen in rheumatic fever, but I do not know how commonly you would have rheumatic fever without the acute arthritis presentation.

**Term to be merged with**
MONDO:0017767 rheumatic fever

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
**Ada (2024-03-28 Mondo expert call):** 
yes, 'acute rheumatic arthritis' is a feature/a manifestation of rheumatic fever. It is not a disease in itself.

**Comment by katiermullen** [comment]
Based on discussion on the Mondo expert call, recommend obsoleting 'acute rheumatic arthritis' because it is a feature, manifestation of rheumatic fever and not a disease in itself.
