### ISSUE TITLE
Antiphospholipid syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7204]
Antiphospholipid syndrome MONDO:8000010

Note that I do not know if this is the right place to ask for this issue.  Just wanted to say that we reviewed the prevalence of this condition and we will want it listed in our RD NORD list. 

ORCID ID: 0000-001- 9310- 0163

**Comment by sabrinatoro** [comment]
Note: check that this term is added on the NORD-rare after update of the NORD-rare subset

**Comment by sabrinatoro** [comment]
This will be done automatically via the NORD-rare pipeline.
