### ISSUE TITLE
MONDO:0022819 & MONDO:0020296 Congenital arteriovenous fistula/shunt [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7205]
**Mondo term (ID and Label)**
MONDO:0022819 congenital arteriovenous shunt

**Reason for deprecation**
I am not seeing a lot of sources for this first record, only a GARD page showing it's still 'under development.' UMLS includes the CRISP thesaurus sourced term for 'shunt' on the same CUI as the Orphanet concept 98731 and the SNOMED CT 234148007 entries for 'fistula'. UMLS CUI is C0332965  Functionally, I think they are the same?

**Term to be merged with**
MONDO:0020296 Congenital arteriovenous fistula
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Agree with the merging of MONDO:0022819 congenital arteriovenous shunt into MONDO:0020296 Congenital arteriovenous fistula based on the references provided.
