### ISSUE TITLE
MONDO:0023038 & MONDO:0018938 MPS IV[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7206]
**Mondo term (ID and Label)**
eccentrochondrodysplasia MONDO:0018938 

**Reason for deprecation**
Mondo points to [UMLS:C0026707](http://linkedlifedata.com/resource/umls/id/C0026707) as an x-ref on this entry, but this is the concept/CUI for MPS IV (mucopolysaccharidosis type 4 ) UMLS does include eccentrochondrodysplasia  as a synonym on this CUI, but only one source uses this specific term (JABL is the abbreviation, but it looks like it hasn't been updated since 2000).

**Term to be merged with**
MONDO:0018938 MPS IV 
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Agree that the terms MONDO:0023038 and MONDO:0018938 represent the same concept.

Note that MeSH: D009085 Mucopolysaccharidosis IV lists Eccentro-Osteochondrodysplasia and Eccentroosteochondrodysplasia but not eccentrochondrodysplasia as entry terms. 

I don't know if that suggests that the merged MONDO:0023038 concept should be re-labelled when it is added as a syn for MONDO:0018938 MPS IV?

**Comment by nicolevasilevsky** [comment]
note to self:
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0023038 MONDO:0018938 -o -f obo mondo-edit.obo`
