### ISSUE TITLE
OMIM alignment - Feb release

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7211]
Spreadsheet #1 : https://docs.google.com/spreadsheets/d/1A7ILok6Ae7mHQPD88E8k_dGxqLcKcqKWmN0hXpeItXU/edit#gid=487632950

**Comment by sabrinatoro** [comment]
The spreadsheet indicate  includes: 
- terms that are excluded from Mondo (all of them are "genes")
- new terms to add to Mondo
- terms already in Mondo and need the OMIM x-ref
- OMIMPS which are already in Mondo, but the Mondo term is equivalent to an OMIM entry which has been updated to be "type 1" (for these, I removed the original OMIM x-ref, and will check that these are being re-added as children during the next round)

**Comment by kanems** [comment]
Hi Sabrina, I can't open the google doc above, but wanted to check to see if OMIM 254780, MYOCLONIC EPILEPSY OF LAFORA 1 is included on this alignment task?
"Lafora disease" http://purl.obolibrary.org/obo/MONDO_0009697 has the OMIM PS254780 X-ref, but no children terms.  And I do not see OMIM 254780 in the Mondo X-refs from the February release but I don't know if this is an error in our processing.

**Comment by sabrinatoro** [comment]
Hi Megan @kanems 
Thank you for checking in! 
The children of OMIMPS:254780 are not yet in Mondo. I have confirmed that they are in the updated import, and will be available in the next release. These children refer to OMIM:254780 and OMIM:620681.
In summary, it is not an error in your processing :-)
