### ISSUE TITLE
MONDO:0004587 & MONDO:0019152 & MONDO:0016293 [Merge] or [x-ref] ??

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7213]
**Mondo term (ID and Label)**
MONDO:0004587 hereditary night blindness

**Reason for deprecation/Questions/Suggestions**
SNOMED CT [193687000](http://identifiers.org/snomedct/193687000) is Oguchi('s) disease, so I'm not sure it's a match to  MONDO:0004587 hereditary night blindness. ( Move this X-ref to MONDO:0019152 )
And Hereditary night blindness has only one child (congenital stationary night blindness MONDO:0016293), so maybe actually should those two be merged?

**Term to be merged with/additional review**
MONDO:0019152 Oguchi disease ?? UMLS lumps HNB and Oguchi disease, but this seems to be in error (C1306122, I will see if UMLS would split this into a more generic hereditary night blindness vs. the more specific Oguchi type)
or congenital stationary night blindness MONDO:0016293?

Also a minor add on, Oguchi disease-1 and -2 are children of congenital stationary night blindness MONDO:0016293, but MONDO:0019152 Oguchi disease is not, so it seems like those 2 genetic subtypes should be grouped under this broader entry in all instances in the Mondo hierarchy ... maybe? 

I would appreciate any insight from the community from a review of these concepts, will pass along to UMLS for review and potentially CUI updates.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
@sabrinatoro this needs to be added to the list ⬆️

**Comment by nicolevasilevsky** [comment]
note to self:
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0004587 MONDO:0019152  -o -f obo mondo-edit.obo`

**Comment by nicolevasilevsky** [comment]
@katiermullen I'll wait for your review before proceeding

**Comment by katiermullen** [comment]
Proposed classification:

-merge hereditary night blindness with congenital stationary night blindness
  -Oguchi disease (child of congenital stationary night blindness)
      -Oguchi disease-1 (child of Oguchi disease)
      --Oguchi disease-1 (child of Oguchi disease)

**Comment by nicolevasilevsky** [comment]
sounds good, thanks @katiermullen!
