### ISSUE TITLE
MONDO:0005603 &MONDO:0005184  pancreatic ductal/tubular adenocarcinoma[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7215]
**Mondo term (ID and Label)**
MONDO:0005603 pancreatic tubular adenocarcinoma

**Reason for deprecation**
NCI uses these terms as synonyms- http://purl.obolibrary.org/obo/NCIT_C9120 maybe Mondo should merge?

**Term to be merged with**
MONDO:0005184  pancreatic ductal adenocarcinoma
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Agree with the merging of MONDO:0005603 pancreatic tubular adenocarcinoma into MONDO:0005184 pancreatic ductal adenocarcinoma based on NCI use of these terms as synonyms.

**Comment by nicolevasilevsky** [comment]
note to self:
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0005603 MONDO:0005184 -o -f obo mondo-edit.obo`
