### ISSUE TITLE
Synonyms: [ZC4H2 Associated Rare Disorders (ZARD)]

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7217]
### Mondo term

MONDO:0025445 Wieacker-Wolff Syndrome spectrum

### Synonym type

exact

### Additional comments

Newer reports as seen in the NORD report suggest that the correct name should be "ZC4H2 Associated Rare Disorders (ZARD)"; we could keep Wieacker-Wolff Syndrome spectrum as a synonym.  
I would also suggest to merge Wieacker-Wolff syndrome and  Wieacker-Wolff syndrome, female-restricted with this term (currently you have a parent term and the two children, as per OMIM) as we may only need the "parent" term (being that all are, in fact, a phenotyping spectrum and the only difference is that there may be genre-related characteristics that are, in reality, also superimposed. Thoughts?
Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
@galyea123 we prefer to stick with the OMIM preferred labels, but we can add this as an exact synonym.
