### ISSUE TITLE
GATA6- related congenital heart disease with or without pancreatic agenesis or neonatal diabetes

### ISSUE THREAD

**Issue by eedoh01** [monarch-initiative/mondo#7218]
GATA6- related congenital heart disease with or without pancreatic agenesis or neonatal diabetes

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
congenital heart disease 

**Definition**
A heart disease that is present at birth. Representative examples include atrial septal defect 9, conotruncal heart malformations, tetralogy of Fallot, ventricular septal defect, atrioventricular septal defect, bicuspid aortic valve, transposition of the great arteries, persistent truncus arteriosus, congenital heart disease with pancreatic agenesis, and congenital heart disease with neonatal diabetes

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMIDs: 19666519, 23020118, 25937001, 28049534, 29653232, 31301121, 35595280

**Your nano-attribution (ORCID) or URL for a working group**
https://clinicalgenome.org/affiliation/40130/

**Comment by nicolevasilevsky** [comment]
will add with [ROBOT template](https://docs.google.com/spreadsheets/d/1PzCakL380vKgPmiKx78X0OR_3yszzuS7ytHztiIvZVc/edit#gid=1650269388)

**Comment by twhetzel** [comment]
Some of the representative examples are existing disease terms in Mondo, e.g. [atrial septal defect 9](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0013770?lang=en). Is this a new term? If yes, then should this new term has some relation to these other terms?

Note: the parent term is correct in the PR, but the ROBOT template has the wrong parents for this term proposal.

**Comment by nicolevasilevsky** [comment]
> Note: the parent term is correct in the PR, but the ROBOT template has the wrong parents for this term proposal.

yes, the ROBOT template has mistakes, it was only included in the PR for my reference, not for review
