### ISSUE TITLE
[Revise subclass] Review sexual disorder classification

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#723]
**Mondo term (ID and Label)**
"sexual disorder" (MONDO_0000595), and by extension, "physiological sexual disorder" (MONDO_0002134)

**Suggested revision and reasons**
Stemming from an EFO ticket (https://github.com/EBISPOT/efo/issues/425): "Sexual disorder in EFO is currently a child of psychiatric disorder but has in turn a child of physiological sexual disorder, which includes erectile dysfunction. These should not be classed as psychiatric disorders."

EFO has inherited sexual disorder (MONDO_0000595) and physiological sexual disorder (MONDO_0002134) due to mapping of erectile dysfunction (EFO_0004234 and MONDO_0005362).

Also, sexual disorder (MONDO_0000595) has the exact synonym of "sexual and gender identity disorders", suggesting that gender identity disorder (MONDO_0001500) should be related to sexual disorder?

**Comment by nicolevasilevsky** [comment]
note to self - need to revise the superclass for 'sexual disorder' - not sure what the best parent should be, need to look into thiis

**Comment by nicolevasilevsky** [comment]
Looking at this more closely - the mappings for the term MONDO_0000595 'sexual disorder' suggest this is actually a psychiatric disorder.

NCIT:C92202 is Sexual and Gender Identity Disorders and MONDO 'sexual disorder' is using the text def from NCIT:C92202  Sexual and Gender Identity Disorders.

DOID:0060043 'sexual disorder' is an equivalent class and the text def is:
A disease of mental health that involves the impairment in normal sexual functioning.

SCTID:231532002 'sexual disorder' has the Semantic Types: | Mental or Behavioral Dysfunction | Mental or Behavioral Dysfunction | Mental or Behavioral Dysfunction

UMLS:C0236989 has the same label and text def as NCIT.

Proposed solution:
1. Give this class the primary label ' sexual and gender identity disorders' and make sexual disorder a synonym.
2. Move MONDO_0002134 'physiological sexual disorder' to a child of MONDO_0005039 'reproductive system disease'.

**Comment by cmungall** [comment]
this seems reasonable
