### ISSUE TITLE
Create a "mapping change" report to add to the release 

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7230]
Technical call on Feb 02, 2024

Some users might use Mondo for the mappings, therefore it would be good to create a report about changes in mappings, and share it with the Mondo release

Need to examine what tool to do this, KGCL, OAK, sparql query, etc.

**Comment by linikujp** [comment]
Hi, I support this request. With my group, we mainly use MONDO to find out the mappings. While we receive the updates about terms for each release, we will need to have a separate pipeline to check the mapping changes associated with those terms, or even new mappings, deprecated mappings that are not associated with changed terms for each release.  It will be great if MOMDO can provide the mapping changes along with each release.

**Comment by twhetzel** [comment]
Discussing with Nico and Harshad and this can be added into the existing diff pipelines.

**Comment by twhetzel** [comment]
Work towards this is being incorporated in https://github.com/INCATools/ontology-access-kit/pull/605

**Comment by twhetzel** [comment]
The work in OAK is not sufficient for an xref diff so we will make a plan to create this report.

**Comment by twhetzel** [comment]
The first step to addressing this is https://github.com/INCATools/ontology-access-kit/pull/775

**Comment by matentzn** [comment]
Next steps:

1. Add kgcl report goals to mondo.Makefile.

Here is the <details><summary>HPO makefile snippet</summary>

```
##################
### KGCL Diff ####
##################

KGCL_ONTOLOGY=hp-base.obo

prepare_release: kgcl-diff

.PHONY: kgcl-diff
kgcl-diff: kgcl-diff-release-base

.PHONY: kgcl-diff-release-base
kgcl-diff-release-base: reports/difference_release_base.yaml \
						reports/difference_release_base.tsv \
						reports/difference_release_base.md

tmp/hp-released.obo:
	wget http://purl.obolibrary.org/obo/hp.obo -O tmp/hp-released.obo

reports/difference_release_base.md: tmp/hp-released.obo $(KGCL_ONTOLOGY)
	runoak -i simpleobo:tmp/hp-released.obo diff -X simpleobo:$(KGCL_ONTOLOGY) -o $@ --output-type md

reports/difference_release_base.tsv: tmp/hp-released.obo $(KGCL_ONTOLOGY)
	runoak -i simpleobo:tmp/hp-released.obo diff -X simpleobo:$(KGCL_ONTOLOGY) \
	-o $@ --output-type csv --statistics --group-by-property oio:hasOBONamespace

reports/difference_release_base.txt: tmp/hp-released.obo $(KGCL_ONTOLOGY)
	runoak -i simpleobo:tmp/hp-released.obo diff -X simpleobo:$(KGCL_ONTOLOGY) -o $@ --output-type kgcl

reports/difference_release_base.yaml: tmp/hp-released.obo $(KGCL_ONTOLOGY)
	runoak -i simpleobo:tmp/hp-released.obo diff -X simpleobo:$(KGCL_ONTOLOGY) -o $@ --output-type yaml
```

</details>

2. Release OAK (probably done already)
3. Release ODK minor
4. Amend SOP for creating Mondo release notes to use the OAK diff (`reports/difference_release_base.md`) instead of the other MD diff we have right now

**Comment by twhetzel** [comment]
@matentzn is [this PR](https://github.com/monarch-initiative/mondo/pull/7266) still needed related to this overall issue? Can you close the PR or make it active for review as needed? Thanks!

**Comment by matentzn** [comment]
> @matentzn is https://github.com/monarch-initiative/mondo/pull/7266 still needed related to this overall issue? Can you close the PR or make it active for review as needed? Thanks!

Nope, I closed it! Thanks!
