### ISSUE TITLE
Review 'epidermolytic ichthyosis' (MONDO:0007239)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7238]
'epidermolytic ichthyosis' (MONDO:0007239) = OMIM:113800

There is a new OMIMPS: 'epidermolytic hyperkeratosis' (MONDO:0957316)

According to the OMIMPS, 'epidermolytic ichthyosis' (MONDO:0007239) should be a child of 'epidermolytic hyperkeratosis' (MONDO:0957316). However the current record for MONDO:0957316 might include several concepts. 

x-refs should be reviewed for (MONDO:0957316). There might be a term split/merge required

**Comment by kanems** [comment]
I agree this needs review...
OMIM [113800](http://www.omim.org/entry/113800) does not seem to be a correct match to this term, so it probably needs to split out to its own entry that is a child of the Orpha:312 entry and also a child of MONDO:0957316 But i am not sure if the Orpha:312 is actually a direct child of the OMIM PS?
The synonyms from Orphanet suggest that the epidermolytic -hyperkeratosis and -ichthysosis concepts are interchangeable?

**Comment by sabrinatoro** [comment]
This is a complicated issue. I am adding my analysis in 3 different comments, including the to-do list. 
@kanems, when you have a moment, could you take a look at my analysis and let me know if you agree/disagree? Thank you!

**Comment by sabrinatoro** [comment]
**Comment 1: "epidermolytic hyperkeratosis 2"**

The existing OMIM:620150 (currently referring to MONDO:0958184 'epidermolytic hyperkeratosis 2') was recently updated in OMIM (on 02/07/2024). 2 terms now represents 'epidermolytic hyperkeratosis 2'
- OMIM:620707 - Epidermolytic hyperkeratosis 2B, autosomal recessive  (Gene affected = KRT10)
- OMIM:620150 - Epidermolytic hyperkeratosis 2A, autosomal dominant  (Gene affected = KRT10) 

I think we should keep MONDO:0958184 'epidermolytic hyperkeratosis 2 (Gene affected = KRT10) as a grouping term as it is used in other sources such as DOID:0081359 = epidermolytic hyperkeratosis 2 = gene affected KRT10.

TO DO: 
- [] update definition for MONDO:0958184 to include “epidermolytic hyperkeratosis and 'has material basis in germline mutation in' some KRT10)
- [] remove x-ref OMIM:620707 from MONDO:0958184
- [] add x-ref DOID:0081359 to MONDO:0958184
- [] create 2 new terms corresponding to  OMIM:620707 and OMIM:620150

**Comment by sabrinatoro** [comment]
**Comment 2: "general classification"**

General classification should follow orphanet. 
**Parent term** = Keratinopathic ichthyosis (ORDO:281103) = MONDO:0017266
**Children:**
Term names in orphanet | Orphanet ID | OMIM mappings according to Orphanet | Mondo ID corresponding to Orphanet (and OMIM when only 1 omim mapping) | Status in Mondo
-- | -- | -- | -- | --
Annular epidermolytic ichthyosis | ORDO:281139 | OMIM:607602OMIM:620148 | MONDO:0011870 | OK. The Mondo term has 2 children corresponding to the 2 omimRemove the parentage to 'autosomal dominant epidermolytic ichthyosis' (MONDO:0020702)
Autosomal dominant epidermolytic ichthyosis | ORDO:312 | OMIM:113800OMIM:607602 | MONDO:0007239 | The orphanet mapping to omim is incorrect now that omim split OMIM:607602 (see comment 1)Add ORDO:312 to the Mondo recordSee reclassification in comment 3
Autosomal recessive epidermolytic ichthyosis | ORDO:512103 |   | MONDO:0044742 | OKSee reclassification in comment 3
Congenital reticular ichthyosiform erythroderma | ORDO:281190 | OMIM:609165 | MONDO:0012208 | Make this term a child of the parent term: MONDO:0017266
Epidermolytic nevus | ORDO:497737 |   | MONDO:0044656 | OK
Ichthyosis hystrix of Curth-Macklin | ORDO:79503 | OMIM:146590 | MONDO:0007808 | Make this term a child of the parent term: MONDO:0017266
Superficial epidermolytic ichthyosis | ORDO:455 | OMIM:146800 | MONDO:0007813 | OK

**Comment by sabrinatoro** [comment]
**Comment 3: "Epidermolytic hyperkeratosis"**

**finding 1:** From PMID:28815464
Epidermolytic ichthyosis is the **major variant of keratinopathic ichthyosis**, an umbrella term for ichthyosis caused mostly by dominant-negative mutations in the keratin genes KRT1, KRT2, or KRT10 [3]. Epidermolytic ichthyosis is characterized by hyperkeratosis, erythroderma, and superficial skin fragility.

Therefore 'Epidermolytic ichthyosis' should be a child of 'keratinopathic ichthyosis'


**finding 2:** 
OMIMPS:113800 = MONDO:0957316 = Epidermolytic hyperkeratosis
This OMIMPS groups:
- OMIM:113800 - Epidermolytic hyperkeratosis 1 - Gene = KRT1
- OMIM:620707 - Epidermolytic hyperkeratosis 2B, autosomal recessive - Gene = KRT10 (created/updated in OMIM on 02/07/2024)
- OMIM:620150 - Epidermolytic hyperkeratosis 2A, autosomal dominant - Gene = KRT10 = MONDO:0958184 (updated in OMIM on 02/07/2024)


**To do**
I think epidermolytic hyperkeratosis (MONDO:0957316) and epidermolytic ichthyosis (MONDO:0007239) represent the same concept (these names are synonyms in OMIM) and these terms should **be merged.** The term to keep would be ‘epidermolytic ichthyosis’ (MONDO:0007239) as it is the oldest one
 ‘epidermolytic ichthyosis’ would be 
- a child of Keratinopathic ichthyosis (ORDO:281103) = MONDO:0017266
- the parent term for 
   - new term corresponding to OMIM:113800 - Epidermolytic hyperkeratosis 1 - Gene = KRT1
    - MONDO:0958184 'epidermolytic hyperkeratosis 2 (see also comment 1)


The current x-ref should be updated as below: 
Current MONDO:equivalentTo xref | status | To do
-- | -- | --
DOID:0081358 | Represents KRT1 = epidermolytic hyperkeratosis 1 | Move to new term corresponding to OMIM:113800
DOID:4603 | Refers to epidermolytic hyperkeratosis | OK, stays
MESH:D017488 | Refers to general Epidermolytic Ichthyosis | OK, stays
NCIT:C62569 | The NCIT definition is: An autosomal dominant inherited skin disorder caused by mutations in the KRT1 and KRT10 genes. It is manifested at birth and is characterized by generalized erythema, skin blisters and skin fragility. | I think this should be move to Autosomal dominant epidermolytic ichthyosis (MONDO:0007239)
OMIM:113800 | = EPIDERMOLYTIC HYPERKERATOSIS 1; EHK1 (Gene = KRT1) | Move to the new term
Orphanet:312 | Autosomal dominant epidermolytic ichthyosis | move to Autosomal dominant epidermolytic ichthyosis (MONDO:0007239)
SCTID:254167000 | Bullous ichthyosiform erythroderma, which is a synonym in omim | OK stays


Note that the new OMIM terms can be classified also under the existing "autosomal recessive/dominant" term

**Comment by nicolevasilevsky** [comment]
> Comment 1: "epidermolytic hyperkeratosis 2"

Your plan sounds good. I suspect that Lynn + DO team will probably update their term to match OMIM, they may not be aware that OMIM split this into two terms. I'd be happy to check with them, and if they decide to split their term into two terms, we may not need to have the grouping class.

**Comment by nicolevasilevsky** [comment]
> Comment 3: "Epidermolytic hyperkeratosis"

@sabrinatoro I may not be following your comment correctly but you suggested that epidermolytic hyperkeratosis (MONDO:0957316) and epidermolytic ichthyosis (MONDO:0007239) should be merged, but one of these is the OMIMPS (MONDO:0957316) and epidermolytic ichthyosis (MONDO:0007239) is part of the PS, so it should be a child of MONDO:0957316, not merged into it.

**Comment by kanems** [comment]
> Comment 3: Epidermolytic hyperkeratosis
@nicolevasilevsky It looks like @sabrinatoro is suggesting a new Mondo term for the OMIM child concept, thus OMIM 113800 (EPIDERMOLYTIC HYPERKERATOSIS 1) and the DOID matching concept would a NEW record; the remaining equivalentTo items are either synonymous with epid. icthyosis OR need to move to a separate (existing) Mondo ID.  I agree with this reorganization approach. 

All other comments/suggestions seem to be correct to me. And I think this  resolves my other request on #7141 .

**Comment by nicolevasilevsky** [comment]
thanks for clarifying @kanems, sounds good to me!

**Comment by sabrinatoro** [comment]
Left to do: 

- [ ] merge 'epidermolytic hyperkeratosis' (MONDO:0957316) into 'epidermolytic ichthyosis' (MONDO:0007239) 
- [ ] review that the classification and IDs are correct based on comment 3
- [ ] add autosomal dominant/recessive parentage for 'epidermolytic hyperkeratosis 2' terms
