### ISSUE TITLE
Li-Fraumeni syndrome

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7239]
There is a OMIMPS:151623 for Li-Fraumeni syndrome

However, there is already a record MONDO:0018875 which refers to this OMIMPS as "related".
This term should be reviewed

**Comment by sabrinatoro** [comment]
OMIMPS:151623 is a phenotypic series for Li-Fraumeni syndrome and Tumor predisposition syndrome 4, breast/prostate/colorectal.
![Screenshot 2024-02-16 at 13 03 21](https://github.com/monarch-initiative/mondo/assets/12737987/d08215c1-6c90-4ffa-8921-dad5426b7824)

I don't think this OMIMPS should be added as is in Mondo as a grouping term. If so, we should determine what to name this grouping term. 
@nicolevasilevsky, what do you think?

**Comment by nicolevasilevsky** [comment]
@sabrinatoro This was intentionally done and is described in this ticket:
https://github.com/monarch-initiative/mondo/issues/6260

In summary - the ClinGen TP53 Variant Curation Expert Panel said there should only be one form of Li-Fraumeni that is the TP53 variant, the CHEK2 is historical, hence we merged OMIM:191170 with OMIMPS:151623.

**Comment by sabrinatoro** [comment]
@nicolevasilevsky 
Do you think that it would make sense to exclude (or ignore) OMIMPS:151623 from the OMIM alignment then? Because we will not use this term as a "grouping term".

**Comment by nicolevasilevsky** [comment]
this is such an unusual and unprecedented case. I personally prefer to leave it there as it is, as MONDO:relatedTo, otherwise it will probably pop up again in the OMIM migration. Although, I think the OMIM migration script will find any new OMIM term or PS that is not equivalent, and try to add them in but I don't think this has popped again.

**Comment by sabrinatoro** [comment]
Unfortunately, the alignment will try to add it again if it is not equivalent or if it is not in the excluded list (ie it only looks whether the ID is equivalent). 
I will keep an eye on it. 
Thank you! (closing this issue)
