### ISSUE TITLE
[NTR] Ornithine aminotransferase deficiency

### ISSUE THREAD

**Issue by jennygoldstein** [monarch-initiative/mondo#724]
The ClinGen Aminoacidopathy Gene Curation Expert Panel would like to request the addition of the term "ornithine aminotransferase deficiency". This term is currently included as a synonym for "gyrate atrophy" (MONDO:0009796). However, not all patients with ornithine aminotransferase deficiency present with gyrate atrophy. Furthermore, the age of onset of gyrate atrophy can be highly variable in patients with ornithine aminotransferase deficiency, and can be delayed by dietary intervention.

**Preferred term label:**
Ornithine aminotransferase deficiency

**Synonyms**
OAT deficiency, Oat deficiency, OKT deficiency, Okt deficiency, ornithine ketoacid aminotransferase deficiency, ornithine-Delta-aminotransferase deficiency, ornithine Keto acid aminotransferase deficiency

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
Ornithine aminotransferase deficiency is a rare, autosomal disorder of ornithine metabolism. Most patients with ornithine aminotransferase deficiency present in childhood with symptoms of gyrate atrophy, which is caused by elevated ornithine levels. However, the age of onset of gyrate atrophy is variable and can be delayed by dietary intervention. A subset of patients presents in the neonatal period with hyperammonemia (PMID:23076989).

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Inborn error of ornithine metabolism (MONDO:0017356)

**Daughter term**
Gyrate atrophy (MONDO:0009796)
(Note that "ornithine aminotransferase deficiency" would have to be to be removed from the Exact Synonyms for gyrate atrophy, and "OAT deficiency", "Oat deficiency", "OKT deficiency", "Okt deficiency", "ornithine ketoacid aminotransferase deficiency", "ornithine-Delta-aminotransferase deficiency", "ornithine Keto acid aminotransferase deficiency" would have to be removed from the Related Synonyms for gyrate atrophy.

**Your nano-attribution (ORCID)**
0000-0002-5655-9589

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter I see that Ornithine aminotransferase deficiency is a synonym for Gyrate atrophy of choroid and retina, and we wanted to coordinate with you before implementing this change in Mondo. Would you potentially be okay with splitting these out into two diseases?

https://rarediseases.info.nih.gov/diseases/6556/gyrate-atrophy-of-choroid-and-retina

**Comment by jennygoldstein** [comment]
Hi Nicole,


Thanks very much for following up on this. I don't think we want to split ornithine aminotransferase (OAT) deficiency and gyrate atrophy into two separate diseases because gyrate atrophy is caused by OAT deficiency. My concern was how to capture the rare cases of OAT deficiency that don't present with gyrate atrophy but instead have hyperammonemia in the newborn period, abnormal ornithine levels, and have not yet developed gyrate atrophy (but may do later in life).


I talked with Courtney Thaxton (ClinGen Lumping and Splitting Working Group) about this and her suggestion was just to change the text description for MonDO ID to Ornithine Aminotransferase deficiency, and to include gyrate atrophy as a synonym. My initial thought (in the ticket I submitted) was to add Ornithine aminotransferase deficiency as the parent term for gyrate atrophy. However, if it is appropriate from your end to just switch the text description to Ornithine Aminotransferase deficiency, and include gyrate atrophy as a synonym (Courtney's suggestion), I think that's absolutely fine too, recognizing that gyrate atrophy is caused by OAT deficiency, but that individuals with OAT deficiency may be identified and treated before they actually develop gyrate atrophy.


I hope that all makes sense!! Thanks again for following up on this. Please let me know if this needs further discussion.


Thank you for your help, Nicole.


Jenny


________________________________

**Comment by jennygoldstein** [comment]
I'm so sorry - I sent that last email to soon, without including the MonDO ID I was referring to.

What this should say is that Courtney suggested changing the text description for MONDO:0009796 to Ornithine Aminotransferase deficiency, and to include gyrate atrophy as a synonym.


Thanks Nicole!


Jenny

________________________________

**Comment by nicolevasilevsky** [comment]
Hi @jennygoldstein thanks for the clarification. Before I make this change, I'd like to check with @gardinfocenter to make sure they are okay with updating the label of MONDO_0009796 'gyrate atrophy' to Ornithine Aminotransferase deficiency.

Thanks!

**Comment by jennygoldstein** [comment]
Hi Nicole,


OK, that sounds good. Thanks for letting me know, and for all your help with this.


Best wishes,


Jenny


________________________________

**Comment by GARDInfoCenter** [comment]
I have forwarded your email along to our terms lead. I will let you know what she advises.

Thanks,
Maria

**Comment by GARDInfoCenter** [comment]
@nicolevasilevsky 
After reviewing the e-mails and conducting our research, we have decided to keep "gyrate atrophy of the choroid and retina" as our main term and continue to list "gyrate atrophy" and "OAT deficiency" as synonyms. To highlight Jenny's point, we will be updating our summary. However, we are in the process of redesigning our website.

**Comment by nicolevasilevsky** [comment]
@cmungall any objections to renaming MONDO_0009796 from 'gyrate atrophy' to 'Ornithine Aminotransferase deficiency'?

**Comment by nicolevasilevsky** [comment]
Revisiting this - not sure how to best proceed. I will go ahead do a PR to relabel MONDO_0009796, and we will have the xref to GARD and link out to GARD, even though the labels won't match.

@cmungall if you have any objections, please let me know.
