### ISSUE TITLE
amino acid metabolism disease & inborn disorder of amino acid metabolism -syns and relationship?

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7241]
**Mondo IDs**
MONDO:0037871 amino acid metabolism disease & MONDO:0004736 inborn disorder of amino acid metabolism

- On `MONDO:0004736 inborn disorder of amino acid metabolism`, there is a synonym of 
[amino acid metabolic disorder](https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9252?lang=en) from [DOID](https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9252) 
    - I see the intent in this term is that it is for inborn/inherited forms, but the preferred name is a little confusing initially.
- Also I don't see that `MONDO:0004736 inborn disorder of amino acid metabolism` is related in any way to `MONDO:0037871 amino acid metabolism disease`, but I would imagine that the inborn class should be a child of the broader class (which may or may not be inherited, but currently has multiple 'inborn disorder of...X' formatted children concepts. 
- The NCI definition (an exact match on `MONDO:0004736 inborn disorder of amino acid metabolism` ~MONDO:0037871 amino acid metabolism disease~) is "An inherited disorder that affects the metabolism of the amino acids. Representative examples include alkaptonuria, homocystinuria, tyrosinemia, and phenylketonuria."
    - Source: [NCIT:C97090](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C97090)
    - (NV noted): The definition is used on `MONDO:0004736 inborn disorder of amino acid metabolism`  but the equiv xref is on `MONDO:0037871 amino acid metabolism disease`
- But the SNOMED CT exact match on the same Mondo record is agnostic of inborn/acquired 44779003 [https://snomedbrowser.com/Codes/Details/44779003](https://snomedbrowser.com/Codes/Details/44779003).

## Question:
- Can these two terms be reviewed and the relationships and x-refs/exact matches be confirmed? I think UMLS has a lot of these X-refs lumped on the same CUI, but it seems like it should be cleaned up there as well. it would be nice to have the community input on what terms are needed, what should be a stand-alone concept, and which IDs/terms are the same before I open my request with UMLS.

**Note**: _Nicole reformatted this ticket to highlight the questions and action items_

**Comment by nicolevasilevsky** [comment]
_Note: work in progress...._

The terms and xrefs are below:

## MONDO:0037871 amino acid metabolism disease

xref | label
-- | --
xref: NCIT:C97090 {source="MONDO:equivalentTo"} |
xref: SCTID:44779003 {source="MONDO:equivalentTo"} |

## MONDO:0004736 inborn disorder of amino acid metabolism

xref | label
-- | --
xref: DOID:9252 {source="MONDO:equivalentTo"} |
xref: ICD10CM:E72.9 {source="DOID:9252"} |
xref: ICD9:270 {source="DOID:9252"} |
xref: ICD9:270.9 {source="DOID:9252"} |
xref: MESH:D000592 {source="MONDO:equivalentTo", source="DOID:9252"} |
xref: NCIT:C97090 {source="DOID:9252"} |
xref: SCTID:154734005 {source="DOID:9252"} |
xref: SCTID:190680002 {source="DOID:9252"} |
xref: SCTID:190740001 {source="DOID:9252"} |
xref: SCTID:267496003 {source="DOID:9252"} |
xref: SCTID:42930003 {source="MONDO:equivalentTo", source="DOID:9252"} |
xref: SCTID:44779003 {source="MONDO:relatedTo", source="DOID:9252"} |
xref: UMLS:C0002514 {source="MONDO:notFoundInDiseaseSubset", source="DOID:9252"} |

**Comment by nicolevasilevsky** [comment]
I suggest these revisions:

## MONDO:0037871 amino acid metabolism disease

xref | label | equiv?
-- | -- | --
xref: NCIT:C97090 {source="MONDO:equivalentTo"} | Amino Acid Metabolism Disorder | yes
xref: SCTID:190680002 {source="[add Megan's ORCID]", source="https://orcid.org/0000-0001-5208-3432"} | Disorders of amino acid transport and metabolism (disorder) | yes
xref: UMLS:C0002514 {source="MONDO:notFoundInDiseaseSubset"} | disorders of amino acid metabolism | yes

## MONDO:0004736 inborn disorder of amino acid metabolism

xref | label | equiv? | notes
-- | -- | -- | --
xref: DOID:9252 {source="MONDO:equivalentTo"} | [amino acid metabolic disorder](https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_9252) | yes 
xref: [ICD10CM:E72.9](https://www.icd10data.com/ICD10CM/Codes/E00-E89/E70-E88/E72-/E72.9) {source="DOID:9252"} | Disorder of amino-acid metabolism, unspecified |
xref: ICD9:270 {source="DOID:9252"} | Disorders of amino-acid transport and metabolism |
xref: ICD9:270.9 {source="DOID:9252"} | Unspecified disorder of amino-acid metabolism | 
xref: MESH:D000592 {source="MONDO:equivalentTo", source="DOID:9252"} | Amino Acid Metabolism, Inborn Errors | yes | 
xref: NCIT:C97090 {source="DOID:9252"} | Amino Acid Metabolism Disorder |
xref: SCTID:42930003 {source="MONDO:equivalentTo", source="DOID:9252"} | Inborn error of amino acid metabolism (disorder) | yes | 
xref: SCTID:44779003 {source="MONDO:equivalentTo"} | Inborn error of amino acid metabolism (disorder) | yes

**Comment by nicolevasilevsky** [comment]
- [ ] add logical def:

```
'amino acid metabolism disease'
 and ('has characteristic' some inherited)
```
