### ISSUE TITLE
GATA5 related congenital heart defects/ GATA5

### ISSUE THREAD

**Issue by eedoh01** [monarch-initiative/mondo#7242]
**Preferred gene-related syndrome label**
GATA5 related congenital heart defects

**Synonyms**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO:0005453

**Definition**
Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene. For example: Any congenital myopathy in which the cause of the disease is a mutation in the TPM3 gene.

A heart disease that is present at birth. Representative examples include tetralogy of fallot, bicuspid aortic valve, atrial septal defect, double outlet right ventricle, ventricular septal defect, and coarctation of the aorta, and atrioventricular canal. 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMIDs: 22641149, 24638895, 23031282, 22961344, 23289003

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
https://clinicalgenome.org/affiliation/40130/

**Comment by nicolevasilevsky** [comment]
will add with [ROBOT template](https://docs.google.com/spreadsheets/d/1PzCakL380vKgPmiKx78X0OR_3yszzuS7ytHztiIvZVc/edit#gid=1650269388)

**Comment by twhetzel** [comment]
Some of the representative examples are existing disease terms in Mondo, is this a new disease term or a grouping term?
