### ISSUE TITLE
can we use ontobot to add obsoletion tags to obosoletion candidates in Mondo?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#7243]
This is the current workflow:
1. We receive a request to obsolete a term
2. A curator reviews the request and manually copies and pastes the following metadata into [this ROBOT template spreadsheet](https://docs.google.com/spreadsheets/d/1tt1Wk70j9XiHLV1vKQyNiHhaazh286pobpJk1ecSCCg/edit#gid=434975340)
    - Mondo ID
    - Mondo label (this just for human readability)
    - term tracker item
    - Term to consider ID (if applicable)
    - Term to consider label (if applicable)
    - The following fields are concatenated to create a comment: Obsoletion reason (it is always out of scope), exclusion reason, and term to consider (if applicable)
    - Obsoletion candidate subset (`http://purl.obolibrary.org/obo/mondo#obsoletion_candidate`)
    - Obsoletion data (in the format YYYY-MM-DD)

If we had a standardized template that looked something like this in GitHub, could ontobot apply the relevant metadata to the term?

<img width="645" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/ec4bbd68-8c85-4021-802d-4a6dbf701ecf">

Some of the info could be filled out by the user, but some of the info would need to be supplied by us, like the obsoletion candidate subset. Could ontobot be programmed to add additional info like obsoletion candidate or obsoletion date?

We would also need ontobot to be able to concatenate certain info into a comment, like is done in the [spreadsheet](https://docs.google.com/spreadsheets/d/1tt1Wk70j9XiHLV1vKQyNiHhaazh286pobpJk1ecSCCg/edit#gid=434975340) in column I.

The metadata would looks something like this:

<img width="832" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/d16d44fe-03bd-4fe7-992d-068168328049">

**Comment by nicolevasilevsky** [comment]
cc @sabrinatoro @twhetzel

**Comment by sabrinatoro** [comment]
Specific question to @hrshdhgd 
1) can we have ontobot add the "obsoletion candidate" (as explained above)?
2) could we use ontobot to create a 2nd PR **from the same GH issue** to make the actual obsoletion?

**Comment by hrshdhgd** [comment]
> Specific question to @hrshdhgd
> 
> 1. can we have ontobot add the "obsoletion candidate" (as explained above)?

The `obsolete` command does work via `ontobot-change-agent`, example: 
 - Issue: https://github.com/monarch-initiative/mondo/issues/6256
 - PR: https://github.com/monarch-initiative/mondo/pull/6257

> 2. could we use ontobot to create a 2nd PR **from the same GH issue** to make the actual obsoletion?
No. Each issue is associated with one and only one PR.

**Comment by nicolevasilevsky** [comment]
@hrshdhgd this is different that adding the `is_obsolete: true` annotation, this request is to add new annotations, and some of them will be need to be concatenated based on specific input. I'm not sure if ths is possible with ontobot? That is our question.
Thank you!

**Comment by nicolevasilevsky** [comment]
@twhetzel @sabrinatoro - perhaps as an alternative, maybe we could use a sparql query? @matentzn did this sparql in this [PR](https://github.com/monarch-initiative/mondo/pull/7227/files) to add new clingen_preferred synonym types

**Comment by sabrinatoro** [comment]
@nicolevasilevsky a sparql query for what? The query will report a list of terms, not add anything or do an action.

**Comment by nicolevasilevsky** [comment]
If you look at that linked PR, I think Nico used SPARQL to add the clingen_preferred tag (maybe I am wrong?)

**Comment by sabrinatoro** [comment]
I don't think so (or you cannot tell with the PR), but I think that the SPARQL query gives a list of terms (based on specific criteria), and then there was an action (e.g. someone added a tag to something reported in the query). 
But let's ask Nico for clarification.

**Comment by cmungall** [comment]
https://github.com/INCATools/kgcl/issues/49

**Comment by twhetzel** [comment]
From what I understand chatting with Harshad is that KGCL can not yet handle adding the kinds of properties that Mondo uses to indicate that a term is an obsoletion candidate so closing this for and will an eye out for https://github.com/INCATools/kgcl/issues/49
