### ISSUE TITLE
Updates on Mondo Outreach documentation page

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/mondo#7253]
a few updates for the https://mondo.monarchinitiative.org/pages/workshop/#outreach page:

- [x] Update the Mondo Outreach heading to remove "2023"  
- [x] Update the schedule table to have the year attached to the date of the presentation 
- [x] (not necessary, but a suggestion) organize the schedule table in reverse order so that the most recent is at the top. This may make it easier for people to see what is next when they open the page.

**Comment by twhetzel** [comment]
Added changes, please review.

**Comment by sagehrke** [comment]
@twhetzel looks great!
