### ISSUE TITLE
[Revise text def]

### ISSUE THREAD

**Issue by ekyle23** [monarch-initiative/mondo#7255]
**Mondo term: G6PD deficiency (MONDO:0005775)**

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
An X-linked genetic condition caused by alterations in the gene G6PD that result in moderately to severely decreased activity levels of the enzyme glucose-6-phosphate dehydrogenase. Most individuals with G6PD deficiency are asymptomatic. Individuals with G6PD variants that cause G6PD deficiency are at risk for neonatal jaundice. These individuals are also at risk for acute hemolytic anemia in response to certain medication exposures, chemical exposures, infections, or consumption of fava beans.

**Your nano-attribution (N/A)**

**Comment by nicolevasilevsky** [comment]
@ekyle23 could you please share your ORCID or are you part of ClinGen? If yes, could you share the URL to your expert panel?

Thanks!

**Comment by ekyle23** [comment]
Hi Nicole,

I am part of ClinGen! Here is the site for my G6PD VCEP: https://www.clinicalgenome.org/affiliation/50147/

Thank you,
Emily M. Kyle, B.S. (she, her)
ClinGen Coordinator
American College of Medical Genetics and Genomics
7101 Wisconsin Ave #1101, Bethesda, MD 20814
ACMG Office: 301.718.9603 | Direct: 240.858.5009
www.acmg.net<https://protect-us.mimecast.com/s/0Mc9CJ67v7CLky4fzHyTv/>

***@***.***

***@***.***

Follow ACMG on
***@***.***<https://twitter.com/TheACMG>     ***@***.*** <https://protect-us.mimecast.com/s/iR75CL95x5iM0XoSjczUh/>      ***@***.*** <https://protect-us.mimecast.com/s/cVBOCM85y5HVp9oc1eiHl/>      ***@***.*** <https://protect-us.mimecast.com/s/Q4yCCNk5z5t5Y9ntz1H-B/>      ***@***.*** <https://www.youtube.com/user/TheACMGChannel>
[Text  Description automatically generated]

**Comment by nicolevasilevsky** [comment]
thank you @ekyle23!
