### ISSUE TITLE
MONDO:0005594 severe cutaneous adverse reaction

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7258]
**Mondo term (ID and Label):**
MONDO:0005594 severe cutaneous adverse reaction

**Xref that should be fixed (ID and label):**
SNOMEDCT [275322007](http://identifiers.org/snomedct/275322007) "Scar"
NCIT [C34483](https://uts.nlm.nih.gov/uts/umls/vocabulary/NCI/C34483) "scar"
These are specific for "A permanent mark left on the skin in the process of wound healing." 
But based on the primary name, I think these matched in error based on the acronym SCAR.

Add UMLS CUI for severe cutaneous adverse reaction C5554042  (Noting they also have Severe cutaneous adverse reactions (SMQ), CUI: C1869024 as a type of "classification" with a definition of " This SMQ was developed to identify cases of severe, sometimes life-threatening skin reactions that are often drug-induced. Severe cutaneous adverese reactions (SCARs) include: Erythema multiforme, Stevens-Johnsons syndrome, toxic epidermal necrolysis, drug dreactions with eosinophilia and systematic symptoms [DRESS], and acute generalized exanthematous pustulosis." (source: MedDRA, Medical dictionary for regulatory activities ID  20000020, as provided by UMLS; https://www.meddra.org/ ) I think the C5554042  CUI is the right type of record, but the definition on the other cui for SCARs is certainly useful to use instead of the one for 'scar.'
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**

**Comment by nicolevasilevsky** [comment]
Nice catch @kanems. I think you are exactly right that these xrefs were adding based on text matching to the SCAR abbreviation.

@zoependlington FYI, these mistakes exist in EFO too.
