### ISSUE TITLE
Narcolepsy

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7264]
Narcolepsy MONDO:0021107

Narcolepsy is currently classified into two subtypes  1 and 2 (narcolepsy with cataplexy and narcolepsy without cataplexy respectively) 
See MONDO classification  here: https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0021107?lang=en

0000-001-9310-0163

Thank you!  Gioconda

**Comment by nicolevasilevsky** [comment]
Hi @galyea123 can you please clarify what the action item is? Thank you!

**Comment by galyea123** [comment]
Hi!  Narcolepsy with cataplexy is narcolepsy type 1 and Narcolepsy without cataplexy is narcolepsy type 2. (https://www.ninds.nih.gov/health-information/disorders/narcolepsy) 
Type 1 narcolepsy (previously known as narcolepsy with cataplexy)—This diagnosis is based on the individual either having low levels of a brain hormone (hypocretin) or reporting cataplexy and having excessive daytime sleepiness on a special nap test.
Type 2 narcolepsy (previously known as narcolepsy without cataplexy)—People with this condition experience excessive daytime sleepiness but usually do not have muscle weakness triggered by emotions. They usually also have less severe symptoms and have normal levels of the brain hormone hypocretin.narcolepsy without cataplexy.

 In MONDO narcolepsy is classified as: 

narcolepsy without cataplexy
narcolepsy-cataplexy syndrome (3)
  narcolepsy 1
  narcolepsy 3
  narcolepsy 7

In addition to that notice that the Orphanet page for narcolepsy type 1 links to all the OMIM subtypes not only 1, 3 and 7 (this are subtypes that are only based in the specific gene mutation and usually only one or two cases and some only associate with susceptibility or the association is not yet well-defined.

Thank you, Gioconda

I

**Comment by nicolevasilevsky** [comment]
@sabrinatoro and @galyea123 - could you please review this and see if you agree:

![issue-7264 drawio](https://github.com/monarch-initiative/mondo/assets/6722114/718d239f-f62b-4c2c-8cc1-5c69c9b7b0fc)

**Comment by galyea123** [comment]
Hi Sabrina!  I think it should follow the current classification. Narcolepsy is currently subdivided into two types according to the [International Classification of Sleep Disorders, 3rd edition](https://aasm.org/clinical-resources/international-classification-sleep-disorders/) and also to [Orphanet](https://www.orpha.net/en/disease/classification/group/Orphanet%20classification%20of%20rare%20neurological%20diseases?orphaCode=619284&firstParent=0&name=Narcolepsy&mode=name): 
narcolepsy type 1 (NT1), formerly known as narcolepsy with cataplexy) and 
narcolepsy type 2 (NT2), formerly known as  narcolepsy without cataplexy. 
Unlike canine narcolepsy which is monogenic, narcolepsy in humans is not a single genetic disease and it is sporadic in most cases (considered multifactorial). Most of NT1carry a specific HLA haplotype HLA-DQB1*06:02 which confer a susceptibility to the disease. 
NT2 is also a complex disorder, but its genetic is even less understood.
This is helpful: https://www.nature.com/articles/s41439-018-0033-7 
Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
<img width="747" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/d0f5fc30-eaf2-40e9-9c31-317459a07240">
