### ISSUE TITLE
Add recording to Mondo Outreach for Feb 9, 2024

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/mondo#7269]
- [x] Add recording for the February 9, 2024 EBI/OpenTargets Mondo Outreach call to the Outreach page [here](https://mondo.monarchinitiative.org/pages/workshop/#outreach)
Recording is [here](https://drive.google.com/file/d/1fdKunlS2Un6suYdF3mKHv02DdejkOGyn/view?usp=sharing)

- [x] Add March 8, 2024 to the schedule 
Details: Orphanet mapping practices [Julie Tahraoui]

**Comment by twhetzel** [comment]
Updates added: https://mondo.monarchinitiative.org/pages/workshop/#outreach
