### ISSUE TITLE
pseudohypoaldosteronism type 1/I MONDO:0957319 & MONDO:0019161 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7273]
**Mondo term (ID and Label)**
MONDO:0957319, pseudohypoaldosteronism, type I

**Reason for deprecation**
I think these may be the same? The Orphanet mappings only partially overlap with the OMIM PS, but maybe that's a gap in the Orpha mappings and the other OMIM records? But Type "1" vs "I" usually ends up being the same concept in many other cases I've curated/aligned between various sources. 

**Term to be merged with**
MONDO:0019161, pseudohypoaldosteronism type 1
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
MONDO:0957319, pseudohypoaldosteronism, type I maps to the OMIM PS in which there are 4 entries: 

PSEUDOHYPOALDOSTERONISM, TYPE I, AUTOSOMAL DOMINANT; PHA1A
PSEUDOHYPOALDOSTERONISM, TYPE IB1, AUTOSOMAL RECESSIVE; PHA1B1
PSEUDOHYPOALDOSTERONISM, TYPE IB3, AUTOSOMAL RECESSIVE; PHA1B3
PSEUDOHYPOALDOSTERONISM, TYPE IB2, AUTOSOMAL RECESSIVE; PHA1B2

 I wonder if MONDO:0957319, pseudohypoaldosteronism, type I should be merged with MONDO:0019161, pseudohypoaldosteronism type 1 

And if: 
NCIT:C123251 should be mapped to MONDO:0009917 autosomal recessive pseudohypoaldosteronism type 1?

I also wonder if MONDO:0019161, pseudohypoaldosteronism type 1 should have all of the children in the OMIM PS?

Currently the only children of MONDO:0019161 are:

MONDO:0008329 autosomal dominant pseudohypoaldosteronism type 1
MONDO:0009917 autosomal recessive pseudohypoaldosteronism type 1

**Comment by kanems** [comment]
@katiermullen and @sabrinatoro any updates on this request? Do we need to reach out to Julie at Orphanet to get clarification about the scope of their term?

**Comment by katiermullen** [comment]
@kanems Thank you for your question. I think that clarification of the Orphanet term would help in aligning the orpha and OMIM mappings.

**Comment by sabrinatoro** [comment]
I agree with Katie, we should follow up with orphanet, but I think they will (should) update their mappings. 
I see that the [orphanet term](https://www.orpha.net/en/disease/detail/756?name=756&mode=orpha) was last updated in 2021, while the omim terms were updated in 2023/2024. So I imagine they are currently out of synch, but we should still reach out and clarify. 
Thank you for doing this @kanems 
I think that the other 2 new terms in

**Comment by sabrinatoro** [comment]
I agree with the merge. Based on the definition, I believe that Orphanet:756 represents the same grouping concept as OMIMPS:177735 (though orphanet:756 needs to be updated to show all 3 version of the autosomal recessive diseases). Therefore I am merging MONDO:0957319 into MONDO:0019161.
In addition: 
- changing the name of MONDO:0009917 to reflect the latest information available in OMIM:264350. New name PSEUDOHYPOALDOSTERONISM, TYPE IB1, AUTOSOMAL RECESSIVE; PHA1B1. Also reviewing the synonyms and making sure that the x-ref are correct
- updating the classification to show as in the previous comment
- note that based on its definition, DOID:0060854 would refer to a (not in Mondo) grouping term for recessive type 1. I updated the “source” information for this x-ref to refer this.
