### ISSUE TITLE
MONDO:0020327 & MONDO:0004665 nodular sclerosis classical Hodgkin lymphoma[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7278]
**Mondo term (ID and Label)**
MONDO:0020327 classic Hodgkin lymphoma, nodular sclerosis type

**Reason for deprecation**
These two records appear to be the same concept, both have exact matches that map to C0152268 in UMLS 
(Orphanet [98843](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=98843) and SNOMEDCT [118608000](http://identifiers.org/snomedct/118608000) and NCI C3518) 

**Term to be merged with**
MONDO:0004665 nodular sclerosis classical Hodgkin lymphoma
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Agree with the merging of MONDO:0020327 classic Hodgkin lymphoma, nodular sclerosis type into MONDO:0004665 nodular sclerosis classical Hodgkin lymphoma.
