### ISSUE TITLE
MONDO:0006196 endometrial serous adenocarcinoma & MONDO:0003629 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7280]
**Mondo term (ID and Label)**
MONDO:0003629 uterine corpus serous adenocarcinoma

**Reason for deprecation**
The 'uterine corpus serous adenocarcinoma' reports an exact match of  "[endometrial serous adenocarcinoma](https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_5750?lang=en)[DOID](https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FDOID_5750) "

And "uterine corpus serous adenocarcinoma" is an NCI-sourced synonym on  MONDO:0006196 (NCI code = C27838 confirms NCI treats these as synonyms)

**Term to be merged with**
MONDO:0006196  endometrial serous adenocarcinoma
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Confirming merge of MONDO:0003629 uterine corpus serous adenocarcinoma into MONDO:0006196 endometrial serous adenocarcinoma based on NCIT considering uterine corpus serous adenocarcinoma a synonym of endometrial serous adenocarcinoma.

https://nciterms.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C27838
