### ISSUE TITLE
severe intellectual disability-progressive postnatal microcephaly- midline stereotypic hand movements syndrome is the same as intellectual disability, X-linked 1   

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7283]
Hi!  I want first to clarify that I don't know if this is the right issue category as I am not asking to obsolete/deprecate any of these terms but to merge them as they are synonyms and should not be listed as separate conditions.  I would also ask to add  "IQSEC2-Related Disorder" as a synonym (we have a NORD report with this name).  

MONDO:0010656 intellectual disability, X-linked 1 
MONDO:0018347 severe intellectual disability-progressive postnatal microcephaly- midline stereotypic hand movements syndrome.

ORCID ID 0000-001-9310-0163

Thank you, Gioconda Alyea

**Comment by katiermullen** [comment]
Agree with the merging of MONDO:0018347 severe intellectual disability-progressive postnatal microcephaly- midline stereotypic hand movements syndrome into MONDO:0010656 intellectual disability, X-linked 1.

Additional synonym: "IQSEC2-Related Disorder" source: https://rarediseases.org/rare-diseases/iqsec2-related-disorder/
