### ISSUE TITLE
Duplicate terms for familial hypercholesterolemia

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#729]
Noticed the following duplicates during some EFO mapping:

MONDO_0007750 (hypercholesterolemia, familial) duplicates with MONDO_0005439 (familial hypercholesterolemia).

The latter (MONDO_0005439) is a parent of the former (MONDO_0007750) and we currently map EFO_0004911 to MONDO_0005439,

Thanks!

**Comment by nicolevasilevsky** [comment]
@zoependlington I will create a pull request to merge MONDO_0007750 with MONDO_0005439 and send a note to the mailing list in case anyone has any objections.

**Comment by cmungall** [comment]
Be careful. Remember we should not in general have equivalents to OMIMs be superclasses of other OMIMs!

This is more nuanced, first consider what the semantics of this are:
https://omim.org/entry/143890

(this is also tied in with the question of susceptibilities as diseases)

**Comment by nicolevasilevsky** [comment]
It looks like MONDO_0005439 'familial hypercholesterolemia' is xref'ing two OMIM terms:
OMIM:143890 HYPERCHOLESTEROLEMIA, FAMILIAL (which has synonyms type II and type IIa)
OMIM:144010 HYPERCHOLESTEROLEMIA, AUTOSOMAL DOMINANT, TYPE B

so is the xref to OMIM:144010 on MONDO_0005439 'familial hypercholesterolemia incorrect?

**Comment by nicolevasilevsky** [comment]
@cmungall OMIM made changes to OMIM’s representation of Familial hypercholesterolemia in response to this query. There is now a phenotypic series: https://www.omim.org/phenotypicSeries/PS143890

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 
As Nicole has already made a pull request for this ticket, and labeled it "pending PR", I'll take the liberty to assign it tentatively to your upcoming release, as it's affecting EFO. Thanks in advance.
