### ISSUE TITLE
Request for new term [inborn error of surfactant metabolism]

### ISSUE THREAD

**Issue by peastc** [monarch-initiative/mondo#7305]
### Label

inborn error of surfactant metabolism

### Synonyms

hereditary pulmonary alveolar proteinosis

### Synonym type

related

### Definition

Lung disease caused by the presence of a genetic variant negatively affecting pulmonary surfactant associated proteins or processes.

### Parent term

MONDO:0015925

### Children term(s)

MONDO:0016323, MONDO:0012582, MONDO:0018603, MONDO:0009929,  MONDO:0014206, MONDO:0024465, MONDO:0010424, MONDO:0013712

### ORCID Identifier

https://orcid.org/0009-0007-1636-9645

### Additional comments

I am submitting the request to introduce this term on behalf of the ClinGen Interstitial Lung Disease Gene Curation Expert Panel. Our panel believes that the term "inborn error of surfactant metabolism" should replace "hereditary pulmonary alveolar proteinosis" as it is a more accurate parent term for the hereditary surfactant related diseases that reside under it in the disease ontology tree. 
Attached is an image to clarify our request to replace the term "hereditary pulmonary alveolar proteinosis" with "inborn error of surfactant metabolism" and move this parent term and the gene related syndromes beneath it to the parent term "interstitial lung disease". Please disregard the part of this image showing "interstitial lung disease due to SFTPB dysfunction" as a term; we will submit a separate request to introduce that term. 
![update](https://github.com/monarch-initiative/mondo/assets/152438755/f72c62a8-5ec0-4b17-b723-1879f3499b38)

**Comment by nicolevasilevsky** [comment]
Hi @peastc - Nice to virtually meet you, I'm Nicole, I'm a curator with Mondo, I don't believe we've worked together before.

Thanks for your request. if I understand correctly, you are requesting that 'hereditary pulmonary alveolar proteinosis' be relabeled to 'inborn error of surfactant metabolism'. In cases like these, you can request a term to be relabled (there is a [template](https://github.com/monarch-initiative/mondo/issues/new?assignees=&labels=relabel+term&projects=&template=relabel-term.md&title=) for that). However, I'd like to point you to our [disease naming conventions](https://mondo.monarchinitiative.org/pages/disease-naming/) in Mondo. 

In Mondo, we aim to use the OMIM labels as the primary labels for our terms. We can add your term as an exact synonym and add a 'ClinGen label' tag to it. We hope that your ClinGen technical team can enable the terms tagged with 'ClinGen label' to display in your curation interface, so you will see that as the primary label in your system, but the primary label in Mondo will remain as 'hereditary pulmonary alveolar proteinosis'.

Our other Mondo curators and technical developers @sabrinatoro and @twhetzel can advise you too, if you have further questions, or you are welcome to join one of our developers calls to learn more.

Thanks for contributing to Mondo.

**Comment by peastc** [comment]
Hi @nicolevasilevsky! Nice to e-meet you! I am fairly new to the ClinGen team and I am excited to continue to work with you. 
Thank you for your guidance here and for adding this synonym. I will discuss the introduction of new terms as exact synonyms with our GCEP and UNC ClinGen team.
