### ISSUE TITLE
Relabel term [neonatal acute respiratory distress due to SP-B deficiency to interstitial lung disease due to SP-B dysfunction]

### ISSUE THREAD

**Issue by peastc** [monarch-initiative/mondo#7306]
**Mondo term (ID and Label):** MONDO:0009929, neonatal acute respiratory distress due to SP-B deficiency

**Suggested new label:** interstitial lung disease due to SP-B dysfunction

**Your nano-attribution (ORCID):** https://orcid.org/0009-0007-1636-9645

**_Optional_:** I am submitting this request on behalf of the  ClinGen Interstitial Lung Disease Gene Curation Expert Panel. Upon curation of the gene SFTPB, we discovered published cases of interstitial lung disease due to SP-B dysfunction with disease onset outside of the neonatal period (PMIDs:28888561, 37380697) and more unpublished cases are known to the experts of the panel. For this reason, we find it appropriate to relabel this term to include the full spectrum of case presentation known to occur due to SFTPB dysfunction.

**Comment by nicolevasilevsky** [comment]
@peastc We aim to use the OMIM labels for the primary label, so I updated this label to match the current OMIM label ('surfactant metabolism dysfunction, pulmonary, 1') and I added your label as an exact synonym with a 'ClinGen label" on it.
