### ISSUE TITLE
MONDO:0023041 ectodermal dysplasia Berlin type & MONDO:0009522 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7309]
**Mondo term (ID and Label)**
MONDO:0023041 ectodermal dysplasia Berlin type

**Reason for deprecation**
Uses same synonym and same GARD id as the suggested merge term below.

**Term to be merged with**
MONDO:0009522 Leukomelanoderma-infantilism-intellectual disability-hypodontia-hypotrichosis syndrome

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Agree with the merge of MONDO:0023041 ectodermal dysplasia Berlin type into MONDO:0009522 Leukomelanoderma-infantilism-intellectual disability-hypodontia-hypotrichosis syndrome based on overlapping synonyms and GARD id.
