### ISSUE TITLE
SPATA5L1-related complex neurodevelopmental disorder with motor features and hearing loss

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#7317]
### Label

SPATA5L1-related complex neurodevelopmental disorder with motor features and hearing loss

### Synonym type

None

### Definition

A neurodevelopmental disorder related to biallelic variants in SPATA5L1 and characterized by a spectrum of intellectual disability, hearing loss, and motor features including spasticity, dystonia, and/or hypotonia. Other phenotypic features commonly reported with the neurodevelopmental presentation include spasticity, focal or generalized epilepsy, and microcephaly.   

### Parent term

complex neurodevelopmental disorder MONDO:0100038

### Additional comments

https://clinicalgenome.org/affiliation/40006/

@ErinRiggs

**Comment by nicolevasilevsky** [comment]
need to add gene 

@twhetzel @matentzn I tried to add the gene and the command was taking ages:
sh run.sh make refresh-merged (from instructions: https://mondo.readthedocs.io/en/latest/editors-guide/import-terms-for-logical-axioms/)

It didn't used to be so slow, is there a way to address this?

**Comment by matentzn** [comment]
When did it slow down? It takes much longer since we use the merged workflow, this is expected, but this has been like this for about 6 months?

**Comment by nicolevasilevsky** [comment]
it's quite possible I haven't run this workflow in the past 6 months...?

It was super slow, it ran for over an hour before I gave up. Is this the new normal?

**Comment by twhetzel** [comment]
I have not run the import for genes, just taxon, and that took ~2 hours. I gather it would be helpful to add how long this import takes on the Mondo web site so we know that these are long processes and not broken and will eventually finish.

**Comment by twhetzel** [comment]
@nicolevasilevsky in the meantime, I can also run this to add the gene if you want.

**Comment by nicolevasilevsky** [comment]
it's the same workflow for genes, so it sounds like I should expect it to take about 2 hours too. Thanks @twhetzel!

**Comment by twhetzel** [comment]
ok, so it's just a different file that is updated, but all the rest is the same. do you want to run it or should I run it?

**Comment by nicolevasilevsky** [comment]
I can take care of it, thanks though!
