### ISSUE TITLE
MONDO:0005134 Experimental autoimmune encephalomyelitis [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7325]
**Mondo term (ID and Label)**
MONDO:0005134 Experimental autoimmune encephalomyelitis 

**Suggested revision and reasons**
I think this is a non-human animal disease, based on the definition?
"An autoimmune demyelinating disease of the central nervous system that is produced experimentally in _animals_ by the injection of homogenized brain or spinal cord in Freund's adjuvant... Experimental allergic encephalomyelitis (EAE) is used as an animal model for demyelinating diseases ..."

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Discussed on curation call on 2024-03-14 that experimental diseases are within the scope of Mondo so this term should be moved to non-human animal branch as requested.
