### ISSUE TITLE
Primary/monoclonal MCAS [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7326]
**Mondo term (ID and Label)**
Primary mast cell activation syndrome MONDO:0100005

**Reason for deprecation**
Based on the definition and trying to map to UMLS, I think this is conceptually equivalent with the Orphanet term on the MONDO entry below.

The SNOMEDCT definition on UMLS C4267893 is very similar to the orphanet term (also mapped to this CUI)  "A rare haematologic disease characterised by symptoms of mast cell activation in the absence of cutaneous findings, as well as absence of diagnostic criteria of systemic mastocytosis with tryptase levels of less than 20 mg/ml and normal to low burden of mast cells. Bone marrow biopsy reveals the presence of monoclonal mast cells carrying the KIT D816V mutation and/or expressing CD25. Symptoms include recurrent episodes of flushing, headache, hypotension, abdominal cramping, nausea, diarrhoea, cardiac arrhythmia, bronchoconstriction and bleeding diathesis. (SNOMEDCT_US)"  [1260202003]
UMLS has no match for "primary mast cell activation syndrome" but based on the definition and PMID citation, the intent for the Mondo record seems to be MCAS with and underlying molecular pertubation in the KIT gene.

Note also the synonym on  MONDO:0100005 has a typo (it is current "primary _MACS_" but I think it should be _MCAS_ ?)
**Term to be merged with**
MONDO:0033954 monoclonal mast cell activation syndrome
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Agree with the merging of Primary mast cell activation syndrome MONDO:0100005 into MONDO:0033954 monoclonal mast cell activation syndrome.

Also thank you for identifying the typo:  "primary MACS" should be "primary MCAS"! Source: PMID:33261124
