### ISSUE TITLE
Add NCBIGene to Mondo to refer to non-human animal genes

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7327]
Part of #7271

Please add the NCBI Genes to Mondo so they are available for axioms annotations of non-human animal genetic diseases.

I assume adding these genes will require adding a new import (?). 

The list of required NCBIGenes can be found in [this spreadsheet](https://docs.google.com/spreadsheets/d/1aKuKc2yKy4Z1_yzntsOSi-Z-2V_AMKdmcwOZsVpUwtM/edit#gid=1157876657) 
@katiermullen can answer any questions.
Thanks!

**Comment by matentzn** [comment]
@katiermullen I will do this next week!

**Comment by twhetzel** [comment]
@sabrinatoro is this a one time batch request vs. the using [Detailed instructions for adding a new gene](https://mondo.readthedocs.io/en/latest/editors-guide/import-terms-for-logical-axioms/#detailed-instructions-for-adding-a-new-gene)?
