### ISSUE TITLE
HIV is a subClass of cancer?!

### ISSUE THREAD

**Issue by turbomam** [monarch-initiative/mondo#734]
**Mondo term (ID Label)**
MONDO_0022034 `lentivirus infection`

**Bug/Typo/Error description**
MONDO_0022034 `lentivirus infection` is asserted to be a subClass of MONDO_0006485 `uterine carcinosarcoma`

Therefore a query for 

`?s rdfs:subClassOf*  <http://purl.obolibrary.org/obo/MONDO_0004992>`

reports that MONDO_0005109 `HIV infectious disease` is a subClass of MONDO_0004992 `cancer`

**Comment by nicolevasilevsky** [comment]
This superclass assertion comes from MESH:D016180. It does seem like a strange classification. @cmungall could we remove this SubClass Of assertion?

**Comment by nicolevasilevsky** [comment]
I believe this was fixed, I don't see this bug anymore. Please reopen if needed.
