### ISSUE TITLE
Watermelon stomach

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7345]
Watermelon stomach

Gastric antral vascular ectasia (GAVE)

Gastric antral vascular ectasia (GAVE) is a [rare disorder that causes severe acute gastrointestinal bleeding. Also known as watermelon stomach, due to its endoscopic appearance,  this condition is marked by dilated capillaries localized to the antrum that give the appearance of watermelon streaks. The dilated vessels render the affected areas more susceptible to bleeding. Even though the cause is still unknown. The number of cases in the general population is not known but is rare.  It occurs in about 4% of non-variceal upper GI bleedings and 6% of upper GI bleeds in patients with liver cirrhosis. The exact cause is unknown; however, it is often associated with several conditions such as cirrhosis and autoimmune diseases,  systemic sclerosis, and CREST syndrome. GAVE has become a distinct entity with established co-morbid conditions. Treatment can be done with endoscopic coagulation of the lesions. 

https://www.sciencedirect.com/science/article/pii/S2210261222007209
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8110233/
https://www.sages.org/wiki/gastric-antral-vascular-ectasia/

Parent term: Rare hemorrhagic disorder

Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
Hi Gioconda,
This term already exists in Mondo:
MONDO:0006767

Was your intention to request a new term?

Thanks,
Nicole

**Comment by galyea123** [comment]
Hi Nicole!  I am very sorry I was not clear.  I was trying to find out why this one is not tagged as rare in MONDO (I see it in GARD but not in Orphanet) and the literature does support it is rare.

I apologize for the confusion. Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
Sounds good! @sabrinatoro could you please add a rare tag?
