### ISSUE TITLE
Simultanagnosia 

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7348]
Simultanagnosia is really an uncommon symptom of parieto-occipital lobe lesions, even thought there is literature that considers it as a disease. It is not in Orphanet either. This one will be removed from NORD RD list. Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
@sabrinatoro I think the nord_rare tag needs to be removed from this.

**Comment by sabrinatoro** [comment]
According to PMID:[23616758](https://pubmed.ncbi.nlm.nih.gov/23616758), this is a real disease. 
The NORD-rare tag will be removed automatically after refresh of the rare subset.
