### ISSUE TITLE
Orphanet 98819 Familial temporal lobe epilepsy

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7349]
**Mondo term (ID and Label):**
MONDO:0011965 familial temporal lobe epilepsy 2

**Xref that should be fixed (ID and label):**
[Familial temporal lobe epilepsy](https://www.ebi.ac.uk/ols4/ontologies/ordo/classes/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_98819?lang=en)[ORDO](https://www.ebi.ac.uk/ols4/ontologies/ordo/classes/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_98819)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
This Orphanet entry maps to 2 MIM numbers, so I think it has to go up higher in this branch, but I'm not sure where. Maybe MONDO:0005115 ? But this is equivalent to the OMIM PS, which has more than 2 children terms. 

Other Mondo entries to review as part of this remapping: MONDO:0100032 familial temporal lobe epilepsy syndrome (has no x-refs, but in name seems similar to Epilepsy, familial temporal lobe - PS600512 (OMIM)  ? )

**Comment by sabrinatoro** [comment]
I agree that Orphanet:98819 is equivalent to MONDO:0005115 (also based on the definition).


@nicolevasilevsky (I think you worked on Epilepsy), do you think we should merge the following terms? 
'temporal lobe epilepsy' MONDO:0005115
'familial temporal lobe epilepsy syndrome' MONDO:0100032

They both refer to "familial temporal lobe epilepsy". 
Thanks!

**Comment by nicolevasilevsky** [comment]
Hi, Yes, I did work on the epilepsy classification.

Yes, I think it makes sense to merge 'familial temporal lobe epilepsy syndrome' MONDO:0100032 with 'familial temporal lobe epilepsy syndrome' MONDO:0100032.

This term comes from the ILAE classification, but what is interesting, if you click on the genetics page that is linked to this term, it says the gene [DEPDC5](https://www.epilepsydiagnosis.org/aetiology/gene-abnormalities-overview.html#DEPDC5) is implicated but I have the impression this is a potential gene that is implicated, no necessarily _the_ gene. 

https://www.epilepsydiagnosis.org/syndrome/other-familial-temporal-lobe-genetics.html

This gene is not involved with temporal lobe epilepsy in OMIM: https://www.omim.org/entry/614191?search=DEPDC5&highlight=depdc5

The [Gene Reviews page for DEPDC5](https://www.ncbi.nlm.nih.gov/books/NBK385626/) does not suggest definitive involvement:

Familial temporal lobe epilepsy has rarely been described [[Ishida et al 2013](https://www.ncbi.nlm.nih.gov/books/NBK385626/#), [Krenn et al 2020](https://www.ncbi.nlm.nih.gov/books/NBK385626/#)] and includes two subtypes.
- Familial mesial temporal lobe epilepsy (FMTLE) is characterized by focal seizures with ictal mesial temporal lobe symptomatology, including psychic symptoms such as déjà vu and fear or autonomic symptoms such as nausea. Hippocampal sclerosis is commonly observed, as are febrile seizures preceding focal seizures.
- Autosomal dominant epilepsy with auditory features (ADEAF) is characterized by focal seizures with auditory auras and symptoms suggesting lateral temporal onset. It is considered a mild syndrome, with onset in adolescence or adulthood, low seizure frequency, and only rare secondarily generalized seizures.
- It is unclear if ADEAF is part of DEPDC5-related epilepsy. While a [heterozygous](https://www.ncbi.nlm.nih.gov/books/n/gene/glossary/def-item/heterozygous/) DEPDC5 [pathogenic variant](https://www.ncbi.nlm.nih.gov/books/n/gene/glossary/def-item/pathogenic-variant/) can be found in individuals with seizures with auditory features, to date heterozygous DEPDC5 pathogenic variants have not been identified in larger families with the classic ADEAF [phenotype](https://www.ncbi.nlm.nih.gov/books/n/gene/glossary/def-item/phenotype/) [[Bisulli et al 2016](https://www.ncbi.nlm.nih.gov/books/NBK385626/#)].

I think this merger makes  sense,
