### ISSUE TITLE
Change term for MONDO:0009607

### ISSUE THREAD

**Issue by jennygoldstein** [monarch-initiative/mondo#735]
Based on discussion with the ClinGen Aminoacidopathy Gene Curation Panel, please can we request that the main term description for MONDO:0009607 i.e. "brain demyelination due to methionine adenosyltransferase deficiency" is changed to "methionine adenosyltransferase deficiency"? The reason for this request is that most individuals with this enzyme deficiency do not have symptoms, and that other symptoms, in addition to neurological symptoms, can be present (https://omim.org/clinicalSynopsis/250850). Thank you.

**Comment by nicolevasilevsky** [comment]
This sounds fine to me. @cmungall do you have any objections?

**Comment by nicolevasilevsky** [comment]
This would be in line with NCIT, the primary label is:
Methionine Adenosyltransferase Deficiency  NCIT:C123435

and OMIM's primary label is:
METHIONINE ADENOSYLTRANSFERASE I/III DEFICIENCY OMIM:250850

**Comment by nicolevasilevsky** [comment]
@jennygoldstein what is your ORCID?

**Comment by jennygoldstein** [comment]
Hi Nicole,


It's 0000-0002-5655-9589


Thanks for your help,


Jenny


________________________________

**Comment by jennygoldstein** [comment]
HI Nicole,


Thanks for you help with this. Do you know when the change will appear on the MonDO website?


Best wishes,


Jenny


________________________________

**Comment by nicolevasilevsky** [comment]
Hi Jenny, this is pending @cmungall's review and merge on the pull request, and then the changes will be available in the next release, which usually occurs around the first of the month.

**Comment by jennygoldstein** [comment]
OK, great! Thank you Nicole and Chris.


Jenny


________________________________
