### ISSUE TITLE
Add link to Mondo logo

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/mondo#736]
**Mondo term (ID Label)**
N/A

**Bug/Typo/Error description**
This is a kind of "none of the above" type of ticket that's more of a meta-issue with this repo itself: somewhere (probably in the README) we need to have a link to the Mondo logo. I think it's in GitHub somewhere, but can't find it. @nicolevasilevsky just updated it and I was going to suggest to her that she commit the new one but I can't find where it should go. @jmcmurry must know.

**Comment by nlharris** [comment]
I didn't assign @cmungall; he was autoassigned.

**Comment by nicolevasilevsky** [comment]
@nlharris the logos are saved in julie's repo: https://github.com/jmcmurry/closed-illustrations
I just tried to do a PR to this repo but was denied access.

I will add the updated mondo logo on the readme for this repo.

**Comment by nlharris** [comment]
Thanks. Can you also add the link to it to the README, for future reference? (Should it be stored in this repo rather than Julie's private repo?)

**Comment by nicolevasilevsky** [comment]
I created a PR to add the AI file to this repo

**Comment by jmcmurry** [comment]
I fixed tagline in source [here](https://github.com/jmcmurry/closed-illustrations/tree/master/logos/mondo-logos)

**Comment by nicolevasilevsky** [comment]
do we want to add these files to the Mondo repo too?

**Comment by nicolevasilevsky** [comment]
FYI - I updated the [blog post](https://medium.com/@MonarchInit/new-release-of-mondo-disease-ontology-9a48521353e3?postPublishedType=repub) and the [ReadMe](https://github.com/monarch-initiative/mondo)
