### ISSUE TITLE
MONDO:0000417 & MONDO:0010826, early onset/childhood absence epilepsy[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7360]
**Mondo term (ID and Label)**
MONDO:0000417 early onset absence epilepsy

**Reason for deprecation**
Seem to be the same disorder (frequent absence seizures, age of onset from 4-10 yrs)

**Term to be merged with**
MONDO:0010826 childhood absence epilepsy
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
note to self:
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0000417 MONDO:0010826 -o -f obo mondo-edit.obo`
