### ISSUE TITLE
MONDO:0000698 gamma-amino butyric acid metabolism disorder

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7361]
**Mondo term (ID and Label):**
MONDO:0000698 gamma-amino butyric acid metabolism disorder 

**Xref that should be fixed (ID and label):**
Add ORPHA:79175 "[Disorder of gamma-aminobutyric acid metabolism](https://www.orpha.net/en/disease/detail/79175?search=Disorder-of-gamma-aminobutyric-acid-metabolism&mode=name)"

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
This Orpha ID used to be on MONDO:0019224, which was obsoleted as out of scope, but I think if the DOID term still is included in Mondo, the orpha X-ref can be added to this term. (not an exact match, based on additional children for this Mondo term vs. the Orpha classification, but they're very similar)

**Comment by sabrinatoro** [comment]
Adding the orphanet x-ref.
