### ISSUE TITLE
spondyloepiphyseal dysplasia with metatarsal shortening RELABEL

### ISSUE THREAD

**Issue by RyanFWebb** [monarch-initiative/mondo#7375]
**Mondo term (ID and Label):**
Czech dysplasia, metatarsal type
MONDO:0012206

**Suggested new label:**
spondyloepiphyseal dysplasia with metatarsal shortening

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
0009-0003-2127-3550

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
I am requesting this relabel on behalf of ClinGen's Skeletal Disorders GCEP, with the historical term to be included in the description of this skeletal dysplasia.

**Comment by twhetzel** [comment]
This was completed with https://github.com/monarch-initiative/mondo/pull/7388
