### ISSUE TITLE
Ehlers-Danlos syndrome, arthrochalasia type 

### ISSUE THREAD

**Issue by RyanFWebb** [monarch-initiative/mondo#7377]
**Mondo term (ID and Label):**

**Suggested new label:**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**

**Comment by sabrinatoro** [comment]
@RyanFWebb 
Was this issue created by mistake, or do you have a specific request? 
Thank you for updating this issue.

**Comment by RyanFWebb** [comment]
Hi Sabrina, apologies for the duplicate issue. I believe the term was previously arthrochalasis instead of arthrochalasia which is why I went to submit this ticket. Everything seems in order now though. Thanks!
