### ISSUE TITLE
MONDO:0037821 porphyrin metabolism disease[Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7381]
**Mondo term (ID and Label)**
MONDO:0037821 porphyrin metabolism disease

**Suggested revision and reasons**
I am not sure I understand the current structure/relationships in this branch. 
I see inborn porphyrin metabolism disorders, but no acquired forms. Then porphyria has hepatic and inborn forms, but are the hepatic forms of porphyria all acquired? 
SNOMED CT 29094004 (as shown in UMLS) has a number of children that don't seem to be located under this part of Mondo's hierarchy (I am adding a couple of Mondo IDs that are potential matches, but I know this needs more in-depth research)
![image](https://github.com/monarch-initiative/mondo/assets/71083858/407a04e7-ac95-4f09-8fbc-dfd26f376d80)
Disorder of porphyrin metabolism
-[Disorder of bilirubin metabolism](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/80006005) Could this match MONDO:0024431 ?
-[Ferrochelatase deficiency](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/276265003)  MONDO:0008319 ?
-[Heme oxygenase-1 deficiency](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/1230003009)
-[Inherited disorder of porphyrin metabolism](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/403832004)
-[Neonatal jaundice with porphyria](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/206458002)
-[Porphobilinogen deaminase deficiency](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/276263005)
-[Porphyria](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/418470004)
-[Porphyrinopathy](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/371628009)
-[Porphyruria](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/44574006)
-[Uroporphyrinogen decarboxylase deficiency](https://uts.nlm.nih.gov/uts/umls/vocabulary/SNOMEDCT_US/276262000)

I see UMLS has lumped porphyrin & heme metabolism disorders with porphyria, so I will ask if they can review this mapping to better align with SNOMED and we will update MedGen's CUI mappings accordingly.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by twhetzel** [comment]
@kanems we are working on this now and yes, there should be at least an 'acquired porphyria' since 'porphyria cutanea tarda' has both an acquired and inherited form. I will continue reviewing and sort out more details.

A question for you, it looks like MONDO:0022714 'chester porphyria' should be obsoleted and merged with MONDO:0008294 'acute intermittent porphyria'. Do you agree with this change?

**Comment by kanems** [comment]
@twhetzel I would not merge the Chester-type porphyria concept with AIP for a few reasons...
1. OMIM treats it as an "included" concept https://www.omim.org/entry/176000 
2. OMIM's description of the initial family with the disorder indicates it's highly variable phenotype, though molecularly it is a "type" of AIP since the same gene is affected as AIP.
3.  UMLS, MeSH, and SNOMED CT have unique codes for it (UMLS CUI: C0268322| MeSH C536341|  SNOMEDCT_US 84816006 )

**Comment by twhetzel** [comment]
Thanks [kanems](https://github.com/kanems), we did not propose to merge those terms.
