### ISSUE TITLE
Change MONDO:0007727 autosomal dominant familial periodic fever

### ISSUE THREAD

**Issue by nataliedeuitch** [monarch-initiative/mondo#7384]
**Mondo term (ID and Label):**
MONDO:0007727 autosomal dominant familial periodic fever

**Suggested new label:**
TNF receptor-associated periodic fever syndrome (TRAPS)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

https://orcid.org/0000-0002-0146-1162

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**

**Comment by nicolevasilevsky** [comment]
@nataliedeuitch thanks for this request!

In Mondo, we aim to align with the OMIM label as the primary label, so I added this as an exact synonym with a clingen label.

See more information here:
https://mondo.monarchinitiative.org/pages/disease-naming/

Let us know if you have any questions.
