### ISSUE TITLE
MONDO:0007736 HPA 1 Recognition polymorphism, beta-globin-related[Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7391]
**Mondo term (ID and Label)**
[MONDO:0007736](https://monarchinitiative.org/MONDO:0007736) 
HPA 1 Recognition polymorphism, beta-globin-related
**Reason for deprecation**
From the OMIM x-ref: "This entry is included in the database for historical reasons; the beta-related HpaI RFLP was the first to be discovered."
This is describing DNA polymorphism that was found in association with sickle-cell trait, not actually a disease entry from OMIM.

**Suggested term to consider**
MONDO:0011382 sickle cell anemia

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
note to self:
`sh run.sh owltools --use-catalog mondo-edit.obo  --obsolete-replace MONDO:0007736 MONDO:0011382 -o -f obo mondo-edit.obo`
