### ISSUE TITLE
Tag Intellectual developmental disorder with hypotonia, impaired speech, and dysmorphic facies as rare

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7402]
Intellectual developmental disorder with hypotonia, impaired speech, and dysmorphic facies MONDO:0859197

I don't know if this will be under "Relabel term".  I am asking to tag this as rare for NORD.  It is in OMIM.

0000-001-9310-0163

We had a patient request to add this to the NORD rare disease list.
Thank you, Gioconda

**Comment by sabrinatoro** [comment]
Thank you for your request @galyea123 .
We are getting all the "rare disease according to NORD" tag from you. The NORD team is creating a table with all the MONDO IDs that should be rare, and we update MONDO based on this table. Please make sure that this table at NORD is up to date, and this Mondo term will be automatically tagged. 
(you can refer to the email discussion between Sean and Nico. Please let me know if you have any question.)

**Comment by sabrinatoro** [comment]
This will be done automatically via the NORD-rare pipeline.
