### ISSUE TITLE
some eponymous labels that need review of capitalization.  

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#7403]
**Mondo term (ID Label)**

MONDO:0022577 | Billet bear syndrome.  Does this even exist in current diagnoses?  I could not find anything but https://checkorphan.org/disease/billet-bear-syndrome/

MONDO:0022639 | Cantu sanchez-corona Garcia-Cruz syndrome

MONDO:0022739 | Christian demyer franken syndrome

MONDO:0022798 | Cohen lockood wyborney syndrome

MONDO:0022862 | Cormier rustin munnich syndrome

MONDO:0023068 | Engelhard yatziv syndrome

**Bug/Typo/Error description**

**Your nano-attribution (ORCID)**

**Comment by nicolevasilevsky** [comment]
@ericsid are you aware if Billet bear syndrome is still considered a valid disease entity?
https://rarediseases.info.nih.gov/diseases/892/billet-bear-syndrome

thanks!

**Comment by ericsid** [comment]
Cannot find any publication evidence confirming this concept after initial identification from a case report in 1988. 

Do not see an issue with deprecating it as obsolete.
