### ISSUE TITLE
[Merge X-linked spermatogenic failure 1 with Sertoli cell-only syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7409]
X-linked spermatogenic failure 1 MONDO:0056795

You have both terms but they are synonyms.

Sertoli cell-only syndrome

Thank you, Gioconda

**Comment by sabrinatoro** [comment]
IDs:
Sertoli cell-only syndrome - MONDO:0010595
X-linked spermatogenic failure 1 - MONDO:0056795  (keep this term)

Adding these terms on the list of terms to merge. Curators: please review before proceeding.

**Comment by katiermullen** [comment]
Agree with merging Sertoli cell-only syndrome - MONDO:0010595 into X-linked spermatogenic failure 1 - MONDO:0056795 based on duplication and overlapping synonyms.

**Comment by katiermullen** [comment]
@sabrinatoro @galyea123 

Upon closer review of these terms, it appears that 'Sertoli cell-only syndrome' is a grouping term for 'spermatogenic failure, Y-linked, 1' and 'X-linked spermatogenic failure 1'. 

The definition of 'Sertoli cell-only syndrome' in Mondo suggests that are multiple etiologies "Most cases of SCO syndrome are idiopathic (of unknown cause), but causes may include deletions of genetic information on regions of the Y-chromosome, especially on the azoospermia factor (AZF) region of Y-chromosome. Other causes include exposure to chemicals or toxins, history of radiation therapy, and history of severe trauma."

Therefore, I would suggest that we do not merge 'Sertoli cell-only syndrome' with the more specific 'X-linked spermatogenic failure 1'.

**Comment by galyea123** [comment]
Hi!  I do agree that there are multiple etiologies for Sertoli cell-only syndrome and I can see where this can be very confusing.  The synonyms originally are listed in OMIM and this term, X-linked spermatogenic failure 1 is listed in OMIM and GARD (they may have got it from OMIM) which consider it as a synonym: Please see:

https://omim.org/entry/305700 
**305700**
SPERMATOGENIC FAILURE, X-LINKED, 1; SPGFX1
Alternative titles; symbols
SERTOLI CELL-ONLY SYNDROME
GERMINAL CELL APLASIA
DEL CASTILLO SYNDROME

The other one has differences in the synonyms (alternative titles)
https://omim.org/entry/400042: 
**400042**
SPERMATOGENIC FAILURE, Y-LINKED, 1; SPGFY1
Alternative titles; symbols
SERTOLI CELL-ONLY SYNDROME, Y-LINKED
SERTOLI CELL-ONLY SYNDROME, TYPE I
Other entities represented in this entry:
SERTOLI CELL-ONLY SYNDROME, TYPE II, INCLUDED
HYPOSPERMATOGENESIS, INCLUDED
INCOMPLETE SERTOLI CELL-ONLY SYNDROME, INCLUDED

For reviews see: https://emedicine.medscape.com/article/437884-overview and https://www.ncbi.nlm.nih.gov/books/NBK534293/ (note that these papers do not mention the OMIM term)

Also, there is a GR that is relevant to this issue: https://www.ncbi.nlm.nih.gov/books/NBK1339/ "Sertoli cell-only (SCO) syndrome is the term applied to the finding of germinal aplasia in males. It has numerous causes including Y [deletion](https://www.ncbi.nlm.nih.gov/books/n/gene/glossary/def-item/deletion/), exposure to toxic chemotherapy agents or irradiation, mumps orchitis, Down syndrome, Klinefelter syndrome (47,XXY), [congenital adrenal hypoplasia](https://www.ncbi.nlm.nih.gov/books/n/gene/cah/), [isolated](https://www.ncbi.nlm.nih.gov/books/n/gene/glossary/def-item/isolated/) FSH deficiency, and hyperprolactinemia. For each of these, the medical history, the presence of other anomalies or symptoms, or [chromosome](https://www.ncbi.nlm.nih.gov/books/n/gene/glossary/def-item/chromosome/) analysis should differentiate them from Y chromosome infertility. In most cases, the etiology of SCO syndrome is unknown."

That said, I think that it will be good to clarify with OMIM as the term 305700**
SPERMATOGENIC FAILURE, X-LINKED, 1 specifically list "Sertoli cell-only syndrome" as a synonym. 

Thank you, Gioconda Alyea

**Comment by sabrinatoro** [comment]
That sounds good to me. Thank you for looking into this @katiermullen, and thank you for you feedback @galyea123. 

@katiermullen could you please review the synonyms and make sure they are correct, please? Thank you!

**Comment by katiermullen** [comment]
Thank you for the clarification @galyea123! 

I can confirm that the above synonyms are present in Mondo as either exact or related synonyms.

I agree with @galyea123 that we need to clarify with OMIM the synonyms that are associated with the OMIM term 305700**
SPERMATOGENIC FAILURE, X-LINKED, 1. 

@sabrinatoro do we have a medical expert call coming up to discuss this?

Thank you!

**Comment by katiermullen** [comment]
Discussed on medical experts call on October 15, 2024. Plan to merge terms as requested.
