### ISSUE TITLE
Request for new synonym for Roberts-SC phocomelia syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7410]
### Mondo term

Roberts-SC phocomelia syndrome MONDO:0100253

### Synonyms

ESCO2 Spectrum Disorder

### Synonym type

exact

### Additional comments

Gene Review: https://www.ncbi.nlm.nih.gov/books/NBK1153

Note: We have a NORD report too.

Thank you, Gioconda

**Comment by sabrinatoro** [comment]
added
