### ISSUE TITLE
Tag Birt-Hogg-Dube syndrome to NORD rare and to Orphanet

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7411]
You had "obsolete Birt-Hogg-Dube syndrome"  (I also removed this from NORD) and you also have "Birt-Hogg-Dube syndrome" MONDO:0800444 with subtypes 1 and 2. 
Thank you, Gioconda

**Comment by sabrinatoro** [comment]
This will be done automatically via the NORD-rare pipeline.
