### ISSUE TITLE
Obsolete phosphoenolpyruvate carboxykinase deficiency, mitochondrial

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7419]
phosphoenolpyruvate carboxykinase deficiency, mitochondrial MONDO:0009864

Obsoleted in Orphanet

Suggested term to consider Phosphoenolpyruvate carboxykinase deficiency

0000-001-9310-0163

Thank you, Gioconda Alyea

**Comment by sabrinatoro** [comment]
@galyea123 
This term is a real disease (we have cross-ref to other sources) and should not be obsoleted. 
It has been obsoleted in Orphanet because it is not considered rare anymore. This subset should be updated after the next rare subset update.

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________
