### ISSUE TITLE
Installing jq makes whole travis job file prematurely

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#742]
@ShahimEssaid installing jq in the travis job makes it fail altogether, probably because the travis ubuntu distro does not have the correct repositories installed. Is installing jq really necessary? It is often pre-installed.

**Comment by ShahimEssaid** [comment]
Yes, the default Ubuntu distribution for a Travis build does not have a jq
package. I think it is 16.04 if I remember correctly. I changed the build
to use 18.04 by adding:

dist: bionic

to the Travis build. I'm not sure if it is installed by default in the
image used by Travis. I have a:

sudo apt install jq

step to to make sure it's available.

Sent from mobile. Excuse brevity, typos, and the ever helpful
auto-incorrect.

**Comment by matentzn** [comment]
Yeah, looks like this is the right direction! Still, right now, the travis job cant run at all with that `sudo apt install jq`. 

https://travis-ci.org/monarch-initiative/mondo/builds/548814275?utm_source=github_status&utm_medium=notification

Any idea on how to fix this? Thanks a lot Shahim!

**Comment by ShahimEssaid** [comment]
Oh, I see. You meant the setup I had is no longer working. I'll look into
this tomorrow. I'm not sure if they changed their bionic image and the apt
sources are not the same. It should be easy to modify the build to add the
needed source to make it work.

Sent from mobile. Excuse brevity, typos, and the ever helpful
auto-incorrect.
