### ISSUE TITLE
Mondo build exceeds 50 minute hard limit of Travis

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#743]
Travis has a hard limit of 50 minutes for running builds [with the free plan](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts).

There are afaics at least two places where we could save considerable time:

1. Currently we execute the entire battery of QC tests on three different artefacts. Any chance we can reduce this a bit? Maybe restrict ourselves to the sparql checks really necessary at each step?
  - robot verify -i mondo-edit.obo-noimports.owl
  - robot verify -i mondo.owl
  - robot verify -i mondo.obo
2. The reasoner is run twice, which consumes a lot of time:
- [owltools --no-logging --use-catalog  mondo-edit.obo disjoint_sibs.owl imports/equivalencies.owl --merge-support-ontologies --run-reasoner -r elk](https://github.com/monarch-initiative/mondo/blob/7470e1f1f19a1d899bf9ae6ac474c1d2cb051649/src/ontology/Makefile#L739)
- [robot reason](https://github.com/monarch-initiative/mondo/blob/7470e1f1f19a1d899bf9ae6ac474c1d2cb051649/src/ontology/Makefile#L174) -T true -x true -X true -i filtered.owl -r ELK

After the next ROBOT release, we can perhaps squeeze a few more minutes by empying the new [Jena engine](https://github.com/ontodev/robot/pull/475) in ROBOT (as per @cmungall  suggestion).

Lastly, we can, as @ShahimEssaid suggested, retire the Travis job altogether in favour of Jenkins, but I would like to try getting it to run befor that, at least one more time.

**Comment by ShahimEssaid** [comment]
For now I changed the .travis.yml configuration so that Travis doesn't run the "make" test. This allows the overall status to reflect the result of Jenkins. Jenkins build is also fixed and is working now.

**Comment by matentzn** [comment]
@ShahimEssaid  cool! If jenkins runs all the qc now, maybe that is enough? @cmungall?

**Comment by nicolevasilevsky** [comment]
I think this is no longer an issue
closing, please reopen if needed

**Comment by matentzn** [comment]
Hopefully never again :D
