### ISSUE TITLE
Relabel term [pulmonary fibrosis and/or bone marrow failure, telomere-related, 5 to ZCCHC8-related teleomere biology disorder]

### ISSUE THREAD

**Issue by peastc** [monarch-initiative/mondo#7431]
**Mondo term (ID and Label):** MONDO:0032865, pulmonary fibrosis and/or bone marrow failure, telomere-related, 5

**Suggested new label:** ZCCHC8-related teleomere biology disorder

**Your nano-attribution (ORCID)** https://orcid.org/0009-0007-1636-9645

**_Optional_:** This request comes from the ClinGen Interstitial Lung Disease Gene Curation Expert Panel whom upon reviewing the curation of the ZCCHC8 and this disease entity found that a relabeled term was needed to encapsulate the phenotypes that may be recovered in future studies of this gene outside of IPF and bone marrow failure.

**Comment by sabrinatoro** [comment]
I added this disease name as a synonym with the tag "ClinGen label"

**Comment by sabrinatoro** [comment]
To be done via BioPortal KGCL.
@cmungall

**Comment by peastc** [comment]
Hello, I need to request an update here to correct the spelling. I incorrectly submitted it as "ZCCHC8-related tele**o**mere biology disorder" when it should be "ZCCHC8-related telomere biology disorder". Please let me know if this can be updated before the 2024-05 Mondo Release, thank you! @sabrinatoro

**Comment by nlharris** [comment]
Already fixed: https://github.com/monarch-initiative/mondo/pull/7757
