### ISSUE TITLE
Merge cardiomyopathy, dilated, with wooly hair, keratoderma, and tooth agenesis and Erythrokeratodermia-cardiomyopathy syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7435]
cardiomyopathy, dilated, with wooly hair, keratoderma, and tooth agenesis and Erythrokeratodermia-cardiomyopathy syndrome

"Erythrokeratodermia-cardiomyopathy syndrome" MONDO:0018774 (https://www.orpha.net/en/disease/detail/476096) is synonym with  "cardiomyopathy, dilated, with wooly hair, keratoderma, and tooth agenesis" MONDO:0014355 (synonym: "Dilated cardiomyopathy with woolly hair, keratoderma, and tooth agenesis"  as per  OMIM 615821) 

Thank you,

Gioconda Alyea

**Comment by katiermullen** [comment]
Agree with the proposed merge of MONDO:0018774 erythrokeratodermia-cardiomyopathy syndrome into MONDO:0014355 cardiomyopathy, dilated, with wooly hair, keratoderma, and tooth agenesis
