### ISSUE TITLE
add NCBITaxon: Borrelia miyamotoi (NCBITaxon: 47466)

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7453]
In the [last import](https://github.com/monarch-initiative/mondo/pull/7449), Borrelia miyamotoi (NCBITaxon:47466) was added in ncbitaxon_terms.txt, but it was not added to "merged_import.owl", and therefore it is not available to use for axiom annotations. 

I don't know what is special about this NCBITaxon. 
Please add this NCBITaxon to Mondo. 

Follow-up work (for Sabrina): add axiom annotation to MONDO:0958150 based on PMID:36113496 and PMID:36839539

**Comment by twhetzel** [comment]
Was there any kind of logging output from the `sh run.sh make refresh-merged` command?

**Comment by sabrinatoro** [comment]
> Was there any kind of logging output from the sh run.sh make refresh-merged command?
I don't think so (but maybe I don't understand the question). 

It looks like the issue is that NCBITaxon:87882 needs to be added to https://github.com/obophenotype/ncbitaxon/blob/master/subsets/taxon-subset-ids.txt?
I'll do that! 
Thanks!

**Comment by twhetzel** [comment]
Ok, so the new updates to the [docs](https://mondo.readthedocs.io/en/latest/editors-guide/import-terms-for-logical-axioms/#detailed-instructions-for-adding-a-new-ncbi-taxon-identifier) along with the PR being merged in https://github.com/obophenotype/ncbitaxon/blob/master/subsets/taxon-subset-ids.txt resolved the issue?
