### ISSUE TITLE
Hyperinsulinemic Hypoglycemia with Polycystic Kidney Disease

### ISSUE THREAD

**Issue by vgitau** [monarch-initiative/mondo#7457]
### Label

hyperinsulinemic hypoglycemia with polycystic kidney disease

### Synonyms

n/a

### Synonym type

None

### Definition

Hyperinsulinemic Hypoglycemia with Polycystic Kidney Disease. The HPO terms are: HP:0000825, HP:0000113.

### Parent term

MONDO:0005803 hyperinsulinemic hypoglycemia

### Children term(s)

N/A

### Website URL

https://clinicalgenome.org/affiliation/40066/

**Comment by sabrinatoro** [comment]
to do: 
find x-ref and source to support that this is a disease and not a phenotype

**Comment by vgitau** [comment]
A curation has been completed for PMM2 and Hyperinsulinemic Hypoglycemia with Polycystic Kidney Disease. I am writing to inquire on the MONDO ID timeline. Please let us know if you have any questions regarding this curation.

**Comment by nicolevasilevsky** [comment]
@vgitau Thanks for the ticket! Do you have a paper that we can reference for this new term? We will aim to have this term available by the next release.

**Comment by nicolevasilevsky** [comment]
@vgitau this paper looks like a good reference: https://pubmed.ncbi.nlm.nih.gov/28373276/
Do you agree?

Thank you!

**Comment by vgitau** [comment]
@nicolevasilevsky Yes, those are good references. Both articles are cited within the approved evidence summary. I have attached a copy of it here: [PMM2_Evidence Summary (1).docx](https://github.com/monarch-initiative/mondo/files/14983538/PMM2_Evidence.Summary.1.docx)

**Comment by twhetzel** [comment]
@vgitau we are working to refine the definition to add more details. Do you find this definition acceptable:
```
An autosomal recessive disorder caused specifically by the phosphomannomutase 2 gene (PMM2) promoter variant c.-167G>T, either in a homozygous state or in trans with another pathogenic variant in PMM2." 

With source references to: https://clinicalgenome.org/affiliation/40066/, PMID:28373276, PMID:36412659.
```
Please do suggest any changes needed for the definition.

**Comment by vgitau** [comment]
@twhetzel This definition is acceptable! Thank you for working on it!

**Comment by twhetzel** [comment]
Thank you for reviewing @vgitau!
