### ISSUE TITLE
[Merge]MONDO:0002839 leather-bottle stomach into MONDO:0018184 gastric linitis plastica

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7459]
**Mondo term (ID and Label)**
MONDO:0002839 leather-bottle stomach

**Reason for deprecation**
from [expert](https://orcid.org/0009-0001-6494-4831) review [here](https://docs.google.com/spreadsheets/d/1fXgb5tXZA-gtdFBsM3TQDK0cSk5RIxZypgRwF_1knnQ/edit#gid=1819577174)":
- leather-bottle stomach is a synonym for MONDO:0018184 gastric linitis plastic.
- Linitis plastica or leather-bottle stomach is a morphological variant of diffuse stomach cancer. Therefore it is not a general cancer-related condition, but a specific form of gastric adenocarcinoma 

**Term to be merged with**
 MONDO:0018184 gastric linitis plastica

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
created from https://github.com/monarch-initiative/mondo/issues/6533

**Comment by sabrinatoro** [comment]
- From [expert](https://orcid.org/0009-0001-6494-4831): Linitis plastica or leather-bottle stomach is a morphological variant of diffuse stomach cancer. Therefore it is not a general cancer-related condition, but a specific form of gastric adenocarcinoma (synonymous for MONDO:0018184 gastric linitis plastica).
- From [PMID:33085441](https://www.ncbi.nlm.nih.gov/books/NBK563294/):LP, a phenotype of gastric carcinoma, is interchangeably but not accurately termed Borrmann type 4, which occurs in the Asian population. Other interchangeable terms include; Schirrous carcinoma, Lauren carcinoma, or signet cell carcinoma.
- From [here](https://academic.oup.com/qjmed/article/112/3/233/5116103): LP is a diffuse-type carcinoma with a scirrhous stroma, involving the sub-mucosal and muscular layers of the stomach.1 LP is an uncommon and aggressive form of gastric carcinoma with a high rate of metastatic disease at the time of diagnosis, and the diagnosis is delayed owing to sparing of the gastric mucosal layer by the malignancy; (https://doi.org/10.1093/qjmed/hcy229)
- From here (https://www.sciencedirect.com/topics/medicine-and-dentistry/linitis-plastica): Linitis plastica refers to diffuse narrowing and loss of pliability of a gastrointestinal organ. The linitis pattern is most commonly seen in scirrhous carcinoma of the stomach.
- Issue from Chris [here](https://github.com/NCI-Thesaurus/thesaurus-obo-edition/issues/42): NCIT:C3190 is a finding and not a disease, but most people use this term to refer to the disease.

My understanding is that Linitis plastica or leather-bottle stomach (MONDO:0002839) is a phenotype of diffuse gastric adenocarcinomas (though this phenotype does not occur in “all” diffuse gastric adenocarcinoma). (option 1) 
However, many people use this term to refer to a rare form of diffuse gastric adenocarcinoma (ie MONDO:0018184). (option 2)

IF option 1: we should obsolete MONDO:0002839 based on the fact that it is a phenotype
IF option 2: we should merge MONDO:0002839 and MONDO:0018184


(note: if merging, we need to remove the ‘excluded subclass of’)

**Comment by sabrinatoro** [comment]
**on the Mondo expert call 2023-03-28**
 'linitis plastica' is a specific disease and a specific form of gastric adenocarcinoma

**Comment by katiermullen** [comment]
Based on comments, 'linitis plastica' is a specific disease and a specific form of gastric adenocarcinoma, therefore, recommend merging MONDO:0002839 leather-bottle stomach into MONDO:0018184 gastric linitis plastica.

From @sabrinatoro above: (note: if merging, we need to remove the ‘excluded subclass of’)
