### ISSUE TITLE
should PS607634 be connected to multiple MONDO records?

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#746]
**Mondo term (ID Label)**

https://www.ebi.ac.uk/ols/search?q=omimps_607634&ontology=mondo
returns both MONDO:0017198 and MONDO:0020645
**Bug/Typo/Error description**
Given that the term for  https://www.omim.org/phenotypicSeries/PS607634 is Osteopetrosis, autosomal dominant, should OMIMPS_607634 be an XRef only for MONDO:0020645?

**Comment by nicolevasilevsky** [comment]
yes, I believe so. @cmungall please let us know if otherwise
