### ISSUE TITLE
Request for new term hereditary spastic paraplegia 82

### ISSUE THREAD

**Issue by melnel000** [monarch-initiative/mondo#7469]
### Label

hereditary spastic paraplegia 82

### Synonym type

None

### Definition

Any hereditary spastic paraplegia in which the cause of the disease is a mutation in the PCYT2 gene.

References: PMID: [31637422](https://pubmed.ncbi.nlm.nih.gov/31637422), also described in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10497947/.

### Parent term

MONDO:0015150 complex hereditary spastic paraplegia

### ORCID Identifier

https://orcid.org/my-orcid?orcid=0000-0002-9698-992X

### Additional comments

This term exists in OMIM (https://www.omim.org/entry/618770) but I do not find an equivalent MONDO ID.

**Comment by nicolevasilevsky** [comment]
Hi @melnel000, thanks for the ticket. This does exist in Mondo:
MONDO:0032906 spastic paraplegia 82, autosomal recessive

We can add your definition.
