### ISSUE TITLE
[Revise subclass] eye disease and nervous system disease

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#747]
Hi,

MONDO:0005328 eye disease is a descendant of nervous system disorder. While of course an eye contains some components of the nervous system, an eye in its entirety is not a part of the nervous system. And some eye diseases such as conjunctivitis or eye allergy are not nervous system diseases. In EFO3 we have the same issue, inherited from MONDO (we didn't have it in EFO2). It seems to come from MONDO 'disease of visual system' and 'sensory system disease'. UBERON, which we import, seems to have it right (sensory system has part some part of some nervous system). Could you please investigate?

In this particular case, may we please ask to prioritise this ticket, as it's creating problems for our main users. Thank you very much in advance.

Paola and Zoe (cc @zoependlington and @simonjupp for their reference)

**Comment by nicolevasilevsky** [comment]
@cmungall I am not sure of the best way to address this- can you help?

sensory system disorder is asserted to be a subclass of 'nervous system disorder' and this assertion is attributed to DOID:0050155 and EFO:0001058. Could we remove this (and make it an excluded subclass of?)

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky @cmungall 
Is there any update on this, please? Sorry to ask, but this one is a bit of a priority for us, as it affects our main users at the moment. Thanks in advance for looking into it.

**Comment by nicolevasilevsky** [comment]
I created a PR with the proposed edits above. @cmungall let me know if this is not the correct course of action

**Comment by cmungall** [comment]
this is the correct course of action.

you can see it is justified by anatomy:

```
id: UBERON:0001032
name: sensory system
def: "Anatomical system that overlaps the nervous system and is responsible for receiving and processing sensory information." [Wikipedia:Sensory_system]
...
relationship: overlaps UBERON:0001016 ! nervous system
relationship: part_of UBERON:0004456 ! entire sense organ system

```

**Comment by nicolevasilevsky** [comment]
Cool, thanks @cmungall!
