### ISSUE TITLE
create a simplified OWL version of mondo

### ISSUE THREAD

**Issue by simonjupp** [monarch-initiative/mondo#748]
Would it be possible to get a slightly simplified OWL version of Mondo that excludes the equivalences to the other disease ontologies, but preserves cross-bridging axioms to the other non-disease ontologies? 

Querying the closure for each term in the current mondo.owl using ELK seems to take forever and is why we don't load this version into OLS (I think BioPortal were having a similar issue). I haven't tested it but I think we might have a better shot indexing with this simplified version, and it would lead to a better representation of Mondo in OLS. 

related to EBISPOT/OLS#229

**Comment by nicolevasilevsky** [comment]
@simonjupp is this still needed?

Sorry for the long delay!

**Comment by nicolevasilevsky** [comment]
I will close this but please reopen if this is still needed. Thanks!
