### ISSUE TITLE
[Obsolete] MONDO:0000866 'hereditary myoglobinuria'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#7483]
**Mondo term (ID and Label)**
MONDO:0000866 'hereditary myoglobinuria'

**Reason for deprecation**
there is a comment:
TODO: cede to HPO

It is a finding in NCIT

**Suggested term to consider**
HP:0002913

**Comment by sabrinatoro** [comment]
I agree. All the x-ref refer to a finding and not to a disease.
