### ISSUE TITLE
updates needed for Mondo website

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#7491]
Some updates are needed:

- [x] https://mondo.monarchinitiative.org/pages/resources/: presentations have not been updated since 2022
- [x] https://mondo.monarchinitiative.org/: summary statistics are from 2022, maybe this should be updated as least yearly?
- [x] https://mondo.monarchinitiative.org/pages/contributors/: Trish and Katie are missing as a contributors
- [x] https://mondo.monarchinitiative.org/pages/disease-naming/: clingen preferred should be clingen label

**Comment by twhetzel** [comment]
Do we have a list and links to Mondo presentations anywhere to pull this information to add to the site?

**Comment by twhetzel** [comment]
The links for existing [presentations](https://mondo.monarchinitiative.org/pages/resources/) is broken. For example "[Standardizing Rare Disease Data Collection: It Takes an (Ontology) Village]" resolves to: https://mondo.monarchinitiative.org/pages/resources/(https://doi.org/10.5281/zenodo.7125341)

How were the links for the presentations set-up and where is the page to edit to add/fix these?

**Comment by nicolevasilevsky** [comment]
@twhetzel I can help answer the questions above (later), I assigned this to myself, I will come back to this asap

**Comment by nicolevasilevsky** [comment]
> For example "Standardizing Rare Disease Data Collection: It Takes an (Ontology) Village" resolves to: https://mondo.monarchinitiative.org/pages/resources/(https://doi.org/10.5281/zenodo.7125341)

this just has a typo, there are an extra set of parentheses

> How were the links for the presentations set-up and where is the page to edit to add/fix these?

the links are created using markdown
The instructions for editing the website are here: [https://mondo.readthedocs.io/en/stable/editors-guide/mondo-website-editing/](https://mondo.readthedocs.io/en/stable/editors-guide/mondo-website-editing/)

> For the Summary statistics on https://mondo.monarchinitiative.org/, how are these generated and where is the page to edit to update the information?

I think @matentzn and I created this table based on the release mentioned above the table, it was manually created.

**Comment by twhetzel** [comment]
I added [links to presentations](https://mondo.monarchinitiative.org/pages/resources/) I found in the gDrive for 2023 and 2024. While some presentations have the same name, the content is a little different for each.

For the stats, I linked to the tagged release page of Mondo. 

@nicolevasilevsky can you review this?

**Comment by nicolevasilevsky** [comment]
Looks good to me @twhetzel!
