### ISSUE TITLE
[IRF6-Related Conditions/IRF6]

### ISSUE THREAD

**Issue by eedoh01** [monarch-initiative/mondo#7493]
**Preferred gene-related syndrome label**
IRF6 Related Conditions 

**Definition**
Van der Woude syndrome, popliteal pterygium syndrome, cleft lip with or without palate, or a spectrum of one or two of those conditions in which the cause of the disease is a mutation in the _IRF6_ gene. 

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMIDs: 12219090, 12920575, 14618417, 19842205, 20184620, 33906476, 20803643, 25691407, 14757865, 18478600, 20803643, 27252970

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
https://clinicalgenome.org/affiliation/40059/

**Comment by eedoh01** [comment]
Hi MONDO Team. I just wanted to check in to see if this term will be released soon?

**Comment by eedoh01** [comment]
Hi MONDO Team. I just wanted to check in to see when this term will be released?

**Comment by eedoh01** [comment]
Hi MONDO Team. I just wanted to check in to see when this term will be released?

**Comment by nicolevasilevsky** [comment]
Hi @eedoh01 - this should be available in the next release at the beginning of August.

Thanks! 🌞
