### ISSUE TITLE
Mondo RPPR stats Phenomics First

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#7496]
From 2023-06-01 to 2024-05-31

| Event | Total | Internal | Internal (%) | External | External (%) |
| -------- | -------- | -------- | -------- | -------- | -------- |
| Contributors | 96 | 19 |  19.79 | 77 |  80.21 |
| Issues opened | 536 | 184 |  34.33 | 352 |  65.67 |
| Issues closed | 458 | 279 |  60.92 | 179 |  39.08 |
| Pull requests opened | 643 | 449 |  69.83 | 194 |  30.17 |
| Pull requests closed | 628 | 410 |  65.29 | 218 |  34.71 |
| Pull requests merged | 547 | 348 |  63.62 | 199 |  36.38 |
| Comments | 1789 | 1231 |  68.81 | 558 |  31.19 |
| Commits | 621 | 463 |  74.56 | 158 |  25.44 |
| Releases | 8 | 0 |  0.00 | 8 |  100.00 |

Nice facts for report from diff summary:

Changed text definitions: 1863
New / changed synonyms: 7572
New classes: 1390

**Comment by matentzn** [comment]
@sabrinatoro can you fold any fact you find relevant into the rppr?

**Comment by sabrinatoro** [comment]
Thank you @matentzn !!

**Comment by sabrinatoro** [comment]
@matentzn do you know how many terms we obsoleted? and merged?

**Comment by sabrinatoro** [comment]
I guess you know how many merge because they are obsoleted+have the obsoletion reason="merged terms"

**Comment by matentzn** [comment]
260 terms with "terms merged" annotation in the reporting period

**Comment by matentzn** [comment]
actually no

**Comment by sabrinatoro** [comment]
I updated the RPPR with this information. Thank you @matentzn.

**Comment by sabrinatoro** [comment]
Event	Total	Internal	Internal (%)	External	External (%)
Issues opened	536	184	34.33	352	65.67
Issues closed	458	279	60.92	179	39.08

@matentzn My understanding is that 
352 issues were opened by external users and 179 issues were closed by internal users. 
Is that correct??


Alternative: 279 issues opened by internal users were closed, and 179 issues opened by external users were closed

**Comment by sabrinatoro** [comment]
It is enough, I just wanted to make sure that the wording was correct. 
Thank you!
