### ISSUE TITLE
MONDO:0005550 infectious disease has (very) ambiguous synonyms

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#750]
MONDO:0005550 infectious disease has the following synonyms, among others:

root caused disease or disorder 
root infectious disease
root disease or disorder 
ID

The root-based synonyms are ambiguous, think plant root disease.
The ID synonym is a legitimate acronym, but will work wonders in text mining :-D

Could you please disambiguate the root ones (and make them narrow synonyms) and delete ID?
Many thanks in advance!

**Comment by paolaroncaglia** [comment]
Tagging @zoependlington and @simonjupp for their reference.

**Comment by cmungall** [comment]
I'm embarrassed about the 'root's, this is ncbitaxon:1...

**Comment by cmungall** [comment]
For ID, would a BROAD synonym also cause issues? I feel it probably would but I am not sure when the cutoff is.. 3 letter acronyms OK?

**Comment by paolaroncaglia** [comment]
@cmungall @nicolevasilevsky 
Thanks for deleting the root-containing synonyms.
As for "ID" being a broad (instead of exact) synonym of 'infectious disease':
I can only check with our main users if their text mining pipeline uses exact synonyms only, I'll let you know;
In general, 3-letter acronyms as broad synonyms (never exact ;-) ) would be acceptable I think;
With "ID", it's not just the 2-letter-only, it's the complete ambiguity that's very risky... you can't really tell if your users will feed all of your synonyms to a pipeline regardless of their scope, so ID would do more harm than good (how often is it used to stand for 'infectious disease' anyway?).
Anyway, thanks for addressing this!

**Comment by nicolevasilevsky** [comment]
@cmungall in the current PR, I annotated "ID" as an abbreviation and as 'synonym to be removed from public release but maintained in edit version as record of external source' - does that properly address the issue?

**Comment by paolaroncaglia** [comment]
@cmungall @nicolevasilevsky
In reply to Chris' question "For ID, would a BROAD synonym also cause issues?"
Beyond the considerations of ambiguity for a 2-letter acronym, I checked with our users and their text mining pipeline uses labels and exact synonyms only, so they wouldn't pick up "ID" as a broad synonym of 'infectious disease'. I can't speak for other users though who may put all synonyms in the same bag regardless of their scope. Thanks!
