### ISSUE TITLE
WARS2-related combined oxidative phosphorylation defect and neurodevelopmental disorder, mitochondrial, with abnormal movements and lactic acidosis with or without seizures

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7508]
Hi!  I apologize for maybe not being using the right form for the request (currently in Brazil).  I noticed that you have WARS2-related combined oxidative phosphorylation defect and neurodevelopmental disorder, mitochondrial, with abnormal movements and lactic acidosis with or without seizures as separated conditions and they are the same condition (as per Orphanet and OMIM)  I believe the terms should me merged into one and that  WARS2-related combined oxidative phosphorylation defect (as per Orphanet) which should be the primary (preferred term) as per Orphanet and there is also a Gene Review article. Notice other synonyms: Mitochondrial tryptophanyl-tRNA synthetase deficiency as per Orphanet)  and WARS2 deficiency Thank you!  Gioconda 

NOTE: GR notes in nomenclature:  Other designations used in the literature to refer to individuals with phenotypes within the WARS2 deficiency spectrum include:

NEMMLAS (neurodevelopmental disorder, mitochondrial, with abnormal movements and lactic acidosis, with or without seizures) (OMIM 617710)
Childhood-onset parkinsonism-dystonia 3 (OMIM 619738)

**Comment by sabrinatoro** [comment]
@galyea123 
Could you please give more information on your request? 
It looks like MONDO:0060578 (neurodevelopmental disorder, mitochondrial, with abnormal movements and lactic acidosis with or without seizures) is currently equivalent to ORPHA:572798 (Disorder) [WARS2-related combined oxidative phosphorylation defect](https://www.orpha.net/en/disease/detail/572798?name=WARS2-related%20combined%20oxidative%20phosphorylation%20defect&mode=name).

The Orphanet name should be added, but I cannot find the other Mondo term that should be merged. 

Thank you!

**Comment by sabrinatoro** [comment]
@galyea123 please see question above. Thank you!

**Comment by sabrinatoro** [comment]
@galyea123 Thank you for your patience. 
I added the following: 
- exact synonym: Mitochondrial tryptophanyl-tRNA synthetase deficiency
- broad synonyms**
   - WARS2 deficiency
   - WARS2-related disorder

** The reason to make these broad synonyms is the fact that variation in the WARS2 gene can lead to different diseases: Neurodevelopmental disorder, mitochondrial, with abnormal movements and lactic acidosis, with or without seizures (OMIM:617710, MONDO:0060578) and Parkinsonism-dystonia 3, childhood-onset (OMIM:619738, MONDO:0030676)

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________
