### ISSUE TITLE
Exclude non exact xrefs for key resources from release

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#7511]
Xrefs for resources such as OMIM, ORDO and DO should be restricted to exact.

- [ ] @sabrinatoro to provide an exhaustive list of resources (maybe include NCIT, ICD11 foundation?)
- [x] @twhetzel to raise in 1:1 call to implement filter (i will show how)

**Comment by twhetzel** [comment]
Sure, it's on the agenda for 8-Apr-2024.
