### ISSUE TITLE
[Ehlers-Danlos syndrome, kyphoscoliotic and deafness type replacement?

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7527]
I notice 
[Ehlers-Danlos syndrome, kyphoscoliotic and deafness type](https://monarchinitiative.org/MONDO:0013800)
is obsoleted but there does not seem to be a replacement?

What should we use  for  the  fkp14 gene instead?
https://www.omim.org/entry/225400?search=fkbp14&highlight=fkbp14

OMIM has 2 
EHLERS-DANLOS SYNDROME, KYPHOSCOLIOTIC TYPE, 1; EDSKSCL1
https://www.omim.org/entry/225400?search=fkbp14&highlight=fkbp14
and
EHLERS-DANLOS SYNDROME, KYPHOSCOLIOTIC TYPE, 2; EDSKSCL2

bother cause by fkp14

**Comment by ValWood** [comment]
I found
Ehlers-Danlos syndrome, kyphoscoliotic type 1 MONDO:0016002
but there is no type 2 term in Mondo

**Comment by nicolevasilevsky** [comment]
@ValWood type 2 is: MONDO:0013800

I updated the label to match the OMIM label
