### ISSUE TITLE
Proposal: add synonym 'ZCCHC8-related teleomere biology disorder' for pulmonary fibrosis and/or bone marrow failure, telomere-related, 5

### ISSUE THREAD

**Issue by kgcl-change-request** [monarch-initiative/mondo#7528]
## Hey ontobot! apply:

* create exact synonym 'ZCCHC8-related teleomere biology disorder' for MONDO:0032865

---

Comment: This request comes from the ClinGen Interstitial Lung Disease Gene Curation Expert Panel whom upon reviewing the curation of the ZCCHC8 and this disease entity found that a relabeled term was needed to encapsulate the phenotypes that may be recovered in future studies of this gene outside of IPF and bone marrow failure.

This request comes from BioPortal user: sabrinatoro

**Comment by nlharris** [comment]
Should this be "telomere" rather than "teleomere"?
