### ISSUE TITLE
MONDO:0042724 macrocephaly, intellectual disability, short stature, spastic paraplegia and cns malformations[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7546]
**Mondo term (ID and Label)**
MONDO:0042724 macrocephaly, intellectual disability, short stature, spastic paraplegia and cns malformations

**Reason for deprecation**
This term has no active x-refs in mondo, but has an overlapping alt name: Volcke Soekarman syndrome  (attributed to GARD 172, only difference is Hyphen (Volcke-Soekarman ...)) and this GARD ID and matching alt name are on MONDO:0016571

**Term to be merged with**
MONDO:0016571 macrocephaly-short stature-paraplegia syndrome

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by twhetzel** [comment]
Based on the reasons in the original post, I agree MONDO:0042724 'macrocephaly, intellectual disability, short stature, spastic paraplegia and cns malformations' should be merged with MONDO:0016571 'macrocephaly-short stature-paraplegia syndrome'.
