### ISSUE TITLE
MONDO:0022575 biliary hypoplasia[Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7548]
**Mondo term (ID and Label)**
MONDO:0022575 biliary hypoplasia

**Reason for deprecation**
>Editor note: consider making this a finding

**Suggested term to consider**
Perhaps HPO needs to make a term for this instead, as a conceptual complement to Biliary _Hyper_plasia (HP:0006560)
Attn @pnrobinson 
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by yshwetar** [comment]
Biliary Hypoplasia is a phenotype, not a disease. Obsolete added to label and definition, along with has obsolesence reason and is obsolete #8340
