### ISSUE TITLE
MONDO:0015429 & MONDO:0022737 choroideremia hypopituitarism [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7553]
**Mondo term (ID and Label)**
MONDO:0015429 choroideremia-hypopituitarism syndrome

**Reason for deprecation**
The Orphanet ID on this is obsolete, the UMLS 'CN' id is not correct either. Seems like it could be conceptually similar to "choroideremia hypopituitarism" 

However, a Pubmed search of "choroideremia hypopituitarism" returns only 3 hits, one of which is the case report from 1989 PMID: 2624260 
PMID: 18978655 and PMID: 37732399 are also retrieved, but seem to focus on other disease concepts that are phenotypically similar (i.e. Oliver-McFarlane syndrome, MONDO:0010152) . Suggests that this may not be a valid condition in current literature?  Also noting that UMLS metathesaurus reports the SNOMEDCT concept on [715417002](http://identifiers.org/snomedct/715417002) is no longer active (obsoleted atom, looks like maybe retired in 2020?)

**Term to be merged with**
choroideremia hypopituitarism, http://purl.obolibrary.org/obo/MONDO_0022737
OR 
obsolete entirely with a suggested alternative term from Orphanet: "Instead, consider using [Xq21 microdeletion syndrome](https://www.orpha.net/en/disease/detail/1435) " 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment]
This issue should be reviewed in the next release to figure out whether to merge or obsolete

**Comment by katiermullen** [comment]
Questions for medical experts call:
1. Is choroideremia hypopituitarism a valid disease? [See Mondo](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0022737)
2. What is the relation (if any) to trichomegaly-retina pigmentary degeneration-dwarfism syndrome aka Oliver-McFarlane syndrome? [See Mondo](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0010152)
3. This [PMID ](https://pubmed.ncbi.nlm.nih.gov/37732399/)seems to group these 5 diseases: Biallelic pathogenic PNPLA6 variants cause five systemic neurological disorders: spastic paraplegia type 39, Gordon-Holmes, Boucher-Neuhäuser, Laurence-Moon, and Oliver-McFarlane syndromes.
4. Are these disorders distinct from [Xq21 microdeletion syndrome](https://www.orpha.net/en/disease/detail/1435)?

**Comment by sabrinatoro** [comment]
@katiermullen 
I listening to the recording, and I agree that it is all that is needed. 
I will add these obsoletion tags

**Comment by katiermullen** [comment]
Decision in the curation call is to merge MONDO:0015429 choroideremia-hypopituitarism syndrome into choroideremia hypopituitarism, http://purl.obolibrary.org/obo/MONDO_0022737 given that there are xrefs for the disease and users may need this term, thus obsoletion does not seem indicated at this time.
