### ISSUE TITLE
MONDO:0000169 microphthalmia, isolated, with cataract (OMIM phenotypic series) [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7554]
**Mondo term (ID and Label)**
MONDO:0000169 microphthalmia, isolated, with cataract

**Reason for deprecation**
[OMIMPS:156850](https://omim.org/MIM:PS156850) is no longer active in OMIM

**Suggested term to consider**
MONDO:0007995 microphthalmia, isolated, with cataract 1

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
@kanems thank you for submitting this issue! 

MONDO:0000169 microphthalmia, isolated, with cataract will be obsoleted and term to consider will be MONDO:0007995 microphthalmia, isolated, with cataract 1 as you suggest. 

This change will appear in the next Mondo release.
