### ISSUE TITLE
Meier-Gorlin syndrome 7; MGORS7

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#756]
**Mondo term (ID Label)**
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0014894

**Bug/Typo/Error description**
For some reason in the OBO version the label is given as Meier-Gorlin syndrome 7; MGORS7. In OLS it is correct.

**Comment by nicolevasilevsky** [comment]
to do - look into this

**Comment by nicolevasilevsky** [comment]
Looks like this has been resolved
