### ISSUE TITLE
branchial arch abnormalities, choanal atresia, athelia, hearing loss, and hypothyroidism syndrome and choanal atresia-athelia-hypothyroidism-delayed puberty-short stature syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7560]
choanal atresia-athelia-hypothyroidism-delayed puberty-short stature syndrome MONDO:0859345 and branchial arch abnormalities, choanal atresia, athelia, hearing loss, and hypothyroidism syndrome MONDO:0859345

MONDO list these conditions as separate terms but they are the same condition.  

Thank you!

Gioconda Alyea

**Comment by sagehrke** [comment]
Dear @galyea123, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by katiermullen** [comment]
Proceeding as indicated to merge MONDO:0859345 'branchial arch abnormalities, choanal atresia, athelia, hearing loss, and hypothyroidism syndrome' into MONDO:0035651 'choanal atresia-athelia-hypothyroidism-delayed puberty-short stature syndrome'

**Comment by sabrinatoro** [comment]
@kanems,
Please be aware that we have merged these 2 terms. This merge is also supported by the orphanet-omim mapping. (according to orphanet, OMIM:620186 maps to Orphanet:589856)

These terms have currently a different x-refs to MedGen and UMLS:
- MONDO:0859345 = MEDGEN:1824056; UMLS:C5774283
- MONDO:0035651 =  MEDGEN:1830104; UMLS:C5680310

Let us know if you have any questions or concerns. Thank you!

**Comment by kanems** [comment]
I have opened a ticket with UMLS to request the CUI merge (suggested retaining C5680310), since Orphanet asserts they are the same concept. We will clean up the MedGen terms once we process the update from Mondo. thanks!
