### ISSUE TITLE
Restructuring of the alpha thalassemia ontology (MONDO:0011399)

### ISSUE THREAD

**Issue by courtneythaxton** [monarch-initiative/mondo#7561]
We are requesting an update for the alpha thalassemia ontology MONDO:0011399. This request comes from the ClinGen [General Gene curation Expert Panel](https://www.clinicalgenome.org/affiliation/40026/) (GGCEP) and the [Hemoglobinopathy VCEP](https://www.clinicalgenome.org/affiliation/50052/), and the [Disease Naming Advisory Committee (DNAC)](https://www.clinicalgenome.org/working-groups/disease-naming-advisory-committee/). @lindsworls and I helped lead the groups in this discussion and will help with any points you need us to take back to these groups.

This request comes with updates to definitions, new child and grandchild terms, etc. As part of the DNAC, @ahamosh and @mellybelly reviewed this on our last call April 3, 2024 and approved this new architecture, but they are also free to add any updates or concerns.

Here are the suggested edits: 

Current alpha thalassemia Mondo: 
![image](https://github.com/monarch-initiative/mondo/assets/32530005/6238be04-2627-44da-ad72-2cc37bfc5dbf)

New suggestions are outline in the attached word document: [Hemoglobin Mondo_v2.docx](https://github.com/monarch-initiative/mondo/files/14907146/Hemoglobin.Mondo_v2.docx)

@nicolevasilevsky @sabrinatoro please let us know if you need to meet to discuss.

**Comment by nicolevasilevsky** [comment]
Thanks @courtneythaxton, this is so great!

@sabrinatoro I am happy to take this ticket and implement these changes.

I moved your word doc into a google doc [here](https://docs.google.com/document/d/15r4yl36uzBTKUT-3JVXii9zZth49o0GTWbRmMAWiOL0/edit).

This is related to https://github.com/monarch-initiative/mondo/issues/4229, and hopefully this work will address this ticket as well (cc @maglott, @kanems)

@courtneythaxton I do have some questions and I'll add them as comments on the google doc. I'm happy to set up a meeting if that is easier too.

**Comment by nicolevasilevsky** [comment]
@courtneythaxton - here is the new hierarchy

<img width="378" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/c3a7d726-0b88-4861-8ddf-56b33d93a363">

**Comment by courtneythaxton** [comment]
@nicolevasilevsky The hierarchy looks good.
