### ISSUE TITLE
DICER1-related tumor predisposition MONDO:0100216

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7562]
### Mondo term

DICER1-related tumor predisposition

### Synonyms

PPB familial tumor and dysplasia syndrome, PPBFTDS, Pleuropulmonary blastoma familial tumor and dysplasia syndrome, Pleuropulmonary blastoma, DICER1 syndrome

### Synonym type

exact

**Comment by nicolevasilevsky** [comment]
@galyea123 PPB `familial tumor and dysplasia syndrome` and `PPBFTDS` are synonyms for MONDO:0011014 'pleuropulmonary blastoma' according to OMIM: https://omim.org/entry/601200

**Comment by nicolevasilevsky** [comment]
DICER1 syndrome is already a synonym on MONDO:0100216 'DICER1-related tumor predisposition'

**Comment by sabrinatoro** [comment]
@nicolevasilevsky I think this issue might be addressed in https://github.com/monarch-initiative/mondo/pull/7784 and #7051

**Comment by nicolevasilevsky** [comment]
Yeah, I think this can be closed. @galyea123 please let us know if there are any outstanding action items.
