### ISSUE TITLE
Congenital muscular dystrophy with cerebellar involvement 

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7565]
Hi!  In the list provided by MONDO to us (NORD) this term was obsoleted and I did not find it  in MONDO.  I did not find a ticket related to the reason for it to be obsoleted and would like to know as this term is still in Orphanet.

Thank you! Gioconda

**Comment by nicolevasilevsky** [comment]
Hi @galyea123 this term was obsoleted because it is a grouping term that grouped together terms based on phenotypic features, it was obsoleted as part of our mass obsoletion effort.

Is further action needed on our part?

Thanks for your question. :)
