### ISSUE TITLE
Congenital muscular dystrophy without intellectual disability

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7566]
Hi! In the list provided by MONDO to us (NORD) this term was obsoleted and I did not find it in MONDO. I did not find a ticket related to the reason for it to be obsoleted and I would like to know the reason as this term is still in Orphanet.https://www.orpha.net/en/disease/detail/370980?name=congenital%20muscular%20dystrophy%20without%20intellectual%20disability&mode=name

Thank you! 
Best,
Gioconda

**Comment by nicolevasilevsky** [comment]
@galyea123 this term was also obsoleted as part of our mass obsoletion effort to exclude grouping classes that group together terms based on phenotypic features.

Let me know if you have further questions or if further action is needed. Thanks!

**Comment by galyea123** [comment]
Hi Nicole!  I  see that Orphanet consider it to be a disorder in the classification:
ORPHA:370980 https://www.orpha.net/en/disease/detail/370980

Classification level: Disorder

Synonym(s):
CMD without intellectual disability
CMD-no MR
Congenital muscular dystrophy-dystroglycanopathy without intellectual disability

GARD does list it too. See also OMIM:  https://omim.org/entry/613152

 Of note, FKTN variants are responsible for a clinical spectrum ranging from CMD without brain involvement to isolated, dilated cardiomyopathy.

Thank you, Gioconda

**Comment by sabrinatoro** [comment]
might be solved by https://github.com/monarch-initiative/mondo/issues/7693

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________
