### ISSUE TITLE
 syndromic sensorineural deafness due to combined oxidative phosphorylation defect

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7570]
Hi! This term is obsoleted in the list MONDO provided to NORD .  It is active in Orphanet https://www.orpha.net/en/disease/detail/457223.  It is listed in MONDO as per OMIM as  combined oxidative phosphorylation deficiency 34.  Please add   syndromic sensorineural deafness due to combined oxidative phosphorylation defect as a synonym and add tag it to NORD rare. 

Thank you, Gioconda

**Comment by nicolevasilevsky** [comment]
@galyea123 thanks for the tickt.

This is already listed as an exact synonym:
<img width="580" alt="image" src="https://github.com/monarch-initiative/mondo/assets/6722114/f1969575-5886-43bb-8532-eab6141f85ad">

Please let us know if anything else is needed.

Best,
Nicole

**Comment by galyea123** [comment]
Hi Nicole!  Only tagging it to NORD rare.  Thank you! Gioconda
