### ISSUE TITLE
Update Mondo Outreach page with April 5, 2024 recording

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/mondo#7571]
Hi @twhetzel, please update the Mondo Outreach page with the recording from April 5, 2024 with guests from OMIA. The recording is in the drive. 

@sabrinatoro does "Use of Mondo in OMIA" work for the topic of the April 5th outreach call?

**Comment by sabrinatoro** [comment]
I don't remember the title of their presentation. Can we use the following title? 

Online Mendelian Inheritance in Animals (OMIA)

**Comment by twhetzel** [comment]
Link updated.
