### ISSUE TITLE
Request for new term [CTNNB1-related neurodevelopmental disorder and/or vitreoretinopathy]

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#7572]
### Label

CTNNB1-related neurodevelopmental disorder and/or vitreoretinopathy

### Synonym type

None

### Definition

Any neurodevelopmental disorder and/or exudative vitreoretinopathy caused by a monoallelic variant in the CTNNB1 gene. Variants in CTNNB1 are related to a neurodevelopmental condition with a broad spectrum of presentations ranging from isolated vitreoretinopathy to a complex neurodevelopmental disorder with mild to severe intellectual disability, microcephaly, spasticity, autism spectrum disorder, and visual defects, including retinal detachment, and abnormal retinal vascularization.

### Parent term

MONDO:0000508 Syndromic ID and MONDO:0019516 exudative vitreoretinopathy

### Children term(s)

MONDO:0014035 severe intellectual disability-progressive spastic diplegia syndrome; MONDO:0033123 exudative vitreoretinopathy 7

### Website URL

https://clinicalgenome.org/affiliation/40006/

**Comment by nicolevasilevsky** [comment]
@icordovaG I added this as MONDO:0100571 CTNNB1-related neurodevelopmental disorder and/or vitreoretinopathy with the parent 'hereditary disease', as the more specific parents were too specific and did not apply to all of the children terms (for example, 'severe intellectual disability-progressive spastic diplegia syndrome' is not a type of retinal vascular disorder, which is a parent of exudative vitreoretinopathy. All of the children terms inherit all of the properties of the parents in an ontology.)

Thanks!
