### ISSUE TITLE
EN1-related dorsoventral syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7574]
Hi!  EN1-related dorsoventral syndrome was obsoleted in the list MONDO provided to NORD.  I noticed that MONDO, does not list this condition anymore (it is listed in Orphanet) however MONDO does list 
endove syndrome, limb-brain type MONDO:0030979  and endove syndrome, limb-only type MONDO:0030978  

 I would like to tag the two forms to NORD rare (it is currently not in NORD list) and to consider relisting the EN1-related dorsoventral syndrome with the  relevant synonyms: ENDOVE syndrome and ENDOVES.  

Thank you, Gioconda

**Comment by sagehrke** [comment]
Dear @galyea123, 

Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by sabrinatoro** [comment]
might be solved by https://github.com/monarch-initiative/mondo/issues/7693
