### ISSUE TITLE
remove confidence annnotations

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#7575]
we no longer need to keep the confidence annotations, could someone please remove these?
eg: `property_value: confidence "1.246376811594203" xsd:double` on id: MONDO:0000136
thanks!
🌷 

@twhetzel I could work on this with Nico during our 1:1 or if you'd like to take this, it would be great. Please let us know how you prefer to proceed. It's not super urgent but should be quick and easy to do. Thanks!

**Comment by twhetzel** [comment]
@matentzn which mondo file should the confidence annotations be removed from, `mondo-edit.obo` vs. a released version of mondo?

**Comment by nicolevasilevsky** [comment]
perfect, thanks!
