### ISSUE TITLE
facial dysmorphism, hypertrichosis, epilepsy, intellectual/developmental delay, and gingival overgrowth syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7580]
I apologize in advance for these many messages.  In MONDO this term does not list TMEM94-associated congenital heart defect-facial dysmorphism-developmental delay syndrome as a synonym, but it is mention as an exact match.
Is it needed to add it as a synonym?
Thank you!  Gioconda

**Comment by nicolevasilevsky** [comment]
Hi @galyea123 - what is the source where you see `TMEM94-associated congenital heart defect-facial dysmorphism-developmental delay syndrome` is a synonym for `facial dysmorphism, hypertrichosis, epilepsy, intellectual/developmental delay, and gingival overgrowth syndrome`?

It seems like this should be a synonym for MONDO:0032672 `'intellectual developmental disorder with cardiac defects and dysmorphic facies'` - I will add this.

Thanks!

**Comment by galyea123** [comment]
My mistake when writing the term!.  
TMEM94-associated congenital heart defect-facial dysmorphism-developmental delay syndrome is a synonym of "intellectual developmental disorder with cardiac defects and dysmorphic facies". Thank you Nicole!
