### ISSUE TITLE
hereditary angioedema with normal C1inh

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7581]
Hi!  Again I apologize for these many messages. This term was obsoleted in the list MONDO sent to NORD.  The term is active in Orphanet and we want to have it listed at NORD, however it is currently not listed at MONDO.
Thank you!
Gioconda Alyea

**Comment by nicolevasilevsky** [comment]
Hi @galyea123 we can reinstate this term.

Note to self, see: MONDO:0033947 obsolete hereditary angioedema with normal C1Inh
