### ISSUE TITLE
orofaciodigital syndrome 18

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7582]
This term is duplicated for Oral-facial-digital syndrome with short stature and brachymesophalangy.

Thank you, Gioconda Alyea

**Comment by nicolevasilevsky** [comment]
I agree - we should merge MONDO:0034823 'oral-facial-digital syndrome with short stature and brachymesophalangy' into MONDO:0054770 'orofaciodigital syndrome 18'

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________
