### ISSUE TITLE
 retinal ciliopathy due to mutation in the RPGR gene

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7585]
Hi!  This term was obsoleted in MONDO (it is a group of disorders) and it is listed in Orphanet.  I would suggest to add this term  "retinal ciliopathy due to mutation in the RPGR gene" as a synonym for RPGR-related retinopathy MONDO:0100437.

Thank you, Gioconda Alyea

**Comment by nicolevasilevsky** [comment]
Hi @galyea123 

retinal ciliopathy due to mutation in the RPGR gene" is already a synonym for RPGR-related retinopathy MONDO:0100437

Is there anything else that is needed or can this be closed?

Thanks!

**Comment by galyea123** [comment]
No, that is all. Thank you Nicole,
Best, 
Gioconda Alyea
