### ISSUE TITLE
Mondo website updates

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#759]
I would like to suggest the following updates to the Mondo website: 

- [x] Add the logo on the top left (replace The Mondo Ontology) (and make it clickable and link back to the home page)
- [ ] Add Monarch logo on the bottom of the page (can we do something similar as HPO? https://hpo.jax.org/app/)
- [ ] Make the overall font size a bit smaller
- [ ] Add a left hand side bar on the following pages: **Users** (left nav should include Download Mondo, Versions, View Mondo, Report issues/bugs/new term requests, changes, etc, Who uses Mondo), **Resources** (left nav should include Relevant Publications, Relevant Presentations and Ontology Development Tools) 

![image](https://user-images.githubusercontent.com/6722114/60552340-40c9ff80-9ce3-11e9-9e9d-9625ef7c433e.png)

**Comment by ShahimEssaid** [comment]
Regarding font size, the size is automatically reduced if the browser's width is reduced. It's only too large if the window is very wide but I can set the largest size to something smaller if needed.

**Comment by nicolevasilevsky** [comment]
Thanks - I think it would look better if it is a bit smaller

**Comment by nicolevasilevsky** [comment]
Is there a logo without the tag line? it's really small and hard to read

**Comment by nicolevasilevsky** [comment]
(but looks good otherwise - thanks!)

**Comment by nicolevasilevsky** [comment]
@ShahimEssaid are you able to work on this?

**Comment by nicolevasilevsky** [comment]
@jiaola would you be able to work on this?
If not, let's close.

**Comment by nicolevasilevsky** [comment]
Hi @joeflack4. The Monarch UI is different from the Mondo website, I think we should leave this ticket here. No problem to move it to the bottom of your list, there is no rush.

**Comment by nicolevasilevsky** [comment]
the website is going to be merged with the readthedocs site. I think this ticket is out of scope and can be closed.
