### ISSUE TITLE
Request for new term [vertebral artery dissection]

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7593]
### Label

vertebral artery dissection

### Synonym type

None

### Definition

Vertebral artery dissection (VAD) is a rare cause of stroke in the general population; however, represents one of the more common causes of stroke in patients younger than 45 years of age. Its signs and symptoms can be vague, and diagnosis can be elusive. Spontaneous dissections have been reported. However, incidental minor trauma often precipitates this potentially dangerous condition. Often some neck distortion such as chiropractic manipulation, bending of the neck, or blunt trauma causes the dissection. The dissection of the artery may ultimately lead to a stroke which often can be delayed for days following the acute dissection.  Source: https://www.ncbi.nlm.nih.gov/books/NBK441827/

### Parent term

cervical artery dissection

### Website URL

https://www.ncbi.nlm.nih.gov/books/NBK441827/  https://www.cureus.com/articles/51091-vertebral-artery-dissection-a-pain-in-the-neck#!/ https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2588305/   https://emedicine.medscape.com/article/761451-overview

### Additional comments

We received a message from an inquirer who is a stroke survivor asking if we  had this condition listed at NORD.  Currently it is not listed in NORD and it is not in Orphanet either (I will write a ticket to them for their consideration). Orphanet does list familial cervical artery dissection  (note that cervical artery dissection occurs when there's a tear in either a carotid or vertebral artery).  It is a rare condition.
Please let me know your thoughts.  Thank you, Gioconda Alyea

**Comment by sagehrke** [comment]
Dear @galyea123, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
Hi Gioconda,

Thank you for your continued collaboration as we look to improve MONDO.

As stated in your definition for Vertebral Artery Dissection: "Vertebral artery dissection (VAD) is a rare cause of stroke in the general population". VAD is a _cause_ of stroke, and not a disease itself. Further documentation on what are and are not included as disease definitions in MONDO can be found here: https://mondo.readthedocs.io/en/stable/editors-guide/exclusion-reasons/#exclusion-reasons. This would most likely be considered an 'external factor' exclusion reason.

If you have any further questions or comments, feel free to reach out.

Yousif

**Comment by galyea123** [comment]
Hi Yousif!

Thank you for your response.

To my understanding vertebral artery dissection is, in fact, a disease, as it has specific pathogenesis (an expanding hematoma in the vessel wall is the root lesion in vertebral artery dissection) natural history, clinical features, and treatment. It is not just a cause of stroke.  I believe the following article may be helpful to clarify my points. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2588305/ 

In addition, please note that there is an ICD-10 code I77. 74 for Dissection of vertebral artery is a medical classification as listed by WHO under the range - Diseases of the circulatory system.

Of note, a disorder in the Orphanet database can be a disease, a malformation syndrome, a clinical syndrome, a morphological or a biological anomaly or a particular clinical situation (in the course of a disorder). We also sometimes include consequences of a medical procedure (ex: Scarring in glaucoma filtration surgical procedures).


Thank you!

Best,

Gioconda Alyea

**Comment by galyea123** [comment]
Hi!  I was looking in 7976 but I am not sure if you deciding on adding the term?  Thank you, Gioconda

**Comment by yshwetar** [comment]
Hi Gioconda!

Yes, we will be adding it to our 2024-08 release.

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________
