### ISSUE TITLE
sudden cardiac failure, infantile

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7596]
The term sudden cardiac failure, infantile MONDO:0014973 is not tagged to NORD rare (only to OMIM). We received an inquiry from a patient asking to include this term in our list (I found it in our list).  Please let me know if you can tag this to NORD.  Thank you! Gioconda

**Comment by sagehrke** [comment]
Dear @galyea123, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by sabrinatoro** [comment]
@galyea123 
Please add this term to the NORD rare disease list that we import into Mondo, and it will be automatically tagged with nord-rare. Thank you!

**Comment by galyea123** [comment]
Done! Thank you! Gioconda
