### ISSUE TITLE
Intellectual developmental disorder, autosomal dominant 42 and Global developmental delay-neuro-ophthalmological abnormalities-seizures-intellectual disability syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7597]
MONDO list the following terms as separate disorders but they are the same condition:

Global developmental delay-neuro-ophthalmological abnormalities-seizures-intellectual disability syndrome MONDO:0024252
Intellectual developmental disorder, autosomal dominant 42 MONDO:0014855

We may want to merge the terms and add the corresponding synonyms.

Of note, in NORD we have a report about this condition under the name "GNB1-Related Disorder" 

Thank you! Gioconda

**Comment by sagehrke** [comment]
Dear @galyea123, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by katiermullen** [comment]
@galyea123 Thank you for this request!

Based on review of these terms, it appears that they represent the same condition. Therefore, we will merge MONDO:0024252 'global developmental delay-neuro-ophthalmological abnormalities-seizures-intellectual disability syndrome' into MONDO:0014855 'intellectual disability, autosomal dominant 42.' 

This change will appear in the next release of Mondo.

**Comment by sabrinatoro** [comment]
- I added the synonym "GNB1-Related Disorder". However, since a variation in the GNB1 is associated with multiple different diseases, I made this synonym "broad"

- @kanems please be aware that we merged the following 2 Mondo terms. Each of these terms maps to different MedGen and UMLS terms:
MONDO:0024252 (obsoleted, merged to the other Mondo term) = MEDGEN:1798905 ; UMLS:C5567482
MONDO:0014855 (kept) = MEDGEN:934741 ; UMLS:C5567482

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________
