### ISSUE TITLE
MONDO:0009253 Fryns syndrome alt name

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7600]
**Mondo term (ID Label)**
MONDO:0009253 Fryns syndrome

**Bug/Typo/Error description**
The synonym Moerman Van den Berghe Fryns syndrome is attributed to GARD
`name" : "Moerman Van den Berghe Fryns syndrome",
    "scope" : "hasRelatedSynonym",
    "type" : null,
    "xrefs" : [ {
      "database" : "GARD",
      "id" : "0003699",
      "description" : null,
      "url" : "https://rarediseases.info.nih.gov/diseases/0003699/index"`
But I do not see this synonym on GARD's site: https://rarediseases.info.nih.gov/diseases/3699/fryns-syndrome 

Also note that this related syn is conflicting with MONDO:0015424's alt name of Moerman-Vandenberghe-Fryns syndrome, but this entire Mondo record seems like it could/should be retired anyways (more to come from MedGen team along these lines, we have a number of Mondo IDs that we think should be obsoleted because the sources are obsoleted)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by twhetzel** [comment]
@kanems now that some time has passed, MONDO:0015424 'lethal chondrodysplasia, Moerman type' is able to be obsoleted and I will make that change.

For MONDO:0009253 'Fryns syndrome', I am not sure why the synonym 'Moerman Van den Berghe Fryns syndrome' is attributed to GARD, but not on their web site. I am checking on this. However, I do see in UMLS that [Fryns syndrome](https://uts.nlm.nih.gov/uts/umls/concept/C0220730) does include this term from MeSH https://uts.nlm.nih.gov/uts/umls/concept/C0220730 and can change the attribution to MeSH.
