### ISSUE TITLE
MONDO:0022413 Albright-like syndrome

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7603]
MONDO:0022413 Albright-like syndrome
Points to a link in GARD that is no longer active. 
There is no disease definition and very little information on OLS about phenotypes... I note
Subclass of  ... 
[disease shares features of](https://www.ebi.ac.uk/ols4/ontologies/mondo/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252Fmondo%2523disease_shares_features_of?lang=en)some[polyostotic fibrous dysplasia](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0008274?lang=en)

And then string similarity suggests maybe this could be merged with MONDO:0010886 2q37 microdeletion syndrome (SYN from OMIM of "Albright hereditary osteodystrophy-like syndrome") 
Or maybe obsolete this Albright-like syndrome concept with a suggested alternate of the 2q37 microdeletion? I am not sure, but I would appreciate if there could be some review of MONDO:0022413 . Right now MedGen can't map it to any CUIs in UMLS or other sources, so we're not displaying it publicly.

**Comment by sagehrke** [comment]
Dear @kanems, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by twhetzel** [comment]
NOTE: this term is on the obsoletion candidate list following this issue: https://github.com/monarch-initiative/mondo/issues/7700
