### ISSUE TITLE
MONDO:0022858   continuous spike-wave during slow sleep syndrome [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7606]
**Mondo term (ID and Label)**
MONDO:0022858 continuous spike-wave during slow sleep syndrome

**Reason for deprecation**
GARD (https://rarediseases.info.nih.gov/diseases/1513/continuous-spike-wave-during-slow-sleep-syndrome ) points to the Orphanet (https://www.orpha.net/en/disease/detail/725) entry 

**Term to be merged with**
MONDO:0019123 continuous spikes and waves during sleep

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by twhetzel** [comment]
I agree the terms should be merged based on the reasons in the original post.
