### ISSUE TITLE
MONDO:0022869 & MONDO:0001389 congenital coronary artery anomaly/malformation [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7607]
**Mondo term (ID and Label)**
MONDO:0022869 coronary arteries congenital malformation

**Reason for deprecation**
Based on sources in UMLS, these terms are synonyms. 
(also it may be worth re-adding the X-ref to ORPHA:1081, since GARD still points to their page and it seems this concept will remain in Mondo)

**Term to be merged with**
 congenital coronary artery anomaly MONDO:0001389

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
