### ISSUE TITLE
split term: acquired hyperprolactinemia MONDO:0024305

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7610]
**Term to split:**
acquired hyperprolactinemia MONDO:0024305

**Name for new terms:** Note - when a term should be split, there should be 2+ new terms. Please list the new labels below. 
acquired hyperprolactinemia (DOID x-ref)
Chiari-Frommel syndrome (MeSH D002640;  UMLS -  C0008043; SNOMEDCT -85039006) 

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonyms that end in "1", "2", etc. should move to subclass.
(see above for X-refs for Chiari-Frommel syndrome)
I think that MeSH D006966 is a better match to MONDO:0005804 rather than this 'acquired' form. 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by katiermullen** [comment]
@kanems Thank you for requesting this split term. 

I see that the term MONDO:0024305 acquired hyperprolactinemia has exact synonym Chiari-Frommel syndrome

And also MONDO:0043226 postpartum amenorrhea-galactorrhea syndrome has related synonym Chiari-Frommel syndrome with db-xrefs ([SCTID:85039006](http://snomed.info/id/85039006) and [MESH:D002640](http://id.nlm.nih.gov/mesh/D002640). This term is classified under familial hyperprolactinemia which may not be correct?

The definition of Chiari-Frommel syndrome from MeSH "A POSTPARTUM condition consists of persistent lactation (GALACTORRHEA) and AMENORRHEA in patients not BREAST FEEDING." MeSH D002640

Would it make sense to move MONDO:0043226 'postpartum amenorrhea-galactorrhea syndrome' to a child of 'acquired hyperprolactinemia', use the definition from MeSH, and remove the synonym 'Chiari-Frommel syndrome' from 'acquired hyperprolactinemia'?

Side note: Is MONDO:0023209 'galactorrhoea-hyperprolactinaemia' a 'familial hyperprolactinemia'?

**Comment by katiermullen** [comment]
Discussed on curation call on 30 May 2024. 

Plan to move: galactorrhoea-hyperprolactinaemia and postpartum amenorrhea-galactorrhea syndrome as children of acquired hyperprolactinaemia. They are incorrectly inferred as as familial due to an old OMIM x-ref stating that galactorrhea is inherited. Once this x-ref is removed, the terms should be classified correctly. 

Plan to keep galactorrhoea-hyperprolactinaemia for now even though it may be more of a combination phenotype rather than a distinct disease. Will use the UMLS CUI C2930894 as an exact match as stated above.
