### ISSUE TITLE
MONDO:0100016 early-onset generalized dystonia [Revise text def]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7611]
**Mondo term (ID and Label)**
MONDO:0100016 early-onset generalized dystonia

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
There are currently synonyms that seem more like definitions on this term:
"A generalis[z]ed isolated dystonia characteris[z]ed by early-onset, which may be clinically indistinguishable from DYT-TOR1A and may be the most common cause of early-onset generalis[z]ed dystonia, at least outside the Askenazi Jewish population."
 
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

Note that there is a UMLS concept that is 'similar' to this preferred name, but I am not sure that 'early' and 'childhood' should be equated in this situation: "Childhood Onset Dystonias" (UMLS CUI: C0752202) includes one of the many different concepts on https://id.nlm.nih.gov/mesh/D020821.html . Because of the lack of clarity in the scope of this MeSH term, I am not advocating for it as an X-ref, just trying to connect the dots on the various sources of information we're trying to reconcile in MedGen.  I cannot find a better match in UMLS for this "early-onset generalized dystonia."

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
_There a synonyms that of early-onset generalized dystonia that seem more like definitions:_

I agree with the collaborator that these synonyms seem like definitions.

_Linking early-onset generalized dystonia with UMLS concept childhood onset dystonia:_

According to the following publication (PMID:20301665), "Onset ranging from age four to 64 years has been reported with the vast majority beginning before age 26 years". The average age is far outside of childhood. For now, I recommend we do not X-ref this term unless a clinical expert chimes.
