### ISSUE TITLE
MONDO:0011836 & MONDO:0006465 Thyroid gland oncocytic follicular carcinoma [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7613]
**Mondo term (ID and Label)**
MONDO:0006465 Thyroid gland oncocytic follicular carcinoma

**Reason for deprecation**
Many overlapping synonyms between these 2 terms. 
NCI (http://purl.obolibrary.org/obo/NCIT_C4946) has
Legacy Concept Name: Thyroid_Hurthle_Cell_Carcinoma
(Up to you all which sources' name you will use as Mondo's primary name)

**Term to be merged with**
thyroid Hurthle cell carcinoma  MONDO:0011836

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by twhetzel** [comment]
I agree these terms should be merged based on the original post highlighting the overlap in synonyms.
