### ISSUE TITLE
MONDO:0000884 & MONDO:0013296 myeloid neoplasm associated with FGFR1 rearrangement [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7614]
**Mondo term (ID and Label)**
MONDO:0000884 myeloid and lymphoid neoplasms associated with FGFR1 abnormalities

**Reason**
Exact match on one of these is same name as other
[Myeloid/lymphoid neoplasm associated with FGFR1 rearrangement](https://www.ebi.ac.uk/ols4/ontologies/ordo/classes/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_168953?lang=en)[ORDO](https://www.ebi.ac.uk/ols4/ontologies/ordo/classes/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_168953)

[DOID definition](http://purl.obolibrary.org/obo/DOID_0080167) is A myeloid and lymphoid neoplasms with eosinophilia and abnormalities of PDGFRA, PDGFRB, and FGFR1 that is characterized by the rearrangement of the FGFR1 gene, resulting in translocations with an 8p11 breakpoint. (80167) that matches syns/ molecular etiology on the other term.
**term to merge with **
MONDO:0013296 myeloid neoplasm associated with FGFR1 rearrangement

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by katiermullen** [comment]
@kanems Thank you for this request!

For the reasons that you state, MONDO:0000884 myeloid and lymphoid neoplasms associated with FGFR1 abnormalities will be merged into MONDO:0013296 myeloid neoplasm associated with FGFR1 rearrangement.

This change will appear in the next release of Mondo.
