### ISSUE TITLE
CEBALID syndrome

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7615]
Hi!  This is only a brief message asking to tag this to NORD rare.   We have a report with the name MN1 C-Terminal Truncation Syndrome.  Thank you! Gioconda Alyea

**Comment by sagehrke** [comment]
Dear @galyea123,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by sabrinatoro** [comment]
@galyea123
Please add this term to the NORD rare disease list that we import into Mondo, and it will be automatically tagged with nord-rare. Thank you!
