### ISSUE TITLE
[Revise subclass] autosomal dominant nonsyndromic hearing loss (MONDO:0019587)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7621]
**Mondo term (ID and Label)**

I noticed that
autosomal dominant nonsyndromic hearing loss (MONDO:0019587)
seems to have a logical inconsistency .

<img width="1105" alt="Screenshot 2024-04-21 at 15 51 40" src="https://github.com/monarch-initiative/mondo/assets/7359272/e3923f55-b7d0-46dd-990d-7d9d24a6a804">

It is broader than its 2 parents
prelingual non-syndromic genetic hearing loss
postlingual non-syndromic genetic hearing loss
(if these are both autosomal, they should be subclasses, not superclasses)

The logical conclusion of this organization is that  we have exact overlap between annotations:

<img width="993" alt="Screenshot 2024-04-21 at 15 53 14" src="https://github.com/monarch-initiative/mondo/assets/7359272/578dba1c-09fd-4cb6-a347-f69403b56b71">

where I would expect them to be mutually exclusive?

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
Hi @ValWood,

We agree with your finding above and have removed all instances where the concept is a child of both pre and post-lingual non-syndromic genetic hearing loss.

Thank you,

Yousif

**Comment by sabrinatoro** [comment]
We also made "prelingual non-syndromic genetic hearing loss" and "postlingual non-syndromic genetic hearing loss" Mondo terms disjointed as we think that a disease cannot be both pre and post lingual non-syndromic hearing loss at the same time. 
If (or when) we find an example of a disease can can be both, we will remove the disjointness.
