### ISSUE TITLE
[Revise subclass] microcephaly with or without chorioretinopathy, lymphedema, or intellectual disability (MONDO:0007918)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7622]
**Mondo term (ID and Label)**

microcephaly with or without chorioretinopathy, lymphedema, or intellectual disability (MONDO:0007918)
does not have the superclass
microcephaly (MONDO:0001149)

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
Hi @ValWood,

We have added microcephaly as a superclass to microcephaly with or without chorioretinopathy, lymphedema, or intellectual disability.

Thank you,

Yousif
