### ISSUE TITLE
[Revise subclass] familial Alzheimer disease (MONDO:0100087) missing superclass 

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7623]
**Mondo term (ID and Label)**

familial Alzheimer disease (MONDO:0100087)
should have the superclass
"inherited neurodegenerative disorder" (MONDO:0024237

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
Hi @ValWood,

We have added inherited neurodegenerative disorder as a superclass to familial Alzheimer disease, along with the PMID:9804539 as evidence for this mapping.

Thank you,

Yousif
