### ISSUE TITLE
[Revise subclass] spinal muscular atrophy (MONDO:0001516) missing superclass

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7624]
**Mondo term (ID and Label)**

spinal muscular atrophy (MONDO:0001516)

**Suggested revision and reasons**

should have inherited inherited neurodegenerative disorder" ([MONDO:0024237](https://www.pombase.org/term/MONDO:0024237)))
superclass

The definitions says 
Spinal muscular atrophy (SMA) refers to a group of **inherited conditions** that affect the muscles

and they have the superclass
neurodegenerative disease (MONDO:0005559)

(might be better to define spinal muscular atrophy as
A motor neurone disease  that affects the muscles...

and define motor neurone disorder as a "neurological disease" ( to follow the genus/differentia) 
if the existing parents are correct (they do seem to be)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
