### ISSUE TITLE
GARD xref for CAMFAK is wrong

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#763]
See also #89 

We have two xrefs for COFS - one is for 

https://rarediseases.info.nih.gov/diseases/1060/cataract-microcephaly-failure-to-thrive-kyphoscoliosis

other for 

https://rarediseases.info.nih.gov/diseases/6027/cofs-syndrome

**Comment by cmungall** [comment]
@GARDInfo it seems the page for CAMFAK has disappeared? https://rarediseases.info.nih.gov/diseases/1060/cataract-microcephaly-failure-to-thrive-kyphoscoliosis

**Comment by cmungall** [comment]
Note that OMIM does not place CAMFAK in the COFS PS:

https://omim.org/phenotypicSeries/PS214150

https://omim.org/entry/212540

@nicolevasilevsky can you investigate? Should CAMFAK be its own disease? cc @pnrobinson 

Note that the most recent pub on CAMFAK is last century, the omim entry doesn't seem to have undergone major edits since 1986? I am inclined to leave as an explicit obsolete entry in MONDO

**Comment by nicolevasilevsky** [comment]
@ShahimEssaid and I looked at this and we are unclear. 

This article from 2004 lists a differential diagnosis of CAMFAK, syndrome involving cataract, arthrogryposis, microcephaly, and kyphoscoliosis (CAMAK) and COFS, which sound they are distinct diseases: 
https://www.ncbi.nlm.nih.gov/pubmed/15216542

Mondo has all three of these as synonyms on the same class.

We are leaning towards towards new classes.

**Comment by nicolevasilevsky** [comment]
looks like this class has been obsoleted. Closing this ticket.
MONDO_0020742
