### ISSUE TITLE
[Revise subclass] "spondyloepimetaphyseal dysplasia, Isidor-Toutain type" (MONDO:0032885)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7633]
**Mondo term (ID and Label)**

"spondyloepimetaphyseal dysplasia, Isidor-Toutain type" ([MONDO:0032885](https://www.pombase.org/term/MONDO:0032885))

**Suggested revision and reasons**

add superclass
 spondyloepimetaphyseal dysplasia (MONDO:0100510)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
Hi @ValWood,

We have added spondyloepimetaphyseal dysplasia as a superclass to spondyloepimetaphyseal dysplasia, Isidor-Toutain type, along with the PMID:23956136 as evidence for this mapping.

Thank you,

Yousif
