### ISSUE TITLE
[Revise subclass] congenital myasthenic syndrome 12 (MONDO:0012518)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7637]
**Mondo term (ID and Label)**

congenital myasthenic syndrome 12 (MONDO:0012518)
Any congenital myasthenic syndromes with glycosylation defect in which the cause of the disease is a mutation in the GFPT1 gene.

should be is_a
is_a
"disorder of glycosylation" (MONDO:0024322)

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
