### ISSUE TITLE
[Revise subclass] MONDO:0014321 premature ovarian failure 8

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7638]
**Mondo term (ID and Label)**

should 
MONDO:0014321 premature ovarian failure 8
be is_a 
MONDO:0005047 infertility disorder

it seems so?

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
_Request that MONDO:0014321 premature ovarian failure 8 be defined as a subclass of MONDO:0005047 infertility disorder._

"Primary ovarian insufficiency (POI) is a disease spectrum **that not only affects female fertility** but also contributes to morbidity and mortality associated with the long-term withdrawal of estrogen. This disease spectrum has previously been referred to as **premature ovarian failure**." (PMID:36943992, https://pubmed.ncbi.nlm.nih.gov/36943992)

- As suggested by the collaborator, **forms of Premature Ovarian Failure should be a subclass of infertility disorder**.
- Additionally, **Primary Ovarian Insufficiency should be included as a broad synonym for all forms of Premature Ovarian Failure** (PMID:17970776, https://pubmed.ncbi.nlm.nih.gov/17970776/)
