### ISSUE TITLE
Update Mondo Outreach page with May 3, 2024 presenter

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/mondo#7642]
Please add Bryan Laraway ([N3C](https://covid.cd2h.org/)] as the presenter for May 3, 2024 on the Mondo Outreach schedule page https://mondo.monarchinitiative.org/pages/workshop/#outreach
Topic can be **Use of Mondo in the National Covid Cohort Collaborative**

**Comment by twhetzel** [comment]
Done
