### ISSUE TITLE
[NTR] Noxacusis

### ISSUE THREAD

**Issue by A-84** [monarch-initiative/mondo#7643]
**Preferred gene-related syndrome label**
Noxacusis or Pain Hyperacusis

**Synonyms**
Noxacusis
Pain Hyperacusis
Noise-Induced Pain
Auditory Nociception

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Hyperacusis

**Definition**
Noxacusis/Pain Hyperacusis is characterized by individuals who experience otalgia or pain (e.g., dull ache, burning, sharp, stabbing pain and throbbing pain) in response to everyday sounds. This differs clinically from those whose primary symptom is the perception of everyday sounds as excessively loud (termed loudness hyperacusis).

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
https://pubmed.ncbi.nlm.nih.gov/25104073/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4664349/
Chang Liu, Ph.D: https://liu.med.jhmi.edu/people/chang-liu-ph-d/
Elisabeth B. Glowatzki, Ph.D: https://www.hopkinsmedicine.org/profiles/details/elisabeth-glowatzki
Paul Fuchs, Ph.D.: https://www.hopkinsmedicine.org/profiles/details/paul-fuchs (note that Dr. Fuchs priority research interest involves hyperacusis)

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by A-84** [comment]
Additional material for definition source: https://pubmed.ncbi.nlm.nih.gov/25104073/

**Comment by nicolevasilevsky** [comment]
@A-84 I added this as MONDO:0800459 noxacusis

**Comment by A-84** [comment]
@nicolevasilevsky Thank you for the prompt response. Forgive me if this is a silly question, but does this mean that Noxacusis has officially been added to MONDO's ontology? Thank you.

**Comment by nicolevasilevsky** [comment]
It has been added and it will be available in the next release. (Not a silly question, thanks for asking!)

**Comment by A-84** [comment]
@nicolevasilevsky thanks so much!
