### ISSUE TITLE
Request for new term [Dyneinopathy]

### ISSUE THREAD

**Issue by icordovaG** [monarch-initiative/mondo#7652]
### Label

Dyneinopathy

### Synonym type

None

### Definition

Dyneinopathy is a spectrum of disease related to monoallelic variants in DYNC1H1 and characterized by variable neuromuscular and/or neurodevelopmental presentations. While not absolute, there appear to be genotype-phenotype correlations based on the location of the variant. Patients with variants in the stem domain of DYNC1H1 have been reported with a predominantly neuromuscular presentation, including congenital myopathy, spinal muscular atrophy, Charcot-Marie-Tooth (CMT), and less frequently, intellectual disability and autism. Patients with variants in the motor domain predominantly present with neurodevelopmental presentations including intellectual disability, seizures, malformations of cortical development (abnormal brain MRI findings such as pachygyria, heterotopias, enlarged ventricles, hypoplasia of CC, brain stem, cerebellum), autism, and less frequently, neuromuscular phenotypes (PMIDs: 33991169, 32656949 32788638; GeneReviews: [https://www.ncbi.nlm.nih.gov/books/NBK1116/?term=dync1h1]. 

### Parent term

MONDO:0000508 Syndromic ID and MONDO:0019516 exudative vitreoretinopathy

### Children term(s)

Charcot-Marie-Tooth disease axonal type 2O MONDO:0013644; intellectual disability, autosomal dominant 13 MONDO:0013805

### ORCID Identifier

https://clinicalgenome.org/affiliation/40006/

### Website URL

https://clinicalgenome.org/affiliation/40006/

### Additional comments

In OMIM, DYNC1H1 is related to three children terms, two of which have exact mapping to MONDO terms (listed above in children terms). The third, spinal muscular atrophy (MONDO:0001516), is representing the OMIM term 'Spinal muscular atrophy, lower extremity-predominant 1, AD' but is not the exact same. Could you also create the more specific term 'Spinal muscular atrophy, lower extremity-predominant 1, AD' and add that as a child for this term? We do not want this new term to be a parent of the more general SMA MONDO term. Please let me know if you need anything from me. 

clinicalgenome.org/affiliation/40006/ and https://clinicalgenome.org/affiliation/40063/ 
@ErinRiggs

**Comment by sagehrke** [comment]
Dear @icordovaG,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
Thank you @ErinRiggs for your term request submission! I have submitted a pull-request that it be added.

To address your comment about 'Spinal muscular atrophy, lower extremity-predominant 1, AD', it would be best if you submitted another term request for 'Spinal muscular atrophy, lower extremity-predominant 1, AD', similar to the submission above. We can then incorporate it as a subclass of Dyneinopathy.

**Comment by yshwetar** [comment]
Hi @ErinRiggs

Thank you for your continued collaboration as we look to improve MONDO.

For your recommended new term 'Spinal muscular atrophy, lower extremity-predominant 1, AD', we found another term that we believe is the same term you're looking for: MONDO:0008026, 'autosomal dominant childhood-onset proximal spinal muscular atrophy without contractures' (https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0008026), which has the exact cross-reference to OMIM:158600 (https://omim.org/entry/158600). Would this suffice as a child term for dyneinopathy?

Let us know, and thank you!

Yousif
