### ISSUE TITLE
Make mondo.obo OBO basic

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#7653]
mondo.obo is an odd beast. In general the .obo files for any OBO project are

1. isomorphic to the OWL
2. the OBO basic version

I much prefer 1, and having an explicit foo-basic ontology, with obo and owl and json isomorphic versions

However, 2 is common practice, which arose from the fact that a certain cluster of tools with implicit profiles that only accepted .obo pushed their requirements (this is coupled with confusing ad-hoc choices about which browser uses which version). But it makes a certain amount of sense, and is a standard, albeit very de-facto.

However, mondo.obo is an entirely different beast. It appears to be mondo-base.obo. This is getting ahead of things. Tools are not yet ready for base files. It's not clear who the intended audience for mondo.obo is. People who like .obo because it is simple will not be satisfied because it is has dangling classes. The leading obo format based bioinformatics tool, pronto, breaks on it (https://github.com/althonos/pronto/issues/225).

bioportal consumes mondo.obo and is unusable because of the dangling classes.

On top of this there is nothing in the OBO metadata to help:
https://obofoundry.org/ontology/mondo

"As OWL. xrefs can be used as proxy for equivalence. Uses Mondo IDs."

The "as OWL" statement is false. I may be responsible for the opaque comments about proxy equivalence.

Happy with either of two options:

- mondo.obo becomes isomorphic to mondo.owl
- mondo.obo follows the OBO basic profile

In addition we should add a base release https://obofoundry.org/ontology/mondo and we should be encouraging consumers to adapt their tools to accept this

**Comment by cmungall** [comment]
Re-upping the priority on this. Options 1 and 2 are both simple to implement, and the status quo is highly suboptimal

**Comment by cmungall** [comment]
Upping the priority on this

**Comment by matentzn** [comment]
This has been dealt with for a while and already been released:

https://github.com/monarch-initiative/mondo/pull/7736/files

1. mondo.obo corresponds to mondo.owl which corresponds to mondo-full.owl (including imports)
2. We have a new mondo-simple.owl which has only the class hierarchy, ready for bioportal

- [ ] Missing: contact bioportal to use the simple release instead of mondo.obo.

**Comment by nlharris** [comment]
See also #7559

**Comment by sabrinatoro** [comment]
@matentzn @cmungall is there anything else to do for this issue? I thought we resolved this, but maybe not? 
Thanks!

**Comment by cmungall** [comment]
can be closed when the metadata here is updated https://obofoundry.org/ontology/mondo !

**Comment by cmungall** [comment]
oh my that hasn't been touched for a while


mondo.owl | Main OWL edition | Complete ontology. Uses MONDO IDs. Imports merged. The original mondo.owl without merged imports and with equivalence axioms can now be obtained from the release pages and is called mondo-with-equivalents.
-- | -- | --


"Uses MONDO IDs" that's a blast from the past

**Comment by jvendetti** [comment]
> contact bioportal to use the simple release instead of mondo.obo

BioPortal is now serving the simple version (as of yesterday)

https://bioportal.bioontology.org/ontologies/MONDO

**Comment by matentzn** [comment]
Thank you @jvendetti

**Comment by nlharris** [comment]
This looks much better! Thanks @jvendetti!
Can we close this issue?

**Comment by matentzn** [comment]
With this it can: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2657
