### ISSUE TITLE
MONDO:0100520 NKX2-1 related choreoathetosis and congenital hypothyroidism with or without pulmonary dysfunction[Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7657]
**Mondo term (ID and Label)**
MONDO:0100520 NKX2-1 related choreoathetosis and congenital hypothyroidism with or without pulmonary dysfunction

**Suggested revision and reasons**
ClinGen lumps these MIM IDs in their concept; would it make sense to have them as children to the ClinGen term in Mondo?
[MIM:188550 - {Thyroid cancer, nonmedullary, 1}](https://omim.org/entry/188550) MONDO:0008567
[MIM:118700 - Chorea, hereditary benign](https://omim.org/entry/118700) MONDO:0021011
[MIM:610978 - Choreoathetosis, hypothyroidism, and neonatal respiratory distress](https://omim.org/entry/610978) MONDO:0012593

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
