### ISSUE TITLE
MONDO:0020654 renal pelvis/ureter urothelial carcinoma &MONDO:0020659 [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7658]
**Mondo term (ID and Label)**
MONDO:0020659 upper tract urothelial carcinoma
**Reason for deprecation**
Orphanet says it maps to UMLS C0220648 (https://www.orpha.net/en/disease/detail/598216 )
which is also the equivalent mapping for NCI C7716

Names also appear to overlap, I think these may be the same disease concept?

**Term to be merged with**
MONDO:0020654 renal pelvis/ureter urothelial carcinoma 
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by twhetzel** [comment]
I agree these should be merged based on the original post and evidence they are linked by being mapped to UMLS C0220648.
