### ISSUE TITLE
MONDO:0042965 Machado-Joseph disease type 5 [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7659]
**Mondo term (ID and Label)**
MONDO:0042965 Machado-Joseph disease type 5

**Reason for deprecation**
ICD9 code is general "Cerebellar ataxia NOS (334.3)" and given that there are no other sources, recommend to obsolete this and suggest the parent term. (Noting that SNOMED CT and UMLS have terms only for types 1-4, no 5.)

**Suggested term to consider**
MONDO:0007182 Machado-Joseph disease 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
Lack of research on a type 5 presentation, term is scheduled for obsoletion. #8342
