### ISSUE TITLE
split term: schwannomatosis

### ISSUE THREAD

**Issue by allaway** [monarch-initiative/mondo#7663]
**Term to split:** 

Schwannomatosis

**Name for new terms:** 

SMARCB1-related schwannomatosis
LZTR1-related schwannomatosis 
22q-related schwannomatosis
Schwannomatosis-NOS
Schwannomatosis-NEC

**List properties that should be moved to new term:** Note- ORDO tends to represent the generic class. Most properties (such as synonyms and database cross references) will move to the generic term. Synonynms that end in "1", "2", etc. should move to subclass.

To be honest' I don't quite follow this - happy to do this but might need more explanation on what I need to provide here :)

**Your nano-attribution (ORCID)**
0000-0003-3573-3565

If needed, I can provide several sources for this change, but this powerpoint from the Children's Tumor Foundation has a nice summary https://www.ctf.org/wp-content/uploads/2023/12/DiagnosticCriteria2022.pdf

**Comment by sagehrke** [comment]
Dear @allaway,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by allaway** [comment]
Hello! I just wanted to follow up on this request. Thank you.

**Comment by twhetzel** [comment]
TODO:
- [ ] relabel MONDO:0024517 'schwannomatosis 1' to `SMARCB1-related schwannomatosis` based on updated diagnostic and nomenclature [PMID: 35674741](https://pubmed.ncbi.nlm.nih.gov/35674741/)
- [ ] Add 'schwannomatosis 1' as an exact synonym with provenance
---
- [ ] relabel MONDO:0014299 'schwannomatosis 2' to 'LZTR1-related schwannomatosis' based on updated diagnostic and nomenclature [PMID: 35674741](https://pubmed.ncbi.nlm.nih.gov/35674741/)
- [ ] Add 'schwannomatosis 2' as an exact synonym with provenance
---
- [ ] create '22q-related schwannomatosis' as a new term 
--- 
- [ ] Add 'schwannomatosis-NOS and `schwannomatosis-NEC` as narrow synonyms to MONDO:0008075 'schwannomatosis'
