### ISSUE TITLE
Revise NF2 to NF2-related schwannomatosis 

### ISSUE THREAD

**Issue by allaway** [monarch-initiative/mondo#7664]
**Mondo term (ID and Label):**
MONDO:0007039 neurofibromatosis type 2

**Suggested new label:**
NF2-related schwannomatosis 

**Your nano-attribution (ORCID)**
0000-0003-3573-3565

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Renamed in 2022 along with "schwannomatosis": https://www.sciencedirect.com/science/article/pii/S1098360022007730

**Comment by sagehrke** [comment]
Dear @allaway,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by allaway** [comment]
Hello! I just wanted to follow up on this request. Thank you.

**Comment by twhetzel** [comment]
Hi @allaway - we are working on this ticket now so it can be included in the next Mondo release.

**Comment by allaway** [comment]
Thank you @twhetzel!
