### ISSUE TITLE
Typo "Cessium" vs. "Cesium"

### ISSUE THREAD

**Issue by ericsid** [monarch-initiative/mondo#7670]
**Mondo term (ID and Label):**
MONDO:0800384
cessium poisoning

**Suggested new label:**
cesium poisoning

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
0000-0001-7697-3026

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Typo; here is a pubchem link for reference: https://pubchem.ncbi.nlm.nih.gov/compound/Cesium

**Comment by sagehrke** [comment]
Dear @ericsid,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
