### ISSUE TITLE
"asbestos intoxication" should not be an exact synonym of "asbestosis"

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#7690]
"asbestos intoxication" is considered an exact synonym to MONDO:0016466 asbestosis, but these are not the same thing ("asbestos intoxication" is not a commonly recognized medical term). Since this synonym is now EXACT and RELATED in mondo, I suggest the exact one has to go.

**Comment by sabrinatoro** [comment]
This issue blocks [this PR](https://github.com/monarch-initiative/mondo/pull/7685)

**Comment by sabrinatoro** [comment]
I removed the "intrinsic asthma" synonym from MONDO:0800112 to resolve the QC fail until these terms are merged
