### ISSUE TITLE
Several issues 

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7694]
As decided I am sending several issues in one template: (please let Sabrina know about these requests and let me know if you rather have me sending individual requests)

1. Issue request: Add synonyms
MONDO entry:   nephrotic syndrome 14  (MONDO:0033203)
Note: MONDO already have the following synonyms: 
•	familial steroid-resistant nephrotic syndrome with adrenal insufficiency
•	nephrotic syndrome 14
•	nephrotic syndrome, type 14
•	NPHS14
•	primary adrenal insufficiency-steroid-resistant nephrotic syndrome due to SGPL1 deficiency
Add the following synonyms: 
RENI syndrome
Renal, endocrine, neurologic and immune syndrome
Sphingosine phosphate lyase insufficiency syndrome
SPLIS 
Familial steroid-resistant nephrotic syndrome with adrenal insufficiency
SGPL1 Deficiency, Steroid-Resistant Nephrotic Syndrome Type 14

2. Issue request:  Add synonym
MONDO entry: neurodevelopmental disorder with microcephaly, epilepsy, and hypomyelination MONDO:0032705
Synonym to be added: 5,10 – Methenyltetrahydrofolate Synthetase Deficiency
NOTE: NORD has a report for this condition (English and Spanish)

3. Issue request: TAG condition as rare
MONDO entry: Beck-Fahrner syndrome MONDO:0032922 
Request: Tag it as rare and please tag it as NORD rare
NOTE:  I sent a ticket to Orphanet requesting to add this term (currently under “Non-specific syndromic intellectual disability” as there is also a GR). We are writing a NORD report. 

Thank you, Gioconda Alyea

**Comment by sagehrke** [comment]
Dear @galyea123,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
