### ISSUE TITLE
MONDO:0017424 non-syndromic brachydactyly

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7697]
**Mondo term (ID and Label):**
MONDO:0017424 non-syndromic brachydactyly

**Xref that should be fixed (ID and label):**
[SCTID:43476002](http://snomed.info/id/43476002)  Brachydactyly is the concept represented by this ID.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Other comments:**
This X-ref should instead be on the parent term MONDO:0021004 brachydactyly

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
