### ISSUE TITLE
MONDO:0020175 Malignant tumor of palpebral epidermis & MONDO:0021313 eyelid cancer[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7698]
**Mondo term (ID and Label)**
MONDO:0020175 Malignant tumor of palpebral epidermis

**Reason for deprecation**
Overlapping synonyms;
SNOMED CT code [423425006](http://identifiers.org/snomedct/423425006) is mapped to same CUI as 'eyelid cancer' in UMLS. 

**Term to be merged with**
MONDO:0021313 eyelid cancer
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by katiermullen** [comment]
@kanems Thank you for this request!

Based on the overlapping synonyms that you point out, MONDO:0020175 malignant tumor of palpebral epidermis will be merged into MONDO:0021313 eyelid cancer.

This change will appear in the next Mondo release.
