### ISSUE TITLE
Review: Kallman syndrome

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#77]
We follow ORDO in placing a number of different OMIM entries as narrower than Kallman

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_478

![image](https://user-images.githubusercontent.com/50745/35843365-84766f30-0abc-11e8-8278-bd0973b847aa.png)

consistent with

```
   is_a MONDO:0018800 ! Kallmann syndrome ***  [xref: DOID:3614] [xref: ICD10:E23.0] [xref: MedDRA:10053142] [xref: MESH:D017436] [xref: NCIT:C75479] [xref: Orphanet:478] [xref: SCTID:93559003] [xref: UMLS:C0162809]
      is_a MONDO:0007844 ! hypogonadotropic hypogonadism 2 with or without anosmia [xref: DOID:0090083] [xref: ICD10:E23.0] [xref: OMIM:147950] [xref: UMLS:C1563720]
      is_a MONDO:0009482 ! hypogonadotropic hypogonadism 3 with or without anosmia [xref: DOID:0090092] [xref: ICD10:E23.0] [xref: OMIM:244200] [xref: UMLS:C2930927] [xref: UMLS:C3550478]
      is_a MONDO:0010635 ! hypogonadotropic hypogonadism 1 with or without anosmia [xref: DOID:0090094] [xref: ICD10:E23.0] [xref: NCIT:C75480] [xref: OMIM:308700] [xref: UMLS:C1563719]
      is_a MONDO:0012528 ! hypogonadotropic hypogonadism 4 with or without anosmia [xref: DOID:0090077] [xref: ICD10:E23.0] [xref: OMIM:610628] [xref: UMLS:C1857720] [xref: UMLS:C3552343]
      is_a MONDO:0012880 ! hypogonadotropic hypogonadism 5 with or without anosmia [xref: DOID:0090084] [xref: ICD10:E23.0] [xref: OMIM:612370] [xref: UMLS:C2675302] [xref: UMLS:C3552553]
      is_a MONDO:0012988 ! hypogonadotropic hypogonadism 6 with or without anosmia [xref: DOID:0090086] [xref: ICD10:E23.0] [xref: OMIM:612702] [xref: UMLS:C2675188] [xref: UMLS:C3552574]
      is_a MONDO:0013910 ! hypogonadotropic hypogonadism 8 with or without anosmia [xref: DOID:0090074] [xref: ICD10:E23.0] [xref: OMIM:614837] [xref: UMLS:C3553841]
      is_a MONDO:0013911 ! hypogonadotropic hypogonadism 9 with or without anosmia [xref: DOID:0090085] [xref: ICD10:E23.0] [xref: OMIM:614838] [xref: UMLS:C3553842]
      is_a MONDO:0013913 ! hypogonadotropic hypogonadism 11 with or without anosmia [xref: DOID:0090071] [xref: ICD10:E23.0] [xref: OMIM:614840] [xref: UMLS:C3553844]
      is_a MONDO:0013926 ! hypogonadotropic hypogonadism 14 with or without anosmia [xref: DOID:0090087] [xref: ICD10:E23.0] [xref: OMIM:614858] [xref: UMLS:C3540450]
      is_a MONDO:0013946 ! hypogonadotropic hypogonadism 15 with or without anosmia [xref: DOID:0090075] [xref: ICD10:23.0] [xref: OMIM:614880] [xref: UMLS:C3553977]
      is_a MONDO:0013961 ! hypogonadotropic hypogonadism 16 with or without anosmia [xref: DOID:0090080] [xref: ICD10:E23.0] [xref: OMIM:614897] [xref: UMLS:C3554021]
      is_a MONDO:0014102 ! hypogonadotropic hypogonadism 17 with or without anosmia [xref: DOID:0090079] [xref: ICD10:E23.0] [xref: OMIM:615266] [xref: UMLS:C3808971]
      is_a MONDO:0014103 ! hypogonadotropic hypogonadism 18 with or without anosmia [xref: DOID:0090076] [xref: ICD10:E23.0] [xref: OMIM:615267] [xref: UMLS:C3808975]
      is_a MONDO:0014105 ! hypogonadotropic hypogonadism 19 with or without anosmia [xref: DOID:0090090] [xref: ICD10:E23.0] [xref: OMIM:615269] [xref: UMLS:C3808981]
      is_a MONDO:0014106 ! hypogonadotropic hypogonadism 20 with or without anosmia [xref: DOID:0090082] [xref: ICD10:E23.0] [xref: OMIM:615270] [xref: UMLS:C3808983]
      is_a MONDO:0014107 ! hypogonadotropic hypogonadism 21 with or without anosmia [xref: DOID:0090093] [xref: ICD10:E23.0] [xref: OMIM:615271] [xref: UMLS:C3808986]
      is_a MONDO:0014461 ! hypogonadotropic hypogonadism 22 with or without anosmia [xref: DOID:0090081] [xref: ICD10:E23.0] [xref: OMIM:616030] [xref: UMLS:C4014988]
```

However, there is an issue here; let's take https://omim.org/entry/610628 (HH4)

"In the presence of anosmia, idiopathic hypogonadotropic hypogonadism has been called 'Kallmann syndrome (KS),' whereas in the presence of a normal sense of smell, it has been termed 'normosmic idiopathic hypogonadotropic hypogonadism (nIHH)' (summary by Raivio et al., 2007). Because families have been found to segregate both KS and nIHH, the disorder is here referred to as 'hypogonadotropic hypogonadism with or without anosmia (HH)"

so it's seems incorrect to place the HHs under KS, as the true path rule is violated.

The ORDO def for KS is

*Kallmann syndrome (KS) is a developmental genetic disorder characterized by the association of congenital hypogonadotropic hypogonadism (CHH) due to gonadotropin-releasing hormone (GnRH) deficiency, __and anosmia or hyposmia (with hypoplasia or aplasia of the olfactory bulbs)__*

Note that GARD calls this OMIM ID "KAL4" and "Kallman syndrome 4"
https://rarediseases.info.nih.gov/diseases/10772/kallmann-syndrome-4

In HPOA we have an 'occasional' annotation of this OMIM to Anosmia

One possibility would be to make two subtypes of every HH[n]: KS[n] and niHH[n]. However, this seems like overkill.

It may be better to place HH[n] under the more general [MONDO:0018555](http://purl.obolibrary.org/obo/MONDO_0018555) ! hypogonadotropic hypogonadism

For now, we will follow ORDO and place the HH[n]s under KS, even though each may not have all the classic KS symptoms

**Comment by nicolevasilevsky** [comment]
🎂 happy 3rd birthday, ticket!
h/t @monicacecilia 

we will continue to follow ORDO as mentioned above. We can consider re-reviewing at a later time. Closing for now.
