### ISSUE TITLE
[NTR] Refeeding Syndrome

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/mondo#770]
parent: ?? 
 label: refeeding syndrome 
definition: Potentially fatal shifts in fluids and electrolytes that may occur in malnourished patients receiving artificial refeeding (whether enterally or parenterally).
Reference: PMID: 2109122 , PMID: 18583681
Nano-attribution: 0000-0002-7463-6306

This state alters ion status most significantly (i.e. hypophosphatemia, hypomagnesemia, hypokalemia) but it can also impact macronutrient metabolism so I was uncertain as to the best parent class option.

**Comment by laurenechan** [comment]
Is there any particular parent that comes to mind for this term, should we choose to include it?

**Comment by nicolevasilevsky** [comment]
maybe MONDO_0005137 'nutritional disorder'?

def: Any condition related to a disturbance between proper intake and utilization of nourishment.

**Comment by laurenechan** [comment]
Good thought! I appreciate that parent class being able to address the irregular intake leading up to the refeeding, and then the irregular nutrient utilization during

**Comment by nicolevasilevsky** [comment]
this has been added as MONDO_0400005
closing
