### ISSUE TITLE
Exclude `Orphanet:377788` from rare subset pipeline

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo#7704]
## Overview
Exclude `Orphanet:377788` "Disease" from the rare disease subset generation pipeline.

## Context
See this discussion thread:
- https://github.com/monarch-initiative/mondo-ingest/pull/510#discussion_r1592954704

Nico:
> Please exclude
> MONDO:0000001 | http://purl.obolibrary.org/obo/mondo#ordo_disease | Orphanet:377788 | disease | disease
> -- | -- | -- | -- | --
> 
> From the ORDO subset - which is the "ORDO" disorder class itself. Adding this makes the entire ontology become "rare"!

Joe:
> Orphanet:377788 "Disease" is a direct subclass of Orphanet:557493 "Disorder", which is one of the subsets that we've selected. 

Nico:
> I didn't realise "disease" was a subclass of "disorder"... create an issue to... exclude the term from the rare disease subset generation pipeline (with the logic that, while the term is, indeed in the ordo_disorder subset, it should not be added to the rare disease subset, which you are not concerned with here).

**Comment by matentzn** [comment]
To be clear, `Orphanet:377788` is already excluded from the rare disease subset - this issue is about explicitly excluding it from the rare subset pipeline. Thanks @joeflack4, will take care of it!

**Comment by joeflack4** [comment]
Thanks for clarification! I'm completely in the dark on this side of things; those two things sound almost identical. I updated the title~
