### ISSUE TITLE
Sharpin-related autoinflammatory syndrome

### ISSUE THREAD

**Issue by nataliedeuitch** [monarch-initiative/mondo#7706]
**Sharpin-related autoinflammatory syndrome**
For example: NAA10-related syndrome

**Sharpenia**

**autoinflammatory syndrome (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

**Definition**
 An auntoinflammatory disease in which the cause of the disease is a mutation in the Sharpin gene. 

**Definition source (PMID: 38609546)

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
(https://orcid.org/0000-0002-0146-1162) https://clinicalgenome.org/affiliation/40139

**Comment by sagehrke** [comment]
Dear @nataliedeuitch,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
