### ISSUE TITLE
MONDO:0007727 autosomal dominant familial periodic fever to TNF receptor 1-associated periodic syndrome (TRAPS

### ISSUE THREAD

**Issue by nataliedeuitch** [monarch-initiative/mondo#7707]
**Mondo term (ID and Label):**
MONDO:0007727 autosomal dominant familial periodic fever

**Suggested new label:**
TNF receptor 1-associated periodic syndrome (TRAPS)

**Your nano-attribution (ORCID)**
(https://orcid.org/0000-0002-0146-1162) https://clinicalgenome.org/affiliation/40139/

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
We're just curating this gene as a part of the autoinflammatory GCEP and would like to make sure that the main curation is for TNF receptor 1-associated periodic syndrome (TRAPS) as this is what the disease is called. There are many autosomal dominant familial periodic fevers so it's a bit confusing as labeled and not specific to mutation sin the TNFRSF1A gene.

**Comment by sagehrke** [comment]
Dear @nataliedeuitch,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by katiermullen** [comment]
@nataliedeuitch thank you for your request!

In Mondo, we aim to align with the OMIM label as the primary label. This term has an exact synonym 'TNF receptor-associated periodic fever syndrome' with synonym type 'ClinGen label'

Would you prefer that we update the exact synonym with ClinGen label to 'TNF receptor **1**-associated periodic fever syndrome'? 

Let us know if you have any questions.

@nicolevasilevsky
