### ISSUE TITLE
MONDO:0968955 hypocalcified amelogenesis imperfecta [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7708]
**Mondo term (ID and Label)**
MONDO:0968955 hypocalcified amelogenesis imperfecta

**Suggested revision and reasons**
This seems like it should be parent to 
amelogenesis imperfecta, type 3A MONDO_0007538
amelogenesis imperfecta type 3B MONDO_0021547
amelogenesis imperfecta, type 3c MONDO_0032717

Rationale: ORDO synonym is Amelogenesis imperfecta type 3
(I have separately reached out to Orphanet to see if they will add the OMIM ref for type IIIC to their mappings, if that makes sense)
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
