### ISSUE TITLE
[Merge] MONDO:0011292 (dermatitis, atopic) into MONDO:0004980 (atopic eczema)

### ISSUE THREAD

**Issue by Sean-Ontoforce** [monarch-initiative/mondo#7712]
**Mondo term (ID and Label)**
MONDO:0011292 (dermatitis, atopic)

**Reason for deprecation**
The MONDO entry for "Atopic Eczema" (MONDO:0004980) has "atopic dermatitis" (DOID:3310) as an exactMatch, yet the MONDO entry for "atopic dermatitis" itself is not mapped to this term.
Also, all of these entries (the DOID and the MONDO ones) reference the same OMIM term (OMIM:603165). So there's some circular referencing happening here.

**Term to be merged with**
MONDO:0004980 (atopic eczema)

**Your nano-attribution (ORCID)**
0000-0002-9584-9618

**Comment by sagehrke** [comment]
Dear @Sean-Ontoforce,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team

**Comment by nicolevasilevsky** [comment]
@twhetzel and @Sean-Ontoforce I don't think these terms should merged actually. They seem like the same term based on the label/synonyms, but MONDO:0004980 'atopic eczema' is equivalent to many xrefs including OMIMPS:603165, which groups together many susceptibilities to atopic eczema (see https://www.omim.org/phenotypicSeries/PS603165). I think the OMIMPS is equivalent to MONDO:0100178 'dermatitis, atopic, susceptibility to', which groups together the subclasses in the OMIMPS.

The subclass MONDO:0011292 'dermatitis, atopic' is equiv to https://omim.org/entry/603165, which is described in OMIM as "Atopic dermatitis (ATOD), also known as eczema, is a common chronic pruritic inflammatory skin disease with a strong genetic component.", so I don't think it is correct to classify this particular term as a child of the inherited form. There is evidence that there are cases of atopic dermatitis that are not genetic: https://www.niams.nih.gov/health-topics/atopic-dermatitis

This branch will need some reworking, I am happy to help if needed.
