### ISSUE TITLE
Add several Xrefs to MONDO:0004980 (atopic eczema)

### ISSUE THREAD

**Issue by Sean-Ontoforce** [monarch-initiative/mondo#7713]
**Mondo term (ID and Label):**
MONDO:0004980 (atopic eczema)

**Xref that should be fixed (ID and label):**
equivalentTo: SCTID:24079001 (Atopic dermatitis (disorder))
equivalentTo: SCTID:200775004 (Atopic neurodermatitis (disorder))
equivalentTo: ICD10:L20 (Atopic dermatitis)
otherHierarchy: HP:0001047 (Atopic dermatitis)

**Your nano-attribution (ORCID)**
0000-0002-9584-9618

**Other comments:**

**Comment by sagehrke** [comment]
Dear @Sean-Ontoforce,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible. 

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo! 

Sincerely,
The Mondo Team
