### ISSUE TITLE
[NTR/gene] PIK3CA

### ISSUE THREAD

**Issue by abbe-Lai** [monarch-initiative/mondo#7718]
Preferred gene-related syndrome label
PIK3CA-related Overgrowth spectrum

Synonyms
MONDO:0100283

Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)
MONDO:0019716

Definition
Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene.

Any malformations/disorders resulting from pathogenic gain-of-function variants in the PIK3CA gene. The variants can be germline or somatic

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID: 25557259; 23592320; 23946963

Children terms (if applicable) Should any existing terms be re-classified as children underneath this new proposed term?
MONDO:0014047
MONDO:0017812
MONDO:0013038  
MONDO:0011240
MONDO:0019375

Your nano-attribution (ORCID) or URL for a working group
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://clinicalgenome.org/affiliation/50020/

**Comment by sagehrke** [comment]
Dear @abbe-Lai, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
