### ISSUE TITLE
[NTR] Skeletal fluorosis

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/mondo#772]
parent: metabolic disease (MONDO:0005066) 
label: skeletal fluorosis 
exact synonym: fluorosis of the skeleton
 definition: A condition that results from excessive fluoride ingestion leading to fluoride accumulation in the bone progressively over many years. The early symptoms of skeletal fluorosis, include stiffness and pain in the joints. In severe cases, the bone structure may change and ligaments may calcify, with resulting impairment of muscles and pain.
Reference: PMID:3295994, https://www.who.int/water_sanitation_health/diseases-risks/diseases/fluorosis/en/ 
Nano-attribution: 0000-0002-7463-6306

**Comment by nicolevasilevsky** [comment]
this term has been added: MONDO_0400003
