### ISSUE TITLE
[Revise subclass]  inherited fatty acid metabolism disorder (MONDO:0037858)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7723]
**Mondo term (ID and Label)**

 inherited fatty acid metabolism disorder (MONDO:0037858)

**Suggested revision and reasons**

is positioned under
inborn organic aciduria MONDO:0000688
which is under
 inborn disorder of amino acid metabolism (MONDO:0004736)

 fatty acid is not an amino acid, this brings all fatty acid metabolism disorders under amino acid.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by cmungall** [comment]
Hey, Ontobot!

* delete edge MONDO:0037858 rdfs:subClassOf  MONDO:0000688

**Comment by nicolevasilevsky** [comment]
Hi @ValWood - I think this was addressed - these are the current parents of inherited fatty acid metabolism disorder (MONDO:0037858):

<img width="451" alt="image" src="https://github.com/user-attachments/assets/fef3fdf3-7ed6-4cdf-a05c-705a9f69a982">

Does this look okay to you? Can this ticket be closed or is more action needed? Thanks!

**Comment by ValWood** [comment]
Hi @nicolevasilevsky, yes, that is addressed. Thanks!
