### ISSUE TITLE
[Revise subclass] early myoclonic encephalopathy (MONDO:0016022)

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7727]
**Mondo term (ID and Label)**

early myoclonic encephalopathy (MONDO:0016022)

is classed as a 
mitochondrial substrate carrier disorder (MONDO:0016801)

but it isn't a mitochondrial substrate carrier disorder (MONDO:0016801)
(or at least not all descendants are).

developmental and epileptic encephalopathy, 3 (MONDO:0012245)
is,   but epilepsy, familial adult myoclonic, 3
is not.  I didn't check others.

**Suggested revision and reasons**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @ValWood, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
