### ISSUE TITLE
[NTR] Phrynoderma

### ISSUE THREAD

**Issue by laurenechan** [monarch-initiative/mondo#773]
parent: hyperkeratosis 
label: phrynoderma 
definition: Phrynoderma is a form of follicular hyperkeratosis seen in young children and adolescents due to nutritional deficiencies. It is clinically characterized by discrete, follicular, skin-colored papules with keratotic plugs distributed over elbows, knees, extensor extremities, and buttocks.
xref: NCIT_C112827 
Reference: DOI: 10.4103/2319-7250.175657, PMID: 21965845
Nano-attribution: 0000-0002-7463-6306

Notably, the NCIT xref states that this disease state is particularly aligned with vitamin A deficiency, and while still likely true, other nutritional deficiencies have been correlated with phrynoderma beyond vitamin A in recent literature.

**Comment by nicolevasilevsky** [comment]
@cmungall Hyperkeratosis is in HP. Should we add this and phrynoderma  to Mondo?
