### ISSUE TITLE
Add synonym 'ZCCHC8-related teleomere biology disorder' for pulmonary fibrosis and/or bone marrow failure, telomere-related, 5

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/mondo#7732]
### Mondo term

MONDO:0032865

### Synonyms

ZCCHC8-related teleomere biology disorder

### Synonym type

exact

### Additional comments

Hey ontobot! apply:
- create exact synonym 'ZCCHC8-related teleomere biology disorder' for MONDO:0032865

**Comment by nlharris** [comment]
(this is for making a screenshot for the KGCL paper -- will delete afterwards)

**Comment by twhetzel** [comment]
@nlharris - is the process still being changed so that a PR is not automatically be created? This issue did create a PR: https://github.com/monarch-initiative/mondo/pull/7733

**Comment by nlharris** [comment]
I'm not sure

**Comment by twhetzel** [comment]
Is there someone else you suggest to check with?
