### ISSUE TITLE
Mollaret meningitis

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7737]
Hello,

I received a message from a patient affected with this condition and I noticed it is not listed in MONDO or Orphanet. It is in GARD. https://rarediseases.info.nih.gov/diseases/10868/mollaret-meningitis  

Definition: Mollaret’s meningitis, also known as recurrent benign lymphocytic meningitis, is a rare clinical disorder characterized by at least three recurrent episodes of meningitis associated with spontaneous recovery with or without antiviral therapy. Herpes simplex virus type 2 has frequently been implicated in the setting of this illness. RBLM is rare with prevalence rates estimated at 2 per 100,000 persons. 

References: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9586678/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2744243/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8233175/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10239340/

Thank you, Gioconda Alyea

**Comment by sagehrke** [comment]
Dear @galyea123,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
