### ISSUE TITLE
Add a synonym for MONDO:0859190

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7739]
### Mondo term

neurodevelopmental-craniofacial syndrome with variable renal and cardiac abnormalities

### Synonyms

ZMYM2-related neurodevelopmental disorder with multiple anomalies

### Synonym type

exact

### Additional comments

NORD will have a report.  Thank you! Gioconda Alyea

**Comment by sagehrke** [comment]
Dear @galyea123,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by galyea123** [comment]
Hi!  Just adding that this request is linked to issue 7641 https://github.com/monarch-initiative/mondo/issues/7641  as the condition was included in my message with several issues.  Thank you, Gioconda

**Comment by nlharris** [comment]
@sabrinatoro would it be ok if I try to do an Ontobot synonym request for the synonym requested here?

**Comment by sabrinatoro** [comment]
@nlharris yes, please!!

**Comment by twhetzel** [comment]
Through other processes, this synonym already existed in Mondo. However, I added the user's orcid.

@nlharris while ontobot did create the PR etc., it was not able to remove the extra whitespace in the synonym label, e.g. `' ZMYM2-related neurodevelopmental disorder with multiple anomalies'` in the [PR](https://github.com/monarch-initiative/mondo/pull/7798/files#diff-889e0a9ba62d62cc6ee7c5c9bead0075444d506253590ef0dcf4786904ac6768R549576).

**Comment by nlharris** [comment]
Hmm, that extra leading space inside the quotes seems like a minor ontobot bug that should be reported. But why wasn't it possible to request changes to the PR to get rid of the extra space? Was it because it had already been merged when you noticed the extra space?

**Comment by nlharris** [comment]
(Closing this ticket since it's done - but you should still be able to add comments)
