### ISSUE TITLE
Autosomal dominant developmental and epileptic encephalopathy 31A

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7740]
### Label

Autosomal dominant developmental and epileptic encephalopathy 31A

### Synonyms

DNM1-Encephalopathy and Neurodevelopmental Disorder

### Synonym type

broad

### Definition

Developmental and epileptic encephalopathy-31A (DEE31A) is an autosomal dominant neurologic disorder characterized by the global developmental delay apparent in early infancy. Most individuals have onset of various types of refractory seizures in the first months or years of life, which exacerbates the psychomotor deficits. Patients have hypotonia and profound intellectual disability with absent speech and inability to walk or ataxic gait. Some patients may have additional features, including dysmorphic features or cortical visual impairment (summary by the [EuroEPINOMICS-RES Consortium et al., 2014]

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9748255/
See OMIM: https://omim.org/entry/616346

Thank you, Gioconda Alyea

### Parent term

developmental and epileptic encephalopathy MONDO:0100062

### Additional comments

NORD will have a report entitled DNM1-Encephalopathy and Neurodevelopmental Disorder which includes Autosomal dominant developmental and epileptic encephalopathy 31A.

**Comment by galyea123** [comment]
I realized I already had opened an issue with a request for this one.  Please dismiss this one.  Thank you, Gioconda

**Comment by sagehrke** [comment]
Thank you, @galyea123! 
Please see https://github.com/monarch-initiative/mondo/issues/7641 to address this ticket.
