### ISSUE TITLE
Autosomal recessive developmental and epileptic encephalopathy 31B

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7741]
### Label

autosomal recessive developmental and epileptic encephalopathy 31B

### Synonyms

DNM1-Encephalopathy and Neurodevelopmental Disorder

### Synonym type

broad

### Definition

Developmental and epileptic encephalopathy-31B (DEE31B) is an autosomal recessive neurologic disorder with early-onset epilepsy, generalized muscular hypotonia, visual impairment, and severe neurodevelopmental delay

### Parent term

developmental and epileptic encephalopathy MONDO:0100062

### Additional comments

NORD will have a report entitled DNM1-Encephalopathy and Neurodevelopmental Disorder which includes autosomal recessive developmental and epileptic encephalopathy 31B and autosomal dominant developmental and epileptic encephalopathy 31A.

**Comment by galyea123** [comment]
Hi!  I realized that I already had made a request for this one.  Please dismiss it.  Thank you, Gioconda

**Comment by sagehrke** [comment]
Thank you, @galyea123! 
Please see https://github.com/monarch-initiative/mondo/issues/7641 to address this ticket.
