### ISSUE TITLE
Request for new synonym Parkinson Disease MONDO:0005180

### ISSUE THREAD

**Issue by dilshans2k** [monarch-initiative/mondo#7742]
### Mondo term

Parkinson disease MONDO:0005180

### Synonyms

PD

### Synonym type

exact

### Additional comments

Currently `PD` and `LOPD` is linked to `late-onset Parkinson disease` `MONDO:0008199`, but only `LOPD` is required to be linked with `MONDO:0008199` and `PD` should be linked with `MONDO:0005180`

**Comment by dilshans2k** [comment]
Anyone with the medical expertise can shed some light as to how to handle acronyms better?
For eg:
Searching `LOPD` on google gives `late onset pompe disease`, but in `MONDO` ontology, it is linked to `late onset parkinson disease`

**Comment by sagehrke** [comment]
Dear @dilshans2k,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
