### ISSUE TITLE
MONDO:0011929 xref & def showing for all ORPHA terms in HPO browser

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/mondo#7744]
@matentzn helpfully brought me here! Sorry I'm not much help I originally thought this was a HPOA/HPO website issue.

**Bug/Typo/Error description**

Currently all ORPHA diseases display an incorrect MONDO xref to MONDO:0011929. I came across this browsing ORPHA term annotations on the HPO website.

The definition is the same (incorrect again from MONDO:0011929) for each ORPHA disease as well.

OMIM MONDO xrefs look good though! (At least browsing via HPO)

Originally posted:

TheJacksonLaboratory/hpo-web#289

**Comment by sagehrke** [comment]
Dear @peupeubangbang,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by matentzn** [comment]
The exact same xref was reported by another user on slack (@bryanlaraway), so it may be worth getting to the bottom of this.

**Comment by twhetzel** [comment]
@peupeubangbang can you add a link to the HPO browser for one of the HPO terms that displays this issue?

**Comment by bryanlaraway** [comment]
Here's the one I encountered first: https://hpo.jax.org/browse/disease/ORPHA:84

**Comment by twhetzel** [comment]
Thanks @bryanlaraway!

I don't see how this is an issue in Mondo. The ID for "Fanconi anemia" in Mondo is `[MONDO:0019391](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0019391)` not `MONDO:0011929` as shown on the [HPO](https://hpo.jax.org/browse/disease/ORPHA:84) site and [web service](https://ontology.jax.org/api/network/annotation/ORPHA:84).

There are only 4 terms in Mondo with xrefs to Orphanet:84 (assuming that is what the HPO site is using this Orphanet ID) and these Mondo terms are all related to "Fanconi anemia".

@matentzn why do you think this is a problem with Mondo and not the HPO web site?

**Comment by twhetzel** [comment]
I asked Nico to review these findings and he said he contacted the HPO folks and it's because a wrong relationship on the HPO website (xref instead of skos:exactMatch) is being used. Closing this issue since it's not a Mondo issue.
