### ISSUE TITLE
Request for new synonym MONDO:0017169 

### ISSUE THREAD

**Issue by dilshans2k** [monarch-initiative/mondo#7745]
### Mondo term

multiple endocrine neoplasia

### Synonyms

MEN

### Synonym type

related

### Additional comments

Currently `MONDO:0017169` has related synonym `men`, but since `men` is an acronym for `multiple endocrine neoplasia`, hence it should be `MEN`

**Comment by dilshans2k** [comment]
Similarly,

`MONDO:0011126` has synonym `Air`, but since `Air` is used as an acronym for `acute insulin response`, hence it should be `AIR`

**Comment by sagehrke** [comment]
Dear @dilshans2k,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by twhetzel** [comment]
These changes will be addressed by https://github.com/monarch-initiative/mondo/issues/7746
