### ISSUE TITLE
Mondo terms acronym synonyms must be in capital case

### ISSUE THREAD

**Issue by dilshans2k** [monarch-initiative/mondo#7746]
**Mondo term (ID Label)**
MONDO:0011126, MONDO:0017169

**Bug/Typo/Error description**
- `MONDO:0011126:Air` -> `AIR`
- `MONDO:0017169:men` -> `MEN`

**Your nano-attribution (ORCID)**
0009-0005-1076-2062

**Comment by sagehrke** [comment]
Dear @dilshans2k,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
