### ISSUE TITLE
RIPOR2

### ISSUE THREAD

**Issue by RyanFWebb** [monarch-initiative/mondo#7747]
**autosomal dominant nonsyndromic genetic hearing loss**

**Synonyms**
N/A

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
N/A

**Definition**
Any autosomal dominant nonsyndromic genetic hearing loss in which the cause of the disease is a mutation in the _RIPOR2_ gene.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
PMID: 32631815

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
N/A

**Your nano-attribution (ORCID) or URL for a working group**
[ClinGen Hearing Loss GCEP](https://clinicalgenome.org/affiliation/40007/)

**Comment by sagehrke** [comment]
Dear @RyanFWebb,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
Hi Ryan,

I believe your submission for an autosomal dominant nonsyndromic hearing loss due to mutation in RIOPR2 is related to [Deafness Autosomal Dominant 21](https://omim.org/entry/607017), MONDO:0011761. Let me know what you think - thank you!

-Yousif

**Comment by RyanFWebb** [comment]
Hi Yousif,

That's correct, sorry if I mistakenly entered something else.

Thank you,
Ryan

*Ryan Webb*

Clinical Genomic Research Coordinator

Broad Institute of MIT and Harvard

105 Broadway, Cambridge, MA 02142

***@***.***

207.752.4372

Pronouns: he/him

[image: BroadInstLogoforDigitalRGB.png] <https://www.broadinstitute.org/>
