### ISSUE TITLE
Synonym for GUBS

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/mondo#7762]
### Mondo term

Genitourinary and/or brain malformation syndrome MONDO:0032934

### Synonyms

GUB syndrome
Urogenital and/or brain malformation syndrome
UBMS
UBM syndrome

### Synonym type

exact

### Additional comments
GeneReviews:NBK573670

**Comment by sagehrke** [comment]
Dear @peupeubangbang,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
