### ISSUE TITLE
Myelin oligodendrocyte glycoprotein (MOG) antibody-associated disease (MOGAD) 

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7776]
### Label

Myelin oligodendrocyte glycoprotein (MOG) antibody-associated disease (MOGAD) 

### Synonyms

MOGAD

### Synonym type

exact

### Definition

Request to add a new disease: 

Myelin oligodendrocyte glycoprotein (MOG) antibody-associated disease (MOGAD) is an inflammatory demyelinating disease of the central nervous system (CNS) with the presence of conformation-sensitive antibodies against MOG. The spectrum of MOGAD includes monophasic/relapsing optic neuritis, myelitis, neuromyelitis optica spectrum disorder (NMOSD) phenotype without aquaporin 4 (AQP4) antibodies, acute/multiphasic demyelinating encephalomyelitis (ADEM/MDEM)-like presentation, and brainstem and cerebral cortical encephalitis. The prevalence of MOGAD is approximately 1.3–2.5/100,000.  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10542411/

NOTE:  I noticed that MONDO list the following that are included in MOGAD:

- isolated optic neuritis with anti-MOG antibodies (MONDO:0035668)
- acute transverse myelitis with anti-MOG antibodies (MONDO:0035666)  
- acute disseminated encephalomyelitis with anti-MOG antibodies (MONDO:0035669)  and also
- neuromyelitis optica spectrum disorder with anti-MOG antibodies (MONDO:0035664)  

From the same source: "The MOG antibodies were initially detected primarily in a subgroup of patients with acute/multiphasic demyelinating encephalomyelitis (ADEM/MDEM) (2, 3). Subsequent studies showed that MOG antibodies were also present in patients with optic neuritis, myelitis, neuromyelitis optica spectrum disorder (NMOSD) phenotype without aquaporin 4 (AQP4) antibodies, and brainstem and cerebral cortical encephalitis; Recently, the international diagnostic criteria for MOGAD were published (12), and the diagnosis of MOGAD is now made based on the presence of at least one of the core clinical demyelinating events (optic neuritis, myelitis, ADEM, cerebral monofocal or polyfocal deficits, brainstem or cerebellar deficits, and cerebral cortical encephalitis often with seizures), a positive MOG-IgG test, and the exclusion of alternative diagnoses including MS."

See also: MOGAD is now recognized as an autonomous, antibody-mediated inflammatory demyelinating disorder, most frequently with relapsing course and a variety of clinical manifestations. As it is a rare condition, researchers should still focus on the different aspects of the disease: its pathophysiological mechanisms, the identification of markers of the disease status and outcome, the incidence in various regions and patients populations. All of the above should form the basis for development and elaboration of the MOGAD diagnosis criteria to be ultimately approved by experts. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7795410/

We have a NORD report.

Thank you, Gioconda Alyea

### Parent term

inflammatory demyelinating disease of the central nervous system

### ORCID Identifier

0000-001-9310-0163

**Comment by sagehrke** [comment]
Dear @galyea123,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by galyea123** [comment]
Hi!  Any updates in this request?  Thank you! Gioconda Alyea

**Comment by galyea123** [comment]
Hi Sabrina!  Just wanted to clarify if this term was added (I saw the GitHub ticket but I could not tell...).  I apologize for bothering you!
Thank you!! Gioconda
________________________________

**Comment by sabrinatoro** [comment]
No bothering at all @galyea123. :-)
Yes, this term has been added: the PR was merged earlier today. It will be available in our next release (scheduled on August 6)
Best, Sabrina

**Comment by galyea123** [comment]
[heart]         Gioconda Alyea reacted to your message:
________________________________
