### ISSUE TITLE
MONDO:0009455 (OMIM 242870)[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7780]
**Mondo term (ID and Label)**
MONDO:0009455 immunodeficiency, partial combined, with absence of HLA Determinants and beta-2-microglobulin from lymphocytes

**Reason for deprecation**
OMIM 242870 is no longer a separate record, it has been split- 
MOVED TO [604571](https://www.omim.org/entry/604571) MHC CLASS I DEFICIENCY 1 AND [209920](https://www.omim.org/entry/209920) MHC CLASS II DEFICIENCY 1

**Term to be merged with**
I don't know if these are in Mondo yet, but since it was a split and not a 1:1 merge, maybe this is an obsolete with "see X or Y" suggested alternate term?

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by twhetzel** [comment]
I agree MONDO:0009455 'immunodeficiency, partial combined, with absence of HLA Determinants and beta-2-microglobulin from lymphocytes' should be split based on the original post that the OMIM used as an xref has also been split.

TODO
- [ ] Obsolete MONDO:0009455 'immunodeficiency, partial combined, with absence of HLA Determinants and beta-2-microglobulin from lymphocytes' 
- [ ] Move the relevant axioms from MONDO:0009455 to the existing terms MONDO:0971006 'MHC class I deficiency 1' and MONDO:0971005 'MHC class II deficiency 1'
