### ISSUE TITLE
Request for new term [TRIP11 related skeletal dysplasia]

### ISSUE THREAD

**Issue by sng2140** [monarch-initiative/mondo#7782]
### Label

TRIP11 related skeletal dysplasia 

### Synonym type

None

### Definition

TRIP11 related skeletal dysplasia describes both achondrogenesis type 1a and ondontochondrodysplasia. Reduced protein function in TRIP11 causes a spectrum of skeletal symptoms from a more mild phenotype, called ondontochondrodysplasia, with features including short stature and joint laxity to a more severe phenotype, called achondrogenesis type 1a, which presents as a lethal prenatal or neonatal skeletal dysplasia (PMID:20089971; 30728324 ). The clinical severity of achondrogenesis compared to ondontochondrodysplasia is related to the residual function of the gene which is not currently possible to anticipate based on genotype alone. The phenotype cannot fully be predicted by genotype alone, evidenced by variants being reported with both phenotypes. 

### Parent term

skeletal dysplasia: MONDO:0018230

### ORCID Identifier

Achondrogenesis type 1a MONDO:0008701 Odontochondrodysplasia MONDO:0031169

### Additional comments

Both  achondrogenesis type 1a and ondontochondrodysplasia are specifically caused by variants in TRIP11. They both share the parent term “skeletal dysplasia” under “musculoskeletal system disorder”.  We are combining Achondrogenesis 1a and odontochondrodyplasia into one Mondo and gene-disease relationship.

**Comment by sagehrke** [comment]
Dear @sng2140 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
A cursory literature search does show both achondrogenesis type 1a (ACG1A) and ondontochondrodysplasia (ODCD) are spectrum disorders of TRIP11 mutation (PMID: 34111908). A new term 'TRIP11 related skeletal dysplasia' as a parent class of the two is appropriate.
