### ISSUE TITLE
Def. of MONDO:0008006 Mobius syndrome contains repeated text (3x)

### ISSUE THREAD

**Issue by paola-scibite** [monarch-initiative/mondo#7787]
**Mondo term (ID Label)**
MONDO:0008006 Mobius syndrome 

**Bug/Typo/Error description**
In OLS4, the definition reads:

"Moebius syndrome is a very rare congenital cranial dysinnervation disorder characterized by complete or incomplete facial paralysis in association with bilateral palsy of the abducens nerve causing impairment of ocular abduction. The syndrome also includes various other congenital anomalies.
This term's classification was reviewed in the context of the Strategic Refinement project (2023) and was determined to be excluded from the 'musculoskeletal system disorder' (MONDO:0002081) ontology branch ([0000-0001-9310-0163)](https://orcid.org/0000-0001-9310-0163))MONDO:0002081) ontology branch (https://orcid.org/0000-0001-9310-0163)[musculoskeletal system disorder](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0002081?lang=en)) ontology branch (https://orcid.org/0000-0001-9310-0163)"

The final bit of text appears repeated 3x, looks like the hyperlinks may contain syntax errors?
I tried searching for "Strategic Refinement project" in case there are other similar cases, but couldn't find results.
![Screenshot 2024-06-06 at 14 08 34](https://github.com/monarch-initiative/mondo/assets/61156599/b24d0858-c0cc-457a-b4cf-cd6151bffff0)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0000-0002-2825-0621

P.S. Feel free to change the ticket label, looks more like a typo than a bug, but I can't edit that myself from this account.

**Comment by sagehrke** [comment]
Dear @paola-scibite, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by twhetzel** [comment]
Hi @paola-scibite! Thank you for reporting this. It looks like this may have been fixed since the initial report. Here is the view I see in Protege and OLS. Do you see the same now in OLS for [MONDO:0008006](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0008006)?

![protege-screenshot](https://github.com/user-attachments/assets/cfaa76bf-a89b-4879-90d0-ba4c0e1cb909)
---
![ols-screenshot](https://github.com/user-attachments/assets/bdccf2fe-3191-40c7-aa5b-a55a2530b44b)

**Comment by cmungall** [comment]
Hi @paola-scibite

Thanks for pointing this out.

Quite appropriate that this loop happened for Möbius syndrome. ǝɯoɹpuʎs snᴉqöɯ ɹoɟ pǝuǝddɐɥ dool sᴉɥʇ ʇɐɥʇ ǝʇɐᴉɹdoɹddɐ ǝʇᴉnq. Quite appropriate that this loop happened for Möbius syndrome.

**Comment by paola-scibite** [comment]
> Hi @paola-scibite! Thank you for reporting this. It looks like this may have been fixed since the initial report. Here is the view I see in Protege and OLS. Do you see the same now in OLS for [MONDO:0008006](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0008006)?

Hi @twhetzel ! Yes, I see the same, so it's fixed. Thank you.
