### ISSUE TITLE
[NTR/gene]Treacher Collins Syndrome caused by mutation in ABC (TEST NOT REAL SUBMISSION)

### ISSUE THREAD

**Issue by yshwetar** [monarch-initiative/mondo#7807]
**Preferred gene-related syndrome label**
For example: NAA10-related syndrome
Treacher Collins Syndrome caused by mutation in ABC

**Synonyms**
ABC Treacher Collins Syndrome
ABC related Treacher Collins Syndrome
ABC TCS

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

Treacher Collins Syndrome

**Definition**
Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene. For example: Any congenital myopathy in which the cause of the disease is a mutation in the TPM3 gene.

Any form of Treacher Collins Syndrome in which the cause of the disease is a mutation in the ABC gene.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)

PMID: 837469

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

MONDO: XXXXXX
MONDO: XXXXXX

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

ORCID: XXXX-XXXX-XXXX

**Comment by sagehrke** [comment]
Hi @yshwetar - can this test ticket be closed? Thank you!

**Comment by yshwetar** [comment]
Yes! Thanks for checking.
