### ISSUE TITLE
synonym scope for ADNP-related multiple congenital anomalies - intellectual disability - autism spectrum disorder

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#7812]
Question from Paula Duek Roggli on slack

Why http://purl.obolibrary.org/obo/MONDO_0014379 has related synonym:
intellectual disability, autosomal dominant 28
ADNP syndrome
mental retardation, autosomal dominant 28
Could we consider them exact synonyms?
Why "Helsmoortel-VAN DER AA syndrome" is related? Is it because the definition of this disease is "non syndromic"? Even if exact maps to http://purl.obolibrary.org/obo/DOID_0070058?

**Comment by katiermullen** [comment]
In review of this term, MONDO:0014379, it is equivalent to OMIM:615873

The OMIIM label is HELSMOORTEL-VAN DER AA SYNDROME; HVDAS

Therefore, the synonym, Helsmoortel-VAN DER AA syndrome, should be considered an exact synonym. 

In addition, ADNP syndrome is considered both a related and exact synonym for this term. I think it should be exact based on the description of the disease in GARD:0012931.

These updates have been made.
