### ISSUE TITLE
Add Xrefs to MONDO:0005279 (pulmonary embolism)

### ISSUE THREAD

**Issue by hibaontoforce** [monarch-initiative/mondo#7829]
**Mondo term (ID and Label):**
MONDO:0005279 (pulmonary embolism)

**Xref that should be fixed (ID and label):**
equivalentTo: ICD10 I26: (Pulmonary embolism )

**Your nano-attribution (ORCID)**
0000-0002-6228-6214

**Other comments:**

**Comment by sagehrke** [comment]
Dear @hibaontoforce, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by twhetzel** [comment]
Thank you for the xref suggestion @hibaontoforce. This is included for MONDO:0005279.
