### ISSUE TITLE
congenital myasthenic syndrome 4

### ISSUE THREAD

**Issue by melnel000** [monarch-initiative/mondo#7831]
### Label

congenital myasthenic syndrome 4

### Synonym type

None

### Definition

Any congenital myasthenic syndrome in which the cause of the disease is a mutation in the CHRNE gene.

### Parent term

MONDO:0020344 postsynaptic congenital myasthenic syndrome   

### Children term(s)

MONDO:0011600 congenital myasthenic syndrome 4A, MONDO:0014586 congenital myasthenic syndrome 4B, MONDO:0012157  congenital myasthenic syndrome 4C

### ORCID Identifier

https://orcid.org/0000-0002-9698-992X

### Additional comments

We are not able to clinically classify our case (who harbours a pathogen bi-allelic CHRNE variant) into the definitions for congenital myasthenic syndrome 4A, B or C. Therefore, we are requesting a new MONDO ID for congenital myasthenic syndrome 4 referring to any congenital myasthenic syndrome in which the cause of the disease is a mutation in the CHRNE gene.

**Comment by sagehrke** [comment]
Dear @melnel000, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
