### ISSUE TITLE
MONDO:0859569:  fix capitalization

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#7832]
**Mondo term (ID Label)** MONDO:0859569; braddock-carey syndrome 1

**Bug/Typo/Error description**   change to Braddock-Carey syndrome 1

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @maglott, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by maglott** [comment]
Adding two more:


[endove syndrome, limb-only type]
MONDO:0030978
[endove syndrome, limb-brain type]
MONDO:0030979

endove is an acronym, should be ENDOVE
