### ISSUE TITLE
Neurofibromatosis 2

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7834]
Hi!  This is a request to add the following synonyms to Neurofibromatosis 2:

- NF2-Related Schwannomatosis
- Full NF2
- Full neurofibromatosis type 2
- Nonmosaic NF2-related schwannomatosis
- Nonmosaic neurofibromatosis type 2

Sources: 
https://www.ncbi.nlm.nih.gov/books/NBK1201/ 
https://www.orpha.net/en/disease/detail/637

Note that we have a NORD report entitled NF2-Related Schwannomatosis

Thank you!  Gioconda

**Comment by sagehrke** [comment]
Dear @galyea123,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
