### ISSUE TITLE
Request for new term "methicillin-susceptible staphylococcus aureus infectious disease"

### ISSUE THREAD

**Issue by nklsbckmnn** [monarch-initiative/mondo#7835]
### Label

methicillin-susceptible staphylococcus aureus infectious disease

### Synonym type

None

### Definition

Infections caused by a strain of Staphylococcus aureus that is susceptible to the action of the antibiotic methicillin.

### Parent term

MONDO:0005545

**Comment by sagehrke** [comment]
Dear @nklsbckmnn, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
