### ISSUE TITLE
Request for new term "Intestinal fistula"

### ISSUE THREAD

**Issue by nklsbckmnn** [monarch-initiative/mondo#7837]
### Label

Intestinal fistula

### Synonym type

None

### Definition

A pathologic tract that connects an opening in the intestine to some epithelial surface.

### Parent term

MONDO:0005020 intestinal disorder

### Children term(s)

MONDO:0000754 anal fistula

**Comment by sagehrke** [comment]
Dear @nklsbckmnn, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
