### ISSUE TITLE
Request for new term "Metastatic malignant neoplasm in the brain"

### ISSUE THREAD

**Issue by nklsbckmnn** [monarch-initiative/mondo#7839]
### Label

Metastatic malignant neoplasm in the brain

### Synonym type

None

### Definition

A metastatic malignant neoplasm affecting the brain.

### Parent term

MONDO:0001657 brain cancer or MONDO:00024880 metastatic malignant neoplasm

### Additional comments

Some "metastatic malignant neoplasms" are defined as "secondary neoplasms", "metastatic malignant neoplasm in the lymph nodes" is defined as "neoplasm". Cancers currently only include "neoplasms", but not "secondary neoplasms" which means that some "metastatic malignant neoplasms" are not cancers, while "metastatic malignant neoplasm in the lymph nodes" is. The textual definitions for some cancers also explicitly mention metastases.

**Comment by sagehrke** [comment]
Dear @nklsbckmnn, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
