### ISSUE TITLE
Request for new term "cerebral artery stenosis"

### ISSUE THREAD

**Issue by nklsbckmnn** [monarch-initiative/mondo#7840]
### Label

cerebral artery stenosis

### Synonym type

None

### Definition

Abnormal narrowing of a cerebral artery.

### Parent term

MONDO_0011057 cerebrovascular disorder

### Children term(s)

MONDO_0000944 cerebral artery occlusion

**Comment by sagehrke** [comment]
Dear @nklsbckmnn, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
