### ISSUE TITLE
MONDO:0015985 bone dysplasia, Azouz type [Obsolete]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7842]
**Mondo term (ID and Label)**
MONDO:0015985 bone dysplasia, Azouz type 

**Reason for deprecation**
The SNOMED CT entry in UMLS is now showing as obsolete; the GARD page shows as "under development" and the link from Gard to orphanet is on the retired record. 
MedGen does not have an active use case for this concept for submissions in GTR or ClinVar; it does not appear that there is much/any demand for this specific disease. 

**Suggested term to consider**
Per Orphanet's comment, they redirect to "Primary bone dysplasia with disorganized development of skeletal components" which is ORPHA:93450 (not in Mondo) 
or skeletal dysplasia http://purl.obolibrary.org/obo/MONDO_0018230

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems, 
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
bone dysplasia, Azouz type is not used in any other reference, and not referred to in medical literature. The term has been obsoleted #8350
