### ISSUE TITLE
Request for new term "sepsis"

### ISSUE THREAD

**Issue by nklsbckmnn** [monarch-initiative/mondo#7843]
### Label

infectious disease with sepsis

### Synonym type

None

### Definition

 An infection involving a dysregulated host response causing life-threatening organ dysfunction.

### Parent term

MONDO_0005550 infectious disease

### Children term(s)

MONDO_0700217 neonatal sepsis; MONDO_0005229 bacterial infectious disease with sepsis 

### Additional comments

https://jamanetwork.com/journals/jama/fullarticle/2492881

**Comment by sagehrke** [comment]
Dear @nklsbckmnn,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
