### ISSUE TITLE
Polymerase proofreading-associated polyposis

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#7845]
**Preferred gene-related syndrome label**

Polymerase proofreading-associated polyposis
(and ideally separate terms for the 

**Synonyms**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**

MONDO:0021057 classic or attenuated familial adenomatous polyposis (or a descendent)

**Definition**
Please write the definition in the format: Any [parent class] in which the cause of the disease is a mutation in the [gene name] gene. For example: Any congenital myopathy in which the cause of the disease is a mutation in the TPM3 gene.

A "classic or attenuated familial adenomatous polyposis" (I don't know which), caused by a defect in polymerase proofreading in which the cause of disease is a mutation in the  POLE or POLD1 genes.

Polymerase proofreading-associated polyposis (PPAP) is an [autosomal dominant](https://en.wikipedia.org/wiki/Autosomal_dominant) hereditary cancer syndrome, which is characterized by numerous polyps in the colon and an increased risk of [colorectal cancer](https://en.wikipedia.org/wiki/Colorectal_cancer).[[1]](https://en.wikipedia.org/wiki/Polymerase_proofreading-associated_polyposis#cite_note-Church-1) It is caused by [germline mutations](https://en.wikipedia.org/wiki/Germline_mutation) in [DNA polymerase](https://en.wikipedia.org/wiki/DNA_polymerase) ε ([POLE](https://en.wikipedia.org/wiki/POLE_(gene))) and δ ([POLD1](https://en.wikipedia.org/wiki/POLD1))

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)

https://en.wikipedia.org/wiki/Polymerase_proofreading-associated_polyposis

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by yshwetar** [comment]
Hi Val,

Does 'polymerase proofreading-related adenomatous polyposis; MONDO:0018653' represent the term you are looking to add?

Following the [Orphanet](https://www.orpha.net/en/disease/gene/list/447877?mode=name) and [Clingen](https://search.clinicalgenome.org/kb/conditions/MONDO:0018653) labels, this disease has mutations in the same genes.

**Comment by ValWood** [comment]
Yes that's it.

Do you know why this is correlated and not causal?

**Comment by yshwetar** [comment]
The two sub-categories of polymerase proofreading-related adenomatous polyposis (PPAP) are only correlated with PPAP, and have been implicated in other diseases. Therefore, PPAP itself is only correlated with these diseases as well. Hope this helps.
