### ISSUE TITLE
MONDO:0035433 &MONDO:0029133  Calpain-3-related limb-girdle muscular dystrophy D4[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7848]
**Mondo term (ID and Label)**
MONDO:0035433 Calpain-3-related limb-girdle muscular dystrophy D4

**Reason for deprecation**
Per Orphanet, this record is an exact match to OMIM [618129](https://omim.org/entry/618129)  http://www.orpha.net/ORDO/Orphanet_565909

**Term to be merged with**
MONDO:0029133 Muscular dystrophy, limb-girdle, autosomal dominant 4
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sagehrke** [comment]
Dear @kanems,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by twhetzel** [comment]
I agree these should be merged based on the reasons in the original post and disease descriptions for each term.
