### ISSUE TITLE
[NTR/gene] GBA1-related Parkinson disease

### ISSUE THREAD

**Issue by stromulus** [monarch-initiative/mondo#7859]
Hi! I am the chair of the ClinGen variant curation expert panel for GBA1-related Parkinson disease. We have already completed GCEP work and confirmed this to be a Definitive association. As far as I can tell, there is no current gene-related syndrome term in the ontology for this. I have not made a request to MONDO previously, so I appreciate your assistance on this matter. Please let me know if there is any other information you need.

**Preferred gene-related syndrome label**

GBA1-related Parkinson disease

**Synonyms**

GBA-related Parkinson's Disease

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Parkinson disease MONDO:0005180

**Definition**
Any increased susceptibility for developing Parkinson disease due to the presence of a monoallelic pathogenic variant, likely pathogenic variant, or risk allele in the _GBA1_ gene.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)

https://search.clinicalgenome.org/CCID:004931
PMID: 19858467
PMID: 19846850
PMID: 19433656

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
None

**Your nano-attribution (ORCID) or URL for a working group**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

0000-0003-3254-7564

**Comment by sagehrke** [comment]
Dear @stromulus,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your patience and for your contributions to Mondo!

Sincerely,
The Mondo Team
