### ISSUE TITLE
Update Mondo Outreach call page

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/mondo#7864]
Hi @twhetzel please update the following: 

- [x] for Toyofumi's topic, please update it to be his talk title: Enhancing Interoperability of Biomedical Resources Using Ontologies
- [x] Add the upcoming schedule to the table:
    - [x] July 26th - Summer Break
    - [x] August 23rd - Summer Break
    - [x] September 20 - Externally managed metadata in Mondo

Thank you! 🌟

**Comment by twhetzel** [comment]
The [page](https://mondo.monarchinitiative.org/pages/workshop/#outreach) is updated.
