### ISSUE TITLE
Request for new synonym MONDO:0016089

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/mondo#7868]
### Mondo term

infantile Krabbe disease

### Synonyms

infantile onset Krabbe disease, infantile-onset Krabbe disease

### Synonym type

exact

### Additional comments

PMID:20301416

**Comment by sagehrke** [comment]
Dear @peupeubangbang,
Thank you for reaching out to the Mondo Disease Ontology, part of the [Monarch Initiative](https://monarchinitiative.org/)!

We have received your ticket and will review it as soon as possible.

If you have any additional information or updates relevant to your inquiry, please add them in a comment on this ticket. Your input is valuable in helping us understand and resolve the issue effectively.

Thank you for your contributions to Mondo!

Sincerely,
The Mondo Team

**Comment by yshwetar** [comment]
_Infantile onset Krabbe disease should be an exact synonym of infantile Krabbe disease:_

Based on the article provided by the collaborator (PMID:20301416), **recommend including 'infantile-onset Krabbe disease' and 'infantile onset Krabbe disease' as exact synonyms for 'infantile Krabbe disease'.**
