### ISSUE TITLE
QC check for x-refs

### ISSUE THREAD

**Issue by katiermullen** [monarch-initiative/mondo#7872]
Could you please create a QC check (if it does not exist) to make sure that anytime there is a MONDO:preferredExternal that the x-ref also has the annotation MONDO:equivalentTo.

An example where I did not follow this rule is MONDO:1011429, the x-ref to OMIA:000605 should have the annotation MONDO:equivalentTo.

Note: the QC check should ensure that if an x-ref has a MONDO:relatedTo annotation it does not have a MONDO:preferredExternal annotation.

Finally, could you please add OMIA to the list of x-refs to QC: src/sparql/qc/general/qc-xref-without-source.sparql

Thank you!

---
Update from Trish:
- [ ] Create QC check to make sure that anytime there is an xref with source annotation `MONDO:preferredExternal` that there is also an xref source annotation of `MONDO:equivalentTo`
- [ ] Create QC check to make sure that anytime there is an xref with source annotation `MONDO:relatedTo` that it _does not_ also have an xref source annotation of `MONDO:preferredExternal`
- [ ] Add OMIA to the list of x-refs to QC: "src/sparql/qc/general/qc-xref-without-source.sparql"

**Comment by matentzn** [comment]
@sabrinatoro the only way for me to do this is if it ends up on a 1:1 meeting with us and I can do it then and there

**Comment by matentzn** [comment]
Its done: https://github.com/monarch-initiative/mondo/pull/8012
