### ISSUE TITLE
Request for new term "persistent atrial fibrillation"

### ISSUE THREAD

**Issue by nklsbckmnn** [monarch-initiative/mondo#7887]
### Label

Persistent atrial fibrillation

### Synonym type

None

### Definition

Atrial fibrillation that is continuous and sustains for >7 d.

### Parent term

MONDO_0004981 atrial fibrillation

### Additional comments

https://www.ahajournals.org/doi/10.1161/CIR.0000000000001193

**Comment by twhetzel** [comment]
@kanems this will be a new term (MONDO:1030009) mapped as 'equivalentTo' both MEDGEN:749907 and UMLS:C2585653.
