### ISSUE TITLE
ClinGen G6PD VCEP - response to issue 6252

### ISSUE THREAD

**Issue by mweaver88** [monarch-initiative/mondo#7890]
The ClinGen G6PD VCEP recommends trying to make the MONDO IDs consistent with the most recent WHO guidelines of the classification of G6PD deficiency ([https://www.who.int/publications/m/item/WHO-UCN-GMP-MPAG-2022.01](https://url.us.m.mimecastprotect.com/s/yQYrC0RXJXSKkGrUwKARy)), as these WHO guidelines should be the gold standard. The VCEP includes members of that WHO panel, and they have helped craft the proposed MONDO definitions above such that MONDO:0005775 corresponds to “WHO Class B”, and MONDO:0010480 corresponds to “WHO Class A” variants. As WHO Class C and U variants do not constitute a disease state, we did not feel the need to have MONDO IDs that correspond to these WHO classes.

**Mondo term (ID and Label)**
GCPD Deficiency (MONDO: 0005775)
G6PD deficiency, with chronic non-spherocytic hemolytic anemia (CNSHA)  (MONDO:0010480)

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
ClinGen G6PD VCEP proposed language:

G6PD deficiency - MONDO:0005775
An X-linked genetic condition caused by alterations in the gene G6PD that result in moderately to severely decreased activity levels of the enzyme glucose-6-phosphate dehydrogenase (G6PD). Most individuals with G6PD deficiency are asymptomatic throughout their life. Individuals with G6PD variants that cause G6PD deficiency are at risk for severe neonatal jaundice. These individuals are also at risk for acute hemolytic anemia in response to certain medication exposures, chemical exposures, infections, or consumption of fava beans. 

G6PD deficiency, with chronic non-spherocytic hemolytic anemia (CNSHA)  - MONDO:0010480
An X-linked genetic condition caused by alterations in the gene G6PD that result in severely decreased activity levels of the enzyme glucose-6-phosphate dehydrogenase (G6PD). Individuals with hemizygous or homozygous G6PD variants associated with chronic non-spherocytic hemolytic anemia (CNSHA) will clinically manifest CNSHA. Individuals with G6PD variants that cause CNSHA are also at risk for severe neonatal jaundice and acute exacerbation of their chronic hemolytic anemia in response to certain medication exposures, chemical exposures, infections, or consumption of fava beans.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by mweaver88** [comment]
Good morning, does the notice that the issue was closed two weeks ago mean that the proposed language changes are accepted?
Many thanks, Meredith

**Comment by sabrinatoro** [comment]
Hi @mweaver88 
yes, the proposed language changes had been accepted. I reviewed what we had and made very minor typos/wording updates.
