### ISSUE TITLE
NTR: spastic triplegia

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/mondo#7919]
### Label

spastic triplegia

### Synonyms

triplegia spastic, spastic triplegic, triplegic spastic, triplegic spasticity, triplegic cerebral palsy, triplegic CP

### Synonym type

exact

### Definition

Spastic weakness found in three limbs, most commonly both lower extremities and one upper extremity.

### Parent term

MONDO:0000396 spastic cerebral palsy

### Additional comments

**Exact xrefs** 
SCTID:702320006
UMLS:C5676777
HP:0034183

**Comment by sabrinatoro** [comment]
Hi @kanems, I would like your opinion on this issue. 

I found 2 terms in MedGen (both "disease or syndrome"):
- Spastic triplegia:  [MedGen UID: 1814346](https://www.ncbi.nlm.nih.gov/medgen/?term=Spastic+triplegia); Concept ID: C5676777; xref: HP:0034183
- Triplegic cerebral palsy:  [MedGen UID: 825116](https://www.ncbi.nlm.nih.gov/medgen/?term=C3839271); Concept ID: C3839271 ; xref: SNOMED CT:702320006

What is the difference between these 2 terms? My original thought was that "spastic triplegia" referred to a "feature" or a "phenotype", but they are both reported as "disease or syndrome".

Thank you for your help!

**Comment by kanems** [comment]
The CUI from UMLS C5676777 has the semantic type of Disease or Syndrome; but internally we would classify the concept of Spastic triplegia as a Finding because the only source we have for this is HPO, thus it should be a phenotype. I can follow up with UMLS to see if they can update this semantic type in the next release.

**Comment by sabrinatoro** [comment]
Thank you @kanems, that was my suspicion. Have a nice day!

**Comment by sabrinatoro** [comment]
@kanems 
I just want to let you know that I created a new term and I added the following MedGen and UMLS x-ref. These will be updated based on your mapping later. Please let me know if you have any questions. Thank you! 

id: MONDO:0700279
name: spastic triplegia
xref: MEDGEN:825116 {source="MONDO:equivalentTo"}
xref: SCTID:702320006 {source="MONDO:equivalentTo"}
xref: UMLS:C3839271 {source="MONDO:equivalentTo"}
