### ISSUE TITLE
NTR: spastic dystonia

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/mondo#7920]
### Label

spastic dystonia

### Synonyms

dystonic spasticity, spastic dystonic, dystonic spastic, dystonic/spastic, spastic/dystonic, dystonic-spastic, spastic-dystonic

### Synonym type

exact

### Definition

Characterized by involuntary tonic muscle contraction, spastic dystonia is a subset of dystonia with pathophysiological mechanisms more in common with spasticity.
PMID: 36940234

### Parent term

MONDO:0000400 mixed cerebral palsy

### Additional comments

**XREFs exact**
UMLS:C1838879

**Comment by sabrinatoro** [comment]
@pnrobinson can I get your opinion on this issue? (or the one of your Cerebral palsy experts @jagcsun)

- MedGen report [spastic dystonia](https://www.ncbi.nlm.nih.gov/medgen/?term=C1838879) as a finding, and not a disease or syndrome. 
- PMID:29161622; PMID:36940234: it looks like "spastic dystonia" is a phenotype, however, one could argue that it could also be a disease/disorder (then maybe it should be called "isolated" spastic dystonia; though I don't know if it makes sense). 

What do you think? Is this term a type of "mixed cerebral palsy" (the disease/disorder) and therefore should be in Mondo)? Or do you think there is no evidence that this is disease/disorder and should be solely viewed as a phenotype (and therefore not be in Mondo). 

Thank you for your help!

**Comment by pnrobinson** [comment]
This is not a disease.
It is a "bundled" finding and should be coded by the HPO two terms for Spasticity and for Dystonia

**Comment by kanems** [comment]
For what it's worth, the only source for this entry in UMLS is OMIM, specifically as a clinical descriptor from their clinical synopses.
![image](https://github.com/user-attachments/assets/4e6ee59b-5a3a-4394-b05f-7d4f05393d1d)
(I see it's on these MIM entries: [# 535000](https://www.omim.org/entry/535000) [# 619487](https://www.omim.org/entry/619487) )

**Comment by sabrinatoro** [comment]
Thank you @pnrobinson and @kanems 

@peupeubangbang Thank you for your request. As discussed in this issue, the term you requested refers to phenotypes, and not to a specific disease concept. Therefore the term you requested will not be added into Mondo. 

You can use the following HPO terms instead: 
- HP:0001257 - Spasticity - http://purl.obolibrary.org/obo/HP_0001257
- HP:0001332 - Dystonia - http://purl.obolibrary.org/obo/HP_0001332

Please let me know if you have any questions. Thank you!
