### ISSUE TITLE
Bulk request for new gene related syndrome terms from ClinGen Retina GCEP

### ISSUE THREAD

**Issue by wchankey** [monarch-initiative/mondo#7923]
**Preferred gene-related syndrome label**
Please see attached Excel sheet below for 23 proposed gene-related syndrome labels.

**Synonyms**
Please see attached Excel sheet below for synonyms for 23 proposed gene-related syndrome labels.

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Please see attached Excel sheet below for parent terms for 23 proposed gene-related syndrome labels.

**Definition**
Please see attached Excel sheet below for definitions for 23 proposed gene-related syndrome labels.

**Definition source (Please give PubMed ID, if applicable, in format PMID:####
ClinGen Retina Gene Curation Expert Panel

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 
Please see attached Excel sheet below for children terms for 23 proposed gene-related syndrome labels.

**Your nano-attribution (ORCID) or URL for a working group**
ORCID ID = 0000-0001-5935-2391 / https://clinicalgenome.org/working-groups/clinical-domain/ocular-cdwg/

[Batch_TermRequests_ClinGenRetinaGCEP_07012024.xlsx](https://github.com/user-attachments/files/16112555/Batch_TermRequests_ClinGenRetinaGCEP_07012024.xlsx)

**Comment by yshwetar** [comment]
Hi @wchankey!

A few changes/additions were made in the pull requests above.

For #8144
- Through literature search, found achromatoposia 5 to be a child of new term 'PDE6C-related retinopathy' and was added as so ([LSWG curation](https://search.clinicalgenome.org/kb/genes/HGNC:8787)).

For #8145
- New term submission 'KCNV2-related retinopathy' has an exact synonym of a term already present in MONDO, 'cone dystrophy with supernormal rod response (MONDO:0012475)'. No new term was made, and instead 'KCNV2-related retinopathy' was made an exact synonym of 'cone dystrophy with supernormal rod response (MONDO:0012475)'.
- Through literature search, found retinopathy of prematurity to be a child of new term 'FZD4-related exudative vitreoretinopathy' and was added as so ([LSWG curation](https://search.clinicalgenome.org/kb/genes/HGNC:4042)).

For #8151
- PROM1-related dominant retinopathy and PROM1-related recessive retinopathy were both proposed as new terms. However they both have the same child, cone rod dystrophy 12. A disease can't be a child of the same disease in both the AD and AR states in MONDO. Therefore, we decided to create the parent term PROM1-related retinopahy, with the three children terms: PROM1-related dominant retinopathy, PROM1-related recessive retinopathy, and cone rod dystrophy 12.
- An additional literature search showed fundus albipunctatus to be a child of PRPH2-related retinopathy, and was added as so ([LSWG curation](https://search.clinicalgenome.org/kb/genes/HGNC:9942)).

Let us know your thoughts and if these are appropriate. Thank you!

Yousif
