### ISSUE TITLE
MONDO:0000432 Self-Loop JSON Loading

### ISSUE THREAD

**Issue by iimpulse** [monarch-initiative/mondo#7935]
**MONDO:0000432**

**Bug/Typo/Error description**
When loading the simple base graph with our internal ontology load phenol we fail to parse the graph to due a self referencing loop. 

`Self-loop edge: Relationship [source=MONDO:0000432, target=MONDO:0000432, id=361, relationshipType=RelationshipType{id='http://purl.obolibrary.org/obo/RO_0004029', label='disease has feature'}]',`

https://orcid.org/0000-0002-2157-3591

**Comment by matentzn** [comment]
Which file are you using?

**Comment by matentzn** [comment]
This is the cycle:

```
[Term]
id: MONDO:0000432
....
relationship: disease_has_feature MONDO:0000432 {source="MONDO:Wikidata"} ! lymphoplasmacytic lymphoma
```

MONDO:0000432 is a phenotypic feature of itself.

- [ ] Add QC check to ensure this does not happen again
- [ ] Fix by removing the `disease_has_feature MONDO:0000432` assertion

**Comment by matentzn** [comment]
Here is the qc check that need to be added:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix IAO: <http://purl.obolibrary.org/obo/IAO_>
prefix MONDO: <http://purl.obolibrary.org/obo/MONDO_>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX RO: <http://purl.obolibrary.org/obo/RO_>


SELECT ?entity ?property ?value 

WHERE
{
  VALUES ?property { RO:0004003 RO:0004029 }
  ?entity rdfs:subClassOf [
        owl:onProperty ?property ;
        owl:someValuesFrom ?entity
      ] .
  BIND ("Self cycle detected" as ?value)
} 

```

@twhetzel can you take this on? This is a real bug and should be fixed before the release I think!

**Comment by twhetzel** [comment]
Sure, I can do this.
