### ISSUE TITLE
MONDO:0014606- Spelling Error in Definition

### ISSUE THREAD

**Issue by madysoncbrown** [monarch-initiative/mondo#7964]
Intellectual disability-microcephaly-strabismus-behavioral abnormalities syndrome (MONDO:0014606)

In the definition for MONDO:0014606 the word "aggressiveness" was spelled incorrectly:

"Intellectual disability-microcephaly-strabismus-behavioral abnormalities syndrome is a rare, genetic, syndromic intellectual disability disorder characterized by craniofacial dysmorphism (microcephaly, hypotonic facies, strabismus, long and flat malar region, posteriorly rotated ears, flat nasal bridge with broad nasal tip, short philtrum, thin vermillion border, open mouth with down-turned corners, high arched palate, pointed chin), global developmental delay, intellectual disability and variable neurobehavioral abnormalities (autism spectrum disorder, **_aggressivness_**, self injury). Additional features include vision abnormalities and variable sensorineural hearing loss, as well as short stature, hypotonia and gastrointestinal manifestations (e.g. poor feeding, gastroesophageal reflux, constipation)."

https://www.clinicalgenome.org/curation-activities/dosage-sensitivity/
https://search.clinicalgenome.org/kb/gene-dosage/HGNC:18801

@elizabeth-gavrilov
@ErinRiggs

**Comment by katiermullen** [comment]
@madysoncbrown 

Thank you for submitting this issue! The error has been fixed and will appear corrected in the next Mondo release.
