### ISSUE TITLE
weiss-kruszka syndrome (MONDO:0032836)- Relabel Weiss-Kruszka Syndrome

### ISSUE THREAD

**Issue by madysoncbrown** [monarch-initiative/mondo#7965]
weiss-kruszka syndrome (MONDO:0032836)

Weiss-Kruszka Syndrome

The ClinGen Dosage Sensitivity team received a notice of obsoletion for weiss-kruska syndrome due to it being a "duplicate". The notice stated that this MONDO term will be merged with MONDO:0044715 "metopic ridging-ptosis-facial dysmorphism syndrome".

This impacts the Dosage Sensitivity WG curation for ZNF462.

Can we please discuss not obsoleting Weiss-Kruszka Syndrome because "metopic ridging-ptosis-facial dysmorphism syndrome" does not encompass the neurodevelopmental phenotype. If you do decide moving forward with changing the name could there please be a neurodevelopmental phenotype added into the name of the new MONDO term as well. 

Preferably we would like to keep the term Weiss-Kruszka Syndrome and additionally request that the name please be capitalized. Weiss-Kruszka is the name in OMIM and is the name of the GeneReviews ([Weiss-Kruszka Syndrome - GeneReviews® - NCBI Bookshelf (nih.gov)](https://www.ncbi.nlm.nih.gov/sites/books/NBK549204/)). Please keep us updated. 

https://www.clinicalgenome.org/curation-activities/dosage-sensitivity/

@elizabeth-gavrilov
@ErinRiggs

**Comment by ErinRiggs** [comment]
Hello - can someone please update us on the status of this request?  We keep seeing it each month on the planned obsoletion report that gets sent to ClinGen, and I'd like some resolution.
Thanks,
Erin

**Comment by sabrinatoro** [comment]
Hello @ErinRiggs. 
We have received a lot of user requests, and we haven't reached this issue yet. Thank you for bringing our attention to it.
I will take a look right now and update you. 
Thank you for your patience.

**Comment by ErinRiggs** [comment]
Thanks Sabrina - we just wanted to make sure our objection was logged and that it wasn't obsoleted without further discussion :)

**Comment by sabrinatoro** [comment]
Based on the information in this issue, the terms 'Weiss-Kruszka syndrome' (MONDO:0032836) and 'metopic ridging-ptosis-facial dysmorphism syndrome' do not refer to identical disease concepts. 
I made 'Weiss-Kruszka syndrome' (MONDO:0032836) "protected from obsoletion" and updated the capitalization of the term label. 

These changes will be available in the next Mondo release.

**Comment by ErinRiggs** [comment]
Thanks Sabrina!  And thank you for also fixing the capitalization!
