### ISSUE TITLE
Incorrect ICD10 mapping for undifferentiated carcinoma of the corpus uteri

### ISSUE THREAD

**Issue by may-lim** [monarch-initiative/mondo#7998]
**Mondo term (ID and Label):**
MONDO:0016267 
undifferentiated carcinoma of the corpus uteri

**Xref that should be fixed (ID and label):**
ICD10CM:C50 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
https://orcid.org/0000-0002-7347-2434

**Other comments:**
C50 refers to breast cancer whereas the Mondo ID refers to a uterine cancer, perhaps C54.9 is more appropriate

**Comment by katiermullen** [comment]
@may-lim thank you for this request!

The ICD10 mapping for MONDO:0016267 'undifferentiated carcinoma of the corpus uteri' has been corrected to C54.9.

In addition, the  ICD10 mapping for MONDO:0016266 'squamous cell carcinoma of the corpus uteri' to C54.1 based on https://www.orpha.net/en/disease/detail/213716

These changes will appear in the next release of Mondo.
