### ISSUE TITLE
Request for new synonym Complex neurodevelopmental disorder with or without aldosteronism

### ISSUE THREAD

**Issue by Jciesielka1** [monarch-initiative/mondo#7999]
### Mondo term

0014200: Aldosterone-producing adenoma with seizures and neurological abnormalities

### Synonyms

Complex neurodevelopmental disorder with or without aldosteronism

### Synonym type

None

### Additional comments

Please add the following definition for this term: An autosomal dominant neurodevelopmental condition related to variants in CACNA1D. Most reported variants are de novo and functional studies have indicated a gain-of-function disease mechanism (PMIDs: 23913001, 37122292). This condition is characterized by developmental delay/intellectual disability, autism spectrum disorder, hypotonia and seizures (PMIDs: 32666275, 37122292). Other reported features include endocrine abnormalities such as primary aldosteronism and congenital hyperinsulinemic hypoglycemia, self-injurious behavior, facial dysmorphisms, and heart defects.

**Comment by ErinRiggs** [comment]
Hello - just checking on the status of this request?
