### ISSUE TITLE
MONDO_0021937 Asrar Facharzt Haque syndrome is the same as MONDO_0011273 'H syndrome'?

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#80]
I believe **MONDO_0021937 Asrar Facharzt Haque syndrome** is a synonym for **MONDO_0011273 'H syndrome'**.

[Gard](https://rarediseases.info.nih.gov/diseases/581/asrar-facharzt-haque-syndrome) links out to this [paper](https://www-ncbi-nlm-nih-gov.liboff.ohsu.edu/pubmed/?term=9572458). The syndrome is named after the authors names, and it is also called Rosai-Dorfman disease, I believe.

I think those two classes should be merged.

**Comment by cmungall** [comment]
Thanks! I will take care of this.

I just added a new label 'merge request' (duplicate is for dupe tickets not classes!)

**Comment by cmungall** [comment]
cc @GARDInfoCenter
