### ISSUE TITLE
fix ICD10 xref on isolated agammaglobulinemia

### ISSUE THREAD

**Issue by rwst** [monarch-initiative/mondo#800]
**Mondo term (ID and Label):**
MONDO:0016462 isolated agammaglobulinemia

**Xref that should be fixed (ID and label):**
ICD10:E80.0

**Other comments:**
D80.0 is the closest match (but not exact as there could be non-hereditary isolated agammaglobulinemias)

**Comment by nicolevasilevsky** [comment]
@cmungall this xref to ICD10:E80.0 comes from Orphanet (Orphanet:229717). Do we want to replace it?

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet and @annieolry and @Orphanet - please note the comment above
