### ISSUE TITLE
Request for new term "hypertensive urgency"

### ISSUE THREAD

**Issue by nklsbckmnn** [monarch-initiative/mondo#8005]
### Label

hypertensive urgency

### Synonym type

None

### Definition

Severe hypertension that is characterized by rapid onset of extremely high blood pressure without hypertension-mediated organ damage.

### Parent term

MONDO:0005044 (hypertensive disorder)

**Comment by twhetzel** [comment]
I agree with the user request to add this new term as it is also found in other ontologies such as SNOMED, NCIT, ICD11 and UMLS.
