### ISSUE TITLE
Request for new synonyms: infantile Krabbe disease

### ISSUE THREAD

**Issue by peupeubangbang** [monarch-initiative/mondo#8029]
### Mondo term

infantile Krabbe disease MONDO:0016089

### Synonyms

early onset Krabbe disease, early-onset Krabbe disease, early symptomatic Krabbe disease

### Synonym type

exact

### Additional comments

PMID:20301416
PMID:30777126

**Comment by peupeubangbang** [comment]
@ehurwitz sorry for the work ive caused for PR #8110 just added in Pubmed IDs then.

Also I forgot to put in the last word **disease** for the synonym request "early symptomatic Krabbe **disease**" if you wouldn't mind adding that in? (I've updated the issue)

Thanks for your help!

**Comment by ehurwitz** [comment]
@peupeubangbang No problem at all! I I updated the synonym to include the word 'disease'. And thank you very much for providing the PMIDs!
