### ISSUE TITLE
Conflicting IRIs for OMIM identifiers

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/mondo#804]
Our scigraph data graph has two iri patterns for OMIM identifiers,

Purl version:
https://scigraph-data-dev.monarchinitiative.org/scigraph/graph/neighbors.png?id=OBO%3AOMIM_105830&depth=1&blankNodes=false&direction=BOTH&entail=false

OMIM version:
https://scigraph-data-dev.monarchinitiative.org/scigraph/graph/neighbors.png?id=OMIM:105830&depth=1&blankNodes=false&direction=BOTH&entail=false&relationshipType=RO:0002200

The consequence is that the mondo graph is not connected to the dipper a-box graph.  This means we're missing closures, not categorizing the ids as diseases, and not clique merging.

Potential paths forward:
- Change dipper iris back to purls
- Convert omim ids to purls before they are ingested by scigraph
- Change mondo omim IRIs

This is a blocker for releasing our db.

**Comment by ShahimEssaid** [comment]
@kshefchek  Let's talk this coming week so I can understand how I can help. I'm not that familiar with the other pieces of this issue.

**Comment by kshefchek** [comment]
To distill it down, we want to make sure we are using the exact same IRIs in dipper and MONDO, essentially:

In dipper we're currently using
OMIM:
http://omim.org/entry/1234
OMIMPS:
http://www.omim.org/phenotypicSeries/PS1234

As is stands, MONDO uses
http://purl.obolibrary.org/obo/OMIM_1234
for skosExactMatch: "http://identifiers.org/omim/1234"
OMIMPS:
http://purl.obolibrary.org/obo/OMIMPS_1234

We have a terrible hack to normalize the IRIs after building monarch.owl.

**Comment by nicolevasilevsky** [comment]
@kshefchek is this still an issue?
