### ISSUE TITLE
MONDO:0011893 & MONDO:0011226 (DEAFNESS, AUTOSOMAL DOMINANT 15/52)[Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#8059]
**Mondo term (ID and Label)**
MONDO:0011893 autosomal dominant nonsyndromic hearing loss 52

**Reason for deprecation**
OMIM merged https://www.omim.org/entry/607683 
This entry was incorporated into [602459](https://www.omim.org/entry/602459) on August 7, 2024.

**Term to be merged with**
MONDO:0011226 Autosomal dominant nonsyndromic hearing loss 15 

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by twhetzel** [comment]
Thank you @kanems. This will be merged and the update available in the next Mondo release.
