### ISSUE TITLE
"prostate cancer, hereditary"

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#8060]
all "prostate cancer, hereditary" are incorrectly classified in mondo as "familial prostate carcinoma" (these could be carcinoma or non-carcinoma). 
There is no source annotation to support this incorrect classification.

This issue was created as part of the OMIM alignment for the September release.

**Comment by sabrinatoro** [comment]
Though most prostate cancers are carcinoma, we cannot say that all of them are. 
Therefore, I created the new term: "prostate cancer, hereditary" (MONDO:0700275).

The following x-ref were previously equivalent to 'familial prostate carcinoma' (MONDO:0023122), I think they should be equivalent to this new term instead: 
- [OMIM:176807](https://omim.org/entry/176807)
- [Orphanet:1331](https://www.orpha.net/en/disease/detail/1331)
- SCTID:715412008
- MESH:C537243

@kanems : the following x-refs are currently exact to 'familial prostate carcinoma' (MONDO:0023122); I think they would map to this new "prostate cancer, hereditary" (MONDO:0700275) instead
- MEDGEN:419810
- UMLS:C2931456

@ericsid: the following x-refs are currently exact to 'familial prostate carcinoma' (MONDO:0023122); I think they would map to this new "prostate cancer, hereditary" (MONDO:0700275) instead
GARD:4520



In addition, I made all "prostate cancer, hereditary" diseases children of this new term 'prostate cancer, hereditary' (MONDO:0700275) instead of them being children of 'familial prostate carcinoma' (MONDO:0023122) (there were no sources for the 'familial prostate carcinoma' parentage)
The ontology therefore looks like this: 
![Screenshot 2024-08-20 at 3 18 42 PM](https://github.com/user-attachments/assets/8d506ab0-dd75-4fd6-b8fa-9afb8fd0203c)

**Comment by kanems** [comment]
I agree with the CUI and MedGen concept mapping to the new term. I'll go ahead and move the existing identifier for familial prostate _carcinoma_ to a new entry in MedGen. We'll use the UMLS CUI for this concept- C4722328 Hereditary Prostate Carcinoma with an NCI term: C103817.
I've updated it in our system now, should be available in the next 24-48 hours on the web and FTP downloads to get the new MedGen UID for the 'carcinoma' term.

**Comment by sabrinatoro** [comment]
Thank you @kanems

**Comment by nicolevasilevsky** [comment]
sounds good to me too @sabrinatoro!
