### ISSUE TITLE
keratoconus

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#8068]
Hi!  Keratoconus was obsoleted in Orphanet and recent publications show that is not rare in USA either. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9375461/
https://www.aoa.org/news/clinical-eye-care/diseases-and-conditions/pediatric-keratoconus-prevalence-higher-than-believed-may-change-care-approach?sso=y
https://journals.lww.com/claojournal/abstract/2021/09000/estimated_prevalence_of_keratoconus_in_the_united.5.aspx

Thank you!  

Gioconda Alyea

**Comment by sabrinatoro** [comment]
Thank you @galyea123. 
All rare disease subsets are maintained automatically based on external sources. We will share this information with the rare disease source so they can update their rare disease list that Mondo ingests.

**Comment by sabrinatoro** [comment]
@ericsid
Please see above: keratoconus (MONDO:0015486) is no longer considered rare in the US. You might want to review your rare disease association with this term. Thank you!
