### ISSUE TITLE
Request for new term [sycosis barbae]

### ISSUE THREAD

**Issue by paulacalipho** [monarch-initiative/mondo#8081]
### Label

sycosis barbae

### Synonyms

bacterial folliculitis

### Synonym type

related

### Definition

Bacterial folliculitis of the beard and/or mustache areas, usually caused by _Staphylococcus aureus_.
http://purl.obolibrary.org/obo/DERMO_0002078

### Parent term

MONDO:0006552 folliculitis MONDO:0005113 bacterial infectious disease

### ORCID Identifier

https://orcid.org/0000-0002-0819-0473

### Additional comments
Term request done in the context of the OBO Community Challenge 2024

**Reference for synonym**
PMID:33085351 reference for RELATED synonym "bacterial folliculitis"
Uncertain whether the integration of a related synonym is beneficial or will create confusion.

**Parent term**
Uncertain whether to consider this term SubClassOf MONDO:0005545 'staphylococcus aureus infection' because definition indicates only “usually”.

**Term in other terminologies**
sycosis barbae -[ http://purl.bioontology.org/ontology/MEDDRA/10042731](http://purl.bioontology.org/ontology/MEDDRA/10042731)
sycosis barbae -[ http://purl.bioontology.org/ontology/SNOMEDCT/156410002](http://purl.bioontology.org/ontology/SNOMEDCT/156410002)

**Additional comments that may require to open a different issue**
The following terms could also be subClassOf MONDO:0006552 folliculitis based on DERMO ontology:
MONDO:0021660 'deep seated dermatophytosis'
MONDO:0000242 'tinea barbae'
MONDO:0002260 hidradenitis (and childs)
MONDO:0012865 'Pseudofolliculitis barbae'

Many thanks MONDO!

**Comment by sabrinatoro** [comment]
> Parent term
Uncertain whether to consider this term SubClassOf MONDO:0005545 'staphylococcus aureus infection' because definition indicates only “usually”.

You are correct: since the definition indicates it is "usually" due to a staphylococcus aureus infection, it is not 100% of the cases, therefore the parent  'staphylococcus aureus infection' would not be correct.
