### ISSUE TITLE
MONDO_0017579 Baraitser-Winter cerebrofrontofacial syndrome reference to an ExactSynonym to an non-exist MONDO ID

### ISSUE THREAD

**Issue by linikujp** [monarch-initiative/mondo#8085]
**Mondo term (ID Label)**
Baraitser-Winter cerebrofrontofacial syndrome

**Bug/Typo/Error description**
The ExactSynonym of this term is Baraitser-winter syndrome, which reference to MONDO 0000719 (no longer a MONDO valid ID) via DbXref. 

**Your nano-attribution (ORCID)**
0000-0003-2620-0345

**Comment by katiermullen** [comment]
Hi @linikujp thank you for submitting this issue!

The term MONDO:0017579 'Baraitser-Winter cerebrofrontofacial syndrome' has the db-xref to the obsoleted Mondo term MONDO:0000719 'obsolete Baraitser-winter syndrome' that was merged with this term. 

Mondo maintains db-xrefs to Mondo terms that have been obsoleted and merged with another Mondo term as standard practice.

In this case, we have also included an additional db-xref for the syn  'Baraitser-winter syndrome,' Orphanet:2995. This will appear in the next Mondo release.

Please note that we are working on an automated pipeline to updated db-xrefs. Thank you!
