### ISSUE TITLE
MONDO hasExactSyn axiom DbXref points to an ORCID ID

### ISSUE THREAD

**Issue by linikujp** [monarch-initiative/mondo#8089]
**Mondo term (ID Label)**
Below screen shot is for one MONDO term: myotonic dystrophy MONDO:0016107; but I believe I have seen this during other terms' search in CENTree. 
![image](https://github.com/user-attachments/assets/e291f474-7eb7-408b-8ace-a87b48edc767)

**Bug/Typo/Error description**
You could check if this bug exist in other terms. See my another related issue about dbXref in ExactSyn use (https://github.com/monarch-initiative/mondo/issues/8085). This probably a QC issue where the dbXref is not correctly parsed. 

**Your nano-attribution (ORCID)**
0000-0003-2620-0345

**Comment by katiermullen** [comment]
@linikujp Thank you for submitting this issue!

In Mondo, an ORCID is an acceptable db-xref. 

The ORCID is used to give credit to the requester of, in this case, the synonym. If additional db-xrefs are available, they will be added as well.

Please note that we are working on an automated pipeline to updated db-xrefs. Thank you!
