### ISSUE TITLE
merge brucellosis, bovine + Brucella abortus brucellosis

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#809]
Also: add axiom linking too ncbitaxon

**Comment by pnrobinson** [comment]
I am not convinced that we should be working on animal diseases right now, but in any case these are not synonymous because at least 3 types of Brucella can cause bovine brucellosis
https://www.aphis.usda.gov/animal_health/animal_diseases/brucellosis/downloads/bruc-facts.pdf
