### ISSUE TITLE
ILD and SFTPC Relabing

### ISSUE THREAD

**Issue by ekendall2** [monarch-initiative/mondo#8104]
**Mondo term (ID and Label):** MONDO:0018603, interstitial lung disease due to SP-C dysfunction

**Suggested new label:** SFTPC- related interstitial lung disease

**Your nano-attribution (ORCID)** https://orcid.org/0009-0009-7379-954X
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)** 

[Mondo Relabeling Request Tree .pdf](https://github.com/user-attachments/files/16732103/Mondo.Relabeling.Request.Tree.pdf)

**Comment by nicolevasilevsky** [comment]
@ekendall2 is this ticket only asking for the one term to be relabeled or do you have additional requests as outlined in the attached PDF?
