### ISSUE TITLE
[Obsolete] Syndrome due to FAR1 deficiency

### ISSUE THREAD

**Issue by jmcglaughon** [monarch-initiative/mondo#811]
**Mondo term (ID and Label)** severe intellectual disability-epilepsy-cataract syndrome due to fatty acyl-CoA reductase 1 deficiency (MONDO:0014510)

**Reason for deprecation** There is currently only one publication with patients that have this disorder (PMID: 25439727), so it cannot be assumed that all patients with FAR1 deficiency will have severe intellectual disability, epilepsy, and cataracts. Naming the disease for the deficiency, rather than the phenotype, would be more inclusive.

**Suggested replacement or term to consider** Fatty acyl-CoA reductase 1 disorder or fatty acyl-CoA reductase 1 deficiency.

@nicolevasilevsky This is a ClinGen request

**Comment by annieolry** [comment]
On the other hand, if there is a new description of patients with FAR1 deficiency with a very different phenotype, it will be usefull to have different codes for the various phenotypes. This issue refers directly to general rules adopted when maintaining a terminology and making decision on this kind of issue should follow a more general policy to avoid discrepancies in a specific field (metabolic one in this case). Choosing a clinical or a metabolic name heavily depend on the purpose of the use of the terminology. Both are acceptable, they just depend of the use case.

**Comment by nicolevasilevsky** [comment]
@jmcglaughon Sounds like there is a case for keeping this term. Is that okay with you?

**Comment by nicolevasilevsky** [comment]
@jmcglaughon following up, now that we are back from the holidays. Thanks!

**Comment by courtneythaxton** [comment]
Hi @nicolevasilevsky , Jen McGlaughon has moved on from ClinGen. I will take this question back to the ClinGen Peroxisomal Deficiency GCEP for consideration.

**Comment by courtneythaxton** [comment]
I just reviewed this with the group. At this time in ClinGen, there are only 3 published case reports with individuals asserted with a variation in FAR1. Thus, the gene-disease classification is preliminary "Limited". Given this clinical validity classification, it seems that there is not enough data on individuals to suggest that the FAR1 variation is really causing the phenotypes asserted for the individuals (e.g. intellectual deficiency, epilepsy, cataract). Given this classification and lack of data, we feel that the disease entity at this time is really the metabolic deficiency, and thus would prefer to have the disease entity termed: Fatty acyl-CoA reductase 1 disorder or fatty acyl-CoA reductase 1 deficiency.

@annieolry Does this explanation seem reasonable to you.
tagging @nicolevasilevsky  as well.

**Comment by nicolevasilevsky** [comment]
Ok - to clarify @courtneythaxton, you would like MONDO_0014510 to be relabeled to 'Fatty acyl-CoA reductase 1 disorder or fatty acyl-CoA reductase 1 deficiency'?

Thanks!

**Comment by courtneythaxton** [comment]
Hi @nicolevasilevsky that is correct! Please do NOT obsolete. We are performing a curation on this FAR1 gene in the Aminoacidoapathy Gene Curation Expert Panel.

**Comment by annieolry** [comment]
Hi @courtneythaxton, thanks for your comment, it sounds perfectly reasonable! Orphanet will also change the name to "Fatty acyl-CoA reductase 1 disorder".

**Comment by courtneythaxton** [comment]
@nicolevasilevsky 

I wanted to update can we call it simply "fatty acyl-CoA reductase 1 deficiency." the Fatty acyl-CoA reductase 1 disorder could be considered a synonym.

Thanks!
@courtneythaxton

**Comment by nicolevasilevsky** [comment]
sounds good, done
