### ISSUE TITLE
Interstitial Lung Disease in Anti-MDA5 Positive Dermatomyositis

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#8118]
### Label

Anti-melanoma differentiation-associated gene 5-positive dermatomyositis 

### Synonyms

Anti–MDA5 Antibody Positive Dermatomyositis, MDA-5 DM, MDA5+ DM

### Synonym type

exact

### Definition

Hi!  After an inquiry from a patient diagnosed with this condition I searched MONDO and Orphanet and found that this term it is not listed (I sent them a ticket as well) .  

You do list Amyopathic dermatomyositis MONDO:0043317 which is also in Orphanet https://www.orpha.net/en/disease/detail/645626 but you do not include the term "Clinically Amyopathic Dermatomyositis" (CADM) as a synonym. (Note that Amyopathic Dermatomyositis (ADM) and hypomyopathic Dermatomyositis (HDM), together are referred to as Clinically Amyopathic Dermatomyositis (CADM) and are subsets of Dermatomyositis (DM), one of the Idiopathic Inflammatory Myopathies)".

In the Orphanet  page about  Dermatomyositis ORPHA:221  they do mention the MDA5 antibody: "Anti-MDA5 DM (5-20%) present with classical skin lesions, ulcerations, mechanic's hands, arthritis, pulmonary involvement, and no or mild muscle involvement."
 
As per a review that includes the terminology, "Anti-melanoma differentiation-associated gene 5-positive dermatomyositis (MDA5+ DM) is a rare but distinct subtype of idiopathic inflammatory myopathy, which has been reported worldwide, but predominantly in East Asia.  The clinical features include dermatomyositis rashes, amyopathic or hypomyopathic muscle involvement and interstitial lung disease, frequently as a rapid progressive course and high mortality.  Before the identification of the serology hallmark for this disease, i.e., anti-MDA5 autoAB the nomenclature was "clinically amyopahtic dermatomyositis" (CADM)". https://pubmed.ncbi.nlm.nih.gov/33405101/

See also: https://www.mdpi.com/2674-0621/4/1/4 (a review from 2024 that I found very helpful) 
See pubmed: https://pubmed.ncbi.nlm.nih.gov/?term=Anti-melanoma+differentiation-associated+gene+5+%28MDA-5%29+dermatomyositis+%28DM%29+

Please consider reviewing this term for inclusion,
Gioconda Alyea

### Parent term

dermatomyositis

### ORCID Identifier

0000-001-9310-0163

### Additional comments

The importance of the term is the association with the interstitial lung disease which can be rapidly progressive.  When identified and treated early some cases seem to have a better prognosis.

**Comment by katiermullen** [comment]
Hi @galyea123!

Thank you for this new term request. To clarify, would you suggest that we add a related synonym, "clinically amyopathic dermatomyositis (CADM)" to amyopathic dermatomyositis MONDO:0043317?

And in addition, as a child "dermatomyositis" we will add a new term "anti-melanoma differentiation-associated gene 5-positive dermatomyositis" as requested.

**Comment by galyea123** [comment]
Hi!  Clinically amyopathic dermatomyositis is classified as hypomyopathic or amyopathic dermatomyositis (i.e., amyopathic dermatomyositis and hypomyopathic dermatomyositis, together referred to as Clinically Amyopathic Dermatomyositis (CADM), which are subtypes of  dermatomyositis, , one of the Idiopathic Inflammatory Myopathies.The former nomenclature for anti-melanoma differentiation-associated gene 5 (MDA5) dermatomyositis is clinically amyopathic dermatomyositis (CADM). To answer your question: 

I am requesting to add the new term "anti-melanoma differentiation-associated gene 5-positive dermatomyositis" with the synonym "Clinically amyopathic dermatomyositis" and CADM.   This condition is "parent" of "amyopathic dermatomyositis" (and also a parent of "hypomyopathic dermatomyositis"-which is not in the MONDO database or Orphanet -  **may also consider adding it too**** - please note that I am waiting for Orphanet response too)

The new term "anti-melanoma differentiation-associated gene 5-positive dermatomyositis" is a child of dermatomyositis. 

Thank you, Gioconda

**Comment by katiermullen** [comment]
Thank you @galyea123.

@sabrinatoro and I have added your requested new terms: "hypomyopathic dermatomyositis", "anti-melanoma differentiation-associated gene 5-positive dermatomyositis" and "clinically amyopathic dermatomyositis". 

-We have added "clinically amyopathic dermatomyositis" as a parent of "amyopathic dermatomyositis" and "hypomyopathic dermatomyositis"
-We have also added the other autoantibody subtypes of dermatomyositis listed in ORPHA:221.  
-We have also had added related synonyms for "clinically amyopathic dermatomyositis" and "anti-melanoma differentiation-associated gene 5-positive dermatomyositis" relating them to each other. Note: according to PMID: 35134633, these terms are related, but not exact synonyms: "A subset of patients with CADM are positive for a specific autoantibody known as anti-melanoma differentiation-associated gene 5 (MDA-5)." 
-We now have:

![Image](https://github.com/user-attachments/assets/5bdbda94-8736-4757-9eb3-97a0840f77f3)

Please let me know if you have questions or comments! Thank you!

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________
