### ISSUE TITLE
Trichorhinophalangeal Syndrome type III

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#8122]
trichorhinophalangeal syndrome, type III http://purl.obolibrary.org/obo/MONDO_0008597

**Reason for deprecation**
In 2023, the classification of genetic skeletal disorders was updated. These updates help to clarify the classification of these related conditions and provide a more accurate understanding of the genetic basis behind them. According to the new guidelines:

•	TRPS caused by a pathogenic variant in the TRPS1 gene is now referred to as trichorhinophalangeal dysplasia (syndrome) types 1/3. This covers what was previously known as TRPS1 and TRPS3.
•	TRPS caused by a larger deletion in chromosome 8 (specifically affecting the region 8q23.3-q24.11, which includes the TRPS1 and EXT1 genes) is referred to as Langer-Giedion syndrome (trichorhinophalangeal dysplasia (syndrome) type 2).
Source: https://www.ncbi.nlm.nih.gov/books/NBK425926/
Term to consider: trichorhinophalangeal dysplasia types 1/3. (I suggest adding this synonym to trichorhinophalangeal syndrome type I MONDO:0008596 - note that you already list type III trichorhinophalangeal syndrome as a synonym)
ORCID ID 0000-001-9310-0163

Thank you,

Gioconda Alyea

**Comment by twhetzel** [comment]
Thank you @galyea123 for the term obsoletion request and reason for obsoletiong. This will be included in the next Mondo release.

TODO
- [ ] obsolete MONDO:0008597
- [ ] add synonyms 'trichorhinophalangeal dysplasia types 1/3' and 'trichorhinophalangeal dysplasia (syndrome) types 1/3' to with source PMID: 28426188 (the pmid for the nbk link)
