### ISSUE TITLE
KCND2-related neurodevelopmental disorder with or without seizures

### ISSUE THREAD

**Issue by ens-ecibrian** [monarch-initiative/mondo#8155]
**Preferred gene-related syndrome label**
KCND2-related neurodevelopmental disorder with or without seizures

**Synonyms**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
Mendelian neurodevelopmental disorder MONDO_0100500

**Definition**
A neurodevelopmental disorder caused by variation in the KCND2 gene. This disorder is characterized by early-onset global developmental delay with impaired motor, speech and cognitive development. Patients often present muscle hypotonia, and less frequently, developmental epileptic encephalopathy, visual impairment and physical dysmorphisms.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)**
PMID:34245260 

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
0000-0002-0987-9862

**Additional comments**
Request from the G2P team (EMBL-EBI)

**Comment by yshwetar** [comment]
New term 'KCND2-related neurodevelopmental disorder with or without seizures' has been added with associated sources and definitions.
