### ISSUE TITLE
CAMK2D-related neurodevelopmental disorder and dilated cardiomyopathy

### ISSUE THREAD

**Issue by ens-ecibrian** [monarch-initiative/mondo#8158]
**Preferred gene-related syndrome label**
CAMK2D-related neurodevelopmental disorder and dilated cardiomyopathy

**Synonyms**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
MONDO_0100500

**Definition**
A neurodevelopmental disorder caused by variation in the CAMK2D gene. This disorder is characterised by intellectual disability, speech and motor delay, behavioural problems and dilated cardiomyopathy. Patients often present brain structural anomalies and hypotonia, and less frequently, seizures.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)**
PMID:38272033

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
0000-0002-0987-9862

**Additional comments**
Request from the G2P team (EMBL-EBI)

**Comment by yshwetar** [comment]
We have created the new term CAMK2D-related neurodevelopmental disorder and dilated cardimyopathy in #8368. Thank you!
