### ISSUE TITLE
ClinGen request to relabel MONDO:0013069

### ISSUE THREAD

**Issue by peastc** [monarch-initiative/mondo#8185]
**Mondo term (ID and Label):** 
MONDO:0013069, autosomal recessive optic atrophy, OPA7 type

**Suggested new label:** 
TMEM126A-related optic atrophy with or without extraocular features

**Your nano-attribution (ORCID)**
https://orcid.org/0009-0007-1636-9645

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
Upon the curation of the gene-disease relationship between autosomal recessive optic atrophy and TMEM126A to the definitive level, the ClinGen Glaucoma and Neuro-Ophthalmology GCEP finds it relevant to relabel this term to the ClinGen preferred dyadic name to represent the very strong evidence of this gene disease relationship known to exist in the literature at this time. 
PMIDs used to in the curation reviewed and approved by experts are: 19327736, 20405026, 22815638, 22815638, 31119195, 30961538, 36071901, 23500070, 33882309, 33879611, 33879611, 33879611
[TMEM126A 09192024 .pdf](https://github.com/user-attachments/files/17067366/TMEM126A.09192024.pdf)

**Comment by katiermullen** [comment]
@peastc Thank you for submitting this issue!

The clin gen preferred name has been added as an exact synonym to the term, MONDO:0013069, autosomal recessive optic atrophy, OPA7 type. 

This information will appear in the next release of Mondo.
