### ISSUE TITLE
[Revise subclass] MONDO:0019303 'premature aging' and children

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#821]
MONDO:0019303 'premature aging' 
is currently

Subclass of:
disorder of development or morphogenesis
skin disease
RO_0002573 some rare

I believe that the parentage to skin disease terms is incorrect and an artefact due to ORDO provenance. Skin appearance may be affected in prematurely aged individuals, but that doesn't make premature aging (and all of its children) a disease of the skin. We face the same issue in EFO. Please consider implementing similar changes to the ones I outlined in https://github.com/EBISPOT/efo/issues/544. Thanks!

**Comment by nicolevasilevsky** [comment]
note to self - to remove superclass assertion for 'skin disease'

**Comment by nicolevasilevsky** [comment]
Continued from above: suggestions for children of 'Premature aging': from https://github.com/EBISPOT/efo/issues/544

**Acrogeria:**

- [ ] Add parents 'genetic disorder' and 'skin disease' (if the latter is removed from 'premature aging')

- [ ] Add def "A congenital skin condition characterized by premature aging, more especially in the form of unusually fragile, thin skin on the hands and feet. Its onset is in early childhood; it progresses over the next few years and then remains stable. A bruising tendency has been observed."

 Add xref Wikipedia:Acrogeria

**De Barsy syndrome:**

- [ ]  Remove all existing parents except for 'Premature aging' (consider changing them in axioms pointing to phenotypes)

- [ ] Add parent 'autosomal recessive disease'

- [ ] Edit def to "A rare autosomal recessive genetic disorder characterized by facial dysmorphism (down-slanting palpebral fissures, a broad flat nasal bridge and a small mouth) with a progeroid appearance, large and late-closing fontanel, cutis laxa (CL), joint hyperlaxity, athetoid movements and hyperreflexia, pre- and postnatal growth retardation, intellectual deficit and developmental delay, and corneal clouding and cataract. [ Orphanet:2962 ]"

**Flynn-Aird syndrome:**

- [ ]  Remove parent 'Rare genetic neurological disorder' (consider changing it in an axiom pointing to phenotype)
- [ ]  Add parent 'autosomal dominant disease'

**Hallermann-Streiff syndrome:**

- [ ] Remove all existing parents except for 'Premature aging' (consider changing them in axioms pointing to phenotypes)
- [ ] Add parent 'genetic disorder'

**LMNA-related cardiocutaneous progeria syndrome:**

- [ ]  Remove parent 'Rare genetic cardiac disease' (consider changing it in an axiom pointing to phenotype)

- [ ]  Add parent 'genetic disorder'

- [ ] Add def "A rare, genetic, premature aging syndrome characterized by adulthood-onset cutaneous manifestations that result in a prematurely aged appearance (i.e. premature thinning and graying of scalp hair, loss of subcutaneous fat, tightening of skin) associated with prominent cardiovascular manifestations, such as accelerated atherosclerosis, calcific valve disease, and cardiomyopathy. Patients present loss of eyebrows and eyelashes in childhood and have a predisposition to develop malignancies. [ Orphanet:363618 ]"

**progeroid syndrome:**

- [ ] Fix typo in def, should start with uppercase A.

**Comment by cmungall** [comment]
also is premature aging a good disease name?

**Comment by nicolevasilevsky** [comment]
It does seem like more of a phenotype than a disease. In MeSH, it is classified under 'Signs and Symptoms'
https://meshb.nlm.nih.gov/record/ui?ui=D019588

@cmungall are you suggesting we rename it? or obsolete it?

If we renamed it, what should we rename it as? premature aging syndrome? premature aging disorder?

This article describes 'premature aging syndrome' but I think they are talking about progeroid syndromes:
https://www.ncbi.nlm.nih.gov/pubmed/22411253

This article describes premature aging syndromes too:
https://academic.oup.com/ageing/article-pdf/27/1/73/34683/27-1-73.pdf

This site uses the term 'premature aging disorders': https://www.coriell.org/1/NIA/Collections/Premature-Aging-Disorders

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 
Same here please - tentatively adding to your upcoming release milestone :-)
