### ISSUE TITLE
[Revise subclass] MONDO:0018702 a subclass of MONDO:0015564

### ISSUE THREAD

**Issue by DnlRKorn** [monarch-initiative/mondo#8210]
**Mondo term (ID and Label)**
MONDO:0018702 should be made a subclass of MONDO:0015564

**Suggested revision and reasons**
"Recently, a unique clinicopathologic variant of multicentric Castleman's disease (MCD) has been identified in Japan." - PMID:23801135
It seems like this should be included somewhere in the Castleman hierarchy; maybe keeping it's current parent and also getting MONDO:0015564 as a parent.

**Your nano-attribution (ORCID)**
(https://orcid.org/)](https://orcid.org/0000-0002-1780-9872)

**Comment by katiermullen** [comment]
@DnlRKorn Thank you for this request!

Based on references that you provided as well as PMID:36148768, MONDO:0018702 Castleman-Kojima disease will be made a subclass of MONDO:0035838 idiopathic multicentric Castleman disease.

This update will appear in the next release of Mondo.
