### ISSUE TITLE
MBD4-related recessive tumor predisposition syndrome

### ISSUE THREAD

**Issue by keparis** [monarch-initiative/mondo#8214]
**Preferred gene-related syndrome label**
MBD4-related recessive tumor predisposition syndrome

**Synonyms**

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)**
[tumor predisposition syndrome 2](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0859267)

**Definition**
MBD4-related recessive tumor predisposition syndrome is an autosomal recessive cancer predisposition condition including different kinds of tumors or malignancies which manifest in young adults. The most frequent features of this syndrome include acute myeloid leukemia (AML), myelodysplastic syndrome, colorectal polyposis and carcinoma, and uveal melanoma.

**Definition source (Please give PubMed ID, if applicable, in format PMID:#######)
[Childhood, Adolescent and Young Adult Cancer Predisposition Gene Curation Expert Panel](https://clinicalgenome.org/affiliation/40157/)

**Children terms (if applicable)** Should any existing terms be re-classified as children underneath this new proposed term? 

**Your nano-attribution (ORCID) or URL for a working group**
https://orcid.org/0009-0004-3069-7846

**Comment by katiermullen** [comment]
@keparis thank you for this request! 

In reviewing this request, MONDO:0859267 'tumor predisposition syndrome 2' has db-xref [OMIM:619975](https://omim.org/entry/619975) that has synonyms 'MBD4-ASSOCIATED NEOPLASIA SYNDROME; MANS' as well as the gene association: MBD4, and description: 

Tumor predisposition syndrome-2 (TPDS2) is an autosomal recessive cancer predisposition syndrome characterized by the onset of various types of tumors or malignancies in young adulthood. The most common clinical manifestations include acute myeloid leukemia (AML), myelodysplastic syndrome, colorectal adenomatous polyposis and carcinoma, and uveal melanoma.

If acceptable, I will add the definition, synonyms, gene association and clin gen preferred name, MBD4-related recessive tumor predisposition syndrome, to the term, MONDO:0859267 'tumor predisposition syndrome 2."

**Comment by keparis** [comment]
Great, thank you so much!
