### ISSUE TITLE
combined oxidative phosphorylation deficiency (MONDO:0000732) definition is truncated

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#8216]
**Mondo term (ID and Label)**

combined oxidative phosphorylation deficiency (MONDO:0000732)

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**

A mitochondrial oxidative phosphorylation disorder in which multiple mitochondrial respiratory chain complexes.

is not a complete sentance

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by katiermullen** [comment]
Hi @ValWood,

Thank you for submitting this issue. The definition has been revised to "A mitochondrial oxidative phosphorylation disorder in which multiple mitochondrial respiratory chain complexes are affected." 

The change will appear in the next release of Mondo.
