### ISSUE TITLE
query proposed obsoletion of MONDO:0024321 | disorder of GPI anchor biosynthesis

### ISSUE THREAD

**Issue by ValWood** [monarch-initiative/mondo#8220]
re 
MONDO:0024321 | disorder of GPI anchor biosynthesis

This seems like a useful grouping term. Can you describe more fully the reason for obsoletion.?

https://github.com/monarch-initiative/mondo/blob/master/src/ontology/reports/mondo_obsoletioncandidates.tsv

**Comment by ValWood** [comment]
Also I question the current parentage, disorder of glycosylation. A GPI anchors isn't classed as glycosylation, its a glycolipid not a carbohydrate?

**Comment by ValWood** [comment]
The term is useful because it groups all of the disorders connected to a single linear pathway (which will presumably have related phenotypes).
<img width="735" alt="GPI biosynthesis" src="https://github.com/user-attachments/assets/27fcc661-6a87-4474-acfc-8005f390de1d">

**Comment by sabrinatoro** [comment]
refers to https://github.com/monarch-initiative/mondo/issues/7700
