### ISSUE TITLE
[Revise subclass] MONDO:0001165 'tongue disease' subclass of 'sensory system disease'

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#823]
MONDO:0001165 'tongue disease' is currently a subclass of 'mouth disease' (which is ok of course) and of 'sensory system disease', which doesn't seem entirely correct as the tongue has roles in digestion and speech too (see https://en.wikipedia.org/wiki/Tongue). This issue is similar to https://github.com/monarch-initiative/mondo/issues/747. Would you please consider removing the parentage as you did there? In fact, you may want to consider the same course of action for these other children of 'sensory system disease': 
disease of ear
nose disease
Thanks!

**Comment by paolaroncaglia** [comment]
Tagging @zoependlington for her reference.

**Comment by nicolevasilevsky** [comment]
this may be an issue for Uberon, I will look into this further

**Comment by nicolevasilevsky** [comment]
![image](https://user-images.githubusercontent.com/6722114/65727216-f18a3580-e06b-11e9-8071-237dfa747f9c.png)

tongue is a subclass of sense organ in Uberon - is this something we should revisit? If yes, I can create a ticket in Uberon.

**Comment by nicolevasilevsky** [comment]
same with disease of ear - ear is a subclass of sense organ in Uberon

**Comment by cmungall** [comment]
Note we already excluded the is-a from SSD to nervous system disease for
same underlying reasons.

What's the use case for sensory system disease? Maybe the intent is nervous
system part of sensory system disease?

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 
Thanks. Here's the Uberon ticket: https://github.com/obophenotype/uberon/issues/1517
I'll look into the sensory system disease issue next.

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia I am not sure what to do here, can we discuss on our next call?

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky
(and @cmungall )
Sure, I added this ticket to the agenda for our next Mondo-EFO call. However, I'm afraid I don't have much wisdom to bring into the discussion in addition to what I wrote here https://github.com/obophenotype/uberon/issues/1517#issuecomment-545463448. @cmungall , could you weigh in, please? 
Thank you both.

**Comment by cmungall** [comment]
is sensory system disease even a useful grouping? What is the intended meaning? What are the expected subclasses?

Maybe the intent is for this to mean the nervous system parts of the sensory system (thus would include sensory epithelium of the nose but not the whole nose or nose skeleton)?

**Comment by nicolevasilevsky** [comment]
'sensory system disease' was created from Mondo patterns. All of the (inferred) children have other parents so i don't think we'd lose much if we obsoleted 'sensory system disease'.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 
Tagging this for Dec release as I think you're very close to a resolution ;-) and the issue affects EFO at a fairly high level. We appreciate...

**Comment by nicolevasilevsky** [comment]
decision - obsolete 'sensory system disease'. This is high priority for EFO
