### ISSUE TITLE
[Revise subclass] MONDO:0008608 down syndrome subclass of many

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#824]
MONDO:0008608 down syndrome
is currently

Subclass of: 
syndromic intellectual disability
Moyamoya syndrome
chromosomal anomaly with epilepsy as a major feature
genetic multiple congenital anomalies/dysmorphic syndrome
rare syndrome with cardiac malformations
multiple congenital anomalies/dysmorphic syndrome-intellectual disability
total autosomal trisomy

I suspect that at least some of those parents should better be represented as associations with phenotypes or disorders. The link to Moyamoya syndrome was brought up in a previous MONDO ticket (https://github.com/monarch-initiative/mondo/issues/544). The broader issue of parentage inherited from Orphanet is documented in EFO too (https://github.com/EBISPOT/efo/issues/322). In this particular case, EFO inherits parentage of Down syndrome from MONDO (http://www.ebi.ac.uk/efo/EFO_0001064). Any opinions?

Also, the label should be 'Down syndrome' as it's an eponym (https://en.wikipedia.org/wiki/Down_syndrome#History).

Thanks!

**Comment by cmungall** [comment]
We really need to review the only-ordo supported is-as soon

Definitely not a type of moyamoya.

for the others, wondering if we should even obsolete some of the parents

@nicolevasilevsky can you handle?

**Comment by nicolevasilevsky** [comment]
@cmungall I removed several superclasses and made them excludedSubclassOf:
- MONDO:0000508 'syndromic intellectual disability'
- MONDO:0003847 'inherited genetic disease' 
- MONDO:0018792 Moyamaoya syndrome  
- MONDO:0015652 'chromosomal anomaly with epilepsy as a major feature' 
- MONDO:0015159 'multiple congenital anomalies/dysmorphic syndrome-intellectual disability'
- MONDO:0015506 'rare syndrome with cardiac malformations'

Should we consider obsoleting any of these terms?

Should we create a new ticket re: reviewing the only-ordo supported is-as relationships?

**Comment by nicolevasilevsky** [comment]
Another question here that @paolaroncaglia brought up on our call is - some of the old superclasses for Down Syndrome are phenotypes (ie intellectual disability, cardiac malformations) - do we want to capture these logically on this term somehow?

**Comment by cmungall** [comment]
given we do not have common disease association files in place yes, make these disease-has-phenotype links if you believe them to be true

**Comment by nicolevasilevsky** [comment]
Would this be the correct way to do this:
add SubClassOf axioms:
'disease has feature' some 'Intellectual disability'
'disease has feature' some epilepsy
'disease has feature' some 'Abnormal facial shape'
'disease has feature' some 'Abnormality of the cardiovascular system'

Thanks!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 
Another "pending PR". Yes, I'm reviewing EFO tickets in Mondo in view of our meeting on Monday... thank you both!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Reopening this ticket please as something seems to have gone wrong, MONDO:0008608 'Down syndrome' still has some weird superclasses, including 'syndromic intellectual disability' that is both a superclass and an excluded superclass? See https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0008608, and I'm seeing the same in current EFO + Mondo import. To summarize, 'Down syndrome' should only be a direct subclass of 'total autosomal trisomy'.
Not sure what happened, let me know if I can help. Tagging this for your January release please. And thank you! :-)
