### ISSUE TITLE
[Revise subclass] hepatitis terms children of MONDO:0024294 skin disease caused by infection

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#825]
MONDO:0024294 skin disease caused by infection
has, among others, the following children:
hepatitis A
hepatitis B
hepatitis C
hepatitis E
- [ ] hepatitis may cause jaundice, so the skin condition is a symptom/phenotype, not a disease parent
- [ ] (less important) hepatitis A/B/C/D are, strictly speaking, the virus' names; consider disambiguating to 'hepatitis X infection'?
See https://github.com/EBISPOT/efo/issues/549. Thanks and I promise to stop here for today :-)

**Comment by cmungall** [comment]
@nicolevasilevsky can you paste a protege explanation?

**Comment by nicolevasilevsky** [comment]
![image](https://user-images.githubusercontent.com/6722114/65697910-94bd5980-e030-11e9-87be-0b5860501e2c.png)

**Comment by nicolevasilevsky** [comment]
@ana-rath-orphanet - looping you in to this ticket.

Per your email, it sounds like we should revise these labels to 'hepatitis B virus infection', instead of 'hepatitis B infection'
