### ISSUE TITLE
NDUFB11-Related Disorders

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#8253]
NDUFB11-Related Disorders

Preferred name: NDUFB11-Related Disorders

**Definition**

NDUFB11-related disorders are a group of rare genetic conditions caused by changes (variants) in the NDUFB11 gene. 
Disease-causing variants in the NDUFB11 gene are associated with a range of symptoms and include the following four conditions: 

- Mitochondrial complex I deficiency nuclear type 30 (MC1DN30), a mitochondrial condition affecting the body’s ability to produce energy, which can lead to problems in multiple organs, especially the muscles, brain, and heart. 
- X-linked sideroblastic anemia with lactic acidosis, a type of anemia that results from abnormal utilization of iron associated with lactic acidosis, a buildup of lactic acid in the bloodstream. 
- Histiocytoid cardiomyopathy, a serious heart condition. 
- Linear skin defects with multiple congenital anomalies type 3, a rare condition characterized by abnormalities of the skin, eye and heart. 

Affected individuals may have overlap of these four conditions. It is not yet possible to predict which condition a person will have based upon the specific gene variant.

There is no cure for NDUFB11-related disorders, but treatment can help manage symptoms.

**Definition source 
van Rahden VA, Fernandez-Vizarra E, Alawi M, et al. Mutations in NDUFB11, encoding a complex I component of the mitochondrial respiratory chain, cause microphthalmia with linear skin defects syndrome. Am J Hum Genet.2015;96(4):640-650. doi:10.1016/j.ajhg.2015.02.002.
Shehata BM, Cundiff CA, Lee K, et al. Exome sequencing of patients with histiocytoid cardiomyopathy reveals a de novo NDUFB11 mutation that plays a role in the pathogenesis of histiocytoid cardiomyopathy. Am J Med Genet A.2015;167A(9):2114-2121. doi:10.1002/ajmg.a.37138.
Kohda M, Tokuzawa Y, Kishita Y, et al. A comprehensive genomic analysis reveals the genetic landscape of mitochondrial respiratory chain complex deficiencies. PLoS Genet. 2016;12(1). doi:10.1371/journal.pgen.1005679.
Torraco A, Bianchi M, Verrigni D, et al. A novel mutation in NDUFB11 unveils a new clinical phenotype associated with lactic acidosis and sideroblastic anemia. Clin Genet. 2017;91(3):441-447. doi:10.1111/cge.12790

**Children terms (if applicable)* Mitochondrial complex I deficiency, nuclear type 30 	3
Linear skin defects with multiple congenital anomalies 3
Also X-linked sideroblastic anemia and histiocytoid cardiomyopathy

ORCID number: 0000-001-9310-0163

Thank you! Gioconda Alyea

**Comment by yshwetar** [comment]
We have added the new term 'NDUFB11-Related Disorders' with only the child 'Mitochondrial complex I deficiency nuclear type 30 (MC1DN30)', as this is the only child term to occur in all manifestations of the disorder.
