### ISSUE TITLE
Logical definition of "ovarian granulosa cell tumor" is redundant

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#8268]
~#8262(closed)~ #8264 caused the following failure as pointed out by @twhetzel:

## [DISJOINT-SIB-OF ovarian granulosa cell tumor](urn:uuid:3cf8909e-38bd-41c6-b951-ee30c8994bdc) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##
  - [DISJOINT-SIB-OF ovarian granulosa cell tumor](urn:uuid:3cf8909e-38bd-41c6-b951-ee30c8994bdc) SubClassOf [granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0006036)
    - [granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0006036) EquivalentTo [neoplasm](http://purl.obolibrary.org/obo/MONDO_0005070) and ([disease has location](http://purl.obolibrary.org/obo/RO_0004026) some [granulosa cell](http://purl.obolibrary.org/obo/CL_0000501))
      - [granulosa cell](http://purl.obolibrary.org/obo/CL_0000501) SubClassOf [follicular cell of ovary](http://purl.obolibrary.org/obo/CL_0002174)
        - [follicular cell of ovary](http://purl.obolibrary.org/obo/CL_0002174) SubClassOf [ovarian surface epithelial cell](http://purl.obolibrary.org/obo/CL_2000064)
          - [ovarian surface epithelial cell](http://purl.obolibrary.org/obo/CL_2000064) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992)
  - [disease has location](http://purl.obolibrary.org/obo/RO_0004026) o [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [disease has location](http://purl.obolibrary.org/obo/RO_0004026)
  - [ovarian granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0023283) EquivalentTo [granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0006036) and ([disease has location](http://purl.obolibrary.org/obo/RO_0004026) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992))
  - [ovarian granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0023283) DisjointWith [DISJOINT-SIB-OF ovarian granulosa cell tumor](urn:uuid:3cf8909e-38bd-41c6-b951-ee30c8994bdc)
# Axiom Impact 
## Axioms used 1 times
- [granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0006036) EquivalentTo [neoplasm](http://purl.obolibrary.org/obo/MONDO_0005070) and ([disease has location](http://purl.obolibrary.org/obo/RO_0004026) some [granulosa cell](http://purl.obolibrary.org/obo/CL_0000501)) [O1]
- [ovarian granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0023283) EquivalentTo [granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0006036) and ([disease has location](http://purl.obolibrary.org/obo/RO_0004026) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992)) [O1]
- [granulosa cell](http://purl.obolibrary.org/obo/CL_0000501) SubClassOf [follicular cell of ovary](http://purl.obolibrary.org/obo/CL_0002174) [O1]
- [follicular cell of ovary](http://purl.obolibrary.org/obo/CL_0002174) SubClassOf [ovarian surface epithelial cell](http://purl.obolibrary.org/obo/CL_2000064) [O1]
- [ovarian surface epithelial cell](http://purl.obolibrary.org/obo/CL_2000064) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992) [O1]
- [DISJOINT-SIB-OF ovarian granulosa cell tumor](urn:uuid:3cf8909e-38bd-41c6-b951-ee30c8994bdc) SubClassOf [granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0006036) [O1]
- [ovarian granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0023283) DisjointWith [DISJOINT-SIB-OF ovarian granulosa cell tumor](urn:uuid:3cf8909e-38bd-41c6-b951-ee30c8994bdc) [O1]
- [disease has location](http://purl.obolibrary.org/obo/RO_0004026) o [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [disease has location](http://purl.obolibrary.org/obo/RO_0004026) [O1]

The problem is a bit opaque as it is caught by an ancient check which has long since been superceded by `robot reason --allow-equivalent-classes none` (the test injects hypothetical siblings and makes sure they can theoretically exist, thereby ensuring a child is not the same as its parent).

Here is the issue: 

`granulosa cell tumor` is defined as a [granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0006036) EquivalentTo [neoplasm](http://purl.obolibrary.org/obo/MONDO_0005070) and ([disease has location](http://purl.obolibrary.org/obo/RO_0004026) some [granulosa cell](http://purl.obolibrary.org/obo/CL_0000501)) and [ovarian granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0023283) is defined as a [granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0006036) and ([disease has location](http://purl.obolibrary.org/obo/RO_0004026) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992)). Unfortunately, through a chain of inference in CL, [granulosa cell](http://purl.obolibrary.org/obo/CL_0000501) is considered a part of the `ovaries`. So saying that [ovarian granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0023283) is has ([disease has location](http://purl.obolibrary.org/obo/RO_0004026) some [ovary](http://purl.obolibrary.org/obo/UBERON_0000992)) is redundant, therefore the two classes are considered the same.

This is a great catch by QC. My assumption is that either the fact that [granulosa cell](http://purl.obolibrary.org/obo/CL_0000501) is considered a part of the `ovaries` is wrong, or [ovarian granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0023283) is logically underspecified!

**Comment by twhetzel** [comment]
Thanks @matentzn - that was my general impression from the [qc error log](https://github.com/monarch-initiative/mondo/actions/runs/11467370674/job/31910098595?pr=8264#step:4:83). Did you come across why this happened now as a result of running the [refresh imports](https://mondo.readthedocs.io/en/latest/editors-guide/import-terms-for-logical-axioms/)?

@sabrinatoro or @nicolevasilevsky are either of you able to take the curator role on this to resolve this issue?

**Comment by matentzn** [comment]
> Did you come across why this happened now as a result of running the [refresh imports](https://mondo.readthedocs.io/en/latest/editors-guide/import-terms-for-logical-axioms/)?

It is either due to changes in CL classification (one that made [granulosa cell](http://purl.obolibrary.org/obo/CL_0000501)  part of the ovaries) or because the role chain `disease has location` < `disease has location` o `part of` was added to RO!

**Comment by nicolevasilevsky** [comment]
> @sabrinatoro or @nicolevasilevsky are either of you able to take the curator role on this to resolve this issue?

no, I can't, sorry

**Comment by matentzn** [comment]
A quick fix is to remove the logical definition of [ovarian granulosa cell tumor](http://purl.obolibrary.org/obo/MONDO_0023283), but someone should probably google the following:

Are all granulosa cell tumors are by definition "ovarian"?

**Comment by twhetzel** [comment]
From a few references I've seen:
- Granulosa cell tumors are the most common type of sex cord stromal tumor accounting for about 2-5% of ovarian neoplasms. REF: https://pmc.ncbi.nlm.nih.gov/articles/PMC3978936/
- However, "Granulosa cell tumors can arise in locations other than the ovary..." REF: https://pmc.ncbi.nlm.nih.gov/articles/PMC8893158/#:~:text=Granulosa%20cell%20tumors%20can%20arise,differentiating%20GCT%20from%20other%20neoplasms.

**Comment by cmungall** [comment]
here's the issue

```yaml
id: MONDO:0006036
name: granulosa cell tumor
intersection_of: MONDO:0005070 ! neoplasm
intersection_of: disease_has_location CL:0000501 ! granulosa cell
```

**Comment by sabrinatoro** [comment]
I agree with everything said here. In addition: 

-  "granulosa cell tumor" can occur in ovary and in testis. Therefore,  "granulosa cell tumor" is NOT equivalent to "ovarian granulosa cell tumor" (this had to be confirmed). 

-  After reading the definition for "granulosa cell tumor", I think that the logical definition of "neoplasm located in a granulosa cell" is not correct. "granulosa cell tumor" is "characterized by the presence of granulosa-like cells and Call-Exner bodies". (ie it is NOT "located in"). I therefore removed the logical definition for this term. The resulting classification seems more sane. 

- I agree with Chris that the DPs for neoplasm located in cells should be reviewed. A new issue should be created for this (@twhetzel can you please create this issue? thank you) 

PR has been updated; waiting for QC checks to run.

**Comment by twhetzel** [comment]
Sure, I added an [issue](https://github.com/monarch-initiative/mondo/issues/8271) referencing back to this for more details.
