### ISSUE TITLE
 Klippel-Trenaunay syndrome vs angioosteohypertrophic syndrome

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#83]
Orphanet treats as 2 distinct

```
   is_a Orphanet:98196 ! Malformation syndrome with hamartosis
    is_a Orphanet:2346 ! Angioosteohypertrophic syndrome ***
     is_a Orphanet:90308 ! Klippel-TrC)naunay syndrome *** 
```

also says it is exact for https://omim.org/entry/149000

```
id: Orphanet:2346
name: Angioosteohypertrophic syndrome
synonym: "Klippel-Trénaunay-Weber syndrome" EXACT []
...
xref: OMIM:149000 {source="E (exact mapping (the terms and the concepts are equivalent))"}
```

however, this omim entry bundles the two

TODO:

 * [x] review literature for evidence of split vs lump
 * [x] alert ordo if merge requested

**Comment by nicolevasilevsky** [comment]
I think we should lump.
https://jamanetwork.com/journals/jamapediatrics/article-abstract/501900?redirect=true

I'll make a ticket on the ORDO tracker.
