### ISSUE TITLE
Add Xrefs to MONDO:0000384 (bladder benign neoplasm) #7829

### ISSUE THREAD

**Issue by hibaontoforce** [monarch-initiative/mondo#8310]
**Mondo term (ID and Label):**
MONDO:0000384 (bladder benign neoplasm)

**Xref that should be fixed (ID and label):**
equivalentTo: ICD9:223.3 (Benign neoplasm of bladder)
equivalentTo: ICD10:D30.3 (Benign neoplasm of bladder) 

**Your nano-attribution (ORCID)**
0000-0002-6228-6214

**Comment by twhetzel** [comment]
Thank you @hibaontoforce for the request to add these xrefs. The xref to ICD9 already exists, however the xref to ICD10 was missing and is now added. This should be available in the next Mondo release.
