### ISSUE TITLE
Updates to fix QC errors for multiple gene associations

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#8329]
Updates to fix or add qc exclusions for new qc check failures for https://github.com/monarch-initiative/mondo/issues/8316

FAIL Rule ../sparql/qc/mondo/qc-multiple-gene-associations.sparql: 4 violation(s)
entity,label,geneIdentifiers
- [x]  http://purl.obolibrary.org/obo/MONDO_0011974,retinitis pigmentosa 7,"http://identifiers.org/hgnc/10254, http://identifiers.org/hgnc/9942" --> exclude from QC check, see https://github.com/monarch-initiative/mondo/issues/8276
- [x] http://purl.obolibrary.org/obo/MONDO_0100188,combined ApoA-I and ApoC-III deficiency,"http://identifiers.org/hgnc/600, http://identifiers.org/hgnc/610" --> see comment in post below
- [x] http://purl.obolibrary.org/obo/MONDO_0100050,"Usher syndrome, type 1D/F","http://identifiers.org/hgnc/13733, http://identifiers.org/hgnc/14674" --> exclude from QC check, see https://github.com/monarch-initiative/mondo/issues/8276
- [x] http://purl.obolibrary.org/obo/MONDO_0011908,juvenile myelomonocytic leukemia,"http://identifiers.org/hgnc/1541, http://identifiers.org/hgnc/9644, http://identifiers.org/hgnc/7765, http://identifiers.org/hgnc/17073" --> see comment in post below

**Comment by twhetzel** [comment]
- MONDO_0100188 'combined ApoA-I and ApoC-III deficiency' - based on the xref for the definition (PMID: 3118360) this term seems more related to [OMIM:620058](https://www.omim.org/entry/620058), which does have a single disease defining gene so I removed the two gene associations. In addition, if we agree that MONDO_0100188 is the same as OMIM:620058 then there is already another MONDO term for this, ie MONDO:0859290.

**Comment by katiermullen** [comment]
@twhetzel Thanks for all of your work on this!

It seems based on [this publication ](https://pmc.ncbi.nlm.nih.gov/articles/PMC6942922/)that these (MONDO:0100188 and MONDO:0859290) are different diseases:

"There are a number of forms of familial apolipoprotein A-I deficiency: those characterized by a lack of plasma apoA-I, apoC-III, and apoA-IV, those characterized by a lack of apoA-I and apoC-III, and those characterized by a lack of apoA-I only. These states are briefly reviewed below."

I hope this helps. Let me know if you need more info!

**Comment by sabrinatoro** [comment]
I agree with Katie, MONDO:0100188 is the same as MONDO:0859290 are not the same. 
A quick review show that MONDO:0100188 is caused by variation in both APOA1 amd APOC3 (at the same time). While MONDO:0859290 is caused by a deletion of the entire APOA1/C3/A4 gene complex.

**Comment by twhetzel** [comment]
Thanks for reviewing @katiermullen! Based on the reference you linked they do seem different if using labels of the terms for comparison. Do you think the PMID and OMIM references on MONDO:0100188 'combined ApoA-I and ApoC-III deficiency' are correct:
- [PMID:3118360](https://pubmed.ncbi.nlm.nih.gov/3118360/), "DNA inversion within the apolipoproteins AI/CIII/AIV-encoding gene cluster of certain patients with premature atherosclerosis"
- [OMIM:618463](https://omim.org/entry/618463) HYPOALPHALIPOPROTEINEMIA, PRIMARY, 2

**Comment by twhetzel** [comment]
To summarize the chat, the actions for MONDO:0100188 are to remove the synonym, change the PMID to [PMID:20616715](https://pubmed.ncbi.nlm.nih.gov/20616715/) that Katie kindly provided and also use this as the source for the gene association statements.
