### ISSUE TITLE
Fix inconsistencies in xrefs related to errors in Synonym sync

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#8332]
See https://github.com/monarch-initiative/mondo/pull/8270#issuecomment-2477845119

```
FAIL Rule ../sparql/qc/mondo/qc-exact-synonyms-non-exact-mappings.sparql: 4 violation(s)
entity,label,xref,synonym,code
http://purl.obolibrary.org/obo/MONDO_0012817,Ewing sarcoma,NCIT:C7542,PNET of Thoracopulmonary region,MONDO:relatedTo
http://purl.obolibrary.org/obo/MONDO_0020528,ACTH-dependent Cushing syndrome,ICD10CM:E24.0,pituitary-dependent Cushing's disease,MONDO:directSiblingOf
http://purl.obolibrary.org/obo/MONDO_0004471,bacterial arthritis,NCIT:C26700,septic arthritis,MONDO:directSiblingOf
http://purl.obolibrary.org/obo/MONDO_0002514,hepatobiliary neoplasm,DOID:3117,hepatobiliary tumors,MONDO:mondoIsBroaderThanSource
```

**Comment by twhetzel** [comment]
It looks like these changes have already been made in the latest version of mondo-edit.obo.

**Comment by twhetzel** [comment]
Ah, now I see what is happening. The CURIEs that are an issue are the ones that are being added as provenance of a confirmed exact synonym match between Mondo and an external source and that external source has some other xref relationship other than `MONDO:equivalentTo`so the fix that needs to happen is:
- [ ] confirm that for these failing cases that there truly is an equivalentTo relationship with the xref 
- [ ] change the xref source to `MONDO:equivalentTo`

**Comment by joeflack4** [comment]
@twhetzel I will finish looking into these tomorrow! Thanks.

**Comment by twhetzel** [comment]
Added a ticket to address this in the Synonym Sync pipeline https://github.com/monarch-initiative/mondo-ingest/issues/687
