### ISSUE TITLE
Duplicate Merge ancylostomiasis/ankylostomiasis

### ISSUE THREAD

**Issue by gtsueng** [monarch-initiative/mondo#836]
It looks like: ankylostomiasis (MONDO:0019184) is the same as ancylostomiasis (MONDO:0005645) with ankylostomiasis being a dated and less frequently used spelling. At some point, it was even spelled [anchylostomiasis](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5148390/) 

Also, ankylostomiasis (MONDO:0019184) has the statement "AKA: ancylostomiasis" suggesting that they're the same.

**Comment by nicolevasilevsky** [comment]
thanks @gtsueng! I'll leave this open for a bit, in order to allow any community feedback.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@gtsueng 
EFO has EFO:0007145 ancylostomiasis, mapped to MONDO:0005645 and defined as 

"Infection by hookworms of the genus Ancylostoma. [ NCIT:P378 ]"

and

"A parasitic helminthiasis infectious disease that involves infection of skin, eyes, and viscera in humans by the parasitic nematodes Ancylostoma braziliense, Ancylostoma ceylanicum, Ancylostoma duodenale or Ancylostoma caninum. The larvae cause lesions on the skin at the site of penetration. The infection has_symptom intestinal bleeding, has_symptom abdominal pain, has_symptom anemia, has_symptom severe diarrhea and has_symptom malnutrition. [ http://www.ebi.ac.uk/ontology/webulous#OPPL_pattern ]"

The two MONDO terms seem the same to me, and based on the name of the disease agent, the most correct label would be ancylostomiasis.
