### ISSUE TITLE
Some xrefs map to multiple mondo terms

### ISSUE THREAD

**Issue by dst1** [monarch-initiative/mondo#841]
I hope this is the right place and way to reference this issues.

I'm using the MONDO ontology json from obofoundry downloaded at 26.09.2019
I found 4 cases where a single xref maps to multiple MONDO terms (presented here in json like form):
```{json}
{
  "HP:0001651": [
    "MONDO:0015661",
    "MONDO:0004823"
  ],
  "HP:0000010": [
    "MONDO:0001650",
    "MONDO:0005247"
  ],
  "MESH:D006524": [
    "MONDO:0025085",
    "MONDO:0006011"
  ],
  "HP:0001941": [
    "MONDO:0006022",
    "MONDO:0041261"
  ]
}
```
Specifically:
 - `MONDO:0015661` and  `MONDO:0004823` are both the same as `HP:0001651` (semantically) however are found in different places at the ontology tree. Also, `MONDO:0004823` should be labeled with `Orphanet:1666`.
-  `HP:0000010` - is neither `MONDO:0001650` nor `MONDO:0005247` as it is recurrent. I couldn't find a suitable alternative in HPO. Medically, `MONDO:0001650` should be a descendant of  `MONDO:0005247` as it is an infection of a bladder. This will solve another placement issue of  `MONDO:0001777` found under both of these.
-  `MONDO:0006011` includes both viral hepatitis in humans and animals - `MESH:D006524`, `MESH:D006525`, `MONDO:0025085` is exactly `MESH:D006524` (animals). I'm not sure how and if this can be resolved.
- `MONDO:0006022` is exactly `HP:0001941` while `MONDO:0041261` can also potentially include alkalosis and so shouldn't refer to `HP:0001941`.

----
also the MESH urls on the site are broken:
`https://meshb.nlm.nih.gov/record/ui?name={ID}`
instead of the working:
`https://meshb.nlm.nih.gov/record/ui?ui={ID}`

**Comment by nicolevasilevsky** [comment]
Thanks @dst1!

1) I think MONDO:0015661 'dextrocardia (disease)' and MONDO:0004823 dextrocardia should be merged. @cmungall or others, any objections?
2) I agree, I will make these edits on a branch and do PR:
- remove HP_0000010 'Recurrent urinary tract infections' as a dbxref from MONDO:0001650 'acute cystitis (disease)' and MONDO:0005247 'urinary tract infection (disease)'.
- move MONDO:0001650 'acute cystitis (disease)' to a child of MONDO:0005247 'urinary tract infection (disease)'.
3) MESH:D006524 is labeled as MONDO:NonHumanEquivalent. I feel like this addresses this issue, no?
4) I will remove HP: 0001941 as an dbxef to MONDO:0041261 'disorder of acid-base balance'
