### ISSUE TITLE
Fix Mondo qc check errors after running EMC pipeline

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#8416]
The Externally Managed Content pipeline was run from the GH Action and [failed the Mondo QC check](https://github.com/monarch-initiative/mondo/actions/runs/11925302864/job/33237165239#step:5:34).
```
FAIL Rule ../sparql/qc/mondo/qc-ordo-subset-exact-mapping.sparql: 6 violation(s)
entity,property,value
http://purl.obolibrary.org/obo/MONDO_0017333,http://purl.obolibrary.org/obo/mondo#ordo_disorder,Orphanet:289494
http://purl.obolibrary.org/obo/MONDO_0020659,http://purl.obolibrary.org/obo/mondo#ordo_disorder,Orphanet:598216
http://purl.obolibrary.org/obo/MONDO_0024252,http://purl.obolibrary.org/obo/mondo#ordo_disorder,Orphanet:488613
http://purl.obolibrary.org/obo/MONDO_0034823,http://purl.obolibrary.org/obo/mondo#ordo_disorder,Orphanet:508501
http://purl.obolibrary.org/obo/MONDO_0035433,http://purl.obolibrary.org/obo/mondo#ordo_disorder,Orphanet:565909
http://purl.obolibrary.org/obo/MONDO_0035454,http://purl.obolibrary.org/obo/mondo#ordo_disorder,Orphanet:567502
```

**Comment by matentzn** [comment]
Can you try to add

```
FILTER NOT EXISTS { ?entity owl:deprecated "true"^^xsd:boolean . }
```

as line 32 of the query `src/sparql/qc/mondo/qc-ordo-subset-exact-mapping.sparql` and see if that fixes the issue? seems like a bug. Seems like a recently obsoleted term also some a rerun with fresh data in mondo ingest might fix this. But the line is IMO missing anyways.

**Comment by twhetzel** [comment]
Sure, I will try that and that makes sense as I can see `MONDO_0017333` is obsoleted. Thank you.

**Comment by twhetzel** [comment]
Yes, that fixed it as I tested the qc checks locally running `sh run.sh make GITHUB_ACTION=true IMP=false PAT=false test -B`.  There's a PR now to update the SPARQL query.
