### ISSUE TITLE
Mondo Outreach page updates

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo#8427]
remove lines in the schedule where there are no presentations, e.g. cancelled and summer break https://mondo.monarchinitiative.org/pages/workshop/#outreach

**Comment by sagehrke** [comment]
@twhetzel can you please get this updated in the next day or so. thanks!

**Comment by twhetzel** [comment]
Thanks for the ping, the [page](https://mondo.monarchinitiative.org/pages/workshop/#outreach) is updated.
