### ISSUE TITLE
Unsatisfiable class in Mondo

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#8429]
When refreshing the OMIM gene relations (#8108) we noticed the following unsat.

This will be fun to crack! QC fail: https://github.com/monarch-initiative/mondo/actions/runs/11962410332/job/33350758622

## [osteopetrosis, autosomal dominant 3](http://purl.obolibrary.org/obo/MONDO_0020848) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [osteopetrosis, autosomal dominant 3](http://purl.obolibrary.org/obo/MONDO_0020848) SubClassOf [osteopetrosis](http://purl.obolibrary.org/obo/MONDO_0017198)
    - [osteopetrosis](http://purl.obolibrary.org/obo/MONDO_0017198) SubClassOf [osteosclerosis](http://purl.obolibrary.org/obo/MONDO_0002933)
      - [osteosclerosis](http://purl.obolibrary.org/obo/MONDO_0002933) SubClassOf [bone remodeling disease](http://purl.obolibrary.org/obo/MONDO_0000833)
        - [bone remodeling disease](http://purl.obolibrary.org/obo/MONDO_0000833) EquivalentTo [bone disorder](http://purl.obolibrary.org/obo/MONDO_0005381) and ([disease disrupts](http://purl.obolibrary.org/obo/RO_0004024) some [bone remodeling](http://purl.obolibrary.org/obo/GO_0046849))
          - [bone disorder](http://purl.obolibrary.org/obo/MONDO_0005381) EquivalentTo [disease](http://purl.obolibrary.org/obo/MONDO_0000001) and ([disease has location](http://purl.obolibrary.org/obo/RO_0004026) some [bone tissue](http://purl.obolibrary.org/obo/UBERON_0002481))
  - [osteopetrosis, autosomal dominant 3](http://purl.obolibrary.org/obo/MONDO_0020848) SubClassOf [has characteristic](http://purl.obolibrary.org/obo/RO_0000053) some [Autosomal dominant inheritance](http://purl.obolibrary.org/obo/HP_0000006)
  - [osteopetrosis, autosomal dominant 3](http://purl.obolibrary.org/obo/MONDO_0020848) SubClassOf [has material basis in germline mutation in](http://purl.obolibrary.org/obo/RO_0004003) some [PLEKHM1](http://identifiers.org/hgnc/29017)
  - [autosomal recessive osteopetrosis 6](http://purl.obolibrary.org/obo/MONDO_0012679) SubClassOf [has characteristic](http://purl.obolibrary.org/obo/RO_0000053) some [Autosomal recessive inheritance](http://purl.obolibrary.org/obo/HP_0000007)
  - [autosomal recessive osteopetrosis 6](http://purl.obolibrary.org/obo/MONDO_0012679) EquivalentTo [osteopetrosis](http://purl.obolibrary.org/obo/MONDO_0017198) and ([has material basis in germline mutation in](http://purl.obolibrary.org/obo/RO_0004003) some [PLEKHM1](http://identifiers.org/hgnc/29017))
  - [autosomal dominant disease](http://purl.obolibrary.org/obo/MONDO_0000426) EquivalentTo [disease](http://purl.obolibrary.org/obo/MONDO_0000001) and ([has characteristic](http://purl.obolibrary.org/obo/RO_0000053) some [Autosomal dominant inheritance](http://purl.obolibrary.org/obo/HP_0000006))
  - [autosomal recessive disease](http://purl.obolibrary.org/obo/MONDO_0006025) EquivalentTo [disease](http://purl.obolibrary.org/obo/MONDO_0000001) and ([has characteristic](http://purl.obolibrary.org/obo/RO_0000053) some [Autosomal recessive inheritance](http://purl.obolibrary.org/obo/HP_0000007))
  - [autosomal dominant disease](http://purl.obolibrary.org/obo/MONDO_0000426) DisjointWith [autosomal recessive disease](http://purl.obolibrary.org/obo/MONDO_0006025)

## [paroxysmal nocturnal hemoglobinuria 1](http://purl.obolibrary.org/obo/MONDO_0010438) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [paroxysmal nocturnal hemoglobinuria 1](http://purl.obolibrary.org/obo/MONDO_0010438) SubClassOf [paroxysmal nocturnal hemoglobinuria](http://purl.obolibrary.org/obo/MONDO_0100244)
    - [paroxysmal nocturnal hemoglobinuria](http://purl.obolibrary.org/obo/MONDO_0100244) SubClassOf [acquired aplastic anemia](http://purl.obolibrary.org/obo/MONDO_0015610)
      - [acquired aplastic anemia](http://purl.obolibrary.org/obo/MONDO_0015610) EquivalentTo [aplastic anemia](http://purl.obolibrary.org/obo/MONDO_0015909) and ([has characteristic](http://purl.obolibrary.org/obo/RO_0000053) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141))
  - [paroxysmal nocturnal hemoglobinuria 1](http://purl.obolibrary.org/obo/MONDO_0010438) SubClassOf [has material basis in germline mutation in](http://purl.obolibrary.org/obo/RO_0004003) some [PIGA](http://identifiers.org/hgnc/8957)
    - [PIGA](http://identifiers.org/hgnc/8957) SubClassOf [gene](http://purl.obolibrary.org/obo/SO_0000704)
  - [has characteristic](http://purl.obolibrary.org/obo/RO_0000053) some [acquired](http://purl.obolibrary.org/obo/MONDO_0021141) DisjointWith [has characteristic](http://purl.obolibrary.org/obo/RO_0000053) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)
  - [has material basis in germline mutation in](http://purl.obolibrary.org/obo/RO_0004003) some [gene](http://purl.obolibrary.org/obo/SO_0000704) SubClassOf [has characteristic](http://purl.obolibrary.org/obo/RO_0000053) some [inherited](http://purl.obolibrary.org/obo/MONDO_0021152)

# Ontologies used: 
- axioms.owl (http://purl.obolibrary.org/obo/mondo/imports/axioms.owl)
- mondo.owl (http://purl.obolibrary.org/obo/mondo.owl)
- merged_import.owl (http://purl.obolibrary.org/obo/mondo/imports/merged_import.owl)

**Comment by twhetzel** [comment]
Only MONDO:0020848 remains as an issue. Due to a bug in the omim ingest pipeline and/or lack information in an omim file, a gene association was added to MONDO:0010438 saying it was germline, when it already had somatic.

**Comment by twhetzel** [comment]
Nico pointed this out:
[autosomal recessive osteopetrosis 6](http://purl.obolibrary.org/obo/MONDO_0012679) EquivalentTo [osteopetrosis](http://purl.obolibrary.org/obo/MONDO_0017198) and ([has material basis in germline mutation in](http://purl.obolibrary.org/obo/RO_0004003) some [PLEKHM1](http://identifiers.org/hgnc/29017))
[osteopetrosis, autosomal dominant 3](http://purl.obolibrary.org/obo/MONDO_0020848) SubClassOf [has material basis in germline mutation in](http://purl.obolibrary.org/obo/RO_0004003) some [PLEKHM1](http://identifiers.org/hgnc/29017)

Based on https://omim.org/entry/611497, MONDO:0012679 'autosomal recessive osteopetrosis 6' has a gene association with evidence from medgen that does not meet our criteria for disease defining gene associations (phenotype label is prefixed with a special character, e.g. `?`) we add from omim. However, other sources like [ClinGen](https://search.clinicalgenome.org/kb/genes/HGNC:29017) include both of these diseases caused by this gene. 

@sabrinatoro can you advise how to resolve this issue?

**Comment by twhetzel** [comment]
I removed the gene association from MONDO:0012679 'autosomal recessive osteopetrosis 6' since this does not meet our rules for adding gene associations based on OMIM data and for now we need to move forward on the Tech side based on discussions with @matentzn. If this is not the right decision from a curation perspective, that needs to be addressed later.

**Comment by matentzn** [comment]
FWIW I agree with the change for now, here it is for reference:

https://github.com/monarch-initiative/mondo/commit/da20096d18ad980b78c65398ac60867fc3d506d3#diff-889e0a9ba62d62cc6ee7c5c9bead0075444d506253590ef0dcf4786904ac6768L288824

**Comment by twhetzel** [comment]
These changes were included in https://github.com/monarch-initiative/mondo/pull/8108 so this ticket is also closed now.
