### ISSUE TITLE
Merge and obsolete one of two vCJD terms

### ISSUE THREAD

**Issue by gtsueng** [monarch-initiative/mondo#847]
**Mondo term (ID and Label)**
variant Creutzfeld Jacob disease (MONDO:0005409)

**Reason for deprecation**
Appears to be a spelling variation for:
variant Creutzfeldt-Jakob disease (MONDO:0007012) which has more xrefs associated with it.

**Comment by cmungall** [comment]
oh, we should definitely merge, can you do this Nicole?

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia FYI - I obsoleted MONDO:0005409 variant Creutzfeld Jacob disease (EFO_0004597) on PR https://github.com/monarch-initiative/mondo/pull/865
