### ISSUE TITLE
[Revise subclass] MONDO:0017709 disorder of lipid absorption and transport

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#858]
MONDO:0017709 disorder of lipid absorption and transport
has no definition. It is 
Subclass of: 
pancreas disease
inherited lipid metabolism disorder
RO_0002573 some rare
EFO has more or less the same, and we're questioning the pancreas and inherited/genetic superclasses. Please see https://github.com/EBISPOT/efo/issues/572 for details. Would you be able to provide any additional info on this term please, so we can evaluate the most appropriate label and placement for it?
Thanks!

**Comment by nicolevasilevsky** [comment]
Hi @paolaroncaglia I can't find any additional info about this term.

@maglott could you possibly help give us any more info about UMLS:CN227181?

Or @ana-rath-orphanet could you give us any more info about Orphanet:309028

Thank you!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky thanks for following up!

**Comment by maglott** [comment]
Orphanet is the primary on this record.  MedGen created CN227181 for Orphanet:309028.   The only 'definitions' I see are the classifications.

**Comment by nicolevasilevsky** [comment]
Thank you @maglott! Hopefully Ana or Annie can weigh in from Orphanet.

**Comment by ana-rath-orphanet** [comment]
It corresponds to a group of disorders, which preferred term is Disorder of lipid absorption and transport, including:

![Capture d’écran 2019-10-11 à 01 40 51](https://user-images.githubusercontent.com/43431008/66614272-a7a36280-ebc8-11e9-9e2a-e8d5fcf054a9.png)

No definition yet as it is a category
I don't know if this is what you wanted to have as an answer
Ana

**Comment by nicolevasilevsky** [comment]
Thanks @ana-rath-orphanet! @paolaroncaglia does this help answer your question?

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky and @ana-rath-orphanet 
Many thanks for your feedback! Yes, that helps me address https://github.com/EBISPOT/efo/issues/572. Nicole, feel free to close this ticket.
