### ISSUE TITLE
[Revise subclass] MONDO:0009833 Shwachman-Diamond syndrome

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#859]
Another case of ORDO-derived superclasses, please see https://github.com/EBISPOT/efo/issues/573 for details. Thanks!

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia what is the action item here? Do you want to remove all of the subclass assertions? 

We could make this term a child of MONDO_0002254 'syndromic disease'

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Yes, I suggest to remove all existing subclass assertions for MONDO:0009833 Shwachman-Diamond syndrome, and make it a subclass of MONDO_0002254 'syndromic disease' (as you suggest and based on the definition) and also a subclass of MONDO:0006025 'autosomal recessive disease' based on the Wikipedia entry (see https://en.wikipedia.org/wiki/Shwachman%E2%80%93Diamond_syndrome#Genetics). Thanks.
