### ISSUE TITLE
Representation of responses to drugs

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#860]
Should a category be created for pharmacologic responses? 

- Orphanet made some of their records obsolete
-  There are still some records in the category  from OMIM, e.g. MONDO_0014330
- GTR has many tests related to pharmacogenomics, e.g.
https://www.ncbi.nlm.nih.gov/gtr/tests/558523/indication/
that cannot be represented in MONDO.

If these are in scope for MONDO, seems the category could be more specific than MONDO_0003847, inherited genetic disease

Thanks, 
Donna

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall what are your thoughts?

**Comment by pnrobinson** [comment]
This definitely should not be represented as "MONDO_0003847, inherited genetic disease". I would think that it is probably best to integrate the MONDO data with something like https://www.pharmgkb.org/

**Comment by cmungall** [comment]
Yes, obsolete these. I think the best home is OBA, since these are traits

**Comment by maglott** [comment]
What is OBA?

**Comment by nicolevasilevsky** [comment]
Ontology of Biological Attributes: http://www.obofoundry.org/ontology/oba.html

**Comment by nicolevasilevsky** [comment]
@maglott are there other terms besides MONDO_0014330 'eculizumab, poor response to' that should be obsoleted and added to OBA instead?

Do you want to make a ticket in OBA for the terms you need?
https://github.com/obophenotype/bio-attribute-ontology

Thanks!

**Comment by cmungall** [comment]
I think we can make a first pass at these ourselves

**Comment by cmungall** [comment]
but any help welcome of course!

**Comment by nicolevasilevsky** [comment]
@cmungall there are 98 responses listed on this webpage:
https://www.ncbi.nlm.nih.gov/gtr/tests/558523/indication/

Should all of these be added to OBA? If yes, I can make a ticket. I am not sure if I have ever edited OBA though. It is all pattern based, right?

**Comment by cmungall** [comment]
do these denote abnormal response, or the general response trait? If former, also belong in HPO? How is this coordinated with loinc2hpo? cc @pnrobinson

**Comment by pnrobinson** [comment]
We have a request to add a general abnormal response to medication X, still considering this. I am not sure where best to put these terms & worried about combinatorial explosions (even more :-0). This would not be directly connected to LOINC2HPO, which does not include the genetic infos.

**Comment by maglott** [comment]
For consideration:  When ClinVar receives submissions from PharmGKB, there is a parent (unqualified) response to medication X, and then depending on the drug and the metabolic effect, e.g.
simvastatin response - Toxicity/ADR
simvastatin response - Efficacy

Compare to the terms that Orphanet made obsolete:
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=240985
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=240913

**Comment by maglott** [comment]
Sorry, I did not read from the top of the thread.
Here are more concepts from UMLS and OMIM that we have categorized in part as pharmacologic responses:
C1861502|Colchicine resistance|120080|
C0750384|Warfarin response|122700|
C1860214|Acetophenetidin sensitivity|200300|
C1859352|Carbimazole sensitivity|212060|
C0878587|Slow acetylator due to N-acetyltransferase enzyme variant|243400|
C1838854|Aminoglycoside-induced deafness|580000|
C1827409|Disorder due cytochrome p450 CYP2D6 variant|608902|
C1836023|CYP2C19-related poor drug metabolism|609535|
C3281153|Efavirenz response|614546|

And of course , there are the LOINC codes for function and metabolizer status

**Comment by nicolevasilevsky** [comment]
Thanks @maglott 

@cmungall This is a list of terms that are candidates to be obsoleted from Mondo, and I will create a ticket to request these in OBA:

MONDO_0007348 Colchicine resistance
MONDO_0008697 'acetophenetidin sensitivity'
MONDO_0008906 Carbimazole sensitivity
MONDO_0012294 CYP2C19-related poor drug metabolism
MONDO_0012148 'drug metabolism, poor, CYP2D6-related'
MONDO_0014330 'eculizumab, poor response to'

**Comment by cmungall** [comment]
Note that anything with 'poor' in the label is out of scope for OBA, as it
should be the value-neutral trait. However, you can still make terms for
the agnostic form.

Anything with 'poor' is a candidate for HPO, pending Peter's decision on
this
