### ISSUE TITLE
Should there be a design pattern for genetic disorders vs. unspecified?

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#861]
I am looking at MONDO_0008698 (achalasia (disease)), which is a child of both idiopathic achalasia and inherited genetic disease.

I am looking because I am trying to understand representation of these CUI from UMLS:
[C0014848]  Esophageal Achalasia  (no genetic restriction)
[C2939435]  Hypertensive lower esophageal sphincter (no genetic restriction)
[C1860213]  Achalasia, familial esophageal  (also OMIM ACHALASIA, FAMILIAL ESOPHAGEAL [A11979735/OMIM/PT/200400])

Is there a rule to keep a distinction between heritable disorders and those for which the genetic basis is not part of the definition?  

My questions:
* should there be a distinction between Esophageal Achalasia  and Hypertensive lower esophageal sphincter?
* should there be a distinction between what is currently represented as [C1860213] and [C0014848] /[C2939435]

Thanks

**Comment by sabrinatoro** [comment]
When known, we distinguish between heritable disorder and disorder for which the genetic basis is either unknown or non-existent. Heritable disorders get the axiom: `‘has modifier’ some inherited`. Idiopathic disorders get the axiom: `‘has modifier’ some idiopathic`.

With regards to this issue, it looks like the issues with the “achalasia” term have been resolved already: 
The general concept “achalasia” (UMLS:C1321756, including both inherited and non-inherited) is the parent term for both inherited, 'achalasia, familial esophageal' (MONDO:0100457; UMLS:C1860213), and not inherited,  'idiopathic achalasia' (MONDO:0019635; UMLS:C0859976)

‘Esophageal Achalasia’ and ‘Hypertensive lower esophageal sphincter’ are not represented in Mondo as specific terms (their corresponding UMLS are currently “related” to the general parent term ‘achalasia’). Should we create new terms for these terms (note that they seem to be phenotypes and not diseases)? These would be children of the parent term “achalasia” or ‘idiopathic achalasia’ (MONDO:0019635; UMLS:C0859976), depending on whether the cause of the disease is known (though not genetic) or not, respectively. 
@nicolevasilevsky : any thoughts regarding the creation of new terms?

**Comment by nicolevasilevsky** [comment]
I'm not opposed to adding the new terms if @maglott needs them and it is helpful for MedGen. I recommend that you go ahead. Thanks @sabrinatoro!

**Comment by kanems** [comment]
On behalf of MedGen, I don't think we need to add terms to Mondo if they are represented as phenotypes in HPO; but I do think it is important that if a familial form of a disease and a non-genetic form exist, they should not be lumped into a single concept (i.e. avoid equating an OMIM gene-specific record with a clinical presentation of unknown etiology). If that results in a pattern like:
>Parent: Disease X
>>Child 1: Familial disease X (OMIM PS)
>>>Grandchildren 1-N: Familial disease X, type 1 and  so on.. -N
>>Children 2-n: Acquired/idiopathic/post-infectious disease X (or whatever other etiologies/records exist) 
Then there may be overlap in Mondo with HPO for the top "Parent" term, but I think Mondo has handled those rare instances pretty well and we don't really run into too many issues (except when there are shared preferred names on different concepts, but that's a different sort of problem for a different ticket)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems!

Yes, we don't want to have a genetic form and idiopathic form of a disease lumped into the same concept.

@sabrinatoro I don't think there are any remaining action items, I will close.
