### ISSUE TITLE
MONDO_0009290, glycogen storage disease II

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#862]
**Mondo term (ID and Label):**
MONDO_0009290, glycogen storage disease II
**Xref that should be fixed (ID and label):**
 "exactMatch http://linkedlifedata.com/resource/umls/id/C3695005"
**Other comments:**
Concept: [C3695005]  GLYCOGEN STORAGE DISEASE, TYPE IIIc
vs
"exactMatch http://linkedlifedata.com/resource/umls/id/C0017921"
Concept: [C0017921]  Glycogen storage disease type II

Thanks for checking.

**Comment by nicolevasilevsky** [comment]
Hi @maglott I am a bit unclear what you are asking for. Would you like the xref to UMLS:C3695005  to be removed?

Thanks for clarifying!

**Comment by maglott** [comment]
Yes, please remove UMLS:C3695005. AFAICT,  GLYCOGEN STORAGE DISEASE, TYPE IIIc is distinct from Glycogen storage disease type II
