### ISSUE TITLE
[Revise text def] MONDO:0011071 "hereditary thrombocytopenia with normal platelets and hematologic cancer predisposition syndrome"

### ISSUE THREAD

**Issue by Mohan-Shruthi** [monarch-initiative/mondo#863]
**Mondo term (ID and Label)** 
MONDO:0011071; "hereditary thrombocytopenia with normal platelets and hematologic cancer predisposition syndrome"
URL: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/MONDO_0011071

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**
_Suggested revised term label:_ hereditary thrombocytopenia and hematologic cancer predisposition syndrome
_Suggested revised definition:_ The disorder is characterized by thrombocytopenia of varying severity and a predisposition to hematologic malignancies. It may be caused due to germ line variations in the RUNX1, ETV6 or ANKRD26 genes (PMID: 28600339). This definition is provided by the experts in the Clingen Myeloid Malignancy Variant Curation Expert Panel. (https://clinicalgenome.org/affiliation/50034/). 

Reason for request: The ClinGen Myeloid Malignancy Variant Curation Expert Panel requests that the term associated with MONDO:0011071 be edited as “hereditary thrombocytopenia and hematologic cancer predisposition syndrome” (current term: hereditary thrombocytopenia with normal platelets and hematologic cancer predisposition syndrome). This request is based on the evidence that individuals with germ line variants in the RUNX1, ETV6 or ANKRD26 genes may have varying severity of thrombocytopenia and associated platelet defects, along with a predisposition to hematologic malignancies. Therefore, the “normal platelets” in the current term label has to be removed.  
 
Moreover, we would like to keep this revised term as the parent and suggest child terms incorporating each of the 3 genes that cause this condition. We ask that the definition and synonyms associated with this parent term be removed as they would be appropriate for one of the newly created child terms: hereditary thrombocytopenia and hematological cancer predisposition syndrome associated with RUNX1. I will open a separate issue (NTR) requesting the adding of child terms. At this time, we don’t have any synonym suggestions for this term, since this nomenclature is not in wide use currently and this is an effort to standardize it.

Please let me know if there are any questions.

Thanks,
Shruthi Mohan
ClinGen Biocurator, UNC-Chapel Hill

**Comment by Mohan-Shruthi** [comment]
Hi Chris,

I noticed that the MonDo page for MONDO:0011071 – “hereditary thrombocytopenia and hematologic cancer predisposition syndrome” retains the Exact and Related Synonyms, which are appropriate (and also present) in the newly created child term, MONDO:0100083 – “hereditary thrombocytopenia and hematological cancer predisposition syndrome associated with RUNX1”. Is there a reason for retaining these synonyms in the parent term or can they be removed?

Thanks,
Shruthi

**Comment by nicolevasilevsky** [comment]
@Mohan-Shruthi 

On the parent term, these synonyms were marked with the annotation "Synonym to be removed from public release but maintained in edit version as record of external usage".

Where do you see these synonyms? It seems that they should not be displayed.

**Comment by nicolevasilevsky** [comment]
Oh, I see them in [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0011071) and Monarch

**Comment by Mohan-Shruthi** [comment]
OK. Sending a screenshot from OLS.

**Comment by nicolevasilevsky** [comment]
I think this has been resolved.
