### ISSUE TITLE
Revise or obsolete seeming duplicates for Haemophilus meningitis

### ISSUE THREAD

**Issue by gtsueng** [monarch-initiative/mondo#877]
haemophilus meningitis (MONDO:0000889) definition: Infections of the nervous system caused by bacteria of the genus haemophilus, and marked by prominent inflammation of the meninges. haemophilus influenzae type B is the most common causative organism. The condition primarily affects children under 6 years of age but may occur in adults
AKA: Haemophilus influenzae bacterial meningitis, Haemophilus influenzae caused bacterial meningitis

haemophilus influenzae meningitis (MONDO:0006775) definition: Infections of the nervous system caused by bacteria of the genus HAEMOPHILUS, and marked by prominent inflammation of the MENINGES. HAEMOPHILUS INFLUENZAE TYPE B is the most common causative organism. The condition primarily affects children under 6 years of age but may occur in adults.

The SNOMEDCT IDs for the two are different, and it looks like MONDO:0000889 gained additional specificity/mentions to haemophilus influenzae, which the corresponding SNOMEDCT item lacks. Recommend either revising MONDO:0000889 to not mention haemophilus influenzae in the definition and AKA and reference MONDO:0006775 as a child of it, OR to merge and obsolete one of them.

**Comment by cmungall** [comment]
These should be merged, but do we need a parent concept for infection-site neutral haemophilus?

**Comment by nicolevasilevsky** [comment]
we do have MONDO_0006926 'haemophilus infectious disease', and MONDO_0000889 'haemophilus meningitis' is inferred to be a child
