### ISSUE TITLE
create a table of Mondo source data for website

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#881]
I will add a table to the Mondo website with the source data.

Nico offered to automatically derive this from metadata, but needs some clarification. I'll put up a manually curated table on the website as a placeholder.

cc @cmungall, @jmcmurry

**Comment by nicolevasilevsky** [comment]
I created a 'sources' page on the Mondo website here: https://mondo.monarchinitiative.org/pages/sources/

I can update this when we have the automatically derived data.

**Comment by nicolevasilevsky** [comment]
We need this info for a table/for the website
Want SSSOM files from Mondo to source
- each file gets a header
- indication of the mapping quality (ie high quality, etc.)
- categorization of sources into fully covered, maintained, refresh date,

**Comment by matentzn** [comment]
Why is this ticket in review? Isnt the action item to make the table automatically?

**Comment by nicolevasilevsky** [comment]
yes, that is the action item. Must be in review as a mistake.
