### ISSUE TITLE
[Revise subclass] MONDO_0019395 'Hinman syndrome'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#885]
**Mondo term (ID and Label)**
MONDO_0019395 'Hinman syndrome'

**Suggested revision and reasons**
This is a subclass of 'disease or disorder'. Could we classify it at least under MONDO_0006026 MONDO_0006026

The text def is:
Hinman syndrome (HS) or non-neurogenic neurogenic bladder is a voiding dysfunction of the bladder of neuropsychological origin that is characterized by functional bladder outlet obstruction in the absence of neurologic deficits.

**Comment by cmungall** [comment]
Go ahead and do it. Also add disjointness axiom.

Can you also axiomatize neurogenic bladder? In fact are we sure it's a
disease and not a phenotype? (HP:0000011)
