### ISSUE TITLE
Sucrose Intolerance Disease xref proposal

### ISSUE THREAD

**Issue by TudorOprea** [monarch-initiative/mondo#886]
**Mondo term (ID and Label):*MONDO:0045021*

**Xref that should be fixed (ID and label):*https://omim.org/entry/222900*

**“sucrose intolerance disease” is mappable to https://ghr.nlm.nih.gov/condition/congenital-sucrase-isomaltase-deficiency and to https://omim.org/entry/222900.
Gene associated: "SI" - Rename Disease or add synomym "Congenital sucrase-isomaltase deficiency"  aka MONDO:0009114**

**Comment by cmungall** [comment]
The action here is to make MONDO:0045021 a superclass of MONDO:0009114 (which is already mapped to OMIM:222900 - mappings should be 1:1), and we should add a new sibling for the secondary/acquired form

**Comment by cmungall** [comment]
OK, it's a bit more complex. SI is dual function with 2 domains one serving as the isomaltase, the other as a sucrose alpha-glucosidase. Thus it's possible to have GSID without necessarily having SI.

I think the best thing to do may be to obsolete the generic sucrose intolerance class MONDO:0045021, as it's a dubious grouping, we have the HP classes for representing phenotype
