### ISSUE TITLE
Check gard-derived syns

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#89]
@pnrobinson noticed "Contractural arachnodactyly" should not be a syn for Marfan. We got this from gard. We should check these.

**Comment by nicolevasilevsky** [comment]
@cmungall would you like me to systematically go through all of the gard_subset classes and check the synonyms? If yes, would it be possible to generate a spreadsheet with all these terms and synonyms, as that would be faster than viewing each term in Protege. 
Thanks!

**Comment by nicolevasilevsky** [comment]
@cmungall is this still needed?

**Comment by nicolevasilevsky** [comment]
> "Contractural arachnodactyly" should not be a syn for Marfan 

this is not longer a syn for Marfan.

**Comment by monicacecilia** [comment]
Bigger picture: we need to look into ingest for GARD, would need to review >4K synonyms - manually.

**Comment by nicolevasilevsky** [comment]
I think this should be closed, as this is likely a one-off event. Closing for now.
