### ISSUE TITLE
All classes must have a primary label

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/mondo#890]
**Mondo term (ID Label)**
https://beta.monarchinitiative.org/disease/MONDO:0008932
related to #482 

**Bug/Typo/Error description**

QC checks should scan for classes that don't have any label

**Comment by pnrobinson** [comment]
Here is another example, I think there are several in addition to the obsolete classes

```
{
      "id" : "http://purl.obolibrary.org/obo/MONDO_0020420",
      "meta" : {
        "basicPropertyValues" : [ {
          "pred" : "http://www.w3.org/2004/02/skos/core#exactMatch",
          "val" : "http://www.orpha.net/ORDO/Orphanet_99084"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#exactMatch",
          "val" : "http://linkedlifedata.com/resource/umls/id/C2062889"
        }, {
          "pred" : "http://www.w3.org/2004/02/skos/core#exactMatch",
          "val" : "http://purl.obolibrary.org/obo/NCIT_C99144"
        } ]
      }
    }, 
```

**Comment by cmungall** [comment]
I think there's 2 tickets here

The first is that primary label should not be initialization eg PCD julie
example

The second is weird... I thought we ensured everything has level.. will
check what is up here

**Comment by matentzn** [comment]
I cannot confirm this error @nicolevasilevsky: There is no non-obsolete class without a label in Mondo.

Here is the check:
https://api.triplydb.com/s/nd0Nj9wUL

I think this must have been resolved in one of our QC pushes in the past.

**Comment by nicolevasilevsky** [comment]
ok, I will close this. Please reopen if there is anything else needed. Thanks @matentzn
