### ISSUE TITLE
MONDO_0020420 is neither node nor property

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#892]
**Mondo term (ID Label)**
MONDO_0020420

**Bug/Typo/Error description**
This item is in the nodes section of mondo.json. It is not identified as either a node nor a property. I am not sure if this is valid JSON or not. SInce there is no label, it is not clear what the term is supposed to represent. When I try to find the term in OLS, I get "Something went wrong! Please contact ols-support@ebi.ac.uk to report any bugs or give feedback."
neither node nor property: 
```
{
    "id": "http://purl.obolibrary.org/obo/MONDO_0020420",
    "meta": {
        "basicPropertyValues": [
            {
                "pred": "http://www.w3.org/2004/02/skos/core#exactMatch",
                "val": "http://www.orpha.net/ORDO/Orphanet_99084"
            },
            {
                "pred": "http://www.w3.org/2004/02/skos/core#exactMatch",
                "val": "http://linkedlifedata.com/resource/umls/id/C2062889"
            },
            {
                "pred": "http://www.w3.org/2004/02/skos/core#exactMatch",
                "val": "http://purl.obolibrary.org/obo/NCIT_C99144"
            }
        ]
    }
}
```

**Comment by nicolevasilevsky** [comment]
I think this is fixed, this is 'pulmonary branch stenosis'
