### ISSUE TITLE
http://purl.obolibrary.org/obo/mondo#DEPRECATED

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#893]
**Mondo term (ID Label)**
http://purl.obolibrary.org/obo/mondo#DEPRECATED

**Bug/Typo/Error description**
It seems wrong not to use
"http://www.w3.org/2002/07/owl#deprecated",
as opposed to having a MONDO version of deprecated?

**Comment by cmungall** [comment]
This is more of an artefact of the obo to owl translation. Historically it has been conventional to have synonymtypedefs in ALLCAPS, then these make annoying hash URIs by default. It ends up as the value for a oio:hasSynomymType annotation. I think it's same for HPO LAYPERSON

It would be good to start moving towards standard URIs though. We couldn't really use owl:deprecated with the same structure as it's a property (though actually as it's an AP you can do anything you like with it, it would be unconventional)

We *could* change the structure in this case and just say owl:deprecated=true. But then the structure of these would be different than from all other synonymtypedefs.

I might just keep the same structure, but start moving towards a standard metadata ontology to keep all the URIs in, e.g. om:deprecatedSynonym.

thoughts @dosumis @matentzn ?

**Comment by matentzn** [comment]
+1 for a standard metadata vocab, its coming up here and there in my work as well. I do not understand why http://purl.obolibrary.org/obo/mondo#DEPRECATED exists though rather than owl:deprecated; Once we are out of the R24 madness maybe we should talk what needs to be done to standardise this (and others).

**Comment by balhoff** [comment]
@matentzn this is totally different from owl:deprecated. This one is a synonym type; it's a "valid" synonym but not encouraged to be used (e.g., it is offensive in modern times). This also shows up in Uberon as `http://purl.obolibrary.org/obo/uberon/core#DEPRECATED`. But HPO has an actual IRI, `http://purl.obolibrary.org/obo/HP_0031859`, "obsolete synonym", for this annotation. Personally I would prefer a different English word from "obsolete". But we've already had long discussions about this. :-)

See an example in synonyms of HP 'Mesomelic short stature'.

**Comment by matentzn** [comment]
Ahhh now I know what this is :) thanks Jim!

**Comment by matentzn** [comment]
I guess we cant do anything about this for now; unless we want to get into the abyss of OBO / OWL issues. I will just ask one thing, and if someone answers we can re-open the issues: _Should we try to establish a standard vocabulary for synonymtypes somewhere in OMO, that covers things like deprecation, lay person etc?_
