### ISSUE TITLE
ICD10CQ87.3

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#894]
I am wondering if we want to transform Xrefs like ICD10CQ87.3 to ICD10:CQ87.3 ? 
We are not really consistent here. For instance, we tranform NCBI Gene ids such as 2270 to NCBIGene:2270 (although they do not do this), but we do not transform HGNC ids (which are also integers). Thus, we are being inconsistently inconsistent with the normalization of IDs from the community. This makes it a little more difficult to parse MONDO into data structures.

Thoughts? @cmungall @mellybelly @jmcmurry others?

**Comment by nicolevasilevsky** [comment]
I am in favor of being consistent!

**Comment by pnrobinson** [comment]
So for now in phenotools I will internally transform ICD10CQ87.3 to ICD10:CQ87.3 (and thus make it into a TermId object). But would the data experts in our group consider that to be a grave and misguided mistake?
Moving forward it would be good for us to pre-normalize ids like this in our datastructures.
It is also suboptimal that our Xrefs con be (currently) either (i) CURIES (ii) URLS (iii) strings

**Comment by jmcmurry** [comment]
Not at all grave or misguided. Decoupling ICD from the local part is the preferred mechanism. I thought you could use identifiers.org as the HTTP URI. Details here: https://registry.identifiers.org/registry/icd. However, that doesn't appear to be the case. 

Nothing works (cc'ing @sarala here) but I don't now what should.
-  http://identifiers.org/icd/CQ87 
- http://identifiers.org/icd:CQ87
- http://identifiers.org/icd/CQ87.3
- http://identifiers.org/icd:CQ87.3

I give up; I don't know how one would derive a deterministic URI at any destination.

Ultimately, we will want to move toward ICD11 which will have a more sane and more straightforwardly resolvable identifier structure.  http://id.who.int/icd/entity/1651053999

We have a workaround mechanism in Monarch whereby we can make a temporary resolver for certain IDs resolve even if they are outside of our control. We use this for blank nodes currently. We should constrain all xrefs to be (resolvable) curie syntax.

Feels like there is something I am missing.

**Comment by cmungall** [comment]
> I am wondering if we want to transform Xrefs like ICD10CQ87.3 to ICD10:CQ87.3

Yes! But I am wondering what you are referring to. All xrefs in mondo are already CURIEs, and we use the ICD10 prefix for ICD10

> Details here: https://registry.identifiers.org/registry/icd

I strongly recommend embedding the major version in the prefix for ICD as ICD9, ICD10, and ICD11 are totally different (unlike how different versions of GO, HP, MONDO are different).

**Comment by pnrobinson** [comment]
"All xrefs in mondo are already CURIEs"
=> this is not true in the JSON version. 
=> Have you tried this still buggy tool for phenopackets and pheno-related ontologies? https://github.com/pnrobinson/phenotools
It does pick up a lot of warnings/errors in Mondo that we should fix, including the ICD-non-curie-ness.

**Comment by cmungall** [comment]
Sorry forgot to follow up. Ugh yes we have some malformed xrefs, have fixed and implemented a check

**Comment by nicolevasilevsky** [comment]
Has this been resolved? Can we close this ticket?

**Comment by nicolevasilevsky** [comment]
closing, please reopen if needed
