### ISSUE TITLE
Creation of broader disease entity for ACTA1 related disorder(s)

### ISSUE THREAD

**Issue by justyneross** [monarch-initiative/mondo#900]
For new term requests, please provide the following information:

## Preferred term label

Actinopathy

Note: I see the term “qualitative or quantitative defects of alpha-actin” (MONDO:0016193) exists and this may be the same disease entity I am trying to create but it lacks many details. If that is the case, then I would suggest renaming the entry to Actinopathy, the name currently used in the field, and changing the parent/child terms as described below. 

## Synonyms

actin myopathy, ACTA1 disease

## Textual definition

Actinopathy is a disorder of the musculoskeletal system that covers a wide spectrum of phenotypes and is caused by pathogenic variants in the skeletal muscle α-actin gene (ACTA1). These variants lead to a variety of overlapping adult onset and congenital myopathies characterized by muscle weakness, hypotonia, myopathic face, respiratory dysfunction, and rarely cardiac involvement. Specific skeletal muscle structural lesions visible on muscle biopsy include actin accumulations, nemaline and intranuclear bodies, fiber-type disproportion, cores, caps, dystrophic features and zebra bodies. Disorders associated with ACTA1 pathogenic variants can have autosomal dominant (90%) or recessive (10%) inheritance.

PMIDs in support of this term request: 22825594

## Suggested parent terms

congenital myopathy
qualitative or quantitative protein defects in neuromuscular diseases

## Suggested Child terms for collapse under new term

nemaline myopathy 3 (MONDO:0008070)
congenital fiber-type disproportion myopathy (MONDO:0009711)
congenital myopathy with excess of thin filaments (MONDO:0020342)
progressive scapulohumeroperoneal distal myopathy (MONDO:0014800)
cap myopathy (MONDO:0015753)
zebra body myopathy (MONDO:0019949)

Comment: The most penetrant phenotype among all of the actinopathy disease entities is muscular weakness. While nemaline myopathy is the most common presentation, several other myopathies have been reported in association with ACTA1 mutations. The absence of clearly defined and/or distinct differences in molecular mechanism, coupled with noted phenotypic variability (both intra- and inter-familial) for individual variants, indicates that these entities are part of the same clinical spectrum.

**Comment by maglott** [comment]
If this is restricted to alpha actin, then should the preferred term be alpha actinopathy?

**Comment by justyneross** [comment]
Thank you for the suggestion, in fact it is restricted to alpha1 actin (as opposed to alpha2) so “alpha1 actinopathy” would be the preferred term.
Justyne

________________________________
