### ISSUE TITLE
[Revise subclass] for MONDO:0100080 Cardioectodermal syndrome

### ISSUE THREAD

**Issue by courtneythaxton** [monarch-initiative/mondo#901]
**Mondo term (ID and Label)** MONDO:0100080 Cardioectodermal syndrome

**Suggested revision and reasons**

At this time, two orphan terms appear to have been mapped incorrectly.

Please consider the removal of MONDO:0013600, Insomina (disease) and MONDO:0003406 (sleep wake disorder). 

@nicolevasilevsky @cmungall @mellybelly 

Thanks
@courtneythaxton

**Comment by nicolevasilevsky** [comment]
@courtneythaxton Sorry for the delay in addressing this ticket. I think this issue has been resolved, could you please reopen if action is still needed? Thanks!
