### ISSUE TITLE
Weird AnnotationAssertion in owlaxioms: section of OBO file

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#902]
```
AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#created_by> <http://purl.obolibrary.org/obo/MONDO_0300000> \"\")
```

Is the presence of this assertion necessary or should it be removed?

**Comment by nicolevasilevsky** [comment]
![image](https://user-images.githubusercontent.com/6722114/67583457-79fa0580-f700-11e9-9837-68210b0b4c20.png)

there is this extra annotation, is that what you mean? I can fix this

**Comment by matentzn** [comment]
Thanks Nicole! I have already fixed it in the pull request here: https://github.com/monarch-initiative/mondo/pull/903

**Comment by nicolevasilevsky** [comment]
cool, thanks @matentzn!

**Comment by matentzn** [comment]
Fixed by https://github.com/monarch-initiative/mondo/pull/903
