### ISSUE TITLE
xref on endotheliitis uses a URI, causing bad expansion in owl format

### ISSUE THREAD

**Issue by sgblanch** [monarch-initiative/mondo#904]
**Mondo term (ID Label)**
http://purl.obolibrary.org/obo/MONDO_0015292

**Bug/Typo/Error description**
xref in mondo-edit.obo uses a URI which causes it to be expanded to http://purl.obolibrary.org/obo/http_//purl.obolibrary.org/obo/UBERON_0001986 in the released mondo.owl

**Comment by cmungall** [comment]
oh dear, we should not be making equiv xrefs to uberon classes! @nicolevasilevsky can you remove this. And remove the incorrect NCIT derived syns too

**Comment by cmungall** [comment]
it turns out the ncit xref is incorrect, remove it
