### ISSUE TITLE
is  MONDO:0000171  equivalent to MONDO:0019523

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#906]
They seem to have the same children
I don't know whether https://www.omim.org/phenotypicSeries/PS236670
Muscular dystrophy-dystroglycanopathy, type A

is equivalent to:
ORPHA:899,
Walker-Warburg syndrome

**Comment by nicolevasilevsky** [comment]
I think MONDO_0019523 'Walker-Warburg syndrome' is the same as OMIM:253800 MUSCULAR DYSTROPHY-DYSTROGLYCANOPATHY (CONGENITAL WITH BRAIN AND EYE ANOMALIES), TYPE A, 4; MDDGA4, which is cross-referenced but not a synonym.

I can add it as a synonym. Would that address this ticket?

**Comment by maglott** [comment]
I don't know what the equivalence is, which is why I raised the question.  But if Walker-Warburg syndrome is the same as OMIM:253800, then  ORPHA:899 should be added as an XRef.
@ahamosh , @ana-rath-orphanet  what do you think?

**Comment by ahamosh** [comment]
Sorry for the delay.  OMIM decided that Muscle-Eye-Brain and Walker-Warburg are one phenotype as outcome (lethal for the former, not for the latter) depends on treatment and timing.   Walker-Warburg due to FKTN is the same as MDDGA4.

**Comment by nicolevasilevsky** [comment]
Thanks @ahamosh!

Ok - it is my understanding that `MONDO_0019523 'Walker-Warburg syndrome'` ([OMIM:253800](https://mirror.omim.org/entry/253800)) is equivalent to `MONDO_0009678 'Fukuyama congenital muscular dystrophy'`(and these are equivalent to [ORPHA:899 ](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=8725&Disease_Disease_Search_diseaseGroup=899&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Walker-Warburg-syndrome&title=Walker-Warburg%20syndrome&search=Disease_Search_Simple)Walker-Warburg syndrome).

Thank you!

**Comment by annieolry** [comment]
Sorry not to have commented before. I think that merging these 3 entities is a bit premature. These 3 terms: Walker-Warburg, Muscle-eye-brain and Fukuyama are still widely used in Clinics for coding patients when genetic is not yet confirmed or even when it is. It is a spectrum of severity but yet, there is no consensus in the community to merge them. It would be very interesting to have inputs of experts in this field before obsoleting and merging the entities.

**Comment by nicolevasilevsky** [comment]
Based on @annieolry's comment, I don't think we should merge these terms. Please reopen if anyone disagrees and would like to revisit this issue.
Thanks!
