### ISSUE TITLE
[Revise subclass] Questions re: subclasses of X-linked syndromic intellectual disability	

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#912]
**Mondo term (ID and Label)**
These terms are subclasses of X-linked syndromic intellectual disability and it is questioned whether they should be.

ID | Label | Note
-- | --- | ---
MONDO:0010568 | Aicardi syndrome | Primarily   an epilepsy condition. Characterized by a triad of agenesis of the corpus   callosum, distinctive chorioretinal lacunae, and infantile spasms
MONDO:0010752 | VACTERL association, X-linked,   with or without hydrocephalus | This is a muliple congenital anomaly condition. VACTERL is an acronym for vertebral anomalies (similar to those of spondylocostal dysplasia), anal atresia, cardiac malformations, tracheoesophageal fistula, renal anomalies (urethral atresia with hydronephrosis), and limb anomalies (hexadactyly, humeral hypoplasia, radial aplasia, and proximally placed thumb)
MONDO:0010631 | incontinentia pigmenti | Primarily a skin condition. Seizures, intellectual disability, and other CNS abnormalities have been reported in approximately 30% of individuals with IP

All of these subclassOf assertions come from @Orphanet (cc @ana-rath-orphanet and @annieolry)

Should X-linked syndromic intellectual disability be an excludedSubclassOf for these terms?

**Comment by cmungall** [comment]
do it
