### ISSUE TITLE
return to Marfan 2

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#913]
I know https://github.com/monarch-initiative/mondo/issues/560 was closed,  but am wondering if ORPHA:284973 (Marfan syndrome type 2) should be considered equivalent to MONDO:0012427?
OMIM (https://omim.org/entry/610168) reports MARFAN SYNDROME, TYPE II, FORMERLY as a former term, and ORPHA:284973 cross-references OMIM:610168

**Comment by maglott** [comment]
And from the GeneReview by Dietz:
Marfan syndrome type 2. This term is no longer in use. It was used by Mizuguchi et al [2004] in a report of individuals with a phenotype that resembled Marfan syndrome but is now known to be Loeys-Dietz syndrome, an autosomal dominant disorder caused by a heterozygous pathogenic variant in either TGFBR1 or TGFBR2 (see Differential Diagnosis).

**Comment by nicolevasilevsky** [comment]
Thanks for reporting this @maglott. I'll wait to see if anyone from the community has any comments before taking action.

**Comment by nicolevasilevsky** [comment]
Looking into this more closely, I see Marfan Syndrome Type 2 was already obsoleted, but there is not a 'replaced by'. So the required action for this ticket is to add a 'replaced by' MONDO_0012427 to the obsoleted class 'obsolete Marfan Syndrome Type 2'.

**Comment by maglott** [comment]
I believe so, and, if Orphanet  agrees, add the xref for ORPHA:284973  to MONDO:0012427.

**Comment by nicolevasilevsky** [comment]
@Orphanet @ana-rath-orphanet @annieolry 
do you agree?

**Comment by annieolry** [comment]
This issue is currently assessed by the European Reference Network. Up to now, they still use ORPHA code of Marfan type 2 for patient diagnosis. We should have an answer very soon.
