### ISSUE TITLE
Reclassify EDS in MONDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#92]
Per @pnrobinson, we should reclassify EDS using the latest classification: https://www.ehlers-danlos.com/2017-eds-international-classification/

Then, we should create a bucket under the main EDS that is something like
"uncertain", "n=1", "controverisal" -- not sure about the best name. Another strategy wouyld be to remove these cases completely from the main Monarch website and
to show a button that there are n=1 cases related to EDS that the user can get to with another mouse click.

**Comment by nicolevasilevsky** [comment]
@pnrobinson what about using the following def:
The Ehlers–Danlos syndromes (EDS) are a clinically and genetically heterogeneous group of heritable connective
tissue disorders (HCTDs) characterized by joint hypermobility, skin hyperextensibility, and tissue fragility.
Ref: PMID:28306229 (this is the classification article that you provided)

I can do a pull request, if you agree. I can remove the synonyms. Should we add EDS as a syn too?

**Comment by pnrobinson** [comment]
This definition is a LOT better, let's go for it!
EDS is a very recognizable synonym in the community!

**Comment by nicolevasilevsky** [comment]
Cool, I'll make a PR. Thanks @pnrobinson!

**Comment by nicolevasilevsky** [comment]
@cmungall I am getting a weird diff when I edit the MONDO file:

diff --git a/src/ontology/mondo-edit.obo b/src/ontology/mondo-edit.obo
index d8fb95f..dda688a 100644
--- a/src/ontology/mondo-edit.obo
+++ b/src/ontology/mondo-edit.obo
@@ -136687,7 +136687,6 @@ subset: gard_rare {source="GARD:0006975"}
 subset: ordo_clinical_subtype {source="Orphanet:284963"}
 subset: ordo_disease {source="Orphanet:558"}
 subset: prototype_pattern {source="https://github.com/monarch-initiative/monarch-disease-ontology/issues/101"}
-property_value: excluded_synonym "Contractural arachnodactyly" xsd:string {source="GARD:0006975"}
 synonym: "MARFAN SYNDROME" RELATED [MONDO:Lexical, OMIM:154700]
 synonym: "Marfan syndrome type 1" RELATED [Orphanet:284963]
 synonym: "Marfan Syndrome, Type 1" RELATED [OMIM:154700]
@@ -136724,6 +136723,7 @@ is_a: MONDO:0020236 {source="Orphanet:558"} ! lens position anomaly
 is_a: MONDO:0020272 {source="Orphanet:558"} ! connective tissue disease with eye involvement
 relationship: disease_has_basis_in_dysfunction_of NCBIGene:2200 {source="mim2gene_medgen"}
 property_value: confidence "0.014130103558823048" xsd:double
+property_value: excluded_synonym "Contractural arachnodactyly" xsd:string {source="GARD:0006975"}
 property_value: seeAlso https://rarediseases.info.nih.gov/diseases/6975/marfan-syndrome xsd:anyURI {source="GARD:0006975"}
 
 [Term]
@@ -348504,10 +348504,9 @@ is_a: MONDO:0018331 {source="Orphanet:98203"} ! rare genetic dystonia
 [Term]
 id: MONDO:0020066
 name: Ehlers-Danlos syndrome
-def: "An inherited connective tissue disorder characterized by loose and fragile skin and joint hypermobility." [NCIT:P378]
+def: "The Ehlers–Danlos syndromes (EDS) are a clinically and genetically heterogeneous group of heritable connective tissue disorders (HCTDs) characterized by joint hypermobility, skin hyperextensibility, and tissue fragility." [PMID:28306229]
 subset: ordo_group_of_disorders {source="Orphanet:98249"}
-synonym: "Cutis hyperelastica" EXACT [DOID:13359, SCTID:238848002]
-synonym: "elastic skin" EXACT [CSP2005:1849-3115, DOID:13359]
+synonym: "EDS" EXACT []
 xref: COHD:79145 {source="MONDO:equivalentTo"}
 xref: DOID:13359 {source="MONDO:Leader", source="MONDO:equivalentTo"}
 xref: ICD10:Q79.6 {source="ORDO:98249/specific", source="ORDO:98249/e", source="Orphanet:98249", source="DOID:13359"}

**Comment by cmungall** [comment]
is this done?

**Comment by nicolevasilevsky** [comment]
I think I made a mistake here - I added the def and syn to MONDO_0012114 Ehlers-Danlos syndrome, Beasley-Cohen type, not MONDO_0020066 'Ehlers-Danlos syndrome'. I will fix this later.

**Comment by nicolevasilevsky** [comment]
this is fixed now in PR #105
