### ISSUE TITLE
GARD xref for Alzheimer

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#921]
**Mondo term (ID and Label):**
MONDO_0004975: Alzheimer disease  
MONDO_0015140: early-onset autosomal dominant Alzheimer disease

**Xref that should be fixed (ID and label):**
http://purl.obolibrary.org/obo/GARD_0000632 familial Alzheimer
https://rarediseases.info.nih.gov/diseases/12798/early-onset-autosomal-dominant-alzheimer-disease
**Other comments:**
http://purl.obolibrary.org/obo/GARD_0000632 corresponds to familial Alzheimer.  
https://rarediseases.info.nih.gov/diseases/10254/alzheimer-disease  corresponds to the general term

I don't see a node for familial Alzheimer; should there be one? GARD also provides 
https://rarediseases.info.nih.gov/diseases/12799/late-onset-familial-alzheimer-disease as another genetic Alzheimer; perhaps the broad synonym familial Alzheimer disease/GARD_632  should be removed from MONDO_0015140 to define a new node.  

**For the disease experts**

1.  create a node for Familial Alzheimer http://purl.obolibrary.org/obo/GARD_0000632
2. remove the broad synonym Familial Alzheimer, from MONDO_0015140
3.  create a node for Late-Onset Familial Alzheimer Disease, https://rarediseases.info.nih.gov/diseases/12799/late-onset-familial-alzheimer-disease

**Comment by cmungall** [comment]
This sounds reasonable to me, can you implement Nicole?

**Comment by cmungall** [comment]
This sounds reasonable, can you implement Nicole?
