### ISSUE TITLE
[Revise subclass] MONDO:0005305 epistaxis

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#924]
MONDO:0005305 epistaxis
is currently Subclass of:
cardiovascular disease
nose disease
We have revised the placement of the corresponding EFO term (EFO_0003895) by making it a subclass of the more specific 'vascular disease', rather than 'cardiovascular disease' (we left the 'nose disease' parent as was). Would you consider doing the same, please, so we don't inherited the unwanted broader parent? :-)
Thanks,
Paola

**Comment by cmungall** [comment]
I might go further and obsolete it's only child MONDO:0007563 ! epistaxis, hereditary

it exists to be equivalent to
https://omim.org/entry/132500

Which has a single pub - from 1940

**Comment by paolaroncaglia** [comment]
@cmungall 
@nicolevasilevsky 
@zoependlington 
I'd be ok with replacing the disease term for epistaxis (nosebleed) with a phenotype one. We'll revise EFO accordingly when Mondo release the change.
As for the hereditary child, I wondered about that too, happy to see it gone. Thanks!

**Comment by maglott** [comment]
@ahamosh , any thoughts about https://omim.org/entry/132500

**Comment by pnrobinson** [comment]
I am not sure that there is a *disease* whose main (defining) characteristic is hereditary epistaxis to the extent that a geneticist would name the disease "Hereditary epistaxis", but there is (for instance) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4709944/. There seems to be an ICD10 code for hereditary epistaxis (https://www.icd10data.com/ICD10CM/Codes/I00-I99/I70-I79/I78-/I78.0). I am not sure this is the most useful way of classifying/naming these diseases. @ahamosh, thoughts?

**Comment by ahamosh** [comment]
In OMIM, this is a single report that is from 1940.  I didn't name this and this a total outlier that I wouldn't spend time on.  In principle though there is nothing wrong with calling something hereditary epistaxis, if it is dominant and isolated to epistaxis although probably better to call it dominant isolated epistaxis, similar to dominant isolated ectopia lentis.  The fact that it is a null entry in OMIM, means that even at the time, Dr. McKusick wasn't sure that it was real...

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson and @ahamosh for your input. My understanding it is okay to obsolete these terms. Please let me know if otherwise.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
@cmungall 
Last EFO-related "pending PR" for today!
