### ISSUE TITLE
missing colon (:) in xref mondo.obo

### ISSUE THREAD

**Issue by need47** [monarch-initiative/mondo#925]
**Xref that should be fixed (ID and label):**
MONDO:0000409	chorioamnionitis (not a dbxref)
MONDO:0007029	Orphanet107 (missing colon)
MONDO:0013038	ICD10CQ87.3 (missing colon)
MONDO:0019124	Orphanet727 (missing colon)

**Comment by need47** [comment]
The mondo.obo was downloaded from: http://obofoundry.org/ontology/mondo.html

Note the MONDO website also contains these xrefs as Reference:
https://monarchinitiative.org/disease/MONDO:0000409
https://monarchinitiative.org/disease/MONDO:0007029
https://monarchinitiative.org/disease/MONDO:0013038
https://monarchinitiative.org/disease/MONDO:0019124

**Comment by nicolevasilevsky** [comment]
this is interesting. I don't see these issues in the mondo-edit.obo file, but I do see them in the links in Monarch that are posted above.

Reassigning to @cmungall and @kshefchek

**Comment by cmungall** [comment]
I fixed this previously with #5f011269fc8248c813a74f39e7d3e6a97c0eb03d

**Comment by cmungall** [comment]
@nicolevasilevsky - the `git blame` command can be useful here to see history on a per-line basis

**Comment by need47** [comment]
Thanks for the quick fix. When will the mondo.obo file be updated?

**Comment by nicolevasilevsky** [comment]
Mondo is released around the first of every month.

**Comment by need47** [comment]
Got you, thanks.
