### ISSUE TITLE
[Revise subclass] MONDO:0001071 intellectual disability

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#926]
Stemming from https://github.com/EBISPOT/efo/issues/605

The branch under MONDO:0001071 intellectual disability may benefit from some revisions.
- [x] Its direct children (other than 'non-syndromic i.d.' and 'syndromic i.d.') could probably be placed under 'non-syndromic i.d.' or 'syndromic i.d.'
- [x] The labels of a few of the terms above may have suffered from excessive lowercasing ;-)
- [x]  MONDO:0014224 'Developmental delay with autism spectrum disorder and gait instability' is in the non-syndromic sub-branch. However, by definition non-syndromic intellectual disabilities appear without other abnormalities, while the reference to gait instability suggests that MONDO:0014224 should be in the syndromic sub-branch instead.
- [x] There's a typo in the defs of MONDO:0000509 non-syndromic intellectual disability and MONDO:0000508 syndromic intellectual disability ("_A_ intellectual...")
- [x] MONDO:0005503 developmental disorder of mental health has a typo in the definition that comes from EFO, I fixed it in EFO but you may wish to do the same: "...psycholotgical..."

Thanks!

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia what do you think is the best parent of MONDO_0010252 'intellectual disability, X-linked, with panhypopituitarism'?

I left it under 'intellectual disability' for now.

I moved all the other classes to children of 'syndromic intellectual disability'

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Thanks for fixing all of the above!
As for MONDO_0010252 'intellectual disability, X-linked, with panhypopituitarism', I agree that it's a tricky one. Based on the detailed clinical features in the OMIM entry (https://mirror.omim.org/entry/300123), I suggest to make MONDO_0010252 a subclass of 'syndromic disease' and 'panhypopituitarism, X-linked', but not 'intellectual disability' because that is not reported in all cases and looks more like a symptom/phenotype to me. 
(Note for self, we don't have 'intellectual disability, X-linked, with panhypopituitarism' in EFO.)
