### ISSUE TITLE
update synonyms and def for MONDO:0020066 'Ehlers-Danlos syndrome'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#93]
per @pnrobinson 
https://monarchinitiative.org/disease/MONDO:0020066#overview

AKA:  Cutis hyperelastica, elastic skin 
=> I do not think these are good AKAs!!

def: An inherited connective tissue disorder characterized by loose and fragile skin and joint hypermobility. 
This is also not a great definition.

**Comment by cmungall** [comment]
Bad Synonyms: report source [here DOID, which seems to have gotten them via SNOMED], report proposed action: (e.g. [a] demote EXACT->RELATED; [b] add a DEPRECATED axiom [c] retire the axiom).

In this case I think c is best. Here we change the AP from synonym to excluded_synonym

Def: Also report source [here NCIT]. Let's create a better one and propagate it back to NCIT and ORDO [which currently lacks a def]

**Comment by nicolevasilevsky** [comment]
- made syn 'Cutis hyperelastica, elastic skin' for MONDO:0020066 'Ehlers-Danlos syndrome' an excluded synonym (in PR...)

**Comment by nicolevasilevsky** [comment]
I think this addresses everything. 

@cmungall when you say 'Also report source [here NCIT]' - is there something else I should do, or is suggesting the new def to NCIT what you meant?

**Comment by cmungall** [comment]
Yes, you can see we have an axiom annotation on the def indicating it came from NCIT. If we think the NCIT def can be improved on then we can communicate this back to them so everyone wins
