### ISSUE TITLE
Mondo release request

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#936]
In order to map Mondo to other disease ontologies, I basically need `mondo-base.owl` and the equivalent-class mappings of MONDO ids to other disease ontology IDS (DOID, ORPHANET, etc).

Is it possible to include the MONDO alignments (bridges) as part of the [release](https://github.com/monarch-initiative/mondo/releases/tag/v2019-10-25) in a sperate file?

**Comment by maglott** [comment]
I concur that this would be of general use. Does the definition of 'equivalent-class' mapping require that the MONDO/Other relationship is strictly 1:1?

**Comment by cmungall** [comment]
@matentzn the equivalencies are always available at http://purl.obolibrary.org/obo/mondo/imports/equivalencies.owl

base:
http://purl.obolibrary.org/obo/mondo/mondo-base.owl

@maglott - the semantics of owl equivalentClass are such that all concepts are strictly identical in meaning. This always translates to a 1:1 mapping, *except* when we do a 'proxy merge' - we decide that two concepts in an external resource mean the same thing. This is rare, and the numbers usually come down as we work with the upstream to resolve this.

I will leave this open until we have better documentation and all our products are fully described on the obo page

**Comment by maglott** [comment]
Thanks

**Comment by matentzn** [comment]
Ok thanks! I will close this then for now!
