### ISSUE TITLE
[Revise text def] MONDO:0013343 C1Q deficiency

### ISSUE THREAD

**Issue by bmeldal** [monarch-initiative/mondo#939]
**Mondo term (ID and Label)**
MONDO:0013343 C1Q deficiency

**Suggested revision of textual definition. Please include a source, like a PubMed ID (in the format PMID:#######)**

- "C1q is a protein and together with other proteins, C1r and C1s,..."
+"C1q is a COMPLEX and together with other proteins, C1r and C1s,..."
because C1q constitute of C1QA , C1QB and C1QC.

PMID:29449492

There are also a few spurious white spaces before or after punctuations.

Birgit

**Comment by nicolevasilevsky** [comment]
Hi @bmeldal 
I am not totally clear what your request is. Would you like me to replace the current text definition? If so, could you please paste the text you'd like to use in a comment?
Thanks!

**Comment by bmeldal** [comment]
Ok:

Corrected def:
C1q deficiency is a rare disorder associated with recurrent skin lesions, chronic infections, systemic lupus erythematosus (SLE) or SLE-like diseases. It has also been associated with a kidney disease known as mesangial proliferative glomerulonephritis. C1q is a complex and together with other proteins, C1r and C1s, it forms the C1 complex. This complex is important for the activation of the complement system (a group of proteins that work with the immune system). It also disposes cells that are dead. C1q deficiency presents in 2 different forms, absent C1q protein or abnormal C1q protein. Symptoms include infections (ear infections (otitis media), meningitis, urinary tract infections, oral infections); skin lesions (small blisters (vesicles), dark patches, and atrophic areas) that get worse upon light exposure; cataracts; loss of eyelashes, eyebrows, and scalp hair; blood in urine; and glomerulonephritis. About 93% of cases are associated with systemic lupus erythematosus. It can be caused by mutations in the C1QA, C1QB or C1QC genes and is inherited in an autosomal recessive pattern. Treatment depends on the symptoms. Recently, it was shown that C1q production can be restored by allogeneic hematopoietic stem cell transplantation, a procedure in which a person receives blood-forming stem cells (cells from which all blood cells develop) from a genetically similar, but not identical donor.

I've asked the EBI SPOT team to import it into EFO and they asked me to ask you to correct the def :)
