### ISSUE TITLE
Review: nephropathic cystinosis and AKL

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#960]
id: MONDO:0021725
name: Abderhalden-Kaufmann-Lignac syndrome
def: "A rare autosomal-recessive, lysomal storage childhood disorder involving deposits of cystine crystals in various parts of the body, including the bone marrow, conjunctiva and cornea." [http://www.checkorphan.org/diseases/abderhalden-kaufmann-lignac-syndrome, https://orcid.org/0000-0001-5208-3432, https://www.medigoo.com/articles/abderhalden-kaufmann-lignac-syndrome/, PMID:3606421]

All of the definition citations for AKL are dubious. 

this is blank
https://rarediseases.info.nih.gov/diseases/10074/abderhalden-kaufmann-lignac-syndrome

there is one pmid, in russian 
https://www.ncbi.nlm.nih.gov/pubmed/3606421
"A case of nephropathic cystinosis (Abderhalden-Lignac-Kaufmann disease) in a 8-month girl is reported"

Is the MONDO ID describing the case, or ALK? The abstract seems to state that ALK is just a synonym for nephropathic cystinosis, and these should be merged. I am not seeing any evidence for a distinct disease here

Is this disease any different from AR

**Comment by cmungall** [comment]
Also:

id: MONDO:0009065
name: cystinosis, nephropathic
def: "Cystinosis is an inherited condition in which the body accumulates the amino acid cystine (a building block of proteins) within the cells. Excess cystine forms crystals that can build up and damage cells. These crystals can negatively affect many systems in the body, especially the kidneys and eyes. There are three distinct types of cystinosis: nephropathic cystinosis, intermediate cystinosis, and non-nephropathic or ocular cystinosis. All three types of cystinosis are caused by mutations in the CTNS gene andinherited in an autosomal recessive pattern." [https://rarediseases.info.nih.gov/diseases/9755/nephropathic-cystinosis]


The definition is for a more generic class, cystinosis

**Comment by cmungall** [comment]
this structure is dubious:

![image](https://user-images.githubusercontent.com/50745/68864842-9f968100-06a6-11ea-8ddc-19a2981b64e5.png)

MONDO:0009065 cystinosis, nephropathic: is equiv to https://omim.org/entry/219800 which looks like generic entry but may be for infantile form?
MONDO:0009066 juvenile nephropathic cystinosis: is equiv to https://omim.org/entry/219900 late onset juvenile form

**Comment by cmungall** [comment]
@nicolevasilevsky I merged MONDO:0009065  into MONDO:0009066 can you deal with AKL?

**Comment by nicolevasilevsky** [comment]
Sure thing, Chris!

@GARDinfocenter FYI- I am going to merge this term (https://rarediseases.info.nih.gov/diseases/10074/abderhalden-kaufmann-lignac-syndrome) with 'cystinosis, nephropathic'. Maybe you want to delete the GARD page?

**Comment by GARDInfoCenter** [comment]
Thanks for letting us know. I have forwarded this to our team.

Best,
Maria

**Comment by nicolevasilevsky** [comment]
Hi @GARDInfoCenter, no rush, but just checking if you had any updates on this. Thanks!

**Comment by GARDInfoCenter** [comment]
We have retired AKL but for now will continue to list nephropathic cystinosis.

**Comment by maglott** [comment]
I think there is still a problem with capturing the concept of nephroplastic cystinosis
* there is no such term 
* MONDO:0018467 has the label nephropathic infantile cystinosis but a definition that includes ocular
* MONDO:0018467 has both an exact and related synonym for cystinosis, nephropathic

I think  there should be nodes for
* cystinosis
** nephropatic cystinosis
***infantile nephopathic cystinosis
***juvenile nephropathic cystinosis

**Comment by nicolevasilevsky** [comment]
- nephropatic cystinosis had been obsoleted, so I added it back (MONDO:0100151)
- I merged Abderhalden-Kaufmann-Lignac syndrome with 'nephropathic cystinosis'
    - neither of these terms exist in GARD anymore, they just have cystinosis (see [page](https://rarediseases.info.nih.gov/diseases/6236/cystinosis))
