### ISSUE TITLE
[Obsolete] MONDO_0001445 neurogenic bladder

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#974]
**Mondo term (ID and Label)**
neurogenic bladder

**Reason for deprecation**
are we sure it is a disease and not a phenotype? (HP:0000011)
In NCIT, it is a 'finding': https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C79696
DO classifies it as a disease: https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_12143

**Suggested replacement or term to consider**
HP:0000011

@pnrobinson do you have any thoughts?

**Comment by pnrobinson** [comment]
Neurogenic bladder is a feature of many diseases, e.g., multiple sclerosis, Parkinson's disease or diabetes. It is not in itself a full fledge disease entity in my opinion. In some clinical situations (e.g., urology) where this is the problem being treated, diagnosis codes will represent it as the main disease (the urologist does not treat the Parkinson's for instance). 
@cmungall @mellybelly @nicolevasilevsky @drseb @matentzn 
Probably we need to think about how best to represent this sort of thing using appropriate x-referencing in hp and mondo. If this is a leaf class in Mondo right now, then it could be obsoleted. If it is a grouping class, then we could add a logical definition such as 
```
disease and defined_by_primary_finding some HP:....
```
or even
```
disease considering_during_current_encounter_only_one_aspect some HP:...
```
The second option would reflect clinical but not biological reality. The first option would be convenient but would be inaccurate for neurogenic bladder, which often/usually is not the primary finding.

Thinking vice versa, I think that some HP classes should get a definition such as
```
abnormal phenotype and disease_state_considered_as_phenotypic_feature some MONDO:...
```

**Comment by nicolevasilevsky** [comment]
thanks for the feedback @pnrobinson. neurogenic bladder (disease) does not have any children, so I will obsolete this class.

Re: how to relate disease terms to phenotype terms (and vice versa)- currently in Mondo, we've been using the relation 'disease has feature' some [phenotype]

I like the idea of adding disease relationships in HPO too. Would we need to create a new object property?

**Comment by pnrobinson** [comment]
@nicolevasilevsky I think we would need a new property. Let's talk with the whole group though about this!

**Comment by cmungall** [comment]
Yes, disease_has_feature is usually fine for N conditions but for N+S
conditions (i.e to be used in a def) a stronger or different relation is
required.
