### ISSUE TITLE
Lipodystrophy, Familial Partial, Type 2 - Associated w/ hypercholesterolemia?

### ISSUE THREAD

**Issue by GARDInfoCenter** [monarch-initiative/mondo#98]
GARD received an inquiry from a person who would like to see the HPO Class Hypercholesterolemia (HP:0003124) associated with the disease entry Lipodystrophy, Familial Partial, Type 2 (HP:0000349). Although hypercholesterolemia is not a finding in all patients with familial partial lipodystrophy type 2, hypercholesterolemia does seem to occur in some people with the genetic disorder. The inquirer was told by a doctor at NIH (no additional details given) that hypercholesterolemia is a finding for the disease.

We found the following references for this inquiry:

1.	Valerio CM, de Almeida JS, Moreira RO, et al. Dipeptidyl peptidase-4 levels are increased and partially related to body fat distribution in patients with familial partial lipodystrophy type 2. Diabetol Metab Syndr. 2017; 9: 26; https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5404683 The authors found a slight increase in total cholesterol. – “We also observed higher levels of triglycerides (224.8 ± 85.9 mg/dL) (Fig. 1b), but no changes in LDL cholesterol levels (131 ± 51.6 mg/dL) (Fig. 1d). We observed a slight increase in total cholesterol (203.4 ± 61.0 mg/dL) (Fig. 1c), followed by reduction of HDL cholesterol (33.2 ± 7.3 mg/dL) (Fig. 1e). 

2.	Park JY, Javor ED, Cochran EK, DePaoli AM, Gorden P. Long-term efficacy of leptin replacement in patients with Dunnigan-type familial partial lipodystrophy. Metabolism. 2007 Apr;56(4):508-16; https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2595136 They found that “total cholesterol and LDL were modestly elevated.” 

Maria
@GARDInfoCenter
https://orcid.org/0000-0002-6548-5200

**Comment by nicolevasilevsky** [comment]
Hi Maria (@GARDInfoCenter) - do you mean you would like a phenotype for Hypercholesterolemia (HP:0003124) annotation on the disease Lipodystrophy, Familial Partial, Type 2  (https://www.omim.org/entry/151660)?

cc @pnrobinson

**Comment by GARDInfoCenter** [comment]
Yes, exactly.

**Comment by nicolevasilevsky** [comment]
@pnrobinson - I am having trouble with PhenoteFX, it will not open any files. :(

**Comment by nicolevasilevsky** [comment]
@GARDInfoCenter sorry for the super long delay, I added this annotation to this disease.
