### ISSUE TITLE
OMIM diseases missing from Mondo

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#981]
Tudor created a list of 369 OMIM entries parsed from the HPO annotation files that do not have a mapping in MONDO. Some (most?) of them seem to be obsolete terms in MONDO (although the ID is not always included, which would have been great). He asked what should the interpretation of this gap be? Are these really not diseases? Should one not use the annotations associated with them?

Chris responded:
Some of these are not diseases, but the action here is to ensure we have a report to check if we have obsoleteEquivalents in mondo that are not reflected in the hpoa omit list. 

Some definitely are diseases and I assume were added to omim recently, @cmungall needs to do another sweep of adding new terms

**Comment by maglott** [comment]
NCBI is also interested in OMIM coverage in MONDO. 
What is the standard way to assess that coverage? Are some OMIM records skipped because they are determined to be obsolete or phenotypes rather than diseases? is the _hpoa omit list_ public?

**Comment by nicolevasilevsky** [comment]
cc @pnrobinson

**Comment by nicolevasilevsky** [comment]
[omim_missing_list.txt](https://github.com/monarch-initiative/mondo/files/3871370/omim_missing_list.txt)

**Comment by pnrobinson** [comment]
Please be careful. Some of these items are not diseases, e.g., 
 BLOOD GROUP, I SYSTEM
OMIM:125550 | DERMAL RIDGES-OFF-THE-END
OMIM:142335 | FETAL HEMOGLOBIN QUANTITATIVE TRAIT LOCUS 5
OMIM:141900 | HEMOGLOBIN--BETA LOCUS
OMIM:300910 | BONE MINERAL DENSITY QUANTITATIVE TRAIT LOCUS 18

We can use the omit-list.txt in the HPOA repo!

**Comment by jmcmurry** [comment]
If they're not diseases, can we create a cleaner set for general distribution?

**Comment by nicolevasilevsky** [comment]
closing, please reopen if needed
