### ISSUE TITLE
Multiple xrefs to EFO terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#992]
Some Mondo terms have xrefs to more than one EFO term. Zoe generated a report and Nicole reviewed and commented.

See spreadsheet [here](https://docs.google.com/spreadsheets/d/1Mvyy8IPs_UepLBlBnbicida9Vgdb-CZYaVEsLPQOOro/edit#gid=1621731001)

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
cc @zoependlington 
Thanks. I opened an EFO ticket (https://github.com/EBISPOT/efo/issues/631).
